### ISSUE TITLE
Make easier to make compare_models run fast. E.g. Whitelist or Turbo Levels or Train Time Limit Per Model

### ISSUE THREAD

**Issue by alittlesliceoftom** [pycaret/pycaret#100]
Firstly, really enjoying exploring the library, it's cool, great work!

Secondly, as i first test this library out, the first thing that frustrated me is that compare_models() runs for a very long time at full CPU, without viable exit options, and no saved state.  That means that if I decide to just press compare_models() as seems natural, I bear a risk of getting towards the end of comparison, and then getting stuck on a model - mines currently stuck on (>15 minutes):

TheilSen Regressor | Calculating ETC

The user exp suffers here as I now lose some state, and have to go back and blacklist that model, perhaps after restarting my kernel and buying my CPU a drink. 

Some possible options. 
1. Capture the dfs of the output table to an output that is updated after each model run. This reduces risk of lost state. 
2. Add a max ETC threshold, this enables people wanting to explore quickly to dynamically drop models based on how long they'd take on data. i.e compare_models(max_etc_seconds=300)
3. You could make this even simpler and add a max_time field, this could then calculate max ETC/model, and drop models that take too long inside that definition. 
4. Add an ETC timeout, if models stuck for 10 mins without an ETC, it should move on. 
5. Add a whitelist option as an alternative to blacklist, that only runs the models  in the whitelist.

**Comment by pycaret** [comment]
Thank you for suggestion. 

I am working this as enhancement for next release

**Comment by pycaret** [comment]
@alittlesliceoftom 

### Feature now available in pycaret-nightly.

You can install **pycaret-nightly** using "pip install pycaret-nightly".

New parameter **_whitelist_** is now added in **compare_models()**. See an example below:

> compare_models(whitelist = ['dt', 'rf', 'xgboost', 'lightgbm']) 

This will only train 4 models as mentioned in **_whitelist_** parameter.

Can you please test this and close the issue if the enhancement addresses the original issue.

It will be shipped to PyCaret 2.0x in few weeks.

**Comment by alittlesliceoftom** [comment]
I'll aim to take a look

**Comment by DesiKeki** [comment]
Doesnt seem to be working for me. Getting following error:

`TypeError: compare_models() got an unexpected keyword argument 'whitelist'`

**Comment by Yard1** [comment]
@DesiKeki It has been changed to `include` and `exclude`.

**Comment by DesiKeki** [comment]
@Yard1 Thanks for the quick help. It helped! 👍

**Comment by nateGeorge** [comment]
Looks like some of the docs need to be updated to reflect new arg names, still says "blacklist" and "whitelist": https://pycaret.org/classification/
