### ISSUE TITLE
Content of cross-validation folds

### ISSUE THREAD

**Issue by Laurianne50** [pycaret/pycaret#1000]
Hi,
Is there a way to extract the datasets coresponding to each cross-validation fold in create_model() and tune_model()? I'm aiming at analysing the content of the folds and generating a confusion matrix for each fold.
Many thanks!

**Comment by Yard1** [comment]
You should be able to obtain the fold generator with `get_config('fold_generator')`, and then run it on `get_config('X_train')` and `get_config('y_train')` to obtain the exact same indices as used internally.
