### ISSUE TITLE
Memory Error using pycaret.arules

### ISSUE THREAD

**Issue by astrobenhart** [pycaret/pycaret#1007]
I keep running into memory errors when using pycaret.arules. Typically run into this issue when assigning large array to memory for multiple items, i.e. MemoryError: Unable to allocate 30.0 GiB for an array with shape (273430, 2, 7354).

One solution is to update create_model with low_memory option that can then be used when defining frequent_itemsets as apriori.apriori accepts a low_memory option. The only drawback is processing time, around 3-6 times slower.

def create_model(metric="confidence", threshold=0.5, min_support=0.05, round=4, low_memory=False):
...
    frequent_itemsets = apriori(basket, min_support=min_support, use_colnames=True, low_memory=low_memory)

Alternatively to this it would be great to limit the number of items used by adding in a max_len condition to create_model, it would limit the size of the itemsets. this is also already in apriori.apriori so shouldn't be too hard. 

I'll try to make this change myself but I haven't really done this before so any help would be great.

**Comment by astrobenhart** [comment]
#1008

**Comment by Yard1** [comment]
Thanks, merged.
