### ISSUE TITLE
Dev branch showing 11 folds instead of 10

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#101]
I am getting results back from 11 folds (0 to 10) using the code on the dev branch. Is this expected?

![image](https://user-images.githubusercontent.com/33585645/80936129-60afd100-8d95-11ea-92f7-cefcf909811e.png)

**Comment by pycaret** [comment]
No. Is it colab? Apparently the last fold is repeating. See the results of fold 10 matches with fold 9.

**Comment by ngupta23** [comment]
No, this is VSCode. Apparently `tune_model` is working fine so the issue may be specific to `create_model`.

![image](https://user-images.githubusercontent.com/33585645/80936492-044db100-8d97-11ea-9398-f8e335f26c0b.png)

**Comment by ngupta23** [comment]
Also, may be specific to the classification module. Regression module runs fine.

![image](https://user-images.githubusercontent.com/33585645/80936673-c69d5800-8d97-11ea-8e36-5f6c5821782a.png)

**Comment by pycaret** [comment]
@ngupta23 question for you. When you run the code in VSCODE. Do you also see a processing bar that stays there in output. Do you also have similar experience? For some reasons it's not clearing output of progress bar in VScode. Would you know why?

**Comment by ngupta23** [comment]
I see the progrsss bar alright. It shows the right number of folds and stays on till the end, but does not persist after the cross validation is done.

### While cross validation is being performed (shows correct number of folds)

![image](https://user-images.githubusercontent.com/33585645/80965492-3af7eb80-8dd8-11ea-9665-23aa71d37bc0.png)

### After CV is completed (shows the extra line item for the metrics)

![image](https://user-images.githubusercontent.com/33585645/80965561-55ca6000-8dd8-11ea-93d6-89e362d91c2e.png)

**Comment by pycaret** [comment]
Strange. for some reasons by progress bar doesn't go away. It sits at the bottom in VScode. In other environments like Jupyter notebook it works fine. Any guesses why? I am using VSCode 1.44.2 and executing python in VScode using kernel
