### ISSUE TITLE
Final Features model?

### ISSUE THREAD

**Issue by jen-hayden** [pycaret/pycaret#1010]
I go through the setup with many features that then get pared down to a set of final features that are kept in the final model I have chosen. But the original dataset from which I started may have hundreds of features. How can I tell the final model to only use the final root features I need to keep to do the preprocessing required to get the final features that were kept in the final model. In other words, I am hoping the new data I send for scoring does not need to have 100 main features included but the 20 main features that will predict on new data.

**Comment by Yard1** [comment]
You can check which columns have been left after preprocessing by doing `get_config('X').columns` (with the caveat that categorical columns will be split into one hot encoded ones).

**Comment by jen-hayden** [comment]
I have used `print(get_config('X_train').columns` to get the features remaining in the final model. How to drop those unused features from unseen data so that I don't have to keep 100 initial features, just the ones that would be pre-processed into the final kept features?

**Comment by Yard1** [comment]
We would recommend to leave all the same columns as in data passed to `setup()` in order to avoid any issues, but you could try to do something like
```python
unseen_data_trimmed = unseen_data[columns_to_keep]
```
where `columns_to_keep` is the list of columns to keep.
