### ISSUE TITLE
predict_model() got an unexpected keyword argument 'raw_score'

### ISSUE THREAD

**Issue by doraemonlei** [pycaret/pycaret#1012]
pycaret==2.2.3

but
print(pycaret.__version__)
>2.2.0

predict_model() got an unexpected keyword argument 'raw_score'

**Comment by Yard1** [comment]
Are you using the nightly version?

**Comment by doraemonlei** [comment]
> Are you using the nightly version?

Thank you. I downloaded the latest master branch code, replaced old code, and solved it.
