### ISSUE TITLE
Duplicate rows removal and treating missing value in Target column

### ISSUE THREAD

**Issue by Anoop-A-Anto** [pycaret/pycaret#1013]
Is there any way IN PYCARET setup
**1.** Can we remove duplicate rows using pycaret? 

**2.** Also when trying to preprocess datasets with missing value in Target column leads to errors.

**Comment by Yard1** [comment]
1. We have had an option to do that before but it proved to be very performance intensive. We may readd it as an optional feature.
2. What sort of errors? Can you post the exception message?

**Comment by Anoop-A-Anto** [comment]
![Miss-in-y](https://user-images.githubusercontent.com/75159380/105413273-e3e2c100-5c5b-11eb-979a-cbf1d89374f7.JPG)

**Comment by Anoop-A-Anto** [comment]
**1.**

For duplicate removal Couldn't we enhance by setting method like below for default pipeline in setup?

df.drop_duplicates(keep="first",inplace=True,ignore_index=True)

**Comment by Yard1** [comment]
For duplicate removal - you can just run what you posted before passing it to PyCaret.

As for 2, thanks for the report, I just fixed it in commit 14ee94ed2e46e1d44aa450cfa9dc6a1101d02563.

**Comment by Anoop-A-Anto** [comment]
Appreciate your effort. 
Closing this issue now
