### ISSUE TITLE
Case change and splitting text to new columns as per our requirement

### ISSUE THREAD

**Issue by Anoop-A-Anto** [pycaret/pycaret#1014]
Is there anyway we can set in pycaret setup env for 
**1**. Formatting String cases to lowercase or upper case or trimming unwanted spaces etc. in Text columns ?

**2**. Can we Split columns based on text content? Like A single column containing information -"Apple,Iphone11,64Gb" to be separated to three NEW columns?

**Comment by Yard1** [comment]
PyCaret doesn't offer that functionality, you will need to do those steps separately before passing the data to PyCaret.

**Comment by Anoop-A-Anto** [comment]
could we pass those methods to custom pipeline?

**Comment by Yard1** [comment]
Custom pipeline is applied on every CV step so I don't think it's a good idea as the changes won't be even seen in the preprocessed dataframe.

**Comment by Anoop-A-Anto** [comment]
Hope that in future we could bring an enhancement in pycaret  for cleaning string formatting issues,removing white spaces ,special characters etc. Since this will be a common issue in real world datasets.

**Comment by Yard1** [comment]
PyCaret already automatically removes any special characters from columns, but that step is not customizable. However, greater pipeline customizability in general is planned for the next major release.

**Comment by Anoop-A-Anto** [comment]
It's great news. Thank you for your quick response.
Closing this discussion now
