### ISSUE TITLE
AttributeError: 'str' object has no attribute 'labels_' in IForest Model assignment

### ISSUE THREAD

**Issue by praks1980** [pycaret/pycaret#1015]
![pycar_Err](https://user-images.githubusercontent.com/77641013/105407602-f2c57580-5c53-11eb-9eca-6f54550a8b8c.PNG)
Got this error when trying to assigning the model for Outlier Detection. 

The Dataframe is not created / assigned. Can someone help with debugging or a fix ? Is this associated to https://github.com/pycaret/pycaret/issues/195

**Comment by Yard1** [comment]
You need to pass a model object created with `create_model()` instead of a string.

```python
model = create_model('iforest')
ifor_res = assign_model(model, transformation=False)
```

Let me know if that works.

**Comment by praks1980** [comment]
Yes it worked thank you team.

Regards,
Prakash G

**Comment by praks1980** [comment]
Closing this as it worked.
