### ISSUE TITLE
Scaling and speeding dataframe 4x

### ISSUE THREAD

**Issue by Anoop-A-Anto** [pycaret/pycaret#1016]
Can we enhance dataframe speed by using Modin instead of default pandas in pycaret backend. ?

![Modin](https://user-images.githubusercontent.com/75159380/105418009-76865e80-5c62-11eb-9958-a9527caa3356.JPG)

**Comment by Yard1** [comment]
We have considered this for the future. Sadly it's not as easy to replace Pandas with modin as it seems.
