### ISSUE TITLE
Regression Model Accuracy is confusing & SHAP: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 342: invalid start byte

### ISSUE THREAD

**Issue by pit9921** [pycaret/pycaret#1017]
I really do not understand, how the accuracy of regression (also classification) models is being evaluated.
The same issue is on all algorithms, therefore i am note sure, it is has something with xggoost, scikit-learn or pycaret.
`
xgboost = create_model('xgboost')`
with k=10 there is R2 mean of 28%, Std.Dev=0.7552, Range (-18% - (+74%)).
The performance is creepy.

`best = automl(optimize = 'R2')` - or MAE, or RSMLE. I found out that thic command makes wonders. It could significantly improve the model.

`evaluate_model(xgboost)`
Residual Plots -> TrainR2=100%, TestR2=75%.
Validation Curve -> TrainR2=100%, TestR2=ca. 35%.
`
evaluate_model(best)`
Residual Plots -> TrainR2=100%, TestR2=100%.
Validation Curve -> TrainR2=100%, TestR2=ca. 65%.

`predict_model(best);`
R2=99%

`final_best = finalize_model(best)`
`predict_model(final_best);`
R2=99%

The errors (MAE etc.) are perfect as well as R2.
I check the predicted values on test and compare them to the target variable value and there is no way, that the R2=99%.

The same problem do i have with the classification as well.
- results from a cross-validation are horrible
- but the predictions on test are 100% (but not in reality)

Both datasets (for regression and for classification) have 80 rows.
The same experience i have also with another datasets, however the differences are not so huge.

Is there any explanation?

**Comment by pycaret** [comment]
@pit9921 Which version of pycaret are you using? You can check the version with this code:

```
from pycaret.utils import version 
version()
```

**Comment by pit9921** [comment]
Thank you for your reply. I thought that i had '2.2.3' but i got '2.1' instead.
At the moment i have the version: '2.2.3' and it Regression Model Accuracy for test set was performed correctly.

However, i have got an another issue after upgrading regarded to SHAP values.
The following worked with Pycaret 2.1.
```
`best = automl(optimize = 'R2')`

booster = best.get_booster() 
model_bytearray = booster.save_raw()[4:]
booster.save_raw = lambda : model_bytearray
```
```
explainer = shap.TreeExplainer(booster)
shap_values = explainer.shap_values(X_train)
shap.summary_plot(shap_values, X_train)
```
After upgrading (to 2.2.3) i have got the followng error:
----> 3 explainer = shap.TreeExplainer(booster)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 334: invalid start byte

With:
```
import shap
explainer = shap.TreeExplainer(best)
shap_values = explainer.shap_values(X_train)
shap.summary_plot(shap_values, X_train)
```

i have got: TypeError: Not supported type for data.<class 'sklearn.model_selection._split.KFold'>

**Comment by Yard1** [comment]
Have you tried using PyCaret's built-in `interpret_model` function? It's essentially a wrapper around SHAP.

**Comment by pit9921** [comment]
Yes,
`
final_best = finalize_model(best)`

`interpret_model(best) `- works
`interpret_model(final_best) `- does not work -> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 342: invalid start byte

But i would like to recieve shap values as described in the previous post. I have a dataset with huge variation in the results and i stored the shap values with sessions_ids to get a confidence interval on the end.

**Comment by pit9921** [comment]
![best_vs_final_best](https://user-images.githubusercontent.com/77811022/105577754-cad13180-5d7b-11eb-8f66-a40084baff8c.png)

I checked the both models - best and final_best and they seem to be identical.
The interpret_model(best) works well and with interpret_model(final_best) it does not work.

There are still some issues with the regression model accuracy.
From the attached picture it is obvious, that "best" and "final_best" are identical.

However, with `predict_model(best);` i have got the R2=80% and with `predict_model(final_best);` i have gor the R2=100%.
There is no way to get a r2=100%.

What could be possible checked in order to fix this issue?

**Comment by Yard1** [comment]
Well, the final model has been trained on the entire dataset (that's what `finalize_model()` does), so an R2 of 100% is possible. I am not sure why it would fail SHAP though. Perhaps that's an issue with it and not with PyCaret, but I am not sure. I haven't seen this issue before.
