### ISSUE TITLE
could'nt access y Column Nan value fixed solution

### ISSUE THREAD

**Issue by Anoop-A-Anto** [pycaret/pycaret#1018]
I tried again to run dataset with missing value in y column as mentioned in closed issue  #1013 after problem was fixed in  commit 14ee94ed2e46e1d44aa450cfa9dc6a1101d02563.

But still same error is repeating again. Please help for accessing new fixed solution in pycaret installation

**Comment by Yard1** [comment]
Have you actually updated pycaret first?
`pip install -U git+https://github.com/pycaret/pycaret.git` will install the git version of PyCaret (aka the most up to date one, including that commit I just pushed).

**Comment by Anoop-A-Anto** [comment]
i installed by upgrading. But not by git repository . Let me check that

**Comment by Anoop-A-Anto** [comment]
Installing from git works. 💯 .
Can we achieve the same solution by installing from pypi  later? or when can we use direct installing with this solution incorporated

**Comment by Yard1** [comment]
Yes, once we release an update.

**Comment by Anoop-A-Anto** [comment]
👍 thank you
