### ISSUE TITLE
Pull Request Template 

### ISSUE THREAD

**Issue by rajpratyush** [pycaret/pycaret#1020]
@pycaret I came across that there is no PR template in this repository for creating the pull request.

I would like to add a pull request template which will give a template and users need to fill it in order to open a pull request and maintainer will get better understanding of the pull request with images.

**Comment by pycaret** [comment]
Sure, please feel free to do that.

**Comment by rajpratyush** [comment]
@pycaret Please do assign me this issue.

**Comment by rajpratyush** [comment]
@pycaret Check the PR #1021

**Comment by pycaret** [comment]
@rajpratyush Merged. Thanks.
