### ISSUE TITLE
classification.tune_model() with customize optimize, something is wrong

### ISSUE THREAD

**Issue by quanbingDG** [pycaret/pycaret#1022]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
This my code segment
op = classification.add_metric(id='ap1', name='ap_score',score_func=average_precision_score, target='pred_proba')
xgb_model = classification.tune_model(classification.create_model('xgboost'), optimize=op)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-153-0a033b391718> in <module>
----> 1 xgb_model = classification.tune_model(classification.create_model('xgboost'), optimize=op)

~/opt/anaconda3/lib/python3.7/site-packages/pycaret/classification.py in tune_model(estimator, fold, round, n_iter, custom_grid, optimize, custom_scorer, search_library, search_algorithm, early_stopping, early_stopping_max_iters, choose_better, fit_kwargs, groups, return_tuner, verbose, tuner_verbose, **kwargs)
   1092         verbose=verbose,
   1093         tuner_verbose=tuner_verbose,
-> 1094         **kwargs,
   1095     )
   1096 

~/opt/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py in tune_model_supervised(estimator, fold, round, n_iter, custom_grid, optimize, custom_scorer, search_library, search_algorithm, early_stopping, early_stopping_max_iters, choose_better, fit_kwargs, groups, return_tuner, verbose, tuner_verbose, display, **kwargs)
   3967     # setting optimize parameter
   3968 
-> 3969     compare_dimension = optimize.display_name
   3970     optimize = optimize.scorer
   3971 

~/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5460             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5461                 return self[name]
-> 5462             return object.__getattribute__(self, name)
   5463 
   5464     def __setattr__(self, name: str, value) -> None:

AttributeError: 'Series' object has no attribute 'display_name'

**Comment by Yard1** [comment]
You should not pass the `op` to optimize but instead a string id of the metric you have added (so that would be `ap1` here).

**Comment by quanbingDG** [comment]
thanks
