### ISSUE TITLE
Tutorial: Include load_model in the website

### ISSUE THREAD

**Issue by marianotir** [pycaret/pycaret#1024]
**Is your feature request related to a problem? Please describe.**
save_model is describe in the tutorial but load_model is not. 

**Describe the solution you'd like**
Add load_model to the website tutorial

**Comment by pycaret** [comment]
@marianotir Which link are you looking at? I can see `load_model` documentation in API documentation.

![Uploading image.png…]()

**Comment by marianotir** [comment]
Here 

https://pycaret.org/guide/

**Comment by pycaret** [comment]
Thanks @marianotir

Since `save_model` and `load_model` is covered as part of one page. I have now added `load` alias in the menu itself.

![image](https://user-images.githubusercontent.com/58118658/105896243-8d231180-5fe4-11eb-85a2-fcf77ae5961d.png)
