### ISSUE TITLE
Facing  value error for pycaret nlp setup

### ISSUE THREAD

**Issue by solondas007** [pycaret/pycaret#1026]
IM facing this error when I'm setting up the pycaret nlp setup command:

# setting up the pycaret nlp environment for topic modelling of the text features. 
py_nlp = setup(data = data, target = 'text', session_id = 123)

ValueError: y contains previously unseen labels: 'Customer Service  Representative Hawkeye Recruitment provides cost effective recruitment advertising solutions to help you cast the widest net to find the perfect candidate for your job. We can help improve your recruitment efforts, and streamline your hiring process.\xa0 General Dynamics Information Technology is actively recruiting for Temporary Customer Service Representatives in Coralville, Iowa.Unlike other call centers, our "help centers" are environments free from high-pressure sales, collections or telemarketing.\xa0 We provide our customers with the resources, benefits and information they need, creating a positive connection between the public and various government agencies.Open interviews will be conducted at the Coralville facility located at 2400 Oakdale Blvd., Coralville, IA, Monday through Friday, from 9 A.M. to 4 P.M. and Wednesdays from 4\xa0 P.M to 7 P.M.GENERAL SUMMARY:The CMS Customer Service Representative I (CSR) is responsible for delivering general Marketplace\xa0 information to callers.\xa0 The CSRs use basic office equipment and technology such as telephones, email, and web browsers to perform their duties.\xa0 The processes that the CSRs must follow are well defined and documented in standard operating procedures and scripts.\xa0 Prescribed scripts must be read verbatim to the caller.\xa0 Neither subject matter knowledge nor independent decision making is required by this position.\xa0\xa0The Customer Service Representative I reports directly to the Customer Service Supervisor.\xa0 This is an entry level position responsible for disseminating general Marketplace information.\xa0 Application processing, enrollment guidelines and a general Marketplace background will be the focus with callers.\xa0 The Customer Service Representative I will follow scripting to determine when to transfer the caller to a Customer Service Representative II\xa0 JOB RESPONSIBILITIES:* Provide knowledgeable responses to telephone inquiries in a courteous and professional manner, utilizing pre-scripted responses which they must read verbatim to provide basic general and claims specific information.* Follow established and documented policies and standard operating procedures such as filling out timesheets, adhering to privacy rules and responding to numerous phone inquiries.* Utilize standard technology such as telephone, e-mail, and web browser to perform job duties.* Assist caller with filling out online application and submitting it electronically to plan provider for processing.* Complete basic call log related to the phone inquiries such as clicking radio buttons to confirm which scripts were read by the CSR to the caller.* Refer calls as required to Customer Service Representative II.* Maintain up-to-date knowledge of CMS regulations and policies as they apply.\xa0* Report problems that occur via the online system so they can be addressed by the appropriate parties.\xa0* Respond to telephone inquiries within the set departmental staffing and time parameters.\xa0* May be required to work GDIT scheduled holidays. Overtime may be required.* Perform other related duties as assigned.\xa0* Regular and predictable attendance is required.\xa0EDUCATION / EQUIVALENT TRAINING:* High School diploma or equivalent requiredEXPERIENCE:* Minimum 6 months customer service/secretarial/telemarketing experience required.\xa0* Must be able to speak and read English clearly, professionally and fluently.* Must be able to type a minimum of 20 WPM.\xa0* Ability to effectively work within established contractual turnaround times required.\xa0* Must have demonstrated excellent interpersonal and the ability to organize simultaneous tasks.\xa0* Proven ability to work as a member of a team.* All CMS personnel will be required by contract to undergo program update training as the program changes.* Spanish fluency is desirableWORKING CONDITIONS:The work is typically performed in an office environment, which requires proper safety and security precautions. To ensure our contact center production area is at minimal risk for unauthorized disclosure (that is, the release or divulgence of information by an entity to persons or organizations outside of that entity) of Personally Identifiable Information (PII) or ProtectedHealth Information (PHI), the work environment operates under a Secure Floor Policy. The Secure Floor Policy limits or restricts personal belongings, electronic devices, or paper that can be brought into production areas.The above job description is not intended to be, nor should it be construed as, exhaustive of all responsibilities, skills, efforts, or working conditions associated with this job.Requests for reasonable accommodations will be considered to enable individuals with disabilities to perform the principal (essential) functions of this job.General Dynamics Information Technology is an Equal Opportunity/Affirmative Action Employer (M/F/D/V).\xa0 '

**Comment by solondas007** [comment]
[files.zip](https://github.com/pycaret/pycaret/files/5865310/files.zip)

**Comment by pycaret** [comment]
@solondas007 I don't see any error log? Can you please upload the dataset as well as Notebook with reproducible error?

**Comment by ngupta23** [comment]
Hi @solondas007 , We will close this out. Feel free to reopen and provide the necessary information to debug.
