### ISSUE TITLE
Pycaret not working in EKS cluster

### ISSUE THREAD

**Issue by sagarnildass** [pycaret/pycaret#1028]
Hi,

I have developed a simple dash web app which uses pycaret in the backend. When I am pressing the button which calls the compare_models() function, the training is starting successfully. However, just after sometime, in between the logs of the training, I am getting this line:

INFO:Thread-137:werkzeug:192.168.71.8 - - [25/Jan/2021 13:08:57] "GET / HTTP/1.1" 200 -

At that point of time, the training stops and the leaderboard is not generated in the frontend. 

When I am using a smaller dataset like Titanic, the same thing works fine and I could see the leaderboard then.

Please help

![image](https://user-images.githubusercontent.com/18384685/105710694-7675af80-5f3d-11eb-83d7-6df6afd02fc2.png)

**Comment by rajpratyush** [comment]
@sagarnildass can you share the link of the dataset

**Comment by sagarnildass** [comment]
@rajpratyush : Please find it here: s3://darkarosh-ml-data-regression/big_mart_sales/train.csv

**Comment by rajpratyush** [comment]
@sagarnildass it would be really helpful if you can share the codebase so that I can go through it

**Comment by sagarnildass** [comment]
Closing this as this problem was due to a gunicorn timeout error.
