### ISSUE TITLE
Unable to plot after loading config and model files.

### ISSUE THREAD

**Issue by aliagowani** [pycaret/pycaret#1030]
I created a clustering model (kmeans). 

![Screen Shot 2021-01-26 at 4 08 04 PM](https://user-images.githubusercontent.com/51864674/105912185-b2b61800-5ff0-11eb-8ce8-05a09f23a4c2.png)

The model and configs were saved.
![Screen Shot 2021-01-26 at 4 08 57 PM](https://user-images.githubusercontent.com/51864674/105912289-daa57b80-5ff0-11eb-81dc-3525d53af62b.png)

Python is restarted.

I load the model and config files.
![Screen Shot 2021-01-26 at 4 10 27 PM](https://user-images.githubusercontent.com/51864674/105912388-07599300-5ff1-11eb-86b2-5e899324fea9.png)

Then I want to plot the clusters but receive the following error:
![Screen Shot 2021-01-26 at 4 11 14 PM](https://user-images.githubusercontent.com/51864674/105912474-235d3480-5ff1-11eb-92c3-719617c1adab.png)

I am unable to create any of the plots and receive the same error. Not sure if it has to do with the output label name as in clustering the label is called Cluster?

How can I save the model, config, etc files and then come back to them so I can continue to evaluate or plot the model?

**Comment by Yard1** [comment]
@aliagowani can you try saving the model without pipeline (`model_only=True`).

**Comment by aliagowani** [comment]
Yes, passing just the estimator works! Thank you.
![Screen Shot 2021-01-27 at 9 36 29 AM](https://user-images.githubusercontent.com/51864674/106014522-2ef93b80-6083-11eb-8c7b-001995bcce0e.png)
