### ISSUE TITLE
Problems with regression ML models

### ISSUE THREAD

**Issue by javierperezcastan** [pycaret/pycaret#1031]
Hi¡

My issue is about with the regression ML models. I have trained a ML regresssion model, apply the finalize model function, save it and load it in another script. 

However, when I predict a new database with the loaded ML model, the results of the regression predictions are integers insteat of floats. So I obtain a prediction with a value of 2 instead of 2.5678. 

Can you help with this?

Best regards
Javier

**Comment by Yard1** [comment]
Can you post code we can use to reproduce the issue?

**Comment by javierperezcastan** [comment]
I have investigated and the problem arises when I open the loaded model in a different script than the one I have used to save it. 

I think it is a problem that it shows when I apply predict that appear at the bottom ml_usecase = Classification but it is a regression.

![image](https://user-images.githubusercontent.com/64135621/106273294-b33df100-6232-11eb-9b36-5d2ee3fcd06f.png)

**Comment by Yard1** [comment]
Are you running setup before loading the model?

**Comment by javierperezcastan** [comment]
No, I use the ML model without using the setup process. The idea is to apply it directly to new data as it would be applied in reality. The results that it provides are regression results but without decimals, i.e., instead of 5.2345 the model gives just the number 5.

**Comment by Yard1** [comment]
Are you importing `predict_model` from the `pycaret.regression` module?

**Comment by javierperezcastan** [comment]
Thanks, that was the problem¡ I was only importing the pycaret.classification module. 
Just one question more, How can I use the load_model function if the model is in other folder?

**Comment by Yard1** [comment]
Just pass a path instead: `load_model('path/to/folder/modelfile')`

**Comment by javierperezcastan** [comment]
Great job¡

Thank you very much¡
