### ISSUE TITLE
Please add partial dependence plots

### ISSUE THREAD

**Issue by alirezayazdani21** [pycaret/pycaret#1032]
Please add 2D and 3D Partial Dependence Plots as an option in the "interpret_model" function. 

Partial dependence plots (PDP) show the dependence between the target response and a set of input features of interest, marginalizing over the values of all other input features (the ‘complement’ features). Intuitively, we can interpret the partial dependence as the expected target response as a function of the input features of interest.

Examples:
https://scikit-learn.org/stable/modules/partial_dependence.html

https://christophm.github.io/interpretable-ml-book/pdp.html#pdp

**Comment by rajpratyush** [comment]
I would like to work on this @pycaret

**Comment by castorfou** [comment]
Is it feasible to save a Pycaret model and use the standard PDP lib in scikit-learn waiting for this pycaret implementation?

**Comment by Yard1** [comment]
PyCaret models are just sklearn-models, so yes, it is possible.

**Comment by pycaret** [comment]
@rajpratyush I have assigned this to you.

@Yard1 Where should Raj submit the PR? Can you please let him know. Are we still using `master` branch?

**Comment by Yard1** [comment]
@rajpratyush @pycaret `master` for now, yes

**Comment by ngupta23** [comment]
Hi @rajpratyush , Is this in work?

**Comment by rajpratyush** [comment]
No i am not working on it

**Comment by ngupta23** [comment]
OK, thanks for getting back. Would you like to continue to own this issue?
