### ISSUE TITLE
How to extract information on interpret_model(plot = 'correlation')

### ISSUE THREAD

**Issue by giantorreno** [pycaret/pycaret#1033]
I would like to know how to extract information, such as the SHAP value (y-axis) and its corresponding variable in x-axis, from the image generated by interpret_model(model, plot = 'correlation') in pycaret? I would like to store the information in a dataframe and do some preprocessing techniques for a better analysis.

**Comment by S-UP** [comment]
Related to this: Is it possible to extract the variables and SHAP values from the 'summary' plot? This would allow to build nice automations like passing the top 10 variables into the 'correlation' plot. Also it would help with omitting typos as I am using Featuretools to generate quite a lot of features and reading and re-entering them manually is sometimes challenging.

**Comment by Yard1** [comment]
You can use the SHAP library on a PyCaret model separately to obtain more detailed results

**Comment by ngupta23** [comment]
@S-UP Towards the very end of [this notebook](https://nbviewer.jupyter.org/github/ngupta23/ds7333_qtw/blob/master/case_study_7/submission_Kannan_Moro_Gupta/code/cs7.ipynb), you will see how to use SHAP manually with a `pycaret` model.
