### ISSUE TITLE
DummyRegressor and DummyClassifier

### ISSUE THREAD

**Issue by reza1615** [pycaret/pycaret#104]
I suggest to have all possible DummyRegressor and DummyClassifier in compare model to have a baseline for comparing the results.

**Comment by pycaret** [comment]
@reza1615 Which algorithm these classes use? sklearn documentation doesn't recommend using these? isn't it?

**Comment by reza1615** [comment]
@pycaret: Dummy models are just for comparing and we can compare nominated model with the worst case scenario (Dummy models).
Sklearn define them to have a baseline.

**Comment by reza1615** [comment]
@pycaret You removed the history https://github.com/pycaret/pycaret/graphs/contributors
I don't contribute here

**Comment by jbechtel** [comment]
@pycaret I agree that these would be a nice comparison to have in `compare_models`. [DummyRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.dummy.DummyRegressor.html) and [DummyClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.dummy.DummyClassifier.html) with all of their strategies should be included. This is a good sanity check to make sure that the best model is at least outperforming the baseline. Maybe we add a check that disallows them from being deployed.
