### ISSUE TITLE
Add Model Zoo for Time Series

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#1040]
Per @moezali1 

> models() function similar to pycaret.classification and pycaret.regression should store pre-trained models for users to see the availability of models in model library / zoo

> I am thinking of following models to be considered in model zoo:
- [ ] AutoARIMA
- [ ] ETS (auto)
- [ ] Regression models (let's use ReducedRegression with 3-4 estimators from sklearn that are known to perform well on univariate time series data -- consider Linear Regression, XGBoost, LightGBM, CatBoost)
- [ ] BATS / TBATS

**Comment by Yard1** [comment]
FYI the `models()` function will be automatically populated by models in containers (https://github.com/pycaret/pycaret/issues/1036)

**Comment by atwahsz** [comment]
Fbprophet include ?

**Comment by ngupta23** [comment]
@atwahsz , Yes, that will be included as well.

**Comment by atwahsz** [comment]
also , a great addition to the setup() is to pass a grouping by for preprocessing (so group by and do the preprocess steps)

**Comment by ngupta23** [comment]
@atwahsz,  could you clarify your comment. Also, if it is a separate topic, could you please create a separate issue in GitHub. Thanks!

**Comment by ngupta23** [comment]
Model have been added to the `time_series` branch (this is still in development), but ok to close.
