### ISSUE TITLE
pos_label=1 is not a valid label: array(['0.0', '1.0'], dtype='<U3')

### ISSUE THREAD

**Issue by javierperezcastan** [pycaret/pycaret#1042]
Hi, 
When I run the create_model function it appears this error,  "pos_label=1 is not a valid label: array(['0.0', '1.0'], dtype='<U3')"
I have read through the internet and it appears to be that there are more 1.0 than 0.0 . Is there any way to solve this issue?

Best regads
Javier

**Comment by Yard1** [comment]
Can you share the notebook/script and the dataset?

**Comment by javierperezcastan** [comment]
I cannot share the dataset sorry but I send you pictures of the problem. 
![image](https://user-images.githubusercontent.com/64135621/106456000-44a89f80-648d-11eb-8d60-a36d8ecf2a06.png)
![image](https://user-images.githubusercontent.com/64135621/106456038-4eca9e00-648d-11eb-9793-032f1cb3c61c.png)
![image](https://user-images.githubusercontent.com/64135621/106456104-5ee27d80-648d-11eb-84b4-ca99a601ef70.png)
![image](https://user-images.githubusercontent.com/64135621/106456140-67d34f00-648d-11eb-9fc9-c2da25143675.png)

I have tried to do it by my own the trainning process and it is a problem calculating the classification metrics:
![image](https://user-images.githubusercontent.com/64135621/106456179-77eb2e80-648d-11eb-82ae-2a411b464792.png)
![image](https://user-images.githubusercontent.com/64135621/106456208-7f123c80-648d-11eb-8074-5830351c497e.png)

**Comment by Yard1** [comment]
What happens if you cast the target to `int`?

**Comment by javierperezcastan** [comment]
Does it works¡¡

Thank  you very much
Javier
