### ISSUE TITLE
Setting distance on clustering modules

### ISSUE THREAD

**Issue by hugo-pires** [pycaret/pycaret#1045]
Hello and congratulations for a great job

Is it possible when using cluster module to set distance to manhattan distance (or other)?

Thank you

**Comment by Yard1** [comment]
It would depend on the model used. I believe some have arguments you can pass as keyword arguments in `create_model`. You'd need to check the documentation of the packages the models are from - `models()` should tell you where to look.

**Comment by hugo-pires** [comment]
You're telling to use Scikit-learn documentation?

**Comment by Yard1** [comment]
Indeed.

**Comment by hugo-pires** [comment]
Thanks

**Comment by aliagowani** [comment]
@hugo-pires did you end up trying this out and passing the argument in the create model? Wondering how it turned out for you?

**Comment by hugo-pires** [comment]
@aliagowani I've tried. But I guess is not possible, according to I've found on this issue:

https://github.com/scikit-learn/scikit-learn/issues/13956

**Comment by aliagowani** [comment]
@hugo-pires I see; I appreciate the follow-up.
