### ISSUE TITLE
Consider adding classification report to performance measures

### ISSUE THREAD

**Issue by rehoyt** [pycaret/pycaret#1049]
**Is your feature request related to a problem? Please describe.**
For classification models the performance measures are very good but do they reflect a weighted average?

**Describe the solution you'd like**
If a Python "classification_report" was included in the pipeline we could get performance measures for the majority and minority classes, along with macro averages, micro averages and weighted averages. I think this tells a more complete story

**Describe alternatives you've considered**
I sometimes run a model through another program such as WEKA so I can see more parameters for classification performance

**Additional context**
![image](https://user-images.githubusercontent.com/25651922/107060835-0f59c580-679d-11eb-9820-39e3417a8059.png)
![classification_report](https://user-images.githubusercontent.com/25651922/107060874-1d0f4b00-679d-11eb-9490-ba2374431bd1.jpg)

**Comment by vtoliveira** [comment]
You can use `add_metric` function to calculate scores based on different weights.

Here is an example:

```python
add_metric('recall_w', 'Recall Wght', recall_score, greater_is_better=True, average='weighted')
```
