### ISSUE TITLE
get_config() inqury

### ISSUE THREAD

**Issue by atwahsz** [pycaret/pycaret#1051]
i wanted to do iterative imputation on a dataset , and then get it back without any scaling only the iterative imputation filling the missing numerical variables.

get_config() returns transformed datasets 

is there a workaround ?

**Comment by Yard1** [comment]
I'd use `get_config('prep_pipe')` to obtain the preprocessing pipeline, remove steps you don't want from it, and then use it to transform data.

**Comment by atwahsz** [comment]
@Yard1 also question about tune_model . is it possible to verbose or output a table for each iter that shows scores ?

**Comment by Yard1** [comment]
You can get the tuner object with a an argument I can't remember right now but I know is there. `return_tuner=True` I think. You should be able to get those details from it.
