### ISSUE TITLE
KeyError during clustering setup

### ISSUE THREAD

**Issue by hugo-pires** [pycaret/pycaret#1053]
Hello

During clustering setup I got the following error message:

`KeyError: 3`
 
the last message was:

Status | . . . . . . . . . . . . . . . . . . | Preparing Data for Modeling
-- | -- | --

on the error stack I found the following code:

`-> 1041         train_data.loc[0:3, target] = 3`

Could you help me?

**Comment by Yard1** [comment]
Can you upload the logs.log file created in the folder from where you run the notebook?

**Comment by hugo-pires** [comment]
Here it is.

Thank you
[logs.log](https://github.com/pycaret/pycaret/files/5939322/logs.log)

**Comment by Yard1** [comment]
Can you also share the dataset and the notebook you used?

**Comment by Yard1** [comment]
I have pushed commit cb5f11f52c0ac50709dad12ebdba5c92f880a03a that should fix this issue. Can you install the development version of PyCaret with `pip install -U git+https://github.com/pycaret/pycaret.git` and try again?

**Comment by hugo-pires** [comment]
The error stays the same, but I am not sure if the version was updated. How can I check if have the updated version?

**Comment by Yard1** [comment]
Can you create a new virtual environment and install pycaret there again using the above command?

**Comment by hugo-pires** [comment]
I've done it, but the error is the same. Sorry

**Comment by Yard1** [comment]
I have just tested this out on colab using the notebook you have sent me and it is working as intended, so somehow you must not be updating pycaret correctly. Perhaps try `pip install -U --user git+https://github.com/pycaret/pycaret.git`

**Comment by hugo-pires** [comment]
I will double check but is still not working. Probably some version problem. Thank you very much

**Comment by Yard1** [comment]
Maybe try to uninstall pycaret first: `pip uninstall pycaret`

**Comment by hugo-pires** [comment]
Running! Thanks a lot
