### ISSUE TITLE
HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by JulienCANTONI** [pycaret/pycaret#1054]
****Is your feature request related to a problem? Please describe.**
I can't use 'get_data', I have a "HTTPError: HTTP Error 404: Not Found"

**A clear and concise description of what the problem is.** 
I had had installed pycaret. I was used to low coding with it.
I don't understand why I have this error. 
I have reinstalled it with conda prompt but I can't use Pycaret unfortunatelly.

**Describe the solution you'd like**
I would like to solve this problem to use again Pycaret.

**Describe alternatives you've considered**
None, except if it is a Norton antivirus problem.

**Additional context**
See screen shots.
![image](https://user-images.githubusercontent.com/45997682/107155830-eabb4480-697a-11eb-95de-783c4e2ef613.png)
![image](https://user-images.githubusercontent.com/45997682/107155754-74b6dd80-697a-11eb-9e14-400fd14c7eff.png)
![image](https://user-images.githubusercontent.com/45997682/107155767-89937100-697a-11eb-9cee-8921a0c2db0e.png)
![image](https://user-images.githubusercontent.com/45997682/107155804-b8114c00-697a-11eb-99c7-90f3848b3271.png)
![image](https://user-images.githubusercontent.com/45997682/107155850-06264f80-697b-11eb-91cd-15e6630d7d14.png)
![image](https://user-images.githubusercontent.com/45997682/107155857-1fc79700-697b-11eb-93c3-d08b6c3768ca.png)
![image](https://user-images.githubusercontent.com/45997682/107155872-353cc100-697b-11eb-8937-4f9e3321ff83.png)

**Comment by Yard1** [comment]
I do not believe `dataSet` is a dataset pycaret can provide. You can get a list of all available datasets with `get_data('index')`.

**Comment by JulienCANTONI** [comment]
@Yard1 I just have tried to load another dataset, that I could have get with Pycaret before. I have got the same error. So I don't think that is the reason. Nevertheless thanks a lot

**Comment by JulienCANTONI** [comment]
And I just have tried with the edge explorator and not with Chrome. The same error :(.

**Comment by JulienCANTONI** [comment]
I have just understood my error. Thanks @Yard and sorry for my mistake
