### ISSUE TITLE
optimize_threshold function chart not rendering

### ISSUE THREAD

**Issue by hugo-pires** [pycaret/pycaret#1056]
Hello

When I run:

`optimize_threshold(tuned, true_negative = 10, false_negative = -200, )`

I get an empty chart
![screenshot](https://user-images.githubusercontent.com/7768784/107161322-f49d7180-6993-11eb-9948-02ff6d440bce.png)

The optimized value is showing up.

Could you help?

Thanks a lot

**Comment by Yard1** [comment]
Does this happen in Colab?

**Comment by pycaret** [comment]
@hugo-pires Which environment you are using?

**Comment by hugo-pires** [comment]
Thank you
@Yard1 It is working on Google Colab.
@pycaret Do you mean which libs am I using?
