### ISSUE TITLE
Make logging configurable

### ISSUE THREAD

**Issue by joschkazj** [pycaret/pycaret#1057]
Hi,

first of all many thanks for putting together this package! Ever since reading the book by Kuhn and Johnson and working with caret in R I've been wanting an equivalent Python library.

Referencing #315 I wanted to propose to change the way the default logger is configured in [`pycaret.internal.logging`](https://github.com/pycaret/pycaret/blob/master/pycaret/internal/logging.py#L26):
```python
    try:
        ch = logging.FileHandler("logs.log")    # <-- don't specify a handler with a fixed filename, here
    except:
        print("Could not attach a FileHandler to the logger! No logs will be saved.")
        traceback.print_exc()
        ch = logging.NullHandler()
    ch.setLevel(logging.DEBUG)
```

In [#315](https://github.com/pycaret/pycaret/issues/315#issuecomment-667677236):
> pycaret commented on Aug 2, 2020
>@eonsmile Nope. Is there is a reason you want to disable? Maybe we can mark this as enhancement and somebody can work on making this functionality optional, if that make sense.

For me the use case is an application wrapping a PyCaret model. I've packaged the application using PyInstaller and it is distributed with a setup wizard as a "conventional" Windows application. After installation it's placed in the system's program folder (C:\Program Files (x86)) where normal users don't have write permissions -- but PyCaret wants to create its log file there. As PyCaret is imported in different modules, monkey-patching would require editing some external libraries as well, so re-configuration of the logger appears to be impractical.

Therefore I suggest to make the logging handler configurable, or do you have strong reasons to hard-code the file output?

Additionally, the [Python docs on logging](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library) state:
>Note
>
>It is strongly advised that you do not add any handlers other than NullHandler to your library’s loggers. This is because the configuration of handlers is the prerogative of the application developer who uses your library. The application developer knows their target audience and what handlers are most appropriate for their application: if you add handlers ‘under the hood’, you might well interfere with their ability to carry out unit tests and deliver logs which suit their requirements. 

If you accept this I would be happy to submit a PR implementing it.

Keep up the good work
Joschka

**Comment by Yard1** [comment]
The main issue is figuring out a robust way to configure the logging path - but aside from that, there's nothing preventing it being more configurable. A PR will be appreciated!

**Comment by pycaret** [comment]
@joschkazj @Yard1 I am in full support of providing the ability to turn off logging. I have a couple of use cases where people are not able to use PyCaret on Databricks because PyCaret tries to create a `logs.log` file on a master node which is administratively restricted to create any log file. So if we can maybe provide a parameter in the `setup` to control that? Don't know whats the best way but definitely, ability to disable logging is great.

**Comment by amjadraza** [comment]
I am not sure what thought process has been followed while coding up logging however as agreed above it is important to issue to tackle. I had written a Custom Logging class in the past shipped with Python Package. Recently, I have come across the python package `loguru`, it may be worth exploring....

@joschkazj Happy to discuss further.

**Comment by moezali1** [comment]
This is being addressed in the release of 2.3.6.

**Comment by TridevNS** [comment]
@moezali1 is there any way to configure the log directory... Getting below error on databricks cluster.
![Screen Shot 2022-04-26 at 12 32 58 PM](https://user-images.githubusercontent.com/17480441/165241635-ef5c78fe-d0c8-4685-bb10-cd3d452c50a6.png)
.

**Comment by timmhuang** [comment]
Just checking in again to see if anyone found a way to workaround this on Databricks? Or can we now disable log writing somehow?

**Comment by brucewlee** [comment]
@timmhuang @ekdz @TridevNS 

Go to your library address and change the file below:

<some dir>/pycaret/internal/logging.py

What I did was:
<img width="638" alt="Screenshot 2023-07-25 at 12 25 12 PM" src="https://github.com/pycaret/pycaret/assets/54278520/af78783b-114d-4af8-87a6-350473c994e8">

I hope my answer helps.
