### ISSUE TITLE
AWS model deployment failed with unexpected keyword

### ISSUE THREAD

**Issue by Weltbummler1** [pycaret/pycaret#1059]
Hi, could not find any related issue: 

Deploying my code to AWS works fine with:.

`deploy_model(final_model, model_name = 'lr_aws', platform = 'aws', authentication = { 'bucket'  : 'pycaret-test' })`
`Model Succesfully Deployed on AWS S3`

but prediction failed (code is from the documentation) with: 

`predictions = predict_model(model_name = 'lr_aws', data = data_unseen, platform = 'aws', authentication = { 'bucket' : 'pycaret-test' })`

_---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-eb0cb74cb62f> in <module>
TypeError: predict_model() got an unexpected keyword argument 'model_name'_

The keyword argument error pops up for model_name, platform and authentication.... Can't figure out what the issue is. 

Any help is appreciated. 

Thx

**Comment by Yard1** [comment]
That is not how you should do predictions. You need to first obtain the model object from AWS and then run predict on it.

**Comment by Weltbummler1** [comment]
Got it, makes sense. 

`aws_model = load_model(model_name = 'lr_aws', platform = 'aws', authentication = { 'bucket'  : 'pycaret-test' })`
`predictions = predict_model(aws_model, data = data_unseen)`
