### ISSUE TITLE
setup(df, target='target') error

### ISSUE THREAD

**Issue by zach-hedge** [pycaret/pycaret#1061]
Receiving value error with a very simple model setup:

>>> setup(model_df, target='success')

`ValueError: Setting a random_state has no effect since shuffle is False. You should leave random_state to its default (None), or set shuffle=True.
`

Same code snippet worked fine 12-18 hours ago

**Comment by Yard1** [comment]
Try making a new virtual environment and installing the development version of PyCaret with `pip install -U git+https://github.com/pycaret/pycaret.git`.

**Comment by zach-hedge** [comment]
@Yard1 Worked like a charm! Thanks!
