### ISSUE TITLE
ERROR: pandas-profiling 2.10.1 has requirement requests>=2.24.0, but you'll have requests 2.23.0 which is incompatible.

### ISSUE THREAD

**Issue by saimmehmood** [pycaret/pycaret#1062]
Found this issue when installed pycaret on colab using 
> !pip install pycaret

**Comment by pycaret** [comment]
@saimmehmood Hi. This is just a warning, not an error. I just tried installing on colab got these warnings but PyCaret works just fine.

![Uploading image.png…]()
