### ISSUE TITLE
Discrepancy in AUC calculation?

### ISSUE THREAD

**Issue by Scoodood** [pycaret/pycaret#1065]
How does Pycaret calculate the **AUC** in the following multiclass dataset? I try to manually calculate them using `add_metric()` and `roc_auc_score`. But the numbers are off slightly. Is this normal or a bug somewhere?

```python
from pycaret.datasets import get_data
from pycaret.classification import *
from sklearn.metrics import roc_auc_score

data2 = get_data('iris')
clf = setup(data2, target='species', session_id=123, silent=True, verbose=False)
add_metric('auc2', 'AUC2', roc_auc_score, target='pred_proba', multi_class='ovr')
add_metric('auc3', 'AUC3', roc_auc_score, target='pred_proba', multi_class='ovo')
best = compare_models(include=['rf', 'catboost', 'xgboost', 'lightgbm'], fold=3)
```
![Capture](https://user-images.githubusercontent.com/15989924/107835465-730c6180-6d4e-11eb-8c85-8394f0d1ef52.PNG)

<hr>

For binary classification, it's ok
```python
data1 = get_data('juice')
clf = setup(data1, target='Purchase', session_id=123, silent=True, verbose=False)
add_metric('auc2', 'AUC2', roc_auc_score, target='pred_proba')
best = compare_models(include=['rf', 'catboost', 'xgboost', 'lightgbm'], fold=3)
```

![Capture](https://user-images.githubusercontent.com/15989924/107835829-b0252380-6d4f-11eb-9b88-94fee4ef1af6.PNG)

**Comment by Yard1** [comment]
We use `average="weighted"` for ROC-AUC calculation. If you do:
```python
add_metric('auc2', 'AUC2', roc_auc_score, target='pred_proba', multi_class='ovr', average='weighted')
```
the results will be identical with the PyCaret ROC-AUC. Hope that helps.

**Comment by Scoodood** [comment]
Dear @Yard1, thanks a lot!

**Comment by sorenwacker** [comment]
Does this affect both multi-class and binary-classification? Is supposed to be fixing class imbalance? I get a similar discrepancy between the `pycaret` reported value and `scikit-learn` for a binary classification problem.
