### ISSUE TITLE
Load_config() throws error

### ISSUE THREAD

**Issue by sagarnildass** [pycaret/pycaret#1070]
I am trying to reproduce the example in your documentation for load_config and save_config

```
from pycaret.datasets import get_data
juice = get_data('juice')
from pycaret.classification import *
exp_name = setup(data = juice,  target = 'Purchase')
save_config('myvars.pkl')
```

Now I restarted the jupyter notebook and loaded the config like this:

```
from pycaret.classification import load_config
load_config('myvars.pkl')
```

Now when I am running a create_model command like this:

```
create_model('xgboost', verbose=True)
```
It throws an error: NameError: name 'create_model_container' is not defined

Am I doing something wrong? It seemed like from your documentation load_config is the same as running setup and then I should have been able to run the create_model successfully.

Please help!

**Comment by Yard1** [comment]
This should be fixed in an update to be released this week.

**Comment by sagarnildass** [comment]
Cool thanks!

**Comment by S-UP** [comment]
It does not look like this has been fixed. 

I am running version 2.3.0 and still see this happening.
