### ISSUE TITLE
compare_models return null object in colab

### ISSUE THREAD

**Issue by prabhakaran2812** [pycaret/pycaret#1074]
compare_models return null object in colab

**Comment by prabhakaran2812** [comment]
But it works in my pc local

**Comment by Yard1** [comment]
Run it with `errors="raise" ` to see what's the issue.

**Comment by prabhakaran2812** [comment]
Thanks tried this
    best = compare_models(turbo=True) when i print best it give [] (empty output) showed no errors BUT
When I ran     best = compare_models(turbo=True,errors="raise") below was the error
print best gave the name of the best model and showed the error that n_split > n_sample. 
Upon debugging found it turned to be data sample insufficiency. When I increased the sample size, problem disappeared.
Thanks for the help. Errors=raise helped me debug the problem

**Comment by prabhakaran2812** [comment]
Pycaret is awesome!

**Comment by Anagha-github** [comment]
thank you very much.. this helped me too
