### ISSUE TITLE
TypeError: predict_model() got an unexpected keyword argument 'platform'

### ISSUE THREAD

**Issue by AmolMavuduru** [pycaret/pycaret#1079]
I trained a model and ran the following code in a Jupyter Notebook after deploying the model to AWS successfully. 

```
from pycaret.regression import *
predictions = predict_model('automl-model', 
                            data = pred_holdouts, 
                            platform = 'aws', 
                            authentication = { 'bucket' : 'pycaret-ca-housing-model' })
```

I followed the documentation for the predict_model function [here](https://pycaret.org/regression/).

However, I ran into the following error after running the code.

TypeError: predict_model() got an unexpected keyword argument 'platform'

**Comment by Yard1** [comment]
You need to load the model first. The documentation under the link is outdated, please use this one: https://pycaret.readthedocs.io/en/latest/

**Comment by AmolMavuduru** [comment]
@Yard1 Thanks for pointing that out! So the deploy_model function really just uploads the pickled model to a storage service (ie. S3) in a cloud platform right? I was expecting it to deploy the model to some kind of service for running predictions in the cloud.
