### ISSUE TITLE
"Cox and Snell R2" and "Nagelkerke R2" for Logistic Regression like in SAS

### ISSUE THREAD

**Issue by azharirfan** [pycaret/pycaret#108]
SAS Software displays "Cox and Snell R2" and "Nagelkerke R2" for Logistic Regression. A number of organizations and Senior Management are used to seeing the R2 for Logistic Regression. Hence please see if similar calculations(s) be replicated in pycaret for Classification. 

SAS Usage: https://communities.sas.com/t5/Statistical-Procedures/Cox-Snell-and-Naglekerke-R-squares/td-p/162734

**Comment by azharirfan** [comment]
This is the math used by SAS to calculate the values:
https://support.sas.com/resources/papers/proceedings/proceedings/sugi25/25/st/25p256.pdf

Others:
https://web.archive.org/web/20130701052120/http://www.ats.ucla.edu:80/stat/mult_pkg/faq/general/Psuedo_RSquareds.htm
http://wlm.userweb.mwn.de/ST004.pdf
https://stats.idre.ucla.edu/other/mult-pkg/faq/general/faq-what-are-pseudo-r-squareds/

**Comment by pycaret** [comment]
@azharirfan thanks for sharing.

I will mark this as an enhancement for future.
