### ISSUE TITLE
No module named 'pycaret.internal' - loading saved model from local drive - using jupyter notebook

### ISSUE THREAD

**Issue by pavangadde** [pycaret/pycaret#1080]
loading saved model using joblib.load and load_model
facing No module named 'pycaret.internal' error

**Comment by pycaret** [comment]
@pavangadde Which version are you using? Can you please install the latest version of PyCaret in a new conda environment and try again and let us know how it goes?

Link to installation guide: https://pycaret.readthedocs.io/en/latest/installation.html

**Comment by ngupta23** [comment]
@pavangadde , we will close this issue. Feel free to reopen if the issue persists.

**Comment by Subrata15** [comment]
HI, I still have this issue, my pycaret version is 2.1.2, any though?

**Comment by ngupta23** [comment]
This is a very old version. Please install the latest version in a new conda env and check.

**Comment by talhaanwarch** [comment]
i am getting same error in `2.3.5` ModuleNotFoundError: No module named 'pycaret.internal.pycaret_experiment'

**Comment by OleksiyAnokhin** [comment]
The same version on `2.3.5` version

**Comment by ngupta23** [comment]
I think you might be trying to use the time series module? Is my understanding correct? If so, you need to install it in a separate environment from the regular pycaret. The regular pycaret (2.3.x) does not have the 'pycaret.internal.pycaret_experiment' module yet. It is only available in the time series module.

To install the time series module, for now, you should do the following in a clean environment

```
pip install pycaret-ts-alpha
```

Then you can do this

```python
from pycaret import show_versions
show_versions()
```

You should see pycaret 3.0.0 in there. This would mean that you have installed the pycaret time series module correctly.

If you want to use anything other than the time series module, you should do this in a clean environment for now

```
!pip install -U pycaret
```

Then , when you do this

```
import pycaret
print(pycaret.__version__)
```

You should see 2.3.x. If you see 3.0.0 here, then you have not installed it correctly.

**Comment by OleksiyAnokhin** [comment]
@ngupta23 , thanks, would be great, if you guys did a short tutorial on how to do TS with exogenous variables. Working on it right now.

**Comment by ngupta23** [comment]
Yes, it's already there. Check out this post: https://www.linkedin.com/posts/guptanick_pycaret-timeseries-opensource-activity-6903390711044038656-IsZv
