### ISSUE TITLE
TypeError: apriori() got an unexpected keyword argument 'low_memory'

### ISSUE THREAD

**Issue by dcsai-hitomi** [pycaret/pycaret#1081]
When I ran the following tutorial on Colaboratory, the following error message was displayed.

Association Rule Mining Tutorial (ARUL101)
https://github.com/pycaret/pycaret/blob/master/tutorials/Association%20Rule%20Mining%20Tutorial%20-%20ARUL01.ipynb

model1 = create_model() #model created and stored in model1 variable.
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-137ddd2a0679> in <module>()
----> 1 model1 = create_model() #model created and stored in model1 variable.

/usr/local/lib/python3.7/dist-packages/pycaret/arules.py in create_model(metric, threshold, min_support, round, low_memory, max_len)
    208     basket = basket.applymap(encode_units)
    209 
--> 210     frequent_itemsets = apriori(basket, min_support=min_support, use_colnames=True, low_memory=low_memory, max_len=max_len)
    211     rules = association_rules(frequent_itemsets, metric=metric, min_threshold=threshold)
    212     rules = rules.sort_values(by=[metric], ascending=False).reset_index(drop=True)

TypeError: apriori() got an unexpected keyword argument 'low_memory'
```

This support was added in PyCaret 2.3
#1008

When I ran `pip install pycaret` run,mlxtend version is 0.14.0 was installed
```
Requirement already satisfied: mlxtend in /usr/local/lib/python3.7/dist-packages (from pycaret) (0.14.0)
```
The low_memory parameter was added from mlxtend 0.17
https://github.com/rasbt/mlxtend/releases/tag/v0.17.0

mlxtend has no version specified
https://github.com/pycaret/pycaret/blob/master/requirements.txt#L21

**Comment by Yard1** [comment]
Thanks for pointing this out, will update the requirements.

**Comment by pycaret** [comment]
Thank you @dcsai-hitomi for pointing this out.
