### ISSUE TITLE
Get and apply Pipeline Setup in the unseen data

### ISSUE THREAD

**Issue by brunobarella** [pycaret/pycaret#1084]
How do I get the construction pipeline of the input dataset made in the setup?
For example, when I apply on data not seen in the model.

[Link to the intermediate regression tutorial](https://github.com/pycaret/pycaret/blob/master/tutorials/Regression%20Tutorial%20Level%20Intermediate%20-%20REG102.ipynb) presents an example. The unseen data has 8 columns, but in the model there are 39. How do I create the rest of the columns and apply the finished model over the unseen data?

**Comment by Yard1** [comment]
If you have an experiment running, you just need to call `predict_model(data=unseen_data)`. If you don't want to run PyCaret, you can either use `save_model()` which saves the entire pipeline (by default) to disk, or use `get_config(prep_pipe)` to obtain the same thing. PyCaret pipelines use the sklearn API.

**Comment by brunobarella** [comment]
I got this by applying `predict_model(data=unseen_data)`:
`AttributeError: 'LGBMRegressor' object has no attribute 'predict_model'`

But applying `predict(get_config(prep_pipe).transform(unseen_data))` it worked:
![image](https://user-images.githubusercontent.com/28939189/109247447-b17c3480-77c2-11eb-8563-58c336cb599d.png)
