### ISSUE TITLE
Label Encoded	

### ISSUE THREAD

**Issue by SSITB** [pycaret/pycaret#1085]
Hi ,

Is there a way to define the label for the target encoded.
For example suppose I have 3 classes A,B,C when setup the env, I will have for example 
A-->1 , B-->2 , C-->3 , 
what I want is when I add more class D, the label encoding is changing this will be hard to check the confusion matrix of the 3 classes vs 4 classes

**Comment by SSITB** [comment]
@wkuopt ,What I want exactly is to define the label encoder 1,2,3,4, what i did to resolve this, is to add number before the class before the setup, like this the label encoder will be ordered.
The reason behind is when i want to compare the confusion matrix for 3 classes or 4 or 5, I want the class add to be the same,

**Comment by Sebagam** [comment]
Is there a way to display the original labels when plotting the reports?
