### ISSUE TITLE
Accessing variables from setup - Example "Label Encoded"

### ISSUE THREAD

**Issue by SSITB** [pycaret/pycaret#1087]
Hi,

Suppose i want to access label encoded value from the setup,  currently I am guessing by trying, as below
reg1[24][0][1] this will return the table description as database than need to get the value.

Is there a better way to access the value from the description table, or to navigate through the tuple setup output

An alternative to the below 
reg1[24][0][1]['Value'][3]

Output :
A: 0, B : 1, C: 2, D: 3

**Comment by Yard1** [comment]
`get_config('prep_pipe').named_steps["dtypes"].replacement` will give you a dict of encoded labels.

**Comment by SSITB** [comment]
Perfect, but the documentation is not clear on how to get this, is there some detail documentation to access these variables

**Comment by wkuopt** [comment]
Hey @SSITB, this also seems to solve issue #1085, since you can do the mapping between the results with different levels?
