### ISSUE TITLE
Custom model - Unable to set shape for input to custom model

### ISSUE THREAD

**Issue by prabhakaran2812** [pycaret/pycaret#1093]
I am trying to use a custom model like below

```python
def mycustommodel():
  mymodel=Sequential()
  mymodel.add(LSTM(50,return_sequences=True,input_shape=(465,1)))
  mymodel.add(LSTM(50,return_sequences=True))
  mymodel.add(LSTM(50))
  mymodel.add(Dense(1))
  mymodel.compile()
  return mymodel

Kmodel = KerasClassifier(build_fn=mycustommodel,verbose=1)

km = create_model(Kmodel)
```

I know this LSTM need a specific input shape for x_train, but I dont have option to shape through setup / create model. Please advise.

The error below
ValueError: Input 0 of layer sequential_3 is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (None, 410)

**Comment by ngupta23** [comment]
It may be possible that the preprocessing is changing the number of features in the dataset. After the setup, you may be able to get the X_train value using `get_config` ([see doc](https://pycaret.org/get-config/)). Then pass that number of columns in X_train to your custom model before adding it to `pycaret`.
