### ISSUE TITLE
Add function/parameter to set working directory

### ISSUE THREAD

**Issue by garyee** [pycaret/pycaret#1098]
**Is your feature request related to a problem? Please describe.**
It would be great, if the path for all file-based output could be set with one function.
This includes save_model, logs ... I also get a cat_boost folder sometimes. I am using Google Colab with GDrive connected.

**Describe the solution you'd like**
It would be of great help, if all files would be put into my GDrive directory as the runtime environment will be deleted by Colab after a while. I imagine a function or a parameter for setup where I can set the path and all functions which write to the filesystem use this path as default directory.

**Describe alternatives you've considered**
What I do right now is to put the path into every function which I know writes files. But I do not know where the cat_boost folder comes from and I did not find any place where I can set the path for it.

**Additional context**
Very nice Library!

**Comment by ngupta23** [comment]
Lets leave this open for now.
