### ISSUE TITLE
Catboost version problem while installing pycaret

### ISSUE THREAD

**Issue by Davisy** [pycaret/pycaret#110]
I got this error while installing pycaret

ERROR: Could not find a version that satisfies the requirement catboost==0.20.2 (from pycaret) (from versions: none)
ERROR: No matching distribution found for catboost==0.20.2 (from pycaret)

**Comment by DaGuT** [comment]
already fixed in dev-1.0.1 version

**Comment by Davisy** [comment]
> already fixed in dev-1.0.1 version
> You can install it with `pip install https://github.com/pycaret/pycaret/archive/dev-1.0.1.zip`

thanks
