### ISSUE TITLE
Estimator xgboost and catboost not found

### ISSUE THREAD

**Issue by sulphuricacid** [pycaret/pycaret#1101]
I installed pycaret using !pip3 install pycaret

from pycaret.datasets import get_data 
from pycaret.regression import * 
dataset = get_data('diamond')
exp_reg = setup(dataset,target = 'Price')
x = create_model('xgboost')

this is the error I'm getting (same for catboost estimator as well)

   2897         if estimator not in available_estimators:
   2898             raise ValueError(
-> 2899                 f"Estimator {estimator} not available. Please see docstring for list of available estimators."
   2900             )
   2901     elif not hasattr(estimator, "fit"):

ValueError: Estimator xgboost not available. Please see docstring for list of available estimators.

**Comment by sulphuricacid** [comment]
lightbgm also not working

**Comment by Yard1** [comment]
You need to install them through pip separately, or do `pip install -U "pycaret[full]"`

**Comment by sulphuricacid** [comment]
thank you, its working
