### ISSUE TITLE
['response, coronary heart disease'] not found in axis

### ISSUE THREAD

**Issue by KrishnaMohinani** [pycaret/pycaret#1106]
I really don't understand why I am having this error if I run the line. Trying to solve a classification problem.
clf = setup(data = df,target = 'response, coronary heart disease')

The data can be viewed from the link below
https://raw.githubusercontent.com/KrishnaMohinani/SAheart/main/SAheart.csv

**Comment by Yard1** [comment]
Can you try renaming the column to something else?

**Comment by KrishnaMohinani** [comment]
Works now. 
Thanks
