### ISSUE TITLE
llvmlite not allowing pycaret to install

### ISSUE THREAD

**Issue by ahad-aa** [pycaret/pycaret#1109]
When I try the following code:

pip install pycaret

the error message i get is:

"ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."

i have tried several ways of installing/upgrading llvmlite but no success. 

Any suggestions?

**Comment by Yard1** [comment]
Can you try installing PyCaret in a new virtual environment?

**Comment by moezali1** [comment]
@ahad-aa You can follow the instructions here for installing a new conda environment and then installing pycaret in that env.

https://pycaret.readthedocs.io/en/latest/installation.html
