### ISSUE TITLE
pycaret error: not importing all libraries

### ISSUE THREAD

**Issue by davdkela225** [pycaret/pycaret#1134]
I am trying to import all libraries from pycaret but I got an error. I had tried the following methods:

1. Did the installation on my virtual environment via a terminal using this command: pip install pycaret
2. Did the following command in a jupiter notebook: !pip install pycaret

Then I have the following error in my jupiter notebook

from pycaret.classification import *

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-35-a8cb12878b37> in <module>
----> 1 from pycaret.classification import *

~/opt/anaconda3/envs/mlbootcamp38/lib/python3.8/site-packages/pycaret/classification.py in <module>
      8 import numpy as np
      9 
---> 10 import pycaret.internal.tabular
     11 from pycaret.internal.Display import Display, is_in_colab, enable_colab
     12 from typing import List, Tuple, Any, Union, Optional, Dict

~/opt/anaconda3/envs/mlbootcamp38/lib/python3.8/site-packages/pycaret/internal/tabular.py in <module>
     45 import pycaret.containers.models.clustering
     46 import pycaret.containers.models.anomaly
---> 47 import pycaret.internal.preprocess
     48 import pandas as pd
     49 import numpy as np

~/opt/anaconda3/envs/mlbootcamp38/lib/python3.8/site-packages/pycaret/internal/preprocess.py in <module>
     32 from sklearn.ensemble import RandomForestClassifier as rfc
     33 from sklearn.ensemble import RandomForestRegressor as rfr
---> 34 from lightgbm import LGBMClassifier as lgbmc
     35 from lightgbm import LGBMRegressor as lgbmr
     36 import sys

~/opt/anaconda3/envs/mlbootcamp38/lib/python3.8/site-packages/lightgbm/__init__.py in <module>
      6 import os
      7 
----> 8 from .basic import Booster, Dataset, register_logger
      9 from .callback import early_stopping, print_evaluation, record_evaluation, reset_parameter
     10 from .engine import CVBooster, cv, train

~/opt/anaconda3/envs/mlbootcamp38/lib/python3.8/site-packages/lightgbm/basic.py in <module>
     93 
     94 
---> 95 _LIB = _load_lib()
     96 
     97 

~/opt/anaconda3/envs/mlbootcamp38/lib/python3.8/site-packages/lightgbm/basic.py in _load_lib()
     84     if len(lib_path) == 0:
     85         return None
---> 86     lib = ctypes.cdll.LoadLibrary(lib_path[0])
     87     lib.LGBM_GetLastError.restype = ctypes.c_char_p
     88     callback = ctypes.CFUNCTYPE(None, ctypes.c_char_p)

~/opt/anaconda3/envs/mlbootcamp38/lib/python3.8/ctypes/__init__.py in LoadLibrary(self, name)
    445 
    446     def LoadLibrary(self, name):
--> 447         return self._dlltype(name)
    448 
    449 cdll = LibraryLoader(CDLL)

~/opt/anaconda3/envs/mlbootcamp38/lib/python3.8/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    367 
    368         if handle is None:
--> 369             self._handle = _dlopen(self._name, mode)
    370         else:
    371             self._handle = handle

OSError: dlopen(/Users/theonlyone/opt/anaconda3/envs/mlbootcamp38/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/theonlyone/opt/anaconda3/envs/mlbootcamp38/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found

**Comment by Yard1** [comment]
That doesn't look like an issue with PyCaret. Can you try on Google Colab?

**Comment by Darkhero1976** [comment]
@Yard1 I am also getting errors while installing pycaret on Google Colab; first I tried with 'pip install', then I used 'conda install', then I used prefixes, 

such as '!conda install -c conda-forge --prefix {sys.prefix} pycaret', I am also using conda virtual environment but '!source activate' command is only valid inside the cell, so it must be repeated at the beginning of every cell to be able to use conda virtual env.

This is a good blogpost, but this isn't working either:
http://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/index.html

The error I get:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abortfailed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

**Comment by Darkhero1976** [comment]
This time I tried without using conda virtual environment and using /usr/local as prefix:
!conda install -c conda-forge --prefix /usr/local pycaret

I got this error:
Collecting package metadata (current_repodata.json): failed
InvalidVersionSpec: Invalid version '4.19.112+': empty version component

**Comment by Yard1** [comment]
Pip install by itself should work. Can you try, in a fresh environment: `!pip install -U pycaret-nightly[full]`?

**Comment by Darkhero1976** [comment]
I tried that command in Google Colab, this one: '!pip install -U pycaret-nightly[full]', I got these errors:

ERROR: pandas-profiling 2.11.0 has requirement requests>=2.24.0, but you'll have requests 2.23.0 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: pyldavis 3.3.1 has requirement numpy>=1.20.0, but you'll have numpy 1.19.5 which is incompatible.
ERROR: pyldavis 3.3.1 has requirement pandas>=1.2.0, but you'll have pandas 1.1.5 which is incompatible.
ERROR: phik 0.11.2 has requirement scipy>=1.5.2, but you'll have scipy 1.4.1 which is incompatible.
ERROR: botocore 1.20.45 has requirement urllib3<1.27,>=1.25.4, but you'll have urllib3 1.24.3 which is incompatible.
ERROR: awscli 1.19.45 has requirement colorama<0.4.4,>=0.2.5, but you'll have colorama 0.4.4 which is incompatible.

Also I got another error:
from pycaret.utils import enable_colab
pycaret.utils.enable_colab()
NameError: name 'pycaret' is not defined

**Comment by Darkhero1976** [comment]
@Yard1 @pycaret I think I am out of luck with pycaret :(

**Comment by Yard1** [comment]
Please find an example notebook I just put together below:
https://colab.research.google.com/drive/1jPm6J2aOG9KRQ8Aaa63TR-0p6sFIfRSk?usp=sharing

**Comment by moezali1** [comment]
@Darkhero1976 What is your operating system?
