### ISSUE TITLE
Issue regarding compare_models()

### ISSUE THREAD

**Issue by SuhanC** [pycaret/pycaret#1135]
Hello, 
I'm using pycaret's compare_models() to compare my top 5 models by your tutorial,
but it seems it gives an repeated error when making the model. 

Error message is liek below.
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-45752a1152bc> in <module>
     59                             +'_p_0.05_automl_'+target_phen+'_hpv',sep='\t')
     60 
---> 61 saveML_automl_topmerge('pathologic_N')

<ipython-input-4-45752a1152bc> in saveML_automl_topmerge(target_phen, cptac_merged_phen, cv_final)
     25         if len(ml_mat1.columns)>1 :
     26 
---> 27             top5 = compare_models(n_select = 3,fold=5,exclude = ['knn','catboost'],verbose=False) #,include=['lda','lr','qda'],,
     28             tuned_top5 = [tune_model(i) for i in top5]
     29             best = automl(optimize = 'AUC',use_holdout=False)

~/anaconda3/lib/python3.7/site-packages/pycaret/classification.py in compare_models(include, exclude, fold, round, cross_validation, sort, n_select, budget_time, turbo, errors, fit_kwargs, groups, verbose)
    782         fit_kwargs=fit_kwargs,
    783         groups=groups,
--> 784         verbose=verbose,
    785     )
    786 

~/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py in compare_models(include, exclude, fold, round, cross_validation, sort, n_select, budget_time, turbo, errors, fit_kwargs, groups, verbose, display)
   1908 
   1909     # checking error for exclude (string)
-> 1910     available_estimators = _all_models
   1911 
   1912     if exclude != None:

NameError: name '_all_models' is not defined---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-45752a1152bc> in <module>
     59                             +'_p_0.05_automl_'+target_phen+'_hpv',sep='\t')
     60 
---> 61 saveML_automl_topmerge('pathologic_N')

<ipython-input-4-45752a1152bc> in saveML_automl_topmerge(target_phen, cptac_merged_phen, cv_final)
     25         if len(ml_mat1.columns)>1 :
     26 
---> 27             top5 = compare_models(n_select = 3,fold=5,exclude = ['knn','catboost'],verbose=False) #,include=['lda','lr','qda'],,
     28             tuned_top5 = [tune_model(i) for i in top5]
     29             best = automl(optimize = 'AUC',use_holdout=False)

~/anaconda3/lib/python3.7/site-packages/pycaret/classification.py in compare_models(include, exclude, fold, round, cross_validation, sort, n_select, budget_time, turbo, errors, fit_kwargs, groups, verbose)
    782         fit_kwargs=fit_kwargs,
    783         groups=groups,
--> 784         verbose=verbose,
    785     )
    786 

~/anaconda3/lib/python3.7/site-packages/pycaret/internal/tabular.py in compare_models(include, exclude, fold, round, cross_validation, sort, n_select, budget_time, turbo, errors, fit_kwargs, groups, verbose, display)
   1908 
   1909     # checking error for exclude (string)
-> 1910     available_estimators = _all_models
   1911 
   1912     if exclude != None:

NameError: name '_all_models' is not defined

How do i fix it? 
I re-installed latest version myself, but it wont work. 

Thank you !

**Comment by Yard1** [comment]
Have you ran `setup()` before?

**Comment by SuhanC** [comment]
@Yard1 During editing my code, setup() had removed for some reason. 
Thanks! I figured it out.
