### ISSUE TITLE
pmml

### ISSUE THREAD

**Issue by zhaozhongfeng1990** [pycaret/pycaret#114]
how to convert model to pmml .Thanks for this great library and continuous support.

**Comment by pycaret** [comment]
@zhaozhongfeng1990  Unfortunately at this point you can only save it as a pickle file. PMML is not supported. I will tag this is enhancement for future and see if somebody would like to work on this.

**Comment by pycaret** [comment]
Help wanted.

Can somebody please work on to include this functionality in **save_model** and **load_model** function in **pycaret.classification pycaret.regression pycaret.clustering pycaret.anomaly and pycaret.nlp**. New parameter "format" should be added. Default should be ".pkl". When format is set to ".pmml", pipeline should be saved as .pmml.

Reach out moez.ali@queensu.ca if discussion needed.

**Comment by pycaret** [comment]
Closing this thread. `duplicate`
