### ISSUE TITLE
Simple_Imputer' object has no attribute 'fill_value_categorical

### ISSUE THREAD

**Issue by gianghoang217** [pycaret/pycaret#1140]
Hi, I'm using the Pycaret 2.3.0, the model runs smoothly on my local but ran into the same issue on both Google colab and when deployed to lambda. Has anyone happened to solve that issue yet? Thanks

"errorMessage": "'Simple_Imputer' object has no attribute 'fill_value_categorical'",
  "errorType": "AttributeError",

**Comment by moezali1** [comment]
@gianghoang217 Can you please share your code and notebook with sample data? I will take a look.

What's version of PyCaret you are using?

@Yard1 I think we have discussed this error in the past "'Simple_Imputer' object has no attribute 'fill_value_categorical'". Do you have any clue?

**Comment by Yard1** [comment]
I believe it has been fixed on master already. `pycaret-nightly` should have the fix.

**Comment by gianghoang217** [comment]
@moezali1 , @Yard1 I found out the reason for this error, if the scikit learn package updated to 0.24.1, I  downgraded it to 0.23.2, no more errors. Thanks for your help!

**Comment by venkaateshd** [comment]
hi, i would like to check if downgrading the scikit learn is the only solution for this problem ? i am getting same problem too.

i am afraid downgrading will disturb my other applications.

Thanks and please advise.

**Comment by HaithemH** [comment]
Hi there 
Same problem here with PyCaret 2.2.0

**Comment by HaithemH** [comment]
Yup Yup, problem solved with PyCaret 2.3
