### ISSUE TITLE
About the problems using Colab

### ISSUE THREAD

**Issue by sixten16** [pycaret/pycaret#1142]
Hi, when i use pycaret with colab, it often throw an error. But there is no error in running the same code locally. One possible reason is that: Colab's pre installed environment conflicts with pycaret. One possible solution is using conda by  
```
!pip install -q condacolab
import condacolab
condacolab.install_miniconda()
```
```
import condacolab
condacolab.check()
```
And then
`!pip install pycaret[full]`
The previous problem seems to have been solved.

**Comment by moezali1** [comment]
@sixten16 I just tried opening a fresh colab notebook and tried `pip install pycaret[full]` and it worked without any problems.

**Comment by sixten16** [comment]
> @sixten16 I just tried opening a fresh colab notebook and tried `pip install pycaret[full]` and it worked without any problems.

There is no problem in `pip install pycaret[full]`.  I mean when i used pycaret in colab for machine learning, it often throw errors.
Use `!pip install -q condacolab
import condacolab
condacolab.install_miniconda()`
can solve the problem.

**Comment by sixten16** [comment]
> @sixten16 I just tried opening a fresh colab notebook and tried `pip install pycaret[full]` and it worked without any problems.

And about the error,  you can find it by searching for colab in pycaret's issues. Such as https://github.com/pycaret/pycaret/issues/1140
