### ISSUE TITLE
Hi! i'am use Hydrogen + Atom, and sometime it's all broken

### ISSUE THREAD

**Issue by kingtelepuz5** [pycaret/pycaret#1143]
from time to time after running best_model = comprage_models () I get very strong distortions of my development environment, I can not say that I am sure that the problem is in Pycaret, perhaps Atom + Nydrogen is to blame, but the rest of the frames do not break, perhaps you can find the reason if not even, thanks anyway for your attention. 

when displaying the table of results, the lines on the left fly away in different directions, large spaces appear between the lines, which are not fixed in any way except to "enter / exit" the file completely. But again, I'm not very sure if this is a problem with your frame, but I guess so because I have not seen this with others. Maybe it's also because I'm using the extension ".py ", maybe we can suggest an alternative extension for nydrogen. Thanks :)

I'm a foreigner, so I use a translator, sorry for the inaccuracies

**Comment by kingtelepuz5** [comment]
The same thing happens with a text editor and during the launch of some output from the frames, it just dies. Thanks for any answer, if this is a problem in the development environment, I will definitely duplicate it on another forum. But thanks for any participation!
![Снимок экрана от 2021-04-06 22-11-35](https://user-images.githubusercontent.com/61143710/113765556-18c3c780-9725-11eb-8406-ad073303331e.png)

![Снимок экрана от 2021-04-06 22-12-31](https://user-images.githubusercontent.com/61143710/113765645-355fff80-9725-11eb-8f6b-fd4debb063f2.png)

this error is also not new

**Comment by kingtelepuz5** [comment]
ubunta 20.04 LTS, Atom + Hydrogen

**Comment by kingtelepuz5** [comment]
and I would like to add on my own, thank you very much for the work you've done, it's just amazing! When I accidentally found your library, I was crying with happiness, I am 19 and I am new to data science, but your library gave me a chance not to break, but on the contrary, to figure it out with everything, which I continue to do. Thank you so much for the tutorials, thank you so much for the examples. Definitely later, when I have more experience in development, I will join your community :)

**Comment by Yard1** [comment]
I would recommend you use an interactive Python notebook (ipynb) instead of pure script files. They are the mainstray for interactive data science. I am not sure if Atom has support for those but I know VSCode does. PyCaret is optimised to be used with notebooks.

**Comment by kingtelepuz5** [comment]
I looked at your YouTube videos with demonstrations, and now I understand my idea breaks down, though it will be much easier just to use Jupiter, thanks for the answer!
