### ISSUE TITLE
How do I get TOP-K evaluation indicators for multi-classification? For example, TOP-3 accuracy.

### ISSUE THREAD

**Issue by doraemonlei** [pycaret/pycaret#1144]
How do I get TOP-K evaluation indicators for multi-classification? For example, TOP-3 accuracy.

**Comment by vtoliveira** [comment]
I am not sure if I understood correcly, but to select top k models using a specific metric you can do:

```python
best = compare_models(
    sort='Accuracy', 
    n_select=5
)
```

This way best will be a list with 5 best models ordered from top to bottom rank.

**Comment by moezali1** [comment]
@doraemonlei 

```
top_3_models = compare_models(n_select = 3, sort = 'Accuracy')
compare_models_result = pull()
type(compare_models_result) #pd.DataFrame
compare_models_result['Accuracy'][:3] #sub-select top 3
```

**Comment by doraemonlei** [comment]
> I am not sure if I understood correcly, but to select top k models using a specific metric you can do:
> 
> ```python
> best = compare_models(
>     sort='Accuracy', 
>     n_select=5
> )
> ```
> 
> This way best will be a list with 5 best models ordered from top to bottom rank.

Thank you, but maybe I didn't express myself correctly.I mean Top-K accuracy (recall, precision), not Top-K model.

**Comment by doraemonlei** [comment]
> @doraemonlei
> 
> ```
> top_3_models = compare_models(n_select = 3, sort = 'Accuracy')
> compare_models_result = pull()
> type(compare_models_result) #pd.DataFrame
> compare_models_result['Accuracy'][:3] #sub-select top 3
> ```

Thank you, but maybe I didn't express myself correctly.I mean Top-K accuracy (recall, precision), not Top-K model.

**Comment by moezali1** [comment]
@doraemonlei See this example:

```
%%time
best = compare_models(sort = 'Accuracy')
best_scores = pull()
best_scores['Accuracy'][:3]
```

You can use the `pull` function to store the score grid as `pd.DataFrame` and then you can access the `Accuracy` or any other metric just the way you will access elements of the list. (see the last line of code in the above example.

Hope this helps.

![image](https://user-images.githubusercontent.com/54699234/114286127-0cdc4c00-9a2a-11eb-9098-b63c7b909ad4.png)

**Comment by doraemonlei** [comment]
> @doraemonlei See this example:
> 
> ```
> %%time
> best = compare_models(sort = 'Accuracy')
> best_scores = pull()
> best_scores['Accuracy'][:3]
> ```
> 
> You can use the `pull` function to store the score grid as `pd.DataFrame` and then you can access the `Accuracy` or any other metric just the way you will access elements of the list. (see the last line of code in the above example.
> 
> Hope this helps.
> 
> ![image](https://user-images.githubusercontent.com/54699234/114286127-0cdc4c00-9a2a-11eb-9098-b63c7b909ad4.png)

I think you still don't understand what I mean. For example, in ImageNet multi-classification task, if you want to get Top-3 accuracy, which means that the top-3 labels predicted by the model contain correct labels, then we think the results are correct.

**Comment by Yard1** [comment]
You can add your own metrics with `add_metric`. Please refer to the documentation.

**Comment by doraemonlei** [comment]
> You can add your own metrics with `add_metric`. Please refer to the documentation.

ok, thanks!
