### ISSUE TITLE
Logging setup parameters when running create_model, tune_model, etc.

### ISSUE THREAD

**Issue by vtoliveira** [pycaret/pycaret#1146]
Is there a easy way to log setup parameters to other functions such as create_model, tune_model, compare_models, etc?

For example, the image below shows how it is today:

![image](https://user-images.githubusercontent.com/32197310/113862947-6d942c00-977f-11eb-9b04-85b658b6d8b5.png)
****

I would like to have these parameters in all next experiments so I can track them correcly when ordering by some metric.

**Comment by Yard1** [comment]
We don't have a builtin functionality that would let you save the parameters passed to functions other than `setup()`, sorry.

**Comment by vtoliveira** [comment]
That's fine. Do you think this is too complicated to build? I could somehow help with that.

Anyaway, to anyone interested in a workaround, I had an idea: getting all runs from MlFlow and then filling NaN values for setup parameters using forward fill (All setup parameters start with capital letter). Apparently this works fine.

**Comment by Yard1** [comment]
I think it would be rather tiresome to implement it at this stage, though the next major release will come with another general architecture refactor which should make it easier.

**Comment by vtoliveira** [comment]
That's is good news. Ok then, I will close this issue and wait for next release. Thanks very much.
