### ISSUE TITLE
Accessing the Preprocess pipeline to use on similiar datasets for other machine learning libraries 

### ISSUE THREAD

**Issue by gyasis** [pycaret/pycaret#1147]
Is there a way to access only the preprocessing step of the pipeline of a trained model? For example, if I use the preprocessing to create features for the data, instead of using the pipeline with the trained model can I somehow get a returned data frame of a test dataset using the preprocessing of the trained dataset? Sometimes I may want to train the data on other libraries but would still like to use pycaret for some steps. 

I've thought of combining the data from the trained model with get_config but I don't think I can guarantee the same results on a test dataset without a target variable when I want to create features unless I'm also predicting said dataset. I think I saw it mentioned that since the saved model is a list I can access elements of the list, but I can't comprehend how that use that saved step to output a processed dataframe that wasn't inputted with the setup function

I hope thats a clear explanation and would appreciate any help

**Comment by Yard1** [comment]
You can obtain the pipeline with `get_config("prep_pipe")` after running `setup()`. The pipeline can be used with new data, provided the name of the target column stays the same.

**Comment by gyasis** [comment]
Ok. Thank You!
