### ISSUE TITLE
Large Dataset Stuck on Setup()

### ISSUE THREAD

**Issue by rlee300** [pycaret/pycaret#1148]
I'm using Pycaret classification to do some machine learning with my >1 million of data (this includes 18 categorical and 1 numerical features). Pandas Dataframe is storing the data pulled from Oracle database. These steps take about 2-3 minutes. When my data is being preprocessed, it's taking >7 hours. Is there a way to improve the speed? Pycaret is a great resource and I want to continue to use it. Any suggestions on improving the speed would be great!

Here's python SQL code: from pycaret.classification import *

init setup
clfl = setup(data=SQL_Query, target = 'cat_ind',silent = True, html = False,categorical_features= [cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,cat9,cat10,cat11,cat12,cat13,cat14,cat15,cat16,cat17],numeric_features=['amt'],ignore_features=['paid','catignore']remove_outliers=True,train_size=0.9,handle_unknown_categorical=True, unknown_categorical_method='most_frequent'))

**Comment by moezali1** [comment]
@rlee300 Can you tell me how many levels each categorical factor has in the dataset? I am wondering if it is making the dataset too sparse for `remove_outliers` liking. Have you tried with `remove_outliers = False`. 

You can also try using the `high_cardinality_features` functionality. That may compress the space and should help with timing.

![image](https://user-images.githubusercontent.com/54699234/114034522-4192ac80-984c-11eb-92e5-ce9ce6992fba.png)

**Comment by rlee300** [comment]
THANK YOU!!!! When I set it false, it worked like a charm! I'm so happy that I can continue to use this awesome tool. Thank you, again!
