### ISSUE TITLE
Amazon SageMaker Studio  installation 

### ISSUE THREAD

**Issue by hakobjan** [pycaret/pycaret#115]
Getting multiple error massages while trying to pip install pycaret  in Amazon SageMaker Studio.

`ERROR: Command errored out with exit status 1: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ysd97u4u/shap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ysd97u4u/shap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xnb7t32a/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.7m/shap Check the logs for full command output.`

**Comment by pycaret** [comment]
@hakobjan I don't know how to resolve that. I will keep it open and tag it for help needed and see if somebody can respond.

**Comment by DaGuT** [comment]
Please, try `!pip install https://github.com/pycaret/pycaret/archive/dev-1.0.1.zip` and show the error message if it still gives an error.

**Comment by hakobjan** [comment]
Gives the exact same Error

**Comment by DaGuT** [comment]
As far as I know there is only xgboost that can come non-compiled from devs.

Idk if you can install linux packages on  ASS, but if you can, then:
`sudo apt-get install build-essential libssl-dev libffi-dev python-dev python-pip libsasl2-dev libldap2-dev`

If not, then try to install other version of xgboost
`pip install xgboost==VERSION`
where version can be: 1.1.0rc2 , 1.0.2 , 0.90 (try each)

if it installs, then try installying dev version of pycaret again.
__
It'd be great to see full logs to get better understanding.

**Comment by sathishkumar369** [comment]
Try to use command as
    !pip install pycaret    in notebook instances.it worked for me Amazon notebook instances. It will automatically install all the packages.
Note: you must set the kernel as python 3.
Because by default it opens with pyspark.
You should change it python 3.
Hope it would work for you.
