### ISSUE TITLE
Get metrics: Homogeneity, Rand Index, Completeness

### ISSUE THREAD

**Issue by gm039** [pycaret/pycaret#1150]
Hi,

How to get metrics as Homogeneity, Rand Index, Completeness. Let's consider that I have ground-truth labels available.

![image](https://user-images.githubusercontent.com/50217085/114032483-579f6d80-984a-11eb-84a5-34ab0e20eeb6.png)

Thanks

**Comment by moezali1** [comment]
@gm039 It is very simple. There is a parameter `ground_truth` which accepts the name of the column containing the ground-truth value in the dataset.

```
create_model('kmeans', ground_truth='name_of_col')
```

Hope this helps. If yes, please close the issue. :)

**Comment by gm039** [comment]
Thanks, It worked.
