### ISSUE TITLE
error message when installing full version 

### ISSUE THREAD

**Issue by Jacques2101** [pycaret/pycaret#1151]
Hi
I tried to install Pycaret on my computer using the full version. I did on my terminal: 
`pip install pycaret[full]`as mention but get an error message: 
```zsh: no matches found: pycaret[full]```

Any ideas ? 
thx

**Comment by Yard1** [comment]
That's due to how zsh expands square brackets. Whenever you have a pip package with square brackets, put it in quotes - `pip install "pycaret[full]"` should work fine.

**Comment by Jacques2101** [comment]
work fine. 
Thx.
