### ISSUE TITLE
Optimizing saved pipeline size (disk space wise)

### ISSUE THREAD

**Issue by pyaf** [pycaret/pycaret#1155]
**Is your feature request related to a problem? Please describe.**

Saving the pycaret pipeline with `save_model` saves many intermediary variables associated with `pycaret.internal.preprocess.Fix_multicollinearity` class are also saved. According to me, they can be dropped during saving the pipeline because they are of no use during loading the model and making predictions with it during production. Idea credit goes to @pranaymodukuru 

**Describe the solution you'd like**

While saving the pipeline, delete variables which won't be required during prediction. Most of the disk space is used my `pycaret.internal.preprocess.Fix_multicollinearity` class' variables, we should drop them while saving the pipeline.

**Describe alternatives you've considered**
The main solution is quick and harmless, I don't think we'd require an alternative.

**Additional context**
Applying the proposed solution reduced the pipeline pickle file size from 2.5GB to a few MBs.

**Comment by Yard1** [comment]
Thanks, I just took a look at the class. There are a lot of variables that don't have to be bound to the object there. I'll attempt to optimize it.

**Comment by pranaymodukuru** [comment]
For people looking for a quick solution, here is a wrapper function to save the model after removing these space-occupying variables that are not required during inference.

```python
def save_slim_model(model, experiment_config, get_config, model_name):
    """
    model: pycaret model
    experiment_config: variable returned by "setup" function of pycaret
    get_config: a function from pycaret (just pass it as argument)
    model_name: str 
    """
    
    ## Get prep_pipe variable
    import pandas
    import joblib
    from copy import deepcopy
    
    prep_pipe = get_config("prep_pipe")

    ## Slim down prep_pipe by removing data frames greater than threshold
    for i, (name, step) in enumerate(prep_pipe.steps):    
        if step == "passthrough":
            continue
            
        ## Currently only removing dataframes from "Fix_multicollinearity"
        if isinstance(step, pycaret.internal.preprocess.Fix_multicollinearity):
            step.melt = None
            step.corr_matrix = None
            step.data1 = None
            step.avg_cor = None
            step.targ_cor = None
            step.merge = None
            step.merge1 = None
            step.one = None
            step.non_zero = None
    
    ## Add model to the prep_pipe
    prep_pipe.steps.append(["trained_model", model])
    
    ## Save model
    model_name = f"{model_name}.pkl"
    joblib.dump(prep_pipe, model_name)
    
    return (model, model_name)
```
