### ISSUE TITLE
Why target  is required in insurance data set for setup

### ISSUE THREAD

**Issue by sabatlive** [pycaret/pycaret#1158]
**Is your feature request related to a problem? Please describe.**
Why target  is required in insurance data set for setup

**Describe the solution you'd like**
I am trying to run the notebook. I can see insurance data. But, setup fails saying charges field is missing.

**Describe alternatives you've considered**
It should not complain about missing target field.

**Additional context**
It is a stopper for new users. I had to add a column called 'charges' to proceed.

**Comment by moezali1** [comment]
@sabatlive Can you share the Notebook and your code. I can run the following code and it works without problem.

```
from pycaret.datasets import get_data
data = get_data('insurance')

from pycaret.regression import *
s = setup(data, target = 'charges')
```
