### ISSUE TITLE
Feature Request: option to save plots with user defined file names

### ISSUE THREAD

**Issue by snewhouse** [pycaret/pycaret#1161]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be great to run something like:

```
png_out = "./plots/ml.feature_plot.png"
plot_model(base_ml, plot="feature", display_format="streamlit", save=True, filename = png_out )
```

**Describe alternatives you've considered**
NA

**Additional context**
I'm creating a streamlit app for ML and would like to export and save any and all plots to local directories and give them specific file names at the same time as displaying in streamlit.

**Comment by Yard1** [comment]
Should be doable
