### ISSUE TITLE
One-hot encoding should drop the last column and not alter binary columns

### ISSUE THREAD

**Issue by nateGeorge** [pycaret/pycaret#1162]
**Is your feature request related to a problem? Please describe.**
One-hot encoding of categorical columns keeps all categories for multi-category columns and alters binary categorical columns.

**Describe the solution you'd like**
For multi-category columns with n categories, we should only keep n-1 of the one-hot encoded features. The last OHE column can be inferred from the rest of them, and the columns together are perfectly collinear. For binary categorical columns, we should not OHE them but leave them as-is.

**Describe alternatives you've considered**
Perhaps we can custom-code our own preprocessor or preprocess the data before putting it into setup(), or we can set `preprocess=False`. But it would be better if it was automatic to drop the last OHE column and not alter binary columns.

**Additional context**
Example: the PhoneService column is binary but is auto-OHE'd by pycaret. The other categorical columns (Contract and PaymentMethod) are multi-class and are OHE'd by pycaret, but all columns are kept instead of dropping the last one.

Code to reproduce:
```python
import pandas as pd
from pycaret.classification import setup, compare_models, predict_model

df = pd.read_csv('https://pastebin.com/raw/uk7z1SVD', index_col='customerID')
automl = setup(data=df, target='Churn')
print(automl[3])
```

Original data:
![image](https://user-images.githubusercontent.com/10804060/114626075-6c2b9d80-9c70-11eb-9c61-a4d824a19856.png)

After pycaret auto-preprocessing:
![image](https://user-images.githubusercontent.com/10804060/114626246-a72dd100-9c70-11eb-9067-b9725cb4f6d7.png)

**Comment by Yard1** [comment]
We have made a conscious choice not to drop columns in OHE, though I would agree myself that an exception could be made for binary columns - perhaps that could be made into a configurable argument. Please consult https://inmachineswetrust.com/posts/drop-first-columns/ for explanation why we do not drop columns.

**Comment by nateGeorge** [comment]
I see, thanks for the link. It seems like a binary categorical column does not need to be OHE at all since it is already 0 and 1.
