### ISSUE TITLE
Wildcard imports in docs should be changed

### ISSUE THREAD

**Issue by nateGeorge** [pycaret/pycaret#1163]
[According to PEP8, the style guide for Python](https://www.python.org/dev/peps/pep-0008/#imports), "Wildcard imports (from <module> import *) should be avoided, as they make it unclear which names are present in the namespace, confusing both readers and many automated tools."

In the examples and other pages in the docs it seems wildcard imports are always used, like here on the [setup page](https://pycaret.org/setup/):

![image](https://user-images.githubusercontent.com/10804060/114639966-5a57f380-9c8c-11eb-8681-b09916452dea.png)

It should be an easy fix to change these. Instead of importing as

`from pycaret.classification import *`

we could do

`import pycaret.classification as pycc`

or

`from pycaret.classification import setup`

or something like that.

Importing as a wildcard could cause problems if there are overlapping function or class names between pycaret and other packages, or even within pycaret if both clustering and classification are used in the same scope or file, for example.

**Comment by ngupta23** [comment]
Hi @nateGeorge , Good suggestion. Would appreciate a PR to update this. Would you be able to submit this?

**Comment by nateGeorge** [comment]
I will see if I can get it done in the next few weeks.

By the way, I noticed MLBox does it this way too, which is perhaps why it's this way here.

**Comment by Yard1** [comment]
Yes, the idea was to make this more user-friendly for beginners, who may not be aware of which functions they will need. I think we should leave it as-is for now, considering that the wildcard import is designed to be used in a notebook for quick experiments, and not in production scripts. We could add a comment that we recommend using explicit imports for those.

**Comment by nateGeorge** [comment]
Hmm, I could see wildcard imports being useful for experts developing code but not for beginners as it would get confusing (e.g. where is this function coming from I see in this example?). Plus we don't want to create bad habits with beginners. Most other packages import with an alias instead of a wildcard, like `import pandas as pd` or `import numpy as np`. Pycaret classification could be `import pycaret.classification as pyc` for example, then everything could be used almost as easily as a wildcard import, like `pyc.setup()`.

I also noticed all the docs and examples have spaces between arguments, the equals signs, and the values for the arguments. Again, this is not best Python coding practice according to PEP8 and most people. One reason being searchability - if you want to search code for a parameter like `preprocess=True`, the lack of spaces helps differentiate it from a variable `preproces = True`. The first chapter of the book Clean Code in Python 2nd Ed by Mariano Anaya talks about this.  I'm not sure about spacings for arguments with type hints, I would have to look that up.

These things (wildcard import and spaces in arguments) are all over the docs and codebase and would probably take a while to fix. In fact, it would probably be easier to use some automation to update things, but that could cause unintented problems. I would guess it would take a few days to go through and update things to PEP8 standards in the docs.

**Comment by Yard1** [comment]
Wildcard imports are intended to be used mainly in jupyter notebooks by users importing the public API are are indeed the intended way to use PyCaret in a notebook.

**Comment by ngupta23** [comment]
> These things (wildcard import and spaces in arguments) are all over the docs and codebase and would probably take a while to fix. In fact, it would probably be easier to use some automation to update things, but that could cause unintented problems. I would guess it would take a few days to go through and update things to PEP8 standards in the docs.

We have started using `black` to autoformat the code (for any new additions). So it should improve over time.
