### ISSUE TITLE
Series.dtypes must be int, float or bool

### ISSUE THREAD

**Issue by DSrijon01** [pycaret/pycaret#1166]
I was going through the[ Feature Selection Documentation](https://pycaret.org/feature-importance/) in Pycaret.org 
Based on the given example I tried on my Jupyter notebook to run the chunk of code to see if it actually works or not. 
But it gave me a error  **Series.dtypes must be int, float or bool**  

- I was using the internal dataset of pycaret according to the example. 
- I tried it on my own preprocessed data followed by the same error. 
- I tried it on my google colab with the same error.
![2](https://user-images.githubusercontent.com/60281395/114721826-1d0e6700-9d5b-11eb-8822-3ff61ae98ab5.JPG)
![3](https://user-images.githubusercontent.com/60281395/114721838-1f70c100-9d5b-11eb-9643-488de602471e.JPG)
![1](https://user-images.githubusercontent.com/60281395/114721843-20095780-9d5b-11eb-8f86-faa0e3c2f820.JPG)

- I am using pycaret 2.3 on my venv. 

I am guessing this is a bug if not is there anyway to fix it if so please suggest how. I am attaching the ss for the error.

P.S. - I was given the same error while trying the [logistic regression for beginner tutorial](https://github.com/pycaret/pycaret/blob/master/tutorials/Regression%20Tutorial%20Level%20Beginner%20-%20REG101.ipynb) on my own dataset while trying to fit the **LIGHTGBM**, didn't add it as an issue because I was skeptic but I believe it is associated.

**Comment by Yard1** [comment]
This does look like a bug. Will take a look, thanks.
