### ISSUE TITLE
xgboost and lightgbm fail silently if preprocess=False with categorical columns

### ISSUE THREAD

**Issue by nateGeorge** [pycaret/pycaret#1168]
If we set preprocess=False with categorical columns (e.g. if we have label-encoded columns that are automatically detected as categorical), xgboost and lightgbm show 0 for all metrics (accuracy, AUC, etc) but are actually silently failing. For example:

```python
import pandas as pd
from pycaret.classification import setup, compare_models, predict_model, save_model, load_model

df = pd.read_csv('https://pastebin.com/raw/JQALwWB0', index_col='Patient number')

automl = setup(df, target='Diabetes', preprocess=False)

best = compare_models()
```

The results of `compare_models` are:

![image](https://user-images.githubusercontent.com/10804060/114759519-7fe00e00-9d1b-11eb-8987-238d8a05f13a.png)

However, if we specifically ask for xgboost and/or lightgbm, it shows the error:

```python
best = compare_models(include=['xgboost', 'lightgbm'])
```

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-c5e730c36453> in <module>()
----> 1 best = compare_models(include=['xgboost', 'lightgbm'])

13 frames
/usr/local/lib/python3.7/dist-packages/xgboost/data.py in _transform_pandas_df(data, enable_categorical, feature_names, feature_types, meta, meta_type)
    213                 categorical type is supplied, DMatrix parameter
    214                 `enable_categorical` must be set to `True`."""
--> 215         raise ValueError(msg + ', '.join(bad_fields))
    216 
    217     if feature_names is None and meta is None:

ValueError: DataFrame.dtypes for data must be int, float, bool or categorical.  When
                categorical type is supplied, DMatrix parameter
                `enable_categorical` must be set to `True`.Gender
```

We can get around this by specifying that the columns detected as categorical should be numeric, or setting `preprocess=True`:

`automl = setup(df, target='Diabetes', preprocess=False, numeric_features=['Gender', 'Height'])`

I think it would be good if the models did not  fail silently (showing 0s for all metrics) and some sort of warning was printed, or better yet, maybe if it handled categorical columns that could be numeric as numeric for xgboost and lightgbm.

**Comment by Yard1** [comment]
If preprocess is set to false, the user needs to make sure their data is in the correct format. What happens if you run `compare_models(errors="raise")`?

**Comment by nateGeorge** [comment]
Good point, perhaps it is expected behavior then, but it would still be nice to have something alert the user that xgboost and lightgbm failed. `errors='raise'` does not change anything.

**Comment by Yard1** [comment]
Yeah, I suppose that if all metrics return 0's it should treat it as if an exception was raised.
