### ISSUE TITLE
typeError: can only concatenate str (not "float") to str

### ISSUE THREAD

**Issue by eliwchen** [pycaret/pycaret#117]
I get the typeError, when I  import a  dataset.
The detail is below.

TypeError                                 Traceback (most recent call last)
<ipython-input-25-819900f202da> in <module>
----> 1 s= setup(data,target="price",categorical_features=cat_feat)

~\AppData\Roaming\Python\Python37\site-packages\pycaret\regression.py in setup(data, target, train_size, sampling, sample_estimator, categorical_features, categorical_imputation, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_interaction, feature_ratio, interaction_threshold, transform_target, transform_target_method, session_id, silent, profile)
    955                                           target_transformation = transform_target, #new
    956                                           target_transformation_method = transform_target_method_pass, #new
--> 957                                           random_state = seed)
    958 
    959     progress.value += 1

~\AppData\Roaming\Python\Python37\site-packages\pycaret\preprocess.py in Preprocess_Path_One(train_data, target_variable, ml_usecase, test_data, categorical_features, numerical_features, time_features, features_todrop, display_types, imputation_type, numeric_imputation_strategy, categorical_imputation_strategy, apply_zero_nearZero_variance, club_rare_levels, rara_level_threshold_percentage, apply_untrained_levels_treatment, untrained_levels_treatment_method, apply_ordinal_encoding, ordinal_columns_and_categories, apply_cardinality_reduction, cardinal_method, cardinal_features, apply_binning, features_to_binn, apply_grouping, group_name, features_to_group_ListofList, apply_polynomial_trigonometry_features, max_polynomial, trigonometry_calculations, top_poly_trig_features_to_select_percentage, scale_data, scaling_method, Power_transform_data, Power_transform_method, target_transformation, target_transformation_method, remove_outliers, outlier_contamination_percentage, outlier_methods, apply_feature_selection, feature_selection_top_features_percentage, remove_multicollinearity, maximum_correlation_between_features, remove_perfect_collinearity, apply_feature_interactions, feature_interactions_to_apply, feature_interactions_top_features_to_select_percentage, cluster_entire_data, range_of_clusters_to_try, apply_pca, pca_method, pca_variance_retained_or_number_of_components, random_state)
   2538     return(pipe.fit_transform(train_data),pipe.transform(test_data))
   2539   else:
-> 2540     return(pipe.fit_transform(train_data))
   2541 
   2542 

E:\ProgramData\Anaconda3\lib\site-packages\sklearn\pipeline.py in fit_transform(self, X, y, **fit_params)
    381         """
    382         last_step = self._final_estimator
--> 383         Xt, fit_params = self._fit(X, y, **fit_params)
    384         with _print_elapsed_time('Pipeline',
    385                                  self._log_message(len(self.steps) - 1)):

E:\ProgramData\Anaconda3\lib\site-packages\sklearn\pipeline.py in _fit(self, X, y, **fit_params)
    311                 message_clsname='Pipeline',
    312                 message=self._log_message(step_idx),
--> 313                 **fit_params_steps[name])
    314             # Replace the transformer of the step with the fitted
    315             # transformer. This is necessary when loading the transformer

E:\ProgramData\Anaconda3\lib\site-packages\joblib\memory.py in __call__(self, *args, **kwargs)
    353 
    354     def __call__(self, *args, **kwargs):
--> 355         return self.func(*args, **kwargs)
    356 
    357     def call_and_shelve(self, *args, **kwargs):

E:\ProgramData\Anaconda3\lib\site-packages\sklearn\pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    724     with _print_elapsed_time(message_clsname, message):
    725         if hasattr(transformer, 'fit_transform'):
--> 726             res = transformer.fit_transform(X, y, **fit_params)
    727         else:
    728             res = transformer.fit(X, y, **fit_params).transform(X)

~\AppData\Roaming\Python\Python37\site-packages\pycaret\preprocess.py in fit_transform(self, dataset, y)
   1957   def fit_transform(self,dataset,y=None):
   1958     data = dataset.copy()
-> 1959     corr = pd.DataFrame(np.corrcoef(data.drop(self.target,axis=1).T))
   1960     corr.columns = data.drop(self.target,axis=1).columns
   1961     corr.index = data.drop(self.target,axis=1).columns

<__array_function__ internals> in corrcoef(*args, **kwargs)

E:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\function_base.py in corrcoef(x, y, rowvar, bias, ddof)
   2524         warnings.warn('bias and ddof have no effect and are deprecated',
   2525                       DeprecationWarning, stacklevel=3)
-> 2526     c = cov(x, y, rowvar)
   2527     try:
   2528         d = diag(c)

<__array_function__ internals> in cov(*args, **kwargs)

E:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\function_base.py in cov(m, y, rowvar, bias, ddof, fweights, aweights)
   2429             w *= aweights
   2430 
-> 2431     avg, w_sum = average(X, axis=1, weights=w, returned=True)
   2432     w_sum = w_sum[0]
   2433 

<__array_function__ internals> in average(*args, **kwargs)

E:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\function_base.py in average(a, axis, weights, returned)
    391 
    392     if weights is None:
--> 393         avg = a.mean(axis)
    394         scl = avg.dtype.type(a.size/avg.size)
    395     else:

E:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py in _mean(a, axis, dtype, out, keepdims)
    149             is_float16_result = True
    150 
--> 151     ret = umr_sum(arr, axis, dtype, out, keepdims)
    152     if isinstance(ret, mu.ndarray):
    153         ret = um.true_divide(

TypeError: can only concatenate str (not "float") to str

**Comment by tianflame** [comment]
I encountered the same problem. I checked my dataset and found that the column name of my DataFrame is NOT "str" type but "int" type. So I give each column one name with string type and the problem is solved.

**Comment by pycaret** [comment]
Known bug. working on a fix for next release.

Tagging this as Bug.
