### ISSUE TITLE
Is it possible to provide a scikit-learn interface?

### ISSUE THREAD

**Issue by zhenlingcn** [pycaret/pycaret#1182]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Scikit-learn has been widely adopted as a command interface standard for many learning algorithms in the machine learning domain. Is it thus possible to provide a scikit-learn interface for pycaret to make it easier for users to understand how to use this package?

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Yard1** [comment]
It's hard to define what should happen after running `fit`. The next major release will bring an object based API so making sklearn wrappers will be very quick and simple.

**Comment by zhenlingcn** [comment]
@Yard1  Great. Thanks for your reply. I feel this is a reasonable solution.
