### ISSUE TITLE
binary_multiclass_score_func is a non-pickable object and causes error

### ISSUE THREAD

**Issue by aeriosk** [pycaret/pycaret#1188]
relating to https://github.com/pycaret/pycaret/commit/499ac03df22d7b5a73ed2b42fbcd8edba12207a5

pycaret.internal.metrics.binary_multiclass_score_func seems to be a non-pickable object. Error raised when running sklearn cross_validation in joblib parallel.

Code to replicate:

from pycaret.classification import setup,compare_models,models,create_model
from pycaret.datasets import get_data
dataset = get_data('credit')
data = dataset.sample(frac=0.95, random_state=786)
data_unseen = dataset.drop(data.index)
data.reset_index(inplace=True, drop=True)
data_unseen.reset_index(inplace=True, drop=True)
exp_clf101 = setup(data = data, target = 'default', session_id=123)
best_model = compare_models()
create_model('dt')

"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\backend\queues.py", line 153, in _feed
    obj_ = dumps(obj, reducers=reducers)
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\backend\reduction.py", line 271, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\backend\reduction.py", line 264, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
AttributeError: Can't pickle local object 'binary_multiclass_score_func.<locals>.wrapper'
"""

**Comment by Yard1** [comment]
Hey, I couldn't reproduce that on my machine. It also doesn't cause our Windows CI to fail. Can you try making a fresh virtual environment and installing `pycaret-nightly[full]` there?
