### ISSUE TITLE
How to use ensemble_model() to predict new dataset?

### ISSUE THREAD

**Issue by Yoshitama** [pycaret/pycaret#1189]
I use esemble_model() to predict on a new dataset but it returned an error: it seems like esemble_model() will return a list of models instead of a single model. But I can`t use a list to predict. How can I use ensemble_model correctly?

Here is the code:

tuned_top5 = [tune_model(i) for i in top5]
bagged_top5 = [ensemble_model(i) for i in tuned_top5]
...
predictions = predict_model(bagged_top5, data=feature2) 

error details:
AttributeError: 'list' object has no attribute 'predict'

**Comment by Yard1** [comment]
What version of PyCaret are you using?

**Comment by Yoshitama** [comment]
> What version of PyCaret are you using?

'2.2.0'

**Comment by Yard1** [comment]
You need to upgrade to 2.3 asap. 2.2 is not supported anymore. In 2.3, ensemble_model returns a single estimator.
