### ISSUE TITLE
missing models in compare_models() - Regression

### ISSUE THREAD

**Issue by pit9921** [pycaret/pycaret#1192]
Hi,

i have a version '2.3.0' and when i run `best = compare_models()` it gives the results with 18 algorithms.
When i run `models()` it shows me the list with 25 algorithms.

Why the command `compare_models()` does not include all available models?

![Screenshot 2021-04-22 203731](https://user-images.githubusercontent.com/77811022/115768484-a56bb800-a3aa-11eb-84dd-75f721b2bb8d.png)
![Screenshot 2021-04-22 203759](https://user-images.githubusercontent.com/77811022/115768487-a6044e80-a3aa-11eb-876f-07a6b22059b3.png)

**Comment by Yard1** [comment]
Models with turbo set to False are not run by default, as well as any non-sklearn models you may not have installed (xgboost, catboost). Furthermore, if a model raises an exception during fitting it will be ommited from the list. If you want to run all the models you have installed and ensure that none fail silently, do:
```compare_models(turbo=False, errors="raise")```

**Comment by pit9921** [comment]
ok, i see. Thank you for the reply.
I was interested in the XGBOOST, but got the following error:
XGBoostError: need to call fit or load_model beforehand

Is there way how to fix it?

**Comment by Yard1** [comment]
I haven't seen this issue before. Is this happening on colab? Can you share the notebook?
