### ISSUE TITLE
Anomaly Detection - Tune -> ValueError: Found input variables with inconsistent numbers of samples: [125, 0]

### ISSUE THREAD

**Issue by pit9921** [pycaret/pycaret#1194]
Hi,
i run the knn algorithm for anomaly detection:
![image](https://user-images.githubusercontent.com/77811022/115911875-f04f0380-a46e-11eb-990b-938ffa4dfe31.png)

I would like to tune it, but got the following error:
ValueError: Found input variables with inconsistent numbers of samples: [125, 0]

![image](https://user-images.githubusercontent.com/77811022/115911974-0bba0e80-a46f-11eb-83e9-5e2c3d257540.png)

ValueError                                Traceback (most recent call last)
<ipython-input-22-7b8092b36c10> in <module>
----> 1 tuned_knn = tune_model(model = 'knn', supervised_target = 'Refl')

~\Anaconda3\lib\site-packages\pycaret\anomaly.py in tune_model(model, supervised_target, supervised_type, supervised_estimator, method, optimize, custom_grid, fold, fit_kwargs, groups, round, verbose)
    818         groups=groups,
    819         round=round,
--> 820         verbose=verbose,
    821     )
    822 

~\Anaconda3\lib\site-packages\pycaret\internal\tabular.py in tune_model_unsupervised(model, supervised_target, supervised_type, supervised_estimator, optimize, custom_grid, fold, groups, ground_truth, method, fit_kwargs, round, verbose, display, **kwargs)
   3437             groups=groups,
   3438             round=round,
-> 3439             refit=False,
   3440         )
   3441         results[k] = pull(pop=True).loc["Mean"]

~\Anaconda3\lib\site-packages\pycaret\internal\tabular.py in create_model_supervised(estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, verbose, system, X_train_data, y_train_data, metrics, display, **kwargs)
   3120             n_jobs=n_jobs,
   3121             return_train_score=False,
-> 3122             error_score=0,
   3123         )
   3124         model_fit_end = time.time()

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

~\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py in cross_validate(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, return_train_score, return_estimator, error_score)
    231 
    232     """
--> 233     X, y, groups = indexable(X, y, groups)
    234 
    235     cv = check_cv(cv, y, classifier=is_classifier(estimator))

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in indexable(*iterables)
    290     """
    291     result = [_make_indexable(X) for X in iterables]
--> 292     check_consistent_length(*result)
    293     return result
    294 

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in check_consistent_length(*arrays)
    254     if len(uniques) > 1:
    255         raise ValueError("Found input variables with inconsistent numbers of"
--> 256                          " samples: %r" % [int(l) for l in lengths])
    257 
    258 

ValueError: Found input variables with inconsistent numbers of samples: [125, 0]

**Comment by Yard1** [comment]
Can you share the full code?

**Comment by Yard1** [comment]
@pycaret It's possible, I hadn't had the chance to check. @pit9921 Can you update your PyCaret version to 2.3.1 and try again?

**Comment by pit9921** [comment]
Hi, it works now, thank you.

**Comment by Yard1** [comment]
Can you share the data and the code?

**Comment by CJosh88** [comment]
I just encountered this issue on 2.3.1. I downgraded to 2.2 and the issue went away.

**Comment by pycaret** [comment]
@wkuopt FYA

**Comment by wkuopt** [comment]
Hi @CJosh88 , can you point us to the dataset so that we can reproduce the error?
