### ISSUE TITLE
Cross validation with/without shuffling rows

### ISSUE THREAD

**Issue by tmontana** [pycaret/pycaret#12]
Hi.  Great package.  Thank you.

Is there a way to select whether we want rows to be shuffled or not during CV?  What is the base behavior?  Not shuffling is critical for time series analysis.

Thanks

**Comment by tmontana** [comment]
Similar to setting KFold(..., shuffle=True) or KFold(..., shuffle=False) in SKlearn

**Comment by pycaret** [comment]
Hi,

shuffle in kfold is set to False by default. Currently there is no way to set shuffle to True. I will keep this open so can be included in feature list for future.

Thanks,
Moez

**Comment by pycaret** [comment]
### Feature now available in pycaret-nightly.

You can install **pycaret-nightly** using "pip install pycaret-nightly".

New parameter **folds_shuffle** is now added in setup. By default it is set to _False_. 

Can you please test this and close the issue if the enhancement addresses the original issue.

It will be shipped to PyCaret 2.0x in few weeks.

**Comment by tmontana** [comment]
It's great.  Thank you.
