### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by TonyTnT** [pycaret/pycaret#120]
when i loading my data it shows that
![image](https://user-images.githubusercontent.com/43055856/81505830-d6331880-9324-11ea-8a21-1b23aa65e379.png)

i think there is no problem in my data
![image](https://user-images.githubusercontent.com/43055856/81505848-f531aa80-9324-11ea-9511-ec64cb7831fa.png)

this is my data
![image](https://user-images.githubusercontent.com/43055856/81505818-bef42b00-9324-11ea-8f5d-3858d0c6e79a.png)

so could you tell me what went wrong?

**Comment by pycaret** [comment]
Hi. 

Can you try changing your col names so that they are string. I can see they are named as 1,2,3,4 etc. Can u force them into string? Adding a character in-front or after should do the trick for now. 

I am tagging this as a bug to be fixed in next release. 

Let me know how it goes?

**Comment by TonyTnT** [comment]
> Hi.
> 
> Can you try changing your col names so that they are string. I can see they are named as 1,2,3,4 etc. Can u force them into string? Adding a character in-front or after should do the trick for now.
> 
> I am tagging this as a bug to be fixed in next release.
> 
> Let me know how it goes?

i try to force the columns' name into string, it does work 
thanks for your help
