### ISSUE TITLE
predict_model output | Label & Score relationship

### ISSUE THREAD

**Issue by Asymptote** [pycaret/pycaret#1200]
Hi,
Please find attached the screenshot of predict_model output (on unseen data). 
How is it possible that a probability of 0.64 is a positive class and 0.98 is a negative class, while 0.5165 is a negative as well?
Am I missing something?

<img width="96" alt="Screen Shot 2021-04-26 at 4 31 50 AM" src="https://user-images.githubusercontent.com/307615/116014923-9144e680-a648-11eb-8f95-ae1692cdb5dd.png">

**Comment by Yard1** [comment]
The output is the probability of predicted class. If you want the same output format as sklearn would give you, you can do `predict_model(model, raw_score=True)`.

**Comment by Asymptote** [comment]
oh! okay 
So this probability is of the Label. This makes sense.
Thanks
