### ISSUE TITLE
Raise Error when setting fold_strategy='groupkfold' and call finalize_model

### ISSUE THREAD

**Issue by HalfMAI** [pycaret/pycaret#1201]
**Is your feature request related to a problem? Please describe.**
Raise Error when setting fold_strategy='groupkfold' and call finalize_model

**Describe alternatives you've considered**
After using fold_strategy="groupkfold", do I need to set any other value when using finalize_model?

**Additional context**
code:
> from pycaret.datasets import get_data
> boston = get_data('boston')
> from pycaret.regression import *
> exp_name = setup(data = boston,  target = 'medv', silent=True, 
>                  fold_strategy='groupkfold', fold_groups='chas', fold=2                     # testing on groupkfold
>                  )
> lr = create_model('lr')
> final_lr = finalize_model(lr)

result:

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-50-6fdb6afa05b5> in <module>()
>       4 exp_name = setup(data = boston,  target = 'medv', silent=True, fold_strategy='groupkfold', fold_groups='chas', fold=2)
>       5 lr = create_model('lr')
> ----> 6 final_lr = finalize_model(lr)
> 
> 6 frames
> /usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py in check_consistent_length(*arrays)
>     254     if len(uniques) > 1:
>     255         raise ValueError("Found input variables with inconsistent numbers of"
> --> 256                          " samples: %r" % [int(l) for l in lengths])
>     257 
>     258 
> 
> ValueError: Found input variables with inconsistent numbers of samples: [506, 506, 354]

**Comment by Yard1** [comment]
Thanks. Fixed in dev.
