### ISSUE TITLE
AttributeError: 'Make_Time_Features' object has no attribute 'list_of_features'

### ISSUE THREAD

**Issue by wgova** [pycaret/pycaret#1204]
I am running the anomaly detection module on preprocessed time series data. My data columns look like this:

hour	period	routingname	routingomname	networkname	responsecodelongdescription	obresponseduration
0	Downtime Route1		Route1.1	          	Network1         0 - No Error	                                2790

I am getting this error on Python 3.7 running from Jupyter Notebook. But I get that error with this setup:

from pycaret.anomaly import *
exp_anomaly = setup(data=data_sel,imputation_type='iterative')

**Comment by Yard1** [comment]
Ensure your scikit-learn version is 0.23.2 (not the latest 0.24).
