### ISSUE TITLE
How do you identify which coefficient map to which independent variables in Pycaret regression model?

### ISSUE THREAD

**Issue by ganesh3** [pycaret/pycaret#1206]
Hi,

We are using pycaret to run a regression model which will also give us feature importance of each of the co-efficients in the model. 

When we look at the tuned models feature importance (tuned_model.feature_importances_)
, it is essentially an array of values which we are not sure how it correlates to the independent variables. 

![WhatsApp Image 2021-04-30 at 16 54 19](https://user-images.githubusercontent.com/968180/116689337-98b41900-a9d5-11eb-8932-52d124332b37.jpeg)

How can we identify which independent variables are these co-efficients for?

Thanks
Ganesh

**Comment by pycaret** [comment]
@ganesh3 What you need is the name of columns in the same order that you can attach with this. To get the name of columns:

```
xtrain_cols = get_config('X_train').columns
```

Hope this helps. Please close the issue if this answers your question.

**Comment by ganesh3** [comment]
Thanks.
