### ISSUE TITLE
python util.py synchronize.py bug when tune_model('rf'), but tune_model('et') works

### ISSUE THREAD

**Issue by costaverde** [pycaret/pycaret#1208]
With anaconda3, python3.9, pycaret 2.1.2:
tune_model('rf') returns:   (but tune_model('et') works well)

Traceback (most recent call last):
  File "[..]/anaconda3/envs/py39/lib/python3.9/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "[..]/lib/python3.9/site-packages/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by pycaret** [comment]
@costaverde Unfortunately PyCaret and some of its dependencies yet do not work on Python 3.9. 

The error will go away if you degrade to Python 3.6, 3.7, or 3.8. 

![image](https://user-images.githubusercontent.com/58118658/116720369-17935c80-a9aa-11eb-9a18-fdd9c705e4bd.png)

Let me know how it goes.

**Comment by costaverde** [comment]
Yes, it goes well with Python 3.8. Thanks for the great work.
