### ISSUE TITLE
Processing forever when run in Google Colab. How do you auto-accept inferred datatypes?

### ISSUE THREAD

**Issue by sanzgiri** [pycaret/pycaret#121]
Even with a very small dataset, the setup step takes forever on Google Colab. Looks like it is waiting for response to this prompt "Following data types have been inferred automatically, if they are correct press enter to continue or type 'quit' otherwise." - but I am not able to provide any input within Google Colab = - pressing enter does nothing.  Is there a way to "auto accept" the inferred datatypes and continue?

**Comment by sanzgiri** [comment]
never mind, the prompt is there, just didn't notice

**Comment by pycaret** [comment]
@sanzgiri  Thanks.
