### ISSUE TITLE
pls add same functionality as R caret : 143  Quantile Regression Neural Network  qrnn

### ISSUE THREAD

**Issue by Sandy4321** [pycaret/pycaret#1212]
**Is your feature request related to a problem? Please describe.**
https://github.com/tobigithub/caret-machine-learning/wiki/caret-ml-overview

143 | Quantile Regression Neural Network | qrnn
-- | -- | --

**Describe the solution you'd like**
same functionality as R caret : 143  Quantile Regression Neural Network  qrnn

**Comment by ngupta23** [comment]
Hi @Sandy4321, If you do find this regressor in a Python package and if it is `scikit-learn` compatible (has `fit` and `predict` method amongst other things), you can add it as a custom model in `pycaret`. An example is shown below and you can find some details [here](https://pycaret.org/create-model/).

```python
# train custom model
from gplearn.genetic import SymbolicRegressor
symreg = SymbolicRegressor(generation = 50)
sc = create_model(symreg)
```

**Comment by Sandy4321** [comment]
it is the point there is no such functionality on scikit learn but only in R caret : 143 Quantile Regression Neural Network qrnn

**Comment by ngupta23** [comment]
Hi @Sandy4321 , The goal of `pycaret` is not to implement new models. That is left to base libraries like sklearn. Probably this question would be more appropriate in that repo. If it is implemented, we can look into incorporating it into `pycaret` in the future,
