### ISSUE TITLE
Support for fbprophet in Timeseries branch

### ISSUE THREAD

**Issue by akashg116414** [pycaret/pycaret#1214]
Support fbprophet for timeseries forecasting, add fbprophet in create_model, compare_model and tune_model for timeseries forecasting.

**Comment by ngupta23** [comment]
Hi @akashg116414 , Thanks for the feedback. Yes, this is planned already in the time-series module.

**Comment by ngupta23** [comment]
This is already available in the alpha release so closing this issue.
