### ISSUE TITLE
predict_model() index reset issue

### ISSUE THREAD

**Issue by usyed15181** [pycaret/pycaret#1218]
I am using Pycaret Classification and want to add ignored features back to predict_model()'s dataframe. I cannot do it because test set's index is reset after predict_model().

For e.g., Take this dataset,
index | Feature A | Feature B | Feature C | Target
0 | 10 | 20 | Adam | Yes
1 | 20 | 30 | Steve | No
2 | 100 | 100 | Shan | Yes

At setup() I ignore Feature C, so train/test dataset becomes
index | Feature A | Feature B | Target
0 | 10 | 20 |  Yes ---> Assume Train set
1 | 20 | 30 |  No ---> Assume Train set
**2 | 100 | 100 |  Yes --> Assume Test set**

After predict_model() for hold-out dataset, results are 
index | Feature A | Feature B | Target | Label | Score
**0 | 100 | 100 |  Yes | Yes | 0.6** --> index resets for test set

Now, I want to add back Feature C in results, so the expected outcome would be
index | Feature A | Feature B | Target | Label | Score | Feature C
**X | 100 | 100 |  Yes | Yes | 0.6 | Shan**

I cannot do that because original dataset index was 2 for this record but predict_model dataset index is 0.

Is there an alternate way i can add back ignored features from original dataset in predict_model()'s results for the correct record? 

Thanks

**Comment by moezali1** [comment]
This issue has been resolved now in PyCaret 3rc-4

```
pip install --pre pycaret
```

To retain the original index pass `index=True` in the `setup` function,
