### ISSUE TITLE
Limit the number of processors being used

### ISSUE THREAD

**Issue by amgfernandes** [pycaret/pycaret#1222]
I am aware that you can use n_jobs to decide if you are going to use all processors or a single one. 

But, is there a way to limit the number of processors that can be used (for example if you want to limit to 10)?

Thank you in advance,
Miguel

**Comment by Yard1** [comment]
`n_jobs=-1` means all available processors will be used, `n_jobs=10` means that 10 processors will be used.

**Comment by amgfernandes** [comment]
Thanks for the fast reply. I tried that but was not working. But I figure out why.
