### ISSUE TITLE
Model Tuning Value Error [BUG]

### ISSUE THREAD

**Issue by farmboycycles** [pycaret/pycaret#1225]
**Describe the bug**
Caveat: decent chance this is due to user error.
In attempting to tune a NLP model, I keep receiving a "ValueError: Found array with 0 sample(s) (shape=(0, 14)) while a minimum of 1 is required." during the 'evaluating the regressor' step and always with when evaluating the least number of topics regardless of what I set custom_grid to be. This occurs when I'm running the model against a multi-variate supervised_target (essentially a NPS rating). I have confirmed there are multiple entries for all 5 values on the NPS scale. 

**To Reproduce**
Key columns from the dataset are: 
       comment	                                                                rating
0	For the field "calling name to display" it wou...	3
1	On the Reports Dashboard, reports (like port-i...	4
2	'Tis much slower than the old one. :(	                3
3	Can we tighten up this area so the user does n...	2
4	The  portal is very user friendly 	                        4

```python
 setup(data=data, target='comment', 
                    custom_stopwords=['try','go','need','would','thank','say'],
                    session_id=42)
tune_model(model = 'lda', multi_core = True, custom_grid = [3,4,5,6,7,8,9,10], supervised_target='rating'
```

**Expected behavior**
Model to run? Is my sample size too small? Or does tuning not work with multi-variate classification? 

**Additional context**
I am able to run the tune_model code above without a supervised_target.
I am using a jupyter notebook.
Thanks for your guidance and thanks for pycaret, it's awesome!

**Versions**
pycaret version 2.3.0 

</details>

**Comment by farmboycycles** [comment]
Update, I consolidated rating values by mapping all to 0 or 1 to increase sample size for each rating/topic combination and reran tune_model with supervised_target = 'rating' and received the same error.

**Comment by pycaret** [comment]
@farmboycycles Can you share the dataset?

**Comment by farmboycycles** [comment]
Unfortunately I can't share all data due to privacy concerns. There is a sample included below. The dataset I was analyzing and receiving the error included ~650 comments and ratings. 
[sample_ratings.txt](https://github.com/pycaret/pycaret/files/6561106/sample_ratings.txt)

Thank you for taking a look at this and sorry I can't share more data. If I can help troubleshoot in other ways, please let me know.

**Comment by moezali1** [comment]
We are no more supporting the `nlp` and `arules` module in PyCaret due to lack to resources. Closing the issue now.
