### ISSUE TITLE
[DOC] List default hyperparameters searched with different algorithms when using tune_model()

### ISSUE THREAD

**Issue by nateGeorge** [pycaret/pycaret#1226]
#### Describe the issue linked to the documentation

When using the [`tune_model()` function](https://pycaret.readthedocs.io/en/latest/api/classification.html?highlight=tune_model#pycaret.classification.tune_model), it looks like it uses sklearn gridsearch by default and it looks like default hyperparameters are [here](https://github.com/pycaret/pycaret/blob/c04bf2ccf34c6087e5b88f87623563acba0e95b9/pycaret/containers/models/classification.py#L843) (for adaboost, for example). It seems like this would be good to have in the docs somewhere, or somehow returned as part of the tune_model or a related function (also see this related feature request: #1227 ). Otherwise, we don't know what hyperparameters are being searched without looking in the source code.

#### Suggest a potential alternative/fix

It seems like there should be a page in the docs listing the default hyperparameters that are searched, or at least a link to the place in the codebase for the different algorithms. Or an explanation of what it is searching when we use `tune_model()`.

**Comment by Yard1** [comment]
I would just like to clarify that by default, `tune_model` runs a random grid search. There are other search algorithms and libraries available.

**Comment by pycaret** [comment]
@nateGeorge You can access the default hyperparameters grids like this. See below the example I have created on the `juice` dataset.

```
# load dataset
from pycaret.datasets import get_data
data = get_data('juice')

# init setup
from pycaret.classification import *
s = setup(data, target = 'Purchase', silent = True)

# access hyperparameters of dt
models(internal=True).loc['dt']['Tune Grid']
```
This returns the following:
![image](https://user-images.githubusercontent.com/58118658/117289966-3dea4980-ae3b-11eb-813f-7fe69f719661.png)

I think it has to be made more prominent in the documentation somewhere. Thanks for bringing out.

**Comment by nateGeorge** [comment]
Ah thanks, yes, it looks like the return_tuner can do it too. Honestly I think it would be worth putting both this method and the return_tuner in the docs/example of tune_model. I should've looked through the hyperparameters more carefully.
