### ISSUE TITLE
Access CV scores and hyperparameter combos after tuning

### ISSUE THREAD

**Issue by nateGeorge** [pycaret/pycaret#1227]
**Description**
After using `tune_model()` I have no idea what the hyperparameters were that were searched if I didn't provide them. I also have no idea what the cross-validation (CV) scores were for the different hyperparameter combos. It seems like another function would be in order to print out the different hyperparameters and scores.

**Describe the solution you'd like**
A function to print out the hyperparameters and scores from tune_model(). It seems like tune_model may need to return a different object than the optimized model, or otherwise return that information. I'm not sure how to do this without breaking backwards compatability.

**Describe alternatives you've considered**
Use the optimizer packages directly. You can also see the default hyperparameters searched in the code (for example, [here](https://github.com/pycaret/pycaret/blob/c04bf2ccf34c6087e5b88f87623563acba0e95b9/pycaret/containers/models/classification.py#L843) for adaboost). But you still don't know the CV scores, so it's hard to evaluate how meaningful the optimized model is.

**Comment by Yard1** [comment]
You can access the underlying tuner object by setting `return_tuner=True`. The function will then return a tuple of the fitted model and the fitted underlying tuner object (different depending on search library chosen):
```python
tuned_model, tuner = tune_model(model)
```

**Comment by nateGeorge** [comment]
Thanks, I overlooked that parameter.
