### ISSUE TITLE
[DOC] Add reference to original caret

### ISSUE THREAD

**Issue by georgeblck** [pycaret/pycaret#1228]
Thank you for this package. It is nice to see a well maintained caret-Package in python.  
However, I find it very surprising that the [original caret](https://github.com/topepo/caret/) is not mentioned once in this repo or the docs --- shout-out to @rhjp and the indeed appropriate PR #713 to change this. Usually the data science community is very keen on giving credit where credit is due. 

This part of the README

> The design and simplicity of PyCaret is inspired by the emerging role of citizen data scientists, a term first used by Gartner.

is simply misleading without at least a mention of the eponymous and popular R-package that has been around since at least 2007.

**Comment by rhjp** [comment]
Thanks for reminding my @georgeblck, that PR has been sitting there for 7 months. Fixed some new README conflicts that arose and now ready for review and merging. I'm not worried about how caret is mentioned, but you're right; _give credit where credit is due_.

**Comment by pycaret** [comment]
@georgeblck Just added. Closing this issue now.

**Comment by georgeblck** [comment]
Thank you!

**Comment by eitsupi** [comment]
Hi, unfortunately, this description seems to have been lost during a major rewrite of the README. a7805fd417092c5979720eed422b01fd883f2510
