### ISSUE TITLE
tune_model on train data?

### ISSUE THREAD

**Issue by pyaf** [pycaret/pycaret#1244]
I'm looking into the tune_model functionality of pycaret, and it can be seen that the `model_grid` is fitted on training data (`X_train`) [Reference](https://github.com/pycaret/pycaret/blob/4941df82919c2834b69e498ae5f322e826a79ad2/pycaret/internal/tabular.py#L4471)

Could you please confirm if I am correct here? If yes, then shouldn't we fit it on internal validation splits or maybe the test data provided in the pycaret setup?

CC @pranaymodukuru

**Comment by Yard1** [comment]
Cross Validation is performed internally by the tuners.

**Comment by pyaf** [comment]
Okay, thanks! @Yard1
