### ISSUE TITLE
[BUG] Fix_imbalance doesn't seem to be working

### ISSUE THREAD

**Issue by set92** [pycaret/pycaret#1261]
**Describe the bug**
I tried to use the library to process a dataset of telco clients, but it didn't correct the imbalance dataset. I used https://www.kaggle.com/blastchar/telco-customer-churn as dataset to check if it was because of my dataset.

**To Reproduce**
```python
from pycaret.classification import *
from imblearn.under_sampling import RandomUnderSampler
import pandas as pd

df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
clf1 = setup(
    data=df,
    use_gpu=True,
    target="Churn",
    train_size=0.8,
    preprocess=True,
    fix_imbalance = True,
    fix_imbalance_method = RandomUnderSampler(), #Also tried with SMOTE but is the same
    remove_perfect_collinearity=True,
    handle_unknown_categorical=True,
    remove_multicollinearity=True,
    silent=True,
)

print(df['Churn'].value_counts(normalize=True)) #No     0.73463  ----  Yes    0.26537
print(get_config('y_train').value_counts(normalize=True)) #0    0.732517  ----   1    0.267483

print(df['Churn'].shape[0]) #7043
print(get_config('y_train').shape[0]) #5634

```
Returns the following value_counts before running pycaret
```
No     0.73463
Yes    0.26537
```
and the next value_counts after running it:
```
0    0.732517
1    0.267483
```

And in the real dataset, which is another dataset of telco but bigger, happened the same. It went from 
```
1.0    0.875741
0.0    0.124259
``` 
to 
```
1    0.875497
0    0.124503
```

**Expected behavior**
If I use RandomUnderSampler() without pycaret and with my real dataset I go from 
```
1.0    0.875741
0.0    0.124259
```
to 
```
1.0    0.555552
0.0    0.444448
```
 and in the one of Kaggle I go from 
```
Yes    0.26537
No     0.73463
```
to 
```
Yes    0.5
No     0.5
```
which looks more normal to me. Because it needs to balance and have around 0.5 each class no? or I'm doing something wrong / not understanding something?

**Versions**
<details>
'2.3.1'
</details>

**Comment by Yard1** [comment]
The imbalance fixing step is applied for each CV fold and during model fitting and thus the changes introduced by it will not be visible in the dataframes obtained through `get_config`.
