### ISSUE TITLE
[BUG] ValueError: Estimator catboost not available. Please see docstring for list of available estimators.

### ISSUE THREAD

**Issue by gm039** [pycaret/pycaret#1262]
Hi,

I see an issue in pycaret 2.3.1. It throws errors in running catboost and xgboost model.

ValueError: Estimator catboost not available. Please see docstring for list of available estimators.

![image](https://user-images.githubusercontent.com/50217085/118721186-8bca5e80-b7f8-11eb-9bec-e1419d728d8a.png)

**Comment by Yard1** [comment]
CatBoost and XGBoost are not mandatory dependences. You need to either install `catboost` and `xgboost` packages separately or install PyCaret with all of its optional dependencies with `"pycaret[full]"`.

**Comment by gm039** [comment]
Thanks.
