### ISSUE TITLE
Compare Models, Shuffle=True Error

### ISSUE THREAD

**Issue by hamzag95** [pycaret/pycaret#1266]
I am trying to run the compare_models() function but I get an error regarding Kfold cross validation,

This error happens when I run the compare_models() function. 
 "setting a random_state has no effect since shuffle is False. You should leave random_state to its default (None) or set shuffle=True"

Below is my full PyCaret code, where df is a pandas data frame with missing values filled in. Dataset is housing prices dataset from Kaggle:

reg1 = setup(data=df, target='SalePrice', data_split_shuffle=True)
best_model = compare_models()

**Comment by Yard1** [comment]
This should have been fixed in the latest PyCaret version. Please run `pip install -U pycaret` and try again.

**Comment by hamzag95** [comment]
@Yard1 what version should I be running? Im running 2.1.2 right now

**Comment by Yard1** [comment]
2.1.3

**Comment by hamzag95** [comment]
Thanks!
