### ISSUE TITLE
Can you add a feature to export/convert PyCaret model to ONNX format?  This would enable deploying models created with PyCaret to any platform.

### ISSUE THREAD

**Issue by tsereno** [pycaret/pycaret#1267]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**
A clear and concise description of what you want to happen, ideally taking into consideration the existing toolbox design, classes and methods. 

**Describe alternatives you've considered**

**Additional context**

**Comment by ngupta23** [comment]
@moezali1 wrote [an article](https://towardsdatascience.com/deploy-pycaret-models-on-edge-devices-with-onnx-runtime-c6d060a2e1a6) on it a few days back. Please refer to it to see how it can be done.
