### ISSUE TITLE
Manually updating Hyperparameters, after tune_model() call

### ISSUE THREAD

**Issue by AdityaKj** [pycaret/pycaret#127]
After running the tune_model - function e.g. for tune_model('xgboost') , I would like to update some of the hyper-parameters ex. scale_pos_weight (imbalanced data) (or any other params) from the output model of tune_model() function.
Suggest a way to do this so that I could finalize the updated model please.

**Comment by pycaret** [comment]
@AdityaKj In current version this is not possible. In our next release this functionality is added. You will be able to simply pass the parameter under create_model. I will keep this issue open until release.
Tagging this as enhancement.

Thanks for reaching out.

**Comment by AdityaKj** [comment]
> @AdityaKj In current version this is not possible. In our next release this functionality is added. You will be able to simply pass the parameter under create_model. I will keep this issue open until release.
> Tagging this as enhancement.
> 
> Thanks for reaching out.
 
Awesome !! Thank you so much for the package... Awaiting the next release ....
