### ISSUE TITLE
Import pycaret took a long time

### ISSUE THREAD

**Issue by bimhud** [pycaret/pycaret#1270]
With the latest version, importing pycaret took along time to finish due to its plotly dependency which inturn took a long time when you're running in an isolated environment without connecting to the internet.

Not sure this is the issue of pycaret or there is away out to speed up this process.

Tested on Pycaret 2.3.1, python 3.6

**Comment by bimhud** [comment]
**Run this command:**

time python -c "from pycaret.classification import *"

**Obtain 4m to complete the import**

real	4m19.667s
user	0m6.285s
sys	4m7.291s

**Comment by bimhud** [comment]
time python -c "import plotly.express"

real	3m5.489s
user	0m3.293s
sys	2m56.742s

**Comment by pycaret** [comment]
@Yard1 Any suggestions?

**Comment by Yard1** [comment]
This is a plotly issue, not PyCaret. We can't make plotly an optional dependency, though, so I am not sure what we can do here.
