### ISSUE TITLE
[BUG]ValueError: Setting a random_state has no effect since shuffle is False. You should leave random_state to its default (None), or set shuffle=True.

### ISSUE THREAD

**Issue by dkinneyBU** [pycaret/pycaret#1278]
**Describe the bug**

**To Reproduce**

```python
# Import packages
import pandas as pd
from pycaret.classification import *
df = pd.read_csv('./data/data.csv')
```

**Expected behavior**

**Additional context**
 1 clf1 = setup(df, target = 'diagnosis')

D:\Users\David\anaconda3\lib\site-packages\pycaret\classification.py in setup(data, target, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs)
    578         log_plots = ["auc", "confusion_matrix", "feature"]
    579 
--> 580     return pycaret.internal.tabular.setup(
    581         ml_usecase="classification",
    582         available_plots=available_plots,

D:\Users\David\anaconda3\lib\site-packages\pycaret\internal\tabular.py in setup(data, target, ml_usecase, available_plots, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, transform_target, transform_target_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs, display)
   1215         )
   1216     elif fold_strategy == "stratifiedkfold":
-> 1217         fold_generator = StratifiedKFold(
   1218             fold_param, random_state=seed, shuffle=fold_shuffle_param
   1219         )

D:\Users\David\anaconda3\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     61             extra_args = len(args) - len(all_args)
     62             if extra_args <= 0:
---> 63                 return f(*args, **kwargs)
     64 
     65             # extra_args > 0

D:\Users\David\anaconda3\lib\site-packages\sklearn\model_selection\_split.py in __init__(self, n_splits, shuffle, random_state)
    634     @_deprecate_positional_args
    635     def __init__(self, n_splits=5, *, shuffle=False, random_state=None):
--> 636         super().__init__(n_splits=n_splits, shuffle=shuffle,
    637                          random_state=random_state)
    638 

D:\Users\David\anaconda3\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     61             extra_args = len(args) - len(all_args)
     62             if extra_args <= 0:
---> 63                 return f(*args, **kwargs)
     64 
     65             # extra_args > 0

D:\Users\David\anaconda3\lib\site-packages\sklearn\model_selection\_split.py in __init__(self, n_splits, shuffle, random_state)
    288 
    289         if not shuffle and random_state is not None:  # None is the default
--> 290             raise ValueError(
    291                 'Setting a random_state has no effect since shuffle is '
    292                 'False. You should leave '

ValueError: Setting a random_state has no effect since shuffle is False. You should leave random_state to its default (None), or set shuffle=True.
-->

**Versions**
<details>

2.2.0

**Comment by Yard1** [comment]
Please update to the latest (2.3.1) version of PyCaret. This bug has been fixed in it. You can do that with `pip install -U pycaret`.

**Comment by Yard1** [comment]
If the issue persists after updating, please reopen the issue.

**Comment by dkinneyBU** [comment]
That worked. Apparently conda did not install the latest version, even though I specified update. And then my peers wonder why I loathe anaconda...

thank you...
