### ISSUE TITLE
[BUG] Distribute Pycaret on Spark (databricks)

### ISSUE THREAD

**Issue by noamanemobidata** [pycaret/pycaret#1281]
**Distribute Pycaret on Spark (databricks)**

Hi! 
I try to run pycaret models  for each group in a spark dataframe using applyInPandas with an pandas UDF but I got this error : 
`ERROR:logs:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.`

```python

schema= StructType([
  StructField('ds', DateType()),
  StructField('yhat', IntegerType()),
  StructField('ID', StringType())
  
])

def pycat(df: pd.DataFrame) -> pd.DataFrame:

  s = setup(data = train, test_data = test, target = 'qte', fold_strategy = 'timeseries', numeric_features = ['Year', 'Series'], fold = 3, transform_target = True, session_id = 123)
 ...
  return predictions_df


(sparkDF
           .repartition('ID')
           .groupBy('ID')
           .applyInPandas(pycat, schema=schema)
          )
```

**Comment by ngupta23** [comment]
Can you try adding silent=True in the setup?

**Comment by noamanemobidata** [comment]
yes the function works well with a Pandas DataFrame. 
Not working  with `silent=True` in spark cluster... maybe the problem is the fact that we can't run multiple `setup`  functions simultaneously in single worker ?

**Comment by Yard1** [comment]
That could be the reason. The next major update should help with that.

**Comment by ngupta23** [comment]
You could try to run with number of shuffle partitions = number of executors and try to launch only 1 core per executor. Is that possible with your setup? I am not 100% sure but that could ensure that only 1 setup per executor at a time.

**Comment by pycaret** [comment]
@noamanemobidata Can you try explicitly passing `n_jobs = 1`. I am hopeful it might fix the issue for you.

**Comment by noamanemobidata** [comment]
Works with `n_jobs = 1`  
Thank you
