### ISSUE TITLE
Add save_path to plot_model

### ISSUE THREAD

**Issue by pyaf** [pycaret/pycaret#1288]
**Describe the Problem**

`plot_model` currently has the `save` argument which can be used to save the plots. It does not provide the functionality to decide where to save the plot and with what name. Right now it saves the plot with predefined names in the current working directory. 

**Describe the solution you'd like**

We can have another argument `save_path` which is used whenever the `save` argument is true, we can use this path to save the plots. If `save` is True but `save_path` is not provided, we can go with what we currently have.

**Comment by Yard1** [comment]
It's a good suggestion, and has been asked for before. We'll make it so that `save` will take a string/path as an argument in the next major release. Thanks.

**Comment by rg666** [comment]
May I pick up this 'good first issue'?

**Comment by pycaret** [comment]
@rg666 Sure please go a head.

**Comment by bhanuteja2001** [comment]
Hi, I would like to work on this as well.

**Comment by bhanuteja2001** [comment]
Is this still opened?
I would like to work on it as well.
