### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by lcast5576** [pycaret/pycaret#1293]
**Describe the bug**

setup() is keep getting memoryerror with data shape (276759, 893)

**To Reproduce**

```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

Computer memory is 16gb 
pycaret '2.2.0'
Can't share data set. 
**Versions**
<details>

</details>

**Comment by Yard1** [comment]
Please try updating PyCaret to the latest release (2.3.1). If you are using feature interactions or polynomial, trigonometric features, turn them off.
