### ISSUE TITLE
[BUG] RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by reza1615** [pycaret/pycaret#1299]
**Describe the bug**
after creating clustering model with brich on DataBricks AZURE. 
the model is created correctly but when i want to plot the model shows the below error

training data.shape is (50000, 100) 
![image](https://user-images.githubusercontent.com/2202483/119720232-b7bc9400-be37-11eb-8197-5a3098f521ba.png)

**To Reproduce**

```python
birch = create_model('birch',num_clusters=5)
plot_model(birch)
```

 
pycaret.__version__ :  '2.3.1'

**Comment by pycaret** [comment]
@reza1615 Would you like to work on this issue?

**Comment by ngupta23** [comment]
Can you try changing the variable name from `birch` to something else. Not sure it will work, but worth a try.
