### ISSUE TITLE
Colab link for Binary Classification Tutorial sends you to NLP Tutorial

### ISSUE THREAD

**Issue by salilathalye** [pycaret/pycaret#13]
On the Binary Classification Tutorial (CLF102) – Level Intermediate page, click on the Colab icon. You get sent to the NLP Tutorial notebook.

**Comment by pycaret** [comment]
Thanks for pointing that out. Will fix today. Much appreciated.

**Comment by pycaret** [comment]
Issue Fixed. Thank you.
