### ISSUE TITLE
How to profile the data after setting up?

### ISSUE THREAD

**Issue by dioncst** [pycaret/pycaret#130]
Hi，
Thank you very much for this wonderful program. I have a little question here. 

I'm wondering how can I get the profiling report of data after setting up? I would like to see how the data were changed. Please take your tutorial as an example.(http://www.pycaret.org/tutorials/html/CLF102.html#6.0-Comparing-All-Models)

Thanks!

**Comment by AdityaKj** [comment]
in the setup() please add profile=True, this would give pandas_profiling report

**Comment by dioncst** [comment]
Thanks，I’ve tried this, but seems it gave profilings of original data.



On 05/13/2020 15:12, AJ wrote:

in the setup() please add profile=True, this would give pandas_profiling report

**Comment by AdityaKj** [comment]
> Thanks，I’ve tried this, but seems it gave profilings of original data. On 05/13/2020 15:12, AJ wrote: in the setup() please add profile=True, this would give pandas_profiling report 

Okay, if your need is to view the dataset post setup, meaning the dataset after applicable transformations, then you could do ..
exp1 = setup(...)
exp1[0] --> this gives you the transformed pandas-dataframe and further if you need profiling of this dataframe you could run setup with the above dataframe object. Hope this helps..

**Comment by dioncst** [comment]
Thank you for your quick reply. This works for me!

**Comment by rahulsahai78** [comment]
Hi Aditya,
can you please explain the step to look up the transformed train dataset in pycaret?
thanks,
