### ISSUE TITLE
One hot encoded column by pycaret gets dropped in get_config

### ISSUE THREAD

**Issue by sagarnildass** [pycaret/pycaret#1303]
When I am running pycaret on titanic data, after running setup, I am pulling X_train, X_test etc by get_config method. But when I am printing X_train, I am seeing that for the 'Sex' column, only 1 one-hot-encoded column (Sex_male) is present while the other is dropped. But for other one-hot encoded columns, this is not the case and I am seeing that all the columns are correctly present. I don't want the "Sex_female" column to get dropped. How to achieve this?

**To Reproduce**

```python
from pycaret.classification import *
clf1 = setup(df, 
             target = label_column, 
             session_id=123,
             ignore_features=ignore_features,
             log_experiment=False,
             use_gpu=True)

X_train = get_config('X_train')
y_train = get_config('y_train')
X_test = get_config('X_test')
y_test = get_config('y_test')
```

**Expected behavior**

All one-hot encoded columns should be present even if it's a binary variable.

**Additional context**

**Versions**
<details>

</details>

**Comment by Yard1** [comment]
By default we drop columns that are perfectly colinear with each another. You can disable that behavior with `remove_perfect_collinearity=False` in `setup`. Let me know if that helps.

**Comment by sagarnildass** [comment]
Got it! Works perfectly now. You may want to change your documentation though. Over there, it says that the default value is False.

https://pycaret.org/classification/#get-config
