### ISSUE TITLE
[BUG] pull() with tune_model and choose_better=True may not be working as expected. 

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#1307]
**Describe the bug**
pull() with tune_model and choose_better=True may not be working as expected. It still pulls the worse metrics (not the better metrics). Not sure if this is specific to time_series but that is where the bug was discovered.

**To Reproduce (from `time_series` branch)**

```python
from pycaret.internal.pycaret_experiment import TimeSeriesExperiment

fh = np.arange(1, 13)
fold = 3

exp = TimeSeriesExperiment()
exp.setup(data=y, fh=fh, fold=fold, fold_strategy="expanding", session_id=42)

model = exp.create_model("naive")
metrics_create = exp.pull()

# Custom Grid
custom_grid = {"strategy": ["mean"]}
tuned_model1 = exp.tune_model(model, custom_grid=custom_grid)
metrics_tune1 = exp.pull()

# Choose Better
tuned_model2 = exp.tune_model(model, custom_grid=custom_grid, choose_better=True)
metrics_tune2 = exp.pull()

print(f"Create Model:(untuned) {model}")
print(f"Tuned Model custom_grid: {tuned_model1}")
print(f"Tuned Model choose_better = True: {tuned_model2}")

print(f"Metrics Create: {metrics_create}")
print(f"Metrics Tune 1: {metrics_tune1}")
print(f"Metrics Tune 2: {metrics_tune2}")
```

**Expected behavior**
`metrics_tune2` should have been same as `metrics_create`, but come out to be same as `metrics_tune1` even though the final model for `tuned_model2` is overridden to be the same as the original estimator (`model`)

**Versions**
Development version on `time_series` branch

**Comment by Yard1** [comment]
Will take a look, this is most likely something that will be an issue in all modules.
