### ISSUE TITLE
[BUG] Fail to import "from pycaret.regression import *"

### ISSUE THREAD

**Issue by hokmingkwan** [pycaret/pycaret#1308]
**Describe the bug**

After !pip install pycaret and try to import from pycaret.regression import * at Kaggle environment, I got below error msg:

"ImportError: cannot import name '_raise_dep_warning_if_not_pytest' from 'sklearn.utils.deprecation' (/opt/conda/lib/python3.7/site-packages/sklearn/utils/deprecation.py)"

**To Reproduce**

```python
!pip install pycaret
from pycaret.regression import *
```

**Expected behavior**

"ImportError: cannot import name '_raise_dep_warning_if_not_pytest' from 'sklearn.utils.deprecation' (/opt/conda/lib/python3.7/site-packages/sklearn/utils/deprecation.py)"

**Versions**

'2.3.1'

</details>

**Comment by Yard1** [comment]
Can you try
```
!pip uninstall scikit-learn
!pip install -U pycaret
```
Instead?

**Comment by hokmingkwan** [comment]
> Can you try
> 
> ```
> !pip uninstall scikit-learn
> !pip install -U pycaret
> ```
> 
> Instead?

It works now, thanks!
