### ISSUE TITLE
NLP - Provide Texts and dictionary - Stops on 20% progress

### ISSUE THREAD

**Issue by ManuelBanza** [pycaret/pycaret#131]
Hi,

I am using a dataset with 600k rows and when I use the option tune_model it just stucks, I waited 24 hours and still does not pass the 20/25%.

Is it possible to get the Texts and dicitionary so I can see the Coherence score on my own? I ca see in your code that it seems to be the text and id2word:

```
for i in master:
            progress.value += 1 
            monitor.iloc[2,1:] = 'Evaluating Coherence With ' + str(param_grid[counter]) + ' Topics'
            update_display(monitor, display_id = 'monitor')

            model = CoherenceModel(model=i, texts=text, dictionary=id2word, coherence='c_v')
            model_coherence = model.get_coherence()
            coherence.append(model_coherence)
            metric.append('Coherence')
            counter += 1
```
However I get the error : 
NameError: name 'text' is not defined

Also is it possible to limit the num_of_topics in the tune_model? I can see that it goes to thousands, but I do not need that, I would like to limit to 20 for example. I did not find this in the documentation

Thanks.
Awesome library!

**Comment by pycaret** [comment]
@ManuelBanza Thanks for reporting. text, corpus, and i2word is returned in setup variable. If you check the variable in which setup is stored you will find them. I should have made that clear in documentation. I will include it soon.

Another good point re # of topics in tune_model. If you would like feel free to submit a PR to accomodate for that change. Ideally you will include a parameter in tune_model named 'custom_grid' to handle customized grid that takes list which contains num of topics for each run. 

Feel free to submit a PR on dev-1.0.1 branch. I am marking this as enhancement anyways. Incase you are not able to do it, I will keep it in the list of enhancement for future.

Thank you again for reporting.

**Comment by ManuelBanza** [comment]
@pycaret thank you for the help. However I am having the same issue. For example in the setup variable you have this:

```
"""
    STEP 8 - CREATING CORPUS AND DICTIONARY
    """  
    
    monitor.iloc[1,1:] = 'Compiling Corpus'
    monitor.iloc[2,1:] = 'Step 9 of '+ str(total_steps)
    update_display(monitor, display_id = 'monitor')
    
    #creating dictionary
    id2word = corpora.Dictionary(text)
```

So the dictionary is id2word, however when I try to see the coherence score:
```
# Compute Coherence Score
coherence_model_lda = CoherenceModel(model=lda, texts=text, dictionary=id2word, coherence='c_v')
coherence_lda = coherence_model_lda.get_coherence()
print('\nCoherence Score: ', coherence_lda)
```
I get the error:
NameError: name 'id2word' is not defined
Thanks again for the help

**Comment by ManuelBanza** [comment]
Hi @pycaret thanks for the help. However I know get this error:
KeyError: 832

And get it when I tried to calculate myself the coherence score and also when I want to se the optical model. Ex:

1- 
````
# Compute Coherence Score
coherence_model_lda = CoherenceModel(model=lda, texts=text, dictionary=id2word, coherence='c_v')
coherence_lda = coherence_model_lda.get_coherence()
print(coherence_lda)
````
KeyError: 832

2-
````
model_list, coherence_values = compute_coherence_values(dictionary=id2word, corpus=corpus, texts=text, start=2, limit=40, step=6)
# Show graph
import matplotlib.pyplot as plt
limit=40; start=2; step=6;
x = range(start, limit, step)
plt.plot(x, coherence_values)
plt.xlabel("Num Topics")
plt.ylabel("Coherence score")
plt.legend(("coherence_values"), loc='best')
plt.show()
````
Thanks!

**Comment by pycaret** [comment]
@ManuelBanza Can you re-test this using pycaret `2.1.2`

**Comment by moezali1** [comment]
We are no more supporting the `nlp` and `arules` module in PyCaret due to lack to resources. Closing the issue now.
