### ISSUE TITLE
[BUG] AttributeError: 'Make_Time_Features' object has no attribute 'list_of_features'

### ISSUE THREAD

**Issue by soerendip** [pycaret/pycaret#1314]
Using the dataset from kaggle I get "Tabular Playground Series - May 2021" with

```
import pycaret

from pycaret.classification import *

df = pd.read_csv('/kaggle/input/tabular-playground-series-may-2021/train.csv', index_col=0)

exp_clf = setup(df, target = 'target', imputation_type='iterative')

```

> AttributeError: 'Make_Time_Features' object has no attribute 'list_of_features'

**Comment by soerendip** [comment]
This is an incompatibility with the latest `scikit-learn` library. 
using `scikit-learn==0.23.2` works.

**Comment by Yard1** [comment]
Yes, PyCaret is not yet compatible with sklearn 0.24. It will be rectified in the next major release.

**Comment by sandorkonya** [comment]
> Yes, PyCaret is not yet compatible with sklearn 0.24. It will be rectified in the next major release.

I still have this issue in 2022 :(
In custom env in conda.

scikit-learn              1.0.2            py39he931e04_0    conda-forge
scipy                     1.8.0            py39hc0c34ad_1    conda-forge
pycaret                   2.2.3              pyhd3deb0d_0    conda-forge

first AttributeError: 'SimpleImputer' object has no attribute '_validate_data'  
and if i use  imputation_type='iterative', 
AttributeError: 'Make_Time_Features' object has no attribute 'list_of_features'

**Comment by shshnkg** [comment]
> > Yes, PyCaret is not yet compatible with sklearn 0.24. It will be rectified in the next major release.
> 
> I still have this issue in 2022 :( In custom env in conda.
> 
> scikit-learn 1.0.2 py39he931e04_0 conda-forge scipy 1.8.0 py39hc0c34ad_1 conda-forge pycaret 2.2.3 pyhd3deb0d_0 conda-forge
> 
> first AttributeError: 'SimpleImputer' object has no attribute '_validate_data' and if i use imputation_type='iterative', AttributeError: 'Make_Time_Features' object has no attribute 'list_of_features'

Exact same issue - fixed the first SimpleImputer error with "imputation_type = 'iterative', and the second error emerges even though i have scikit-learn==0.23.2 installed.
