### ISSUE TITLE
CatBoostError: catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: catboost_info

### ISSUE THREAD

**Issue by yashwatwani** [pycaret/pycaret#132]
while running "comapre_models()"

CatBoostError                             Traceback (most recent call last)
<ipython-input-6-9ff5ccfe3077> in <module>()
----> 1 compare_models()

/usr/local/lib/python3.6/dist-packages/pycaret/classification.py in compare_models(blacklist, fold, round, sort, turbo)
   3434             if hasattr(model, 'predict_proba'):
   3435 
-> 3436                 model.fit(Xtrain,ytrain)
   3437                 pred_prob = model.predict_proba(Xtest)
   3438                 pred_prob = pred_prob[:,1]

/usr/local/lib/python3.6/dist-packages/catboost/core.py in fit(self, X, y, cat_features, text_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   3791         self._fit(X, y, cat_features, text_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
   3792                   eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period,
-> 3793                   silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   3794         return self
   3795 

/usr/local/lib/python3.6/dist-packages/catboost/core.py in _fit(self, X, y, cat_features, text_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   1688                 params,
   1689                 allow_clear_pool,
-> 1690                 train_params["init_model"]
   1691             )
   1692 

/usr/local/lib/python3.6/dist-packages/catboost/core.py in _train(self, train_pool, test_pool, params, allow_clear_pool, init_model)
   1223 
   1224     def _train(self, train_pool, test_pool, params, allow_clear_pool, init_model):
-> 1225         self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
   1226         self._set_trained_model_attributes()
   1227 

_catboost.pyx in _catboost._CatBoost._train()

_catboost.pyx in _catboost._CatBoost._train()

CatBoostError: catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: catboost_info

**Comment by pycaret** [comment]
@yashwatwani Can you please share more details regarding your OS and environment. Also can you tell which version of catboost you are using. You can do pip freeze to check that.

**Comment by GLevV** [comment]
It could be fixed with `allow_writing_files=False` when CatBoost model is initialized. It will prevent cb from writing files to disk

**Comment by pycaret** [comment]
@yashwatwani Is this issue resolved? You can stop catboost from writing files on disk by passing `allow_writing_files` param. 

```
catboost = create_model('catboost', allow_writing_files = False
```

Please close the issue if that works.
