### ISSUE TITLE
Error during SetUp()

### ISSUE THREAD

**Issue by venkaateshd** [pycaret/pycaret#1321]
i am trying to do a regression model , and a fresher to pycaret. 

i am using the tutorial notebook, Regression 101 for beginner and when i set up the model i get a value error (please see the error below)

ValueError: Setting a random_state has no effect since shuffle is False. You should leave random_state to its default (None), or set shuffle=True.

Any advises or solutions in this aspect would be really helpful.

Thank you.

Regards,
Venkaatesh

**Comment by pycaret** [comment]
@venkaateshd please update your pycaret version

```
pip install --upgrade pycaret
```

**Comment by venkaateshd** [comment]
> pip install --upgrade pycaret

when i try to upgrade pycaret, this is the error i am getting . please advise how do i solve it ?

![image](https://user-images.githubusercontent.com/51989263/120430242-4c2f7500-c3a9-11eb-9bbb-b1b6137993e1.png)

**Comment by babaniyi** [comment]
Since you have this error, don't update it. Reinstall it using

```
pip install pycaret
```

**Comment by babaniyi** [comment]
> i am trying to do a regression model , and a fresher to pycaret.
> 
> i am using the tutorial notebook, Regression 101 for beginner and when i set up the model i get a value error (please see the error below)
> 
> ValueError: Setting a random_state has no effect since shuffle is False. You should leave random_state to its default (None), or set shuffle=True.
> 
> Any advises or solutions in this aspect would be really helpful.
> 
> Thank you.
> 
> Regards,
> Venkaatesh

What this means is you have 2 options but select only 1 (not both). Either  set 
```
shuffle = True, 
random_state = 123
```
OR

```
shuffle = True
```

**Comment by AdriBee** [comment]
> > pip install --upgrade pycaret
> 
> when i try to upgrade pycaret, this is the error i am getting . please advise how do i solve it ?
> 
> ![image](https://user-images.githubusercontent.com/51989263/120430242-4c2f7500-c3a9-11eb-9bbb-b1b6137993e1.png)

I have had the same problem. For my case, I solved it installing Visual Studio C++ from https://visualstudio.microsoft.com/visual-cpp-build-tools/

This stackoverflow post will guide you through the installation process. There seem to be a problem with Bottleneck during installation, but this solved it for me.

https://stackoverflow.com/questions/44951456/pip-error-microsoft-visual-c-14-0-is-required

Hope this helps! :)

**Comment by pycaret** [comment]
@venkaateshd 

Install `bottleneck` using conda and then install `pycaret`. It should fix the issue.

```
pip uninstall pycaret -y
conda install bottleneck
pip install pycaret
```
