### ISSUE TITLE
How to convert "exp_nlp" into dataframe

### ISSUE THREAD

**Issue by Sakil786** [pycaret/pycaret#133]
Hi I want to convert exp_nlp  output into dataframe.
I am writing code:
exp_nlp =pd.DataFrame(exp_nlp )
I am getting error.
Please help.

**Comment by ManuelBanza** [comment]
hi @Sakil786 
I think you can use the assign_model:

lda_results = assign_model(exp_nlp)

it will add the topics to your dataset

**Comment by pycaret** [comment]
@ManuelBanza Thanks for helping.

@Sakil786 You can close the issue if the answer has solved your problem?

Please check https://www.pycaret.org/assign-model for more details.
