### ISSUE TITLE
MAE and MASE metric support for time series modules 

### ISSUE THREAD

**Issue by TremaMiguel** [pycaret/pycaret#1331]
**Describe the bug**

Check `MAE` and `MASE` metric support in `cross_validate_ts` function. [Reference](https://github.com/pycaret/pycaret/blob/time_series/pycaret/containers/metrics/time_series.py#L188)

**Comment by ngupta23** [comment]
@TremaMiguel I think MAE is working fine. Did you see any issues with it?

MASE will require an extra argument to be passed to the metrics container and will need additional work.

**Comment by ngupta23** [comment]
@Yard1  Related to #1406 

For each fold, we need to pass y_train to calculated the scaled metric (MASE) in this case. Is this possible today? If not, what changes would be needed? Thanks!

**Comment by ngupta23** [comment]
See supported syntax for adding this metric here: https://github.com/pycaret/pycaret/issues/1900#issuecomment-982153605
