### ISSUE TITLE
PyCaret setup not completely running in Django views

### ISSUE THREAD

**Issue by PardeepRassani** [pycaret/pycaret#1333]
I have a function in the views.py of a Django app, in which I am setting up setup function of PyCaret regression module:

```python
from pycaret.regression import setup, compare_models, pull, get_logs
s = setup(data=df.copy(), target=selectedTarget, train_size=selectedTrainingPercentage,numeric_features= selectedFeatureColumns, silent =True, log_experiment=True)
print("Pycaret setup run")
```

and I get the following output where setup is not fully run, neither giving any error:

![Screenshot from 2021-06-05 00-37-08](https://user-images.githubusercontent.com/36777973/120917154-fc152300-c6c6-11eb-8070-a3258b619282.png)

**Versions**
2.3.1

**Comment by ngupta23** [comment]
You may be running out of memory. Monitor the memory usage to verify this. If it is close to the limit, try

1. with `preprocess = False` to see if it works. 
2. on a different machine like Google Colab which may have a larger memory.

**Comment by PardeepRassani** [comment]
I am running PyCaret on jupyter notebook locally, which is working fine even without `preprocess = False`, however setup is  running completely in Django views if I set `preprocess = False` but then I get empty output from compare_models() or pull().

**Comment by ngupta23** [comment]
Not sure. It might be a Django specific issue. Maybe someone with experience in this framework can help.

**Comment by maverick-gst** [comment]
Once the setup is complete, can you try to access X/X_train from
get_config, yo check all the global variables are available from setup.

**Comment by PardeepRassani** [comment]
@maverick-gst yes I am able to get the X from get_config('X) once the setup is complete. The X is not empty, it is the dataset that I passed to setup.

**Comment by moezali1** [comment]
Can't reproduce.
