### ISSUE TITLE
Save interpret_model output in mlflow

### ISSUE THREAD

**Issue by set92** [pycaret/pycaret#1337]
**Is your feature request related to a problem? Please describe.**
I'm trying to use MLFlow as the platform to track the runs, and if I wanted to have also the plots of XAI to know how the model worked, but seems they aren't in log_plots parameter of setup(). And I was not able to find a option to track it in setup() or interpret_model()

**Describe the solution you'd like**
I suppose it could be easy to add a parameter log_interpretation like the others (log_data, log_profile, log_plots).

**Describe alternatives you've considered**
I suppose I could do 
```
interpret_model(model, plot = 'summary')
... # line to make mlflow register the .png file returned by interpret_model which I'm not sure how do it
```

**Comment by pycaret** [comment]
@set92 Would you like to work on this enhancement?

**Comment by set92** [comment]
@pycaret I'm not very confident in my programming skills and I haven't done it before, but I could try since I think I know how it should work. 

Right now what I'm using is:
```python
def xai_model(model):
    mlflow.set_tag("mlflow.runName", type(model).__name__)
    model_id = pycaret.internal.tabular._get_model_id(best_model)
    #if the model is not a tree SHAP will not work
    if model_id in ["et", "lightgbm", "xgboost", "dt", "catboost", "rf"]:
        for plot_type in ['summary', 'correlation']: 
            interpret_model(model, plot = plot_type, save=True)
            file = f"SHAP {plot_type}.png"
            mlflow.log_artifact(file)
            os.remove(file)
```
I was not able to use 'reason' and 'pdp', the first one because it is at observation level and wasn't sure how to ask the user for input, and the other option was always using the 'observation' plot of the first row. And I was unable to use 'pdp' because it gave me an error of not being implemented and I didn't check it more.
