### ISSUE TITLE
Finding and removing duplicate data during setup

### ISSUE THREAD

**Issue by azharirfan** [pycaret/pycaret#134]
Hi, it may not be a big issue, but i have tried Pycaret on my work dataset and there were some entries duplicated (by error) and it would be great to have an option in setup that could be activated to find (and remove) duplicate entries or atleast highligh to user that possible duplicate entires are noticed. Suggestion: ID column (if available in the dataset) can be used to identify a possible duplicate.

**Comment by pycaret** [comment]
@azharirfan Thanks.

Marking this as an enhancement for future.

**Comment by pycaret** [comment]
# Open for contribution now

**Comment by Yard1** [comment]
I'm afraid there's no "magic solution" for this. Finding duplicates is one of the things that is going to be computationally expensive either way. I guess one could try to do something with hashing, but I'd need to test it.

**Comment by Yard1** [comment]
Pandas provides a function to find duplicate rows - I doubt anything we come up with is going to be faster than that.

**Comment by pycaret** [comment]
@Yard1 After thinking a lot about this. The cost-benefit for this feature is not viable. If there are duplicate rows, users can remove it themselves before passing it into pycaret. 

Closing this issue.
