### ISSUE TITLE
[BUG] Possibly with Simple Imputer?

### ISSUE THREAD

**Issue by zhaozhongfeng1990** [pycaret/pycaret#1345]
**Describe the bug**
when i run 
''clf1 = setup(prepare_data, target = 'Class', session_id=456, train_size=0.7,        
             log_experiment=False, experiment_name='test1')

then  return 
        'Simple_Imputer' object has no attribute 'fill_value_categorical'

how can i fix this,thanks

**Comment by ngupta23** [comment]
Please provide more details (like a minimum reproducible example with the other required details that were mentioned in the bug template like version used, etc.

**Comment by Yard1** [comment]
Make sure you have `sklearn==0.23.2`. Other versions (including newer ones) are not supported at this moment.
