### ISSUE TITLE
Could not convert STR column to FLOAT when this column has missing values

### ISSUE THREAD

**Issue by FaridAhamadaGunners** [pycaret/pycaret#135]
I load a dataset (8000,22) with a string column contains float numbers. So the setup() function infer that this column is categorical because this column contains whitespace characters. 
So when i force the setup() function with the parameter numeric_features set to with this column 

I encountered this error : ValueError: could not convert string to float 

When i debug the code i see that in the script preprocess.py you use the function .astype(float64) for conversion. I think you should use the pandas function to_numeric() with the parameter errors set to 'coerce' and the parameter downcast to 'integer'  or 'float or whatever. This function with theses settings will convert any columns in numeric and will force the unrecognized values to NaN.

**Comment by pycaret** [comment]
@FaridAhamadaGunners Can you submit the PR to dev-1.0.1 branch?

**Comment by FaridAhamadaGunners** [comment]
Yes, i will do it
