### ISSUE TITLE
Significant d8fference between train AUC and mean cross validated AUC

### ISSUE THREAD

**Issue by ptanalyst** [pycaret/pycaret#1355]
**Is your feature request related to a problem? Please describe.**
I have seen that the result that I am getting of train auc from the evaluate model  (use_train_data=yes) is significantly higher than the mean AUC of cv result from the create model for test/hold out data set. Is there any way to minimise this gap

**Describe the solution you'd like**
I think a metric should be calculated in terms of difference between train and test AUC and putting a threshold like 10% or 15% and accordingly choosing the best model would be good option.

**Comment by ptanalyst** [comment]
First issue

**Comment by Yard1** [comment]
This is not an issue with PyCaret but rather with data and/or models you are using. In general, metrics on train data will be higher than on test/validation data.
