### ISSUE TITLE
Scored train data set

### ISSUE THREAD

**Issue by ptanalyst** [pycaret/pycaret#1356]
Is there anyway to get the train data scored - when we run the predict_model(), we get only test/hold out data scored

**Comment by pycaret** [comment]
@ptanalyst You can access the index of `X_train` using the `get_config` function and then call the `predict_model`. See example below:

```
from pycaret.datasets import get_data
data = get_data('juice')

from pycaret.classification import *
s = setup(data, target = 'Purchase', silent = True)

lr = create_model('lr')

train_data = data.iloc[get_config('X_train').index]
train_predictions = predict_model(lr, data=train_data)
train_predictions.head()
```
