### ISSUE TITLE
[DOC] Sampling no longer available in pycaret but still on the webpage documentation

### ISSUE THREAD

**Issue by astenuz** [pycaret/pycaret#1357]
#### Describe the issue linked to the documentation

The webpage for pycaret refers to a featured named sampling https://pycaret.org/sampling/. However, this feature is no longer available according to the setup function in pycaret 2.3.1 (screenshot added).
<img width="546" alt="image" src="https://user-images.githubusercontent.com/4689127/121939314-833f4800-cd12-11eb-9603-b7eb269a230f.png">

#### Suggest a potential alternative/fix
It would be nice to clarify if this sampling can be achieved by other means in pycaret. For example the part of generating multiple model for different training sample sizes could be very useful to select minimum sample sizes and assess generalization performance.

**Comment by datanerdie** [comment]
I agree. Is there a reason why the sampling feature is dropped (https://github.com/pycaret/pycaret/commit/e154dd9ad56c5449efdd454814e2c43caf1292ba#diff-c51d929bd6802959f40dc156e067fc81fd5e159c9bf7d40c8f15d4b6f379b833)?

**Comment by theadammurphy** [comment]
I'm working with a dataset of 600k rows and 100 cols. Pycaret is supposed to be a fast and effective way to do loads of experiments but it takes AGES to run a simple `compare_models()` without any tuning. I started with CPU but realised that was going to be way too slow. I've switched to GPU and some models are super fast (1s) but others take 30+ mins. 

Having this sample function would give me the confidence to work with a smaller dataset from the off. Can you reimplement it?

**Comment by Yard1** [comment]
You can sample the data yourself before passing it to PyCaret. That's literally the only thing that it was doing.
