### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'display_id'

### ISSUE THREAD

**Issue by gillbates** [pycaret/pycaret#136]
Hi pycaret team,

when i try following code according to the tutorial

`
diabetes = pd.read_csv('/Users/xxx/projects/github/pycaret/datasets/diabetes.csv')
clf1 = setup(data=diabetes, target='Class variable')

compare_models()

`

when I cloned the repo and use following code from tutorial.
`
Traceback (most recent call last):
  File "/Users/xxx/projects/python/pycaret/test.py", line 15, in <module>
    compare_models()
  File "/Users/xxx/projects/python/pycaret/venv/lib/python3.7/site-packages/pycaret/classification.py", line 3185, in compare_models
    display_id = display_.display_id
AttributeError: 'NoneType' object has no attribute 'display_id'
`

running on python 3.7.7 macos

Anyone could help?

**Comment by amjadraza** [comment]
did you try with session_id?

Below code worked for me in notebook
`!pip install pycaret
from pycaret.datasets import get_data
from pycaret.classification import *
diabetes = get_data('diabetes')
# diabetes = pd.read_csv('/Users/xxx/projects/github/pycaret/datasets/diabetes.csv')

clf1 = setup(data=diabetes, target='Class variable', session_id=12369)

compare_models()`

**Comment by gillbates** [comment]
it runs well in notebook. But still gets the same error when I run in pycharm/terminal

**Comment by pycaret** [comment]
@gillbates Hi Gillbates, Thanks for reporting. This is a known bug which prevents pycaret to run in environment that doesn't support html such as pycharm or CLI. This will be fixed in our next release (in couple of weeks from now). 

Thanks.
