### ISSUE TITLE
Return dataframe with processed features after setup()

### ISSUE THREAD

**Issue by babaniyi** [pycaret/pycaret#1362]
**Feature Request**

Currently after implementing setup() where setup() includes some data processing techniques such as outlier removal, missing value imputation, one-hot encoding, etc the user doesn't have access to the processed data used for data modelling but trusts PyCaret has done these data transformation behind the scene.

**Solution I would like**

It would be great to have a feature that returns the newly created processed data (which transforms the data) specified by the user. This feature could be called *return_transformed_data*.

Incorporating such a feature will increase the trust in PyCaret and I'm certain will be a game-changer in the ML industry.

**Comment by Yard1** [comment]
This is already available as a feature by running `get_config('X')` after `setup()`. Let me know if that helps.

**Comment by babaniyi** [comment]
> This is already available as a feature by running `get_config('X')` after `setup()`. If that doesn't help, feel free to reopen the issue.

Thanks for the information. I have to update to the latest version.
