### ISSUE TITLE
[BUG] Numeric features which are imputed using Iterative Imputer are not getting normalized

### ISSUE THREAD

**Issue by arnabmanna619** [pycaret/pycaret#1364]
**Describe the bug**
When I am doing both imputation using Iterative imputer and then normalizing the numeric features, I see that the features which were imputed are not getting normalized. It's working fine when the imputation is 'simple', only causing problems when the imputation is 'iterative'.

**Comment by Yard1** [comment]
Thank you. Do you have a script and a dataset this can be reproduced on?

**Comment by arnabmanna619** [comment]
The dataset is confidential but I have run it on a sample data
```
sample = pd.DataFrame({'A': [10.8, 15.6, 13.1, np.nan, 2.3], 'B': [42.6, 35.8, 12.9, 27.6, 44.2], 'target': [0, 1, 1, 1, 0]})

exp = setup(data = sample, target = 'target', imputation_type='iterative', 
            numeric_features=['A', 'B'], normalize=True, normalize_method='minmax',
            data_split_shuffle=True, data_split_stratify=True, fold=5, session_id=123)

get_config('X')
```

The above gives the following output : 
A | B
10.80 | 0.903614
15.60 | 0.493976
13.10 | -0.885542
8.95 | 0.000000
2.30 | 1.000000

**Comment by Yard1** [comment]
Thanks, will take a look.

**Comment by Yard1** [comment]
@arnabmanna619 Fixed in https://github.com/pycaret/pycaret/pull/1371, thanks for the report!
