### ISSUE TITLE
Refactor time series unit tests

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#1368]
**Is your feature request related to a problem? Please describe.**

- [x] Some time series tests could be made more modular.
- [x] Also, tests need to be sped up
- [x] Separate out slow tests into own py file and run separately in parallel to speed up execution

**Describe the solution you'd like**
- [x] Create a fixture of created models that can be reused by all tests instead of creating models in each test individually. This will speed up the tests somewhat.
- [x] For non default parameters, add a fixture that will pick different values (from the domain of values) for different models. e.g. 
_Originally posted by @TremaMiguel in https://github.com/pycaret/pycaret/pull/1361#discussion_r652305381_
- [x] Add `conftest.py`
_Originally posted by @TremaMiguel in https://github.com/pycaret/pycaret/pull/1332#discussion_r646229159_

**Comment by moezali1** [comment]
@ngupta23 

Is @TremaMiguel still working on the time series module?

**Comment by ngupta23** [comment]
> Is @TremaMiguel still working on the time series module?

I will reassign if he is unavailable.
