### ISSUE TITLE
Upgrade from sktime 0.5.3 to 0.7.0

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#1369]
**Is your feature request related to a problem? Please describe.**
Alpha version of time series module is using an older version of sktime (0.5.3)

**Describe the solution you'd like**
Upgrade to latest version of sktime (0.6.1) which has breaking changes compared to older version.

**Comment by TremaMiguel** [comment]
One change here requires changing the `ExpandingWIndowSplitter` 

[v0.6.1](https://github.com/alan-turing-institute/sktime/blob/v0.6.1/sktime/forecasting/model_selection/_split.py#L471)
[v0.5.3](https://github.com/alan-turing-institute/sktime/blob/v0.5.3/sktime/forecasting/model_selection/_split.py#L295)

**Comment by ngupta23** [comment]
Completed
