### ISSUE TITLE
Request for Time series modules

### ISSUE THREAD

**Issue by sathishkumar999** [pycaret/pycaret#137]
Hi Pycaret Team...
I've been using pycaret modules since 1 month....It makes most of the models automative.
All data science modules are available, except  for time series modules.
could you guys add Time series modules in next version such as "Arima and Holt-Winters".
where most of the retail companies are using for forecasting the monthly, quarterly and yearly product sales.

**Comment by pycaret** [comment]
@sathishkumar369 Thanks for your feedback. This is surely in the list.

Keeping this issue open and tagging this as an enhancement.

**Comment by pycaret** [comment]
@ngupta23 FYI.

**Comment by ngupta23** [comment]
Hi @sathishkumar999 , This is currently in work. A Alpha/Beta version should be ready shortly. Would you be interested in being one of the testers for this module?

**Comment by balins** [comment]
> Hi @sathishkumar999 and @balins , This is currently in work. A `beta` version should be ready shortly. Would you be interested in being one of the testers for this module?

Hi @ngupta23, sorry, but I'm no longer into time series analysis.
