### ISSUE TITLE
Confusion Matrix

### ISSUE THREAD

**Issue by gveronese01** [pycaret/pycaret#1379]
Enable the confusion matrix response to be in percentage.

**Comment by rajagurunath** [comment]
Hi @gveronese01 , @ngupta23 

I understood there is an option/parameter in the yellowbrick which enables showing percentage in the confusion matrix plot 
as specified in this [documentation](https://www.scikit-yb.org/en/latest/api/classifier/confusion_matrix.html#yellowbrick.classifier.confusion_matrix.ConfusionMatrix) 

And pycaret has a confusion matrix function in the below file
https://github.com/pycaret/pycaret/blob/f54016b6df7a7210eef5501b30c9b9b31a3ca3ae/pycaret/internal/tabular.py#L6527

I guess we need to pass that extra parameter `percent = True` here right? I am new to pycaret Sorry if this question didn't make sense, can we get this parameter from the user in the setup function itself? or any other way the user can configure this parameter that I am not aware of, please let me know I am happy to take this functionality as my good first issue.

Thanks in Advance

**Comment by pycaret** [comment]
@Yard1 Can we handle this through **kwargs or any other recommendation?

**Comment by Yard1** [comment]
We'll probably have to make a new plot type like we did with feature plot (top 10 and all)

**Comment by moezali1** [comment]
This issue is being worked in #1939. Hence closing this one.
