### ISSUE TITLE
plotly version not working for 4.4.1.

### ISSUE THREAD

**Issue by vishal-subedi** [pycaret/pycaret#138]
Hey, I noticed that the pycaret module throws an error while using plotly=4.4.1, which is mentioned in the requirement.txt file in the repo. However, it works fine with the latest version i.e. 4.7.1, so it could be changed to something like plotly > 4.4.1

**Comment by DaGuT** [comment]
it's fixed in dev 1.0.1.

**Comment by pycaret** [comment]
@vishal-subedi Issue fixed in dev-1.0.1. Will be pushed in production in next release.

@DaGuT  Thanks.
