### ISSUE TITLE
Keep features out of feature selection

### ISSUE THREAD

**Issue by npapan69** [pycaret/pycaret#1382]
Dear all, in my opinion adding the possibility to define "immune" features to the feature selection process, would enhance pyCaret substantially. In other words, have a "must_keep" parameter in the setup of the classification problem would leave out of the feature selection process. Something like that would make it possible to perform subcohort analysis according to a feature value and check for bias in the models.
Thank you in advance

**Comment by maverick-gst** [comment]
I agree with this. Currently we are thinking of handling in our case, with
setting X_train, X_test with important columns added after setup, using
set_config.

**Comment by tvdboom** [comment]
Good idea. I'll add this possibility as extra feature to the refactoring of the preprocessing module.

**Comment by tvdboom** [comment]
Done in v3.0
