### ISSUE TITLE
[BUG] Wrong feature inference 

### ISSUE THREAD

**Issue by noobmaster29** [pycaret/pycaret#1383]
We are currently using setup and compare_model to obtain a model with Pycaret. Our setup is in Knime. The input dimension is 7 features and 1 target. All the features are integer or floats. However, the setup function still interprets some of them as categorical features and ends up creating more columns to encode them. 

**To Reproduce**

from pycaret.regression import *
import pandas as pd

input_table = pd.read_csv("demo.csv")

reg1 = setup(data = input_table, target = "target", silent=True)
best_model = compare_models(n_select = 3)
best_model[2].n_features_

Output: 51

**Expected behavior**
We expected the trained model to have a 7 input dimension. However, the trained models have different input dimensions. 

**Additional context**
This issue was avoided by manually declaring each variable as numeric_features in the setup function. However, since the features were already preprocessed into numeric features, it is unclear why setup decided to reinterpret them as categorial features. 

**Versions**
>>> pycaret.__version__
'2.3.1'
sklearn.__version__
'0.23.1'

[demo.csv](https://github.com/pycaret/pycaret/files/6687475/demo.csv)

**Comment by pycaret** [comment]
@noobmaster29 Hi.. You can explicitly define data types in the `setup` function by using `categorical_features` and/or `numeric_features` parameter. Simply pass the name of the columns as a list. For example:

```
s = setup(data, target = 'target', categorical_features = ['cat_col1', 'cat_col2'], numeric_features = ['num_col1', 'num_col2'], 
```

Hope this helps.
