### ISSUE TITLE
setup() got an unexpected keyword argument 'fold_strategy'

### ISSUE THREAD

**Issue by lgpatruyo** [pycaret/pycaret#1389]
### Discussed in https://github.com/pycaret/pycaret/discussions/1388

<div type='discussions-op-text'>

<sup>Originally posted by **lgpatruyo** June 22, 2021</sup>
Hi, I am trying to follow the code in your document "Time Series Forecasting with PyCaret Regression Module". 
I have installed PyCaret 2.2 and also the nightly version. I did create a separate virtual environment. 

I am getting the above error: "setup() got an unexpected keyword argument 'fold_strategy'". I actually do not see that argument in the method help. Any idea what could be wrong?

Setup() was not recognizing the argument 'test_data' either. I fixed that by only using (data = data, train_size = 0.9, data_split_shuffle = False,...) and deleting the 'test_data' argument.

Thanks,</div>

**Comment by ngupta23** [comment]
Answered #1388
