### ISSUE TITLE
How to continue training?

### ISSUE THREAD

**Issue by wukan1986** [pycaret/pycaret#139]
xgboost and lightgbm can pass old model by fit, but how to do it in pycaret?

**Comment by pycaret** [comment]
@wukan1986 Do you mean you have a lightgbm and xgboost model with specific parameters and you want to re-train on new data using same parameters?

**Comment by wukan1986** [comment]
> @wukan1986 Do you mean you have a lightgbm and xgboost model with specific parameters and you want to re-train on new data using same parameters?

Yes

`fit(X, y, sample_weight=None, base_margin=None, eval_set=None, eval_metric=None, early_stopping_rounds=None, verbose=True, xgb_model=None, sample_weight_eval_set=None, callbacks=None)`

> xgb_model (str) – file name of stored XGBoost model or ‘Booster’ instance XGBoost model to be loaded before training (allows training continuation)

`fit(X, y, sample_weight=None, init_score=None, eval_set=None, eval_names=None, eval_sample_weight=None, eval_class_weight=None, eval_init_score=None, eval_metric=None, early_stopping_rounds=None, verbose=True, feature_name='auto', categorical_feature='auto', callbacks=None, init_model=None)[source]`

> init_model (string, Booster, LGBMModel or None, optional (default=None)) – Filename of LightGBM model, Booster instance or LGBMModel instance used for continue training.

**Comment by pycaret** [comment]
@wukan1986 

# This feature is now available in PyCaret 2.0

You can pass model hyper parameters within **create_model** function directly. For example:

lightgbm = create_model('lightgbm', learning_rate = 0.2) 
xgboost = create_model('xgboost', max_depth = 10)

Hope this helps.
