### ISSUE TITLE
MLFlow Experiment Logging (ad hoc)

### ISSUE THREAD

**Issue by S-C-H** [pycaret/pycaret#1390]
**Is your feature request related to a problem? Please describe.**
Sometimes additional graphs or outputs (objects, csvs) are created in a pycaret workflow e.g. custom interpretability plots etc. It would be nice to log in the same MLFlow experiment

**Describe the solution you'd like**
A Util function allowing a graph, csv or other python object to be logged to the MLFlow experiment for the run

**Comment by jfagn** [comment]
I think by "experiment" you mean "run". Otherwise, you can simply create a new run in MLFlow with only your additional output.
