### ISSUE TITLE
how to handle missing values on unseen data (final real time data)

### ISSUE THREAD

**Issue by SriRamGovardhanam** [pycaret/pycaret#1399]
Hey, Firstly thank you for making this project opensource, repo is really awesome. 
I have seen imputation during setup but is it possible to add impute feature while predicting the real time data?

like using it in predict_model() method to handle missing values on unseen data.

response would be much appreciated!

**Comment by pycaret** [comment]
@SriRamGovardhanam Thank you.

Imputation and any other transformation that you choose in the `setup` function are automatically applied during inference on real-time data. All you need to do is call the `predict_model` function on the pipeline that you have saved using the `save_model` function and pass the new data. For example:

```
**# init setup**
from pycaret.classification import *
s = setup(data, target = 'target', silent = True)

**# train lr model**
lr = create_model('lr')

**# save trained model/pipeline**
save_model(lr, 'c:/users/models/lr-deloyed')

**# load trained model/pipeline**
lr_trained = load_model('c:/users/models/lr-deloyed')

predictions = predict_model(lr_trained, data=pass_new_raw_data)

```

**Comment by SriRamGovardhanam** [comment]
Thanks for the reply.
Even I followed the same procedure as mentioned above, which is:
```
light = create_model('lightgbm')
prediction = predict_model(light, data = test1)
prediction.head(15)
```
this is the output dataframe I got
![temp](https://user-images.githubusercontent.com/35695549/123504077-b966bb00-d674-11eb-9d72-6221f98953cf.png)


data in independent variables here are not imputed, or at least I cannot see here.
