### ISSUE TITLE
Parellelizing compare_models

### ISSUE THREAD

**Issue by ericmjl** [pycaret/pycaret#14]
Hi team,

Wonderful work with `pycaret`! I'm wondering if you might be open to a PR that parallelizes `compare_models()`, such that one core takes on one model class? Yes, this might change some of the UI elements, but it might also speed up training. I have some experience using Dask, and am happy to lend some time to make this happen, though I might also need some guidance through the codebase at some point.

**Comment by pycaret** [comment]
Hi,

Thanks for showing interest.

This is a very good idea. . Can you please create an entry on https://www.pycaret.org/contribute. I will start getting back to people in next 2-3 weeks.

Thanks
