### ISSUE TITLE
NLP num of line doesn't match error from colab

### ISSUE THREAD

**Issue by DaiZack** [pycaret/pycaret#140]
nlp.py

line 141

 `   try:
        max_sub = len(data[target].values.tolist())
    except:
        max_sub = len(data)`

When the data frame target column has empty values, it courses num of lines not match error in model_plot step.

PS: I ran it from Colab

**Comment by pycaret** [comment]
@DaiZack Thanks. Please feel free to submit a PR on dev-1.0.1 branch.

**Comment by pycaret** [comment]
@DaiZack Hi. Do you plan to submit a PR on this one?
