### ISSUE TITLE
Forecast Plots should include Prediction Interval

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#1404]
**Is your feature request related to a problem? Please describe.**

Per this [comment on LinkedIn](https://www.linkedin.com/feed/update/urn:li:ugcPost:6814933350713741312?commentUrn=urn%3Ali%3Acomment%3A%28ugcPost%3A6814933350713741312%2C6814934502796779520%29&replyUrn=urn%3Ali%3Acomment%3A%28ugcPost%3A6814933350713741312%2C6815038277939273728%29) from @RamiKrispin

**Describe the solution you'd like**

The forecast plots do not have PI, recommend to show it as default (I always argue that models without PI should never be used).

**Comment by ngupta23** [comment]
@ramikrispin 

Regarding Prediction Intervals, this is available for some models right now (but not all - e.g. not available for reduced regression models). By default, we set it to not return this, but it could be returned by setting the following argument (as in cell 16 + in [this notebook](https://github.com/pycaret/sktime-dev-days-2021/blob/main/sktime_dev_days_201.ipynb)).

```python
exp.predict_model(model, return_pred_int=True)
```

I understand the hesitation of not using models without prediction intervals. In the future, we may add an option to allow using only models that have prediction intervals. Would this be helpful?

**Comment by RamiKrispin** [comment]
Thanks @ngupta23, that is only my personal perspective (having PI as default on plot) :) 
You should set the default options of your functions with the ones you believe

**Comment by ngupta23** [comment]
This is fixed by https://github.com/pycaret/pycaret/pull/1615
