### ISSUE TITLE
Add Prediction Interval coverage of the test set

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#1406]
**Is your feature request related to a problem? Please describe.**
Per this [comment on LinkedIn](https://www.linkedin.com/feed/update/urn:li:ugcPost:6814933350713741312?commentUrn=urn%3Ali%3Acomment%3A%28ugcPost%3A6814933350713741312%2C6814934502796779520%29&replyUrn=urn%3Ali%3Acomment%3A%28ugcPost%3A6814933350713741312%2C6815038277939273728%29) from @RamiKrispin

**Describe the solution you'd like**
If you are running a horse race between multiple models with backtesting, it is nice to add the PI coverage rate on the testing partitions.

**Comment by ngupta23** [comment]
@ramikrispin PI coverage on test set would be a valuable addition. We will consider adding it!

**Comment by pycaret** [comment]
How can we calculate coverage for models that doesn't support PI?

Question only.

**Comment by ngupta23** [comment]
It will have to be limited to models that have PI. For others it will be NaN for now.

We will also add an option in setup to only use models that have a PI (when using compare_models), since this is a requirement in many applications.

**Comment by ngupta23** [comment]
@Yard1 ... For each fold, we need to calculate how many actual data points in the test set are within the prediction interval. This would need us to pass additional arguments to the metric calculator (for upper and lower confidence interval). Is this possible today? If not, what changes would be needed? Thanks!

**Comment by ngupta23** [comment]
@ramikrispin  This has been implemented. It will go out in the next release.
