### ISSUE TITLE
Add compute time for each model as metrics

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#1407]
**Is your feature request related to a problem? Please describe.**

Per this [comment on LinkedIn](https://www.linkedin.com/feed/update/urn:li:ugcPost:6814933350713741312?commentUrn=urn%3Ali%3Acomment%3A%28ugcPost%3A6814933350713741312%2C6814934502796779520%29&replyUrn=urn%3Ali%3Acomment%3A%28ugcPost%3A6814933350713741312%2C6815038277939273728%29) from @RamiKrispin

**Describe the solution you'd like**

It would be nice to have the compute time of each model as one of the evaluation metrics

**Comment by ngupta23** [comment]
@ramikrispin The compute time is already included in the results from `compare_models()` (though not as a metric). We could add it to `create_model()` as well. Would this satisfy your requirement?

**Comment by RamiKrispin** [comment]
I think that compute time should be side by side with the error metric that users can evaluate the cost-benefit of using a more "expensive" model with respect to the added value it provides (e.g., improvement in the accuracy, etc.)

**Comment by pycaret** [comment]
Isn't TT column in compare_models serving that purpose? 

There is no point of adding TT in create_model as time by fold is not the information people will generally care about.

**Comment by ngupta23** [comment]
@RamiKrispin could you clarify how you would like this to work? Currently, training time is already provided for compare_models. Is there anything else you would like to see?

![image](https://user-images.githubusercontent.com/33585645/124854307-c2a53100-df6c-11eb-9cfa-6f9c6006d642.png)

**Comment by ngupta23** [comment]
@RamiKrispin , I created a [Kaggle Notebook](https://www.kaggle.com/ngupta23/metrics-vs-training-time-tradeoff-using-pycaret?scriptVersionId=68413869) to show show the training time could be used to eliminate the slow models from the list. Let me know if this is what you were looking for.

**Comment by RamiKrispin** [comment]
@ngupta23 sorry, missed your last comment. I think that having a column with the run time is sufficient.

**Comment by ngupta23** [comment]
Thanks @RamiKrispin . We will close this in that case. Feel free to open a new Issue if you have more feedback. Thanks!
