### ISSUE TITLE
Auto Detect Seasonal Period for annual data

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#1408]
**Is your feature request related to a problem? Please describe.**
Auto Detect `seasonal_period` for annual data. Currently it assumes 1 by default so it has to be specified manually in setup.

**Describe the solution you'd like**
Figure out a way to compute the `seasonal_period` from this data instead of asking user to input it.

**Describe alternatives you've considered**
Manual entry of `seasonal_period` can not be automated since it varies from dataset to dataset.

**Additional context**
Feedback received from `sktime` dev days presentation

**Comment by ngupta23** [comment]
@fkiraly 

> recommend adding it to the grid search parameters

**Comment by ngupta23** [comment]
@fkiraly

This disadvantage is that it can increase the search space and slow down the tuning. Another option could be to use statistical tests and find the `seasonal_period` that gives the best test statistic and use that as the `seasonal_period`. Need to research if such a test exists. The advantage of this approach is that statistical tests are less time consuming than expanding the grid's search space.

Just jotting down some ideas here ...

**Comment by fkiraly** [comment]
See this discussion in `sktime`
https://github.com/alan-turing-institute/sktime/issues/1056

Shall we have that meeting where we plan the technical roadmap together?
E.g., what should be in `sktime`, what should be in `pycaret`, what the interfaces are?
Let's connect on slack.

**Comment by ngupta23** [comment]
Solved in #3151 

![image](https://user-images.githubusercontent.com/33585645/205534619-2e620fd2-cbb0-4e5f-9ac7-78d229604fcb.png)
