### ISSUE TITLE
How to get AUC of prediction on test data?

### ISSUE THREAD

**Issue by gerxyuan** [pycaret/pycaret#141]
I want to observe how the model performs in the test set, but I can only get a table of predicted results at the moment, I want to see the results of Accuracy, AUC,Recall, Prec, F1, Kappa. how does that work?

**Comment by pycaret** [comment]
@gerxyuan you can use predict_model without passing data parameter and it will print a table of metrics on test dataset (which is separated when you run setup).

See more details : https://www.pycaret.org/predict-model

**Comment by gerxyuan** [comment]
Thank you! And  I asked the wrong question, actually my question should have been how to get AUC of prediction on unseen data(or new data)?

**Comment by DogarXu** [comment]
The same question

**Comment by gerxyuan** [comment]
> The same question
sorry,
predict_model(final_rf, data=data_unseen) ?
it print a table without AUC
Thank you.

**Comment by pycaret** [comment]
@gerxyuan predict_model appends two new columns to dataset. Label and Score. Label contains prediction (1 or 0) and Score contains probabilities.
