### ISSUE TITLE
The Kernel appears to have died. It will restart automatically. Classification. 

### ISSUE THREAD

**Issue by fjehlik** [pycaret/pycaret#1414]
**Describe the bug**

Howdy folks, I am also using Pycaret 2.3.1, Ubuntu 20.04, Anaconda Navigator 2.0.3 installation, and setup an environment solely with Pycaret (conda install pycaret[full] via the terminal). I am having the exact same issue with Jupyter/Jupyter lab that was posted in another issue thread that was closed. While running Jupyter, it randomly stops the kernel and gives the same error so that I can never complete running the code. I am using the Pycaret classification module. Long time Pycaret user, this problem is new. Unfortunately I can no longer complete any runs as it will always stop randomly during the code execution.  

**To Reproduce**

```python
import os
import numpy as np
import pandas as pd
#from glob import glob
from pandas_profiling import ProfileReport

# Plotting libraries
import matplotlib.pyplot as plt

# Pycaret import classification module 
from pycaret.classification import * 

# Pycaret import classification module 
from pycaret.classification import * 

# Intialize the setup
clf = setup(df, target = 'label',
            train_size=0.8,    
            normalize=True,
            transformation=True,
            ignore_low_variance=True,
            remove_multicollinearity = True, # default threshold = 0.9
            feature_selection=True,
            #pca=True,
            session_id=1,
            fix_imbalance=True,  # SMOTE
            silent=True,
            use_gpu=True,
               )


```

**Expected behavior**

**Additional context**

**Versions**
Pycaret 2.3.1
Ubuntu 20.04
Anaconda Navigator 2.0.3 
Jupyter 6.4.0

<!--
Please run the following code snippet and paste the output here:
 
import pycaret
pycaret.__version__

**Comment by yanmc** [comment]
i met this situation too

**Comment by fjehlik** [comment]
I may have found a solution for my case, however, it is not particularly elegant. I uninstalled and reinstalled Anaconda a couple of times, but that didn't work. I then reinstalled Ubuntu 20.04 (without selecting the format drive option, just the erase and reinstall Ubuntu option), then reinstalled Anaconda, and that still didn't work. I then reinstalled Ubuntu 20.04 again, and this time selected the option of formatting the entire drive. After this, it appears to be working. 

Finding the corrupted kernel is above my Linux pay grade skills, so the only option that seemed to work for me was an entire Ubuntu format drive re-install. If you go this route, be careful to save any and all files you don't want eliminated. If anyone has come across this and has any other solutions I'd love to hear them~

**Comment by fjehlik** [comment]
...I may have spoken too soon. The kernel just died again at the end of a run. This is really frustrating!

**Comment by pycaret** [comment]
@fjehlik Can you strip out all the parameters from your `setup` and just pass mandatory parameters like `data`, `target`. You can also pass `silent` and `session_id` if you would like. This can help us isolate issue to one specific functionality.

How big is your dataset?

**Comment by fjehlik** [comment]
HI @pycaret, thank you for the follow-up, it is appreciated. The dataset is a highly imbalanced classification set, 64000 rows, ~75 columns (features, mixed numeric/categorical). 

As it stands it may be an issue with my motherboard and or motherboard/BIOS version/GPU fault rather than anything to do with Pycaret. I am currently trying to sort that out. Once I have the PC back I'll do some testing, if it has no issue will close it out, or, if it does I will strip per your request and send an update.

**Comment by wkuopt** [comment]
Since there hasn't been an update. I will close this issue.
