### ISSUE TITLE
ValueError: The Box-Cox transformation can only be applied to strictly positive data[BUG]

### ISSUE THREAD

**Issue by sgujjaABM** [pycaret/pycaret#1417]
Hi, I am using pycaret 2.3 for regression analysis, and get this error below: Can you please help? Thanks.
<img width="1201" alt="Screen Shot 2021-07-01 at 1 01 06 AM" src="https://user-images.githubusercontent.com/78435087/124068010-81f76600-da08-11eb-80c2-edbef73df681.png">
**Describe the bug**

**To Reproduce**

```python
lr = create_model('lr')
ValueError: The Box-Cox transformation can only be applied to strictly positive data
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by tvdboom** [comment]
Hi. The documentation says the following about target transformations:

'Box-cox' and 'yeo-johnson' methods are supported. Box-Cox requires input data to
be strictly positive, while Yeo-Johnson supports both positive or negative data.
When transform_target_method is 'box-cox' and target variable contains negative
values, method is internally forced to 'yeo-johnson' to avoid exceptions.

Can you check if you have negative values in the target column? If they do, the error makes sense, but the documentation is wrong, since it is not forcing the yeo-johnson method. If this is the case, try adding `transformation_method='yeo-johnson'` to the setup call. If you do not have negative values in the target column, it means somewhere in the pipeline the column is being transformed, which, looking at your selected parameters, should not happen. In that case we should dig deeper to see what is going on exactly.

**Comment by IncubatorShokuhou** [comment]
Would it be a good idea to just switch `box-cox` to `yeo-johnson` if there is non-positive data in target? 
Actually, In fact, the `yeo-johnson`  transformations on the positive line are equivalent to the generalised Box–Cox transformations ( according to the origin paper of `yeo-johnson`) [<sup>1</sup>](#refer-anchor-1).

<div id="refer-anchor-1"></div>
- [1] Johnson, Y. R. A. . (2000). A new family of power transformations to improve normality or symmetry. Biometrika, 87(4), 954-959.

**Comment by IncubatorShokuhou** [comment]
I think we may even just drop the `transformation_method`, and automatically choose the method according to the data of the target.

**Comment by sgujjaABM** [comment]
Hi, thank you for the reply. There are no negative values in the target column. The values range from 0 to 100, and is negatively skewed.

```
regr = setup(dataset, target = 'y',numeric_features = features,transform_target=True
top5 = compare_models(n_select = 5)
.
.
raise ValueError("The Box-Cox transformation can only be "
ValueError: The Box-Cox transformation can only be applied to strictly positive data
```

Setting transform_target_method='yeo-johnson', seemed to have worked for only 9 models, and low value of R2 on train data
```
regr = setup(dataset, target = 'y',numeric_features = features,transform_target=True,transform_target_method='yeo-johnson' )
top5 = compare_models(n_select = 5)
pull()
```
<img width="885" alt="Screen Shot 2021-07-01 at 10 36 13 PM" src="https://user-images.githubusercontent.com/78435087/124212323-c7756b00-dabc-11eb-8979-f036f35c6f0e.png">

To check these metrics on the train set using Random Forest Regressor from scikit-learn by log transforming my target variable using the formula: log10(max(target_variable)+1 - x) or log10(100 + 1 - x) 
 
```
x = data.drop('y',axis = 1)
y = data['y']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 123)
random_model = RandomForestRegressor().fit(x_train,y_train)
train_prediction = random_model.predict(x_train)
r2_score(y_train,train_prediction)
Out[107]: 0.9263066322724389
```
Attached is the input file for your reference.
[test_pycaret_input.csv](https://github.com/pycaret/pycaret/files/6751795/test_pycaret_input.csv)

Thanks for helping. Please let me know if I should create a new issue for this?

**Comment by IncubatorShokuhou** [comment]
> Hi, thank you for the reply. There are no negative values in the target column. The values range from 0 to 100, and is negatively skewed.
> 
> ```
> regr = setup(dataset, target = 'y',numeric_features = features,transform_target=True
> top5 = compare_models(n_select = 5)
> .
> .
> raise ValueError("The Box-Cox transformation can only be "
> ValueError: The Box-Cox transformation can only be applied to strictly positive data
> ```
> 
> Setting transform_target_method='yeo-johnson', seemed to have worked for only 9 models, and results in low value of R2 on train data
> 
> ```
> regr = setup(dataset, target = 'y',numeric_features = features,transform_target=True,transform_target_method='yeo-johnson' )
> top5 = compare_models(n_select = 5)
> pull()
> ```
> 
> <img alt="Screen Shot 2021-07-01 at 10 36 13 PM" width="885" src="https://user-images.githubusercontent.com/78435087/124212323-c7756b00-dabc-11eb-8979-f036f35c6f0e.png">
> 
> To check these metrics on the train set using Random Forest Regressor from scikit-learn by log transforming my target variable separately using the formula: log10(max(target_variable)+1 - x) or log10(100 + 1 - x)
> 
> ```
> x = data.drop('y',axis = 1)
> y = data['y']
> x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 123)
> random_model = RandomForestRegressor().fit(x_train,y_train)
> train_prediction = random_model.predict(x_train)
> r2_score(y_train,train_prediction)
> Out[107]: 0.9263066322724389
> ```
> 
> Attached is the original input file for your reference.
> [test_pycaret_input.csv](https://github.com/pycaret/pycaret/files/6751795/test_pycaret_input.csv)
> 
> Thanks for helping. Please let me know if I should create a new issue for this?

There are zeros in `y`, so Cox-Box (which requires all positive, not non-negative) cannot work on it.

**Comment by sgujjaABM** [comment]
Thank you. Can you please help me understand the discrepancy in R2 metric on the train set from running RF in pycaret vs. scikit-learn package? Is there anything I should be doing differently in my setup function?

**Comment by IncubatorShokuhou** [comment]
BTW, your data is so confusing. Thera are only 880 binary features, and many of them have only 0. I am quite confused if modeling on such data can work.

**Comment by IncubatorShokuhou** [comment]
> Thank you. Can you please help me understand the discrepancy in R2 metric on the train set from running RF in pycaret vs. scikit-learn package? Is there anything I should be doing differently in my setup function?

Pycaret will automatically split the dataset and execute K-fold by default, maybe that causes the different.

**Comment by IncubatorShokuhou** [comment]
All of your data should be `bin_numeric_features`. Also, `ignore_low_variance` may help you remove those all-zero features.
Again, your dataset is too special and confusing, and I am quite not sure how to make the prediction better, actually.

**Comment by sgujjaABM** [comment]
I can try with `bin_numeric_features` and `ignore_low_variance`, and also run setup with the same train and test data sets used in scikit-learn. Can you please confirm if this code below is correct for setup without splitting the data into train/test:

`regr = setup(data=train, target = 'y',test_data= test,ignore_low_variance=True,bin_numeric_features=features)`

Please see the link below to the paper using Pycaret's automML features for regression analysis on binary data:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7970465/

Thanks again.

**Comment by IncubatorShokuhou** [comment]
@sgujjaABM You do not have to split data in `setup`. You only need to split the train and test data before setup, and put the train data into setup, and test the final trained model on yout test dataset.
For example, you can do:
```python
data_seen = df[:4000]
data_unseen = df[4000:]
regr = setup(data=data_seen , target = 'y',ignore_low_variance=True,bin_numeric_features=features)
```

**Comment by IncubatorShokuhou** [comment]
I just notice that your` test_pycaret_input.csv` is different with the data you actually using. I thought all your features are 0-1, so I suggest you to use `bin_numeric_features`. If they are actually numeric_features ,your origin `setup` settings are right.

**Comment by sgujjaABM** [comment]
Hi, Sorry for the confusion - the first screenshot was on scaled data. However, everything that I am testing currently is using the same input file that I shared, and the features are binary:

test_pycaret_input.csv
<img width="682" alt="Screen Shot 2021-07-01 at 11 36 40 PM" src="https://user-images.githubusercontent.com/78435087/124217000-69995100-dac5-11eb-8e66-acd516329912.png">

```
dataset = pd.read_csv("test_pycaret_input.csv", sep=',')
response = 'y'
features = list(dataset.columns) 
features.remove(response) 
print(features)
regr = setup(dataset, target = 'y',bin_numeric_features = features,ignore_low_variance=True)
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/my-pycaret-env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
**KeyError: '0'**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/anaconda3/envs/my-pycaret-env/lib/python3.6/site-packages/pycaret/regression.py", line 646, in setup
    profile_kwargs=profile_kwargs,
  File "/home/ec2-user/anaconda3/envs/my-pycaret-env/lib/python3.6/site-packages/pycaret/internal/tabular.py", line 1331, in setup
    train_data = prep_pipe.fit_transform(train_data)
  File "/home/ec2-user/anaconda3/envs/my-pycaret-env/lib/python3.6/site-packages/sklearn/pipeline.py", line 367, in fit_transform
    Xt = self._fit(X, y, **fit_params_steps)
  File "/home/ec2-user/anaconda3/envs/my-pycaret-env/lib/python3.6/site-packages/sklearn/pipeline.py", line 296, in _fit
    **fit_params_steps[name])
  File "/home/ec2-user/anaconda3/envs/my-pycaret-env/lib/python3.6/site-packages/joblib/memory.py", line 352, in __call__
    return self.func(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/my-pycaret-env/lib/python3.6/site-packages/sklearn/pipeline.py", line 740, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/home/ec2-user/anaconda3/envs/my-pycaret-env/lib/python3.6/site-packages/pycaret/internal/preprocess.py", line 1238, in fit_transform
    hist, _ = np.histogram(data[i], bins="sturges")
  File "/home/ec2-user/anaconda3/envs/my-pycaret-env/lib/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/ec2-user/anaconda3/envs/my-pycaret-env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
**KeyError: '0'**
```
Using numeric_features:

```
regr = setup(dataset, target = 'y',numeric_features = features,ignore_low_variance=True)
top5 = compare_models(n_select = 5)
pull()
```
**R2 on train is 0.48**
<img width="1093" alt="Screen Shot 2021-07-01 at 11 49 58 PM" src="https://user-images.githubusercontent.com/78435087/124217836-10322180-dac7-11eb-9260-77947011ab8c.png">


Using scikit-learn:
```
data = pd.read_csv("test_pycaret_input.csv", sep=',')
x = data.drop('y',axis = 1)
y = data['y']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 123)
random_model = RandomForestRegressor().fit(x_train,y_train)
train_prediction = random_model.predict(x_train)
r2_score(y_train,train_prediction)
**Out[120]: 0.92**
```

**Comment by IncubatorShokuhou** [comment]
> x_test,y_train,y_test

Maybe your nativa rf model overfits. You should test your native rf model on x_test and caculate r2_score on y_test.

**Comment by sgujjaABM** [comment]
sorry for the late reply. yes, there is overfitting with the RF model on test data.
