### ISSUE TITLE
About exp.compare_models( ) function

### ISSUE THREAD

**Issue by mertcan-yukselsin** [pycaret/pycaret#1418]
Hello,

First of all, thank you for sharing such tool to the community! It has lots of good properties and I'm pretty sure that you guys will increase its performance more in future!

My question is about exp.compare_models( ) function. Because I'm using an hourly time series data having 400k rows, while searching for all models, it stucks at autoarima model. I couldn't see any part about removing some models while searching for the best one (for instance, I want to remove autoarima model). Is it possible (or will it be possible)? If so, can you give me some tips, or an example simple code please?

Thank you!

**Comment by Yard1** [comment]
@ngupta23 @mertcan-yukselsin Try `compare_models(exclude=["autoarima"])`
