### ISSUE TITLE
Should we just give up support for legacy  version of cuML? 

### ISSUE THREAD

**Issue by IncubatorShokuhou** [pycaret/pycaret#1419]
**Is your feature request related to a problem? Please describe.**
Should we just give up support for legacy  version of cuML (version under "21") and just switch to stable versions?
I am working on applying cuml on  `preprocess.py`, and I discover that there are so many `random forest` in `preprocess.py` 
, which means I have to judge the version of cuML nearly everywhere to resolve the keyword problem of random_state/seed (see https://github.com/pycaret/pycaret/issues/1394), which is too complex and puzzling.

**Describe the solution you'd like**
Give up support for legacy  version of rapids (including cuML/cuDF etc.) and switch to stable version.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by pycaret** [comment]
@Yard1 Any thoughts on this?

**Comment by Yard1** [comment]
@IncubatorShokuhou What would be the minimal version that you think we should support?

**Comment by IncubatorShokuhou** [comment]
21.06 I think, which is the first stable version, and most APIs are more consistent with sklearn (i.e. random seed in RF).

---Original---
From: "Antoni ***@***.***&gt;
Date: Fri, Jul 23, 2021 20:42 PM
To: ***@***.***&gt;;
Cc: "Hao ***@***.******@***.***&gt;;
Subject: Re: [pycaret/pycaret] Should we just give up support for legacy  version of cuML?  (#1419)




 
@IncubatorShokuhou What would be the minimal version that you think we should support?

**Comment by Yard1** [comment]
Does that cuml version support the sklearn version we have pinned?

**Comment by IncubatorShokuhou** [comment]
I haven't studied this issue in depth, but as far as I know, the API of the estimators in most recent versions of sklearn and cuML are relatively fixed, so there should be no significant inconsistancy.




---Original---
From: "Antoni ***@***.***&gt;
Date: Fri, Jul 23, 2021 21:34 PM
To: ***@***.***&gt;;
Cc: "Hao ***@***.******@***.***&gt;;
Subject: Re: [pycaret/pycaret] Should we just give up support for legacy  version of cuML?  (#1419)




 
Does that cuml version support the sklearn version we have pinned?
