### ISSUE TITLE
Request for adding correlation techniques in preprocessing and recommendation techniques to add in association rule mining module.

### ISSUE THREAD

**Issue by sathishkumar999** [pycaret/pycaret#142]
Please add some more correlation techniques to find strengthen between the features in preprocessing.
1.karl Pearson correlation.(relation between two numeric features)
2.spearmen rank correlation.(relation between more than two numeric features)
3.Chi-square correlation.(relation between categorical features)
4.Biserial correlation.(relation between numerical and categorical).

And also add some more association rule mining techniques FP tree,collaborative and content based filtering.and also an option for minimum and maximum number of products to recommend after training the module.

**Comment by pycaret** [comment]
@sathishkumar369 Hi Satish. Thanks for all the suggestions. Wonderful ideas. Please feel free to submit a PR on dev-1.0.1 branch. I would particularly be more interested for enhancements in association rule module. Happy to talk further.

Thanks.

**Comment by zhere** [comment]
Wonderful ideas，Hope to use this function as soon as possible 。

**Comment by ngupta23** [comment]
@tvdboom @moezali1 - Is this still needed after the upgrades made to 3.0.0 preprocessing?

**Comment by tvdboom** [comment]
Let's close it since it's an old threat. OP can create a new issue if he thinks preprocessing in 3.0 requires extra techniques.
