### ISSUE TITLE
[BUG]Azure deployment error - 

### ISSUE THREAD

**Issue by jaehyunshinML** [pycaret/pycaret#1427]
**Describe the bug**
Followed Regression Tutorial (REG102)  and tried to deploy to Azure cloud but i got an error. 

It wokred perfectly on the local.

when I run 

deploy_model(model = tuned_lasso, model_name = 'lasso', platform = 'azure', authentication = {'container' : AZURE_STORAGE_CONNECTION_STRING})

this commend I've got

 'NoneType' object has no attribute 'rstrip'

Thanks!

**Comment by ngupta23** [comment]
Did you provide your actual connection string?

**Comment by jaehyunau** [comment]
Yes i did ! Copied from my azure storage
