### ISSUE TITLE
Set up Issue

### ISSUE THREAD

**Issue by robert-hoyt** [pycaret/pycaret#144]
I am trying to upload and analyze the heart prediction dataset. If I run it via a path from my computer it starts the setup and then stops and gives an error message. 
If I run it via get_data from your repository I get a different error message. The code is below, followed by the error message. 

from pycaret.datasets import get_data
data = get_data('heart_disease') 
pycaret.classification import *
exp1 = setup(heart_disease, target = 'Disease')

NameError                                 Traceback (most recent call last)
<ipython-input-24-ddaabdcfc4f3> in <module>
      1 from pycaret.classification import *
----> 2 exp1 = setup(heart_disease, target = 'Disease')

NameError: name 'heart_disease' is not defined

I thought I defined it when I uploaded the dataset

**Comment by DaGuT** [comment]
it should be `exp1 = setup(data, target = 'Disease')`

Your 'heart_disease' is not defined, you save it to 'data' variable instead.

**Comment by robert-hoyt** [comment]
I now realize that instead of setup(heart_disease, target = 'Disease') it should be
setup(data, target = 'Disease'). It generates another error message

  |   |  
-- | -- | --

Initiated | . . . . . . . . . . . . . . . . . . | 15:28:56
Status | . . . . . . . . . . . . . . . . . . | Preparing Data for Modeling
ETC | . . . . . . . . . . . . . . . . . . | Calculating ETC

**Comment by DaGuT** [comment]
If you have macos:

1. install brew ( [brew home page](https://brew.sh/index_ru) ). There is just 1 command, but I cant copy it here as my antivirus blocks the page the moment I paste it.
2. install `brew install libomp` 
3. and then install `pip install lightgbm` again.

___

Sorry, I dont know any easier way to install libomp, so you need to install brew package manager :\

**Comment by robert-hoyt** [comment]
That commands gives this error. I can try to find the brew package manager

  File "<ipython-input-1-0034d6b14513>", line 1
    homebrew install libomp
                   ^
SyntaxError: invalid syntax

**Comment by DaGuT** [comment]
I provided a link with brew (check point 1)

**Comment by robert-hoyt** [comment]
I was able to install brew in the terminal and lipomp. I now have it working in Jupyter Notebook and Google Colab but with slightly different performance parameters for unclear reasons. I got really good results performing classification in RapidMiner so wanted to compare it with what I got using PyCaret, Thanks for your help
