### ISSUE TITLE
[BUG] save_model saves only the pipeline. No associated data or metrics are stored

### ISSUE THREAD

**Issue by skannan-maf** [pycaret/pycaret#1440]
**Describe the bug**

It looks like load_model() only saves the pipeline object and not the "holdout" and "training data" associated with it or any other training metric. For e.g. it is not possible to run "predict_model", if I individually load the model separately to examine what its performance was on the holdout set etc.

**To Reproduce**

Load a saved model in a separate notebook and then run "predict_model(loaded_model)" to examine the holdout data predictions and you can see it errs out

```python
a_model = load_model('model_v1')
predict_model(a_model) # errors out because nothing related to training is stored in the model object
```

**Expected behavior**

The loaded model object should have a way to inspect training errors or test error metrics. And of course the associated data would also be good to have.

**Additional context**

**Versions**
2.3.1

</details>

**Comment by Yard1** [comment]
That is expected behavior. Saving data with the model would inflate it massively. You can run `setup()` again with the same data and then use the loaded model in this manner.

**Comment by skannan-maf** [comment]
Oh.. okay.. But I will not even know what was training and what was test in the data, right? I can use it for prediction without a doubt... But I would not have access to any metrics or any info on training... Thats my bother... But if thats by design, its okay then... Thanks!
