### ISSUE TITLE
Set a key when deploying and loading models from AWS

### ISSUE THREAD

**Issue by dalmad2** [pycaret/pycaret#1443]
**Is your feature request related to a problem? Please describe.**
Currently, I can't give a key when deploying and loading models from AWS. A key is the model path. If a model shouldn't be saved in a root AWS S3 folder, a key/path must be assigned. But, the current PyCaret doesn't support it.

**Describe the solution you'd like**
If you look at the file, pycaret.internal.persistence, and line number 155,  you will see `key = f"{model_name}.pkl"`.
If this is simply replaced with something like
```
if authentication.get("key"):
    key = authentication.get("key")
else:
    key = f"{model_name}.pkl"
```
and change the documentation, the problem will be solved.

**Additional context**
The company I work at has too many S3 buckets. The company wants to avoid creating more S3 buckets if possible. If I can only deploy a model in a root S3 folder, I will end up with deploying many models in one bucket or categorizing models and deploying them in different folders which I want to avoid.

**Comment by wkuopt** [comment]
Being able to specify the S3 path is definitely very useful. We can collaborate on this :)

**Comment by pycaret** [comment]
@wkuopt Thank you so much for working on this. :) 

@dalmad2 Thanks for bringing this up.
