### ISSUE TITLE
[BUG] Optuna tuning always maximizes metric

### ISSUE THREAD

**Issue by georgeblck** [pycaret/pycaret#1444]
**Describe the bug**
I was using `tune_model` with the search library optuna and the results were getting worse. I thought it was because of overfitting but now found a possible bug that would explain the results.

The corresponding code-bug that I found is [here](https://github.com/pycaret/pycaret/blob/c76f4b7699474bd16a2e2a6d0f52759ae29898b6/pycaret/internal/tabular.py#L4272) (for regression). The `direction` option in `optuna.create_study( direction="maximize", sampler=sampler, pruner=pruner)` should not always be maximize but changed corresponding to the used metric in the `tune_model()`

**To Reproduce**

```python
import numpy as np
EPSILON = 1e-10

def _error(actual: np.ndarray, predicted: np.ndarray):
    """ Simple error """
    return actual - predicted

def _percentage_error(actual: np.ndarray, predicted: np.ndarray):
    """
    Percentage error

    Note: result is NOT multiplied by 100
    """
    return _error(actual, predicted) / (actual + EPSILON)

def mapeReverse(actual: np.ndarray, predicted: np.ndarray):
    """
    Mean Absolute Percentage Error

    Properties:
        + Easy to interpret
        + Scale independent
        - Biased, not symmetric
        - Undefined when actual[t] == 0

    Note: result is NOT multiplied by 100
    """
    return 1.0-np.mean(np.abs(_percentage_error(actual, predicted)))

# Example is from pycaret website
from pycaret.datasets import get_data 
boston = get_data('boston') 
# Importing module and initializing setup 
from pycaret.regression import * 
reg1 = setup(data = boston, target = 'medv',session_id = 1991)


# Add custom reversed MAPE-metric so that maximizing is sensible
add_metric('mapeRev', 'MAPErev', mapeReverse, greater_is_better=True)
# train a decision tree model
lgbm = create_model('lightgbm')
# tune hyperparameters with optuna and normal MAPE
tuned_once = tune_model(lgbm,search_library="optuna",optimize = 'MAPE')

# Tune with reversed MAPE --> results are better --> tuning works as it should
tuned_twice = tune_model(lgbm,search_library="optuna",optimize = 'mapeRev')
```

**Expected behavior**
Both functions should have similar results. 

**Versions**
<details>

'2.3.1'
</details>

**Comment by Yard1** [comment]
Thanks, this is indeed wrong.

**Comment by Yard1** [comment]
@georgeblck @pycaret Turns out I was wrong, and this is working correctly. The direction has to be set to always maximize, because the scorer function will automatically flip the sign if `greater_is_better=False`. As for why your two functions don't have similar results, I imagine it's due to the small number of samples.
