### ISSUE TITLE
`load_model` won't work with AWS Lambda

### ISSUE THREAD

**Issue by sot232** [pycaret/pycaret#1447]
**Is your feature request related to a problem? Please describe.**
When using AWS Lambda, `load_model` doesn't work. 
The problems are caused by:
- Saving a model file locally

`load_model` saves a pkl file locally, then it loads the model. AWS Lambda only allocates 512MB disk space when saving files. If you have large size models which exceed 512 MB, you will get error messages.

As a temporary fix, I load PyCaret models by using `joblib` and `s3fs` modules. (For more information, see the answer introducing `S3FileSystem` in https://stackoverflow.com/questions/48964181/how-to-load-a-pickle-file-from-s3-to-use-in-aws-lambda) `s3fs` allows you to load pkl files without saving.

**Describe the solution you'd like**
A clear and concise description of what you want to happen, ideally taking into consideration the existing toolbox design, classes and methods.
- Avoiding saving an actual copy of pkl file in the environment by using something like S3FileSystem

**Comment by sot232** [comment]
I don't know how to participate in an open-source project. If you guys are okay, I would like to fix this problem.

**Comment by wkuopt** [comment]
Hey @sot232, not sure if I got your request clearly - you can use the deploy_model function (https://pycaret.org/deploy-model/) for AWS S3, and then load the model to lambda with your method?

**Comment by sot232** [comment]
@wkuopt Thank you for your comment.

I tested this out. If you upload any models through `deploy_model` and load models through `load_model`, you can load models in AWS Lambda. However, if you deal with large size models which exceed 512 MB, this won't work because of the Lambda limitation (/tmp directory storage is limited to 512MB. https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html) I will revise my initial request.

**Comment by wkuopt** [comment]
AFAIK, the storage limit is about the lambda deployment package and the lambda layers. If you save models on S3, then this would not be an issue. The same goes for the library that you want to install :) Also there is also the EFS option now: https://aws.amazon.com/blogs/compute/using-amazon-efs-for-aws-lambda-in-your-serverless-applications/

**Comment by sot232** [comment]
@wkuopt Thank you for your reply. I still think `load_model` doesn't work if the model size is too big. (i.e. model size > 9 GB) This may be an issue with Lambda. I am closing this ticket. Thank you again.
