### ISSUE TITLE
Catboost's Categorical feature to numeric conversion

### ISSUE THREAD

**Issue by lokesharya99** [pycaret/pycaret#1449]
**Pycaret convert categorical variable to one hot matrix, So how does it uses catboost feature of categorical to numeric conversion ?**

In the pycaret documentation it is mentioned that when preprocessing is set to true, in that case pycaret converts all categorical feature to one hot matrix. 

In Catboost documentation it is mentioned that when passing data to catboost, no preprocessing of categorical features required. Catboost uses some algo to convert categorical feature to numeric instead of converting it to one hot matrix, which can be controlled by  parameter one hot max size, which means when we set one hot max size to 3 then all the categorical feature unique values less than 3 will be converted to one hot matrix and above 3 will be converted to numeric which controls over fitting of the model quite well.

I have been using pycaret since a month now and catboost almost 2 years now. Numeric conversion of categorical feature is the one of the best feature of catboost which I haven't noticed pycaret saying it does that.

In the use of pycaret with categorical data noticed that catboost is not coming out to be best model which very unlikely. Hence curious if separate treatment for catboost is already there or not.

Thank you

**Comment by IncubatorShokuhou** [comment]
As far as I can see, you are right. In the preprocessing step, the categorical feature are encoded by one-hot encoder, and that do will influence the performance of catboost.

**Comment by IncubatorShokuhou** [comment]
BTW, do you know how to transform features using catboost and fit data with other method? If that is possible, maybe we are able to add a new preprocessing method to PyCaret. @lokesharya99

**Comment by lokesharya99** [comment]
I'm not exactly able to understand what actually catboost it doing, but they have mentioned their technique on the website.
[https://catboost.ai/docs/concepts/algorithm-main-stages_cat-to-numberic.html](url)

Catboost is doing it internally, so i'm not sure if it would be possible to get data out of it directly, we would have go into catboost code to access this preprocessing.

**Comment by Yard1** [comment]
There is a catboost encoder in category_encoders package.

**Comment by lokesharya99** [comment]
Thank you, @Yard1 so can we specify this encoding in pycaret using any argument?

**Comment by Yard1** [comment]
No, not yet. But it should be possible in the next major release (date pending).

**Comment by tvdboom** [comment]
Yes, the new release will contain the possibility to choose with which encoder algorithm to encode the categorical columns.
