### ISSUE TITLE
Errors faced while installing PyCaret- Catboost/VS installer stopped

### ISSUE THREAD

**Issue by rijesh123** [pycaret/pycaret#145]
[err installing pycaret.docx](https://github.com/pycaret/pycaret/files/4641040/err.installing.pycaret.docx)
I've attached errors that I am facing while installing PyCaret.
Please help how to proceed further.

**Comment by DaGuT** [comment]
install pycaret with `pip install https://github.com/pycaret/pycaret/archive/dev-1.0.1.zip`

**Comment by rijesh123** [comment]
@DaGuT, Thanks for quick reply.

Tried >> pip install https://github.com/pycaret/pycaret/archive/dev-1.0.1.zip
but still I am facing below error.
Previous I also tried to install "Microsoft Visual C++ 14.0" but faced issues as shown in the error doc attached.

    copying thinc\neural\_classes\maxout.py -> build\lib.win32-3.7\thinc\neural\
_classes
    copying thinc\neural\_classes\mish.py -> build\lib.win32-3.7\thinc\neural\_c
lasses
    copying thinc\neural\_classes\model.py -> build\lib.win32-3.7\thinc\neural\_
classes
    copying thinc\neural\_classes\multiheaded_attention.py -> build\lib.win32-3.
7\thinc\neural\_classes
    copying thinc\neural\_classes\relu.py -> build\lib.win32-3.7\thinc\neural\_c
lasses
    copying thinc\neural\_classes\resnet.py -> build\lib.win32-3.7\thinc\neural\
_classes
    copying thinc\neural\_classes\rnn.py -> build\lib.win32-3.7\thinc\neural\_cl
asses
    copying thinc\neural\_classes\selu.py -> build\lib.win32-3.7\thinc\neural\_c
lasses
    copying thinc\neural\_classes\softmax.py -> build\lib.win32-3.7\thinc\neural
\_classes
    copying thinc\neural\_classes\static_vectors.py -> build\lib.win32-3.7\thinc
\neural\_classes
    copying thinc\neural\_classes\__init__.py -> build\lib.win32-3.7\thinc\neura
l\_classes
    creating build\lib.win32-3.7\thinc\extra\_vendorized
    copying thinc\extra\_vendorized\keras_datasets.py -> build\lib.win32-3.7\thi
nc\extra\_vendorized
    copying thinc\extra\_vendorized\keras_data_utils.py -> build\lib.win32-3.7\t
hinc\extra\_vendorized
    copying thinc\extra\_vendorized\keras_generic_utils.py -> build\lib.win32-3.
7\thinc\extra\_vendorized
    copying thinc\extra\_vendorized\__init__.py -> build\lib.win32-3.7\thinc\ext
ra\_vendorized
    creating build\lib.win32-3.7\thinc\extra\wrapt
    copying thinc\extra\wrapt\decorators.py -> build\lib.win32-3.7\thinc\extra\w
rapt
    copying thinc\extra\wrapt\importer.py -> build\lib.win32-3.7\thinc\extra\wra
pt
    copying thinc\extra\wrapt\wrappers.py -> build\lib.win32-3.7\thinc\extra\wra
pt
    copying thinc\extra\wrapt\__init__.py -> build\lib.win32-3.7\thinc\extra\wra
pt
    copying thinc\linalg.pyx -> build\lib.win32-3.7\thinc
    copying thinc\structs.pyx -> build\lib.win32-3.7\thinc
    copying thinc\typedefs.pyx -> build\lib.win32-3.7\thinc
    copying thinc\cpu.pxd -> build\lib.win32-3.7\thinc
    copying thinc\linalg.pxd -> build\lib.win32-3.7\thinc
    copying thinc\structs.pxd -> build\lib.win32-3.7\thinc
    copying thinc\typedefs.pxd -> build\lib.win32-3.7\thinc
    copying thinc\__init__.pxd -> build\lib.win32-3.7\thinc
    copying thinc\compile_time_constants.pxi -> build\lib.win32-3.7\thinc
    copying thinc\linalg.cpp -> build\lib.win32-3.7\thinc
    copying thinc\structs.cpp -> build\lib.win32-3.7\thinc
    copying thinc\typedefs.cpp -> build\lib.win32-3.7\thinc
    copying thinc\linear\avgtron.pyx -> build\lib.win32-3.7\thinc\linear
    copying thinc\linear\features.pyx -> build\lib.win32-3.7\thinc\linear
    copying thinc\linear\linear.pyx -> build\lib.win32-3.7\thinc\linear
    copying thinc\linear\serialize.pyx -> build\lib.win32-3.7\thinc\linear
    copying thinc\linear\sparse.pyx -> build\lib.win32-3.7\thinc\linear
    copying thinc\linear\avgtron.pxd -> build\lib.win32-3.7\thinc\linear
    copying thinc\linear\features.pxd -> build\lib.win32-3.7\thinc\linear
    copying thinc\linear\serialize.pxd -> build\lib.win32-3.7\thinc\linear
    copying thinc\linear\sparse.pxd -> build\lib.win32-3.7\thinc\linear
    copying thinc\linear\__init__.pxd -> build\lib.win32-3.7\thinc\linear
    copying thinc\linear\avgtron.cpp -> build\lib.win32-3.7\thinc\linear
    copying thinc\linear\features.cpp -> build\lib.win32-3.7\thinc\linear
    copying thinc\linear\linear.cpp -> build\lib.win32-3.7\thinc\linear
    copying thinc\linear\serialize.cpp -> build\lib.win32-3.7\thinc\linear
    copying thinc\linear\sparse.cpp -> build\lib.win32-3.7\thinc\linear
    copying thinc\neural\ops.pyx -> build\lib.win32-3.7\thinc\neural
    copying thinc\neural\optimizers.pyx -> build\lib.win32-3.7\thinc\neural
    copying thinc\neural\_aligned_alloc.pyx -> build\lib.win32-3.7\thinc\neural
    copying thinc\neural\cpu.pxd -> build\lib.win32-3.7\thinc\neural
    copying thinc\neural\ops.pxd -> build\lib.win32-3.7\thinc\neural
    copying thinc\neural\__init__.pxd -> build\lib.win32-3.7\thinc\neural
    copying thinc\neural\ops.cpp -> build\lib.win32-3.7\thinc\neural
    copying thinc\neural\optimizers.cpp -> build\lib.win32-3.7\thinc\neural
    copying thinc\neural\_aligned_alloc.cpp -> build\lib.win32-3.7\thinc\neural
    copying thinc\neural\_custom_kernels.cu -> build\lib.win32-3.7\thinc\neural
    copying thinc\neural\_murmur3.cu -> build\lib.win32-3.7\thinc\neural
    copying thinc\extra\cache.pyx -> build\lib.win32-3.7\thinc\extra
    copying thinc\extra\eg.pyx -> build\lib.win32-3.7\thinc\extra
    copying thinc\extra\mb.pyx -> build\lib.win32-3.7\thinc\extra
    copying thinc\extra\search.pyx -> build\lib.win32-3.7\thinc\extra
    copying thinc\extra\cache.pxd -> build\lib.win32-3.7\thinc\extra
    copying thinc\extra\eg.pxd -> build\lib.win32-3.7\thinc\extra
    copying thinc\extra\mb.pxd -> build\lib.win32-3.7\thinc\extra
    copying thinc\extra\search.pxd -> build\lib.win32-3.7\thinc\extra
    copying thinc\extra\__init__.pxd -> build\lib.win32-3.7\thinc\extra
    copying thinc\extra\cache.cpp -> build\lib.win32-3.7\thinc\extra
    copying thinc\extra\eg.cpp -> build\lib.win32-3.7\thinc\extra
    copying thinc\extra\mb.cpp -> build\lib.win32-3.7\thinc\extra
    copying thinc\extra\search.cpp -> build\lib.win32-3.7\thinc\extra
    running build_ext
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for V
isual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
    ERROR: Failed building wheel for thinc
    Running setup.py clean for thinc
    Building wheel for blis (setup.py): started
    Building wheel for blis (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptool
s, tokenize; sys.argv[0] = '"'"'C:\\Users\\Dell\\AppData\\Local\\Temp\\pip-insta
ll-e2xdq17k\\blis\\setup.py'"'"'; __file__='"'"'C:\\Users\\Dell\\AppData\\Local\
\Temp\\pip-install-e2xdq17k\\blis\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"
'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close
();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Dell\
AppData\Local\Temp\pip-wheel-it2b8swp'
         cwd: C:\Users\Dell\AppData\Local\Temp\pip-install-e2xdq17k\blis\
    Complete output (21 lines):
    BLIS_COMPILER? None
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\blis
    copying blis\about.py -> build\lib.win32-3.7\blis
    copying blis\benchmark.py -> build\lib.win32-3.7\blis
    copying blis\__init__.py -> build\lib.win32-3.7\blis
    creating build\lib.win32-3.7\blis\tests
    copying blis\tests\common.py -> build\lib.win32-3.7\blis\tests
    copying blis\tests\test_dotv.py -> build\lib.win32-3.7\blis\tests
    copying blis\tests\test_gemm.py -> build\lib.win32-3.7\blis\tests
    copying blis\tests\__init__.py -> build\lib.win32-3.7\blis\tests
    copying blis\cy.pyx -> build\lib.win32-3.7\blis
    copying blis\py.pyx -> build\lib.win32-3.7\blis
    copying blis\cy.pxd -> build\lib.win32-3.7\blis
    copying blis\__init__.pxd -> build\lib.win32-3.7\blis
    running build_ext
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for V
isual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
    ERROR: Failed building wheel for blis
    Running setup.py clean for blis
    Building wheel for srsly (setup.py): started
    Building wheel for srsly (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptool
s, tokenize; sys.argv[0] = '"'"'C:\\Users\\Dell\\AppData\\Local\\Temp\\pip-insta
ll-e2xdq17k\\srsly\\setup.py'"'"'; __file__='"'"'C:\\Users\\Dell\\AppData\\Local
\\Temp\\pip-install-e2xdq17k\\srsly\\setup.py'"'"';f=getattr(tokenize, '"'"'open
'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.clo
se();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Del
l\AppData\Local\Temp\pip-wheel-q61xregk'
         cwd: C:\Users\Dell\AppData\Local\Temp\pip-install-e2xdq17k\srsly\
    Complete output (71 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\srsly
    copying srsly\about.py -> build\lib.win32-3.7\srsly
    copying srsly\util.py -> build\lib.win32-3.7\srsly
    copying srsly\_json_api.py -> build\lib.win32-3.7\srsly
    copying srsly\_msgpack_api.py -> build\lib.win32-3.7\srsly
    copying srsly\_pickle_api.py -> build\lib.win32-3.7\srsly
    copying srsly\__init__.py -> build\lib.win32-3.7\srsly
    creating build\lib.win32-3.7\srsly\cloudpickle
    copying srsly\cloudpickle\cloudpickle.py -> build\lib.win32-3.7\srsly\cloudp
ickle
    copying srsly\cloudpickle\__init__.py -> build\lib.win32-3.7\srsly\cloudpick
le
    creating build\lib.win32-3.7\srsly\msgpack
    copying srsly\msgpack\exceptions.py -> build\lib.win32-3.7\srsly\msgpack
    copying srsly\msgpack\util.py -> build\lib.win32-3.7\srsly\msgpack
    copying srsly\msgpack\_ext_type.py -> build\lib.win32-3.7\srsly\msgpack
    copying srsly\msgpack\_msgpack_numpy.py -> build\lib.win32-3.7\srsly\msgpack

    copying srsly\msgpack\_version.py -> build\lib.win32-3.7\srsly\msgpack
    copying srsly\msgpack\__init__.py -> build\lib.win32-3.7\srsly\msgpack
    creating build\lib.win32-3.7\srsly\tests
    copying srsly\tests\test_json_api.py -> build\lib.win32-3.7\srsly\tests
    copying srsly\tests\test_msgpack_api.py -> build\lib.win32-3.7\srsly\tests
    copying srsly\tests\test_pickle_api.py -> build\lib.win32-3.7\srsly\tests
    copying srsly\tests\__init__.py -> build\lib.win32-3.7\srsly\tests
    creating build\lib.win32-3.7\srsly\ujson
    copying srsly\ujson\__init__.py -> build\lib.win32-3.7\srsly\ujson
    creating build\lib.win32-3.7\srsly\tests\cloudpickle
    copying srsly\tests\cloudpickle\cloudpickle_file_test.py -> build\lib.win32-
3.7\srsly\tests\cloudpickle
    copying srsly\tests\cloudpickle\testutils.py -> build\lib.win32-3.7\srsly\te
sts\cloudpickle
    copying srsly\tests\cloudpickle\__init__.py -> build\lib.win32-3.7\srsly\tes
ts\cloudpickle
    creating build\lib.win32-3.7\srsly\tests\msgpack
    copying srsly\tests\msgpack\test_buffer.py -> build\lib.win32-3.7\srsly\test
s\msgpack
    copying srsly\tests\msgpack\test_case.py -> build\lib.win32-3.7\srsly\tests\
msgpack
    copying srsly\tests\msgpack\test_except.py -> build\lib.win32-3.7\srsly\test
s\msgpack
    copying srsly\tests\msgpack\test_extension.py -> build\lib.win32-3.7\srsly\t
ests\msgpack
    copying srsly\tests\msgpack\test_format.py -> build\lib.win32-3.7\srsly\test
s\msgpack
    copying srsly\tests\msgpack\test_limits.py -> build\lib.win32-3.7\srsly\test
s\msgpack
    copying srsly\tests\msgpack\test_memoryview.py -> build\lib.win32-3.7\srsly\
tests\msgpack
    copying srsly\tests\msgpack\test_newspec.py -> build\lib.win32-3.7\srsly\tes
ts\msgpack
    copying srsly\tests\msgpack\test_numpy.py -> build\lib.win32-3.7\srsly\tests
\msgpack
    copying srsly\tests\msgpack\test_pack.py -> build\lib.win32-3.7\srsly\tests\
msgpack
    copying srsly\tests\msgpack\test_read_size.py -> build\lib.win32-3.7\srsly\t
ests\msgpack
    copying srsly\tests\msgpack\test_seq.py -> build\lib.win32-3.7\srsly\tests\m
sgpack
    copying srsly\tests\msgpack\test_sequnpack.py -> build\lib.win32-3.7\srsly\t
ests\msgpack
    copying srsly\tests\msgpack\test_stricttype.py -> build\lib.win32-3.7\srsly\
tests\msgpack
    copying srsly\tests\msgpack\test_subtype.py -> build\lib.win32-3.7\srsly\tes
ts\msgpack
    copying srsly\tests\msgpack\test_unpack.py -> build\lib.win32-3.7\srsly\test
s\msgpack
    copying srsly\tests\msgpack\__init__.py -> build\lib.win32-3.7\srsly\tests\m
sgpack
    creating build\lib.win32-3.7\srsly\tests\ujson
    copying srsly\tests\ujson\test_ujson.py -> build\lib.win32-3.7\srsly\tests\u
json
    copying srsly\tests\ujson\__init__.py -> build\lib.win32-3.7\srsly\tests\ujs
on
    copying srsly\msgpack\_packer.pyx -> build\lib.win32-3.7\srsly\msgpack
    copying srsly\msgpack\_unpacker.pyx -> build\lib.win32-3.7\srsly\msgpack
    copying srsly\msgpack\buff_converter.h -> build\lib.win32-3.7\srsly\msgpack
    copying srsly\msgpack\pack.h -> build\lib.win32-3.7\srsly\msgpack
    copying srsly\msgpack\pack_template.h -> build\lib.win32-3.7\srsly\msgpack
    copying srsly\msgpack\sysdep.h -> build\lib.win32-3.7\srsly\msgpack
    copying srsly\msgpack\unpack.h -> build\lib.win32-3.7\srsly\msgpack
    copying srsly\msgpack\unpack_define.h -> build\lib.win32-3.7\srsly\msgpack
    copying srsly\msgpack\unpack_template.h -> build\lib.win32-3.7\srsly\msgpack

    copying srsly\ujson\JSONtoObj.c -> build\lib.win32-3.7\srsly\ujson
    copying srsly\ujson\objToJSON.c -> build\lib.win32-3.7\srsly\ujson
    copying srsly\ujson\ujson.c -> build\lib.win32-3.7\srsly\ujson
    copying srsly\ujson\py_defines.h -> build\lib.win32-3.7\srsly\ujson
    copying srsly\ujson\version.h -> build\lib.win32-3.7\srsly\ujson
    running build_ext
    building 'srsly.msgpack._unpacker' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for V
isual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
    ERROR: Failed building wheel for srsly
    Running setup.py clean for srsly
  Failed to build cymem preshed murmurhash thinc blis srsly
  ERROR: pytest-astropy 0.8.0 requires pytest-cov>=2.0, which is not installed.
  ERROR: pytest-astropy 0.8.0 requires pytest-filter-subpackage>=0.1, which is n
ot installed.
  Installing collected packages: setuptools, wheel, cython, cymem, murmurhash, p
reshed, numpy, blis, wasabi, srsly, zipp, importlib-metadata, catalogue, plac, t
qdm, thinc
      Running setup.py install for cymem: started
      Running setup.py install for cymem: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setupto
ols, tokenize; sys.argv[0] = '"'"'C:\\Users\\Dell\\AppData\\Local\\Temp\\pip-ins
tall-e2xdq17k\\cymem\\setup.py'"'"'; __file__='"'"'C:\\Users\\Dell\\AppData\\Loc
al\\Temp\\pip-install-e2xdq17k\\cymem\\setup.py'"'"';f=getattr(tokenize, '"'"'op
en'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.c
lose();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users
\Dell\AppData\Local\Temp\pip-record-fe0rv09c\install-record.txt' --single-versio
n-externally-managed --prefix 'C:\Users\Dell\AppData\Local\Temp\pip-build-env-8l
lxudx5\overlay' --compile --install-headers 'C:\Users\Dell\AppData\Local\Temp\pi
p-build-env-8llxudx5\overlay\Include\cymem'
           cwd: C:\Users\Dell\AppData\Local\Temp\pip-install-e2xdq17k\cymem\
      Complete output (7 lines):
      running install
      running build
      running build_py
      package init file 'cymem\tests\__init__.py' not found (or not a regular fi
le)
      running build_ext
      building 'cymem.cymem' extension
      error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for
 Visual Studio": https://visualstudio.microsoft.com/downloads/
      ----------------------------------------
  ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\pytho
n.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\De
ll\\AppData\\Local\\Temp\\pip-install-e2xdq17k\\cymem\\setup.py'"'"'; __file__='
"'"'C:\\Users\\Dell\\AppData\\Local\\Temp\\pip-install-e2xdq17k\\cymem\\setup.py
'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace(
'"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"
'"'))' install --record 'C:\Users\Dell\AppData\Local\Temp\pip-record-fe0rv09c\in
stall-record.txt' --single-version-externally-managed --prefix 'C:\Users\Dell\Ap
pData\Local\Temp\pip-build-env-8llxudx5\overlay' --compile --install-headers 'C:
\Users\Dell\AppData\Local\Temp\pip-build-env-8llxudx5\overlay\Include\cymem' Che
ck the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\python.
exe' 'C:\ProgramData\Anaconda3\lib\site-packages\pip' install --ignore-installed
 --no-user --prefix 'C:\Users\Dell\AppData\Local\Temp\pip-build-env-8llxudx5\ove
rlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https
://pypi.org/simple -- setuptools wheel 'cython>=0.25' 'cymem>=2.0.2,<2.1.0' 'pre
shed>=3.0.2,<3.1.0' 'murmurhash>=0.28.0,<1.1.0' thinc==7.4.0 Check the logs for
full command output.

(base) C:\Users\Dell>

**Comment by DaGuT** [comment]
> Previous I also tried to install "Microsoft Visual C++ 14.0" but faced issues as shown in the error doc attached.

Em... You're supposed to install Visual Studio ( https://visualstudio.microsoft.com/ru/downloads/ ) when you catch that error. Are you sure you install it and not redistributable packages?

**Comment by rijesh123** [comment]
Thanks DaGuT.
Tried to install > vs_community__1952959766.1589753943.exe
It says VS Installer has stopped working.
So you say that I need to crack that first before getting on with PyCaret installation?

**Comment by DaGuT** [comment]
Yeah, for some reason you should do it. At least logs say so. And we should believe them and try their ideas.

**Comment by sriprad** [comment]
Hi ,
I am also facing the above error @rijesh123 Please let me know if you solved it. thanks

**Comment by DaGuT** [comment]
@sriprad have you tried installing visual studio?

**Comment by sriprad** [comment]
@DaGuT  thank you for the reply. yes i installed it. But it's throwing error just like above @rijesh123  posted with errors- like failed due to wheel Shap, Astropy and wordcloud.

**Comment by sriprad** [comment]
Building wheels for collected packages: wordcloud, shap, astropy
  Building wheel for wordcloud (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\p.sridharansrinivas\appdata\local\continuum\anaconda3\envs\work2\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\P.SridharanSrinivas\\AppData\\Local\\Temp\\pip-install-ua68mxsk\\wordcloud\\setup.py'"'"'; __file__='"'"'C:\\Users\\P.SridharanSrinivas\\AppData\\Local\\Temp\\pip-install-ua68mxsk\\wordcloud\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\P.SridharanSrinivas\AppData\Local\Temp\pip-wheel-00gkz5xx'
       cwd: C:\Users\P.SridharanSrinivas\AppData\Local\Temp\pip-install-ua68mxsk\wordcloud\
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\wordcloud
  copying wordcloud\color_from_image.py -> build\lib.win-amd64-3.8\wordcloud
  copying wordcloud\tokenization.py -> build\lib.win-amd64-3.8\wordcloud
  copying wordcloud\wordcloud.py -> build\lib.win-amd64-3.8\wordcloud
  copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-3.8\wordcloud
  copying wordcloud\_version.py -> build\lib.win-amd64-3.8\wordcloud
  copying wordcloud\__init__.py -> build\lib.win-amd64-3.8\wordcloud
  copying wordcloud\__main__.py -> build\lib.win-amd64-3.8\wordcloud
  copying wordcloud\stopwords -> build\lib.win-amd64-3.8\wordcloud
  copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-3.8\wordcloud
  UPDATING build\lib.win-amd64-3.8\wordcloud/_version.py
  set build\lib.win-amd64-3.8\wordcloud/_version.py to '1.7.0'
  running build_ext
  building 'wordcloud.query_integral_image' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
  Building wheel for shap (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\p.sridharansrinivas\appdata\local\continuum\anaconda3\envs\work2\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\P.SridharanSrinivas\\AppData\\Local\\Temp\\pip-install-ua68mxsk\\shap\\setup.py'"'"'; __file__='"'"'C:\\Users\\P.SridharanSrinivas\\AppData\\Local\\Temp\\pip-install-ua68mxsk\\shap\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\P.SridharanSrinivas\AppData\Local\Temp\pip-wheel-85_q90z7'
       cwd: C:\Users\P.SridharanSrinivas\AppData\Local\Temp\pip-install-ua68mxsk\shap\
  Complete output (63 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\shap
  copying shap\common.py -> build\lib.win-amd64-3.8\shap
  copying shap\datasets.py -> build\lib.win-amd64-3.8\shap
  copying shap\__init__.py -> build\lib.win-amd64-3.8\shap
  creating build\lib.win-amd64-3.8\shap\explainers
  copying shap\explainers\bruteforce.py -> build\lib.win-amd64-3.8\shap\explainers
  copying shap\explainers\explainer.py -> build\lib.win-amd64-3.8\shap\explainers
  copying shap\explainers\gradient.py -> build\lib.win-amd64-3.8\shap\explainers
  copying shap\explainers\kernel.py -> build\lib.win-amd64-3.8\shap\explainers
  copying shap\explainers\linear.py -> build\lib.win-amd64-3.8\shap\explainers
  copying shap\explainers\mimic.py -> build\lib.win-amd64-3.8\shap\explainers
  copying shap\explainers\partition.py -> build\lib.win-amd64-3.8\shap\explainers
  copying shap\explainers\permutation.py -> build\lib.win-amd64-3.8\shap\explainers
  copying shap\explainers\pytree.py -> build\lib.win-amd64-3.8\shap\explainers
  copying shap\explainers\sampling.py -> build\lib.win-amd64-3.8\shap\explainers
  copying shap\explainers\tree.py -> build\lib.win-amd64-3.8\shap\explainers
  copying shap\explainers\__init__.py -> build\lib.win-amd64-3.8\shap\explainers
  creating build\lib.win-amd64-3.8\shap\explainers\other
  copying shap\explainers\other\coefficent.py -> build\lib.win-amd64-3.8\shap\explainers\other
  copying shap\explainers\other\lime.py -> build\lib.win-amd64-3.8\shap\explainers\other
  copying shap\explainers\other\maple.py -> build\lib.win-amd64-3.8\shap\explainers\other
  copying shap\explainers\other\random.py -> build\lib.win-amd64-3.8\shap\explainers\other
  copying shap\explainers\other\treegain.py -> build\lib.win-amd64-3.8\shap\explainers\other
  copying shap\explainers\other\__init__.py -> build\lib.win-amd64-3.8\shap\explainers\other
  creating build\lib.win-amd64-3.8\shap\explainers\deep
  copying shap\explainers\deep\deep_pytorch.py -> build\lib.win-amd64-3.8\shap\explainers\deep
  copying shap\explainers\deep\deep_tf.py -> build\lib.win-amd64-3.8\shap\explainers\deep
  copying shap\explainers\deep\__init__.py -> build\lib.win-amd64-3.8\shap\explainers\deep
  creating build\lib.win-amd64-3.8\shap\plots
  copying shap\plots\bar.py -> build\lib.win-amd64-3.8\shap\plots
  copying shap\plots\colorconv.py -> build\lib.win-amd64-3.8\shap\plots
  copying shap\plots\colors.py -> build\lib.win-amd64-3.8\shap\plots
  copying shap\plots\decision.py -> build\lib.win-amd64-3.8\shap\plots
  copying shap\plots\dependence.py -> build\lib.win-amd64-3.8\shap\plots
  copying shap\plots\embedding.py -> build\lib.win-amd64-3.8\shap\plots
  copying shap\plots\force.py -> build\lib.win-amd64-3.8\shap\plots
  copying shap\plots\force_matplotlib.py -> build\lib.win-amd64-3.8\shap\plots
  copying shap\plots\image.py -> build\lib.win-amd64-3.8\shap\plots
  copying shap\plots\monitoring.py -> build\lib.win-amd64-3.8\shap\plots
  copying shap\plots\partial_dependence.py -> build\lib.win-amd64-3.8\shap\plots
  copying shap\plots\summary.py -> build\lib.win-amd64-3.8\shap\plots
  copying shap\plots\__init__.py -> build\lib.win-amd64-3.8\shap\plots
  creating build\lib.win-amd64-3.8\shap\benchmark
  copying shap\benchmark\experiments.py -> build\lib.win-amd64-3.8\shap\benchmark
  copying shap\benchmark\measures.py -> build\lib.win-amd64-3.8\shap\benchmark
  copying shap\benchmark\methods.py -> build\lib.win-amd64-3.8\shap\benchmark
  copying shap\benchmark\metrics.py -> build\lib.win-amd64-3.8\shap\benchmark
  copying shap\benchmark\models.py -> build\lib.win-amd64-3.8\shap\benchmark
  copying shap\benchmark\plots.py -> build\lib.win-amd64-3.8\shap\benchmark
  copying shap\benchmark\__init__.py -> build\lib.win-amd64-3.8\shap\benchmark
  creating build\lib.win-amd64-3.8\shap\plots\resources
  copying shap\plots\resources\bundle.js -> build\lib.win-amd64-3.8\shap\plots\resources
  copying shap\plots\resources\logoSmallGray.png -> build\lib.win-amd64-3.8\shap\plots\resources
  copying shap\tree_shap.h -> build\lib.win-amd64-3.8\shap
  running build_ext
  numpy.get_include() c:\users\p.sridharansrinivas\appdata\local\continuum\anaconda3\envs\work2\lib\site-packages\numpy\core\include
  building 'shap._cext' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for shap
  Running setup.py clean for shap

**Comment by sriprad** [comment]
@DaGuT  Microsoft Visual C++ is already installed not sure why it's giving error

**Comment by sriprad** [comment]
@DaGuT I have Developer Powershell for VS 2019

**Comment by sriprad** [comment]
Visual studio 2019

**Comment by DaGuT** [comment]
and you still have "Microsoft Visual C++ 14.0 is required"??

**Comment by sriprad** [comment]
yes that's what the error says. I am confused

**Comment by rijesh123** [comment]
@sriprad Download complete visual studio not just the buildtools

**Comment by rijesh123** [comment]
> should do it. At least logs say so. A



> Yeah, for some reason you should do it. At least logs say so. And we should believe them and try their ideas.

Yes. I reinstalled Visual studio and it worked. Thanks @DaGuT

**Comment by sriprad** [comment]
@rijesh123  Thanks. I installed completely but still it's an issue

**Comment by sriprad** [comment]
@rijesh123  can you please share the link for the visual studio to be downloaded? i downloaded from here
https://visualstudio.microsoft.com/

**Comment by rijesh123** [comment]
@sriprad: Yes that's correct. To install visual studio, I have also used the same link you shared.
See the your error message and try installing any related components if any
