### ISSUE TITLE
Support for better and more explicitly parallelization, including distributed

### ISSUE THREAD

**Issue by IncubatorShokuhou** [pycaret/pycaret#1450]
**Is your feature request related to a problem? Please describe.**
In current version of PyCaret, only a stand-alone version with/without GPU is supported.   

Actually, even in the current version, some conceptions related to parallelization is not so clear (as far as I am concerned). For example, in https://github.com/pycaret/pycaret/blob/master/pycaret/internal/tabular.py , there are variables like `n_jobs_param` and `_gpu_n_jobs_param`, which seems to indicate that PyCaret support multi gpu. But actually, all the `cuml` methods used in PyCaret now are all single-GPU implementation, which has nothing to do with multi-gpu.  

Meanwhile, many users are looking forward to a distributed version (`dask` is most frequently mentioned) of PyCaret, for example, https://github.com/pycaret/pycaret/issues/639 , https://github.com/pycaret/pycaret/issues/939 , https://github.com/pycaret/pycaret/issues/96 .  

So I am wondering if we can more explicitly reference to parallelism in `setup`, and implement different versions of parallelization using different libraries (i.e. `dask` , `cuml.dask`). Also, support for `dask.dataset` and `cudf` ,and parallelization in preprocessing may also be implemented under the a same framework.

**Describe the solution you'd like**
 - A more explicitly parallelization parameter in PyCaret. For example:
     - `local_cpu`, corresponding to current version without GPU.
     - `local_gpu`, corresponding to current version with GPU.
     - `distributed_cpu`, corresponding a version using `dask-ml` for distributed training. Also, an implementation that distribute each model to different cpu node is also possible. All we need is to pass the `dask client` into `setup` .
     - `distributed_gpu` , corresponding a version using `cuml.dask` for distributed training. Single node with multi GPU may also have to use a `dask CUDACluster`. Also pass `dask client` into `setup` .
   
 - Add support for `dask.dataframe` and `cudf`, which may need many detailed changes in preprocessing step.
 
 - Accelerate preprocessing methods that cost much time with `cuml` , `cudf` , ` dask-ml` or  `dask.dataframe`, in accordance with the above parameters.

**Describe alternatives you've considered**
Other distributed parallelization methods (i.e. `ray`) may also be alternative.

**Additional context**
NA

**Comment by moezali1** [comment]
This issue is now being moved to #2015
