### ISSUE TITLE
tune_model can support timeout, progress report

### ISSUE THREAD

**Issue by skannan-maf** [pycaret/pycaret#1452]
**Is your feature request related to a problem? Please describe.**
While running tune_model, I only see a statement saying "10 folds of N fits resulting in N*10" fits. I don't get to see how many fits actually completed. It is not clear how long should I wait.

**Describe the solution you'd like**
1. tune_model should support a timeout value - after which the API simply returns the best among the models run so far
2. tune_model needs to show progress as to how many fits have completed....
3. tune_model should show what is the current best MAPE or whatever criteria that the user specify reached and also the model that achieved it. It is better to log this in a file or in some form so that even if the user aborts tune_model, they do have some result in hand
4. tune_model should accept "n_jobs" as argument. Currently it uses a default of -1. Sometimes this is not preferred. So it will be great to have the user specify this
5. tune_model should be abortable in Jupyter without losing the kernel. Currently since this is multi-processing based, it is difficult to aboart an execution. We end up restarting jupyter and hence all the current variables are lost and the tune-model results (whatever accumulated so far) are also lost.

**Describe alternatives you've considered**
1. Stop/Restart jupyter and abort tuning without results 

**Additional context**

**Comment by Yard1** [comment]
As we are using various different tuning backends, most of the features proposed here would be very hard or impossible to implement. You can obtain extra information about trials with `tuner_verbose` parameter which controls the verbosity of the tuning backend. You can set the `n_jobs` parameter in `setup()`. Some tuning backends support timeouts and those can be passed through either kwargs or `fit_kwargs` in `tune_model`.

**Comment by skannan-maf** [comment]
Thank you for your inputs. 

I have set tuner_verbose() but still no messages on progress. It has been running for 2 hours now and I dont know how much is completed or how long i have to wait.

n_jobs -> Thanks for the info. I will use this.

Will check the tuner specific options. Perhaps they have something for me.

Meanwhile - If no work can be taken on this, you can close this one.

**Comment by Yard1** [comment]
You can consider using tune-sklearn or optuna backends as they are more advanced than the default scikit-learn one. Please refer to the documentation.

**Comment by skannan-maf** [comment]
Sure, I just read the recently filed bug on Optuna... i.e. it maximizes always. So I will check the tune-sklearn.

Truly appreciate your time on this and your suggestions. I m closing this now. Thanks!

**Comment by Yard1** [comment]
As a workaround for always maximization, you can define your custom error metrics as being negative. That way it will work properly.
