### ISSUE TITLE
Backward fill / Forward fill and interpolate with time for missing date values

### ISSUE THREAD

**Issue by sathishkumar999** [pycaret/pycaret#146]
Hi pycaret team...
I figure out that, In pycaret modules there is no option for making Imbalanced data into balanced one in classification. as we know there are many oversampling and under sampling techniques are there to make it balance, but in majority of the cases we use SMOTE module.  so that we can train the module equally for both "Yes and No" classes. which avoids inaccurate prediction on new data. parallelly, where we can increase precision and recall scores too.

I noticed that, while setup the module it can automatically fill the continues and categorical  missing features by using mean for numerical and mode for categorical. but there is no option for "date type" feature. for date type we use forward fill and backward fill or we use mean value between that missing features.
Example: 5,4,nan,6(date type)
In this case we fill this missing value with 4 or 6. or we fill it by using average between 4 and 6,which is 5.
please add this option in next release. where we use it in most of the time series forecasting projects.

**Comment by pycaret** [comment]
@sathishkumar369 Excellent points. 

I am tagging this issue as an enhancement. There are two points:

1. Add SMOTE functionality
2. Allow missing dates to be filled with backward fill or forward fill.

Thanks.

**Comment by sathishkumar369** [comment]
Not really missing dates. missing values corresponding to data type feature.
![Screenshot (183)](https://user-images.githubusercontent.com/40235632/83127881-4f3db880-a0f8-11ea-9369-7f4ae4119012.png)
![Screenshot (184)](https://user-images.githubusercontent.com/40235632/83127914-5a90e400-a0f8-11ea-818e-30b22b08713d.png)
![Screenshot (185)](https://user-images.githubusercontent.com/40235632/83127933-6381b580-a0f8-11ea-8b6f-ff04509a523a.png)

**Comment by ngupta23** [comment]
Since your example is referring to time series analysis, I wanted to let you know that this will be added to the time series module shortly. You can track the progress here: https://github.com/pycaret/pycaret/issues/1752.

I will close this Issue for now. We can track it in the link mentioned above.
