### ISSUE TITLE
[BUG] Could not build wheels for bottleneck which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by lucazav** [pycaret/pycaret#1461]
I'm trying to install PyCaret on my Windows 10 machine. I created a brand new conda environment with Python 3.6. Then I run the command: `pip install pycaret`. I'm getting the following error:

> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
>   ----------------------------------------
>   ERROR: Failed building wheel for bottleneck
> Failed to build bottleneck
> ERROR: Could not build wheels for bottleneck which use PEP 517 and cannot be installed directly

Any hint?

**Comment by ngupta23** [comment]
Check out the FAQs that have been pinned on the Issues pages. There is a similar post and solution there.

**Comment by lucazav** [comment]
Thank you @ngupta23 , I already installed the Build Tools to go ahead. But you shouldn't force the user to download these tools in order to compile stuff. You should provide the already compiled stuff to Windows users.

**Comment by Yard1** [comment]
@lucazav @ngupta23 PyCaret itself doesn't require anything to be compiled, but we cannot control the installation processes of our dependencies. This is out of our hands.

**Comment by pycaret** [comment]
@lucazav I think I figured out your problem. I can reproduce your issue as of yesterday in python=3.6 environment. 

The solution is to create a new conda environment with python=3.8 and the problem will go away :)

**Comment by lucazav** [comment]
It's better to specify this into the installation guide.

**Comment by pycaret** [comment]
@lucazav The problem is specific to few windows OS. Another solution is to install `bottleneck` through conda before installing PyCaret.

```
conda install bottleneck
pip install pycaret
```
