### ISSUE TITLE
[BUG] Kernel becomes dead when dealing with huge dataset using pycaret

### ISSUE THREAD

**Issue by deenam** [pycaret/pycaret#1463]
**Describe the bug**
i'm currently using a bigger dataset with shape as (1987726, 65). This is causing kernel to be dead half way through setup() function execution 

**To Reproduce**
Use a big data set of the order of (1987726, 65), 

from pycaret.classification  import *
reg1 = setup(data = data_to_train, target = 'rlf',categorical_features =cat_cols,numeric_features=num_cols,train_size=0.50)

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by pycaret** [comment]
@deenam How much memory you have on your system? 

Can you share the dataset so I can try to reproduce this? 

I have experimented on bigger datasets than this, without problems. So wondering if this has to do with memory?

**Comment by igorkf** [comment]
@deenam is this a regression or classification problem?   
I ask this because you import `classification` but you are saving the `setup` as `reg1`.   
The variable name is not a problem...but do you want to use regression?

**Comment by ngupta23** [comment]
Closing since this is a stale issue. Feel free to reopen is issue still exists.
