### ISSUE TITLE
How can i extract values of bi grams from PyCaret topic modeler?

### ISSUE THREAD

**Issue by aqibfayyaz** [pycaret/pycaret#1464]
i have trained PyCaret topic modeler using the pycaret documentation https://pycaret.readthedocs.io/en/latest/api/nlp.html#pycaret.nlp.get_topics

I am able to plot Bigrams using following code as mentioned in documentation

plot_model(plot = 'bigram',save = True)
Now i want to know how can i get the values of Bigrams so i can use them later in code etc.Any help would be greatly appreciated.

**Comment by aqibfayyaz** [comment]
Please reply its important.

**Comment by zerrouki95samir** [comment]
Hello; 

Any update on this ?

**Comment by moezali1** [comment]
We are no more supporting the `nlp` and `arules` module in PyCaret due to lack to resources. Closing the issue now.
