### ISSUE TITLE
[BUG] ValueError: Found input variables with inconsistent numbers of samples: [4830, 4018]

### ISSUE THREAD

**Issue by bennydayana** [pycaret/pycaret#1465]
while doing clustering,
_

> exp_name = setup(df, session_id=1948)
> #tune model
> tuned_hclust = tune_model(model = 'hclust', supervised_target = 'outcome')

_
I am getting an error for pycaret-nightly-2.3.2.dev1626396171 and the current stable version also.
Similar like https://github.com/pycaret/pycaret/issues/1194
The error occurs when the shape of df is (4830, 197).
When it is (5859, 197), no problem occurs...

**Comment by pycaret** [comment]
@bennydayana Can you try to reproduce this bug in stable version of pycaret i.e. `2.3.2`. 

Also - can you share the dataset so I can try to reproduce the error?

**Comment by pycaret** [comment]
@wkuopt FYA

**Comment by wkuopt** [comment]
@bennydayana could you provide the data for us to reproduce the error?

**Comment by wkuopt** [comment]
Closed due to inactivity.
