### ISSUE TITLE
[BUG] Kernel Dying Classification Light GBM

### ISSUE THREAD

**Issue by lauraamy** [pycaret/pycaret#1468]
**Describe the bug**
My kernel dies during compare_models(), and this happens when it's going through Light GBM every time. 

**To Reproduce**
Data shape : 307507 rows × 795 columns
setup(train_df[feats], target = 'TARGET', fold_shuffle = True,
                train_size = 0.7, data_split_shuffle=True, session_id = 2,
                fix_imbalance = True)

Then I do compare_models() with an added custom metric and the kernel dies during Light GBM.

I have tried reinstalling ipykernel, and creating a new virtual environment, to no avail. 

**Versions**
pycaret = 2.23
Scikit learn = 0.23.2 (I keep it on this version for my classification to work, otherwise I get an error relating Simple Imputer)

**Comment by pycaret** [comment]
@lauraamy Regarding `sklearn==0.23.2`. It is fine as `pycaret` is not yet compatible with `sklearn==0.24`.

Can you try excluding the lightgbm model from `compare_models`:

```
compare_models(exclude = ['lightgbm'])
```

or can you try training LightGBM separately using `create_model` to see if you still face the same issue.

```
lightgbm = create_model('lightgbm')
```

Is it possible for you to share the dataset?

**Comment by lauraamy** [comment]
I would prefer to include lightgbm for the project I am doing. As for training with create_model, I still face the same issue unfortunately. 
Here is my dataset, that I plug directly into setup:
https://drive.google.com/file/d/1iX4JijfwAC4jfwMsCaXcRYRW6mJBkuXq/view?usp=sharing
And then:
exp_clf = setup(data, target = 'TARGET', fold_shuffle = True,
                train_size = 0.7, data_split_shuffle=True, session_id = 2,
                fix_imbalance = True)

compare_models(include = ["ada", "lightgbm", "ridge", "svm", "nb"])  

The compare_models starts off fine on lightgbm but then after a while, before moving onto ridge the kernel seems to die every time.

**Comment by lauraamy** [comment]
Also, when I add my own metric the compare_models() outputs just this : [] 
This is the metric I add:

def my_comp_score(y_true, y_pred):
    
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    
    tn_weight = 1
    fp_weight = 0
    fn_weight = -10
    tp_weight = 0

    # gain function 
    gain = tp*(tp_weight) + tn*(tn_weight) + fp*(fp_weight) + fn*(fn_weight)
    
    best = (tn + fp) * tn_weight + (tp + fn) * tp_weight
    
    # baseline is a naive model that predicts non default(negative) for everyone
    # so all true positives and false negatives would be incorrectly shown as negative
    baseline = (tn + fp) * tn_weight + (tp + fn) * fn_weight
    
    score = (gain - baseline) / (best - baseline)
    
    return score

I don't see why it should cause a problem, I wonder what I'm missing?

**Comment by wkuopt** [comment]
Hi @lauraamy , could you paste the error message from the terminal where you launched the jupyter notebook?

**Comment by lauraamy** [comment]
I launched the jupyter notebook with anaconda, and I have tried using a new virtual environment with anaconda but it keeps crashing every time the compare_models gets to lightgbm.  

<img width="1323" alt="Screenshot 2021-08-23 at 15 17 17" src="https://user-images.githubusercontent.com/86826494/130458219-6ed92bd5-169c-4b39-867c-98486f1aea5d.png">

**Comment by moezali1** [comment]
@lauraamy This looks like your OS issue with `lightgbm`. Are you using MAC?

**Comment by lauraamy** [comment]
Yes ! I'm using MAC
In my case I can get lightgbm to work with pycaret, but for a smaller dataset

**Comment by wkuopt** [comment]
Hi @lauraamy , I tried to reproduce the error and found memory error in my terminal. An example:
```
MemoryError: Unable to allocate 519. MiB for an array with shape (162465, 837) and data type float32
```
However, my kernel did not die and here is the output:
![image](https://user-images.githubusercontent.com/74427160/142745176-d975c4fd-f1e7-4041-9da9-e8cbcdeca828.png)


The result was obtained with the following code:
```
data = pd.read_csv('pycaret\\tests\\lightgbm_issue.csv')
target = 'TARGET'
assert isinstance(data, pd.core.frame.DataFrame)

# compare models
_ = pycaret.classification.setup(data, target=target, fold_shuffle=True, train_size=0.7, data_split_shuffle=True, session_id=2, fix_imbalance=True)
pycaret.classification.compare_models(include=["ada", "lightgbm", "ridge", "svm", "nb"])
```

I think we can conclude this to be a memory issue.
