### ISSUE TITLE
 module 'pandas' has no attribute 'SparseDtype'

### ISSUE THREAD

**Issue by doraemonlei** [pycaret/pycaret#147]
Multiclass Classification Tutorial Level Beginner - MCLF101.ipynb
compare_models()
pandas==1.0.3
catboost==0.20.2

# logs
AttributeError                            Traceback (most recent call last)
<ipython-input-11-9ff5ccfe3077> in <module>
----> 1 compare_models()

e:\workspace\env_prnet_366\lib\site-packages\pycaret\classification.py in compare_models(blacklist, fold, round, sort, turbo)
   3434             if hasattr(model, 'predict_proba'):
   3435 
-> 3436                 model.fit(Xtrain,ytrain)
   3437                 pred_prob = model.predict_proba(Xtest)
   3438                 pred_prob = pred_prob[:,1]

e:\workspace\env_prnet_366\lib\site-packages\sklearn\multiclass.py in fit(self, X, y)
    237                 "not %s" % self.label_binarizer_.classes_[i],
    238                 self.label_binarizer_.classes_[i]])
--> 239             for i, column in enumerate(columns))
    240 
    241         return self

e:\workspace\env_prnet_366\lib\site-packages\joblib\parallel.py in __call__(self, iterable)
    915             # the use of the lock
    916             with self._lock:
--> 917                 job = self._jobs.pop(0)
    918 
    919             try:

e:\workspace\env_prnet_366\lib\site-packages\joblib\parallel.py in dispatch_one_batch(self, iterator)
    757 
    758         self.n_dispatched_tasks += len(batch)
--> 759         self.n_dispatched_batches += 1
    760 
    761         dispatch_timestamp = time.time()

e:\workspace\env_prnet_366\lib\site-packages\joblib\parallel.py in _dispatch(self, batch)
    714     def __exit__(self, exc_type, exc_value, traceback):
    715         self._terminate_backend()
--> 716         self._managed_backend = False
    717 
    718     def _initialize_backend(self):

e:\workspace\env_prnet_366\lib\site-packages\joblib\_parallel_backends.py in apply_async(self, func, callback)
    180             env[self.TBB_ENABLE_IPC_VAR] = "1"
    181         return env
--> 182 
    183     @staticmethod
    184     def in_main_thread():

e:\workspace\env_prnet_366\lib\site-packages\joblib\_parallel_backends.py in __init__(self, batch)
    547             # calls, but cleanup the temporary resources that the Parallel call
    548             # created. This 'hack' requires a private, low-level operation.
--> 549             self._workers._temp_folder_manager._unlink_temporary_resources(
    550                 context_id=self.parallel._id
    551             )

e:\workspace\env_prnet_366\lib\site-packages\joblib\parallel.py in __call__(self)
    223 # 'fork' to 'forkserver' or 'spawn' to avoid this issue albeit at the cost
    224 # of causing semantic changes and some additional pool instantiation overhead.
--> 225 DEFAULT_MP_CONTEXT = None
    226 if hasattr(mp, 'get_context'):
    227     method = os.environ.get('JOBLIB_START_METHOD', '').strip() or None

e:\workspace\env_prnet_366\lib\site-packages\joblib\parallel.py in <listcomp>(.0)
    223 # 'fork' to 'forkserver' or 'spawn' to avoid this issue albeit at the cost
    224 # of causing semantic changes and some additional pool instantiation overhead.
--> 225 DEFAULT_MP_CONTEXT = None
    226 if hasattr(mp, 'get_context'):
    227     method = os.environ.get('JOBLIB_START_METHOD', '').strip() or None

e:\workspace\env_prnet_366\lib\site-packages\sklearn\multiclass.py in _fit_binary(estimator, X, y, classes)
     77     else:
     78         estimator = clone(estimator)
---> 79         estimator.fit(X, y)
     80     return estimator
     81 

e:\workspace\env_prnet_366\lib\site-packages\catboost\core.py in fit(self, X, y, cat_features, text_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   3791         self._fit(X, y, cat_features, text_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
   3792                   eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period,
-> 3793                   silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   3794         return self
   3795 

e:\workspace\env_prnet_366\lib\site-packages\catboost\core.py in _fit(self, X, y, cat_features, text_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   1676             use_best_model, eval_set, verbose, logging_level, plot,
   1677             column_description, verbose_eval, metric_period, silent, early_stopping_rounds,
-> 1678             save_snapshot, snapshot_file, snapshot_interval, init_model
   1679         )
   1680         params = train_params["params"]

e:\workspace\env_prnet_366\lib\site-packages\catboost\core.py in _prepare_train_params(self, X, y, cat_features, text_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   1564 
   1565         train_pool = _build_train_pool(X, y, cat_features, text_features, pairs, sample_weight, group_id,
-> 1566                                        group_weight, subgroup_id, pairs_weight, baseline, column_description)
   1567         if train_pool.is_empty_:
   1568             raise CatBoostError("X is empty.")

e:\workspace\env_prnet_366\lib\site-packages\catboost\core.py in _build_train_pool(X, y, cat_features, text_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, column_description)
    971             raise CatBoostError("y has not initialized in fit(): X is not catboost.Pool object, y must be not None in fit().")
    972         train_pool = Pool(X, y, cat_features=cat_features, text_features=text_features, pairs=pairs, weight=sample_weight, group_id=group_id,
--> 973                           group_weight=group_weight, subgroup_id=subgroup_id, pairs_weight=pairs_weight, baseline=baseline)
    974     return train_pool
    975 

e:\workspace\env_prnet_366\lib\site-packages\catboost\core.py in __init__(self, data, label, cat_features, text_features, column_description, pairs, delimiter, has_header, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    371                         )
    372 
--> 373                 self._init(data, label, cat_features, text_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    374         super(Pool, self).__init__()
    375 

e:\workspace\env_prnet_366\lib\site-packages\catboost\core.py in _init(self, data, label, cat_features, text_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    952             baseline = np.reshape(baseline, (samples_count, -1))
    953             self._check_baseline_shape(baseline, samples_count)
--> 954         self._init_pool(data, label, cat_features, text_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    955 
    956 

_catboost.pyx in _catboost._PoolBase._init_pool()

_catboost.pyx in _catboost._PoolBase._init_pool()

_catboost.pyx in _catboost._PoolBase._init_features_order_layout_pool()

_catboost.pyx in _catboost._set_features_order_data_pd_data_frame()

AttributeError: module 'pandas' has no attribute 'SparseDtype'

**Comment by doraemonlei** [comment]
I created a pure virtual environment and the problem was solved.

**Comment by pycaret** [comment]
@doraemonlei Thanks. Closing this now.
