### ISSUE TITLE
Unable to use predict_model after load_model in pycaret.anomaly

### ISSUE THREAD

**Issue by SudheerRaghu** [pycaret/pycaret#1470]
Error occurs for iforest, knn and cluster model types in pycaret.anomaly. Model building done with preprocess=False.

pycaret version : 2.3.2
python version: 3.7.3 & 3.8.5

pycaret.anomaly.save_model(model, 'model_path', model_only = True)
ad_model = pycaret.anomaly.load_model('model_path)
train_data_scored = pycaret.anomaly.predict_model(model=ad_model, data=train_data)
Traceback (most recent call last):
  File "C:\Users\sudheermoguluri\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-0e13c60f6503>", line 1, in <module>
    train_data_scored = pycaret.anomaly.predict_model(model=ad_model, data=train_data)
  File "C:\Users\sudheermoguluri\AppData\Local\Continuum\anaconda3\lib\site-packages\pycaret\anomaly.py", line 870, in predict_model
    estimator=model, data=data, ml_usecase=MLUsecase.ANOMALY,
  File "C:\Users\sudheermoguluri\AppData\Local\Continuum\anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 8363, in predict_model_unsupervised
    pred = estimator.predict(prep_pipe.transform(data_transformed))
NameError: name 'prep_pipe' is not defined

**Comment by moezali1** [comment]
@SudheerRaghu 

Is there a specific reason you are passing `model_only = True`. If you save the model with `model_only = False` the predict_model` function works as expected.

Having said that @Yard1 - This seems like a valid problem. When we only save the model as oppose to the entire pipeline, the `predict_model` fails with the NameError.

NameError: name 'prep_pipe' is not defined

`predict_model` should work regardless.

**Comment by SudheerRaghu** [comment]
@moezali1 No specific reason as I got errors for both cases. I thought I should save only the model when `preprocess=False`. 

Either way, it's good if the `model_only` variable changes dynamically based on the `preprocess` and `custom_pipeline` inputs. 

Please let me know if any additional info is required. Thanks.

**Comment by moezali1** [comment]
@tvdboom Do you mind taking look issue with `predict_model` in `pycaret.anomaly` when `model_only=True` used with `save_model`.

Here is the notebook to reproduce: https://colab.research.google.com/drive/16rMVlFB__RGBdZEEPIozZpJCY6OxxVWa?usp=sharing

After `save_model` don't forget to restart the kernel.
