### ISSUE TITLE
[BUG]setup(target = 'label'),KeyError: 'label'

### ISSUE THREAD

**Issue by doraemonlei** [pycaret/pycaret#1478]
python 3.8.10
pycaret[full], 2.3.3
win10
jupyter notebook

`
data = pd.read_excel('1875-29.xlsx') # have 'label' column

exp_clf1 = setup(data = data, 
                 target = 'label', 
                ……  
                )
`

`
KeyError                                  Traceback (most recent call last)
d:\anaconda3\envs\env_pycaret\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3360             try:
-> 3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:

d:\anaconda3\envs\env_pycaret\lib\site-packages\pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

d:\anaconda3\envs\env_pycaret\lib\site-packages\pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'label'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
C:\Users\ADMINI~1\AppData\Local\Temp/ipykernel_25776/2717966094.py in <module>
----> 1 exp_clf1 = setup(data = data, 
      2                  target = 'label',
      3                  session_id=123,
      4                  normalize = True,
      5                  transformation = True,

d:\anaconda3\envs\env_pycaret\lib\site-packages\pycaret\classification.py in setup(data, target, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs)
    579         log_plots = ["auc", "confusion_matrix", "feature"]
    580 
--> 581     return pycaret.internal.tabular.setup(
    582         ml_usecase="classification",
    583         available_plots=available_plots,

d:\anaconda3\envs\env_pycaret\lib\site-packages\pycaret\internal\tabular.py in setup(data, target, ml_usecase, available_plots, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, transform_target, transform_target_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs, display)
   1328             test_data = pd.concat([X_test, y_test], axis=1)
   1329 
-> 1330         train_data = prep_pipe.fit_transform(train_data)
   1331         # workaround to also transform target
   1332         dtypes.final_training_columns.append(target)

d:\anaconda3\envs\env_pycaret\lib\site-packages\sklearn\pipeline.py in fit_transform(self, X, y, **fit_params)
    365         """
    366         fit_params_steps = self._check_fit_params(**fit_params)
--> 367         Xt = self._fit(X, y, **fit_params_steps)
    368 
    369         last_step = self._final_estimator

d:\anaconda3\envs\env_pycaret\lib\site-packages\sklearn\pipeline.py in _fit(self, X, y, **fit_params_steps)
    290                 cloned_transformer = clone(transformer)
    291             # Fit or load from cache the current transformer
--> 292             X, fitted_transformer = fit_transform_one_cached(
    293                 cloned_transformer, X, y, None,
    294                 message_clsname='Pipeline',

d:\anaconda3\envs\env_pycaret\lib\site-packages\joblib\memory.py in __call__(self, *args, **kwargs)
    350 
    351     def __call__(self, *args, **kwargs):
--> 352         return self.func(*args, **kwargs)
    353 
    354     def call_and_shelve(self, *args, **kwargs):

d:\anaconda3\envs\env_pycaret\lib\site-packages\sklearn\pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    738     with _print_elapsed_time(message_clsname, message):
    739         if hasattr(transformer, 'fit_transform'):
--> 740             res = transformer.fit_transform(X, y, **fit_params)
    741         else:
    742             res = transformer.fit(X, y, **fit_params).transform(X)

d:\anaconda3\envs\env_pycaret\lib\site-packages\pycaret\internal\preprocess.py in fit_transform(self, data, y)
   2709             data frame
   2710     """
-> 2711         self.fit(data)
   2712         return self.transform(data)
   2713 

d:\anaconda3\envs\env_pycaret\lib\site-packages\pycaret\internal\preprocess.py in fit(self, data, y)
   2540 
   2541         # Calculate the correlation with the target
-> 2542         targ_cor = pd.DataFrame(corr_matrix[self.target_variable].dropna())
   2543         targ_cor["feature"] = targ_cor.index
   2544         targ_cor.reset_index(drop=True, inplace=True)

d:\anaconda3\envs\env_pycaret\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   3453             if self.columns.nlevels > 1:
   3454                 return self._getitem_multilevel(key)
-> 3455             indexer = self.columns.get_loc(key)
   3456             if is_integer(indexer):
   3457                 indexer = [indexer]

d:\anaconda3\envs\env_pycaret\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:
-> 3363                 raise KeyError(key) from err
   3364 
   3365         if is_scalar(key) and isna(key) and not self.hasnans:

KeyError: 'label'

`

**Comment by zingochampis** [comment]
Also #1482 and #1483. Let's join forces and push the issue!

**Comment by moezali1** [comment]
#1482 #1483 and this issue - all can be handled at once.
