### ISSUE TITLE
[BUG]Classification Setup fails when remove_multicollinearity is present

### ISSUE THREAD

**Issue by shreyajane23** [pycaret/pycaret#1482]
**Describe the bug**

**To Reproduce**

```python
#Pycaret Model SetUp and execute training 
clf_base = setup(data = train_full,target = 'h1n1_vaccine', 
                 ignore_features=['seasonal_vaccine'],feature_interaction=True,feature_ratio=True,ignore_low_variance = True,
                 remove_multicollinearity = True, multicollinearity_threshold = 0.95,
                 train_size=0.8, session_id=42)
```

**Expected behavior**
 2 clf_base = setup(data = train_full,target = 'h1n1_vaccine', 
      3                  ignore_features=['seasonal_vaccine'],feature_interaction=True,feature_ratio=True,ignore_low_variance = True,
      4                  remove_multicollinearity = True, multicollinearity_threshold = 0.95,
      5                  train_size=0.8, session_id=42)

~\anaconda3\lib\site-packages\pycaret\classification.py in setup(data, target, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs)
    579         log_plots = ["auc", "confusion_matrix", "feature"]
    580 
--> 581     return pycaret.internal.tabular.setup(
    582         ml_usecase="classification",
    583         available_plots=available_plots,

~\anaconda3\lib\site-packages\pycaret\internal\tabular.py in setup(data, target, ml_usecase, available_plots, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, transform_target, transform_target_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs, display)
   1328             test_data = pd.concat([X_test, y_test], axis=1)
   1329 
-> 1330         train_data = prep_pipe.fit_transform(train_data)
   1331         # workaround to also transform target
   1332         dtypes.final_training_columns.append(target)

~\anaconda3\lib\site-packages\sklearn\pipeline.py in fit_transform(self, X, y, **fit_params)
    365         """
    366         fit_params_steps = self._check_fit_params(**fit_params)
--> 367         Xt = self._fit(X, y, **fit_params_steps)
    368 
    369         last_step = self._final_estimator

~\anaconda3\lib\site-packages\sklearn\pipeline.py in _fit(self, X, y, **fit_params_steps)
    290                 cloned_transformer = clone(transformer)
    291             # Fit or load from cache the current transformer
--> 292             X, fitted_transformer = fit_transform_one_cached(
    293                 cloned_transformer, X, y, None,
    294                 message_clsname='Pipeline',

~\anaconda3\lib\site-packages\joblib\memory.py in __call__(self, *args, **kwargs)
    350 
    351     def __call__(self, *args, **kwargs):
--> 352         return self.func(*args, **kwargs)
    353 
    354     def call_and_shelve(self, *args, **kwargs):

~\anaconda3\lib\site-packages\sklearn\pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    738     with _print_elapsed_time(message_clsname, message):
    739         if hasattr(transformer, 'fit_transform'):
--> 740             res = transformer.fit_transform(X, y, **fit_params)
    741         else:
    742             res = transformer.fit(X, y, **fit_params).transform(X)

~\anaconda3\lib\site-packages\pycaret\internal\preprocess.py in fit_transform(self, data, y)
   2709             data frame
   2710     """
-> 2711         self.fit(data)
   2712         return self.transform(data)
   2713 

~\anaconda3\lib\site-packages\pycaret\internal\preprocess.py in fit(self, data, y)
   2540 
   2541         # Calculate the correlation with the target
-> 2542         targ_cor = pd.DataFrame(corr_matrix[self.target_variable].dropna())
   2543         targ_cor["feature"] = targ_cor.index
   2544         targ_cor.reset_index(drop=True, inplace=True)

~\anaconda3\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   3022             if self.columns.nlevels > 1:
   3023                 return self._getitem_multilevel(key)
-> 3024             indexer = self.columns.get_loc(key)
   3025             if is_integer(indexer):
   3026                 indexer = [indexer]

~\anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3080                 return self._engine.get_loc(casted_key)
   3081             except KeyError as err:
-> 3082                 raise KeyError(key) from err
   3083 
   3084         if tolerance is not None:

KeyError: 'h1n1_vaccine'
-->

**Additional context**

**Versions**
<details>

</details>

**Comment by ngupta23** [comment]
Check to make sure that your dataframe has a column called `h1n1_vaccine`. Also, if there are leading or trailing spaces in the column name, then the same needs to be provided to the `target` argument.

**Comment by zingochampis** [comment]
@ngupta23 I logged a similar bug #1483. In my case no extra spaces in target column name, and it is present in the dataset. If I comment out multicollinearity parameters, the setup completes just fine.

**Comment by shreyajane23** [comment]
@ngupta23 - i have the same issue that @zingochampis  mentioned. There are no spaces in my target column name and it is also present in the dataset. If i comment the multicollinearity parameters the setup works fine. This code used to work in the earlier version of Pycaret

**Comment by zingochampis** [comment]
@shreyajane23 @ngupta23  upgrading pycaret nightly DID NOT FIX THE ISSUE :-(

**Comment by zingochampis** [comment]
@shreyajane23  fortunately my feature set is not large, so after inspecting the correlation matrix, I manually removed 2 features that had correlations >=0.79 with another feature. A poor workaround though.

**Comment by shreyajane23** [comment]
@zingochampis  i tried upgrading pycaret to nightly too. Did not work for me either. Although i did notice that there was some fix for the multicollinearity part in version 2.3.2 which i assume did not get fixed.
