### ISSUE TITLE
[BUG] Unable to run interpret_model after a load_model

### ISSUE THREAD

**Issue by skannan-maf** [pycaret/pycaret#1484]
**Describe the bug**

Unable to run pycaret.regression.interpret_model() after a load_model() to explain a prediction.
Errors out saying "This function only supports tree based models for binary classification: et, dt, lightgbm, rf"
Though the problem is a "regression" problem, the error message talks about "classification". I assume thats a typo.
Also, the model is a scikit pipeline ending with "et" model..
Since Shap predictions are supported on "et" model, I was expecting this to work.
I had used this before the save_model() while the experiment was tested... And it worked fine at that time.
After saving and then loading in another jupyter notebook, I am unable to explain predictions.... (though predict_model works well)

**To Reproduce**

```python

model_26 = pycaret.regression.load_model("model_output/model_v26")
# model_26 is a scikit pipeline object that has many steps .. with the final step being "Extra Trees regressor"
# model_26 was saved from another jupyter_notebook which trains multiple models and saves them
# Here i m loading one such saved model and trying to explain its predictions

# A setup is needed before interpret_model(). Without a setup, I get some errors. So, I added setup()
pycaret.regression.setup(  
            data=reg_base_df[feature_columns + ignore_features + ['REG_TARGET']], 
            train_size=0.75,
            data_split_stratify=['Country'],
            target='REG_TARGET', 
            fold = 5, #Earlier this was not specified and defaulted to 10
            fold_shuffle=True,
            feature_selection=True, 
            feature_selection_threshold=0.30,
            categorical_features=[ 'cat1', 'cat2', 'cat3' ],
            ignore_features=['ign1', 'ign2'] ,
            imputation_type='iterative',
            transformation=False, 
            normalize=True, 
            remove_multicollinearity=True, 
            multicollinearity_threshold=0.95,
            remove_perfect_collinearity=True,
            silent=True,
            n_jobs=8
        )

# Invoke interpret model
pycaret.regression.interpret_model(model_26, plot="reason", 
                                   X_new_sample=base_df[base_df.attr==value])
# X_new_sample will have just exactly 1 row
# same issue for plot="summary" as well
```

**Expected behavior**

A reason plot explaining the prediction output

**Additional context**

**Versions**
2.3.1

</details>

**Comment by moezali1** [comment]
@skannan-maf Here is what I will recommend:

Step 1 - Training
```
from pycaret.datasets import get_data
data = get_data('boston')

from pycaret.regression import *
s = setup(data, target = 'medv')

lightgbm = create_model('lightgbm')

save_model(lightgbm, 'lgb')

save_config('lgb_config')
```

Step 2 - Re-use later

```
# in new notebook
from pycaret.regression import load_model, load_config, interpret_model

l = load_model('lgb')
config = load_config('lgb_config')
interpret_model(l[-1])
```

This works for me. Let me know if this helps.

![image](https://user-images.githubusercontent.com/54699234/128606669-3ab629a5-7c85-4851-bd85-1bb6f5e39758.png)

**Comment by skannan-maf** [comment]
Thanks for the detailed steps! It was very helpful.

I suppose "save_config" saves everything including data (and that can be costly..)
It would be a "nice to have" to save everything else except data and then have an API to specify the data (load_config(pkl_file, data = data_df))

Thanks!
