### ISSUE TITLE
Request  for adding some method in preprocessing  ，so that i can build some features

### ISSUE THREAD

**Issue by zhere** [pycaret/pycaret#149]
for example：
1、 From the "datetime" field, extract "date," hour "," weekday "," month " ；
2、Mapping some fields；

Pycaret a great tool ，I hope it will become more powerful  ！！！

**Comment by DaGuT** [comment]
Cant you just edit your dataframe in advance?

**Comment by zhere** [comment]
Sorry, I'm not a technician. It takes time to use other tools for data processing. Now it's easier for me to use pycaret for data processing, so I hope it can be implemented in pycaret 。

**Comment by pycaret** [comment]
@zhere Thanks. PyCaret automatically extracts the features you mentioned from the Date and then eventually drop the date column for modeling. I am closing this issue now. Thanks
