### ISSUE TITLE
Need more control on Feature selection 

### ISSUE THREAD

**Issue by skannan-maf** [pycaret/pycaret#1491]
**Is your feature request related to a problem? Please describe.**
As of now, Users can only specify Feature selection threshold while enabling feature selection. However, if the user wants to keep some columns as "sticky", they cannot specify it. 

**Describe the solution you'd like**
Sticky features in terms of "regular expressions"
Sticky features in terms of "categorical/nominal/numeric/date time" etc.
Sticky features by data-types
Sticky features as an explicit collection of a list

These features will not be considered for removal and will be present in the final dataframe

**Describe alternatives you've considered**
N/A

**Additional context**
Pycaret version 2.3.1

**Comment by Yard1** [comment]
cc @tvdboom

**Comment by tvdboom** [comment]
Yes, this is something we are working on and will be present in the next major release. The implementation will probably be a new parameter called something like `keep_features` where the user can specify a list of names of the features he wants to keep.
