### ISSUE TITLE
Compare Model does not ignore "error" 

### ISSUE THREAD

**Issue by mfahadakbar** [pycaret/pycaret#1494]
**Describe the bug**
The default behaviour or error handling in the compare_models function is to ignore (in case a specific model fails) the error and jump to the next model in the line. However, there are some situations when a model successfully fits all the folds in the training data set but doesn't fit on the entire data set. In that case, it does not handle the error and raises it, resulting in the collapse of the entire process.

I am facing this issue with my custom model which is simply an exponential equation. At times, the equation would fit on say all the folds, but won't find a fit on the entire training data set. 

It should be a simple fix. Just as if cross-validation fails, move to the next model, the same way if the fitting on the entire training data set fails, proceed to the next model

@Yard1 @moezali1

**Comment by moezali1** [comment]
Thanks @mfahadakbar

@Yard1 - Need your help here, please!

**Comment by Yard1** [comment]
Thanks, will take a look

**Comment by mfahadakbar** [comment]
Here is a link to the file where it happens
https://colab.research.google.com/drive/1abVjDHX8IGndEUbaqo016_E6I-cnZVaL?usp=sharing

**Comment by Yard1** [comment]
Fixed in https://github.com/pycaret/pycaret/pull/1510
