### ISSUE TITLE
blend_models does not handle custom estimator

### ISSUE THREAD

**Issue by mfahadakbar** [pycaret/pycaret#1496]
the custom estimator does not work with the blend_models function.
A reproducible notebook is provided below

https://colab.research.google.com/drive/1rq87KS5DuK1xF7wuJslIb0VTnoNZj0-4?usp=sharing

@Yard1 @moezali1

**Comment by moezali1** [comment]
Thanks @mfahadakbar

@Yard1 - Need your help here, please!

**Comment by Yard1** [comment]
Fixed in https://github.com/pycaret/pycaret/pull/1500
