### ISSUE TITLE
[BUG] [installation]

### ISSUE THREAD

**Issue by DanieleBaranzini** [pycaret/pycaret#1498]
** "api-ms-win-core-winrt-string-l1-1-0" is missing during pycaret 2.3.3 installation...**

during installation Pycaret 2.3.3  (on windows 7, 64bit, python 3.7) a ddl seems to miss out ...all is fine untill I call  pycaret.classification import *...and  all ends with a pop up window telling me that "api-ms-win-core-winrt-string-l1-1-0" is missing

any thoughts? 
-->

**Comment by moezali1** [comment]
@DanieleBaranzini Have you installed PyCaret in a fresh conda environment? If not, can you try that?

Here's the instruction: https://pycaret.readthedocs.io/en/latest/installation.html

**Comment by DanieleBaranzini** [comment]
@moezali1 Thanks Mr PyCaret! 
Problem Solved by 

1) first I 'conda install bottleneck' as I got 'failures to build bottlenecks  ...due to PEP 517'
2) and  then I proceeded to pip install pycaret[full] ...and all works vanilla now : )
