### ISSUE TITLE
Problem installing pycaret

### ISSUE THREAD

**Issue by klahrich** [pycaret/pycaret#15]
Hi everyone,

I had some issues pip-installing pycaret. Some of my other libraries use the same underlying packages as pycaret, but require more recent versions.

Here are the error messages I get:

ERROR: prettierplot 0.1.1 has requirement scikit-learn>=0.22.1, but you'll have scikit-learn 0.22 which is incompatible.
ERROR: mlmachine 0.1.3 has requirement catboost>=0.22, but you'll have catboost 0.20.2 which is incompatible.
ERROR: mlmachine 0.1.3 has requirement scikit-learn>=0.22.1, but you'll have scikit-learn 0.22 which is incompatible.
ERROR: mlmachine 0.1.3 has requirement shap>=0.35.0, but you'll have shap 0.32.1 which is incompatible.
ERROR: mlmachine 0.1.3 has requirement xgboost>=1.0.2, but you'll have xgboost 0.90 which is incompatible.

Would it be a possibility to update your requirements file ?

Thank you

**Comment by LinxiFan** [comment]
Agreed, the `requirements.txt` seems to be very restrictive. Is there a reason to require those packages to be the exact version number?

**Comment by KaitoKikuhara** [comment]
I thought to solve that problem setup.py have to be changed with the requirements file. because of requirements in setup.py too.
