### ISSUE TITLE
Incorrect encoding of the target label [BUG]

### ISSUE THREAD

**Issue by harsh204016** [pycaret/pycaret#1501]
**Describe the bug**
While running the setup function for the classification problem, it is encoding the target labels which is already int64 
![image](https://user-images.githubusercontent.com/37452506/128900395-5f0f481b-fab0-4ad4-8730-6070d0994ca4.png)
![image](https://user-images.githubusercontent.com/37452506/128900452-03c421c9-160f-44d8-b4b5-f114d5e355c7.png)

**To Reproduce**

for reference of code 
https://www.kaggle.com/harsh2040/music-genre-classification-using-pycaret?scriptVersionId=71069819

**Expected behavior**
It should not encode the target label 

**Additional context**
Please correct me if I am missing something.

**Versions**
2.3.3

</details>
One more boolean parameter can be added in the setup if the user wants to encodes the target label or not.

**Comment by wkuopt** [comment]
Hey @Yard1 @moezali1 i am thinking to add that flag as suggested to override it, but still default the flag to true so that by default we still encode the target variable. Any thoughts?

**Comment by Yard1** [comment]
Can we, by default, encode only if target isn't an integer already?

**Comment by wkuopt** [comment]
@Yard1 yes that works too. I will make the change
