### ISSUE TITLE
[BUG]BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

### ISSUE THREAD

**Issue by sarahzouinina** [pycaret/pycaret#1503]
Hello guys,

I have an issue with tuning the model, I get this error,
Would you help me please?

Thanks 

```
from sklearn.model_selection import train_test_split
from pycaret.regression import *
import pandas as pd

train = pd.read_csv('~/August_Playground/data/train.csv')

train.pop('loss')
train.pop('id')

X_train, X_test, y_train, y_test = train_test_split(train, target, test_size=0.33, random_state=42)
df_train = pd.concat([X_train, y_train], axis=1)

reg1 = setup(data = df_train, target = 'loss')
lightgbm = create_model('lightgbm')
tuned_lgbm = tune_model(lightgbm, n_iter=20)
```

**Error**
Fitting 10 folds for each of 20 candidates, totalling 200 fits
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
exception calling callback for <Future at 0x29067d57e20 state=finished raised BrokenProcessPool>
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\SarahZOUININA\AppData\Roaming\Python\Python38\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\Users\SarahZOUININA\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "pandas\_libs\internals.pyx", line 572, in pandas._libs.internals.BlockManager.__cinit__
TypeError: __cinit__() takes at least 2 positional arguments (0 given)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SarahZOUININA\AppData\Roaming\Python\Python38\site-packages\joblib\externals\loky\_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "C:\Users\SarahZOUININA\AppData\Roaming\Python\Python38\site-packages\joblib\parallel.py", line 359, in __call__
    self.parallel.dispatch_next()
  File "C:\Users\SarahZOUININA\AppData\Roaming\Python\Python38\site-packages\joblib\parallel.py", line 792, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "C:\Users\SarahZOUININA\AppData\Roaming\Python\Python38\site-packages\joblib\parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\SarahZOUININA\AppData\Roaming\Python\Python38\site-packages\joblib\parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\SarahZOUININA\AppData\Roaming\Python\Python38\site-packages\joblib\_parallel_backends.py", line 531, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "C:\Users\SarahZOUININA\AppData\Roaming\Python\Python38\site-packages\joblib\externals\loky\reusable_executor.py", line 177, in submit
    return super(_ReusablePoolExecutor, self).submit(
  File "C:\Users\SarahZOUININA\AppData\Roaming\Python\Python38\site-packages\joblib\externals\loky\process_executor.py", line 1102, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\SarahZOUININA\AppData\Roaming\Python\Python38\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\Users\SarahZOUININA\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "pandas\_libs\internals.pyx", line 572, in pandas._libs.internals.BlockManager.__cinit__
TypeError: __cinit__() takes at least 2 positional arguments (0 given)
"""

The above exception was the direct cause of the following exception:

BrokenProcessPool                         Traceback (most recent call last)
<ipython-input-19-44b89b099089> in <module>
----> 1 tuned_lgbm = tune_model(lightgbm, n_iter=20)

~\Anaconda3\lib\site-packages\pycaret\regression.py in tune_model(estimator, fold, round, n_iter, custom_grid, optimize, custom_scorer, search_library, search_algorithm, early_stopping, early_stopping_max_iters, choose_better, fit_kwargs, groups, return_tuner, verbose, tuner_verbose, **kwargs)
   1082     """
   1083 
-> 1084     return pycaret.internal.tabular.tune_model_supervised(
   1085         estimator=estimator,
   1086         fold=fold,

~\Anaconda3\lib\site-packages\pycaret\internal\tabular.py in tune_model_supervised(estimator, fold, round, n_iter, custom_grid, optimize, custom_scorer, search_library, search_algorithm, early_stopping, early_stopping_max_iters, choose_better, fit_kwargs, groups, return_tuner, verbose, tuner_verbose, display, **kwargs)
   4478                 pycaret.internal.patches.sklearn._mp_ParameterGrid_getitem,
   4479             ):
-> 4480                 model_grid.fit(X_train, y_train, groups=groups, **fit_kwargs)
   4481         else:
   4482             model_grid.fit(X_train, y_train, groups=groups, **fit_kwargs)

~\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     71                           FutureWarning)
     72         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 73         return f(**kwargs)
     74     return inner_f
     75 

~\AppData\Roaming\Python\Python38\site-packages\sklearn\model_selection\_search.py in fit(self, X, y, groups, **fit_params)
    734                 return results
    735 
--> 736             self._run_search(evaluate_candidates)
    737 
    738         # For multi-metric evaluation, store the best_index_, best_params_ and

~\AppData\Roaming\Python\Python38\site-packages\sklearn\model_selection\_search.py in _run_search(self, evaluate_candidates)
   1527     def _run_search(self, evaluate_candidates):
   1528         """Search n_iter candidates from param_distributions"""
-> 1529         evaluate_candidates(ParameterSampler(
   1530             self.param_distributions, self.n_iter,
   1531             random_state=self.random_state))

~\AppData\Roaming\Python\Python38\site-packages\sklearn\model_selection\_search.py in evaluate_candidates(candidate_params)
    706                               n_splits, n_candidates, n_candidates * n_splits))
    707 
--> 708                 out = parallel(delayed(_fit_and_score)(clone(base_estimator),
    709                                                        X, y,
    710                                                        train=train, test=test,

~\AppData\Roaming\Python\Python38\site-packages\joblib\parallel.py in __call__(self, iterable)
   1052 
   1053             with self._backend.retrieval_context():
-> 1054                 self.retrieve()
   1055             # Make sure that we get a last message telling us we are done
   1056             elapsed_time = time.time() - self._start_time

~\AppData\Roaming\Python\Python38\site-packages\joblib\parallel.py in retrieve(self)
    931             try:
    932                 if getattr(self._backend, 'supports_timeout', False):
--> 933                     self._output.extend(job.get(timeout=self.timeout))
    934                 else:
    935                     self._output.extend(job.get())

~\AppData\Roaming\Python\Python38\site-packages\joblib\_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

~\Anaconda3\lib\concurrent\futures\_base.py in result(self, timeout)
    437                 raise CancelledError()
    438             elif self._state == FINISHED:
--> 439                 return self.__get_result()
    440             else:
    441                 raise TimeoutError()

~\Anaconda3\lib\concurrent\futures\_base.py in __get_result(self)
    386     def __get_result(self):
    387         if self._exception:
--> 388             raise self._exception
    389         else:
    390             return self._result

~\AppData\Roaming\Python\Python38\site-packages\joblib\externals\loky\_base.py in _invoke_callbacks(self)
    623         for callback in self._done_callbacks:
    624             try:
--> 625                 callback(self)
    626             except BaseException:
    627                 LOGGER.exception('exception calling callback for %r', self)

~\AppData\Roaming\Python\Python38\site-packages\joblib\parallel.py in __call__(self, out)
    357         with self.parallel._lock:
    358             if self.parallel._original_iterator is not None:
--> 359                 self.parallel.dispatch_next()
    360 
    361 

~\AppData\Roaming\Python\Python38\site-packages\joblib\parallel.py in dispatch_next(self)
    790 
    791         """
--> 792         if not self.dispatch_one_batch(self._original_iterator):
    793             self._iterating = False
    794             self._original_iterator = None

~\AppData\Roaming\Python\Python38\site-packages\joblib\parallel.py in dispatch_one_batch(self, iterator)
    857                 return False
    858             else:
--> 859                 self._dispatch(tasks)
    860                 return True
    861 

~\AppData\Roaming\Python\Python38\site-packages\joblib\parallel.py in _dispatch(self, batch)
    775         with self._lock:
    776             job_idx = len(self._jobs)
--> 777             job = self._backend.apply_async(batch, callback=cb)
    778             # A job can complete so quickly than its callback is
    779             # called before we get here, causing self._jobs to

~\AppData\Roaming\Python\Python38\site-packages\joblib\_parallel_backends.py in apply_async(self, func, callback)
    529     def apply_async(self, func, callback=None):
    530         """Schedule a func to be run"""
--> 531         future = self._workers.submit(SafeFunction(func))
    532         future.get = functools.partial(self.wrap_future_result, future)
    533         if callback is not None:

~\AppData\Roaming\Python\Python38\site-packages\joblib\externals\loky\reusable_executor.py in submit(self, fn, *args, **kwargs)
    175     def submit(self, fn, *args, **kwargs):
    176         with self._submit_resize_lock:
--> 177             return super(_ReusablePoolExecutor, self).submit(
    178                 fn, *args, **kwargs)
    179 

~\AppData\Roaming\Python\Python38\site-packages\joblib\externals\loky\process_executor.py in submit(self, fn, *args, **kwargs)
   1100         with self._flags.shutdown_lock:
   1101             if self._flags.broken is not None:
-> 1102                 raise self._flags.broken
   1103             if self._flags.shutdown:
   1104                 raise ShutdownExecutorError(

BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

**Comment by moezali1** [comment]
@sarahzouinina This seems like an old issue with Loky. Can you try this:

In your `setup` function can you pass `n_jobs=1` and see if the issue goes away? Change your setup code to this:

```
reg1 = setup(data = df_train, target = 'loss', n_jobs=1)

```

**Comment by moezali1** [comment]
@sarahzouinina Hi. Can you confirm if the issue is resolved?

**Comment by sarahzouinina** [comment]
@moezali1 Thank you for the mention, yes it is solved
