### ISSUE TITLE
[BUG] if setup() receives categorical with np.na values then it inference it as Date type.

### ISSUE THREAD

**Issue by sagittefrat** [pycaret/pycaret#1514]
if setup() receives categorical with np.na values then it inference it as Date type.

I've also tried converting them to object types as mentioned in other responses but he only thing that worked is fillna().
I'm not sure it a bug but at least should raise some error that pycaret does not handle nones

** this is not working:
data=data.sample(n=1000000, random_state=1).astype('object')"""
exp_name = setup(data = data,  target = 'max_pb_flag', categorical_features=x_train.columns.to_list(), numeric_features=[] , date_features=[])

** this is working:
data=data.sample(n=1000000, random_state=1).astype('object')"""
exp_name = setup(data = data.fillna(0),  target = 'max_pb_flag', categorical_features=x_train.columns.to_list(), numeric_features=[] , date_features=[])

data is a pandas df

**Comment by moezali1** [comment]
@sagittefrat Thanks for reporting. Can you please upload a reproducible notebook and sample data to reproduce this error on our end?

**Comment by wkuopt** [comment]
Hi @sagittefrat,

I tested with the following example and the dtype is correctly inferred. Please let me know if your test case is different, and we can reopen the ticket.

Code:
```
def test_datatype_infer_error():
    dataset = pd.DataFrame([[np.nan, 1],
                            [0, 1],
                            [1, 0],
                            [1, 1]],
                           columns=list("AB"))
    dataset['A'] = dataset['A'].astype('category')
    target = 'B'

    pipe = pycaret.internal.preprocess.Preprocess_Path_One(
        train_data=dataset, target_variable=target, display_types=False
    )
    X = pipe.fit_transform(dataset)

    for col in X.columns:
        if col != 'B':
            assert X[col].dtype == np.float32
```
Dataset before:
```
 A  B
0  NaN  1
1  0.0  1
2  1.0  0
3  1.0  1
A    category
B       int64
```
Dataset after preprocessing:
```
B  A_0.0  A_1.0  A_not_available
0  1    0.0    0.0              1.0
1  1    1.0    0.0              0.0
2  0    0.0    1.0              0.0
3  1    0.0    1.0              0.0
B                    int64
A_0.0              float32
A_1.0              float32
A_not_available    float32
```
