### ISSUE TITLE
Nan values by ZERO for next version

### ISSUE THREAD

**Issue by chamsdg** [pycaret/pycaret#152]
I would just like to make a contribution that will have to be seen in the next versions
often in the real world we replace not every time the null values by the average or by the median
but rather by zero to express the understanding of a customer

AIDARA Chamsedine
From Senegal
aidarachamsedine10@gmail.com

**Comment by pycaret** [comment]
@chamsdg Hi. Can you please start reviewing the code in preprocess.py. The methods are handled in Simple_Imputer class.

Once the new method is added in preprocess.py I will also have to add that in documentation and validation control for other modules (that I can handle - no worries).

Please submit a PR with test case on dev-1.0.1 branch.

Thanks for your suggestion. Really liked it.

[ENHANCEMENT]

**Comment by pycaret** [comment]
@chamsdg Hi. Do you plan to submit a PR on this?

**Comment by chamsdg** [comment]
Hello, sorry  i will do tomorrow
I am busy with th EID Filtre(ramadan party)

Thank you
AIDARA Chamsedine
DATA SCIENTIST

**Comment by chamsdg** [comment]
Hello, sorry for the delay.
I checked the imputer class as you said
but the numeric values are replaced only by the average
and the median
while often it’s not the right way
in the real world we can find ourselves with a variable
which contains 50% of Nan values
in this case it will be absurd on our part to replace them by
average or median
this percentage represents a real behavior of the customer
then it must be replaced by zero
what you didn’t take into account
my wish is that you add this parameter(0) in addition to the
median and average

Thank you

**Comment by pycaret** [comment]
## This is now fixed on `master`.
