### ISSUE TITLE
[BUG] Attributes would be removed in `scikit-learn 0.25`

### ISSUE THREAD

**Issue by crusher083** [pycaret/pycaret#1531]
Attributes: 
- `average_intercept_`
- `average_coef_`
- `standard_intercept_`
- `standard_coef_`    

are going to be removed in new `scikit-learn` version 0.25. 

**To Reproduce**
Predict using `LogisticRegression` with `pycaret` on every dataset.

**Additional context**
Librabry needs adaptation for a newer sklearn version.

**Versions**
- python 3.8.11
- pycaret 2.3.3

**Comment by moezali1** [comment]
@crusher083 Thanks for bringing this up. We are aware of it and we are currently working on revamping the preprocessing module that will allow us to switch to the latest version of sklearn.

**Comment by kennysong** [comment]
+1 for compatibility with sklearn 1.0. 

Our team uses sklearn 1.0 in production, and want to add PyCaret, but it's quite difficult due to this issue.

**Comment by tvdboom** [comment]
v3.0 supports the latest sklearn. closing.
