### ISSUE TITLE
[BUG] Repeated calls of setup lead to extended warning output in jupyter-lab 3.1.4

### ISSUE THREAD

**Issue by sorenwacker** [pycaret/pycaret#1536]
It is a routine to remove features that are different in train and test.
```
from pycaret.classification import *
import logging

features = df.columns.to_list()
features.remove('is_test')

for i in range(10):
    
    _ = setup(df[features + ['is_test']], target='is_test', silent=True)

    model = create_model('xgboost')

    plot_model(model, plot = 'feature')
    
    fi = pd.DataFrame({'Feature': get_config('X_train').columns, 'Value' : abs(model.feature_importances_)}).sort_values(by='Value', ascending=False)

    fi = fi.reset_index(drop=True)

    top_feature = fi.loc[0,'Feature']
    
    features.remove(top_feature)

    logging.warning(f'removing feature {top_feature}')
```

This leads to extended warning output in the jupyter notebook:

```
INFO:logs:Visual Rendered Successfully
INFO:logs:plot_model() succesfully completed......................................
INFO:logs:Initializing get_config()
INFO:logs:get_config(variable=X_train)
INFO:logs:Global variable: X_train returned as         Adenine-Pos1  Agmatine-Pos2  Agmatine-Pos4  Alpha-Aminobutyrate-Pos1  \
ID                                                                             
...<here is a dataframe of my input data>...
INFO:logs:get_config() succesfully completed......................................
WARNING:root:removeing feature UnkPos29-P164-F96
```
I guess the error comes from repeated calls of setup. I would expect the warnings not to change upon repeated calls.

**Comment by moezali1** [comment]
@Yard1 Any thoughts on this?

**Comment by soerendip** [comment]
Maybe a word why I am doing this? It is a loop that removes the most predictive features. The purpose is to make train and test sets more similar to each other and to eliminate features that can discriminate both sets from each other. First I combine train and test and add a variable 'is_test' and then the features are removed until the cross validated ROC sinks below a certain threshold.

**Comment by Yard1** [comment]
Try setting `verbose=False`?

**Comment by soerendip** [comment]
`verbose=False` only remove the displayed table. It is not changing the log messages. 

This is how it looks in  the jupyter-lab 3.1.4. I have observed this before when calling setup multiple times in one session.

![image](https://user-images.githubusercontent.com/3391614/131770563-fdd4fa34-274d-4dbe-8bd8-aa7c8bfb0653.png)

**Comment by ngupta23** [comment]
Check [this link](https://github.com/pycaret/pycaret/issues/2440#issuecomment-1102683661). The solution here worked for me. We will close this for now, but feel free to reopen or create a new issue if the problem persists. Thanks!
