### ISSUE TITLE
PyCaret automl function returning the wrong model parameters?

### ISSUE THREAD

**Issue by nunon** [pycaret/pycaret#1539]
**Describe the bug**
I'm using PyCaret to solve a regression problem.

After training 3 models, I decided to use automl function.

**To Reproduce**

```python
best = automl(optimize = 'MAE')
best
```

This returns:

ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                    max_depth=None, max_features='auto', max_leaf_nodes=None,
                    max_samples=None, min_impurity_decrease=0.0,
                    min_impurity_split=None, min_samples_leaf=1,
                    min_samples_split=2, min_weight_fraction_leaf=0.0,
                    n_estimators=100, n_jobs=-1, oob_score=False,
                    random_state=123, verbose=0, warm_start=False)

It seems the model (ET) is being created with the default hyper-parameters.

Although:
```python
save_model(best, model_name='best-model')
best_model
```
Returns:

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.300000012, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=-1, num_parallel_tree=1,
             objective='reg:squarederror', random_state=123, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='auto',
             validate_parameters=1, verbosity=0)

**Expected behavior**

**Additional context**

**Versions**
<details>

 2.3.3

</details>

**Comment by nunon** [comment]
@moezali1 
You may see it here:
https://colab.research.google.com/drive/1Bplartd4banFwWoPsIFACZMYEYHrP1Rq?usp=sharing
The last two cells are the relevant ones.
Thank you

**Comment by moezali1** [comment]
@nunon Access denied. Can you make your Notebook public?

![image](https://user-images.githubusercontent.com/54699234/131578324-4c89c037-dbe9-43e2-8b2d-a9b9a7ebbbf3.png)

**Comment by nunon** [comment]
Oh, sorry, please try again.
I believe it is accessible now. The dataset isn't mine, I can't share it.
Thank you.

**Comment by moezali1** [comment]
@nunon Nope, unfortunately same issue:

![image](https://user-images.githubusercontent.com/54699234/132416411-b931d8c1-6ffc-49c0-b353-42335d1d8d4c.png)

**Comment by nunon** [comment]
@moezali1 please check again now.
thanks!

**Comment by moezali1** [comment]
@nunon I looked at your Notebook and I find nothing wrong. You did `compare_models` and then a couple of the `create_model` and `tune_model` calls. This is the model that gets picked up in the `automl` function based on MAE. 

![image](https://user-images.githubusercontent.com/54699234/134772423-c4a33db5-a1ad-4331-af71-15122f08c016.png)

This is correct and expected behavior. This is the lowest `MAE` you have got in your current run as shown in the Notebook.

**Comment by nunon** [comment]
@moezali1 
The issue is the model deployment as per script test_predict.ypnb

from pycaret.regression import *
new_prediction = predict_model(saved_final_lightgbm, data = data_unseen)

Returns error:
ValueError: Pipeline not found
