### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sharlalka0805** [pycaret/pycaret#1540]
**Describe the bug**
Unable to install pycare on local desktop 

**To Reproduce**
Download and install Python and then use PyCharm IDE . 
Create a new project and go to settings and Python interpretor and try to install Pycaret from there 

```python
<Paste your code here>
```

**Expected behavior**
library should get install wihout any issue

**Additional context**

**Versions**
<details>

</details>

Full error Stack : 

C:\Users\User\Desktop\Documents\05_01_Study_Materials\Purdue\Fall_2021\MOD_1\Industry_Practicum\PyCaret>pip install pycaret
Defaulting to user installation because normal site-packages is not writeable
Collecting pycaret
  Using cached pycaret-2.3.3-py3-none-any.whl (264 kB)
Collecting textblob
  Using cached textblob-0.15.3-py2.py3-none-any.whl (636 kB)
Collecting scipy<=1.5.4
  Using cached scipy-1.5.4-cp38-cp38-win_amd64.whl (31.4 MB)
Collecting Boruta
  Using cached Boruta-0.3-py3-none-any.whl (56 kB)
Collecting pandas-profiling>=2.8.0
  Using cached pandas_profiling-3.0.0-py2.py3-none-any.whl (248 kB)
Collecting lightgbm>=2.3.1
  Using cached lightgbm-3.2.1-py3-none-win_amd64.whl (1.0 MB)
Collecting gensim<4.0.0
  Using cached gensim-3.8.3-cp38-cp38-win_amd64.whl (24.2 MB)
Requirement already satisfied: seaborn in c:\program files\lib\site-packages (from pycaret) (0.11.1)
Collecting cufflinks>=0.17.0
  Using cached cufflinks-0.17.3-py3-none-any.whl
Requirement already satisfied: nltk in c:\program files\lib\site-packages (from pycaret) (3.5)
Collecting mlflow
  Using cached mlflow-1.20.1-py3-none-any.whl (14.6 MB)
Collecting mlxtend>=0.17.0
  Using cached mlxtend-0.18.0-py2.py3-none-any.whl (1.3 MB)
Requirement already satisfied: IPython in c:\program files\lib\site-packages (from pycaret) (7.22.0)
Collecting umap-learn
  Using cached umap_learn-0.5.1-py3-none-any.whl
Collecting pyLDAvis
  Using cached pyLDAvis-3.3.1.tar.gz (1.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting scikit-plot
  Using cached scikit_plot-0.3.7-py3-none-any.whl (33 kB)
Collecting plotly>=4.4.1
  Using cached plotly-5.2.2-py2.py3-none-any.whl (21.8 MB)
Collecting spacy<2.4.0
  Using cached spacy-2.3.7-cp38-cp38-win_amd64.whl (9.7 MB)
Collecting imbalanced-learn==0.7.0
  Using cached imbalanced_learn-0.7.0-py3-none-any.whl (167 kB)
Collecting wordcloud
  Using cached wordcloud-1.8.1-cp38-cp38-win_amd64.whl (155 kB)
Collecting kmodes>=0.10.1
  Using cached kmodes-0.11.0-py2.py3-none-any.whl (18 kB)
Collecting pyod
  Using cached pyod-0.9.2-py3-none-any.whl
Collecting scikit-learn==0.23.2
  Using cached scikit_learn-0.23.2-cp38-cp38-win_amd64.whl (6.8 MB)
Requirement already satisfied: matplotlib in c:\program files\lib\site-packages (from pycaret) (3.4.1)
Requirement already satisfied: numpy==1.19.5 in c:\program files\lib\site-packages (from pycaret) (1.19.5)
Requirement already satisfied: joblib in c:\program files\lib\site-packages (from pycaret) (1.0.1)
Requirement already satisfied: pandas in c:\program files\lib\site-packages (from pycaret) (1.2.3)
Collecting yellowbrick>=1.0.1
  Using cached yellowbrick-1.3.post1-py3-none-any.whl (271 kB)
Requirement already satisfied: ipywidgets in c:\users\user\appdata\roaming\python\python38\site-packages (from pycaret) (7.6.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\program files\lib\site-packages (from scikit-learn==0.23.2->pycaret) (2.1.0)
Requirement already satisfied: six>=1.9.0 in c:\program files\lib\site-packages (from cufflinks>=0.17.0->pycaret) (1.15.0)
Requirement already satisfied: setuptools>=34.4.1 in c:\program files\lib\site-packages (from cufflinks>=0.17.0->pycaret) (49.2.1)
Collecting colorlover>=0.2.1
  Using cached colorlover-0.3.0-py3-none-any.whl (8.9 kB)
Requirement already satisfied: smart-open>=1.8.1 in c:\program files\lib\site-packages (from gensim<4.0.0->pycaret) (5.0.0)
Collecting Cython==0.29.14
  Using cached Cython-0.29.14-cp38-cp38-win_amd64.whl (1.7 MB)
Requirement already satisfied: traitlets>=4.2 in c:\program files\lib\site-packages (from IPython->pycaret) (5.0.5)
Requirement already satisfied: jedi>=0.16 in c:\program files\lib\site-packages (from IPython->pycaret) (0.18.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\program files\lib\site-packages (from IPython->pycaret) (3.0.18)
Requirement already satisfied: backcall in c:\program files\lib\site-packages (from IPython->pycaret) (0.2.0)
Requirement already satisfied: pickleshare in c:\program files\lib\site-packages (from IPython->pycaret) (0.7.5)
Requirement already satisfied: decorator in c:\program files\lib\site-packages (from IPython->pycaret) (5.0.5)
Requirement already satisfied: pygments in c:\program files\lib\site-packages (from IPython->pycaret) (2.8.1)
Requirement already satisfied: colorama in c:\program files\lib\site-packages (from IPython->pycaret) (0.4.4)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\users\user\appdata\roaming\python\python38\site-packages (from ipywidgets->pycaret) (3.5.1)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in c:\users\user\appdata\roaming\python\python38\site-packages (from ipywidgets->pycaret) (1.0.0)
Requirement already satisfied: ipykernel>=4.5.1 in c:\program files\lib\site-packages (from ipywidgets->pycaret) (5.5.3)
Requirement already satisfied: nbformat>=4.2.0 in c:\program files\lib\site-packages (from ipywidgets->pycaret) (5.1.3)
Requirement already satisfied: tornado>=4.2 in c:\program files\lib\site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (6.1)
Requirement already satisfied: jupyter-client in c:\program files\lib\site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (6.1.12)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\program files\lib\site-packages (from jedi>=0.16->IPython->pycaret) (0.8.2)
Requirement already satisfied: wheel in c:\program files\lib\site-packages (from lightgbm>=2.3.1->pycaret) (0.36.2)
Requirement already satisfied: cycler>=0.10 in c:\program files\lib\site-packages (from matplotlib->pycaret) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\program files\lib\site-packages (from matplotlib->pycaret) (1.3.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\program files\lib\site-packages (from matplotlib->pycaret) (2.8.1)
Requirement already satisfied: pyparsing>=2.2.1 in c:\program files\lib\site-packages (from matplotlib->pycaret) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in c:\program files\lib\site-packages (from matplotlib->pycaret) (8.2.0)
Requirement already satisfied: jupyter-core in c:\program files\lib\site-packages (from nbformat>=4.2.0->ipywidgets->pycaret) (4.7.1)
Requirement already satisfied: ipython-genutils in c:\program files\lib\site-packages (from nbformat>=4.2.0->ipywidgets->pycaret) (0.2.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\program files\lib\site-packages (from nbformat>=4.2.0->ipywidgets->pycaret) (3.2.0)
Requirement already satisfied: attrs>=17.4.0 in c:\program files\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->pycaret) (20.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\program files\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->pycaret) (0.17.3)
Requirement already satisfied: pytz>=2017.3 in c:\program files\lib\site-packages (from pandas->pycaret) (2021.1)
Collecting tangled-up-in-unicode==0.1.0
  Using cached tangled_up_in_unicode-0.1.0-py3-none-any.whl (3.1 MB)
Collecting phik>=0.11.1
  Using cached phik-0.12.0-cp38-cp38-win_amd64.whl (659 kB)
Requirement already satisfied: tqdm>=4.48.2 in c:\program files\lib\site-packages (from pandas-profiling>=2.8.0->pycaret) (4.60.0)
Collecting visions[type_image_path]==0.7.1
  Using cached visions-0.7.1-py3-none-any.whl (102 kB)
Requirement already satisfied: PyYAML>=5.0.0 in c:\program files\lib\site-packages (from pandas-profiling>=2.8.0->pycaret) (5.4.1)
Collecting missingno>=0.4.2
  Using cached missingno-0.5.0-py3-none-any.whl (8.8 kB)
Collecting htmlmin>=0.1.12
  Using cached htmlmin-0.1.12-py3-none-any.whl
Requirement already satisfied: requests>=2.24.0 in c:\program files\lib\site-packages (from pandas-profiling>=2.8.0->pycaret) (2.25.1)
Collecting pydantic>=1.8.1
  Using cached pydantic-1.8.2-cp38-cp38-win_amd64.whl (2.0 MB)
Requirement already satisfied: jinja2>=2.11.1 in c:\program files\lib\site-packages (from pandas-profiling>=2.8.0->pycaret) (3.0.1)
Collecting bottleneck
  Using cached Bottleneck-1.3.2.tar.gz (88 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting networkx>=2.4
  Using cached networkx-2.6.2-py3-none-any.whl (1.9 MB)
Collecting multimethod==1.4
  Using cached multimethod-1.4-py2.py3-none-any.whl (7.3 kB)
Collecting imagehash
  Using cached ImageHash-4.2.1-py2.py3-none-any.whl
Requirement already satisfied: MarkupSafe>=2.0 in c:\program files\lib\site-packages (from jinja2>=2.11.1->pandas-profiling>=2.8.0->pycaret) (2.0.1)
Collecting tenacity>=6.2.0
  Using cached tenacity-8.0.1-py3-none-any.whl (24 kB)
Requirement already satisfied: wcwidth in c:\program files\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->IPython->pycaret) (0.2.5)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\program files\lib\site-packages (from pydantic>=1.8.1->pandas-profiling>=2.8.0->pycaret) (3.7.4.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\program files\lib\site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (1.26.4)
Requirement already satisfied: idna<3,>=2.5 in c:\program files\lib\site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\lib\site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\program files\lib\site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (4.0.0)
Collecting cymem<2.1.0,>=2.0.2
  Using cached cymem-2.0.5-cp38-cp38-win_amd64.whl (36 kB)
Collecting srsly<1.1.0,>=1.0.2
  Using cached srsly-1.0.5-cp38-cp38-win_amd64.whl (178 kB)
Collecting catalogue<1.1.0,>=0.0.7
  Using cached catalogue-1.0.0-py2.py3-none-any.whl (7.7 kB)
Collecting blis<0.8.0,>=0.4.0
  Using cached blis-0.7.4-cp38-cp38-win_amd64.whl (6.5 MB)
Collecting wasabi<1.1.0,>=0.4.0
  Using cached wasabi-0.8.2-py3-none-any.whl (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0
  Using cached murmurhash-1.0.5-cp38-cp38-win_amd64.whl (21 kB)
Collecting thinc<7.5.0,>=7.4.1
  Using cached thinc-7.4.5-cp38-cp38-win_amd64.whl (910 kB)
Collecting preshed<3.1.0,>=3.0.2
  Using cached preshed-3.0.5-cp38-cp38-win_amd64.whl (112 kB)
Collecting plac<1.2.0,>=0.9.6
  Using cached plac-1.1.3-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: notebook>=4.4.1 in c:\program files\lib\site-packages (from widgetsnbextension~=3.5.0->ipywidgets->pycaret) (6.3.0)
Requirement already satisfied: Send2Trash>=1.5.0 in c:\program files\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (1.5.0)
Requirement already satisfied: terminado>=0.8.3 in c:\program files\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.9.4)
Requirement already satisfied: argon2-cffi in c:\program files\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (20.1.0)
Requirement already satisfied: pyzmq>=17 in c:\program files\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (22.0.3)
Requirement already satisfied: prometheus-client in c:\program files\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.10.0)
Requirement already satisfied: nbconvert in c:\program files\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (6.0.7)
Requirement already satisfied: pywin32>=1.0 in c:\program files\lib\site-packages (from jupyter-core->nbformat>=4.2.0->ipywidgets->pycaret) (300)
Requirement already satisfied: pywinpty>=0.5 in c:\program files\lib\site-packages (from terminado>=0.8.3->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.5.7)
Requirement already satisfied: cffi>=1.0.0 in c:\program files\lib\site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (1.14.5)
Requirement already satisfied: pycparser in c:\program files\lib\site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (2.20)
Collecting PyWavelets
  Using cached PyWavelets-1.1.1-cp38-cp38-win_amd64.whl (4.3 MB)
Requirement already satisfied: click>=7.0 in c:\program files\lib\site-packages (from mlflow->pycaret) (7.1.2)
Requirement already satisfied: sqlalchemy in c:\users\user\appdata\roaming\python\python38\site-packages (from mlflow->pycaret) (1.4.17)
Requirement already satisfied: packaging in c:\program files\lib\site-packages (from mlflow->pycaret) (20.9)
Collecting importlib-metadata!=4.7.0,>=3.7.0
  Using cached importlib_metadata-4.7.1-py3-none-any.whl (17 kB)
Collecting querystring-parser
  Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
Collecting alembic<=1.4.1
  Using cached alembic-1.4.1-py2.py3-none-any.whl
Collecting prometheus-flask-exporter
  Using cached prometheus_flask_exporter-0.18.2-py3-none-any.whl
Requirement already satisfied: protobuf>=3.7.0 in c:\program files\lib\site-packages (from mlflow->pycaret) (3.15.8)
Collecting databricks-cli>=0.8.7
  Using cached databricks_cli-0.15.0-py3-none-any.whl
Requirement already satisfied: entrypoints in c:\program files\lib\site-packages (from mlflow->pycaret) (0.3)
Collecting waitress
  Using cached waitress-2.0.0-py3-none-any.whl (56 kB)
Requirement already satisfied: gitpython>=2.1.0 in c:\users\user\appdata\roaming\python\python38\site-packages (from mlflow->pycaret) (3.1.17)
Requirement already satisfied: Flask in c:\program files\lib\site-packages (from mlflow->pycaret) (1.1.2)
Collecting cloudpickle
  Using cached cloudpickle-1.6.0-py3-none-any.whl (23 kB)
Collecting docker>=4.0.0
  Using cached docker-5.0.0-py2.py3-none-any.whl (146 kB)
Requirement already satisfied: sqlparse>=0.3.1 in c:\users\user\appdata\roaming\python\python38\site-packages (from mlflow->pycaret) (0.4.1)
Collecting python-editor>=0.3
  Using cached python_editor-1.0.4-py3-none-any.whl (4.9 kB)
Collecting Mako
  Using cached Mako-1.1.5-py2.py3-none-any.whl (75 kB)
Collecting tabulate>=0.7.7
  Using cached tabulate-0.8.9-py3-none-any.whl (25 kB)
Collecting websocket-client>=0.32.0
  Using cached websocket_client-1.2.1-py2.py3-none-any.whl (52 kB)
Collecting pywin32>=1.0
  Using cached pywin32-227-cp38-cp38-win_amd64.whl (9.1 MB)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\user\appdata\roaming\python\python38\site-packages (from gitpython>=2.1.0->mlflow->pycaret) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\user\appdata\roaming\python\python38\site-packages (from gitdb<5,>=4.0.1->gitpython>=2.1.0->mlflow->pycaret) (4.0.0)
Collecting zipp>=0.5
  Using cached zipp-3.5.0-py3-none-any.whl (5.7 kB)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\user\appdata\roaming\python\python38\site-packages (from sqlalchemy->mlflow->pycaret) (1.1.0)
Requirement already satisfied: itsdangerous>=0.24 in c:\program files\lib\site-packages (from Flask->mlflow->pycaret) (2.0.1)
Requirement already satisfied: Werkzeug>=0.15 in c:\program files\lib\site-packages (from Flask->mlflow->pycaret) (2.0.1)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\program files\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (1.4.3)
Requirement already satisfied: bleach in c:\program files\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (3.3.0)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\program files\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.5.3)
Requirement already satisfied: jupyterlab-pygments in c:\program files\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.1.2)
Requirement already satisfied: defusedxml in c:\program files\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.7.1)
Requirement already satisfied: testpath in c:\program files\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.4.4)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\program files\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.8.4)
Requirement already satisfied: nest-asyncio in c:\program files\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (1.5.1)
Requirement already satisfied: async-generator in c:\program files\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (1.10)
Requirement already satisfied: webencodings in c:\program files\lib\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.5.1)
Requirement already satisfied: regex in c:\program files\lib\site-packages (from nltk->pycaret) (2021.4.4)
Collecting numexpr
  Using cached numexpr-2.7.3-cp38-cp38-win_amd64.whl (93 kB)
Requirement already satisfied: future in c:\users\user\appdata\roaming\python\python38\site-packages (from pyLDAvis->pycaret) (0.18.2)
Collecting sklearn
  Using cached sklearn-0.0.tar.gz (1.1 kB)
Collecting funcy
  Using cached funcy-1.16-py2.py3-none-any.whl (32 kB)
Collecting pyLDAvis
  Using cached pyLDAvis-3.3.0.tar.gz (1.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
  Using cached pyLDAvis-3.2.2-py2.py3-none-any.whl
Collecting numba>=0.35
  Using cached numba-0.54.0-cp38-cp38-win_amd64.whl (2.3 MB)
Collecting statsmodels
  Using cached statsmodels-0.12.2-cp38-none-win_amd64.whl (9.4 MB)
Collecting llvmlite<0.38,>=0.37.0rc1
  Using cached llvmlite-0.37.0-cp38-cp38-win_amd64.whl (17.0 MB)
Collecting patsy>=0.5
  Using cached patsy-0.5.1-py2.py3-none-any.whl (231 kB)
Collecting pynndescent>=0.5
  Using cached pynndescent-0.5.4-py3-none-any.whl
Building wheels for collected packages: bottleneck
  Building wheel for bottleneck (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\program files\python.exe' 'C:\Users\User\AppData\Roaming\Python\Python38\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\User\AppData\Local\Temp\tmpp4kdeief'
       cwd: C:\Users\User\AppData\Local\Temp\pip-install-ib9kmoi1\bottleneck_93a0774157f0408e9691d464221a4b8a
  Complete output (51 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\bottleneck
  copying bottleneck\_pytesttester.py -> build\lib.win-amd64-3.8\bottleneck
  copying bottleneck\_version.py -> build\lib.win-amd64-3.8\bottleneck
  copying bottleneck\__init__.py -> build\lib.win-amd64-3.8\bottleneck
  creating build\lib.win-amd64-3.8\bottleneck\benchmark
  copying bottleneck\benchmark\autotimeit.py -> build\lib.win-amd64-3.8\bottleneck\benchmark
  copying bottleneck\benchmark\bench.py -> build\lib.win-amd64-3.8\bottleneck\benchmark
  copying bottleneck\benchmark\bench_detailed.py -> build\lib.win-amd64-3.8\bottleneck\benchmark
  copying bottleneck\benchmark\__init__.py -> build\lib.win-amd64-3.8\bottleneck\benchmark
  creating build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\move.py -> build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\nonreduce.py -> build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\nonreduce_axis.py -> build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\reduce.py -> build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\__init__.py -> build\lib.win-amd64-3.8\bottleneck\slow
  creating build\lib.win-amd64-3.8\bottleneck\src
  copying bottleneck\src\bn_config.py -> build\lib.win-amd64-3.8\bottleneck\src
  copying bottleneck\src\bn_template.py -> build\lib.win-amd64-3.8\bottleneck\src
  copying bottleneck\src\__init__.py -> build\lib.win-amd64-3.8\bottleneck\src
  creating build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\input_modification_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\list_input_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\memory_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\move_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\nonreduce_axis_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\nonreduce_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\reduce_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\scalar_input_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\util.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\__init__.py -> build\lib.win-amd64-3.8\bottleneck\tests
  UPDATING build\lib.win-amd64-3.8\bottleneck/_version.py
  set build\lib.win-amd64-3.8\bottleneck/_version.py to '1.3.2'
  running build_ext
  running config
  compiling '_configtest.c':
  
  
  
  int __attribute__((optimize("O3"))) have_attribute_optimize_opt_3(void*);
  
  int main(void)
  {
      return 0;
  }
  
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for bottleneck
Failed to build bottleneck
ERROR: Could not build wheels for bottleneck which use PEP 517 and cannot be installed directly

**Comment by moezali1** [comment]
@sharlalka0805 Please install bottleneck library before installing pycaret and this may fix the issue. 

```
conda install bottleneck
pip install pycaret
```
