### ISSUE TITLE
Hey! Pleas add neural network, and i think this library be the best in the world, maybe use scikit learn neural network on book "python one lines"!?? 

### ISSUE THREAD

**Issue by kingtelepuz5** [pycaret/pycaret#1541]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**
A clear and concise description of what you want to happen, ideally taking into consideration the existing toolbox design, classes and methods. 

**Describe alternatives you've considered**

**Additional context**

**Comment by moezali1** [comment]
@kingtelepuz5 You can use mlp in pycaret just like any other model. See example:

```
from pycaret.datasets import get_data
data = get_data('juice')

from pycaret.classification import *
s = setup(data, target = 'Purchase', silent = True)

mlp = create_model('mlp')
```

![image](https://user-images.githubusercontent.com/54699234/131220385-478b01bc-a24e-4edc-a551-7869916efe1d.png)

Hope this helps.

**Comment by kingtelepuz5** [comment]
yes! thansk so much :)
