### ISSUE TITLE
Modeling on a sample of data

### ISSUE THREAD

**Issue by KarinaYabra** [pycaret/pycaret#1546]
When I initialize the Setup, PyCaret does not ask the sample size and considers all the database (590,000 rows x 15 columns). Then, when trying to run the different models it crashes due to memory issues. What should I do so that I can consider x% of the database as a sample to run everything? Thanks.

**Comment by KarinaYabra** [comment]
Hi, thanks for the answer. I thought about that but the thing is that I know that Pycaret does a preliminary sample analysis where it shows a graph with the metric (let say accuracy) based on the sample size so that one can choose the optimal size and if I sample the data on my own I loose that.

**Comment by Yard1** [comment]
That feature has been removed in one of the updates, as we have decided it didn't provide enough value to justify the cost of maintaining it. Sorry.

**Comment by KarinaYabra** [comment]
Ok, thank you so much for the answer.
