### ISSUE TITLE
Not using GPU for Light GBM

### ISSUE THREAD

**Issue by lokesharya99** [pycaret/pycaret#1547]
Hi Team,

I'm trying to train a model on Kaggle using pycaret, i have data for more than 50k observations, I have specified use gpu as True, but Pycaret is unable to train Light GBM on GPU, I have tried the tutorial given here but still not using GPU more then 2-3% 
as shown in the Image CPU is going upto 200% but GPU is 0.

Catboost and XGB are able to run on GPU.

![image](https://user-images.githubusercontent.com/49523069/131864706-3158fa35-49f1-469d-a158-85f998601088.png)

Can anyone help me out how should we use GPU for Light GBM.

Thank in advance.
Regards

**Comment by lokesharya99** [comment]
Tried the way given on pycaret github page for colab.

I'm using kaggle so i believe there is no need to install GPU version there. But i still tried uninstalling existing version and installing GPU version.

**Comment by moezali1** [comment]
@lokesharya99 Please follow this Notebook for LightGBM GPU installation on Kaggle: https://www.kaggle.com/abhishek/running-lightgbm-on-gpu
