### ISSUE TITLE
How can I make the plot output by plot be of svg type, or I can customize the DPI? The clarity of the existing graphs does not meet the journal's requirements

### ISSUE THREAD

**Issue by moon195** [pycaret/pycaret#1550]
How can I make the plot output by plot be of svg type, or I can customize the DPI? The clarity of the existing graphs does not meet the journal's requirements
at lest 300dpi

**Comment by moezali1** [comment]
Hi @moon195 

There is a `scale` parameter in the `plot_model` function that you can use to control the resolutions of the graphic.

![image](https://user-images.githubusercontent.com/54699234/132416236-fdecd54c-3287-4bf2-b6fe-b37f88b9ecdb.png)

Check out documentation: https://pycaret.readthedocs.io/en/latest/api/classification.html

**Comment by moon195** [comment]
Thanks for your reply, I finally modified it pycaret/internal/plots/yellowbrick.py，replace .png with .svg.It worked.Successfully make the  plot model output svg format.
