### ISSUE TITLE
Hide these parameters in plot_model function for time_series

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1555]
Can we hide the following parameters from the `plot_model` function in `pycaret.time_series`:
    
![image](https://user-images.githubusercontent.com/54699234/132988285-503c412a-dd38-4a1a-8b1f-3ed6080fb24d.png)

    scale: float = 1, ------ not applicable as we are using plotly now 
    save: bool = False, -------- not applicable as you can save plotly graph through front-end
    fold: Union[int, Any, NoneType] = None, ----- not applicable
    fit_kwargs: Union[dict, NoneType] = None, ---- not applicable as no fitting will happen during plot_model
    use_train_data: bool = False, ---- not applicable on time_series
    verbose: bool = True, ------- not applicable
    system: bool = True, ---------- not applicable (its used internally but user has nothing to do with this).

Thanks.

**Comment by ngupta23** [comment]
@moezali1 - Removed all unnecessary ones except `system`. That is needed for the unit tests to pass (@Yard1 - added this).

**Comment by Yard1** [comment]
We probably can remove system and use something like an env var. Will add that to my PR.

**Comment by moezali1** [comment]
I can still see those parameters:

![image](https://user-images.githubusercontent.com/54699234/134771996-c461a27e-6dd9-45d0-a38b-468c849a8a32.png)

**Comment by ngupta23** [comment]
I forgot to remove them from functional API. I will remove them in the next PR shortly.
