### ISSUE TITLE
check_stats(test='summary') not working in time_series module

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1557]
check_stats(test='summary') not working in time_series module. All other tests work just fine!

```
from pycaret.datasets import get_data
data = get_data('airline')

from pycaret.time_series import *
s = setup(data, fold = 5, fh = 12, session_id = 123)

check_stats(test='summary')
```

ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_25192/3830716122.py in <module>
----> 1 check_stats(test='summary')

~\pycaret\pycaret\internal\utils.py in wrapper(*args, **kwargs)
    780                 if globals_d[name] is None:
    781                     raise ValueError(message)
--> 782             return func(*args, **kwargs)
    783 
    784         return wrapper

~\pycaret\pycaret\time_series.py in check_stats(estimator, test, alpha, split)
   1902 ) -> pd.DataFrame:
   1903 
-> 1904     return _CURRENT_EXPERIMENT.check_stats(
   1905         estimator=estimator, test=test, alpha=alpha, split=split,
   1906     )

~\pycaret\pycaret\internal\pycaret_experiment\time_series_experiment.py in check_stats(self, estimator, test, alpha, split)
   3313         if estimator is None:
   3314             data = self._get_y_data(split=split)
-> 3315             results = test_(data=data, test=test, alpha=alpha)
   3316         else:
   3317             raise NotImplementedError(

~\pycaret\pycaret\internal\tests\time_series.py in test_(data, test, alpha, *kwargs)
     39         results = is_gaussian(data=data, alpha=alpha, verbose=True)[1]
     40     else:
---> 41         raise ValueError(f"Tests: '{test}' is not supported.")
     42     return results
     43 

ValueError: Tests: 'summary' is not supported.

**Comment by ngupta23** [comment]
It was called `summary_stats` earlier. Fixed to `summary` now.

**Comment by moezali1** [comment]
Now `check_stats='summary'` shows following error:

![image](https://user-images.githubusercontent.com/54699234/134771786-4ac1db97-2d6d-43db-901c-94a5a549fb60.png)

**Comment by ngupta23** [comment]
try with explicit argument since estimator is the first argument in the function

`check_stats(test="summary")`
