### ISSUE TITLE
load_model not working without setup in time_series module

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1558]
This is a critical bug.

**TRAINING PHASE**
```
from pycaret.datasets import get_data
data = get_data('airline')

from pycaret.time_series import *
s = setup(data, fold = 5, fh = 12, session_id = 123)

best = compare_models()

save_model(best, 'best-model')
```
It works fine. Model is saved. The problem happens during prediction. See below:

**PREDICTION PHASE (IN NEW NOTEBOOK)**

```
from pycaret.time_series import load_model
l = load_model('best-model')
```
ValueError: _CURRENT_EXPERIMENT global variable is not set. Please run setup() first.

**Comment by moezali1** [comment]
It working for Object-Oriented API but does not work for functional API.

**Comment by Yard1** [comment]
Ok, will look into it
