### ISSUE TITLE
metric grid in the predict_model function of time_series

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1561]
metric grid in the predict_model function of time_series

When the `predict_model` function is used without the `fh` parameter the metric grid makes sense as it is evaluated on the test set. However, when `fh` is not `None` metrics doesn't make sense since it is expected that `predict_model` used with `fh` None means the user is generating predictions in the unknown future.  The test set is an exception that's why `predict_model(model)` just by itself is valid only when `fh=None`.

Please change this behavior as such when `fh` is not None the metric evaluation shouldn't be performed or shown (leave it up to you).

Example:
![image](https://user-images.githubusercontent.com/54699234/132992074-7cbc823f-926d-496b-9f14-0002819b99d1.png)

**Comment by ngupta23** [comment]
Only show the test set metrics when fh is None. For a user defined fh, do not show test metrics.

Enhancement: if fh < one used for training, then we can show it.

**Comment by ngupta23** [comment]
@moezali1 

I think I already take care of this [Link](https://github.com/pycaret/pycaret/blob/e08165bb1a6e920f7596421716415620fa994b4f/pycaret/internal/pycaret_experiment/time_series_experiment.py#L2690). This is what the logic is doing

1. If fh is not provided, then use fh provided during training
2. If fh is provided and is < fh used during training, then use only the common periods to compute the metrics
3. Similarly, if fh is provided and is > fh used during training, then use only the common periods to compute the metrics

Let me know if this is acceptable.

**Comment by moezali1** [comment]
@ngupta23 I propose we keep it simple. If the `fh` is provided, do not show the grid at all and only show the forecast. What do you think? If people request dynamic metric scoring on test set with varied `fh` ranges, we can later add it as an enhancement.

**Comment by moezali1** [comment]
As discussed:

Keep the functionality. but when `fh` is not None. Let's print and log a generic exception saying something about "metric grid is evaluated only for common periods ....."

**Comment by moezali1** [comment]
Re-discussed:

Please implement if `fh` is not None and `X_test` doesn't exist in the global environment then do not display metric grid.

Use-case: If I try to use the trained model in the new Notebook where X_test doesn't exist in the global environment, the Metric grid is all NaN.

**Comment by ngupta23** [comment]
@moezali1 How do I reproduce this? I am not seeing the metrics displayed on my end.

![image](https://user-images.githubusercontent.com/33585645/134789965-b4cc7caa-41f2-48a6-9f05-48a65b92fcc7.png)

**Comment by moezali1** [comment]
@ngupta23 You are using the `predict` method from the class itself. You should do this instead:

```
exp.predict_model(m)
```

**Comment by ngupta23** [comment]
@moezali1  Please check out the PR for this fix. Thanks!
