### ISSUE TITLE
plot renames in plot_model function of time_series

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1562]
plot renames in plot_model function of time_series

Can you please rename plots as per following:

'splits-tt' --> 'train_test_split'
'splits_cv' --> 'cv'
'predictions' --> 'forecast'

**Comment by moezali1** [comment]
wrong plot showing up with `plot='cv'`:

![image](https://user-images.githubusercontent.com/54699234/134771754-ab33d0ff-6603-4ecd-902b-1b7121b037a1.png)

**Comment by ngupta23** [comment]
Estimator is the first argument. Can you try with `plot="cv"` explicitly?
