### ISSUE TITLE
Title when plot = 'predictions' in plot_model of time_series

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1565]
Model name should appear in the title when plot = 'predictions' in plot_model of time_series

Currently:

```
from pycaret.datasets import get_data
data = get_data('airline')

from pycaret.time_series import *
s = setup(data, fold = 5, fh = 12, session_id = 123)

naive = create_model('naive', verbose=False)
plot_model(naive, plot = 'predictions')
```

![image](https://user-images.githubusercontent.com/54699234/132992315-31d6d3aa-9fc4-43a4-b8eb-3993fbce41b0.png)

Also, Forecasts in the title should be reworded to Forecast.

**Comment by ngupta23** [comment]
Get model container from model object, then get model name from container.

**Comment by moezali1** [comment]
I still don't see the model name in the title. I see in legend. Is it possible to add in the title? 

![image](https://user-images.githubusercontent.com/54699234/134772047-754d3339-0ef3-4a60-af39-981d674a2c75.png)

Adding them to the title makes it more readable. I understand why you used `Forecast(s)` in the title so that we can re-use the same function for multiple models being plotted on the same graph. I say we can deal with it later when we add such a plot. Most likely it will be a separate plot type and not the `forecast`. Let's keep `forecast` simple so people can build this workflow: setup --> compare_models --> plot_model(best)

**Comment by ngupta23** [comment]
Could you not have something like this pretty soon `plot_model([model1, model2, model3])`. I think that should be coming fairly quickly.

**Comment by moezali1** [comment]
As agreed: 

Title can be: {name of time_series} Actual and Forecast

If there is no name then "Actual and Forecast".
