### ISSUE TITLE
get_config for certain variables not working in time_series

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1566]
get_config for certain variables not working in time_series

```
get_config('X_test') # not working
get_config('create_model_container') # not working
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_28112/1317718211.py in <module>
----> 1 get_config('X_test')

~\pycaret\pycaret\internal\utils.py in wrapper(*args, **kwargs)
    780                 if globals_d[name] is None:
    781                     raise ValueError(message)
--> 782             return func(*args, **kwargs)
    783 
    784         return wrapper

~\pycaret\pycaret\time_series.py in get_config(variable)
   1779     """
   1780 
-> 1781     return _CURRENT_EXPERIMENT.get_config(variable=variable)
   1782 
   1783 

~\pycaret\pycaret\internal\pycaret_experiment\pycaret_experiment.py in get_config(self, variable)
    281 
    282         if variable not in self.variables:
--> 283             raise ValueError(
    284                 f"Variable {variable} not found. Possible variables are: {list(self.variables)}"
    285             )

ValueError: Variable X_test not found. Possible variables are: ['data_before_preprocess', '_gpu_n_jobs_param', 'exp_name_log', 'logging_param', '_available_plots', '_ml_usecase', 'fh', '_all_models_internal', 'X_train', 'exp_id', 'experiment__', '_all_models', 'seasonal_period', 'fold_param', 'fold_groups_param_full', 'USI', 'y', 'seed', 'log_plots_param', 'y_test', 'gpu_param', 'display_container', 'prep_pipe', 'n_jobs_param', 'seasonality_present', 'html_param', '_internal_pipeline', 'master_model_container', 'variable_keys', '_all_metrics', 'y_train', 'fold_generator']

**Comment by ngupta23** [comment]
@moezali1 @Yard1 

I got `X_test` to work, but `create_model_container` does not work. I checked and it does not work for regression either.

```python
from pycaret.datasets import get_data

dataset = get_data("diamond")
data = dataset.sample(frac=0.9, random_state=786).reset_index(drop=True)
data_unseen = dataset.drop(data.index).reset_index(drop=True)

from pycaret.regression import *

exp_reg101 = setup(data=data, target="Price", session_id=123, silent=True)
compare_models(["ada", "dt"])
temp = get_config("create_model_container")
```

```python
File "c:\Users\Nikhil\OneDrive\my_libraries\my_python_libraries\pycaret_dev\pycaret\internal\pycaret_experiment\pycaret_experiment.py", line 284, in get_config
    f"Variable {variable} not found. Possible variables are: {list(self.variables)}"
ValueError: Variable create_model_container not found. Possible variables are: ['y', 'fold_groups_param', 'X_train', 'prep_pipe', 'master_model_container', 'y_train', 'html_param', '_all_metrics', 'fold_generator', '_all_models_internal', 'imputation_classifier', '_all_models', 'fold_param', 'log_plots_param', '_internal_pipeline', 'seed', 'transform_target_param', '_gpu_n_jobs_param', 'stratify_param', 'y_test', 'data_before_preprocess', '_ml_usecase', 'experiment__', 'transform_target_method_param', 'X', 'exp_name_log', 'X_test', 'USI', 'fold_groups_param_full', 'variable_keys', 'display_container', 'gpu_param', 'exp_id', 'fold_shuffle_param', 'target_param', '_available_plots', 'iterative_imputation_iters_param', 'imputation_regressor', 'logging_param', 'n_jobs_param']
```

**Comment by Yard1** [comment]
@ngupta23 Looks like we got rid of it, so it's a matter of updating documentation. Will add that to my PR.
