### ISSUE TITLE
plot_model(plot='splits_cv') improvement in time_series

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1569]
plot_model(plot='splits_cv') improvement in time_series

Two improvements:

1. Can we limit the y-axis to only integer labels. See the example below in which we see 0.5, 1.5, 2.5:
![image](https://user-images.githubusercontent.com/54699234/132992723-5202e424-65fd-449a-9e49-32d6f0a64d40.png)

2. `splits_cv` plot on the dataset with 3000+ data points takes down the entire Notebook. It makes it non-responsive. I am guessing this is happening due to a large number of hover-over points. We may have to find a way to make it work with a large number of data points efficiently.

**Comment by ngupta23** [comment]
Disable hover points above a certain number of data points * number of splits.
