### ISSUE TITLE
Compare_models() needs a better way to select models.

### ISSUE THREAD

**Issue by Srikanth421** [pycaret/pycaret#157]
The function compare_models() has an option to blacklist models but it would be better to also have something like a whitelist i.e., list models to compare rather than exclude models to compare. I'm new here and would like to contribute to the project if given a chance.

**Comment by sathishkumar369** [comment]
yes, that would be a better to give an option for selecting a list of models to train while using compare_models(). because some models take long time to train the model,when we work for large amount data. some times,it may even get stuck.

**Comment by pycaret** [comment]
@sathishkumar369 

Already in plan to be included in next release.

Marking this as enhancement.
