### ISSUE TITLE
display progress bar in compare_models of time_series behaving abnormal

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1570]
display progress bar in compare_models of time_series behaving abnormally:

The bar hits the full completion but the run isn't completed. 10+ models were remaining at this point:

![image](https://user-images.githubusercontent.com/54699234/132992847-3db8437e-8218-4204-a410-a6fc22a3c16f.png)

**Comment by Yard1** [comment]
Couldn't replicate on my end.
