### ISSUE TITLE
[BUG]building docker image fails

### ISSUE THREAD

**Issue by elBichon** [pycaret/pycaret#1575]
Hello team
I am trying to build a docker image for pycaret (both locally and in a github actions), at first I just used the dockerfile that is provided in the documentation and systematically get this error
"  ERROR: Could not build wheels for bottleneck which use PEP 517 and cannot be installed directly
  The command '/bin/sh -c pip install --trusted-host pypi.python.org -r requirements.txt' returned a non-zero code: 1"
or " ERROR: Failed building wheel for bottleneck"
The last thing I tried is as follow in the Dockerfile: 
"RUN conda install bottleneck
RUN pip install --upgrade pip setuptools wheel
RUN pip install PyPI
RUN pip install pyinstaller
RUN pip install requirements.txt"

The docker image build systematically fails whatever I do. Is the documentation up to date ? Am I maybe missing something here ?

**Comment by moezali1** [comment]
@elBichon In your docker image, can you install `bottleneck` with `conda` before running `pip install pycaret`. That should fix the issue? Let me know?

**Comment by elBichon** [comment]
Hi @moezali1, do you mean something like RUN conda install bottleneck ?
I did and now I get a "  ERROR: Could not build wheels for bottleneck which use PEP 517 and cannot be installed directly
  The command '/bin/sh -c pip install --trusted-host pypi.python.org -r requirements.txt' returned a non-zero code: 1"
  I also tried the following combinations:
  "FROM python:3.7-slim
WORKDIR /app
ADD . /app
RUN conda install bottleneck
RUN apt-get update && apt-get install -y libgomp1
RUN pip install --trusted-host pypi.python.org -r requirements.txt
CMD ["/app/app.py"]"
-----------------
FROM python:3.7-slim
WORKDIR /app
ADD . /app
RUN apt-get update && apt-get install -y libgomp1
RUN conda install bottleneck
RUN pip install --trusted-host pypi.python.org -r requirements.txt
CMD ["/app/app.py"]
-----------------
FROM python:3.7-slim
WORKDIR /app
ADD . /app
RUN apt-get update && apt-get install -y libgomp1
RUN conda install bottleneck
RUN pip install pycaret
CMD ["/app/app.py"]

always getting the same error

Thinking that it may be an issue with my github repository (you never know, I created a new one with the following dockerfile)
"FROM python:3.7-slim
WORKDIR /app
ADD . /app
RUN pip install bottleneck 
RUN apt-get update && apt-get install -y libgomp1
RUN pip install --trusted-host pypi.python.org -r requirements.txt
CMD ["/app/app.py"]"
/bin/sh: 1: conda: not found
The command '/bin/sh -c conda install bottleneck' returned a non-zero code: 127
Error: Process completed with exit code 127.

I also tried "FROM python:3.7-slim
WORKDIR /app
ADD . /app
RUN apt-get update && apt-get install -y libgomp1
RUN apt-get install curl
RUN apt-get install wget
RUN cd /tmp
RUN curl –O https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
RUN sha256sum Anaconda3–2020.02–Linux–x86_64.sh
RUN bash Anaconda3-2020.02-Linux-x86_64.sh
RUN conda install bottleneck 
RUN pip install --trusted-host pypi.python.org -r requirements.txt
CMD ["/app/app.py"]"
without succes, I guess I am still not fully understanding the dockerfile and github actions process...

**Comment by moezali1** [comment]
@wkuopt Wondering if you can help here?

**Comment by wkuopt** [comment]
Sure @moezali1 i will look into it

**Comment by elBichon** [comment]
Thanks to the two of you, if it helps, maybe I can share the repo with you ?

**Comment by wkuopt** [comment]
@elBichon Yes, could you share the repo with us so that I can investigate more? Also the error seems to be related to the installation of bottleneck. Here is the same issue that I found after a quick search: https://github.com/pydata/bottleneck/issues/281 Have you tried the solutions in it?

**Comment by wkuopt** [comment]
Hi @elBichon  , I believe this is not a Pycaret issue, since it's the bottleneck library that's causing the error. If you build Pycaret alone, then there is no issue. I will close the issue.
