### ISSUE TITLE
Is it using all available cores?

### ISSUE THREAD

**Issue by gkourogiorgas** [pycaret/pycaret#158]
Many sklearn algos have the n_jobs argument for parallelizing where possible. Is it set to -1 by default in pycaret?

**Comment by pycaret** [comment]
Yes. by default it's using -1 for n_jobs. However in the first release there were places where it was not using all cores. Those are already fixed and will be there in next release. In addition we have now given a n_jobs parameter under setup if somebody manually wants to change that.
