### ISSUE TITLE
Add Exogenous Variable Support for Time Series

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#1588]
**Is your feature request related to a problem? Please describe.**
Add ability to create multivariate time series

**Describe the solution you'd like**
Current time series module only supports univariate time series. It would be nice to have multivariate time series capability as well.

**Describe alternatives you've considered**
None available.

**Additional context**
`sktime` may have started to support some level of multivariate time series. Start by incorporating it into `pycaret`.

**Comment by ngupta23** [comment]
- [ ] Add VAR Model
    - See [comment link here](https://www.linkedin.com/feed/update/urn:li:activity:6867476659512127488?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6867476659512127488%2C6867497611818000384%29&replyUrn=urn%3Ali%3Acomment%3A%28activity%3A6867476659512127488%2C6867512755595878400%29)
- [ ] Univariate Models with exogenous variables

**Comment by ngupta23** [comment]
## Proposed `setup` interface

Supports:

1. univariate,
2. univariate with exogenous variables and
3.  vector multivariate models.

| Data Type    | # Columns | Setup Arg `target` | Setup Arg `index` | Setup Arg `type` | Setup Arg `ignore_features` | Type | Notes |
|--------------|-----------|--------------------|-------------------|------------------|-----------------------------|-------|-------|
| pd.Series         |  1       |  None                         | None       | None or "uni"    |                             | Univariate | Picks column as data and pd.index for frequency      |
| pd.DataFrame |  1       |  None                         | None       | None or "uni"    |                             | Univariate | Picks column as data and pd.index for frequency      |
| pd.DataFrame |  > 1    | 1 column specified    | None       | "uni"                   |                             | Univariate | Picks specified column as target, rest are ignored and pd.index as index      |
| pd.DataFrame |  > 2    | 1 column specified    | Specified | "uni"                   |                             | Univariate | Picks specified columns as target and index and rest as ignored      |
| pd.DataFrame |  > 1    | 1 column specified    | None       | None or "multi" |                             | Multivariate (also called "univariate with exogenous") | Picks specified column as target, rest as multivariate and pd.index as index      |
| pd.DataFrame |  > 2    | 1 column specified    | Specified | None or "multi" |                             | Multivariate (also called "univariate with exogenous") | Picks specified columns as target and index and rest as multivariate      |
| pd.DataFrame |  > 1    | > 1 column specified | None       | None                 |                             | Multivariate (Vector Based) | Picks specified columns as target, and pd.index as index and perform true multivariate - e.g. VAR      |
| pd.DataFrame |  > 3    | > 1 column specified | Specified | None                 |                             | Multivariate - (Vector Based) | Picks specifed columns as targets and index and and perform true multivariate - e.g. VAR      |


NOTES:
* When a column is selected as "index", internally it is converted using `pd.to_datetime` using default arguments and set as index.

**Comment by ngupta23** [comment]
Simplified interface after discussion with @ltsaprounis 

### Changes:

- Removed 1C and 1D. The alternate for this is as follows - If the user has a dataframe with multiple columns and wants to do univariate analysis on a single column, they can
    1. simply pass the single column to the `data` argument in `setup` or
    2. pass the rest of the columns to `ignore_features` in `setup`.

### Advantages:

- Will remove the need to add the `type` argument in setup and hence avoid confusion of what is "univariate without exogenous", "univariate with exogenous" and "multivariate".


### New Matrix of Use Cases

| Sl. No. |   Data Type  | # Columns |   Setup Arg `target`   | Setup Arg `index` |     Setup Arg `ignore_features`    |              Type             |                                                Notes                                                |
|:-------:|:------------:|:---------:|:--------------------:|:---------------:|:--------------------------------:|:-----------------------------:|:---------------------------------------------------------------------------------------------------:|
| 1A      | pd.Series    | 1         | None                 | None            | NA                               | Univariate (no exogenous)     | Picks column as data and   pd.index for frequency                                                   |
| 1B      | pd.DataFrame | 1         | None                 | None            | NA                               | Univariate (no exogenous)     | Picks column as data and   pd.index for frequency                                                   |
| 2A      | pd.DataFrame | > 1       | 1 column specified   | None            | Column specified will be ignored | Univariate (with exogenous)   | Picks specified column as   target, rest as exogenous variables and pd.index as index               |
| 2B      | pd.DataFrame | > 2       | 1 column specified   | Specified       | Column specified will be ignored | Univariate (with exogenous)   | Picks specified columns as   target and index and rest as exogenous variables                       |
| 3A      | pd.DataFrame | > 1       | > 1 column specified | None            | Column specified will be ignored | Multivariate (Vector Based)   | Picks specified columns as   target, and pd.index as index and perform true multivariate - e.g. VAR |
| 3B      | pd.DataFrame | > 3       | > 1 column specified | Specified       | Column specified will be ignored | Multivariate - (Vector Based) | Picks specifed columns as   targets and index and and perform true multivariate - e.g. VAR          |

**Comment by ngupta23** [comment]
Sample code to detect target and exogenous variables: https://gist.github.com/ngupta23/1053638d20fab6e5de84c9da43e6a455

**Comment by ngupta23** [comment]
Initial version available in `ts_exog` branch. To test

```python
import pandas as pd
from pycaret.internal.pycaret_experiment import TimeSeriesExperiment
from pycaret.datasets import get_data

data = get_data("uschange")

FH = 12
target = "Unemployment"

data_for_modeling = data.iloc[:-12]
future_data = data.iloc[-12:]
future_exog = future_data.drop(columns=target)

print(data_for_modeling.shape, future_data.shape, future_exog.shape)


#### Setup Experiment ----
exp = TimeSeriesExperiment()
exp.setup(
    data=data_for_modeling, target=target, fh=FH, seasonal_period=4, session_id=42
)

#### Baseline Model ----
model = exp.create_model("arima")
preds = exp.predict_model(model)
exp.plot_model(model)

#### Tune Model ----
tuned_model = exp.tune_model(model)
tuned_preds = exp.predict_model(tuned_model)
exp.plot_model(tuned_model)

#### Finalize Model ----
final_model = exp.finalize_model(tuned_model)
future_preds = exp.predict_model(final_model, data=future_exog)
print(future_preds)
exp.plot_model(final_model)  # Uses test split from before finalizing as future exogenous values
exp.plot_model(final_model, data_kwargs={'X_test': future_exog}) # Uses provided X_test values
```

**Comment by ngupta23** [comment]
After discussing with @ltsaprounis , it was decided that the `plot_model` functionality will be changed to avoid confusion

Earlier
```python
exp.plot_model(final_model)  # Uses test split from before finalizing as future exogenous values
exp.plot_model(final_model, data_kwargs={'X_test': future_exog}) # Uses provided X_test values
```

Proposed
```python
exp.plot_model(final_model)  # Now fails due to missing future X values
exp.plot_model(final_model, data_kwargs={'X': future_exog}) # This works since future X values are provided
```

Also note that the name `X_test` has been changed to `X` to make it more general

**Comment by ngupta23** [comment]
Compared to https://github.com/pycaret/pycaret/issues/1588#issuecomment-1013804131, if you do not have the future exogenous variables available from external sources, then you can predict them yourself using pycaret as shown below.

```python
import numpy as np
import pandas as pd
from pycaret.datasets import get_data
from pycaret.internal.pycaret_experiment import TimeSeriesExperiment


data = get_data("uschange")

FH = 12
target = "Consumption"
exog_vars = [col for col in data.columns if target != col]

print(data.shape)


#### Setup Experiment ----
exp = TimeSeriesExperiment()
exp.setup(data=data, target=target, fh=FH, seasonal_period=4, session_id=42)

#### Baseline Model ----
model = exp.create_model("arima")
preds = exp.predict_model(model)
exp.plot_model(model)

#### Tune Model ----
tuned_model = exp.tune_model(model)
tuned_preds = exp.predict_model(tuned_model)
exp.plot_model(tuned_model)

#### Finalize Model ----
final_model = exp.finalize_model(tuned_model)

#### Future predictions (needs future exogenous variables)

# Step 1: Make models for exog variables ----

exog_exps = []
exog_models = []
for exog_var in exog_vars:
    exog_exp = TimeSeriesExperiment()
    exog_exp.setup(data=data[exog_var], fh=FH, seasonal_period=4, session_id=42)

    # Users can customize how to model future exogenous variables i.e. add
    # more steps and models to potentially get better models at the expense
    # of higher modeling time.
    best_baseline_models = exog_exp.compare_models(
        include=["arima", "ets", "exp_smooth", "theta", "lightgbm_cds_dt",], n_select=3,
    )
    best_tuned_models = [
        exog_exp.tune_model(best_baseline_model)
        for best_baseline_model in best_baseline_models
    ]
    blender = exog_exp.blend_models(best_tuned_models, choose_better=True)
    final_exog_model = exog_exp.finalize_model(blender)

    exog_exps.append(exog_exp)
    exog_models.append(final_exog_model)

# Step 2: Get future predictions for exog variables ----
future_exog = [
    exog_exp.predict_model(exog_model)
    for exog_exp, exog_model in zip(exog_exps, exog_models)
]
future_exog = pd.concat(future_exog, axis=1)

# Step 3: Make future predictions for the target ----
future_preds = exp.predict_model(final_model, X=future_exog)
exp.plot_model(final_model, data_kwargs={"X": future_exog})
```

**Comment by gesourav** [comment]
target= is an unexpected keyword in the setup() function and hence adding exogeneous variables is not an option. Can you kindly help me in understanding this? the version installed do match with the one that is required
