### ISSUE TITLE
Tune Model [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by wsn4iv** [pycaret/pycaret#159]
I am using Windows 10 and Python 3.7.1. Whenever I run tune_model() for any model, I receive a [Errno 22] Invalid argument error. I have tried running it is admin with no luck. The full error code as well as the file used are attached.

[Tune Error.txt](https://github.com/pycaret/pycaret/files/4658836/Tune.Error.txt)
[Social_Network_Ads.xlsx](https://github.com/pycaret/pycaret/files/4658840/Social_Network_Ads.xlsx)

Please help.

**Comment by pycaret** [comment]
@wsn4iv Hi. I am unable to reproduce this issue at my end. Can I ask you version of your xgboost. I am using xgboost 0.90.

**Comment by wsn4iv** [comment]
I am using xgboost 0.90.

**Comment by pycaret** [comment]
@wsn4iv Can you please update your pycaret version to `2.1.2` and xgboost to `1.1.1`

If it still doesn't work, please feel free to open another Issue.
