### ISSUE TITLE
XGBoost

### ISSUE THREAD

**Issue by salmanea** [pycaret/pycaret#1592]
**Is your feature request related to a problem? Please describe.**
Hi, thanks for the great work. I am missing XGBoost among the methods that Pycaret has. 

**Describe the solution you'd like**
Please add XGBoost classifiers and regressors to Pycaret.

**Comment by ngupta23** [comment]
It is already available ([Link](https://github.com/pycaret/pycaret/blob/e3d5c0fdf949c896aa82b23503a9316d7ef8eb7c/pycaret/containers/models/regression.py#L1437)). You may have to install the xgboost library separately since it is a soft dependency.

**Comment by mossan555** [comment]
I think that you should type "pip install pycaret[full]".

If you type "pip install pycaret", you will get a part of PyCaret.

**Comment by salmanea** [comment]
Thanks both. I'll close this.

**Comment by salmanea** [comment]
Thanks both. I'll close this.
