### ISSUE TITLE
Specificity

### ISSUE THREAD

**Issue by salmanea** [pycaret/pycaret#1593]
**Is your feature request related to a problem? Please describe.**
I think optimizing on metrics should also allow for specificity

**Describe the solution you'd like**
Please add specificity so that something like this is available:  `compare_models(sort='specificity')`. It is important as it provides a clearer picture of False Positives of the classification.

**Comment by ngupta23** [comment]
You can add your own metrics to the list (specificity) and optimize them. Check out this issue: https://github.com/pycaret/pycaret/issues/880

**Comment by salmanea** [comment]
Thanks @ngupta23. I followed the link but I couldn't understand how one could add their own metrics.

**Comment by moezali1** [comment]
@salmanea Here is example I created for you: 

```
from pycaret.datasets import get_data
data = get_data('juice')

from pycaret.classification import *
s = setup(data, target = 'Purchase', session_id = 123, silent = True)

# create a custom function
def calculate_specificity(y, y_pred):
    
    tp, tn, fn, fp = 0.0,0.0,0.0,0.0
    for l,m in enumerate(y):        
        if m==y_pred[l] and m==1:
            tp+=1
        if m==y_pred[l] and m==0:
            tn+=1
        if m!=y_pred[l] and m==1:
            fn+=1
        if m!=y_pred[l] and m==0:
            fp+=1
            
    return tn/(tn+fp)

# add metric to PyCaret
add_metric('specificity', 'specificity', calculate_specificity)

lr = create_model('lr')
```

![image](https://user-images.githubusercontent.com/54699234/134011861-99d7f216-39cd-4638-ac5a-23c684882657.png)

Hope this helps.

Ref: https://stackoverflow.com/questions/33275461/specificity-in-scikit-learn

**Comment by salmanea** [comment]
@moezali1 Thanks for the example. Appreciate it.
