### ISSUE TITLE
Unsupervised Sentiment Analysis Using Vader

### ISSUE THREAD

**Issue by mghifari1910** [pycaret/pycaret#1594]
Hello,
In the NLP Model, when we returned the dataframe with topics and the dominant_topic Is it also possible to automatically label each row with the positive, negative or neutral category?

There's notebook by Hassan Amin on Kaggle explaining unsupervised sentiment analysis using Vader
https://www.kaggle.com/hassanamin/unsupervised-sentiment-analysis-using-vader
https://pypi.org/project/vaderSentiment/
https://github.com/cjhutto/vaderSentiment

it can assess sentiment based on punctuation, capitalization, conjunctions and slang even on emoji and emoticon
is it possible to implement it on NLP modules?
it would be really nice if it can automatically label data to 'positive', 'negative' or 'neutral' category based on the highest sentiment score

**Comment by moezali1** [comment]
@mghifari1910 I wouldn't oppose the idea of adding a new model called `sentiment` under the `create_model` function of `pycaret.nlp`. Would you like to work on this @mghifari1910?

**Comment by mghifari1910** [comment]
> @mghifari1910 I wouldn't oppose the idea of adding a new model called `sentiment` under the `create_model` function of `pycaret.nlp`. Would you like to work on this @mghifari1910?

i'm sorry but i have no experience/knowledge in package development so i think i can't help on this :(
Thank you Sir Moez can't wait for it to be implemented & released on new update. Oh also, can the evaluation dashboard include bar chart comparing each sentiment distribution and top words for each sentiment?

**Comment by moezali1** [comment]
@mghifari1910  no problem. I will keep this issue open until somebody shows the interest in working on this.

**Comment by moezali1** [comment]
We are no more supporting the `nlp` and `arules` module in PyCaret due to lack to resources. Closing the issue now.
