### ISSUE TITLE
[BUG] IndexError: index 3 is out of bounds for axis 0 with size 3 exception while using predict_model() function 

### ISSUE THREAD

**Issue by GDGauravDutta** [pycaret/pycaret#1595]
IndexError: index 3 is out of bounds for axis 0 with size 3 exception while using predict_model() function 

predict_model(tuned_lightgbm)

Error :
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_43/3931662032.py in <module>
----> 1 predict_model(tuned_lightgbm)

/opt/conda/lib/python3.7/site-packages/pycaret/classification.py in predict_model(estimator, data, probability_threshold, encoded_labels, raw_score, round, verbose)
   1952         round=round,
   1953         verbose=verbose,
-> 1954         ml_usecase=MLUsecase.CLASSIFICATION,
   1955     )
   1956 

/opt/conda/lib/python3.7/site-packages/pycaret/internal/tabular.py in predict_model(estimator, data, probability_threshold, encoded_labels, raw_score, round, verbose, ml_usecase, display)
   8626         pred = pred.astype(int)
   8627         if not raw_score:
-> 8628             score = [s[pred[i]] for i, s in enumerate(score)]
   8629         try:
   8630             score = pd.DataFrame(score)

/opt/conda/lib/python3.7/site-packages/pycaret/internal/tabular.py in <listcomp>(.0)
   8626         pred = pred.astype(int)
   8627         if not raw_score:
-> 8628             score = [s[pred[i]] for i, s in enumerate(score)]
   8629         try:
   8630             score = pd.DataFrame(score)

IndexError: index 3 is out of bounds for axis 0 with size 3

**Comment by GDGauravDutta** [comment]
https://www.kaggle.com/gauravduttakiit/fetal-health-classification-tuned-at-accuracy

Added

**Comment by moezali1** [comment]
@tvdboom Can you take a look at this? I doubt this problem still exist but if it is there can we fix and close this? seems like a simple fix. Not sure if @mpaulonis is still available to help.

**Comment by tvdboom** [comment]
This is already fixed.
