### ISSUE TITLE
Training/ Test split for time series forecasting

### ISSUE THREAD

**Issue by ghcmartins** [pycaret/pycaret#160]
Hi Pycaret team! For time series forecasting is important to be sure that during train/test split data selected from train are older than test data. Can you clarify if this is assured by the Train_size in setup()? All the best!

**Comment by ghcmartins** [comment]
Extracting data from test and train I could find it doesn´t advance on future, but it still not sure if the train set is "shuffled" in any way for the k folds validation

**Comment by pycaret** [comment]
@ghcmartins As of first release train_test and Kfold is not shuffling. For next release there would be a shuffle_param and fold_shuffle_param in setup function. The change has already been made, feel free to check on dev-1.0.1 branch.

**Comment by ghcmartins** [comment]
Thank you very much!
