### ISSUE TITLE
Request for adding spark support for large dataset.

### ISSUE THREAD

**Issue by xhlubuntu** [pycaret/pycaret#162]
Request for adding spark support for large dataset.

**Comment by pycaret** [comment]
Not sure about spark. But command line support is coming up in next release which means you will be able to use it on Databricks with parallel processing but no distributed processing yet.

Tagging this as enhancement for future.

**Comment by korkile** [comment]
+1

**Comment by CosmicMiriam** [comment]
+1

**Comment by ericbugin** [comment]
spark support would be very useful

**Comment by absognety** [comment]
Is this functionality going to be there in upcoming releases?

**Comment by piEsposito** [comment]
Agree

**Comment by FeFortti** [comment]
+1

**Comment by moezali1** [comment]
This issue is now being moved to #2015
