### ISSUE TITLE
Add text_features parameter in the setup

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1638]
Add the new parameter `text_features` in the `setup` function.

Just like we have `ignore_features` or `date_features`. We should also have `text_features` that gets a column name as a string and run some kind of embeddings. Maybe we can add another parameter `text_features_method` to define things like `CountVectorizer` or `TfidfVectorizer`. We will also have to think a way to be able to pass arbitrary parameters as dictionary to those vectorizers because there are some important params like `min_df` and `max_df` that user may want to control.

**Comment by tvdboom** [comment]
Good idea. Added in the newest commit (see #1492). For now, there isn't an option for the user to decide it's own parameters, he can only choose an estimator: "bow" for bag of words - CountVectorizer or "tf-idf" for TfidfVectorizer. We can think on how the implementation of custom parameters would look like. It would probably require some kind of kwargs parameter in setup, which isn't consistent with the rest of the API. Another option would be to let the user add its own estimator, but that has its own problems...
