### ISSUE TITLE
Multi threaded compare_models()

### ISSUE THREAD

**Issue by TalhaAsmal** [pycaret/pycaret#164]
The prevalence of multi-core and multi-thread systems, it would make sense to allow multiple models to be trained simultaneously, or alternatively training multiple folds at a time. This will substantially reduce processing time, and increase the usefullness of this package.

As an example, an 8C/16T CPU is only utilized ~14% during the compare_models() run.

**Comment by pycaret** [comment]
@TalhaAsmal Did you meant using n_jobs parameter in sklearn?

**Comment by DJ-LYH** [comment]
> @TalhaAsmal Did you meant using n_jobs parameter in sklearn?
Yes, I think that would be helpful to speed up

**Comment by pycaret** [comment]
Added **n_jobs** parameter in **setup**.

Please install **pycaret-nightly** or **pycaret==2.0**
