### ISSUE TITLE
error message " Target parameter: ET0 mm/day does not exist in the data provided."

### ISSUE THREAD

**Issue by Mohammedsaied89** [pycaret/pycaret#1641]
![image](https://user-images.githubusercontent.com/54103097/135633101-cc95019c-80ab-4deb-a9c4-c6f28125648d.png)
[mydata - Copy.xlsx](https://github.com/pycaret/pycaret/files/7267757/mydata.-.Copy.xlsx)

**Comment by moezali1** [comment]
@Mohammedsaied89 As the error message suggests, target col doesn't exist in the dataset. You don't have to split X and y for PyCaret. Your setup should be as follows:

```
setup(data = data, target = 'name_of_col')
```

Hope this helps.
