### ISSUE TITLE
blend_models method parameter not taking effect in pycaret.time_series

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1644]
blend_models method parameter not taking effect in pycaret.time_series

```
from pycaret.datasets import get_data
data = get_data('airline')

from pycaret.time_series import *
s = setup(data, fold = 5, fh = 12, session_id = 123)

best_models = compare_models(n_select = 3)

# blending with different methods
blender_mean = blend_models(best_models, method = 'mean')
blender_median = blend_models(best_models, method = 'median')
blender_voting = blend_models(best_models, method = 'voting')
```
![image](https://user-images.githubusercontent.com/54699234/135716450-0d68a519-b51e-4359-b1b0-d11e83ff190e.png)

Regardless of the voting method, the results of all these commands are exactly the same. See below:

![image](https://user-images.githubusercontent.com/54699234/135716427-61b48bdc-5565-4f79-8f89-d794feeb6df4.png)

![image](https://user-images.githubusercontent.com/54699234/135716431-e62b9281-1714-4b1c-b045-544f1561e870.png)

![image](https://user-images.githubusercontent.com/54699234/135716436-d50371d8-ddfa-460c-96b7-45a798f48779.png)

**Comment by ngupta23** [comment]
@moezali1 , Mean and Voting will give the same answer when no weights are provided to the voting blender (defaults to equal weights).

For median, it is a little surprisong that you are getting the same error, but it looks like you have both ARIMA and Auto ARIMA in the model list so if both of them settle on the same parameters, they will dominate the median calculation out of the 3 models.

I verified in the 101 notebook [[Link](https://github.com/pycaret/pycaret/blob/time_series/time_series_101.ipynb)] that we get different answers for the 3 blenders. Can you try with 4 models and check again. The median should give you different results. 

Also, for voting, try giving different weights to the blender (see 101 notebook).

**Comment by ngupta23** [comment]
`method` was not being passed from the functional API to the internal OOP call. This has been fixed now.
