### ISSUE TITLE
Time Series plot_model support for difference plots

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#1654]
Add option to plot difference plots. Use `sktime` `Differencer` for this. More [details here](https://www.sktime.org/en/v0.9.0/api_reference/auto_generated/sktime.transformations.series.difference.Differencer.html)

## Option 1: User can specify `order` of difference

```python
plot_model(plot="diff") # Defaults to order = 1 (first difference)

# User can specify a specific order of difference with data_kwargs.
# e.g. this does 1st difference, then 1st difference on differenced data (2nd order difference).
# Finally shows original and 2nd order differenced data.
plot_model(plot="diff", data_kwargs={'order':2})  
# If using sktime differencer, this is equivalent to lags=[1, 1]

# Same as above but finally shows original, 1st order, and 2nd order differenced data.
plot_model(plot="diff", data_kwargs={'order':[1,2]})  
```

## Option 2: User can specify `lags` directly
```python
# Instead of specifying the order, user can specify lags directly as well. These should be passed to the underlying sktime Differencer
# The below if equivalent to `plot_model(plot="diff", data_kwargs={'order':2})`
plot_model(plot="diff", data_kwargs={'lags':[1,1]})


# Does first difference then 12th difference
# From `sktime` doc: "given a timeseries with monthly periodicity, using lags=[1, 12] corresponds to applying a standard first difference to handle trend, and followed by a seasonal difference (at lag 12) to attempt to account for seasonal dependence."
plot_model(plot="diff", data_kwargs={'lags': [1,12]}) 

# User may specify multiple sets of lags as well
# This should show 3 plots - Original, then one with lags = [1, 12], then one with lags = [1, 1, 12]
plot_model(plot="diff", data_kwargs={'lags': [[1,12], [1, 1, 12]}) 
```

## Option 3: Use Option 1 or 2 and plot additional plots such as ACF, PACF

Trellis with ACF and PACF below the time series in individual rows. This would return a plot of 3x3
* Row 1: Original Dataset, 1st order difference, 2nd order difference
* Row 2: ACF for Original Dataset, 1st order difference, 2nd order difference
* Row 3: PACF for Original Dataset, 1st order difference, 2nd order difference

```python
plot_model(plot="diff", data_kwargs={'order':[1,2], 'acf': True, 'pacf" True})  
```

**Comment by ngupta23** [comment]
Consider using `sktime` difference transformer for this to make it consistent with underlying sktime package.

https://www.sktime.org/en/v0.9.0/api_reference/auto_generated/sktime.transformations.series.difference.Differencer.html

**Comment by ngupta23** [comment]
@codecypher Are you going to work on this one?

**Comment by ngupta23** [comment]
So we should always plot the original and then the differences. 

If only first difference is asked for, it can be a 1x2 plot. If first 2 are asked for, then it can be a 1x3 plot.

Anything more than that.wouod need to wrap into multiple rows.

**Comment by codecypher** [comment]
No, it would kinda help to have an example of what we want to do.

**Comment by ngupta23** [comment]
@codecypher I updated the original post itself to avoid confusion. Let me know if this makes more sense.

https://github.com/pycaret/pycaret/issues/1654#issue-1018369554

**Comment by ngupta23** [comment]
@codecypher As you build this, think about adding modular functions to get the data required for the plot (i.e. the differences). I would like to reuse those functions for the `check_stats` functionality. For example, I will use your function to get the differenced data and then run statistical tests on them (#1655)

**Comment by ngupta23** [comment]
@codecypher I got some time to work on this. Since you are working on the frequency components, I will go ahead and add some code for this. We can sync up once that is done.

This is sample code for base functions that need to be incorporated: https://gist.github.com/ngupta23/c93116dede5436c05faffd992181b89d

**Comment by ngupta23** [comment]
To test

```python
import pandas as pd
from pycaret.datasets import get_data

y = get_data("airline")

#### Setup the experiment ----
from pycaret.internal.pycaret_experiment import TimeSeriesExperiment
exp = TimeSeriesExperiment()
exp.setup(data=y, fh=12, session_id=42)

# Works on original dataset
exp.plot_model(plot="diff") # Default Diff Order = 1
exp.plot_model(plot="diff", data_kwargs={"order_list":[1, 2]})
exp.plot_model(plot="diff", data_kwargs={"lags_list":[1, 12, [1, 12]]})
exp.plot_model(plot="diff", data_kwargs={"order_list":[1, 2], "lags_list":[1, 12, [1, 12]]})

# Works on model residuals
model = exp.create_model("theta")
exp.plot_model(model, plot="diff") # Default Diff Order = 1
```
