### ISSUE TITLE
Time Series Plot Model (Frequency Components)

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#1656]
Add plot models for Spectral Density and FFT

```python
plot_model(plot='spectrogram')
plot_model(plot='welch')
plot_model(plot='fft')
```

All three can be achieved through scipy functions. We just need to plot them using plotly.

**Comment by ngupta23** [comment]
@sedy2014 - you can have a look at this issue.

**Comment by sedy2014** [comment]
> @sedy2014 - you can have a look at this issue.

Will do. Thanks.

**Comment by ngupta23** [comment]
@codecypher Are you going to work on this one? Let me know so that it can be assigned appropriately.

**Comment by codecypher** [comment]
Does this refer to scipy.signal.spectrogram, scipy.signal.welch, and spicy.fft?

**Comment by ngupta23** [comment]
Yes, correct. We basically want to plot the frequency profile that will make it easier to identify the `seasonal_period`.

**Comment by codecypher** [comment]
Do we have sample data? I understand the SciPy example but not sure if it applies to time_series_101.ipynb

**Comment by ngupta23** [comment]
> I understand the SciPy example but not sure if it applies to time_series_101.ipynb

You can apply it to the airline dataset. Why do you think it is not applicable?

**Comment by codecypher** [comment]
Well, Spectrograms are used as a way of visualizing the change of a nonstationary signal’s frequency content over time which is quite different from the sample data.

**Comment by ngupta23** [comment]
Ah, I see your confusion now. This is what I really meant. https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.periodogram.html. Lets change it to this then

```python
plot_model(plot='periodogram') # Change from "spectrogram"
plot_model(plot='welch')
plot_model(plot='fft')
```

**Comment by codecypher** [comment]
Oh good. I was confused. All I got was a blank plot. 

Jeff Holmes

On Jan 5, 2022, at 1:43 PM, Nikhil Gupta ***@***.***> wrote:
Ah, I see your confusion now. This is what I really meant. https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.periodogram.html. Lets change it to this then

plot_model(plot='periodogram') # Change from "spectrogram"
plot_model(plot='welch')
plot_model(plot='fft')

**Comment by codecypher** [comment]
I would need to see a code example of how we want to do the plots. I am working on fft right now and I still don't know what we want to plot using the airline dataset.

**Comment by codecypher** [comment]
I found some examples using fft with time series data. However, the code examples for SciPy are less than helpful.

**Comment by ngupta23** [comment]
The images that you attached did not come through. Can you attach them again and share your sample code somehow?

**Comment by ngupta23** [comment]
I wrote template code snippets for all 3 options. Have a look and let me know if that makes sense.

https://gist.github.com/ngupta23/f09baa54465b2247a87455d6008523e3

**Comment by codecypher** [comment]
Hmm. This will work for now but if I am going to work on other tickets we would have to come up with a better approach.. It would be helpful if you could provide references with code examples or refer to lines of existing source code and describe what you would like done. A sample of the output you would like to see would be good to. Sorry, the ticket just doesn't provide enough information for me to implement anything.

**Comment by ngupta23** [comment]
Do you have all the information you need now from my code gist?

**Comment by codecypher** [comment]
No it would prefer some references. I think there are some mistakes in the code smaples you provid

**Comment by ngupta23** [comment]
I am not sure what additional information you are looking for. What are the mistakes?

**Comment by ngupta23** [comment]
@codecypher I believe all the information should be there in the code that I sent to you (https://github.com/pycaret/pycaret/issues/1656#issuecomment-1012391671). All that is needed is to convert the data to plotly plots and add to pycaret. Let me know if you want me to pick it up. We would like to have this released at the end of Feb release as it is an important feature for EDA. Thanks!

**Comment by codecypher** [comment]
Actually no. 

I like the potential of PyCaret but there would have to be some changes in your software development (SD) approach before I would be willing to donate my time and expertise. 

I can tell from the comments in the PRs that you have a lot of developers who volunteer to contribute but later give up. 

Here are some problems that I have encountered so far:

- Code one-liners and one or two sentences are not appropriate for specifying new software requirements, especially in a PR. 

- The current SD approach is very inefficient because the developer has to play 20-questions to elicit the requirements needed to complete the PR request. 

  This is not an agile approach and it is not approproate for an open-source or remote project. 
  
  The author of a PR should fully define the requirements and cite references with code samples as well as give samples of any graphs/tables or other output that is to be generated.

- Other open source projects such as scikit-learn and Keras seem to be well documented and also have documentation for new developers who would like to contribute.

- A professional software engineer should always be able to cite textbook references as well as articles gor all algorithms and graphs.

- I am confident that commercial software analysis tool and memory profiler will identify numerous code issues/defects in the PyCaret source code. I came across numerous examples of code smells and antipatterns in the small section of code that I viewed in the timel_series module. 

If you change your SD approach, please feel free to contact me.

**Comment by ngupta23** [comment]
@codecypher We are aware of these challenges but these things take time to fix especially with a codebase this large that is being supported by a small group of dedicated volunteers who are doing this in their free time (and not getting paid to do this). Comparing it to scikit-learn and Keras is not a fair comparison because they have been around for a much longer time and are backed financially by larger firms. Our hope is that one-day pycaret will also get there. The number of volunteers at pycaret has been increasing but that being said, we will be going through a code refactoring process later this year to make it easier for newcomers to get started quickly. I can understand that you are not ready to contribute at this time so for now, I will pick up this issue.

**Comment by ngupta23** [comment]
Only supporting Periodogram and FFT for now. We can revisit welch later since these two should probably be enough to get the information we want.

For Testing

```python
from pycaret.datasets import get_data
from pycaret.internal.pycaret_experiment import TimeSeriesExperiment

data = get_data("airline")
exp = TimeSeriesExperiment()
exp.setup(data=data, session_id=42, fh=12)
```


```python
exp.plot_model(plot="periodogram")
exp.plot_model(plot="fft")
```

![image](https://user-images.githubusercontent.com/33585645/152643735-c1cacd3d-776e-4c92-a17b-4d9363d33520.png)

![image](https://user-images.githubusercontent.com/33585645/152643748-92c78497-1758-4248-a57b-7435b18fa42c.png)

```python
exp.plot_model(plot="diff", data_kwargs={'periodogram': True})
exp.plot_model(plot="diff", data_kwargs={'fft': True})
exp.plot_model(plot="diff", data_kwargs={'acf': True, 'periodogram': True, "fft": True})
```

![image](https://user-images.githubusercontent.com/33585645/152643755-73c03af6-c88c-4433-893a-1f8da3ff132b.png)

![image](https://user-images.githubusercontent.com/33585645/152643768-8b9792bb-fc65-47ff-9ca3-fedaa09fcde3.png)

![image](https://user-images.githubusercontent.com/33585645/152643784-6dc1a90a-a666-4dee-a853-8c7088e4c5e2.png)

**Comment by codecypher** [comment]
I think the most pressing issue right now is that u seem to have a habit of giving one-liner function prototypes and/or one sentence blurbs and think that a seasoned developer can somehow use that to complete the PR. A seasoned developer donating their time is not going to want to play 20 questions to get u to do your job.
