### ISSUE TITLE
Error running python script in powerBI

### ISSUE THREAD

**Issue by rijesh123** [pycaret/pycaret#168]
from pycaret.clustering import *
dataset = get_clusters(data = dataset)

DataSource.Error: ADO.NET: Python script error.
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 13, in <module>
    from pycaret.clustering import *
ModuleNotFoundError: No module named 'pycaret'

Details:
    DataSourceKind=Python
    DataSourcePath=Python
    Message=Python script error.
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 13, in <module>
    from pycaret.clustering import *
ModuleNotFoundError: No module named 'pycaret'

    ErrorCode=-2147467259
    ExceptionType=Microsoft.PowerBI.Scripting.Python.Exceptions.PythonScriptRuntimeException

Python 3.8(64)

**Comment by vandermoerDOTcom** [comment]
Do you have pycaret installed (check by running import pycaret in the python shell (if you don’t get an error it is installed) and set the path in powerbi? 
I have pycaret running on python 3.6.6 in windows. I install modules in python with powershell. If you have more python versions running than you have to specify on what version you want to install modules. For installing with powershell I use: py -3.6 -m pip install pycaret.

Let me know if this solves your question.

Have a nice day 😊

**Comment by rijesh123** [comment]
@vandermoerDOTcom  Many thanks for your reply.

It looks like pycaret is installed on my system but still it says "Module not found error"

Please check the attached file and advice.
[Load errors.docx](https://github.com/pycaret/pycaret/files/4672296/Load.errors.docx)

**Comment by vandermoerDOTcom** [comment]
@rijesh123

Run PowerShell as admin and type: py -3.8 -m pip install pycaret . After this check if it is installed in Python IDE. Powerbi shut recognize the default os program for python and you shut be able to select the right python version if you have more than one. I tested it on version 3.8.1. (I don’t use anaconda).

Have a nice day 😊

**Comment by rijesh123** [comment]
Thanks @vandermoerDOTcom .

![image](https://user-images.githubusercontent.com/65109986/82751424-14ade600-9daf-11ea-9fa2-34101652c2f2.png)

Recently I uninstalled python 3.8 and tried 3.7.7

I followed your instructions and got attached message

**Comment by vandermoerDOTcom** [comment]
@rijesh123

You don’t need to type python first in powershell. Run PowerShell as admin and type: py -3.7 -m pip install pycaret .

**Comment by rijesh123** [comment]
@vandermoerDOTcom Many thanks for your help on this.

All sorted now. I completely uninstalled Python,Anaconda and installed again :)

**Comment by pycaret** [comment]
@vandermoerDOTcom  @rijesh123 Thank you for sorting this out. If the issue is resolved can you please close the issue?

**Comment by rijesh123** [comment]
Thanks @vandermoerDOTcom
