### ISSUE TITLE
How to start without supervision

### ISSUE THREAD

**Issue by xxyy001** [pycaret/pycaret#169]
for pycaret.classification，
exp1 = setup(data, target = 'xxx')

**Comment by pycaret** [comment]
@xxyy001 pass silent=True and verbose=False. 

Let me know how it goes.

**Comment by xxyy001** [comment]
It works, thank you, but there is no keyword “ verbose”

**Comment by xxyy001** [comment]
Please Enter the sample % of data you would like to use for modeling. Example: Enter 0.3 for 30%.
Press Enter if you would like to use 100% of the data.
 
Sample Size: 

it still needs to choose.

**Comment by pycaret** [comment]
Can you also please pass sampling=False

**Comment by xxyy001** [comment]
> Can you also please pass sampling=False

thanks

**Comment by xxyy001** [comment]
it works. Thanks

**Comment by abhisht51** [comment]
Has this issue been resolved ?
