### ISSUE TITLE
[BUG] return_data parameter in the plot_model for time series is not working

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1698]
`return_data` parameter in the plot_model function in pycaret.time_series module is not working as expected

**Comment by ngupta23** [comment]
Requirement: This should return the raw data used to create the plots (not the data for from plotly)

**Comment by ngupta23** [comment]
@sayantan1410 This is another issue that you can look at if you are interested. Let me know and I will assign it to you. Thanks!

**Comment by sayantan1410** [comment]
Give me a little bit time, once I am done with the previous ones,  I will drop a comment here and then you can assign this to me !!

**Comment by ngupta23** [comment]
Sounds good. Take your time.

**Comment by codecypher** [comment]
What is the status? I would like to try workin on this ticket if it is still open.

**Comment by ngupta23** [comment]
@codecypher - @sayantan1410  is already working on it. But we would love for you to contribute to any other open (unassigned) issue. 

Please have a look at this roadmap for open tickets: https://github.com/pycaret/pycaret/issues/1648. If you want a curated list, may I recommend one of the plotting features such as https://github.com/pycaret/pycaret/issues/1656 or https://github.com/pycaret/pycaret/issues/1654.

Let me know. I would be happy to have a quick call to get you up to speed of needed. 

Also, it might be good if you can join the slack channel for discussions: https://join.slack.com/t/pycaret/shared_invite/zt-row9phbm-BoJdEVPYnGf7_NxNBP307w

**Comment by codecypher** [comment]
Will do. I would recommend assigning it to him since it is not showing as assigned to anyone.
