### ISSUE TITLE
Couldnt find any tests

### ISSUE THREAD

**Issue by fcakyon** [pycaret/pycaret#17]
Hello,

First of all, thanks a lot for this comprehensive library.

I wanted to add cross platform continious integration workflow pr but couldnt locate the tests for the implemented functions. Where can i find them?

If there arent any, you should definitely consider adding unit/integration tests, otherwise it would be extremely hard to identify/localize bugs and errors.

Bests

**Comment by pycaret** [comment]
Hi,

Would you like to contribute in building unit tests? please reach out moez@pycaret.org.

Thanks

**Comment by rmill040** [comment]
Look, this library is anything but "production ready" for serious machine learning applications. You are off to a good start but go check out any of the libraries this package depends on and see how far away the current codebase is from the level of testing, code quality, and overall effort it takes to build a production ready machine learning library. I really hope nobody is using or will be using this package for critical machine learning applications.

**Comment by pycaret** [comment]
Thanks for your comment @rmill040. 

Is there anything specific you can help us with?
