### ISSUE TITLE
Add insample forecast when plot='forecast' in pycaret.time_series

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1700]
Add insample forecast when plot='forecast' in pycaret.time_series

Add a new parameter called the `in_sample` and set it to `True` by default. After adding this functionality, the plot model (plot = 'forecast') will show a line plot with two lines. One for actual and one for the forecast.

**Comment by ngupta23** [comment]
For now (until we add this internally), users can get this using the following

```python
y_train = get_config("y_train")
plot_model(estimator=model, data_kwargs={'fh': -np.arange(0, len(y_train))})
```

**Comment by ngupta23** [comment]
As discussed on 11/6/2021, this will be implemented as a separate plot since the combined plot for out-of-sample and in-sample forecasts was very busy
