### ISSUE TITLE
reset the fh after plot_model(plot='forecast')

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1701]
reset the fh after plot_model(plot='forecast')

`fh` parameter is defined in the setup. When I run the following

```
plot_model(model, plot = 'forecast', data_kwargs = {'fh' : 24}) 
```
`fh` parameter is globally set to 24. That shouldn't be the case. We should reset it to whatever it was defined at the time of the `setup` run.

**Comment by ngupta23** [comment]
Yes, this is also true for `predict_model`. I will look into it
