### ISSUE TITLE
Add `save` argument to `plot_model` and `interpret_model` in time series

### ISSUE THREAD

**Issue by Yard1** [pycaret/pycaret#1708]
`plot_model` and `interpret_model` should have a `save` argument for consistency with other modules, if possible. It should take both bools and string paths.

This is also required for `log_plots` functionality (automatically creating, saving and uploading plots to mlflow when a model is created).

**Comment by ngupta23** [comment]
Implemented in https://github.com/pycaret/pycaret/commit/658ba6ff3fc8879237c281954bea03951e225e0c
