### ISSUE TITLE
Error No module named 'plotly.graph_objs._area'

### ISSUE THREAD

**Issue by BismeetSingh** [pycaret/pycaret#172]
While trying to use pycaret on following dataset in Kaggle: https://www.kaggle.com/aljarah/xAPI-Edu-Data,Pycaret throws an error. This is the setup code:
`exp_clf = setup(df, target = 'Class')`

Logs:
 ---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-402-5e61dbe27c41> in <module>
----> 1 exp_clf = setup(df, target = 'Class')

/opt/conda/lib/python3.7/site-packages/pycaret/classification.py in setup(data, target, train_size, sampling, sample_estimator, categorical_features, categorical_imputation, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_interaction, feature_ratio, interaction_threshold, session_id, silent, profile)
    684 
    685     #cufflinks
--> 686     import cufflinks as cf
    687     cf.go_offline()
    688     cf.set_config_file(offline=False, world_readable=True)

/opt/conda/lib/python3.7/site-packages/cufflinks/__init__.py in <module>
     13 from . import datagen
     14 from . import helper
---> 15 from . import tools
     16 from . import colors
     17 from . import pandastools

/opt/conda/lib/python3.7/site-packages/cufflinks/tools.py in <module>
      4 import pandas as pd
      5 import plotly.offline as py_offline
----> 6 import plotly.figure_factory as ff
      7 from plotly.graph_objs import Figure, Scatter, Line
      8 from plotly.subplots import make_subplots

/opt/conda/lib/python3.7/site-packages/plotly/figure_factory/__init__.py in <module>
     12 
     13 
---> 14 from plotly.figure_factory._2d_density import create_2d_density
     15 from plotly.figure_factory._annotated_heatmap import create_annotated_heatmap
     16 from plotly.figure_factory._bullet import create_bullet

/opt/conda/lib/python3.7/site-packages/plotly/figure_factory/_2d_density.py in <module>
      6 
      7 import plotly.colors as clrs
----> 8 from plotly.graph_objs import graph_objs
      9 
     10 

/opt/conda/lib/python3.7/site-packages/plotly/graph_objs/graph_objs.py in <module>
----> 1 from plotly.graph_objs import *

/opt/conda/lib/python3.7/site-packages/plotly/graph_objs/__init__.py in __getattr__(import_name)
    292 
    293             Supported dict properties:
--> 294 
    295                 align
    296                     Sets the horizontal alignment of the text

/opt/conda/lib/python3.7/site-packages/_plotly_utils/importers.py in __getattr__(import_name)

/opt/conda/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

ModuleNotFoundError: No module named 'plotly.graph_objs._area'

**Comment by pycaret** [comment]
@BismeetSingh Can you try the same dataset on your local Jupyter please? Does the problem still persist.

**Comment by BismeetSingh** [comment]
It works on my machine. Maybe its  some dependency issue on Kaggle notebooks.
