### ISSUE TITLE
Request to add "timing" column to compare_models()

### ISSUE THREAD

**Issue by bigtoga** [pycaret/pycaret#173]
Just would be useful to have another column "Execution Time (ms)" to compare_models(). As I often go through a first EDA/exploration w compare_models "to figure out what I want to blacklist for my next run", sometimes I am "on the fence" (unclear) on whether the metrics alone help make the decision and "How long did this one take?" might help make it easier to decide whether a model should be included/excluded.

Example - if I'm going a classification model and I have two models right at my cutoff (let's say my imaginary cutoff is "Nothing w Accuracy below 70 and Recall below 75"), and I have two models that are both at 70/75, I'd love to know "One model took 45 minutes but another took 4 minutes to come to the same metrics". I would exclude that 45 minute model and not lose anything. 

Thanks!

**Comment by bigtoga** [comment]
Maybe also add "Avg execution time per fold"? Would be useful.

**Comment by pycaret** [comment]
@bigtoga Thanks for reporting. We have added training time in compare_models() function in dev-1.0.1 branch. Thanks for suggestion.
