### ISSUE TITLE
OSError: dlopen(/Users/cint41/opt/anaconda3/lib/python3.7/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib Referenced from: /Users/cint41/opt/anaconda3/lib/python3.7/site-packages/lightgbm/lib_lightgbm.so Reason: image not found

### ISSUE THREAD

**Issue by Jpirog** [pycaret/pycaret#174]
I continually get this error, running this in Anaconda on a Mac.

from pycaret import classification
classification_setup = classification.setup(data= data_classification, target='Personal Loan')

OSError                                   Traceback (most recent call last)
<ipython-input-8-f89d9155af62> in <module>
----> 1 classification_setup = classification.setup(data= data_classification, target='Personal Loan')

~/opt/anaconda3/lib/python3.7/site-packages/pycaret/classification.py in setup(data, target, train_size, sampling, sample_estimator, categorical_features, categorical_imputation, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_interaction, feature_ratio, interaction_threshold, session_id, silent, profile)
    878 
    879     #import library
--> 880     from pycaret import preprocess
    881 
    882     data = preprocess.Preprocess_Path_One(train_data = data, 

~/opt/anaconda3/lib/python3.7/site-packages/pycaret/preprocess.py in <module>
     31 from sklearn.ensemble import RandomForestClassifier as rfc
     32 from sklearn.ensemble import RandomForestRegressor as rfr
---> 33 from lightgbm import LGBMClassifier as lgbmc
     34 from lightgbm import LGBMRegressor as lgbmr
     35 import sys

~/opt/anaconda3/lib/python3.7/site-packages/lightgbm/__init__.py in <module>
      6 from __future__ import absolute_import
      7 
----> 8 from .basic import Booster, Dataset
      9 from .callback import (early_stopping, print_evaluation, record_evaluation,
     10                        reset_parameter)

~/opt/anaconda3/lib/python3.7/site-packages/lightgbm/basic.py in <module>
     31 
     32 
---> 33 _LIB = _load_lib()
     34 
     35 

~/opt/anaconda3/lib/python3.7/site-packages/lightgbm/basic.py in _load_lib()
     26     if len(lib_path) == 0:
     27         return None
---> 28     lib = ctypes.cdll.LoadLibrary(lib_path[0])
     29     lib.LGBM_GetLastError.restype = ctypes.c_char_p
     30     return lib

~/opt/anaconda3/lib/python3.7/ctypes/__init__.py in LoadLibrary(self, name)
    440 
    441     def LoadLibrary(self, name):
--> 442         return self._dlltype(name)
    443 
    444 cdll = LibraryLoader(CDLL)

~/opt/anaconda3/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: dlopen(/Users/cint41/opt/anaconda3/lib/python3.7/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/cint41/opt/anaconda3/lib/python3.7/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found

**Comment by pycaret** [comment]
@Jpirog Hi. We have seen issues in installing LightGBM on MAC. We have some installation guide on our page https://www.pycaret.org/install. Please let me know if that solves the problem. If you find the installation guide for MAC not so accurate, please feel free to propose changes.

**Comment by Jpirog** [comment]
Thank you for this. I was installing Pycaret from a different article that didn't mention the special Mac instructions. I followed the links you mentioned and it worked like a charm.
