### ISSUE TITLE
bug in plot_model of time_series (pycaret-ts-alpha)

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1740]
bug in plot_model of time_series (pycaret-ts-alpha). To reproduce:

```
!pip install pycaret-ts-alpha

from pycaret.datasets import get_data
data = get_data('500', folder = 'time_series/seasonal')

from pycaret.time_series import *
setup(data, fh = 7, fold = 5, session_id = 123, seasonal_period='D')

plot_model(plot = 'decomp_classical')
plot_model(plot = 'decomp_stl')
```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-103-4d56c7d73b8f> in <module>()
----> 1 plot_model(best, plot = 'decomp_stl')

3 frames
/usr/local/lib/python3.7/dist-packages/pycaret/internal/pycaret_experiment/time_series_experiment.py in check_and_clean_resid(self, resid)
   3501         else:
   3502             raise ValueError(
-> 3503                 "Residuals time points do not match either test set or full dataset."
   3504             )
   3505         resid.dropna(inplace=True)

ValueError: Residuals time points do not match either test set or full dataset.

Same error for both the plots.

I have also seen the same error with plot_model(plot = 'residuals'). You can reproduce the error with the `pycaret_downloads` dataset.

**Comment by ngupta23** [comment]
I do not get this. This is what you should be seeing

![image](https://user-images.githubusercontent.com/33585645/138369873-26ec399d-2e25-47c8-8daf-266524d17bad.png)

**Comment by ngupta23** [comment]
@moezali1 Looks like your error is related to an model called "best". Can you add the reproducible code for this. I am not able to replicate it.
