### ISSUE TITLE
Feature important and shap interpret_model should be base on average of CV multi folds

### ISSUE THREAD

**Issue by reza1615** [pycaret/pycaret#1749]
I run pycaret two times without session_id and I got two different interpret_model and feature important plots. In my opinion, pycaret should generate these plots based on the average of CV multi folds not the best/last fold ratios.
![image](https://user-images.githubusercontent.com/2202483/138503927-a4d76b8f-29aa-438e-a6a4-20e73c0cc465.png)

**Comment by moezali1** [comment]
With the current design, all the interpretations and analyses are based on the test set.
