### ISSUE TITLE
PyCaret - XGBoost, error installing library

### ISSUE THREAD

**Issue by galdezanni** [pycaret/pycaret#1755]
Hey guys,

I'm trying to use PyCaret on GoogleColab to run XGBoost Classifier, but it's getting an error.
I installed the complete package:

`!pip install pycaret[full]`

but when I import the rating library it gives me an error:

`from pycaret.classification import *`

TypeError: load() missing 1 required positional argument: 'Loader'

When I install the standard version, the import doesn't give an error, but it doesn't have XGBoost
`!pip install pycaret`

![image](https://user-images.githubusercontent.com/29483565/138561820-1761a4da-1a3b-4ddd-9e6e-01a2969289bf.png)

**Comment by moezali1** [comment]
This is fixed now. 

`pip install pycaret[full]` is now working on colab.

**Comment by galdezanni** [comment]
@moezali1 ,

great!!! thank you!!!
