### ISSUE TITLE
[DOC] Create a pycaret time series cheat sheet 

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#1762]
Include

- [ ] functions from functional API,
- [ ] overview of object oriented approach
- [ ] Common arguments that are used with each function/method

**Comment by ngupta23** [comment]
Pablo is creating this already: https://www.linkedin.com/posts/pablo-moreno-363188150_pycaret-cheat-sheet-all-functions-and-setup-activity-6884489626548097024-9jkx

**Comment by PabloJMoreno** [comment]
Cheat sheet created. There are 2 versions, so you can pick the one you like the most
[PyCaret cheat_sheet_all_functions.pdf](https://github.com/pycaret/pycaret/files/7817563/PyCaret.cheat_sheet_all_functions.pdf)
[PyCaret cheat_sheet_tutorial.pdf](https://github.com/pycaret/pycaret/files/7817566/PyCaret.cheat_sheet_tutorial.pdf)

Thanks @ngupta23 for the outstanding job done with the TS module of PyCaret!

**Comment by ngupta23** [comment]
Thanks @PabloJMoreno for picking this up. I have assigned it to you.

**Comment by ngupta23** [comment]
Available here: https://pycaret.gitbook.io/docs/learn-pycaret/cheat-sheet
