### ISSUE TITLE
render tsne plot in Colab

### ISSUE THREAD

**Issue by dvu4** [pycaret/pycaret#1768]
https://github.com/pycaret/pycaret/blob/1f113c01c0a4554dbd5022f1e8825b4caee2a950/pycaret/nlp.py#L2737

Hi,
I tried to plot t-sne in Colab but it did not work even though plotly version is 4.4.1. I think adding option renderer='colab' will work . Is there any way I can add this option ?

  `fig.show(renderer="colab")`

**Comment by moezali1** [comment]
@Yard1 Is this the new thing? I don't think in past we were doing this?

**Comment by Yard1** [comment]
@dvu4 You can set a global plotly renderer. Check plotly documentation on how to do so.
