### ISSUE TITLE
GaussianNB() vs ModifiedNB() - Laplace smoothing

### ISSUE THREAD

**Issue by ghcmartins** [pycaret/pycaret#178]
Hi Pycaret team! 

In order to solve an issue with NayveBayes models, when the probability of something is zero, there is a "correction" called Laplace Smoothing. If you can implement that or the solution proposed by https://github.com/chembl/ModifiedNB wouyld be very nice!

Best Reagrds

**Comment by pycaret** [comment]
@ghcmartins Thanks for suggestion. I will mark this as an enhancement for future inclusion.

**Comment by pycaret** [comment]
@ghcmartins With PyCaret 2.0 you can use custom models in **create_model** function. I tried install ModifiedNB and try fitting it on 'juice' dataset. This is the error I get. 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-41725f07525b> in <module>
      3 from ModifiedNB import ModifiedNB
      4 mnb = ModifiedNB()
----> 5 mnb.fit(Xtrain,ytrain)

~\Anaconda3\lib\site-packages\sklearn\naive_bayes.py in fit(self, X, y, sample_weight)
    639 
    640         self._init_counters(n_effective_classes, n_features)
--> 641         self._count(X, Y)
    642         alpha = self._check_alpha()
    643         self._update_feature_log_prob(alpha)

~\Anaconda3\lib\site-packages\ModifiedNB\ModifiedNB.py in _count(self, X, Y)
     28         """Count and smooth feature occurrences."""
     29         if np.any((X.data if issparse(X) else X) < 0):
---> 30             raise ValueError("Input X must be non-negative")
     31         self.feature_count_ += safe_sparse_dot(Y.T, X)
     32         self.class_count_ += Y.sum(axis=0)

ValueError: Input X must be non-negative

If you want, please log an issue here : https://github.com/chembl/ModifiedNB

**Comment by pycaret** [comment]
# Not related to PyCaret
