### ISSUE TITLE
Log plots in pycaret.time_series module

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1782]
When `log_plots=True` in the `setup` function. Please log the following plots in MLflow:

- forecast
- residuals
- diagnostics

Additionally, all the plots that doesn't require estimator can also be lagged at a setup stage such as ACF, PACF, ts, etc.

**Comment by ngupta23** [comment]
> Additionally, all the plots that doesn't require estimator can also be lagged at a setup stage such as ACF, PACF, ts, etc.

This is a good feature to have. We will take this up later (after model MLFlow logging is implemented).
