### ISSUE TITLE
[INSTALL] Error when installing PyCaret

### ISSUE THREAD

**Issue by Guuuud** [pycaret/pycaret#1786]
I got a problem when installing PyCaret in my virtual environment
Python 3.8.10.   macOs Catalina 10.15.7
Command: pip install PyCaret
Can anyone help with this? Appreciated.

Error message log:

> ERROR: Command errored out with exit status 1:
   command: /Users/lee/.conda/envs/TensorFlow/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/1y/492pgpsd7vv980kggtsmx9140000gn/T/pip-install-pm27_fz8/wordcloud_336161f269fa47b1971094c90f31c6d4/setup.py'"'"'; __file__='"'"'/private/var/folders/1y/492pgpsd7vv980kggtsmx9140000gn/T/pip-install-pm27_fz8/wordcloud_336161f269fa47b1971094c90f31c6d4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/1y/492pgpsd7vv980kggtsmx9140000gn/T/pip-wheel-oen3ac9z
       cwd: /private/var/folders/1y/492pgpsd7vv980kggtsmx9140000gn/T/pip-install-pm27_fz8/wordcloud_336161f269fa47b1971094c90f31c6d4/
  Complete output (91 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.7
  creating build/lib.macosx-10.9-x86_64-3.7/wordcloud
  copying wordcloud/wordcloud_cli.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
  copying wordcloud/_version.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
  copying wordcloud/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
  copying wordcloud/tokenization.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
  copying wordcloud/wordcloud.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
  copying wordcloud/color_from_image.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
  copying wordcloud/__main__.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
  copying wordcloud/stopwords -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
  copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
  UPDATING build/lib.macosx-10.9-x86_64-3.7/wordcloud/_version.py
  set build/lib.macosx-10.9-x86_64-3.7/wordcloud/_version.py to '1.8.1'
  running build_ext
  building 'wordcloud.query_integral_image' extension
  creating build/temp.macosx-10.9-x86_64-3.7
  creating build/temp.macosx-10.9-x86_64-3.7/wordcloud
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/lee/.conda/envs/TensorFlow/include -arch x86_64 -I/Users/lee/.conda/envs/TensorFlow/include -arch x86_64 -I/Users/lee/.conda/envs/TensorFlow/include/python3.7m -c wordcloud/query_integral_image.c -o build/temp.macosx-10.9-x86_64-3.7/wordcloud/query_integral_image.o
  In file included from wordcloud/query_integral_image.c:4:
  In file included from /Users/lee/.conda/envs/TensorFlow/include/python3.7m/Python.h:63:
  In file included from /Users/lee/.conda/envs/TensorFlow/include/python3.7m/pyport.h:578:
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/ctype.h:69:10: error: '_ctype.h' file not found, did you mean 'ctype.h'?
  #include <_ctype.h>
           ^
  In file included from wordcloud/query_integral_image.c:4:
  In file included from /Users/lee/.conda/envs/TensorFlow/include/python3.7m/Python.h:63:
  In file included from /Users/lee/.conda/envs/TensorFlow/include/python3.7m/pyport.h:579:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/wctype.h:40:
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:53:24: error: use of undeclared identifier '_CTYPE_A'
          return (__istype(_wc, _CTYPE_A|_CTYPE_D));
                                ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:53:33: error: use of undeclared identifier '_CTYPE_D'
          return (__istype(_wc, _CTYPE_A|_CTYPE_D));
                                         ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:59:24: error: use of undeclared identifier '_CTYPE_A'
          return (__istype(_wc, _CTYPE_A));
                                ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:65:24: error: use of undeclared identifier '_CTYPE_C'
          return (__istype(_wc, _CTYPE_C));
                                ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:77:25: error: use of undeclared identifier '_CTYPE_D'
          return (__isctype(_wc, _CTYPE_D));
                                 ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:83:24: error: use of undeclared identifier '_CTYPE_G'
          return (__istype(_wc, _CTYPE_G));
                                ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:89:24: error: use of undeclared identifier '_CTYPE_L'
          return (__istype(_wc, _CTYPE_L));
                                ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:95:24: error: use of undeclared identifier '_CTYPE_R'
          return (__istype(_wc, _CTYPE_R));
                                ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:101:24: error: use of undeclared identifier '_CTYPE_P'
          return (__istype(_wc, _CTYPE_P));
                                ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:107:24: error: use of undeclared identifier '_CTYPE_S'
          return (__istype(_wc, _CTYPE_S));
                                ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:113:24: error: use of undeclared identifier '_CTYPE_U'
          return (__istype(_wc, _CTYPE_U));
                                ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:119:25: error: use of undeclared identifier '_CTYPE_X'
          return (__isctype(_wc, _CTYPE_X));
                                 ^
  In file included from wordcloud/query_integral_image.c:4:
  In file included from /Users/lee/.conda/envs/TensorFlow/include/python3.7m/Python.h:63:
  In file included from /Users/lee/.conda/envs/TensorFlow/include/python3.7m/pyport.h:579:
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/wctype.h:52:24: error: use of undeclared identifier '_CTYPE_B'
          return (__istype(_wc, _CTYPE_B));
                                ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/wctype.h:65:24: error: use of undeclared identifier '_CTYPE_X'
          return (__istype(_wc, _CTYPE_X));
                                ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/wctype.h:71:24: error: use of undeclared identifier '_CTYPE_I'
          return (__istype(_wc, _CTYPE_I));
                                ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/wctype.h:77:24: error: use of undeclared identifier '_CTYPE_D'
          return (__istype(_wc, _CTYPE_D));
                                ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/wctype.h:83:24: error: use of undeclared identifier '_CTYPE_Q'
          return (__istype(_wc, _CTYPE_Q));
                                ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/wctype.h:95:24: error: use of undeclared identifier '_CTYPE_T'
          return (__istype(_wc, _CTYPE_T));
                                ^
  19 errors generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
Failed to build wordcloud
Installing collected packages: wordcloud, umap-learn, textblob, spacy, scikit-plot, pyod, pyLDAvis, pandas-profiling, mlxtend, lightgbm, kmodes, imbalanced-learn, gensim, cufflinks, Boruta, pycaret
    Running setup.py install for wordcloud ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/lee/.conda/envs/TensorFlow/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/1y/492pgpsd7vv980kggtsmx9140000gn/T/pip-install-pm27_fz8/wordcloud_336161f269fa47b1971094c90f31c6d4/setup.py'"'"'; __file__='"'"'/private/var/folders/1y/492pgpsd7vv980kggtsmx9140000gn/T/pip-install-pm27_fz8/wordcloud_336161f269fa47b1971094c90f31c6d4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/1y/492pgpsd7vv980kggtsmx9140000gn/T/pip-record-j219wqbm/install-record.txt --single-version-externally-managed --compile --install-headers /Users/lee/.conda/envs/TensorFlow/include/python3.7m/wordcloud
         cwd: /private/var/folders/1y/492pgpsd7vv980kggtsmx9140000gn/T/pip-install-pm27_fz8/wordcloud_336161f269fa47b1971094c90f31c6d4/
    Complete output (91 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/wordcloud
    copying wordcloud/wordcloud_cli.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
    copying wordcloud/_version.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
    copying wordcloud/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
    copying wordcloud/tokenization.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
    copying wordcloud/wordcloud.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
    copying wordcloud/color_from_image.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
    copying wordcloud/__main__.py -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
    copying wordcloud/stopwords -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
    copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-10.9-x86_64-3.7/wordcloud
    UPDATING build/lib.macosx-10.9-x86_64-3.7/wordcloud/_version.py
    set build/lib.macosx-10.9-x86_64-3.7/wordcloud/_version.py to '1.8.1'
    running build_ext
    building 'wordcloud.query_integral_image' extension
    creating build/temp.macosx-10.9-x86_64-3.7
    creating build/temp.macosx-10.9-x86_64-3.7/wordcloud
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/lee/.conda/envs/TensorFlow/include -arch x86_64 -I/Users/lee/.conda/envs/TensorFlow/include -arch x86_64 -I/Users/lee/.conda/envs/TensorFlow/include/python3.7m -c wordcloud/query_integral_image.c -o build/temp.macosx-10.9-x86_64-3.7/wordcloud/query_integral_image.o
    In file included from wordcloud/query_integral_image.c:4:
    In file included from /Users/lee/.conda/envs/TensorFlow/include/python3.7m/Python.h:63:
    In file included from /Users/lee/.conda/envs/TensorFlow/include/python3.7m/pyport.h:578:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/ctype.h:69:10: error: '_ctype.h' file not found, did you mean 'ctype.h'?
    #include <_ctype.h>
             ^
    In file included from wordcloud/query_integral_image.c:4:
    In file included from /Users/lee/.conda/envs/TensorFlow/include/python3.7m/Python.h:63:
    In file included from /Users/lee/.conda/envs/TensorFlow/include/python3.7m/pyport.h:579:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/wctype.h:40:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:53:24: error: use of undeclared identifier '_CTYPE_A'
            return (__istype(_wc, _CTYPE_A|_CTYPE_D));
                                  ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:53:33: error: use of undeclared identifier '_CTYPE_D'
            return (__istype(_wc, _CTYPE_A|_CTYPE_D));
                                           ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:59:24: error: use of undeclared identifier '_CTYPE_A'
            return (__istype(_wc, _CTYPE_A));
                                  ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:65:24: error: use of undeclared identifier '_CTYPE_C'
            return (__istype(_wc, _CTYPE_C));
                                  ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:77:25: error: use of undeclared identifier '_CTYPE_D'
            return (__isctype(_wc, _CTYPE_D));
                                   ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:83:24: error: use of undeclared identifier '_CTYPE_G'
            return (__istype(_wc, _CTYPE_G));
                                  ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:89:24: error: use of undeclared identifier '_CTYPE_L'
            return (__istype(_wc, _CTYPE_L));
                                  ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:95:24: error: use of undeclared identifier '_CTYPE_R'
            return (__istype(_wc, _CTYPE_R));
                                  ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:101:24: error: use of undeclared identifier '_CTYPE_P'
            return (__istype(_wc, _CTYPE_P));
                                  ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:107:24: error: use of undeclared identifier '_CTYPE_S'
            return (__istype(_wc, _CTYPE_S));
                                  ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:113:24: error: use of undeclared identifier '_CTYPE_U'
            return (__istype(_wc, _CTYPE_U));
                                  ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_wctype.h:119:25: error: use of undeclared identifier '_CTYPE_X'
            return (__isctype(_wc, _CTYPE_X));
                                   ^
    In file included from wordcloud/query_integral_image.c:4:
    In file included from /Users/lee/.conda/envs/TensorFlow/include/python3.7m/Python.h:63:
    In file included from /Users/lee/.conda/envs/TensorFlow/include/python3.7m/pyport.h:579:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/wctype.h:52:24: error: use of undeclared identifier '_CTYPE_B'
            return (__istype(_wc, _CTYPE_B));
                                  ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/wctype.h:65:24: error: use of undeclared identifier '_CTYPE_X'
            return (__istype(_wc, _CTYPE_X));
                                  ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/wctype.h:71:24: error: use of undeclared identifier '_CTYPE_I'
            return (__istype(_wc, _CTYPE_I));
                                  ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/wctype.h:77:24: error: use of undeclared identifier '_CTYPE_D'
            return (__istype(_wc, _CTYPE_D));
                                  ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/wctype.h:83:24: error: use of undeclared identifier '_CTYPE_Q'
            return (__istype(_wc, _CTYPE_Q));
                                  ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/wctype.h:95:24: error: use of undeclared identifier '_CTYPE_T'
            return (__istype(_wc, _CTYPE_T));
                                  ^
    19 errors generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/lee/.conda/envs/TensorFlow/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/1y/492pgpsd7vv980kggtsmx9140000gn/T/pip-install-pm27_fz8/wordcloud_336161f269fa47b1971094c90f31c6d4/setup.py'"'"'; __file__='"'"'/private/var/folders/1y/492pgpsd7vv980kggtsmx9140000gn/T/pip-install-pm27_fz8/wordcloud_336161f269fa47b1971094c90f31c6d4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/1y/492pgpsd7vv980kggtsmx9140000gn/T/pip-record-j219wqbm/install-record.txt --single-version-externally-managed --compile --install-headers /Users/lee/.conda/envs/TensorFlow/include/python3.7m/wordcloud Check the logs for full command output.

**Comment by moezali1** [comment]
Seems like `wordcloud` installation is failing. Check if this helps: https://github.com/amueller/word_cloud/issues/105

**Comment by aicybersec** [comment]
it works on Colab but not on notebook

**Comment by aicybersec** [comment]
I installed wordcloud with conda but still pycaret don't get installed
