### ISSUE TITLE
Time Series MLFlow logging during `setup`

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#1790]
> Additionally, all the plots that doesn't require estimator can also be lagged at a setup stage such as ACF, PACF, ts, etc.

This is a good feature to have. We will take this up later (after model MLFlow logging is implemented).

_Originally posted by @ngupta23 in https://github.com/pycaret/pycaret/issues/1782#issuecomment-955689962_

**Comment by ngupta23** [comment]
We want to log the following plots during setup

- [ ] "diagnostics" (covers ACF, PACF, Periodogram, QQ-plot)
- [ ] "decomp" (covers classical decomposition)
- [ ] "diff" (covers difference plots)

**Comment by ngupta23** [comment]
This can mimic the way `_mlflow_log_model` is implemented

https://github.com/pycaret/pycaret/blob/b3fcf143f8d0dfae008fe8b69aef82074bec8215/pycaret/internal/pycaret_experiment/tabular_experiment.py#L168

So, maybe create another method called `_mlflow_log_setup` and internally, you can call the respective `plot_model` calls (similar to what is done inside `_mlflow_log_model`

https://github.com/pycaret/pycaret/blob/b3fcf143f8d0dfae008fe8b69aef82074bec8215/pycaret/internal/pycaret_experiment/tabular_experiment.py#L293

**Comment by ryanxjhan** [comment]
Hi @ngupta23, can you assign this issue to me? Thanks!

**Comment by ryankarlos** [comment]
@ngupta23  Is this issue being worked on or can I have a go ? My first contribution to pycaret

**Comment by ngupta23** [comment]
Thanks @ryankarlos. I have assigned it to you. This is not being worked on right now by anyone.
