### ISSUE TITLE
Blending

### ISSUE THREAD

**Issue by sulantha2006** [pycaret/pycaret#1792]
### Discussed in https://github.com/pycaret/pycaret/discussions/1772

<div type='discussions-op-text'>

<sup>Originally posted by **sulantha2006** October 27, 2021</sup>
Blending requires to use a percentage of the training data to train the meta learner. 
How is this implemented in pycaret? I assume the models are not retrained with the reduced training set. 

Can you help? Thanks. </div>

**Comment by moezali1** [comment]
@sulantha2006 Blending is just a voting classifier or regressor and it doesn't require setting % of training data aside for meta learners. I think you wanted to say stacking.

For stacking, we are using sklearn implementation of `StackingClassifier` and `StackingRegressor` with KFold cross-validation. To learn more about the details of implementation please see: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.StackingClassifier.html
