### ISSUE TITLE
[BUG] Classification Score decimal problem

### ISSUE THREAD

**Issue by Curry-38** [pycaret/pycaret#1794]
I get a knn mode from classification, but why I output the data and data_unseen, the classification Score only has one decimal that is not enough. Obviouly, I need 4 decimals as the example from the Pycaret.

So how fix this problem?
![image](https://user-images.githubusercontent.com/67360084/139819417-6be1c011-2fbc-4e09-95fe-e0ece83ac1ec.png)

**Comment by wkuopt** [comment]
Hi @Curry-38 , can you share the data and code for reproducing this issue?

**Comment by moezali1** [comment]
@Curry-38 This is not a bug. Looking at the numbers it seems like you are using the KNN model?

If that's true then KNN has a very limited concept of probability. Its estimate is simply a fraction of votes among nearest neighbors. Increase the number of neighbors to 15 or 100 or query points near the decision boundary and you will see more diverse results. Currently, your points are simply always having 5 neighbors of the same label (thus probability 0 or 1).

Read more: https://stackoverflow.com/questions/37089177/probability-prediction-method-of-kneighborsclassifier-returns-only-0-and-1
