### ISSUE TITLE
Dataframe constructor not properly called

### ISSUE THREAD

**Issue by BismeetSingh** [pycaret/pycaret#18]
While running a simple linear regression model on kaggle using pycaret, I get the error 
DataFrame constructor not properly called on running setup. The dataset contains only two columns.

```
df=pd.read_csv("/kaggle/input/salary-data-simple-linear-regression/Salary_Data.csv")`
setup_data1 = setup(data = df, target = 'Salary', session_id=123) 
```
Logs:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-c3ad091d442b> in <module>
----> 1 setup_data1 = setup(data = df, target = 'Salary', session_id=123)

/opt/conda/lib/python3.6/site-packages/pycaret/regression.py in setup(data, target, train_size, sampling, sample_estimator, categorical_features, categorical_imputation, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_interaction, feature_ratio, interaction_threshold, transform_target, transform_target_method, session_id, silent, profile)
    955                                           target_transformation = transform_target, #new
    956                                           target_transformation_method = transform_target_method_pass, #new
--> 957                                           random_state = seed)
    958 
    959     progress.value += 1

/opt/conda/lib/python3.6/site-packages/pycaret/preprocess.py in Preprocess_Path_One(train_data, target_variable, ml_usecase, test_data, categorical_features, numerical_features, time_features, features_todrop, display_types, imputation_type, numeric_imputation_strategy, categorical_imputation_strategy, apply_zero_nearZero_variance, club_rare_levels, rara_level_threshold_percentage, apply_untrained_levels_treatment, untrained_levels_treatment_method, apply_ordinal_encoding, ordinal_columns_and_categories, apply_cardinality_reduction, cardinal_method, cardinal_features, apply_binning, features_to_binn, apply_grouping, group_name, features_to_group_ListofList, apply_polynomial_trigonometry_features, max_polynomial, trigonometry_calculations, top_poly_trig_features_to_select_percentage, scale_data, scaling_method, Power_transform_data, Power_transform_method, target_transformation, target_transformation_method, remove_outliers, outlier_contamination_percentage, outlier_methods, apply_feature_selection, feature_selection_top_features_percentage, remove_multicollinearity, maximum_correlation_between_features, remove_perfect_collinearity, apply_feature_interactions, feature_interactions_to_apply, feature_interactions_top_features_to_select_percentage, cluster_entire_data, range_of_clusters_to_try, apply_pca, pca_method, pca_variance_retained_or_number_of_components, random_state)
   2538     return(pipe.fit_transform(train_data),pipe.transform(test_data))
   2539   else:
-> 2540     return(pipe.fit_transform(train_data))
   2541 
   2542 

/opt/conda/lib/python3.6/site-packages/sklearn/pipeline.py in fit_transform(self, X, y, **fit_params)
    381         """
    382         last_step = self._final_estimator
--> 383         Xt, fit_params = self._fit(X, y, **fit_params)
    384         with _print_elapsed_time('Pipeline',
    385                                  self._log_message(len(self.steps) - 1)):

/opt/conda/lib/python3.6/site-packages/sklearn/pipeline.py in _fit(self, X, y, **fit_params)
    311                 message_clsname='Pipeline',
    312                 message=self._log_message(step_idx),
--> 313                 **fit_params_steps[name])
    314             # Replace the transformer of the step with the fitted
    315             # transformer. This is necessary when loading the transformer

/opt/conda/lib/python3.6/site-packages/joblib/memory.py in __call__(self, *args, **kwargs)
    353 
    354     def __call__(self, *args, **kwargs):
--> 355         return self.func(*args, **kwargs)
    356 
    357     def call_and_shelve(self, *args, **kwargs):

/opt/conda/lib/python3.6/site-packages/sklearn/pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    724     with _print_elapsed_time(message_clsname, message):
    725         if hasattr(transformer, 'fit_transform'):
--> 726             res = transformer.fit_transform(X, y, **fit_params)
    727         else:
    728             res = transformer.fit(X, y, **fit_params).transform(X)

/opt/conda/lib/python3.6/site-packages/pycaret/preprocess.py in fit_transform(self, dataset, y)
   1957   def fit_transform(self,dataset,y=None):
   1958     data = dataset.copy()
-> 1959     corr = pd.DataFrame(np.corrcoef(data.drop(self.target,axis=1).T))
   1960     corr.columns = data.drop(self.target,axis=1).columns
   1961     corr.index = data.drop(self.target,axis=1).columns

/opt/conda/lib/python3.6/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    483                 )
    484             else:
--> 485                 raise ValueError("DataFrame constructor not properly called!")
    486 
    487         NDFrame.__init__(self, mgr, fastpath=True)

ValueError: DataFrame constructor not properly called!

**Comment by pycaret** [comment]
Hi, 

Thanks for logging the issue. I don't see if you have imported regression module in above code. Can you please confirm if you have run the below code before running setup function:

from pycaret.regression import *

Thanks.

**Comment by BismeetSingh** [comment]
Yes, I have made all the necessary imports otherwise the error would be module not found. I didnt write that since I thought that's implied.

**Comment by pycaret** [comment]
Thanks. Can you try this on a local Jupyter notebook or Google colab and see if you can reproduce the error? 

Can you also share the csv file?

**Comment by BismeetSingh** [comment]
I get the same error on a local Jupyter Notebook. Cant attach the csv so shared the link to the file:
https://www.kaggle.com/karthickveerakumar/salary-data-simple-linear-regression

**Comment by DaGuT** [comment]
@pycaret help granted :) at https://github.com/pycaret/pycaret/pull/33

**Comment by pycaret** [comment]
@DaGuT Thank you so so much. I will start working on PR's in weeks time.

**Comment by DaGuT** [comment]
@pycaret issue solved and can be closed?

**Comment by cryptonaut1357** [comment]
i have the same issue - one numeric, one label data type 

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-cb3d7795c377> in <module>()
      1 from pycaret.regression import *
----> 2 exp1 = setup(df, target = 'y')

~\Anaconda3\lib\site-packages\pycaret\regression.py in setup(data, target, train_size, sampling, sample_estimator, categorical_features, categorical_imputation, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_interaction, feature_ratio, interaction_threshold, transform_target, transform_target_method, session_id, silent, profile)
    955                                           target_transformation = transform_target, #new
    956                                           target_transformation_method = transform_target_method_pass, #new
--> 957                                           random_state = seed)
    958 
    959     progress.value += 1

~\Anaconda3\lib\site-packages\pycaret\preprocess.py in Preprocess_Path_One(train_data, target_variable, ml_usecase, test_data, categorical_features, numerical_features, time_features, features_todrop, display_types, imputation_type, numeric_imputation_strategy, categorical_imputation_strategy, apply_zero_nearZero_variance, club_rare_levels, rara_level_threshold_percentage, apply_untrained_levels_treatment, untrained_levels_treatment_method, apply_ordinal_encoding, ordinal_columns_and_categories, apply_cardinality_reduction, cardinal_method, cardinal_features, apply_binning, features_to_binn, apply_grouping, group_name, features_to_group_ListofList, apply_polynomial_trigonometry_features, max_polynomial, trigonometry_calculations, top_poly_trig_features_to_select_percentage, scale_data, scaling_method, Power_transform_data, Power_transform_method, target_transformation, target_transformation_method, remove_outliers, outlier_contamination_percentage, outlier_methods, apply_feature_selection, feature_selection_top_features_percentage, remove_multicollinearity, maximum_correlation_between_features, remove_perfect_collinearity, apply_feature_interactions, feature_interactions_to_apply, feature_interactions_top_features_to_select_percentage, cluster_entire_data, range_of_clusters_to_try, apply_pca, pca_method, pca_variance_retained_or_number_of_components, random_state)
   2538     return(pipe.fit_transform(train_data),pipe.transform(test_data))
   2539   else:
-> 2540     return(pipe.fit_transform(train_data))
   2541 
   2542 

~\Anaconda3\lib\site-packages\sklearn\pipeline.py in fit_transform(self, X, y, **fit_params)
    381         """
    382         last_step = self._final_estimator
--> 383         Xt, fit_params = self._fit(X, y, **fit_params)
    384         with _print_elapsed_time('Pipeline',
    385                                  self._log_message(len(self.steps) - 1)):

~\Anaconda3\lib\site-packages\sklearn\pipeline.py in _fit(self, X, y, **fit_params)
    311                 message_clsname='Pipeline',
    312                 message=self._log_message(step_idx),
--> 313                 **fit_params_steps[name])
    314             # Replace the transformer of the step with the fitted
    315             # transformer. This is necessary when loading the transformer

~\Anaconda3\lib\site-packages\joblib\memory.py in __call__(self, *args, **kwargs)
    353 
    354     def __call__(self, *args, **kwargs):
--> 355         return self.func(*args, **kwargs)
    356 
    357     def call_and_shelve(self, *args, **kwargs):

~\Anaconda3\lib\site-packages\sklearn\pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    724     with _print_elapsed_time(message_clsname, message):
    725         if hasattr(transformer, 'fit_transform'):
--> 726             res = transformer.fit_transform(X, y, **fit_params)
    727         else:
    728             res = transformer.fit(X, y, **fit_params).transform(X)

~\Anaconda3\lib\site-packages\pycaret\preprocess.py in fit_transform(self, dataset, y)
   1957   def fit_transform(self,dataset,y=None):
   1958     data = dataset.copy()
-> 1959     corr = pd.DataFrame(np.corrcoef(data.drop(self.target,axis=1).T))
   1960     corr.columns = data.drop(self.target,axis=1).columns
   1961     corr.index = data.drop(self.target,axis=1).columns

~\Anaconda3\lib\site-packages\pandas\core\frame.py in __init__(self, data, index, columns, dtype, copy)
    466                                    dtype=values.dtype, copy=False)
    467             else:
--> 468                 raise ValueError('DataFrame constructor not properly called!')
    469 
    470         NDFrame.__init__(self, mgr, fastpath=True)

ValueError: DataFrame constructor not properly called!`

**Comment by DaGuT** [comment]
@cryptonaut1357 
dev version 1.0.1 has this problem fixed. You can install it with:
`pip install https://github.com/pycaret/pycaret/archive/dev-1.0.1.zip`

Or you can apply changes yourself:  https://github.com/pycaret/pycaret/pull/70/files
