### ISSUE TITLE
HuberRegressor Fails in compare_models()

### ISSUE THREAD

**Issue by asaddiqu** [pycaret/pycaret#181]
Following error message appears in model_compare() for regressions:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-9ff5ccfe3077> in <module>
----> 1 compare_models()

~\AppData\Roaming\Python\Python37\site-packages\pycaret\regression.py in compare_models(blacklist, fold, round, sort, turbo)
   2918             Xtrain,Xtest = data_X.iloc[train_i], data_X.iloc[test_i]
   2919             ytrain,ytest = data_y.iloc[train_i], data_y.iloc[test_i]
-> 2920             model.fit(Xtrain,ytrain)
   2921             pred_ = model.predict(Xtest)
   2922 

~\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\_huber.py in fit(self, X, y, sample_weight)
    293             raise ValueError("HuberRegressor convergence failed:"
    294                              " l-BFGS-b solver terminated with %s"
--> 295                              % opt_res.message)
    296         self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
    297         self.scale_ = parameters[-1]

ValueError: HuberRegressor convergence failed: l-BFGS-b solver terminated with b'ABNORMAL_TERMINATION_IN_LNSRCH'

**Comment by srikanthSampathi1** [comment]
@asaddiqu how did you resolve this issue?
