### ISSUE TITLE
issue with module 'sklearn' has no wttribute 'pipeline'

### ISSUE THREAD

**Issue by fakhrmoosavy** [pycaret/pycaret#1818]
hi 
when I am running 
from pycaret.classification import * 
I am facing this error:
module'sklearn' has no attribute 'pipeline'. I already installed sklearn version 0.23.2 and also I ran this line 
from sklearn.pipeline import Pipeline
and it is working to me but not sure why I am facing above error for pycaret.classification. Any idea or comments?

Thanks and looking forward for your help

**Comment by moezali1** [comment]
Please show the complete traceback.

**Comment by fakhrmoosavy** [comment]
Hi Moez,
Here it is :
![image](https://user-images.githubusercontent.com/58143342/140854347-98a4daba-e9c8-4a5a-9e7a-6e3efabfee13.png)

Thanks

**Comment by fakhrmoosavy** [comment]
![image](https://user-images.githubusercontent.com/58143342/140854793-8dc6735a-796e-4bfa-9a4d-64b1a5be3da1.png)
