### ISSUE TITLE
change "test" into "validation"

### ISSUE THREAD

**Issue by wolfryu** [pycaret/pycaret#1832]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

Dataset should be split into train ,test and validation.
Test data = unseen data.
"train" "test" data split by pycaret setup API, the "test" is not real test dataset, the "test" will be used in "evaluate_model", "tune_model" ... , so the "test" here is "validation"! The user will confused about this!

**Describe the solution you'd like**
A clear and concise description of what you want to happen, ideally taking into consideration the existing toolbox design, classes and methods. 

Change "test" into "validation", both the code and the documents.

**Describe alternatives you've considered**

Tell user, the "test" data will be used in "evaluate_model" ... in documents.

**Additional context**

**Comment by moezali1** [comment]
@wolfryu 

test data is not used by PyCaret in `tune_model`.  In the `evaluate_model` function it is only used for evaluation based on the final model selected based on cross-validation. I don't believe there is any change required in documentation or either in the library itself.

Thanks for reporting anyways.
