### ISSUE TITLE
Time Series | Remove R2 as a metric

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#1834]
See [linkedin comments here](https://www.linkedin.com/feed/update/urn:li:activity:6863853023995731968?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6863853023995731968%2C6863864860342546433%29&replyUrn=urn%3Ali%3Acomment%3A%28activity%3A6863853023995731968%2C6863989154536054784%29) for reason.

**Comment by moezali1** [comment]
I don't agree with this comment. Let's discuss.

**Comment by ngupta23** [comment]
Ok, Once MASE is added, it could replace R2 if we want. MASE is anyway more important.

**Comment by moezali1** [comment]
MASE is added now, but please do not remove R2.

Users have the ability to use the `remove_metric` function to remove R2 if they want.

**Comment by ngupta23** [comment]
Why is R2 not a good measure for time series:

- https://www.youtube.com/watch?v=MN5AYymKDhc
- https://www.jstor.org/stable/2286421

**Comment by ngupta23** [comment]
Poll Results

[Poll 1](https://www.linkedin.com/posts/profile-moez_datascience-machinelearning-opensource-activity-6926174966946119680-eUh_?utm_source=linkedin_share&utm_medium=member_desktop_web)

[Poll 2](https://www.linkedin.com/posts/pycaret_datascience-machinelearning-opensource-activity-6926175098462740480-pJH5?utm_source=linkedin_share&utm_medium=member_desktop_web)

**Comment by ngupta23** [comment]
@moezali1 So what is the final call?

**Comment by moezali1** [comment]
@ngupta23 Let's keep R2 for now please.

![image](https://user-images.githubusercontent.com/54699234/167966851-cc3f53bc-20fa-4bc1-8146-36759ec6406b.png)

**Comment by ngupta23** [comment]
ok, closing for now then.
