### ISSUE TITLE
[DOC] Pycaret regression's save_experiment missing

### ISSUE THREAD

**Issue by valejop** [pycaret/pycaret#1835]
#### Describe the issue linked to the documentation
I don't see the save_experiment function in the pycaret.regression module. I re-installed pycaret via pip but it doesn't show. I'm using the 2.3.4 version.

#### Suggest a potential alternative/fix

If it works well with you, could you give me the version you are using please?

**Comment by moezali1** [comment]
@valejop `save_experiment` function was removed from pycaret>=2.0. 

You can now instead use the `save_config` function if you want to save your experiment settings. 

![image](https://user-images.githubusercontent.com/54699234/141522797-605db485-7d79-44d7-8a42-2ec99c465f71.png)

Read more: https://pycaret.readthedocs.io/en/latest/api/classification.html
