### ISSUE TITLE
"Multi label" Classification 

### ISSUE THREAD

**Issue by harikiran-mudipalli** [pycaret/pycaret#184]
Is there a way to run model on a multi-label / multi-target dataset?

**Comment by pandeynandancse** [comment]
@harikiran-mudipalli pass target column names as a list in target parameter.
And let me know if it worked.
Thanks,

**Comment by harikiran-mudipalli** [comment]
I tried it but it doesn't work. There is a MultiOutputClassifier() from sklearn which takes care of multiple targets. This option isn't available in pycaret's source code.

**Comment by krannnn** [comment]
@harikiran-mudipalli did you find a solution? I'm trying to do the same: multilabel classification

**Comment by harikiran-mudipalli** [comment]
@krannnn I'm trying to add sklearn's MultiOutputClassifier() in the pycaret scripts but then we can not do parameter tuning as there is no option of tuning in MultiOutputClassifier() source code as far as I observed. I was partially able to solve a multilabel problem without pycaret, from scratch by implementing papers.

**Comment by pycaret** [comment]
@krannnn  @harikiran-mudipalli  @pandeynandancse 

This is not supported at the moment. I am tagging this as an enhancement for future release.

**Comment by yashmehta10** [comment]
I could only think of this workaround for time-being.
Try selecting target=target1 and ignore_features=[target2] to train classifier 1,
then target=target2 and ignore_features=[target1] to train classifier 2.
I hope this works!

**Comment by harshag24** [comment]
@yashmehta10 after creating this models how to get single output using both the classifiers?

**Comment by yashmehta10** [comment]
Can you show me how do you want the target to look like? @harshag24

**Comment by pycaret** [comment]
@harikiran-mudipalli Maybe you are looking for Multi-label classifier not Multiclass classification. If you are looking for Multi-label, it's not supported in 2.0 as of yet.

**Comment by harshag24** [comment]
@yashmehta10  I wanted outputs of both the models in separate columns in a dataframe , never mind I did that.
