### ISSUE TITLE
[DOC] Explanation of the score in predict_model output

### ISSUE THREAD

**Issue by sorenwacker** [pycaret/pycaret#1842]
Hi,

I cannot find an explanation of the 'Score' column generated by `predict_model()`. 

I would expect to find an explanation [here](https://pycaret.org/predict-model/), but it is not even mentioned. 

It does not seem to be related to the probability corresponding to `predict_proba()` from 'scikit-learn' as positive and negative predictions have the same score range 0.5 to 1. The probability would actually be a very useful output of a classification model to get by default (different issue though).

Is it some kind of certainty score? Maybe you could add a short paragraph to the docs.

**Comment by moezali1** [comment]
@sorenwacker The column `Score` returned by the `predict_model` function is the probability of the predicted class.

![image](https://user-images.githubusercontent.com/54699234/141662895-fa9da90f-ec7a-4277-a928-f26363cc6fa2.png)

If you would like to see the probability of both the classes, just pass `raw_score = True` in the `predict_model` function.

**Comment by sorenwacker** [comment]
Oh, so the page I was referring to is actually not the official documentation! Thanks!
