### ISSUE TITLE
[BUG] scikit-learn 0.24 or 1.0 compability?

### ISSUE THREAD

**Issue by kurucan** [pycaret/pycaret#1847]
Successfully installed pycaret-2.3.4 scikit-learn-0.23.2

no scikit-learn 0.24 or 1.0.1 stable version compability?

**Comment by Yard1** [comment]
The next major release will feature compatibility for latest versions of scikit-learn.

**Comment by kylegilde** [comment]
Was this addressed in the 2.3.6 release? If no, is this planned for a specific release? Thank you!

**Comment by Yard1** [comment]
The next major release (3.0) will feature compatibility with latest scikit-learn versions.
