### ISSUE TITLE
Classification Setup Removing Features Without Being Asked

### ISSUE THREAD

**Issue by joaopcnogueira** [pycaret/pycaret#185]
First of all, I have no words to thank you all  people for having create Pycaret! I truly believe it is goin[g to be the defacto python ml library. For me, it already is!

Well, modeling today with pycaret I came into the following issue:

I have 70 features numeric features and I sign to remove 4 features, named `['dt_ref', 'seller_city', 'seller_state', 'seller_id']`. Even though, the final set of features to be used by pycaret has 65 features. I have noticed that beyond the features I have told it to remove, he also removed another one, called `idade_base_mes`. 

Digging further, I've noticed that this features presents a high correlation with another one, `idade_base_dias`. But, I haven't set to true the `remove_multicollinearity` parameter in the setup function.

Any clue on what's going on?

For reproducibility:
[data](https://drive.google.com/drive/folders/1kdrHJOXGGud5nVv2EJU0IcXLma47ovu1?usp=sharing)
Here is the code I am using:
[notebook](https://github.com/joaopcnogueira/dtona/blob/master/participacao-live/modeling_pycaret.ipynb)

**Requirements**:
pycaret=1.0.0
pandas=1.0.4
numpy=1.18.4
sqlalchemy=1.3.13

**Comment by pycaret** [comment]
@joaopcnogueira This is happening not because of remove_multicollinearity. There is another functionality in preprocess.py which is bound to remove 100% collinear variables. In this case idade_base_dias is 100% collinar with atleast 1 other variable.

**Comment by joaopcnogueira** [comment]
Thank you very much for the answer!

Can you tell me what is this functionality? I planning to teach machine learning with PyCaret and just wanna know in details what is really driving this behaviour.
