### ISSUE TITLE
[BUG] No module named 'pycaret.internal.pycaret_experiment'

### ISSUE THREAD

**Issue by kurucan** [pycaret/pycaret#1851]
On my linux python 3.7 virtual environment, I  have installed the latest pycaret from pip, I get the error below while importing?

I am following the example on the notebook below;
https://nbviewer.org/github/pycaret/pycaret/blob/time_series_beta/time_series_101.ipynb

import time
import numpy as np
import pandas as pd

from pycaret.datasets import get_data
from pycaret.internal.pycaret_experiment import TimeSeriesExperiment

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-b4e66adae9ae> in <module>
      4 
      5 from pycaret.datasets import get_data
----> 6 from pycaret.internal.pycaret_experiment import TimeSeriesExperiment

ModuleNotFoundError: No module named 'pycaret.internal.pycaret_experiment'

**Comment by moezali1** [comment]
@kurucan You have to install `pycaret-ts-alpha`. Please create a new conda environment and install time series module with `pip install pycaret-ts-alpha`. It should work then!

**Comment by kurucan** [comment]
> @kurucan You have to install `pycaret-ts-alpha`. Please create a new conda environment and install time series module with `pip install pycaret-ts-alpha`. It should work then!

sorry, I missed that it is a seperate package, thanks !

I have successufully run the example on python env, not on conda.

**Comment by ngupta23** [comment]
Just a follow-up in case folks face the same issue again. 

`pycaret-ts-alpha` has been depracated and the time series module has now been merged back to the main `pycaret` module. You can install it by using 

`pip install --pre pycaret`

With this installation, you can now also use the time series module along with the other tasks such as regression, classification, clustering, etc.
