### ISSUE TITLE
[BUG] business days freq (like stock market) is not supported

### ISSUE THREAD

**Issue by kurucan** [pycaret/pycaret#1853]
I have a data consisting of business days only, excluding weekends.

pandas series as: Freq: B, Name: sales, Length: 8955, dtype: float64

ValueError: Unsupported Period frequency: B, valid Period frequencies: S, T, H, D, W, M, Q, A, Y

How to deal data like stock market?

**Comment by moezali1** [comment]
@kurucan Can you please upload your Notebook and data here so we can try to reproduce the error and troubleshoot?

**Comment by kurucan** [comment]
below is the code and attached you will find stock market data as business days.

import time
import numpy as np
import pandas as pd
from pycaret.datasets import get_data
from pycaret.internal.pycaret_experiment import TimeSeriesExperiment
[y.csv](https://github.com/pycaret/pycaret/files/7534009/y.csv)

y = pd.read_csv('y.csv')
y[["date"]] = y[["date"]].apply(pd.to_datetime)
y = y.set_index('date')
y = y.asfreq(freq='B')
y = y.squeeze()

fh = 4 # or alternately fh = np.arange(1,13)
fold = 3
fold_strategy = 'sliding'
exp = TimeSeriesExperiment()
exp.setup(data=y, fh=fh)
exp.models()

**Comment by ngupta23** [comment]
@kurucan Modeling stock data is not a good idea using traditional methods. This data is a random walk and the predictions will not be useful (same as last known data point). I will write an article to explain that.

For the time being, please resample to weekly data and model it to see that this is indeed the case. Something like shown below.

```python
# Resample weekly to avoid missing weekends
stock_df = stock_df.resample("W").mean()
```

Nonetheless modeling business week would be helpful. I will close this issue and note that as a future enhancement (unrelated to modeling stock market).
