### ISSUE TITLE
[BUG] error on weekly freq data: TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by kurucan** [pycaret/pycaret#1855]
I am getting the error below for creatng the model when using weekly resampled data , I have also resampled the data to monhtly freq, It works fine. 

Below is the code and attached you will find weekly data example.

[y_weekly.csv](https://github.com/pycaret/pycaret/files/7534217/y_weekly.csv)

import time
import numpy as np
import pandas as pd

from pycaret.datasets import get_data
from pycaret.internal.pycaret_experiment import TimeSeriesExperiment

y = pd.read_csv('y_weekly.csv')
y[["date"]] = y[["date"]].apply(pd.to_datetime)
y = y.set_index('date')
y = y.asfreq(freq='W')
y = y.squeeze()

fh = 4 # or alternately fh = np.arange(1,13)
fold = 3
fold_strategy = 'sliding'
exp = TimeSeriesExperiment()
exp.setup(data=y, fh=fh)
model = exp.create_model("rf_cds_dt")

ERROR:root:Fit failed on BaseCdsDtForecaster(regressor=Lasso(random_state=7991))
ERROR:root:Found input variables with inconsistent numbers of samples: [1084, 1080]
ERROR:root:Fit failed on BaseCdsDtForecaster(regressor=Lasso(random_state=7991))
ERROR:root:Found input variables with inconsistent numbers of samples: [1085, 1081]
ERROR:root:Fit failed on BaseCdsDtForecaster(regressor=Lasso(random_state=7991))
ERROR:root:Found input variables with inconsistent numbers of samples: [1083, 1079]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_206467/1539794985.py in <module>
     17 exp = TimeSeriesExperiment()
     18 exp.setup(data=y, fh=fh)
---> 19 model = exp.create_model("lasso_cds_dt")

~/env-pycaret/lib/python3.7/site-packages/pycaret/internal/pycaret_experiment/time_series_experiment.py in create_model(self, estimator, fold, round, cross_validation, fit_kwargs, verbose, **kwargs)
   1355             fit_kwargs=fit_kwargs,
   1356             verbose=verbose,
-> 1357             **kwargs,
   1358         )
   1359 

~/env-pycaret/lib/python3.7/site-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py in create_model(self, estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, verbose, system, add_to_model_list, X_train_data, y_train_data, metrics, display, **kwargs)
   1553             refit,
   1554             system,
-> 1555             display,
   1556         )
   1557 

~/env-pycaret/lib/python3.7/site-packages/pycaret/internal/pycaret_experiment/time_series_experiment.py in _create_model_with_cv(self, model, data_X, data_y, fit_kwargs, round, cv, groups, metrics, refit, system, display)
   1493         self.logger.info("Calculating mean and std")
   1494 
-> 1495         avgs_dict = {k: [np.mean(v), np.std(v)] for k, v in score_dict.items()}
   1496 
   1497         display.move_progress()

~/env-pycaret/lib/python3.7/site-packages/pycaret/internal/pycaret_experiment/time_series_experiment.py in <dictcomp>(.0)
   1493         self.logger.info("Calculating mean and std")
   1494 
-> 1495         avgs_dict = {k: [np.mean(v), np.std(v)] for k, v in score_dict.items()}
   1496 
   1497         display.move_progress()

<__array_function__ internals> in mean(*args, **kwargs)

~/env-pycaret/lib/python3.7/site-packages/numpy/core/fromnumeric.py in mean(a, axis, dtype, out, keepdims)
   3371 
   3372     return _methods._mean(a, axis=axis, dtype=dtype,
-> 3373                           out=out, **kwargs)
   3374 
   3375 

~/env-pycaret/lib/python3.7/site-packages/numpy/core/_methods.py in _mean(a, axis, dtype, out, keepdims)
    158             is_float16_result = True
    159 
--> 160     ret = umr_sum(arr, axis, dtype, out, keepdims)
    161     if isinstance(ret, mu.ndarray):
    162         ret = um.true_divide(

TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

**Comment by ngupta23** [comment]
Missing values are not supported yet (it will be in a subsequent release). Can you try imputing the missing values manually for now before running the code?

**Comment by kurucan** [comment]
Many thanks, It was due to the missing values after pd.resample..
