### ISSUE TITLE
[BUG] cv plot only shows 3 folds

### ISSUE THREAD

**Issue by kurucan** [pycaret/pycaret#1856]
I am following the example on pycaret/time_series_beta/time_series_101.ipynb

# Show the Cross Validation splits inside the train set
exp.plot_model(plot="cv")

this plot only shows 3 folds even though I set fold numbers different from 3.

model training accepts the fold parameter input and works fine.

**Comment by kurucan** [comment]
closed.

**Comment by ngupta23** [comment]
https://github.com/pycaret/pycaret/issues/1856
