### ISSUE TITLE
[BUG] fold number input does not work

### ISSUE THREAD

**Issue by kurucan** [pycaret/pycaret#1857]
I am following the example on pycaret/time_series_beta/time_series_101.ipynb

I am trying to set fold number different from the default value but still showing me as 3.

![fold number](https://user-images.githubusercontent.com/7413036/141692913-4aeff67e-6aaf-458c-b5d2-807fd5225e8d.png)

**Comment by ngupta23** [comment]
You have to pass the fold parameter to the setup method
