### ISSUE TITLE
How to get output dataframe displayed after running create_model()?

### ISSUE THREAD

**Issue by bhishanpdl** [pycaret/pycaret#186]
I was just introduced to this library and I already liked it a lot. It's easy to use
and has lots of pre-built models. I like to extend my thanks to the devs for creating this awesome module.

I have one follow up question:
```python
clf_xgb = create_model('xgboost')
clf_xgb_tuned = tune_model('xgboost',fold=5,optimize='Recall')
```

When we run this code, it displays a dataframe with metric columns.
But the object clf_xgb is xgboost object (NOT pandas dataframe).

How to get the output dataframe displayed there?

If we can get output classifier as well as dataframe like:
```python
clf_xgb, df_xgb = create_model('xgboost') # feature request
clf_xgb_tuned, df_xgb_tuned = tune_model('xgboost',fold=5,optimize='Recall')
```

It would be much easier to compare which model is working better.

**Comment by pycaret** [comment]
@bhishanpdl Thanks for raising this.

This is not available in pycaret==1.0.0. However for next release I have created a universal function pull() which will return the dataframe of previously run model. so using your example:

clf_xgb = create_model('xgboost')
clf_xgb_df = pull()

In this example clf_xgb_df will be a pandas dataframe containing the results of clf_xgb. clf_xgb stores xgboost model.

Tagging this as enhancement and will close this issue once next version is released.

**Comment by bhishanpdl** [comment]
That's GREAT news, waiting for the next release.

**Comment by pycaret** [comment]
pull function now available in **pycaret-nightly**
