### ISSUE TITLE
[BUG] plot_model() is not working consistently

### ISSUE THREAD

**Issue by tugra-alp** [pycaret/pycaret#1865]
I used compare_model() to select top 3 models, and combine them with blend_model() function.

fh=np.arange(25,73) : 1 day gap and 2 days forecast horizon in each split (Hourly data).

`custom_split = SlidingWindowSplitter(fh=np.arange(25,73) , window_length=1200, step_length=720)`
`exp = TimeSeriesExperiment()`
`exp.setup(data=data1,  
                  fold_strategy = custom_split,        
                  preprocess = False, 
                  session_id = 42    
          )`
.
.
.
`exp.plot_model(blended_model, plot='forecast')`

After created blended_model object to see model performance, used plot_model and got this error.

![plotmodelissue](https://user-images.githubusercontent.com/82160533/142409610-f9fac09e-49b6-40c9-8c6c-2e44c1686a9a.png)

![plotmodelerrorreport](https://user-images.githubusercontent.com/82160533/142409693-ca04479d-0364-472f-afa4-6792ac0ddfef.png)

Note: Even i create single model to see model performance, same error raise up. 
Note: Sometimes this code snippet works fine, but when i re-run it, it comes with same error.

**Comment by ngupta23** [comment]
You seem to be passing a lot of custom things to the splitter. I can not tell the issue just by looking at the pictures. Can you share a minimally reproducible example (code + data) so I can debug? Thanks!

**Comment by ngupta23** [comment]
Can you try passing fh = np.arange(1, 73) and check. I dont think intermittent fh is supported yet. Just a guess by looking at the image and the difference in the shapes in the error message.

**Comment by tugra-alp** [comment]
As a Temporary solving,
This problem can solve if we set data_kwargs when plotting. 
Ex:
fh=np.arange(25,73) : 1 day gap and 2 days forecast horizon in each split (Hourly data).

exp.plot_model(estimator=model, data_kwargs = {'fh' : 72})

**Comment by ngupta23** [comment]
Fixed, it will be available in the next release.
