### ISSUE TITLE
[BUG] Time Series W-THU support

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#1866]
**Describe the bug**

- [x] W-THU is not supported right now. It only works if user specifies `seasonal_period` in setup

**To Reproduce**
![image](https://user-images.githubusercontent.com/33585645/142557323-ea93d9e1-8f9a-4242-aa54-aba775496f61.png)

**Expected behavior**
Would have expected it to automatically infer the freq = 52 from there.

**Comment by ngupta23** [comment]
@sayantan1410 - this might be a good one to look at if you are just starting off. You will need to look into how this is handled in the setup function - somewhere [over here](https://github.com/pycaret/pycaret/blob/73857c0502ec4d47e6ad6c03c2a3ec7a98af7d41/pycaret/internal/pycaret_experiment/time_series_experiment.py#L1007).

Let me know if you need any help to get started.

**Comment by ngupta23** [comment]
Also, "X" minute intervals are not supported (e.g. X = 10)

![image](https://user-images.githubusercontent.com/33585645/142730571-01a43326-8cd4-4975-a6fe-ba83a84905ee.png)

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-266e79e5cdae> in <module>
      5 from pycaret.internal.pycaret_experiment import TimeSeriesExperiment
      6 exp = TimeSeriesExperiment()
----> 7 exp.setup(data=y, fh=12, session_id=42)
      8 
      9 #### Initial Training ----

~/anaconda3/lib/python3.8/site-packages/pycaret/internal/pycaret_experiment/time_series_experiment.py in setup(self, data, preprocess, imputation_type, fold_strategy, fold, fh, seasonal_period, enforce_pi, n_jobs, use_gpu, custom_pipeline, html, session_id, system_log, log_experiment, experiment_name, log_plots, log_profile, log_data, verbose, profile, profile_kwargs)
   1013                 self.seasonal_period = SeasonalPeriod[index_freq].value
   1014             else:
-> 1015                 raise ValueError(
   1016                     f"Unsupported Period frequency: {index_freq}, valid Period frequencies: {', '.join(SeasonalPeriod.__members__.keys())}"
   1017                 )

ValueError: Unsupported Period frequency: 10T, valid Period frequencies: S, T, H, D, W, M, Q, A, Y
```

**Comment by sayantan1410** [comment]
I will surely look at it and will let you know a tentative time within which I can complete it, soon. Also, if I find any issue while solving going through it, I will let you know. 
@ngupta23

**Comment by sayantan1410** [comment]
Hey, I have started working on it and will complete it by tomorrow or day after tomorrow !!
@ngupta23

**Comment by sayantan1410** [comment]
Hello, can you give me a little bit insight on :-
1. Why we want to have frequency = 7 in this case, is it because of the dtype or we need to infer frequency = 7 for all the cases, basically how to infer what should be the frequency ?

**Comment by ngupta23** [comment]
@sayantan1410 , Currently it is based on the frequency. For example, weekly data has assumed frequency of 7 since the values will most likely repeat after a week. e.g. traffic on Saturdays might be lower than traffic on Wednesdays, etc. 

For other frequencies, it is different. For example, quarterly has assumed frequency of 4.

This is a best guess at this time only. In the future, we may add more intelligence to this extraction process.

**Comment by sayantan1410** [comment]
For the first part of the issue,
The pycaret module is correctly infering the frequency of 'W-THU' to be 52. There is no problem with it. 
Here's the code: 
`import pandas as pd`
`from pycaret.internal.pycaret_experiment import TimeSeriesExperiment`
`from pycaret.datasets import get_data`
`data = get_data('pycaret_downloads')`
`data['Date'] = pd.to_datetime(data['Date'])`
`data = data.groupby('Date').sum()`
`data = data.asfreq('W-THU')`
`exp = TimeSeriesExperiment()`
`exp.setup(data=data,fh=4,fold=1)`

If I have made any mistake in understanding the problem feel free to comment about that here.

**Comment by ngupta23** [comment]
@sayantan1410 Thanks for verifying. This should be good. You can proceed to the next part. Thanks!

**Comment by sayantan1410** [comment]
Welcome, Yeah I have started working on the next part !!! @ngupta23

**Comment by sayantan1410** [comment]
> * [ ]  Also, "X" minute intervals are not supported (e.g. X = 10). May have to split by numerics (starting with) as well and take the last part for checking the frequency.
> 
> ![image](https://user-images.githubusercontent.com/33585645/142730571-01a43326-8cd4-4975-a6fe-ba83a84905ee.png)
> 
> ```python
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-24-266e79e5cdae> in <module>
>       5 from pycaret.internal.pycaret_experiment import TimeSeriesExperiment
>       6 exp = TimeSeriesExperiment()
> ----> 7 exp.setup(data=y, fh=12, session_id=42)
>       8 
>       9 #### Initial Training ----
> 
> ~/anaconda3/lib/python3.8/site-packages/pycaret/internal/pycaret_experiment/time_series_experiment.py in setup(self, data, preprocess, imputation_type, fold_strategy, fold, fh, seasonal_period, enforce_pi, n_jobs, use_gpu, custom_pipeline, html, session_id, system_log, log_experiment, experiment_name, log_plots, log_profile, log_data, verbose, profile, profile_kwargs)
>    1013                 self.seasonal_period = SeasonalPeriod[index_freq].value
>    1014             else:
> -> 1015                 raise ValueError(
>    1016                     f"Unsupported Period frequency: {index_freq}, valid Period frequencies: {', '.join(SeasonalPeriod.__members__.keys())}"
>    1017                 )
> 
> ValueError: Unsupported Period frequency: 10T, valid Period frequencies: S, T, H, D, W, M, Q, A, Y
> ```

Hey can I get the dataset for which this error is happening, it will be easier for me to reproduce the issue then.

**Comment by ngupta23** [comment]
Just for reference: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html (these are the options that are available)
