### ISSUE TITLE
Accelerating pycaret

### ISSUE THREAD

**Issue by atwahsz** [pycaret/pycaret#187]
Is threre n_jobs option to accelerate the processing time ? Or Dask also

**Comment by pycaret** [comment]
@atwahsz Next release of pycaret will provide a parameter in setup() to control n_jobs accross the experiment run. By default it will be set to -1. 

Tagging this as an enhancement for now. Will close this once next version is released.

**Comment by pycaret** [comment]
@atwahsz 

### Feature available now.

This feature is now available for your testing. You can install pycaret nightly build using pip.

> pip install pycaret-nightly
