### ISSUE TITLE
[BUG] Data leakage if feature selection is enabled during setup in pycaret.classification

### ISSUE THREAD

**Issue by praveenck06** [pycaret/pycaret#1874]
Firstly, I like to thank for building this amazing tool

**Describe the bug**

It looks like entire training dataset is used for features selection and then same dataset is used for model selection with cross-validation.
Where the issue lies is during model selection training data will be divided into smaller splits and evaluated on those splits but during the feature selection entire training set will used to select features. These selected features will have some information about the final class of the model
 
Below are proof for the same:

With cross validation enabled
![image](https://user-images.githubusercontent.com/33887466/142715075-0be66111-a676-4c92-8d12-9ec2b031da86.png)

Without cross validation 
![image](https://user-images.githubusercontent.com/33887466/142714998-12018e0c-17b5-4898-9fcc-e9de024c41a7.png)

Why there is ~20% difference by just disabling the cross-validation?

**Expected behavior**
Instead of performing feature selection during the setup, move it to during model building and for each CV iteration let it perform feature selection and return the best features.

**Versions**

'2.3.5'

**Comment by wkuopt** [comment]
@Yard1 I believe this issue will be fixed once we are done with preprocessing revamping? Once preprocessing becomes sklearn compatible, we can fit and transform separately for different folds in cross validation.

**Comment by Yard1** [comment]
It will be, correct

**Comment by gm039** [comment]
@Yard1 @ngupta23 

Any plan to work on this issue? The cross-validation results are misleading.
By the way, what is the best way to select the best models among a few?

**Comment by Yard1** [comment]
This will be resolved in the next major update (3.0)
