### ISSUE TITLE
expose beta coefficients in print(lr)

### ISSUE THREAD

**Issue by DanieleBaranzini** [pycaret/pycaret#1875]
**for any parameterized model like linear regressions (OLS) let's generate:**

> lr = create_model('lr')
>>...
> print(lr)

**...in the output the pycaret do not print the beta values of each feature predictor for final cross-validated model lr**

**solution:**
**>> have a printout of the beta coefficients**

**Comment by moezali1** [comment]
@DanieleBaranzini The returned class is just a sklearn estimator. You can access the coefficient with `coef_` parameter. Like this:

![image](https://user-images.githubusercontent.com/54699234/142742882-5f79a2b0-4568-468a-b79d-d4cf9cfde329.png)

Hope this helps.

**Comment by DanieleBaranzini** [comment]
Thanks Moez, appreciated.

Daniele

**Comment by DanieleBaranzini** [comment]
@moezali1 a little further clarification (if possible): is it correct to say that in your example above (10-k fold) such beta parameters (coef_) are of a 'finalised' trained model that  is a final 11th model that use all training data available (in your example above 9 training + 1 validation folds together). 

The same process used to finalize a selected trained model by pooling all available data (training + test/holdout set)?

Daniele
