### ISSUE TITLE
[BUG] Unable to disable shuffle when making use of the classification setup

### ISSUE THREAD

**Issue by AlgoQ** [pycaret/pycaret#1888]
**Describe the bug**
When I disable the data_split_shuffle parameter when generating the setup variable for classification, the data stays shuffled. I've noticed this when exploring the `setup` variable.

**To Reproduce**
```python
setup = setup(data = data, target = 'label', session_id=123, data_split_shuffle=False) 
```

**Versions**
<details>
pycaret: 2.3.5
</details>

**Comment by moezali1** [comment]
Hi @AlgoQ - I have tested this and it seems like `data_split_shuffle` is working as expected. 

```
from pycaret.datasets import get_data
data = get_data('diabetes')

from pycaret.classification import *
s = setup(data, target = 'Class variable', session_id = 123, data_split_shuffle = True)

get_config('X_train').index
```
![image](https://user-images.githubusercontent.com/54699234/143689650-4280a468-b92f-4520-b9e0-86eaf4ef6abd.png)


```
from pycaret.datasets import get_data
data = get_data('diabetes')

from pycaret.classification import *
s = setup(data, target = 'Class variable', session_id = 123, data_split_shuffle = False)

get_config('X_train').index
```
![image](https://user-images.githubusercontent.com/54699234/143689668-e21471c1-0c27-4554-af0d-df078ed9d144.png)
