### ISSUE TITLE
load_model error

### ISSUE THREAD

**Issue by D-junyang** [pycaret/pycaret#189]
why when I saved the  'rf' model, it's class is true, but when  I load it it's class is a list class?
![1](https://user-images.githubusercontent.com/46164563/83515128-7127a880-a507-11ea-8608-a63cb2e62232.png)
![2](https://user-images.githubusercontent.com/46164563/83515139-74bb2f80-a507-11ea-937e-e26d00faa598.png)

**Comment by pycaret** [comment]
@D-junyang Hi. When you execute save_model it saves the transformation pipeline and model as two separate elements in list. You can access element 1 if you particularly want model. For example:

rf = create_model('rf')
save_model(rf, 'rf_saved')
loaded_rf = load_model('rf_saved')

To access model:
model = loaded_rf[1]

Hope this helps.
