### ISSUE TITLE
[BUG] Fix_imbalance parameter not working

### ISSUE THREAD

**Issue by ReeceJames24** [pycaret/pycaret#1890]
**Describe the bug**

Pulling the transformed 'X_train' and 'y_train' dataframes from get_config() after setup(......, fix_imbalance=True) still shows heavily imbalanced data. 

**To Reproduce**

```python
clf = setup(data3, 
            target = 'target', 
            categorical_features = nominals,
            ordinal_features = ordinals_dict,
            fix_imbalance=True,
            use_gpu=True)

#Pull transformed y_train dataset
y_train = get_config('y_train')

#Check distribution of classes
y_train.value_counts()
```

**Expected behavior**

The documentation for get_config() says X_train and y_train are already the transformed versions of the data meaning they should be balanced already. My assumption now is that my data is fed to the model still imbalanced leading to extremely overfit models as my data is uniquely hyper imbalanced.

![Screenshot (227)](https://user-images.githubusercontent.com/68687766/143524037-2b7afdd4-5ee1-43ef-8c4e-64f9537deeaa.png)
**Additional context**

**Versions**
<details>

'2.3.5'

</details>

**Comment by Yard1** [comment]
The resampling is applied per every fold in CV and therefore will not be visible in the dataframes obtained through get_config.
