### ISSUE TITLE
Time Series models to use `sp_to_use`

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#1894]
Currently, all models use something like this

```python
self.seasonality_present = globals_dict.get("seasonality_present")
sp = globals_dict.get("seasonal_period")
self.sp = sp if sp is not None else 1
```

```python
def _set_args(self) -> Dict[str, Any]:
    args = {"sp": self.sp} if self.seasonality_present else {}
```

Consider replacing `sp` here with `sp_to_use` instead (from `self.sp_to_use`).

```python
self.sp_to_use = globals_dict.get("sp_to_use")

def _set_args(self) -> Dict[str, Any]:
    args = {"sp": self.sp_to_use}
```

**Comment by ngupta23** [comment]
complete after merging preprocessing since we would be changing form using `globals_dict` to `experiment` in Model Container.

**Comment by drmario-gh** [comment]
As we talked in #1901, I'll happily take up this one.

**Comment by ngupta23** [comment]
Thanks, @drmario-gh. I will assign this to you.
