### ISSUE TITLE
Memmory related Crash

### ISSUE THREAD

**Issue by npapan69** [pycaret/pycaret#19]
Dear All,

Thanks for the great library, I'm facing problems when trying to use pandas to import my csv which has 130 rows and 110 columns. It consumes all my RAM (which is 64GB, MacBook Pro 16") and crashes. Any ideas? Up till now, I was able to use it only with csv files with a limited number of columns .

Nikos

**Comment by pycaret** [comment]
Hi,

It is quite surprising that with 64GB memory a csv load fails. Can you share the size of csv file? is it dataset publicly available? if yes, I would like to try that on several pc's as well. Can you share?

Thanks.

**Comment by pycaret** [comment]
One more question - are you using Python 32 bit or 64 bit?

**Comment by npapan69** [comment]
I'm using MacOS Catalina and 64bit Python. The size of the csv is about 5MB with 4300 columns and 99 rows. I'm uploading here the xlsx version of it.
[test_pycaret.xlsx](https://github.com/pycaret/pycaret/files/4496923/test_pycaret.xlsx)

Thanks

**Comment by npapan69** [comment]
The problem happens using JupiterNotebooks both locally and in Google Collabs

**Comment by pycaret** [comment]
Hi, I will check this out and get back.

**Comment by mfahadakbar** [comment]
@moezali1 can you share the details with me too? I think I experienced this issue as well, will talk to you about it

**Comment by DaGuT** [comment]
I confirm the same issue on Ubuntu 19.10 with python notebook.

It wants to eat more than 400gigs of RAM for a 6mb csv file :\

Log:

> ---------------------------------------------------------------------------
> MemoryError                               Traceback (most recent call last)
>  in 
> ----> 1 exp_clf101 = setup(data = data, target = 'Label')
> 
> /usr/local/lib/python3.7/dist-packages/pycaret/classification.py in setup(data, target, train_size, sampling, sample_estimator, categorical_features, categorical_imputation, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_interaction, feature_ratio, interaction_threshold, session_id, silent, profile)
>     929                                           display_types = display_dtypes_pass, #this is for inferred input box
>     930                                           target_transformation = False, #not needed for classification
> --> 931                                           random_state = seed)
>     932 
>     933     progress.value += 1
> 
> /usr/local/lib/python3.7/dist-packages/pycaret/preprocess.py in Preprocess_Path_One(train_data, target_variable, ml_usecase, test_data, categorical_features, numerical_features, time_features, features_todrop, display_types, imputation_type, numeric_imputation_strategy, categorical_imputation_strategy, apply_zero_nearZero_variance, club_rare_levels, rara_level_threshold_percentage, apply_untrained_levels_treatment, untrained_levels_treatment_method, apply_ordinal_encoding, ordinal_columns_and_categories, apply_cardinality_reduction, cardinal_method, cardinal_features, apply_binning, features_to_binn, apply_grouping, group_name, features_to_group_ListofList, apply_polynomial_trigonometry_features, max_polynomial, trigonometry_calculations, top_poly_trig_features_to_select_percentage, scale_data, scaling_method, Power_transform_data, Power_transform_method, target_transformation, target_transformation_method, remove_outliers, outlier_contamination_percentage, outlier_methods, apply_feature_selection, feature_selection_top_features_percentage, remove_multicollinearity, maximum_correlation_between_features, remove_perfect_collinearity, apply_feature_interactions, feature_interactions_to_apply, feature_interactions_top_features_to_select_percentage, cluster_entire_data, range_of_clusters_to_try, apply_pca, pca_method, pca_variance_retained_or_number_of_components, random_state)
>    2538     return(pipe.fit_transform(train_data),pipe.transform(test_data))
>    2539   else:
> -> 2540     return(pipe.fit_transform(train_data))
>    2541 
>    2542 
> 
> ~/.local/lib/python3.7/site-packages/sklearn/pipeline.py in fit_transform(self, X, y, **fit_params)
>     383         """
>     384         last_step = self._final_estimator
> --> 385         Xt, fit_params = self._fit(X, y, **fit_params)
>     386         with _print_elapsed_time('Pipeline',
>     387                                  self._log_message(len(self.steps) - 1)):
> 
> ~/.local/lib/python3.7/site-packages/sklearn/pipeline.py in _fit(self, X, y, **fit_params)
>     313                 message_clsname='Pipeline',
>     314                 message=self._log_message(step_idx),
> --> 315                 **fit_params_steps[name])
>     316             # Replace the transformer of the step with the fitted
>     317             # transformer. This is necessary when loading the transformer
> 
> /usr/local/lib/python3.7/dist-packages/joblib/memory.py in __call__(self, *args, **kwargs)
>     353 
>     354     def __call__(self, *args, **kwargs):
> --> 355         return self.func(*args, **kwargs)
>     356 
>     357     def call_and_shelve(self, *args, **kwargs):
> 
> ~/.local/lib/python3.7/site-packages/sklearn/pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
>     726     with _print_elapsed_time(message_clsname, message):
>     727         if hasattr(transformer, 'fit_transform'):
> --> 728             res = transformer.fit_transform(X, y, **fit_params)
>     729         else:
>     730             res = transformer.fit(X, y, **fit_params).transform(X)
> 
> /usr/local/lib/python3.7/dist-packages/pycaret/preprocess.py in fit_transform(self, dataset, y)
>     328     data= dataset.copy()
>     329     # since this is for training , we dont nees any transformation since it has already been transformed in fit
> --> 330     data = self.fit(data)
>     331 
>     332     # additionally we just need to treat the target variable
> 
> /usr/local/lib/python3.7/dist-packages/pycaret/preprocess.py in fit(self, dataset, y)
>     123               min_number = min(data[i])
>     124               max_number = max(data[i])
> --> 125               arr = np.arange(min_number,max_number+1,1)
>     126               try:
>     127                 all_match = sum(data[i].sort_values() == arr)
> 
> MemoryError: Unable to allocate 454. GiB for an array with shape (61000385383,) and data type float64


Pandas frame info:
`<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Columns: 4306 entries, Label to peritumoral_wavelet2-LLL_ngtdm_Strength
dtypes: float64(4300), int64(5), object(1)
memory usage: 4.3+ MB`

**Comment by pycaret** [comment]
@DaGuT Thanks.
@mfahadakbar Can you please have a look at #26

**Comment by mfahadakbar** [comment]
@pycaret accept the pull request, its all good
@DaGuT thanks for the fix

**Comment by DaGuT** [comment]
@pycaret issue solved and can be closed?

**Comment by pycaret** [comment]
@DaGuT yes. closing the issue now.

Thanks.
