### ISSUE TITLE
request to add an option to download all evaluated visualization plots

### ISSUE THREAD

**Issue by sathishkumar369** [pycaret/pycaret#190]
Hi pycaret team!
could you please add an option to download the visualization plots.

![Screenshot (189)](https://user-images.githubusercontent.com/40235632/83515975-de314300-a4f3-11ea-9b21-aa70712892f0.png)

**Comment by D-junyang** [comment]
maybe you can do that by adding  like visualizer.poof(outpath='./regression_picture/' + plot + '.png')  at source code

**Comment by pycaret** [comment]
@sathishkumar369 @D-junyang Thanks for suggestion. Adding this feature in next release.

Tagging this as enhancement and will close when next version is released.
