### ISSUE TITLE
tuning custom pipeline in tune_model time_series

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1902]
```
from sktime.transformations.series.impute import Imputer
from sktime.transformations.series.boxcox import LogTransformer
from sktime.forecasting.compose import TransformedTargetForecaster
from sktime.forecasting.arima import ARIMA

forecaster = TransformedTargetForecaster(
    [
        ("impute", Imputer()),
        ("log", LogTransformer()),
        ("model", ARIMA(seasonal_order=(0,1,0,12))),
    ]
)

my_custom_model = create_model(forecaster)

my_grid = {'imputer__method': ["drift", "bfill", "ffill"]}
tuned_model = tune_model(my_custom_model, custom_grid=my_grid)
```

---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\externals\loky\process_executor.py", line 431, in _process_worker
    r = call_item()
  File "C:\Users\owner\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\externals\loky\process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\owner\pycaret\pycaret\internal\pycaret_experiment\time_series_experiment.py", line 261, in _fit_and_score
    forecaster.set_params(**parameters)
  File "C:\Users\owner\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\compose\_pipeline.py", line 129, in set_params
    self._set_params("steps", **kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\base\_meta.py", line 54, in _set_params
    super().set_params(**params)
  File "C:\Users\owner\anaconda3\envs\pycaret-ts\lib\site-packages\sklearn\base.py", line 230, in set_params
    raise ValueError('Invalid parameter %s for estimator %s. '
ValueError: Invalid parameter imputer for estimator TransformedTargetForecaster(steps=[('impute', Imputer()),
                                   ('log', LogTransformer()),
                                   ('model',
                                    ARIMA(seasonal_order=(0, 1, 0, 12)))]). Check the list of available parameters with `estimator.get_params().keys()`.
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_35480/4174777882.py in <module>
      1 my_grid = {'imputer__method': ["drift", "bfill", "ffill"]}
----> 2 tuned_model = tune_model(my_custom_model, custom_grid=my_grid)

~\pycaret\pycaret\internal\utils.py in wrapper(*args, **kwargs)
    813                 if globals_d[name] is None:
    814                     raise ValueError(message)
--> 815             return func(*args, **kwargs)
    816 
    817         return wrapper

~\pycaret\pycaret\time_series.py in tune_model(estimator, fold, round, n_iter, custom_grid, optimize, custom_scorer, search_algorithm, choose_better, fit_kwargs, return_tuner, verbose, tuner_verbose, **kwargs)
    582     """
    583 
--> 584     return _CURRENT_EXPERIMENT.tune_model(
    585         estimator=estimator,
    586         fold=fold,

~\pycaret\pycaret\internal\pycaret_experiment\time_series_experiment.py in tune_model(self, estimator, fold, round, n_iter, custom_grid, optimize, custom_scorer, search_algorithm, choose_better, fit_kwargs, return_tuner, verbose, tuner_verbose, display, **kwargs)
   2085 
   2086             additional_scorer_kwargs = self.get_additional_scorer_kwargs()
-> 2087             model_grid.fit(
   2088                 y=data_y,
   2089                 X=data_X,

~\pycaret\pycaret\internal\pycaret_experiment\time_series_experiment.py in fit(self, y, X, additional_scorer_kwargs, **fit_params)
    474             return results
    475 
--> 476         self._run_search(evaluate_candidates)
    477 
    478         self.best_index_ = results["rank_test_%s" % refit_metric].argmin()

~\pycaret\pycaret\internal\pycaret_experiment\time_series_experiment.py in _run_search(self, evaluate_candidates)
    658     def _run_search(self, evaluate_candidates):
    659         """Search n_iter candidates from param_distributions"""
--> 660         return evaluate_candidates(
    661             ParameterSampler(
    662                 self.param_distributions, self.n_iter, random_state=self.random_state

~\pycaret\pycaret\internal\pycaret_experiment\time_series_experiment.py in evaluate_candidates(candidate_params)
    440                 n_jobs=self.n_jobs, verbose=self.verbose, pre_dispatch=self.pre_dispatch
    441             )
--> 442             out = parallel(
    443                 delayed(_fit_and_score)(
    444                     forecaster=clone(base_forecaster),

~\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\parallel.py in __call__(self, iterable)
   1052 
   1053             with self._backend.retrieval_context():
-> 1054                 self.retrieve()
   1055             # Make sure that we get a last message telling us we are done
   1056             elapsed_time = time.time() - self._start_time

~\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\parallel.py in retrieve(self)
    931             try:
    932                 if getattr(self._backend, 'supports_timeout', False):
--> 933                     self._output.extend(job.get(timeout=self.timeout))
    934                 else:
    935                     self._output.extend(job.get())

~\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

~\anaconda3\envs\pycaret-ts\lib\concurrent\futures\_base.py in result(self, timeout)
    442                     raise CancelledError()
    443                 elif self._state == FINISHED:
--> 444                     return self.__get_result()
    445                 else:
    446                     raise TimeoutError()

~\anaconda3\envs\pycaret-ts\lib\concurrent\futures\_base.py in __get_result(self)
    387         if self._exception:
    388             try:
--> 389                 raise self._exception
    390             finally:
    391                 # Break a reference cycle with the exception in self._exception

ValueError: Invalid parameter imputer for estimator TransformedTargetForecaster(steps=[('impute', Imputer()),
                                   ('log', LogTransformer()),
                                   ('model',
                                    ARIMA(seasonal_order=(0, 1, 0, 12)))]). Check the list of available parameters with `estimator.get_params().keys()`.

**Comment by ngupta23** [comment]
There is a typo in the grid. It should be `impute_method` instead of `imputer_method`.

```python
my_grid = {'impute__method': ["drift", "bfill", "ffill"]}
```

It works after that is fixed

![image](https://user-images.githubusercontent.com/33585645/143937287-0ae3f6ad-46a4-4773-8dff-9ef523345ca0.png)

**Comment by ngupta23** [comment]
But it does not look like it is taking the parameters in the final model correctly. Let me look into this.

![image](https://user-images.githubusercontent.com/33585645/143937951-8048b345-a45d-489f-bca7-4ed93f444741.png)

**Comment by ngupta23** [comment]
This is ok. `choose_better = True` by default, hence it picks the original model itself. This works fine. I will close this out. Feel free to reopen if needed.

```python
my_grid = {"impute__method": ["bfill", "ffill"]}
tuned_custom = exp.tune_model(custom_model, custom_grid=my_grid, choose_better=False)
```
