### ISSUE TITLE
issue intalling pycaret-ts-alpha in jupiter notebook

### ISSUE THREAD

**Issue by DanieleBaranzini** [pycaret/pycaret#1904]
I cannot run pycaret-ts-alpha following this (https://towardsdatascience.com/announcing-pycarets-new-time-series-module-b6e724d4636c):

events: 
I generated a virtual env, 
then pip installed pycaret-ts-alpha (but no pycaret due to expected conflicts according to Ali), 
but the following error is given when I run the following 
_________
ModuleNotFoundError Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_17724/228855616.py in <module>
      1 import pandas as pd
----> 2 from pycaret.datasets import get_data
      3 data = get_data('pycaret_downloads')
      4 data['Date'] = pd.to_datetime(data['Date'])
      5 data = data.groupby('Date').sum()

ModuleNotFoundError: No module named 'pycaret.datasets'
_________

in pip list I have 
pycaret-ts-alpha              3.0.0.dev1636735356

as suggested by tutorial I did not intall pycaret library in this virt env

Note:  if I run on Colab all is working but not in this  jupiter notebook

my env:
All on windows 7 - anaconda 1.9.12

**Comment by ngupta23** [comment]
Its hard to say the issue with your local environment. It is working ok for me in my local environment and in Colab in general so its not a package specific issue. Can you run in Colab for now?

Also, what happend when you do this?

```python
import pycaret
from pycaret.internal.pycaret_experiment import TimeSeriesExperiment
```

**Comment by DanieleBaranzini** [comment]
@ngupta23 Hi, and thanks for the support:

interesting as I got this (about o module named 'pycaret.internal.patches') following your suggestion:

> import pycaret
from pycaret.internal.pycaret_experiment import TimeSeriesExperiment

![image](https://user-images.githubusercontent.com/42250123/144178506-f7b29e30-92d8-41dc-825e-917f203a23fd.png)

my pip list below:


`Package                       Version
----------------------------- -------------------
alembic                       1.4.1Note: you may need to restart the kernel to use updated packages.

argon2-cffi                   21.1.0
async-generator               1.10
attrs                         21.2.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
bleach                        4.1.0
blis                          0.7.5
Boruta                        0.3
catalogue                     1.0.0
certifi                       2021.10.8
cffi                          1.15.0
charset-normalizer            2.0.7
click                         8.0.3
cloudpickle                   2.0.0
colorama                      0.4.4
colorlover                    0.3.0
cufflinks                     0.17.3
cycler                        0.11.0
cymem                         2.0.6
Cython                        0.29.14
databricks-cli                0.16.2
debugpy                       1.5.1
decorator                     5.1.0
defusedxml                    0.7.1
docker                        5.0.3
entrypoints                   0.3
Flask                         2.0.2
funcy                         1.16
future                        0.18.2
gensim                        3.8.3
gitdb                         4.0.9
GitPython                     3.1.24
greenlet                      1.1.2
htmlmin                       0.1.12
idna                          3.3
ImageHash                     4.2.1
imbalanced-learn              0.7.0
importlib-metadata            4.8.2
importlib-resources           5.4.0
ipykernel                     6.5.1
ipython                       7.30.0
ipython-genutils              0.2.0
ipywidgets                    7.6.5
itsdangerous                  2.0.1
jedi                          0.18.1
Jinja2                        3.0.3
joblib                        1.0.1
jsonschema                    4.2.1
jupyter-client                7.1.0
jupyter-core                  4.9.1
jupyterlab-pygments           0.1.2
jupyterlab-widgets            1.0.2
kiwisolver                    1.3.2
kmodes                        0.11.1
lightgbm                      3.3.1
llvmlite                      0.36.0
Mako                          1.1.5
MarkupSafe                    2.0.1
matplotlib                    3.4.3
matplotlib-inline             0.1.3
missingno                     0.5.0
mistune                       0.8.4
mlflow                        1.21.0
mlxtend                       0.19.0
multimethod                   1.6
murmurhash                    1.0.6
nbclient                      0.5.9
nbconvert                     6.3.0
nbformat                      5.1.3
nest-asyncio                  1.5.1
networkx                      2.6.3
nltk                          3.6.5
notebook                      6.4.6
numba                         0.53.1
numexpr                       2.7.3
numpy                         1.19.5
packaging                     21.3
pandas                        1.3.4
pandas-profiling              3.1.0
pandocfilters                 1.5.0
parso                         0.8.2
patsy                         0.5.2
phik                          0.12.0
pickleshare                   0.7.5
Pillow                        8.4.0
pip                           21.3.1
plac                          1.1.3
plotly                        5.3.1
pmdarima                      1.8.4
preshed                       3.0.6
prometheus-client             0.12.0
prometheus-flask-exporter     0.18.5
prompt-toolkit                3.0.23
protobuf                      3.19.1
pycaret-ts-alpha              3.0.0.dev1636735356
pycparser                     2.21
pydantic                      1.8.2
Pygments                      2.10.0
pyLDAvis                      3.2.2
pynndescent                   0.5.5
pyod                          0.9.5
pyparsing                     3.0.6
pyrsistent                    0.18.0
python-dateutil               2.8.2
python-editor                 1.0.4
pytz                          2021.3
PyWavelets                    1.2.0
pywin32                       227
pywinpty                      1.1.6
PyYAML                        5.4.1
pyzmq                         22.3.0
querystring-parser            1.2.4
regex                         2021.11.10
requests                      2.26.0
scikit-learn                  0.24.2
scikit-plot                   0.3.7
scipy                         1.5.4
seaborn                       0.11.2
Send2Trash                    1.8.0
setuptools                    59.4.0
six                           1.16.0
sktime                        0.8.1
smart-open                    5.2.1
smmap                         5.0.0
spacy                         2.3.7
SQLAlchemy                    1.4.27
sqlparse                      0.4.2
srsly                         1.0.5
statsmodels                   0.12.1
tabulate                      0.8.9
tangled-up-in-unicode         0.1.0
tbats                         1.1.0
tenacity                      8.0.1
terminado                     0.12.1
testpath                      0.5.0
textblob                      0.17.1
thinc                         7.4.5
threadpoolctl                 3.0.0
tornado                       6.1
tqdm                          4.62.3
traitlets                     5.1.1
typing_extensions             4.0.0
umap-learn                    0.5.2
urllib3                       1.26.7
visions                       0.7.4
waitress                      2.0.0
wasabi                        0.8.2
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              1.2.1
Werkzeug                      2.0.2
wheel                         0.37.0
widgetsnbextension            3.5.2
wordcloud                     1.8.1
yellowbrick                   1.3.post1
zipp                          3.6.0`

**Comment by ngupta23** [comment]
Hey, what does this mean? Did you do that?

> alembic 1.4.1Note: you may need to restart the kernel to use updated packages.

**Comment by ngupta23** [comment]
@DanieleBaranzini I also released an updated pycaret-ts-alpha version yesterday. I did not change anything regarding the installation but would be worth a try. Also, the recommendation above to try and restart the kernel might help. 

Let me know how it goes.

**Comment by DanieleBaranzini** [comment]
@ngupta23  SOLVED! the pycaret time series module is now up an running even in my jupiter ntbk as well:   --> the issue was  my windows 7 (sic!) configuration...there was a nasty dll (Api-ms-win-core-winrt-l1-1-0.dll) that I had to bring back to life and port it into the virtual env were I was doing my pycaret tests as you suggested...in fact there was nothing erroneous in pycaret but actually a corrupted dll in my window configuration.

I am leading a European project on energy management forecasting and pycaret is in full application...I will keep you and Ali informed if you like....the pycaret approach seems to maintain a required high velocity to semi-automatically refresh/refit the time series model/s and serve on a kubernetes enviroment ...actually we are going with Kubeflow as MLOps

a big thank you to you and one final question: is there any Kubeflow demo (even alpha version) served by pycaret at the moment? I know and fully tested mlflow with pycaret but nothing with Kube.... 

Daniele

**Comment by ngupta23** [comment]
Glad you like it.

I am not sure about Kuberflow.  @moezali1 - does that work with `pycaret`?

**Comment by ngupta23** [comment]
I have opened a separate issue for Kubeflow. We will go ahead and close this one since it is resolved.
