### ISSUE TITLE
add "grid_interval" as a parameter in optimize_threshold method

### ISSUE THREAD

**Issue by wolfryu** [pycaret/pycaret#1910]
**Is your feature request related to a problem? Please describe.**
When using optimize_threshold method, calculate_loss method will run 10000 times to find best threshold. Because gird interval is 0.0001. It will cost a lot of time to calculate threshod, however, sometimes we do not need so small gird search interval.
~~~
 grid = np.arange(0, 1, 0.0001) 
~~~

**Describe the solution you'd like**
add "grid_interval" as a parameter in optimize_threshold method
change
~~~
def optimize_threshold(
    estimator,
    true_positive: int = 0,
    true_negative: int = 0,
    false_positive: int = 0,
    false_negative: int = 0,
):
~~~
into:
~~~
def optimize_threshold(
    estimator,
    true_positive: int = 0,
    true_negative: int = 0,
    false_positive: int = 0,
    false_negative: int = 0,
    gird_interval = 0.0001,
):
~~~
~~~
grid = np.arange(0, 1, gird_interval )
~~~

Thank you!

**Comment by moezali1** [comment]
@wolfryu Would you like to work on this issue?

**Comment by wolfryu** [comment]
@moezali1 
Sure! I am glad to contribute to this great project! 
Is there any instruction of contribution on Pycaret? Or just make a contribution the same as other open source projects? (such as this: https://www.dataschool.io/how-to-contribute-on-github/)

**Comment by moezali1** [comment]
@wolfryu Please submit the PR explaining what change is made and why. Also, please ensure you update the test cases for this (if any). Thanks

**Comment by wolfryu** [comment]
Thank you!
