### ISSUE TITLE
Change name for INPI metric

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#1914]
Change INPI to PICOV (Prediction Interval Coverage)

Refer this feedback from [LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:6872550071746015233?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6872550071746015233%2C6872597586633621504%29&replyUrn=urn%3Ali%3Acomment%3A%28activity%3A6872550071746015233%2C6872636030349012992%29) from @valeman

**Comment by moezali1** [comment]
In statistics, the coverage probability of a technique for calculating a confidence interval is the proportion of the time that the interval contains the true value of interest.[1] For example, suppose our interest is in the mean number of months that people with a particular type of cancer remain in remission following successful treatment with chemotherapy. The confidence interval aims to contain the unknown mean remission duration with a given probability. This is the "confidence level" or "confidence coefficient" of the constructed interval which is effectively the "nominal coverage probability" of the procedure for constructing confidence intervals. The "nominal coverage probability" is often set at 0.95. The coverage probability is the actual probability that the interval contains the true mean remission duration in this example.

https://en.wikipedia.org/wiki/Coverage_probability

**Comment by ngupta23** [comment]
@moezali1  @valeman So should we shorthand it "COVPROB" then?

**Comment by moezali1** [comment]
@ngupta23 I have submitted this to Prof. Anton for his suggestion. Will put the response here!

**Comment by ngupta23** [comment]
Based on the discussion on 8th Jan 2022, we will change this to "COV_PROB".

**Comment by sayantan1410** [comment]
@ngupta23 ,I think I will be able to do it.

**Comment by valeman** [comment]
So for late reply folks, Cov_Prob sounds much better.

**Comment by ngupta23** [comment]
To Test

```python
from pycaret.datasets import get_data
from pycaret.internal.pycaret_experiment import TimeSeriesExperiment

data = get_data("airline")
exp = TimeSeriesExperiment()
exp.setup(data=data, session_id=42, fh=12, verbose=True, enforce_pi=True)

# get best model baased on coveage probability
best = exp.compare_models(sort="cov_prob")

# Test Predictions
y_pred = exp.predict_model(best)
```

**Comment by ngupta23** [comment]
On further investigation, the word "coverage" is more generally seen. e.g. This is what it is called in Prophet and I have seen it elsewhere as well. I would recommend changing it to "coverage" to match what is generally used in the industry. Not a big change, but better to be consistent with the general forecasting population.

**Comment by moezali1** [comment]
I agree with this. coverage looks more appropriate.
