### ISSUE TITLE
Create a geographic heat map using the results

### ISSUE THREAD

**Issue by azharirfan** [pycaret/pycaret#192]
There are instances where the dataset contains Postal Codes, City Names or other location identifiers. It would be great if pycaret can allow creating a geographic heatmap (using these location identifiers) and the results of modelling. Eg, if the data set has Canadian provinces and i run regression to forecast sales volume, then a geographic map in the end to show (average or actual) sales volume by province would be great to have. 

Some resources i found on the geographic heatmaps are provided below:
- https://geopandas.org/mapping.html
- https://medium.com/@m_vemuri/create-a-geographic-heat-map-of-the-city-of-toronto-in-python-cd2ae0f8be55 
- https://towardsdatascience.com/lets-make-a-map-using-geopandas-pandas-and-matplotlib-to-make-a-chloropleth-map-dddc31c1983d
- https://gist.github.com/samik-saha/c8c565e5bf4d2d203c210d90573141ef

**Comment by pycaret** [comment]
@azharirfan Marking as enhancement. (low priority)
