### ISSUE TITLE
time series - add Root Mean Squared Scaled Error for time series

### ISSUE THREAD

**Issue by ltsaprounis** [pycaret/pycaret#1923]
Root Mean Squared Scaled Error is a very popular time series metric. Similarly to MASE (already supported) it is scaled by the error of a one-step Naive forecaster in the in-sample set:

![](https://raw.githubusercontent.com/ltsaprounis/dsf-ts-forecasting/0ebdcc637f9971f7c7f6751e436def9f8bbaad4e/notebooks/images/02_rmsse.png)

It's also a very popular scaled metric for intermittent time series due to it's properties for optimising for the mean (MASE will optimise for the median) and it won't be infinity for cases where the actuals are zeros as in the percentage metrics.

I think it will be a valuable addition to the metrics for time series forecasting.

**Comment by ngupta23** [comment]
Hi @ltsaprounis , Thanks for the discussion the other day and for picking this up. I have assigned this to you.

This would be the location to start looking to add new metrics: https://github.com/pycaret/pycaret/blob/time_series/pycaret/containers/metrics/time_series.py
