### ISSUE TITLE
setup() in clustering doesn't support passing silent=True

### ISSUE THREAD

**Issue by agrawalparth08** [pycaret/pycaret#193]
from pycaret.clustering import *
data_setup = setup(df, normalize = True, silent=True, session_id = 42,verbose=False)

`_TypeError: setup() got an unexpected keyword argument 'silent'_`

**Comment by agrawalparth08** [comment]
The workaround is to have supervised=True and having one column at least as supervised_target="".
Can this be fixed to similar thing like in classification by passing silent variable in setup?

**Comment by pycaret** [comment]
@agrawalparth08 Thanks for pointing out. This is a bug and will be fixed in next release.
