### ISSUE TITLE
Normalized confusion matrix

### ISSUE THREAD

**Issue by trungtly** [pycaret/pycaret#1939]
**Is your feature request related to a problem? Please describe.**
Currently the `plot_model()` function (classification) plots the confusion matrix with absolute numbers. It would be great to have the normalized confusion as well.

**Describe the solution you'd like**
Just need to normalize the current confusion matrix to show values between 0 and 1.

**Describe alternatives you've considered**

**Additional context**

**Comment by moezali1** [comment]
@trungtly Thanks for suggesting. We are working on this and this functionality will be available in the next release `2.3.6`.

**Comment by moezali1** [comment]
Done
