### ISSUE TITLE
setup(), providing options for train/test split

### ISSUE THREAD

**Issue by s-bhatia** [pycaret/pycaret#194]
I cannot seem to figure out how to avoid data shuffle during setup.

I intend to provide first 70% rows for training and remaining 30% for testing without re-arranging the order.
Also, would be great to have stratified split.

**Comment by pycaret** [comment]
@s-bhatia While this is not possible in this version. In next release there is a parameter of data_split_shuffle in setup() function that you can turn off by changing it to False.

I will keep this open until next release and will close the issue upon release.

Thanks.

**Comment by pycaret** [comment]
@s-bhatia 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
