### ISSUE TITLE
parallel back-end

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1943]
At the moment scikit-learn uses `loky` backend to single node parallel processing. There are 3-4 other options for backend like `multithreading` or `ray`. We should create a new parameter in setup for the user to set that backend. 

We can set the backend that gets reflected in the `n_jobs` parameter by using a function from `sklearn.utils` module.

Hopefully its not a big change.

**Comment by Yard1** [comment]
Duplicate
