### ISSUE TITLE
NLP tutorial #2 Extrinsic Classifier- "KeyError: "['PendStatus'] not found in axis"

### ISSUE THREAD

**Issue by dcohron** [pycaret/pycaret#196]
Working through the last model in the NLP tutorial #2 using my own dataframe with 1 column of type string used in the lda model and 1 column with label, also of type string.  The tune_model function runs for a little bit and I see "100 topics", "200 topics", "300 topics"...  However, on "Evaluating Classifier with 2 topics" get error "KeyError: "['PendStatus'] not found in axis" with PendStatus the name of the column in the data frame assigned as "data" in the model setup and identified as "supervised_target" parameter in the call to tune_model.

**Comment by pycaret** [comment]
@dcohron Any chances you can share sample data?

**Comment by dcohron** [comment]
Unfortunately cannot share data as company a regulated entity (healthcare).  However, I believe that I found the problem in that I was using labels as data type string ("good"/"bad").  When I changed the labels to 0 and 1 in building the binary classifier, this seemed to solve the issue.  My fault, but did not notice this in the documentation.  

If it is the case that labels for the classifier must be integers, then please close this request.

I do thank you for your quick response.  Great work on the tool.  Very helpful and very, very useful.  Thank you for your efforts.

**Comment by pycaret** [comment]
@dcohron Thanks. I thought I have handled the label encoding but apparently not. Will look at this as soon as I can. The expected outcome should be, it should work even with categorical labels such as "good / bad" instead of 1/0.

Thanks for reporting.

**Comment by pycaret** [comment]
@dcohron Can you please re-test this and confirm if you still get the issue in `2.1.2` release. Thanks

**Comment by gm039** [comment]
Hi,

I am facing an issue in re-plotting the AUC, Confusion matrix etc with the loaded model (Trained on 80%) on the test data (20 %).
I am able to load the model successfully predict the performance metric using it as well. 

![image](https://user-images.githubusercontent.com/50217085/96027648-2a877a80-0e26-11eb-996e-2b398afaa35f.png)

But when I try to plot the model.

plot_model(saved_mdl, plot = 'confusion_matrix'). I get following error.


KeyError                                  Traceback (most recent call last)
<ipython-input-20-a2dbcbb13dae> in <module>()
----> 1 plot_model(saved_mdl, plot = 'confusion_matrix')

12 frames
/usr/local/lib/python3.6/dist-packages/pycaret/classification.py in plot_model(estimator, plot, scale, save, verbose, system)
   7728         progress.value += 1
   7729         visualizer = PrecisionRecallCurve(model, random_state=seed)
-> 7730         visualizer.fig.set_dpi(visualizer.fig.dpi * scale)
   7731         logger.info("Fitting Model")
   7732         visualizer.fit(Xtrain, ytrain)

/usr/local/lib/python3.6/dist-packages/yellowbrick/classifier/base.py in fit(self, X, y, **kwargs)
    172         """
    173         # Super fits the wrapped estimator
--> 174         super(ClassificationScoreVisualizer, self).fit(X, y, **kwargs)
    175 
    176         # Extract the classes and the class counts from the target

/usr/local/lib/python3.6/dist-packages/yellowbrick/base.py in fit(self, X, y, **kwargs)
    357         """
    358         if not check_fitted(self.estimator, is_fitted_by=self.is_fitted):
--> 359             self.estimator.fit(X, y, **kwargs)
    360         return self
    361 

/usr/local/lib/python3.6/dist-packages/sklearn/pipeline.py in fit(self, X, y, **fit_params)
    328         """
    329         fit_params_steps = self._check_fit_params(**fit_params)
--> 330         Xt = self._fit(X, y, **fit_params_steps)
    331         with _print_elapsed_time('Pipeline',
    332                                  self._log_message(len(self.steps) - 1)):

/usr/local/lib/python3.6/dist-packages/sklearn/pipeline.py in _fit(self, X, y, **fit_params_steps)
    294                 message_clsname='Pipeline',
    295                 message=self._log_message(step_idx),
--> 296                 **fit_params_steps[name])
    297             # Replace the transformer of the step with the fitted
    298             # transformer. This is necessary when loading the transformer

/usr/local/lib/python3.6/dist-packages/joblib/memory.py in __call__(self, *args, **kwargs)
    350 
    351     def __call__(self, *args, **kwargs):
--> 352         return self.func(*args, **kwargs)
    353 
    354     def call_and_shelve(self, *args, **kwargs):

/usr/local/lib/python3.6/dist-packages/sklearn/pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    738     with _print_elapsed_time(message_clsname, message):
    739         if hasattr(transformer, 'fit_transform'):
--> 740             res = transformer.fit_transform(X, y, **fit_params)
    741         else:
    742             res = transformer.fit(X, y, **fit_params).transform(X)

/usr/local/lib/python3.6/dist-packages/pycaret/preprocess.py in fit_transform(self, dataset, y)
    329     data= dataset.copy()
    330     # since this is for training , we dont nees any transformation since it has already been transformed in fit
--> 331     data = self.fit(data)
    332 
    333     # additionally we just need to treat the target variable

/usr/local/lib/python3.6/dist-packages/pycaret/preprocess.py in fit(self, dataset, y)
    177     #for time & dates
    178     #self.drop_time = [] # for now we are deleting time columns
--> 179     for i in data.drop(self.target,axis=1).columns:
    180       # we are going to check every first row of every column and see if it is a date
    181       match = datefinder.find_dates(data[i].values[0]) # to get the first value

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py in drop(self, labels, axis, index, columns, level, inplace, errors)
   4167             level=level,
   4168             inplace=inplace,
-> 4169             errors=errors,
   4170         )
   4171 

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py in drop(self, labels, axis, index, columns, level, inplace, errors)
   3882         for axis, labels in axes.items():
   3883             if labels is not None:
-> 3884                 obj = obj._drop_axis(labels, axis, level=level, errors=errors)
   3885 
   3886         if inplace:

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py in _drop_axis(self, labels, axis, level, errors)
   3916                 new_axis = axis.drop(labels, level=level, errors=errors)
   3917             else:
-> 3918                 new_axis = axis.drop(labels, errors=errors)
   3919             result = self.reindex(**{axis_name: new_axis})
   3920 

/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py in drop(self, labels, errors)
   5276         if mask.any():
   5277             if errors != "ignore":
-> 5278                 raise KeyError(f"{labels[mask]} not found in axis")
   5279             indexer = indexer[~mask]
   5280         return self.delete(indexer)

KeyError: "['TARGET'] not found in axis"

**Comment by moezali1** [comment]
We are no more supporting the `nlp` and `arules` module in PyCaret due to lack to resources. Closing the issue now.
