### ISSUE TITLE
Message The Kernel appears to have died - Clustering

### ISSUE THREAD

**Issue by ManuelBanza** [pycaret/pycaret#197]
Hi,

I tried to copy the tutorial for making clustering analysis and when I use a dataset like "mice" it works just fine, but then I used my own dataset with 160k rows and when I do the setup and validate the datatypes it just takes too long to run and then this message shows up. 

<img width="709" alt="Captura de ecrã 2020-06-04, às 10 12 38" src="https://user-images.githubusercontent.com/53525022/83738297-07fd7d80-a64c-11ea-8433-7a482dda163b.png">

Any help?
Thanks!

**Comment by ManuelBanza** [comment]
Hi,

I am having this problem with other models like classification. I already install everything from scratch. Can anyone help me?
Thanks

**Comment by pycaret** [comment]
@ManuelBanza Hi Manuel which environment are you using it in? Is it Kaggle Kernel?

**Comment by ManuelBanza** [comment]
hi @pycaret ,
I am using jupyter notebook. I already create two conda environments but the problem remains.
Thanks

**Comment by shadowWalker404** [comment]
hi @pycaret，
I have the same problem. I load the juice data from pycaret.dataset by get_data('juice').
and when I setup,the kernel will restart.   (jupyter notebook)

**Comment by ksharpeypd** [comment]
Hi,

I have the same problem following simple installation guide and tutorial, on an ubuntu server with p3.7.

when I get to classification the kernel dies

**Comment by shadowWalker404** [comment]
> Hi,
> 
> I have the same problem following simple installation guide and tutorial, on an ubuntu server with p3.7.
> 
> when I get to classification the kernel dies

1

**Comment by shadowWalker404** [comment]
> hi @pycaret，
> I have the same problem. I load the juice data from pycaret.dataset by get_data('juice').
> and when I setup,the kernel will restart. (jupyter notebook)

I solve this problem. You can find the logs which is same path with your code and it will tell you which model have problem.I spent a day to adjust my lightgbm and xgboost

**Comment by pycaret** [comment]
@ManuelBanza We have made some changes in `pycaret==2.2` that should fix this issue. Can you please try after updating the version and let us know if the issue persists?

For now, I am closing this issue. Please feel free to open another issue, if you would like.

**Comment by Scottwrench** [comment]
I am using pycaret 2.3.1 and getting the same problem in the regression module.

**Comment by profbiyi** [comment]
I get this error every time I try to use pycaret for anything. it's frustrating

**Comment by shivajigit** [comment]
It seems a memory issue. It got resolved by reducing the dataset ..say  
df=df.head(10000)
run setup() and compare_models() again
