### ISSUE TITLE
Integrate sklearn-intelex

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#1971]
Integrate sklearn-intelex

It is an intel driver for scikit-learn acceleration. There are few algorithms supported: https://intel.github.io/scikit-learn-intelex/algorithms.html

Results are awesome:

Original: 

![image](https://user-images.githubusercontent.com/54699234/146644694-36b11dfa-b48e-4da0-b43f-2d679c7303e1.png)

With Intel Driver:
![image](https://user-images.githubusercontent.com/54699234/146644703-a118867c-36d5-4f9b-86f9-7cb0b2fbc0a5.png)

**Comment by Yard1** [comment]
Honestly, is it worth doing that on our side? One simply needs to do `patch_sklearn()` at the very start of the script, before importing pycaret, and nothing else is needed

**Comment by moezali1** [comment]
It's such a low-hanging fruit that I cannot resist and I think it will just create more awareness around intel drivers for scikit-learn. I think there is no harm in adding a parameter in setup, something like `use_intel_accelerator` or `use_intelex`

**Comment by moezali1** [comment]
Also, I tried that just running `patch_sklearn` at the beginning of Jupyter Notebook doesn't work. Unless you don't import explicitly from `sklearnex` example: `from sklearnex.neighbors import KNeighborsClassifier`, you do not get performance gain. 

When `patch_sklearn` is used after setup and before `create_model`, it doesn't generate any error but accelerator just doesn't work. If you want to see the error, this is how you can produce it:

```
from pycaret.datasets import get_data
data = get_data('poker')

from sklearnex import patch_sklearn
patch_sklearn()

from pycaret.classification import *
s = setup(data, target = 'CLASS', session_id = 123)
```
ValueError                                Traceback (most recent call last)
<ipython-input-3-01e726776a0e> in <module>
      1 from pycaret.classification import *
----> 2 s = setup(data, target = 'CLASS', session_id = 123)

~\pycaret\pycaret\classification.py in setup(data, target, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs)
    579         log_plots = ["auc", "confusion_matrix", "feature"]
    580 
--> 581     return pycaret.internal.tabular.setup(
    582         ml_usecase="classification",
    583         available_plots=available_plots,

~\pycaret\pycaret\internal\tabular.py in setup(data, target, ml_usecase, available_plots, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, transform_target, transform_target_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs, display)
   1349             test_data = pd.concat([X_test, y_test], axis=1)
   1350 
-> 1351         train_data = prep_pipe.fit_transform(train_data)
   1352         # workaround to also transform target
   1353         dtypes.final_training_columns.append(target)

~\anaconda3\envs\pycaret-dev\lib\site-packages\sklearn\pipeline.py in fit_transform(self, X, y, **fit_params)
    365         """
    366         fit_params_steps = self._check_fit_params(**fit_params)
--> 367         Xt = self._fit(X, y, **fit_params_steps)
    368 
    369         last_step = self._final_estimator

~\anaconda3\envs\pycaret-dev\lib\site-packages\sklearn\pipeline.py in _fit(self, X, y, **fit_params_steps)
    290                 cloned_transformer = clone(transformer)
    291             # Fit or load from cache the current transformer
--> 292             X, fitted_transformer = fit_transform_one_cached(
    293                 cloned_transformer, X, y, None,
    294                 message_clsname='Pipeline',

~\anaconda3\envs\pycaret-dev\lib\site-packages\joblib\memory.py in __call__(self, *args, **kwargs)
    347 
    348     def __call__(self, *args, **kwargs):
--> 349         return self.func(*args, **kwargs)
    350 
    351     def call_and_shelve(self, *args, **kwargs):

~\anaconda3\envs\pycaret-dev\lib\site-packages\sklearn\pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    738     with _print_elapsed_time(message_clsname, message):
    739         if hasattr(transformer, 'fit_transform'):
--> 740             res = transformer.fit_transform(X, y, **fit_params)
    741         else:
    742             res = transformer.fit(X, y, **fit_params).transform(X)

~\pycaret\pycaret\internal\preprocess.py in fit_transform(self, dataset, y)
    419 
    420         # since this is for training , we dont nees any transformation since it has already been transformed in fit
--> 421         data = self.fit(data)
    422 
    423         # additionally we just need to treat the target variable

~\pycaret\pycaret\internal\preprocess.py in fit(self, dataset, y)
    218         for i in data.select_dtypes(include=["int64"]).columns:
    219             if i != self.target:
--> 220                 if data[i].nunique() <= 20:  # hard coded
    221                     data[i] = data[i].apply(str_if_not_null)
    222                 else:

~\anaconda3\envs\pycaret-dev\lib\site-packages\pandas\core\generic.py in __nonzero__(self)
   1327 
   1328     def __nonzero__(self):
-> 1329         raise ValueError(
   1330             f"The truth value of a {type(self).__name__} is ambiguous. "
   1331             "Use a.empty, a.bool(), a.item(), a.any() or a.all()."

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

When you do this instead:

```
from pycaret.datasets import get_data
data = get_data('poker')

from pycaret.classification import *
s = setup(data, target = 'CLASS', session_id = 123)

from sklearnex import patch_sklearn
patch_sklearn()

knn = create_model('knn')
```
You don't get any acceleration and the model returned is a normal sklearn estimator.

Only this way works:

```
from pycaret.datasets import get_data
data = get_data('poker')

from pycaret.classification import *
s = setup(data, target = 'CLASS', session_id = 123)

from sklearnex.neighbors import KNeighborsClassifier
knn_intelex = KNeighborsClassifier()
knn = create_model(knn_intelex)
```
The model returned here is a `daal4py` patched estimator. complete name: `daal4py.sklearn.neighbors._classification.KNeighborsClassifier`

![image](https://user-images.githubusercontent.com/54699234/146939629-a142280e-1678-4d6c-be2f-1e909ab704f0.png)

The runtime of knn on `poker` dataset without intel acceleration is around 9 min 30 sec and with acceleration is 12 seconds only.

Python 3.8.8 (Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]

**Comment by moezali1** [comment]
@Yard1 I am thinking to handle it through the model container. What do you think?

**Comment by agorshk** [comment]
Hi @moezali1 , I'm one of sklearn-intelex maintainers. I appreciate that you are interesting of it, I'm happy to help you with the activity.

You mentioned that you have some issues with kNN importing, we are investigating it. I also open for any discussion related with sklearn-intelex project, if you share challenges ahead of your project we can discuss and probably find a solution.

**Comment by diegovalenzuelaiturra** [comment]
`scikit-learn-intelex` is not available for apple silicon (M1) macs and it is a dependency of `pycaret[full]`, which breaks the installation.

**Comment by napetrov** [comment]
> > `scikit-learn-intelex` is not available for apple silicon (M1) macs and it is a dependency of `pycaret[full]`, which breaks the installation.
> 
> @Yard1 @moezali1 Should we remove it from requirements-optional.txt in that case? Users can install it manually if they want.
> 
> https://github.com/pycaret/pycaret/blob/6678c518a8522c28c80d34fa38a77df2763faa1d/requirements-optional.txt#L17

I would say that defining requirements for platform would be better option - using platform.machine and pin in to x86 only
