### ISSUE TITLE
models() not working

### ISSUE THREAD

**Issue by sumeshmr** [pycaret/pycaret#1973]
NameError: name 'logger' is not defined
Traceback:
File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pycaret/regression.py", line 2098, in models
    type=type, internal=internal, raise_errors=raise_errors
File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 9582, in models
    logger.info(f"gpu_param set to {gpu_param}")

**Comment by ngupta23** [comment]
Please provide complete code (reproducible example) to reproduce the error. You can find more details here: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by sumeshmr** [comment]
`from pycaret.regression import *
models()`

pycaret version 2.3.5

**Comment by moezali1** [comment]
@sumeshmr You must execute `setup` first to see the models through `models()` function. This is because when you initialize `setup`, depending on whether you are using GPU or not, specific estimators are imported.

```
from pycaret.datasets import get_data
data = get_data('boston')

from pycaret.regression import *
s = setup(data, target = 'medv')

models()
```

Hope this helps.

**Comment by sumeshmr** [comment]
Hello,

This behavior looks weird. I wanted to list all the regression algorithms supported, now this is not possible without a data set and calling setup method?
