### ISSUE TITLE
[BUG] version 2.2.0 instead of 2.3.5 being installed after running pip install pycaret

### ISSUE THREAD

**Issue by rjuarezp** [pycaret/pycaret#1976]
**Isue**

I just create a new virtual environment (```python -m venv venv``` with python 3.9.9) and run ```pip install pycaret```

**To Reproduce**

```python
pip install pycaret
```

**After that, I just run**
```python
import pycaret
print(pycaret.__version__)
```

**and I get version 2.2.0!!!! Do you know why I am not getting the version 2.3.5? Thanks for the help!**

The version 2.2.0 is having the **AttributeError: 'Make_Time_Features' object has no attribute 'list of features'** issue and I cannot use pycaret. That's why I want to upgrade to 2.3.5 to see whether this issue has already been solved.

**Comment by msincan** [comment]
This may be a workaround but, have you considered trying `pip install pycaret==2.3.5`

**Comment by moezali1** [comment]
@rjuarezp It seems like you have installed unstable and stable release in the same environment. Maybe thats why. 

I suggest you either try it in a fresh conda environment or do this:

```
pip uninstall -y pycaret
pip install pycaret
```

Hope this helps.
