### ISSUE TITLE
[BUG] Colab error , load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by atwahsz** [pycaret/pycaret#1988]
![img](https://github.com/atwahsz/misc_graphics/blob/main/Screenshot%20from%202021-12-23%2010-34-43.png?raw=true)
as seen in the image above

**Comment by BassCoder2808** [comment]
Hi @atwahsz , the error is not related to the pycaret library it is actually related to the version of pyyaml which google colab uses.
The latest version of pyyaml is 6.0 which is not compatible with the current way Google Colab imports packages. This can also be seen through the requirements.txt file where it has been specifically mentioned about the pyyaml version. It should be less than 6.0.
The easiest and simplest solution would be to downgrade the pyyaml version.
So just downgrade pyyaml version to 5.4.1 which is compatible with the current way Google Colab imports and It will solve your error. 
Use this command to downgrade pyyaml 
```
!pip install pyyaml==5.4.1
```

**Comment by moezali1** [comment]
@BassCoder2808 +1.

In the next release, we will pin the `payyaml` version for Colab. However, in the meantime, you will have to do as @BassCoder2808 suggested. 

Alternatively, you can install pycaret's master branch from GitHub directly:

```
!pip install git+https://www.github.com/pycaret/pycaret@master
```

Thanks
