### ISSUE TITLE
Anaconda 3

### ISSUE THREAD

**Issue by saurabh1157** [pycaret/pycaret#199]
While installation of anaconda 3 it gets stuck at setting up the package cache. Any help is truly appreciated.

**Comment by pycaret** [comment]
@saurabh1157 Can you please provide more information. Error log message or pictures might help.

**Comment by saurabh1157** [comment]
Hello,

This is the screen print for your perusal.Please provide your
expert assistance.

Best regards,
[image: image.png]
Saurabh Olkar

**Comment by incoming-virus** [comment]
![Annotation 2020-06-08 224809](https://user-images.githubusercontent.com/40635351/84083825-41324680-a9da-11ea-903d-04fef4e7babf.png)
 My package cache isnt setting up properly

**Comment by saurabh1157** [comment]
Hello,

Can you please provide assistance on the screen print provided. Truly
appreciated.

Best regards,
Saurabh Olkar

**Comment by incoming-virus** [comment]
Restart the installation process again. The already installed packages will be skipped

**Comment by saurabh1157** [comment]
Hello,

Thank you for your response.

I did install miniconda and it is working fine now. My apologies for
missing the update in the forum.

Best regards,
Saurabh Olkar
