### ISSUE TITLE
[BUG] `plot_kwargs` argument of `plot_model()` not working in regression

### ISSUE THREAD

**Issue by astenuz** [pycaret/pycaret#1996]
**Describe the bug**

When trying to pass `plot_kwargs` to the `plot_model()` method in the regression submodule, the argument is ignored. For example, when using the type of plot 'learning' and wanting to change the scoring function to other than r2 (eg. `scoring=‘neg_median_absolute_error’`)

**To Reproduce**

```python
# Importing dataset
from pycaret.datasets import get_data
boston = get_data('boston')

# Importing module and initializing setup
from pycaret.regression import *
reg1 = setup(data = boston, target = 'medv')

# creating a model
lr = create_model('lr')

# plotting a model
plot_model(lr, plot='learning', plot_kwargs=dict(scoring='neg_median_absolute_error'))
```

Output:
![image](https://user-images.githubusercontent.com/4689127/147496761-5d66181a-7470-46e0-bb49-ceea29de9f46.png)

**Expected behavior**
This code still generates the learning plot with the r2 scoring instead of -mae. One would expect that changing the scoring shows a different plot.

**Additional context**

This happens because the definition inside regression of plot models does not pass the `plot_kwargs` argument to the internal function. 

https://github.com/pycaret/pycaret/blob/02460744f8e844c2fccd97a8fbedfb23302df6ae/pycaret/regression.py#L1507-L1519

**Versions**
'2.3.5' installed from nightly with commit 0246074

</details>

**Comment by moezali1** [comment]
@astenuz Thanks for reporting. I will fix this.

**Comment by moezali1** [comment]
@astenuz Just fixed this on `master`. https://github.com/pycaret/pycaret/commit/7739023fc19d69974376002a01bec8c9f5693721

Can you please test and confirm if the issue is resolved now?

**Comment by moezali1** [comment]
Self-tested. Issue closed now.

**Comment by astenuz** [comment]
Thanks! just saw this. Its working correctly now 👌
