### ISSUE TITLE
[BUG] import error after installation of pycaret[full] on Google Colab

### ISSUE THREAD

**Issue by teddylee777** [pycaret/pycaret#1998]
**Describe the bug**
I am testing on a Google Colab.
After I install pycaret[full] on Google Colab and then when I try to import either
classfication/regression modules I got following error

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-2975aae603d7> in <module>()
----> 1 from pycaret.classification import *

11 frames
/usr/local/lib/python3.7/dist-packages/distributed/config.py in <module>()
     18 
     19 with open(fn) as f:
---> 20     defaults = yaml.load(f)
     21 
     22 dask.config.update_defaults(defaults)

TypeError: load() missing 1 required positional argument: 'Loader'

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-d648e8a90e30> in <module>()
----> 1 from pycaret.regression import *

11 frames
/usr/local/lib/python3.7/dist-packages/distributed/config.py in <module>()
     18 
     19 with open(fn) as f:
---> 20     defaults = yaml.load(f)
     21 
     22 dask.config.update_defaults(defaults)

TypeError: load() missing 1 required positional argument: 'Loader'

**To Reproduce**
```python
# installation
!pip install pycaret[full]
```

```python
from pycaret.regression import * 
from pycaret.classification import * 
```

**Expected behavior**
does not produce any error on import

**Additional context**
I've also tried additional installation

`!pip install pyyaml==5.4.1`

but it didn't work

**Versions**
<details>
pycaret version : 2.3.5
</details>

Thanks in advance

**Comment by moezali1** [comment]
@teddylee777 

You can solve this problem by running this command after installing pycaret:

You have to click on the `RESTART RUNTIME` button for the changes to take effect on Colab.

```
!pip uninstall -y pyyaml
!pip install pyyaml==5.4.1
```
