### ISSUE TITLE
Python Support max 3.8?[DOC]

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#2007]
Anaconda (normal download) now is with python 3.9, and installation of pyycaret its impossible.

It's very hard associate pycaret only supports python 3.8.x. So documentation should said "Pycaret only supports <= python 3.8.x"

or, when try install pycaret via ex: pip... shoud get message like "only supports python 3.8..."

I think people make confusion about error because software not showing best error messages.

Its only my opinion..

**Comment by moezali1** [comment]
Thanks for the suggestion @celestinoxp. It is already taken care of in the new documentation .. on the way.

![image](https://user-images.githubusercontent.com/54699234/148148655-0d1a119c-0c75-4c08-80b4-7dea77f7463e.png)
