### ISSUE TITLE
Compatibility guarantees for loading models saved with different version of PyCaret / scikit-learn?

### ISSUE THREAD

**Issue by kennysong** [pycaret/pycaret#2016]
PyCaret models are saved in (joblib's) pickle files. Pickle files import class definition code at load time, so it could cause compatibility issues if I save a model in PyCaret 2.2 and try to load it in PyCaret 2.3.

Additionally, PyCaret models seem to use scikit-learn models [under the hood](https://github.com/pycaret/pycaret/blob/06f340d26b712abb5cb68368e23573f95b6917b7/pycaret/containers/models/classification.py#L230). However, scikit-learn pickles [are not compatible across different versions of scikit-learn](https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations). 

Does PyCaret provide any compatibility guarantees for pickled models? (For example, pinning scikit-learn==0.23.2 and maintaining backward compatibility in the PyCaret class layers.)

If not, is there any way to determine what version of PyCaret and scikit-learn a pickled model was generated with, so I can make sure to use the right environment at load time?

**Comment by liwii** [comment]
It seems that in PyCaret 2.3 the version of scikit-learn is fixed to `0.23.2`,
https://github.com/pycaret/pycaret/blob/e826133202c68ca8b3a37ffc2450e968c72cf1cf/requirements.txt#L8

while in the previous versions there was no upper bound for the scikit-learn version.
https://github.com/pycaret/pycaret/blob/3dcb3c8c2cc3c0633ed6329ccce4c5a03bee88a7/requirements.txt#L7

I'm also curious how it will be treated in the future versions of PyCaret.

**Comment by kennysong** [comment]
Thanks! Looks like the possible combinations of PyCaret version to scikit-learn version are:

| PyCaret Version  | Possible Scikit-Learn Versions |
| ------------- | ------------- |
| 0.0.1 to 0.0.60  | ???   |
| 1.0.0  | ???   |
| [2.0](https://github.com/pycaret/pycaret/blob/2.0/requirements.txt) to [2.1.2](https://github.com/pycaret/pycaret/blob/2.1.2/requirements.txt)  | scikit-learn>=0.23   |
| [2.2](https://github.com/pycaret/pycaret/blob/2.2/requirements.txt) to [2.2.2](https://github.com/pycaret/pycaret/blob/2.2.2/requirements.txt)  | scikit-learn>=0.23.2 |
| [2.2.3](https://github.com/pycaret/pycaret/blob/2.2.3/requirements.txt) to [2.3.5](https://github.com/pycaret/pycaret/blob/2.3.5/requirements.txt) | scikit-learn==0.23.2 |
| after 2.3.5 | ??? |

Since there are multiple combinations of PyCaret + scikit-learn possible, we need a way to determine what PyCaret version and scikit-learn version a pickled model was saved with.

**Comment by moezali1** [comment]
@kennysong PyCaret 2.x is compatible with 0.23.2. It will stay the same for all the 2.x releases.

When we release PyCaret 3.x it will be compatible with the latest version of scikit-learn. Hope this helps.

**Comment by moezali1** [comment]
@liwii In future we plan to make `pycaret` compatible with the always the latest version of `sklearn`

**Comment by kennysong** [comment]
@moezali1 Thanks for the clarification! 

The other part of my question: Since a PyCaret model contains other code than scikit-learn, does a pickled PyCaret model have compatibility guarantees across PyCaret versions?

**Comment by wkuopt** [comment]
Hi @kennysong you can pip freeze the installed libraries and their versions along with your pycaret model to ensure that the model can be loaded without issues. In general, the developers should keep track of the model lineage for reproducibility.

**Comment by kennysong** [comment]
We'd prefer to identify the version from the model file directly, rather than generating and handling it in a separate artifact. 

Most ML libraries solve this problem in one of two ways:
1. Allow the user to determine what library version a model file was generated with (so the user can use the correct library version at load time) 
2. Provide compatibility guarantees (so the user doesn't need to worry about what library version they use to load the model file)

Either (1) or (2) works for us, so hopefully PyCaret can support one of them.

**Comment by wkuopt** [comment]
Thanks @kennysong . Can you provide links to the ml library that you mentioned for both options? That will give us some good reference.

**Comment by kennysong** [comment]
Sure!

> 1. Allow the user to determine what library version a model file was generated with (so the user can use the correct library version at load time)

In scikit-learn, saved model files can only be loaded in [the same library version they were saved with](https://scikit-learn.org/1.0/modules/model_persistence.html#security-maintainability-limitations). However, the library version is [saved in the pickle](https://stackoverflow.com/questions/41146759/check-sklearn-version-before-loading-model-using-joblib/41201029) so you can read it at load time. (It's slightly [more complicated](https://github.com/scikit-learn/scikit-learn/issues/22055) than this, but that's the idea.)

> 2. Provide compatibility guarantees (so the user doesn't need to worry about what library version they use to load the model file)

TensorFlow can serialize models into [the SavedModel format](https://www.tensorflow.org/tutorials/keras/save_and_load#save_the_entire_model), which can work across runtimes as well (save in Python, load in JavaScript).

PyTorch can serialize models into [the TorchScript format](https://pytorch.org/tutorials/beginner/saving_loading_models.html#export-load-model-in-torchscript-format), which is similar.

**Comment by kennysong** [comment]
It will be very helpful if you can provide (1) in PyCaret 2.4 (store the PyCaret library version and sklearn library version in the pickle).

**Comment by kennysong** [comment]
This issue is not stale.

**Comment by pyaf** [comment]
![image](https://user-images.githubusercontent.com/17473589/161491531-ecba5454-c5ab-4e92-acb8-895e2c6cff99.png)

Hi @moezali1, 

yellowbrick>=1.0.1 requires scikit-learn>1.0.0 

and pycaret requires scikit-learn==0.23.2

Due to this mismatch, I'm not able to install my custom library which uses pycaret as a dependency.

**Comment by pyaf** [comment]
Good to know that 3.0.0 is coming soon. 

Installing the pycaret-ts-alpha gives the following error:
![image](https://user-images.githubusercontent.com/17473589/161515921-694c13dd-12ec-4cf2-8692-fbd1e2c16cd3.png)

I'm installing pycaret-ts-alpha as a dependency for my custom package. I've listed it in `install_requires` and installing the custom package using setuptools with `python setup.py install`. Could you please help me with these

**Comment by ngupta23** [comment]
What is causing numpy 1.22.3 to be installed? If I just install pycaret-ts-alpha it works ok for me.

**Comment by kennysong** [comment]
It looks like PyCaret 3.0 [will update requirements.txt](https://github.com/pycaret/pycaret/blob/a9a069af0643faf4268da70629760c19f2e24201/requirements.txt#L9) to `scikit-learn>=1.0.2`. 

Since this covers multiple sklearn versions, it will no longer be possible for us to identify the version of sklearn used to generate a PyCaret pickle.

So, bumping this feature request for the 3.0 release:

> It will be very helpful if you can provide (1) in PyCaret 2.4 (store the PyCaret library version and sklearn library version in the pickle).

**Comment by kennysong** [comment]
Checking in: Will this be picked up before the 3.0 release? It's an important compatibility issue for us to be able to serve PyCaret 3.X serialized models in production.

If it's not planned, will you accept a PR implementing the functionality before the 3.0 release?

**Comment by kennysong** [comment]
Since there's no response from the maintainers, we're planning to submit a PR in the next few weeks.

This is an important compatibility issue for us to be able to serve PyCaret 3.X serialized models in production.
