### ISSUE TITLE
[BUG]Decision boundary plot for test data wrong

### ISSUE THREAD

**Issue by ANOOPAANTO** [pycaret/pycaret#2019]
**Describe the bug**

Class Report and confusion matrix showing good test data(holdout set) accuracy -> while Decision boundary plot shows very low test data accuracy for the same model!

![error screenshot](https://raw.githubusercontent.com/ANOOPAANTO/Pycaret_issues/main/Test_data_decision_boundary_%20error.JPG)

**Comment by moezali1** [comment]
@ANOOPAANTO How can you tell accuracy from the decision boundary plot?
