### ISSUE TITLE
parameter sample_size for setup not available

### ISSUE THREAD

**Issue by Barry1** [pycaret/pycaret#202]
When running setup() on huge data (>25.000) one is asked for a sample_size. This is a quite cool feature. But, when running with `silent=True`, I think one should also be able to pass the sample_size as a parameter.
So I suggest adding an optional parameter `sample_size` with default `None` and if given the interactive question (maybe also based on `silent`) would not be raised.

**Comment by Barry1** [comment]
Maybe one step further overloading the parameter `sampling` might also work: If numeric running not interactive and using that value as the `sample_size`

**Comment by pycaret** [comment]
@Barry1 Thanks. This a good suggestion. 

For next release I have linked silent parameter with sampling parameter. At the moment you turn sampling to False if you don't want to sample, in which case 100% of the dataset would be used. 

In next release when silent is set to True it will internally switch sampling to False.

However, I like your suggestion on sampling_size parameter. For now, I will mark this issue as an enhancement for future.

**Comment by Barry1** [comment]
Sounds good, thanks!

Am Sa., 6. Juni 2020 um 20:21 Uhr schrieb PyCaret <notifications@github.com
