### ISSUE TITLE
AttributeError: 'Fix_multicollinearity' object has no attribute 'target_corr_weight'

### ISSUE THREAD

**Issue by sagarnildass** [pycaret/pycaret#2021]
**Describe the bug**
When I am running pycaret leaderboard generator with remove_multicollinearity=True, multicollinearity_threshold=0.9, it fails with the error message: AttributeError: 'Fix_multicollinearity' object has no attribute 'target_corr_weight'

**Comment by moezali1** [comment]
@sagarnildass which version are you using? I am unable to reproduce this error. See below:

```
from pycaret.datasets import get_data
data = get_data('juice')

from pycaret.classification import *
s = setup(data, target = 'Purchase', remove_multicollinearity=True, session_id = 123)

lr = create_model('lr')
dt = create_model('dt')
xgboost = create_model('xgboost')

get_leaderboard()['Model'][0].steps
```

![image](https://user-images.githubusercontent.com/54699234/148563559-0823da9d-0171-4c1c-a2fb-e70c36e4464b.png)

Make sure you are using latest version i.e. pycaret==2.3.5.
