### ISSUE TITLE
[BUG] Problem still persist with the create_api func

### ISSUE THREAD

**Issue by ajayarunachalam** [pycaret/pycaret#2034]
**Problem still persist with the create_api func. Pls. check.**

**Comment by ngupta23** [comment]
Please provide a reproducible example of what the problem is.

**Comment by ajayarunachalam** [comment]
![image](https://user-images.githubusercontent.com/17896896/148651941-a9722507-ce9b-441c-b141-33686df43c6b.png)

**Comment by ngupta23** [comment]
This functionality will only be released in 2.3.6. It is unavailable in the version you are using.

**Comment by ngupta23** [comment]
2.3.6 is now available. Can you try with this latest version?

**Comment by ajayarunachalam** [comment]
Yes, I will update you back. Thanks.

**Comment by ajayarunachalam** [comment]
works fine.
