### ISSUE TITLE
[DOC] Clustering Model Tutorials

### ISSUE THREAD

**Issue by maiaufrrj** [pycaret/pycaret#2042]
Good morning to all here.
Could anyone help me to localize this tutorials?

1) Clustering Tutorial (CLU102) - Level Intermediate
2) Clustering Tutorial (CLU103) - Level Advanced
both pages are not founds.

This links are indicated in the end of this page:
http://www.pycaret.org/tutorials/html/CLU101.html

Thanks in advance for all efforts to help me acess this guide.

**Comment by ngupta23** [comment]
@moezali1 Does the new documentation cover this?

**Comment by ngupta23** [comment]
@maiaufrrj  it may be possible that we only have the beginner tutorial for this

https://pycaret.gitbook.io/docs/get-started/tutorials

**Comment by moezali1** [comment]
Yes @ngupta23 

@maiaufrrj Please use the link @ngupta23 has mentioned above. The website link is old and will be removed soon.
