### ISSUE TITLE
Data Types for `pycaret.regression.eda()`

### ISSUE THREAD

**Issue by OleksiyAnokhin** [pycaret/pycaret#2043]
I am using `pycaret.regression.eda(data=None, target: Optional[str] = None, display_format: str = 'bokeh', **kwargs)` from [documentation](https://pycaret.readthedocs.io/en/latest/api/regression.html).

When I check `dtypes` of my data, I only have `int64` and `float64` dtypes.

But when I run the `.eda()` function, half of my features are identified as categorical. 

![image](https://user-images.githubusercontent.com/24446791/148776839-be4f8e94-8696-4878-bbe2-2bb4f606e4ae.png)

I am trying to transform them with `numeric_features: string, default = None` from this [source](https://pycaret.org/data-types/) for `.eda()`, but I guess it only works for creating the instance. 

- Is such behavior for misinterpretation of numeric variables expected? 
- Does it affect the model results?
- Can I transform variables for `pycaret.regression.eda()`? 
-
Thanks!

**Comment by moezali1** [comment]
Hmm. I think `eda` function is not getting dtypes from the `setup`. It's a third party library which I guess automatically infers type using pandas dtypes. Can you try converting your `int` to `float` and see if this fixes the issue for EDA.

Thanks
