### ISSUE TITLE
change default label encoded level or orders

### ISSUE THREAD

**Issue by MichaelPeibo** [pycaret/pycaret#205]
Hi, thanks for developing this great tool!

I want to change the default order or levels of label encoded during `setup`, because I have several models(five) and I found `setup` function define label encoded by first-come-to-first-row.

For example, in my #1 dataset first label is A, then class 0 is assigned A, while in my #2 dataset first label is B, then class 0 is assigned B.

I want to make them consistent in my several models, which is easy to read for `interpret_model`.

I did not find a way to do that, any suggestion? Thanks!

**Comment by pycaret** [comment]
@MichaelPeibo Not possible at the moment but you raise a good point. I will keep this open for future enhancement.

**Comment by MichaelPeibo** [comment]
I sort of solve it by shuffling the data. But still looking forword to tunable parameters.
