### ISSUE TITLE
Bug in dahsboard () when the columns has especial characters

### ISSUE THREAD

**Issue by reza1615** [pycaret/pycaret#2053]
It seems before sending feature columns to the explainerdashboard. pycaret should clean them

```
InvalidComponentIdError: The element `feature-input-CE_Send to Fraud_1.0-input-40` contains `.` in its ID.
Characters `.`, `{` are not allowed in IDs
```

![image](https://user-images.githubusercontent.com/2202483/149231429-13b53e3d-4035-4419-a912-40c5e67b1324.png)

**Comment by moezali1** [comment]
PR merged.
