### ISSUE TITLE
[BUG] drift report error

### ISSUE THREAD

**Issue by reza1615** [pycaret/pycaret#2059]
when the index is not ordinal the drift report shows error
![image](https://user-images.githubusercontent.com/2202483/149582370-41295c14-46b5-46fc-a1b7-93a15ceccf64.png)

**Comment by reza1615** [comment]
![image](https://user-images.githubusercontent.com/2202483/149587054-fa5ac969-993a-4199-b3a5-69763267e3aa.png)

**Comment by moezali1** [comment]
@reza1615 I have assigned it to you.

**Comment by sahanaraguram2000** [comment]
I am getting a different kind of error with drift report regression. Please help me understand why this happens.

Here is the code:

`import pandas as pd
from pycaret.regression import *
data = pd.read_csv("E:\\on_nine_ai\\testing data\\Iris.csv")
s = setup(data, target = 'PetalWidthCm', session_id = 123)
lr = create_model('lr')
pred_holdout = predict_model(lr,drift_report=True)`

and here is the error that I get

`<pandas.io.formats.style.Styler object at 0x0000021EF96CD0A0>
Traceback (most recent call last):
  File "sample.py", line 6, in <module>
    pred_holdout = predict_model(lr,drift_report=True)
  File "C:\Users\LENOVO\anaconda3\envs\one_nine_fastapi\lib\site-packages\pycaret\regression.py", line 1760, in predict_model
    return pycaret.internal.tabular.predict_model(
  File "C:\Users\LENOVO\anaconda3\envs\one_nine_fastapi\lib\site-packages\pycaret\internal\tabular.py", line 8796, in predict_model
    create_regression_drift_report(
  File "C:\Users\LENOVO\anaconda3\envs\one_nine_fastapi\lib\site-packages\pycaret\internal\drift_report.py", line 86, in create_regression_drift_report  
    dashboard.calculate(reference_data, current_data, column_mapping=column_mapping)
  File "C:\Users\LENOVO\anaconda3\envs\one_nine_fastapi\lib\site-packages\evidently\dashboard\dashboard.py", line 147, in calculate
    self.execute(reference_data, current_data, column_mapping)
  File "C:\Users\LENOVO\anaconda3\envs\one_nine_fastapi\lib\site-packages\evidently\pipeline\pipeline.py", line 45, in execute
    instance.calculate(rdata, cdata, column_mapping)
  File "C:\Users\LENOVO\anaconda3\envs\one_nine_fastapi\lib\site-packages\evidently\analyzers\data_drift_analyzer.py", line 66, in calculate
    keys = set(list(reference_data[feature_name][np.isfinite(reference_data[feature_name])].unique()) +
  File "C:\Users\LENOVO\anaconda3\envs\one_nine_fastapi\lib\site-packages\pandas\core\generic.py", line 2032, in __array_ufunc__
    return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
  File "C:\Users\LENOVO\anaconda3\envs\one_nine_fastapi\lib\site-packages\pandas\core\arraylike.py", line 364, in array_ufunc
    result = getattr(ufunc, method)(*inputs, **kwargs)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`

**Comment by john6214058** [comment]
I also have this issue.
ypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_17120/478297414.py in <module>
----> 1 predict_model(catboost,drift_report= True)

~\AppData\Roaming\Python\Python38\site-packages\pycaret\classification.py in predict_model(estimator, data, probability_threshold, encoded_labels, raw_score, drift_report, round, verbose)
   2023     """
   2024 
-> 2025     return pycaret.internal.tabular.predict_model(
   2026         estimator=estimator,
   2027         data=data,

~\AppData\Roaming\Python\Python38\site-packages\pycaret\internal\tabular.py in predict_model(estimator, data, probability_threshold, encoded_labels, drift_report, raw_score, round, verbose, ml_usecase, display)
   8783     if drift_report:
   8784         if ml_usecase == MLUsecase.CLASSIFICATION:
-> 8785             create_classification_drift_report(
   8786                 _get_model_name(estimator),
   8787                 prep_pipe,

~\AppData\Roaming\Python\Python38\site-packages\pycaret\internal\drift_report.py in create_classification_drift_report(estimator_name, prep_pipe, unprocessed_data, X_train, X_test)
     39 
     40     dashboard = Dashboard(tabs=[DataDriftTab(), CatTargetDriftTab()])
---> 41     dashboard.calculate(reference_data, current_data, column_mapping=column_mapping)
     42     report_name = f"{estimator_name}_Drift_Report_Classification.html"
     43     dashboard.save(report_name)

~\AppData\Roaming\Python\Python38\site-packages\evidently\dashboard\dashboard.py in calculate(self, reference_data, current_data, column_mapping)
    145                   column_mapping: Optional[ColumnMapping] = None):
    146         column_mapping = column_mapping or ColumnMapping()
--> 147         self.execute(reference_data, current_data, column_mapping)
    148 
    149     def __render(self, template: Callable[[TemplateParams], str]):

~\AppData\Roaming\Python\Python38\site-packages\evidently\pipeline\pipeline.py in execute(self, reference_data, current_data, column_mapping)
     43             instance.options_provider = self.options_provider
     44             self.analyzers_results[analyzer] =\
---> 45                 instance.calculate(rdata, cdata, column_mapping)
     46         for stage in self.stages:
     47             stage.options_provider = self.options_provider

~\AppData\Roaming\Python\Python38\site-packages\evidently\analyzers\data_drift_analyzer.py in calculate(self, reference_data, current_data, column_mapping)
     64             confidence = options.get_confidence(feature_name)
     65             func = options.get_feature_stattest_func(feature_name, ks_stat_test)
---> 66             keys = set(list(reference_data[feature_name][np.isfinite(reference_data[feature_name])].unique()) +
     67                        list(current_data[feature_name][np.isfinite(current_data[feature_name])].unique()))
     68 

~\AppData\Roaming\Python\Python38\site-packages\pandas\core\generic.py in __array_ufunc__(self, ufunc, method, *inputs, **kwargs)
   2030         self, ufunc: np.ufunc, method: str, *inputs: Any, **kwargs: Any
   2031     ):
-> 2032         return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
   2033 
   2034     # ideally we would define this to avoid the getattr checks, but

~\AppData\Roaming\Python\Python38\site-packages\pandas\core\arraylike.py in array_ufunc(self, ufunc, method, *inputs, **kwargs)
    362         # ufunc(series, ...)
    363         inputs = tuple(extract_array(x, extract_numpy=True) for x in inputs)
--> 364         result = getattr(ufunc, method)(*inputs, **kwargs)
    365     else:
    366         # ufunc(dataframe)

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by reza1615** [comment]
I sent a PR and waiting to merge @moezali1

**Comment by reza1615** [comment]
It is solved
