### ISSUE TITLE
plots not showing in jupyter lab but does show in jupyter notebook

### ISSUE THREAD

**Issue by n8craig** [pycaret/pycaret#206]
I am working through the PyCaret Natural Language Processing Tutorial ([NLP101](
http://www.pycaret.org/tutorials/html/NLP101.html)). This looks like a really interesting tool, I'm keen to use it for classifying news items for social science research. I am running the tutorial code out of Jupyter Lab 1.2.6 and Jupyter Notebook 6.0.3 on Windows 10 with Firefox 77.0.1.

- On both platforms the lda models run properly and are reported.
- If the tutorial is run from Jupyter Lab, none of the `plot()` results show. There is a space in the outputs where it looks like a plot should be, but that space is blank.
- If the same tutorial is run from Jupyter Notebook, all of the `plot()` outputs are displayed correctly.
- When run from Jupyter Notebook, the `evaluate_model()` function does not seem to work properly. The output shows the plot type, a topic dropdown, and a run model button. No combination of plot type, topics, and submission of the run buttons produces any visible result. I expect it to show different figures or result. I think this latter matter is the same as #165.

I'm not sure where to find any kind of error log that I might report. If someone can direct me to the correct location I would report that information here if it helps. Thanks in advance.

**Comment by pycaret** [comment]
@n8craig I am not sure but maybe try this if it helps:

On top of your notebook in Jupyter Lab, put this on top:

from pycaret.utils import enable_colab
enable_colab()

**Comment by n8craig** [comment]
I logged out of Jupyter Lab, placed the suggested code up with the imports and re-ran the model.

Suggested addition:
`from pycaret.utils import enable_colab`
`enable_colab()`

Results:
- `plot()`: works on the first run, but if the outputs are cleared subsequent runs do not produce a figure.
- `plot_model(plot = 'bigram')`: does not produce a figure.
- `plot_model(lda, plot = 'frequency', topic_num = 'Topic 1')`: does not produce a figure.
- `plot_model(lda2, plot = 'topic_distribution')`: does not produce a figure.
- `plot_model(lda2, plot = 'tsne')`: does not produce a figure.
- `plot_model(lda2, plot = 'umap')` works, and if the outputs are cleared figures are produced on subsequent runs.

So the addition seems to have made some improvement, but the issue persists. Thank you very much for looking into the matter.

**Comment by n8craig** [comment]
Based on continued tinkering, I'm starting to wonder if the issue doesn't have something to do with Jupyter theming.

- If I apply a dark theme to Jupyter Notebook, the figures are not produced.
- If I use the default Jupyter Lab theme, the figures are produced.
- evaluate_model(lda) still does not work but that is a different issue #165.

Note: the results described here are with the suggested `enable_colab()` option commented out.

**Comment by n8craig** [comment]
Based on my tinkering the issue seems to have some relationship to Jupyter theming. I can get the figures to render if Jupyter Lab is set to default theme and the kernel restarted.

**Comment by 59ranjbar** [comment]
Hi,
I have the same issue as @n8craig  had. When putting  from pycaret.utils import enable_colab and enable_colab() on top of jupyter only plot_model(lda) worked but the other did not. Any fix for this issue?

Thank you always for your help.

**Comment by IgorFobia** [comment]
I keep having the same issue.
I am using
pycaret==2.3.3
jupyterlab==3.1.12

**Comment by osvaldoberg** [comment]
I have the same issue as @n8craig had.

**Comment by jfewz** [comment]
%matplotlib inline
%config inlinebackend.figure_format = 'retina'

Try running that, it worked for me :)
