### ISSUE TITLE
No model results for `compare_models()` in regression, while applying `transform_target`

### ISSUE THREAD

**Issue by OleksiyAnokhin** [pycaret/pycaret#2067]
Team, I am running a simple regression and everything works. 

When I try to add:

    `transform_target = True`, `transform_target_method = 'box-cox'`, # or another method

the modelling results for `compare_models()` are not printed. 

Thanks

**Comment by moezali1** [comment]
@OleksiyAnokhin Can you set errors='raise' in the `compare_models` function and show us what the error says?

**Comment by OleksiyAnokhin** [comment]
@moezali1 , this is with `errors = raise`

![image](https://user-images.githubusercontent.com/24446791/149836904-f77de519-1a56-4c55-b150-94c9a8bdb91d.png)

This is without `transform_target`

![image](https://user-images.githubusercontent.com/24446791/149837165-4c0370f6-6510-4ca3-a8aa-f80a246a9e85.png)

**Comment by moezali1** [comment]
@OleksiyAnokhin Can you share the dataset so I can see what's going on? 

Do you have negative values in your target?
