### ISSUE TITLE
[BUG] Timeseries Setup fails with some datasets

### ISSUE THREAD

**Issue by Rjotsin** [pycaret/pycaret#2068]
**Describe the bug**
 Hi team, discovered this bug when setting up a data set. Setup errors out for the pycaret-ts-alpha package. Happens on both Jupyter and Databricks. 

Link to dataset included at the bottom, monthly timeseries three years long. My goal was to use the theta model with this, but it seems to be erroring out with the arima package. 

ValueError: There are no more samples after a first-order seasonal differencing. See http://alkaline-ml.com/pmdarima/seasonal-differencing-issues.html for a more in-depth explanation and potential work-arounds.

**To Reproduce**

```python
from pycaret.time_series import setup
import pandas as pd

df = pd.read_csv('pycaret_error_data.csv')

df['Date'] = pd.to_datetime(df['Date'] , infer_datetime_format=True)
df = df.set_index('Date').resample('M').sum()

setup(data=df, fh=3, fold=3, session_id=123, n_jobs=1, seasonal_period='M', system_log=False)
```

**Expected behavior**
 Note, Setup states it was successful, but errors out right after. 

![image](https://user-images.githubusercontent.com/18150981/149709613-14d428ed-8173-4af9-a843-50795e90256d.png)
![image](https://user-images.githubusercontent.com/18150981/149709307-ac211fd3-17d6-4ba8-856a-9057b3bf5112.png)

**Additional context**

csv file: https://drive.google.com/file/d/171fezHPPrtavyJ71hihINV4bRhIL3GEl/view?usp=sharing

**Comment by ngupta23** [comment]
You have very few data points and are trying to model ARIMA with a seasonality of 12 as well as 3 fold cross validation. There are not enough data point to model it like this. Maybe disable cross validation to see if it helps.

**Comment by Rjotsin** [comment]
I did try many combinations of fh and folds and sadly no results. I was planning on just using theta, not arima, is there any way to avoid the arima validation steps?

**Comment by moezali1** [comment]
@ngupta23 In this case why would `setup` fail. No model training is done at this stage. no?

**Comment by ngupta23** [comment]
It does some checks in setup for the value of d and D. I am guessing it is failing there. I will need to look into it in detail and get back.

**Comment by Rjotsin** [comment]
@ngupta23 here is the complete output
[timeseries_pycaret_error_output.txt](https://github.com/pycaret/pycaret/files/7892250/timeseries_pycaret_error_output.txt)

**Comment by ngupta23** [comment]
@Rjotsin I have made a fix and submitted a PR to the local development branch `time_series`. The fix will go out in the next release of the time series module. In the meantime,  you can install from Git directly (once the associated PR is approved and merged to the `time_series` branch).


## Instructions for installing the time series branch.
```
# Create a Conda env
>>> conda create -n pycaret_ts_git_install python=3.8  (you can name it whatever you want)
>>> conda activate pycaret_ts_git_install

# Install packages
>>> pip install -U git+https://github.com/pycaret/pycaret.git@time_series
>>> pip install -U sktime
>>> pip install -U pmdarima
```

**Comment by moezali1** [comment]
Thank you so much @ngupta23
