### ISSUE TITLE
setup() Categorical and Numeric features

### ISSUE THREAD

**Issue by ManuelBanza** [pycaret/pycaret#207]
Hi,

I am trying to force some columns to be categorical but i get the error:
````
from pycaret.classification import *
exp_clf101 = setup(data = data, categorical_feature = [[ 'agent', 'company']], 
                   label_feature= 'is_repeated_guest', numeric_feature= [['adults', 'children', 'babies']],
                   target = 'is_canceled', session_id=123, 
                   remove_multicollinearity = True, multicollinearity_threshold = 0.95)

TypeError: setup() got an unexpected keyword argument 'categorical_feature'
````

In the settings it says:

If you choose to enter ‘quit‘ because one or more data types were not inferred correctly, you can overwrite them within setup command by passing categorical_feature parameter to force categorical type and numeric_feature parameter to force numeric type. Similarly, in order to ignore certain features to become part of experiment you can pass ignore_features parameter within setup.

Can anyone help?
Thanks

**Comment by pycaret** [comment]
@ManuelBanza Hi. I think that is because of typo. You should be passing categorical_features parameter and not categorical_feature.

Hope this helps.

**Comment by ManuelBanza** [comment]
hi @pycaret thanks it worked 👍  is it possible to have set as label feature as well?
