### ISSUE TITLE
[BUG] Tune_Model is Broken

### ISSUE THREAD

**Issue by phdwight** [pycaret/pycaret#2075]
**tune_model is broken**
 1 tuned_dt = tune_model('dt')

1 frames
/usr/local/lib/python3.7/dist-packages/pycaret/internal/tabular.py in tune_model_supervised(estimator, fold, round, n_iter, custom_grid, optimize, custom_scorer, search_library, search_algorithm, early_stopping, early_stopping_max_iters, choose_better, fit_kwargs, groups, return_tuner, verbose, tuner_verbose, display, **kwargs)
   3856     if type(estimator) is str:
   3857         raise TypeError(
-> 3858             "The behavior of tune_model in version 1.0.1 is changed. Please pass trained model object."
   3859         )
   3860 

TypeError: The behavior of tune_model in version 1.0.1 is changed. Please pass trained model object.
-->

**To Reproduce**
Follow the tutorial: https://www.pycaret.org/tutorials/html/CLF101.html
At the point of tune_model, it will show up.

```python
tuned_dt = tune_model('dt')
```

**Expected behavior**
It should run tuning a model

**Additional context**

**Versions**
none

</details>

**Comment by gserapio** [comment]
try passing a trained model object. in other words, remove the quotes from `dt`.

**Comment by gserapio** [comment]
> try passing a trained model object. in other words, remove the quotes from `dt`.

`tuned_dt = tune_model(dt)`

**Comment by moezali1** [comment]
@phdwight It is not broken. You are using very old documentation. `tune_model` doesn't accept a string anymore. You have to do this:

```
dt = create_model('dt')
tuned_dt = tune_model(dt)
```
Hope this helps.
