### ISSUE TITLE
NLP Data Question

### ISSUE THREAD

**Issue by wsn4iv** [pycaret/pycaret#208]
I see when assigning a model, additional columns are added to the dataset identifying the Topic each line is associated with. Is it also possible to export the Trigram, Bigram, Word Cloud, etc. data associated with the plots?

**Comment by pycaret** [comment]
@wsn4iv Excellent point. Not for next release but this is definitely a great feature to be included in future releases. I will keep this open and tag this as an enhancement.

**Comment by moezali1** [comment]
We are no more supporting the `nlp` and `arules` module in PyCaret due to lack to resources. Closing the issue now.
