### ISSUE TITLE
NameError: stats_check() function

### ISSUE THREAD

**Issue by aRafiyi** [pycaret/pycaret#2083]
Hi everyone,

Since yesterday, the `stats_check()` function throws the following error:

"NameError: name 'stats_check' is not defined"

Also, it seems that there is no documentation for this function.

**Comment by ngupta23** [comment]
Its `check_stats`

**Comment by aRafiyi** [comment]
Hi Nikhil,

As you mentioned it was `check_stats` that mistakenly reported as `stats_check`.

Thanks for that!
