### ISSUE TITLE
[BUG] Pycaret 2.3.6 Evidently Not working for drift_report=True

### ISSUE THREAD

**Issue by DerekKane** [pycaret/pycaret#2085]
I had installed the latest version of pycaret 2.3.6 onto a docker jupyter/tensorflow-notebook build. I recreated the example on the YouTube channel with the Evidently and it worked with no issue. However, when I rebuilt my container today the pycaret code doesnt seem to be working now and throws up an error claiming ModuleNotFoundError: No module named 'evidently.tabs'. Ther version of Evidently installed is 0.1.41.dev0 and I used a !pip install evidently

**To Reproduce**

```python
# load dataset
from pycaret.datasets import get_data
data = get_data('boston')

# init setup
from pycaret.regression import *
s = setup(data, target = 'medv', session_id = 123, silent = True)

# train model
dt = create_model('dt')

predict_model(dt)

# generate report
preds = predict_model(dt, drift_report = True)
```

**Expected behavior**

The last line of the code preds = predict_model(dt, drift_report = True) should produce the drift report. 

**Additional context**
Here is the full print out of the error:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [5], in <module>
      1 # generate report
----> 2 preds = predict_model(dt, drift_report = True)

File /opt/conda/lib/python3.9/site-packages/pycaret/regression.py:1759, in predict_model(estimator, data, drift_report, round, verbose)
   1699 def predict_model(
   1700     estimator,
   1701     data: Optional[pd.DataFrame] = None,
   (...)
   1704     verbose: bool = True,
   1705 ) -> pd.DataFrame:
   1707     """
   1708     This function predicts ``Label`` using a trained model. When ``data`` is
   1709     None, it predicts label on the holdout set.
   (...)
   1756 
   1757     """
-> 1759     return pycaret.internal.tabular.predict_model(
   1760         estimator=estimator,
   1761         data=data,
   1762         drift_report=drift_report,
   1763         probability_threshold=None,
   1764         encoded_labels=True,
   1765         round=round,
   1766         verbose=verbose,
   1767         ml_usecase=MLUsecase.REGRESSION,
   1768     )

File /opt/conda/lib/python3.9/site-packages/pycaret/internal/tabular.py:8794, in predict_model(estimator, data, probability_threshold, encoded_labels, drift_report, raw_score, round, verbose, ml_usecase, display)
   8785         create_classification_drift_report(
   8786             _get_model_name(estimator),
   8787             prep_pipe,
   (...)
   8790             X_test_,
   8791         )
   8793     elif ml_usecase == MLUsecase.REGRESSION:
-> 8794         create_regression_drift_report(
   8795             _get_model_name(estimator),
   8796             prep_pipe,
   8797             data_before_preprocess,
   8798             X_train,
   8799             X_test_,
   8800         )
   8802 # function to replace encoded labels with their original values
   8803 # will not run if categorical_labels is false
   8804 def replace_lables_in_column(label_column):

File /opt/conda/lib/python3.9/site-packages/pycaret/internal/drift_report.py:65, in create_regression_drift_report(estimator_name, prep_pipe, unprocessed_data, X_train, X_test)
     59     raise ImportError(
     60         "It appears that evidently (required for `drift_report=True`) is not installed. "
     61         "Do: pip install evidently"
     62     )
     64 from evidently.dashboard import Dashboard
---> 65 from evidently.tabs import DataDriftTab, NumTargetDriftTab
     66 from evidently.pipeline.column_mapping import ColumnMapping
     68 p = prep_pipe.steps[0][1].learned_dtypes

ModuleNotFoundError: No module named 'evidently.tabs'

**Versions**
<details>

Please run the following code snippet and paste the output here:
 
import pycaret
pycaret.__version__

</details>

**Comment by reza1615** [comment]
After the recent merge it is ok
![image](https://user-images.githubusercontent.com/2202483/151050072-a8e0441e-e161-4ea6-a208-4658cc08d414.png)

**Comment by reza1615** [comment]
It is fixed. If there are any issues feel free to reopen it
