### ISSUE TITLE
[BUG] Problem... with drift...

### ISSUE THREAD

**Issue by JuanBGV** [pycaret/pycaret#2088]
Problem... with drift...

I had installed the latest version of pycaret 2.3.6-I recreated the example on the YouTube channel with the Evidently and it worked without any problems. However, when I rebuilt today, the pycaret code doesn't seem to be working now and throws up an error that states ModuleNotFoundError: There is no module called 'evidently.tabs'. The version of Evidently installed is 0.1.41.dev0 and I used a !pip installation evidently..

Can I help

**Comment by moezali1** [comment]
@JuanBGV There is a pending PR for the drift report. I wonder if that PR will resolve this issue, if not, will you be interested in working on this?

**Comment by reza1615** [comment]
Now it seems ok
![image](https://user-images.githubusercontent.com/2202483/151050853-a244f993-197d-4cb6-ac88-acdf80b95617.png)

**Comment by JuanBGV** [comment]
Thank you- Great.
