### ISSUE TITLE
Programatially extract keywords from Topics

### ISSUE THREAD

**Issue by ecdedios** [pycaret/pycaret#209]
Is there a way to programmatically extract the keywords from each topics in the NLP module? Currently, I am having to hover over the result of plot_model() but I'd rather that I get it without hovering.

**Comment by pycaret** [comment]
@ecdedios Good question.

The model object returned by create_model('lda') function is a gensim object. You can call off all the methods/attributes of gensim. To get the keyword of topics from trained LDA model you can do something like this:

lda = create_model('lda')
lda.print_topics()

Let me know if that works.

Thanks.

**Comment by ecdedios** [comment]
Worked like a charm! This is a really great library. Thank you so much!!!
