### ISSUE TITLE
how can show all rows during setup to confirm if all features type been identify correct

### ISSUE THREAD

**Issue by john6214058** [pycaret/pycaret#2098]
Code:
from pycaret.datasets import get_data
dataset = get_data('mice')
from pycaret.clustering import *

exp_clu101 = setup(data, normalize = True, 
                   ignore_features = ['MouseID'],
                   session_id = 123)

here I got a summary data frame to confirm if all the features types were identified correct.

Current problem is if  there are total 81 features, it can not show all the features.

**Comment by luizricardo6n** [comment]
Did you manage to solve it? @john6214058

**Comment by john6214058** [comment]
solved, thanks
