### ISSUE TITLE
Enhancements for setting prediction threshold for classification

### ISSUE THREAD

**Issue by ThinhNg** [pycaret/pycaret#210]
Hello!

This is really great work.
I've ran into some limitations with the classification side.

Two main things(The first one is the a higher priority):

1. I'm working with an unbalanced dataset and was trying to set the threshold for when I'm plotting the classification_report or the confusion matrix.

There wasn't an option to predict based on a classification threshold.
Is it possible to add that in?

2. The data that is returned from setup(....)
Has a lot of useful information, except I have figure out what the index of each component of the dataset.
e.g.
setupInfo=setup(....)
#Transformed_testX
transform_TestX=setupInfo[3]
#Testy
TestY=setupInfo[5]

Is it possible to add in indexes for the different datasets that setup returns.

Thanks,

**Comment by pycaret** [comment]
@ThinhNg Thanks for reaching out. Both are good points.

For 1st one, you can pass probability_threshold parameter under predict_model function to achieve predictions based on given threshold level. I am not sure if we can pass the parameter under classification report but I will check that.

For no 2. This is a good idea. I will tag this as an enhancement to include a function to get the objects from setup(). I agree it's not the most useful thing at the moment.

**Comment by pycaret** [comment]
# Feature available in PyCaret 2.0

## A new function **get_config()** has been added
https://www.pycaret.org/get-config

**Comment by rotimi2020** [comment]
I think pycaret is having issue with imbalanced classification.
