### ISSUE TITLE
# Decision Boundary Chart does not match with the Confusion matrix

### ISSUE THREAD

**Issue by PitS99** [pycaret/pycaret#2106]
Decision Boundary Chart does not match with the Confusion matrix.

![image](https://user-images.githubusercontent.com/69504431/151762191-b22c9f0c-336e-475d-a0ba-c64adfbb40a3.png)

vs.

![image](https://user-images.githubusercontent.com/69504431/151762292-915e6530-400b-44bb-b364-3ee5643ed858.png)

Class 1 - there is a good match between both charts
Class 3 - there is a good match between both charts
Class 2 - there is a missmatch.  On "Decision Boundary" is one point missing and True vs. Predicted Classes does not match.

Confusion Matrix: Class2 - 4 are correct classified, 2 not correct
Decision Boundary: Class2 - 2 are correct classified, 3 not correct classified (1 is missing)

**Comment by moezali1** [comment]
Well, the Decision boundaries x and y-axis are PCA'ed, so there is an information loss there. I am not sure if this will ever match this way.
