### ISSUE TITLE
[BUG] Datasets unable to read from a web address

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#2107]
**Describe the bug**
Unable to read data from a web location using `address` filed

**To Reproduce**

```python
from pycaret.datasets import get_data
data = get_data(
    "economic_indicators_all_ex_3mo_china_inc_treas3mo", 
address="https://raw.githubusercontent.com/ngupta23/DS6373_TimeSeries/2b40f0071c3b7ec6a05dc0106f64e041f8cbaaef/Projects/gdp_prediction/data/",
)
```

```python
    raise ValueError(f"Data could not be read. Please check your inputs...")
ValueError: Data could not be read. Please check your inputs...
```

An extra path "data/commom/" is being appended to the address. 

**Expected behavior**
Data should be read from the link directly without appending anything else to it (i.e. the user should provide the complete link for the dataset)

**Versions**
Time Series Module (Jan 30th release)

**Comment by sayantan1410** [comment]
@ngupta23 Hey, I would like to on this one !!

**Comment by sayantan1410** [comment]
@ngupta23 Hey, when I am reproducing the bug it is running successfully, 
I have done `pip install pycaret` and then ran the above code, do I have to install a specific version of pycaret for reproducing the bug ? 
here's the link to the notebook - https://colab.research.google.com/drive/1-FoFLjSR_klLuTEcLvKBAZ1-Om-KAQvm?usp=sharing

**Comment by ngupta23** [comment]
@sayantan1410 This is in the time_series branch. 

You can try with `!pip install pycaret-ts-alpha`

**Comment by sayantan1410** [comment]
Okay sure !!
