### ISSUE TITLE
Session Crashed on Colab and Kaggle

### ISSUE THREAD

**Issue by pandeynandancse** [pycaret/pycaret#211]
I am  trying to set up the model using setup() method but when it is doing so session is being crashed as CPU is working too much and RAM is also being used too much  on Google colab as colab provides 12.72 GB free RAM but this module is requiring more than that and thus crashing.
I have dataset of 25000 rows and 18 columns.

**Comment by pycaret** [comment]
@pandeynandancse Thanks for reporting. The dataset is very small, this shouldn't happen. One thing I could think of is if the data types are inferred wrong as a result of which there would be a numeric column that is considered as categorical resulted in sparse matrix. When you execute setup the data types that are printed, were they okay?

**Comment by pandeynandancse** [comment]
Yes , pycaret was considering numerical features as categorical features ,Now it has been resolved .
Thanks.
