### ISSUE TITLE
How to deal with big data and shrink required memory

### ISSUE THREAD

**Issue by Brunokemon** [pycaret/pycaret#2118]
Hi, I have some really big training data files (ranging from 1gb to 5gb) and I'm having trouble using them with Pycaret

Here is the code I'm using
```
data = pandas.read_csv('TrainingData.csv', low_memory=False, error_bad_lines=False, memory_map=True)

setup = setup( data = data, n_jobs=nJobs, target = 'phenotype', silent=True, train_size = 0.7, use_gpu = True)

best_models = compare_models( sort = 'MSE', n_select = 3)
```

for the dataset with 1gb it yields the following memory error
```
File "preprocess.py", line 2745, in fit_transform
    corr = pd.DataFrame(np.corrcoef(targetless_data.T))
  File "<__array_function__ internals>", line 6, in corrcoef
  File ".../lib/python3.7/site-packages/numpy/lib/function_base.py", line 2551, in corrcoef
    c = cov(x, y, rowvar)
  File "<__array_function__ internals>", line 6, in cov
  File "...lib/python3.7/site-packages/numpy/lib/function_base.py", line 2479, in cov
    c = dot(X, X_T.conj())
  File "<__array_function__ internals>", line 6, in dot
numpy.core._exceptions.MemoryError: Unable to allocate 1.64 TiB for an array with shape (474210, 474210) and data type float64
```

so I'd like to know if it is possible to make it explicit for Pycaret that the data is int32 instead of float64 and other tips that would shrink the needed memory size.

Thank u.

**Comment by ngupta23** [comment]
It looks like you have about 0.5 Million features. Is that correct? Do you really need all of them for your modeling?

**Comment by Brunokemon** [comment]
I removed less important features but that still leaves me with about 0.3 Million features.
Yeah it's still a lot but biological data has a lot of important features unfortunately that I can't remove.

**Comment by ngupta23** [comment]
Do you know which model is giving the issue in `compare_models()`. If so, you could try to remove it from the list using the `exclude` argument to see if it will work.

**Comment by Brunokemon** [comment]
I've put to test each model, one by one today earlier. We'll see which one causes the issue.

**Comment by moezali1** [comment]
@Brunokemon I bet `knn` here will be a deal breaker here. Do you have GPU available? If yes, I suggest use `use_gpu = True` in the `setup`.

**Comment by tvdboom** [comment]
Is it possible to convert your data to a [sparse dataframe](https://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html)? That would definitely help with the memory the most and the majority of sklearn's models support sparse input.

Shrinking the data types is not yet implemented, but will be a new feature for the next major release, as well as some improvements in memory efficiency.

**Comment by tvdboom** [comment]
Also, if your data does not need preprocessing, use `preprocess=False` in setup(). That will skip the transformation steps that is causing the memory failure in your example.

**Comment by Brunokemon** [comment]
@moezali1 I have a GPU. I'm waiting the results of the KNN. Hope it works.

**Comment by tvdboom** [comment]
The majority of sklearn models **can't** deal with NaN values. The compressed value in a sparse dataframe is usually zero.

**Comment by Brunokemon** [comment]
I needed to do additional data filtering and that made it work. 

Thanks, lads, for the help.
