### ISSUE TITLE
[BUG] Installation Issue

### ISSUE THREAD

**Issue by jgdpsingh** [pycaret/pycaret#2125]
**Describe the bug**

The library is not installing at all. I tried running Command prompt as administrator as well but to no avail. 

**To Reproduce**
Requirement already satisfied: phik>=0.11.1 in c:\users\jagdeep\appdata\roaming\
python\python39\site-packages (from pandas-profiling>=2.8.0->pycaret) (0.12.0)
Requirement already satisfied: networkx>=2.4 in c:\users\jagdeep\anaconda3\lib\s
ite-packages (from visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pyc
aret) (2.6.3)
Requirement already satisfied: imagehash in c:\users\jagdeep\appdata\roaming\pyt
hon\python39\site-packages (from visions[type_image_path]==0.7.4->pandas-profili
ng>=2.8.0->pycaret) (4.2.1)
Requirement already satisfied: Pillow in c:\users\jagdeep\anaconda3\lib\site-pac
kages (from visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pycaret) (
8.4.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\jagdeep\anaconda3\l
ib\site-packages (from matplotlib->pycaret) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\jagdeep\anaconda3\lib\si
te-packages (from matplotlib->pycaret) (0.10.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\jagdeep\anaconda3\li
b\site-packages (from matplotlib->pycaret) (3.0.4)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\jagdeep\appdata\roami
ng\python\python39\site-packages (from plotly>=4.4.1->pycaret) (8.0.1)
Requirement already satisfied: wcwidth in c:\users\jagdeep\anaconda3\lib\site-pa
ckages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->IPython->pycaret) (0.
2.5)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\jagdeep\an
aconda3\lib\site-packages (from pydantic>=1.8.1->pandas-profiling>=2.8.0->pycare
t) (3.10.0.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jagdeep\anaconda3\lib\si
te-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\jagdeep\anacond
a3\lib\site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (
1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jagdeep\anaconda3\
lib\site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (202
1.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\jagdeep\ana
conda3\lib\site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycare
t) (2.0.4)
Requirement already satisfied: notebook>=4.4.1 in c:\users\jagdeep\anaconda3\lib
\site-packages (from widgetsnbextension~=3.5.0->ipywidgets->pycaret) (6.4.5)
Requirement already satisfied: terminado>=0.8.3 in c:\users\jagdeep\anaconda3\li
b\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->py
caret) (0.9.4)
Requirement already satisfied: nbconvert in c:\users\jagdeep\anaconda3\lib\site-
packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret)
(6.1.0)
Requirement already satisfied: prometheus-client in c:\users\jagdeep\anaconda3\l
ib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->p
ycaret) (0.11.0)
Requirement already satisfied: argon2-cffi in c:\users\jagdeep\anaconda3\lib\sit
e-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret
) (20.1.0)
Requirement already satisfied: Send2Trash>=1.5.0 in c:\users\jagdeep\anaconda3\l
ib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->p
ycaret) (1.8.0)
Requirement already satisfied: pywinpty>=0.5 in c:\users\jagdeep\anaconda3\lib\s
ite-packages (from terminado>=0.8.3->notebook>=4.4.1->widgetsnbextension~=3.5.0-
>ipywidgets->pycaret) (0.5.7)
Requirement already satisfied: cffi>=1.0.0 in c:\users\jagdeep\anaconda3\lib\sit
e-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywid
gets->pycaret) (1.14.6)
Requirement already satisfied: pycparser in c:\users\jagdeep\anaconda3\lib\site-
packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.
5.0->ipywidgets->pycaret) (2.20)
Requirement already satisfied: smart-open>=1.8.1 in c:\users\jagdeep\appdata\roa
ming\python\python39\site-packages (from gensim->pycaret) (5.2.1)
Requirement already satisfied: Cython==0.29.23 in c:\users\jagdeep\appdata\roami
ng\python\python39\site-packages (from gensim->pycaret) (0.29.23)
Requirement already satisfied: PyWavelets in c:\users\jagdeep\anaconda3\lib\site
-packages (from imagehash->visions[type_image_path]==0.7.4->pandas-profiling>=2.
8.0->pycaret) (1.1.1)
Requirement already satisfied: prometheus-flask-exporter in c:\users\jagdeep\app
data\roaming\python\python39\site-packages (from mlflow->pycaret) (0.18.7)
Requirement already satisfied: cloudpickle in c:\users\jagdeep\anaconda3\lib\sit
e-packages (from mlflow->pycaret) (2.0.0)
Requirement already satisfied: Flask in c:\users\jagdeep\anaconda3\lib\site-pack
ages (from mlflow->pycaret) (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\jagdeep\anaconda3\lib\site
-packages (from mlflow->pycaret) (1.4.22)
Requirement already satisfied: gitpython>=2.1.0 in c:\users\jagdeep\appdata\roam
ing\python\python39\site-packages (from mlflow->pycaret) (3.1.26)
Requirement already satisfied: querystring-parser in c:\users\jagdeep\appdata\ro
aming\python\python39\site-packages (from mlflow->pycaret) (1.2.4)
Requirement already satisfied: waitress in c:\users\jagdeep\appdata\roaming\pyth
on\python39\site-packages (from mlflow->pycaret) (2.0.0)
Requirement already satisfied: databricks-cli>=0.8.7 in c:\users\jagdeep\appdata
\roaming\python\python39\site-packages (from mlflow->pycaret) (0.16.2)
Requirement already satisfied: protobuf>=3.7.0 in c:\users\jagdeep\appdata\roami
ng\python\python39\site-packages (from mlflow->pycaret) (3.19.4)
Requirement already satisfied: importlib-metadata!=4.7.0,>=3.7.0 in c:\users\jag
deep\anaconda3\lib\site-packages (from mlflow->pycaret) (4.8.1)
Requirement already satisfied: docker>=4.0.0 in c:\users\jagdeep\appdata\roaming
\python\python39\site-packages (from mlflow->pycaret) (5.0.3)
Requirement already satisfied: alembic in c:\users\jagdeep\appdata\roaming\pytho
n\python39\site-packages (from mlflow->pycaret) (1.7.6)
Requirement already satisfied: sqlparse>=0.3.1 in c:\users\jagdeep\appdata\roami
ng\python\python39\site-packages (from mlflow->pycaret) (0.4.2)
Requirement already satisfied: entrypoints in c:\users\jagdeep\anaconda3\lib\sit
e-packages (from mlflow->pycaret) (0.3)
Requirement already satisfied: packaging in c:\users\jagdeep\anaconda3\lib\site-
packages (from mlflow->pycaret) (21.0)
Requirement already satisfied: click>=7.0 in c:\users\jagdeep\anaconda3\lib\site
-packages (from mlflow->pycaret) (8.0.3)
Requirement already satisfied: tabulate>=0.7.7 in c:\users\jagdeep\anaconda3\lib
\site-packages (from databricks-cli>=0.8.7->mlflow->pycaret) (0.8.9)
Requirement already satisfied: websocket-client>=0.32.0 in c:\users\jagdeep\anac
onda3\lib\site-packages (from docker>=4.0.0->mlflow->pycaret) (1.2.3)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\jagdeep\appdata\roami
ng\python\python39\site-packages (from gitpython>=2.1.0->mlflow->pycaret) (4.0.9
)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\jagdeep\anaconda3\lib
\site-packages (from gitdb<5,>=4.0.1->gitpython>=2.1.0->mlflow->pycaret) (5.0.0)

Requirement already satisfied: zipp>=0.5 in c:\users\jagdeep\anaconda3\lib\site-
packages (from importlib-metadata!=4.7.0,>=3.7.0->mlflow->pycaret) (3.6.0)
Requirement already satisfied: Mako in c:\users\jagdeep\appdata\roaming\python\p
ython39\site-packages (from alembic->mlflow->pycaret) (1.1.6)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\jagdeep\anaconda3\li
b\site-packages (from sqlalchemy->mlflow->pycaret) (1.1.1)
Requirement already satisfied: itsdangerous>=0.24 in c:\users\jagdeep\anaconda3\
lib\site-packages (from Flask->mlflow->pycaret) (2.0.1)
Requirement already satisfied: Werkzeug>=0.15 in c:\users\jagdeep\anaconda3\lib\
site-packages (from Flask->mlflow->pycaret) (2.0.2)
Requirement already satisfied: jupyterlab-pygments in c:\users\jagdeep\anaconda3
\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->
ipywidgets->pycaret) (0.1.2)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\jagdeep\anaconda3\l
ib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ip
ywidgets->pycaret) (0.8.4)
Requirement already satisfied: testpath in c:\users\jagdeep\anaconda3\lib\site-p
ackages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets-
>pycaret) (0.5.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\jagdeep\anaconda
3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0-
>ipywidgets->pycaret) (1.4.3)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\jagdeep\anacon
da3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.
0->ipywidgets->pycaret) (0.5.3)
Requirement already satisfied: defusedxml in c:\users\jagdeep\anaconda3\lib\site
-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidget
s->pycaret) (0.7.1)
Requirement already satisfied: bleach in c:\users\jagdeep\anaconda3\lib\site-pac
kages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->p
ycaret) (4.0.0)
Requirement already satisfied: async-generator in c:\users\jagdeep\anaconda3\lib
\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgets
nbextension~=3.5.0->ipywidgets->pycaret) (1.10)
Requirement already satisfied: nest-asyncio in c:\users\jagdeep\anaconda3\lib\si
te-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbe
xtension~=3.5.0->ipywidgets->pycaret) (1.5.1)
Requirement already satisfied: webencodings in c:\users\jagdeep\anaconda3\lib\si
te-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0-
>ipywidgets->pycaret) (0.5.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\jagdeep\anaconda3\lib
\site-packages (from nltk->pycaret) (2021.8.3)
Requirement already satisfied: funcy in c:\users\jagdeep\appdata\roaming\python\
python39\site-packages (from pyLDAvis->pycaret) (1.17)
Collecting sklearn
  Using cached sklearn-0.0.tar.gz (1.1 kB)
Requirement already satisfied: numexpr in c:\users\jagdeep\anaconda3\lib\site-pa
ckages (from pyLDAvis->pycaret) (2.7.3)
Requirement already satisfied: future in c:\users\jagdeep\anaconda3\lib\site-pac
kages (from pyLDAvis->pycaret) (0.18.2)
Collecting pyLDAvis
  Using cached pyLDAvis-3.3.0.tar.gz (1.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
  Using cached pyLDAvis-3.2.2-py2.py3-none-any.whl
Requirement already satisfied: statsmodels in c:\users\jagdeep\anaconda3\lib\sit
e-packages (from pyod->pycaret) (0.12.2)
Requirement already satisfied: numba>=0.35 in c:\users\jagdeep\anaconda3\lib\sit
e-packages (from pyod->pycaret) (0.54.1)
Requirement already satisfied: llvmlite<0.38,>=0.37.0rc1 in c:\users\jagdeep\ana
conda3\lib\site-packages (from numba>=0.35->pyod->pycaret) (0.37.0)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\jagdeep\app
data\roaming\python\python39\site-packages (from spacy->pycaret) (1.0.6)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\jagdeep\appda
ta\roaming\python\python39\site-packages (from spacy->pycaret) (2.0.6)
Requirement already satisfied: wasabi<1.1.0,>=0.8.1 in c:\users\jagdeep\appdata\
roaming\python\python39\site-packages (from spacy->pycaret) (0.9.0)
Requirement already satisfied: pathy>=0.3.5 in c:\users\jagdeep\appdata\roaming\
python\python39\site-packages (from spacy->pycaret) (0.6.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.8 in c:\users\jagdeep\ap
pdata\roaming\python\python39\site-packages (from spacy->pycaret) (3.0.8)
Requirement already satisfied: typer<0.5.0,>=0.3.0 in c:\users\jagdeep\appdata\r
oaming\python\python39\site-packages (from spacy->pycaret) (0.4.0)
Requirement already satisfied: srsly<3.0.0,>=2.4.1 in c:\users\jagdeep\appdata\r
oaming\python\python39\site-packages (from spacy->pycaret) (2.4.2)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\jagdeep\appdata\r
oaming\python\python39\site-packages (from spacy->pycaret) (2.0.6)
Requirement already satisfied: thinc<8.1.0,>=8.0.12 in c:\users\jagdeep\appdata\
roaming\python\python39\site-packages (from spacy->pycaret) (8.0.13)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\jagdeep\a
ppdata\roaming\python\python39\site-packages (from spacy->pycaret) (1.0.1)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in c:\users\jagdeep\appdata\ro
aming\python\python39\site-packages (from spacy->pycaret) (0.7.5)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\jagdeep\appda
ta\roaming\python\python39\site-packages (from spacy->pycaret) (3.3.0)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\jagdeep\appdata
\roaming\python\python39\site-packages (from spacy->pycaret) (3.0.6)
Requirement already satisfied: patsy>=0.5 in c:\users\jagdeep\anaconda3\lib\site
-packages (from statsmodels->pyod->pycaret) (0.5.2)
Requirement already satisfied: pynndescent>=0.5 in c:\users\jagdeep\appdata\roam
ing\python\python39\site-packages (from umap-learn->pycaret) (0.5.6)
Building wheels for collected packages: wordcloud
  Building wheel for wordcloud (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Jagdeep\anaconda3\python.exe' -u -c 'import io, os, sys, s
etuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Jagdeep\\AppData\\Local\\Temp
\\pip-install-z9mjfyjb\\wordcloud_0913a61ca2de46e392daeafbf24661e0\\setup.py'"'"
'; __file__='"'"'C:\\Users\\Jagdeep\\AppData\\Local\\Temp\\pip-install-z9mjfyjb\
\wordcloud_0913a61ca2de46e392daeafbf24661e0\\setup.py'"'"';f = getattr(tokenize,
 '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"
'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n
'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bd
ist_wheel -d 'C:\Users\Jagdeep\AppData\Local\Temp\pip-wheel-ennob0wh'
       cwd: C:\Users\Jagdeep\AppData\Local\Temp\pip-install-z9mjfyjb\wordcloud_0
913a61ca2de46e392daeafbf24661e0\
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\color_from_image.py -> build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\tokenization.py -> build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\wordcloud.py -> build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\_version.py -> build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\__init__.py -> build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\__main__.py -> build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\stopwords -> build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-3.9\wordcloud
  UPDATING build\lib.win-amd64-3.9\wordcloud/_version.py
  set build\lib.win-amd64-3.9\wordcloud/_version.py to '1.8.1'
  running build_ext
  building 'wordcloud.query_integral_image' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsof
t C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
Failed to build wordcloud
Installing collected packages: wordcloud, umap-learn, textblob, spacy, scikit-pl
ot, pyod, pyLDAvis, pandas-profiling, mlxtend, lightgbm, kmodes, imbalanced-lear
n, gensim, cufflinks, catboost, pycaret
    Running setup.py install for wordcloud ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Jagdeep\anaconda3\python.exe' -u -c 'import io, os, sys,
 setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Jagdeep\\AppData\\Local\\Te
mp\\pip-install-z9mjfyjb\\wordcloud_0913a61ca2de46e392daeafbf24661e0\\setup.py'"
'"'; __file__='"'"'C:\\Users\\Jagdeep\\AppData\\Local\\Temp\\pip-install-z9mjfyj
b\\wordcloud_0913a61ca2de46e392daeafbf24661e0\\setup.py'"'"';f = getattr(tokeniz
e, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO(
'"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r
\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record 'C:\Users\Jagdeep\AppData\Local\Temp\pip-record-hz7efuy9\instal
l-record.txt' --single-version-externally-managed --compile --install-headers 'C
:\Users\Jagdeep\anaconda3\Include\wordcloud'
         cwd: C:\Users\Jagdeep\AppData\Local\Temp\pip-install-z9mjfyjb\wordcloud
_0913a61ca2de46e392daeafbf24661e0\
    Complete output (20 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\color_from_image.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\tokenization.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\wordcloud.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\_version.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\__init__.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\__main__.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\stopwords -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-3.9\wordcloud
    UPDATING build\lib.win-amd64-3.9\wordcloud/_version.py
    set build\lib.win-amd64-3.9\wordcloud/_version.py to '1.8.1'
    running build_ext
    building 'wordcloud.query_integral_image' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Micros
oft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Jagdeep\anaconda3\pytho
n.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\U
sers\\Jagdeep\\AppData\\Local\\Temp\\pip-install-z9mjfyjb\\wordcloud_0913a61ca2d
e46e392daeafbf24661e0\\setup.py'"'"'; __file__='"'"'C:\\Users\\Jagdeep\\AppData\
\Local\\Temp\\pip-install-z9mjfyjb\\wordcloud_0913a61ca2de46e392daeafbf24661e0\\
setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.e
xists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"'
);code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(c
ode, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Jagdeep\AppData\Loca
l\Temp\pip-record-hz7efuy9\install-record.txt' --single-version-externally-manag
ed --compile --install-headers 'C:\Users\Jagdeep\anaconda3\Include\wordcloud' Ch
eck the logs for full command output.

**Comment by ngupta23** [comment]
Your error seems to be related to this one: https://github.com/pycaret/pycaret/issues/1254

```
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Micros
oft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
```

**Comment by ngupta23** [comment]
@jgdpsingh I am going to close this now. Feel free to reopen if the above does not resolve the installation issue.

**Comment by jgdpsingh** [comment]
I installed the Visual C++ 2019 but it's still showing the same issue. Can you help me out?

**Comment by ngupta23** [comment]
That is the only error in the message that you posted. If you are still getting the same message, maybe check that the Visual C++ 2019 installation happened correctly.

Alternately, try installing on Google Colab as it is working there.
