### ISSUE TITLE
AttributeError  -  Traceback (most recent call last)

### ISSUE THREAD

**Issue by lsfranco7** [pycaret/pycaret#2126]
**Describe the bug**

**To Reproduce**
<div class="output_area" style="box-sizing: border-box; padding: 0px; break-inside: avoid; -webkit-box-orient: horizontal; -webkit-box-align: stretch; display: flex; flex-direction: row; align-items: stretch; color: rgb(0, 0, 0); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="output_subarea output_html rendered_html" dir="auto" style="box-sizing: border-box; color: rgb(0, 0, 0); overflow-x: visible; padding: 0.4em; -webkit-box-flex: 1; flex: 1 1 0%; max-width: calc(100% - 14ex);"><br class="Apple-interchange-newline">
</div></div><div class="output_area" style="box-sizing: border-box; padding: 0px; break-inside: avoid; -webkit-box-orient: horizontal; -webkit-box-align: stretch; display: flex; flex-direction: row; align-items: stretch; color: rgb(0, 0, 0); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="prompt" style="box-sizing: border-box; min-width: 15ex; padding: 0px 0.4em; margin: 0px; font-family: monospace; text-align: right; line-height: 1.21429em; user-select: none; cursor: default;"></div><div class="output_subarea output_text output_error" dir="auto" style="box-sizing: border-box; overflow-x: visible; padding: 0.4em; -webkit-box-flex: 1; flex: 1 1 0%; max-width: calc(100% - 14ex); text-align: left; color: rgb(0, 0, 0); line-height: 1.21429em;"><pre style="box-sizing: border-box; overflow: auto; font-family: monospace; font-size: inherit; display: block; padding: 1px 0px; margin: 0px; line-height: inherit; color: black; word-break: break-all; overflow-wrap: break-word; background-color: transparent; border: 0px; border-radius: 0px; white-space: pre-wrap; vertical-align: baseline;"><span class="ansi-red-intense-fg ansi-bold" style="box-sizing: border-box; color: rgb(178, 43, 49); font-weight: bold;">---------------------------------------------------------------------------</span>
<span class="ansi-red-intense-fg ansi-bold" style="box-sizing: border-box; color: rgb(178, 43, 49); font-weight: bold;">AttributeError</span>                            Traceback (most recent call last)
Input <span class="ansi-green-intense-fg ansi-bold" style="box-sizing: border-box; color: rgb(0, 116, 39); font-weight: bold;">In [2]</span>, in <span class="ansi-cyan-fg" style="box-sizing: border-box; color: rgb(96, 198, 200);">&lt;module&gt;</span>
<span class="ansi-green-fg" style="box-sizing: border-box; color: rgb(0, 162, 80);">      6</span> best <span style="box-sizing: border-box; color: rgb(98, 98, 98);">=</span> compare_models(sort <span style="box-sizing: border-box; color: rgb(98, 98, 98);">=</span> <span style="box-sizing: border-box; color: rgb(175, 0, 0);">'</span><span style="box-sizing: border-box; color: rgb(175, 0, 0);">MAE</span><span style="box-sizing: border-box; color: rgb(175, 0, 0);">'</span>)
<span class="ansi-green-fg" style="box-sizing: border-box; color: rgb(0, 162, 80);">      7</span> results <span style="box-sizing: border-box; color: rgb(98, 98, 98);">=</span> pull()
<span class="ansi-green-intense-fg ansi-bold" style="box-sizing: border-box; color: rgb(0, 116, 39); font-weight: bold;">----&gt; 8</span> model_results <span style="box-sizing: border-box; color: rgb(98, 98, 98);">=</span> <span class="ansi-yellow-bg" style="box-sizing: border-box; background-color: rgb(221, 182, 43);">results</span><span class="ansi-yellow-bg" style="box-sizing: border-box; background-color: rgb(221, 182, 43); color: rgb(98, 98, 98);">.</span><span class="ansi-yellow-bg" style="box-sizing: border-box; background-color: rgb(221, 182, 43);">Model</span><span style="box-sizing: border-box; color: rgb(98, 98, 98);">.</span>tolist()
<span class="ansi-green-fg" style="box-sizing: border-box; color: rgb(0, 162, 80);">      9</span> best_model <span style="box-sizing: border-box; color: rgb(98, 98, 98);">=</span> model_results[<span style="box-sizing: border-box; color: rgb(98, 98, 98);">0</span>]
<span class="ansi-green-fg" style="box-sizing: border-box; color: rgb(0, 162, 80);">     10</span> <span style="box-sizing: border-box; color: rgb(0, 135, 0);">print</span>(best_model[<span style="box-sizing: border-box; color: rgb(98, 98, 98);">0</span>])

File <span class="ansi-green-intense-fg ansi-bold" style="box-sizing: border-box; color: rgb(0, 116, 39); font-weight: bold;">~\anaconda3\envs\pycaretnew\lib\site-packages\pandas\core\generic.py:5583</span>, in <span class="ansi-cyan-fg" style="box-sizing: border-box; color: rgb(96, 198, 200);">NDFrame.__getattr__</span><span class="ansi-blue-intense-fg ansi-bold" style="box-sizing: border-box; color: rgb(0, 101, 202); font-weight: bold;">(self, name)</span>
<span class="ansi-green-fg" style="box-sizing: border-box; color: rgb(0, 162, 80);">   5576</span> <span class="ansi-bold" style="box-sizing: border-box; font-weight: bold; color: rgb(0, 135, 0);">if</span> (
<span class="ansi-green-fg" style="box-sizing: border-box; color: rgb(0, 162, 80);">   5577</span>     name <span class="ansi-bold" style="box-sizing: border-box; font-weight: bold; color: rgb(175, 0, 255);">not</span> <span class="ansi-bold" style="box-sizing: border-box; font-weight: bold; color: rgb(175, 0, 255);">in</span> <span style="box-sizing: border-box; color: rgb(0, 135, 0);">self</span><span style="box-sizing: border-box; color: rgb(98, 98, 98);">.</span>_internal_names_set
<span class="ansi-green-fg" style="box-sizing: border-box; color: rgb(0, 162, 80);">   5578</span>     <span class="ansi-bold" style="box-sizing: border-box; font-weight: bold; color: rgb(175, 0, 255);">and</span> name <span class="ansi-bold" style="box-sizing: border-box; font-weight: bold; color: rgb(175, 0, 255);">not</span> <span class="ansi-bold" style="box-sizing: border-box; font-weight: bold; color: rgb(175, 0, 255);">in</span> <span style="box-sizing: border-box; color: rgb(0, 135, 0);">self</span><span style="box-sizing: border-box; color: rgb(98, 98, 98);">.</span>_metadata
<span class="ansi-green-fg" style="box-sizing: border-box; color: rgb(0, 162, 80);">   5579</span>     <span class="ansi-bold" style="box-sizing: border-box; font-weight: bold; color: rgb(175, 0, 255);">and</span> name <span class="ansi-bold" style="box-sizing: border-box; font-weight: bold; color: rgb(175, 0, 255);">not</span> <span class="ansi-bold" style="box-sizing: border-box; font-weight: bold; color: rgb(175, 0, 255);">in</span> <span style="box-sizing: border-box; color: rgb(0, 135, 0);">self</span><span style="box-sizing: border-box; color: rgb(98, 98, 98);">.</span>_accessors
<span class="ansi-green-fg" style="box-sizing: border-box; color: rgb(0, 162, 80);">   5580</span>     <span class="ansi-bold" style="box-sizing: border-box; font-weight: bold; color: rgb(175, 0, 255);">and</span> <span style="box-sizing: border-box; color: rgb(0, 135, 0);">self</span><span style="box-sizing: border-box; color: rgb(98, 98, 98);">.</span>_info_axis<span style="box-sizing: border-box; color: rgb(98, 98, 98);">.</span>_can_hold_identifiers_and_holds_name(name)
<span class="ansi-green-fg" style="box-sizing: border-box; color: rgb(0, 162, 80);">   5581</span> ):
<span class="ansi-green-fg" style="box-sizing: border-box; color: rgb(0, 162, 80);">   5582</span>     <span class="ansi-bold" style="box-sizing: border-box; font-weight: bold; color: rgb(0, 135, 0);">return</span> <span style="box-sizing: border-box; color: rgb(0, 135, 0);">self</span>[name]
<span class="ansi-green-intense-fg ansi-bold" style="box-sizing: border-box; color: rgb(0, 116, 39); font-weight: bold;">-&gt; 5583</span> <span class="ansi-bold" style="box-sizing: border-box; font-weight: bold; color: rgb(0, 135, 0);">return</span> <span class="ansi-yellow-bg" style="box-sizing: border-box; background-color: rgb(221, 182, 43); color: rgb(0, 135, 0);">object</span><span class="ansi-yellow-bg" style="box-sizing: border-box; background-color: rgb(221, 182, 43); color: rgb(98, 98, 98);">.</span><span class="ansi-yellow-bg" style="box-sizing: border-box; background-color: rgb(221, 182, 43); color: rgb(0, 0, 255);">__getattribute__</span><span class="ansi-yellow-bg" style="box-sizing: border-box; background-color: rgb(221, 182, 43);">(</span><span class="ansi-yellow-bg" style="box-sizing: border-box; background-color: rgb(221, 182, 43); color: rgb(0, 135, 0);">self</span><span class="ansi-yellow-bg" style="box-sizing: border-box; background-color: rgb(221, 182, 43);">,</span><span class="ansi-yellow-bg" style="box-sizing: border-box; background-color: rgb(221, 182, 43);"> </span><span class="ansi-yellow-bg" style="box-sizing: border-box; background-color: rgb(221, 182, 43);">name</span><span class="ansi-yellow-bg" style="box-sizing: border-box; background-color: rgb(221, 182, 43);">)</span>

<span class="ansi-red-intense-fg ansi-bold" style="box-sizing: border-box; color: rgb(178, 43, 49); font-weight: bold;">AttributeError</span>: 'DataFrame' object has no attribute 'Model'</pre></div></div>
</body>
</html>
-->

```python
# Model Definitions
s = setup(data = train_df, test_data = test_df, target = dependent_col, fold_strategy = 'timeseries', 
          numeric_features = feature_cols, fold = 3, transform_target = True, session_id = 123)

# Creates model comparison matrix
best = compare_models(sort = 'MAE')
results = pull()
model_results = results.Model.tolist()
best_model = model_results[0]
print(best_model[0])
```

**Expected behavior**
 Get the model prediction summary metrics

**Additional context**

**Versions**
<details>

 '2.3.6'

</details>

**Comment by ngupta23** [comment]
`results` is a Pandas dataframe and it does not have an attribute call Models. This is not a pycaret bug.
