### ISSUE TITLE
Train the model with 100% of the data instead of train_size<1.0

### ISSUE THREAD

**Issue by GDGauravDutta** [pycaret/pycaret#2127]
Train the model with 100% of the data instead of train_size<1.0

Presently, we don't have this feature, which is restricting us to use it any competitions.

finalize_model(parameters) is retraining the same train data again.

**Comment by ngupta23** [comment]
The idea behind modeling would be to make a model that can be generalized to an unknown dataset. In the case of any competition, this unknown dataset would be the private leaderboard datasets. So you can (and should) still use the recommended methodology of performing a train-test split on the public dataset, then cross-validate the train split. Once you are happy with the results, you can finalize the model which will train on the entire public dataset (train + test split). You can then use this to submit your predictions. This will be the best strategy to ensure that you do not overfit to the public dataset and score well on the private leaderboard.


> finalize_model(parameters) is retraining the same train data again.

I am not sure what you mean by this. But based on the wording, this is not correct. `finalize_model` trains on the "Train + Test" split.

**Comment by GDGauravDutta** [comment]
I am able to see final showing train data only .

**Comment by ngupta23** [comment]
> I am able to see final showing train data only .

I am not sure what you mean. You will need to provide a reproducible example of what is going on (data + code) for someone to debug further.
