### ISSUE TITLE
Compare_models() to show how model performed at test results

### ISSUE THREAD

**Issue by GDGauravDutta** [pycaret/pycaret#2129]
As an user I loved how compare_models() shows the report of how model performed in trained data. 

I want same to be shown for test data too so as I can visualise how all models performed in test data. 

This will help users to decide the best model upon performance of model in train & test data. 

This will help community to have excellent models rather than thinking how other models may have performed in same test data.

**Comment by ngupta23** [comment]
Using metrics from test data to decide the "best" models defeats the purpose of the test data. Test data is an independent dataset that should not be used to make any decision about hyperparameters or the best model. It is only for reporting purposes.

**Comment by GDGauravDutta** [comment]
It will help to know how good model performed.

Example : rf has good score in training but maybe bad in test data.

If we have a function to show train & test data result for multiple models . It helps to improve our models

**Comment by ngupta23** [comment]
I think what you are really looking for is the comparison of the cross-validation "train" and cross-validation "validation" scores used in cross validation. There is an open Issue for this already. https://github.com/pycaret/pycaret/issues/1909

Using test scores to make decisions will lead to overfitting on the test data. Ideally you want to avoid that and keep the tests data completely separate and not use it for decision making.
