### ISSUE TITLE
KeyError Issue

### ISSUE THREAD

**Issue by robert-hoyt** [pycaret/pycaret#214]
I am following the PyCaret tutorial on classification and using CoLab. I loaded the data with this script from pycaret.datasets import get_data
dataset = get_data('credit', profile=True).    and received this KeyError message below

KeyError                                  Traceback (most recent call last)
<ipython-input-3-a7336600326f> in <module>()
      1 from pycaret.datasets import get_data
----> 2 dataset = get_data('credit', profile=True)

5 frames
/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py in _validate_index_level(self, level)
   1414         elif level != self.name:
   1415             raise KeyError(
-> 1416                 f"Requested level ({level}) does not match index name ({self.name})"
   1417             )
   1418 

KeyError: 'Requested level (var1) does not match index name (None)'

**Comment by robert-hoyt** [comment]
I uploaded the data through Colab and no longer got the error

**Comment by robert-hoyt** [comment]
Closed

**Comment by Taneja-Siddharth** [comment]
@robert-hoyt Hi! I am having the same issue. I am a little unclear about how you fixed this issue. I am running the tutorial on Jupyter Notebook.

**Comment by reenal** [comment]
Hi @Taneja-Siddharth  

step1)  go to your your pycaret environment  whichever you are using activate it
step2)  pip install --upgrade pandas-profiling    
sterp3) environment  go to where all library are insatlled (in  my case) C:\Users\hp\AppData\Roaming\Python\Python36\site-packages\pycaret
step4) open datasets.py
from IPython.display import display
step5)
run code
from pycaret.datasets import get_data
dataset = get_data('credit',profile= True)
print(dataset.head())
step6)
see output 
any help please connect
![Untitled](https://user-images.githubusercontent.com/7302199/88287472-a0ca8400-ccf2-11ea-879d-064e8dac676b.png)
