### ISSUE TITLE
pip package manager issue on colab [BUG]

### ISSUE THREAD

**Issue by Muhtasham** [pycaret/pycaret#2143]
**Describe the bug**

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.27.1 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible. 
WARNING: The following packages were previously imported in this runtime:
  [requests,scipy]

**To Reproduce**

```python
pip install pycaret
```

**Additional context**
Also while installing the full version it gets stucks at installing statsmodels

**Comment by ngupta23** [comment]
It is installing correctly for me (version 2.3.6). Can you check again? Maybe it was a temporary issue. Another thing to check is whether you are installing any other packages that may be interfering with the installation of `pycaret`.

![image](https://user-images.githubusercontent.com/33585645/153652033-22e95a78-0b06-4a54-9a09-d581af1dd856.png)
