### ISSUE TITLE
[BUG] sklearn 0.24.2

### ISSUE THREAD

**Issue by DongningS** [pycaret/pycaret#2145]
I encounter this issue due to incompatibility od sklearn version.

codes to reproduce this problem 
python

**Versions**
python 3.8.8

**Comment by ngupta23** [comment]
It is not clear from your message what the real issue you are facing. Please elaborate with as much detail as you can. Thanks!

**Comment by ngupta23** [comment]
In the mean time, this might be helpful: https://github.com/pycaret/pycaret/issues/1847
