### ISSUE TITLE
Prediction Probabilities in Classification

### ISSUE THREAD

**Issue by aljubrmj** [pycaret/pycaret#215]
predict_model() returns the label and score. Can we also return the prediction probabilities? 

I did it personally by simply saving the sklearn pipe and model objects, and then running them using sklearn methods.

**Comment by aliagowani** [comment]
Aljubrmj,

I am curious how were you able to save the sklearn pipe and model objects. Would you mind sharing the code?

**Comment by subhash-tm** [comment]
Hi i am getting error on classification 
 File "/root/venv/lib/python3.6/site-packages/pycaret/classification.py", line 7975, in predict_model
    pred_ = model.predict(Xtest)
AttributeError: 'tuple' object has no attribute 'predict'

**Comment by aljubrmj** [comment]
@subhash-tm, the model object you are using is a tuple. Find out which tuple element is the model and extract it first. 

@aliagowani, consider the following code/pseudocode:

`clf1 = setup(data = DATA, target = TARGET, train_size = 0.9)
prep_pipe = clf1[-1][-1][1]
model = tune_model(MODEL)

model.predict_proba(prep_pipe.transform(EXAMPLE))
`

**Comment by subhash-tm** [comment]
@aljubrmj Thanks you

**Comment by aliagowani** [comment]
Thanks @aljubrmj. This is exactly what I was looking for.

**Comment by azharirfan** [comment]
> @subhash-tm, the model object you are using is a tuple. Find out which tuple element is the model and extract it first.
> 
> @aliagowani, consider the following code/pseudocode:
> 
> `clf1 = setup(data = DATA, target = TARGET, train_size = 0.9)`
> `prep_pipe = clf1[-1][-1][1]`
> `model = tune_model(ALGORITHM)`
> `model.predict_proba(prep_pipe.transform(EXAMPLE))`

Hi, just for clarity, what needs to be passed in place of EXAMPLE for the command "model.predict_proba(prep_pipe.transform(EXAMPLE))"

**Comment by pycaret** [comment]
@azharirfan Thanks.

@subhash-tm In **pycaret.classification** when you use **predict_model** it returns two columns "Label" and "Score". "Score" column is probability of positive outcome. If its binary you can calculate the probability of other class by 1 - Score. 

Also you can access **predict_proba** from model. For example:
lr = create_model('lr')
lr_predict_proba = lr.predict_proba()

Thanks.

**Comment by aljubrmj** [comment]
@azharirfan EXAMPLE is your input data

@pycaret would this work if I have a prep pipe in a multi-class model?

**Comment by lbaiao** [comment]
When I use the model for inference, on a new DataFrame, the `predict_model` method does not return the 'Scores' column. How can I get these probabilities?

Ex. : `predict_model(my_model, data=new_df)`

**Comment by pycaret** [comment]
Which model are you using? Certain algorithms do not support predict_proba and hence for those there will be no score.

**Comment by lbaiao** [comment]
I am using random forest. If I use the `predict_model`, with the data passed on `setup`, it returns the Scores.

ex.: `predict_model(rf)`

**Comment by pycaret** [comment]
@lbaiao Please attach the notebook here. I cannot reproduce the issue at my end. Which version are you using? I am using `2.1.2`

**Comment by lbaiao** [comment]
@pycaret  I can't post the notebook, because of the data. I was not able to reproduce the bug with public data, or the pycaret datasets. However, I can paste a print screen.

![image](https://user-images.githubusercontent.com/25750921/92001469-1889c680-ed15-11ea-84a9-dd449e389712.png)

**Comment by Yard1** [comment]
`get_config('prep_pipe')` will return the pipeline used.

**Comment by lbaiao** [comment]
@Yard1 Thanks! That was helpful.

**Comment by muriloafonso** [comment]
The Score column in predict_model () is returning a value of 0.5 to 1, instead of 0 to 1. How can I fix this?

**Comment by soaring52** [comment]
predict_model(estimator, data=None, probability_threshold=None, platform=None, authentication=None, verbose=True)

**probability_threshold** : float, default = None
threshold used to convert probability values into binary outcome. By default the probability threshold for all binary classifiers is 0.5 (50%). **This can be changed using probability_threshold param**.

**Comment by PranayMehta** [comment]
> The Score column in predict_model () is returning a value of 0.5 to 1, instead of 0 to 1. How can I fix this?

I am also facing a similar issue in my models. Whatever models I create, I end up assigning score that ranges from 0.5 to 1.0 instead of 0.0 to 1.0 

I am using 2.2 version. Not sure if something has changed in here.

**Comment by PranayMehta** [comment]
> predict_model(estimator, data=None, probability_threshold=None, platform=None, authentication=None, verbose=True)
> 
> **probability_threshold** : float, default = None
> threshold used to convert probability values into binary outcome. By default the probability threshold for all binary classifiers is 0.5 (50%). **This can be changed using probability_threshold param**.

How is this parameter linked with the score that model generates ? If the model generates raw probabilities, then that is the first step that happens during scoring, the threshold parameter is just there to create your own decision boundary. It does not have anything to do with the actual raw scores that model generates.

**Comment by Yard1** [comment]
By default `predict_model` returns the probability of the *predicted* class as a score. If you want the same output sklearn would give you, you need to pass the `raw_score=True` argument to `predict_model`.

**Comment by PranayMehta** [comment]
> raw_score=True

I ran the above mentioned code @Yard1  But I got below error 

![image](https://user-images.githubusercontent.com/23047253/121959363-aed22a80-cd32-11eb-92f4-898f1dfcf2b3.png)

**Comment by Yard1** [comment]
You need to update to the latest PyCaret version (2.2.3). `pip install -U pycaret`
