### ISSUE TITLE
pycaret-ts-alpha can't install [BUG]

### ISSUE THREAD

**Issue by relic-yuexi** [pycaret/pycaret#2173]
**Describe the bug**
When i create a new conda enviroment, and use the `pip install pycaret-ts-alpha` to install that.
I get some wrong.
![QQ截图20220218125837](https://user-images.githubusercontent.com/53668275/154621044-79322f63-bc54-41d9-9d9d-19323e30d501.png)
My python version is 3.9.7.
`ERROR: Failed building wheel for scikit-learn`

**To Reproduce**

```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by moezali1** [comment]
@relic-yuexi I just tried installing `pycaret-ts-alpha` and it worked without any errors.

Check out this Notebook: https://colab.research.google.com/drive/1s6aaaKNCOyNkFCy2LpbWyVNtIZIbRXU4?usp=sharing
