### ISSUE TITLE
how to save figures in high resolution in dashboard

### ISSUE THREAD

**Issue by Jie-NB** [pycaret/pycaret#2174]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**
A clear and concise description of what you want to happen, ideally taking into consideration the existing toolbox design, classes and methods. 

**Describe alternatives you've considered**

**Additional context**

**Comment by moezali1** [comment]
@Jie-NB For that, you will have to raise a request on this repo: https://github.com/oegedijk/explainerdashboard
