### ISSUE TITLE
Compare_model() error 

### ISSUE THREAD

**Issue by GHENA-NIZAR** [pycaret/pycaret#2178]
Hi, I was trying to implement a classification model for the iris data set using the following code :
```
from pycaret.datasets import get_data
data = get_data('iris')
from pycaret.classification  import *
s = setup(data, target = 'species',n_jobs=1)
compare_models()
```
and I don't know what I'm doing wrong to receive this error from the compare_models function :

> AttributeError                            Traceback (most recent call last)
<ipython-input-56-1ad10be5dc92> in <module>
      3 from pycaret.classification  import *
      4 s = setup(data, target = 'species',n_jobs=1)
----> 5 compare_models()

~\Anaconda3\lib\site-packages\pycaret\classification.py in compare_models(include, exclude, fold, round, cross_validation, sort, n_select, budget_time, turbo, errors, fit_kwargs, groups, probability_threshold, verbose)
    777     probability_threshold: float, default = None
    778         Threshold for converting predicted probability to class label.
--> 779         It defaults to 0.5 for all classifiers unless explicitly defined
    780         in this parameter. Only applicable for binary classification.
    781 

~\Anaconda3\lib\site-packages\pycaret\internal\tabular.py in compare_models(include, exclude, fold, round, cross_validation, sort, n_select, budget_time, turbo, errors, fit_kwargs, groups, probability_threshold, verbose, display)
   2070     groups = _get_groups(groups)
   2071 
-> 2072     pd.set_option("display.max_columns", 500)
   2073 
   2074     logger.info("Preparing display monitor")

~\Anaconda3\lib\site-packages\pycaret\internal\Display.py in __init__(self, verbose, html_param, progress_args, master_display_columns, monitor_rows, round)
    167 
    168         if master_display_columns:
--> 169             self.master_display = pd.DataFrame(columns=master_display_columns)
    170 
    171         if monitor_rows and self.html_param:

~\Anaconda3\lib\site-packages\pandas\core\frame.py in __init__(self, data, index, columns, dtype, copy)
    433             )
    434         elif isinstance(data, dict):
--> 435             mgr = init_dict(data, index, columns, dtype=dtype)
    436         elif isinstance(data, ma.MaskedArray):
    437             import numpy.ma.mrecords as mrecords

~\Anaconda3\lib\site-packages\pandas\core\internals\construction.py in init_dict(data, index, columns, dtype)
    237             else:
    238                 nan_dtype = dtype
--> 239             val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
    240             arrays.loc[missing] = [val] * missing.sum()
    241 

~\Anaconda3\lib\site-packages\pandas\core\dtypes\cast.py in construct_1d_arraylike_from_scalar(value, length, dtype)
   1447     else:
   1448         if not isinstance(dtype, (np.dtype, type(np.dtype))):
-> 1449             dtype = dtype.dtype
   1450 
   1451         if length and is_integer_dtype(dtype) and isna(value):

AttributeError: type object 'object' has no attribute 'dtype'

**Comment by moezali1** [comment]
@GHENA-NIZAR I tried reproducing this error but I cannot. It seems like must be related to your environment.

Here is the link to Notebook where I cannot reproduce this error:

https://colab.research.google.com/drive/1krFnjXls27_Dc0S5BWq3FjHvNzdSbqmm?usp=sharing
