### ISSUE TITLE
Preprocessed Dataframe

### ISSUE THREAD

**Issue by UjwalTalele** [pycaret/pycaret#218]
I want to extract the preprocessed dataframe which is generated after setup. Could'nt find any way to do is so far, suggestions requested.

**Comment by pycaret** [comment]
@UjwalTalele You can access the preprocessed dataset stored in object returned upon setup. For example:

s = setup(data, target='target')

X_train = s[2]
X_test = s[3]
y_train = s[4]
y_test = s[5]

Thanks.

**Comment by pranavchat14** [comment]
Every time I run this, I get different values for s[2]. Sometimes it's a dataframe, other times it's a dictionary. Any idea why is that happening?

**Comment by pranavchat14** [comment]
This is very convenient. Thanks.
