### ISSUE TITLE
[BUG] Error importing from pycaret.time_series

### ISSUE THREAD

**Issue by lucazav** [pycaret/pycaret#2184]
I've just create a new environment with Python 3.8 and I've just installed the time series module using this code:

`pip install pycaret-ts-alpha
`

When I try to import stuff using this:

`from pycaret.time_series import *`

I get the following error:

> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> Untitled-1 in <module>
>       <a href='untitled:Untitled-1?line=3'>[4](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/pycaret/internal/pycaret_experiment/__init__.py?line=3)</a> import pandas as pd
>       <a href='untitled:Untitled-1?line=[5](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/pycaret/internal/pycaret_experiment/__init__.py?line=4)'>[6](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/pycaret/internal/pycaret_experiment/__init__.py?line=5)</a> from pycaret.datasets import get_data
> ----> <a href='untitled:Untitled-1?line=6'>7</a> from pycaret.internal.pycaret_experiment import TimeSeriesExperiment
> 
> File ~\miniconda3\envs\pycaret_env\lib\site-packages\pycaret\internal\pycaret_experiment\__init__.py:6, in <module>
>       4 from .classification_experiment import ClassificationExperiment
>       5 from .regression_experiment import RegressionExperiment
> ----> 6 from .time_series_experiment import TimeSeriesExperiment
>       [8](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/pycaret/internal/pycaret_experiment/__init__.py?line=7) from .utils import MLUsecase
>      [11](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/pycaret/internal/pycaret_experiment/__init__.py?line=10) def experiment_factory(usecase: MLUsecase):
> 
> File ~\miniconda3\envs\pycaret_env\lib\site-packages\pycaret\internal\pycaret_experiment\time_series_experiment.py:36, in <module>
>      [33](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/pycaret/internal/pycaret_experiment/time_series_experiment.py?line=32) from pycaret.internal.tunable import TunableMixin
>      [35](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/pycaret/internal/pycaret_experiment/time_series_experiment.py?line=34) import pycaret.containers.metrics.time_series
> ---> [36](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/pycaret/internal/pycaret_experiment/time_series_experiment.py?line=35) import pycaret.containers.models.time_series
>      [37](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/pycaret/internal/pycaret_experiment/time_series_experiment.py?line=36) import pycaret.internal.preprocess
>      [38](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/pycaret/internal/pycaret_experiment/time_series_experiment.py?line=37) import pycaret.internal.persistence
> 
> File ~\miniconda3\envs\pycaret_env\lib\site-packages\pycaret\containers\models\time_series.py:21, in <module>
>      [19](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/pycaret/containers/models/time_series.py?line=18) from sktime.forecasting.compose import make_reduction, TransformedTargetForecaster  # type: ignore
>      [20](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/pycaret/containers/models/time_series.py?line=19) from sktime.forecasting.trend import PolynomialTrendForecaster  # type: ignore
> ---> [21](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/pycaret/containers/models/time_series.py?line=20) from sktime.transformations.series.detrend import ConditionalDeseasonalizer, Detrender  # type: ignore
>      [22](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/pycaret/containers/models/time_series.py?line=21) from sktime.forecasting.base._sktime import DEFAULT_ALPHA  # type: ignore
>      [23](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/pycaret/containers/models/time_series.py?line=22) from sklearn.utils.validation import check_is_fitted  # type: ignore
> 
> File ~\miniconda3\envs\pycaret_env\lib\site-packages\sktime\transformations\series\detrend\__init__.py:8, in <module>
>       [5](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/sktime/transformations/series/detrend/__init__.py?line=4) __author__ = ["mloning", "eyalshafran", "SveaMeyer13"]
>       [6](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/sktime/transformations/series/detrend/__init__.py?line=5) __all__ = ["Detrender", "Deseasonalizer", "ConditionalDeseasonalizer", "STLTransformer"]
> ----> [8](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/sktime/transformations/series/detrend/__init__.py?line=7) from sktime.transformations.series.detrend._deseasonalize import (
>       [9](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/sktime/transformations/series/detrend/__init__.py?line=8)     ConditionalDeseasonalizer,
>      [10](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/sktime/transformations/series/detrend/__init__.py?line=9)     Deseasonalizer,
>      [11](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/sktime/transformations/series/detrend/__init__.py?line=10)     STLTransformer,
>      [12](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/sktime/transformations/series/detrend/__init__.py?line=11) )
>      [13](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/sktime/transformations/series/detrend/__init__.py?line=12) from sktime.transformations.series.detrend._detrend import Detrender
> 
> File ~\miniconda3\envs\pycaret_env\lib\site-packages\sktime\transformations\series\detrend\_deseasonalize.py:11, in <module>
>       [9](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/sktime/transformations/series/detrend/_deseasonalize.py?line=8) import numpy as np
>      [10](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/sktime/transformations/series/detrend/_deseasonalize.py?line=9) import pandas as pd
> ---> [11](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/sktime/transformations/series/detrend/_deseasonalize.py?line=10) from statsmodels.tsa.seasonal import STL as _STL
>      [12](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/sktime/transformations/series/detrend/_deseasonalize.py?line=11) from statsmodels.tsa.seasonal import seasonal_decompose
>      [14](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/sktime/transformations/series/detrend/_deseasonalize.py?line=13) from sktime.forecasting.base._fh import _check_cutoff, _coerce_to_period
> 
> File ~\miniconda3\envs\pycaret_env\lib\site-packages\statsmodels\tsa\seasonal.py:12, in <module>
>      [10](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/statsmodels/tsa/seasonal.py?line=9) from statsmodels.tools.validation import PandasWrapper, array_like
>      [11](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/statsmodels/tsa/seasonal.py?line=10) from statsmodels.tsa._stl import STL
> ---> [12](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/statsmodels/tsa/seasonal.py?line=11) from statsmodels.tsa.filters.filtertools import convolution_filter
>      [13](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/statsmodels/tsa/seasonal.py?line=12) from statsmodels.tsa.tsatools import freq_to_period
>      [15](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/statsmodels/tsa/seasonal.py?line=14) __all__ = ['STL', 'seasonal_decompose', 'seasonal_mean', 'DecomposeResult']
> 
> File ~\miniconda3\envs\pycaret_env\lib\site-packages\statsmodels\tsa\filters\filtertools.py:18, in <module>
>      [16](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/statsmodels/tsa/filters/filtertools.py?line=15) import scipy.fftpack as fft
>      [17](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/statsmodels/tsa/filters/filtertools.py?line=16) from scipy import signal
> ---> [18](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/statsmodels/tsa/filters/filtertools.py?line=17) from scipy.signal.signaltools import _centered as trim_centered
>      [20](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/statsmodels/tsa/filters/filtertools.py?line=19) from statsmodels.tools.validation import array_like, PandasWrapper
>      [22](file:///~/miniconda3/envs/pycaret_env/lib/site-packages/statsmodels/tsa/filters/filtertools.py?line=21) def _pad_nans(x, head=None, tail=None):
> 
> ImportError: cannot import name '_centered' from 'scipy.signal.signaltools' (C:\Users\LucaZavarella\miniconda3\envs\pycaret_env\lib\site-packages\scipy\signal\signaltools.py)

**Comment by ngupta23** [comment]
You probably have scipy 1.8.x installed. Can you downgrade to 1.7.x and try. scipy made some breaking changes in 1.8.x.

**Comment by lucazav** [comment]
I installed just the` pycaret_ts_alpha` package in a new environment. So I suppose there is a reference to the wrong version of SciPy in it.

**Comment by moezali1** [comment]
@lucazav @ngupta23 

I just did a fresh installation on Google Colab and it worked without any problem. 

Here is the link to Notebook: https://colab.research.google.com/drive/1s6aaaKNCOyNkFCy2LpbWyVNtIZIbRXU4?usp=sharing

![image](https://user-images.githubusercontent.com/54699234/154806120-7ab4064b-047f-412c-acc8-c10251309561.png)

No further action is needed.

**Comment by lucazav** [comment]
Ok, I created my environment with Python 3.8. You're using Python 3.7. Maybe the 3.8 version cause the error.
