### ISSUE TITLE
Time Series bug (univariate)

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#2186]
Using `time_series` branch you can reproduce this error:

```
import numpy as np
import pandas as pd
from pycaret.internal.pycaret_experiment import TimeSeriesExperiment

data = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/pollution.csv', 
                  parse_dates= {"date" : ["year","month","day"]})
data.rename(columns = {'pm2.5' : 'pm25'}, inplace=True)
data = data.groupby(by='date').mean()
data.dropna(inplace=True)
data = data['pm25']
data = data.asfreq('D')
data.head()

exp_auto = TimeSeriesExperiment()
exp_auto.setup(data=data, fh=365, session_id=123)
best = exp_auto.compare_models(errors = 'raise')
```
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\externals\loky\process_executor.py", line 431, in _process_worker
    r = call_item()
  File "C:\Users\owner\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\externals\loky\process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\owner\pycaret\pycaret\utils\time_series\forecasting\model_selection.py", line 132, in _fit_and_score
    raise ValueError(
ValueError: y_test indices do not match y_pred_indices or split/prediction length does not match forecast horizon.
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_31996/3899222376.py in <module>
----> 1 best = exp_auto.compare_models(errors = 'raise')

~\pycaret\pycaret\internal\pycaret_experiment\time_series_experiment.py in compare_models(self, include, exclude, fold, round, cross_validation, sort, n_select, budget_time, turbo, errors, fit_kwargs, verbose)
   1055         """
   1056 
-> 1057         return super().compare_models(
   1058             include=include,
   1059             exclude=exclude,

~\pycaret\pycaret\internal\pycaret_experiment\supervised_experiment.py in compare_models(self, include, exclude, fold, round, cross_validation, sort, n_select, budget_time, turbo, errors, fit_kwargs, groups, probability_threshold, verbose, display)
    776             results_columns_to_ignore = ["Object", "runtime", "cutoff"]
    777             if errors == "raise":
--> 778                 model, model_fit_time = self.create_model(**create_model_args)
    779                 model_results = self.pull(pop=True)
    780             else:

~\pycaret\pycaret\internal\pycaret_experiment\time_series_experiment.py in create_model(self, estimator, fold, round, cross_validation, fit_kwargs, verbose, **kwargs)
   1173 
   1174         """
-> 1175         return super().create_model(
   1176             estimator=estimator,
   1177             fold=fold,

~\pycaret\pycaret\internal\pycaret_experiment\supervised_experiment.py in create_model(self, estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, probability_threshold, verbose, system, add_to_model_list, X_train_data, y_train_data, metrics, display, **kwargs)
   1534             return model
   1535 
-> 1536         model, model_fit_time, model_results, avgs_dict = self._create_model_with_cv(
   1537             model,
   1538             data_X,

~\pycaret\pycaret\internal\pycaret_experiment\time_series_experiment.py in _create_model_with_cv(self, model, data_X, data_y, fit_kwargs, round, cv, groups, metrics, refit, system, display)
   1287 
   1288         additional_scorer_kwargs = self.get_additional_scorer_kwargs()
-> 1289         scores, cutoffs = cross_validate(
   1290             # Commented out since supervised_experiment also does not clone
   1291             # when doing cross_validate

~\pycaret\pycaret\utils\time_series\forecasting\model_selection.py in cross_validate(forecaster, y, X, cv, scoring, fit_params, n_jobs, return_train_score, error_score, verbose, **additional_scorer_kwargs)
    229         parallel = Parallel(n_jobs=n_jobs)
    230 
--> 231         out = parallel(
    232             delayed(_fit_and_score)(
    233                 forecaster=clone(forecaster),

~\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\parallel.py in __call__(self, iterable)
   1052 
   1053             with self._backend.retrieval_context():
-> 1054                 self.retrieve()
   1055             # Make sure that we get a last message telling us we are done
   1056             elapsed_time = time.time() - self._start_time

~\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\parallel.py in retrieve(self)
    931             try:
    932                 if getattr(self._backend, 'supports_timeout', False):
--> 933                     self._output.extend(job.get(timeout=self.timeout))
    934                 else:
    935                     self._output.extend(job.get())

~\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

~\anaconda3\envs\pycaret-ts\lib\concurrent\futures\_base.py in result(self, timeout)
    442                     raise CancelledError()
    443                 elif self._state == FINISHED:
--> 444                     return self.__get_result()
    445                 else:
    446                     raise TimeoutError()

~\anaconda3\envs\pycaret-ts\lib\concurrent\futures\_base.py in __get_result(self)
    387         if self._exception:
    388             try:
--> 389                 raise self._exception
    390             finally:
    391                 # Break a reference cycle with the exception in self._exception

ValueError: y_test indices do not match y_pred_indices or split/prediction length does not match forecast horizon.

![image](https://user-images.githubusercontent.com/54699234/154817451-7d2bf3d0-1f68-48ec-8d5c-327b3e08aa47.png)

I have reproduced this bug on `pycaret-ts-alpha` on colab. https://colab.research.google.com/drive/1QFf8_ebO0yTtf7uxyRWiCVMjIBuCMfq6?usp=sharing

**Comment by ngupta23** [comment]
I think the data has missing values. Until imputation is implemented, the data  needs to be imputed before passing to pycaret. Can you try that and see if it resolves the problem?

**Comment by moezali1** [comment]
@ngupta23 You are right.

![image](https://user-images.githubusercontent.com/54699234/154886206-af16105e-c39f-4d2b-ae70-e871cfeff829.png)
