### ISSUE TITLE
[BUG] Unable to impute data on test data before prediction_model like we can do during compare models.

### ISSUE THREAD

**Issue by prabhakaran2812** [pycaret/pycaret#2192]
**Describe the bug**

**To Reproduce**

```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by ngupta23** [comment]
There is not enough information here to reproduce the error. Please submit a Minimally Reproducible Example per

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by prabhakaran2812** [comment]
I will open a feature request though.
