### ISSUE TITLE
[BUG] Prophet Model Not available in list of estimators

### ISSUE THREAD

**Issue by vermaankitttn** [pycaret/pycaret#2194]
I am trying to use the beta version of the time series module of the pycaret. On analysing I found that though in tutorials it is mentioned that prophet model can be used, however it is not available in list of estimators

**To Reproduce**

1) Create a new virtual environment
2) Install pycaret-ts-alpha library
3) run setup function and check models(), fbprophet is not available
4) create fbprophet model
prophet = create_model('prophet')
print(prophet)
 ERROR:-
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [14], in <module>
# create fbprophet model
 prophet = exp.create_model('prophet')
  print(prophet)

File ~\anaconda3\envs\pycaret_ts_alpha\lib\site-packages\pycaret\internal\pycaret_experiment\time_series_experiment.py:1583, in TimeSeriesExperiment.create_model(self, estimator, fold, round, cross_validation, fit_kwargs, verbose, **kwargs)
   1480 def create_model(
   1481     self,
   1482     estimator: Union[str, Any],
   (...)
   1488     **kwargs,
   1489 ):
   1491     """
   1492     This function trains and evaluates the performance of a given estimator
   1493     using cross validation. The output of this function is a score grid with
   (...)
   1581 
   1582     """
-> 1583     return super().create_model(
   1584         estimator=estimator,
   1585         fold=fold,
   1586         round=round,
   1587         cross_validation=cross_validation,
   1588         fit_kwargs=fit_kwargs,
   1589         verbose=verbose,
   1590         **kwargs,
   1591     )

File ~\anaconda3\envs\pycaret_ts_alpha\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py:1336, in _SupervisedExperiment.create_model(self, estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, probability_threshold, verbose, system, add_to_model_list, X_train_data, y_train_data, metrics, display, **kwargs)
   1334 if isinstance(estimator, str):
   1335     if estimator not in available_estimators:
-> 1336         raise ValueError(
   1337             f"Estimator {estimator} not available. Please see docstring for list of available estimators."
   1338         )
   1339 elif not hasattr(estimator, "fit"):
   1340     raise ValueError(
   1341         f"Estimator {estimator} does not have the required fit() method."
   1342     )

ValueError: Estimator prophet not available. Please see docstring for list of available estimators.

**Comment by ngupta23** [comment]
Prophet is an optional dependency in `pycaret`. You will need to install it on your own. It does not get installed when you install pycaret-ts-alpha.
