### ISSUE TITLE
[BUG] plot_model and evaluate_model() is not showing results

### ISSUE THREAD

**Issue by phdwight** [pycaret/pycaret#2196]
**Describe the bug**

executing the plot_model and evaluate_model does not return anything

**To Reproduce**

When trying to execute the following code:
```python
plot_model(tuned_rf, 'confusion_matrix')
```
or 
```python
evaluate_model(tuned_rf)
```
- and clicking on the confusion matrix 
here is the notebook: https://github.com/phdwight/machinelearning_experiments/blob/main/Wine%20Quality%20ML%20Experiment%20-%20Binary%20Classification.ipynb

**Expected behavior**

a confusion matrix is shown
**Additional context**

**Versions**
'2.3.6'
<details>

</details>

**Comment by moezali1** [comment]
@phdwight I executed your notebook and it works perfectly fine. `evaluate_model` uses interactive widget that's why you will not see it when you are viewing Notebook on GitHub.
