### ISSUE TITLE
Mac OS pycaret installation

### ISSUE THREAD

**Issue by mgabmgabmgab** [pycaret/pycaret#2197]

**Comment by mgabmgabmgab** [comment]
I use this website as reference : https://docs.python.org/3/tutorial/venv.html

**Comment by ngupta23** [comment]
These resources might help: 

[Link 1](https://pareekshithkatti.medium.com/setting-up-python-for-data-science-on-m1-mac-ced8a0d05911)
[Link 2](https://dschloe.github.io/python/python_edu/00_settings/pycaret_installation_on_m1_mac/)
