### ISSUE TITLE
Vocab Size showing zero while using NLP (pycaret.nlp)

### ISSUE THREAD

**Issue by TechyNilesh** [pycaret/pycaret#22]
Can you please provides the solution about this, I try many data but **vocab size is showing zero** and not working **create_model('lda')**, showing error _**"cannot compute LDA over an empty collection (no terms)"**_

I attached screen shot also you can see below..?
![12](https://user-images.githubusercontent.com/49296182/79642485-5c8f8b00-81bb-11ea-96c3-05170e0582d7.PNG)

**Comment by pycaret** [comment]
Hi, 

Thanks for asking. You should be passing target = 'text' because the column containing text is named 'text'. So it should be following code:

exp_nlp = setup(data=df, target='text')

Let me know how it goes.

Thanks.

**Comment by TechyNilesh** [comment]
Acutely I want to compare my text classification like you provide but its not tracking TFidf vector...How we can use Text classification in your library..??

**Comment by pycaret** [comment]
Hi,

Do you want to use text in your dataset to eventually build a classification model that predict label named 'target' in dataset?

Thanks.

**Comment by TechyNilesh** [comment]
Yes

**Comment by pycaret** [comment]
follow this code:
dataframe stored in variable df

from pycaret.nlp import *
nlp1 = setup(data=df, target = 'text')
lda = create_model('lda', num_topics = 4)
lda_results = assign_model(lda)

from pycaret.classification import *
clf1 = setup(data = lda_results, target = 'target')

# compare all models
compare_models()

**Comment by TechyNilesh** [comment]
I think you should change the technique of tacking dataframe instead of that you should tack input of X(input) and Y(target) like other algorithms are tacking. Its easy for peoples

**Comment by pycaret** [comment]
PyCaret's API is built to work directly with pandas dataframe.

Closing this issue for now.
