### ISSUE TITLE
different features modeling

### ISSUE THREAD

**Issue by MichaelPeibo** [pycaret/pycaret#221]
Hi, I got a question quite a bit of off-pycaret topic.

Consider I want to evaluate different set of features, should I create model seperately or trained one model than apply parameters of the model to another set of features?

**Comment by pycaret** [comment]
@MichaelPeibo Thanks for reaching out. Can you please elloborate your question. Maybe add some example to help us understand.

**Comment by MichaelPeibo** [comment]
See, I have 1000 features, I choose 200 paticular by calculation some parameters as my hypothesis; then I random choose 200 features as control. 
should I create model seperately? Or apply parameters of the model to another set of features?

**Comment by MichaelPeibo** [comment]
@pycaret  Thanks for reply, but I did not see parameters to 'refit' one established model in `create_model `function. Could you show me an example using minimal code?
Here is function of `create_model`
`create_model(estimator = None, ensemble = False, method = None, fold = 10, round = 4, cross_validation = True, verbose = True, system = True, **kwargs)
`

**Comment by pycaret** [comment]
@MichaelPeibo If you will pass a model object with `fit` and `predict` param. `create_model` will retrain it.
