### ISSUE TITLE
plot_kwargs Parameters

### ISSUE THREAD

**Issue by whire97612** [pycaret/pycaret#2214]
I tried version 2.3.6 of pycaret. It's great! Plot model is now more configurable, but there are very few parameters that can be passed into "plot_kwargs" in the introduction of the document. Please tell me the parameter table that can be passed in? thank you

**Comment by moezali1** [comment]
@whire97612 This is something I will put into the documentation. 

Since pycaret uses yellowbrick, plot_kwargs will accept any parameter that is acceptable to the Visualizer object.

https://github.com/DistrictDataLabs/yellowbrick
