### ISSUE TITLE
[BUG] Help with Regression automl analysis

### ISSUE THREAD

**Issue by sgujjaABM** [pycaret/pycaret#2221]
**Describe the bug**

**To Reproduce**
Hi,
I would like to get some help with the Regression analysis using automl function - running this on my data set that's is split into train and test results in an R2 value (0.29) that is lower than what I get using an alternative approach (R2 = 0.66). Can you please let me know if there's any way to optimize the code, or if I am missing something? Also, is there a function to get train metrics on the train data? Appreciate your help.

**Train metrics:
         MAE     MSE    RMSE      R2   RMSLE      MAPE
0     0.6089  0.5996  0.7743  0.3122  0.3393   20.6643
1     0.4885  0.3515  0.5928  0.0735  0.3314  108.2757
2     0.3803  0.3397  0.5829  0.1621  0.2406    0.2707
3     0.7982  0.8574  0.9260 -0.2144  0.4085    1.3486
4     0.4065  0.2613  0.5112  0.3695  0.2372  137.6645
5     0.3871  0.2096  0.4578  0.0622  0.2442    9.8369
6     0.6234  0.5894  0.7677 -0.7053  0.4602  742.2509
7     0.4911  0.3880  0.6229 -0.2039  0.3236    2.2410
8     0.4226  0.3031  0.5505  0.3419  0.2030    0.2678
9     0.6721  0.5725  0.7566 -0.0664  0.4056   25.8672
Mean  0.5279  0.4472  0.6543  0.0132  0.3194  104.8688
SD    0.1341  0.1906  0.1383  0.3121  0.0824  217.4481
<pandas.io.formats.style.Styler object at 0x7f2b3a75fa90>
Test metrics:
                Model     MAE     MSE    RMSE      R2   RMSLE    MAPE
0  AdaBoost Regressor  0.4111  0.2829  0.5319  0.2905  0.2606  0.8783**

```python
##Setting up the environment in PyCaret
regr = setup(train, target = 'y',n_jobs=-1,test_data=test,numeric_features = features)

# compare all baseline models and select top 5
top5 = compare_models(n_select = 5)

# tune models
tuned_top5 = [tune_model(i) for i in top5]

# ensemble models
bagged_top5 = [ensemble_model(i) for i in tuned_top5]

# blend models
blender = blend_models(estimator_list = top5)

# stack models
stacker = stack_models(estimator_list = top5)

# select best model
best = automl(optimize = 'R2')
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by moezali1** [comment]
@sgujjaABM One thing you can try is increasing the `n_iter` parameter in the `tune_model` function. Example:

```
tuned_top5 = [tune_model(i, n_iter = 50) for i in top5]
```

This may improve the chance of getting the best possible model. The performance of the models is broadly dataset-dependent. I suggest you focus on capturing more data that may have some better signal for target variable.

**Comment by sgujjaABM** [comment]
Thank you for the suggestion @moezali1 . I've tried the n_iter parameter as you mentioned, however the R2 value is still similar.

                     Model     MAE    MSE    RMSE      R2   RMSLE    MAPE
0  Random Forest Regressor  0.3966  0.284  0.5329  0.2878  0.2681  0.9421

To put this in context - I am using the the same train and test data sets to run the other regression algorithm for which the model results in test R2 value of 0.66. It's not clear to me why there's such a difference with pycaret automl.

**Comment by sgujjaABM** [comment]
Hi @moezali1 , not sure why you closed this issue. It still doesn't work as expected.
