### ISSUE TITLE
[BUG] Time Series Issue - set_config save_config

### ISSUE THREAD

**Issue by macazan-jg** [pycaret/pycaret#2226]
**Describe the bug**

I just installed the new time series module and was attempting to run the example from (https://towardsdatascience.com/announcing-pycarets-new-time-series-module-b6e724d4636c) and I get the following error... 

```python
"AttributeError: module 'pycaret.time_series' has no attribute 'set_configsave_config'"
```

**To Reproduce**

```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by ngupta23** [comment]
Please paste the complete code (and data) until the point that you got the error. Also, paste the complete error stack. In general a minimal reproducible example is needed to debug. Thanks!

**Comment by macazan-jg** [comment]
Thanks Nikhil!

Here is the full code and the stack trace.

# Code Below
import traceback

try:
    from pycaret.time_series import *
except:
    traceback.print_exc()
​
Traceback (most recent call last):
  File "<ipython-input-3-e4cda4158417>", line 4, in <module>
    from pycaret.time_series import *
AttributeError: module 'pycaret.time_series' has no attribute 'set_configsave_config'

Screenshot

![image](https://user-images.githubusercontent.com/91613083/156033281-f3eb5655-b099-4987-8d1d-ac95c7e30fa8.png)

**Comment by ngupta23** [comment]
OK, I see the issue now. For now, can you do this instead (do not use *)?

```python
# from pycaret.time_series import <whatever functions you want to use>
from pycaret.time_series import create_model, tune_model, compare_models
```

I will try to push a release later today for this fix.

**Comment by ngupta23** [comment]
@macazan-jg This should be fixed now. Please check.

**Comment by macazan-jg** [comment]
Hi Nikhil,

Yes.  It is fixed.  Thank you so much!

Best,
Justin
