### ISSUE TITLE
setup(), providing options for test dataset

### ISSUE THREAD

**Issue by DJ-LYH** [pycaret/pycaret#223]
Sometimes, we have two dataset, one is train dataset, one is test dataset. So in this situation, we don't need auto-spilt dataset, could you provide parameters that let user could define his own test-dataset?

**Comment by pycaret** [comment]
@DJ-LYH Thanks. This is a good idea. I am tagging this as enhancement for future release.

**Comment by pycaret** [comment]
@Yard1 This is the one we talked about a few days ago. Adding a test_set param in the `setup` function that overwrites the `train_test_split`.

Thanks.

**Comment by pycaret** [comment]
@DJ-LYH 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
