### ISSUE TITLE
Custom_stopwords not working in NLP "TypeError: setup() got an unexpected keyword argument 'custom_stopwords'"

### ISSUE THREAD

**Issue by bsriganesh** [pycaret/pycaret#2234]
nlp1 = setup(data,
             target='Short_Description', 
             session_id=123,
             custom_stopwords = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves',
                                 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 
                                 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', 
                                 "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 
                                 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 
                                 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 
                                 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 
                                 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 
                                 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 
                                 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 
                                 'through', 'during', 'before', 'after', 'above', 'below', 'to', 
                                 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 
                                 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 
                                 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 
                                 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 
                                 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', 
                                 "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 
                                 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', 
                                 "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 
                                 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 
                                 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', 
                                 "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 
                                 'wouldn', "wouldn't"])

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [28], in <cell line: 1>()
----> 1 nlp1 = setup(data,
      2              target='Short_Description', 
      3              session_id=123,
      4              custom_stopwords = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves',
      5                                  'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 
      6                                  'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', 
      7                                  "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 
      8                                  'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 
      9                                  'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 
     10                                  'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 
     11                                  'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 
     12                                  'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 
     13                                  'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 
     14                                  'through', 'during', 'before', 'after', 'above', 'below', 'to', 
     15                                  'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 
     16                                  'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 
     17                                  'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 
     18                                  'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 
     19                                  'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', 
     20                                  "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 
     21                                  've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', 
     22                                  "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 
     23                                  'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 
     24                                  'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', 
     25                                  "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 
     26                                  'wouldn', "wouldn't"])

TypeError: setup() got an unexpected keyword argument 'custom_stopwords'

**Comment by moezali1** [comment]
@bsriganesh Maybe try installing pycaret in a fresh conda environment. I can see `custom_stopwords` in signature and I also can't reproduce this bug on my end.

![image](https://user-images.githubusercontent.com/54699234/158137599-2af3a78d-995b-43b7-b95f-7554ba78beab.png)

**Comment by Haosam** [comment]
@bsriganesh
Did you call multiple pycaret imports before trying to run setup?

**Comment by bsriganesh** [comment]
Hi,

That may have been true.

Thanks,
Bharat Balasubramanian.

Sent from my iPhone

On Mar 28, 2022, at 14:43, Haosam ***@***.***> wrote:

﻿

@bsriganesh<https://github.com/bsriganesh>
Did you call multiple pycaret imports before trying to run setup?
