### ISSUE TITLE
[BUG] Help with generating metrics on Train data set

### ISSUE THREAD

**Issue by sgujjaABM** [pycaret/pycaret#2236]
**Describe the bug**

**To Reproduce**

```python
##Setting up the environment in PyCaret
regr = setup(train, target = 'y',n_jobs=-1,test_data=test,numeric_features = features)

# compare all baseline models and select top 5
top5 = compare_models(n_select = 5)

# tune models
tuned_top5 = [tune_model(i, n_iter = 50) for i in top5]

# ensemble models
bagged_top5 = [ensemble_model(i) for i in tuned_top5]

# blend models
blender = blend_models(estimator_list = top5)

# stack models
stacker = stack_models(estimator_list = top5)

# select best model
best = automl(optimize = 'R2')
cv_metrics = pull()
print("CV metrics:")
print(cv_metrics)

# Deploy Model to generate predictions on train data
predict_model(best, train)
# pull
train_metrics = pull()
print("Train metrics:")
print(train_metrics)

# Deploy Model to generate predictions on hold out data
predict_model(best)
# pull
test_metrics = pull()
print("Test metrics:")
print(test_metrics)
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by ngupta23** [comment]
What is the problem? What do you need help with?

**Comment by sgujjaABM** [comment]
Sorry, I was trying to edit the issue to describe the problem with the screenshot of the output, but it was not being shown. 

"Hi, Can you please share the command to generate classification/regression metrics on train data set. I've tried using the predict_model() command, however it results in CV metrics and not on the train set:
<img width="717" alt="Screen Shot 2022-03-03 at 9 26 54 AM" src="https://user-images.githubusercontent.com/78435087/156584285-d6a5fe30-9e23-4a3d-96e6-9b47549af08a.png">
"

**Comment by sgujjaABM** [comment]
I did see a similar issue #1176, but it's not working for me.

**Comment by sgujjaABM** [comment]
Hi,Can you please help with this issue? Thanks!

**Comment by ngupta23** [comment]
>  however it results in CV metrics and not on the train set

By "not on the train set" what exactly are you looking for - are you wanting the train metrics for each fold - or the metric for the model that is refit on the full train data at the end of CV?

In either case, this is not available right now, but will be available in the next release. There is an open PR for this: https://github.com/pycaret/pycaret/pull/2237

**Comment by sgujjaABM** [comment]
Yes, I am trying to get train metrics on the full train set after CV is completed. Thanks for the heads up on the next release. Can you please let me know when it would be out?
