### ISSUE TITLE
ImportError: cannot import name 'six' from 'sklearn.externals'

### ISSUE THREAD

**Issue by juanfranciscomunoz** [pycaret/pycaret#224]
ImportError: cannot import name 'six' from 'sklearn.externals'

**Comment by pycaret** [comment]
@juanfranciscomunoz Thanks for reporting. Which version of sklearn are you using? Can you please do "pip freeze" and let me know the version.

**Comment by juanfranciscomunoz** [comment]
scikit-learn 0.23.1

**Comment by pycaret** [comment]
@juanfranciscomunoz can you also share the full traceback. When do u get this error? Were you able to initialize setup? Which module are you using?

**Comment by juanfranciscomunoz** [comment]
the module is pycaret

---------------------------------------------------------------------------ImportError
                              Traceback (most recent call
last)<ipython-input-5-f89d9155af62> in <module>----> 1
classification_setup = classification.setup(data= data_classification,
target='Personal Loan')
~/anaconda3/lib/python3.7/site-packages/pycaret/classification.py in
setup(data, target, train_size, sampling, sample_estimator,
categorical_features, categorical_imputation, ordinal_features,
high_cardinality_features, high_cardinality_method, numeric_features,
numeric_imputation, date_features, ignore_features, normalize,
normalize_method, transformation, transformation_method,
handle_unknown_categorical, unknown_categorical_method, pca,
pca_method, pca_components, ignore_low_variance, combine_rare_levels,
rare_level_threshold, bin_numeric_features, remove_outliers,
outliers_threshold, remove_multicollinearity,
multicollinearity_threshold, create_clusters, cluster_iter,
polynomial_features, polynomial_degree, trigonometry_features,
polynomial_threshold, group_features, group_names, feature_selection,
feature_selection_threshold, feature_interaction, feature_ratio,
interaction_threshold, session_id, silent, profile)    878     879
#import library--> 880     from pycaret import preprocess    881
882     data = preprocess.Preprocess_Path_One(train_data = data,
~/anaconda3/lib/python3.7/site-packages/pycaret/preprocess.py in
<module>     24 from sklearn.decomposition import IncrementalPCA
25 from sklearn.preprocessing import KBinsDiscretizer---> 26 from
pyod.models.knn import KNN     27 from pyod.models.iforest import
IForest     28 from pyod.models.pca import PCA as PCA_od
~/anaconda3/lib/python3.7/site-packages/pyod/models/knn.py in <module>
    13 from sklearn.utils.validation import check_is_fitted     14
---> 15 from .base import BaseDetector     16      17
~/anaconda3/lib/python3.7/site-packages/pyod/models/base.py in
<module>     19      20 import abc---> 21 from sklearn.externals
import six     22      23 import numpy as np
ImportError: cannot import name 'six' from 'sklearn.externals'
(/Users/JuanMunoz/anaconda3/lib/python3.7/site-packages/sklearn/externals/__init__.py)


Cordial Saludo,
*Juan Francisco Muñoz.*
Skype: juan.francisco.munoz
Móvil:   +57 3203476602

**Comment by pycaret** [comment]
@juanfranciscomunoz  Thanks for sharing. Can you do this "pip install six".

Let me know if this solves your problem.

**Comment by juanfranciscomunoz** [comment]
Mi solve was delete pycaret and use other tool

Enviado desde mi iPhone
