### ISSUE TITLE
Add Zero Shot text and image classification capabilities.

### ISSUE THREAD

**Issue by PrithivirajDamodaran** [pycaret/pycaret#2248]
**Is your feature request related to a problem? Please describe.**
It's more of a great addition rather a problem. PyCaret has a robust collection of algorithms and datasets. It will be a great addition to have zero shot text & image classification capabilities. It can help in classification as well as in weak labelling data.  

**Describe the solution you'd like**
The solution is pretty straight forward: integrate Alt-ZSC and ZSIC libraries to PyCaret. They both are light-weight,  feature rich, intentionally simple libs and puts SoTA models to the best use. 

Please refer to the repositories for further details.

- [Alt-ZSC](https://github.com/PrithivirajDamodaran/Alt-ZSC)

- [ZSIC](https://github.com/PrithivirajDamodaran/ZSIC)

**Describe alternatives you've considered**
NA
**Additional context**
NA

**Comment by ngupta23** [comment]
Hi @PrithivirajDamodaran To be honest, we need an owner for the NLP module which only has the older classical techniques in it right now. Given your work on NLP (with the latest and greatest techniques), would you be willing to help revamp and own this module's development and roadmap? If so, let's set up a call to discuss with the rest of the core team.

**Comment by PrithivirajDamodaran** [comment]
Thank you - My idea of opening this feature request was to add a new category of feature called “labellers" for PyCaret. 

But I like your larger proposal, I would be happy to own/lead the NLP side of things for PyCaret but at the moment I have some prior professional commitments, so, if you are looking for someone to start immediately, I can also help refer someone in my network. 

Let me know what you think.

**Comment by ngupta23** [comment]
Thanks @PrithivirajDamodaran. I think we have a bit of time here since we are going through a refactor for the other (non-NLP) related modules right now. Let me touch base with you in a bit to discuss the next steps (either way we decide to take it).

This would probably be a new class of tasks as you pointed out. I am envisioning something like this, but of course, we have to go through the planning phase to decide this and what all this experiment class will and can support.

```python
from pycaret.nlp import TextClassificatonExperiment
from pycaret.image import ImageClassificationExperiment
```

**Comment by moezali1** [comment]
We are no more supporting the `nlp` and `arules` module in PyCaret due to lack to resources. Closing the issue now.
