### ISSUE TITLE
Preprocessing: Support for various imputation types

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#2249]
**Is your feature request related to a problem? Please describe.**
I understand that **[`IterativeImputer`](https://scikit-learn.org/stable/modules/impute.html#iterative-imputer)** (MICE) is going to be supported in pycaret 3.0.0, but will other imputation techniques be supported as well?

e.g.

- [ ] Pandas: "ffill", "bfill", groupBy
- [ ] sklearn: KNNImputer
- [ ] lgbm: LightGBM Imputer

**Describe the solution you'd like**
Examples described in **[this notebook](https://www.kaggle.com/robikscube/handling-with-missing-data-youtube-stream)**

**Comment by tvdboom** [comment]
#2256
