### ISSUE TITLE
Anomaly Import Issue

### ISSUE THREAD

**Issue by spf255** [pycaret/pycaret#2253]
I've been using the PyCaret anomaly detection package in a Jupyter Notebook in Cloudera Data Science Workbench (CDSW) for a while now. It's been very valuable! I'm now trying to automate this by running it as a script daily.

I've created a script with the exact same commands that are successfully working in Jupyter Notebook. Unfortunately, importing the anomaly package fails when I run it in a Python workbench in the same CDSW project. I can't seem to get past this issue with `'update_display'`.

`from pycaret.anomaly import *`

Results:
```
ImportError: cannot import name 'update_display'
ImportError                               Traceback (most recent call last)
in engine
----> 1 from pycaret.anomaly import *

/home/cdsw/.local/lib/python3.6/site-packages/pycaret/anomaly.py in <module>()
      9 import warnings
     10 from pycaret.internal.logging import get_logger
---> 11 from pycaret.internal.Display import Display, is_in_colab, enable_colab
     12 import pandas as pd
     13 import numpy as np

/home/cdsw/.local/lib/python3.6/site-packages/pycaret/internal/Display.py in <module>()
      7 import ipywidgets as ipw
      8 from IPython import get_ipython
----> 9 from IPython.display import display, HTML, clear_output, update_display
     10 from typing import Optional, List, Dict, Any
     11 from pycaret.utils import enable_colab

ImportError: cannot import name 'update_display'
```

**Comment by ngupta23** [comment]
Check the `ipython` version on CDSW and see if it has the `update_display` feature. Sometimes the environments in CDSW are older. You may have to update the `ipython` version if that is the case. Just my guess.

https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.update_display

**Comment by spf255** [comment]
I can run a Jupyter session in CDSW and the `IPython` (v 7.16.3) functions load just fine. They are installed in the directory  `./.local/lib/python3.6/site-packages`.

If I try to run this exact same script in a CDSW Python 3 workbench session (command line), this error occurs. In this session, I found it's using the `IPython` package in the same directory `./.local/lib/python3.6/site-packages`.

If the import worked in Jupyter notebook, wouldn't it also work in the command line? Does `pycaret` need to be run in a notebook?

**Comment by spf255** [comment]
Thanks, @ngupta23!

After digging, I found that it's using `IPython` (v. 7.16.3) in this directory when working in Jupyter Notebook:

`/home/cdsw/.local/lib/python3.6/site-packages/IPython/`

And it's using `IPython` (v. 5.1.0) in this directory when working in the command line:

`/var/lib/cdsw/python3-engine-deps/lib/python3.6/site-packages/IPython/`

Since these are being called from the `pycaret` library, I'll have to request our CDSW administrator to update the default package.

**Comment by ngupta23** [comment]
Yes, I have been burned by similar issues on CDSW before , hence my suggestion. Glad it helped.
