### ISSUE TITLE
[BUG] NameError: name 'display_container' is not defined

### ISSUE THREAD

**Issue by sgujjaABM** [pycaret/pycaret#2255]
**Describe the bug**

**To Reproduce**

Hi, I am getting this error when I predict on a new data set with true labels (defined as 'dataset') using existing trained model. This is same as issue #818, however the pull() function doesn't work since I am not using setup function. Can you please help?

NameError: name 'display_container' is not defined

```python
model = load_model(trainedModel)
print(model)

# predict
test_predictions = predict_model(model, dataset)
print(test_predictions.head(5))
test_metrics = pull()
print("Test metrics:")
print(test_metrics)
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by moezali1** [comment]
@sgujjaABM I think your environment is having multiple conflicts with older version of pycaret. Have you installed time series module and pycaret in the same environment?

Can you please try installing pycaret in the new conda environment and try to reproduce the bug?

Thanks
