### ISSUE TITLE
[Time Series] plot_model fails when range of days is over 200d

### ISSUE THREAD

**Issue by Ant3ng** [pycaret/pycaret#2258]
**Describe the bug**

When sample days are over 200d, plot_module in time-series module doesn't give a plot, but a bizarre error.
Even if you can solve the issue by following instruction below (installing `kaleido`), this error might not be expected and welcomed.

```
ValueError                                Traceback (most recent call last)
[<ipython-input-245-2ed2f942f17b>](https://localhost:8080/#) in <module>()
      1 # object-oriented API
----> 2 exp.plot_model()

5 frames
[/usr/local/lib/python3.7/dist-packages/plotly/io/_kaleido.py](https://localhost:8080/#) in to_image(fig, format, width, height, scale, validate, engine)
    137 which can be installed using pip:
    138     $ pip install -U kaleido
--> 139 """
    140         )
    141 

ValueError: 
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using pip:
    $ pip install -U kaleido
```

**To Reproduce**

When days are 200d or less, it is safe
```python
import pandas as pd
from pycaret.internal.pycaret_experiment import TimeSeriesExperiment

n_days = 200

date = pd.date_range(start='2021-01-01', periods=n_days)
data = pd.DataFrame([0] * len(date), index=date, columns=['value'])

# with new object-oriented API
exp = TimeSeriesExperiment()
exp.setup(data, fh = 7, fold = 3, session_id = 123)

# object-oriented API
exp.plot_model()
```

When days are over 200d, problem arises
```python
import pandas as pd
from pycaret.internal.pycaret_experiment import TimeSeriesExperiment

n_days = 201

date = pd.date_range(start='2021-01-01', periods=n_days)
data = pd.DataFrame([0] * len(date), index=date, columns=['value'])

# with new object-oriented API
exp = TimeSeriesExperiment()
exp.setup(data, fh = 7, fold = 3, session_id = 123)

# object-oriented API
exp.plot_model()
```

**Versions**
Google Colab

pycaret.__version__ -> 3.0.0

**Comment by ngupta23** [comment]
For larger datasets, the renderer is switched to a static one (for some plots only) since larger datasets with interactive plots can slow down notebooks. The default threshold is 200 data points You can increase the threshold in setup (please see docstring).

![image](https://user-images.githubusercontent.com/33585645/157428139-bb4e4ffb-94f4-4dc2-bf66-27a2a2174598.png)


> Even if you can solve the issue by following instruction below (installing kaleido), this error might not be expected and welcomed.

Do you have any alternate suggestion on what should be done here?

**Comment by ngupta23** [comment]
> Even if you can solve the issue by following instruction below (installing kaleido), this error might not be expected and welcomed.
Do you have any alternate suggestion on what should be done here?

Maybe we could install `kaleido` by default when we install pycaret. I will look into it,

**Comment by Ant3ng** [comment]
Thank you for reply

> Do you have any alternate suggestion on what should be done here?

Possible suggestion is putting your description on error message. It means telling not just how to fix it (including install `kaleido`), but why this occurred just because of changing number of datasets from 200->201.

> Install `kaleido`

Though I installed kaleido after getting error above, same error occurred. I checked it being installed by seeing its version and I was able to print version. So I made plot doable by adjusting `big_data_threshold`.

**Comment by ngupta23** [comment]
@Ant3ng Thanks for the feedback. I am able to run the plots with > 200 points once `kaleido` is installed. May I know where you are running your analysis?

- Is it in a notebook?
- Is it on your local machine or Google Colab or somewhere else?

It may be possible that you installed `kaleido`, but did not restart the environment so the notebook did not pick up the install. Just some thoughts. If you can provide more details, it will help. Thanks!

**Comment by Ant3ng** [comment]
@ngupta23 
Sorry for being late.

> Is it on your local machine or Google Colab or somewhere else?

Answer is Google Colab.
I found why it didn't work. Order of install might matter. Please correct me if order doesn't matter.

▼ Wrong order
```
1. !pip install pycaret-ts-alpha
2. import library and do exp.plot_model() -> of course it causes error saying install kaleido
3. !pip install -U kaleido
4. import library and do exp.plot_model() -> Again, it causes error saying install kaleido
```

▼ Correct order
```
1. !pip install -U kaleido
2. !pip install pycaret-ts-alpha
3. import library and do exp.plot_model() -> It works correctly
```

> updated error message

I think it is great!! 
If order I mention above is correct, it might be better to incorporate explanation about order into error message.

**Comment by ngupta23** [comment]
Thanks for the feedback. I do not think the order matters (but of course, I could be wrong). In any case, we will install this by default (when you install pycaret) in the next release so users will not get that message.
