### ISSUE TITLE
Installation error when using pip

### ISSUE THREAD

**Issue by rudreshmehta** [pycaret/pycaret#227]
ERROR: No .egg-info directory found in C:\Users\Rudresh Mehta\AppData\Local\Temp\pip-pip-egg-info-bvzqwuas

**Comment by pycaret** [comment]
@rudreshmehta Can you please provide the complete traceback?

**Comment by rudreshmehta** [comment]
I reinstalled and create a new environment. Anyway now it is working.
I want to give a suggestion cum request for a feature that can we do auto optimization on the data before taking it further ?
Here optimization means to allocate the minimum memory require for the data in a column.
