### ISSUE TITLE
[BUG] Pycaret autoML Regression with very high error metrics

### ISSUE THREAD

**Issue by sgujjaABM** [pycaret/pycaret#2270]
**Describe the bug**

**To Reproduce**

Hi, I am running regression analysis on a data set that results in very high error metrics and low R2 values. The metrics on test data are below. Can you please help understand what this means?
Test metrics:
                Model     MAE     MSE    RMSE      R2   RMSLE    MAPE
0  CatBoost Regressor  0.4003  0.3513  0.5927  0.6486  0.0869  0.0723

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/sgujja/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/sgujja/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

  | MAE | MSE | RMSE | R2 | RMSLE | MAPE
-- | -- | -- | -- | -- | -- | --
0 | 22351599414 | 1.06E+21 | 32496877473 | -1.20E+21 | 20.0134 | 4172797270
1 | 1.2548E+12 | 3.42E+24 | 1.84937E+12 | -4.02E+24 | 23.5494 | 2.3559E+11
2 | 30980161417 | 2.95E+21 | 54303055865 | -3.17E+21 | 19.2976 | 5998734855
3 | 80522896256 | 1.28E+22 | 1.13304E+11 | -1.03E+22 | 21.5529 | 1.5264E+10
4 | 26469991746 | 1.65E+21 | 40605196415 | -1.68E+21 | 20.3588 | 5037198411
5 | 23014811900 | 9.89E+20 | 31456062211 | -8.56E+20 | 20.1673 | 4394204696
6 | 25933202949 | 1.45E+21 | 38109673470 | -1.55E+21 | 19.8931 | 4775392614
7 | 33549984264 | 2.44E+21 | 49369468646 | -2.09E+21 | 19.8261 | 6189680775
8 | 28975283188 | 1.77E+21 | 42046314129 | -1.68E+21 | 20.0729 | 5424294252
9 | 2.54716E+12 | 1.45E+25 | 3.80345E+12 | -2.02E+25 | 24.8132 | 4.891E+11
Mean | 4.07377E+11 | 1.79E+24 | 6.05451E+11 | -2.43E+24 | 20.9545 | 7.7594E+10
SD | 8.00926E+11 | 4.35E+24 | 1.19356E+12 | 6.05E+24 | 1.7252 | 1.5328E+11

</body>

</html>

```python
##Setting up the environment in PyCaret
regr = setup(train, target = 'y',n_jobs=-1,test_data=test,numeric_features = features)

# compare all baseline models and select top 5
top5 = compare_models(n_select = 5)

# tune models
tuned_top5 = [tune_model(i, n_iter = 50) for i in top5]

# ensemble models
bagged_top5 = [ensemble_model(i) for i in tuned_top5]

# blend models
blender = blend_models(estimator_list = top5)

# stack models
stacker = stack_models(estimator_list = top5)

# select best model
best = automl(optimize = 'R2')
cv_metrics = pull()
print("CV metrics:")
print(cv_metrics)
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by moezali1** [comment]
@sgujjaABM The metrics on test data are your hold-out metrics. Whereas the metrics you see with training functions like `create_model`, `compare_models`, etc. are cross-validated metrics on the training set only. Ideally the cross-validated metrics and hold-out metrics should be close to each other, if they are not, it signifies over-fitting/under-fitting.

By default the `automl` function runs through all the models trained in the environment and bring back the best model based on the metric defined in `optimize` parameter. It does that by using cross-validation metrics. If you instead want to select model based on hold-out set (which is not recommended) you can pass `use_holdout=True` in the `automl` function.

Let me know if this helps?
