### ISSUE TITLE
[BUG] transform_target_method not working...

### ISSUE THREAD

**Issue by camille1** [pycaret/pycaret#2276]
Although `transform_target_method` is included, Y (labels) is always returned with no transformation

```Python
# load dataset
from pycaret.datasets import get_data
diamond = get_data('diamond')

# init setup
from pycaret.regression import *
r = setup(data = diamond, target = 'Price', transform_target = True, transform_target_method='yeo-johnson', silent=True, verbose=False)

assert get_config('y').sum() == diamond.Price.sum() # should be False


```

**Comment by moezali1** [comment]
@camille1 It's not a bug, it's a feature. When you pass `transform_target=True` we perform the transformations under the hood then when you call `predict` on the model, we inverse transform and return the result. If you are really want to model the transformed y and want to take care of inverse transformation outside of pycaret then you can simply transform your y and pass it into setup without setting `transform_target=True`. This way you will be modeling transformed y which you can then inverse it yourself. Remember, if you do it this way the cross-validation metrics you will see will be based on y-transformed and may not be meaningful. 

If you want to be sure that transformation is working, just train a model and see if it's wrapped around `PowerTransformedTargetRegressor` class. I have ran a quick test to check this:

```
from pycaret.datasets import get_data
diamond = get_data('diamond')

from pycaret.regression import *
r = setup(data = diamond, target = 'Price', transform_target = True)

lr = create_model('lr')

print(lr)
```
![image](https://user-images.githubusercontent.com/54699234/158136144-fe1db166-c3a4-45a9-be6c-66a8a1d172d0.png)

Hope this helps.
