### ISSUE TITLE
Return the transformed dataset 

### ISSUE THREAD

**Issue by AlexanderKonstantinidis** [pycaret/pycaret#228]
As of now if I understand well, we can define transformations on the data --e.g. removal of highly correlated features, limitation of features to the ones passing importance thresholds etc.-- but we never get the final dataset following the transformations as a dataframe we can work with.
I believe it would add great value to the use if the module returned the transformed dataset and I understand that this capability should not be difficult to implement.

**Comment by pycaret** [comment]
@AlexanderKonstantinidis Thanks. You can access the transformed dataset which is stored in the variable in which setup is called. Unfortunately there is no index but the first 5 values are x_train,x_test,y_train,y_test.
