### ISSUE TITLE
Return the history of experiments during the tuning of the model's hyperparameters.

### ISSUE THREAD

**Issue by AlexanderKonstantinidis** [pycaret/pycaret#229]
When we tune a model we get the model tuned but we do not have the opportunity to view the history of experiments (hyperparameters tried and performance achieved).  It would be useful to have this history as a dataframe --each row being an experiment and hyperparameters being columns with the final column being the performance achieved-- so that we may push performance higher by trying some experiments on our own.

**Comment by pycaret** [comment]
@AlexanderKonstantinidis Wonderful suggestion. In next release, PyCaret's logging backend is entirely designed on MLflow. In next release we will be including a csv output of what you are asking. 

Tagging this as an enhancement. Will close the issue on next release.

**Comment by DJ-LYH** [comment]
> @AlexanderKonstantinidis Wonderful suggestion. In next release, PyCaret's logging backend is entirely designed on MLflow. In next release we will be including a csv output of what you are asking.
> 
> Tagging this as an enhancement. Will close the issue on next release.

Could this be used in pycaret-nightly?

**Comment by pycaret** [comment]
@DJ-LYH Yes
