### ISSUE TITLE
[BUG] - TimeSeriesExperiment() - Getting error "ValueError: Unsupported Period frequency: B"

### ISSUE THREAD

**Issue by prabhakaran2812** [pycaret/pycaret#2305]
**Describe the bug**
I am trying to run a simple timeseries experiment, if have consecutive date including Sat, Sun and when I run experiment, it throws ths error "ValueError: Unsupported Period frequency: B, valid Period frequency suffixes are: S, T, H, D, W, M, Q, A, Y" But when I use the dates including Sat & Sun, I do not get this error, Is there a fix for this bug, I dont want to include dummy rows for Sat & Sun. Please advise. 

**To Reproduce**

```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by prabhakaran2812** [comment]
Inherently my question is, for seasonal_period while we have D:7, can we have B:5 (as facilitated by pandas date_range)

**Comment by ngupta23** [comment]
Hi @prabhakaran2812 Can you share your dataset and code snippet with me so I can evaluate and get back to you? Thanks1

**Comment by prabhakaran2812** [comment]
> Hi @prabhakaran2812 Can you share your dataset and code snippet with me so I can evaluate and get back to you? Thanks!

Please find the code snipped to reproduce error (if we replace freq to D and change range to 30, the code works.
import pandas as pd
import datetime
format = '%Y-%m-%d'
a = []
b = []
for x in range(22):
  a.append(x)
  b.append(a)
  a = []
print(a)
chkdf = pd.DataFrame([l for l in b],columns=['Value'],\
                     index=pd.date_range(start="2022-03-01",end="2022-03-30",freq='B').tolist())
exp = TimeSeriesExperiment()
exp.setup(data=chkdf, fh=5,session_id = 30)
best_model = exp.compare_models(turbo=True)

**Comment by prabhakaran2812** [comment]
Condensed the code above

**Comment by ngupta23** [comment]
Thanks for providing the reproducible code. This is helpful. 

Just add the seasonal_period argument to the setup and it should work. Also, note the new class interface in the latest release. 

```python
from pycaret.time_series import TSForecastingExperiment
exp = TSForecastingExperiment()
exp.setup(data=chkdf, fh=5, seasonal_period=5, session_id = 30)
```

**Comment by prabhakaran2812** [comment]
@ngupta23 Thank you!! Does 5 correspond to 5 business days ? I dont see that in https://pycaret.readthedocs.io/en/time_series/api/time_series.html (If it corresponds to 5 business days, could you please add to the pycaret link above so it will be helpful to others. Thanks again, it works!!

**Comment by ngupta23** [comment]
5 is just the expected seasonal_period. It tries to get it from the index is nothing is specified. It looks like the support for Business week is not there right now. But the way I provided bypasses that and just uses what the user provides so this is a workaround.

**Comment by prabhakaran2812** [comment]
Will it impact the prediction for business days (having weekend break) if I use the workaround? Please let me know. Good to see that other incident log. Thanks for that.

**Comment by ngupta23** [comment]
I ran the code and it predicts the gaps correctly. So it is just a matter of adding the "B" to the support index values. But I will have to do a deeper dive when this is implemented. For now, it seems to work, but if you find issues, please report them. Thanks!

![image](https://user-images.githubusercontent.com/33585645/159136495-512edd82-1697-41e7-9280-aacbf2096f7c.png)

**Comment by prabhakaran2812** [comment]
@ngupta23 Thank you! That helps.
