### ISSUE TITLE
Error while installing  pycaret-ts-alpha -U

### ISSUE THREAD

**Issue by biomedatascientistSV** [pycaret/pycaret#2307]
**Describe the bug**

**To Reproduce**

```python
!pip  install pycaret-ts-alpha -U
!pip install prophet
```

**Expected behavior**

**Additional context**

**Versions**
jupyter core     : 4.7.1
jupyter-notebook : 6.3.0
qtconsole        : 5.0.3
ipython          : 7.22.0
ipykernel        : 5.3.4
jupyter client   : 6.1.12
jupyter lab      : 3.0.14
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5
macOS Monterey  : version 12.3

</details>

**Comment by ngupta23** [comment]
@biomedatascientistSV This works for me.

A few things to try:

1. Try on Google Colab to eliminate your machine environment-specific issues. This should go through, but you can also confirm.
2. If 1 passes, then create a fresh environment on your local machine and only install these 2 libraries. There may be other libraries in your current environment that might be interfering with the installation.
3. If 2 fails, then paste the complete error stack so we can look for pointers.

**Comment by ngupta23** [comment]
Solution posted in #962
