### ISSUE TITLE
Getting error when creating clustering kmeans model

### ISSUE THREAD

**Issue by simoneperazzoli** [pycaret/pycaret#231]
Dear all, 
I am getting the following error '**TypeError: invalid data type for einsum**' when I try to create a model for clustering with kmeans: **kmeans = create_model('kmeans')**.
When I run the tutorial case, it works well, but when I try to run with my dataset this error comes.
![WhatsApp Image 2020-06-18 at 20 17 49](https://user-images.githubusercontent.com/32544918/85057456-0b8f1980-b1a1-11ea-82d2-c454b76fcb4f.jpeg)

I am running it in a virtual environment with Python 3.6.9 version
Do you have any idea about what is happening?

**Comment by pycaret** [comment]
@simoneperazzoli Thanks for reporting. Not sure. by any chance you can provide the sample dataset so I can try to reproduce the issue on my end and see what is causing it?

**Comment by simoneperazzoli** [comment]
Thanks for your reply @pycaret 
Here is a sample of the dataset.

[data_to_model.zip](https://github.com/pycaret/pycaret/files/4812170/data_to_model.zip)

**Comment by pycaret** [comment]
@simoneperazzoli I have tried this. It seems like the problem is caused by **sklearn.KMeans**. I can run other clustering models. Can you try fitting KMeans directly from sklearn and let me know if that works. You can open a issue on sklearn github if you want.

**Comment by simoneperazzoli** [comment]
@pycaret thanks for the feedback.
It was possible to run KMeans directly from sklearn, without problems (it is a bit weird). 
I will also try with other clustering models on pycaret. As soon as I get results, I'll tell you.

**Comment by simoneperazzoli** [comment]
@pycaret I have tested with Pycaret 2.0 and it is working now. Thank you for all the support!

**Comment by pycaret** [comment]
Thanks @simoneperazzoli
