### ISSUE TITLE
How to see PCA components name?

### ISSUE THREAD

**Issue by kilickursat** [pycaret/pycaret#2314]
I applied PCA and then feature importance but it shows important features with Component_1,2 and 3 so how can I know/understand which parameters are corresponding to these components?

![PCA3](https://user-images.githubusercontent.com/25801054/159423272-5310a224-07bf-4534-bc50-db4bd57de2f7.png)

**Comment by kilickursat** [comment]
Thanks for your reply. However, the new components are kind of black box.

**Comment by kilickursat** [comment]
I have 18 features and applied PCA for feature extraction and then I would like to see the names of three components in the feature importance plot? For example, component 1 refers to thrust force, component 2 refers to pressure, etc.

**Comment by ngupta23** [comment]
> The components are not a 1-1 representation from the old features.

Correct. But the components are a linear combination of initial features. I believe in R, you can see constituents of the initial features in the components. Irrespective of what @kilickursat is looking for, I hope something similar is available in Python as well (seeing the component composition of initial features).

PS: It may be available in the `components_` attribute in PCA (maybe). Is it possible to get the trained prep_pipe and look at the internals. I think that is all that might be needed.

https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html

**Comment by kilickursat** [comment]
> What is your use case?

@tvdboom and @ngupta23 , First of all, many thanks for your all suggestions and effort. You enlightened me about PCA and feature extraction. Sorry for the late reply due to the time difference. 
I have numerical machine parameters such as torque, thrust, pressure and etc. total of 18 features. In addition, I have 3 main geological layers like A, B and C, and I am trying to classify geological layers using machine parameters. My purpose is to see feature importance for classification/output.

**Comment by kilickursat** [comment]
According to your comments, I have checked and applied Multicollinearity with PyCaret. I think that kind of a way is more reasonable than the PCA for my case.
