### ISSUE TITLE
PyCaret NLP doesn't appear to remove my custom_stopwords list

### ISSUE THREAD

**Issue by ebpetrov** [pycaret/pycaret#232]
The PyCaret NLP doesn't appear to remove the list of custom stopwords I pass to the custom_stopwords argument when I run setup. Words I specified in the custom stopwords list still appear in the ngrams.

**Comment by pycaret** [comment]
@ebpetrov Hi Can you please provide a sample dataset with an example. I will reproduce the issue and try to figure out what's causing it.

**Comment by pycaret** [comment]
@ebpetrov Would you still like to help us resolve this issue?

**Comment by ebpetrov** [comment]
I resolved the problem. Thank you.
