### ISSUE TITLE
when use eda(display_format = 'bokeh') from pycaret with jupyterlab ,the bokeh plot cannot change by selecting different var[BUG]

### ISSUE THREAD

**Issue by mana19** [pycaret/pycaret#2320]
when use eda(display_format = 'bokeh') from pycaret with jupyterlab ,the bokeh plot cannot change by selecting different var.But it run smoothly in notebook. jupyterlab 3.1.2, the ipywidget has been installed.
pycaret 2.3.7
**Describe the bug**

**To Reproduce**

```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by moezali1** [comment]
@mana19 Do you mind logging this issue on [this repo](https://github.com/AutoViML/AutoViz).
