### ISSUE TITLE
sklearn version error when running pycaret 2.3.8

### ISSUE THREAD

**Issue by crystalmunyee** [pycaret/pycaret#2326]
hi i have the some issue with the following error but i checked my scikit learn is already 0.23.2.
Its happens when im setting up the model:
exp_mclf1 = setup(data = job, target = 'Salary_Bins', session_id=123) 

RuntimeError: This version of PyCaret requires scikit-learn==0.23.2, got 0.22. Support for newer scikit-learn versions will be added in a future release.
![image](https://user-images.githubusercontent.com/88234945/160143612-3c14192a-a56a-405f-8531-3304714a0db3.png)

**Comment by moezali1** [comment]
Hi @crystalmunyee Seems like some conflicts. Can you please try that in a fresh environment? I am not able to reproduce this bug when I install pycaret on fresh environment or on Colab.

**Comment by crystalmunyee** [comment]
Hi @moezali1, thanks for the feedback. Im not sure why but reinstalling anaconda and resetup of all the packages is able to work now.
