### ISSUE TITLE
Tuned model behaves even worse

### ISSUE THREAD

**Issue by linchen111** [pycaret/pycaret#234]
Take Extra Trees Classifier for example:

et = create_model('et')
Accuracy	AUC	Recall	Prec.	F1	Kappa
0	0.8140	0.0	0.6000	0.8295	0.7961	0.5175
1	0.8837	0.0	0.8778	0.8808	0.8816	0.7378
2	0.8372	0.0	0.6889	0.8680	0.8135	0.5657
3	0.9070	0.0	0.8111	0.9088	0.9043	0.7831
4	0.8140	0.0	0.7489	0.8098	0.8093	0.5972
5	0.8333	0.0	0.7503	0.8358	0.8315	0.6504
6	0.8095	0.0	0.6774	0.8424	0.7906	0.5372
7	0.7619	0.0	0.5548	0.7628	0.7374	0.3878
8	0.8810	0.0	0.6778	0.8865	0.8668	0.7099
9	0.8095	0.0	0.6992	0.8064	0.7986	0.5404
Mean	0.8351	0.0	0.7086	0.8431	0.8230	0.6027
SD	0.0415	0.0	0.0896	0.0417	0.0469	0.1130

But my turned model is not better
tuned_et = tune_model('et',n_iter = 20,optimize='Recall')
Accuracy	AUC	Recall	Prec.	F1	Kappa
0	0.7907	0.0	0.5667	0.8143	0.7648	0.4416
1	0.8605	0.0	0.8222	0.8586	0.8474	0.6605
2	0.8140	0.0	0.6556	0.8531	0.7787	0.4889
3	0.9070	0.0	0.8111	0.9088	0.9043	0.7831
4	0.8140	0.0	0.6989	0.8085	0.8090	0.5943
5	0.8571	0.0	0.7874	0.8635	0.8546	0.7073
6	0.8333	0.0	0.7885	0.8668	0.8133	0.6090
7	0.7857	0.0	0.5663	0.7989	0.7576	0.4333
8	0.8333	0.0	0.6111	0.8420	0.8103	0.5714
9	0.8095	0.0	0.6992	0.8064	0.7986	0.5404
Mean	0.8305	0.0	0.7007	0.8421	0.8139	0.5830
SD	0.0347	0.0	0.0940	0.0331	0.0425	0.1075

**Comment by aliagowani** [comment]
This has happened to me multiple times as well. Usually, the initial compare() has the best results and then gets worse from there (create_model, tune_model).

**Comment by pycaret** [comment]
@linchen111 Thanks for reporting. This is happening because tune_model uses random grid function. You can try increase **n_iter** parameter within **tune_model()** that may improve the performance.

**Comment by gm039** [comment]
Hi,
Even I am facing a similar issue the tuned model perform worse. I tried increasing n_iter parameters but no improvement in the results. Any suggestions?

**Comment by Yard1** [comment]
You can use `choose_better=True` param to have the original model returned if the tuned one performs better. It is not unusual for tuned models to sometimes give worse results than non-tuned ones.

**Comment by gm039** [comment]
Hi
The option **choose_better=True** still gives a worse model than the untuned one. Even I tried increasing n_iter, but no much improvement.
Any suggestions.

![image](https://user-images.githubusercontent.com/50217085/92946540-ce939580-f424-11ea-86d9-f053f96b5923.png)

**Comment by joaopalotti** [comment]
HI @Yard1, first of all, thanks for the amazing package!

I am having the same problem as everybody here, and I am afraid ``choose_better=True`` is not helping.

```
from pycaret.datasets import get_data
data = get_data('insurance')
reg1 = setup(data, target = 'charges',  session_id=123, log_experiment=True, experiment_name='insurance1', silent=True)
model = create_model('catboost')
print("Before:", pull()["R2"].loc["Mean"])  # Prints 0.8228

tune_model(model, n_iter=1, choose_better=True)
print("After:", pull()["R2"].loc["Mean"])   # Prints 0.6759
```

I am using pycaret==2.2.2 and catboost==0.24.3, both installed with pip.
Am I doing something wrong here?

Thanks,

Joao

**Comment by Yard1** [comment]
@joaopalotti Even when using `choose_better`, the printed dataframe will still be for the tuned model. However, the returned model object will be different.

**Comment by joaopalotti** [comment]
Hi @Yard1 , thanks for your quick reply.
The ``n_iter=1`` was just an example, I am actually using ``n_iter=1000` and still not improving from the default model (probably the default parameters of catboost are already amazing).

I could see that ``tune_model`` is actually returning the best model (in this case, the original one) as you mentioned. 
One silly remaining question here is: once a model is created/trained/tunned, is there another way to get the training CV dataframe results apart from ``pull( )``?

For example:
``tunned_model.get_training_results( )``

I know that I could pull both before and after the tunning part and save the dataframe that has the best results, but I wonder if you are saving (or planning to save in a later release) these results in the model object.

Thanks again!

**Comment by Yard1** [comment]
CV results are saved in an internal list, but it is kot intended to be used by the users. The best way would be to run `create_model` again with the model object (instead of a string) and pull the resulting dataframe.

**Comment by snewhouse** [comment]
I think some of this is down to default settings eg min_samples_split = 2 results in some overfitting. I see the same, really great results with default, my first instinct is overfitting

**Comment by sorenwacker** [comment]
`choose_better=True` should be default, no?

**Comment by Yard1** [comment]
It will be in the next major release.

**Comment by sorenwacker** [comment]
It is an amazing library. I can do so much work in no time. Compared to typing out everything that pycaret does. 

Consider just these to commands::

```
setup(...)
compare_models(...)
```

...just amazing.
