### ISSUE TITLE
ACF and PACF plots to reuse subplot logic directly instead of replicating code.

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#2343]
In Time series module, we can create ACF & PACF plots either 

1. Individually (on data or residuals)

```python
# On original data ----
plot_model(plot = "acf")

# On model residuals ----
plot_model(model, plot = "acf")
```

This uses the `plot_acf` and `plot_pacf` functions as shown below

https://github.com/pycaret/pycaret/blob/915a13d3b4d880b5a0dac0797465217b2ba934b9/pycaret/internal/plots/time_series.py#L446

https://github.com/pycaret/pycaret/blob/915a13d3b4d880b5a0dac0797465217b2ba934b9/pycaret/internal/plots/time_series.py#L539

OR 

2. As part of larger plots as subplots

```python
# On original data ----
plot_model(plot = "diagnostics")

# On model residuals ----
plot_model(model, plot = "diagnostics")
```

This uses the `corr_subplot` as shown below

https://github.com/pycaret/pycaret/blob/915a13d3b4d880b5a0dac0797465217b2ba934b9/pycaret/internal/plots/time_series.py#L783

Currently there is replication of code for these 2 use cases. The subplot approach is more modular (and has been cleaned up). Need to update `plot_acf` and `plot_pacf` to reuse the `corr_subplot` component instead of replicating the code to create these plots again.

**Comment by ngupta23** [comment]
Note: When this change is made, `plot_acf` and `plot_pacf` will be essentially converted to a plotly subplot with 1 row and 1 column. This will allow us to use `corr_subplot` within `plot_acf` as follows (similarly for `plot_pacf`)

```python
fig, acf_data = corr_subplot(fig=fig, data=data, row=1, col=1, plot="acf") 
```

**Comment by ryanxjhan** [comment]
Hi, you can assign this to me.

**Comment by ngupta23** [comment]
@ryanxjhan , Awesome. I have assigned this to you. 

Please create a branch from `time_series` and submit the PR back to the `time_series` branch itself (not `master`)
