### ISSUE TITLE
[BUG] isocalendar().week not works

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#2345]
**Describe the bug**

FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.

**To Reproduce**

My code works --> dados['semana'] = dados['Data'].dt.week

Error after change --> dados['semana'] = dados['Data'].dt.isocalendar().week

**Expected behavior**

No errors

**Additional context**

I have checked, error appear after s = setup(....)
Variables are typed, but variable changed is empty type

After type ENTER show error:
AttributeError: 'float' object has no attribute 'shape'

**Versions**
<details>

3.00

</details>

**Comment by ngupta23** [comment]
What type of analysis are you performing - regression, classification, time_series, other?

You must be using the time_series module package "pycaret-ts-alpha". Currently, it is not integrated with the main pycaret module. If you are doing anything other than time series, please install the main pycaret package for now in a separate environment from pycaret-ts-alpha.

```
pip install pycaret
```

**Comment by celestinoxp** [comment]
you're right. thanks.

**Comment by ngupta23** [comment]
Can you post the complete code with data to reproduce this problem? It is hard to debug without that.

**Comment by celestinoxp** [comment]
> 

https://github.com/celestinoxp/pycaret_tests

**Comment by ngupta23** [comment]
@celestinoxp If the inferred types are not correct, then you can also set them manually in `setup` using arguments like `categorical_features`, `numeric_features`, etc.
