### ISSUE TITLE
[BUG] Model predict after load in 2.3.8 does not work - 'prep_pipe' is not defined

### ISSUE THREAD

**Issue by balgad** [pycaret/pycaret#2348]
**Describe the bug**
After training, finalizing and saving a model, load and predict does not work, "name 'prep_pipe' is not defined" error occured.

**To Reproduce**
I saved notebook and source files [here](https://drive.google.com/drive/folders/17NMU-ZwjXMK_pUkkFqUSzg228XcPAGnT?usp=sharing)

**Versions**
2.3.8, I noticed it works well in 2.3.6

</details>

**Comment by moezali1** [comment]
@Yard1

**Comment by balgad** [comment]
@moezali1 Thanks for your quick reply. It works perfectly, I will use this till fixed. Thanks once again (also for this awesome package)
