### ISSUE TITLE
Clustering plot_model changing the index of the dataset

### ISSUE THREAD

**Issue by ZamoraAndres** [pycaret/pycaret#235]
I found an issue when executing the function:
def plot_model(model, plot='cluster', feature = None, label = False)

This line is changing the index of the dataset and wrongly assigns the cluster label:
[line 2528] b.reset_index(inplace=True, drop=True)

If you remove the line, the plot shows correctly the cluster label for each row.

**Comment by pycaret** [comment]
@ZamoraAndres Thanks for reporting. Is it possible you can provide an example? It will be easier to understand and evaluate the impact before fixing the issue.

**Comment by ZamoraAndres** [comment]
Yes, in this file: https://github.com/pycaret/pycaret/blob/master/clustering.py 

The line 2528 is changing the order of the data, hence assigning the cluster ids to the wrong rows. 

With that line, and by creating a backup attribute based on the original cluster:
data_['Cluster_Backup'] = data_['Cluster']
feature = "Cluster_Backup"

this is the file i received:

  | PCA1 | PCA2 | Cluster | Feature
-- | -- | -- | -- | --
0 | 0.106748 | -0.83035 | Cluster 0 | Cluster 8
1 | 0.21735 | -0.83646 | Cluster 0 | Cluster 9
2 | 0.630243 | -1.52168 | Cluster 0 | Cluster 2
3 | 0.607331 | -2.06602 | Cluster 0 | Cluster 2

and by removing it:

  | PCA1 | PCA2 | Cluster | Feature
-- | -- | -- | -- | --
0 | 0.106748 | -0.83035 | Cluster 8 | Cluster 8
1 | 0.21735 | -0.83646 | Cluster 9 | Cluster 9
2 | 0.630243 | -1.52168 | Cluster 2 | Cluster 2
3 | 0.607331 | -2.06602 | Cluster 2 | Cluster 2

**Comment by pycaret** [comment]
@ZamoraAndres Thank you so much for your help in pointing this out. Can I please ask you to install pycaret-nightly==0.28 in a new environment (or if using the same environment please uninstall pycaret first usig pip uninstall pycaret). 

I have fixed this issue in pycaret.clustering plot_model( plot == 'cluster' / plot == 'tsne').

Can you please test and let me know if this is fine?

I have moved the sorting code after label attachment to avoid the issue of wrong assignment of labels.

Thanks for your help.
