### ISSUE TITLE
ValueError: Estimator cat not available.

### ISSUE THREAD

**Issue by Serg132003** [pycaret/pycaret#2357]
working with pycaret after create_model('cat') got error  
ValueError: Estimator cat not available. Please see docstring for list of available estimators.
i have 
!pip install pycaret[full]

**Comment by ngupta23** [comment]
Did you check the docstring for the list of estimators as indicated by the error message? There is no estimator called "cat".

**Comment by Serg132003** [comment]
Thank you for fast answer. Sorry - I am new to Pycaret - where I can find this 'docstring'?

**Comment by ngupta23** [comment]
@Serg132003 Docstring is a python construct that helps developers document the usage of the function/method and users can refer to them for proper usage. You can find an [overview here](https://www.programiz.com/python-programming/docstrings).
