### ISSUE TITLE
Add setup run check method to base class of experiment

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#2359]
Currently the checks reside in the time series module. It would be better to move them to base class so that all task types can benefit from it.

O, we went with a private method for now. Currently, it is in the time series module only. Later we may add it to the base class itself.

_Originally posted by @ngupta23 in https://github.com/pycaret/pycaret/pull/2354#discussion_r841081569_

**Comment by ngupta23** [comment]
If anyone from the community wants to pick this up, please get in touch with @Yard1 for guidance.

**Comment by moezali1** [comment]
@reza1615 Can you help with this please?
