### ISSUE TITLE
[BUG] Training Time Not Accurate

### ISSUE THREAD

**Issue by ryanxjhan** [pycaret/pycaret#2362]
**Describe the bug**

The training time for some models is indicated as a few seconds when it actually takes 5 - 10 minutes to train.

**To Reproduce**

```python
best = compare_models()
```

**Expected behavior**

**Additional context**

**Versions**
2.3.9
<details>

 

</details>

**Comment by ngupta23** [comment]
Hi @ryanxjhan, can you provide a complete reproducible example and which model time is inaccurate?

**Comment by ryanxjhan** [comment]
@ngupta23 Sorry, I thought this was already a well-known issue. I was doing a regression task. And the `compare_model` training time was never near accurate. I used it for a couple times, and the margin is usually more than 10x (est.). So if it says it took 60 sec to train, it in fact will take 10 - 15 minutes to train. This is especially obvious for tree-based models.

**Comment by ngupta23** [comment]
@ryanxjhan the time noted there is the average time for each fold only. If you have 10 folds, the total time will be ~10x. Plus in the end, the model is also trained on the entire train dataset as well. That time is not included in there.
