### ISSUE TITLE
Converting target column into numerical feature is not supported. 

### ISSUE THREAD

**Issue by anuj-glitch** [pycaret/pycaret#237]
Wrongly detecting the target column in my dataset as a categorical feature whereas, it is actually a numerical feature.
and when I am trying to force convert it into a numerical feature, getting this error?

(Value Error): Column type forced is either target column or doesn't exist in the dataset.

**Comment by pycaret** [comment]
@anuj-glitch Thanks for reporting. I believe you are trying to do Regression? Can you show head of your data?

**Comment by anuj-glitch** [comment]
yes, I am doing Regression.
And here is the head of my dataset.

![image](https://user-images.githubusercontent.com/48061059/85301732-d434ab80-b4c5-11ea-946e-cf39c2056a7e.png)

**Comment by anuj-glitch** [comment]
If, I just leave it as a categorical feature and build a model, then in prediction it is giving me the same value(1874) for all the test samples. that's why I am thinking it is taking this column as a categorical feature.

**Comment by pycaret** [comment]
@anuj-glitch Can you share the dataset?

**Comment by anuj-glitch** [comment]
Dataset -

[Train.zip](https://github.com/pycaret/pycaret/files/4813992/Train.zip)

**Comment by pycaret** [comment]
@anuj-glitch Hi. I have tried this on my end and it works without any issues. Please see my code:

import pandas as pd
data = pd.read_csv('Train.csv')
data.head()

**#initialize setup**
from pycaret.regression import *
reg1 = setup(data, target = 'Attrition_rate', ignore_features=['Employee_ID'])

**#train lr model**
lr = create_model('lr')

**#predict holdout**
pred = predict_model(lr)
pred.head()
