### ISSUE TITLE
[BUG] NameError for _ml_usecase when using evaluate_model()

### ISSUE THREAD

**Issue by anunaykumar03** [pycaret/pycaret#2373]
**Describe the bug**

NameError: name '_ml_usecase' is not defined
This bug keeps showing anytime I run the evaluate_model() function

**To Reproduce**

```python
from pycaret.classification import *

model = load_model('trained_model') #this step works and confirmed by the message Transformation Pipeline and Model Successfully Loaded

evaluate_model(model) #this is where the error hits
```

**Expected behavior**

**Additional context**

**Versions**
2.3.9
<details>

</details>

**Comment by ngupta23** [comment]
Did you run setup before running `evalaute_model`? I think `evaluate_model` required the user to run setup first (when the model is loaded)

**Comment by anunaykumar03** [comment]
> 
I ran setup while creating and saving the model. I am not sure how to run setup after load_model(), since I thought the load_model would automatically load the saved setup and everything from the pkl file.

**Comment by ngupta23** [comment]
No, the setup is not saved. You can run the setup using the same settings as you used to create the model and then it should work. Please check and confirm.

**Comment by ngupta23** [comment]
Related to https://github.com/pycaret/pycaret/issues/2359

**Comment by moezali1** [comment]
@anunaykumar03 If you trying to access plots from the saved model, you must use `save_config` and `load_config` function to load the environment in addition to the model before you can use `plot_model`, `evaluate_model`, etc.

**Comment by anunaykumar03** [comment]
The save_config made it work! Thanks
