### ISSUE TITLE
`develop` branch + Time Series merge

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#2374]
**Is your feature request related to a problem? Please describe.**
Any documentation updates (on `master`) for unreleased version of PyCaret get published automatically. Propose using a `develop` branch going forward.

Plus `time_series` branch needs to be merged into `master` for 3.0.0 release.

**Describe the solution you'd like**

- [x] Create `develop` branch from `master`
- [x] Merge `develop` branch into `time_series`.
- [x] Merge back `time_series` branch into `develop`
- [x] All future PRs go into `develop`
- [x] When releasing, we merge `develop` into `master`

**Additional context**
Refer: https://github.com/pycaret/pycaret/issues/2172#issuecomment-1046036507

**Comment by ngupta23** [comment]
@Yard1 Are there any pending items here? Do we need to create a separate `release` branch which should be used for all API documentation (readthedocs)?

**Comment by Yard1** [comment]
I think that is not necessary, we just need to make sure to configure RTD to use stable (latest non-prerelease tag) by default.

**Comment by ngupta23** [comment]
Tracking documentation here: https://github.com/pycaret/pycaret/issues/2695
