### ISSUE TITLE
[BUG] ImportError: cuML is outdated or not found. Required version is >=0.15, got 1.3.3

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#2377]
**Describe the bug**

I'm investigate some code of pycaret and i think i found some things to pycaret team investigate...

**To Reproduce**

I have code for use gpu like use_gpu = True, but if someone try use a word to force use of gpu like use_gpu = "force", can rceive an curious warning: 

ImportError: cuML is outdated or not found. Required version is >=0.15, got 1.3.3

```python
from pycaret.classification import *
s = setup(dados, target = 'target', use_gpu = "force", fold = 5, session_id = 123, data_split_shuffle=False)
```

**Expected behavior**

**Additional context**

**Versions**
<details>

pycaret 2.3.9
windows 10 (64bits)

</details>

**Comment by moezali1** [comment]
@Yard1 please help.

**Comment by Yard1** [comment]
@celestinoxp Can you upload the `logs.log` file and post it here?

**Comment by celestinoxp** [comment]
[logs.log](https://github.com/pycaret/pycaret/files/8504524/logs.log)

**Comment by MindBack** [comment]
cuML has sckit-learn dependency conflict with pycaret, cuML requires scikit-learn=0.24 while pycaret has scikit-learn==0.23.2, and the latest pycaret dependency is going to be scikit-learn>=1.0.

**Comment by celestinoxp** [comment]
cuML not support windows. Only work in windows via Windows WSL.
