### ISSUE TITLE
My target value is showing as label

### ISSUE THREAD

**Issue by malikergin** [pycaret/pycaret#2380]
![image](https://user-images.githubusercontent.com/83214499/162099563-1c2822bd-adf5-4dd3-9531-98e81d8af1ca.png)

![image](https://user-images.githubusercontent.com/83214499/162099608-a27d0af8-0912-48ea-9752-1f2d9c353425.png)

dmi is my target value and numeric but it's showing label.

**Comment by ngupta23** [comment]
In `setup`, you can specify the data types if the autodetection is not per your liking. Have you tried it?

**Comment by malikergin** [comment]
@ngupta23 yes I've tried but it gave me this error ;
![image](https://user-images.githubusercontent.com/83214499/162597296-45fed586-b571-4ceb-9dce-6b302cfb4b51.png)

**Comment by ngupta23** [comment]
Did you check the type of the target column before feeding it to pycaret?

**Comment by malikergin** [comment]
For example when I change the target value like "dof" this time this variable shows the "label".  I checked my column's type. Float64

**Comment by ngupta23** [comment]
You will need to share a minimally reproducible example (code + data) for someone to have a more detailed look.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by malikergin** [comment]
data:
https://drive.google.com/file/d/1315wxSH8GoEjwiyj4PeWON5pbvzFeYLd/view?usp=sharing



`import pandas as pd
from pycaret.regression import *

dataset = pd.read_csv('malik.csv')

data = dataset.sample(frac=0.9, random_state=786)
data_unseen = dataset.drop(data.index)

data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions: ' + str(data_unseen.shape))

exp_reg102 = setup(data = data, target = 'dmi', session_id=123)


`

**Comment by ngupta23** [comment]
The error message is pretty clear. Your dataset does not have any column called "dmi"

![image](https://user-images.githubusercontent.com/33585645/162810429-bce5a9de-8fa9-48a3-a399-3406e71416c2.png)

**Comment by malikergin** [comment]
Sorry. I changed it but the problem still exists

**Comment by malikergin** [comment]
Do u have any idea why target value is label ?

**Comment by malikergin** [comment]
![image](https://user-images.githubusercontent.com/83214499/162839208-009befdb-99c0-41e1-b1a6-79d585b6c645.png)
I changed target value as 'finwght'. It's showing label again.

**Comment by ngupta23** [comment]
I think it is just calling the target column as label. It works fine though (see attached run on colab)

https://nbviewer.org/gist/ngupta23/3078c5aac7842cbdc3e697a6307a6da6

**Comment by malikergin** [comment]
Understood. Thank you for your interest 👍
