### ISSUE TITLE
[BUG] installation error with Python 3.10

### ISSUE THREAD

**Issue by rajatscibi** [pycaret/pycaret#2381]
installation error with numpy during normal installation and installation error with scikitlearn for anaconda 
![python_error](https://user-images.githubusercontent.com/74652470/162146121-0a10e788-19c6-4e5a-a24a-85807693978a.png)
![python_error1](https://user-images.githubusercontent.com/74652470/162146122-77bc0685-4b0e-43f6-9d9c-10d3ffc790f3.png)
![python_error3](https://user-images.githubusercontent.com/74652470/162146112-b4e8251e-5b25-4d5b-adea-24974683fbb1.png)

**Describe the bug**

**To Reproduce**

```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by ngupta23** [comment]
I think you have many libraries already installed on the environment that you are on. Some of them may be interfering with the installation of `pycaret`. Can you try creating a clean python environment and install `pycaret` using pip?

**Comment by rajatscibi** [comment]
ok Nikhil, I'll try it and get back to you. 

Thanks for your input.

**Comment by SebastianBelmonte95** [comment]
I've tried installing on a clean environment and i'm getting a similar error.
![image](https://user-images.githubusercontent.com/76168625/162287470-9912fbf6-525e-4c5f-a3e3-7a80f28e3ec7.png)

**Comment by rajatscibi** [comment]
I got these replies from **_numpy_** and **_scikit-learn_** communities:

**_Numpy:_** "Since [pycaret requires](https://github.com/pycaret/pycaret/blob/master/requirements.txt#L2) scipy < 1.5.4, I would strongly recommend you use python3.9 or less since there are precompiled binary wheels for that combination. If you use python3.10 you must compile from source, which is not easy."

**_scikit-learn:_** "PyCaret pins scikit-learn to 0.23.2: https://github.com/pycaret/pycaret/blob/16b641a4ce99eb1495477ac6008182d712c73d51/requirements.txt#L7 which does not support Python 3.10.

I suggest using Python 3.8 if you want to use scikit-learn 0.23.2. This way you'll get the wheel [from PyPi](https://pypi.org/project/scikit-learn/0.23.2/#files) and do not need to build it locally."

I am yet to try this. Will report when I have tried. If you get any success kindly let us know here.

**Comment by ngupta23** [comment]
Yes, python 3.10 is not supported. Try 3.8 to be on the safe side. 

The supported python versions should be available on GitHub and on the pypi page.

**Comment by ngupta23** [comment]
The 3.0.0 release of pycaret will short python 3.9 (but still not 3.10).

**Comment by SebastianBelmonte95** [comment]
Aye, 3.8 Worked like a charm as long as it was a clean slate. Thank you guys!

**Comment by ngupta23** [comment]
Update on this: pycaret 3.0.0 was officially released a few days back and supports python 3.7, 3.8, 3.9 and 3.10 now.
