### ISSUE TITLE
[BUG] compare_models in regression Pycaret appear a empty dataframe in databricks

### ISSUE THREAD

**Issue by vivi-scarpioni** [pycaret/pycaret#2385]
**Describe the bug**
 I'm trying running the compare_models in regression module of Pycaret in databricks but return a empty dataframe. I already tried n_jobs =1 and html = False, but didn't work :(
**To Reproduce**

```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by ngupta23** [comment]
There is not enough data here to provide any feedback. Please provide a minimally reproducible example (code + data). See the following for details:

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by moezali1** [comment]
@vivi-scarpioni This is because when there is an exception with one of the models it skips that. In your situation, it seems like all models are failing. Can you please pass `errors = 'raise'` inside your `compare_models` function and let us know what is the error message?

**Comment by moezali1** [comment]
Not enough details.
