### ISSUE TITLE
int32 issue

### ISSUE THREAD

**Issue by ajayprakashm** [pycaret/pycaret#24]
Hi,
I tried to use the package for classification problem, and when i entered the dataframe with target data in setup environment and ran the code, it showed no dtype for the dataframe, but it has dtype of 'int32'. When i changed the dtype to int64, it worked. Can you fix this issue.

**Comment by pycaret** [comment]
issue noted. classifying as bug.

**Comment by mfahadakbar** [comment]
@ajayprakashm can you share the data? want to replicate it

**Comment by ajayprakashm** [comment]
[edata.xlsx](https://github.com/pycaret/pycaret/files/4508810/edata.xlsx)

Load the data and convert data into dtype 'int32' for F1, F2, F3 and F4 and run the setup from pycaret, after executing you should see blank in data types.
