### ISSUE TITLE
[BUG] Exception: Could not deserialize ATN with version � (expected 4).

### ISSUE THREAD

**Issue by Kon3000** [pycaret/pycaret#2401]
from pycaret.classification import *
s = setup(data, target = 'Class variable')
Exception: Could not deserialize ATN with version  (expected 4).

**Comment by ngupta23** [comment]
@Yard1 

We are getting this error in unit tests as well now. Must be related to some underlying library dependency changes.

https://github.com/pycaret/pycaret/actions/runs/2150556969

**Comment by ngupta23** [comment]
But why would fugue impact pycaret when it is not being used in that situation? Do we need to make any changes to our code?

**Comment by Yard1** [comment]
It's due to an import. This situation only occurs when fugue is installed (and we install it in CI). We can probably avoid this until fugue is actually used, yes. I'll make a PR.

**Comment by Kon3000** [comment]
thank you, I am still trying to run the set up in Colab. Now I get this:

from pycaret.regression import *
s = setup(data, target = 'charges')

AttributeError: module 'tornado.ioloop' has no attribute '_Selectable'

**Comment by Yard1** [comment]
Restart runtime after all pip installs.

**Comment by ngupta23** [comment]
This is fixed in 3.0.0 (RC release). Hence, closing.
