### ISSUE TITLE
Extracting train and test data created by setup in Pycaret

### ISSUE THREAD

**Issue by sparvaneh** [pycaret/pycaret#241]
Hi,

Is there any way to extract the train and test data that are created by Pycaret? 
Is there any way to provide train and test data to Pycaret and skip data splitting using Pycaret?

**Comment by pycaret** [comment]
@sparvaneh Thanks for asking. Not possible at the moment. Tagging this as an enhancement for future release.

**Comment by bjuncklaus** [comment]
There's actually a way of retrieving it after `setup` @sparvaneh . The `setup` documentation is this: "This function returns various outputs that are stored in variables as tuples. They are used by other functions in pycaret.". However, after analyzing the source code I found out that the function returns a tuple with this content:
- `X`
- `y`
- `X_train`
- `X_test`
- `y_train`
- `y_test`
- `seed`
- `prep_pipe`
- `experiment__`

So if you have a variable with the content return by the `setup` function you can retrieve the train/test data back by accessing its corresponding tuple index. For example `my_setup = setup(...)` then `X_test_data = my_setup[3]`.

I suggest adding this info to the documentation asap.

**Comment by pycaret** [comment]
Function available in PyCaret 2.0. please check documentation.

**Comment by mvpalheta** [comment]
which is the function ?

**Comment by sparvaneh** [comment]
Please check get_config
For getting training data you can use
training_data = get_config(variable="X_train")

**Comment by miteshyadav** [comment]
Is there a feature that let's users pass their own train test instead of letting it generate automatically by pycaret?

**Comment by Yard1** [comment]
@miteshyadav `setup(test_data=test_df)`
