### ISSUE TITLE
Modularize customization of time series plots

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#2417]
**Is your feature request related to a problem? Please describe.**
In time series plotting module, lot of plots are customized at the end - template, fig size, etc. Since the same code is repeated in all these plots, maybe this could be modularized and reused.

```python
with fig.batch_update():
    template = _resolve_dict_keys(
        dict_=fig_kwargs, key="template", defaults=fig_defaults
    )
    fig.update_layout(title=title, showlegend=False, template=template)

    fig = _update_fig_dimensions(
        fig=fig, fig_kwargs=fig_kwargs, fig_defaults=fig_defaults
    )
```

**Comment by ryankarlos** [comment]
@ngupta23  could you assign this to me please  ?

**Comment by ngupta23** [comment]
Thanks @ryankarlos. I have assigned it to you.
