### ISSUE TITLE
Predictions on unseen data when Cardinal Encoding is used

### ISSUE THREAD

**Issue by sparvaneh** [pycaret/pycaret#242]
Hi, 

I had variables with high cardinality and used "high_cardinality_features" option in setup. Using unseen_predictions = predict_model(final_xgboost, data=data_unseen), I am getting the following error:
"ValueError: Number of features of the model must match the input. Model n_features is 1078 and input n_features is 49 "

I am wondering if there is any way to use Pycaret for Cardinal Encoding to make unseen feature vector similar to what was used for training.

Thanks,
Saman

**Comment by pycaret** [comment]
@sparvaneh Thanks for reporting. Can you share the dataset and the code you are using.

**Comment by sparvaneh** [comment]
Restarting notebook, resolved the issue. 
Initially I create a model without "high_cardinality_features" and the second round I added "high_cardinality_features" that got me to the error message!

**Comment by pycaret** [comment]
@sparvaneh Thanks for sharing.
