### ISSUE TITLE
[BUG] Getting "Key" error on running plot_models on loaded models.

### ISSUE THREAD

**Issue by maverick-scientist** [pycaret/pycaret#2421]
**Describe the bug**
I am getting "Key" error (here, key is the target column) while running plot_models on loaded models that were saved and loaded successfully.

**To Reproduce**

tuned_model = load_model(model_path, model_name)
plot_models(tuned_model, "class_report")
plot_models(tuned_model, "feature")
plot_models(tuned_model, "confusion_matrix")

**Expected behavior**
The plots should run just fine.

**Additional context**
The models were saved with default values.

**Versions**

2.3.10

**Comment by ngupta23** [comment]
Did you run `setup` again before loading the models?

**Comment by maverick-scientist** [comment]
Hi Nikhil,

Yes I did. I then loaded the saved models. I just don’t wish to retrain the
modes when I have them saved. And yes, model metadata was also saved
automatically.

Please advise.

Best Regards,
Abhinav

**Comment by ngupta23** [comment]
Can you add a complete reproducible example so we can debug? See here: 

📌 Overview: http://ow.ly/LoIv50IL5RQ
📌 Examples (Do's and Dont's): http://ow.ly/AXKm50IL5RR

**Comment by maverick-scientist** [comment]
Steps to reproduce:

from pycaret.classification import *

exp01 = setup(data=data, target="Churn", session_id=789, ignore_features=["CUSTOMER_ID"],normalize=True,
feature_selection=True,log_experiment = True, experiment_name = 'churn_04',
log_plots=True, log_profile=True, handle_unknown_categorical=True,
unknown_categorical_method='least_frequent',
numeric_imputation='mean',
categorical_imputation='constant',
profile=True,
profile_kwargs={"explorative" : True, "minimal" : True},
fix_imbalance=False)

model_paths = "path to the saved models"
tuned_model = load_model(model_paths+'tuned_model_version0.1_17apr22')

plot_model(tuned_model, "class_report")

I have also attached a screenshot of the error for your reference. One thing I noticed, when this command was run, it started "Processing" as if it was re-running the "setup" command and also prompted the inferred types (categorical and numerical) and asked for a confirmation before proceeding. This is exactly what happens when we run the "setup" command. Immediately after I confirmed, I got the error.

![image](https://user-images.githubusercontent.com/86669440/163754191-c55b301c-cf16-4a0e-a565-e053f450af0c.png)


I could only share this much due to compliance policies in place.

Is there some parameter I'm missing in the "setup" method?

Please advise.

Thanks,
Abhinav

**Comment by maverick-scientist** [comment]
Just to add, "Churn" is the target column and is a part of "data" that was used in the "setup" method.

**Comment by ngupta23** [comment]
@maverick-scientist again, there is not enough information here to recreate the issue or debug it. Note that if the data is proprietary, you can create a fake dataset yourself to recreate the issue. 

- The do's and dont's have an example of how to create the fake data - minimal to reproduce the problem.
- Alternately, you could try to reproduce the issue with a publicly available dataset or one available in pycaret itself.

Also
- we need to also see how the model was created before saving as that may offer clues.
- do not paste error message images. We need the complete error stack trace to provide useful feedback. Again the do's and dont's have examples of how to provide this information.

**Comment by ngupta23** [comment]
@maverick-scientist Please see attached. It is not very difficult to create a reproducible example using a publicly available dataset.

In this case, the issue seems to be with the way you are saving the model. If you want to continue the experiment again, you must save the model only (without pipeline). When you do the setup again later and load the "model only", the preprocessing pipeline is added at that time. If you try to load a "model with pipeline" it will try to add a pipeline on top of the already existing pipeline and this will lead to errors (such as the one you are getting).

I would highly recommend that you try to create reproducible examples like this for the other issues that you have filed as well.

https://github.com/pycaret/pycaret/issues/2425
https://github.com/pycaret/pycaret/issues/2420


https://nbviewer.ipython.org/gist/ngupta23/0073a48a1e57ac7728d0b81e9ff9e899

![image](https://user-images.githubusercontent.com/33585645/163902747-efa200d8-51fa-467b-a888-598a33007dc5.png)

**Comment by ngupta23** [comment]
FYI... in the next major release (3.0.0), this should work even if you load a model with the pipeline (@Yard1, @tvdboom - please confirm).

You can try it out by installing pycaret-ts-alpha (which acts as a temporary RC release of pycaret 3.0.0) in a new environment (not in the same one where you currently have pycaret installed).

```python
# This will work in 3.0.0 when the model with the pipeline is loaded back and used with plot_model
save_model(model, "test_model", model_only=False)
```

https://nbviewer.ipython.org/gist/ngupta23/38316b18a81d22a5605f5e89ce53355f

**Comment by maverick-scientist** [comment]
Thank you for the detailed explanation.

Does that mean that if I save the mode with metadata, I don’t need to run
setup?

Also, could you please share the code for loading model only?

Many thanks.

Abhinav

**Comment by ngupta23** [comment]
The code is already there in the link I shared. Please go through it
carefully.

**Comment by maverick-scientist** [comment]
I see it. Thank you. While loading, there’s no choice of loading model
only. We load what we saved. Thanks.
