### ISSUE TITLE
[BUG] mlflow ui never runs

### ISSUE THREAD

**Issue by maverick-scientist** [pycaret/pycaret#2425]
**Describe the bug**
Getting error "FileNotFoundError: [WinError 2] The system cannot find the file specified" while running "mlflow ui".

**To Reproduce**
Run "mlflow ui"

**Expected behavior**
It should run without any issues

**Versions**
2.3.10

Not sure if this is the right forum to post this issue. If it is not, please ignore.

**Comment by ngupta23** [comment]
@maverick-scientist there is not enough information here to recreate or debug the issue. Please provide a complete reproducible example so we can debug. Also, note that if the data is proprietary, you can create a fake dataset yourself to recreate the issue. Refer to the following for more details:

📌 Overview: http://ow.ly/LoIv50IL5RQ
📌 Examples (Do's and Dont's): http://ow.ly/AXKm50IL5RR

- The do's and dont's have an example of how to create the fake data - minimal to reproduce the problem.
- Alternately, you could try to reproduce the issue with a publicly available dataset or one available in pycaret itself.

Thanks!

**Comment by ngupta23** [comment]
@maverick-scientist Honestly, I would prefer not to do that since it sets the wrong precedent for the open-source community and is not sustainable in the long run. The globally accepted best practice is to provide a minimal reproducible example and I would encourage you to do that.

Thanks!

**Comment by maverick-scientist** [comment]
Hi Nikhil,
Attaching the code file to reproduce this issue. Could you please check and tell me what's wrong with it or my machine?

Thanks & Regards,
Abhinav

[Simple MLflow.zip](https://github.com/pycaret/pycaret/files/8511837/Simple.MLflow.zip)

**Comment by ngupta23** [comment]
@maverick-scientist The example that you posted has no reference to pycaret. It is a generic MLFlow example. How is it related to pycaret and this repo?

**Comment by maverick-scientist** [comment]
Hi Nikhil,
Thank you for your reply. However, if you read the issue carefully, I’d
clearly mentioned my dilemma whether it was the right forum to post this
issue.

Anyways, thanks for your support. I’d try and see what’s preventing the
MLFlow to run properly on my machine.
