### ISSUE TITLE
Does pycaret supports anomaly detection for time series data in real time

### ISSUE THREAD

**Issue by sathishkumar999** [pycaret/pycaret#243]
Could you please add time series visualization plots identifying anomalies instead of using powe bi. which is good for evaluating in pycaret library itself.

![Screenshot (210)](https://user-images.githubusercontent.com/40235632/85715990-a2138b80-b709-11ea-95e9-ca4a76d66c9b.png)

**Comment by pycaret** [comment]
@sathishkumar369 Thanks. Can you please provide some example of plots you are proposing?

**Comment by sathishkumar369** [comment]
Hi moez!
I know pycaret supoorts anomaly detection.
what i'm proposing is that I want to visualize the anomalies in time series format plots.
I have seen only clustered anomaly detection plots in pycaret.

![image](https://user-images.githubusercontent.com/40235632/85840387-0726ba00-b7ba-11ea-8b00-67b78b573313.png)
![image](https://user-images.githubusercontent.com/40235632/85840517-3806ef00-b7ba-11ea-8341-0ec1c4f302e8.png)

**Comment by Tinnguy** [comment]
Hi,

I need to use anomaly detection with timeseries data and plots as described above. It seems this plot feature is added. Is it available in 2.3 version? Is there any documentation on how to plot it

**Comment by ngupta23** [comment]
Hi @sathishkumar999 @Tinnguy , Hopefully [this article](https://towardsdatascience.com/time-series-anomaly-detection-with-pycaret-706a6e2b2427) from @moezali1 will help answer your questions.
