### ISSUE TITLE
NameError: name 'export_model' is not defined

### ISSUE THREAD

**Issue by gkv856** [pycaret/pycaret#2432]
```
from pycaret.datasets import get_data
boston = get_data('boston')
from pycaret.regression import *
exp_name = setup(data = boston,  target = 'medv')
lr = create_model('lr')
lr_java = export_model(lr, 'java')
```

I got an error saying "export_model" is not defined. 
As per the documentation, it should be under pycaret.regression package.
https://pycaret.readthedocs.io/en/latest/api/regression.html#pycaret.regression.convert_model

**Comment by ngupta23** [comment]
What version of pycaret are you using?

**Comment by gkv856** [comment]
yeah that is correct. I guess we need to update the documentation.

**Comment by ngupta23** [comment]
Correct. Thanks for pointing it out.
