### ISSUE TITLE
Anomaly Detection Power BI

### ISSUE THREAD

**Issue by luistelmocosta** [pycaret/pycaret#244]
Hello, I was following [this tutorial ](https://towardsdatascience.com/build-your-first-anomaly-detector-in-power-bi-using-pycaret-2b41b363244e) to use pycaret in Power BI and get the outliers for a certain table. I was wondering if it is possible to get the column and row where the anomaly is found instead of only returning the row

Kind regards, 
Luís

**Comment by pycaret** [comment]
@luistelmocosta Hi. You can use filter the output from PyCaret in Power Query. If you filter out for Label = 1 (this will select all the outliers). 

Hope this helps.

**Comment by luistelmocosta** [comment]
That's not what I want. If I filter out for Label = 1 it will give me the row-wise outliers. I guess I am looking for some kind of interpreability, which column(s) were important for the row to be an outlier.
