### ISSUE TITLE
Disable logging output in Jupyter notebooks.

### ISSUE THREAD

**Issue by ekamperi** [pycaret/pycaret#2440]
**Is your feature request related to a problem? Please describe.**
While loading a pre-trained model & using it to generate predictions inside a Jupyter notebook, I get tons of logging messages, like:

```
INFO:logs:Initializing load_model()
INFO:logs:load_model(model_name=../scripts/saved_tuned_bm_00007, platform=None, authentication=None, verbose=True)
INFO:logs:Initializing predict_model()
INFO:logs:predict_model(estimator=Pipeline(steps=[('dtypes',
                 DataTypes_Auto_infer(display_types=False,
                                      ml_usecase='classification',
                                      target='label')),
[...]
```

**Describe the solution you'd like**
I'm not sure if PyCaret uses the root logger or a custom logger. If the former, then perhaps do the latter?

**Describe alternatives you've considered**
I tried many workarounds from StackOverflow on how to disable logging from imported modules, but none really worked.

**Additional context**
This is a screenshot from my notebook, where I get flooded by the logging messages:
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/9994264/163970165-a8d49599-4346-490c-9f53-be133d217b8d.png">

**Comment by moezali1** [comment]
@ekamperi Sometimes this is caused by conflict of logger with some other libraries that you may be using in your environment. You can solve this problem by running following code on the top of your notebook:

```
import os
os.environ["PYCARET_CUSTOM_LOGGING_LEVEL"] = "CRITICAL"
```
