### ISSUE TITLE
[BUG] NLP module setup functions fails (locally, also on colab)

### ISSUE THREAD

**Issue by SRoy1024** [pycaret/pycaret#2441]
**Describe the bug**

While trying to recreate the steps from https://pycaret.gitbook.io/docs/get-started/quickstart#natural-language-processing

the code fragment `s = setup(data, target = 'en')` fails

**To Reproduce**

1. On Ubuntu:
Description:	Ubuntu Jammy Jellyfish (development branch)
Release:	22.04
Codename:	jammy
------------------------
```bash
conda create --name env_1Pycaret python=3.9
conda activate env_1Pycaret
pip install pycaret
python -m spacy download en_core_web_sm
```
1a: open Test_NLP.ipynb in vscode

```python
# load dataset
from pycaret.datasets import get_data
data = get_data('kiva')

# print first document
print(data['en'][0])

# init setup
from pycaret.nlp import *
s = setup(data, target = 'en')
```

2. On Colab
```python
!pip install pycaret
# load dataset
from pycaret.datasets import get_data
data = get_data('kiva')
# print first document
print(data['en'][0])
# init setup
from pycaret.nlp import *
s = setup(data, target = 'en')
```

**Expected behavior**
(https://1927305171-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FFLpROzBBqocwXBoemLJC%2Fuploads%2FD0iN8ziE9gqEowySsO9T%2Fimage.png?alt=media&token=da4392e8-2b41-4657-827d-3cd7d78a12d9)

**Additional context**
![image](https://user-images.githubusercontent.com/49712315/163973031-f50832d8-830a-4a96-a095-a11fe464b64d.png)

![image](https://user-images.githubusercontent.com/49712315/163973291-2df892ca-6d19-45e1-a217-24022df054e3.png)

**Versions**
<details>
'2.3.10'
</details>

**Comment by ngupta23** [comment]
Please use python 3.8 for now. Python 3.9 will be supported in the next major release of pycaret i.e. 3.0.0

**Comment by ngupta23** [comment]
It is working fine for me on Colab. See this notebook:

https://gist.github.com/ngupta23/f2054ca79ea851965c0193d7ef2a7874

**Comment by SRoy1024** [comment]
> Please use python 3.8 for now. Python 3.9 will be supported in the next major release of pycaret i.e. 3.0.0

Thanks, Will try: maybe its the non-LTS version (v22.x) of Ubuntu that's causing the problem

FYI: based on [this](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp) I upgraded numpy, and then I could go through the tutorial (NLP one, both locally as well as in colab)

**Comment by SRoy1024** [comment]
> It is working fine for me on Colab. See this notebook:
> 
> https://gist.github.com/ngupta23/f2054ca79ea851965c0193d7ef2a7874

thanks: [this](https://gist.github.com/SRoy1024/1aa26f95aa29719d2f0cde4567a3aff2) is mine (after the numpy upgrade)

**Comment by ngupta23** [comment]
Glad you could get it resolved. The upcoming release will pin numpy to around the same version that you have. 

https://github.com/pycaret/pycaret/blob/3c1c02f9def66d922cbd466c5dffda46f886b925/requirements.txt

We will close this issue since it seems to be resolved. Feel free to reopen if the issue persists.
