### ISSUE TITLE
[BUG] upgrade shoud update dependencies

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#2442]
**Describe the bug**

I used `pip install --upgrade pycaret[full]` command and pycaret upgraded from version 2.3.9 to 2.3.10. So far so good. What I found is that the dependencies weren't updated... shouldn't they be updated as per requirements.txt? or in this case I used pycaret[full] should update according to requirements-optional.txt.

I also tried uninstalling pycaret and re-installing it again and only pycaret was installed, but the installation didn't touch the dependencies because they were already installed... but shouldn't the pycaret install check the dependencies versions and update them?

Finally I managed to update the dependencies through the command
`pip install --update -r https://raw.githubusercontent.com/pycaret/pycaret/master/requirements.txt`

and then for the optional dependencies:
`pip install --update -r https://raw.githubusercontent.com/pycaret/pycaret/master/requirements-optional.txt`

Question: Should pycaret installation update dependencies? (Maybe check wen is first instalattion).

I believe that most users who use pycaret, have dependencies on old versions and don't enjoy all the advantages of having the updated versions.

Simple test for all pycaret users, use command: `pip install --upgrade pycaret`

Now in jupyter notebook, for example

```
import pycaret
pycaret.__version__
```

If it's 2.3.10, it's OK.

```
import pandas as pd
pd.__version__
```

If it is < 1.4.1, the installation did not update the dependencies, so they will only be updated with the command `pip install --update -r https://raw.githubusercontent.com/pycaret/pycaret/master/requirements.txt`

Note: Example of pandas but can with other dependence in requeriments.txt

this test was run on:
- windows 10 (64bits)
- python 3.8.13
- pip 22.0.4

**Comment by moezali1** [comment]
@Yard1 @tvdboom What are your thoughts here?

**Comment by Yard1** [comment]
We can't really change pip's behavior.
