### ISSUE TITLE
INSTALLATION: Can PyCaret support scikit-learn >=0.24.2 and scipy >= 1.7.1 ? Hope the future updates can support these 2 versions

### ISSUE THREAD

**Issue by mingjun1120** [pycaret/pycaret#2444]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Windows-10-10.0.19044-SP0

### Installation Method

pip install

### pycaret Version

2.3.10

### Python Version

3.8.12

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by ngupta23** [comment]
Yes, in the next major release (3.0.0), we will upgrade these library versions. See the requirement file here for version numbers. 

https://github.com/pycaret/pycaret/issues/2441#issuecomment-1103704420

**Comment by mingjun1120** [comment]
@ngupta23 The `numpy` maximum only can support version 1.20.0?
For the `scikit-learn` library, could it be >= 0.24.2?

**Comment by ngupta23** [comment]
> For the scikit-learn library, could it be >= 0.24.2?

No, there were syntax changes in the 1.0.x version (if I am correct). We will be switching to the latest one (> 1.0.x) in the 3.0.0 release.

> The numpy maximum only can support version 1.20.0?

In order to maintain compatibility with other modules that get installed, this might be the case. But you can manually try changing it to a different version yourself to see if it works (no guarantees though).

**Comment by mingjun1120** [comment]
> > For the scikit-learn library, could it be >= 0.24.2?
> 
> No, there were module changes in sklearn 1.0.x version (if I am correct). We will be switching to the latest one (> 1.0.x) in the 3.0.0 release.
> 
> > The numpy maximum only can support version 1.20.0?
> 
> In order to maintain compatibility with other modules that get installed, this might be the case. But you can manually try changing it to a different version yourself to see if it works (no guarantees though).

Ok

**Comment by mingjun1120** [comment]
@ngupta23 
When will pycaret version 3.0.0 be released?

**Comment by ngupta23** [comment]
@mingjun1120 The release candidate should be released in a month or so. You can track the progress here:

https://github.com/pycaret/pycaret/milestone/5

**Comment by mingjun1120** [comment]
> @mingjun1120 The release candidate should be released in a month or so. You can track the progress here:
> 
> https://github.com/pycaret/pycaret/milestone/5

I see. Hope the version 3.0.0 can successfully be released on time!!! (I really need the version 3 😭)
