### ISSUE TITLE
[DOC]: Setting 'warn_independent_sampling' to False for Optuna TPEsampler

### ISSUE THREAD

**Issue by zeydabadi** [pycaret/pycaret#2446]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://pycaret.gitbook.io/docs/get-started/release-notes#tune_model-1

### Documentation problem

There is no reference on how to set '`warn_independent_sampling`' to `False` when using `optuna` as the `search_library` in `tune_model()`

### Suggested fix for documentation

Perhaps it should be added as an example in docstring of `tune_model` how to pass specific parameters to the search_library methods.

**Comment by ngupta23** [comment]
Just curious: Can this be passed to the tune_model call [using kwargs](https://pycaret.readthedocs.io/en/latest/api/classification.html#pycaret.classification.tune_model)?

e.g. 

```python
## adding more trials to optuna study
tuned_model, tuner = tune_model(
    tuned_model,
    search_library='optuna',
    search_algorithm='tpe',
    early_stopping='asha',
    choose_better=False,
    verbose=True,
    tuner_verbose=5,
    return_tuner=True,
    **{'warn_independent_sampling': Sth}  ## <-- additional kwargs
)
```

**Comment by zeydabadi** [comment]
Just tried it and got this error:
`/site-packages/optuna/_experimental.py in wrapped_init(self, *args, **kwargs)
     88                 )
     89 
---> 90                 _original_init(self, *args, **kwargs)
     91 
     92             cls.__init__ = wrapped_init

TypeError: __init__() got an unexpected keyword argument 'warn_independent_sampling'
`

**Comment by zeydabadi** [comment]
`
`

**Comment by ngupta23** [comment]
@zeydabadi I see you closed this. Was the issue resolved? It did not look like adding this as kwargs solved the issue. 

- If this has been solved, can you share your solution here?
- If it has not been solved, can you share an example of how you would do this type of tuning manually without pycaret? That will help guide the next steps.
