### ISSUE TITLE
[ENH] plot_model should return matplotlib figure 

### ISSUE THREAD

**Issue by sorenwacker** [pycaret/pycaret#2447]
### Describe the feature you want to add to this project

I would like to modify the figure before saving it and also I would like to save it in different formats (png, pdf, svg). 
However, `plot_model(...)` seems to call `plt.show()` and there is no option to get the figure object. 

### Describe your proposed solution

`plot_model()` should return the figure object.

```
def plot_model(...):
    ....
    return fig
```

### Describe alternatives you've considered, if relevant

`get_config('figure')` could return the current figure.

**Comment by moezali1** [comment]
@ngupta23 How are we handling this in time series module? I think we are returning figure there? is it?

**Comment by ngupta23** [comment]
@sorenwacker , In the time series module, you can use the `return_fig` argument to return the `plotly` figure object to you. Then you can manipulate this object just as you would do in `plotly` to customize it.

Alternately, some basic manipulation such as figure height, width and template can be set directly through the `plot_kwargs` argument in the `plot_model` call.

**Comment by sorenwacker** [comment]
Hm, can I provide an axis argument `plot_model(..., ax=gca())`? That could solve some of  the issues? I still would prefer to get the image object. I am using the classification module right now.

**Comment by Emanhabbak** [comment]
@ngupta23 ,I sent the required arguments in the plot_kwargs dictionery.but they didn't apply to the figure
