### ISSUE TITLE
[DOC]: There are 2 places with documentation, which is the main one?

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#2450]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://pycaret.gitbook.io/docs/
https://pycaret.readthedocs.io/en/latest/index.html

### Documentation problem

There are 2 places with documentation, which is the main one?

- https://pycaret.gitbook.io/docs/
- https://pycaret.readthedocs.io/en/latest/index.html

### Suggested fix for documentation

There are 2 places with documentation, which is the main one?

- https://pycaret.gitbook.io/docs/
- https://pycaret.readthedocs.io/en/latest/index.html

there should be 1 single website for documentation, otherwise it can cause confusion.

**Comment by ngupta23** [comment]
The first link is the primary documentation page for all things PyCaret. The second link is actually the API reference (that gived details about individual functions) and is available through the first link itself (see below).

Hope that answers your question. Please close the issue if it does. Thanks!

![image](https://user-images.githubusercontent.com/33585645/164505581-68d878af-1d4f-4561-ac37-ba8c8d0ba1e1.png)
