### ISSUE TITLE
[ENH]: Add fugue support for 3.0.0rc

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#2452]
### Describe the feature you want to add to this project

Incorporate fugue/spark parallelization for `compare_models` in 3.0.0rc release

### Describe your proposed solution

- [ ] Fugue support for 2.3.10 will have to be reworked for 3.0.0 because of new OOP structure.
- [ ] Also add it to the `time_series` module which did not have this capability earlier.

**Comment by goodwanghan** [comment]
Hello @ngupta23 , thanks for letting us know. What will the timeline look like? I will be very busy in the next 2-3 weeks. Maybe I can start later in May, is that fine?

**Comment by moezali1** [comment]
@goodwanghan I think that is a reasonable timeline. I would say we are 2-3 weeks away from 3.0 rc.
