### ISSUE TITLE
[BUG]: Possible bug in bug report

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#2475]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the main branch of pycaret.

### Issue Description

This is an issue screen of the bug report. Should "main" branch be renamed to "develop" branch.

![image](https://user-images.githubusercontent.com/54699234/166109649-3d2040f7-e3d2-401c-a29e-5a35e1e6eb85.png)

### Reproducible Example

```python
.
```

### Expected Behavior

.

### Actual Results

```python-traceback
.
```

### Installed Versions

<details>
3.0.0
</details>

**Comment by ngupta23** [comment]
Solved now.
