### ISSUE TITLE
[BUG]: `interpret_model` bug

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#2476]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [x] I have confirmed this bug exists on the main branch of pycaret.

### Issue Description

![image](https://user-images.githubusercontent.com/54699234/166109764-7ed337f0-8b2b-46b1-a6a8-df84211adccb.png)

### Reproducible Example

```python
from pycaret.datasets import get_data
data = get_data('juice')
from pycaret.classification import setup
s = setup(data, target = 'Purchase', session_id = 123)
lightgbm = create_model('lightgbm')
interpret_model(lightgbm)
```

### Expected Behavior

It should display the plot.

### Actual Results

```python-traceback
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    332                 pass
    333             else:
--> 334                 return printer(obj)
    335             # Finally look for special method names
    336             method = get_real_method(obj, self.print_method)

4 frames
/usr/local/lib/python3.7/dist-packages/matplotlib/backends/backend_agg.py in print_png(self, filename_or_obj, metadata, pil_kwargs, *args, **kwargs)
    503             Metadata in the PNG file as key-value pairs of bytes or latin-1
    504             encodable strings.
--> 505             According to the PNG specification, keys must be shorter than 79
    506             chars.
    507 

ImportError: cannot import name '_png' from 'matplotlib' (/usr/local/lib/python3.7/dist-packages/matplotlib/__init__.py)
<Figure size 576x626.4 with 2 Axes>
```

### Installed Versions

3.0.0

**Comment by ngupta23** [comment]
@moezali1  is the code correct?

**Comment by moezali1** [comment]
@ngupta23 Nope. I just edited.

**Comment by ngupta23** [comment]
I think I also got this on Colab today. It happens because colab reinstalls a newer version of matplotlib (which works fine), but you have to restart your kernel for that to take effect. After restarting the kernel, this issue should go away. Can you double-check?
