### ISSUE TITLE
[BUG]: `predict_model` on develop branch not working

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#2478]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

`predict_model` function not working.

![image](https://user-images.githubusercontent.com/54699234/166110986-14c86ecf-c390-47a7-97a5-a21d2ca8701d.png)

### Reproducible Example

```python
dt = create_model('dt')
predict_model(dt)
```

### Expected Behavior

The function should predict the hold-out set and also displays the performance metric as 2.0 version.

### Actual Results

```python-traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-63-d7d5a74520ef> in <module>()
----> 1 predict_model(dt);

1 frames
/usr/local/lib/python3.7/dist-packages/pycaret/time_series/forecasting/oop.py in predict_model(self, estimator, fh, X, return_pred_int, alpha, round, verbose)
   3804         """
   3805 
-> 3806         estimator.check_is_fitted()
   3807 
   3808         pipeline_with_model, estimator_ = self._predict_model_reconcile_pipe_estimator(

AttributeError: 'DecisionTreeClassifier' object has no attribute 'check_is_fitted'
```

### Installed Versions

3.0.0

**Comment by ngupta23** [comment]
@moezali1 You are running time series here, but model dt is probably coming from regression/classification. Are you mixing up experiments?

**Comment by moezali1** [comment]
You are right. I can't reproduce this bug anymore. My bad.
