### ISSUE TITLE
[ENH]: Change default metric for time series

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#2487]
### Describe the feature you want to add to this project

Default metric `mape` does not work well when the actual values are 0

Why MAPE and sMAPE are not good metrics:
- [Link 1](https://en.wikipedia.org/wiki/Mean_absolute_percentage_error)
- [Link 2](https://towardsdatascience.com/choosing-the-correct-error-metric-mape-vs-smape-5328dec53fac)
- [Link 3](https://stats.stackexchange.com/questions/299712/what-are-the-shortcomings-of-the-mean-absolute-percentage-error-mape)

![image](https://user-images.githubusercontent.com/33585645/166158997-4e9bebbc-6bf5-4c44-bef4-c5fc890a23a9.png)

[This notebook](https://gist.github.com/ngupta23/723926a3b8a815503578ea1625a35049) shows some of the issues with MAPE and sMAPE:

![image](https://user-images.githubusercontent.com/33585645/166160256-6c0d17b2-cdcf-47a1-a938-fcc1b176cc18.png)

**Issues MAPE**

1. When y_true = 0, MAPE ~ 1e15!!

**Issues sMAPE**
1. After y_pred exceeds a certain value, sMAPE is capped at 2.0. This implies that we do not care about the precise value of y_pred once it crosses a certain value. This is not exactly true and can be misleading.
2. sMAPE value is not symmetric around the true value. If we over forecast by 0.1 and under forecast by 0.1, it produces different metric values. Ideally, both of them should be the same.

### Describe your proposed solution

Change default metric to MASE from MAPE 

**MASE Advantages**

1. As the predicted value moves away from the actual, the metric increases as expected. This has a more meaningful interpretation.
2. Unusually high values of metrics not produced (only produced when all y_train = same value which is quite rare.
3. The metric is symmetric. If we over forecast by 0.1 and under forecast by 0.1, it produces the same metric value.

**Comment by moezali1** [comment]
@ngupta23 How are MASE values interpreted? MAPE is % error. What about MASE?

**Comment by ngupta23** [comment]
MASE is the error relative to the naive forecast. So 1 would be same as naive forecast. < 1 would be better than naive forecast. > 1 would be worse than naive forecast.

**Comment by ngupta23** [comment]
In the 5/12 meeting (@moezali1 , @Yard1,  @tvdboom, @ngupta23 ), it was decided to change the default to MASE.
