### ISSUE TITLE
[BUG]: Shape is not correct in the setup display grid

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#2496]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

The shape printed in the setup grid for the Train dataset and Test dataset is not correct. It should be a shape after transformation (one-hot-encoding, feature selection, etc.) At the moment it shows the original shape of the columns.

```
from pycaret.datasets import get_data
data = get_data('income')

from pycaret.classification import *
s = setup(data, target = 'income >50K', session_id = 123)
```
![image](https://user-images.githubusercontent.com/54699234/166457922-3abd845a-4949-4288-98f0-9ba721cdc79b.png)

```
get_config('X_train').shape
```
![image](https://user-images.githubusercontent.com/54699234/166458116-3ebdc5a3-f032-4e0a-8cb9-3ed0ecfbde4f.png)

```
data.shape
```
![image](https://user-images.githubusercontent.com/54699234/166458177-df58032c-4117-4114-a53e-241614242aac.png)

### Reproducible Example

```python
from pycaret.datasets import get_data
data = get_data('income')
from pycaret.classification import *
s = setup(data, target = 'income >50K', session_id = 123)
```

### Expected Behavior

We should show the transformed shape of the train and test (after all preprocessing).

### Actual Results

```python-traceback
.
```

### Installed Versions

3.0.0

**Comment by tvdboom** [comment]
Isn't it a bit confusing to have the original dataset shape on Data shape and after the transformed shape on train and test? I feel like we should do all three after transformation or all three before.

**Comment by tvdboom** [comment]
We could also display both. A column with Original data shape, and Transformed data shape. And then Transformed Train shape and Transformed test shape
