### ISSUE TITLE
NaN records when Assign Model - NLP

### ISSUE THREAD

**Issue by ManuelBanza** [pycaret/pycaret#250]
Hi,
I did all the steps from the tutorials but when I do the code:

````
# Assign Model to dataset
lda_results = assign_model(tuned_unsupervised)
lda_results.head()
````

it returns a data set with NaN values but with values in the topic columns

<img width="997" alt="Captura de ecrã 2020-06-26, às 20 25 39" src="https://user-images.githubusercontent.com/53525022/85893706-46213380-b7eb-11ea-8baf-c277bc76f8de.png">

<img width="994" alt="Captura de ecrã 2020-06-26, às 20 27 40" src="https://user-images.githubusercontent.com/53525022/85893827-82549400-b7eb-11ea-9c69-7782fda086fd.png">

**Comment by pycaret** [comment]
@ManuelBanza Thanks for reporting. Can you please share the dataset so I can try to reproduce this issue?

**Comment by ManuelBanza** [comment]
Hi @pycaret 
here it is the link: https://we.tl/t-HM6IBZRalK 

Thanks for the help

**Comment by djcunniffe** [comment]
Hi @ManuelBanza I had a similar problem and it was caused by filtering my dataframe before assigning the model. df.reset_index() resolved it for me.

**Comment by RobVor** [comment]
Hi,

Same problem.

Resting the index, as suggested by djcunniffe, doesn't change the outcome.
