### ISSUE TITLE
[INSTALL]: Installation on MAC

### ISSUE THREAD

**Issue by Kon3000** [pycaret/pycaret#2502]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Mac M1

### Installation Method

pip install

### pycaret Version

latest

### Python Version

3.9.7

### Description

  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [139 lines of output]
      setup.py:460: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /private/var/folders/d_/70sn5cp12dxgdq7n2ktht_zh0000gn/T/pip-modern-metadata-jgoxi25d'), proceeding with generating Cython sources and expanding templates

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by ngupta23** [comment]
Check out the FAQ section. It has some pointers about installing on MAC

https://github.com/pycaret/pycaret/issues/1298

**Comment by ngupta23** [comment]
Also, try python version 3.8 to see if it works: https://github.com/numpy/numpy/issues/17784
