### ISSUE TITLE
[DOC]: Add reference to original caret

### ISSUE THREAD

**Issue by eitsupi** [pycaret/pycaret#2506]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

README and https://pycaret.gitbook.io/docs/#pycaret-for-citizen-data-scientists

### Documentation problem

As mentioned in #1228, there is no reference to the original caret.
The reference that was added temporarily was removed in #1908.

### Suggested fix for documentation

https://github.com/pycaret/pycaret/blob/3e8fb5603bd8cd3f3c39b32d631d6de80dd3d86c/README.md?plain=1#L19

**Comment by eitsupi** [comment]
I am wondering what the block label represents. If you feel this issue is unnecessary, feel free to close it.

**Comment by ngupta23** [comment]
@eitsupi We will update the readme in the main 3.0.0 release.

**Comment by ngupta23** [comment]
5th Nov 2022:

@moezali1 will fix this when he fixes the doc for 3.0.0 (final release)
