### ISSUE TITLE
[BUG]: Time series setup display grid in 3.0

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#2507]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

This is the output from the `setup` function in PyCaret (develop branch).

![image](https://user-images.githubusercontent.com/54699234/167134100-9a72bb39-ece0-4013-90df-fb9d2b342729.png)

I think we have removed `preprocess` parameter from the `setup` since it was irrelevant for time series. If that is True, we should also remove it from setup grid.

### Reproducible Example

```python
from pycaret.time_series import *
s = setup(data, fh = 12, session_id = 123)
```

### Expected Behavior

preprocess shouldn't show up in setup grid.

### Actual Results

```python-traceback
See above.
```

### Installed Versions

3.0.0

**Comment by ngupta23** [comment]
I don't think it is a bug, it was intentional to provide information about what is happening. For example, when some preprocessing is set, we get the details

![image](https://user-images.githubusercontent.com/33585645/167253460-c6147bb6-35d0-470f-95ec-4c8b32415210.png)

**Comment by moezali1** [comment]
@ngupta23 Let's discuss tomorrow morning and then we can close this.
