### ISSUE TITLE
Assign Sentiment to each text record - NLP

### ISSUE THREAD

**Issue by ManuelBanza** [pycaret/pycaret#251]
Hi,

In the NLP Model when we do the assign model a dataset is returned with topics and the dominant_topic. Is it possible to also bring the sentiment score and polarity?

Cheers!

**Comment by mghifari1910** [comment]
There's notebook by Hassan Amin on Kaggle explaining unsupervised sentiment analysis using Vader 
https://www.kaggle.com/hassanamin/unsupervised-sentiment-analysis-using-vader
https://pypi.org/project/vaderSentiment/

it can assess sentiment based on punctuation, capitalization, conjunctions and slang even on emoji and emoticon
is it possible to implement it on NLP modules?

**Comment by moezali1** [comment]
We are no more supporting the `nlp` and `arules` module in PyCaret due to lack to resources. Closing the issue now.
