### ISSUE TITLE
[ENH]: Set data_split_shuffle to False by default when fold_strategy is set to "timeseries"

### ISSUE THREAD

**Issue by ykskks** [pycaret/pycaret#2523]
### Describe the feature you want to add to this project

Currently, you can split data in time series manner by setting `fold_strategy ` to `timeseries` in `pycaret.regression.setup`.

However, `data_split_shuffle` is `True` by default, which can lead to timeseries split on randomly ordered data, if a user doesn't explicitly set `data_split_shuffle` to `False`.

```python
# probably not what users want
s = setup(data, target, fold_strategy='timeseries')

# correct
s = setup(data, target, fold_strategy='timeseries', data_split_shuffle=False)
```

I don't think there is a use case for timeseries split on randomly ordered data as users are expected to sort data by date before passing to the function.

There is a risk when users forget to set `data_split_shuffle` to `False`, as it can lead to unexpected data split and possibly harm model evaluation result.

Thus, I think it is safer to limit `data_split_shuffle` to be only`False` when `fold_strategy ` is `timeseries`.

### Describe your proposed solution

[In setup function's input validation](https://github.com/pycaret/pycaret/blob/724cb30600e491ccf1e79fdaa96efde5961a9919/pycaret/internal/tabular.py#L746), I want to add the following.

```python
if fold_strategy == "timeseries" and fold_shuffle is True:
    raise ValueError(
        "'timeseries' fold_strategy requires 'data_split_shuffle' to be 'False' as it can lead to unexpected data split."
    )
```

### Additional context

I did not notice this behavior myself and realized later that my model evaluation was too optimistic as the split was done randomly when I expected to be time series. 

I think this proposition is a change that contributes to more successful application of ML to real world problems by reducing the unexpected mistakes.

**Comment by ykskks** [comment]
@ngupta23 
Thank you!
Can I work on this and submit a PR?

**Comment by ngupta23** [comment]
Yes, sure but check with @Yard1 on where this needs to be added.

**Comment by ykskks** [comment]
@Yard1 
What do you think about this enhancement?

While this might appear as a restriction for users, I can't think of a situation where data should be shuffled in time-series split. Thus, this change will make it safer to use pycaret especially for non-specialists, preventing invalid model evaluation in time-series data by design.

**Comment by Yard1** [comment]
This sounds reasonable. If you are interested in implementing this yourself, please do the following:
* Use the `develop` branch (we'll be making that the master soon, but not yet)
* Add the logic in this method - https://github.com/pycaret/pycaret/blob/dc1c4543d05a4e84e480c0eea51bbb992419a619/pycaret/internal/preprocess/preprocessor.py#L232
* Make sure to validate both cases - user passing a string or an `TimeSeriesSplit` object directly

Let me know if you have any questions!
