### ISSUE TITLE
Request to add new features as topic keywords, inferring the topic and optimal topics in topic modelling

### ISSUE THREAD

**Issue by sathishkumar999** [pycaret/pycaret#253]
Hi Moez and team of pycaret!

since we are working on topic modelling project we stareted using pycaret nlp library.
but there are some features needs to add in nlp library. 

while assigning a model we have seen that it's showing the number of topics with percentages, dominant_topic and perc_dominant_topic.

![Screenshot (225)](https://user-images.githubusercontent.com/40235632/85952641-5ae6fe00-b988-11ea-9765-efe464ed5e16.png)

here I'm proposing some features, which are
remove the topics with percentages, because if we have 20 toipcs it writes percentage for all the topics, which makes more complex of the data set. I think there's no need of topic_0, topic_2.etc columns after assigning the model.please keep only three columns,which are pre_processed_text, dominant_topic and perc_dominant_topic.

next proposal is finding the optimal number of topics while setup the model for LDA. to finding the optimal topics we use coherence one.please add this feature.

![Screenshot (222)](https://user-images.githubusercontent.com/40235632/85952749-1e67d200-b989-11ea-8907-e61c5bb2d3d4.png)

![Screenshot (223)](https://user-images.githubusercontent.com/40235632/85952762-29bafd80-b989-11ea-91b9-f1f2ce8c9a89.png)

another proposal is inferring the topic from keywords.

![Screenshot (227)](https://user-images.githubusercontent.com/40235632/85953045-4b1ce900-b98b-11ea-87b3-76202261e717.png)

final proposal is please add a new column while assigning a model which is topic_keywords and number of documents along with dominant_topic and perc_dominant_topic.

![Screenshot (224)](https://user-images.githubusercontent.com/40235632/85952818-7272b680-b989-11ea-91d0-acd55ee2be72.png)

In pycaret while evaluating the model I have seen top 100 keywords for topics. add this as new parameter as num_topic_ keywords=10(default) while assigning a model as a new column instead of visualizing. And also bigram and trigram words as new columns.

![Screenshot (221)](https://user-images.githubusercontent.com/40235632/85952896-02b0fb80-b98a-11ea-8a95-a3a1b0758437.png)

![Screenshot (224)](https://user-images.githubusercontent.com/40235632/85952897-02b0fb80-b98a-11ea-94d2-e6db8f84e63e.png)

Hope you got my points.
why am I telling all these to pycaret team, because when I bring this pycaret library to my company project, team lead has pointed out all these disadvantages. so we started developing from scratch instead of using pycaret library. we have already done the project too. I want pycaret to be use in end to end project at least in next release.

I think this blog might help you for implementing my requests.
https://www.machinelearningplus.com/nlp/topic-modeling-gensim-python/#16buildingldamalletmodel

thanks.

**Comment by moezali1** [comment]
We are no more supporting the `nlp` and `arules` module in PyCaret due to lack to resources. Closing the issue now.
