### ISSUE TITLE
[BUG]: Plots not showing by default

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#2532]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

Plots do not show by default. Here is the detailed code to reproduce: https://gist.github.com/ngupta23/9a284cd47b1fbd5ea2868345452d304d

![image](https://user-images.githubusercontent.com/33585645/167915270-aa87bec6-1425-458a-bfb1-616b861ee5b8.png)

### Reproducible Example

```python
from pycaret.datasets import get_data
dataset = get_data('credit')

from pycaret.classification import ClassificationExperiment
exp = ClassificationExperiment()
exp.setup(data = dataset, target = 'default', session_id=123)

dt = exp.create_model('dt')

# Plot does not show by default.
exp.plot_model(dt)

# Now it shows
%matplotlib inline
exp.plot_model(dt)
```

### Expected Behavior

The plot should show by default without %matplotlib inline.

### Actual Results

```python-traceback
No error stack.
```

### Installed Versions

!pip install git+https://github.com/pycaret/pycaret.git@develop   

<details>
System:
    python: 3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0]
executable: /usr/bin/python3
   machine: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic

PyCaret required dependencies:
                 pip: 21.1.3
          setuptools: 57.4.0
             pycaret: 3.0.0
             ipython: Not installed
          ipywidgets: 7.7.0
               numpy: 1.21.6
              pandas: 1.3.5
              jinja2: 2.11.3
               scipy: 1.4.1
              joblib: 1.1.0
             sklearn: 1.0.2
                pyod: Installed but version unavailable
            imblearn: 0.8.1
   category_encoders: 2.4.1
            lightgbm: 3.3.2
               numba: 0.55.1
            requests: 2.27.1
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.5.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.11.3
               tbats: Installed but version unavailable
            pmdarima: 1.8.5

PyCaret optional dependencies:
                shap: Not installed
           interpret: Not installed
                umap: Not installed
    pandas_profiling: Installed but version unavailable
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
             xgboost: 0.90
            catboost: Not installed
              kmodes: Not installed
             mlxtend: 0.14.0
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: 0.2
              optuna: Not installed
               skopt: Not installed
              mlflow: Not installed
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: Not installed
           evidently: Not installed
                nltk: 3.2.5
            pyLDAvis: Not installed
              gensim: 3.6.0
               spacy: 2.2.4
           wordcloud: 1.5.0
            textblob: 0.15.3
              psutil: 5.4.8
               fugue: Not installed
           streamlit: Not installed
             prophet: Not installed
</details>

**Comment by moezali1** [comment]
@ngupta23 I can't even get the plot to show up on colab. I get this error with `plot_model`:

```
ImportError                               Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/IPython/core/formatters.py](https://localhost:8080/#) in __call__(self, obj)
    332                 pass
    333             else:
--> 334                 return printer(obj)
    335             # Finally look for special method names
    336             method = get_real_method(obj, self.print_method)

4 frames
[/usr/local/lib/python3.7/dist-packages/matplotlib/backends/backend_agg.py](https://localhost:8080/#) in print_png(self, filename_or_obj, metadata, pil_kwargs, *args, **kwargs)
    503             Metadata in the PNG file as key-value pairs of bytes or latin-1
    504             encodable strings.
--> 505             According to the PNG specification, keys must be shorter than 79
    506             chars.
    507 

ImportError: cannot import name '_png' from 'matplotlib' (/usr/local/lib/python3.7/dist-packages/matplotlib/__init__.py)
```

**Comment by ngupta23** [comment]
> @ngupta23 I can't even get the plot to show up on colab. I get this error with `plot_model`:

@moezali1 Make sure to restart your kernel after installing, else the correct version of matplotlib does not take effect.

**Comment by moezali1** [comment]
@ngupta23 @Yard1 I have tested this locally in a fresh environment and it works without running %matplotlib inline and also the size of plots are fine. 

So what we were looking at seems like a Google colab specific issue. Hence I am closing this issue.

No action needed.
