### ISSUE TITLE
[BUG]: ValueError: y contains previously unseen labels: nan

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#2535]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

If dataset have empty values, i receive ValueError: y contains previously unseen labels: nan

Note: Works in 2.3.10

Ps: i have also problems in  setup, try test 

- combine_rare_levels=True
- feature_interaction = True
- feature_ratio = True
- feature_selection_threshold=0.8
- trigonometry_features=True

### Reproducible Example

```python
s = setup(dados,
          target = 'vencedor_tr',
          train_size = 0.8,
          #combine_rare_levels=True,
          #feature_interaction = True,
          #feature_ratio = True,
          remove_outliers=True,
          ignore_features = ['tipo_de_jogo', 'ronda'],
          use_gpu=True,
          feature_selection=True,
          #feature_selection_threshold=0.8,
          silent=True,
          session_id = 123,
          #fold_strategy = 'timeseries',
          data_split_shuffle=False,
          fold=5,
          normalize=True,
          polynomial_features=True,
          polynomial_degree=2,
          #trigonometry_features=True
         )
```

### Expected Behavior

 no erros

i want use setup like this:

s = setup(dados,
          target = 'vencedor_tr',
          train_size = 0.8,
          combine_rare_levels=True,
          feature_interaction = True,
          feature_ratio = True,
          remove_outliers=True,
          ignore_features = ['tipo_de_jogo', 'ronda'],
          use_gpu=True,
          feature_selection=True,
          feature_selection_threshold=0.8,
          silent=True,
          session_id = 123,
          fold_strategy = 'timeseries',
          data_split_shuffle=False,
          fold=5,
          normalize=True,
          polynomial_features=True,
          polynomial_degree=2,
          trigonometry_features=True
         )

### Actual Results

```python-traceback
Please use `triu` from the `scipy.linalg` namespace, the `scipy.linalg.special_matrices` namespace is deprecated.
`np.typeDict` is a deprecated alias for `np.sctypeDict`.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~\miniconda3\lib\site-packages\sklearn\utils\_encode.py:182, in _encode(values, uniques, check_unknown)
    181 try:
--> 182     return _map_to_integer(values, uniques)
    183 except KeyError as e:

File ~\miniconda3\lib\site-packages\sklearn\utils\_encode.py:126, in _map_to_integer(values, uniques)
    125 table = _nandict({val: i for i, val in enumerate(uniques)})
--> 126 return np.array([table[v] for v in values])

File ~\miniconda3\lib\site-packages\sklearn\utils\_encode.py:126, in <listcomp>(.0)
    125 table = _nandict({val: i for i, val in enumerate(uniques)})
--> 126 return np.array([table[v] for v in values])

File ~\miniconda3\lib\site-packages\sklearn\utils\_encode.py:120, in _nandict.__missing__(self, key)
    119     return self.nan_value
--> 120 raise KeyError(key)

KeyError: nan

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Input In [19], in <cell line: 3>()
      1 #setup
----> 3 s = setup(dados,
      4           target = 'vencedor_tr',
      5           train_size = 0.8,
      6           #combine_rare_levels=True,
      7           #feature_interaction = True,
      8           #feature_ratio = True,
      9           remove_outliers=True,
     10           ignore_features = ['tipo_de_jogo', 'ronda'],
     11           use_gpu=True,
     12           feature_selection=True,
     13           #feature_selection_threshold=0.8,
     14           silent=True,
     15           session_id = 123,
     16           #fold_strategy = 'timeseries',
     17           data_split_shuffle=False,
     18           fold=5,
     19           normalize=True,
     20           polynomial_features=True,
     21           polynomial_degree=2,
     22           #trigonometry_features=True
     23          )

File ~\miniconda3\lib\site-packages\pycaret\classification\functional.py:534, in setup(data, target, train_size, test_data, ordinal_features, numeric_features, categorical_features, date_features, text_features, ignore_features, keep_features, preprocess, imputation_type, numeric_imputation, categorical_imputation, iterative_imputation_iters, numeric_iterative_imputer, categorical_iterative_imputer, text_features_method, max_encoding_ohe, encoding_method, polynomial_features, polynomial_degree, low_variance_threshold, remove_multicollinearity, multicollinearity_threshold, bin_numeric_features, remove_outliers, outliers_method, outliers_threshold, fix_imbalance, fix_imbalance_method, transformation, transformation_method, normalize, normalize_method, pca, pca_method, pca_components, feature_selection, feature_selection_method, feature_selection_estimator, n_features_to_select, custom_pipeline, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, silent, verbose, memory, profile, profile_kwargs)
    532 exp = _EXPERIMENT_CLASS()
    533 set_current_experiment(exp)
--> 534 return exp.setup(
    535     data=data,
    536     target=target,
    537     train_size=train_size,
    538     test_data=test_data,
    539     ordinal_features=ordinal_features,
    540     numeric_features=numeric_features,
    541     categorical_features=categorical_features,
    542     date_features=date_features,
    543     text_features=text_features,
    544     ignore_features=ignore_features,
    545     keep_features=keep_features,
    546     preprocess=preprocess,
    547     imputation_type=imputation_type,
    548     numeric_imputation=numeric_imputation,
    549     categorical_imputation=categorical_imputation,
    550     iterative_imputation_iters=iterative_imputation_iters,
    551     numeric_iterative_imputer=numeric_iterative_imputer,
    552     categorical_iterative_imputer=categorical_iterative_imputer,
    553     text_features_method=text_features_method,
    554     max_encoding_ohe=max_encoding_ohe,
    555     encoding_method=encoding_method,
    556     polynomial_features=polynomial_features,
    557     polynomial_degree=polynomial_degree,
    558     low_variance_threshold=low_variance_threshold,
    559     remove_multicollinearity=remove_multicollinearity,
    560     multicollinearity_threshold=multicollinearity_threshold,
    561     bin_numeric_features=bin_numeric_features,
    562     remove_outliers=remove_outliers,
    563     outliers_method=outliers_method,
    564     outliers_threshold=outliers_threshold,
    565     fix_imbalance=fix_imbalance,
    566     fix_imbalance_method=fix_imbalance_method,
    567     transformation=transformation,
    568     transformation_method=transformation_method,
    569     normalize=normalize,
    570     normalize_method=normalize_method,
    571     pca=pca,
    572     pca_method=pca_method,
    573     pca_components=pca_components,
    574     feature_selection=feature_selection,
    575     feature_selection_method=feature_selection_method,
    576     feature_selection_estimator=feature_selection_estimator,
    577     n_features_to_select=n_features_to_select,
    578     custom_pipeline=custom_pipeline,
    579     data_split_shuffle=data_split_shuffle,
    580     data_split_stratify=data_split_stratify,
    581     fold_strategy=fold_strategy,
    582     fold=fold,
    583     fold_shuffle=fold_shuffle,
    584     fold_groups=fold_groups,
    585     n_jobs=n_jobs,
    586     use_gpu=use_gpu,
    587     html=html,
    588     session_id=session_id,
    589     system_log=system_log,
    590     log_experiment=log_experiment,
    591     experiment_name=experiment_name,
    592     experiment_custom_tags=experiment_custom_tags,
    593     log_plots=log_plots,
    594     log_profile=log_profile,
    595     log_data=log_data,
    596     silent=silent,
    597     verbose=verbose,
    598     memory=memory,
    599     profile=profile,
    600     profile_kwargs=profile_kwargs,
    601 )

File ~\miniconda3\lib\site-packages\pycaret\classification\oop.py:351, in ClassificationExperiment.setup(self, data, target, train_size, test_data, ordinal_features, numeric_features, categorical_features, date_features, text_features, ignore_features, keep_features, preprocess, imputation_type, numeric_imputation, categorical_imputation, iterative_imputation_iters, numeric_iterative_imputer, categorical_iterative_imputer, text_features_method, max_encoding_ohe, encoding_method, polynomial_features, polynomial_degree, low_variance_threshold, remove_multicollinearity, multicollinearity_threshold, bin_numeric_features, remove_outliers, outliers_method, outliers_threshold, fix_imbalance, fix_imbalance_method, transformation, transformation_method, normalize, normalize_method, pca, pca_method, pca_components, feature_selection, feature_selection_method, feature_selection_estimator, n_features_to_select, custom_pipeline, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, silent, verbose, memory, profile, profile_kwargs)
    347     container.append(
    348         ["Target mapping", ", ".join([f"{k}: {v}" for k, v in mapping.items()])]
    349     )
    350 container.append(["Original data shape", self.dataset.shape])
--> 351 container.append(["Transformed data shape", self.dataset_transformed.shape])
    352 container.append(["Transformed train set shape", self.train_transformed.shape])
    353 container.append(["Transformed test set shape", self.test_transformed.shape])

File ~\miniconda3\lib\site-packages\pycaret\internal\pycaret_experiment\pycaret_experiment.py:472, in _PyCaretExperiment.dataset_transformed(self)
    470 if self._ml_usecase != MLUsecase.TIME_SERIES:
    471     if self.target_param:
--> 472         return pd.concat([*self.pipeline.transform(X=self.X, y=self.y)], axis=1)
    473     else:
    474         return self.pipeline.transform(self.X)

File ~\miniconda3\lib\site-packages\pycaret\internal\pipeline.py:191, in Pipeline.transform(self, X, y)
    187 def transform(self, X=None, y=None):
    188     for _, _, transformer in self._iter(
    189         with_final=hasattr(self._final_estimator, "transform")
    190     ):
--> 191         X, y = _transform_one(transformer, X, y)
    193     return variable_return(X, y)

File ~\miniconda3\lib\site-packages\pycaret\internal\pipeline.py:48, in _transform_one(transformer, X, y)
     46 if "y" in signature(transformer.transform).parameters:
     47     args.append(y)
---> 48 output = transformer.transform(*args)
     50 if isinstance(output, tuple):
     51     X, y = output[0], output[1]

File ~\miniconda3\lib\site-packages\pycaret\internal\preprocess\transformers.py:192, in TransfomerWrapper.transform(self, X, y)
    189     elif "X" not in transform_params:
    190         return X, y
--> 192 output = self.transformer.transform(*args)
    194 # Transform can return X, y or both
    195 if isinstance(output, tuple):

File ~\miniconda3\lib\site-packages\sklearn\preprocessing\_label.py:138, in LabelEncoder.transform(self, y)
    135 if _num_samples(y) == 0:
    136     return np.array([])
--> 138 return _encode(y, uniques=self.classes_)

File ~\miniconda3\lib\site-packages\sklearn\utils\_encode.py:184, in _encode(values, uniques, check_unknown)
    182         return _map_to_integer(values, uniques)
    183     except KeyError as e:
--> 184         raise ValueError(f"y contains previously unseen labels: {str(e)}")
    185 else:
    186     if check_unknown:

ValueError: y contains previously unseen labels: nan
```

### Installed Versions

<details>
System:
    python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\username\miniconda3\python.exe
   machine: Windows-10-10.0.22616-SP0

PyCaret required dependencies:
                 pip: 22.0.4
          setuptools: 61.2.0
             pycaret: 3.0.0
             ipython: Not installed
          ipywidgets: 7.6.5
               numpy: 1.21.6
              pandas: 1.4.2
              jinja2: 3.1.2
               scipy: 1.8.0
              joblib: 1.1.0
             sklearn: 1.0.2
                pyod: Installed but version unavailable
            imblearn: 0.9.0
   category_encoders: 2.4.1
            lightgbm: 3.3.2
               numba: 0.55.1
            requests: 2.27.1
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.8.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.11.3
               tbats: Installed but version unavailable
            pmdarima: 1.8.5

PyCaret optional dependencies:
                shap: 0.40.0
           interpret: 0.2.7
                umap: Installed but version unavailable
    pandas_profiling: 3.2.0
  explainerdashboard: Installed but version unavailable
             autoviz: 0.1.39
           fairlearn: 0.7.0
             xgboost: 2.0.0-dev
            catboost: 1.0.5
              kmodes: 0.12.1
             mlxtend: 0.19.0
        tune_sklearn: 0.4.3
                 ray: 1.12.0
            hyperopt: 0.2.7
              optuna: 2.10.0
               skopt: 0.9.0
              mlflow: 1.25.1
              gradio: 2.9.4
             fastapi: 0.77.1
             uvicorn: 0.17.6
              m2cgen: 0.10.0
           evidently: 0.1.49.dev0
                nltk: 3.7
            pyLDAvis: 3.3.1
              gensim: 4.2.0
               spacy: 3.3.0
           wordcloud: 1.8.1
            textblob: 0.17.1
              psutil: 5.9.0
               fugue: 0.6.6
           streamlit: Not installed
             prophet: 1.0
</details>

**Comment by ngupta23** [comment]
@celestinoxp Can you provide your dataset to us as this seems to be closely linked to your dataset?

**Comment by celestinoxp** [comment]
dataset:
[Espanha_LaLiga.csv](https://github.com/pycaret/pycaret/files/8673697/Espanha_LaLiga.csv)

**Comment by tvdboom** [comment]
Hi. The dataset you have shared is missing the target column `vencedor_tr`, which is where the problem arises. Missing values in the target column makes no sense since this is what you are trying to predict. Can you try running the same code but removing the rows with missing values in column `vencedor_tr`? You can use this code: `dados = dados.dropna(subset="vencedor_tr")`.

That said. I agree that this error message is not clear enough. I'll see if I can make it clearer. Thanks for pointing this out.

**Comment by celestinoxp** [comment]
> Oi. O conjunto de dados que você compartilhou não contém a coluna de destino `vencedor_tr`, que é onde surge o problema. Valores ausentes na coluna de destino não fazem sentido, pois é isso que você está tentando prever. Você pode tentar executar o mesmo código, mas removendo as linhas com valores ausentes na coluna `vencedor_tr`? Você pode usar este código: `dados = dados.dropna(subset="vencedor_tr")`.
> 
> Dito isto. Concordo que esta mensagem de erro não é suficientemente clara. Vou ver se consigo deixar mais claro. Obrigado por apontar isso.

But the notebook code creates a column "winner_tr ".
I'll share the code in the notebook for you to test yourself: 
[Previsão de jogos.zip](https://github.com/pycaret/pycaret/files/8676901/Previsao.de.jogos.zip)

**Comment by tvdboom** [comment]
I see. You indeed have `NaN` values in the target column. You need to remove those rows since you can't use them. Running `dados = dados.dropna(subset="vencedor_tr")` one cell before initializing pycaret solves the issue.

**Comment by celestinoxp** [comment]
> I see. You indeed have `NaN` values in the target column. You need to remove those rows since you can't use them. Running `dados = dados.dropna(subset="vencedor_tr")` one cell before initializing pycaret solves the issue.

I can't drop "vencedor_tr" lines! Then how i can predict winner team?

**Comment by tvdboom** [comment]
You can't make predictions if you don't know the result. Else, what would you predict for those lines?

**Comment by celestinoxp** [comment]
> Você não pode fazer previsões se não souber o resultado. Caso contrário, o que você prevê para essas linhas?

1º - have you see notebook i send???
2º - notenook i send in pycaret 2.3.10 works
3º - pycaret 3.0 (with all depencencies updated) not working...

**Comment by tvdboom** [comment]
I have seen your notebook and I have ran it using pycaret 3.0.

pycaret 2.3.10 does under the hood what I am telling you to do manually. Drop the rows (it's only 3 of them) and it will work on version 3.0 as well.

I know not the features are not empty. But that doesn't matter. If you don't know what the target value is the features are useless (you can't use them to train the model nor to evaluate it). Imputing the target column also makes no sense since this is what you are trying to do with the model in the first place.

**Comment by celestinoxp** [comment]
Then how can i predict the winner team if i not have number of goals? I need to have number of goals to predict the winner? do not make sense. Example how i can predict winner (vencedor_tr) of game "Betis vs Barcelona" in dataset (is last row).
dados = dados.dropna(subset="vencedor_tr") delete this row....

**Comment by celestinoxp** [comment]
I made a video, showing the installation of pycaret 2.3.10 and how the notebook works.
Then I installed pycaret 3.0 and put the SAME notebook to work and it shows the error.
But the video is big 273MB. How do I make it available for you to see?

**Comment by tvdboom** [comment]
I understand what you are saying. Still, my point holds. What pycaret 2.3.10 is doing is removing your rows under the hood. pycaret 3.0 doesn't do that, it returns an error instead, which is the error you are getting.

You are simply not allowed to have missing values in the target column. The error is not a bug, it's intended, since having missing values in the target column doesn't make sense from a machine learning perspective. Removing the rows is perfectly acceptable. I can't make it more clear than this.

> Then how can i predict the winner team if i not have number of goals? I need to have number of goals to predict the winner? do not make sense, because if i know number of goals i know who is the winner. Example how i can predict winner (vencedor_tr) of game "Betis vs Barcelona" in dataset (is last row)? dados = dados.dropna(subset="vencedor_tr") delete this row.... then how can predict?

If you want to predict the winner for the last three rows, you need to first initialize pycaret without them, and after use the `predict_model` function using those three rows as new unseen data. Then you will get the model predictions on those rows.

**Comment by Ruibin-Liu** [comment]
You can move the rows with `NaN` into an *external* test set by:
```python
dados_ext_test = dados[dados['vencedor_tr'].isnull()]
dados = dados.drop(dados_ext_test.index)
```
And now, run your `setup` function.
As @tvdboom said, you can use the `dados_ext_test`  only in `predict_model` but not in `create_model`, `compare_models`, and so on.

**Comment by DanieleBaranzini** [comment]
@celestinoxp , I think that @tvdboom is right on this: 
( ''_If you want to predict the winner for the last three rows, you need to first initialize pycaret without them, and after use the predict_model function using those three rows as new unseen data. Then you will get the model predictions on those rows._")

This is well known as a missing imputation procedure in statistics (training a model on the available complete cases, and then predict the missing values for those samples with missingness).  So remove missing cases (the entire sample rows with missing values ...3 cases in your example) from the training set, train the estimator on the compete dataset, and finally predict the missing values with `predict_model` 

Sometimes the prediction process is iterated two or more times where at each iteration the estimated value on the missing case is replaced by a new prediction and the process stops when the predicted values don not vary significantly.

**Comment by ngupta23** [comment]
Agreed with @tvdboom on this. But since the functionality is changing from the prior version (where this was being dropped silently), maybe it would make sense to raise an Exception for this with appropriate message. That might be better. Thanks!
