### ISSUE TITLE
interpret_model (reason) on an other dataset than the train/test

### ISSUE THREAD

**Issue by bourbe** [pycaret/pycaret#254]
Hi,

I contruct a model with pycaret and when I launch this:

classification.interpret_model(classification_xgb, plot = 'reason', observation = 0), it gives me the interpretation on observation 0 on the test dataset

> How is it possible to do the same with a dataset that I upload in .csv for example or a dataset different of train/test

regards

**Comment by pycaret** [comment]
@bourbe Not possible yet. Adding this to **enhancement** list.

**Comment by pycaret** [comment]
# Open for contribution now

**Comment by jbechtel** [comment]
@pycaret I'd be interested in contributing to this, however I'd like your view on its feasibility. From the SHAP side of things, it is easy. Looks like it's just 
```
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_new_sample)
```
Taking a brief look at the code, it seems like pycaret currently just grabs `X_train` or `X_test` from `global` scope, and uses that for `X_new_sample`. The problem then is tracking down what transformations `X_train` and `X_test` have already undergone. Is this as easy as applying the `prep_pipe` from `global` scope via `prep_pipe.transform(X_new_sample)`? It's unclear to me whether there are other transformations that may occur outside `prep_pipe` that are necessary to get `X_new_sample` and `X_train`/`X_test` to be compatible.

**Comment by Yard1** [comment]
@jbechtel That should be all that's necessary. I'll assign this issue to you, thanks.
