### ISSUE TITLE
Loading model get failed

### ISSUE THREAD

**Issue by ajaysh2193** [pycaret/pycaret#255]
Hi,

While loading saved pycaret classifier model (.pkl file) in flask app, I am facing an error i.e. **ValueError: EOF: reading array data, expected 262144 bytes got 239490**. I have tried to use joblib also, but getting the same issue. 
Model is able to predict in jupyter notebook but facing the issue while using in flask app. Attaching code snippet and error screenshot!

![error](https://user-images.githubusercontent.com/24571705/86040205-3e6ac480-ba61-11ea-9863-3ac2efca6d25.jpeg)
![code](https://user-images.githubusercontent.com/24571705/86040215-41fe4b80-ba61-11ea-906f-5cdcef0d41c3.jpeg)

**Comment by pycaret** [comment]
@ajaysh2193 Can you share more details about the environment the version of joblib.

**Comment by ajaysh2193** [comment]
pycaret==1.0.0, joblib==0.15.1

**Comment by ajsharma007** [comment]
Any suggestion?

**Comment by ajaysh2193** [comment]
Any suggestion?
