### ISSUE TITLE
Modular Instalation for Deployment

### ISSUE THREAD

**Issue by joaopcnogueira** [pycaret/pycaret#256]
Hi everyone! As always, first I would like to thank you all for making pycaret! I am already using it as my primary machine learning tool.

I would like to make a sugestion. If I put pycaret==1.0.0 in my requirements.txt file, all of the good stuff will come, but maybe in a deployment environment that is not necessary. Imagine that I am create a machine learning app for classification, wouldn't make sense to only have installed in my builded project only the classification module? 

Thank you very much!

**Comment by pycaret** [comment]
@joaopcnogueira Thanks. That's a great suggestion.

Would you like to work on this for future release?

**Comment by joaopcnogueira** [comment]
Hi! Thank you for the answer!

I have never builded a feature like this, but I would like to help!

**Comment by pycaret** [comment]
# Open for contribution now

**Comment by Yard1** [comment]
As far as I know pip doesn't support this, though I have a workaround in mind. Basically, we'd create another `pycaret` package, `pycaret[full]`, which by itself would be empty, but it would install `pycaret` + any optional dependencies. It's a bit hacky but should work fine.

I think it may be more straightforward with conda, but I don't have much experience with it.

**Comment by pycaret** [comment]
@Yard1 Do you think I should post on my LinkedIn to seek for help from somebody who can help us with modular installation?

**Comment by Yard1** [comment]
Let's get the refactor done first, then we can think about publishing changes @pycaret

**Comment by pycaret** [comment]
Modular installation similar to what `ray` has will be implemented before the `2.2` release.

**Comment by pycaret** [comment]
@joaopcnogueira This issue has been addressed in `pycaret=2.2`. 

The default installation of pycaret is a slim version. Many libraries are moved to optional requirements for which you will have to do `pip install pycaret[full]`.

Hope this helps :)

**Comment by joaopcnogueira** [comment]
Hello there! 

Thank you very much guys for having put a lot of work into this, much appreciated! 

Also wanna to say that I have already use the new version 2.2 and it is working like a charm, congratulations to you all guys. 

I firmly believe that PyCaret is a turning point of all python machine learning/data science ecossystem, in the same level as pandas and scikit-learn!

It helped a lot!
