### ISSUE TITLE
[BUG]: SVM Predict_model doesn't show Score.

### ISSUE THREAD

**Issue by itomoko77** [pycaret/pycaret#2562]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

I created SVM model using create_model('svm') and would like to check Score in predict_model, but no Score column was shown. 

I tried all algorithm models including best (best = compare_models() ), and found that only Label column was added in case of SVM and Ridge Classifier, Score column wasn't added. 

### Reproducible Example

```python
import pandas as pd
from pycaret.classification import *

train_df = pd.read_csv("./train.csv")
s = setup(train_df, target = 'FLAG', ignore_features =['GET_TS', 'EQPT_TYPE', 'TOOL_TYPE', 'WORK_TYPE', 'ENV'] )

svm = create_model('svm')

eval_df = pd.read_csv("./test.csv")

predict_model(svm, data=eval_df)
```

### Expected Behavior

predict_model shows Label and Score columns.

### Actual Results

```python-traceback
predict_model shows only Label columns.
```

### Installed Versions

<details>
'2.3.10'
</details>

**Comment by moezali1** [comment]
@itomoko77 This is because `predict_proba` for `SGDClassifier` is not available when loss is `hinge`. You can create SVM this way to get `Score` as well if you would like:

```
svm = create_model('svm', loss = 'log')
```

Hope this helps.

**Comment by itomoko77** [comment]
Thanks! It works.

**Comment by lcg29** [comment]
when I use：
> svm = create_model('svm', loss = 'log')
then:
TypeError: __init__() got an unexpected keyword argument 'loss'

maybe a version problem?
