### ISSUE TITLE
[DOC]:  indications on how to retrieve holdout dataset

### ISSUE THREAD

**Issue by rdataforge** [pycaret/pycaret#2563]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://github.com/pycaret/pycaret/blob/master/tutorials/Regression%20Tutorial%20Level%20Beginner%20-%20REG101.ipynb

### Documentation problem

> In order to demonstrate the predict_model() function on unseen data, a sample of 600 records has been withheld from the original dataset to be used for predictions. This should not be confused with a train/test split as this particular split is performed to simulate a real life scenario. Another way to think about this is that these 600 records are not available at the time when the machine learning experiment was performed.

below this paragraph there is other regarding same topic:

> Before finalizing the model, it is advisable to perform one final check by predicting the test/hold-out set and reviewing the evaluation metrics. If you look at the information grid in Section 6 above, you will see that 30% (1621 samples) of the data has been separated out as a test/hold-out sample. All of the evaluation metrics we have seen above are cross-validated results based on training set (70%) only. Now, using our final trained model stored in the tuned_lightgbm variable we will predict the hold-out sample and evaluate the metrics to see if they are materially different than the CV results.

Assuming this two paragraphs are true, how the holdout set is used? should be separated by hand previously? Seems that is used somehow and we should be warned
 
How should be the hold-out sample retrieved?

### Suggested fix for documentation

There is no clear guidance on how really is the holdout set used.

is there any way of retrieving the holdout set for further manual comprobations?

**Comment by moezali1** [comment]
@rdataforge hold-out set is used when you do not pass any new data in the `predict_model` function. It is also used in plots developed using the `plot_model` function.

To access the hold-out set you can use `get_config('X_test')`
