### ISSUE TITLE
Feature Selection Confusion

### ISSUE THREAD

**Issue by npapan69** [pycaret/pycaret#257]
Dear All,
I'm a bit confused about how feature selection is working. For example in the setup the feature selection is true and I see that it takes into consideration a subset of features (from 106 initially down to 55). But then in the evaluate_model I get an AUC which value is not changing after I activate the feature selection tab (RFE_CV) and I get only 4 features. I would expect different AUC. Can you explain how feature selection is working?

Many thanks

**Comment by pycaret** [comment]
@npapan69 Thanks for reporting. In order to answer this, can you please provide more details about this issue. Example, dataset, expected result and outcome, I might be able to help.

**Comment by npapan69** [comment]
Thanks for your response, let me come back with a more specific question. In order to get the performance of a model on a subset of features that have been selected by the RFECV, the feature_selection in the setting of Environment should be set to true? And if yes when I set that to true I get for example 45 features shown on the setup output while the RFECV selects less than 45. The measured performance if I click AUC tab in the evaluate_model refers to which model? The one with the 45 features initially selected or the RFECV features?

**Comment by pycaret** [comment]
@npapan69 I see your confusion.

RFECV in plot_model is for analysis only. It actually doesn't effect your dataset. 

Please close the issue if this answers your question.

**Comment by npapan69** [comment]
So I don't see the meaning of being there if it doesn't affect the model. Can anyone explain?
Thanks anyway
