### ISSUE TITLE
[BUG]: How do we show the pycaret.anomaly.plot_model(model, plot = 'tsne') in production code in a frontend of website?

### ISSUE THREAD

**Issue by revanks** [pycaret/pycaret#2579]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### ### `In Pycaret Anomaly module we are able to plot **tsne`** plots in jupyter notebook, but in case production code I also need to show same tsne plots in frontend of website. I think this feature available in Streamlit, but I am using FastAPI framework. Is there any way to get these plots please let me know.  Thanks

from pycaret.datasets import get_data
anomaly = get_data('anomaly')
from pycaret.anomaly import *
exp_name = setup(data = anomaly)
knn = create_model('knn')
plot_model(knn, plot = 'tsne')

### Reproducible Example

```python
from pycaret.datasets import get_data
anomaly = get_data('anomaly')
from pycaret.anomaly import *
exp_name = setup(data = anomaly)
knn = create_model('knn')
plot_model(knn, plot = 'tsne')
```

### Expected Behavior

from pycaret.datasets import get_data
anomaly = get_data('anomaly')
from pycaret.anomaly import *
exp_name = setup(data = anomaly)
knn = create_model('knn')
plot_model(knn, plot = 'tsne')

### Actual Results

```python-traceback
from pycaret.datasets import get_data
anomaly = get_data('anomaly')
from pycaret.anomaly import *
exp_name = setup(data = anomaly)
knn = create_model('knn')
plot_model(knn, plot = 'tsne')
```

### Installed Versions

<details>
python 3.8
</details>

**Comment by moezali1** [comment]
@revanks You can use the `save` parameter to save the image and then load it whereever you want. If you are using `streamlit` as front-end, easier way is to set `display_format='streamlit'`.
