### ISSUE TITLE
Stratification based on a selected variable in a regression problem

### ISSUE THREAD

**Issue by raheems** [pycaret/pycaret#258]
Is there any option to stratify based on a binary covariate? 

For instance, I am doing a regression but I want to create the train test split based on a binary variable (treatment indicator variable). Is it possible?

Thanks

**Comment by pycaret** [comment]
@raheems Not yet possible. Tagging this as an enhancement for future release.

**Comment by pycaret** [comment]
# Open for contribution now

**Comment by clgarciga** [comment]
@pycaret I'm working on incorporating sklearn.model_selection.GroupShuffleSplit and sklearn.model_selection.PredefinedSplit and I think this would be a straightforward extension. Feel free to assign this to me if you'd like.

**Comment by pycaret** [comment]
@clgarciga Assigning to you.

**Comment by clgarciga** [comment]
@pycaret Sure thing.

@Yard1 Let me know once you want me to get started on this.

**Comment by pycaret** [comment]
@Yard1 has completed this functionality in `2.2-refactor`.

Cheers.

**Comment by pycaret** [comment]
@raheems 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
