### ISSUE TITLE
[BUG]: ModuleNotFoundError: No module named 'statsmodels.tsa._stl'

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#2580]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

When try use any notebook with pycaret, pycaret gives me a error message:
ModuleNotFoundError: No module named 'statsmodels.tsa._stl'

### Reproducible Example

```python
from pycaret.classification import *
```

### Expected Behavior

no error messages

### Actual Results

```python-traceback
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 from pycaret.classification import *

File ~\miniconda3\lib\site-packages\pycaret\classification\__init__.py:1, in <module>
----> 1 from pycaret.classification.functional import (
      2     add_metric,
      3     automl,
      4     blend_models,
      5     calibrate_model,
      6     check_fairness,
      7     compare_models,
      8     convert_model,
      9     create_api,
     10     create_app,
     11     create_docker,
     12     create_model,
     13     dashboard,
     14     deep_check,
     15     deploy_model,
     16     eda,
     17     ensemble_model,
     18     evaluate_model,
     19     finalize_model,
     20     get_config,
     21     get_leaderboard,
     22     get_logs,
     23     get_metrics,
     24     interpret_model,
     25     load_config,
     26     load_model,
     27     models,
     28     optimize_threshold,
     29     plot_model,
     30     predict_model,
     31     pull,
     32     remove_metric,
     33     save_config,
     34     save_model,
     35     set_config,
     36     set_current_experiment,
     37     setup,
     38     stack_models,
     39     tune_model,
     40 )
     41 from pycaret.classification.oop import ClassificationExperiment
     43 __all__ = [
     44     "ClassificationExperiment",
     45     "setup",
   (...)
     82     "create_app",
     83 ]

File ~\miniconda3\lib\site-packages\pycaret\classification\functional.py:9, in <module>
      6 import pandas as pd
      7 from joblib.memory import Memory
----> 9 from pycaret.classification.oop import ClassificationExperiment
     10 from pycaret.internal.utils import (
     11     DATAFRAME_LIKE,
     12     TARGET_LIKE,
     13     check_if_global_is_not_none,
     14 )
     16 # from pycaret.parallel import ParallelBackend # unused

File ~\miniconda3\lib\site-packages\pycaret\classification\oop.py:15, in <module>
     12 from joblib.memory import Memory
     14 import pycaret.containers.metrics.classification
---> 15 import pycaret.containers.models.classification
     16 import pycaret.internal.patches.sklearn
     17 import pycaret.internal.patches.yellowbrick

File ~\miniconda3\lib\site-packages\pycaret\containers\models\classification.py:19, in <module>
     17 import pycaret.containers.base_container
     18 import pycaret.internal.cuml_wrappers
---> 19 from pycaret.containers.models.base_model import (
     20     ModelContainer,
     21     leftover_parameters_to_categorical_distributions,
     22 )
     23 from pycaret.internal.cuml_wrappers import get_svc_classifier
     24 from pycaret.internal.distributions import (
     25     Distribution,
     26     IntUniformDistribution,
     27     UniformDistribution,
     28 )

File ~\miniconda3\lib\site-packages\pycaret\containers\models\base_model.py:9, in <module>
      7 from pycaret.containers.base_container import BaseContainer
      8 from pycaret.internal.distributions import CategoricalDistribution
----> 9 from pycaret.internal.pycaret_experiment.pycaret_experiment import _PyCaretExperiment
     10 from pycaret.internal.utils import get_logger
     11 from pycaret.utils import get_allowed_engines

File ~\miniconda3\lib\site-packages\pycaret\internal\pycaret_experiment\pycaret_experiment.py:9, in <module>
      7 import pycaret.internal.patches.sklearn
      8 import pycaret.internal.patches.yellowbrick
----> 9 import pycaret.internal.persistence
     10 from pycaret import show_versions
     11 from pycaret.internal.logging import get_logger

File ~\miniconda3\lib\site-packages\pycaret\internal\persistence.py:12, in <module>
     10 from pycaret.internal.utils import get_logger
     11 from pycaret.utils._dependencies import _check_soft_dependencies
---> 12 from pycaret.utils.time_series.forecasting.pipeline import _add_model_to_pipeline
     15 def deploy_model(
     16     model, model_name: str, authentication: dict, platform: str = "aws", prep_pipe_=None
     17 ):
     18     """
     19     (In Preview)
     20 
   (...)
    100 
    101     """

File ~\miniconda3\lib\site-packages\pycaret\utils\time_series\forecasting\pipeline.py:8, in <module>
      6 from sktime.forecasting.compose import ForecastingPipeline, TransformedTargetForecaster
      7 from sktime.transformations.compose import TransformerPipeline
----> 8 from sktime.transformations.series.impute import Imputer
     11 def _add_model_to_pipeline(
     12     pipeline: ForecastingPipeline, model: BaseForecaster
     13 ) -> ForecastingPipeline:
     14     """Removes the dummy model from the preprocessing pipeline and adds the
     15     passed model to it instead.
     16 
   (...)
     30         The forecasting pipeline with the dummy model replaced with the correct one.
     31     """

File ~\miniconda3\lib\site-packages\sktime\transformations\series\impute.py:16, in <module>
     13 from sklearn.utils import check_random_state
     15 from sktime.forecasting.base import ForecastingHorizon
---> 16 from sktime.forecasting.trend import PolynomialTrendForecaster
     17 from sktime.transformations.base import BaseTransformer
     20 class Imputer(BaseTransformer):

File ~\miniconda3\lib\site-packages\sktime\forecasting\trend.py:15, in <module>
     13 from sklearn.pipeline import make_pipeline
     14 from sklearn.preprocessing import PolynomialFeatures
---> 15 from statsmodels.tsa.seasonal import STL as _STL
     17 from sktime.forecasting.base import BaseForecaster
     18 from sktime.forecasting.naive import NaiveForecaster

File ~\miniconda3\lib\site-packages\statsmodels\tsa\seasonal.py:9, in <module>
      6 from pandas.core.nanops import nanmean as pd_nanmean
      8 from statsmodels.tools.validation import PandasWrapper, array_like
----> 9 from statsmodels.tsa._stl import STL
     10 from statsmodels.tsa.filters.filtertools import convolution_filter
     11 from statsmodels.tsa.tsatools import freq_to_period

ModuleNotFoundError: No module named 'statsmodels.tsa._stl'
```

### Installed Versions

<details>
System:
    python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\username\miniconda3\python.exe
   machine: Windows-10-10.0.22621-SP0

PyCaret required dependencies:
                 pip: 22.1
          setuptools: 59.8.0
             pycaret: 3.0.0
             ipython: Not installed
          ipywidgets: 7.7.0
               numpy: 1.21.6
              pandas: 1.4.2
              jinja2: 3.1.2
               scipy: 1.8.1
              joblib: 1.1.0
             sklearn: 1.1.1
                pyod: Installed but version unavailable
            imblearn: 0.9.1
   category_encoders: Not installed
            lightgbm: 3.3.2
               numba: 0.55.1
            requests: 2.27.1
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.8.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.11.4
               tbats: Not installed
            pmdarima: Not installed

PyCaret optional dependencies:
"is" with a literal. Did you mean "=="?
"is" with a literal. Did you mean "=="?
"is" with a literal. Did you mean "=="?
"is" with a literal. Did you mean "=="?
"is not" with a literal. Did you mean "!="?
"is" with a literal. Did you mean "=="?
"is" with a literal. Did you mean "=="?
"is not" with a literal. Did you mean "!="?

The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`

The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
Alert! from version 0.1.39, fter importing, you must do '%matplotlib inline' to display charts in Jupyter Notebooks.
    AV = AutoViz_Class()
    dfte = AV.AutoViz(filename, sep=',', depVar='', dfte=None, header=0, verbose=0, lowess=False,
               chart_format='svg',max_rows_analyzed=150000,max_cols_analyzed=30, save_plot_dir=None)
Note: verbose=0 or 1 generates charts and displays them in your local Jupyter notebook.
      verbose=2 does not display plots but saves them in AutoViz_Plots folder in local machine.
Updated: chart_format='bokeh' generates and displays charts in your local Jupyter notebook.
      chart_format='server' generates and displays charts in the browser - one tab for each chart.
      chart_format='html' silently saves charts HTML format - they are also interactive!
Please use `triu` from the `scipy.linalg` namespace, the `scipy.linalg.special_matrices` namespace is deprecated.
invalid escape sequence \.
invalid escape sequence \.
                shap: 0.40.0
           interpret: 0.2.7
                umap: 0.5.3
    pandas_profiling: 3.2.0
  explainerdashboard: Installed but version unavailable
             autoviz: 0.1.39
           fairlearn: 0.7.0
             xgboost: 1.6.1
            catboost: 1.0.6
              kmodes: 0.12.1
             mlxtend: 0.19.0
       statsforecast: 0.5.5
        tune_sklearn: 0.4.3
                 ray: 1.12.1
            hyperopt: 0.2.7
              optuna: 2.10.0
               skopt: 0.9.0
              mlflow: 1.26.0
              gradio: 3.0.5
             fastapi: 0.78.0
             uvicorn: 0.17.6
              m2cgen: 0.10.0
           evidently: 0.1.50.dev0
                nltk: 3.7
            pyLDAvis: 3.3.1
              gensim: 4.2.0
               spacy: 3.3.0
           wordcloud: 1.8.1
            textblob: 0.17.1
              psutil: 5.9.1
               fugue: 0.6.6
           streamlit: Not installed
             prophet: Not installed
</details>

**Comment by celestinoxp** [comment]
problem solved.
solution: uninstall and re-install statsmodels.
--------------------------------------------------
It is curious that when we downgrade from python3.9 to python3.8 the packages remain in the python3.9 version.
Here is my experience: when you downgrade python, you must reinstall all packages.
The ideal is after reinstalling python, deleting all packages and installing the necessary ones.

**Comment by ngupta23** [comment]
Yes, it would not be advisable to change python versions in an environment. If you want to do that, it is best to create a new environment with the required python version. The reason is that the package version availability is dependent on the python versions.
