### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by shapatel13** [pycaret/pycaret#2582]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

![image](https://user-images.githubusercontent.com/50153301/170101233-0429716c-a059-4d5d-87d5-bc7130ffef74.png)

### Reproducible Example

```python
pip install pycaret[full]
from pycaret.classification import *
```

### Expected Behavior

should complete

### Actual Results

```python-traceback
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-a8cb12878b37> in <module>()
----> 1 from pycaret.classification import *

5 frames
/usr/local/lib/python3.7/dist-packages/pandas/compat/_optional.py in import_optional_dependency(name, extra, errors, min_version)
    116     except ImportError:
    117         if errors == "raise":
--> 118             raise ImportError(msg) from None
    119         else:
    120             return None

ImportError: Missing optional dependency 'Jinja2'. DataFrame.style requires jinja2. Use pip or conda to install Jinja2.

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
```

### Installed Versions

<details>
Replace this line with the output of the version code above.
</details>
full version

**Comment by ngupta23** [comment]
The solution is recommended here: https://github.com/pycaret/pycaret/issues/2490. Closing for now. Feel free to reopen if you have followups
