### ISSUE TITLE
[BUG]: TypeError: setup() got an unexpected keyword argument 'feature_interaction'

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#2586]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

when use feature_interaction=True in setup show error.
feature_interaction=False, show error too.

### Reproducible Example

```python
import pycaret
import pandas as pd 

#titanic train_data (original dataset)
train_data = pd.read_csv("train.csv")

from pycaret.classification import *
s = setup(data=train_data, target='Survived', feature_interaction=True)
```

### Expected Behavior

no errors

### Actual Results

```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [9], in <cell line: 2>()
      1 from pycaret.classification import *
----> 2 s = setup(data=train_data, target='Survived', feature_interaction=False)

TypeError: setup() got an unexpected keyword argument 'feature_interaction'
```

### Installed Versions

<details>
System:
    python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\celes\miniconda3\python.exe
   machine: Windows-10-10.0.22621-SP0

PyCaret required dependencies:
                 pip: 22.1.1
          setuptools: 59.8.0
             pycaret: 3.0.0
             ipython: Not installed
          ipywidgets: 7.7.0
               numpy: 1.21.6
              pandas: 1.4.2
              jinja2: 3.1.2
               scipy: 1.7.3
              joblib: 1.1.0
             sklearn: 1.1.1
                pyod: Installed but version unavailable
            imblearn: 0.9.1
   category_encoders: 2.4.1
            lightgbm: 3.3.2
               numba: 0.55.1
            requests: 2.27.1
          matplotlib: 3.5.1
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.8.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.11.4
               tbats: Installed but version unavailable
            pmdarima: 1.8.5

PyCaret optional dependencies:
Alert! from version 0.1.39, fter importing, you must do '%matplotlib inline' to display charts in Jupyter Notebooks.
    AV = AutoViz_Class()
    dfte = AV.AutoViz(filename, sep=',', depVar='', dfte=None, header=0, verbose=0, lowess=False,
               chart_format='svg',max_rows_analyzed=150000,max_cols_analyzed=30, save_plot_dir=None)
Note: verbose=0 or 1 generates charts and displays them in your local Jupyter notebook.
      verbose=2 does not display plots but saves them in AutoViz_Plots folder in local machine.
Updated: chart_format='bokeh' generates and displays charts in your local Jupyter notebook.
      chart_format='server' generates and displays charts in the browser - one tab for each chart.
      chart_format='html' silently saves charts HTML format - they are also interactive!
`scipy.sparse.sparsetools` is deprecated!
scipy.sparse.sparsetools is a private module for scipy.sparse, and should not be used.
                shap: 0.40.0
           interpret: 0.2.7
                umap: 0.5.3
    pandas_profiling: 3.2.0
  explainerdashboard: Installed but version unavailable
             autoviz: 0.1.39
           fairlearn: 0.7.0
             xgboost: 1.6.1
            catboost: 1.0.6
              kmodes: 0.12.1
             mlxtend: 0.19.0
       statsforecast: 0.5.5
        tune_sklearn: Not installed
                 ray: Installed but version unavailable
            hyperopt: 0.2.7
              optuna: 2.10.0
               skopt: 0.9.0
              mlflow: 1.26.0
              gradio: 3.0.5
             fastapi: 0.78.0
             uvicorn: 0.17.6
              m2cgen: 0.10.0
           evidently: 0.1.50.dev0
                nltk: 3.7
            pyLDAvis: 3.3.1
              gensim: 4.2.0
               spacy: 3.3.0
           wordcloud: 1.8.1
            textblob: 0.17.1
              psutil: 5.9.1
               fugue: 0.6.6
           streamlit: 1.9.0
             prophet: 1.0
</details>

**Comment by tvdboom** [comment]
Just as #2585, the problem here is the documentation. The `feature_interaction` and `trigonometry_features` are deprecated in version 3.0. The documentation needs to be updated accordingly. For now, it's best if you look at the docstrings in github's code.
