### ISSUE TITLE
[BUG]: Feature to balance the dataset is not working

### ISSUE THREAD

**Issue by gcovfur** [pycaret/pycaret#2588]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

Hi guys, I have a question about imbalanced databases. I'm trying to setup balancing tools like:
rus = RandomUnderSampler(random_state=1)

s = setup(
    dataframe,
    'TARGET',
    fold=4,
    fix_imbalance= True,
    fix_imbalance_method= rus,
    feature_selection= True,
    use_gpu=True
)
Is there something that I'm doing wrong? When I use the setup like this, I'm having problems with overfitting.

I sent this question on slack and I was directed to open a issue here.

Thanks a lot in advance!!!

### Reproducible Example

```python
import pandas as pd
from imblearn.under_sampling import RandomUnderSampler
from pycaret.classification import *

rus = RandomUnderSampler(random_state=1)

s = setup(
    dataframe,
    'TARGET',
    fold=4,
    fix_imbalance= True,
    fix_imbalance_method= rus,
    feature_selection= True,
    use_gpu=True
)
```

### Expected Behavior

After the code execution is expected that the dataset have the same number of rows for the 2 classes and that it was made by undersampling method.

### Actual Results

```python-traceback
In actual results, the same dataset used as data entering is returning in the end of pycaret setup proccess.
```

### Installed Versions

<details>
2.3.10
</details>

**Comment by tvdboom** [comment]
Thanks for noticing. This is indeed a bug and being tracked in #2587
