### ISSUE TITLE
Getting an error while running the topic modeling

### ISSUE THREAD

**Issue by sathishkumar369** [pycaret/pycaret#259]
Hi pycaret team,
when I was using setup for topic modeling it's giving me an error

PFA

![Screenshot (233)](https://user-images.githubusercontent.com/40235632/86212473-c2be6400-bb95-11ea-917d-41352e33b4c3.png)
![Screenshot (234)](https://user-images.githubusercontent.com/40235632/86212485-c94cdb80-bb95-11ea-9c70-46518dde8748.png)

when I have run this from scratch also I got the same error.
but I was able to fix it in scratch,just by increasing the max_length of the text.
but I don't know how to fix it in pycaret.

I used this code to fix it on scratch.

nlp = spacy.load("en_core_web_sm", disable=['parser', 'ner'])
nlp.max_length = 3000000

**Comment by pycaret** [comment]
Thanks for reporting @sathishkumar369. Will take this correction in next release.

**Comment by pycaret** [comment]
@sathishkumar369 

Can you please try this using **pycaret-nightly**. Please close the issue if this has been fixed.

**Comment by sathishkumar369** [comment]
Thanks Moez and Team for fixing this error. I'm very happy to close the issue.
Thanks once again for your hardwork.
