### ISSUE TITLE
[INSTALL]: ERROR: Could not build wheels for scikit-learn, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by CJosh88** [pycaret/pycaret#2590]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Windows-10-10.0.19042-SP0

### Installation Method

pip install

### pycaret Version

pycaret-2.3.10

### Python Version

3.10.4

### Description

Unable to install pycaret due to an error (see installation logs below). I tried opening anaconda prompt with admin rights but the issue persists. 

### Installation Logs

<details>

(base) PS C:\WINDOWS\system32> pip install pycaret
Collecting pycaret
  Using cached pycaret-2.3.10-py3-none-any.whl (320 kB)
Collecting scikit-learn==0.23.2
  Using cached scikit-learn-0.23.2.tar.gz (7.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: yellowbrick>=1.0.1 in c:\users\ch0981\anaconda3\lib\site-packages (from pycaret) (1.4)
Requirement already satisfied: seaborn in c:\users\ch0981\anaconda3\lib\site-packages (from pycaret) (0.11.2)
Collecting spacy<2.4.0
  Using cached spacy-2.3.7-cp39-cp39-win_amd64.whl (9.4 MB)
Requirement already satisfied: IPython in c:\users\ch0981\anaconda3\lib\site-packages (from pycaret) (7.29.0)
Collecting wordcloud
  Using cached wordcloud-1.8.1-cp39-cp39-win_amd64.whl
Collecting mlflow
  Using cached mlflow-1.26.0-py3-none-any.whl (17.8 MB)
Collecting imbalanced-learn==0.7.0
  Using cached imbalanced_learn-0.7.0-py3-none-any.whl (167 kB)
Requirement already satisfied: ipywidgets in c:\users\ch0981\anaconda3\lib\site-packages (from pycaret) (7.6.5)
Collecting scikit-plot
  Using cached scikit_plot-0.3.7-py3-none-any.whl (33 kB)
Collecting lightgbm>=2.3.1
  Using cached lightgbm-3.3.2-py3-none-win_amd64.whl (1.0 MB)
Collecting pandas-profiling>=2.8.0
  Using cached pandas_profiling-3.2.0-py2.py3-none-any.whl (262 kB)
Collecting umap-learn
  Using cached umap_learn-0.5.3-py3-none-any.whl
Collecting pyod
  Using cached pyod-1.0.1-py3-none-any.whl
Collecting scipy<=1.5.4
  Using cached scipy-1.5.4-cp39-cp39-win_amd64.whl (31.4 MB)
Requirement already satisfied: joblib in c:\users\ch0981\anaconda3\lib\site-packages (from pycaret) (1.1.0)
Collecting pyyaml<6.0.0
  Using cached PyYAML-5.4.1-cp39-cp39-win_amd64.whl (213 kB)
Collecting Boruta
  Using cached Boruta-0.3-py3-none-any.whl (56 kB)
Collecting cufflinks>=0.17.0
  Using cached cufflinks-0.17.3-py3-none-any.whl
Requirement already satisfied: plotly>=4.4.1 in c:\users\ch0981\anaconda3\lib\site-packages (from pycaret) (5.7.0)
Collecting textblob
  Using cached textblob-0.17.1-py2.py3-none-any.whl (636 kB)
Requirement already satisfied: pandas in c:\users\ch0981\anaconda3\lib\site-packages (from pycaret) (1.3.4)
Requirement already satisfied: matplotlib in c:\users\ch0981\anaconda3\lib\site-packages (from pycaret) (3.4.3)
Requirement already satisfied: nltk in c:\users\ch0981\anaconda3\lib\site-packages (from pycaret) (3.6.5)
Collecting gensim<4.0.0
  Using cached gensim-3.8.3-cp39-cp39-win_amd64.whl
Requirement already satisfied: numba<0.55 in c:\users\ch0981\anaconda3\lib\site-packages (from pycaret) (0.54.1)
Collecting mlxtend>=0.17.0
  Using cached mlxtend-0.19.0-py2.py3-none-any.whl (1.3 MB)
Collecting pyLDAvis
  Using cached pyLDAvis-3.3.1-py2.py3-none-any.whl
Collecting kmodes>=0.10.1
  Using cached kmodes-0.12.1-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: numpy>=1.13.3 in c:\users\ch0981\anaconda3\lib\site-packages (from imbalanced-learn==0.7.0->pycaret) (1.20.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\ch0981\anaconda3\lib\site-packages (from scikit-learn==0.23.2->pycaret) (2.2.0)
Requirement already satisfied: six>=1.9.0 in c:\users\ch0981\anaconda3\lib\site-packages (from cufflinks>=0.17.0->pycaret) (1.16.0)
Requirement already satisfied: setuptools>=34.4.1 in c:\users\ch0981\anaconda3\lib\site-packages (from cufflinks>=0.17.0->pycaret) (58.0.4)
Requirement already satisfied: colorlover>=0.2.1 in c:\users\ch0981\anaconda3\lib\site-packages (from cufflinks>=0.17.0->pycaret) (0.3.0)
Requirement already satisfied: smart-open>=1.8.1 in c:\users\ch0981\anaconda3\lib\site-packages (from gensim<4.0.0->pycaret) (5.2.1)
Requirement already satisfied: matplotlib-inline in c:\users\ch0981\anaconda3\lib\site-packages (from IPython->pycaret) (0.1.2)
Requirement already satisfied: jedi>=0.16 in c:\users\ch0981\anaconda3\lib\site-packages (from IPython->pycaret) (0.18.0)
Requirement already satisfied: decorator in c:\users\ch0981\anaconda3\lib\site-packages (from IPython->pycaret) (5.1.0)
Requirement already satisfied: backcall in c:\users\ch0981\anaconda3\lib\site-packages (from IPython->pycaret) (0.2.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\ch0981\anaconda3\lib\site-packages (from IPython->pycaret) (3.0.20)
Requirement already satisfied: colorama in c:\users\ch0981\anaconda3\lib\site-packages (from IPython->pycaret) (0.4.4)
Requirement already satisfied: pickleshare in c:\users\ch0981\anaconda3\lib\site-packages (from IPython->pycaret) (0.7.5)
Requirement already satisfied: pygments in c:\users\ch0981\anaconda3\lib\site-packages (from IPython->pycaret) (2.10.0)
Requirement already satisfied: traitlets>=4.2 in c:\users\ch0981\anaconda3\lib\site-packages (from IPython->pycaret) (5.1.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\users\ch0981\anaconda3\lib\site-packages (from ipywidgets->pycaret) (3.5.1)
Requirement already satisfied: ipykernel>=4.5.1 in c:\users\ch0981\anaconda3\lib\site-packages (from ipywidgets->pycaret) (6.4.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in c:\users\ch0981\anaconda3\lib\site-packages (from ipywidgets->pycaret) (0.2.0)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\ch0981\anaconda3\lib\site-packages (from ipywidgets->pycaret) (5.1.3)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in c:\users\ch0981\anaconda3\lib\site-packages (from ipywidgets->pycaret) (1.0.0)
Requirement already satisfied: wheel in c:\users\ch0981\anaconda3\lib\site-packages (from lightgbm>=2.3.1->pycaret) (0.37.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\ch0981\anaconda3\lib\site-packages (from matplotlib->pycaret) (1.3.1)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\ch0981\anaconda3\lib\site-packages (from matplotlib->pycaret) (3.0.4)
Requirement already satisfied: pillow>=6.2.0 in c:\users\ch0981\anaconda3\lib\site-packages (from matplotlib->pycaret) (8.4.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\ch0981\anaconda3\lib\site-packages (from matplotlib->pycaret) (2.8.2)
Requirement already satisfied: cycler>=0.10 in c:\users\ch0981\anaconda3\lib\site-packages (from matplotlib->pycaret) (0.10.0)
Requirement already satisfied: llvmlite<0.38,>=0.37.0rc1 in c:\users\ch0981\anaconda3\lib\site-packages (from numba<0.55->pycaret) (0.37.0)
Requirement already satisfied: pytz>=2017.3 in c:\users\ch0981\anaconda3\lib\site-packages (from pandas->pycaret) (2021.3)
Requirement already satisfied: pydantic>=1.8.1 in c:\users\ch0981\anaconda3\lib\site-packages (from pandas-profiling>=2.8.0->pycaret) (1.8.2)
Requirement already satisfied: multimethod>=1.4 in c:\users\ch0981\anaconda3\lib\site-packages (from pandas-profiling>=2.8.0->pycaret) (1.8)
Requirement already satisfied: jinja2>=2.11.1 in c:\users\ch0981\anaconda3\lib\site-packages (from pandas-profiling>=2.8.0->pycaret) (2.11.3)
Requirement already satisfied: visions[type_image_path]==0.7.4 in c:\users\ch0981\anaconda3\lib\site-packages (from pandas-profiling>=2.8.0->pycaret) (0.7.4)
Requirement already satisfied: phik>=0.11.1 in c:\users\ch0981\anaconda3\lib\site-packages (from pandas-profiling>=2.8.0->pycaret) (0.12.2)
Requirement already satisfied: requests>=2.24.0 in c:\users\ch0981\anaconda3\lib\site-packages (from pandas-profiling>=2.8.0->pycaret) (2.26.0)
Requirement already satisfied: missingno>=0.4.2 in c:\users\ch0981\anaconda3\lib\site-packages (from pandas-profiling>=2.8.0->pycaret) (0.5.1)
Requirement already satisfied: tangled-up-in-unicode==0.2.0 in c:\users\ch0981\anaconda3\lib\site-packages (from pandas-profiling>=2.8.0->pycaret) (0.2.0)
Requirement already satisfied: markupsafe~=2.1.1 in c:\users\ch0981\anaconda3\lib\site-packages (from pandas-profiling>=2.8.0->pycaret) (2.1.1)
Requirement already satisfied: tqdm>=4.48.2 in c:\users\ch0981\anaconda3\lib\site-packages (from pandas-profiling>=2.8.0->pycaret) (4.62.3)
Requirement already satisfied: htmlmin>=0.1.12 in c:\users\ch0981\anaconda3\lib\site-packages (from pandas-profiling>=2.8.0->pycaret) (0.1.12)
Requirement already satisfied: attrs>=19.3.0 in c:\users\ch0981\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pycaret) (21.2.0)
Requirement already satisfied: networkx>=2.4 in c:\users\ch0981\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pycaret) (2.6.3)
Requirement already satisfied: imagehash in c:\users\ch0981\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pycaret) (4.2.1)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\ch0981\anaconda3\lib\site-packages (from plotly>=4.4.1->pycaret) (8.0.1)
Collecting plac<1.2.0,>=0.9.6
  Using cached plac-1.1.3-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\ch0981\anaconda3\lib\site-packages (from spacy<2.4.0->pycaret) (2.0.6)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\ch0981\anaconda3\lib\site-packages (from spacy<2.4.0->pycaret) (3.0.6)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in c:\users\ch0981\anaconda3\lib\site-packages (from spacy<2.4.0->pycaret) (0.7.7)
Collecting srsly<1.1.0,>=1.0.2
  Using cached srsly-1.0.5-cp39-cp39-win_amd64.whl (177 kB)
Requirement already satisfied: wasabi<1.1.0,>=0.4.0 in c:\users\ch0981\anaconda3\lib\site-packages (from spacy<2.4.0->pycaret) (0.9.1)
Collecting catalogue<1.1.0,>=0.0.7
  Using cached catalogue-1.0.0-py2.py3-none-any.whl (7.7 kB)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\ch0981\anaconda3\lib\site-packages (from spacy<2.4.0->pycaret) (1.0.7)
Collecting thinc<7.5.0,>=7.4.1
  Using cached thinc-7.4.5-cp39-cp39-win_amd64.whl (904 kB)
Collecting yellowbrick>=1.0.1
  Using cached yellowbrick-1.3.post1-py3-none-any.whl (271 kB)
Collecting numpy>=1.13.3
  Using cached numpy-1.19.5-cp39-cp39-win_amd64.whl (13.3 MB)
Requirement already satisfied: Flask in c:\users\ch0981\anaconda3\lib\site-packages (from mlflow->pycaret) (1.1.2)
Requirement already satisfied: docker>=4.0.0 in c:\users\ch0981\anaconda3\lib\site-packages (from mlflow->pycaret) (5.0.3)
Requirement already satisfied: importlib-metadata!=4.7.0,>=3.7.0 in c:\users\ch0981\anaconda3\lib\site-packages (from mlflow->pycaret) (4.8.1)
Requirement already satisfied: click>=7.0 in c:\users\ch0981\anaconda3\lib\site-packages (from mlflow->pycaret) (8.0.3)
Requirement already satisfied: alembic in c:\users\ch0981\anaconda3\lib\site-packages (from mlflow->pycaret) (1.7.7)
Requirement already satisfied: querystring-parser in c:\users\ch0981\anaconda3\lib\site-packages (from mlflow->pycaret) (1.2.4)
Requirement already satisfied: sqlparse>=0.3.1 in c:\users\ch0981\anaconda3\lib\site-packages (from mlflow->pycaret) (0.4.2)
Requirement already satisfied: prometheus-flask-exporter in c:\users\ch0981\anaconda3\lib\site-packages (from mlflow->pycaret) (0.20.1)
Requirement already satisfied: protobuf>=3.7.0 in c:\users\ch0981\anaconda3\lib\site-packages (from mlflow->pycaret) (3.20.1)
Requirement already satisfied: waitress in c:\users\ch0981\anaconda3\lib\site-packages (from mlflow->pycaret) (2.1.1)
Requirement already satisfied: entrypoints in c:\users\ch0981\anaconda3\lib\site-packages (from mlflow->pycaret) (0.3)
Requirement already satisfied: databricks-cli>=0.8.7 in c:\users\ch0981\anaconda3\lib\site-packages (from mlflow->pycaret) (0.16.6)
Requirement already satisfied: packaging in c:\users\ch0981\anaconda3\lib\site-packages (from mlflow->pycaret) (21.0)
Requirement already satisfied: cloudpickle in c:\users\ch0981\anaconda3\lib\site-packages (from mlflow->pycaret) (2.0.0)
Requirement already satisfied: gitpython>=2.1.0 in c:\users\ch0981\anaconda3\lib\site-packages (from mlflow->pycaret) (3.1.27)
Requirement already satisfied: sqlalchemy in c:\users\ch0981\anaconda3\lib\site-packages (from mlflow->pycaret) (1.4.22)
Requirement already satisfied: regex>=2021.8.3 in c:\users\ch0981\anaconda3\lib\site-packages (from nltk->pycaret) (2021.8.3)
Requirement already satisfied: future in c:\users\ch0981\anaconda3\lib\site-packages (from pyLDAvis->pycaret) (0.18.2)
Requirement already satisfied: sklearn in c:\users\ch0981\anaconda3\lib\site-packages (from pyLDAvis->pycaret) (0.0)
Collecting pyLDAvis
  Using cached pyLDAvis-3.3.0.tar.gz (1.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached pyLDAvis-3.2.2-py2.py3-none-any.whl
Requirement already satisfied: numexpr in c:\users\ch0981\anaconda3\lib\site-packages (from pyLDAvis->pycaret) (2.7.3)
Requirement already satisfied: funcy in c:\users\ch0981\anaconda3\lib\site-packages (from pyLDAvis->pycaret) (1.17)
Requirement already satisfied: statsmodels in c:\users\ch0981\anaconda3\lib\site-packages (from pyod->pycaret) (0.12.2)
Requirement already satisfied: pynndescent>=0.5 in c:\users\ch0981\anaconda3\lib\site-packages (from umap-learn->pycaret) (0.5.6)
Requirement already satisfied: pyjwt>=1.7.0 in c:\users\ch0981\anaconda3\lib\site-packages (from databricks-cli>=0.8.7->mlflow->pycaret) (2.1.0)
Requirement already satisfied: oauthlib>=3.1.0 in c:\users\ch0981\anaconda3\lib\site-packages (from databricks-cli>=0.8.7->mlflow->pycaret) (3.2.0)
Requirement already satisfied: tabulate>=0.7.7 in c:\users\ch0981\anaconda3\lib\site-packages (from databricks-cli>=0.8.7->mlflow->pycaret) (0.8.9)
Requirement already satisfied: websocket-client>=0.32.0 in c:\users\ch0981\anaconda3\lib\site-packages (from docker>=4.0.0->mlflow->pycaret) (1.3.2)
Requirement already satisfied: pywin32==227 in c:\users\ch0981\anaconda3\lib\site-packages (from docker>=4.0.0->mlflow->pycaret) (227)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\ch0981\anaconda3\lib\site-packages (from gitpython>=2.1.0->mlflow->pycaret) (4.0.9)
Requirement already satisfied: zipp>=0.5 in c:\users\ch0981\anaconda3\lib\site-packages (from importlib-metadata!=4.7.0,>=3.7.0->mlflow->pycaret) (3.6.0)
Requirement already satisfied: debugpy<2.0,>=1.0.0 in c:\users\ch0981\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (1.4.1)
Requirement already satisfied: tornado<7.0,>=4.2 in c:\users\ch0981\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (6.1)
Requirement already satisfied: jupyter-client<8.0 in c:\users\ch0981\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (6.1.12)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\ch0981\anaconda3\lib\site-packages (from jedi>=0.16->IPython->pycaret) (0.8.2)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\ch0981\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets->pycaret) (3.2.0)
Requirement already satisfied: jupyter-core in c:\users\ch0981\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets->pycaret) (4.8.1)
Requirement already satisfied: wcwidth in c:\users\ch0981\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->IPython->pycaret) (0.2.5)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\ch0981\anaconda3\lib\site-packages (from pydantic>=1.8.1->pandas-profiling>=2.8.0->pycaret) (3.10.0.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\ch0981\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\ch0981\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ch0981\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (3.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ch0981\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2021.10.8)
Requirement already satisfied: notebook>=4.4.1 in c:\users\ch0981\anaconda3\lib\site-packages (from widgetsnbextension~=3.5.0->ipywidgets->pycaret) (6.4.5)
Requirement already satisfied: Mako in c:\users\ch0981\anaconda3\lib\site-packages (from alembic->mlflow->pycaret) (1.2.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\ch0981\anaconda3\lib\site-packages (from sqlalchemy->mlflow->pycaret) (1.1.1)
Requirement already satisfied: Werkzeug>=0.15 in c:\users\ch0981\anaconda3\lib\site-packages (from Flask->mlflow->pycaret) (2.0.2)
Requirement already satisfied: itsdangerous>=0.24 in c:\users\ch0981\anaconda3\lib\site-packages (from Flask->mlflow->pycaret) (2.0.1)
Requirement already satisfied: prometheus-client in c:\users\ch0981\anaconda3\lib\site-packages (from prometheus-flask-exporter->mlflow->pycaret) (0.11.0)
Requirement already satisfied: patsy>=0.5 in c:\users\ch0981\anaconda3\lib\site-packages (from statsmodels->pyod->pycaret) (0.5.2)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\ch0981\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython>=2.1.0->mlflow->pycaret) (5.0.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\ch0981\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->pycaret) (0.18.0)
Requirement already satisfied: pyzmq>=13 in c:\users\ch0981\anaconda3\lib\site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets->pycaret) (22.2.1)
Requirement already satisfied: Send2Trash>=1.5.0 in c:\users\ch0981\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (1.8.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\ch0981\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.9.4)
Requirement already satisfied: nbconvert in c:\users\ch0981\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (6.1.0)
Requirement already satisfied: argon2-cffi in c:\users\ch0981\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (20.1.0)
Requirement already satisfied: PyWavelets in c:\users\ch0981\anaconda3\lib\site-packages (from imagehash->visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pycaret) (1.1.1)
Requirement already satisfied: pywinpty>=0.5 in c:\users\ch0981\anaconda3\lib\site-packages (from terminado>=0.8.3->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.5.7)
Requirement already satisfied: cffi>=1.0.0 in c:\users\ch0981\anaconda3\lib\site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (1.14.6)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\ch0981\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.8.4)
Requirement already satisfied: testpath in c:\users\ch0981\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.5.0)
Requirement already satisfied: jupyterlab-pygments in c:\users\ch0981\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.1.2)
Requirement already satisfied: bleach in c:\users\ch0981\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (4.0.0)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\ch0981\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.5.3)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\ch0981\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (1.4.3)
Requirement already satisfied: defusedxml in c:\users\ch0981\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.7.1)
Requirement already satisfied: pycparser in c:\users\ch0981\anaconda3\lib\site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (2.20)
Requirement already satisfied: nest-asyncio in c:\users\ch0981\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (1.5.1)
Requirement already satisfied: async-generator in c:\users\ch0981\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (1.10)
Requirement already satisfied: webencodings in c:\users\ch0981\anaconda3\lib\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.5.1)
Building wheels for collected packages: scikit-learn
  Building wheel for scikit-learn (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for scikit-learn (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      Partial import of sklearn during the build process.
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      C:\Users\ch0981\AppData\Local\Temp\pip-build-env-qw67512i\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py:528: UserWarning: Fallback spawn triggered. Please update distutils monkeypatch.
        warnings.warn(
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /Tctest_program.c /Foobjects\test_program.obj
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.32.31326\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.19041.0\\um\x64 objects\test_program.obj /OUT:test_program.exe
      Traceback (most recent call last):
        File "C:\Users\ch0981\Anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\ch0981\Anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\ch0981\Anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\ch0981\AppData\Local\Temp\pip-build-env-qw67512i\overlay\Lib\site-packages\setuptools\build_meta.py", line 244, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\ch0981\AppData\Local\Temp\pip-build-env-qw67512i\overlay\Lib\site-packages\setuptools\build_meta.py", line 229, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\ch0981\AppData\Local\Temp\pip-build-env-qw67512i\overlay\Lib\site-packages\setuptools\build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\ch0981\AppData\Local\Temp\pip-build-env-qw67512i\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 304, in <module>
          setup_package()
        File "setup.py", line 300, in setup_package
          setup(**metadata)
        File "C:\Users\ch0981\AppData\Local\Temp\pip-build-env-qw67512i\overlay\Lib\site-packages\numpy\distutils\core.py", line 137, in setup
          config = configuration()
        File "setup.py", line 183, in configuration
          config.add_subpackage('sklearn')
        File "C:\Users\ch0981\AppData\Local\Temp\pip-build-env-qw67512i\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 1033, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
        File "C:\Users\ch0981\AppData\Local\Temp\pip-build-env-qw67512i\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 999, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File "C:\Users\ch0981\AppData\Local\Temp\pip-build-env-qw67512i\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 941, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "sklearn\setup.py", line 88, in configuration
          cythonize_extensions(top_path, config)
        File "C:\Users\ch0981\AppData\Local\Temp\pip-install-c_a1_k82\scikit-learn_6c8225163b344cfbbc916c2978fb6211\sklearn\_build_utils\__init__.py", line 50, in cythonize_extensions
          basic_check_build()
        File "C:\Users\ch0981\AppData\Local\Temp\pip-install-c_a1_k82\scikit-learn_6c8225163b344cfbbc916c2978fb6211\sklearn\_build_utils\pre_build_helpers.py", line 70, in basic_check_build
          compile_test_program(code)
        File "C:\Users\ch0981\AppData\Local\Temp\pip-install-c_a1_k82\scikit-learn_6c8225163b344cfbbc916c2978fb6211\sklearn\_build_utils\pre_build_helpers.py", line 51, in compile_test_program
          output = subprocess.check_output('./test_program')
        File "C:\Users\ch0981\Anaconda3\lib\subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\ch0981\Anaconda3\lib\subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\ch0981\Anaconda3\lib\subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\ch0981\Anaconda3\lib\subprocess.py", line 1420, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      PermissionError: [WinError 5] Access is denied
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-learn
Failed to build scikit-learn
ERROR: Could not build wheels for scikit-learn, which is required to install pyproject.toml-based projects
WARNING: There was an error checking the latest version of pip.

</details>

**Comment by ngupta23** [comment]
Please use an environment with python 3.8. python 3.10 is not supported yet.
