### ISSUE TITLE
[INSTALL]: Incompatibilities on Google Colab

### ISSUE THREAD

**Issue by EnSei1984** [pycaret/pycaret#2591]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic

### Installation Method

pip install

### pycaret Version

2.3.10

### Python Version

3.7.13

### Description

Does anyone know how I can get Pycaret to run on Google Colab? Several months ago PyCaret with version 2.3.6 was running on Colab but now there are so many incompatibilities that I can't get PyCaret to run for hours. Is there a guide that can help? When I uninstall and reinstall the respective versions (e.g. numpy >= 1.21 is required but installed is numpy 1.19.5), the incompatibilities simply move to the next package. Especially PyCarets NLP module causes problems, by the message: 
```

---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

[<ipython-input-5-7bbc59339599>](https://localhost:8080/#) in <module>()
----> 1 from pycaret.nlp import *

5 frames

[/usr/local/lib/python3.7/dist-packages/pandas/compat/_optional.py](https://localhost:8080/#) in import_optional_dependency(name, extra, errors, min_version)
    116     except ImportError:
    117         if errors == "raise":
--> 118             raise ImportError(msg) from None
    119         else:
    120             return None

ImportError: Missing optional dependency 'Jinja2'. DataFrame.style requires jinja2. Use pip or conda to install Jinja2.


---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```
The suggested solution on stackoverflow (https://stackoverflow.com/questions/72090241/unable-to-resolve-import-error-from-pycaret) doesn't work for this issue.  So the question: Can someone please help and give clues how I can get PyCaret working on Colab?

### Installation Logs

<details>

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.8.0+zzzcolab20220506162203 requires tf-estimator-nightly==2.8.0.dev2021122109, which is not installed.
xarray-einstats 0.2.2 requires numpy>=1.21, but you have numpy 1.19.5 which is incompatible.
tensorflow 2.8.0+zzzcolab20220506162203 requires numpy>=1.20, but you have numpy 1.19.5 which is incompatible.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.27.1 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.

</details>

**Comment by moezali1** [comment]
@EnSei1984 After you install pycaret, please do this `pip install -U jinja2`. Restart your kernel and it will work.
