### ISSUE TITLE
[BUG]: name 'create_api' is not defined

### ISSUE THREAD

**Issue by kakalovedata** [pycaret/pycaret#2593]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

NameError: name 'create_api' is not defined
 

### Reproducible Example

```python
from pycaret.datasets import get_data
data = get_data('iris')
from pycaret.classification import *
s = setup(data, target = 'species', session_id = 123, ignore_features = ['petal_width'])
lr = create_model('lr')
create_api(lr, 'my_lr_api')
```

### Expected Behavior

无法创建api， 提示没有create_api 这个命令

### Actual Results

```python-traceback
NameError: name 'create_api' is not defined
```

### Installed Versions

<details>
Replace this line with the output of the version code above.
</details>

**Comment by moezali1** [comment]
@kakalovedata Hi. Can you please tell me which version you are using? and the complete traceback.

**Comment by ngupta23** [comment]
@kakalovedata Since we have not heard back, we will close this for now. Feel free to provide more details and we can reopen it at that time. Thanks!
