### ISSUE TITLE
request to add extracting the pre_processed data after setup

### ISSUE THREAD

**Issue by sathishkumar369** [pycaret/pycaret#260]
Hi pycaret team!

requesting to add a new feature which is extracting the preprocessed data in Dataframe format from setup model, before creating the model for all regression,classification,clustering and nlp models. so that we can use the preprocessed data for some another data analysis.

![image](https://user-images.githubusercontent.com/40235632/86324740-a5080200-bc5c-11ea-9822-a5966e5ce32d.png)

**Comment by pycaret** [comment]
@sathishkumar369 Thanks for the suggestion. Tagging this as an enhancement.

**Comment by bjuncklaus** [comment]
There's actually a way of retrieving it after `setup` @sathishkumar369 . The `setup` documentation is this: "This function returns various outputs that are stored in variables as tuples. They are used by other functions in pycaret.". However, after analyzing the source code I found out that the function returns a tuple with this content:
- `X`
- `y`
- `X_train`
- `X_test`
- `y_train`
- `y_test`
- `seed`
- `prep_pipe`
- `experiment__`

So if you have a variable with the content return by the `setup` function you can retrieve the train/test data back by accessing its corresponding tuple index. For example `my_setup = setup(...)` then `X_test_data = my_setup[3]`.

I suggest adding this info to the documentation asap.

**Comment by pycaret** [comment]
# Feature available in PyCaret 2.0

## A new function **get_config()** has been added in PyCaret 2.0. (pip install pycaret==2.0)
https://www.pycaret.org/get-config
