### ISSUE TITLE
[BUG]: Setting a random_state has no effect since shuffle is False. You should leave random_state to its default (None), or set shuffle=True.

### ISSUE THREAD

**Issue by mw1296** [pycaret/pycaret#2603]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

I tried below two solutions and they both are no longer working:
`shuffle=True` returns:
TypeError: setup() got an unexpected keyword argument 'shuffle'
`fold_shuffle=True` returns:
TypeError: setup() got an unexpected keyword argument 'fold_shuffle'

Anyone facing the same issue? 

### Reproducible Example

```python
from pycaret.datasets import get_data
dataset = get_data('mice')

# check shape of data
dataset.shape
# withhold 5% of data for testing purpose
data=dataset.sample(frac=0.95, random_state=786)
data_unseen=dataset.drop(data.index)
data.reset_index(drop=True,inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

# seting up environment for Pycaret
from pycaret.anomaly import *
exp_ano101=setup(data,normalize=True,
                 fold_shuffle=True,
                 ignore_features=['MouseID'],           
                 session_id=123)
```

### Expected Behavior

either shuffle or fold_shuffle works

### Actual Results

```python-traceback
exp_ano101=setup(data,normalize=True,
                 shuffle=True,
                 ignore_features=['MouseID'],
                 session_id=123)
Traceback (most recent call last):

  File "<ipython-input-15-b2fd4c8e0bbd>", line 1, in <module>
    exp_ano101=setup(data,normalize=True,

TypeError: setup() got an unexpected keyword argument 'shuffle'


exp_ano101=setup(data,normalize=True,
                 fold_shuffle=True,
                 ignore_features=['MouseID'],
                 session_id=123)
Traceback (most recent call last):

  File "<ipython-input-16-158d4092ed52>", line 1, in <module>
    exp_ano101=setup(data,normalize=True,

TypeError: setup() got an unexpected keyword argument 'fold_shuffle'
```

### Installed Versions

<details>
2.2
</details>

**Comment by mw1296** [comment]
update: 
The root issue is the version of scikit-learn being too new. Solution is to degrade version to 0.23.2 as mentioned in this thread
https://stackoverflow.com/a/70483174/19231753

**Comment by ngupta23** [comment]
@mw1296 This is a very old version of pycaret. Can you upgrade to the latest version? It should not have any issues.

`pip install -U --pre pycaret`
