### ISSUE TITLE
[INSTALL]: Build wheel failing for Scikit learn 

### ISSUE THREAD

**Issue by SSMK-wq** [pycaret/pycaret#2605]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Windows-10-10.0.19044-SP0

### Installation Method

pip install

### pycaret Version

=latest

### Python Version

3.7

### Description

I tried installing the Pycaret using `pip install pycaret` command and got the below error

```
tatus-deactivated.json.gz -> build\bdist.win-amd64\wheel\.\sklearn\datasets\tests\data\openml\292
      error: could not create 'build\bdist.win-amd64\wheel\.\sklearn\datasets\tests\data\openml\292\api-v1-json-data-list-data_name-australian-limit-2-data_version-1-status-deactivated.json.gz': No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-learn
Failed to build scikit-learn
ERROR: Could not build wheels for scikit-learn, which is required to install pyproject.toml-based projects
```

How can I avoid this error and try using Pycaret?

### Installation Logs

<details>

tatus-deactivated.json.gz -> build\bdist.win-amd64\wheel\.\sklearn\datasets\tests\data\openml\292
      error: could not create 'build\bdist.win-amd64\wheel\.\sklearn\datasets\tests\data\openml\292\api-v1-json-data-list-data_name-australian-limit-2-data_version-1-status-deactivated.json.gz': No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-learn
Failed to build scikit-learn
ERROR: Could not build wheels for scikit-learn, which is required to install pyproject.toml-based projects

</details>

**Comment by ngupta23** [comment]
It works ok for me. Not sure if it is related to this issue (Microsoft Visual C++ installation): https://stackoverflow.com/questions/70377207/can-not-install-scikit-learn. Can you check the solution in this link?

**Comment by ngupta23** [comment]
@SSMK-wq Since we have not heard back, we will close this for now. Feel free to comment on this and we will reopen this if the issue persists. Thanks!
