### ISSUE TITLE
[BUG]: plot_model(iforest) shows no graph in pycaret

### ISSUE THREAD

**Issue by mw1296** [pycaret/pycaret#2608]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

Following the tutorial https://github.com/pycaret/pycaret/blob/master/tutorials/Anomaly%20Detection%20Tutorial%20Level%20Beginner%20-%20ANO101.ipynb
when I approach plot_model(iforest), the plot displays nothing. I've enabled inline graph and unmuted the plot, and make sure this is not a display issue. 
The only change I made is that I'm using "Anomaly" dataset instead of "Mice". 
Any thought what is the issue?

### Reproducible Example

```python
import seaborn as sns
from pycaret.datasets import get_data
import graphviz
import pydot
import pydot_ng as pydot
pydot.find_graphviz()
dataset = get_data('anomaly')

# check shape of data
dataset.shape
# withhold 5% of data for testing purpose
data=dataset.sample(frac=0.95, random_state=678)
data_unseen=dataset.drop(data.index)
data.reset_index(drop=True,inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

# pairplot
    
# seting up environment for Pycaret
from pycaret.anomaly import *
exp_ano101=setup(data,normalize=True,
                 session_id=123
                 )

# create a model
iforest=create_model('iforest') 
print(iforest)
# note that the contamination=0.05 determines the proportion of outliers in the dataset

# assign anomaly labels to dataset to analyze result with iforest
iforest_results=assign_model(iforest)
iforest_results.head()

# plot model
plot_model(iforest,'tsne')
```

### Expected Behavior

https://cdn-images-1.medium.com/max/1000/1*XprV1KkrqkEBMKxLh7aCCw.png

### Actual Results

```python-traceback
no graph is shown and the created plot has no value

```

### Installed Versions

<details>
2.2
</details>

**Comment by kilickursat** [comment]
Could you try to install "!pip install matplotlib==3.1.3" and try to plot? It might be helpful.

**Comment by ngupta23** [comment]
@mw1296 This is a very old version of pycaret. Can you upgrade to the latest version? It should not have any issues.

`pip install -U --pre pycaret`
