### ISSUE TITLE
[INSTALL]: python 3.9 with pycaret 2.3.10

### ISSUE THREAD

**Issue by d4deva** [pycaret/pycaret#2614]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Windows

### Installation Method

pip install

### pycaret Version

Pycaret[full]

### Python Version

3.9.12

### Description

Getting the following error
Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\sramaraopras\\Anaconda3\\Lib\\site-packages\\win32\\_win32sysloader.pyd' Consider using the `--user` option or check the permissions.

### Installation Logs

ERROR: Command errored out with exit status 1:
command: 'C:\Users\sramaraopras\Anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sramaraopras\\AppData\\Local\\Temp\\pip-install-9oaowory\\wordcloud_a796e1de8d9844a6aefe67a688e2d7fd\\setup.py'"'"'; __file__='"'"'C:\\Users\\sramaraopras\\AppData\\Local\\Temp\\pip-install-9oaowory\\wordcloud_a796e1de8d9844a6aefe67a688e2d7fd\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\sramaraopras\AppData\Local\Temp\pip-wheel-n5rouxzp'
cwd: C:\Users\sramaraopras\AppData\Local\Temp\pip-install-9oaowory\wordcloud_a796e1de8d9844a6aefe67a688e2d7fd\
Complete output (20 lines):
running bdist_wheel
running build
running build_py
creating build
creating build\lib.win-amd64-3.9
creating build\lib.win-amd64-3.9\wordcloud
copying wordcloud\color_from_image.py -> build\lib.win-amd64-3.9\wordcloud
copying wordcloud\tokenization.py -> build\lib.win-amd64-3.9\wordcloud
copying wordcloud\wordcloud.py -> build\lib.win-amd64-3.9\wordcloud
copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-3.9\wordcloud
copying wordcloud\_version.py -> build\lib.win-amd64-3.9\wordcloud
copying wordcloud\__init__.py -> build\lib.win-amd64-3.9\wordcloud
copying wordcloud\__main__.py -> build\lib.win-amd64-3.9\wordcloud
copying wordcloud\stopwords -> build\lib.win-amd64-3.9\wordcloud
copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-3.9\wordcloud
UPDATING build\lib.win-amd64-3.9\wordcloud/_version.py
set build\lib.win-amd64-3.9\wordcloud/_version.py to '1.8.1'
running build_ext
building 'wordcloud.query_integral_image' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
----------------------------------------
ERROR: Failed building wheel for wordcloud
Running setup.py clean for wordcloud
Failed to build wordcloud
Installing collected packages: wordcloud, umap-learn, textblob, spacy, slicer, scikit-plot, s3transfer, pyod, pyLDAvis, pyaml, py4j, pandas-profiling, msrest, mlxtend, mlflow, lightgbm, kmodes, imbalanced-learn, docutils, cufflinks, colorlog, cmaes, cliff, catboost, azure-core, tune-sklearn, shap, scikit-optimize, pycaret, optuna, hyperopt, azure-storage-blob, awscli
Running setup.py install for wordcloud ... error
ERROR: Command errored out with exit status 1:
command: 'C:\Users\sramaraopras\Anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sramaraopras\\AppData\\Local\\Temp\\pip-install-9oaowory\\wordcloud_a796e1de8d9844a6aefe67a688e2d7fd\\setup.py'"'"'; __file__='"'"'C:\\Users\\sramaraopras\\AppData\\Local\\Temp\\pip-install-9oaowory\\wordcloud_a796e1de8d9844a6aefe67a688e2d7fd\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\sramaraopras\AppData\Local\Temp\pip-record-1hau0nvd\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\sramaraopras\Anaconda3\Include\wordcloud'
cwd: C:\Users\sramaraopras\AppData\Local\Temp\pip-install-9oaowory\wordcloud_a796e1de8d9844a6aefe67a688e2d7fd\
Complete output (22 lines):
running install
C:\Users\sramaraopras\Anaconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
warnings.warn(
running build
running build_py
creating build
creating build\lib.win-amd64-3.9
creating build\lib.win-amd64-3.9\wordcloud
copying wordcloud\color_from_image.py -> build\lib.win-amd64-3.9\wordcloud
copying wordcloud\tokenization.py -> build\lib.win-amd64-3.9\wordcloud
copying wordcloud\wordcloud.py -> build\lib.win-amd64-3.9\wordcloud
copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-3.9\wordcloud
copying wordcloud\_version.py -> build\lib.win-amd64-3.9\wordcloud
copying wordcloud\__init__.py -> build\lib.win-amd64-3.9\wordcloud
copying wordcloud\__main__.py -> build\lib.win-amd64-3.9\wordcloud
copying wordcloud\stopwords -> build\lib.win-amd64-3.9\wordcloud
copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-3.9\wordcloud
UPDATING build\lib.win-amd64-3.9\wordcloud/_version.py
set build\lib.win-amd64-3.9\wordcloud/_version.py to '1.8.1'
running build_ext
building 'wordcloud.query_integral_image' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\sramaraopras\Anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sramaraopras\\AppData\\Local\\Temp\\pip-install-9oaowory\\wordcloud_a796e1de8d9844a6aefe67a688e2d7fd\\setup.py'"'"'; __file__='"'"'C:\\Users\\sramaraopras\\AppData\\Local\\Temp\\pip-install-9oaowory\\wordcloud_a796e1de8d9844a6aefe67a688e2d7fd\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\sramaraopras\AppData\Local\Temp\pip-record-1hau0nvd\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\sramaraopras\Anaconda3\Include\wordcloud' Check the logs for full command output.

**Comment by celestinoxp** [comment]
1º - Python - I'm not sure if pycaret 2.3.10 will work well with python 3.9. I believe the ideal would be python 3.8 for pycaret 2.3.10 and python 3.9 for pycaret 3.0 (next release still in development).

2º - Wordcloud package -> I had the same problem with that package (wordcloud) and I solved it with here (Unofficial Windows Binaries for Python Extension Packages) https://www.lfd.uci.edu/~gohlke/pythonlibs/#wordcloud

It's my opinion, but maybe a better opinion from pycaret developers is better.

**Comment by ngupta23** [comment]
> 1º - Python - I'm not sure if pycaret 2.3.10 will work well with python 3.9. I believe the ideal would be python 3.8 for pycaret 2.3.10 and python 3.9 for pycaret 3.0 (next release still in development).

Correct... Python 3.9 will be supported from the pycaret 3.0.0 release (to be done shortly)

**Comment by ngupta23** [comment]
pycaret 3.0.0,rc was released recently so you can now install this version with python 3.9. Please give it a try.

`pip install -U --pre pycaret`

**Comment by ngupta23** [comment]
We will close this for now. Feel free to comment (or open another issue) if the problem persists.
