### ISSUE TITLE
[INSTALL]: scikit-learn version requirement

### ISSUE THREAD

**Issue by tczhao** [pycaret/pycaret#2615]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Installation Method

pip install

### pycaret Version

latest

### Python Version

3.7

### Description

I wonder if there's any reason to fix the sklearn version?
`scikit-learn==0.23.2`
https://github.com/pycaret/pycaret/commit/87133aa3c2512a9b1d68394a8ea7388ffda19c14

Could we loosen this restriction?
e.g. `scikit-learn>=0.23.2`

`scikit-learn` is on version > 1.2.0 now, it's resolving between `pandas`/`numpy` versions nicely, but seems `pycaret` needs some work

**Comment by celestinoxp** [comment]
nex relase of pycaret (pycaret 3.0) will support scikit-learn>=1.0.
i believe it will released next few days...

**Comment by tczhao** [comment]
Thank you :))
