### ISSUE TITLE
Option to pass param_distributions in tune_model

### ISSUE THREAD

**Issue by sumeshmr** [pycaret/pycaret#263]
Hello,

Thank you for making this excellent library!

I can see that the parameter combinations are hardcoded in **tune_model**. It would be good if the user can pass his custom parameter combinations. Making it a parameter in the tune_model would be great.

Thanks in advance.

**Comment by pycaret** [comment]
@sumeshmr Thanks for the suggestion. parameter called **custom_grid** is added for next release. If you would like to test, you can install **pycaret-nightly** and let me know how it goes.

For now - I am tagging this issue as an enhancement and will close on release of 2.0x

**Comment by pycaret** [comment]
### Feature now available in pycaret-nightly.

You can install **pycaret-nightly** using "pip install pycaret-nightly".

Can you please test this and close the issue if the enhancement addresses the original issue.

It will be shipped to PyCaret 2.0x in few weeks.

**Comment by sumeshmr** [comment]
I could see the option in the nightly build. Thanks.
