### ISSUE TITLE
Pycaret don't give me a model

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#2630]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

I don´t know if i can try test a small dataframe like 2 columns and 20 rows.
If yes, pycaret don´t give me a model.

### Reproducible Example

```python
import pandas as pd
import numpy as np
import pycaret

#example data with 2 columns and 20 items
df = pd.DataFrame(data=np.random.randint(0, 3, (20,2)), columns =["a", "b"])
df

from pycaret.classification import *

s = setup(df, target='b')

model = compare_models()

models #this should give me a name o choosed model but is empty []

tuned_model = tune_model(model) #boom!
```

### Expected Behavior

models --> should give me a name  of choosed model by compare_models(), to tune_model can tune, however can´t do it because models is empty!

### Actual Results

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 tuned_model = tune_model(model)

File ~\anaconda3\envs\teste2\lib\site-packages\pycaret\internal\utils.py:922, in check_if_global_is_not_none.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    920     if globals_d[name] is None:
    921         raise ValueError(message)
--> 922 return func(*args, **kwargs)

File ~\anaconda3\envs\teste2\lib\site-packages\pycaret\classification\functional.py:1093, in tune_model(estimator, fold, round, n_iter, custom_grid, optimize, custom_scorer, search_library, search_algorithm, early_stopping, early_stopping_max_iters, choose_better, fit_kwargs, groups, return_tuner, verbose, tuner_verbose, return_train_score, **kwargs)
    901 @check_if_global_is_not_none(globals(), _CURRENT_EXPERIMENT_DECORATOR_DICT)
    902 def tune_model(
    903     estimator,
   (...)
    921     **kwargs,
    922 ) -> Any:
    924     """
    925     This function tunes the hyperparameters of a given estimator. The output of
    926     this function is a score grid with CV scores by fold of the best selected
   (...)
   1090 
   1091     """
-> 1093     return _CURRENT_EXPERIMENT.tune_model(
   1094         estimator=estimator,
   1095         fold=fold,
   1096         round=round,
   1097         n_iter=n_iter,
   1098         custom_grid=custom_grid,
   1099         optimize=optimize,
   1100         custom_scorer=custom_scorer,
   1101         search_library=search_library,
   1102         search_algorithm=search_algorithm,
   1103         early_stopping=early_stopping,
   1104         early_stopping_max_iters=early_stopping_max_iters,
   1105         choose_better=choose_better,
   1106         fit_kwargs=fit_kwargs,
   1107         groups=groups,
   1108         return_tuner=return_tuner,
   1109         verbose=verbose,
   1110         tuner_verbose=tuner_verbose,
   1111         return_train_score=return_train_score,
   1112         **kwargs,
   1113     )

File ~\anaconda3\envs\teste2\lib\site-packages\pycaret\classification\oop.py:1426, in ClassificationExperiment.tune_model(self, estimator, fold, round, n_iter, custom_grid, optimize, custom_scorer, search_library, search_algorithm, early_stopping, early_stopping_max_iters, choose_better, fit_kwargs, groups, return_tuner, verbose, tuner_verbose, return_train_score, **kwargs)
   1234 def tune_model(
   1235     self,
   1236     estimator,
   (...)
   1254     **kwargs,
   1255 ) -> Any:
   1257     """
   1258     This function tunes the hyperparameters of a given estimator. The output of
   1259     this function is a score grid with CV scores by fold of the best selected
   (...)
   1423 
   1424     """
-> 1426     return super().tune_model(
   1427         estimator=estimator,
   1428         fold=fold,
   1429         round=round,
   1430         n_iter=n_iter,
   1431         custom_grid=custom_grid,
   1432         optimize=optimize,
   1433         custom_scorer=custom_scorer,
   1434         search_library=search_library,
   1435         search_algorithm=search_algorithm,
   1436         early_stopping=early_stopping,
   1437         early_stopping_max_iters=early_stopping_max_iters,
   1438         choose_better=choose_better,
   1439         fit_kwargs=fit_kwargs,
   1440         groups=groups,
   1441         return_tuner=return_tuner,
   1442         verbose=verbose,
   1443         tuner_verbose=tuner_verbose,
   1444         return_train_score=return_train_score,
   1445         **kwargs,
   1446     )

File ~\anaconda3\envs\teste2\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py:1947, in _SupervisedExperiment.tune_model(self, estimator, fold, round, n_iter, custom_grid, optimize, custom_scorer, search_library, search_algorithm, early_stopping, early_stopping_max_iters, choose_better, fit_kwargs, groups, return_tuner, verbose, tuner_verbose, return_train_score, **kwargs)
   1945 # Check for estimator
   1946 if not hasattr(estimator, "fit"):
-> 1947     raise ValueError(
   1948         f"Estimator {estimator} does not have the required fit() method."
   1949     )
   1951 # checking fold parameter
   1952 if fold is not None and not (
   1953     type(fold) is int or is_sklearn_cv_generator(fold)
   1954 ):

ValueError: Estimator [] does not have the required fit() method.
```

### Installed Versions

<details>
System:
    python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\celes\anaconda3\envs\teste2\python.exe
   machine: Windows-10-10.0.22621-SP0

PyCaret required dependencies:
                 pip: 21.2.4
          setuptools: 60.10.0
             pycaret: 3.0.0.rc1
             ipython: Installed but version unavailable
          ipywidgets: 7.7.0
                tqdm: 4.64.0
               numpy: 1.21.6
              pandas: 1.4.2
              jinja2: 3.1.2
               scipy: 1.8.1
              joblib: 1.1.0
             sklearn: 1.1.1
                pyod: Installed but version unavailable
            imblearn: 0.9.1
   category_encoders: 2.5.0
            lightgbm: 3.3.2
               numba: 0.55.2
            requests: 2.27.1
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.8.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.11.4
               tbats: Installed but version unavailable
            pmdarima: 1.8.5
              psutil: 5.9.1

PyCaret optional dependencies:
                shap: 0.40.0
           interpret: 0.2.7
                umap: 0.5.3
    pandas_profiling: 3.2.0
  explainerdashboard: Installed but version unavailable
             autoviz: 0.1.39
           fairlearn: 0.7.0
             xgboost: 1.6.1
            catboost: 1.0.6
              kmodes: 0.12.1
             mlxtend: 0.20.0
       statsforecast: Installed but version unavailable
        tune_sklearn: Installed but version unavailable
                 ray: Installed but version unavailable
            hyperopt: 0.2.7
              optuna: 2.10.0
               skopt: 0.9.0
              mlflow: 1.26.1
              gradio: 3.0.11
             fastapi: 0.78.0
             uvicorn: 0.17.6
              m2cgen: 0.10.0
           evidently: 0.1.51.dev0
                nltk: 3.7
            pyLDAvis: 3.3.1
              gensim: 4.2.0
               spacy: 3.3.0
           wordcloud: 1.8.1
            textblob: 0.17.1
               fugue: 0.6.6
           streamlit: Installed but version unavailable
             prophet: Installed but version unavailable
</details>

**Comment by ngupta23** [comment]
Can you run compare_models with the following argument: `errors = "raise`. It seems that the models are not getting created for some reason and running with this argument will point out the potential issue.

**Comment by ngupta23** [comment]
It looks like you have very little data to do 10 fold cross-validation. This is what I get when I try your code with `errors="raise"`

```python-traceback
ValueError: n_splits=10 cannot be greater than the number of members in each class.
```
