### ISSUE TITLE
[ENH]: Improved plotting experience for large time series

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#2634]
### Describe the feature you want to add to this project

Handling large time series can be slow when interactions are enabled in plotly.

### Describe your proposed solution

Add plotly resampler when large time series are involved.

https://www.linkedin.com/posts/stevenouri_datascience-visualization-activity-6939386365918752768-ym2b/

![image](https://user-images.githubusercontent.com/33585645/172161178-f9b3c8c2-2f78-4831-b3df-749ea1a0b192.png)

### Describe alternatives you've considered, if relevant

Current implementation which uses scattergl instead of scatter. Though this helps, it can still be slow.

**Comment by jvdd** [comment]
Hi @ngupta23,

Sounds very cool! I'm interested in helping you with integrating [plotly-resampler](https://github.com/predict-idlab/plotly-resampler) :smile: 
Can you give some pointers on how / where you would integrate this in `pycaret`?

Also feel free to reach out / ask questions to me (@jvdd) & @jonasvdd!
