### ISSUE TITLE
[ENH]: Implementation of more imputation methods

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#2638]
### Describe the feature you want to add to this project

Implementation of more imputation methods

### Describe your proposed solution

I found an article with interesting imputation methods (https://towardsdatascience.com/implementation-and-limitations-of-imputation-methods-b6576bf31a6c)

**Comment by ngupta23** [comment]
@celestinoxp You can get this today using the following parameters

https://github.com/pycaret/pycaret/blob/28e0ce63291a319ff8d7b381a2e52fd59e8ea7b6/pycaret/regression/oop.py#L255

```
imputation_type: str or None, default = 'simple'
    - The type of imputation to use. Can be either 'simple' or 'iterative' (MICE).

numeric_imputation
    - "drop": Drop rows containing missing values.
    - "mean": Impute with mean of column.
    - "median": Impute with median of column.
    - "mode": Impute with most frequent value.
    - "knn": Impute using a K-Nearest Neighbors approach.
    - int or float: Impute with provided numerical value.

categorical_imputation: str, default = 'mode'
    - "drop": Drop rows containing missing values.
    - "mode": Impute with most frequent value.
    - str: Impute with provided string.

iterative_imputation_iters: int, default = 5
    - numeric_iterative_imputer: str or sklearn estimator, default = 'lightgbm'
    - categorical_iterative_imputer: str or sklearn estimator, default = 'lightgbm'
```

Do you think any imputer is missing from the list?

**Comment by ngupta23** [comment]
@celestinoxp Do you have any more information about what imputation types need to be added to the existing list in pycaret?

**Comment by celestinoxp** [comment]
@ngupta23 No. i make mistake because i follow docs of https://pycaret.readthedocs.io/en/latest/api/classification.html (from pycaret 2.3.x) instead read source code of pycaret 3.x.

ReadDocs (latest vesrsion) should be updated for new version 3.x.

**Comment by ngupta23** [comment]
> ReadDocs (latest version) must be updated to the new 3.x version.

Yes, this will be done when the RC tag is lifted from pycaret 3.0 (@moezali1 FYI...)
