### ISSUE TITLE
[BUG]: show_versions not working in 3.0.0rc2

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#2639]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

On Google Colab, installing the full version of 3.0.0rc2 --> show_versions is not working (it was working in rc1)

### Reproducible Example

```python
try:
    from pycaret import show_versions
except ModuleNotFoundError:
    !pip install -U --pre pycaret[full]
    from pycaret import show_versions

show_versions()
```

### Expected Behavior

Should work as in 3.0.0rc1

### Actual Results

```python-traceback
System:
    python: 3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0]
executable: /usr/bin/python3
   machine: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic

PyCaret required dependencies:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_371/436312852.py in <module>
----> 1 show_versions()

2 frames
/usr/local/lib/python3.7/dist-packages/pycaret/internal/logging.py in __init__(self, logger)
     37     def __init__(self, logger: Optional[logging.Logger] = None):
     38         self.logger = logger or DummyLogger("dummy")
---> 39         self.redirect_stdout = redirect_stdout(LoggerWriter(logger.info))
     40         self.redirect_stderr = redirect_stderr(LoggerWriter(logger.warning))
     41 

AttributeError: 'NoneType' object has no attribute 'info'
```

### Installed Versions

<details>
3.0.0rc2
</details>

**Comment by Yard1** [comment]
Thanks, should be fixed in b2354ff7e539cd5ca82a2dd07d6fa41cb7054482
