### ISSUE TITLE
pip install pycaret

### ISSUE THREAD

**Issue by Kunalthebug** [pycaret/pycaret#264]
When I was trying to download pycaret for the first time, basic libraries like pandas,scipy,nltk,tqdm along with any other libraries started downloading. I am very curious to know the reason behind because this doesn't happen while downloading other libraries, Is it because pycaret is recently launched and there are dependencies? Can somebody figure this out?

**Comment by pycaret** [comment]
@Kunalthebug Thanks for reporting. There are dependencies listed in requirements.txt file which PyCaret will download when you use "pip install pycaret". 

Other alternate is to build from source from cloning the repo.

In either case, if you already have those libraries installed on your machine, It will not install it.
