### ISSUE TITLE
[BUG]: compare_models() display ERROR

### ISSUE THREAD

**Issue by Riazone** [pycaret/pycaret#2640]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

![Error](https://user-images.githubusercontent.com/52306083/172292205-4fb53c40-ba47-4c6a-aafc-6736168e56b3.png)

### Reproducible Example

```python
from pycaret.datasets import get_data
data = get_data('juice')
from pycaret.classification import *
s = setup(data, target = 'Purchase')

best = compare_models()
```

### Expected Behavior

Expected output is the compare models leadership table.

### Actual Results

```python-traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-9dbb5bbd548b> in <module>
----> 1 best = compare_models()

~\anaconda3\lib\site-packages\pycaret\internal\utils.py in wrapper(*args, **kwargs)
    920                 if globals_d[name] is None:
    921                     raise ValueError(message)
--> 922             return func(*args, **kwargs)
    923 
    924         return wrapper

~\anaconda3\lib\site-packages\pycaret\classification\functional.py in compare_models(include, exclude, fold, round, cross_validation, sort, n_select, budget_time, turbo, errors, fit_kwargs, groups, experiment_custom_tags, probability_threshold, verbose, parallel)
    741     """
    742 
--> 743     return _CURRENT_EXPERIMENT.compare_models(
    744         include=include,
    745         exclude=exclude,

~\anaconda3\lib\site-packages\pycaret\classification\oop.py in compare_models(self, include, exclude, fold, round, cross_validation, sort, n_select, budget_time, turbo, errors, fit_kwargs, groups, experiment_custom_tags, probability_threshold, verbose, parallel)
   1075         # No extra code above this line
   1076 
-> 1077         return super().compare_models(
   1078             include=include,
   1079             exclude=exclude,

~\anaconda3\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py in compare_models(self, include, exclude, fold, round, cross_validation, sort, n_select, budget_time, turbo, errors, fit_kwargs, groups, experiment_custom_tags, probability_threshold, verbose, parallel, caller_params)
    632             DummyDisplay()
    633             if self._remote
--> 634             else CommonDisplay(
    635                 verbose=verbose,
    636                 html_param=self.html_param,

~\anaconda3\lib\site-packages\pycaret\internal\display\display.py in __init__(self, verbose, html_param, progress_args, monitor_rows)
     98                 **progress_args, backend=backend_id, verbose=self.verbose
     99             )
--> 100             self._progress_bar_display.display()
    101         else:
    102             self._progress_bar_display = None

~\anaconda3\lib\site-packages\pycaret\internal\display\progress_bar.py in display(self)
    144             backend=self.backend,
    145         )
--> 146         self.pbar_backend.open()
    147 
    148     def step(self, value: int = 1):

~\anaconda3\lib\site-packages\pycaret\internal\display\progress_bar.py in open(self)
     96 class JupyterProgressBarBackend(ProgressBarBackend):
     97     def open(self):
---> 98         self._pbar = CustomDisplayNotebookTqdm(
     99             desc=self.description,
    100             total=self.max,

~\anaconda3\lib\site-packages\pycaret\internal\display\progress_bar.py in __init__(self, *args, **kwargs)
     60     def __init__(self, *args, **kwargs):
     61         self.display_backend: DisplayBackend = kwargs.pop("display_backend")
---> 62         super().__init__(*args, **kwargs)
     63 
     64     def display(

~\anaconda3\lib\site-packages\tqdm\notebook.py in __init__(self, *args, **kwargs)
    242         # Print initial bar state
    243         if not self.disable:
--> 244             self.display()
    245 
    246     def __iter__(self):

~\anaconda3\lib\site-packages\pycaret\internal\display\progress_bar.py in display(self, msg, pos, close, bar_style, check_delay)
     66     ):
     67         # trick tqdm into doing all the updating without displaying in its own display
---> 68         original_displayed = self.displayed
     69         self.displayed = True
     70         _, pbar, _ = self.container.children

AttributeError: 'CustomDisplayNotebookTqdm' object has no attribute 'displayed'
```

### Installed Versions

<details>
System:
    python: 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\riazu\anaconda3\python.exe
   machine: Windows-10-10.0.22000-SP0

PyCaret required dependencies:
                 pip: 21.0.1
          setuptools: 52.0.0.post20210125
             pycaret: 3.0.0.rc2
             IPython: 7.22.0
          ipywidgets: 8.0.0rc0
                tqdm: 4.59.0
               numpy: 1.21.6
              pandas: 1.4.2
              jinja2: 3.1.2
               scipy: 1.5.4
              joblib: 1.1.0
             sklearn: 1.1.1
                pyod: Installed but version unavailable
            imblearn: 0.9.1
   category_encoders: 2.5.0
            lightgbm: 3.3.2
               numba: 0.55.2
            requests: 2.27.1
          matplotlib: 3.3.4
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.8.0
             kaleido: 0.2.1
         statsmodels: 0.12.2
              sktime: 0.11.4
               tbats: Installed but version unavailable
            pmdarima: 1.8.5
              psutil: 5.9.1
</details>

**Comment by ngupta23** [comment]
Hi @Riazone , It seems to be working in Google Colab, but it is a Linux machine. See https://gist.github.com/ngupta23/d2673f084a846562537fb25f52305732.

Can you try to run this on Colab to confirm. Maybe it is a Windows specific issue. This will help us narrow down the issue.

Thanks!

**Comment by Riazone** [comment]
Hi @ngupta23 , It is running fine in Colab, having issues on my Windows computer in Jupyter notebook.
Thanks!

**Comment by Yard1** [comment]
@Riazone This is a tqdm version issue, please install `pip install -U "tqdm>=4.60.0"` to fix it on your Windows machine. We'll update the requirements.

**Comment by Riazone** [comment]
Thanks. It works now.
