### ISSUE TITLE
[BUG]: When using fold_strategy='groupkfold' and a string to fold_groups setup fails

### ISSUE THREAD

**Issue by rantos9** [pycaret/pycaret#2644]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

This bug was observed in pycaret 3.0.0 rc2. When passing the array directly (fold_groups=dataset.Cut.loc[:4198]) it works with no problems.

### Reproducible Example

```python
from pycaret.regression import RegressionExperiment
from pycaret.datasets import get_data

dataset = get_data('diamond')

exp = RegressionExperiment()

exp.setup(
    data=dataset,
    fold_strategy='groupkfold',
    fold=5,
    fold_groups='Cut'
)
```

### Expected Behavior

setup to run with no problems

### Actual Results

```python-traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [23], in <cell line: 8>()
      4 dataset = get_data('diamond')
      6 exp = RegressionExperiment()
----> 8 exp.setup(
      9     data=dataset,
     10     fold_strategy='groupkfold',
     11     fold=5,
     12     fold_groups='Cut'
     13 )

File ~\anaconda3\envs\pycaret_30_rc2\lib\site-packages\pycaret\regression\oop.py:659, in RegressionExperiment.setup(self, data, data_func, target, train_size, test_data, ordinal_features, numeric_features, categorical_features, date_features, text_features, ignore_features, keep_features, preprocess, imputation_type, numeric_imputation, categorical_imputation, iterative_imputation_iters, numeric_iterative_imputer, categorical_iterative_imputer, text_features_method, max_encoding_ohe, encoding_method, polynomial_features, polynomial_degree, low_variance_threshold, remove_multicollinearity, multicollinearity_threshold, bin_numeric_features, remove_outliers, outliers_method, outliers_threshold, transformation, transformation_method, normalize, normalize_method, pca, pca_method, pca_components, feature_selection, feature_selection_method, feature_selection_estimator, n_features_to_select, transform_target, transform_target_method, custom_pipeline, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, verbose, memory, profile, profile_kwargs)
    651 self.target_param = self.data.columns[-1]
    653 self._prepare_train_test(
    654     train_size=train_size,
    655     test_data=test_data,
    656     data_split_stratify=data_split_stratify,
    657     data_split_shuffle=data_split_shuffle,
    658 )
--> 659 self._prepare_folds(
    660     fold_strategy=fold_strategy,
    661     fold=fold,
    662     fold_shuffle=fold_shuffle,
    663     fold_groups=fold_groups,
    664 )
    665 self._prepare_column_types(
    666     ordinal_features=ordinal_features,
    667     numeric_features=numeric_features,
   (...)
    672     keep_features=keep_features,
    673 )
    675 # Preprocessing ============================================ >>
    676 
    677 # Initialize empty pipeline

File ~\anaconda3\envs\pycaret_30_rc2\lib\site-packages\pycaret\internal\preprocess\preprocessor.py:251, in Preprocessor._prepare_folds(self, fold_strategy, fold, fold_shuffle, fold_groups)
    249 if isinstance(fold_groups, str):
    250     if fold_groups in self.X.columns:
--> 251         if pd.isna(fold_groups).any():
    252             raise ValueError(f"The 'fold_groups' column cannot contain NaNs.")
    253         else:

AttributeError: 'bool' object has no attribute 'any'
```

### Installed Versions

<details>
System:
    python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\Renan\anaconda3\envs\pycaret_30_rc2\python.exe
   machine: Windows-10-10.0.19044-SP0

PyCaret required dependencies:
                 pip: 21.2.2
          setuptools: 60.10.0
             pycaret: 3.0.0.rc2
             IPython: 8.3.0
          ipywidgets: 7.7.0
                tqdm: 4.62.3
               numpy: 1.21.6
              pandas: 1.4.2
              jinja2: 3.1.2
               scipy: 1.8.1
              joblib: 1.1.0
             sklearn: 1.1.1
                pyod: Installed but version unavailable
            imblearn: 0.9.1
   category_encoders: 2.5.0
            lightgbm: 3.3.2
               numba: 0.55.2
            requests: 2.27.1
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.8.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.11.4
               tbats: Installed but version unavailable
            pmdarima: 1.8.5
              psutil: 5.9.1
</details>

**Comment by Yard1** [comment]
Thanks, fixed in bb624762918b8d54d14d4c611a06cf0c08154ac6
