### ISSUE TITLE
[BUG]: tune_model gives me 2 false messages 

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#2645]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

tune_model gives me 2 false messages "Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one)."

1- its showing 2 messages instead 1.
2 - all messages is fake, because tuned_model have more accuracy than original model

### Reproducible Example

```python
import pandas as pd
import pycaret

from pycaret.datasets import get_data

dados = get_data('blood')

from pycaret.classification import *

s = setup(dados, target='Class', use_gpu=True)

best_model = compare_models()

best_model = tune_model(best_model, n_iter=100)
```

### Expected Behavior

no false messages

### Actual Results

```python-traceback
Fitting 10 folds for each of 100 candidates, totalling 1000 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).
```

### Installed Versions

<details>
pycaret: 3.0.0.rc2
</details>

**Comment by celestinoxp** [comment]
![pycaret_original_model](https://user-images.githubusercontent.com/41735311/172458759-3948f9a9-9005-4fb4-8937-5612e892b30b.png)
![pycaret_tuned_model](https://user-images.githubusercontent.com/41735311/172458774-55f3e2cb-0f52-43e1-bd70-e31d6b3aaf00.png)

**Comment by moezali1** [comment]
The message also gets printed when the performance of base model and tuned model is same which is wrong.

![image](https://user-images.githubusercontent.com/54699234/173044234-0a9dbca4-7d69-4d73-bf73-b1620336ec68.png)
