### ISSUE TITLE
how to apply GroupShuffleSplit

### ISSUE THREAD

**Issue by joseazdir** [pycaret/pycaret#2646]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://pycaret.gitbook.io/docs/get-started/release-notes#setup

### Documentation problem

For me there is no clear explanation on how to use GroupShuffleSplit.
I want to avoid to split data in Cross Validation regarding a column I use for grouping purposes (similar to time series but not exactly that). Grouping column is used to send same group rows either to train or test but never be splitted to both

reading sklearn documents the nearest method is 

```
gss = GroupShuffleSplit(n_splits=2, train_size=.7, random_state=42)
gss.split(df, df['target'], df['group'])
```

how to pass such 'gss.split' to cross validation or config?

### Suggested fix for documentation

I think some clarification on this would be great

**Comment by moezali1** [comment]
@Yard1 Is this possible?
