### ISSUE TITLE
UnboundLocalError: local variable 'visualizer' referenced before assignment

### ISSUE THREAD

**Issue by sumeshmr** [pycaret/pycaret#265]
Hello,

I was trying the nightly build version(pycaret-nightly).
I got the below error when I tried the **Validation Curve** in **evaluate_model**

![image](https://user-images.githubusercontent.com/24572078/86792957-a7f75e00-c073-11ea-85ae-5038c8bbbcce.png)

**Comment by pycaret** [comment]
@sumeshmr Thanks for reporting. Can you please share the complete code and dataset? I am unable to reproduce this error on juice dataset.

![image](https://user-images.githubusercontent.com/58118658/86822462-a882fb00-c059-11ea-9b32-de7f6c2e3a11.png)

**Comment by sumeshmr** [comment]
I can see that there is a typo in the variable name in regression.py. Variable defined as **viz** instead of **visualizer**.

![image](https://user-images.githubusercontent.com/24572078/86827106-44ccf200-c09a-11ea-8545-54e750dc1275.png)

**Comment by pycaret** [comment]
@sumeshmr Thank you so much. I have fixed this and it will pushed tonight into pycaret-nightly==0.18.

Appreciate your help.

![image](https://user-images.githubusercontent.com/58118658/86828106-c99b1a00-c060-11ea-87fa-5fa7c2015b22.png)
