### ISSUE TITLE
getting an error while tuning the model

### ISSUE THREAD

**Issue by sathishkumar369** [pycaret/pycaret#266]
Hi,
I installed pycaret nightly. while tuning the model I ran into an error. 

![Screenshot (261)](https://user-images.githubusercontent.com/40235632/86794392-19420b80-c08a-11ea-97da-d31ac13597b1.png)

**Comment by pycaret** [comment]
This is because in 2.0x tune_model accepts trained model only. See example below

dt = create_model('dt')
tuned_dt = tune_model(dt) ... not 'dt'
