### ISSUE TITLE
[ENH]: Parallelism of compare models

### ISSUE THREAD

**Issue by Duncan-Haywood** [pycaret/pycaret#2662]
### Describe the feature you want to add to this project

I would love the speed up of being to run all the models in parallel for the compare_models function. 

### Describe your proposed solution

^

**Comment by moezali1** [comment]
@Duncan-Haywood Right on time. We have added this functionality in our latest release.

See the notebook: https://colab.research.google.com/drive/13HKo1w6M5wFzBtddKYHT-5dB2TNeWQka?usp=sharing
