### ISSUE TITLE
[BUG]: 3.0.0rc2 classification setup, AttributeError: 'str' object has no attribute 'fit'

### ISSUE THREAD

**Issue by cwzkevin** [pycaret/pycaret#2665]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

Trying the 3.0.0rc2 and the setup on classification throw error.

### Reproducible Example

```python
from pycaret.datasets import get_data
data = get_data('income')

from pycaret.classification import *
s = setup(data, target = 'income >50K',
          max_encoding_ohe=2, encoding_method='WOEEncoder')
```

### Expected Behavior

Basically, it is trying to use WOEEncoder for any 3 or more levels of categorical variable.

### Actual Results

```python-traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-c11943f06ef7> in <module>()
      1 from pycaret.classification import *
----> 2 s = setup(data, target = 'income >50K', max_encoding_ohe=2, encoding_method='WOEEncoder')

4 frames
/usr/local/lib/python3.7/dist-packages/pycaret/internal/preprocess/transformers.py in fit(self, X, y, **fit_params)
    164 
    165         args = []
--> 166         transformer_params = signature(self.transformer.fit).parameters
    167         if "X" in transformer_params and X is not None:
    168             if self._include is None:

AttributeError: 'str' object has no attribute 'fit'
```

### Installed Versions

<details>
System:
    python: 3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0]
executable: /usr/bin/python3
   machine: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic

PyCaret required dependencies:
                 pip: 21.1.3
          setuptools: 57.4.0
             pycaret: 3.0.0.rc2
             IPython: 5.5.0
          ipywidgets: 7.7.0
                tqdm: 4.64.0
               numpy: 1.21.6
              pandas: 1.3.5
              jinja2: 2.11.3
               scipy: 1.7.3
              joblib: 1.1.0
             sklearn: 1.0.2
                pyod: Installed but version unavailable
            imblearn: 0.8.1
   category_encoders: 2.5.0
            lightgbm: 3.3.2
               numba: 0.55.2
            requests: 2.28.0
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.5.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.12.0
               tbats: Installed but version unavailable
            pmdarima: 1.8.5
              psutil: 5.9.1
</details>

**Comment by cwzkevin** [comment]
Okay, below works..

`
from pycaret.classification import *
from category_encoders.woe import WOEEncoder

s = setup(data, target = 'income >50K',
          max_encoding_ohe=2, encoding_method=WOEEncoder())
`

**Comment by Yard1** [comment]
This is the intended way to set this argument, yes. Closing as invalid.
