### ISSUE TITLE
[BUG]: 3.0.0rc2 classification load_config, ValueError: _CURRENT_EXPERIMENT global variable is not set. Please run setup() first.

### ISSUE THREAD

**Issue by cwzkevin** [pycaret/pycaret#2667]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

After setup() and save_config(), restarted the kernel/runtime. Can't load_config().

### Reproducible Example

```python
from pycaret.datasets import get_data
from pycaret.classification import *
from category_encoders.woe import WOEEncoder

data = get_data('income')
s = setup(data, target = 'income >50K', max_encoding_ohe=2, encoding_method=WOEEncoder())

save_config('./test_config.pkl.bz2')

### Now, restart the kernel/runtime
from pycaret.classification import *
load_config('./test_config.pkl.bz2')
```

### Expected Behavior

Expect to load the config file

### Actual Results

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-9f4b0adb7473> in <module>()
----> 1 load_config('./test_config.pkl.bz2')

/usr/local/lib/python3.7/dist-packages/pycaret/internal/utils.py in wrapper(*args, **kwargs)
    919             for name, message in global_names.items():
    920                 if globals_d[name] is None:
--> 921                     raise ValueError(message)
    922             return func(*args, **kwargs)
    923 

ValueError: _CURRENT_EXPERIMENT global variable is not set. Please run setup() first.
```

### Installed Versions

<details>
3.0.0.rc2
</details>

**Comment by moezali1** [comment]
@Yard1 This is bug. Can we fix this in rc3 please?

**Comment by cwzkevin** [comment]
At least for previous versions of pycaret, 2.x, 1.x. If you run setup() and save_config, then after restarting, you can load_config to get whatever was saved. Because sometimes, setup() could take an hour or more than a couple of hours to complete... Why it would be not the same at 3.x?

**Comment by Yard1** [comment]
We have done some internal changes that prevent this right now. We will look into changing that in the future

**Comment by ngupta23** [comment]
Per August 29th meeting, we will reevaluate it after 3.0.0rc4 release.

**Comment by ngupta23** [comment]
5th Nov 2022 meeting

@Yard1 is looking into this for rc5 release.

**Comment by fabiokfouri** [comment]
I'am using Pycaret into Kedro Pipeline [https://kedro.readthedocs.io/en/stable/introduction/introduction.html] and I need to run load_config because each node in Pipeline is like a new program session. Rebuild all setup for each node in pipeline appear not correct for me.
