### ISSUE TITLE
[INSTALL]: TimeSeriesExperiment Unavailable After pycaret-ts-alpha Installation

### ISSUE THREAD

**Issue by rreube3** [pycaret/pycaret#2669]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-glibc2.2.5

### Installation Method

pip install

### pycaret Version

3.0.0

### Python Version

3.8.13

### Description

Attempting to install pycaret-ts-alpha on CDSW JupyterLab. I am able to install the package and everything looks fine but I'm getting an error when attempting to import the TimeSeriesExperiment function. I reviewed the import instructions and my process seems normal.

![image](https://user-images.githubusercontent.com/93461855/174526603-ffdad2d1-24dc-4e0d-ac43-76b286e8e335.png)
![image](https://user-images.githubusercontent.com/93461855/174526848-3eebf15f-2ce8-497f-96c3-dc6f662ca222.png)

### Installation Logs

<details>

Collecting pycaret-ts-alpha
  Using cached pycaret_ts_alpha-3.0.0.dev1649017462-py3-none-any.whl (468 kB)
Collecting joblib~=1.0.1
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
Collecting imbalanced-learn>=0.8.1
  Using cached imbalanced_learn-0.9.1-py3-none-any.whl (199 kB)
Requirement already satisfied: ipython>=5.5.0 in /usr/local/lib/python3.8/site-packages (from pycaret-ts-alpha) (7.31.1)
Collecting scikit-learn>=1.0.2
  Downloading scikit_learn-1.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (31.2 MB)
     |████████████████████████████████| 31.2 MB 135.1 MB/s eta 0:00:01███████▏                    | 10.9 MB 1.5 MB/s eta 0:00:14
Collecting numba~=0.55.0
  Downloading numba-0.55.2-cp38-cp38-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.4 MB)
     |████████████████████████████████| 3.4 MB 121.5 MB/s eta 0:00:01
Collecting lightgbm>=3.0.0
  Using cached lightgbm-3.3.2-py3-none-manylinux1_x86_64.whl (2.0 MB)
Collecting category-encoders>=2.4.0
  Using cached category_encoders-2.5.0-py2.py3-none-any.whl (69 kB)
Collecting pandas<1.5.0,>=1.3.0
  Downloading pandas-1.4.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
     |████████████████████████████████| 11.7 MB 115.7 MB/s eta 0:00:01
Collecting scikit-plot>=0.3.7
  Using cached scikit_plot-0.3.7-py3-none-any.whl (33 kB)
Collecting sktime==0.10.1
  Using cached sktime-0.10.1-py3-none-any.whl (6.5 MB)
Collecting plotly>=5.0.0
  Using cached plotly-5.8.2-py2.py3-none-any.whl (15.2 MB)
Collecting statsmodels>=0.12.1
  Downloading statsmodels-0.13.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.9 MB)
     |████████████████████████████████| 9.9 MB 24.8 MB/s eta 0:00:01     |████████████▏                   | 3.8 MB 24.8 MB/s eta 0:00:01
Collecting yellowbrick>=1.4
  Using cached yellowbrick-1.4-py3-none-any.whl (274 kB)
Collecting scipy~=1.7.3
  Downloading scipy-1.7.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (39.3 MB)
     |████████████████████████████████| 39.3 MB 39.7 MB/s eta 0:00:01     |████████████▌                   | 15.3 MB 39.7 MB/s eta 0:00:01
Collecting pyod>=0.9.8
  Using cached pyod-1.0.1.tar.gz (120 kB)
Collecting pmdarima>=1.8.0
  Downloading pmdarima-1.8.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 96.4 MB/s eta 0:00:01
Collecting tbats>=1.1.0
  Using cached tbats-1.1.0-py3-none-any.whl (43 kB)
Collecting kaleido>=0.2.1
  Using cached kaleido-0.2.1-py2.py3-none-manylinux1_x86_64.whl (79.9 MB)
Collecting numpy~=1.21
  Downloading numpy-1.22.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.9 MB)
     |████████████████████████████████| 16.9 MB 95.6 MB/s eta 0:00:01
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.8/site-packages (from pycaret-ts-alpha) (3.3.4)
Collecting deprecated>=1.2.13
  Using cached Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting numpy~=1.21
  Downloading numpy-1.21.6-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     |████████████████████████████████| 15.7 MB 20.4 MB/s eta 0:00:01
Collecting patsy>=0.5.1
  Using cached patsy-0.5.2-py2.py3-none-any.whl (233 kB)
Collecting wrapt<2,>=1.10
  Downloading wrapt-1.14.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (81 kB)
     |████████████████████████████████| 81 kB 20.4 MB/s  eta 0:00:01
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.8/site-packages (from ipython>=5.5.0->pycaret-ts-alpha) (0.17.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.8/site-packages (from ipython>=5.5.0->pycaret-ts-alpha) (4.4.2)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.8/site-packages (from ipython>=5.5.0->pycaret-ts-alpha) (0.1.3)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.8/site-packages (from ipython>=5.5.0->pycaret-ts-alpha) (5.1.1)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.8/site-packages (from ipython>=5.5.0->pycaret-ts-alpha) (0.7.5)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.8/site-packages (from ipython>=5.5.0->pycaret-ts-alpha) (4.8.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.8/site-packages (from ipython>=5.5.0->pycaret-ts-alpha) (0.2.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.8/site-packages (from ipython>=5.5.0->pycaret-ts-alpha) (3.0.8)
Requirement already satisfied: pygments in /usr/local/lib/python3.8/site-packages (from ipython>=5.5.0->pycaret-ts-alpha) (2.8.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.8/site-packages (from ipython>=5.5.0->pycaret-ts-alpha) (56.0.0)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in /usr/local/lib/python3.8/site-packages (from jedi>=0.16->ipython>=5.5.0->pycaret-ts-alpha) (0.7.1)
Requirement already satisfied: wheel in /usr/local/lib/python3.8/site-packages (from lightgbm>=3.0.0->pycaret-ts-alpha) (0.37.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.8/site-packages (from matplotlib>=3.3.0->pycaret-ts-alpha) (9.0.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.8/site-packages (from matplotlib>=3.3.0->pycaret-ts-alpha) (2.8.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /usr/local/lib/python3.8/site-packages (from matplotlib>=3.3.0->pycaret-ts-alpha) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/site-packages (from matplotlib>=3.3.0->pycaret-ts-alpha) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/site-packages (from matplotlib>=3.3.0->pycaret-ts-alpha) (0.10.0)
Requirement already satisfied: six in /usr/local/lib/python3.8/site-packages (from cycler>=0.10->matplotlib>=3.3.0->pycaret-ts-alpha) (1.15.0)
Collecting llvmlite<0.39,>=0.38.0rc1
  Downloading llvmlite-0.38.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
     |████████████████████████████████| 34.5 MB 40.7 MB/s eta 0:00:01
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/site-packages (from pandas<1.5.0,>=1.3.0->pycaret-ts-alpha) (2021.1)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.8/site-packages (from pexpect>4.3->ipython>=5.5.0->pycaret-ts-alpha) (0.6.0)
Collecting tenacity>=6.2.0
  Using cached tenacity-8.0.1-py3-none-any.whl (24 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.8/site-packages (from pmdarima>=1.8.0->pycaret-ts-alpha) (1.26.6)
Collecting Cython!=0.29.18,>=0.29
  Downloading Cython-0.29.30-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 115.2 MB/s eta 0:00:01
Requirement already satisfied: wcwidth in /usr/local/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.5.0->pycaret-ts-alpha) (0.2.5)
Collecting packaging>=21.3
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Building wheels for collected packages: pyod
  Building wheel for pyod (setup.py) ... done
  Created wheel for pyod: filename=pyod-1.0.1-py3-none-any.whl size=147461 sha256=058633f95ebd5818bef0c6317a52129bba9f5ca175d4b6e04b4193c2c54150c0
  Stored in directory: /home/cdsw/.cache/pip/wheels/b1/cc/4c/627210c240d68c4932857dd69725a40032b429dd967323314a
Successfully built pyod
Installing collected packages: numpy, threadpoolctl, scipy, patsy, pandas, packaging, joblib, wrapt, statsmodels, scikit-learn, llvmlite, Cython, tenacity, pmdarima, numba, deprecated, yellowbrick, tbats, sktime, scikit-plot, pyod, plotly, lightgbm, kaleido, imbalanced-learn, category-encoders, pycaret-ts-alpha
Successfully installed Cython-0.29.30 category-encoders-2.5.0 deprecated-1.2.13 imbalanced-learn-0.9.1 joblib-1.0.1 kaleido-0.2.1 lightgbm-3.3.2 llvmlite-0.38.1 numba-0.55.2 numpy-1.21.6 packaging-21.3 pandas-1.4.2 patsy-0.5.2 plotly-5.8.2 pmdarima-1.8.5 pycaret-ts-alpha-3.0.0.dev1649017462 pyod-1.0.1 scikit-learn-1.1.1 scikit-plot-0.3.7 scipy-1.7.3 sktime-0.10.1 statsmodels-0.13.2 tbats-1.1.0 tenacity-8.0.1 threadpoolctl-3.1.0 wrapt-1.14.1 yellowbrick-1.4

</details>

**Comment by ngupta23** [comment]
Hi @rreube3, We recently released pycaret 3.0.0rc which integrates time-series with other modules. Please use that going forward. pycaret-ts-alpha will not be updated anymore.

Also, the API interface is different. Please use the following going forward.

```python
from pycaret.time_series import TSForecastingExperiment
```
