### ISSUE TITLE
can't able to see the parameters inside the model

### ISSUE THREAD

**Issue by sathishkumar369** [pycaret/pycaret#267]
Hi team!
I installed pycaret-nightly today..
when I use print for model,it's showing the parameters. how could I customize those parameters without seeing.
this will bring into a huge problem while we work with clustering data, because parameters plays a vital role in every ML model.
even in version 1, there is no option for controlling parameters. but here in nigtly it's not showing even parameters.

![Screenshot (262)](https://user-images.githubusercontent.com/40235632/86795941-b3568380-c08b-11ea-83ef-2013e2336f04.png)

**Comment by pycaret** [comment]
@sathishkumar369 This is because the default behaviour in sklearn 0.23 changed. If you want to see all parameters, you can check that by get_params() method. See example below:

lr = create_model('lr')
lr.get_params()

Please close the issue if this answers your question.

**Comment by sathishkumar369** [comment]
Hi Moez!
Please create some notebooks in github and upload it for public that all the changes in this nightly or 2.0.
which makes it easier to practice the things. 
looking forward to see the changes in 2.0 and also I believe you guys will fix all the request and suggestions that created in github.
tons of Thanks to the pycaret team and Moez for creating this wonderful library to the data science community.
