### ISSUE TITLE
[ENH]: tune_model is too slow

### ISSUE THREAD

**Issue by longxiaozi** [pycaret/pycaret#2670]
### Describe the feature you want to add to this project

tune_model is too slow

### Describe your proposed solution

I have a train data about 2million rows and 6columns.  When using regression create_model('rf'), it takes about 40 minutes.  When using regression tune_model(rf), it takes a lot of time , more 10 hours, and never finish.  I also used the params, it takes more than 100 hours, and never finish.
cpu: E5-2620 v3 *2
memery: 100G+
gpu: 3080

code:
# coding=utf-8
import pandas as pd
import numpy as np

shuju = r'E:\caret\jk\train.txt'
dataset = pd.read_csv(shuju,sep='\s+',header=None,names=['col1','col2','col3','col4','col5','col6'])

data = dataset.sample(frac=0.9, random_state=786)
data_unseen = dataset.drop(data.index)

data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

from pycaret.regression import *
exp_reg101 = setup(data = data, target = 'col6', use_gpu = True,session_id=123,normalize = True,numeric_features=['col1','col2','col3','col4','col5'])

rf = create_model('rf')
model_rf =pull()
print(model_rf)
model_rf.to_csv('model_rf.csv')

tuned_rf = tune_model(rf)
t_rf =pull()
print(t_rf)
t_rf.to_csv('t_rf.csv')

**Comment by moezali1** [comment]
@longxiaozi For tuning, do you have access to cluster? if yes, you can use ray cluster with `search_library = 'tune-sklearn'` in the `tune_model` function.

https://pycaret.gitbook.io/docs/get-started/functions/optimize#changing-the-search-algorithm

**Comment by longxiaozi** [comment]
> @longxiaozi For tuning, do you have access to cluster? if yes, you can use ray cluster with `search_library = 'tune-sklearn'` in the `tune_model` function.
> 
> https://pycaret.gitbook.io/docs/get-started/functions/optimize#changing-the-search-algorithm

change code: tuned_rf = tune_model(rf,search_library = 'tune-sklearn')

3 hours later, I don't know how much time it will take, but I still haven't finished it yet.

== Status ==
Current time: 2022-06-22 12:35:20 (running for 03:10:59.85)
Memory usage on this node: 30.0/159.9 GiB
Using FIFO scheduling algorithm.
Resources requested: 1.0/24 CPUs, 1.0/1 GPUs, 0.0/83.74 GiB heap, 0.0/39.88 GiB objects
Result logdir: C:\Users\xl\ray_results\_Trainable_2022-06-22_09-24-20
Number of trials: 10/10 (9 PENDING, 1 RUNNING)

**Comment by Yard1** [comment]
This is because the default tuning grid contains parameters and values that are not intended to be used with large data. Consider passing your own tuning grid.

**Comment by moezali1** [comment]
@longxiaozi Have you tried with the custom tuning grid as suggested by @Yard1 ?

**Comment by longxiaozi** [comment]
> @longxiaozi Have you tried with the custom tuning grid as suggested by @Yard1 ?

I use the default tune, and the program still hasn't finished for 3 hours. I don't know whether the grid is set correctly. I have set parameters, and the program still hasn't finished for 100 hours.
code: rf = create_model('rf',n_estimators=200,max_depth=50,min_samples_leaf=2,min_samples_split=2,max_features=2)

**Comment by Yard1** [comment]
Well, the default grid includes large values for n_estimators, max_depth and other parameters that can exponentially increase the training time. You should define your own grid with narrower ranges
