### ISSUE TITLE
[BUG]: Clustering plot_model does not work in Google Colab

### ISSUE THREAD

**Issue by shapatel13** [pycaret/pycaret#2673]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

Hello, I am using the newest pycaret version above.  My plots for clustering are not showing up in google colab.  

### Reproducible Example

```python
# create a mode
kmeans = create_model('kmeans')
plot_model(kmeans)
```

### Expected Behavior

plot_model(kmeans)

### Actual Results

```python-traceback
It is blank.
```

### Installed Versions

System:
    python: 3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0]
executable: /usr/bin/python3
   machine: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic

PyCaret required dependencies:
                 pip: 21.1.3
          setuptools: 57.4.0
             pycaret: 3.0.0.rc2
             IPython: 5.5.0
          ipywidgets: 7.7.0
                tqdm: 4.64.0
               numpy: 1.21.6
              pandas: 1.3.5
              jinja2: 2.11.3
               scipy: 1.7.3
              joblib: 1.1.0
             sklearn: 1.0.2
                pyod: Installed but version unavailable
            imblearn: 0.8.1
   category_encoders: 2.5.0
            lightgbm: 3.3.2
               numba: 0.55.2
            requests: 2.28.0
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.5.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.12.0
               tbats: Installed but version unavailable
            pmdarima: 1.8.5
              psutil: 5.9.1

**Comment by Yard1** [comment]
Cannot reproduce, can you share the notebook? Make sure that you have restarted the runtime when prompted.

**Comment by ngupta23** [comment]
Based on meeting 8th August, @moezali1 will try to reproduce this.

**Comment by moezali1** [comment]
I have tried both with 2.3.10 and 3.X and plot displays fine.

2.3.10 Colab Notebook: https://colab.research.google.com/drive/1nYhuoluCbYNm0Afjmyc6xRqybzbZrLk-?usp=sharing
3.X Colab Notebook: https://colab.research.google.com/drive/1xlJVr8mklXwTnUlCwti6LfBKA6SPjLzW?usp=sharing
