### ISSUE TITLE
[BUG]: TypeError: setup() got an unexpected keyword argument 'feature_interaction'

### ISSUE THREAD

**Issue by yairVanti** [pycaret/pycaret#2675]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

latest pycaret version is missing parameters that are included in documentation in [https://pycaret.readthedocs.io/en/latest/api/classification.html](url)

the message is : 
TypeError: setup() got an unexpected keyword argument 'feature_interaction'

### Reproducible Example

```python
from pycaret.classification import * 
import pandas as pd
exp_reg101 = setup(data = X_train, target = 'Kpi', test_data=X_test,session_id = 123,feature_interaction = True)
```

### Expected Behavior

setup to be completed correctly

### Actual Results

```python-traceback
TypeError: setup() got an unexpected keyword argument 'feature_interaction'
```

### Installed Versions

<details>
'3.0.0.rc2'
</details>

**Comment by ngupta23** [comment]
It looks like this argument was removed from 3.0.0rc release. Can you use `polynomial_features` instead which does something similar and more?

@tvdboom @Yard1 Do you have any comments about this argument removal in 3.0.0rc?

**Comment by tvdboom** [comment]
This argument was replaced with `polynomial_features` because it didn't had a direct `sklearn` implementation. @yairVanti please refer to the docstrings to see the parameters for 3.0.0rc until the official docs are updated
