### ISSUE TITLE
save_experiment failed in pycaret-nightly

### ISSUE THREAD

**Issue by sumeshmr** [pycaret/pycaret#268]
Hello,

I got the below error when saving the experiment while trying pycaret-nightly.

![image](https://user-images.githubusercontent.com/24572078/86797095-f27ad980-c077-11ea-82f0-f44c60245c70.png)

**Comment by pycaret** [comment]
@sumeshmr Thanks for reporting. We are going to remove save_experiment / load_experiment as 2.0 will support MLFlow backend for experiment logging. 

If you would like to see how that works you can pass logging = True in setup() and then at end of your notebook run this code:

!mlflow ui 

You should then be able to see a server on localhost:5000 in your browser. 

Let me know how that goes.

**Comment by sumeshmr** [comment]
The mlflow ui looks excellent. Looking forward to this.

**Comment by pycaret** [comment]
@sumeshmr Thanks.
