### ISSUE TITLE
[BUG]: Custom metric is not working in clustering module

### ISSUE THREAD

**Issue by rjpuzniakADASTRA** [pycaret/pycaret#2689]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [x] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

As I gather from documentation of `pycaret.clustering.create_model`, the custom metric provided by `add_metric` function should be also included in the model creation process and logged along the default metrics. This is however not the case - even though during running `create_model` job the names of custom metrics are listed in the df header, as soon as the job finished only default metrics are listed. The custom metrics are neither displayed nor stored.

### Reproducible Example

```python
from pycaret.clustering import *
import pandas as pd  
 
# Generation of dummy data
data = {'X': [0, 0.1, 0.9, 1], 'Y': [0.1, 0.2, 1.0, 0.8]}  
df = pd.DataFrame(data)  

# Setup
setup(df, silent=True);

# Custom metric
def dummy_metric(y, y_pred):
    return 1

# add metric to PyCaret
add_metric('dummy_metric', 'dummy_metric', dummy_metric)

# Training the model
test_model = create_model('kmeans',num_clusters=2)

pull() # not listing the dummy_metric
```

### Expected Behavior

The added custom metric (`dummy_metric`) should be stored among the default metric, so it can be displayed and logged properly. 

### Actual Results

Unlike the default metrics, the custom metric (`dummy_metric`) is not reported, nor stored in the logs.

### Installed Versions

<details>
'2.3.10'
</details>

**Comment by moezali1** [comment]
This problem has been solved in rc4.

```
pip install --pre pycaret
```

![image](https://user-images.githubusercontent.com/54699234/202457101-8543bb47-8dc6-41ce-a2b6-9e9bb6946da0.png)
