### ISSUE TITLE
[ENH]: Possibility of changing the order of the pipeline along with custom_pipeline in setup.

### ISSUE THREAD

**Issue by jnsflt** [pycaret/pycaret#2693]
### Describe the feature you want to add to this project

I have a custom_pipeline with some feature engineering steps in my model. Although, I also want to use PyCaret's built in "feature_selection" step. However, I don't want feature_selection to happen before my custom feature engineering steps, since it can remove features that would not be removed if feature engineering would be done first. 

Therefore, a feature that can be added is to have the possibility to change the order of the steps in the pipeline yourself. 

The image below shows my pipeline, where _Apply_Rare_Encoding_ is defined in the custom_pipeline. One thing to note is that _Apply_Rare_Encoding_  is a feature engineering step which changes some values.

![image](https://user-images.githubusercontent.com/107557528/176840280-14b47dda-92f9-40c9-a137-ff7c3d493a4c.png)

As you can see, the feature_selection happens before Apply_Rare_Encoding, which is not wanted.

### Describe your proposed solution

The most straight forward solution would be to have a boolean parameter in the setup-function: _feature_selection_after_custom_pipeline_ (or maybe a shorter name), which you set to True if you want the custom_pipeline to come before feature_selection.

Although, a more flexible way could be to make the user specify exactly in which order they want all steps to occur. A solution for this could be to have a parameter in the setup-function: `pipeline_order: array, default = None`

If the parameter is None, then standard pipeline order is used (as now). 

 For example you can use the names of the steps to define the array, where the names correspond to what we can see in the above image.
`order = [numerical_imputer, categorical_imputer, rest_encoding, remove_multicollinearity, balance, Apply_Rare_Encoding, feature_selection]`

and then

`exp.setup(..., pipeline_order = order, ... )`

To use this function, one need to first create their model and look at their pipeline and re-order it according to their names.

This was just my idea on how to achieve this functionality. I'm open to any other suggestions as well.

### Describe alternatives you've considered, if relevant

An additional solution could be to have the order in the setup call correspond to which order you want the setup to happen. For example
`exp.setup(...,  fix_imbalance=True, remove_multicollinearity=True,custom_pipeline=custome_pipeline, feature_selection_True, ...)` would give the order [fix_imbalance, remove_multicollinearity, custom_pipeline, feature_selection].

**Comment by tvdboom** [comment]
@jnsflt Thanks for the ideas. The alternative idea is not feasible since Python doesn't take parameter order into account. I like the idea of being able to specify the position exactly but having to state all the names is long and tedious work. How about making it a `int` parameter specifying the position of the custom steps in the pipeline? It could default to -1 to append it last, but you could insert 0 to put it first or any other desired position.

**Comment by jnsflt** [comment]
Do you mean as a new parameter in setup? So for example `exp.setup(..., custom_pipeline=custom_pipeline, custom_position=2, ...)`. Making the custom pipeline happen after the first and the second step in the pipeline?

Yes that may be more efficient and would solve my problem. But could it be that you want 2 of your custom pipeline steps to run before feature_selection and a third step that run last? Although, that might be a very specific example and not so likely to occur.

**Comment by tvdboom** [comment]
That would make it a bit too complicated imo. I'll implement first the `custom_position` option and if a user needs the extra capabilities, he can always open a new issue on GitHub

**Comment by jnsflt** [comment]
Understandable. Thank you!

**Comment by tvdboom** [comment]
This issue will be solved when https://github.com/pycaret/pycaret/pull/2722 merges
