### ISSUE TITLE
[DOC]: Update documentation for pycaret 3.0.0

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#2695]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://pycaret.readthedocs.io/en/latest/index.html

### Documentation problem

- [x] Currently points to 2.3.10 documentation. Needs to be updated for 3.0.0
- [x] Remove the `time_series` branch documentation since it is now merged with main pycaret.
- [x] Make `stable` as default page
- [ ] Add OOP docs to readthedoc page (@Yard1)

### Suggested fix for documentation

See above

**Comment by moezali1** [comment]
I have now made `stable` version as default.

![image](https://user-images.githubusercontent.com/54699234/185801295-28834145-42f2-40e1-96e6-d688af9d0eee.png)

**Comment by moezali1** [comment]
@ngupta23 Seems like all points are addressed. can we close this?
