### ISSUE TITLE
Change Fold Strategy

### ISSUE THREAD

**Issue by nyk510** [pycaret/pycaret#27]
In pycaret, the number of k-folds can be changed by using fold as an argument. 
However, the fold strategy is fixed as random split (i.e. KFold), cannot be changed by the user. For general problems, there are many cases where you want to use Group KFold or TimeSplitFold.

So I propose that allow the user to change the fold strategy by allowing them to pass an instance that inherits _BaseFold https://github.com/scikit-learn/scikit-learn/blob/95d4f0841d57e8b5f6b2a570312e9d832e69debc/sklearn/model_selection/_split.py#L269. 

It will be a fairly widespread change, but I think the change will make the project be more wonderful

Best Regards.

**Comment by pycaret** [comment]
Thanks. As of 1.0.0. Stratified K-fold is available for classification and Kfold for regression. I will mark this as an enhancements for future release to include Group Kfold, TimeSplitFold.

Somebody also asked for LWO (just writing it here so we do remember this when we are working on this).

**Comment by pycaret** [comment]
@nyk510 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
