### ISSUE TITLE
Topic Modeling - Deployment and Predict Functionality

### ISSUE THREAD

**Issue by Harish12137** [pycaret/pycaret#270]
Hi Team,

I am not able to use predict_model on unseen data to get the topics, which is available in other models but not functioning for topic modeling in Pycaret. I might be wrong but not sure why is this not available for topic modeling.

<img width="357" alt="Untitled picture" src="https://user-images.githubusercontent.com/58198071/86867497-86888780-c0f0-11ea-8551-eef42f7f6195.png">

If so, how do I add custom stop words in PowerBI, because get_topics doesn't have a custom stop-words parameter.
If I was able to use predict_model with the already built model, it would be helpful.

Also the save_model/load_model for the topic modeling doesn't save/load all the data cleaning or pre-processing steps done.

Thank you for this wonderful library, which helps people like me who is not from programming back ground. Its just, I am facing few difficulties here, please suggest.

Regards,
Harish

**Comment by sathishkumar369** [comment]
@Harish12137  It's better you read what's actually a topic modelling. we can't use predict on unsupervised learning algorithms.

**Comment by sathishkumar369** [comment]
@Harish12137  It's better you read what's actually a topic modelling is. we can't use predict on unsupervised learning algorithms.

**Comment by moezali1** [comment]
We are no more supporting the `nlp` and `arules` module in PyCaret due to lack to resources. Closing the issue now.
