### ISSUE TITLE
[ENH]: Support `verbose` in `.choose_better()`

### ISSUE THREAD

**Issue by chrimaho** [pycaret/pycaret#2703]
### Describe the feature you want to add to this project

This line is causing issues when I run experiments:

https://github.com/pycaret/pycaret/blob/98cbf9451f1c20cc701b406f0b9b72d21f4ec2a6/pycaret/internal/pycaret_experiment/supervised_experiment.py#L208

That's because there is no option within the method parameters to declare `verbose`:

https://github.com/pycaret/pycaret/blob/98cbf9451f1c20cc701b406f0b9b72d21f4ec2a6/pycaret/internal/pycaret_experiment/supervised_experiment.py#L133-L141

Neither is there in the class parameters:

https://github.com/pycaret/pycaret/blob/98cbf9451f1c20cc701b406f0b9b72d21f4ec2a6/pycaret/internal/pycaret_experiment/supervised_experiment.py#L68

### Describe your proposed solution

Suggestion:

1. Add a new parameter `verbose` to the `_choose_better()` method.
    - Original: https://github.com/pycaret/pycaret/blob/98cbf9451f1c20cc701b406f0b9b72d21f4ec2a6/pycaret/internal/pycaret_experiment/supervised_experiment.py#L133-L141
    - Proposed:
        ```python
        def _choose_better(
            self,
            models_and_results: list,
            compare_dimension: str,
            fold: int,
            fit_kwargs: Optional[dict] = None,
            groups: Optional[Union[str, Any]] = None,
            display: Optional[CommonDisplay] = None,
            verbose: bool = True,    #<-- Add this
        ):
            ...
        ```

2. Add a conditional statement to this print line.
    - Original: https://github.com/pycaret/pycaret/blob/98cbf9451f1c20cc701b406f0b9b72d21f4ec2a6/pycaret/internal/pycaret_experiment/supervised_experiment.py#L208
    - Proposed:
        ```python
                if verbose:    #<-- Add this
                    print(msg)
        ```

3. For those functions that call this method, add the `verbose` parameter.
    - Original: https://github.com/pycaret/pycaret/blob/f964963c41c56143bd2215c9689af54839bce219/pycaret/time_series/forecasting/oop.py#L2463-L2470
    - Proposed:
        ```python
        if choose_better:
            best_model = self._choose_better(
                [estimator, (best_model, model_results)],
                compare_dimension,
                fold,
                fit_kwargs=fit_kwargs,
                display=display,
                verbose=verbose,    #<-- Add this
            )
        ```
    - Noting that:
        1. The `tune_model()` method already contains the `verbose` parameter.
        2. https://github.com/pycaret/pycaret/blob/f964963c41c56143bd2215c9689af54839bce219/pycaret/time_series/forecasting/oop.py#L1944-L1961
        3. It's simply not yet being parsed through to the lower-level `_choose_better()` method.

**Comment by Yard1** [comment]
Hey @chrimaho, thanks for your suggestion. Would you be interested in submitting a PR yourself? Happy to give you any guidance you may require.

**Comment by chrimaho** [comment]
Hi @Yard1, yup sure thing. Leave it with me 👍

**Comment by chrimaho** [comment]
Thanks! 😊
