### ISSUE TITLE
[BUG]: Unable to use GPU for clustering 

### ISSUE THREAD

**Issue by GDGauravDutta** [pycaret/pycaret#2710]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

!pip install --pre pycaret
from pycaret.clustering import *
exp_clu101 = setup(train, normalize = True, normalize_method='robust',
                   ignore_features = ['id'],
                   use_gpu=True)

Error : 

TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_34/1281045404.py in <module>
      1 exp_clu101 = setup(train, normalize = True, normalize_method='robust',
      2                    ignore_features = ['id'],
----> 3                    use_gpu=True)

/opt/conda/lib/python3.7/site-packages/pycaret/clustering/functional.py in setup(data, ordinal_features, numeric_features, categorical_features, date_features, text_features, ignore_features, keep_features, preprocess, imputation_type, numeric_imputation, categorical_imputation, text_features_method, max_encoding_ohe, encoding_method, polynomial_features, polynomial_degree, low_variance_threshold, remove_multicollinearity, multicollinearity_threshold, bin_numeric_features, remove_outliers, outliers_method, outliers_threshold, transformation, transformation_method, normalize, normalize_method, pca, pca_method, pca_components, custom_pipeline, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, verbose, memory, profile, profile_kwargs)
    426         memory=memory,
    427         profile=profile,
--> 428         profile_kwargs=profile_kwargs,
    429     )
    430 

/opt/conda/lib/python3.7/site-packages/pycaret/internal/pycaret_experiment/unsupervised_experiment.py in setup(self, data, ordinal_features, numeric_features, categorical_features, date_features, text_features, ignore_features, keep_features, preprocess, imputation_type, numeric_imputation, categorical_imputation, text_features_method, max_encoding_ohe, encoding_method, polynomial_features, polynomial_degree, low_variance_threshold, remove_multicollinearity, multicollinearity_threshold, bin_numeric_features, remove_outliers, outliers_method, outliers_threshold, transformation, transformation_method, normalize, normalize_method, pca, pca_method, pca_components, custom_pipeline, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, verbose, memory, profile, profile_kwargs)
    457             experiment_name=experiment_name,
    458             memory=memory,
--> 459             verbose=verbose,
    460         )
    461 

/opt/conda/lib/python3.7/site-packages/pycaret/internal/pycaret_experiment/tabular_experiment.py in _initialize_setup(self, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, memory, verbose)
    347                 cuml_version = (int(cuml_version[0]), int(cuml_version[1]))
    348 
--> 349             if cuml_version is None or not version.parse(cuml_version) >= version.parse(
    350                 "0.15"
    351             ):

/opt/conda/lib/python3.7/site-packages/packaging/version.py in parse(version)
     47     """
     48     try:
---> 49         return Version(version)
     50     except InvalidVersion:
     51         return LegacyVersion(version)

/opt/conda/lib/python3.7/site-packages/packaging/version.py in __init__(self, version)
    262 
    263         # Validate the version and parse it into pieces
--> 264         match = self._regex.search(version)
    265         if not match:
    266             raise InvalidVersion(f"Invalid version: '{version}'")

TypeError: expected string or bytes-like object

### Reproducible Example

```python
!pip install --pre pycaret
from pycaret.clustering import *
exp_clu101 = setup(train, normalize = True, normalize_method='robust',
                   ignore_features = ['id'],
                   use_gpu=True)
```

### Expected Behavior

Use should able to train in GPU

### Actual Results

```python-traceback
no Issue while run
```

### Installed Versions

<details>
System:
    python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53)  [GCC 9.4.0]
executable: /opt/conda/bin/python
   machine: Linux-5.10.123+-x86_64-with-debian-bullseye-sid

PyCaret required dependencies:
                 pip: 22.1.1
          setuptools: 59.8.0
             pycaret: 3.0.0.rc2
             IPython: 7.33.0
          ipywidgets: 7.7.0
                tqdm: 4.64.0
               numpy: 1.21.6
              pandas: 1.3.5
              jinja2: 3.1.2
               scipy: 1.7.3
              joblib: 1.1.0
             sklearn: 1.0.2
                pyod: Installed but version unavailable
            imblearn: 0.9.0
   category_encoders: 2.5.0
            lightgbm: 3.3.2
               numba: 0.55.1
            requests: 2.27.1
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.8.2
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.12.1
               tbats: Installed but version unavailable
            pmdarima: 1.8.5
              psutil: 5.9.1
</details>

**Comment by Yard1** [comment]
We do not have any GPU support for clustering or anomaly detection right now.

**Comment by GDGauravDutta** [comment]
Documentation says differently
![Screenshot_20220712-172934.jpg](https://user-images.githubusercontent.com/62606251/178485099-99138a1e-288d-43bc-bd8b-530f2554692b.jpg)

**Comment by Yard1** [comment]
I'll double check, thanks
