### ISSUE TITLE
[BUG]: Pycaret 3 "group_features" not available in ClassificationExperiment

### ISSUE THREAD

**Issue by chicolucio** [pycaret/pycaret#2711]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

I am trying to learn the new OOP adapting the tutorials available on https://pycaret.gitbook.io/docs/get-started/tutorials to Pycaret 3. I got a `TypeError: setup() got an unexpected keyword argument 'group_features'`.

### Reproducible Example

The intermediate binary classification notebook has the following example:

```python
from pycaret.datasets import get_data
from pycaret.classification import *
dataset = get_data('credit', profile=True)
data = dataset.sample(frac=0.95, random_state=786)
data_unseen = dataset.drop(data.index)

data.reset_index(inplace=True, drop=True)
data_unseen.reset_index(inplace=True, drop=True)

exp_clf102 = setup(data = data, target = 'default', session_id=123,
                  normalize = True, 
                  transformation = True, 
                  ignore_low_variance = True,
                  remove_multicollinearity = True, multicollinearity_threshold = 0.95,
                  bin_numeric_features = ['LIMIT_BAL', 'AGE'],
                  group_features = [['BILL_AMT1', 'BILL_AMT2','BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6'],
                                   ['PAY_AMT1','PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6']],
                  log_experiment = True, experiment_name = 'credit1')
```

I tried to adapt the example to Pycaret 3 as follows:

```python
experiment01 = ClassificationExperiment()
experiment01.setup(data=sample, target='default', session_id=42,
                   use_gpu=False, html=False,
                   normalize=True,
                   transformation=True,
                   low_variance_threshold=0.05,
                   remove_multicollinearity=True,
                   multicollinearity_threshold=0.95,
                   bin_numeric_features=['LIMIT_BAL', 'AGE'],
                   group_features=[
                       ['BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4',
                        'BILL_AMT5', 'BILL_AMT6'],
                       ['PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4',
                        'PAY_AMT5', 'PAY_AMT6']
                   ],
                   log_experiment=True,
                   experiment_name='credit1')
```

As can be seen, I have already changed `ignore_low_variance = True` to `low_variance_threshold=0.05` since there is no more `ignore_low_variance`. However, I can't find an alternative to `group_features`

### Expected Behavior

The setup table with all the parameters.

### Actual Results

```python-traceback
TypeError: setup() got an unexpected keyword argument 'group_features'
```

### Installed Versions

<details>
System:
    python: 3.9.12 (main, Jun  1 2022, 11:38:51)  [GCC 7.5.0]
executable: /opt/anaconda/envs/pycaret/bin/python
   machine: Linux-5.4.0-121-generic-x86_64-with-glibc2.31

PyCaret required dependencies:
                 pip: 21.2.4
          setuptools: 60.10.0
             pycaret: 3.0.0.rc2
             IPython: 8.3.0
          ipywidgets: 8.0.0rc0
                tqdm: 4.64.0
               numpy: 1.22.3
              pandas: 1.4.2
              jinja2: 3.1.2
               scipy: 1.8.1
              joblib: 1.1.0
             sklearn: 1.1.1
                pyod: Installed but version unavailable
            imblearn: 0.9.1
   category_encoders: 2.5.0
            lightgbm: 3.3.2
               numba: 0.55.2
            requests: 2.28.1
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.9.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.12.1
               tbats: Installed but version unavailable
            pmdarima: 1.8.5
              psutil: 5.9.1
</details>

**Comment by tvdboom** [comment]
The `group_features` transformation was not yet available in v3.0. I have added it to #2722. It will be available with next release.
