### ISSUE TITLE
[BUG]: `get_outliers` and `get_clusters` functions missing at PyCaret 3.0-rc

### ISSUE THREAD

**Issue by PabloJMoreno** [pycaret/pycaret#2712]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

After doing some testing on PyCaret 3.0-rc, the functions `get_outliers` and `get_clusters` are missing from the `anomaly` and `clustering` modules respectively.

Thank you

### Reproducible Example

```python
from pycaret.clustering import *
dataset = get_clusters(data=dataset, model='kmeans')
```

### Expected Behavior

produce pandas dataframe with cluster column

### Actual Results

```python-traceback
NameError: name 'get_outliers' is not defined
```

### Installed Versions

<details>
PyCaret 3.0-rc
</details>

**Comment by Yard1** [comment]
This is intended. `get_clusters` has been deprecated and is superseded by running `setup` and then `create_model`.
