### ISSUE TITLE
XGboost throwing an error:  `ValueError: feature_names may not contain [, ] or <`

### ISSUE THREAD

**Issue by rahul-raoniar** [pycaret/pycaret#272]
In Pycaret compare_model( ) throwing an error while training a xgboost while other models showing no such error.

![image](https://user-images.githubusercontent.com/26122609/86998815-cc1b8200-c1ce-11ea-84fd-9506d58994c9.png)

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-94-9ff5ccfe3077> in <module>
----> 1 compare_models()

D:\Software_Installation\envs\datascience\lib\site-packages\pycaret\classification.py in compare_models(blacklist, fold, round, sort, turbo)
   3434             if hasattr(model, 'predict_proba'):
   3435 
-> 3436                 model.fit(Xtrain,ytrain)
   3437                 pred_prob = model.predict_proba(Xtest)
   3438                 pred_prob = pred_prob[:,1]

D:\Software_Installation\envs\datascience\lib\site-packages\xgboost\sklearn.py in fit(self, X, y, sample_weight, eval_set, eval_metric, early_stopping_rounds, verbose, xgb_model, sample_weight_eval_set, callbacks)
    724         else:
    725             train_dmatrix = DMatrix(X, label=training_labels,
--> 726                                     missing=self.missing, nthread=self.n_jobs)
    727 
    728         self._Booster = train(xgb_options, train_dmatrix, self.get_num_boosting_rounds(),

D:\Software_Installation\envs\datascience\lib\site-packages\xgboost\core.py in __init__(self, data, label, missing, weight, silent, feature_names, feature_types, nthread)
    424                 self.set_weight(weight)
    425 
--> 426         self.feature_names = feature_names
    427         self.feature_types = feature_types
    428 

D:\Software_Installation\envs\datascience\lib\site-packages\xgboost\core.py in feature_names(self, feature_names)
    868                        not any(x in f for x in set(('[', ']', '<')))
    869                        for f in feature_names):
--> 870                 raise ValueError('feature_names may not contain [, ] or <')
    871         else:
    872             # reset feature_types also

ValueError: feature_names may not contain [, ] or <`

**When printing column names using `dataset.columns` the following is the printout which does not contain `[, ] or <` in the column names.**

`Index(['location', 'directionmod', 'gender', 'age', 'peoplewait', 'peoplejoin',
       'crosssame', 'crossopposite', 'carrying', 'startcrossatmarked',
       'groupsize', 'straightoblique', 'normalhurried', 'crosswalkviolation',
       'traffic', 'speed', 'cycletimecat', 'greentimecat', 'redtimecat',
       'waitingtimecat', 'sigdep'],
      dtype='object')`

I don't understand if column names have no such symbols then why this throwing an error.

**Comment by pycaret** [comment]
@rahul-raoniar Check categorical variables. , or < must be appearing in one of the values and when one hot encoding is performed column name inherits the value. You are checking column names of original dataset, thats why you cant see , or <. 

Let me know if this helps.

**Comment by rahul-raoniar** [comment]
Yes, you are right. In my data, some variable has these symbols. My age variable has <18 and >60 categories. Thus, during one-hot encoding, this generates column names with these symbols, which created the problem with GBM. 

I re-encoded my categorical variables and now XGBoost working fine.

Thank you for your help.

**Comment by pycaret** [comment]
Thanks @rahul-raoniar 

Closing the issue now.
