### ISSUE TITLE
[INSTALL]: Installing time series module

### ISSUE THREAD

**Issue by psxpa3** [pycaret/pycaret#2720]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

macOS-10.16-x86_64-i386-64bit

### Installation Method

conda install

### pycaret Version

3.0.0

### Python Version

3.8.13

### Description

Hello,  I have one entire day in installing this library. Through this command {!pip install pycaret-ts-alpha}, I get {3.0.0.dev1649017462} version of Pycaret, however, with every version of sklearn (scikit-learn) getting one or the other error. As per the documentation {https://pycaret.gitbook.io/docs/get-started/installation}, it says {PyCaret is not yet compatible with sklearn>=0.23.2}; however, I have tried 0.23.1 to 1.0 versions of sklearn but one or the other error like this one {AttributeError: module 'sklearn.utils._openmp_helpers' has no attribute '__pyx_capi__'}. If you provide any direction, then it will be extremely helpful. Moreover, it would be good if the documentation can be updated frequently.

### Installation Logs

<details>

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 from pycaret import show_versions
      2 show_versions()

File ~/opt/miniconda3/envs/conda_ts_env/lib/python3.8/site-packages/pycaret/__init__.py:1, in <module>
----> 1 from pycaret.utils import __version__
      2 from pycaret.utils._show_versions import show_versions
      4 __all__ = ["show_versions", "__version__"]

File ~/opt/miniconda3/envs/conda_ts_env/lib/python3.8/site-packages/pycaret/utils/__init__.py:9, in <module>
      7 import numpy as np
      8 import pandas as pd
----> 9 from sklearn.metrics._scorer import _PredictScorer, get_scorer  # type: ignore
     11 version_ = "3.0.0"
     12 nightly_version_ = "3.0.0"

File ~/opt/miniconda3/envs/conda_ts_env/lib/python3.8/site-packages/sklearn/metrics/__init__.py:41, in <module>
     37 from ._classification import multilabel_confusion_matrix
     39 from ._dist_metrics import DistanceMetric
---> 41 from . import cluster
     42 from .cluster import adjusted_mutual_info_score
     43 from .cluster import adjusted_rand_score

File ~/opt/miniconda3/envs/conda_ts_env/lib/python3.8/site-packages/sklearn/metrics/cluster/__init__.py:22, in <module>
     20 from ._supervised import fowlkes_mallows_score
     21 from ._supervised import entropy
---> 22 from ._unsupervised import silhouette_samples
     23 from ._unsupervised import silhouette_score
     24 from ._unsupervised import calinski_harabasz_score

File ~/opt/miniconda3/envs/conda_ts_env/lib/python3.8/site-packages/sklearn/metrics/cluster/_unsupervised.py:16, in <module>
     14 from ...utils import check_X_y
     15 from ...utils import _safe_indexing
---> 16 from ..pairwise import pairwise_distances_chunked
     17 from ..pairwise import pairwise_distances
     18 from ...preprocessing import LabelEncoder

File ~/opt/miniconda3/envs/conda_ts_env/lib/python3.8/site-packages/sklearn/metrics/pairwise.py:33, in <module>
     30 from ..utils.fixes import delayed
     31 from ..utils.fixes import sp_version, parse_version
---> 33 from ._pairwise_distances_reduction import PairwiseDistancesArgKmin
     34 from ._pairwise_fast import _chi2_kernel_fast, _sparse_manhattan
     35 from ..exceptions import DataConversionWarning

File sklearn/metrics/_pairwise_distances_reduction.pyx:1, in init sklearn.metrics._pairwise_distances_reduction()

AttributeError: module 'sklearn.utils._openmp_helpers' has no attribute '__pyx_capi__'

</details>

**Comment by ngupta23** [comment]
We have merged time series with the other modules now. Can you try installing the following.

`pip install -U --pre pycaret`

**Comment by psxpa3** [comment]
Thanks @ngupta23 for the reply. Now I am getting error w.r.t logging. I have created a fresh conda environment, and doing the following steps:
1) pip install -U --pre pycaret -- went fine
2) from pycaret.utils import version
version() -- gives '3.0.0.rc2'
3) When I do {from pycaret.time_series import TS}, get the following error 
"""
System:
    python: 3.8.13 (default, Mar 28 2022, 06:16:26)  [Clang 12.0.0 ]
executable: /Users/prpraror/opt/miniconda3/envs/conda_ts_env/bin/python
   machine: macOS-10.16-x86_64-i386-64bit

PyCaret required dependencies:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [6], in <cell line: 2>()
      1 from pycaret import show_versions
----> 2 show_versions()

File ~/opt/miniconda3/envs/conda_ts_env/lib/python3.8/site-packages/pycaret/utils/_show_versions.py:174, in show_versions(optional, logger)
    171     print_func("{k:>10}: {stat}".format(k=k, stat=stat))  # noqa: T001
    173 print_func(f"{prefix}PyCaret required dependencies:")  # noqa: T001
--> 174 optional_deps_info = _get_deps_info(logger=logger)
    175 for k, stat in optional_deps_info.items():
    176     print_func("{k:>20}: {stat}".format(k=k, stat=stat))  # noqa: T001

File ~/opt/miniconda3/envs/conda_ts_env/lib/python3.8/site-packages/pycaret/utils/_show_versions.py:139, in _get_deps_info(optional, logger)
    137     mod = sys.modules[modname]
    138 else:
--> 139     with redirect_output(logger):
    140         mod = importlib.import_module(modname)
    141 ver = _get_module_version(mod)

File ~/opt/miniconda3/envs/conda_ts_env/lib/python3.8/site-packages/pycaret/internal/logging.py:39, in redirect_output.__init__(self, logger)
     37 def __init__(self, logger: Optional[logging.Logger] = None):
     38     self.logger = logger or DummyLogger("dummy")
---> 39     self.redirect_stdout = redirect_stdout(LoggerWriter(logger.info))
     40     self.redirect_stderr = redirect_stderr(LoggerWriter(logger.warning))

AttributeError: 'NoneType' object has no attribute 'info'
"""

**Comment by ngupta23** [comment]
`show_versions` has an issue in rc2 which will be fixed in the next release. Rest should work though.

**Comment by ngupta23** [comment]
rc3 was released recently. The issue should be fixed there so I will close this for now. Feel free to reopen if the issue exists.
