### ISSUE TITLE
[DOC]: Sample notebook could not be loaded in github

### ISSUE THREAD

**Issue by zmatrix24** [pycaret/pycaret#2728]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://github.com/pycaret/pycaret/blob/master/tutorials/Binary%20Classification%20Tutorial%20Level%20Intermediate%20-%20CLF102.ipynb

### Documentation problem

The page won't load for the tutorial notebook.
I tried to copy the raw content and still could not render it.

### Suggested fix for documentation

Reupload the file.

**Comment by ngupta23** [comment]
It is an issue with GitHub. It fails to render notebooks sometimes. Can you open the notebook link in nbviewer?

**Comment by zmatrix24** [comment]
Thanks @ngupta23!
I can see it from the link you provided.
I clicked download from there, it took a while, but I was able to get the raw content and paste it as ipynb file locally. Thanks!
