### ISSUE TITLE
[BUG]: high_cardinality_feature param failed in regression setup()

### ISSUE THREAD

**Issue by jkcdc** [pycaret/pycaret#2729]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

encountered TypeError: setup() got an unexpected keyword argument 'high_cardinality_features' during setup() in regression module.

### Reproducible Example

```python
from pycaret.regression import * 
uk_input_df = pd.read_csv('raw_uk.csv')
trial = setup(data = uk_input_df, target = 'target_frequency', session_id=9, high_cardinality_features = ['acq_date_cohort'], remove_multicollinearity=True, multicollinearity_threshold = 0.7, log_experiment = True, log_plots = True, experiment_name = 'baseline')
```

### Expected Behavior

expected to have normal setup() output
For example, 
![image](https://user-images.githubusercontent.com/102025076/177914128-f8532fd7-ea93-4c10-b5bd-f0a801933b9c.png)

### Actual Results

```python-traceback
TypeError: setup() got an unexpected keyword argument 'high_cardinality_features'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [214], in <cell line: 1>()
----> 1 trial9 = setup(data = trial9_data, target = 'target_frequency', session_id=9, high_cardinality_features = ['acq_date_cohort'], remove_multicollinearity=True, multicollinearity_threshold = 0.7, log_experiment = True, log_plots = True, experiment_name = 'baseline')

TypeError: setup() got an unexpected keyword argument 'high_cardinality_features'
```

### Installed Versions

<details>

System:
    python: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:23:20)  [Clang 12.0.1 ]
executable: /opt/anaconda3/bin/python
   machine: macOS-12.4-x86_64-i386-64bit

PyCaret required dependencies:
                 pip: Installed but version unavailable
          setuptools: 60.10.0
             pycaret: 3.0.0.rc1
             ipython: Installed but version unavailable
          ipywidgets: Installed but version unavailable
                tqdm: Installed but version unavailable
               numpy: 1.21.6
              pandas: 1.4.2
              jinja2: Installed but version unavailable
               scipy: 1.7.3
              joblib: 1.1.0
             sklearn: 1.1.1
                pyod: Installed but version unavailable
            imblearn: Installed but version unavailable
   category_encoders: Installed but version unavailable
            lightgbm: Installed but version unavailable
               numba: Installed but version unavailable
            requests: Installed but version unavailable
          matplotlib: Installed but version unavailable
          scikitplot: Installed but version unavailable
         yellowbrick: Installed but version unavailable
              plotly: Installed but version unavailable
             kaleido: Installed but version unavailable
         statsmodels: Installed but version unavailable
              sktime: Installed but version unavailable
               tbats: Installed but version unavailable
            pmdarima: Installed but version unavailable
              psutil: 5.9.0

PyCaret optional dependencies:
                shap: Installed but version unavailable
           interpret: Installed but version unavailable
                umap: Installed but version unavailable
    pandas_profiling: Installed but version unavailable
  explainerdashboard: Installed but version unavailable
             autoviz: Installed but version unavailable
           fairlearn: Installed but version unavailable
             xgboost: Installed but version unavailable
            catboost: Installed but version unavailable
              kmodes: Installed but version unavailable
             mlxtend: Installed but version unavailable
       statsforecast: Installed but version unavailable
        tune_sklearn: Installed but version unavailable
                 ray: Installed but version unavailable
            hyperopt: Installed but version unavailable
              optuna: Installed but version unavailable
               skopt: Installed but version unavailable
              mlflow: Installed but version unavailable
              gradio: Installed but version unavailable
             fastapi: Installed but version unavailable
             uvicorn: Installed but version unavailable
              m2cgen: Installed but version unavailable
           evidently: Installed but version unavailable
                nltk: Installed but version unavailable
            pyLDAvis: Installed but version unavailable
              gensim: Installed but version unavailable
               spacy: Installed but version unavailable
           wordcloud: Installed but version unavailable
            textblob: Installed but version unavailable
               fugue: Installed but version unavailable
           streamlit: Installed but version unavailable
             prophet: Installed but version unavailable

</details>

**Comment by tvdboom** [comment]
The `high_cardinality_features` parameter has been deprecated in pycaret 3.0. Use the new encoding options to handle high cardinality features:

https://github.com/pycaret/pycaret/blob/98cbf9451f1c20cc701b406f0b9b72d21f4ec2a6/pycaret/regression/functional.py#L237-L247
