### ISSUE TITLE
PyCaret installation problems

### ISSUE THREAD

**Issue by rijesh123** [pycaret/pycaret#273]
I am unable to install PyCaret on my office machine (It is working fine on my personal Laptop).

Please see the errors below (tried via Jupyter notebook and Anaconda prompt)
Via Jupyter notebook: error:

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004A5FAC8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /simple/pycaret/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004A60108>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /simple/pycaret/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004D01B48>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /simple/pycaret/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004D03948>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /simple/pycaret/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004D036C8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /simple/pycaret/
ERROR: Could not find a version that satisfies the requirement pycaret (from versions: none)
ERROR: No matching distribution found for PyCaret

Via anaconda prompt: Error details:
(base) d:\Users\user1>conda create --name powerbi python 3.7
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pk
gs/main/win-64/current_repodata.json>
Elapsed: -
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.
'https://repo.anaconda.com/pkgs/main/win-64'

I am able to access this link externally : 'https://repo.anaconda.com/pkgs/main/win-64'
and anaconda.com is not blocked

**Comment by pycaret** [comment]
@rijesh123 Are you using pip install in anaconda prompt or jupyter notebook?

**Comment by rijesh123** [comment]
Thanks for quick reply.
Yes. I tried "pip install pycaret" in both anaconda prompt and Jupyter notebook. (Bother errors are shown in above post)

**Comment by rijesh123** [comment]
@PyCaret - what may be the reason of this error?

**Comment by rijesh123** [comment]
@PyCaret - what may be the reason of this error?

**Comment by pycaret** [comment]
@rijesh123 To me it seems like http failing. Can you try opening Anaconda Prompt with admin rights and then try **pip install pycaret**. If it doesn't work, can you also try **pip install pycaret-nightly** 

Please let me know how it goes.

**Comment by rijesh123** [comment]
@PyCaret Thank you.
Previously I tried "pip install PyCaret" in Anaconda prompt, but didn't work.
I will request again for Admin access on my office machine and will try >> pip install pycaret-nightly
I will let you know if that works

**Comment by MANISH007700** [comment]
try 
 !pip install pycaret
in your notebook

**Comment by rijesh123** [comment]
Thanks @MANISH007700
I have tried this..but no luck

**Comment by MANISH007700** [comment]
You can try onething ! 

First write
!pip install pycaret
In your notebook. Let it run. If it's showing error  , let it be 

Then try import pycaret. And if now there is no error. You can continue , or else you can try wheel building

**Comment by pycaret** [comment]
@rijesh123 Do you still have issues installing pycaret==2.0?

**Comment by rijesh123** [comment]
@PyCaret I am still waiting for admin access on my office system. I will try again after that.
I have upgraded to 2.0 on my personal laptop

**Comment by MANISH007700** [comment]
I don't know why you are getting error !
Try wheel building , or try installing in venv !

**Comment by pycaret** [comment]
@rijesh123 Do you still need help on this issue or can we close this?

**Comment by rijesh123** [comment]
@pycaret ,@manish007700,
Apologies for late reply. I didn't get a chance to try on my office machine.

I will try again and log a new request if that didn't work

**Comment by Anuj-sultania** [comment]
For kaggle notebooks
Kaggle uses Jupyter notebook format. We can run Command Line Codes by using the Exclamation mark " ! " before the codes.

ex. !pip install 'new packages'

**Just remember to go to "Setting"(at bottom right of kernel) and Turn the internet "ON" before installing the packages. **
