### ISSUE TITLE
[DOC]: Request: Optuna custom grid example 

### ISSUE THREAD

**Issue by thinkinds** [pycaret/pycaret#2731]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://pycaret.readthedocs.io/en/latest/api/regression.html

### Documentation problem

when using Optuna in tune_model, how should I define a customized search space? I tried many times, but all failed, so please provide some examples here.
Thanks.

### Suggested fix for documentation

some simple examples

**Comment by erickp1** [comment]
No estaría de más agregar ejemplos en la documentación.
![Uploading IMG_20220709_201549.jpg…]()

**Comment by erickp1** [comment]
from pycaret.distributions import UniformDistribution, DiscreteUniformDistribution, CategoricalDistribution, IntUniformDistribution

params_lightgbm = {
    "max_depth" : IntUniformDistribution(4, 6, 1),
   "learning_rate" : UniformDistribution(0.05, 0.2, 1),
}


tuned_lightgbm = tune_model(lightgbm, custom_grid=params_lightgbm, optimize="rmse",
                             search_library="optuna", n_iter=20)

https://github.com/pycaret/pycaret/blob/master/pycaret/internal/distributions.py

**This should be in the documentation.**
