### ISSUE TITLE
[BUG]: initial_score / baseline are not passed to model

### ISSUE THREAD

**Issue by joseazdir** [pycaret/pycaret#2734]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

seems that initial baseline score is not passed to model. 
Sometimes you use a previous score from other model to affect the new model (in t he hope you will get a better metric). To do so, you train a model with the same data and use the baseline parameter to set that initial scores for the new model.

### Reproducible Example

```python
from pycaret.datasets import get_data
from pycaret.regression import setup
import numpy as np
import pandas as pd

fake_initial_score = np.round(np.random.uniform(0.0, 3.0, size=(len(data), 1)), 2)

data = get_data('diabetes')
clf=setup(data=data,
          target='Diabetes pedigree function',
          train_size= .80,
          fold_shuffle = True,
          fold = 5,
          html = False,
          silent = True,
          log_experiment = False,
          session_id = 1,
          n_jobs = -1)

model = create_model('xgboost')
tuned_model = tune_model(model, fold=5)
final_model = finalize_model(tuned_model)

# train model again using base_margin = list of supposed initial scores from other model
# the result metrics are identical. That should'nt be  the case. There should be an influence of previous scores

model = create_model('xgboost', base_margin = fake_initial_score)
tuned_model = tune_model(model, fold=5)
final_model = finalize_model(tuned_model)
```

### Expected Behavior

model metrics should be different if initial_score (base margin) is set. There is some influence (sometimes good, sometimes bad) 

I assume the initial scores are not passed to model.

Tested with xgboost and lightgbm

### Actual Results

```python-traceback
There is no error. Just identical metrics no matter  if initial score is set or not.
```

### Installed Versions

<details>'2.3.10'</details>

**Comment by Yard1** [comment]
Can you show how this would work without pycaret?

We are passing the kwargs as is to the model, so I am not sure why this wouldn't work.

**Comment by joseazdir** [comment]
When we use pycaret with xgboost or lightgbm we get the very same scores to the last decimal point. That is not possible. Scores should be affected somehow so we guess that the baseline is not passed (or any other issue)

here an example using catboost outside pycaret.

```
# No Baseline -------------------
train_data = Pool(data=df,
                   label=target,
                   cat_features=categorical_features)


model = CatBoostRegressor(iterations=20,
                          loss_function= 'RMSE',
                          border_count= 254,
                          verbose= False,
                          task_type= 'CPU',
                          random_state= 1,
                          depth= 9,
                          l2_leaf_reg= 5,
                          random_strength= 0.7,
                          eta= 0.15 )

model.fit(train_data)
```

We get metrics and then compare using baseline:

```
train_data = Pool(data=df,
                  label=target,
                  cat_features=categorical_features,
                  baseline=initial_scored
                  )

model = CatBoostRegressor(iterations=20,
                          loss_function= 'RMSE',
                          border_count= 254,
                          verbose= False,
                          task_type= 'CPU',
                          random_state= 1,
                          depth= 9,
                          l2_leaf_reg= 5,
                          random_strength= 0.7,
                          eta= 0.15)
                    
model.fit(train_data)
```

You will notice there is differences in metrics as we expected.

**Comment by Yard1** [comment]
How big of a difference are we talking about? PyCaret rounds the scores, so possibly that is the reason?

**Comment by joseazdir** [comment]
Xgboost metrics with no baseline
![image](https://user-images.githubusercontent.com/106954470/178480571-3bda4ed9-f248-4ea1-bbe1-84c496c09d62.png)

Xgboost metrics with baseline score
![image](https://user-images.githubusercontent.com/106954470/178480681-a8b5434f-e9ff-4c07-90b4-bbee8b849ffc.png)

**Comment by Yard1** [comment]
I can confirm that the argument is indeed being passed to the model. You can even see that if you do `print(model)` after creating the model with arguments. I do not believe this is an issue with PyCaret, based on that.

**Comment by joseazdir** [comment]
ok thanks for double checking.
In addition to that is there any way of passing these parameter to catboost? (as Pool seems not to be directly accessed from pycaret)

**Comment by Yard1** [comment]
Reading xgboost documentation I believe that you are supposed to use `base_margin` as a fit argument, not a model init argument. Indeed, this changes the metrics:
```
from pycaret.datasets import get_data
from pycaret.regression import *
import numpy as np
import pandas as pd


data = get_data('diabetes')

clf=setup(data=data,
          target='Diabetes pedigree function',
          train_size= .80,
          fold_shuffle = True,
          fold = 5,
          log_experiment = False,
          session_id = 1,
          n_jobs = -1)

fake_initial_score = np.round(np.random.uniform(0.0, 3.0, size=(len(get_config("X_train")), 1)), 2)

model = create_model('xgboost')

model = create_model('xgboost', fit_kwargs=dict(base_margin = fake_initial_score))
```

**Comment by joseazdir** [comment]
so any parameter outside setup should be pased this way as **fit_kwargs** ? I am thinking on monotonic constraints or Pool catboost parameters

**Comment by Yard1** [comment]
Looking at catboost code, you would pass the `baseline` argument in `fit_kwargs`.

To summarize - `create_model` kwargs are passed to model initialization, `fit_kwargs` are passed to model `fit()` method. You need to set `fit_kwargs` on every function each time (so eg. on both `create_model` and `tune_model`).

**Comment by joseazdir** [comment]
that's good to know! thanks Yard1 !

**Comment by joseazdir** [comment]
sadly, fit_kwargs is not working for any parameter you use in xgboost:
`TypeError: fit() got an unexpected keyword argument 'monotonic_constraints'`

**Comment by Yard1** [comment]
Please make sure that you are passing the parameters correctly as described in XGBoost documentation

**Comment by joseazdir** [comment]
from the documentation for xgboost here https://xgboost.readthedocs.io/en/stable/tutorials/monotonic.html
`
monotone_constraints = (1,-1)   # a tuple of values`
