### ISSUE TITLE
[DOC]:  

### ISSUE THREAD

**Issue by saravana325da** [pycaret/pycaret#2737]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://[pycaret.gitbook.io](https://pycaret.gitbook.io/docs/learn-pycaret/official-blog/anomaly-detector-in-power-bi-using-pycaret)/docs/learn-pycaret/official-blog/anomaly-detector-in-power-bi-using-pycaret
![pycaret page is not open](https://user-images.githubusercontent.com/42143093/178147592-d0b3ebcf-fa21-49bd-96a4-0f0e1ea5f43f.png)

### Documentation problem

anomaly-detector-in-power-bi-using-pycaret 

this link is not opening for me, i think my firewall is not allowing because.

it says : your connection to this sites is not secure. but it shows https: 
can you please check, from your side, my company VPN is not allowing to read your documents page, so i cannot go through and learn from it.

### Suggested fix for documentation

[  anomaly-detector-in-power-bi-using-pycaret  ](https://pycaret.gitbook.io/docs/learn-pycaret/official-blog/anomaly-detector-in-power-bi-using-pycaret)https://[pycaret.gitbook.io](https://pycaret.gitbook.io/docs/learn-pycaret/official-blog/anomaly-detector-in-power-bi-using-pycaret)/docs/learn-pycaret/official-blog/anomaly-detector-in-power-bi-using-pycaret

**Comment by ShreySrivas** [comment]
> ### pycaret version checks
> * [x]  I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)
> 
> ### Location of the documentation
> https://[pycaret.gitbook.io](https://pycaret.gitbook.io/docs/learn-pycaret/official-blog/anomaly-detector-in-power-bi-using-pycaret)/docs/learn-pycaret/official-blog/anomaly-detector-in-power-bi-using-pycaret ![pycaret page is not open](https://user-images.githubusercontent.com/42143093/178147592-d0b3ebcf-fa21-49bd-96a4-0f0e1ea5f43f.png)
> 
> ### Documentation problem
> anomaly-detector-in-power-bi-using-pycaret
> 
> this link is not opening for me, i think my firewall is not allowing because.
> 
> it says : your connection to this sites is not secure. but it shows https: can you please check, from your side, my company VPN is not allowing to read your documents page, so i cannot go through and learn from it.
> 
> ### Suggested fix for documentation
> [ anomaly-detector-in-power-bi-using-pycaret ](https://pycaret.gitbook.io/docs/learn-pycaret/official-blog/anomaly-detector-in-power-bi-using-pycaret)https://[pycaret.gitbook.io](https://pycaret.gitbook.io/docs/learn-pycaret/official-blog/anomaly-detector-in-power-bi-using-pycaret)/docs/learn-pycaret/official-blog/anomaly-detector-in-power-bi-using-pycaret

The link seems to be working on my end. Try disabling your browser's firewall extensions/ ad-blockers to see if it works.

**Comment by ngupta23** [comment]
Same here, it works fine. We will close this for now. Feel free to open a new one if there are more issues.
