### ISSUE TITLE
[DOC]: PyCaret - QuickStart - Issues

### ISSUE THREAD

**Issue by msdumanlc** [pycaret/pycaret#2740]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://pycaret.gitbook.io/docs/get-started/quickstart

### Documentation problem

Downloaded and installed the Docker version from the installation page.  I am on windows 10 pro.  Running through the Quickstart page.  Most examples look pretty good but I did notice some of the dataset screen shots don’t match what I get?  I would have thought that would be exact?  The Clustering  | Assign Model | the Cluster column values were completely opposite on the web page than what I got?   Might want to review that example a bit.  
 
However, the big issue is with Time Series example on the QuickStart page.  I have included a screen shot of the error.  Any ideas on how to resolve? I have restarted the Kernel and even the Docker contain with no luck?   Thanks in advance, keep up the good work, its impressive!
![image](https://user-images.githubusercontent.com/109091381/178297110-1a327192-1b00-44b3-ab3c-10ac9097e709.png)

### Suggested fix for documentation

Review the Quickstart results and update page.  Resolve the docker issue in screen shot provided.

**Comment by moezali1** [comment]
@msdumanlc Do you have a full error trace?

**Comment by msdumanlc** [comment]
Sorry no.  That was 6 months ago?  If you can complete the Quickstart without any issues must be fixed.  Than you can close the ticket.

**Comment by moezali1** [comment]
The issue has been fixed in the latest image.
