### ISSUE TITLE
[BUG]: choose_better = True in stack_models gives error

### ISSUE THREAD

**Issue by AmandaAll** [pycaret/pycaret#2743]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

Not possible to use choose_better = True in stack_models()

### Reproducible Example

```python
from pycaret.datasets import get_data
from pycaret.classification import *

_data = data.get_data('bank')
exp = ClassificationExperiment()
exp.setup(data = _data, target = 'deposit')

model1 = exp.create_model('rf')
model2 = exp.create_model('dummy')
stacked = exp.stack_models([model1, model2], choose_better=True)
```

### Expected Behavior

From the documentation of choose_better in stack_models:
"When set to True, the returned object is always better performing. The metric used for comparison is defined by the ``optimize`` parameter."

Attaching the error message received in the actual run.

<img width="490" alt="choose_better_fit_kwargs" src="https://user-images.githubusercontent.com/74770486/178448829-deb7a5fe-bef1-4087-a2b5-4db5e67804e3.PNG">

### Actual Results

```python-traceback
Not possible to run the reproducibility example, but get the error message: 
"TypeError: _choose_better() got multiple values for argument 'fit_kwargs'"
```

### Installed Versions

<details>
'3.0.0.rc2'
</details>

**Comment by Yard1** [comment]
Thanks, fixed in a5d05de9a2ef8086b543a26a6146f49d0cf29fff
