### ISSUE TITLE
[ENH]: Add possibility for rare encoding 

### ISSUE THREAD

**Issue by AmandaAll** [pycaret/pycaret#2750]
### Describe the feature you want to add to this project

The possibility to do encoding of rare values, grouping them to one single category for example "other" or "rare". 

### Describe your proposed solution

In setup, the parameter encoding_method only allows encoding methods in category_encoders objects. I cannot find this library to include rare label encoding.

Could rare label encoding be added as an additional parameter in setup? Or the possibility to provide multiple encoding methods in a specified order in encoding_method (also including other libraries), since applying rare encoding will also cause the need for categorical encoding after rare values have been grouped.

**Comment by tvdboom** [comment]
Yes, I was planning to implement something like this in the near future. I'll keep you updated here.
