### ISSUE TITLE
[DOC]: Tutorials missing - The notebook took too long to render or 404

### ISSUE THREAD

**Issue by msdumanlc** [pycaret/pycaret#2753]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://pycaret.gitbook.io/docs/get-started/tutorials

### Documentation problem

From the tutorial web page click on link for **Binary Classification -Level Intermediate**, and/or **Time Series Forecasting - Level Beginner**   Get errors, links are wrong or missing?

Tutiorial page:
https://pycaret.gitbook.io/docs/get-started/tutorials

Notebook links to nowhere?
https://github.com/pycaret/pycaret/blob/master/tutorials/Binary%20Classification%20Tutorial%20Level%20Intermediate%20-%20CLF102.ipynb

https://github.com/pycaret/pycaret/blob/time_series/time_series_101.ipynb

### Suggested fix for documentation

Update links to appropriate pages.

**Comment by ngupta23** [comment]
Thanks for pointing this out. The [time series link](https://github.com/pycaret/pycaret/blob/time_series/time_series_101.ipynb) that you are referring to is old. We will update this shortly. For now, you can refer to this location: https://github.com/pycaret/pycaret/tree/master/examples/time_series/forecasting

The [classification link](https://github.com/pycaret/pycaret/blob/master/tutorials/Binary%20Classification%20Tutorial%20Level%20Intermediate%20-%20CLF102.ipynb) seems to be working fine.

**Comment by Yard1** [comment]
Related to https://github.com/pycaret/pycaret/issues/2814
