### ISSUE TITLE
[DOC]: Cannot install pycaret 3 with command displayed on web-page

### ISSUE THREAD

**Issue by sorenwacker** [pycaret/pycaret#2756]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://pycaret.gitbook.io/docs/

### Documentation problem

PyCaret 3.0-rc is now available. `pip install --pre pycaret` to try it. Check out this example [Notebook](https://colab.research.google.com/drive/1_H0sHYhzKGZDmgzrQLosuZAR3nOaL6CN?usp=sharing).

### Suggested fix for documentation

This command does not install pycaret 3 but pycaret 2.3.10.

I also tried `pip install -U --pre pycaret`

**Comment by sorenwacker** [comment]
Which Python version are you using?

**Comment by ngupta23** [comment]
Anything 3.9 and below should work.

**Comment by sorenwacker** [comment]
Seems that was the issue. Probably, my other environment uses python 3.7 or 3.8.
