### ISSUE TITLE
[BUG]: create_app not removing one-hot codded columns

### ISSUE THREAD

**Issue by nityanantan23** [pycaret/pycaret#2757]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

When I try to run create_app() in the latest master, it doesn't remove the one-hot codded columns. So it shows the error below in the actual result section.

### Reproducible Example

```python
!pip install -U git+https://github.com/pycaret/pycaret.git@master
!pip install gradio --quiet

from pycaret.regression import *
from pycaret.datasets import get_data

boston = get_data('bank')
exp_name = setup(data = boston,  target = 'deposit')
lr = create_model('lr')
create_app(lr)
```

### Expected Behavior

Display URL of gradio

### Actual Results

```python-traceback
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-f9dc2e4d736f> in <module>()
      5 exp_name = setup(data = boston,  target = 'deposit')
      6 lr = create_model('lr')
----> 7 create_app(lr)

5 frames
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py in _validate_read_indexer(self, key, indexer, axis)
   1375 
   1376             not_found = list(ensure_index(key)[missing_mask.nonzero()[0]].unique())
-> 1377             raise KeyError(f"{not_found} not in index")
   1378 
   1379 

KeyError: "['marital_single', 'marital_married', 'marital_divorced', 'education_secondary', 'education_primary', 'education_tertiary', 'education_unknown', 'contact_cellular', 'contact_unknown', 'contact_telephone', 'poutcome_success', 'poutcome_unknown', 'poutcome_failure', 'poutcome_other'] not in index"
```

### Installed Versions

<details>

System:
    python: 3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0]
executable: /usr/bin/python3
   machine: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic

PyCaret required dependencies:
                 pip: 21.1.3
          setuptools: 57.4.0
             pycaret: 3.0.0.rc3
             IPython: 5.5.0
          ipywidgets: 7.7.1
                tqdm: 4.64.0
               numpy: 1.21.6
              pandas: 1.3.5
              jinja2: 2.11.3
               scipy: 1.7.3
              joblib: 1.1.0
             sklearn: 1.0.2
                pyod: Installed but version unavailable
            imblearn: 0.8.1
   category_encoders: 2.5.0
            lightgbm: 3.3.2
               numba: 0.55.2
            requests: 2.28.1
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.9.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.11.4
               tbats: Installed but version unavailable
            pmdarima: 1.8.5
              psutil: 5.9.1</details>

**Comment by ngupta23** [comment]
@tvdboom will look at it per the August 15th meeting

![image](https://user-images.githubusercontent.com/33585645/184621254-aed8d28a-3c54-49a6-b583-821b4a27babd.png)
