### ISSUE TITLE
Pandas proffilling is corrupted after installing pycaret

### ISSUE THREAD

**Issue by SSITB** [pycaret/pycaret#276]
Create a new environment and install pandas profiling as below 
pip install pandas-profiling

run the below code in any notebook
# Profiling

import pandas_profiling as pdp
import pandas as pd
data = pd.read_csv('anyfile.csv')
pdp.ProfileReport(data)

The code works perfect

Now install pycaret and run the above code again
pip install pycaret

You get an error, not sure what is the issue but it seems that pycaret override some libraries used in pandas profiling that let the code broke

**Comment by Virajdatt** [comment]
Not sure why this is happening to you, I just tried it and didn't see any issues running pandas_profiling after installing pycaret.
Can u please add the details of the errors and the versions.

**Comment by pycaret** [comment]
@SSITB Please update your pandas-profiling version using **pip install --upgrade pandas-profiling**.

Please close this issue, if this solves your problem.

**Comment by SSITB** [comment]
Hi, i was not able to run the above **pip install --upgrade pandas-profiling.** and got the below error

ERROR: pycaret 1.0.0 has requirement pandas-profiling==2.3.0, but you'll have pandas-profiling 2.8.0 which is incompatible.

even when i tried to run after pip install 
pip install --upgrade pycaret

i got 
Successfully uninstalled pandas-profiling-2.8.0
Successfully installed pandas-profiling-2.3.0

when u try to run the below code again

import pandas_profiling as pdp
import pandas as pd

data = pd.read_csv('data\\titanic.csv')
pdp.ProfileReport(data)


I got 
KeyError: 'Requested level (var1) does not match index name (None)'

**Comment by pycaret** [comment]
@SSITB Can you try to reproduce the same error with **pycaret-nightly**?

**Comment by SSITB** [comment]
Ya it worked in pycaret-nightly
