### ISSUE TITLE
[BUG]: Combination of PCA and remove_multicollinearity is causing error

### ISSUE THREAD

**Issue by AmandaAll** [pycaret/pycaret#2765]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Not possible to use remove_multicollinearity and pca in combination in setup. 

### Reproducible Example

```python
from pycaret.datasets import get_data
from pycaret.classification import *

_data = get_data('satellite')
exp = ClassificationExperiment()
exp.setup(data = _data, remove_multicollinearity = True, 
    multicollinearity_threshold = 0.9, pca_components= 1.0, pca = True, target = 'Class')
```

### Expected Behavior

Since the nr of pca components is set to 1.0, you would expect 100% of the columns that are left after all the other feature selection methods to be kept to the same nr. 

### Actual Results

```python-traceback
Instead, this is throwing the error:

    497         raise ValueError(
    498             "n_components='mle' is only supported if n_samples >= n_features"
    499         )
    500 elif not 0 <= n_components <= min(n_samples, n_features):
--> 501     raise ValueError(
    502         "n_components=%r must be between 0 and "
    503         "min(n_samples, n_features)=%r with "
    504         "svd_solver='full'" % (n_components, min(n_samples, n_features))
    505     )
    506 elif n_components >= 1:
    507     if not isinstance(n_components, numbers.Integral):
ValueError: n_components=36 must be between 0 and min(n_samples, n_features)=4 with svd_solver='full'
```

### Installed Versions

<details>
'3.0.0.rc2'
</details>

**Comment by tvdboom** [comment]
Hi. This issue is fixed in #2768. I refactored the parameter a bit to follow sklearn's API. To return all components, just leave the parameter to it's default value, which has changed from 1.0 to `None`. After the PR is merged, you can install directly from `master` to utilize this.
