### ISSUE TITLE
[BUG]: Prediction column named the same as target column if target == "Label"

### ISSUE THREAD

**Issue by jnsflt** [pycaret/pycaret#2790]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

In my dataset, the target-column is named "Label". Thus, when predicting on a model it will create a new column named "Label". 

![image](https://user-images.githubusercontent.com/107557528/180458953-c0bb1e87-d43c-4e86-9b1f-fb7ffadfc0c9.png)

This makes it hard for me to use that dataframe, since I do not know which column is my target-column or which is the predicted column. 

This has lead to tedious workaround in my code, changing column names to "_Label". I think these workaround are unnecessary and could be handled by PyCaret instead.

Thanks! 

### Reproducible Example

```python
from pycaret.classification import *
from pycaret.datasets import get_data
df = get_data("juice", verbose=False)
df = df.rename(columns={"STORE":"Label"})
exp = ClassificationExperiment()
exp.setup(data=df)

clf = exp.create_model("rf")

predictions = exp.predict_model(clf)
predictions
```

### Expected Behavior

Maybe change the name to "predicted_label" or similar.

Or check if target == "Label", change predicted column to "Label_1"

### Actual Results

```python-traceback
See picture above.
```

### Installed Versions

<details>
PyCaret 3.0.0rc3
</details>

**Comment by tvdboom** [comment]
#2798 changes the name to `prediction_label`.
