### ISSUE TITLE
[BUG]: categorical column not at index when `create_app()` function is invoqued at PyCaret 3.x

### ISSUE THREAD

**Issue by PabloJMoreno** [pycaret/pycaret#2791]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Working with classification module, I tried to deploy an app using `create_app()` function and I noticed that it is not capturing categorical columns, only numerical / continuous.

It seems that it create column index based on 'trasnfomer dataset' and not picking the original shape dataset

I checked with previous PyCaret 2.X and it works fine, so it seems something only related to PyCaret 3.X

Thank you

### Reproducible Example

```python
from pycaret.classification import *
cla = setup(data = df, target = 'abandono', session_id = 100, train_size = 0.85, 
           ignore_features = ['nivel_salario'])
modelo = create_model('et')
final_model = finalize_model(modelo)
predict_model(final_model, data = nuevo_df)
create_app(final_model)
```

### Expected Behavior

To create app including categorical features.

### Actual Results

```python-traceback
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [30], in <cell line: 1>()
----> 1 create_app(final_model)

File ~\anaconda3\envs\curso\lib\site-packages\pycaret\internal\utils.py:922, in check_if_global_is_not_none.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    920     if globals_d[name] is None:
    921         raise ValueError(message)
--> 922 return func(*args, **kwargs)

File ~\anaconda3\envs\curso\lib\site-packages\pycaret\classification\functional.py:3116, in create_app(estimator, app_kwargs)
   3086 @check_if_global_is_not_none(globals(), _CURRENT_EXPERIMENT_DECORATOR_DICT)
   3087 def create_app(estimator, app_kwargs: Optional[dict] = None) -> None:
   3089     """
   3090     This function creates a basic gradio app for inference.
   3091     It will later be expanded for other app types such as
   (...)
   3114         None
   3115     """
-> 3116     return _CURRENT_EXPERIMENT.create_app(estimator=estimator, app_kwargs=app_kwargs)

File ~\anaconda3\envs\curso\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py:5365, in _SupervisedExperiment.create_app(self, estimator, app_kwargs)
   5362 all_inputs = []
   5363 app_kwargs = app_kwargs or {}
-> 5365 data_without_target = self.X[list(self.X_train_transformed.columns)]
   5367 for i in data_without_target.columns:
   5368     if i in self._fxs["Categorical"] or i in self._fxs["Ordinal"]:

File ~\anaconda3\envs\curso\lib\site-packages\pandas\core\frame.py:3511, in DataFrame.__getitem__(self, key)
   3509     if is_iterator(key):
   3510         key = list(key)
-> 3511     indexer = self.columns._get_indexer_strict(key, "columns")[1]
   3513 # take() does not accept boolean indexers
   3514 if getattr(indexer, "dtype", None) == bool:

File ~\anaconda3\envs\curso\lib\site-packages\pandas\core\indexes\base.py:5782, in Index._get_indexer_strict(self, key, axis_name)
   5779 else:
   5780     keyarr, indexer, new_indexer = self._reindex_non_unique(keyarr)
-> 5782 self._raise_if_missing(keyarr, indexer, axis_name)
   5784 keyarr = self.take(indexer)
   5785 if isinstance(key, Index):
   5786     # GH 42790 - Preserve name from an Index

File ~\anaconda3\envs\curso\lib\site-packages\pandas\core\indexes\base.py:5845, in Index._raise_if_missing(self, key, indexer, axis_name)
   5842     raise KeyError(f"None of [{key}] are in the [{axis_name}]")
   5844 not_found = list(ensure_index(key)[missing_mask.nonzero()[0]].unique())
-> 5845 raise KeyError(f"{not_found} not in index")

KeyError: "['nivel_salario_intermedio', 'nivel_salario_bajo', 'nivel_salario_alto'] not in index"
```

### Installed Versions

<details>
import pycaret
pycaret.__version__
[Out] '3.0.0.rc2'
</details>

**Comment by PabloJMoreno** [comment]
Thank you friends. 
I also noticed another issue in PyCaret 2.3.10 with the same function. Here is the error when I run it in PyCaret 2.3.10:

---------------------------------------------------------------------------
ContextualVersionConflict                 Traceback (most recent call last)
Cell In [11], line 1
----> 1 create_app(xgb_final)

File ~\anaconda3\envs\ml\lib\site-packages\pycaret\classification.py:3209, in create_app(estimator, app_kwargs)
   3180 def create_app(estimator, app_kwargs: Optional[dict] = None) -> None:
   3182     """
   3183     This function creates a basic gradio app for inference.
   3184     It will later be expanded for other app types such as
   (...)
   3207         None
   3208     """
-> 3209     return pycaret.internal.tabular.create_app(
   3210         estimator=estimator, app_kwargs=app_kwargs
   3211     )

File ~\anaconda3\envs\ml\lib\site-packages\pycaret\internal\tabular.py:11003, in create_app(estimator, app_kwargs)
  10974 """
  10975 This function creates a basic gradio app for inference.
  10976 It will later be expanded for other app types such as
   (...)
  10999     None
  11000 """
  11002 try:
> 11003     import gradio as gr
  11004 except ImportError:
  11005     raise ImportError(
  11006         "It appears that gradio is not installed. Do: pip install gradio"
  11007     )

File ~\anaconda3\envs\ml\lib\site-packages\gradio\__init__.py:15
     12 from gradio.routes import get_state, set_state
     13 from gradio.static import Button, Markdown
---> 15 current_pkg_version = pkg_resources.require("gradio")[0].version
     16 __version__ = current_pkg_version

File ~\anaconda3\envs\ml\lib\site-packages\pkg_resources\__init__.py:886, in WorkingSet.require(self, *requirements)
    877 def require(self, *requirements):
    878     """Ensure that distributions matching `requirements` are activated
    879 
    880     `requirements` must be a string or a (possibly-nested) sequence
   (...)
    884     included, even if they were already activated in this working set.
    885     """
--> 886     needed = self.resolve(parse_requirements(requirements))
    888     for dist in needed:
    889         self.add(dist)

File ~\anaconda3\envs\ml\lib\site-packages\pkg_resources\__init__.py:777, in WorkingSet.resolve(self, requirements, env, installer, replace_conflicting, extras)
    774 if dist not in req:
    775     # Oops, the "best" so far conflicts with a dependency
    776     dependent_req = required_by[req]
--> 777     raise VersionConflict(dist, req).with_context(dependent_req)
    779 # push the new requirements onto the stack
    780 new_requirements = dist.requires(req.extras)[::-1]

ContextualVersionConflict: (attrs 22.1.0 (c:\users\pmore\anaconda3\envs\ml\lib\site-packages), Requirement.parse('attrs<22,>=19'), {'markdown-it-py'})

**Comment by moezali1** [comment]
@PabloJMoreno I just tried to reproduce this with rc4 and couldn't. 

Can you upload upload reproducible notebook along with sample data here for me to diagnose and fix the issue.

**Comment by ngupta23** [comment]
I think this was fixed by @tvdboom in https://github.com/pycaret/pycaret/issues/2757. Can we close this?

**Comment by tvdboom** [comment]
Yes, this is fixed. Feel free to reopen if the problem persists.
