### ISSUE TITLE
[BUG]: fix_imbalance=True hides metric output of compare_models.

### ISSUE THREAD

**Issue by AJ5PY** [pycaret/pycaret#2796]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Hi,

Whenever I change fix_imbalance to 'True', the output of the next line of code (compare_models) disappears... Whilst others in the past have suffered from their metric output being hidden for various reasons, I cannot find any on particularly having issues with fix_imbalance.

I have attempted troubleshooting by changing the 'sort=AUC', as well as print(best_model), and pull(). Nonetheless, the only thing which shows the output is if I remove fix_imbalance=True

I am most likely doing something incorrect as I am new to PyCaret, but I cannot find anything online to help my problem. 

Thank you! 

### Reproducible Example

```python
clf1 = setup(data = df_train, target = 'target', fix_imbalance=True,
             fold_shuffle=False,
             data_split_shuffle = False,
             fold_strategy='timeseries',
             log_experiment=True, session_id=42)

best_model = compare_models(sort='AUC')
```

I should note, adding n_select and n_jobs=1 does not help solve the issue (when fix_imbalance=False, it works. When fix_imbalance=True, there is no output).

### Expected Behavior

It should simply showcase the compare_models output for classification, sorted by AUC. 

### Actual Results

```python-traceback
If using print(best_model), the output is simply:
[]

If doing anything else, the code is ran and there is no output, but no issues show either...
```

### Installed Versions

<details>
'2.3.10'
</details>

**Comment by tvdboom** [comment]
Running your example for classification yields `ValueError: Stratified train/test split is not implemented for shuffle=False` since you can't mix stratification (True by default) with shuffling=False.
However, setting `data_split_shuffle=True` worked as expected, showing the ouput of compare_models. Can you share a reproducible example and tell us which module you are using? With data and working code. Thanks

**Comment by AJ5PY** [comment]
Hi, 

Apologies. I should have mentioned that the dataset is time series. On the above code, I am only running my model on the training dataset (df_train). Therefore, data_split_shuffle=True seems to be bad practice. In this case, what am I supposed to do regarding stratification and shuffling? It doesn't make sense to me that an initial classifier (without imbalance fix) works just fine regardless of the stratification and shuffling clash. I actually split the train and test sets outside of pycaret as I am dealing with imbalance. Does this simply mean I should falsify stratification? 

The module I am using is pycaret.classification

I will try to provide data and a working example when I get some time, but perhaps these questions will help solve the problem.

**Comment by tvdboom** [comment]
I am a bit confused here. Why are you using pycaret.classification with time series data? Is date one of your features? What are you trying to predict? Secondly, if you have a test set yourself, use the `test_data` parameter in setup. Else, pycaret is always going to split the data you provide into a train and test set because it needs a test set for evaluation

**Comment by AJ5PY** [comment]
Thanks for your response. 

Classification seemed useful because the target (recessions) is quite rare. Therefore, it would be an imbalanced classification problem despite being time series data. I remove the actual date from economic data, but wish to keep the rows in order.

Thank you for the insight regarding `test_data`, I seem to have missed that out!

**Comment by tvdboom** [comment]
I see. If the order of the rows matter I would not recommend using classification. The majority of the models don't take that into account. What do you think @ngupta23 ?

**Comment by AJ5PY** [comment]
I agree, but the target is binary (0 for no recession, 1 for yes). This means classification would be much better suited, especially when a class imbalance is clear.  Quite a tough spot, so any insight would be much appreciated!

**Comment by ngupta23** [comment]
We do not have a way to fix the imbalance while maintaining the temporal dependence in pycaret. Maybe try a different approach such as predicting the actual GDP and then calling a recession if you see 2 quarters of contraction (similar to what is done **[here](https://htmlpreview.github.io/?https://github.com/ngupta23/gdp_prediction/blob/master/analysis/gdp_prediction_analysis.html)**).

**Comment by AJ5PY** [comment]
Hi @ngupta23 thank you for your response and for sharing this work, it is very closely linked to my project! 

Unfortunately, I would not be able to utilise this definition of a recession, as my project requires me to focus on NBER's definition so I will have to find some kind of work-around. 

If PyCaret does not allow for imbalance fixing whilst maintaining temporal dependence, would I be able to utilise an imbalance fixer from scikit-learn's imblearn prior to the model setup, and then simply employ `fix_imbalance=False` in PyCaret on the imbalance-fixed datasets? From here, would I simply be able to apply `data_split_shuffle = False`, and `fold_strategy='timeseries'` in PyCaret, or would this be a problematic approach overall?

I am happy to close this discussion when you are ready, as I don't think my initial issue clarifies as a bug. However, any insight on a potential way to overcome this challenge would be much appreciated.
