### ISSUE TITLE
[BUG]: models() still not work in pycaret version 2.3.10

### ISSUE THREAD

**Issue by yglpyn8888** [pycaret/pycaret#2797]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

models() still not work in pycaret version 2.3.10
i have seen relatived issues , but the problem is : the logging module has not been installed properly
although i install 'logging' manully, this module seems has problem that cannot be installed

i tried to set internal=True or False, both failed
and i tried 
# from pycaret.datasets import get_data
# data = get_data('boston')
#
# from pycaret.regression import *
# s = setup(data, target = 'medv')
#
# models()
, still not work by giving error msg: urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>

### Reproducible Example

```python
# from pycaret.datasets import get_data
# data = get_data('boston')
#
# from pycaret.regression import *
# s = setup(data, target = 'medv')
#
# models()

import pycaret
import pycaret.classification as clf
print(pycaret.__version__)
clf.models(internal=True)
```

### Expected Behavior

print models() information

### Actual Results

```python-traceback
C:\Users\Y\miniconda3\python.exe C:/Users/Y/Documents/code/py38/train4ddb/train1.py
2.3.10
Traceback (most recent call last):
  File "C:/Users/Y/Documents/code/py38/train4ddb/train1.py", line 11, in <module>
    clf.models(internal=True)
  File "C:\Users\Y\miniconda3\lib\site-packages\pycaret\classification.py", line 2518, in models
    return pycaret.internal.tabular.models(
  File "C:\Users\Y\miniconda3\lib\site-packages\pycaret\internal\tabular.py", line 9988, in models
    logger.info(f"gpu_param set to {gpu_param}")
NameError: name 'logger' is not defined
```

### Installed Versions

2.3.10

**Comment by yglpyn8888** [comment]
I can't install the Logging package, and I have correctly installed pycaret[full], but it doesn't include Logging.

**Comment by yglpyn8888** [comment]
solved

**Comment by ngupta23** [comment]
It would be great if you can post a summary of how you solved it here as it would help others that face the same problem. Thanks!
