### ISSUE TITLE
Specify "n_jobs" Parameters

### ISSUE THREAD

**Issue by rkakamilan** [pycaret/pycaret#28]
Currently n_jobs=-1 is set in `compare_models`, `tune_model` and so on. But I think it would be more useful if user can specify it when the calculation is done on a shared server. I would appreciate if you could consider it.

**Comment by pycaret** [comment]
Thanks. Did you mean by default n_jobs shouldn't be -1 except if somebody is using on server in which case they will pass n_jobs as -1. or do you just want a parameter in each function to define n_jobs?

**Comment by rkakamilan** [comment]
Thanks. I just want to set n_jobs in each function.

**Comment by pycaret** [comment]
pull request passed in dev-1.0.1.
