### ISSUE TITLE
Error when loading dataset with profile=True

### ISSUE THREAD

**Issue by dplew** [pycaret/pycaret#280]
I can successfully run the following two lines:

from pycaret.datasets import get_data
dataset = get_data('diamond')

When I run the same lines (from the regression tutorial) with profile=True:

from pycaret.datasets import get_data
dataset = get_data('diamond', profile=True) 

I get the following Traceback:

<ipython-input-1-6b54b7dd7674> in <module>
      1 # Loading data from pycaret
      2 from pycaret.datasets import get_data
----> 3 dataset = get_data('diamond', profile=True)

~\anaconda3\envs\playcaret\lib\site-packages\pycaret\datasets.py in get_data(dataset, save_copy, profile)
     71         if profile:
     72             import pandas_profiling
---> 73             pf = pandas_profiling.ProfileReport(data_for_profiling)
     74             display(pf)
     75 
~\anaconda3\envs\playcaret\lib\site-packages\pandas_profiling\__init__.py in __init__(self, df, **kwargs)
     66 
     67         # Get dataset statistics
---> 68         description_set = describe_df(df)
     69 
     70         # Get sample

~\anaconda3\envs\playcaret\lib\site-packages\pandas_profiling\model\describe.py in describe(df)
    549 
    550     # Get correlations
--> 551     correlations = calculate_correlations(df, variables)
    552 
    553     # Check correlations between numerical variables

~\anaconda3\envs\playcaret\lib\site-packages\pandas_profiling\model\correlations.py in calculate_correlations(df, variables)
    191                     # Get the Phi_k sorted order
    192                     current_order = (
--> 193                         correlations["phi_k"].index.get_level_values("var1").tolist()
    194                     )
    195 

~\anaconda3\envs\playcaret\lib\site-packages\pandas\core\indexes\base.py in _get_level_values(self, level)
   1477         Index(['a', 'b', 'c'], dtype='object')
   1478         """
-> 1479         self._validate_index_level(level)
   1480         return self
   1481 

~\anaconda3\envs\playcaret\lib\site-packages\pandas\core\indexes\base.py in _validate_index_level(self, level)
   1414         elif level != self.name:
   1415             raise KeyError(
-> 1416                 f"Requested level ({level}) does not match index name ({self.name})"
   1417             )
   1418 

KeyError: 'Requested level (var1) does not match index name (None)'

**Comment by ramnathv** [comment]
I believe the error occurs due to an older version of `pandas-profiling` installed. I was able to get profiling to work by installing the latest version of `pandas-profiling`. It does throw a warning since `pycaret` explicitly requires an older version, but does not lead to any issues as far as i know.

```bash
pip install pandas-profiling==2.8.0
```

@pycaret Any specific reasons to explicitly require older versions (from what I remember `scikit-learn`, `xgboost`, `plotly` etc. are all a few versions behind).

**Comment by pycaret** [comment]
@dplew -- please update your pandas-profiling as suggested by @ramnathv 

@ramnathv - No specific reason. This issue has already been fixed in dev-1.0.1 branch. Please see **requirements.txt** for dev-1.0.1 branch.

Thanks

**Comment by pycaret** [comment]
@dplew Please close this issue, if updating pandas-profiling solves your issue.

**Comment by dplew** [comment]
Thank you @ramnathv and @pycaret.  This solves the problem.
