### ISSUE TITLE
[BUG]: pycaret + mlflow integration does not allow probabilities for classification and binary response models

### ISSUE THREAD

**Issue by DerekKane** [pycaret/pycaret#2801]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

We have been using pycaret 2.2 for the model training procedure and registration to the mlflow server. (python based) My company uses a managed version of this in Azure Databricks. After the registration has been completed, we call the calibrated algorithm in a separate notebook and are trying to score new data with a binary response 0|1. We would also like to leverage the scikit learn function "predict_model" to create the probabilities in addition to the predicted value. This is not working in pycaret and appears to be a bug of some sort. It is also important to note that we are able to see the "predict_model" during the model training but not when we call the algorithm for a separate scoring function. 

### Reproducible Example

```python
# import mlflow.sklearn
# model = mlflow.sklearn.load_model(production_algorithm)
# model.predict_prob(X)
```

### Expected Behavior

we should see the probabilities model.predict_prob(X) but this code errors out. Another example would be the following: predictions_prob = production_algorithm.predict_prob(pd.DataFrame(X))

### Actual Results

```python-traceback
the end result of the prediction should be a numeric value between 0 and 1. Ex. 0.4278
```

### Installed Versions

<details>
System:
    python: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0]
executable: /local_disk0/.ephemeral_nfs/envs/pythonEnv-ca5e1db9-faed-4291-83c9-f55dfcbb8112/bin/python
   machine: Linux-5.4.0-1083-azure-x86_64-with-glibc2.29

PyCaret required dependencies:
                 pip: 21.0.1
          setuptools: 52.0.0
             pycaret: 3.0.0.rc3
             IPython: 7.22.0
          ipywidgets: 7.7.1
                tqdm: 4.64.0
               numpy: 1.21.6
              pandas: 1.4.3
              jinja2: 3.1.2
               scipy: 1.6.2
              joblib: 1.1.0
             sklearn: 1.1.1
                pyod: Installed but version unavailable
            imblearn: 0.8.1
   category_encoders: 2.5.0
            lightgbm: 3.3.2
               numba: 0.55.1
            requests: 2.28.1
          matplotlib: 3.4.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.9.0
             kaleido: 0.2.1
         statsmodels: 0.12.2
              sktime: 0.11.4
               tbats: Installed but version unavailable
            pmdarima: 1.8.4
              psutil: 5.9.1
</details>

**Comment by moezali1** [comment]
@DerekKane We need more details than `code error out` to be able to help.

**Comment by moezali1** [comment]
Just tested this scenario with latest pycaret==3.0.0rc4 and it works fine.

If you are still facing issue, please feel free to open new ticket.
