### ISSUE TITLE
[BUG]: evaluate_model results don't show up in databricks

### ISSUE THREAD

**Issue by moazkh60** [pycaret/pycaret#2804]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

![eval](https://user-images.githubusercontent.com/14291374/181212611-b7add06d-0bf7-4dcd-ac73-061c43dd6983.PNG)

Please check the image this is what I get when I try to run evaluate_model in databricks. Although after this it should show me the evaluation results.

### Reproducible Example

```python
%matplotlib inline
%config InlineBackend.figure_format = 'retina' 
evaluate_model(best_model)
```

### Expected Behavior

It should show all possible classification plots.

### Actual Results

```python-traceback
Please check the image I posted above that's the output that I get
```

### Installed Versions

<details>
System:
    python: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0]
executable: /local_disk0/.ephemeral_nfs/envs/pythonEnv-1a90d712-f514-4f3c-a788-834bdb712b17/bin/python
   machine: Linux-5.4.0-1083-azure-x86_64-with-glibc2.29

PyCaret required dependencies:
                 pip: 21.0.1
          setuptools: 52.0.0
             pycaret: 3.0.0.rc3
             IPython: 7.22.0
          ipywidgets: 7.7.1
                tqdm: 4.64.0
               numpy: 1.21.6
              pandas: 1.4.3
              jinja2: 3.1.2
               scipy: 1.6.2
              joblib: 1.1.0
             sklearn: 1.1.1
                pyod: Installed but version unavailable
            imblearn: 0.8.1
   category_encoders: 2.5.0
            lightgbm: 3.3.2
               numba: 0.55.1
            requests: 2.28.1
          matplotlib: 3.4.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.9.0
             kaleido: 0.2.1
         statsmodels: 0.12.2
              sktime: 0.11.4
               tbats: Installed but version unavailable
            pmdarima: 1.8.4
              psutil: 5.9.1
</details>

**Comment by moezali1** [comment]
Unfortunately `IPython` module is not available for use in Databricks. I heard it is coming soon in future but not yet.
