### ISSUE TITLE
Save metadata with model

### ISSUE THREAD

**Issue by dre2004** [pycaret/pycaret#281]
Hi,

Is there a way to save the parameters that were passed to setup when the model is pickled?

From a pickled model I can't see a way to be able to tell what parameters were used to train the model so I have to either save that separately or try and come up with a naming convention for the saved models that capture these details.

**Comment by ramnathv** [comment]
I believe you can use `save_experiment` to save all the details. According to the [documentation](https://pycaret.org/save-experiment/)

> Saving or logging an entire experiment in PyCaret is as simple as writing save_experiment. The function saves the entire environment including transformation pipeline, models created and all the intermediary outputs as a transferable binary pickle file for later use.

**Comment by ejohnson-amerilife** [comment]
> Save / Load Experiment save_experiment and load_experiment function from pycaret.classification pycaret.regression pycaret.clustering pycaret.anomaly pycaret.nlp is removed in PyCaret 2.0

Ref: https://github.com/pycaret/pycaret/blob/f8c40ab0ccf2003823d3c397b383de61cbca65f6/CHANGELOG.md
