### ISSUE TITLE
[BUG]:  clustering.setup does not accept 'iterative' in imputation_type

### ISSUE THREAD

**Issue by tarmojuristo** [pycaret/pycaret#2810]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

clustering.setup() throws error when specifying imputation_type='iterative'

ValueError: Invalid value for the imputation_type parameter, got iterative. Possible values are: simple, iterative.

### Reproducible Example

```python
from pycaret.datasets import get_data
df = get_data('diabetes')

test = clustering.setup(
        data=df,
        imputation_type='iterative',
        )
```

### Expected Behavior

should accept 'iterative' as value

### Actual Results

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-6a1a7ff6b5f0> in <module>
      2 df = get_data('diabetes')
      3 
----> 4 test = clustering.setup(
      5         data=df,
      6         imputation_type='iterative',

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pycaret/clustering/functional.py in setup(data, ordinal_features, numeric_features, categorical_features, date_features, text_features, ignore_features, keep_features, preprocess, imputation_type, numeric_imputation, categorical_imputation, text_features_method, max_encoding_ohe, encoding_method, polynomial_features, polynomial_degree, low_variance_threshold, remove_multicollinearity, multicollinearity_threshold, bin_numeric_features, remove_outliers, outliers_method, outliers_threshold, transformation, transformation_method, normalize, normalize_method, pca, pca_method, pca_components, custom_pipeline, custom_pipeline_position, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, verbose, memory, profile, profile_kwargs)
    385     exp = _EXPERIMENT_CLASS()
    386     set_current_experiment(exp)
--> 387     return exp.setup(
    388         data=data,
    389         ordinal_features=ordinal_features,

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pycaret/internal/pycaret_experiment/unsupervised_experiment.py in setup(self, data, ordinal_features, numeric_features, categorical_features, date_features, text_features, ignore_features, keep_features, preprocess, imputation_type, numeric_imputation, categorical_imputation, text_features_method, max_encoding_ohe, encoding_method, polynomial_features, polynomial_degree, low_variance_threshold, group_features, group_names, remove_multicollinearity, multicollinearity_threshold, bin_numeric_features, remove_outliers, outliers_method, outliers_threshold, transformation, transformation_method, normalize, normalize_method, pca, pca_method, pca_components, custom_pipeline, custom_pipeline_position, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, verbose, memory, profile, profile_kwargs)
    532                 self._simple_imputation(numeric_imputation, categorical_imputation)
    533             elif imputation_type is not None:
--> 534                 raise ValueError(
    535                     "Invalid value for the imputation_type parameter, got "
    536                     f"{imputation_type}. Possible values are: simple, iterative."

ValueError: Invalid value for the imputation_type parameter, got iterative. Possible values are: simple, iterative.
```

### Installed Versions

<details>
System:
    python: 3.9.7 (v3.9.7:1016ef3790, Aug 30 2021, 16:39:15)  [Clang 6.0 (clang-600.0.57)]
executable: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
   machine: macOS-10.16-x86_64-i386-64bit

PyCaret required dependencies:
                 pip: 22.2.1
          setuptools: 57.4.0
             pycaret: 3.0.0.rc3
             IPython: 7.21.0
          ipywidgets: 8.0.0rc1
                tqdm: 4.62.0
               numpy: 1.21.6
              pandas: 1.4.3
              jinja2: 3.0.2
               scipy: 1.8.1
              joblib: 1.1.0
             sklearn: 1.1.1
                pyod: Installed but version unavailable
            imblearn: 0.9.1
   category_encoders: 2.5.0
            lightgbm: 3.3.1
               numba: 0.55.2
            requests: 2.27.1
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.6.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.11.4
               tbats: Installed but version unavailable
            pmdarima: 1.8.5
              psutil: 5.9.1</details>

**Comment by tvdboom** [comment]
Unsupervised learning only supports `imputation_type="simple"` since you need a target column to fit the estimator for `iterative`. I submitted a PR to update the error and docstrings accordingly.
