### ISSUE TITLE
[DOC]:  tutorial link problem

### ISSUE THREAD

**Issue by diligejy** [pycaret/pycaret#2814]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://pycaret.gitbook.io/docs/get-started/tutorials

### Documentation problem

When I click on the link in "Time Series Forecasting - Level Beginner", it goes to the wrong link (https://github.com/pycaret/pycaret/blob/time_series/time_series_101.ipynb) and a 404 error occurs.
<img width="983" alt="image" src="https://user-images.githubusercontent.com/40735154/182106865-d5cf9a60-e7bd-41ff-9c52-b0c43a8ee576.png">

### Suggested fix for documentation

If you change the link from  "https://github.com/pycaret/pycaret/blob/time_series/time_series_101.ipynb"" to the "https://github.com/pycaret/pycaret/blob/master/examples/TimeSeries_Forecasting.ipynb" link, it seems to be solved.

**Comment by ngupta23** [comment]
related to #2753
