### ISSUE TITLE
[ENH]: Parameter for index column in setup

### ISSUE THREAD

**Issue by jnsflt** [pycaret/pycaret#2815]
### Describe the feature you want to add to this project

Often, we use datasets which have different index columns than usual counter (0,1,2,...). For example a long identification string. In PyCaret, there is no option for setting this index column. 

Before passing in the dataframe, I can however manually set my index_column with `df.set_index("index_col")`. But this is not saved internally in PyCaret. 

Below you will find a bit messy example, creating a new index column for a standard dataset.

> import pandas as pd
import numpy as np
from pycaret.datasets import get_data
from pycaret.classification import *
df = get_data("juice", verbose=False)
size = len(df)
ind_col = ["Instance " + str(i) for i in range(size)]
df_ind = pd.DataFrame(ind_col, columns=["index_col"])
df = pd.concat([df_ind, df],axis=1)
df = df.set_index("index_col")
exp = ClassificationExperiment()
exp.setup(df, target="STORE", verbose=False)
clf = exp.create_model("rf", verbose=False)

If I then write `X_train = exp.get_config("X_train")`, I will not see my index column in the `X_train`.

This also affects `predict_model()`, since the "index_col" in the unseen dataset is just dropped.

### Describe your proposed solution

Add a parameter in `setup()` for setting an index column. This can be stored internally and when doing data preprocessing (for example with an unseen dataset), the index column can be set automatically. 

`df = df.set_index(<stored_index_column>)`

**Comment by tvdboom** [comment]
This is indeed a useful feature, however, it's not as straightforward as you may think. During preprocessing, some of the transformers may drop rows. We have to keep track of which indices are dropped (this means always working with dataframes and never with numpy arrays). This may become an issue specially when users add their own custom pipeline.

However, I think the issues can be solved so I'll give it a try and keep you updated here.
