### ISSUE TITLE
compare_models AttributeError: 'NoneType' object has no attribute 'display_id'

### ISSUE THREAD

**Issue by 64617665** [pycaret/pycaret#282]
_https://colab.research.google.com/drive/1GqQ3XAIzg4krBbnOpKyeRqT0qBQhdwYL#scrollTo=VqG1NnwXEQvK
ipython display broken on regular pycaret build as of 20200714
using pip install pycaret-nightly to get around initial bug_

from pycaret.datasets import get_data
dataset = get_data('credit')
#check the shape of data
dataset.shape
data = dataset.sample(frac=0.95, random_state=786).reset_index(drop=True)
data_unseen = dataset.drop(data.index).reset_index(drop=True)

print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions: ' + str(data_unseen.shape))
from pycaret.classification import *
exp_clf101 = setup(data = data, target = 'default', session_id=123) 
compare_models()

  File "...\Python36\lib\site-packages\pycaret\classification.py", line 4283, in compare_models

AttributeError: 'NoneType' object has no attribute 'display_id'

**Comment by 64617665** [comment]
exp_clf101 = setup(html = False, data = data, target = 'default', session_id=123) 

per previous github issues,

I suggest adding this to your tutorials as a note.

**Comment by neuratree** [comment]
I faced the same issue, seems like a common one when running the code from command line.

@pycaret  : Better to add this to your tutorials docs
