### ISSUE TITLE
[INSTALL]: Unable to use pycaret after installation

### ISSUE THREAD

**Issue by fawad-mahdi** [pycaret/pycaret#2822]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

ImportError: Missing optional dependency 'Jinja2'. DataFrame.style requires jinja2. Use pip or conda to install Jinja2.

### Installation Method

pip install

### pycaret Version

latest

### Python Version

3.7.6

### Description

installing pycaret is giving error of installing dependencies. If I restart my python IDEs, they fail to start citing multiple errors after installing pycaret. 

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by ngupta23** [comment]
The latest version has jinja2 as a dependency so it should be installed.

https://github.com/pycaret/pycaret/blob/9ca12a1eb19683508f8c2d9f03fe22fdfbb0f0f7/requirements.txt#L7

Can you try the following to see if it helps (create a clean environment).

`pip install --pre pycaret`

**Comment by fawad-mahdi** [comment]
Ive reinstalled Jinja2. Created a fresh environment and interestingly after
installing all dependcies jupyter notebook fails to reopen. Have to
uninstall anaconda completely and reinstall. Strange behaviour

**Comment by ngupta23** [comment]
I don't think there is any issue with pycaret here. And installing pycaret in a conda environment should not corrupt conda or prevent you from opening jupyter. There must be some other issue.

**Comment by celestinoxp** [comment]
Hi,

The problem may be from python 3.7 (no longer recommended).

I suggest, you create a new environment with python 3.8 or python 3.9.
