### ISSUE TITLE
[BUG]: azureml experiment registry organization

### ISSUE THREAD

**Issue by alejandroLlorentePiperLab** [pycaret/pycaret#2823]
### pycaret version checks

- [x] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

When AzureML is used as MLFlow server, the structure of the results is wrong because all the different items are nested as sub-jobs inside the main one.

For instance:

- We do the initilization of MLFlow server with the tracking URL from AzureML.
- Create the environment for a classification experiment: load the data and setup.
- We do "compare_models" after setup (only with three models just to test).
- We select the best model and we finalize and save it.

In AzureML results are stored in the following nested way:
- Experiment
    - Job for the best model
      - Job for the first model in compare_models
        - Job for the second model in compare_models
          - Job for the third model in compare_models

![image](https://user-images.githubusercontent.com/110598708/182811571-e9622040-2d78-4918-95cb-be917561b5dd.png)

IMHO the structure should be something like:
- Experiment
  - Job for the best model
  - Job for the all the models in compare_models, showing the comparison

### Reproducible Example

```python
import mlflow

region = "<YOUR REGION HERE>"
subscription_id = '<YOUR SUBSCRIPTION ID HERE>'
resource_group = '<YOUR RESOURCE GROUP HERE>'
workspace_name = '<YOUR WORKSPACE NAME HERE>'
experiment_name = 'mlops_experimentpycaret'

azureml_mlflow_uri = f"azureml://{region}.api.azureml.ms/mlflow/v1.0/subscriptions/{subscription_id}/resourceGroups/{resource_group}/providers/Microsoft.MachineLearningServices/workspaces/{workspace_name}"
mlflow.set_tracking_uri(azureml_mlflow_uri)

from pycaret.datasets import get_data
data = get_data('credit')

# initialize setup
from pycaret.classification import *

s = setup(data, target = 'default',
          log_experiment=True,
          experiment_name=experiment_name,
          log_plots=True,
          log_profile=True,
          log_data=True,
          session_id=1234,
          silent=True,
          verbose=True)

# compare all models
bests = compare_models(include=['dt','lr','nb'],n_select=3)
best = bests[0]
# check feature importance
plot_model(best, plot = 'feature')
# finalize the model
final_best = finalize_model(best)
# save model to disk
save_model(final_best, 'credit-pipeline')
```

### Expected Behavior

IMHO the structure in AzureML should be something like:
- Experiment
  - Job for the best model
  - Job for the all the models in compare_models, showing the comparison

### Actual Results

```python-traceback
No execution errors
```

### Installed Versions

'2.3.10'

**Comment by moezali1** [comment]
@alejandroLlorentePiperLab This issue was fixed recently. Can you please try rc4 version.

https://github.com/pycaret/pycaret/issues/2975
