### ISSUE TITLE
[ENH]: Reorder all utilities and tests

### ISSUE THREAD

**Issue by tvdboom** [pycaret/pycaret#2827]
### Describe the feature you want to add to this project

* I noticed we have `pycaret\internal\pycaret_experiment\utils.py`, `pycaret/internal/utils.py` and `pycaret/utils`. We should move everything to `pycaret/utils` imo.
* We have `pycaret/tests` and `pycaret/internal/tests`. Not sure what the latter does. Can it be moved/removed?
* I suggest to move the whole tests directory outside of the code base. Leave it in the root folder. I think this is best practice.

Let me know your thoughts.

### Describe your proposed solution

..

**Comment by ngupta23** [comment]
> * We have `pycaret/tests` and `pycaret/internal/tests`. Not sure what the latter does. Can it be moved/removed?

`pycaret/internal/tests` refers to statistical tests used in the code and modeling building process. That is different from `pycaret/tests` which are the unit tests. As such, the statistical tests should not be changed/altered in my opinion.

> I noticed we have pycaret\internal\pycaret_experiment\utils.py, pycaret/internal/utils.py and pycaret/utils. We should move everything to pycaret/utils imo.

I noticed the same thing when developing time series. I started consolidating any new utils that I was developing into `pycaret/utils`. I agree, we need to consolidate old/legacy utils into this module as well.

> I suggest to move the whole tests directory outside of the code base. Leave it in the root folder. I think this is best practice.

I am ok with this.
