### ISSUE TITLE
[BUG]: `outliers_method` setup() got an unexpected keyword argument 'outliers_method'

### ISSUE THREAD

**Issue by Prashavu** [pycaret/pycaret#2828]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

setup() is no longer taking 'outliers_method' as a paramter .

### Reproducible Example

```python
from pycaret.regression import *
reg=setup(data=df1,target ='target',silent=True, session_id=123, verbose=False,html=False,remove_outliers=True,data_split_shuffle=True,remove_multicollinearity=True,feature_selection=True,outliers_method='iforest')
```

### Expected Behavior

Should not throw an error

### Actual Results

```python-traceback
TypeError: setup() got an unexpected keyword argument 'outliers_method'
```

### Installed Versions

<details>
'2.3.10'
</details>

**Comment by tvdboom** [comment]
Which version of pycaret are you using? You should install the pre-release version to use this parameter: `pip install --pre pycaret`

**Comment by Prashavu** [comment]
Yes this version mentioned solved the issue
