### ISSUE TITLE
[INSTALL]: pip-compile dependency hell

### ISSUE THREAD

**Issue by JamesMcGuigan** [pycaret/pycaret#2837]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Linux-5.10.133+-x86_64-with-debian-bullseye-sid

### Installation Method

pip install

### pycaret Version

All

### Python Version

3.7.12

### Description

The basic issue is that I am running into dependency hell when attempting to create a self-consistent set of dependencies for pycaret using pip-tools pip-compile.

**What I Expect To Happen:**
- pip-tools pip-compile should successfully resolve a set of pinned dependencies for pycaret

**What Actually Happened**
The first one is usually that it can't find a compatible version of scikit-learn. 

Additionally:
- llvmlite is sometimes required to be specified as a manual dependency #2807 
- Numba sometimes has a hidden dependency on numpy<=1.20

### Installation Logs

I have setup a testbed example of this issue as a Kaggle notebook, showing pip-compile failing to resolve on most recent version of PyCaret:
- https://www.kaggle.com/code/jamesmcguigan/bug-report-pycaret-pip-compile-dependency-hell/

**Comment by celestinoxp** [comment]
Hi @JamesMcGuigan ,

i don't understand what you want to do... install pycaret with all dependencies? full pycaret?

Suggestion: 
Python 3.7 is no longer advisable, use python 3.8 or python 3.9 instead.

The ideal is:
python 3.8 to pycaret 2.3.10 
python 3.9 to pycaret 3.0rc3 (recommended)
Note: To install new python do it in a new clean environment, to avoid conflicts with packages.

To install latest pycaret use `pip install --pre pycaret`

**Comment by ngupta23** [comment]
Just a follow-up (unrelated to the original question): You can still use python 3.7. All our tests pass in it. See more details here if needed: https://github.com/pycaret/pycaret/issues/2862. That being said, since 3.7 is getting old, if there is an option, use 3.8 or 3.9 instead.

**Comment by JamesMcGuigan** [comment]
Thank you, the suggestion to use `pip install --pre pycaret` seems to work and I have successfully managed to get PyCaret working inside the Kaggle Competition environment, which currently puts PyCaret in 1213/1718'th place for the Aug 2022 Tabular Playground Series competition.
- https://www.kaggle.com/code/jamesmcguigan/tps-pycaret3-automl-classification-aug-2022

Still have issues rerunning my old notebook using PyCaret v2 from Feb 2021, but this is less relevant now. 
- https://www.kaggle.com/code/jamesmcguigan/tps-pycaret2-automl-regression-feb-2021

I finally have an updated code demo of PyCaret v3 working on Kaggle. Any suggestions for how to improve these notebooks would be welcome.
