### ISSUE TITLE
No plots with unsupervised learning

### ISSUE THREAD

**Issue by robert-hoyt** [pycaret/pycaret#285]
I have uploaded a file with all numerical values and wanted to run k-means to identify clusters. Based on tutorials I have gotten as far as kmean_results = assign_model(kmeans)
kmean_results.head() and it displays the rows and columns with the new column "clusters". 

When I try to generate any of the plots with e.g. plot_model(kmeans, plot = 'distribution') no plots are generated. I'm not sure what the problem is

**Comment by g0lemXIV** [comment]
Have You got any error or warning message? If no, where You want to run the model? In Jupyter notebook, JupyterLab, Google Colab?

**Comment by robert-hoyt** [comment]
This was run in a Jupyter Lab. 

![image](https://user-images.githubusercontent.com/45010139/87701400-8b3ae480-c75d-11ea-8f82-af06295f20c5.png)

**Comment by g0lemXIV** [comment]
Can you try running it on Jupiter notebook, if it will be working then try to install Plotly extension for JupyterLab like [here](https://medium.com/analytics-vidhya/get-started-with-plotly-jupyter-lab-b280ddcc6008)

**Comment by robert-hoyt** [comment]
Here is what happened
Collecting plotly
  Downloading https://files.pythonhosted.org/packages/bf/5f/47ab0d9d843c5be0f5c5bd891736a4c84fa45c3b0a0ddb6b6df7c098c66f/plotly-4.9.0-py2.py3-none-any.whl (12.9MB)
     |████████████████████████████████| 12.9MB 6.0MB/s eta 0:00:01
Requirement already satisfied, skipping upgrade: six in /Applications/anaconda3/lib/python3.7/site-packages (from plotly) (1.12.0)
Requirement already satisfied, skipping upgrade: retrying>=1.3.3 in /Applications/anaconda3/lib/python3.7/site-packages (from plotly) (1.3.3)
ERROR: pycaret 1.0.0 has requirement plotly==4.4.1, but you'll have plotly 4.9.0 which is incompatible.
ERROR: pycaret 1.0.0 has requirement yellowbrick==1.0.1, but you'll have yellowbrick 1.1 which is incompatible.
Installing collected packages: plotly
  Found existing installation: plotly 4.4.1
    Uninstalling plotly-4.4.1:
      Successfully uninstalled plotly-4.4.1
Successfully installed plotly-4.9.0
Note: you may need to restart the kernel to use updated packages.

**Comment by robert-hoyt** [comment]
I was able to get a plot in Jupyter Notebook, but not Jupyter Lab
