### ISSUE TITLE
[BUG]: Timeseries model fails if we use the parameter use_gpu

### ISSUE THREAD

**Issue by bhishanpdl** [pycaret/pycaret#2857]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I suspect this is a possible bug.
I have installed cuda and successfully ran xgboost, lightgbm and catboost with GPU support.

But, when I tried to run timeseries modelling with pycaret3.0 (latest version as of 2022-08-16), I ran into following error:

```python
File  XXXXX\venv\py310\lib\site-packages\pycaret\containers\models\time_series.py:2416, in CatBoostCdsDtContainer.__init__(self, experiment)
   2411 def __init__(self, experiment) -> None:
   2412     # suppress output
   2413     logging.getLogger("catboost").setLevel(logging.ERROR)
   2415     self.use_gpu = experiment.gpu_param == "force" or (
-> 2416         experiment.gpu_param and len(experiment.X_train) >= 50000
   2417     )
   2419     super().__init__(experiment=experiment)

TypeError: object of type 'NoneType' has no len()
```

The error is caused by `experiment.X_train`, there is no X_train attribute in timeseries, we have only `experiment.y_train`.

# Fix
I did a monkey patching by directly changing the line:
```
From:
 len(experiment.X_train) >= 50000

To:
 len(experiment.y_train) >= 10

```

### Reproducible Example

```python
exp = TSForecastingExperiment()
_ = exp.setup(data=tdf['y_true'],
              fh=30, # 30 days
              fold=3,
              verbose=True,
              html=True,
              use_gpu=True,
              session_id=42
             )
```

### Expected Behavior

No error.

### Actual Results

```python-traceback
File XXXX\venv\py310\lib\site-packages\pycaret\containers\models\time_series.py:2416, in CatBoostCdsDtContainer.__init__(self, experiment)
   2411 def __init__(self, experiment) -> None:
   2412     # suppress output
   2413     logging.getLogger("catboost").setLevel(logging.ERROR)
   2415     self.use_gpu = experiment.gpu_param == "force" or (
-> 2416         experiment.gpu_param and len(experiment.X_train) >= 50000
   2417     )
   2419     super().__init__(experiment=experiment)

TypeError: object of type 'NoneType' has no len()
```

### Installed Versions

<details>
$ pip show pycaret
Name: pycaret
Version: 3.0.0rc2
Summary: PyCaret - An open source, low-code machine learning library in Python.
Home-page: https://github.com/pycaret/pycaret
Author: Moez Ali
Author-email: moez.ali@queensu.ca
License: MIT
Location: c:\users\a126291\onedrive - amerisourcebergen(abc)\venv\py310\lib\site-packages
Requires: category-encoders, imbalanced-learn, ipython, ipywidgets, jinja2, joblib, kaleido, lightgbm, matplotlib, numba, numpy, pandas, plotly, pmdarima, psutil,
 pyod, requests, schemdraw, scikit-learn, scikit-plot, scipy, sktime, statsmodels, tbats, tqdm, yellowbrick
Required-by:

</details>

**Comment by celestinoxp** [comment]
Hi @bhishanpdl,

2 suggestions: 
- If you are using python 3.10, you should python 3.9 (create new clean environment to avoid conflicts with packages).
- Please update your pycaret version from rc2 to rc3. You can use `pip install --upgrade --pre pycaret`
 
If problem pesrsists, you can post new errors here

**Comment by ngupta23** [comment]
I never tested this argument since none of the models can leverage GPU (well maybe regression based - but I will have to check). I will look into it and get back.

**Comment by bhishanpdl** [comment]
The error originally originated when by mistake I used model name “catboost” instead of “catboost_cds_dt” when using “use_gpu=True” but still I assumed it’s a bug. The code failed when used that parameter and ran well if we omit that parameter.

Part 2:
Thanks for Python 3.9 suggestion. I will create new venv and use py39

For now, the monkey patch is working fine with Py310.
