### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by sedy2014** [pycaret/pycaret#287]
I am using anaconda environment , on windows with pycaret installed,and pycharm. i want to run a basic toy example with pycaret (not using freely available datasets), as a simple y=mx+c, where x is 1-d
```

import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd
x= np.arange(0,1000,dtype = 'float64')
Y = (x*2) + 1
data1 = np.vstack((x,Y)).transpose()
# create dataframe as required by Pandas
N= data1.shape[0]
# add first row
dat2 = np.array(['','Col1','Col2'])
for i in range(N):
    dat_row = list(data1[i,:].flatten())
    nm = ['row'+ str(i)]
    dat_row = nm + dat_row
    dat2 = np.vstack ((dat2, dat_row) )

df= pd.DataFrame(data=dat2[1:,1:],
                  index=dat2[1:,0],
                  columns=dat2[0,1:])
print(df)
print('***************************')
columns = df.applymap(np.isreal).all()
print(columns)
print('***************************')
# now, using Pycaret
from pycaret.regression import *
exp_reg = setup(df, html= False,target='Col2')
print('********************************')
compare_models()
```
this gives error:
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process.
I was able to copy this into Jupyter notebook and have no errors. 

any ideas?
sedy

**Comment by hartungalex24** [comment]
I am having the same problem here. However, I am having the issue on Jupyter Notebook and it has persisted after multiple kernel and computer restarts.

**Comment by SzQaNinja** [comment]
Also seeing the same error when trying to use blend_model(method='soft')...  have been using the same data for lots of other work all week, this seems strictly related to the blend_model function for me.

**Comment by pycaret** [comment]
@SzQaNinja @sedy2014 Can you try passing `n_jobs` as `None` in `setup`. By default its set to `-1`

**Comment by pycaret** [comment]
@SzQaNinja @sedy2014 Can you please confirm if you were able to resolve the issue?

**Comment by sedy2014** [comment]
Yes,
it is working now. even without making the change you suggested. I didn't do anythings special other than re-installing pycaret.
