### ISSUE TITLE
[BUG]: fix_imbalance_mothod and fix_imbalance does not seem to work in 3.0.0rc

### ISSUE THREAD

**Issue by Prashavu** [pycaret/pycaret#2871]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

 fix_imbalance_mothod and fix_imbalance does not eem to work as with or without the results are coming out to be the same which should not be happening for a highly imbalanced dataset where 1:0 is 20:80 p.
Also we are not able to see the transformed dataset post setup from get_config('X_train'). I can see only the original untransformed data.

### Reproducible Example

```python
from imblearn.over_sampling import *
adasyn1 = ADASYN(sampling_strategy='all')
from pycaret.datasets import get_data
juice = get_data('juice')
from pycaret.classification import *
exp_name = setup(data = juice,  target = 'Purchase',fix_imbalance=True,fix_imbalance_method=adasyn1)
```

### Expected Behavior

Need to get  the resampled and transformed dataframe.

### Actual Results

```python-traceback
No error , but not functioning as intended
```

### Installed Versions

<details>
3.0.0rc.
</details>

**Comment by tvdboom** [comment]
This works as expected in `master` and it should work from the latest rc release as well. Make sure to download the latest release or directly from master using `pip install -U git+https://github.com/pycaret/pycaret.git@master`

**Comment by Prashavu** [comment]
@tvdboom  are you able to view and get the resampled dataset?

**Comment by tvdboom** [comment]
I think you are using an older version of pycaret that indeed had issues with resampling. Are you sure it's 3.0.0rc3? Can you share the result of `pycaret.__version__`?

**Comment by tvdboom** [comment]
As I said, on master it's working as expected. I can see the resampling being done and get_config('X_train') returns the transformed train set.

**Comment by celestinoxp** [comment]
Note: as the latest release is rc3 and the version that is on master is rc3, you must uninstall pycaret first and then install the version that is on master through pip install -U git+https://github.com/pycaret /pycaret.git@master
