### ISSUE TITLE
[DOC]: Broken Link on top of Google recommendation

### ISSUE THREAD

**Issue by nprime496** [pycaret/pycaret#2874]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

Here is the link proposed by Google for [predict_model](https://www.google.com/search?q=predict_model+pycaret&oq=predict_model+pycaret&aqs=chrome..69i57j69i60l3.5658j0j4&sourceid=chrome&ie=UTF-8)

### Documentation problem

Google Search Engine seems to consider that documentation links hosted at https://pycaret.org/ but it seems like all documentation was moved to https://pycaret.gitbook.io/docs/.

It's not a problem in the documentation per se but it can be quite annoying. For example, I found myself dealing with these redirection everytime I tried to search for something, the latter site is not even in propositions. Plus, the redirection on gitbook send back to homepage, forcing us to search for the topic again. 

### Suggested fix for documentation

* Improve SEO to make clear that https://pycaret.org is not documentation host (or make search available gitbook site)
* Provide meaningful redirection instead of  redirecting on https://pycaret.gitbook.io/docs/ homepage

**Comment by ngupta23** [comment]
> Improve SEO to make clear that https://pycaret.org/ is not documentation host (or make search available gitbook site)

This would be ideal but we don't know how to do this. Do you know how to do it?

> Provide meaningful redirection instead of redirecting on https://pycaret.gitbook.io/docs/ homepage

Why is redirection to https://pycaret.gitbook.io/docs/ not meaningful? It is the one-stop for all things related to `pycaret`. You can use the search bar on that page to navigate anywhere on that website.

**Comment by nprime496** [comment]
For Google referencement, I don't know either, but the problem is most of the time related to SEO. What I noticed though is that searching for [preprocess pycaret](https://www.google.com/search?q=preprocess+pycaret&oq=preprocess+pycaret&aqs=chrome.0.69i59j69i60l3.5481j0j9&sourceid=chrome&ie=UTF-8) gives a result with the right documentation host in search results.

About redirection, it is useful yes! Just that the redirect link always open on **homepage**, it would not really be a problem if we could access the gitbook site directly (easily) from google.

**Comment by moezali1** [comment]
@nprime496 and all. Its a fair point but I don't know how to fix this from SEO perspective. Originally all the documentation was hosted on pycaret.org and when I move them over to Gitbook I thought I will create a redirect instead of removing the pages. Maybe removing the page will delink it from Google SEO algorithm. I will try that in few months.
