### ISSUE TITLE
[BUG]: TypeError: setup() got an unexpected keyword argument 'feature_interaction' (V 3.0.0r)

### ISSUE THREAD

**Issue by pepeto** [pycaret/pycaret#2879]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I have the version 3.0.0.rc2 and I have followed the example found in the official website:
https://pycaret.gitbook.io/docs/get-started/preprocessing/feature-engineering

And I receive and error message:
TypeError: setup() got an unexpected keyword argument 'feature_interaction'

Maybe the 3.0.0.rc2 version has a difference. 
Thank you.

### Reproducible Example

```python
# load dataset
from pycaret.datasets import get_data
insurance = get_data('insurance')

# init setup
from pycaret.regression import *
reg1 = setup(data = insurance, target = 'charges', feature_interaction = True, feature_ratio = True)
```

### Expected Behavior

..

### Actual Results

```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
D:\TEMP\ipykernel_59488\3904441581.py in <cell line: 7>()
      5 # init setup
      6 from pycaret.regression import *
----> 7 reg1 = setup(data = insurance, target = 'charges', feature_interaction = True, feature_ratio = True)

TypeError: setup() got an unexpected keyword argument 'feature_interaction'
```

### Installed Versions

'3.0.0.rc2'

**Comment by moezali1** [comment]
@tvdboom

**Comment by celestinoxp** [comment]
Just as https://github.com/pycaret/pycaret/issues/2585, the problem here is the documentation. The feature_interaction and trigonometry_features are deprecated in version 3.0. The documentation needs to be updated accordingly. For now, it's best if you look at the docstrings in github's code.

**Comment by pepeto** [comment]
@celestinoxp thank you for the answer. Were these deprecated features replaced, or were these functionalities lost?
THANK YOU!

**Comment by tvdboom** [comment]
Please search in the closed issues for your question before opening a new one. This has already been answered in #2675 and #2586.

> This argument was replaced with polynomial_features because it didn't had a direct sklearn implementation. Refer to the docstrings to see the parameters for 3.0.0rc until the official docs are updated
