### ISSUE TITLE
[BUG]: Display progress bar not displaying in 3.0.0.rc3 and ipywidgets 8.0.1 / python=3.8.13

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#2881]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Display progress bar not displaying in 3.0.0.rc3 and ipywidgets 8.0.1 / python=3.8.13

### Reproducible Example

```python
.
```

### Expected Behavior

Display progress bar should show.

### Actual Results

```python-traceback
Display progress bar not displaying in 3.0.0.rc3 and ipywidgets 8.0.1 / python=3.8.13
```

### Installed Versions

3.0

**Comment by ngupta23** [comment]
Per August 29th meeting, @Yard1 to look into it.

**Comment by moezali1** [comment]
The issue is fixed as per latest merge by @tvdboom on 30/8/2022, hence closing.
