### ISSUE TITLE
[BUG]: Why deepchecks is not installed with pycaret[full]

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#2882]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Why `deepchecks` is not installed with `pycaret[full]`? `autoviz` `explainerdashboard`  all of them are installed but not `deepchecks`. Is there a specific reason to this?

### Reproducible Example

```python
.
```

### Expected Behavior

deepchecks should be installed with pycaret[full].

### Actual Results

```python-traceback
Not getting installed.
```

### Installed Versions

3.0

**Comment by ngupta23** [comment]
Per August 22nd, @tvdboom  will

- [ ] add it to MLOps section in requirements-optional.
- [ ] Add optional library check for `deepchecks` in the code where this library is referenced.

**Comment by tvdboom** [comment]
Done in #2866

**Comment by moezali1** [comment]
Will not be done because deepchecks is not yet compatible with latest version of plotly. deepchecks is pinned to plotly==5.5.0 and some other dependencies of pycaret requires the latest version. Hence `deepchecks` is skipped from requirements until that is sorted.

**Comment by ItayGabbay** [comment]
Hey @moezali1 
Deepchecks maintainer here. Just letting you guys know we've finally released a new version (0.9.2) that relaxes this strict plotly requirement. Deepchecks is now compatible with the latest version of plotly.

**Comment by tvdboom** [comment]
@ItayGabbay Thanks for the update. I added the dependency in #3070
