### ISSUE TITLE
[BUG]: create_api function is not creating file correctly

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#2883]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

`create_api` function is not creating file correctly. Notice all the indent:

![image](https://user-images.githubusercontent.com/54699234/185670879-41101d92-c8cf-4957-85cb-7d95e2a651d2.png)

### Reproducible Example

```python
.
```

### Expected Behavior

.

### Actual Results

```python-traceback
.
```

### Installed Versions

3.0

**Comment by celestinoxp** [comment]
I have related that here https://github.com/pycaret/pycaret/issues/2803
