### ISSUE TITLE
[BUG]: why boto3 is not installed with pycaret[full] in 3rc

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#2885]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Why boto3 is not installed with pycaret[full] in 3rc

### Reproducible Example

```python
..
```

### Expected Behavior

..

### Actual Results

```python-traceback
..
```

### Installed Versions

3.0

**Comment by ngupta23** [comment]
Per August 22nd, @tvdboom will

- [ ]  add it to "MLOps" section in requirements-optional.
- [ ]  Add optional library check for boto3 in `deploy_model` in the code where this library is referenced.

**Comment by tvdboom** [comment]
Done in https://github.com/pycaret/pycaret/pull/2866
