### ISSUE TITLE
[ENH][BUG]: Pycaret should detect version of pickle files

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#2886]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

This issue (https://github.com/pycaret/pycaret/issues/2880#issuecomment-1221045683) gave me the idea for pycaret to know how to differentiate a pickle file created in different versions, that is, in case of different versions pycaret should show a related error message. This would save people from having to open issues.

### Reproducible Example

```python
.
```

### Expected Behavior

.

### Actual Results

```python-traceback
.
```

### Installed Versions

<details>
Replace this line with the output of the version code above.
</details>

**Comment by tvdboom** [comment]
This has already been implemented in #2751
