### ISSUE TITLE
CatBoost error with plot_model() and evaluate_model()

### ISSUE THREAD

**Issue by Joydeep75** [pycaret/pycaret#289]
1. 
#=================== Code with with plot_model ===================
plot_model(estimator = tuned_catbst_0) # OR plot_model(estimator = tuned_catbst_0, plot = 'AUC') # OR plot_model(estimator = tuned_catbst_0, plot = 'learning'

=============  ERROR Received with plot_model() ===================
_# An exception has occurred, use %tb to see the full traceback.
# SystemExit: (Estimator Error): CatBoost estimator 
#         is not compatible with plot_model function, try using Catboost with interpret_model instead._

2. **#=================== Code with with evaluate_model ===================**
evaluate_model(tuned_catbst_0)

=============  ERROR Received with evaluate_model() ===================
_---------------------------------------------------------------------------
SystemExit                                Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/ipywidgets/widgets/interaction.py in update(self, *args)
    254                     value = widget.get_interact_value()
    255                     self.kwargs[widget._kwarg] = value
--> 256                 self.result = self.f(**self.kwargs)
    257                 show_inline_matplotlib_plots()
    258                 if self.auto_display and self.result is not None:

/opt/conda/lib/python3.7/site-packages/pycaret/classification.py in plot_model(estimator, plot)
   2644     #exception for CatBoost
   2645     if 'CatBoostClassifier' in str(type(estimator)):
-> 2646         sys.exit('(Estimator Error): CatBoost estimator is not compatible with plot_model function, try using Catboost with interpret_model instead.')
   2647 
   2648     #checking for auc plot

SystemExit: (Estimator Error): CatBoost estimator is not compatible with plot_model function, try using Catboost with interpret_model instead._

**Comment by pycaret** [comment]
@Joydeep75  Thanks. I tried to put a clear message as an exit.

SystemExit: (Estimator Error): CatBoost estimator is not compatible with plot_model function, try using Catboost with interpret_model instead._

Unfortunately catboost is not compatible with our plotting API.

**Comment by Joydeep75** [comment]
I understand and I have used `interpret_model()`. But the output functionality of  `plot_model()` and `interpret_model()` are both different. Hence `interpret_model()` is not THAT helpful as 'plot_model()'. Moreover, `evaluate_model()` is also based on `plot_model()`. So is there any other way to get the functionalities of 'plot_model()' for CatBoost?
