### ISSUE TITLE
[INSTALL]: PyCaret [Full]

### ISSUE THREAD

**Issue by sumantabasak** [pycaret/pycaret#2904]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Kaggle

### Installation Method

pip install

### pycaret Version

Latest

### Python Version

3.8

### Description

I'm using Kaggle platform, and unable to install PyCaret due to dependency issues. 

"ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by ngupta23** [comment]
Please check out the existing issues for how to solve this

https://github.com/pycaret/pycaret/issues?q=label%3Akaggle+is%3Aclosed

**Comment by AbdulJabbar64** [comment]
You can use like this, I have got same error like your error but solved it 

``pip install pycaret --ignore-installed llvmlite`` 
@sumantabasak #1710
