### ISSUE TITLE
[INSTALL]: Time Series installation

### ISSUE THREAD

**Issue by nunon** [pycaret/pycaret#2905]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic

### Installation Method

pip install

### pycaret Version

ts-alpha

### Python Version

3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0]

### Description

I cannot run any of the time series tutorials on Google Colab.
Tried mutliple installations, like: !pip install pycaret-ts-alpha
But I always get an error: ImportError: Missing optional dependency 'Jinja2'. DataFrame.style requires jinja2. Use pip or conda to install Jinja2.

Here is the link to the colab:
https://colab.research.google.com/drive/1zuhMDv28foInmcNnGtio5TQWdgAhhCgs?usp=sharing

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by ngupta23** [comment]
We have merged the time series module with the main pycaret module and also simplified the dependencies. So you can simply install as follows. Let me know if you have any issues with this

`pip install --pre pycaret`

**Comment by nunon** [comment]
Thank you so much, it now installs without issues.
The plots do not show, though:
![image](https://user-images.githubusercontent.com/4312852/186365404-104e0b21-756f-4d72-9369-63cc8a507137.png)
There are lots of warnings concerning the EDA, as you may see in the notebook.
I'm trying pip install catboost

**Comment by nunon** [comment]
I have added to the top of my notebook:

`from pycaret.utils import enable_colab
enable_colab()`

The plots are now displaying!

**Comment by ngupta23** [comment]
@nunon Thanks for confirming

@Yard1 @tvdboom I think we have removed `enable_colab` in unreleased version. Maybe we should add it back?

**Comment by Yard1** [comment]
It should not be required. I'll take a look when I have a moment as to why it's not working out of the box.

**Comment by ngupta23** [comment]
> It should not be required. I'll take a look when I have a moment as to why it's not working out of the box.

OK, thanks. I will close this since the original issue is resolved. I opened a separate one for the rendering issue.

@nunon FYI... In the time series setup function, there is another option to specify the renderer (so even if `enable_colab` is deprecated, you should be able to set the renderer). See docstring for details: 

https://github.com/pycaret/pycaret/blob/f93e7087a671458a20bed6dd3a8bcca891034cfc/pycaret/time_series/forecasting/oop.py#L1529
