### ISSUE TITLE
Plots not being rendered in Google Colan

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#2911]
@nunon Thanks for confirming

@Yard1 @tvdboom I think we have removed `enable_colab` in unreleased version. Maybe we should add it back?

_Originally posted by @ngupta23 in https://github.com/pycaret/pycaret/issues/2905#issuecomment-1225614830_

**Comment by moezali1** [comment]
I just tried and plots are being displayed fine.

https://colab.research.google.com/drive/1xlJVr8mklXwTnUlCwti6LfBKA6SPjLzW?usp=sharing
