### ISSUE TITLE
[BUG]: eda() not interactive in VSCode

### ISSUE THREAD

**Issue by ingluissantana** [pycaret/pycaret#2927]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

The eda() plots are not interactive in VSCode

### Reproducible Example

```python
eda()
%matplotlib inline
```

### Expected Behavior

interactive plots

### Actual Results

```python-traceback
no traceback is just not interactive
```

### Installed Versions

<details>
pycaret 2.3.10
</details>

**Comment by ngupta23** [comment]
Dont know for sure, but try putting `%matplotlib inline` before calling `eda()`

**Comment by ngupta23** [comment]
Other option would be to try with the latest prerelease version of pycaret to see if it works for you.

```bash
pip install --pre pycaret
```

**Comment by moezali1** [comment]
This has to do with `bokeh` support for VS code. The underlying library we use to support `eda` function uses `bokeh` underneath and bokeh is not yet interactive on VS code. 

Unfortunately nothing can be done here from our end. sorry.
