### ISSUE TITLE
[BUG]: `imputation_type` cannot be set to none 

### ISSUE THREAD

**Issue by Prashavu** [pycaret/pycaret#2928]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

After the latest update I am unable to set `imputation_type` = None.
I do not have any NaNs in my dataframe and I should be able to turn off imputation where I dont need it.

### Reproducible Example

```python
from pycaret.datasets import get_data
juice = get_data('juice')
from pycaret.classification import *
exp_name = setup(data = juice,  target = 'Purchase')

Here the default value of `imputation_type` is simple, but I do not want any imputation . How do I turn it off
```

### Expected Behavior

NA

### Actual Results

```python-traceback
NA
```

### Installed Versions

<details>
2.3.10
</details>

**Comment by tvdboom** [comment]
Use the latest rc version: `pip install --pre pycaret` and set `imputation_type=None`
