### ISSUE TITLE
[BUG]: engines parameter in compare_models

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#2930]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

engine parameter in the `compare_models` function is named as `engines` instead of `engine`. I get the idea that `compare_models` is different than `create_model` as such it can take a `dict` of {`model` : `engine`}, however for consistency I suggest we should still name the parameter as `engine`.

Thoughts?

### Reproducible Example

```python
see above
```

### Expected Behavior

see above

### Actual Results

```python-traceback
see above
```

### Installed Versions

3.0rc3

**Comment by tvdboom** [comment]
I agree. I'll make the changes

**Comment by tvdboom** [comment]
apparently we use the `engines` parameter almost everywhere except `create_model`. Still, I agree that we should use a single name for consistency. I'll stick to engine (singular) and change it everywhere
