### ISSUE TITLE
[BUG]: weights only avialbale for blend_models

### ISSUE THREAD

**Issue by Prashavu** [pycaret/pycaret#2931]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

This is more to understand why `weights` parameter( I understand this is to give class(0/1) weights)equivalent to `class_weights` that we have in log_reg /few boosting models, is only available only for `blend_models` as per documentation?
This should be made available for `create_model` and `tune_model` imo.
If not I would like to understand what is `weights` paramater in `blend_models`

### Reproducible Example

```python
from pycaret.datasets import get_data
juice = get_data('juice')
from pycaret.classification import *
exp_name = setup(data = juice,  target = 'Purchase')
lr = create_model('lr')
tuned_lr = tune_model(lr1,optimize = 'F1',return_train_score=True)
how can we give `class_weights` / `weights` here `tune_model`/`create_model`
```

### Expected Behavior

NA

### Actual Results

```python-traceback
NA
```

### Installed Versions

installed from wheel
3.0.0.rc3
</details>

**Comment by Prashavu** [comment]
I tried using this but still wont work
![image](https://user-images.githubusercontent.com/13661149/187861539-4225814e-60e8-472a-9c43-8738a076dc68.png)

**Comment by moezali1** [comment]
@Prashavu You can pass `class_weight` parameter in the `create_model` it self. Example:

```
lr = create_model('lr', class_weight = {0 : 1, 1: 9})
```

If you want to pass sample_weight you have to use fit_kwargs. Like this:

```
lr = create_model('lr', fit_kwargs = {'sample_weight' : list_of_weights})
```

Hope this helps.
