### ISSUE TITLE
[BUG]: Cluster PCA plot and TSnE not showing

### ISSUE THREAD

**Issue by messaoudia** [pycaret/pycaret#2934]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Hello guys

Unfortunately I  was not able to found another common issue, maybe I missed something but I can't display those plots.

![Screenshot 2022-09-02 at 17 26 23](https://user-images.githubusercontent.com/4719434/188182734-8de8e070-aa8e-4201-8376-f3532011b4fe.png)

![Screenshot 2022-09-02 at 17 25 54](https://user-images.githubusercontent.com/4719434/188182645-82b8d177-d4f6-49e6-82f9-90e2c460d8b8.png)

I tried with
```
pycaret[full]==2.3.10
# and
pycaret==3.0.0rc3
```

Firefox 103.0
macOS 12.4

Thanks !

### Reproducible Example

```python
from pycaret.datasets import get_data
data = get_data('jewellery')

from pycaret.clustering import *
s = setup(data)

kmeans = create_model('kmeans')
evaluate_model(kmeans)
```

### Expected Behavior

![expected](https://1927305171-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FFLpROzBBqocwXBoemLJC%2Fuploads%2FobxihKXRnSyD4YLQZo7n%2Fimage.png?alt=media&token=5dc4a5ec-2b33-44df-9710-c1e8e0fc7eb4)

### Actual Results

```python-traceback
No traceback
```

### Installed Versions

<details>
System:
    python: 3.8.0 (default, Nov 19 2021, 14:45:00)  [Clang 13.0.0 (clang-1300.0.29.3)]
executable: /xxx/xxx/.pyenv/versions/3.8.0/envs/lab_3_8/bin/python3.8
   machine: macOS-12.4-x86_64-i386-64bit

PyCaret required dependencies:
                 pip: 22.2.2
          setuptools: 60.10.0
             pycaret: 3.0.0.rc3
             IPython: 8.4.0
          ipywidgets: 8.0.1
                tqdm: 4.64.0
               numpy: 1.21.6
              pandas: 1.4.4
              jinja2: 3.1.2
               scipy: 1.5.4
              joblib: 1.1.0
             sklearn: 1.1.2
                pyod: Installed but version unavailable
            imblearn: 0.9.1
   category_encoders: 2.5.0
            lightgbm: 3.3.2
               numba: 0.55.2
            requests: 2.28.1
          matplotlib: 3.5.3
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.10.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.11.4
               tbats: Installed but version unavailable
            pmdarima: 2.0.1
              psutil: 5.9.1
</details>

<detail>
'2.3.10'
</detail>

**Comment by ngupta23** [comment]
5th Nov 2022 Meeting

- @moezali1 verified this is working on Colab which is using Ubuntu.
- Maybe related to https://github.com/pycaret/pycaret/issues/3061 since these 2 plots use Plotly while others use matplotlib. 
- @Yard1 will look at this with #3061

**Comment by Yard1** [comment]
I cannot reproduce this issue with 3.0.

**Comment by moezali1** [comment]
I also cannot reproduce this in Jupyter Notebook.

**Comment by messaoudia** [comment]
Thanks guys ! I cannot reproduce anymore also
