### ISSUE TITLE
Kaggle and Pycaret

### ISSUE THREAD

**Issue by Joydeep75** [pycaret/pycaret#295]
Hello All, 

I am getting the following error 'Your notebook tried to allocate more memory than is available. It has restarted.' multiple times in a kaggle notebook in GPU mode even. 

The dataset has 33,000-34,000 records. 

It is breaking during the setup process, 

```
clf1 = setup(
    data = train, 
    ignore_features = ['x'],
    #numeric_imputation = 'mean',
    categorical_features = ['y','z', 'p'],
    numeric_features = ['q'],
    silent = True,
    target = 'class')
```

**Comment by Virajdatt** [comment]
I just loaded a similar-sized dataset and built models on Kaggle with a train-dataset of (30050, 55) records and inference on 
(551962, 54) records. 

Can you please provide further details of the error!

**Comment by Joydeep75** [comment]
So basically, my dataset has less number of (row, col) than yours, it is exactly (33126, 8). So I read train, test and submission file and check their heads. It shows fine. 

After that when I perform the setup() as mentioned above. It shows that, it is consuming CPU memories gradually more and shows the above error message. 

I also can mentioned that those csv files are the output from image and based on those features we are predicting the class of the images. But train and test are just .csv files. Images are in different directory and I am NOT using pycaret to do anything with images. 

Moreover, I switched CPU to GPU in kaggle platform, but it just shows that CPU memory is exhausted.

**Comment by pycaret** [comment]
@Joydeep75 When you are committing your Kaggle Notebook, are you passing **silent = True** in **setup()**.

Please provide complete message and sample of dataset so that I can reproduce the issue.

**Comment by Joydeep75** [comment]
Yes I have used both 'with' and 'without', silent = True in setup(). The actual code snippet is mentioned in my first message.

**Comment by GLevV** [comment]
It is not the CPU problem, it's RAM. In CPU mode you will have around 16GB, and in GPU it will be 14GB (so switching to GPU is the opposite of the solution). I don't know the internals of pycaret, so the only advice I can give is try to downcast as many variables as possible.

**Comment by pycaret** [comment]
@Joydeep75 We have made some major improvements with regards to memory footprint in `pycaret==2.2`. I suggest you update the version to 2.2 `pip install --upgrade pycaret` and try again.

Feel free to open another issue, if the issue persists. For now, I am closing this issue.

**Comment by someshfengde** [comment]
I am getting this issue again with Kaggle and pycaret. I have about 20 columns and 20000 rows of data
