### ISSUE TITLE
Binary Classification Tutorial Level Intermediate - CLF102.ipynb - Data Profile error 

### ISSUE THREAD

**Issue by Prabhu-kottapu** [pycaret/pycaret#296]
Pandas profiling step in the  tutorial is throwing  following  error "Requested level (var1) does not match index name (None)'

from pycaret.datasets import get_data
dataset = get_data('credit',profile= True)

**Comment by pycaret** [comment]
@Prabhu-kottapu Can you please provide complete message and traceback?

**Comment by Prabhu-kottapu** [comment]
Sure here it is 

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-42-be28a0622719> in <module>
      1 from pycaret.datasets import get_data
----> 2 dataset = get_data('credit',profile = True)

/anaconda3/lib/python3.6/site-packages/pycaret/datasets.py in get_data(dataset, save_copy, profile)
     71         if profile:
     72             import pandas_profiling
---> 73             pf = pandas_profiling.ProfileReport(data_for_profiling)
     74             display(pf)
     75 

/anaconda3/lib/python3.6/site-packages/pandas_profiling/__init__.py in __init__(self, df, **kwargs)
     66 
     67         # Get dataset statistics
---> 68         description_set = describe_df(df)
     69 
     70         # Get sample

/anaconda3/lib/python3.6/site-packages/pandas_profiling/model/describe.py in describe(df)
    549 
    550     # Get correlations
--> 551     correlations = calculate_correlations(df, variables)
    552 
    553     # Check correlations between numerical variables

/anaconda3/lib/python3.6/site-packages/pandas_profiling/model/correlations.py in calculate_correlations(df, variables)
    191                     # Get the Phi_k sorted order
    192                     current_order = (
--> 193                         correlations["phi_k"].index.get_level_values("var1").tolist()
    194                     )
    195 

/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py in _get_level_values(self, level)
   1477         Index(['a', 'b', 'c'], dtype='object')
   1478         """
-> 1479         self._validate_index_level(level)
   1480         return self
   1481 

/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py in _validate_index_level(self, level)
   1414         elif level != self.name:
   1415             raise KeyError(
-> 1416                 f"Requested level ({level}) does not match index name ({self.name})"
   1417             )
   1418 

KeyError: 'Requested level (var1) does not match index name (None)'

**Comment by mahmoudyusof** [comment]
@frh2020 @Prabhu-kottapu  they both work now with the new release pycaret==2.0 try upgrading and try again

**Comment by Prabhu-kottapu** [comment]
@mahmoudyusof I just tried but It is still not working Perhaps it is problem with Pandas profiling itself ??

**Comment by mahmoudyusof** [comment]
@Prabhu-kottapu ok, if you have pandas-profiling==2.3.0 try upgrading to pandas-profiling==2.8.0, you could know which version you have by running `pip freeze | grep pandas-profiling`
