### ISSUE TITLE
[ENH]: Allow modification of Pipeline memory

### ISSUE THREAD

**Issue by dcnadler** [pycaret/pycaret#2963]
### Describe the feature you want to add to this project

When a Pipeline is instantiated, it uses the current memory to create caching method: https://github.com/pycaret/pycaret/blob/3.0.0.rc3/pycaret/internal/pipeline.py#L82-L84

This is unlike v2, which didn't do anything with the memory.

The issue is with the v3 setup is there is no public way to modify the memory. When I loaded a model, it's memory location was 'local' and a directory that the app doesn't have permission. To point it to a new location, I had to re-create the caching methods with the new memory:

```python
from pycaret.regression import *
from sklearn.utils.validation import check_memory
from pycaret.internal.pipeline import _fit_transform_one, _transform_one

def get_model(name):
    model = load_model(name)
    memory = check_memory("/path/to/new/location")
    model.memory = memory
    model._memory_fit = memory.cache(_fit_transform_one)
    model._memory_transform = memory.cache(_transform_one)
    return model
```

Maybe I'm missing something, but this was the only way I could find to make the change

### Describe your proposed solution

One possible solution is to have a public memory setter on the Pipeline

```python
class Pipeline(imblearn.pipeline.Pipeline):
    def __init__(self, steps, *, memory=None, verbose=False):
        super().__init__(steps, memory=memory, verbose=verbose)
        self._fit_vars = set()
        self._feature_names_in = None
        self.set_memory(self.memory)


    def set_memory(self, new_memory):
        # Set up cache memory objects
        memory = check_memory(new_memory)
        self._memory_fit = memory.cache(_fit_transform_one)
        self._memory_transform = memory.cache(_transform_one)
```

There might be other approaches - I haven't thought too deeply about this.

**Comment by tvdboom** [comment]
There is a `memory` parameter in setup to change the memory of the pipleine. See [here](https://github.com/pycaret/pycaret/blob/84faafe7b982b05a069280e93a081f802775083b/pycaret/classification/oop.py#L682-L686)

**Comment by dcnadler** [comment]
I understand you can set the memory attribute at the time of model creation with `setup()`, but in my case the model was created offline and saved a while ago.

The current program is consuming the saved model with `load_model()`. I'm looking for a way to modify the Pipeline memory when not in the model-creation environment. Unless there's some way to use `setup()` in my case? (but I get a ValueError because I'm not passing any data.)

`pycaret==3.0.0.rc3`

**Comment by tvdboom** [comment]
I see your point. I added a `@setter` for the memory parameter in #2968 so you can do `pipeline.memory = new_memory` in the future version. Thanks for pointing out the issue.
