### ISSUE TITLE
[BUG]: module 'pycaret.containers.metrics' has no attribute 'classification'

### ISSUE THREAD

**Issue by turkalpmd** [pycaret/pycaret#2964]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

My version is = '3.0.0.rc3' and I use Kaggle environment. When I use tune_model function on the cluster module. I took this error;

[BUG]: module 'pycaret.containers.metrics' has no attribute 'classification'

I want to close supervised_type but function is default choosing to classification option.  I'm trying some things and finded previously bug report but I cant solved them. 

@tvdboom 

Related notebook and dataset attached here.

[pycaret_cluster.zip](https://github.com/pycaret/pycaret/files/9570195/pycaret_cluster.zip)

### Reproducible Example

```python
pycaret.clustering import *

# Required Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from pycaret.utils import version
version()

data = pd.read_csv("../input/microcalcification-classification/microcalcification.csv")
data.Microcalcification.replace("'-1'",0,inplace=True)
data.Microcalcification.replace("'1'",1,inplace=True)
data

exp_name = setup(data = data,
                 numeric_features = data.columns.tolist(),
                 preprocess = True,
                 remove_multicollinearity=True,
                 remove_outliers=True,
                 outliers_method="iforest", # other pee,lof
                 transformation_method ="yeo-johnson",
                 normalize = True,
                 normalize_method = "zscore",
                 #pca=True,
                 session_id=123)

model = create_model(model="knn",
                    num_clusters = 2,
                    ground_truth = 'Microcalcification')

tuned_model = tune_model(model,
                         supervised_target = 'Microcalcification',
                         supervised_type = 'classification',
                         supervised_estimator = 'catboost',
                         optimize = 'F1')
```

### Expected Behavior

I expected running code properly but not. I cant understand this blank.

### Actual Results

```python-traceback
AttributeError Traceback (most recent call last)
/tmp/ipykernel_183/1331734822.py in
3 supervised_type = 'classification',
4 supervised_estimator = 'catboost',
----> 5 optimize = 'F1')

/opt/conda/lib/python3.7/site-packages/pycaret/internal/utils.py in wrapper(*args, **kwargs)
920 if globals_d[name] is None:
921 raise ValueError(message)
--> 922 return func(*args, **kwargs)
923
924 return wrapper

/opt/conda/lib/python3.7/site-packages/pycaret/clustering/functional.py in tune_model(model, supervised_target, supervised_type, supervised_estimator, optimize, custom_grid, fold, fit_kwargs, groups, round, verbose)
864 groups=groups,
865 round=round,
--> 866 verbose=verbose,
867 )
868

/opt/conda/lib/python3.7/site-packages/pycaret/internal/pycaret_experiment/unsupervised_experiment.py in tune_model(self, model, supervised_target, supervised_type, supervised_estimator, optimize, custom_grid, fold, groups, ground_truth, method, fit_kwargs, round, verbose, **kwargs)
859 if supervised_type == "classification":
860 metrics = (
--> 861 pycaret.containers.metrics.classification.get_all_metric_containers(
862 self, raise_errors=True
863 )

AttributeError: module 'pycaret.containers.metrics' has no attribute 'classification'
```

### Installed Versions

<details>
'3.0.0.rc3'
</details>

**Comment by tvdboom** [comment]
Hi. Thanks for pointing out the bug. This specific bug is fixed in #2968 but there is another one in tune_model for clustering which is a bit trickier. I'll look at it over the weekend.

**Comment by turkalpmd** [comment]
How can I help you, please share with me and also feel free.

**Comment by tvdboom** [comment]
The new problem arises here:https://github.com/pycaret/pycaret/blob/84faafe7b982b05a069280e93a081f802775083b/pycaret/internal/pycaret_experiment/unsupervised_experiment.py#L1494-L1496

`tune_model` calls `_create_model` internally and `_create_model` transforms the data using the pipeline fitted in `setup`. But this fails since the pipeline in `setup` was fitted on all features, and for `tune_model` we have removed the target feature to use it for supervised learning. So the solution would be to refit the same pipeline but using all features minus the target one. I am not yet sure how I am going to implement this though.
