### ISSUE TITLE
Predict_model() scales features prior to prediction?

### ISSUE THREAD

**Issue by atwahsz** [pycaret/pycaret#297]
As the title asks

All of the best

**Comment by pycaret** [comment]
@atwahsz Yes. If you have scaled / transformed your data during setup(), the transformers are stored in pipeline and when you infer new data using **predict_model** function, It will apply all the preprocessing before generating predictions.

Hope this helps.

**Comment by ouwyukha** [comment]
> 
> 
> @atwahsz Yes. If you have scaled / transformed your data during setup(), the transformers are stored in pipeline and when you infer new data using **predict_model** function, It will apply all the preprocessing before generating predictions.
> 
> Hope this helps.

I'm having trouble with the transform mechanism. call predict_model won't transform the features and straight up giving KeyError. I'm using pycaret 2.0, is it known bug or perhaps there's problem with my packages
