### ISSUE TITLE
[BUG]: Runs recorded in MLflow nests all recursively

### ISSUE THREAD

**Issue by nagamatz** [pycaret/pycaret#2975]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

As started runs in MlflowLogger are never ended, all runs shown in MLflow dashboard seem to be nested recursively.
MLflow 1.28.0 fixed the display of deeply nested runs correctly, so the bug is now problematic.

### Reproducible Example

```python
import mlflow
from pycaret.classification import *
from pycaret.datasets import get_data

mlflow.set_tracking_uri("http://localhost:5000")

data = get_data("diabetes")
setup(data, target="Class variable", log_experiment=True, silent=True)
compare_models(include=["lr", "svm", "rf"])
setup(data, target="Class variable", log_experiment=True, silent=True)
compare_models(include=["lr", "svm", "rf"])
```

### Expected Behavior

Expected display:
![p2](https://user-images.githubusercontent.com/1991802/190944134-3490628a-4eca-490a-af11-c4cdfe41953e.png)

Actual display:
![p1](https://user-images.githubusercontent.com/1991802/190944304-08c41ae2-93fd-4b79-b3ff-ebb594ad2664.png)

### Actual Results

```python-traceback
Attached the figure also in 'Expected Behavior'.
```

### Installed Versions

<details>
'2.3.10'
</details>

**Comment by Yard1** [comment]
Cannot reproduce on master. Please try again with `pip install -U --pre pycaret` @nagamatz and reopen the issue if it persists.
