### ISSUE TITLE
[INSTALL]: Installation Issue

### ISSUE THREAD

**Issue by sabirjana** [pycaret/pycaret#2984]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Windows-10-10.0.22000-SP0

### Installation Method

pip install

### pycaret Version

'3.0.0'

### Python Version

3.8

### Description

Hi, Thanks for your huge contribution towards open source! I have installed ( pip install pycaret-ts-alpha --user) the library successfully and trying to use it for time series and getting the following error -
![image](https://user-images.githubusercontent.com/52304765/192101839-a724a6d4-f8c2-49ed-b518-c5e622e4135f.png)

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by sabirjana** [comment]
While resolving the previous issue, ended up with another
![image](https://user-images.githubusercontent.com/52304765/192103090-cdd83e5c-324d-4efd-a96c-079a0332b365.png)

**Comment by ngupta23** [comment]
In your case, you do not have the right sklearn version installed. You should switch to using the integrated version of the time series module now (where time series is available with other tasks such as regression, classification, etc). Also, please install this in a clean environment.

```
pip install --pre pycaret
```

I will close this for now. If the issue persists, please reopen it or file a new issue.

**Comment by sabirjana** [comment]
Thanks for your quick response. This is a duplicate of https://github.com/pycaret/pycaret/issues/2542. I force install pip install scikit-learn==1.0.2 --user to resolve the issue.
