### ISSUE TITLE
[INSTALL]: cuML + pycaret install steps?

### ISSUE THREAD

**Issue by ninjit** [pycaret/pycaret#2987]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Linux-5.4.0-125-generic-x86_64-with-glibc2.31

### Installation Method

Other

### pycaret Version

2.x + 3.pre

### Python Version

3.9

### Description

I've been trying to get pycaret and cuML (rapids) installed together for a while now, and I think I'm missing something basic.

Main issue seems to be that the Rapids team focus on conda, pycaret uses pip - and this leads to all sorts of package conflicts.

Is there a best practice to get this working?
The rapids team page simply adds pycaret from conda-forge, but this seems to not work either because scipy (and other packages) installed with cuML are far newer than pycaret supports.

I'm going to retry all the different avenues I've attempted so far, and will document the errors and add them as comments
e.g. pip install pycaret; conda install cuML
conda install cuML; pip install pycaret
conda install cuML pycaret
(with the relevant conda repos and cudatoolkit versions included, pycaret --pre or current, etc.)

**Comment by ninjit** [comment]
The rapids.ai release tool suggests:
```sh
conda create -n rapids-22.08 -c rapidsai -c nvidia -c conda-forge  \
    rapids=22.08 python=3.9 cudatoolkit=11.4 \
    pycaret
```

However this takes forever to execute, and the one time I let it go overnight, it conda had exited with some unresolveable conflict message (it's still running now when I tried to repeat...)

**Comment by ninjit** [comment]
I next tried starting with empty environment, and installing packages with mamba (faster than conda) followed by pip
```sh
conda create -n cuml-pycaret python=3.9
conda activate cuml-pycaret
mamba install -c rapidsai -c nvidia -c conda-forge rapids=22.08 cudatoolkit=11.4
pip install pycaret
```

But the pycaret install fails with the following message about `distutils` installed projects 
```sh
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by ninjit** [comment]
Reversing the install order, completes the installs, but results in a borked pycaret installation because of the package versions installed by rapids afterwards
```sh
conda create -n pycaret-cuml python=3.9
conda activate pycaret-cuml
pip install pycaret
mamba install -c rapidsai -c nvidia -c conda-forge cuml=22.08 cudatoolkit=11.4
```
![Screen Shot 2022-09-25 at 12 48 46](https://user-images.githubusercontent.com/753263/192162479-cefd77d8-19f4-4639-859e-59c67c18b8d8.png)

**Comment by ninjit** [comment]
Using --pre for pycaret, after cuml first, installs successfully, but results in a type error when trying to check cuml version
```sh
conda create -n cuml-pycaret-pre python=3.9
conda activate cuml-pycaret-pre
mamba install -c rapidsai -c nvidia -c conda-forge cuml=22.08 cudatoolkit=11.4
pip install --pre pycaret
```
![Screen Shot 2022-09-25 at 13 00 15](https://user-images.githubusercontent.com/753263/192162912-de78b700-2a94-4f8b-ac29-d2cdd549439d.png)

![Screen Shot 2022-09-25 at 13 00 38](https://user-images.githubusercontent.com/753263/192162915-6bb21dda-1a08-4f0e-a93b-825187967793.png)

**Comment by ninjit** [comment]
And the last thing I've tried is installing from github main
```sh
conda create -n rapids-pycaret-git python=3.9
conda activate rapids-pycaret-git
mamba install -c rapidsai -c nvidia -c conda-forge rapids=22.08 cudatoolkit=11.4
pip install -U git+https://github.com/pycaret/pycaret.git
```
 pip complains about some package dependency problems
```sh
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-cudf 22.8.0 requires cupy-cuda115<11.0.0a0,>=9.5.0, which is not installed.
distributed 2022.7.1 requires tornado<6.2,>=6.0.3, but you have tornado 6.2 which is incompatible.
```
But seems to still complete
However I still get the same type error when checking cuml version as above

**Comment by ninjit** [comment]
ok, I think I made a little progress.
Installing full rapids forces sklearn version >1, which is not compatible with the pycaret v2.3 available in conda-forge (but doesn't seem to be specified as a requirement)
Installing just cuML doesn't enforce this
```sh
conda create -n cuml-pycaret python=3.9
conda activate cuml-pycaret
mamba install -c rapidsai -c nvidia -c conda-forge cuml pycaret scikit-plot
```
pycaret in conda-forge is also missing the scikit-plot dependency, so adding that fixes associated import errors.

I'm now running through the test script successfully (Just code from the beginner's classification tutorial), it's using the GPU (running pretty fast), and the returned object is a cuml model type.

However there seems to be something wrong with the metrics being calculated - a problem for another issue perhaps:

![Screen Shot 2022-09-25 at 14 21 56](https://user-images.githubusercontent.com/753263/192166200-06e98fb5-af1e-4729-a176-34f88e47182a.png)

**Comment by vvatlin** [comment]
Same issue for me
