### ISSUE TITLE
[ENH]: Pandas 1.5.0 compatibility

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#2988]
### Describe the feature you want to add to this project

Pandas 1.5.0 compatibility

### Describe your proposed solution

Pandas 1.5.0 compatibility

**Comment by celestinoxp** [comment]
If you use `pip list --outdated` you will receive a list of latest version of packages and versions you have installed.

after update pycaret to rc4 i have a list i can´t update and is considered important to update:

llvmlite 0.38.1  0.39.1 wheel
numba    0.55.2  0.56.2 wheel
numpy    1.22.4  1.23.3 wheel
pandas   1.4.4   1.5.0  wheel
pmdarima 1.8.5   2.0.1  wheel
scipy    1.8.1   1.9.1  wheel

**Comment by ngupta23** [comment]
The goal is not to install the latest version of all the packages but to install a version that is compatible with all the other libraries in that environment. What is the specific issue you are facing? I am able to install pycaret 3.0.0rc4 without any issues.

**Comment by celestinoxp** [comment]
This is not a specific problem. It is said that Pycaret is a software hub, and they all have bugs that are fixed with new versions. If we are not aware of these improvements we will end up using software with bugs that have already been fixed but we are not using it.

The simple fact that a software works doesn't mean that it doesn't have bugs.

Here's a huge list of things that have been fixed, plus all the reasons to update to the latest version: https://pandas.pydata.org/docs/whatsnew/v1.5.0.html#

Like pandas, other software must be used in the latest versions. I only see benefits.

**Comment by celestinoxp** [comment]
I checked in requierements.txt and the reason pycaret doesn't support pandas 1.5.0 seems to be because of sktime compatibility, but they already support the latest pandas. See https://github.com/sktime/sktime/commit/29a1864ab8c302a1b2abc6e7d9fed6f569aaf58a

**Comment by celestinoxp** [comment]
Sorry if i don't agree of 1st rule of programming: "If works don´t touch it".
https://twitter.com/TheInsaneApp/status/1369170238701375489?s=20&t=rEjc0QrLkWcGUao9zn-pmA

**Comment by ngupta23** [comment]
We can relax pandas to match sktime since they have relaxed their requirement. That is not a problem. Bottom line is that in this case, we will be limited by sktime in this case since sktime is a dependency of pycaret.

**Comment by celestinoxp** [comment]
> Podemos relaxar os pandas para combinar com o sktime, pois eles relaxaram sua exigência. Isso não é um problema. A conclusão é que, neste caso, estaremos limitados pelo sktime neste caso, pois o sktime é uma dependência do pycaret.

LGTM. Thank you!
