### ISSUE TITLE
Unable to execute compare_models() 

### ISSUE THREAD

**Issue by singhrishu** [pycaret/pycaret#299]
File attached .
[pycaret_error.docx](https://github.com/pycaret/pycaret/files/4956346/pycaret_error.docx)

**Comment by fargoca** [comment]
Seems like your XGBoost library isnt property installed. Try re installing it separately 
pip install XGBoost

**Comment by pycaret** [comment]
@singhrishu Can you please try installing `pycaret==2.0` in a new conda environment. Follow instructions here : **https://www.pycaret.org/install**
