### ISSUE TITLE
[BUG]: Multiclass Classification boundary plot (plot_model)

### ISSUE THREAD

**Issue by binaryyskull** [pycaret/pycaret#2999]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [ ] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

When I use plot_model(tuned_knn, plot='boundary') then I see a very interesting formation of boundaries as attached

Then, I see this kind of boundary, is not it wrong?
<img width="554" alt="Screenshot" src="https://user-images.githubusercontent.com/114610102/192858989-a20b8f6c-1a6b-4e72-b52a-b111a6b9837a.png">

### Reproducible Example

```python
from pycaret.datasets import get_data
dataset = get_data('iris')

dataset.shape

data = dataset.sample(frac=0.9, random_state=786)
data_unseen = dataset.drop(data.index)

data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions: ' + str(data_unseen.shape))

exp_mclf101 = setup(data = data, target = 'species', session_id=123) 

best = compare_models()

knn = create_model('knn')

import numpy as np
tuned_knn = tune_model(knn, custom_grid = {'n_neighbors' : np.arange(0,50,1)})

plot_model(tuned_knn, plot='boundary')
```

### Expected Behavior

Boundaries should be correct.

### Actual Results

```python-traceback
That code is showing me the boundaries wrongly!
```

### Installed Versions

pycaret 2.3.10 python 3.8.13

**Comment by tvdboom** [comment]
can you try this on the newest version `pip install --pre pycaret`?

**Comment by moezali1** [comment]
@binaryyskull I have tried to reproduce this using pre-release and couldn't. It seems to be working fine.

Here is the Notebook: https://colab.research.google.com/drive/1YXZyEj3yxzIsOiDCHNFBGSZGPOeKeZkT?usp=sharing
