### ISSUE TITLE
compare model bugg

### ISSUE THREAD

**Issue by mfahadakbar** [pycaret/pycaret#30]
compare mode failing here :
![Capture](https://user-images.githubusercontent.com/19522276/79896776-c5068400-83d6-11ea-9309-51035cc29760.PNG)

**Comment by pycaret** [comment]
Can you please try after blacklist RANSAC.
compare_models(blacklist = ['ransac'])

It seems like an exception has to be built for RANSAC (because sometimes it may not converge - just like this example).

Marking this as bug for fix.
