### ISSUE TITLE
Showing original label not encoding value in plot_model for pycaret3

### ISSUE THREAD

**Issue by Louis-udm** [pycaret/pycaret#3001]
### Describe the feature you want to add to this project

Hi pycaret team!

I know that pycaret2.x has solved this issue (#1939), but it seems pyCaret3 does not support this feature.

Thanks!

### Describe your proposed solution

copy the feature form 2.x

**Comment by moezali1** [comment]
@Louis-udm Hi, Here is how you can achieve this:

```
from pycaret.datasets import get_data
dataset = get_data('iris')

from pycaret.classification import *
s = setup(data = data, target = 'species', session_id=123) 

knn = create_model('knn')

plot_model(knn, plot = 'confusion_matrix')

plot_model(knn, plot = 'confusion_matrix', plot_kwargs = {'classes' : get_config('pipeline').steps[0][1].transformer.classes_})

# alternatively this will also work:
plot_model(knn, plot = 'confusion_matrix', plot_kwargs = {'encoder' : get_config('pipeline').steps[0][1].transformer})
```
![image](https://user-images.githubusercontent.com/54699234/200647808-588c564c-a235-4645-afb5-2459c3bfc0ae.png)

**Comment by Louis-udm** [comment]
Cool! Thanks @moezali1
