### ISSUE TITLE
[ENH]: RidgeClassifier new "positive" parameter

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#3005]
### Describe the feature you want to add to this project

In sklearn documentation (https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.RidgeClassifier.html), says:

solver ‘lbfgs’ uses L-BFGS-B algorithm implemented in scipy.optimize.minimize. It can be used only when positive is True.

So. In pycaret\containers\models\classification.py, the ridgeclassifier not have the "positive" parameter. I think we need insert new line like: tune_grid = {
            "positive": [True, False],
        }

Other question is: why exists various lines with tune_grid["..."] ?
Can we insert all parameters in a single tune_grid? like

tune_grid = {
"example_parameter1": [values],
"example_parameter2": [values],
...
}

I have opened a issue, with a sugestion for all classifiers should be reviwed for latest versions of classifiers:  https://github.com/pycaret/pycaret/issues/2983

and insert a comment with the date of update and the version of classifier at these update.

### Describe your proposed solution

https://github.com/pycaret/pycaret/issues/2983, instead of having to create a new issue for each classifier.
Make a list of all classifiers and check all parameters,
check classifiers one-by-one for latest versions

### Additional context

New versions of algorithms have changes and new parameters. If pycaret no use them, then these algorithms use only default parameters...

**Comment by moezali1** [comment]
Related with #2983
