### ISSUE TITLE
MLflow tracking server

### ISSUE THREAD

**Issue by sumeshmr** [pycaret/pycaret#301]
Hello,

Waiting for your next release and MLflow integration. Hope you will support MLflow remote-tracking server as well.

https://mlflow.org/docs/latest/quickstart.html#logging-to-a-remote-tracking-server

**Comment by pycaret** [comment]
Yes it will.

**Comment by sumeshmr** [comment]
I did not see the option to set **mlflow.set_tracking_uri** in the code:
https://github.com/pycaret/pycaret/blob/dev-1.0.1/pycaret/classification.py

**Comment by pycaret** [comment]
@sumeshmr You can include this code in your notebook or script to set tracking uri

import mlflow
mlflow.set_tracking_uri() 

https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.set_tracking_uri

It worked for me. Please close the issue if this resolves your problem.

**Comment by pycaret** [comment]
@sumeshmr Can we close this issue?

**Comment by sumeshmr** [comment]
Yes please
