### ISSUE TITLE
Pycaret is Multithreading ?

### ISSUE THREAD

**Issue by acipolletti** [pycaret/pycaret#302]
Hi, i'm trying to use pycaret in order to create multiple model : iforest and svm, concurrently, using multiple threads. But the pycaret seem to be not thread save. It is correct ? If pycaret can be used in a multithreads env how we should setup and use it?
Thanks in advance Antonio

**Comment by pycaret** [comment]
@acipolletti 

Yes it does. Please update PyCaret to 2.0 and use n_jobs parameter in setup function. By default is set to -1.

Hope this helps.

**Comment by acipolletti** [comment]
Thanks for answer, but my question was a bit different: can i run the functions setup and create_model concurrently in different threads?
Thanks in advance.
