### ISSUE TITLE
[BUG]: Time Series prediction plot not showing prediction interval

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#3029]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

When plotting predictions with an ARIMA model, the prediction interval is not shown.

### Reproducible Example

```python
from pycaret.datasets import get_data
from pycaret.time_series import TSForecastingExperiment


df = get_data("airline")

exp = TSForecastingExperiment()
exp.setup(df, fh=7, fold=3, session_id=123)

model = exp.create_model("arima")

exp.plot_model(model)
```

### Expected Behavior

Prediction interval should be shown

It is not being shown (see below)

![image](https://user-images.githubusercontent.com/33585645/194726663-f4156f37-c9f8-4ff1-87f1-93037d8f1c3a.png)

### Actual Results

```python-traceback
Image shown above
```

### Installed Versions

<details>
System:
    python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\Nikhil\.conda\envs\pycaret_dev_sktime_13p0\python.exe
   machine: Windows-10-10.0.19044-SP0

PyCaret required dependencies:
                 pip: 22.1.2
          setuptools: 61.2.0
             pycaret: 3.0.0rc4
             IPython: 8.4.0
          ipywidgets: 7.7.1
                tqdm: 4.64.0
               numpy: 1.22.4
              pandas: 1.4.3
              jinja2: 3.1.2
               scipy: 1.8.1
              joblib: 1.1.0
             sklearn: 1.1.1
                pyod: 1.0.3
            imblearn: 0.9.1
   category_encoders: 2.5.0
            lightgbm: 3.3.2
               numba: 0.55.2
            requests: 2.28.1
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.9.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.13.1
               tbats: 1.1.0
            pmdarima: 1.8.5
              psutil: 5.9.1

PyCaret optional dependencies:
                shap: Not installed
           interpret: Not installed
                umap: Not installed
    pandas_profiling: Not installed
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
             xgboost: 0.80
            catboost: 1.0.6
              kmodes: Not installed
             mlxtend: Not installed
       statsforecast: 1.0.0
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: Not installed
              optuna: Not installed
               skopt: Not installed
              mlflow: 1.27.0
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: Not installed
           evidently: Not installed
                nltk: Not installed
            pyLDAvis: Not installed
              gensim: Not installed
               spacy: Not installed
           wordcloud: Not installed
            textblob: Not installed
               fugue: Not installed
           streamlit: Not installed
             prophet: Not installed

</details>

**Comment by ngupta23** [comment]
@jonasvdd, It seems that this issue is coming after we changed `Scatter` to `Scattergl` in `plot_predictions_with_confidence` in [this PR](https://github.com/pycaret/pycaret/commit/8ece199d84c29539ef0311c9eea55bc73148ed2f). Can we change this back to `Scatter` (this resolves the issue - I have verified locally)?

![image](https://user-images.githubusercontent.com/33585645/194729649-480f3658-9512-4fb3-be3b-155d27be5382.png)

**Comment by jonasvdd** [comment]
Hi, sure!
I mainly did that to speed up graph construction time. But as it induces this bug, this can certainly be changed back! 

Thanks for checking with me!
