### ISSUE TITLE
[BUG]: Pycaret 3.0.4rc can finalize Prophet

### ISSUE THREAD

**Issue by ConnorReedAvantum** [pycaret/pycaret#3036]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Prophet fails to finalize on Datasets with exogenous variables. 

### Reproducible Example

```python
import pycaret.time_series as pts
import pandas as pd
from sktime.datasets import load_longley

original_data = load_longley()[1].merge(load_longley()[0].rename("TOTEMP"), left_index=True, right_index=True)
experiment = pts.setup(data = original_data, target = "TOTEMP", fh = 3, enforce_exogenous = False, numeric_imputation_exogenous="linear", numeric_imputation_target= "linear")
best = experiment.compare_models(turbo = False, include = ["prophet"])
final = experiment.finalize_model(best)
```

### Expected Behavior

Model is Finalized.

### Actual Results

```python-traceback
Description	Value
0	session_id	7528
1	Target	TOTEMP
2	Approach	Univariate
3	Exogenous Variables	Present
4	Original data shape	(16, 6)
5	Transformed data shape	(16, 6)
6	Transformed train set shape	(13, 6)
7	Transformed test set shape	(3, 6)
8	Rows with missing values	0.0%
9	Fold Generator	ExpandingWindowSplitter
10	Fold Number	3
11	Enforce Prediction Interval	False
12	Seasonal Period(s) Tested	1
13	Seasonality Present	False
14	Seasonalities Detected	[1]
15	Primary Seasonality	1
16	Target Strictly Positive	True
17	Target White Noise	No
18	Recommended d	1
19	Recommended Seasonal D	0
20	Preprocess	True
21	Numerical Imputation (Target)	linear
22	Transformation (Target)	None
23	Scaling (Target)	None
24	Numerical Imputation (Exogenous)	linear
25	Transformation (Exogenous)	None
26	Scaling (Exogenous)	None
27	CPU Jobs	-1
28	Use GPU	False
29	Log Experiment	False
30	Experiment Name	ts-default-name
31	USI	a0a2
 	Model	MASE	RMSSE	MAE	RMSE	MAPE	SMAPE	R2	TT (Sec)
prophet	Prophet	119.7322	120.5635	110953.0238	112460.1561	1.7363	0.5117	-63624.9957	2.8500
Output exceeds the size limit. Open the full output data in a text editor
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/workspaces/TSF/Scripts/BugReportProphet.ipynb Cell 2 in <cell line: 10>()
      8 experiment = pts.setup(data = original_data, target = "TOTEMP", fh = 3, enforce_exogenous = False, numeric_imputation_exogenous="linear", numeric_imputation_target= "linear")
      9 best = experiment.compare_models(turbo = False, include = ["prophet"])
---> 10 final = experiment.finalize_model(best)

File /opt/conda/lib/python3.8/site-packages/pycaret/time_series/forecasting/oop.py:4159, in TSForecastingExperiment.finalize_model(self, estimator, fit_kwargs, model_only, experiment_custom_tags)
   4118 def finalize_model(
   4119     self,
   4120     estimator,
   (...)
   4123     experiment_custom_tags: Optional[Dict[str, Any]] = None,
   4124 ) -> Any:
   4126     """
   4127     This function trains a given estimator on the entire dataset including the
   4128     holdout set.
   (...)
   4156 
   4157     """
-> 4159     return super().finalize_model(
   4160         estimator=estimator,
   4161         fit_kwargs=fit_kwargs,
   4162         model_only=model_only,
   4163         experiment_custom_tags=experiment_custom_tags,
   4164     )

File /opt/conda/lib/python3.8/site-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py:4713, in _SupervisedExperiment.finalize_model(self, estimator, fit_kwargs, groups, model_only, experiment_custom_tags)
   4711     self.predict_model(pipeline_final, data=self.test, verbose=False)
   4712 else:
-> 4713     self.predict_model(pipeline_final, X=self.X_test, verbose=False)
   4715 model_results = self.pull(pop=True).drop("Model", axis=1)
   4716 model_results.index = ["Mean"]

File /opt/conda/lib/python3.8/site-packages/pycaret/time_series/forecasting/oop.py:4081, in TSForecastingExperiment.predict_model(self, estimator, fh, X, return_pred_int, alpha, coverage, round, verbose)
   4078 fh = self._predict_model_reconcile_fh(estimator=estimator_, fh=fh)
   4079 X = self._predict_model_reconcile_X(estimator=estimator_, X=X)
-> 4081 result = get_predictions_with_intervals(
   4082     forecaster=pipeline_with_model,
   4083     alpha=alpha,
   4084     coverage=coverage,
   4085     X=X,
   4086     fh=fh,
   4087     merge=True,
   4088     round=round,
   4089 )
   4090 y_pred = pd.DataFrame(result["y_pred"])
   4092 #################
   4093 # Metrics ####
   4094 #################

File /opt/conda/lib/python3.8/site-packages/pycaret/utils/time_series/forecasting/__init__.py:110, in get_predictions_with_intervals(forecaster, alpha, coverage, X, fh, merge, round)
    108 # Get Point predictions ----
    109 if alpha is None:
--> 110     y_pred = forecaster.predict(fh=fh, X=X)
...
-> 1204         raise ValueError('Dataframe has no rows.')
   1205     df = self.setup_dataframe(df.copy())
   1207 df['trend'] = self.predict_trend(df)

ValueError: Dataframe has no rows.
```

### Installed Versions

<details>
System:
    python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18)  [GCC 10.3.0]
executable: /opt/conda/bin/python
   machine: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.10

PyCaret required dependencies:
                 pip: 21.1.2
          setuptools: 65.3.0
             pycaret: 3.0.0rc4
             IPython: 8.4.0
          ipywidgets: 8.0.1
                tqdm: 4.64.0
               numpy: 1.22.4
              pandas: 1.4.3
              jinja2: 3.1.2
               scipy: 1.8.1
              joblib: 1.1.0
             sklearn: 1.1.2
                pyod: 1.0.4
            imblearn: 0.9.1
   category_encoders: 2.5.0
            lightgbm: 3.3.2
               numba: 0.55.2
            requests: 2.28.1
          matplotlib: 3.5.3
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.10.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.13.2
               tbats: 1.1.0
            pmdarima: 1.8.5
              psutil: 5.9.1

PyCaret optional dependencies:
                shap: 0.34.0
           interpret: 0.2.1
                umap: Not installed
    pandas_profiling: Not installed
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
             xgboost: 1.6.2
            catboost: 1.0.6
              kmodes: Not installed
             mlxtend: Not installed
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: Not installed
              optuna: Not installed
               skopt: Not installed
              mlflow: Not installed
...
            textblob: Not installed
               fugue: Not installed
           streamlit: Not installed
             prophet: 1.1
</details>

**Comment by ngupta23** [comment]
@ConnorReedAvantum Thanks for raising this. This seems to be an issue with the underlying sktime library. I have raised an issue with them. Once this is resolved by them and we upgrade pycaret to their fixed version, this should be fixed automatically. 

Thanks!

**Comment by ngupta23** [comment]
5th Nov 2022 meeting

Discussed with @Yard1 . It does not make sense to display metrics on Test set after finalizing the model. The following section from `supervised_experiment.py` should be removed.

![image](https://user-images.githubusercontent.com/33585645/200120177-8ebaf0f0-5e63-416f-89cf-296536ddd332.png)

**Comment by moezali1** [comment]
@ngupta23 to handle.
