### ISSUE TITLE
[BUG]: Test config file on github needs attention

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#3054]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I've noticed that there are some issues that need attention. See https://github.com/pycaret/pycaret/actions

I tried to check the test.yaml file, but I don't have enough experience to deal with it.

As I understand GitHub is making some updates so the test files should be updated according to the new GitHub updates.

Can anyone comfortable with these changes please check and update the test configuration files?

![pycaret_tests_warnings](https://user-images.githubusercontent.com/41735311/197494965-bb9a81c1-b5bf-4a57-803e-3911082f573f.png)

### Reproducible Example

```python
.
```

### Expected Behavior

.

### Actual Results

```python-traceback
.
```

### Installed Versions

<details>
NA
</details>

**Comment by celestinoxp** [comment]
I think I found a github thread with relationship about canceling. Can anyone confirm?
Discussion: https://github.com/orgs/community/discussions/8336

**Comment by ngupta23** [comment]
I do not see this anymore. Can you send the link to any recent test that shows this?

**Comment by celestinoxp** [comment]
Tests Fixed
