### ISSUE TITLE
[INSTALL]: 

### ISSUE THREAD

**Issue by Bodhi8** [pycaret/pycaret#3065]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Windows-10-10.0.19044-SP0

### Installation Method

pip install

### pycaret Version

pycaret-2.2.3

### Python Version

3

### Description

Trying to import time series. Getting this error:
from pycaret.time_series import *

ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_28800/4278465610.py in <module>
----> 1 from pycaret.time_series import *
      2 s = setup(data, fh = 3, fold = 5, session_id = 123)

ModuleNotFoundError: No module named 'pycaret.time_series'

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by ngupta23** [comment]
You are installing the wrong version of pycaret (it does not have time series in it). Please check the readme on the main pycaret page for install instructions.

https://github.com/pycaret/pycaret#-pycaret-time-series-module
