### ISSUE TITLE
[BUG]: Tune model finished but CPU at 100%

### ISSUE THREAD

**Issue by acivit** [pycaret/pycaret#3066]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Hello!

I realised that when I train a model with compare_models, the processors are busy but when the training ends their consumption is close to zero, but when I apply the tune_model() to that model I trained, when the process finishes the processors keep busy at 100% (and some subprocesses still open in threads)... and that collapses the computer.. 

I'm applying the tune_model function in a thread with a timeout, but the process simplified is:

### Reproducible Example

```python
setup(
            data=self.data,
            target=self.target_regression,
            ignore_features=["id", "device_serial", "date", self.target_classification],
            numeric_features=self.numeric_fields,
            silent=True,
            verbose=False,
            remove_outliers=True,
            normalize=True,
            use_gpu=True,
        )

model = compare_models(verbose=True)
model = tune_model(model, choose_better=True, early_stopping=True, n_iter=10)
```

### Expected Behavior

.

### Actual Results

```python-traceback
The consumption of all the workers of the CPU are 100%. The finetuning process has ended and anything else is running.
```

### Installed Versions

<details>
pandas                    1.5.1
pycaret                   2.3.10
scikit-learn              0.23.2
</details>

**Comment by moezali1** [comment]
@acivit Can you try with `use_gpu = False` and let us know if you have the same issue.

**Comment by celestinoxp** [comment]
1- I think you have another package with some bug. As i can see you use a mix of old packages with recent packages.
scikit-learn 0.23.2 is to old for example, it is possible use scikit-learn 0.24.2? I think its latest supported for pycaret 2.3.10.

2-Maybe you can show us more details about packages instaled.
Please paste the output of `from pycaret import show_versions; show_versions()`. If this does not work, try this instead `import pycaret; pycaret.__version__`

3- if pycaret 2.3.10 is not required, I invite you to try the latest pycaret, pycaret 3 rc4, it has many bug fixes and uses the latest scikit-learn which has amazing improvements.
Only needs use 2 commands:
`pip uninstall pycaret`
`pip install --pre pycaret` or `pip install --pre pycaret[full]`
