### ISSUE TITLE
[BUG]: In Regression, when using transform_target=True all scores returned 0 

### ISSUE THREAD

**Issue by Azlich** [pycaret/pycaret#3078]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

In PyCaret 3.0.0rc4, the setup steps when I specify `transform_target=True` and then create the model via compare_models() or create_model(). It give me all 0 scores in every fold or every model but it can run without error

### Reproducible Example

```python
from pycaret.datasets import get_data
from pycaret.regression import *

data = get_data('insurance')

setup(
    data=data, 
    target='charges', 
    transform_target=True,
    numeric_features=['age', 'children', 'bmi'], 
    categorical_features=['sex', 'smoker', 'region'],
    session_id=101
)

model = create_model('lr')
```

### Expected Behavior

Expected display (PyCaret 2.3.10):

![pycaret2_transform](https://user-images.githubusercontent.com/16594006/200985722-7af4e9f1-ff60-4ee0-8cac-905444920b1e.png)

Actual display (PyCaret 3.0.0rc4):

![pycaret3_transform](https://user-images.githubusercontent.com/16594006/200986189-9228b826-0601-44bd-8607-91b8d6123958.png)

### Actual Results

```python-traceback
It can run successfully without an error message
```

### Installed Versions

<details>
System:
    python: 3.7.15 (default, Oct 12 2022, 19:14:55)  [GCC 7.5.0]
executable: /usr/bin/python3
   machine: Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic

PyCaret required dependencies:
                 pip: 21.1.3
          setuptools: 57.4.0
             pycaret: 3.0.0rc4
             IPython: 7.9.0
          ipywidgets: 7.7.1
                tqdm: 4.64.1
               numpy: 1.21.6
              pandas: 1.3.5
              jinja2: 3.0.0
               scipy: 1.7.3
              joblib: 1.2.0
             sklearn: 1.0.2
                pyod: 1.0.6
            imblearn: 0.8.1
   category_encoders: 2.5.1.post0
            lightgbm: 3.3.3
               numba: 0.55.2
            requests: 2.28.1
          matplotlib: 3.5.3
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.5.0
             kaleido: 0.2.1
         statsmodels: 0.12.2
              sktime: 0.13.4
               tbats: 1.1.1
            pmdarima: 1.8.5
              psutil: 5.9.4

PyCaret optional dependencies:
                shap: Not installed
           interpret: Not installed
                umap: Not installed
    pandas_profiling: 1.4.1
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
             xgboost: 0.90
            catboost: Not installed
              kmodes: Not installed
             mlxtend: 0.14.0
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: 0.1.2
              optuna: Not installed
               skopt: Not installed
              mlflow: Not installed
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: Not installed
           evidently: Not installed
                nltk: 3.7
            pyLDAvis: Not installed
              gensim: 3.6.0
               spacy: 3.4.2
           wordcloud: 1.8.2.2
            textblob: 0.15.3
               fugue: Not installed
           streamlit: Not installed
             prophet: 1.1.1
</details>

**Comment by moezali1** [comment]
@tvdboom I am able to reproduce the issue successfully. Attached is the log file where you can see the exception as well.
[logs.log](https://github.com/pycaret/pycaret/files/10047083/logs.log)
