### ISSUE TITLE
import win32api; ImportError:

### ISSUE THREAD

**Issue by d4deva** [pycaret/pycaret#3079]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Windows-10-10.0.19041-SP0

### Installation Method

pip install

### pycaret Version

pycaret[full]

### Python Version

3.8.8

### Description

Hi Team, I was trying to install pycaret full in my windows laptop usiny "pip install pycaret[full]" command after successful installation, I am getting kernal error; "**import win32api ImportError: DLL load failed while importing win32api: The specified procedure could not be found**." 

I've tried to run "conda install -c anaconda pywin32" command but it is not working. 

getting following error

(base) C:\windows\system32>conda install -c anaconda pywin32
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/anaconda/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://conda.anaconda.org/anaconda/win-64'

### Installation Logs

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.4 requires pathlib, which is not installed.
anaconda-project 0.9.1 requires ruamel-yaml, which is not installed.
Successfully installed Boruta-0.3 Cython-0.29.14 Flask-WTF-0.15.1 Mako-1.2.3 PrettyTable-3.5.0 SALib-1.4.5 WTForms-3.0.1 adagio-0.2.4 aiohttp-3.8.3 aiosignal-1.3.1 alembic-1.8.1 ansi2html-1.8.0 antlr4-python3-runtime-4.11.1 anyio-3.6.2 async-timeout-4.0.2 autopage-0.5.1 autoviz-0.1.58 azure-core-1.26.1 azure-storage-blob-12.14.1 blis-0.7.9 bokeh-2.4.3 boto3-1.26.6 botocore-1.29.6 brotli-1.0.9 cachetools-5.2.0 catalogue-1.0.2 catboost-1.1.1 charset-normalizer-2.1.1 chart-studio-1.1.0 click-8.0.4 cliff-4.0.0 cmaes-0.9.0 cmd2-2.4.2 colorcet-3.0.1 colorlog-6.7.0 colorlover-0.3.0 colour-0.1.5 cufflinks-0.17.3 cymem-2.0.7 dash-2.7.0 dash-auth-1.4.1 dash-bootstrap-components-0.13.1 dash-core-components-2.0.0 dash-cytoscape-0.3.0 dash-html-components-2.0.0 dash-table-5.0.0 databricks-cli-0.17.3 dataclasses-0.6 dill-0.3.6 distlib-0.3.6 docker-6.0.1 dtreeviz-1.4.0 emoji-2.2.0 evidently-0.1.51.dev0 explainerdashboard-0.3.8.2 fairlearn-0.8.0 fastapi-0.86.0 ffmpy-0.3.0 filelock-3.8.0 flask-compress-1.13 flask-seasurf-1.1.1 flask-simplelogin-0.1.1 frozenlist-1.3.3 fs-2.4.16 fugue-0.7.3 fugue-sql-antlr-0.1.1 funcy-1.17 gensim-3.8.3 gitdb-4.0.9 gitpython-3.1.29 google-api-core-2.10.2 google-auth-2.14.1 google-cloud-core-2.3.2 google-cloud-storage-2.6.0 google-crc32c-1.5.0 google-resumable-media-2.4.0 googleapis-common-protos-1.56.4 gradio-3.9 graphviz-0.20.1 grpcio-1.50.0 h11-0.12.0 holoviews-1.14.9 htmlmin-0.1.12 httpcore-0.15.0 httpx-0.23.0 hvplot-0.8.1 hyperopt-0.2.7 imagehash-4.3.1 imbalanced-learn-0.7.0 importlib-metadata-5.0.0 importlib-resources-5.10.0 interpret-0.2.4 interpret-core-0.2.7 isodate-0.6.1 jmespath-1.0.1 jupyter-dash-0.4.2 kmodes-0.12.2 lightgbm-3.3.3 lime-0.2.0.1 linkify-it-py-1.0.3 m2cgen-0.10.0 markdown-3.4.1 markdown-it-py-2.1.0 mdit-py-plugins-0.3.1 mdurl-0.1.2 missingno-0.5.1 mlflow-1.30.0 mlxtend-0.19.0 msrest-0.7.1 multidict-6.0.2 multimethod-1.9 multiprocess-0.70.14 murmurhash-1.0.9 numpy-1.19.5 oauthlib-3.2.2 optuna-2.10.1 orjson-3.8.1 oyaml-1.0 packaging-21.3 pandas-profiling-3.4.0 panel-0.12.7 param-1.12.2 pathos-0.3.0 patsy-0.5.3 pbr-5.11.0 phik-0.12.2 plac-1.1.3 platformdirs-2.5.3 plotly-5.11.0 pox-0.3.2 ppft-1.7.6.6 preshed-3.0.8 prometheus-flask-exporter-0.20.3 protobuf-3.19.6 py4j-0.10.9.7 pyLDAvis-3.2.2 pyamg-4.2.3 pyaml-21.10.1 pyarrow-10.0.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycaret-2.3.10 pycryptodome-3.15.0 pyct-0.4.8 pydantic-1.10.2 pydub-0.25.1 pyjwt-2.6.0 pynndescent-0.5.8 pyod-1.0.6 pyperclip-1.8.2 pyreadline3-3.4.1 python-multipart-0.0.5 pyviz-comms-2.2.1 pywin32-305 qpd-0.3.3 querystring-parser-1.2.4 ray-2.1.0 requests-2.28.1 requests-oauthlib-1.3.1 retrying-1.3.3 rfc3986-1.5.0 rsa-4.9 s3transfer-0.6.0 scikit-learn-0.23.2 scikit-optimize-0.9.0 scikit-plot-0.3.7 scipy-1.5.4 shap-0.41.0 skope-rules-1.0.1 slicer-0.0.7 smart-open-6.2.0 smmap-5.0.0 spacy-2.3.8 sqlparse-0.4.3 srsly-1.0.6 starlette-0.20.4 statsmodels-0.13.5 stevedore-4.1.0 tabulate-0.9.0 tangled-up-in-unicode-0.2.0 tenacity-8.1.0 tensorboardX-2.5.1 textblob-0.17.1 thinc-7.4.6 treeinterpreter-0.2.3 triad-0.7.0 tune-sklearn-0.4.4 typing-extensions-4.4.0 ua-parser-0.16.1 uc-micro-py-1.0.1 umap-learn-0.5.3 uvicorn-0.19.0 virtualenv-20.16.6 visions-0.7.5 waitress-2.1.2 wasabi-0.10.1 websocket-client-1.4.2 websockets-10.4 wordcloud-1.8.2.2 xgboost-1.7.1 yarl-1.8.1 yellowbrick-1.3.post1

Error message: 
 import win32api
ImportError: DLL load failed while importing win32api: The specified procedure could not be found.
![image](https://user-images.githubusercontent.com/65092287/200998346-eb4da6ad-9a51-4d58-a4ca-bff9b5bfe6ee.png)
![image](https://user-images.githubusercontent.com/65092287/200998821-83897143-8364-4d78-96b7-51b65793832a.png)

**Comment by celestinoxp** [comment]
I recommend install pycaret version 3, you need to add --pre sufix, so you can try with these 2 lines:
```
pip uninstall pycaret
pip install --pre pycaret[full]
```
after that tell if pycaret installed successfully

**Comment by d4deva** [comment]
If i uninstall pycaret and install it again i am getting following error:
**Failed to build aiohttp multidict
ERROR: Could not build wheels for multidict, which is required to install pyproject.toml-based projects**

Please recommend or post the link of anaconda that is supportable for the latest version of pycaret.

**Comment by celestinoxp** [comment]
How have some problem/conflict with packages. 
Try these steps.

1.Uninstall anaconda.
2.Go to https://www.anaconda.com/ and download and install anaconda
3. After anaconda installed, install pycaret with this command: pip install --pre pycaret

This should work without problems

**Comment by d4deva** [comment]
The above method work but won't be able the full version of pycaret correct?

**Comment by celestinoxp** [comment]
> 

Of couse, use pip install --pre pycaret[full]

**Comment by d4deva** [comment]
Failed to build aiohttp multidict
ERROR: Could not build wheels for multidict, which is required to install pyproject.toml-based projects


getting the following error if i use use pip install --pre pycaret[full]

**Comment by celestinoxp** [comment]
@ngupta23 @Yard1 Some suggestion?

**Comment by celestinoxp** [comment]
the problem is not from pycaret but from a third party.
I found this: https://stackoverflow.com/questions/74255709/error-could-not-build-wheels-for-frozenlist-multidict-yarl-which-is-required

Try install Microsoft C++ Build Tools. and try install pycaret again

**Comment by d4deva** [comment]
did that getting a new error
ERROR: Cannot uninstall 'TBB'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by celestinoxp** [comment]
Ok, go to anaconda directory normally C:\Users\your username\anaconda3\Lib\site-packages
then find all folders or files with TBB in the name and delete.
after that install pycaret again, it works for me

**Comment by d4deva** [comment]
it worked thanks
