### ISSUE TITLE
[BUG]: no feature_selection_threshold

### ISSUE THREAD

**Issue by 1grigoryan** [pycaret/pycaret#3080]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

It is written here that there is feature_selection_threshold option in setup (https://pycaret.gitbook.io/docs/get-started/preprocessing/feature-selection), but I can choose only feature_selection option. Using the latest version, 3.0-rc.

### Reproducible Example

```python
from pycaret.classification import *
from pycaret.datasets import get_data
data = get_data('juice')
exp1 = setup(data = data , target = 'Purchase', session_id=123, feature_selection = True, feature_selection_threshold = 0.3)
```

### Expected Behavior

.

### Actual Results

```python-traceback
TypeError                                 Traceback (most recent call last)
Input In [2], in <cell line: 4>()
      2 from pycaret.datasets import get_data
      3 data = get_data('juice')
----> 4 exp1 = setup(data = data , target = 'Purchase', session_id=123, feature_selection = True, feature_selection_threshold = 0.3)

TypeError: setup() got an unexpected keyword argument 'feature_selection_threshold'
```

### Installed Versions

System:
    python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
   machine: Windows-10-10.0.19044-SP0

PyCaret required dependencies:
                 pip: 21.2.4
          setuptools: 61.2.0
             pycaret: 3.0.0rc4
             IPython: 8.2.0
          ipywidgets: 7.6.5
                tqdm: 4.64.1
               numpy: 1.21.0
              pandas: 1.4.0
              jinja2: 2.11.3
               scipy: 1.7.1
              joblib: 1.1.0
             sklearn: 1.1.0
                pyod: 1.0.6
            imblearn: 0.9.1
   category_encoders: 2.5.1.post0
            lightgbm: 2.3.1
               numba: 0.55.1
            requests: 2.28.1
          matplotlib: 3.5.1
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.6.0
             kaleido: 0.2.1
         statsmodels: 0.13.4
              sktime: 0.13.4
               tbats: 1.1.1
            pmdarima: 1.8.5
              psutil: 5.9.4

PyCaret optional dependencies:
                shap: Not installed
           interpret: Not installed
                umap: Not installed
    pandas_profiling: Not installed
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
             xgboost: Not installed
            catboost: 1.1
              kmodes: Not installed
             mlxtend: Not installed
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: Not installed
              optuna: Not installed
               skopt: Not installed
              mlflow: Not installed
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: Not installed
           evidently: Not installed
                nltk: 3.7
            pyLDAvis: Not installed
              gensim: 4.1.2
               spacy: Not installed
           wordcloud: Not installed
            textblob: Not installed
               fugue: Not installed
           streamlit: Not installed
             prophet: Not installed

**Comment by tvdboom** [comment]
pycaret 3.0 uses new features. The documentation hasn't been updated yet. See https://github.com/pycaret/pycaret/blob/8fc8d2bff9ae75d067e2a3424a8cbee592f34e0d/pycaret/classification/oop.py#L518 here the available parameters.
