### ISSUE TITLE
Getting error while executing this compare models code

### ISSUE THREAD

**Issue by VinayakDataScience** [pycaret/pycaret#309]
ImportError: DLL load failed: The paging file is too small for this operation to complete.

**Comment by VinayakDataScience** [comment]
|   |  
-- | -- | --

. . . . . . . . . . . . . . . . . . | 22:02:23
. . . . . . . . . . . . . . . . . . | Loading Dependencies
. . . . . . . . . . . . . . . . . . | Compiling Library
. . . . . . . . . . . . . . . . . . | Calculating ETC

**Comment by pycaret** [comment]
@VinayakDataScience 

Can you please share more details about environment, version, OS, python etc and complete trace back for error message. 

Thanks

**Comment by pycaret** [comment]
@VinayakDataScience Do you still need help?
