### ISSUE TITLE
[BUG]: from pycaret.classification import * AttributeError: 'NoneType' object has no attribute 'extensions_by_name'

### ISSUE THREAD

**Issue by EvilCalf** [pycaret/pycaret#3090]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

![image](https://user-images.githubusercontent.com/35754619/202340937-dc91d2e5-92b1-4647-8464-ee0191660d6b.png)

### Reproducible Example

```python
from pycaret.classification import *
```

### Expected Behavior

AttributeError: 'NoneType' object has no attribute 'extensions_by_name'

### Actual Results

```python-traceback
AttributeError: 'NoneType' object has no attribute 'extensions_by_name'
```

### Installed Versions

<details>
2.3.10
</details>

**Comment by Mcd6** [comment]
I also encountered a similar problem.
Like this：
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by tvdboom** [comment]
Please, retry using the master branch `pip install -U git+https://github.com/pycaret/pycaret.git@master` and share a full reproducible example (data + code). We can't debug without

**Comment by moezali1** [comment]
Unable to reproduce.
