### ISSUE TITLE
[BUG]: Kernel Restarting (Kernel appears to have died.)

### ISSUE THREAD

**Issue by henriquepett** [pycaret/pycaret#3091]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

![CleanShot 2022-11-17 at 08 31 42](https://user-images.githubusercontent.com/115732084/202435308-5563a1be-3392-495c-aef5-ff80df4f836a.png)

I'm having a issue when running compare_models(), on the processing data step. It restarts the kernel every time...

I have 19489 rows, and 14 columns. On the computer (AWS Sagemaker), I have 2 CPUs and 8GB RAM.

This is my parameters:
```
    train_split = 0.8
    time_limit = 6
    metric = 'RMSE'
    
    X_train, X_test, y_train, y_test = train_test_split(df_bl_master_notarget, 
                                                        df_bl_master['target'],
                                                        random_state=104, 
                                                        train_size=train_split, 
                                                        shuffle=True)


    base_treino = pd.concat([X_train, y_train], axis=1)
    base_teste = pd.concat([X_test, y_test], axis=1)
              
    exp_reg101 = setup(data = base_treino, target = 'target', silent=True, session_id=123)
    
    best = compare_models(sort = metric, budget_time=time_limit, cross_validation=False)
    ```

What's the problem here? Can I add a parameter on compare_models() that fix this?

### Reproducible Example

```python
train_split = 0.8
    time_limit = 6
    metric = 'RMSE'
    
    X_train, X_test, y_train, y_test = train_test_split(df_bl_master_notarget, 
                                                        df_bl_master['target'],
                                                        random_state=104, 
                                                        train_size=train_split, 
                                                        shuffle=True)


    base_treino = pd.concat([X_train, y_train], axis=1)
    base_teste = pd.concat([X_test, y_test], axis=1)
              
    exp_reg101 = setup(data = base_treino, target = 'target', silent=True, session_id=123)
    
    best = compare_models(sort = metric, budget_time=time_limit, cross_validation=False)
```

### Expected Behavior

It will restart the Kernel.

### Actual Results

```python-traceback
It will restart the kernel.
```

### Installed Versions

<details>
Version: '2.3.10'
</details>

**Comment by moezali1** [comment]
Can you print the output after `setup`. How many columns are created in train set after transformation?

**Comment by henriquepett** [comment]
Sure!

I reran it and realized that the problem is on setup(), not in compare_models(). My mistake!

The state of the notebook after restarting the kernel:

<img width="589" alt="CleanShot 2022-11-21 at 08 55 48@2x" src="https://user-images.githubusercontent.com/115732084/203046972-6d019db9-1591-45ee-8c0d-a3ec27553831.png">

**Comment by moezali1** [comment]
@henriquepett I am guessing this is because one of these feature is categorical or being treated as categorical with many levels and hence it takes a huge time. Can you explicitly pass the data types by using `categorical_features` and `numeric_features` parameter in the `setup`.
