### ISSUE TITLE
How to get the value of compare_models table

### ISSUE THREAD

**Issue by andrealbh** [pycaret/pycaret#31]
When we use the make_model/ compare_models/tune_model function, a table containing much information will be returned. Is it any function used for get a specific row/column/value of the table?

**Comment by pycaret** [comment]
compare_models() returns a dataframe that has all the values. You can access it just like how you would access pandas dataframe (using loc or iloc). Other functions unfortunately, doesn't return the metric table, it only displays them.

I will mark this as an enhancement and if I get more requests like this, I will prioritize this functionality in next release.

**Comment by pycaret** [comment]
@andrealbh 

### Feature now available in pycaret-nightly.
You can install pycaret-nightly using "pip install pycaret-nightly".

New function named **pull()** is now added which allows you to store the dataframe printed as a variable. See example below:

> compare_models()
> results = pull()

variable **results** will be a dataframe.

Can you please test this and close the issue if the enhancement addresses the original issue.

It will be shipped to PyCaret 2.0x in few weeks.
