### ISSUE TITLE
[ENH]: Integration of new algorithm: IsolationForest

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#3108]
### Describe the feature you want to add to this project

Integration of new algorithm: IsolationForest

### Describe your proposed solution

All details: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.IsolationForest.html

**Comment by moezali1** [comment]
@celestinoxp Its already available in `pycaret.anomaly`. We have used implementation from `pyod`.
