### ISSUE TITLE
ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2

### ISSUE THREAD

**Issue by nkalhan** [pycaret/pycaret#311]
Have already installed pycaret-nightly but still have this error:

My code is: 

from pycaret.classification import *
pce_1 = setup(data= lda_data, target = 'Division', session_id=23, train_size=0.80)

--------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-6815b39b1ac4> in <module>
----> 1 pce_1 = setup(data= lda_data, target = 'Division', session_id=23, train_size=0.80)

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\pycaret\classification.py in setup(data, target, train_size, sampling, sample_estimator, categorical_features, categorical_imputation, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, data_split_shuffle, folds_shuffle, n_jobs, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile)
   1772             if html_param:
   1773                 update_display(monitor, display_id = 'monitor')
-> 1774         X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1-train_size, stratify=y, random_state=seed, shuffle=data_split_shuffle)
   1775         progress.value += 1
   1776 

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_split.py in train_test_split(*arrays, **options)
   2150                      random_state=random_state)
   2151 
-> 2152         train, test = next(cv.split(X=arrays[0], y=stratify))
   2153 
   2154     return list(chain.from_iterable((_safe_indexing(a, train),

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_split.py in split(self, X, y, groups)
   1339         """
   1340         X, y, groups = indexable(X, y, groups)
-> 1341         for train, test in self._iter_indices(X, y, groups):
   1342             yield train, test
   1343 

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_split.py in _iter_indices(self, X, y, groups)
   1666         class_counts = np.bincount(y_indices)
   1667         if np.min(class_counts) < 2:
-> 1668             raise ValueError("The least populated class in y has only 1"
   1669                              " member, which is too few. The minimum"
   1670                              " number of groups for any class cannot"

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

**Comment by mahmoudyusof** [comment]
telling by reading the error message, I can tell that the data you have is too skewed because one of the classes has only one sample which is too few, adding one more sample of the same class to the data or removing this class altogether should solve the problem.

**Comment by swankyshahir** [comment]
Check value_counts of the target class and drop the row that has only one instance of it or add rows with more instances of the ssame.

**Comment by pycaret** [comment]
@nkalhan If this solves your problem, please close then issue :)

**Comment by nkalhan** [comment]
Thank you for your reply:
after following your advice, I am getting different error now...

Here is the code below:

from pycaret.classification import *
exp_clf_1 = setup(data, target='Division', high_cardinality_features=['Account Name'], high_cardinality_method='clustering')

![Dataset Description](https://user-images.githubusercontent.com/54247640/89125832-7b532c80-d4e1-11ea-91a8-020994d83243.JPG)


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-e49e5ca99fa0> in <module>
      1 from pycaret.classification import *
----> 2 exp_clf_1 = setup(data, target='Division', high_cardinality_features=['Account Name'], high_cardinality_method='clustering')

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\pycaret\classification.py in setup(data, target, train_size, sampling, sample_estimator, categorical_features, categorical_imputation, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, data_split_shuffle, folds_shuffle, n_jobs, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile)
   1206                                           display_types = display_dtypes_pass, #this is for inferred input box
   1207                                           target_transformation = False, #not needed for classification
-> 1208                                           random_state = seed)
   1209 
   1210     progress.value += 1

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\pycaret\preprocess.py in Preprocess_Path_One(train_data, target_variable, ml_usecase, test_data, categorical_features, numerical_features, time_features, features_todrop, display_types, imputation_type, numeric_imputation_strategy, categorical_imputation_strategy, apply_zero_nearZero_variance, club_rare_levels, rara_level_threshold_percentage, apply_untrained_levels_treatment, untrained_levels_treatment_method, apply_ordinal_encoding, ordinal_columns_and_categories, apply_cardinality_reduction, cardinal_method, cardinal_features, apply_binning, features_to_binn, apply_grouping, group_name, features_to_group_ListofList, apply_polynomial_trigonometry_features, max_polynomial, trigonometry_calculations, top_poly_trig_features_to_select_percentage, scale_data, scaling_method, Power_transform_data, Power_transform_method, target_transformation, target_transformation_method, remove_outliers, outlier_contamination_percentage, outlier_methods, apply_feature_selection, feature_selection_top_features_percentage, remove_multicollinearity, maximum_correlation_between_features, remove_perfect_collinearity, apply_feature_interactions, feature_interactions_to_apply, feature_interactions_top_features_to_select_percentage, cluster_entire_data, range_of_clusters_to_try, apply_pca, pca_method, pca_variance_retained_or_number_of_components, random_state)
   2563     return(pipe.fit_transform(train_data),pipe.transform(test_data))
   2564   else:
-> 2565     return(pipe.fit_transform(train_data))
   2566 
   2567 

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\pipeline.py in fit_transform(self, X, y, **fit_params)
    365         """
    366         fit_params_steps = self._check_fit_params(**fit_params)
--> 367         Xt = self._fit(X, y, **fit_params_steps)
    368 
    369         last_step = self._final_estimator

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\pipeline.py in _fit(self, X, y, **fit_params_steps)
    294                 message_clsname='Pipeline',
    295                 message=self._log_message(step_idx),
--> 296                 **fit_params_steps[name])
    297             # Replace the transformer of the step with the fitted
    298             # transformer. This is necessary when loading the transformer

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\joblib\memory.py in __call__(self, *args, **kwargs)
    350 
    351     def __call__(self, *args, **kwargs):
--> 352         return self.func(*args, **kwargs)
    353 
    354     def call_and_shelve(self, *args, **kwargs):

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    738     with _print_elapsed_time(message_clsname, message):
    739         if hasattr(transformer, 'fit_transform'):
--> 740             res = transformer.fit_transform(X, y, **fit_params)
    741         else:
    742             res = transformer.fit(X, y, **fit_params).transform(X)

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\pycaret\preprocess.py in fit_transform(self, dataset, y)
   1405     # now make PLS
   1406     self.pls = PLSRegression(n_components=2) # since we are only using two componenets to group #PLSRegression(n_components=len(data_t1.columns)-1)
-> 1407     data_pls = self.pls.fit_transform(data_t.drop(self.target,axis=1),data_t[self.target])[0]
   1408 
   1409     # # now we will take one component and then we calculate mean, median, min, max and sd of that one component grouped by the catagorical levels

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\cross_decomposition\_pls.py in fit_transform(self, X, y)
    517         x_scores if Y is not given, (x_scores, y_scores) otherwise.
    518         """
--> 519         return self.fit(X, y).transform(X, y)
    520 
    521     def _more_tags(self):

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\cross_decomposition\_pls.py in fit(self, X, Y)
    281         check_consistent_length(X, Y)
    282         X = self._validate_data(X, dtype=np.float64, copy=self.copy,
--> 283                                 ensure_min_samples=2)
    284         Y = check_array(Y, dtype=np.float64, copy=self.copy, ensure_2d=False)
    285         if Y.ndim == 1:

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\base.py in _validate_data(self, X, y, reset, validate_separately, **check_params)
    418                     f"requires y to be passed, but the target y is None."
    419                 )
--> 420             X = check_array(X, **check_params)
    421             out = X
    422         else:

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     71                           FutureWarning)
     72         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 73         return f(**kwargs)
     74     return inner_f
     75 

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    532 
    533         if all(isinstance(dtype, np.dtype) for dtype in dtypes_orig):
--> 534             dtype_orig = np.result_type(*dtypes_orig)
    535 
    536     if dtype_numeric:

<__array_function__ internals> in result_type(*args, **kwargs)

ValueError: at least one array or dtype is required

**Comment by mahmoudyusof** [comment]
is seems that the error hasn't change. one possible explanation is that pycaret splits the data by stratifying over the the label which means if you have 10 instances of a certain class and use a 70% 30% split then seven of them will end up in the training set and 3 in the validation set, if you only have 2 instances and do a 50-50 split, only one instance will end up in the training set thus causing the same issue. to be safe make sure each class has more than 5 instances or drop classes that have less than that. This might and might not solve the problem, but this is what I know.

**Comment by pycaret** [comment]
@nkalhan Can you please show the value_count of your target variables. One of the class < number of folds. This is the cause of the error.

**Comment by nkalhan** [comment]
@mahmoudyusof  thank you very much for your reply... it was i guess only because on eof the class was less than the number of folds.. i am able to overcome that error.. have some other kind of error now.. please have a look..
@pycaret  thank you very much for your support... please have a look at this error as well.. 

Logistic Regression model ran fine.. but KNN throws error

HOW CAN I OVERCOME THIS MEMORY ERROR? because logistics worked fine but not KNN. In this case, I just want to know beforehand which model can throw memory error. Because each model takes couples of hours to run. Thank you very much again.
![KNN error](https://user-images.githubusercontent.com/54247640/89717378-66313e80-d9b6-11ea-8d08-6cc69c9640a9.JPG)
[logs.log](https://github.com/pycaret/pycaret/files/5046074/logs.log)



---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-45-9ff5ccfe3077> in <module>
----> 1 compare_models()

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\pycaret\classification.py in compare_models(blacklist, whitelist, fold, round, sort, n_select, turbo, verbose)
   4935                 time_start=time.time()
   4936                 logger.info("Fitting Model")
-> 4937                 model.fit(Xtrain,ytrain)
   4938                 logger.info("Evaluating Metrics")
   4939                 time_end=time.time()

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\multiclass.py in fit(self, X, y)
    243                 "not %s" % self.label_binarizer_.classes_[i],
    244                 self.label_binarizer_.classes_[i]])
--> 245             for i, column in enumerate(columns))
    246 
    247         return self

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\joblib\parallel.py in __call__(self, iterable)
   1030                 self._iterating = self._original_iterator is not None
   1031 
-> 1032             while self.dispatch_one_batch(iterator):
   1033                 pass
   1034 

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\joblib\parallel.py in dispatch_one_batch(self, iterator)
    845                 return False
    846             else:
--> 847                 self._dispatch(tasks)
    848                 return True
    849 

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\joblib\parallel.py in _dispatch(self, batch)
    763         with self._lock:
    764             job_idx = len(self._jobs)
--> 765             job = self._backend.apply_async(batch, callback=cb)
    766             # A job can complete so quickly than its callback is
    767             # called before we get here, causing self._jobs to

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\joblib\_parallel_backends.py in apply_async(self, func, callback)
    206     def apply_async(self, func, callback=None):
    207         """Schedule a func to be run"""
--> 208         result = ImmediateResult(func)
    209         if callback:
    210             callback(result)

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\joblib\_parallel_backends.py in __init__(self, batch)
    570         # Don't delay the application, to avoid keeping the input
    571         # arguments in memory
--> 572         self.results = batch()
    573 
    574     def get(self):

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\joblib\parallel.py in __call__(self)
    251         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    252             return [func(*args, **kwargs)
--> 253                     for func, args, kwargs in self.items]
    254 
    255     def __reduce__(self):

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\joblib\parallel.py in <listcomp>(.0)
    251         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    252             return [func(*args, **kwargs)
--> 253                     for func, args, kwargs in self.items]
    254 
    255     def __reduce__(self):

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\multiclass.py in _fit_binary(estimator, X, y, classes)
     79     else:
     80         estimator = clone(estimator)
---> 81         estimator.fit(X, y)
     82     return estimator
     83 

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\neighbors\_base.py in fit(self, X, y)
   1155             self._y = self._y.ravel()
   1156 
-> 1157         return self._fit(X)
   1158 
   1159     def _more_tags(self):

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\neighbors\_base.py in _fit(self, X)
    456             self._tree = KDTree(X, self.leaf_size,
    457                                 metric=self.effective_metric_,
--> 458                                 **self.effective_metric_params_)
    459         elif self._fit_method == 'brute':
    460             self._tree = None

sklearn\neighbors\_binary_tree.pxi in sklearn.neighbors._kd_tree.BinaryTree.__init__()

sklearn\neighbors\_kd_tree.pyx in sklearn.neighbors._kd_tree.allocate_data()

MemoryError: Unable to allocate 13.8 MiB for an array with shape (2, 2047, 441) and data type float64
