### ISSUE TITLE
[ENH]: update all official tutorials before 3.0 release

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#3120]
### Describe the feature you want to add to this project

update all official tutorials before 3.0 release

### Describe your proposed solution

update all official tutorials before 3.0 release

**Comment by Piyushlamsoge** [comment]
If I'm right  , Pycaret not compatible to work with images and to achieve that it can working with other modules So if somehow Pycaret is powerful enough to work with images and other sort of data by its own Then , It is the best module for Both ML and DL as well !!!!!
