### ISSUE TITLE
[DOC]: remove NLP and arules related libraries from requirements-optional

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#3124]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

remove NLP and arules related libraries from requirements-optional

### Documentation problem

remove NLP and arules related libraries from requirements-optional

### Suggested fix for documentation

remove NLP and arules related libraries from requirements-optional

**Comment by ngupta23** [comment]
@moezali1 @Yard1 If we agree on #3099, then this issue should be changed to 3.1.0 milestone.
