### ISSUE TITLE
[DOC]: create benchmark comparison report b/w 2.0 and 3.0

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#3125]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

create benchmark comparison report b/w 2.0 and 3.0

### Documentation problem

create benchmark comparison report b/w 2.0 and 3.0

### Suggested fix for documentation

create benchmark comparison report b/w 2.0 and 3.0

**Comment by moezali1** [comment]
# Results

![image](https://user-images.githubusercontent.com/54699234/210862415-4975d2af-c1a3-438b-9588-6b19880b632c.png)

![image](https://user-images.githubusercontent.com/54699234/210862424-992625b0-5fe3-4a66-9d00-16ea7e7a926f.png)

**Comment by PabloJMoreno** [comment]
hey @moezali1 let me know if I can help you here. I have done a lot of testing already. Thanks
