### ISSUE TITLE
[INSTALL]: 

### ISSUE THREAD

**Issue by Gyagupta** [pycaret/pycaret#3128]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

google colab

### Installation Method

pip install

### pycaret Version

Pycarate=2.0

### Python Version

Pycarate=2.0

### Description

Please help driving the final regression equation after belnding of top 3 models in PyCaret!!
Blending of models
I am blending three or four regression models but cannot get the final equation model (regression equation model).

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by ngupta23** [comment]
@Gyagupta The issue is not clear. Please file the right issue with details to reproduce it. Thanks!

**Comment by Gyagupta** [comment]
I have raised a new issue with details and code.
Please see if that helps in understanding the issue.
