### ISSUE TITLE
[BUG]: get_config('X_train') doesn't return right dataframe

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#3131]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I am running experiment with `feature_selection`. The `setup` output shows I should have 2 features in my transformed dataset but when I call `get_config('X_train')` I see more than 2 features. Why it is not matching?

![image](https://user-images.githubusercontent.com/54699234/204553278-6fad7105-6883-42b4-a7d2-aa696bcdf03c.png)

![image](https://user-images.githubusercontent.com/54699234/204553324-048d02ef-ce67-4ba9-bbc6-a31808388500.png)

See the reproducible notebook:

https://colab.research.google.com/drive/1TDP1RzhusUgZZzww4kKsVNbLGo5tmVV1?usp=sharing

### Reproducible Example

```python
see above
```

### Expected Behavior

see above

### Actual Results

```python-traceback
see above
```

### Installed Versions

master

**Comment by tvdboom** [comment]
We just merged a PR to change this behavior #3117

**Comment by ngupta23** [comment]
@moezali1 With the latest change, you should try getting instead of X_train

```python
get_config('X_train_transformed')
```

**Comment by moezali1** [comment]
@ngupta23 @tvdboom For classification and regression module when I try to get transformed dataset using `get_config('X_train_transformed')` I get this:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-12-5dba283e8527>](https://localhost:8080/#) in <module>
----> 1 get_config('X_train_transformed')

2 frames
[/usr/local/lib/python3.7/dist-packages/pycaret/internal/pycaret_experiment/pycaret_experiment.py](https://localhost:8080/#) in get_config(self, variable)
    281         if variable not in self.variables:
    282             raise ValueError(
--> 283                 f"Variable {variable} not found. Possible variables are: {list(self.variables)}"
    284             )
    285 

ValueError: Variable X_train_transformed not found. Possible variables are: ['log_plots_param', 'master_model_container', 'fold_generator', '_ml_usecase', 'X', 'X_train', 'html_param', 'gpu_param', 'exp_id', 'idx', 'X_test', 'display_container', 'target_param', 'fold_shuffle_param', '_gpu_n_jobs_param', 'y', 'exp_name_log', 'USI', 'logging_param', 'fold_groups_param', 'y_test', 'variable_keys', '_all_models', 'n_jobs_param', 'pipeline', 'data', '_available_plots', 'y_train', '_all_models_internal', 'memory', 'fix_imbalance', 'seed', '_all_metrics', '_is_multiclass']
