### ISSUE TITLE
[BUG]: get_config in functional API not complete

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#3132]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Three issues:

1. All attributes in OOP API should be available with get_config method in functional API but that's not the case. Following are attributes available in OOP:
 - 'dataset',
 - 'dataset_transformed',
 - 'display_container',
 - 'exp_id',
 - 'exp_model_engines',
 - 'exp_name_log',
 - 'fold_generator',
 - 'fold_groups_param',
 - 'fold_shuffle_param',
 - 'gpu_param',
 - 'html_param',
 - 'idx',
 - 'index',
 - 'log_plots_param',
 - 'logger',
 - 'logging_param',
 - 'master_model_container',
 - 'memory',
 - 'n_jobs_param',
 - 'pipeline',
 - 'seed',
 - 'target_param',
 - 'test',
 - 'test_transformed',
 - 'train',
 - 'train_transformed',
 - 'transform_target_param',
 - 'variable_keys',
 - 'variables',
 - 'verbose',
 - 'y',
 - 'y_test',
 - 'y_test_transformed',
 - 'y_train',
 - 'y_train_transformed',
 - 'y_transformed',
 - 'USI',
 - 'X',
 - 'X_test',
 - 'X_test_transformed',
 - 'X_train',
 - 'X_train_transformed',
 - 'X_transformed'

2. In addition to this, certain variables that must be available (as shown in error message) are also not available. For example error msg in get_config shows:

```
ValueError: Variable dataset not found. Possible variables are: ['_all_metrics', 'fix_imbalance', 'X_train', 'fold_groups_param', '_all_models', 'memory', 'y', 'variable_keys', 'USI', 'target_param', 'logging_param', 'exp_id', 'fold_generator', 'n_jobs_param', '_is_multiclass', 'X_test', 'y_train', 'pipeline', 'exp_name_log', '_ml_usecase', 'y_test', '_all_models_internal', 'html_param', 'seed', 'display_container', 'data', '_available_plots', 'gpu_param', 'log_plots_param', 'idx', 'X', 'master_model_container', '_gpu_n_jobs_param', 'fold_shuffle_param']
```
but when you try to get access to `get_config('fix_imbalance')` you will get an error.

3. Finally, `get_config('X_train')` is supposed to give you access to transformed train set but that's not the case. In PyCaret 2 it gives access to transformed train set. If we want to give original dataset sampled to training set for X_train then we must expose `X_train_transformed`. 

Notebook: https://colab.research.google.com/drive/1UFHvlcW4WmCD4fEssr8vDXNFCtI-05jb?usp=sharing

### Reproducible Example

```python
see above
```

### Expected Behavior

see above

### Actual Results

```python-traceback
see above
```

### Installed Versions

master

**Comment by tvdboom** [comment]
@ngupta23 Could you have a look at this one? I think you refactored `get_config` recently. My opinion here is that we perhaps need a bigger refactoring to do this right. My thoughts:

* Having global variables is awful practice in general. Avoid them at all cost. Just keep the current experiments in global for functional API (maybe this is already the case, haven't checked)
* We should have all the parameters retrievable by `get_config` as attributes of the experiment instance plus the data properties.
* All attributes that start with underscore should be strictly internal and therefore not returned by `get_config`. If they should be accessible by users, remove the leading underscore.
* Some attributes are outdated, like `fix_imbalance`. Not sure what that's supposed to return.

Thoughts? (@Yard1 as well)

**Comment by moezali1** [comment]
Action items:

- Keep `get_config` and `set_config` for both functional and OOP API. 
- Make sure all public variables are available in `variable_keys` for user to be able to access them. Right now certain variables like `X_train_transformed` is not available.
- Make consistent OOP and functional API variables.
- Add a function `get_current_experiment` in functional API that will return the object of the active experiment.
