### ISSUE TITLE
I am applying muliple regression methods given in Pycaret libreary and then i am getting final aggregating results of these methods through the blending.

### ISSUE THREAD

**Issue by Gyagupta** [pycaret/pycaret#3139]
I am applying multiple regression methods using Pycaret and then i am getting final aggregating (Y) results of these methods through the blending.
but i am not able to get the final regression equation (with coefficient) after using blender function for multiple regression methods.
how can i get the final regression equation (After blending) also?

please help!!

# Blending models
blender = blend_models(estimator_list = [tuned_decision_tree, tuned_bayesian_ridge, tuned_linear_regression])

_Originally posted by @Gyagupta in https://github.com/pycaret/pycaret/discussions/3138_

**Comment by ngupta23** [comment]
You can not get a "regression equation" for an ensemble model (AFAIK) if that is what you are asking for. 
Have you seen this ability in any other library? If so, please share the details. Thanks!

**Comment by ngupta23** [comment]
It uses the following scikit model under the hood. Please refer to it's documentation on how it works.

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.VotingRegressor.html
