### ISSUE TITLE
How to see all the feature importances, only top ten features are shown

### ISSUE THREAD

**Issue by swankyshahir** [pycaret/pycaret#314]
Dear sir/madam,
when i plot  the feature importance via
`plot_model(lr, plot='feature' , )`

i get to see only the top ten features. How do i see the importance of all the features.

**Comment by pycaret** [comment]
@swankyshahir 

You can always call .coef_ or feature_importances_ method on model if it supports that. For example:

lr = create_model('lr')
lr.coef_

rf = create_model('rf')
rf.feature_importances_

Hope this helps.

**Comment by swankyshahir** [comment]
lr.coef_ gives this output .....long array !!!! i dont think i have this many columns even after accounting for any number of one-hot encoding... also anyway to map the columns/print the columns ,  after transformation...???

array([[ 2.32325073e-01, -3.14324234e-01,  4.79592959e-01,
        -3.63525747e-01,  1.07050221e-01,  8.46515322e-01,
         6.21041569e-01, -4.27698354e-01, -7.23787023e-02,
        -1.20951710e-01,  2.37743277e-01, -1.98385388e-02,
        -4.46115708e-01,  2.28223773e-01, -5.40757627e-01,
         1.29037538e-01, -3.74592536e-01,  4.87046179e-01,
         2.99279248e-01,  5.07666947e-02, -4.95645548e-01,
        -8.89042818e-01,  1.26339588e+00,  1.21305291e-01,
         1.87371636e-01,  8.06706302e-01, -4.93065086e-01,
        -5.01000049e-01,  2.04432632e-01, -1.28852196e-01,
        -1.45516698e-01,  7.10170230e-02, -1.06795827e-03,
        -5.91360006e-01, -4.43434931e-01, -2.09522933e-02,
         1.66531150e+00, -4.62083243e-01,  3.73118977e-01,
        -2.39431277e-01,  1.01468535e-02, -1.43821750e-01],
       [-7.26397732e-01,  3.02963288e-01, -4.44257866e-01,
         1.05396674e+00,  6.90006512e-02, -2.68298416e-01,
        -3.11069217e-01,  1.24963498e-02, -1.33795423e-01,
         4.32311399e-01, -2.07651745e-01,  3.17704157e-01,
        -7.71426728e-02, -3.29666305e-02,  2.70246748e-01,
         4.07820503e-01,  8.57569349e-01, -6.49327790e-01,
        -8.86365701e-01,  8.92864922e-02, -3.82070810e-01,
         8.56154844e-02, -2.28062517e-01,  5.24460951e-01,
         4.33772844e-01,  1.50671541e-01,  2.19384657e-01,
        -8.03885933e-01, -4.69701387e-01, -2.69673970e-01,
         9.61009785e-01,  1.16314135e-01, -3.38005454e-01,
        -4.66438845e-01,  1.94444353e-01, -1.34244488e-01,
        -1.07585357e-01, -5.91331312e-01, -2.88573038e-01,
         2.09826650e+00, -1.10083628e+00, -7.08914080e-01],
       [ 2.97425950e-01,  1.33502127e-01,  3.50777887e-01,
        -6.48104144e-02, -3.37192508e-01,  1.74928175e-01,
         2.97425538e-01, -2.93498864e-01,  4.47826493e-01,
        -4.51658947e-01, -6.46838119e-01,  2.35280577e-01,
         2.01603464e-01,  2.10048299e-01,  5.88052050e-01,
         3.52976682e-01, -7.80592233e-01,  2.71457786e-01,
        -4.31800063e-01,  2.01806274e-01, -5.47392982e-01,
         6.14180339e-01,  2.09845788e-01, -2.76538925e-01,
        -4.49663195e-01,  1.64127330e-01,  4.88498370e-01,
        -2.02868284e-01,  1.54558523e+00, -4.75998030e-01,
        -2.60037489e-01,  3.50653103e-02, -8.44520798e-01,
         9.82796754e-01, -5.43419095e-01, -2.18654329e-02,
        -1.85093690e-01,  3.42212344e-02,  4.89968473e-01,
        -4.23015487e-01,  1.08441944e+00, -1.15127821e+00],
       [ 2.56790687e-01, -7.68467464e-02, -1.82654026e-01,
        -7.22191871e-01,  3.12131977e-01, -2.56558259e-01,
        -4.74025306e-02,  2.22816739e-01, -5.32526708e-01,
         3.57153719e-01,  5.60653600e-01, -4.24653420e-01,
        -1.44745504e-01,  8.78654374e-03, -3.86288802e-01,
        -5.56657118e-01,  1.56885250e-01, -1.32938357e-01,
         9.19040247e-01, -1.44071971e-01,  9.28073088e-01,
         1.23501210e-01, -7.11807190e-01, -3.39725888e-01,
         1.12877660e-02, -4.14954426e-01, -3.91641774e-01,
         7.95349654e-01, -6.95751627e-01,  8.06945486e-01,
        -6.48688875e-01,  2.97236289e-02,  5.07812607e-01,
         1.32539141e-01,  7.27225411e-01,  1.28924148e-01,
        -4.03922748e-01,  3.38874956e-01,  8.95891606e-02,
        -1.59631451e+00,  5.38876205e-02,  1.45287895e+00]])
