### ISSUE TITLE
[BUG]: pycaret-ts-alpha import name issue

### ISSUE THREAD

**Issue by nschneider35** [pycaret/pycaret#3140]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I am trying to run a CSV through Pycaret based on this example and using pycaret-ts-alpha - I am getting the following error:
Exception has occurred: ImportError
cannot import name '_check_param_grid' from 'sklearn.model_selection._search' (/Users/my_user/Library/Python/3.9/lib/python/site-packages/sklearn/model_selection/_search.py)
  File "/Users/my_user/Documents/Pythin/scoring_model", line 13, in <module>
    from pycaret.classification import *

### Reproducible Example

```python
Most recent install
```

### Expected Behavior

No error message 

### Actual Results

```python-traceback
Exception has occurred: ImportError
cannot import name '_check_param_grid' from 'sklearn.model_selection._search' (/Users/my_user/Library/Python/3.9/lib/python/site-packages/sklearn/model_selection/_search.py)
```

### Installed Versions

Most recent (having issues even getting this to run(

**Comment by ngupta23** [comment]
This question has already been answered multiple times. Please refer to older GitHub issues please.
Also, it would be best to use the pre-release version of pycaret now since pycaret-ts-alpha is depracated.
