### ISSUE TITLE
[INSTALL]:  pip install sklearn is depreciated, use pip install scikit-learn

### ISSUE THREAD

**Issue by astrobenhart** [pycaret/pycaret#3141]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Linux-5.4.0-1045-aws-x86_64-with-glibc2.17

### Installation Method

pip install

### pycaret Version

2.3.10

### Python Version

3.8.15

### Description

Need to update install for sklearn to use scikit-learn.

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by ngupta23** [comment]
It is already set to scikit-learn in the master branch (available as pre release right now - 3.0.0rc4). Feel free to reopen if you have a followup.

https://github.com/pycaret/pycaret/blob/6678c518a8522c28c80d34fa38a77df2763faa1d/requirements.txt#L10
