### ISSUE TITLE
Comparing tuned models

### ISSUE THREAD

**Issue by eonsmile** [pycaret/pycaret#316]
Anyway to compare tuned models instead of raw untuned models?  Some models perform much better after tuning and it's good if these can "survive" the initial rounds with compare_models.

**Comment by pycaret** [comment]
@eonsmile This is not possible at the moment. I am tagging **enhancement** on this issue for future versions.

**Comment by pycaret** [comment]
@eonsmile Hi, we have internally checked the viability of this functionality. Actually, in the early release, we were providing this functionality to get the tuned models from compare_models instead of plain vanilla. This wasn't feasible in terms of training time.

At this time, I will be closing this issue, and maybe in future at some point we might reopen to put it in our backlog.

Thanks anyways.

**Comment by Yard1** [comment]
As `compare_models` will support comparison of trained model objects, code will be possible in `2.2`:
```python
5_best = compare_models(n_select = 5)
5_best_tuned = [tune_model(x) for x in 5_best]
compare_models(include = 5_best_tuned)
```.

**Comment by nateGeorge** [comment]
The training time depends on the size of the data and can be sped up with GPU and more powerful hardware. I think it should still be an option in `compare_models` that's deactivated by default. Some models' default hyperparameters are prone to overfitting, like random forests and decision trees with `max_depth=None` (unlimited splits in the trees), and you can get substantial performance increases by tuning models. At least some hyperparameters should be changed from defaults like max_depth to prevent overfitting, or hyperparameters should be set to usual known good values (which are not always the defaults).

The way @Yard1 showed how to do it works if we select all models, then tune them, then compare them again. It's hacky and ugly:

```python
from pycaret.datasets import get_data
import pycaret.classification as pyclf

diabetes = get_data('diabetes')

setup = pyclf.setup(diabetes, target='Class variable')
models = pyclf.models()  # you can't call models() until setup has been called - maybe a bug
fit_models = pyclf.compare_models(n_select=models.shape[0])
tuned_models = [pyclf.tune_model(model) for model in fit_models]
compare_models(tuned_models)
```
