### ISSUE TITLE
Request for time series new features, parameters and Rest API tutorial

### ISSUE THREAD

**Issue by sathishkumar999** [pycaret/pycaret#3162]
### Describe the feature you want to add to this project

Hello pycaret team,
I'm looking for time series forecasting Rest API using pycaret with custom parameters.
But I couldn't not find tutorial on pycaret to create Rest API for forecasting the future. 
I wanted to have tutorial where we can train our time series data on single input or multiple inputs columns. And we have to save the model. 
In the postman or front end we have to provide date range. And it will predict the future elements on daily, weekly, monthly, quarterly, yearly and if the date is combined with time it should forecast hourly. and saves the results in the form of data frame or json results.

the pycaret predict_model should have all these paramerters for time_series

predict_model('date_range' = [from_date, to_date],'hourly' = [],'days'=[],'weekly' = [],'monthly' = [], 'quarterly' = [], 'yearly' = [])

here the user can give the custom date_range and also number of hours forecast, number of days forecast, number of weeks forecast.etc

Conditions and parameters for predict_model inputs.
Conditions_1: date_range
1.If date_range input has less than  5 days. It will give daily forecast,
2.if date_range input has more than 7 days and less than a 30 days. It should predict daily and weekly report. 
3.If date_range input has more than 30 days and less than 90 days, it should predict daily, weekly and monthly report.
4.If date_range input has more than 90 days and less than 265 days. It should predict daily, weekly, monthly and quarterly report.
5.If date_range input has more than 365 days, it should predict daily, weekly, monthly, quarterly and yearly report.
And also it saves all the plots in 3d format.

Condition_2: daily, weekly, monthly, quarterly and yearly parameters in prefict_model. 
And the parameters should be optional. But any one of the parameter must be passed.
Optional parameters in the input are daily, weekly, monthly, quarterly and yearly.

If the user enter daily= 10, it should forecast for 10 days.
If the user enters weekly= 8, it should forecast for 8 weeks.
Like that it should forecast for monthly, quarterly and yearly. And these parameters should be optional.
And the results should be showed in data frame or json format. And all the forecast results should be saved in 3d visualization plots.

Condition_3: Time_parameter
If model is trained along with time. It should forecast for hourly as well.
And in the predict model it should forecast for hourly. And it should be optional parameter along with daily, weekly, monthly, quarterly and yearly. But any one parameter must be mandatory.
Note: for example, if our model is trained from 2000 year to 2020. It should predict only above 2020 year but not below 2000 year.
If the user by mistake provide date range below 2000 year to forecast. It should send a warning message that the model is trained from 2000 year to 2020 year. Please give date range above 2020. But not below 2000 year or else please enter parameters on daily, weekly, monthly, quarterly and yearly. Instead of date_range

### Describe your proposed solution

The solution to give warning message for date range is. We can use minimum and maximum function to identify date_range in table while training and saving the model. In the forecasting when we enter date_range function we use try, except  exception handling in the backend while predict_model. If date range is above maximum_date while training, then only it should forecast. Or else send a alert message. Please enter date range above 2020. Because model is trained between 2000 to 2020. Please don't give date range less than 2000  year or else please enter parameters on daily, weekly, monthly, quarterly and yearly. Instead of date_range. If the data has time while training, the time parameter also should include in predict_model

**Comment by ngupta23** [comment]
If your model is trained on weekly data, you can not directly forecast anything less frequently than that (e.g. day). There are 2 options for you

1. Option 1: Train the model at the lowest level you want to forecast (the training data should be at that level). Then all forecasts will also be at that level. But you have the ability to aggregate up in frequency based on that. e.g. if you are training at a weekly level, you will forecast at the weekly level and then have the ability to aggregate up to monthly, quarterly, or yearly level.
2. Option 2: Build individual models to forecast at different levels, e.g. one model to forecast at weekly level (this will be trained using weekly data), one model to forecast at a monthly level (trained on monthly data), etc.

I don't believe any changes are needed to `pycaret` API interface for this. You will have to write wrapper code around pycaret to customize it for your needs (for training and predicting at the appropriate level).
