### ISSUE TITLE
Request for NLP new Features: language detection, Sentiment analysis, Text transilation, Topic classification, NER[Per, org, Loc], Custom Entities.

### ISSUE THREAD

**Issue by sathishkumar999** [pycaret/pycaret#3163]
### Describe the feature you want to add to this project

Hello Pycaret Team....
I have worked on a project purely on NLP. we have many use cases. and we have successfully built Rest API's for all of them with different python libraries. but In my experience Pycaret Library is great which will train all the models at a time. but we were able to use pycaret only for classification problem. we can't able to use it for remaining all the use cases. so I wanted to bring up to you all those use cases to keep in pycaret. so in future we don't need to use multiple libraries. one library for all the usecase.
the library should be like this

text = ["Hello my name is Sathish kumar. I'm working in XYZ company as Senior software Engineer. I live bangalore City. My native is chittoor, Andhrapradesh. I'm having issue in kit12sd server. please have a look and fix it soon. it's downing my work"]

import pandas as pd
nlp_data = pd.DataFrame(text, columns = ['document'])

from pycaret.nlp import *
nlp_exp = setup(data = nlp_data, custom_entities = [{'servers' :['kit12sd ', 'dgh245'],'apps':['cbds','2424cv'], lang_detection=True, lang_transilation= ['en','Spanish',etc], NER = ['per','org','loc',etc], text_topic_classification = True, sentiment_analysis = True, extract_urls = True, extract_emails = true, top_keyphrase = True, top_keywords = True)

here 1.nlp_data is the document in data frame.
2.custom_entities is optional here. if customer wants to identify his own entities in the document he can pass the entity name and entities in data frame format or dictionary format. here i passed servers and apps to identify them in our document. this parameter should be optional.
3. lang_detection is to detect the language of the given document. by default it's true.
4. lang_transilaion is to transilate the language of the given document. by default it should be English and it can be changed to different languages as optional.
5. NER is used to detect named entities from data. it can be optional as well. and if customer wants to extract specific NER's he can mention whether he wants to extract persons or Organization or Locations .etc from given document.
6. text_topic_classication. this is also optional. if it's true, it should tell the topic of the document. whether it's politics or healthcare or sports. etc
7. sentiment_analysis is to classify whether the document is positive, negative or neutral sentiment. it should be True by default
8.  extract_url's  and emails is to detect and extract the email's from the given document
9.  top_key_phrases and top_keywords are used to extract the top_10 key_phrases and keywords from given document

and the results should be provide in the form of data frame.

print(nlp_exp)

Results = {'Document':['Hello my name is Sathish kumar. I'm working in XYZ company as Senior software Engineer. I live 
                  Bangalore City. I'm having issue in kit12sd server. please have a look and fix it soon. it's downing my work'],
                 'Custom_Entities': ['server':'kit12sd'],
                 'Lang_detection': ['English'],
                 'Lang_transilation': [' '],
                 'NER':['Persons':['Sathish'], 'Locations':['Bangalore','Chittoor','Andhrapradesh'], 'Organizations': ['Abc']],
                 'Text_topic_classification': ['Issue'],
                 'Sentiment_Analysis': ['Negative'],
                 'URL':[''],
                 'Email':[''],
                 'Top_key_phrase':[''],
                 'Top_keywords':['']
              }

### Describe your proposed solution

Hello Pycaret Team....
I have worked on a project purely on NLP. we have many use cases. and we have successfully built Rest API's for all of them with different python libraries. but In my experience Pycaret Library is great which will train all the models at a time. but we were able to use pycaret only for classification problem. we can't able to use it for remaining all the use cases. so I wanted to bring up to you all those use cases to keep in pycaret. so in future we don't need to use multiple libraries. one library for all the usecase.
the library should be like this

text = ["Hello my name is Sathish kumar. I'm working in XYZ company as Senior software Engineer. I live bangalore City. My native is chittoor, Andhrapradesh. I'm having issue in kit12sd server. please have a look and fix it soon. it's downing my work"]

import pandas as pd
nlp_data = pd.DataFrame(text, columns = ['document'])

from pycaret.nlp import *
nlp_exp = setup(data = nlp_data, custom_entities = [{'servers' :['kit12sd ', 'dgh245'],'apps':['cbds','2424cv'], lang_detection=True, lang_transilation= ['en','Spanish',etc], NER = ['per','org','loc',etc], text_topic_classification = True, sentiment_analysis = True, extract_urls = True, extract_emails = true, top_keyphrase = True, top_keywords = True)

here 1.nlp_data is the document in data frame.
2.custom_entities is optional here. if customer wants to identify his own entities in the document he can pass the entity name and entities in data frame format. here i passed servers and apps to identify them in our document. this parameter should be optional.
3. lang_detection is to detect the language of the given document. by default it's true.
4. lang_transilaion is to transilate the language of the given document. by default it should be English and it can be changed to different languages as optional.
5. NER is used to detect named entities from data. it can be optional as well. and if customer wants to extract specific NER's he can mention whether he wants to extract persons or Organization or Locations .etc from given document.
6. text_topic_classication. this is also optional. if it's true, it should tell the topic of the document. whether it's politics or healthcare or sports. etc
7. sentiment_analysis is to classify whether the document is positive, negative or neutral sentiment. it should be True by default
8.  extract_url's  and emails is to detect and extract the email's from the given document
9.  top_key_phrases and top_keywords are used to extract the top_10 key_phrases and keywords from given document

and the results should be provide in the form of data frame.

print(nlp_exp)

Results = {'Document':['Hello my name is Sathish kumar. I'm working in XYZ company as Senior software Engineer. I live 
                  Bangalore City. I'm having issue in kit12sd server. please have a look and fix it soon. it's downing my work'],
                 'Custom_Entities': ['server':'kit12sd'],
                 'Lang_detection': ['English'],
                 'Lang_transilation': [' '],
                 'NER':['Persons':['Sathish'], 'Locations':['Bangalore','Chittoor','Andhrapradesh'], 'Organizations': ['Abc']],
                 'Text_topic_classification': ['Issue'],
                 'Sentiment_Analysis': ['Negative'],
                 'URL':[''],
                 'Email':[''],
                 'top_key_phrase':[''],
                 'top_keywords':['']
}

### Describe alternatives you've considered, if relevant

for custom_entities you can use simple membership operator. if those entity words exists in our document. we can extract and save them in a list and will tag the entity where the user has provided name for those entities initially in dictionary format.
for example: "I'm having issue in abc1245"

nlp_exp = setup(data = nlp_data, custom_entities = {'servers':['abc1245', 'bcde245']})
 if ['abc1245','bcde245'] in document. save them in a list. here 'abc1245' exist in our document. and we have to check the 'abc1245' entity key. here the key for 'abc1245' is the  servers. so we have to save the results as 'custom_entities' : ['servers':['abc1245']]. so like that if the cutomer pass any entities it has scan, identify and tag them in a list.

for language_detection you can use lang id and different lang detection python libraries.

for sentimet analysis you can use state of the art nlp libraries like flair, hugging face, transformers.etc.

for NER you can use you can use state of the art nlp libraries like flair, hugging face, transformers.etc. don't use spacy, nltk. because these models don't understand the context of text.

for language transilation you can use google python library. but it limits number of characters for transilation. and if we pass more than 100k records at a time. it will pass memory error. it would be good if it uses any chunk_size iteration. which means instead of using all the data at a time. it takes 1000 records first and do the analysis and saves the results in df1. and again it does the analysis from 1001 to 2000 and saves the results in df2. finally concatenate all dataframes into one. so it avoids memory error. 

for text_topic_classification you can use zero shot text classification where it can understand the topic of the given document.

for url and email extraction you can use regular expressions.

for top keypharse and keywords extraction you can use multi rake and any other python library.

### Additional context
Request for tutorial documentation if it's completed in the jupyter notebook and also Rest API using flask or fast api
_No response_

**Comment by ngupta23** [comment]
NLP & ARules modules is going to be deprecated shortly. Hence, no additional development is planned for this.
