### ISSUE TITLE
Request for recommendation system tutorial

### ISSUE THREAD

**Issue by sathishkumar999** [pycaret/pycaret#3164]
### Describe the feature you want to add to this project

Hi pycaret team,
Please make a tutorial on pycaret recommendations system with Netflix movie recommendation system. And Flipkart shopping website item recommendations to user.
It should have 2 types.
Collaborative recommendation and content based recommendation.
In collaborative recommendation we recommend based on other users interest.
For example. There are 3 users.
First user watched Spiderman and hulk.
Second user watched Spiderman and Jurassic park.
If third user tries to watch Spiderman. We recommend him to watch Jurassic park and hulk. Because the people who watched Spiderman they also watched Jurassic park and hulk

In content based recommendation system it will recommend based on matched properties.
For example, if the user like to watch Ice age, which is an animation movie. So here we recommend him to watch animation movies such as kumba, Lion King, how to train your dragon.

And it will be same for online shopping websites as well. Recommending products based on others users purchase and recommend products based on similar products

### Describe your proposed solution

You can use cosine similarity and other recommendation techniques.
And also parameter to how many elements that we can recommend.

**Comment by ngupta23** [comment]
NLP & ARules modules is going to be deprecated shortly. Hence, no additional development is planned for this.
