### ISSUE TITLE
[BUG]: Explainer Dashboard Classification Stats page is blanked out

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#3188]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

```
from pycaret.datasets import get_data
data = get_data('juice')

from pycaret.classification import *
s = setup(data, target = 'Purchase', session_id = 123)

lr = create_model('lr')

dashboard(lr)
```

![image](https://user-images.githubusercontent.com/54699234/208332810-c0e2416f-98a5-4a25-b2ad-71b6db63faf1.png)

### Reproducible Example

```python
.
```

### Expected Behavior

The second page of Model Explainer should display normally. 

### Actual Results

```python-traceback
..
```

### Installed Versions

rc5

**Comment by tvdboom** [comment]
I can't reproduce the error. Looks fine when I ran the same code
