### ISSUE TITLE
plot_model, evaluate_model and mlflow not producing any output in jupyter lab

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#319]
When I run the `plot_model`, `evaluate_model` and `mlflow` code cells in the NLP example notebok, they do not produce any output for me (just a blank space). I am using `jupyter lab`.

## Empty plot cells 

![image](https://user-images.githubusercontent.com/33585645/89122130-8a5ac000-d48a-11ea-8fd2-eaaab7b93398.png)

## MLFlow
**The mlflow cell has been running for a long time without any output (I did not see a separate browser window open up either for the experiments).**

![image](https://user-images.githubusercontent.com/33585645/89122139-9b0b3600-d48a-11ea-897c-79db505de285.png)

**Comment by ngupta23** [comment]
# Update

`plot_model` and `evalaute_model` seems to work ok in `jupyter notebook` but not in `jupyter lab`. This seems to a `jupyter lab` specific problem.

I am still having issues running the following cell in `jupyter notebook`. It does not launch anything or produce an output.

```python
!mlflow ui
```

**Comment by pycaret** [comment]
@ngupta23 **plot_model** and **evaluate_model** is a known issue for Jupyter Lab. Would you like to have a look at code and try to troubleshoot?

For the second issue, can you please open localhost:5000 on your browser, it should open up MLFlow server. You can stop/interupt the last cell of your notebook and continue working. The server should stay up. Please let me know if that helps.

Even that doesn't work you can just write "mlflow ui" in the same folder as of your notebook and it should still start up a local server on https://localhost:5000

Hope it helps.

**Comment by ngupta23** [comment]
I don't have any luck running mlflow from the command line either.  I get this (below), but nothing happens even when I paste that localhost link in the browser

```
(pycaret) C:\Users\Nikhil\pycaret>mlflow ui
c:\users\nikhil\.conda\envs\pycaret\lib\site-packages\waitress\adjustments.py:445: DeprecationWarning: In future versions of Waitress clear_untrusted_proxy_headers will be set to True by default. You may opt-out by setting this value to False, or opt-in explicitly by setting this to True.
  DeprecationWarning,
Serving on http://Nikhil:5000
```

**Comment by pycaret** [comment]
@ngupta23 Were you able to resolve this?

**Comment by bolfaine** [comment]
I still have issue with model_plot in Jupyterlab, but works in jubyter notebook. Maybe some with ipy
widgets?

**Comment by ngupta23** [comment]
> 
> 
> @ngupta23 Were you able to resolve this?

Yes, I am still having issues with this.

**Comment by pycaret** [comment]
@ngupta23 Thanks. I have received much feedback wrt jupyter hub. Seems like visuals are not rendering in Jupyter Hub. Not sure who can help, please let's keep this open.

**Comment by ngupta23** [comment]
Its been a while now so we can close this. If needed, we will reopen it.

**Comment by nishuvr** [comment]
I am getting the, nothing gets plotted after running plot_model on colab. Can anyone please help

**Comment by edydev85** [comment]
Hi, 

Both evaluate_model() and interpret_model() start to work after using:

%matplotlib inline
%config InlineBackend.figure_format = 'svg' #or 'retina'. Makes the images more clear

Hope that helps

**Comment by jfewz** [comment]
> 

My word, you sir are a legend

**Comment by Prashavu** [comment]
@edydev85 could you explain howtomake it work. only facing issues plotting `pycaret` models.
`fig = plt.figure(figsize=(18,6))
ax = fig.add_subplot(5,2,1)
plot_model(blender, plot='cooks', save=True, verbose=False, scale=1.1)
ax = fig.add_subplot(5,2,2)
plot_model(blender, plot='manifold', save=True, verbose=False, scale=1.1)`
#plt.savefig('plots_cooks_and_manifold.png', dpi=300, pad_inches=0.25)
plt.show()
This produces no image

**Comment by kinoto86** [comment]
I am getting the same thing, nothing gets plotted after running plot_model, evaluate_model() in jupyterlab. Is there anything we can try for this? Thanks!

**Comment by kinoto86** [comment]
> Hi,
> 
> Both evaluate_model() and interpret_model() start to work after using:
> 
> %matplotlib inline %config InlineBackend.figure_format = 'svg' #or 'retina'. Makes the images more clear
> 
> Hope that helps

how? where??

**Comment by binaryyskull** [comment]
Still, any kind of visualization does not appear on Jupyter Lab using pycaret. Does someone have updates?

**Comment by edygianez** [comment]
Hi! Sorry for such a late reply.

Follows the link to a colab notebook so you guys can check where the %matplotlib inline is set

https://colab.research.google.com/drive/1ZqxMUQeeGTuKEDPP_vrph_nnglPFubaH?usp=sharing

Hope that helps

**Comment by feferna** [comment]
I am facing this same problem. Adding the '%matplotlib inline' does not solve my problem. 

I am trying to plot_model in the JupyterLab 3.4.4 with PyCaret 3.0.0rc4. Is there any way to see the plots?

**Comment by user1683** [comment]
> 

I am having the same issue as well

**Comment by moezali1** [comment]
This issue has been fixed. I am not able to reproduce using pycaret==rc8 and jupyterlab==3.5.2
