### ISSUE TITLE
[BUG]: drift_kwargs argument is missing in rc5 from predict_model function

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#3190]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

drift_kwargs argument is missing in rc5 from predict_model function.

It is available in 2.3.10

### Reproducible Example

```python
..
```

### Expected Behavior

drift_kwargs argument should be available in predict_model function.

### Actual Results

```python-traceback
drift_kwargs not available.
```

### Installed Versions

rc5

**Comment by Yard1** [comment]
It looks like this wasn't used in 2.3.10 anyway, so I think we can remove this. What is the usecase for keeping this argument?

**Comment by moezali1** [comment]
@Yard1 `drift_kwargs` is used to when detecting drift on new dataset. Without the ability to pass `drift_kwargs` the functionality is not complete / broken. Can we add it please?

**Comment by Yard1** [comment]
Is it intended only for passing the second dataset? In that case we can make just than an argument.
