### ISSUE TITLE
[BUG]: shape displayed in setup grid not correct

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#3194]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

We have to recheck how shape is calculated for 4,5,6,7 in image below.

In the current construct original dataset has 18 columns (excluding y) and if I ignore one column the transformed dataset has 17 columns but pycaret is somehow also updating original data shape which is wrong.

![image](https://user-images.githubusercontent.com/54699234/209211181-9c98c698-ffd8-4d9c-9d0c-3276d939523b.png)

### Reproducible Example

```python
from pycaret.datasets import get_data
data = get_data('juice')
s = setup(data, target = "Purchase", session_id = 123, index = 'Id', ignore_features = ['StoreID'])
```

### Expected Behavior

read above.

### Actual Results

```python-traceback
..
```

### Installed Versions

rc5

**Comment by moezali1** [comment]
In other instances the shape is also wrong. For example if you pass your own `test_data` the calculation of shape is totally wrong.

**Comment by tvdboom** [comment]
I changed the original data to show the proper shape in #3189 

> In other instances the shape is also wrong. For example if you pass your own test_data the calculation of shape is totally wrong.

Can you share an example? It works fine with

```
from pycaret.datasets import get_data
data = get_data('juice')
from sklearn.model_selection import train_test_split

train, test = train_test_split(data)

s = setup(train, test_data=test, target = "Purchase", session_id = 123, index = 'Id', ignore_features = ['StoreID'])
```

**Comment by moezali1** [comment]
@tvdboom 

![image](https://user-images.githubusercontent.com/54699234/209817792-6ca6b9b1-9532-4f2e-ab20-45858a9e48b3.png)

This one now gives me an error:

```
from pycaret.datasets import get_data
data = get_data('juice')
data2 = data.copy()
from pycaret.classification import *
s = setup(data, test_data=data2, target = "Purchase", session_id = 123, index = 'Id', ignore_features = ['StoreID'])
```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-10-c462fb437a7e>](https://localhost:8080/#) in <module>
      1 from pycaret.classification import *
----> 2 s = setup(data, test_data=data2, target = "Purchase", session_id = 123, index = 'Id', ignore_features = ['StoreID'])

22 frames
[/usr/local/lib/python3.8/dist-packages/pandas/core/internals/base.py](https://localhost:8080/#) in _validate_set_axis(self, axis, new_labels)
     55 
     56         elif new_len != old_len:
---> 57             raise ValueError(
     58                 f"Length mismatch: Expected axis has {old_len} elements, new "
     59                 f"values have {new_len} elements"

ValueError: Length mismatch: Expected axis has 2140 elements, new values have 4280 elements

**Comment by tvdboom** [comment]
That's because when copying the df you have the same indices. you can't have repeated indices in the train and test set. Use index=False to reset indices in setup
