### ISSUE TITLE
xgboost not working

### ISSUE THREAD

**Issue by wsn4iv** [pycaret/pycaret#32]
First of all, I love this package. It is great and makes training, testing, and tuning so much simpler. 

I am unable to compare or create an xgboost classification or an xgboost regression model. With the same dataset, all of the other models work except xgboost. For the classification, i get the error:
"attempt to get argmax of an empty sequence"

For the regression, i get the error:
"Found array with 0 feature(s) (shape=(4035, 0)) while a minimum of 1 is required."

Please advise.

**Comment by pycaret** [comment]
Hi,

Can you please share your specs, os, environment. 

Can you also please share the dataset so I can try to reproduce an error. 

Thanks.

**Comment by wsn4iv** [comment]
I am using Windows 10
Python 3.7.1
pycaret 1.0.0
xgboost .90
Jupyter Notebook

Thank you for your help.

[PyCaret Test.ipynb.zip](https://github.com/pycaret/pycaret/files/4522534/PyCaret.Test.ipynb.zip)

[Social_Network_Ads.xlsx](https://github.com/pycaret/pycaret/files/4522500/Social_Network_Ads.xlsx)

**Comment by pycaret** [comment]
@wsn4iv 

Sorry I cannot reproduce the issue. It works fine on my computer. I will leave this issue open and see if someone else can help.

Thanks.

**Comment by wsn4iv** [comment]
I figured it out. I had multiple versions of xgboost installed on my computer and pycaret was referencing the wrong one. 

Thank you for looking into this. You may close the ticket.
