### ISSUE TITLE
Example Notebook Contributions Needed

### ISSUE THREAD

**Issue by pycaret** [pycaret/pycaret#320]
Do you have a Notebook you created using PyCaret you want to showcase? 

Then, we need you.

Submit a pull request under examples on master branch. Address: https://github.com/pycaret/pycaret/tree/master/examples

A good notebook must include:

👉 Version used to develop (1.0 or 2.0) and last date updated
👉 Problem Statement: 4 - 5 lines about the use-case  
👉 Data Description / EDA (highly recommended)
👉 Comments and explanation (where needed)
👉 Conclusion / impact 

Submitting a notebook for gallery will be acknowledged as a contributor and will also be distributed using our social media handle.

Do you think you have a big project you have recently done using PyCaret? please reach out moez.ali@queensu.ca

Thanks.

**Comment by ojaashampiholi** [comment]
Are you guys still accepting the PR's?

**Comment by pycaret** [comment]
## Thanks everyone for submissions. It will not be an ongoing activity. I am closing this issue now.
