### ISSUE TITLE
time series numeric_imputation_target="ffill" is not working. and plot_model is not showing any visualization even after training

### ISSUE THREAD

**Issue by sathishkumar999** [pycaret/pycaret#3208]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Hi Pycaret Team @moezali1 , @ngupta23  and @Yard1 
I'm trying to forecasting number of incidents using pycaret time series module. I followed the below youtube video.
but in setup it's showing error. i tried to debug it, but i can't.
moez ali's youtube video on time series: https://www.youtube.com/watch?v=V7K-pFxHop4
the date set is here:
[Incident_data.csv](https://github.com/pycaret/pycaret/files/10313222/Incident_data.csv)

here index is "date" and target is "count_incidents"

### Reproducible Example

```python
import pandas as pd
data = pd.read_csv('Incident_data.csv')
data.head()
data.shape
data.dtypes
data['date'] = pd.to_datetime(data['date'])
data.set_index('date', drop = True,inplace = True)
data.plot()
##Importing and Initializing time series module
from pycaret.time_series import *
forecast_tickets = setup(data, fold = 5, fh = 15)
```

### Expected Behavior

.....

### Actual Results

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [331], line 1
----> 1 forecast_tickets = setup(data, fold = 5, fh = 10)

File ~\anaconda3\envs\pycaret_full\lib\site-packages\pycaret\time_series\forecasting\functional.py:389, in setup(data, data_func, target, index, ignore_features, numeric_imputation_target, numeric_imputation_exogenous, transform_target, transform_exogenous, scale_target, scale_exogenous, fold_strategy, fold, fh, seasonal_period, point_alpha, coverage, enforce_exogenous, n_jobs, use_gpu, custom_pipeline, html, session_id, system_log, log_experiment, experiment_name, log_plots, log_profile, log_data, verbose, profile, profile_kwargs, fig_kwargs)
    387 exp = _EXPERIMENT_CLASS()
    388 set_current_experiment(exp)
--> 389 return exp.setup(
    390     data=data,
    391     data_func=data_func,
    392     target=target,
    393     index=index,
    394     ignore_features=ignore_features,
    395     numeric_imputation_target=numeric_imputation_target,
    396     numeric_imputation_exogenous=numeric_imputation_exogenous,
    397     transform_target=transform_target,
    398     transform_exogenous=transform_exogenous,
    399     scale_target=scale_target,
    400     scale_exogenous=scale_exogenous,
    401     fold_strategy=fold_strategy,
    402     fold=fold,
    403     fh=fh,
    404     seasonal_period=seasonal_period,
    405     point_alpha=point_alpha,
    406     coverage=coverage,
    407     enforce_exogenous=enforce_exogenous,
    408     n_jobs=n_jobs,
    409     use_gpu=use_gpu,
    410     custom_pipeline=custom_pipeline,
    411     html=html,
    412     session_id=session_id,
    413     system_log=system_log,
    414     log_experiment=log_experiment,
    415     experiment_name=experiment_name,
    416     log_plots=log_plots,
    417     log_profile=log_profile,
    418     log_data=log_data,
    419     verbose=verbose,
    420     profile=profile,
    421     profile_kwargs=profile_kwargs,
    422     fig_kwargs=fig_kwargs,
    423 )

File ~\anaconda3\envs\pycaret_full\lib\site-packages\pycaret\time_series\forecasting\oop.py:1626, in TSForecastingExperiment.setup(self, data, data_func, target, index, ignore_features, numeric_imputation_target, numeric_imputation_exogenous, transform_target, transform_exogenous, scale_target, scale_exogenous, fold_strategy, fold, fh, seasonal_period, point_alpha, coverage, enforce_exogenous, n_jobs, use_gpu, custom_pipeline, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, engine, verbose, profile, profile_kwargs, fig_kwargs)
   1622 # Features to be ignored (are not read by self.dataset, self.X, etc...)
   1623 self._fxs = {"Ignore": ignore_features or []}
   1625 (
-> 1626     self._initialize_setup(
   1627         n_jobs=n_jobs,
   1628         use_gpu=use_gpu,
   1629         html=html,
   1630         session_id=session_id,
   1631         system_log=system_log,
   1632         log_experiment=log_experiment,
   1633         experiment_name=experiment_name,
   1634         memory=True,
   1635         verbose=verbose,
   1636     )
   1637     ._check_clean_and_set_data(data)
   1638     ._check_and_clean_index(index=index, seasonal_period=seasonal_period)
   1639     ._check_and_set_targets(target=target)
   1640     ._set_exogenous_names()
   1641     ._check_and_set_forecsting_types()
   1642     ._check_and_set_fh(fh=fh)
   1643     ._set_point_alpha_intervals_enforce_pi(
   1644         point_alpha=point_alpha, coverage=coverage
   1645     )
   1646     ._setup_train_test_split()
   1647     ._set_fold_generator()
   1648     ._set_should_preprocess_data()
   1649     ._set_missingness()
   1650     ._initialize_pipeline()
   1651     ##################################################################
   1652     # Do these after the preprocessing pipeline has been setup.
   1653     # Since the model will see transformed data, these parameters
   1654     # should also be derived from the transformed data.
   1655     ##################################################################
   1656     ._check_and_set_seasonal_period(seasonal_period=seasonal_period)
   1657     ._set_multiplicative_components()
   1658     ._perform_setup_eda()
   1659     ._setup_display_container()
   1660     ._profile(profile, profile_kwargs)
   1661     ._set_exp_model_engines(
   1662         container_default_engines=get_container_default_engines(),
   1663         engine=engine,
   1664     )
   1665     ._set_all_models()
   1666     ._set_all_metrics()
   1667 )
   1669 runtime = np.array(time.time() - runtime_start).round(2)
   1671 self._set_up_logging(
   1672     runtime,
   1673     log_data,
   1674     log_profile,
   1675     experiment_custom_tags=experiment_custom_tags,
   1676 )

File ~\anaconda3\envs\pycaret_full\lib\site-packages\pycaret\time_series\forecasting\oop.py:520, in TSForecastingExperiment._check_and_clean_index(self, index, seasonal_period)
    516 # Convert DateTimeIndex index to PeriodIndex ----
    517 # We use PeriodIndex in PyCaret since it seems to be more robust per `sktime``
    518 # Ref: https://github.com/alan-turing-institute/sktime/blob/v0.10.0/sktime/forecasting/base/_fh.py#L524
    519 if isinstance(self.data.index, pd.DatetimeIndex):
--> 520     self.data.index = self.data.index.to_period()
    522 # Data must not have missing indices ----
    523 if isinstance(self.data.index, pd.PeriodIndex):

File ~\anaconda3\envs\pycaret_full\lib\site-packages\pandas\core\indexes\extension.py:95, in _inherit_from_data.<locals>.method(self, *args, **kwargs)
     93 if "inplace" in kwargs:
     94     raise ValueError(f"cannot use inplace with {type(self).__name__}")
---> 95 result = attr(self._data, *args, **kwargs)
     96 if wrap:
     97     if isinstance(result, type(self._data)):

File ~\anaconda3\envs\pycaret_full\lib\site-packages\pandas\core\arrays\_mixins.py:84, in ravel_compat.<locals>.method(self, *args, **kwargs)
     81 @wraps(meth)
     82 def method(self, *args, **kwargs):
     83     if self.ndim == 1:
---> 84         return meth(self, *args, **kwargs)
     86     flags = self._ndarray.flags
     87     flat = self.ravel("K")

File ~\anaconda3\envs\pycaret_full\lib\site-packages\pandas\core\arrays\datetimes.py:1172, in DatetimeArray.to_period(self, freq)
   1169 freq = self.freqstr or self.inferred_freq
   1171 if freq is None:
-> 1172     raise ValueError(
   1173         "You must pass a freq argument as current index has none."
   1174     )
   1176 res = get_period_alias(freq)
   1178 #  https://github.com/pandas-dev/pandas/issues/33358

ValueError: You must pass a freq argument as current index has none.
```

### Installed Versions

<details>
'3.0.0.rc4'
</details>

**Comment by ngupta23** [comment]
This is not really a bug. Your data has a lot of missing periods in it because of which internal functions can not operate.

![image](https://user-images.githubusercontent.com/33585645/209965761-966326c9-c15f-41a3-b6e8-ecf232152f9c.png)

To fix this, you need to do 2 things 

1. Set the frequency manually outside to let pycaret know what kind of data you are providing. This step will add the missing periods to the data but with the "incident" values missing.
2. After completing step 1, you need to provide an appropriate method to impute (refer to docstring)

```python
import pandas as pd

data = pd.read_csv("Incident_data.csv")
data["date"] = pd.to_datetime(data["date"])
data.set_index("date", drop=True, inplace=True)

# Step 1: Set the frequency of the data manually. 
data = data.asfreq("d")

##Importing and Initializing time series module
from pycaret.time_series import *

# Step 2: Provide the imputation method
forecast_tickets = setup(data, fold=5, fh=15, numeric_imputation_target="ffill")
```

**Comment by sathishkumar999** [comment]
##Importing and Initializing time series module
from pycaret.time_series import *

# Step 2: Provide the imputation method
forecast_tickets = setup(data, fold=5, fh=15, numeric_imputation_target="ffill")

getting error for the above code, even the numeric imputation is passed as ffill
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [37], line 5
      2 from pycaret.time_series import *
      4 # Step 2: Provide the imputation method
----> 5 forecast_tickets = setup(data, fold=5, fh=15, numeric_imputation_target="ffill")

File ~\anaconda3\envs\pycaret_full\lib\site-packages\pycaret\time_series\forecasting\functional.py:389, in setup(data, data_func, target, index, ignore_features, numeric_imputation_target, numeric_imputation_exogenous, transform_target, transform_exogenous, scale_target, scale_exogenous, fold_strategy, fold, fh, seasonal_period, point_alpha, coverage, enforce_exogenous, n_jobs, use_gpu, custom_pipeline, html, session_id, system_log, log_experiment, experiment_name, log_plots, log_profile, log_data, verbose, profile, profile_kwargs, fig_kwargs)
    387 exp = _EXPERIMENT_CLASS()
    388 set_current_experiment(exp)
--> 389 return exp.setup(
    390     data=data,
    391     data_func=data_func,
    392     target=target,
    393     index=index,
    394     ignore_features=ignore_features,
    395     numeric_imputation_target=numeric_imputation_target,
    396     numeric_imputation_exogenous=numeric_imputation_exogenous,
    397     transform_target=transform_target,
    398     transform_exogenous=transform_exogenous,
    399     scale_target=scale_target,
    400     scale_exogenous=scale_exogenous,
    401     fold_strategy=fold_strategy,
    402     fold=fold,
    403     fh=fh,
    404     seasonal_period=seasonal_period,
    405     point_alpha=point_alpha,
    406     coverage=coverage,
    407     enforce_exogenous=enforce_exogenous,
    408     n_jobs=n_jobs,
    409     use_gpu=use_gpu,
    410     custom_pipeline=custom_pipeline,
    411     html=html,
    412     session_id=session_id,
    413     system_log=system_log,
    414     log_experiment=log_experiment,
    415     experiment_name=experiment_name,
    416     log_plots=log_plots,
    417     log_profile=log_profile,
    418     log_data=log_data,
    419     verbose=verbose,
    420     profile=profile,
    421     profile_kwargs=profile_kwargs,
    422     fig_kwargs=fig_kwargs,
    423 )

File ~\anaconda3\envs\pycaret_full\lib\site-packages\pycaret\time_series\forecasting\oop.py:1626, in TSForecastingExperiment.setup(self, data, data_func, target, index, ignore_features, numeric_imputation_target, numeric_imputation_exogenous, transform_target, transform_exogenous, scale_target, scale_exogenous, fold_strategy, fold, fh, seasonal_period, point_alpha, coverage, enforce_exogenous, n_jobs, use_gpu, custom_pipeline, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, engine, verbose, profile, profile_kwargs, fig_kwargs)
   1622 # Features to be ignored (are not read by self.dataset, self.X, etc...)
   1623 self._fxs = {"Ignore": ignore_features or []}
   1625 (
-> 1626     self._initialize_setup(
   1627         n_jobs=n_jobs,
   1628         use_gpu=use_gpu,
   1629         html=html,
   1630         session_id=session_id,
   1631         system_log=system_log,
   1632         log_experiment=log_experiment,
   1633         experiment_name=experiment_name,
   1634         memory=True,
   1635         verbose=verbose,
   1636     )
   1637     ._check_clean_and_set_data(data)
   1638     ._check_and_clean_index(index=index, seasonal_period=seasonal_period)
   1639     ._check_and_set_targets(target=target)
   1640     ._set_exogenous_names()
   1641     ._check_and_set_forecsting_types()
   1642     ._check_and_set_fh(fh=fh)
   1643     ._set_point_alpha_intervals_enforce_pi(
   1644         point_alpha=point_alpha, coverage=coverage
   1645     )
   1646     ._setup_train_test_split()
   1647     ._set_fold_generator()
   1648     ._set_should_preprocess_data()
   1649     ._set_missingness()
   1650     ._initialize_pipeline()
   1651     ##################################################################
   1652     # Do these after the preprocessing pipeline has been setup.
   1653     # Since the model will see transformed data, these parameters
   1654     # should also be derived from the transformed data.
   1655     ##################################################################
   1656     ._check_and_set_seasonal_period(seasonal_period=seasonal_period)
   1657     ._set_multiplicative_components()
   1658     ._perform_setup_eda()
   1659     ._setup_display_container()
   1660     ._profile(profile, profile_kwargs)
   1661     ._set_exp_model_engines(
   1662         container_default_engines=get_container_default_engines(),
   1663         engine=engine,
   1664     )
   1665     ._set_all_models()
   1666     ._set_all_metrics()
   1667 )
   1669 runtime = np.array(time.time() - runtime_start).round(2)
   1671 self._set_up_logging(
   1672     runtime,
   1673     log_data,
   1674     log_profile,
   1675     experiment_custom_tags=experiment_custom_tags,
   1676 )

File ~\anaconda3\envs\pycaret_full\lib\site-packages\pycaret\time_series\forecasting\oop.py:1044, in TSForecastingExperiment._initialize_pipeline(self)
   1041 self.pipeline_fully_trained = deepcopy(self.pipeline)
   1043 # Fit pipelines
-> 1044 self.pipeline.fit(y=self.y_train, X=self.X_train, fh=self.fh)
   1045 self.pipeline_fully_trained.fit(y=self.y, X=self.X, fh=self.fh)
   1047 self._check_transformations()

File ~\anaconda3\envs\pycaret_full\lib\site-packages\sktime\forecasting\base\_base.py:288, in BaseForecaster.fit(self, y, X, fh)
    285 self.reset()
    287 # check and convert X/y
--> 288 X_inner, y_inner = self._check_X_y(X=X, y=y)
    290 # set internal X/y to the new X/y
    291 # this also updates cutoff from y
    292 self._update_y_X(y_inner, X_inner)

File ~\anaconda3\envs\pycaret_full\lib\site-packages\sktime\forecasting\base\_base.py:1300, in BaseForecaster._check_X_y(self, X, y)
   1292     if (
   1293         self.get_tag("scitype:y") == "multivariate"
   1294         and y_metadata["is_univariate"]
   1295     ):
   1296         raise ValueError(
   1297             "y must have two or more variables, but found only one"
   1298         )
-> 1300     _check_missing(y_metadata, "y")
   1302 else:
   1303     # y_scitype is used below - set to None if y is None
   1304     y_scitype = None

File ~\anaconda3\envs\pycaret_full\lib\site-packages\sktime\forecasting\base\_base.py:1246, in BaseForecaster._check_X_y.<locals>._check_missing(metadata, obj_name)
   1240     msg = msg + (
   1241         f" Whether instances of {type(self).__name__} can handle "
   1242         "missing data depends on parameters of the instance, "
   1243         "e.g., estimator components."
   1244     )
   1245 if metadata["has_nans"]:
-> 1246     raise ValueError(msg)

ValueError: ForecastingPipeline cannot handle missing data (nans), but y passed contained missing data.

**Comment by sathishkumar999** [comment]
@ngupta23
here the problem is numeric_imputational_method = 'ffill'  is not working. i fixed this issue by using fillna to fill the missing values. I think the issue in the setup. imputational method is not working and another issue i have encounted plot_model() is showing nothing to me. please have a look into screenshot or code

![screenshot_1](https://user-images.githubusercontent.com/40235632/210040528-932d352e-321c-40f0-8336-a20b56d15159.png)



import pandas as pd
data = pd.read_csv("Incident_data.csv")
data["date"] = pd.to_datetime(data["date"])
data.set_index("date", drop=True, inplace=True)

# Step 1: Set the frequency of the data manually. 
data = data.asfreq("d")
data.fillna(method = 'ffill',inplace=True)
##checking null count
data.isnull().sum()
## Visualizing data
import plotly.express as px
fig = px.line(data)
fig.show() 
##checking null count after preprocessing
data.isnull().sum()
##Importing and Initializing time series module
from pycaret.time_series import *
# Step 2: Provide the imputation method
forecast_tickets = setup(data, fold=5, fh=15, numeric_imputation_target="ffill")
best = compare_models()
##ploting train_test_split
plot_model(best, plot = 'train_test_split')

plot_model is showing nothing

**Comment by ngupta23** [comment]
I am not seeing any issues. It is working fine for me.

## Imputation in Setup

![image](https://user-images.githubusercontent.com/33585645/210118349-b3362ab1-795e-497a-849f-5f02b022954c.png)

## Plotting

![image](https://user-images.githubusercontent.com/33585645/210118362-586fa6b0-a00f-424a-99f7-82afbf70bbb9.png)

Please provide a reproducible example (preferably in the form of a self-contained notebook that I can run) so that I can debug your issue.

**Comment by ngupta23** [comment]
You should not be filling up NA values outside pycaret since the imputation should be fold specific. By filling it outside pycaret, there is scope for data leakage and hence getting optimistic metrics during cross validation and in the test set. Please elaborate on the exact issue with ffill that you are facing and provide a self contained (minimal) reproducible example so that I can help further.

**Comment by sathishkumar999** [comment]
![screenshot_1](https://user-images.githubusercontent.com/40235632/210125693-3f54b5e1-0829-4766-8dff-c7784cca0454.png)
![screenshot_2](https://user-images.githubusercontent.com/40235632/210125696-3a3a7bb1-cb9d-4161-a2a8-f3a869be0421.png)
Hi @ngupta23 , thanks for you're replay.
It's strange for me, I used the same code. but got the error. please check in the screenshots. since i can't upload jupyter file here. i'm pasting the code with error.

import pandas as pd
data = pd.read_csv("Downloads/Incident_data.csv")
data["date"] = pd.to_datetime(data["date"])
data.set_index("date", drop=True, inplace=True)
# Step 1: Set the frequency of the data manually. 
data = data.asfreq("d")
##Importing and Initializing time series module
from pycaret.time_series import *
# Step 2: Provide the imputation method
forecast_tickets = setup(data, fold=5, fh=15, numeric_imputation_target="ffill")

##Error is below.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [3], line 6
      4 from pycaret.time_series import *
      5 # Step 2: Provide the imputation method
----> 6 forecast_tickets = setup(data, fold=5, fh=15, numeric_imputation_target="ffill")

File ~\anaconda3\envs\pycaret_full\lib\site-packages\pycaret\time_series\forecasting\functional.py:389, in setup(data, data_func, target, index, ignore_features, numeric_imputation_target, numeric_imputation_exogenous, transform_target, transform_exogenous, scale_target, scale_exogenous, fold_strategy, fold, fh, seasonal_period, point_alpha, coverage, enforce_exogenous, n_jobs, use_gpu, custom_pipeline, html, session_id, system_log, log_experiment, experiment_name, log_plots, log_profile, log_data, verbose, profile, profile_kwargs, fig_kwargs)
    387 exp = _EXPERIMENT_CLASS()
    388 set_current_experiment(exp)
--> 389 return exp.setup(
    390     data=data,
    391     data_func=data_func,
    392     target=target,
    393     index=index,
    394     ignore_features=ignore_features,
    395     numeric_imputation_target=numeric_imputation_target,
    396     numeric_imputation_exogenous=numeric_imputation_exogenous,
    397     transform_target=transform_target,
    398     transform_exogenous=transform_exogenous,
    399     scale_target=scale_target,
    400     scale_exogenous=scale_exogenous,
    401     fold_strategy=fold_strategy,
    402     fold=fold,
    403     fh=fh,
    404     seasonal_period=seasonal_period,
    405     point_alpha=point_alpha,
    406     coverage=coverage,
    407     enforce_exogenous=enforce_exogenous,
    408     n_jobs=n_jobs,
    409     use_gpu=use_gpu,
    410     custom_pipeline=custom_pipeline,
    411     html=html,
    412     session_id=session_id,
    413     system_log=system_log,
    414     log_experiment=log_experiment,
    415     experiment_name=experiment_name,
    416     log_plots=log_plots,
    417     log_profile=log_profile,
    418     log_data=log_data,
    419     verbose=verbose,
    420     profile=profile,
    421     profile_kwargs=profile_kwargs,
    422     fig_kwargs=fig_kwargs,
    423 )

File ~\anaconda3\envs\pycaret_full\lib\site-packages\pycaret\time_series\forecasting\oop.py:1626, in TSForecastingExperiment.setup(self, data, data_func, target, index, ignore_features, numeric_imputation_target, numeric_imputation_exogenous, transform_target, transform_exogenous, scale_target, scale_exogenous, fold_strategy, fold, fh, seasonal_period, point_alpha, coverage, enforce_exogenous, n_jobs, use_gpu, custom_pipeline, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, engine, verbose, profile, profile_kwargs, fig_kwargs)
   1622 # Features to be ignored (are not read by self.dataset, self.X, etc...)
   1623 self._fxs = {"Ignore": ignore_features or []}
   1625 (
-> 1626     self._initialize_setup(
   1627         n_jobs=n_jobs,
   1628         use_gpu=use_gpu,
   1629         html=html,
   1630         session_id=session_id,
   1631         system_log=system_log,
   1632         log_experiment=log_experiment,
   1633         experiment_name=experiment_name,
   1634         memory=True,
   1635         verbose=verbose,
   1636     )
   1637     ._check_clean_and_set_data(data)
   1638     ._check_and_clean_index(index=index, seasonal_period=seasonal_period)
   1639     ._check_and_set_targets(target=target)
   1640     ._set_exogenous_names()
   1641     ._check_and_set_forecsting_types()
   1642     ._check_and_set_fh(fh=fh)
   1643     ._set_point_alpha_intervals_enforce_pi(
   1644         point_alpha=point_alpha, coverage=coverage
   1645     )
   1646     ._setup_train_test_split()
   1647     ._set_fold_generator()
   1648     ._set_should_preprocess_data()
   1649     ._set_missingness()
   1650     ._initialize_pipeline()
   1651     ##################################################################
   1652     # Do these after the preprocessing pipeline has been setup.
   1653     # Since the model will see transformed data, these parameters
   1654     # should also be derived from the transformed data.
   1655     ##################################################################
   1656     ._check_and_set_seasonal_period(seasonal_period=seasonal_period)
   1657     ._set_multiplicative_components()
   1658     ._perform_setup_eda()
   1659     ._setup_display_container()
   1660     ._profile(profile, profile_kwargs)
   1661     ._set_exp_model_engines(
   1662         container_default_engines=get_container_default_engines(),
   1663         engine=engine,
   1664     )
   1665     ._set_all_models()
   1666     ._set_all_metrics()
   1667 )
   1669 runtime = np.array(time.time() - runtime_start).round(2)
   1671 self._set_up_logging(
   1672     runtime,
   1673     log_data,
   1674     log_profile,
   1675     experiment_custom_tags=experiment_custom_tags,
   1676 )

File ~\anaconda3\envs\pycaret_full\lib\site-packages\pycaret\time_series\forecasting\oop.py:1044, in TSForecastingExperiment._initialize_pipeline(self)
   1041 self.pipeline_fully_trained = deepcopy(self.pipeline)
   1043 # Fit pipelines
-> 1044 self.pipeline.fit(y=self.y_train, X=self.X_train, fh=self.fh)
   1045 self.pipeline_fully_trained.fit(y=self.y, X=self.X, fh=self.fh)
   1047 self._check_transformations()

File ~\anaconda3\envs\pycaret_full\lib\site-packages\sktime\forecasting\base\_base.py:288, in BaseForecaster.fit(self, y, X, fh)
    285 self.reset()
    287 # check and convert X/y
--> 288 X_inner, y_inner = self._check_X_y(X=X, y=y)
    290 # set internal X/y to the new X/y
    291 # this also updates cutoff from y
    292 self._update_y_X(y_inner, X_inner)

File ~\anaconda3\envs\pycaret_full\lib\site-packages\sktime\forecasting\base\_base.py:1300, in BaseForecaster._check_X_y(self, X, y)
   1292     if (
   1293         self.get_tag("scitype:y") == "multivariate"
   1294         and y_metadata["is_univariate"]
   1295     ):
   1296         raise ValueError(
   1297             "y must have two or more variables, but found only one"
   1298         )
-> 1300     _check_missing(y_metadata, "y")
   1302 else:
   1303     # y_scitype is used below - set to None if y is None
   1304     y_scitype = None

File ~\anaconda3\envs\pycaret_full\lib\site-packages\sktime\forecasting\base\_base.py:1246, in BaseForecaster._check_X_y.<locals>._check_missing(metadata, obj_name)
   1240     msg = msg + (
   1241         f" Whether instances of {type(self).__name__} can handle "
   1242         "missing data depends on parameters of the instance, "
   1243         "e.g., estimator components."
   1244     )
   1245 if metadata["has_nans"]:
-> 1246     raise ValueError(msg)

ValueError: ForecastingPipeline cannot handle missing data (nans), but y passed contained missing data.

##I'm using the pycaret version: '3.0.0.rc4'

**Comment by ngupta23** [comment]
Can you install the latest version of the library?

```
pip install -U --pre pycaret
```

**Comment by sathishkumar999** [comment]
hi @ngupta23 .
thanks it's worked. i'm closing the ticket
