### ISSUE TITLE
[BUG]: Pycaret does not handle nested runs properly with MLflow

### ISSUE THREAD

**Issue by ibiscp** [pycaret/pycaret#3209]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).
- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.
- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I opened this issue first in MLflow, but it seems to be a problem with Pycaret, as commented here:
https://github.com/mlflow/mlflow/issues/7612#issuecomment-1366301088

I discovered an issue while testing Pycaret with MLflow. I noticed a significant difference in the way experiments are logged between version 1.27.0 and version 1.28.0 or newer. In version 1.27.0, the results seem to be correct and how I would expect them to be displayed. However, when I update to version 1.28.0 or newer, all of the models are displayed in a cascaded format.

It happens because in version 1.28.0 nested runs were implemented.

<img width="1673" alt="Screenshot 2022-12-27 at 15 57 17" src="https://user-images.githubusercontent.com/19699606/209813143-d4349c3e-3239-4fe0-9ac2-7641104a5b5a.png">

<img width="1673" alt="Screenshot 2022-12-27 at 15 55 38" src="https://user-images.githubusercontent.com/19699606/209813117-2ab8a6c9-549d-425a-862f-924edde7e00e.png">

### Reproducible Example

```python
from pycaret.datasets import get_data
from pycaret.regression import *

data = get_data('diamond')

# initialize setup
s = setup(data, target = 'Price', transform_target = True, log_experiment = True, experiment_name = 'diamond', silent=True)

best = compare_models()
```

### Installed Versions

<details>
2.3.10
</details>

**Comment by ngupta23** [comment]
This is fixed in the latest RC release. Please create a new environment using this rc version and let us know if the issue exists

```
pip install --pre pycaret
```

**Comment by ibiscp** [comment]
Yes, this is fixed in the latest RC release, great!

Closing this issue.
