### ISSUE TITLE
[DOC]: Quickstart is 404 Not Found

### ISSUE THREAD

**Issue by jameshfisher** [pycaret/pycaret#3221]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

I just found PyCaret. I visited https://pycaret.gitbook.io/docs/ and clicked on the link in "If you would like to give it a try, check out our official [quick start](https://nbviewer.org/github/pycaret/pycaret/blob/time_series_beta/time_series_101.ipynb) notebook."

### Documentation problem

That link to https://nbviewer.org/github/pycaret/pycaret/blob/time_series_beta/time_series_101.ipynb yields "404 : Not Found". Not a good look.

### Suggested fix for documentation

I don't know - is there a newer working link?

**Comment by moezali1** [comment]
@jameshfisher Thanks for reporting. Where exactly is this? Can you share with me the complete link to the page where this hyperlink is. I can't seem to find it.

**Comment by jameshfisher** [comment]
Sure:

https://github.com/pycaret/pycaret-docs/blob/ce36438a2c40d03f0ddcbdd6fc2205d7b7641510/README.md?plain=1#L77

**Comment by moezali1** [comment]
@jameshfisher Thanks a lot. Fixed now.

**Comment by moezali1** [comment]
Directed to this url: https://nbviewer.org/github/pycaret/pycaret/blob/master/examples/time_series/forecasting/time_series_101.ipynb
