### ISSUE TITLE
[INSTALL]: Error messages when installing Pycaret in VSCode

### ISSUE THREAD

**Issue by PhilippLa22** [pycaret/pycaret#3224]
(data_mining_env) PS C:\Users\lagra\OneDrive - Universität Bayreuth\5. Codes\1. Projekte\Data Mining> pip install --pre pycaret
Collecting pycaret
  Using cached pycaret-3.0.0rc6-py3-none-any.whl (501 kB)
Collecting ipython>=5.5.0
  Using cached ipython-8.8.0-py3-none-any.whl (775 kB)
Collecting ipywidgets>=7.6.5
  Using cached ipywidgets-8.0.4-py3-none-any.whl (137 kB)
Collecting tqdm>=4.62.0
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting numpy<1.23,>=1.21
  Using cached numpy-1.22.4.zip (11.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pandas<1.6.0,>=1.3.0 in c:\users\lagra\onedrive - universität bayreuth\5. codes\1. projekte\data mining\data_mining_env\lib\site-packages (from pycaret) (1.5.2)
Collecting jinja2>=1.2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting scipy<2.0.0
  Using cached scipy-1.10.0rc2-cp311-cp311-win_amd64.whl (42.2 MB)
Collecting joblib>=1.2.0
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Collecting scikit-learn>=1.0
  Using cached scikit_learn-1.2.0-cp311-cp311-win_amd64.whl (8.2 MB)
Collecting pyod>=0.9.8
  Using cached pyod-1.0.7.tar.gz (147 kB)
  Preparing metadata (setup.py) ... done
Collecting imbalanced-learn>=0.8.1
  Using cached imbalanced_learn-0.10.1-py3-none-any.whl (226 kB)
Collecting category-encoders>=2.4.0
  Using cached category_encoders-2.5.1.post0-py2.py3-none-any.whl (72 kB)
Collecting lightgbm>=3.0.0
  Using cached lightgbm-3.3.3-py3-none-win_amd64.whl (1.0 MB)
Collecting numba>=0.55.0
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\lagra\AppData\Local\Temp\pip-install-ssz0_g19\numba_fe3585ec8f414e5d8b154a8f188680a3\setup.py", line 51, in <module>
          _guard_py_ver()
        File "C:\Users\lagra\AppData\Local\Temp\pip-install-ssz0_g19\numba_fe3585ec8f414e5d8b154a8f188680a3\setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.1; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(data_mining_env) PS C:\Users\lagra\OneDrive - Universität Bayreuth\5. Codes\1. Projekte\Data Mining> pip install pygame --pre
Collecting pygame
  Using cached pygame-2.1.3.dev8-cp311-cp311-win_amd64.whl (10.6 MB)
Installing collected packages: pygame
Successfully installed pygame-2.1.3.dev8
(data_mining_env) PS C:\Users\lagra\OneDrive - Universität Bayreuth\5. Codes\1. Projekte\Data Mining> pip install --pre pycaret
Collecting pycaret
  Using cached pycaret-3.0.0rc6-py3-none-any.whl (501 kB)
Collecting ipython>=5.5.0
  Using cached ipython-8.8.0-py3-none-any.whl (775 kB)
Collecting ipywidgets>=7.6.5
  Using cached ipywidgets-8.0.4-py3-none-any.whl (137 kB)
Collecting tqdm>=4.62.0
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting numpy<1.23,>=1.21
  Using cached numpy-1.22.4.zip (11.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pandas<1.6.0,>=1.3.0 in c:\users\lagra\onedrive - universität bayreuth\5. codes\1. projekte\data mining\data_mining_env\lib\site-packages (from pycaret) (1.5.2)
Collecting jinja2>=1.2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting scipy<2.0.0
  Using cached scipy-1.10.0rc2-cp311-cp311-win_amd64.whl (42.2 MB)
Collecting joblib>=1.2.0
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Collecting scikit-learn>=1.0
  Using cached scikit_learn-1.2.0-cp311-cp311-win_amd64.whl (8.2 MB)
Collecting pyod>=0.9.8
  Using cached pyod-1.0.7.tar.gz (147 kB)
  Preparing metadata (setup.py) ... done
Collecting imbalanced-learn>=0.8.1
  Using cached imbalanced_learn-0.10.1-py3-none-any.whl (226 kB)
Collecting category-encoders>=2.4.0
  Using cached category_encoders-2.5.1.post0-py2.py3-none-any.whl (72 kB)
Collecting lightgbm>=3.0.0
  Using cached lightgbm-3.3.3-py3-none-win_amd64.whl (1.0 MB)
Collecting numba>=0.55.0
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\lagra\AppData\Local\Temp\pip-install-dxfbr7og\numba_de747eefa9004b15b70147ce1d33ad8a\setup.py", line 51, in <module>
          _guard_py_ver()
        File "C:\Users\lagra\AppData\Local\Temp\pip-install-dxfbr7og\numba_de747eefa9004b15b70147ce1d33ad8a\setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.1; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by turkalpmd** [comment]
Firstly you must create conda enviroment with python 3.8

Follow the installing instruction from [here](https://pycaret.readthedocs.io/en/latest/installation.html)

**Comment by ngupta23** [comment]
@turkalpmd is correct. If you are installing pycaret 2.3.10, it only supports up to python 3.8
If you install the pre-release version, it supports up to python 3.10

```
pip install --pre -U pycaret
```

**Comment by Rhuam774** [comment]
Quando tento instalar numba aparece isso:

Collecting numba>=0.55.0
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\RP\AppData\Local\Temp\pip-install-pylirhxm\numba_92f051aa94744752846e71689b90161a\setup.py", line 51, in <module>
          _guard_py_ver()
        File "C:\Users\RP\AppData\Local\Temp\pip-install-pylirhxm\numba_92f051aa94744752846e71689b90161a\setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.1; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by turkalpmd** [comment]
Here is the you error;

RuntimeError: Cannot install on Python version 3.11.1; only versions >=3.7,<3.11 are supported.


Anaconda installing for Windows 11 is [here](https://youtu.be/-sNX_ZMVpQM)
# This is the best way for running pycaret (In my opinion)

```
# create a conda environment 
# ps. : you environment name must be different than pycaret example : datascience_pycaret
conda create --name yourenvname python=3.8  

# activate conda environment
conda activate yourenvname

# install pycaret (stable verison) you can also choose version and [full] of package pycaret[full]==version
# versions; [...,2.3.9, 2.3.10, 3.0.0rc1, 3.0.0rc2, 3.0.0rc3, 3.0.0rc4, 3.0.0rc5, 3.0.0rc6]
pip install pycaret 

# create notebook kernel connected with the conda environment

python -m ipykernel install --user --name yourenvname --display-name "display-name"

```
