### ISSUE TITLE
[DOC]: What does imputation_type="simple" do?

### ISSUE THREAD

**Issue by jameshfisher** [pycaret/pycaret#3226]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

[I'm reading the regression API docs here](https://pycaret.readthedocs.io/en/latest/api/regression.html), which say

> imputation_type: str or None, default = ‘simple’
>
> The type of imputation to use. Can be either ‘simple’ or ‘iterative’. If None, no imputation of missing values is performed.

### Documentation problem

What does `imputation_type="simple"`, the default, actually do?

I found a good description of `imputation_type="iterative"` [in this unofficial article](https://www.linkedin.com/pulse/iterative-imputation-pycaret-22-antoni-baum/). I can also see that you can set the iterative imputer, which defaults to `lightgbm`.

But there is no description of what `simple` means or does.

### Suggested fix for documentation

Describe this in the API docs somewhere, or link to something that describes it.

**Comment by jameshfisher** [comment]
I'm looking at https://github.com/pycaret/pycaret/blob/ff1a8c905ad722d9de4fd8edfe793794a25775c1/pycaret/internal/preprocess/preprocessor.py#L414-L466

Which suggests `imputation_type="iterative"` means:

* For numeric features, impute with the mean. (More precisely: impute with a constant value chosen by the method given in the `numeric_imputation` param.)
* For categorical features, impute with the mode. (More precisely: impute with a constant value chosen by the method given in the `categorical_imputation` param.)

Do I have this right?

**Comment by Yard1** [comment]
Not exactly. Simple imputation consists of filling the values with mean/median for numeric features and most frequent value/constant for categorical values. See https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html

Iterative imputation starts with simple imputation and then fits ML models on each column with missing values, using the values of other columns to predict what should be imputed. This is done several times, thus iterative imputation. Hope that helps - please close the issue if you do not have any more questions.

**Comment by jameshfisher** [comment]
That's helpful, thank you!
