### ISSUE TITLE
[BUG]: plot_model in time series forecasting not shown 

### ISSUE THREAD

**Issue by arekso** [pycaret/pycaret#3230]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

![image](https://user-images.githubusercontent.com/93749238/210912057-e203f8fe-78cf-45ba-b392-835c81ea5691.png)
![image](https://user-images.githubusercontent.com/93749238/210912115-a54e86e0-ba60-48f4-b76c-9f277e051608.png)
![image](https://user-images.githubusercontent.com/93749238/210912202-73d4f8d7-2575-4eb8-b92e-6bb692a20d2a.png)

### Reproducible Example

```python
same as issue description
```

### Expected Behavior

![image](https://user-images.githubusercontent.com/93749238/210912409-9e084c2f-c816-45f1-ab81-fec22acb23dd.png)

### Actual Results

```python-traceback
<function pycaret.time_series.forecasting.functional.plot_model(estimator: Optional[Any] = None, plot: Optional[str] = None, return_fig: bool = False, return_data: bool = False, verbose: bool = False, display_format: Optional[str] = None, data_kwargs: Optional[Dict] = None, fig_kwargs: Optional[Dict] = None, save: Union[str, bool] = False) -> Optional[Tuple[str, list]]>
```

### Installed Versions

System:
    python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
executable: D:\Anaconda\python.exe
   machine: Windows-10-10.0.19042-SP0

PyCaret required dependencies:
                 pip: 21.2.4
          setuptools: 61.2.0
             pycaret: 3.0.0rc4
             IPython: 8.2.0
          ipywidgets: 7.6.5
                tqdm: 4.64.0
               numpy: 1.21.5
              pandas: 1.4.2
              jinja2: 2.11.3
               scipy: 1.7.3
              joblib: 1.1.0
             sklearn: 1.1.3
                pyod: 1.0.6
            imblearn: 0.9.1
   category_encoders: 2.5.1.post0
            lightgbm: 3.3.3
               numba: 0.55.1
            requests: 2.27.1
          matplotlib: 3.5.1
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.6.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.13.4
               tbats: 1.1.1
            pmdarima: 1.8.5
              psutil: 5.9.4

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: 0.3.0
                umap: 0.5.3
    pandas_profiling: 3.4.0
  explainerdashboard: 0.4.0
             autoviz: 0.1.58
           fairlearn: 0.8.0
             xgboost: 1.7.1
            catboost: 1.1.1
              kmodes: 0.12.2
             mlxtend: 0.21.0
       statsforecast: 1.3.1
        tune_sklearn: 0.4.5
                 ray: 2.1.0
            hyperopt: 0.2.7
              optuna: 3.0.3
               skopt: 0.9.0
              mlflow: 2.0.1
              gradio: 3.10.1
             fastapi: 0.87.0
             uvicorn: 0.20.0
              m2cgen: 0.10.0
           evidently: 0.1.59.dev3
                nltk: 3.7
            pyLDAvis: Not installed
              gensim: 4.1.2
               spacy: Not installed
           wordcloud: 1.8.2.2
            textblob: 0.17.1
               fugue: 0.6.6
           streamlit: 1.10.0
             prophet: Not installed

**Comment by ngupta23** [comment]
I don't think this is a bug. You have overwritten your plot by typing `plot_model` after the actual plot_model call. Please remove plot_model at the end and retry. If it fixes your problem, please close the issue.
