### ISSUE TITLE
[BUG]: plot model in pycarret not shown

### ISSUE THREAD

**Issue by arekso** [pycaret/pycaret#3241]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

plot model in pycarret not shown, only display finish not the plot

![image](https://user-images.githubusercontent.com/93749238/211437833-ca3fbaf2-c6ba-4cb4-951e-addc124892a4.png)

![image](https://user-images.githubusercontent.com/93749238/211437866-f799a4f9-12d7-479f-b143-744b58e587e9.png)

![image](https://user-images.githubusercontent.com/93749238/211437926-c31bd31a-79f6-4273-8612-5f1c55079644.png)

### Reproducible Example

```python
df_all_kurs = df_all[['Year Month Number','Kurs']]

df_all_kurs['Year Month Number'] = pd.to_datetime(df_all_kurs['Year Month Number']).dt.strftime('%Y-%m')
df_all_kurs['Year Month Number'] = pd.to_datetime(df_all_kurs['Year Month Number'], errors='coerce').dt.to_period('m')
df_all_kurs = df_all_kurs.set_index('Year Month Number', drop=True, append=False, inplace=False, verify_integrity=False)
df_all_kurs = df_all_kurs.head(84)
#df_all_kurs.set_index("Year Month Number", inplace = True)


fh = 12 # or alternately fh = np.arange(1,13)
fold = 10

fig_kwargs={'renderer': 'notebook'}

df_all_kurs

from pycaret.time_series import *

s = setup(df_all_kurs, fh = 12, fold = 5, session_id = 123)
best = compare_models()

plot_model(best, plot = 'forecast', data_kwargs = {'fh' : 12})
```

### Expected Behavior

![image](https://user-images.githubusercontent.com/93749238/211438122-34b9592e-d05f-4bf4-9fb7-a0651b395f62.png)

### Actual Results

```python-traceback
it prints nothing
```

### Installed Versions

System:
    python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
executable: D:\Anaconda\python.exe
   machine: Windows-10-10.0.19042-SP0

PyCaret required dependencies:
                 pip: 21.2.4
          setuptools: 61.2.0
             pycaret: 3.0.0rc4
             IPython: 8.2.0
          ipywidgets: 7.6.5
                tqdm: 4.64.0
               numpy: 1.21.5
              pandas: 1.4.2
              jinja2: 2.11.3
               scipy: 1.7.3
              joblib: 1.1.0
             sklearn: 1.1.3
                pyod: 1.0.6
            imblearn: 0.9.1
   category_encoders: 2.5.1.post0
            lightgbm: 3.3.3
               numba: 0.55.1
            requests: 2.27.1
          matplotlib: 3.5.1
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.6.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.13.4
               tbats: 1.1.1
            pmdarima: 1.8.5
              psutil: 5.9.4

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: 0.3.0
                umap: 0.5.3
    pandas_profiling: 3.4.0
  explainerdashboard: 0.4.0
             autoviz: 0.1.58
           fairlearn: 0.8.0
             xgboost: 1.7.1
            catboost: 1.1.1
              kmodes: 0.12.2
             mlxtend: 0.21.0
       statsforecast: 1.3.1
        tune_sklearn: 0.4.5
                 ray: 2.1.0
            hyperopt: 0.2.7
              optuna: 3.0.3
               skopt: 0.9.0
              mlflow: 2.0.1
              gradio: 3.10.1
             fastapi: 0.87.0
             uvicorn: 0.20.0
              m2cgen: 0.10.0
           evidently: 0.1.59.dev3
                nltk: 3.7
            pyLDAvis: Not installed
              gensim: 4.1.2
               spacy: Not installed
           wordcloud: 1.8.2.2
            textblob: 0.17.1
               fugue: 0.6.6
           streamlit: 1.10.0
             prophet: Not installed

**Comment by ngupta23** [comment]
You have not passed fig_kwargs to the setup function.

**Comment by arekso** [comment]
> You have not passed fig_kwargs to the setup function.

hi @ngupta23 tq for your response, im totally newbie, can you help me fix the code?

**Comment by ngupta23** [comment]
Please refer to the 101 notebook. It shows how to do it.
