### ISSUE TITLE
PicklingError: Can't pickle <class 'pyod.models.pca.PCA'>: it's not found as pyod.models.pca.PCA

### ISSUE THREAD

**Issue by Piyushlamsoge** [pycaret/pycaret#3259]
I try to build classification model in google colab, But when i going to save the model its shows the same error everytime 

HERE IS MY CODE :
`!pip install pycaret` 

`import pandas as pd
df = pd.read_csv('/content/Iris.csv')
df`

`from pycaret.classification import *
s = setup(data = df , target = 'Species' , preprocess = True , numeric_features = ['SepalLengthCm' , 'SepalWidthCm' , 'PetalLengthCm' , 'PetalWidthCm'] , transformation = True , remove_outliers = True  )`

`ada = create_model('ada')`

`plot_model(ada , plot = 'feature')`

`model = finalize_model(ada)`

`new_data = df.copy()
new_data.drop('Species' , axis = 1 , inplace = True)
new_data`

`predictions = predict_model(model , data = new_data)
predictions`

`save_model(model , 'my_model')`

AND THE ERROR I'M TALKING ABOUT IS HERE:
![pycaret_issue](https://user-images.githubusercontent.com/88150820/212045593-821d9d89-2e35-4cec-9b6a-7d51b8806df5.png)

_Originally posted by @Piyushlamsoge in https://github.com/pycaret/pycaret/discussions/3246_

**Comment by tvdboom** [comment]
Which version of pycaret is this? Could you try with pip install --pre pycaret?

**Comment by moezali1** [comment]
@Piyushlamsoge I am unable to reproduce this issue using the latest rc8 version.

Google Colab: https://colab.research.google.com/drive/13xEoqyL5dKQbB4HYawl2w1uODRDWSfeJ?usp=sharing

**Comment by Piyushlamsoge** [comment]
@tvdboom i'm using  latest version of pycaret on google and also used several previous version of it as well.

**Comment by Piyushlamsoge** [comment]
@moezali1  I rewrite the whole bunch of  code and now it is work perfectly fine for me. Thank you for designing such amazing tool!!!!!!!

**Comment by bhudge** [comment]
I'm having the same issue. How did you resolve this? @Piyushlamsoge

**Comment by bhudge** [comment]
Nevermind I got it!

**Comment by Piyushlamsoge** [comment]
@bhudge how do you solve this can you please share with me just for reference
