### ISSUE TITLE
ConnectionRefusedError

### ISSUE THREAD

**Issue by morestart** [pycaret/pycaret#327]
```Python
from pycaret.datasets import get_data
data = get_data('juice')
```

this is full link `https://raw.githubusercontent.com/pycaret/pycaret/master/datasets/juice.csv`

i see the source code use pd.read_csv to get the csv data, but it will get urlopen error

i change the get data part to this:
```python
import requests
from io import StringIO
r = requests.get(complete_address)
data = pd.read_csv(StringIO(r.text))
```

it work

**Comment by pycaret** [comment]
@morestart Whats the version of your pandas library?

**Comment by morestart** [comment]
> @morestart Whats the version of your pandas library?

my pandas version is 1.1.0

**Comment by pycaret** [comment]
@morestart Can you please install `pycaret-nightly` in a separate environment and try to reproduce the error?

**Comment by morestart** [comment]
if i use this code, i got ssl error:
`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1056)>
`
```python
from pycaret.datasets import get_data
data = get_data('juice')
```

so i remove ssl verfiy
```python
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

i got this error:
`urllib.error.HTTPError: HTTP Error 404: Not Found`

**Comment by pycaret** [comment]
@morestart I have never seen this before. I will keep the issue open and see if anybody else can help you with this issue. Whatever it is, it has to do something with your computer/internet settings.

**Comment by Yard1** [comment]
It's possible your virtual enviroment (eg. conda)/base Python installation is incorrectly set up.

**Comment by morestart** [comment]
> It's possible your virtual enviroment (eg. conda)/base Python installation is incorrectly set up.

my enviroment  is Virtualenv , but this code is work for me
```python
import requests
from io import StringIO
r = requests.get(complete_address)
data = pd.read_csv(StringIO(r.text))
```

**Comment by rajpratyush** [comment]
I used the same process in the conda environment in windows 10. My Anaconda navigator version is 1.9.7 and I am also having Nvidia GeForce GTX 1050.and it worked in one go. so I guess @Yard1 is right maybe your virtual environment is incorrectly set up. 
![Screenshot (651)](https://user-images.githubusercontent.com/53184883/105570768-4a0d3800-5d71-11eb-84ff-ddb68e2b3e81.png)
