### ISSUE TITLE
[BUG]: Wrong tune_grid["split_criterion"] parameter for RandomForestRegressor when using GPU

### ISSUE THREAD

**Issue by Ali-Flt** [pycaret/pycaret#3277]
### pycaret version checks

- [ ] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Here the tune_grid["split_criterion"]  parameter for `RandomForestRegressor` has a value of `[2, 3]` whereas as stated in [cuML's doc](https://docs.rapids.ai/api/cuml/stable/api.html#cuml.ensemble.RandomForestRegressor) this parameter doesn't accept value of '3'. This leads to `tune_model` function in regression module to fail. 3 should be removed from the tune_grid. 
https://github.com/pycaret/pycaret/blob/cb6f7ea7a1743bc5b3f6087d5208ef914aa200c8/pycaret/containers/models/regression.py#L1249-L1250

If I'm right it's really surprising for this issue to be missed because it would be noticed if anyone tries to tune a RandomForestRegressor. Am I the only person using `use_gpu=True` out there?

### Reproducible Example

```python
setup(...,
use_gpu=True)
model = ... #RandomForestRegressor
tune_model(model, search_library='optuna')
```

### Expected Behavior

correct parameters are used to tune RandomForestRegressor using cuML

### Actual Results

```python-traceback
wrong parameters used resulting in "MAE is not supported" error message by cuML
```

### Installed Versions

<details>

</details>

**Comment by Yard1** [comment]
@Ali-Flt unfortunately we are unable to test with GPUs in CI due to their cost. Thank you for making the issue, I'll take a look.
