### ISSUE TITLE
[BUG]: AttributeError: dtype while using use_gpu=True in regression

### ISSUE THREAD

**Issue by Ali-Flt** [pycaret/pycaret#3278]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

error when using `predict_model`

### Reproducible Example

```python
setup(...,
      use_gpu=True)
compare_models()
...
tune_model()
...
predict_model(model)
```

### Expected Behavior

No errors occur

### Actual Results

```python-traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
.....
    912 leader_board = get_leaderboard(verbose=False)
    913 for i, model in leader_board.iterrows():
--> 914     predict_result = predict_model(model['Model'], verbose=False)
    915     mae = mean_absolute_error(
    916         y_true=predict_result['label'], y_pred=predict_result['prediction_label'])
    917     leader_board.loc[i, 'test_MAE'] = mae

File ~/mambaforge/envs/pycaret_gitmain_python3.9/lib/python3.9/site-packages/pycaret/regression/functional.py:1927, in predict_model(estimator, data, drift_report, round, verbose)
   1924 if experiment is None:
   1925     experiment = _EXPERIMENT_CLASS()
-> 1927 return experiment.predict_model(
   1928     estimator=estimator,
   1929     data=data,
   1930     drift_report=drift_report,
   1931     round=round,
   1932     verbose=verbose,
   1933 )

File ~/mambaforge/envs/pycaret_gitmain_python3.9/lib/python3.9/site-packages/pycaret/regression/oop.py:2220, in RegressionExperiment.predict_model(self, estimator, data, drift_report, round, verbose)
   2159 def predict_model(
   2160     self,
   2161     estimator,
   (...)
   2165     verbose: bool = True,
   2166 ) -> pd.DataFrame:
   2168     """
   2169     This function predicts ``Label`` using a trained model. When ``data`` is
   2170     None, it predicts label on the holdout set.
   (...)
   2217 
   2218     """
-> 2220     return super().predict_model(
   2221         estimator=estimator,
   2222         data=data,
   2223         probability_threshold=None,
   2224         encoded_labels=False,
   2225         drift_report=drift_report,
   2226         round=round,
   2227         verbose=verbose,
   2228     )

File ~/mambaforge/envs/pycaret_gitmain_python3.9/lib/python3.9/site-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py:4983, in _SupervisedExperiment.predict_model(self, estimator, data, probability_threshold, encoded_labels, raw_score, drift_report, round, verbose, ml_usecase, preprocess)
   4980         probability_threshold = estimator.probability_threshold
   4981     estimator = get_estimator_from_meta_estimator(estimator)
-> 4983 pred = np.nan_to_num(estimator.predict(X_test_))
   4985 try:
   4986     score = estimator.predict_proba(X_test_)

File ~/mambaforge/envs/pycaret_gitmain_python3.9/lib/python3.9/site-packages/cuml/internals/api_decorators.py:595, in BaseReturnArrayDecorator.__call__.<locals>.inner(*args, **kwargs)
    590 @wraps(func)
    591 def inner(*args, **kwargs):
    592     with self._recreate_cm(func, args) as cm:
    593 
    594         # Call the function
--> 595         ret_val = func(*args, **kwargs)
    597     return cm.process_return(ret_val)

File base.pyx:70, in cuml.linear_model.base.LinearPredictMixin.predict()

File base.pyx:269, in cuml.common.base.Base.__getattr__()

AttributeError: dtype
```

### Installed Versions

<details>
System:
    python: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29)  [GCC 10.4.0]
executable: /home/ali/mambaforge/envs/pycaret_gitmain_python3.9/bin/python
   machine: Linux-6.1.6-arch1-1-x86_64-with-glibc2.36

PyCaret required dependencies:
                 pip: 22.3.1
          setuptools: 60.10.0
             pycaret: 3.0.0rc8
             IPython: 8.8.0
          ipywidgets: 8.0.4
                tqdm: 4.64.1
               numpy: 1.23.5
              pandas: 1.5.3
              jinja2: 3.1.2
               scipy: 1.10.0
              joblib: 1.2.0
             sklearn: 1.1.3
                pyod: 1.0.7
            imblearn: 0.10.1
   category_encoders: 2.6.0
            lightgbm: 3.3.5.99
               numba: 0.56.4
            requests: 2.28.2
          matplotlib: 3.6.3
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.13.0
             kaleido: 0.2.1
         statsmodels: 0.13.5
              sktime: 0.15.1
               tbats: 1.1.2
            pmdarima: 2.0.2
              psutil: 5.9.4

PyCaret optional dependencies:
                shap: Not installed
           interpret: Not installed
                umap: Not installed
    pandas_profiling: Not installed
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
             xgboost: 1.6.2
            catboost: Not installed
              kmodes: Not installed
             mlxtend: Not installed
       statsforecast: Not installed
        tune_sklearn: 0.4.5
                 ray: 2.2.0
            hyperopt: 0.2.7
              optuna: 3.1.0
               skopt: 0.9.0
              mlflow: Not installed
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: Not installed
           evidently: Not installed
                nltk: Not installed
            pyLDAvis: Not installed
              gensim: Not installed
               spacy: Not installed
           wordcloud: Not installed
            textblob: Not installed
               fugue: Not installed
           streamlit: Not installed
             prophet: Not installed

</details>

**Comment by Yard1** [comment]
Hi, I couldn't reproduce this. Can you post a reproductible end to end example and let us know your cuML version and where you are running it?

**Comment by Yard1** [comment]
I cannot reproduce this. Can you post a full end to end reproductible example? What is your cuML version?
