### ISSUE TITLE
[BUG]: Streamlit app not detecting `pycaret` library

### ISSUE THREAD

**Issue by fitnesswanderer** [pycaret/pycaret#3296]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I am trying to deploy this model on Streamlit and run locally.While running locally, I am getting this error.
![errorpycaret](https://user-images.githubusercontent.com/12171326/216820521-da6049f7-7298-495a-b7e7-d34c815621f4.JPG)

I created new environment on conda . My requirments.txt contains pycaret version 2.3.5 and Python 3.8

This is the link for [my git hub repo](https://github.com/fitnesswanderer/Deployment-using-Streamlit)

### Reproducible Example

```python
from pycaret.regression import*
import streamlit as st
import pandas as pd
import numpy as np

model = load_model('deployment_28042020')

def predict(model, input_df):
    predictions_df = predict_model(estimator=model, data=input_df)
    predictions = predictions_df['Label'][0]
    return predictions

def run():

    from PIL import Image
    image = Image.open('logo.png')
    image_hospital = Image.open('hospital.jpg')

    st.image(image,use_column_width=False)

    add_selectbox = st.sidebar.selectbox(
    "How would you like to predict?",
    ("Online", "Batch"))

    st.sidebar.info('This app is created to predict patient hospital charges')
    st.sidebar.success('https://www.pycaret.org')
    
    st.sidebar.image(image_hospital)

    st.title("Insurance Charges Prediction App")

    if add_selectbox == 'Online':

        age = st.number_input('Age', min_value=1, max_value=100, value=25)
        sex = st.selectbox('Sex', ['male', 'female'])
        bmi = st.number_input('BMI', min_value=10, max_value=50, value=10)
        children = st.selectbox('Children', [0,1,2,3,4,5,6,7,8,9,10])
        if st.checkbox('Smoker'):
            smoker = 'yes'
        else:
            smoker = 'no'
        region = st.selectbox('Region', ['southwest', 'northwest', 'northeast', 'southeast'])

        output=""

        input_dict = {'age' : age, 'sex' : sex, 'bmi' : bmi, 'children' : children, 'smoker' : smoker, 'region' : region}
        input_df = pd.DataFrame([input_dict])

        if st.button("Predict"):
            output = predict(model=model, input_df=input_df)
            output = '$' + str(output)

        st.success('The output is {}'.format(output))

    if add_selectbox == 'Batch':

        file_upload = st.file_uploader("Upload csv file for predictions", type=["csv"])

        if file_upload is not None:
            data = pd.read_csv(file_upload)
            predictions = predict_model(estimator=model,data=data)
            st.write(predictions)

if __name__ == '__main__':
    run()
```

### Expected Behavior

It should run and show the required output
![outputstreamli](https://user-images.githubusercontent.com/12171326/216820707-0812f8b0-9f2c-4073-97a5-17810cc5006c.JPG)

### Actual Results

```python-traceback
You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.1.100:8501

2023-02-05 18:07:07.744 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\username\anaconda3\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\username\Documents\testappdeploy\Deployment-using-Streamlit-main\app.py", line 1, in <module>
    import pycaret
ModuleNotFoundError: No module named 'pycaret'
```

### Installed Versions

<details>

![pycaretinstall](https://user-images.githubusercontent.com/12171326/216821267-477f2264-c2a8-4846-8974-4fb7e854dde1.JPG)

</details>

**Comment by ngupta23** [comment]
When running your streamlit app, have you made sure that the right conda environment is activated (i.e. the one that has pycaret installed)?

**Comment by fitnesswanderer** [comment]
When I am trying to install pycaret on conda I am getting this error.
![error32](https://user-images.githubusercontent.com/12171326/216961558-4a4ee50a-8d68-4737-b314-935772f79777.JPG)

How to resolve it?

**Comment by tvdboom** [comment]
restart your process (terminal or even pc to be sure) and try it again

**Comment by fitnesswanderer** [comment]
After restarting PC and terminal I ma getting this error.
![errorpre](https://user-images.githubusercontent.com/12171326/217173764-818d12fd-654a-4074-9025-77d6fef2066c.JPG)

**Comment by tvdboom** [comment]
it looks like you are loading a model trained on a different version of pycaret than you have currently installed. Make sure the two versions are the same (the one on which you saved the model)

**Comment by ngupta23** [comment]
When did you create this model and what version of pycaret did you use to create it?
It looks like the model was created using a different version of pycaret than the one that is used in the streamlit app. Please make sure you are using a consistent conda env between the model creation and the streamlit app (with respect to the pycaret version).

**Comment by fitnesswanderer** [comment]
Hey,
I ran this model on latest version of Pycaret. 
![pycaret1](https://user-images.githubusercontent.com/12171326/217730963-9c6cf062-483f-43ac-81db-b42e5f0a956a.JPG)
![pycaret2](https://user-images.githubusercontent.com/12171326/217730982-3a09616b-2de3-49d1-8290-de71a4817a5c.JPG)

I am really at the cross roads as what is the issue?

**Comment by tvdboom** [comment]
> I ran this model on latest version of Pycaret.

That's probably the problem. You need to run it on the same version of pycaret as used to save the model. It looks like you are using a model from 2020. If so, check which version of pycaret you used then and install that one on your streamlit environment.

**Comment by fitnesswanderer** [comment]
So I checked it was on pycaret version 1.0.0 and now I have installed 2.3.10. How do I install Pycaret 1.0.0?

**Comment by tvdboom** [comment]
`pip install pycaret==1.0.0`

**Comment by fitnesswanderer** [comment]
![err122](https://user-images.githubusercontent.com/12171326/217828540-67a15308-d5e8-47c8-8e96-540d5459f9a6.JPG)
 This is not working.

**Comment by tvdboom** [comment]
you have a space between pycaret and ==

**Comment by fitnesswanderer** [comment]
![err123](https://user-images.githubusercontent.com/12171326/217833762-b1e94e58-ceab-4f0b-b231-75bfef59dd90.JPG)
 This is the current output.

**Comment by moezali1** [comment]
@fitnesswanderer The above output relates to error in installing `shap` library. Maybe you can try installing `shap` with conda instead of pip. 

For now I am closing this issue as it doesn't relate or require any fix in pycaret.
