### ISSUE TITLE
SystemExit: (Type Error): using Tune_Model

### ISSUE THREAD

**Issue by chamsdg** [pycaret/pycaret#330]
Hello, when i want to tune my model in jupyterLab
I get this error:

An exception has occurred, use %tb to see the full traceback.

SystemExit: (Type Error): The behavior of tune_model in version 1.0.1 is changed. Please pass trained model object.

Need help me

**Comment by chamsdg** [comment]
i find the solution of my error

**Comment by 13293824182** [comment]
hi, i meet the same error, how do you slove the problem? thanks
