### ISSUE TITLE
[DOC]: Apple Silicon M1 installation guide

### ISSUE THREAD

**Issue by alegolas79** [pycaret/pycaret#3307]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://pycaret.gitbook.io/docs/get-started/installation

### Documentation problem

I have checked in several other issues pieces of information and bits to install properly pycaret into Apple M1.
I have found conflicting information very sparse here and there

### Suggested fix for documentation

a full dedicated Apple M1 installation guide with python version and known dependency

**Comment by moezali1** [comment]
@alegolas79 Are you mac user? Can you write one such guide?

**Comment by asmaier** [comment]
This worked on Mac M1 with Python 3.8
```
brew install cmake
pipenv install pycaret
```

See
- https://github.com/pycaret/pycaret/issues/2989#issuecomment-1260654928
- https://stackoverflow.com/questions/61883115/how-to-install-pycaret-python-library-in-mac-mojave
- https://stackoverflow.com/questions/74566704/cannot-install-lightgbm-3-3-3-on-apple-silicon
