### ISSUE TITLE
Inference and Setting of categorical_features does not work with pandas categoricals

### ISSUE THREAD

**Issue by moritzwilksch** [pycaret/pycaret#331]
Hey, I was just messing around with the seaborn-included "tips" dataset when I noticed the following:

- when features in the data frame have the type "categorical" they are not inferred as categorical. Instead, the type in the inferred table is just an empty string.
- when manually passing `categorical_features` = [...] the behaviour **does not change**, it does not override anything
- when manually converting all `categorical` columns to `object` and re-running the inference, the categories are correctly inferred.
Somehow there seems to be an issue with the handling of pandas categoricals (maybe the inference is only run on object columns,  ignoring all categorical colums).

**Comment by pycaret** [comment]
@moritzwilksch Can you please share the sample of the dataset here?

**Comment by moritzwilksch** [comment]
It is included with seaborn so:

```python
import pandas as pd
import seaborn as sns
df = sns.load_dataset('tips')
```

or via direct download from:
https://github.com/mwaskom/seaborn-data/blob/master/tips.csv

It looks like this:
![image](https://user-images.githubusercontent.com/58488209/89193165-e2d2b000-d5a5-11ea-9d34-8e1f71e8f47c.png)


But running:
```python
reg1 = setup(data=df,
             target='tip',
             categorical_features = ['sex', 'smoker', 'day', 'time'],
             numeric_features=['total_bill', 'size'],
)
```

gives:
![image](https://user-images.githubusercontent.com/58488209/89193309-1a415c80-d5a6-11ea-8943-aca8226b1228.png)

No matter whether I explicitly include categorical_features or not, the output of setup always looks like this.

**Comment by pycaret** [comment]
@moritzwilksch Thanks for reporting. PyCaret doesn't work with categorical data type of pandas df. Can you please change the data type to object before passing to pycaret. Please let me know if that works? Thanks

**Comment by moritzwilksch** [comment]
Yes as mentioned in my first post, after manually changing the type to object the auto-inference works just fine.

**Comment by pycaret** [comment]
Thanks for confirming @moritzwilksch. I will keep this issue open so that I can include this exception in documentation for next release.

**Comment by pycaret** [comment]
# include as a documentation exception in 2.1 sprint.
