### ISSUE TITLE
[BUG]: comet logger interfering

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#3310]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Even though I am not using comet logger, it is interfering and messing up our logger as well. 

comet logger should only get involved when log_experiment='comet_ml'. Otherwise it shouldn't get invoked.

![image](https://user-images.githubusercontent.com/54699234/218618717-c276eabd-3a2b-4854-8911-706281a0e8e8.png)

### Reproducible Example

```python
see above
```

### Expected Behavior

see above

### Actual Results

```python-traceback
see above
```

### Installed Versions

rc9

**Comment by Yard1** [comment]
Fixed in f250d707ba7a9785ee352162af385422c85804c7

**Comment by moezali1** [comment]
tested using `master` branch on 3/15/2023. The issue has been fixed.
