### ISSUE TITLE
[BUG]: create_api not working

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#3311]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

create_api failing. check out this colab: https://colab.research.google.com/drive/1Zv99qrhXN-KMZfi0Z9XZ4VoP4ArEmjD3?usp=sharing

### Reproducible Example

```python
see above
```

### Expected Behavior

see above

### Actual Results

```python-traceback
see above
```

### Installed Versions

rc9

**Comment by Yard1** [comment]
Fixed in 43e001f1a4922b22a765b8c5b1171f7f98088219
