### ISSUE TITLE
[BUG]: Time series notebooks tutorials not working

### ISSUE THREAD

**Issue by mateocomba123** [pycaret/pycaret#3313]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Hi,
The links to the time series tutorials are not working.

Example:

https://nbviewer.org/github/pycaret/pycaret/tree/master/examples/time_series/forecasting/

![image](https://user-images.githubusercontent.com/72084989/218819937-18f08fa0-5035-4bf1-ad2e-2149d18f18a8.png)

### Reproducible Example

```python
.
```

### Expected Behavior

.

### Actual Results

```python-traceback
.
```

### Installed Versions

.

**Comment by ngupta23** [comment]
@moezali1 Is there a reason why we removed the `examples` folder? In general, I have seen most repositories have an `examples` folder with notebooks. Can we follow the same convention? Also, can we add back the time series notebooks?

**Comment by moezali1** [comment]
@mateocomba123 This has been fixed. The official examples are here now: https://github.com/pycaret/pycaret/tree/master/examples
