### ISSUE TITLE
[BUG]: get_leaderboard function appends standard deviation scores instead of mean

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#3314]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

get_leaderboard function appends standard deviation scores instead of mean.

Reproduce the issue using tutorial/tutorial regression.ipynb.

### Reproducible Example

```python
see above
```

### Expected Behavior

see above

### Actual Results

```python-traceback
see above
```

### Installed Versions

rc9

**Comment by Yard1** [comment]
Fixed in 737cf5ddd2b5d79d1a5a9c8b9f3bc3e3244d0169
