### ISSUE TITLE
[INSTALL]: 

### ISSUE THREAD

**Issue by ahsanmanuu** [pycaret/pycaret#3317]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Anaconda

### Installation Method

pip install

### pycaret Version

pycaret full version

### Python Version

3.6

### Description

![image](https://user-images.githubusercontent.com/49349586/219369292-9e725da4-cb67-4e4e-af75-535450816084.png)
While installing pycaret full. I am facing the problem as mentioned in the attached image.
I have pypandoc version 1.10

Please help
Nothing is working I am in trouble last month

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by moezali1** [comment]
@ahsanmanuu 

This issue can be solved by updating pypandoc. Try this:

```
pip install -U pypandoc
```

**Comment by ahsanmanuu** [comment]
Jazak ALLAH mueez bhai.
I am so happy that after a long time you didn't forget and respond.
I salute to you.
I am subscriber and user of pycaret from india.
