### ISSUE TITLE
[BUG]: Classification vs Regression

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#3319]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

```
import pandas as pd
import numpy as np

num_cols = 900
num_rows = 1300

data = np.random.rand(num_rows, num_cols) * 10
int_data = np.random.randint(0, 10, size=(num_rows, num_cols))
mixed_data = np.where(np.random.rand(num_rows, num_cols) > 0.5, data, int_data)

df = pd.DataFrame(data)

df.columns = ['col_' + str(i) for i in range(num_cols)]

print(df.head())

from pycaret.classification import *

test = setup(data=df, target='col_899', fold=5)

model = compare_models()
```

It should convert the target "col_899" to string because i used pycaret.classification.

### Reproducible Example

```python
.
```

### Expected Behavior

.

### Actual Results

```python-traceback
.
```

### Installed Versions

<details>
all latest
</details>

**Comment by moezali1** [comment]
@tvdboom If my target variable `target_col` is a float and I import `pycaret.classification` and set `target='target_col'`. Will it / Should it automatically convert the `target_col` to categorical since I imported `pycaret.classification` or should it give error?
