### ISSUE TITLE
[BUG]: Generic test

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#3320]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

i created a generic code for generating 800 columns and 1300 rows in a pandas dataframe with random values to test and the rule times are weird.

i have a cpu amd ryzen 7 4800H 8 cores / 16 threads
16gb ram ddr4 3200mhz

### Reproducible Example

```python
import pandas as pd
import random
import string

# Definir o número de colunas e linhas
num_cols = 900
num_rows = 1300

# Gerar os valores aleatórios para preencher o dataframe
data = []
for i in range(num_rows):
    row = []
    for j in range(num_cols):
        letter = random.choice(string.ascii_lowercase)
        row.append(letter)
    data.append(row)

# Criar o dataframe
df = pd.DataFrame(data)

# Renomear as colunas
df.columns = ['col_' + str(i) for i in range(num_cols)]

# Visualizar o dataframe
print(df.head())

from pycaret.classification import *

test = setup(data=df, target='col_899', fold=5)

model = compare_models()
```

### Expected Behavior

.

### Actual Results

```python-traceback
1- classification in strange times
2- catboost doesn't seem to be fine
3- gpus not used! and i have 2 (1 in cpu intgrated and other nvidia gtx 1650ti)
```

### Installed Versions

<details>
pycaret 3 rc9
all latest
</details>

**Comment by moezali1** [comment]
@Yard1 Can you suggest as to why GPU is not consumed? I think for Catboost we have some rule configured that rows>50000 for GPU to kick-in. Do you rem?

**Comment by Yard1** [comment]
I'll remove that special case.
