### ISSUE TITLE
[INSTALL]: AttributeError: module 'numpy' has no attribute 'float'.

### ISSUE THREAD

**Issue by KhalidAmine** [pycaret/pycaret#3322]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

macOS-10.15.7-x86_64-i386-64bit

### Installation Method

pip install

### pycaret Version

2.3.10

### Python Version

3.8.8

### Description

After trying to install pycaret (pip install pycaret) and doing from pycaret.classification import * , i get this error: 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 5
      3 import statsmodels.api as sm
      4 import numpy as np
----> 5 from pycaret.classification import *
      6 import matplotlib.pyplot as plt

File ~/Desktop/dev/Eth_ML_predictor/ML-env/lib/python3.8/site-packages/pycaret/classification.py:10
      7 import pandas as pd
      8 import numpy as np
---> 10 import pycaret.internal.tabular
     11 from pycaret.loggers.base_logger import BaseLogger
     12 from pycaret.parallel import ParallelBackend

File ~/Desktop/dev/Eth_ML_predictor/ML-env/lib/python3.8/site-packages/pycaret/internal/tabular.py:16
     10 from pycaret import loggers
     11 from pycaret.internal.meta_estimators import (
     12     PowerTransformedTargetRegressor,
     13     CustomProbabilityThresholdClassifier,
     14     get_estimator_from_meta_estimator,
     15 )
---> 16 from pycaret.internal.pipeline import (
     17     add_estimator_to_pipeline,
     18     get_pipeline_estimator_label,
...

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by ngupta23** [comment]
For Mac, maybe you can refer to these FAQs (search for `Mac` in the link below) to see if it helps. Unfortunately, we have no way to verify this issue. 

https://github.com/pycaret/pycaret/issues/1298

**Comment by talha-soffos** [comment]
Got same error in windows in a fresh virtual env. Python version 3.8.5 , windows 10 home.
This is how I installed the package
`pip install pycaret[full]`

**Comment by ngupta23** [comment]
I would not recommend installing full. Please see here: https://github.com/pycaret/pycaret/issues/3330

**Comment by Yard1** [comment]
Install `"numpy<1.24"` to fix.

**Comment by ngupta23** [comment]
> Install "numpy<1.24" to fix.

@Yard1 Does the requirements.txt need to be revised?

**Comment by Yard1** [comment]
Yes, I'll update it
