### ISSUE TITLE
[BUG]: Strange algorithm times

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#3328]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

regardless of the code I used, and the dataset (which has a lot of columns), there is a very big difference in the times that the algorithms take to create a model. Something doesn't seem right, the time difference is too big.

create a code to generate a dataset with random data, example 2000 columns x 1000 rows

from pycaret.classification import *

![image](https://user-images.githubusercontent.com/41735311/220791332-564118af-17ac-44c8-8406-d94cb1fb989b.png)

### Reproducible Example

```python
.
```

### Expected Behavior

smaller time difference between algorithms

### Actual Results

```python-traceback
see image
```

### Installed Versions

<details>
System:
    python: 3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\username\Anaconda3\python.exe
   machine: Windows-10-10.0.22623-SP0

PyCaret required dependencies:
                 pip: 23.0.1
          setuptools: 67.4.0
             pycaret: 3.0.0rc9
             IPython: 8.10.0
          ipywidgets: 8.0.4
                tqdm: 4.64.1
               numpy: 1.24.2
              pandas: 1.5.3
              jinja2: 3.1.2
               scipy: 1.10.1
              joblib: 1.3.0.dev0
             sklearn: 1.3.dev0
                pyod: 1.0.7
            imblearn: 0.10.1
   category_encoders: 2.6.0
            lightgbm: 3.3.5.99
               numba: 0.56.4
            requests: 2.28.2
          matplotlib: 3.7.0
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.9.0
             kaleido: 0.2.1
         statsmodels: 0.13.5
              sktime: 0.16.1
               tbats: 1.1.2
            pmdarima: 2.0.2
              psutil: 5.9.4

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: 0.3.0
                umap: 0.5.3
    pandas_profiling: 4.0.0
  explainerdashboard: 0.4.2.1
             autoviz: 0.1.58
           fairlearn: 0.8.0
             xgboost: 1.7.3
            catboost: 1.1.1
              kmodes: 0.12.2
             mlxtend: 0.21.0
       statsforecast: 1.4.0
        tune_sklearn: 0.4.5
                 ray: 2.2.0
            hyperopt: 0.2.7
              optuna: 3.1.0
               skopt: 0.9.0
              mlflow: 2.1.1
              gradio: 3.19.1
             fastapi: 0.92.0
             uvicorn: 0.20.0
              m2cgen: 0.10.0
           evidently: 0.2.5
               fugue: 0.8.1
           streamlit: Not installed
             prophet: Not installed
</details>

**Comment by celestinoxp** [comment]
Try with this code
import pandas as pd
import random
import string

# Definir o número de colunas e linhas
num_cols = 2000
num_rows = 2000

# Gerar os valores aleatórios para preencher o dataframe
data = []
for i in range(num_rows):
    row = []
    for j in range(num_cols):
        letter = random.choice(string.ascii_lowercase)
        row.append(letter)
    data.append(row)

# Criar o dataframe
df = pd.DataFrame(data)

# Renomear as colunas
df.columns = ['col_' + str(i) for i in range(num_cols)]

# Visualizar o dataframe
print(df.head())

from pycaret.classification import *

test = setup(data=df, target='col_899', fold=5)

model = compare_models()

**Comment by moezali1** [comment]
@celestinoxp Can you try multiplying TT (Sec) with fold? I think the TT Sec is time per one fit. I am not 100% sure though.

**Comment by ngupta23** [comment]
Also, it may not include the final train time for the full train data.
