### ISSUE TITLE
custom parameters are not working for clustering algorithms.

### ISSUE THREAD

**Issue by sathishkumar369** [pycaret/pycaret#334]
Hi pycaret team!
Loved your work for pycaret 2.0 version.

custom parameters are not working for clustering algorithms, I have customized parameters for kmeans as well as dbscan. it's throwing an error.
I checked for the classification one with random forest by changing criterion= "gini to entropy", it's worked well.

PFA.
![Screenshot (324)](https://user-images.githubusercontent.com/40235632/89198844-68b52200-d5cb-11ea-86ee-0a7d033ada5c.png)

**Comment by pycaret** [comment]
@sathishkumar369 Thanks for reporting. This is a bug (only impacting DBSCAN in pycaret.clustering).

**Comment by sathishkumar369** [comment]
Hi Moez,
Not only for dbscan, even I checked for kmeans.
It's throwing same error.
I guess keyword arguments kwargs** are not interpreted properly to clustering algorithms.

**Comment by pycaret** [comment]
@sathishkumar369 This will only be an issue in DBSCAN. 

For **Kmeans** and other algorithms, if you are trying to use **n_clusters**, that will be a problem. Instead you should use **num_clusters** which internally maps it with **n_clusters**.

Hope that helps.

**Comment by sathishkumar369** [comment]
@pycaret 
Yeah, thanks that helped.
But in real time scenario's dbscan has some special features which can also cluster unique (noisy) data.
Can I expect dbscan will work fine in tuning parameters?
