### ISSUE TITLE
[BUG]: Faild to run the LeavaOneOut strategy for CV.

### ISSUE THREAD

**Issue by m-kaka** [pycaret/pycaret#3347]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

When set the Custom CV strategy(LeaveOneOuf), Pycaret showed the error related to "n_splits".
Please chceck the below my answers.

### Reproducible Example

```python
from pycaret.regression import *
from sklearn.model_selection import LeaveOneOut
from pycaret.datasets import get_data
boston_data = get_data('boston')
cv2 = LeaveOneOut()
exp = setup(boston_data, target = 'medv', fold_strategy = cv2, session_id=123)
br_model = create_model('br')
```

### Expected Behavior

Training the model even if changed the fold_strategy from k-fold to LeaveOneOut.

### Actual Results

```python-traceback
Cell In [3], line 2
      1 #best_model = compare_models()
----> 2 br_model = create_model('br')

File /usr/local/lib/python3.8/site-packages/pycaret/regression.py:946, in create_model(estimator, fold, round, cross_validation, fit_kwargs, groups, verbose, return_train_score, **kwargs)
    831 def create_model(
    832     estimator: Union[str, Any],
    833     fold: Optional[Union[int, Any]] = None,
   (...)
    840     **kwargs,
    841 ):
    843     """
    844     This function trains and evaluates the performance of a given estimator
    845     using cross validation. The output of this function is a score grid with
   (...)
    943 
    944     """
--> 946     return pycaret.internal.tabular.create_model_supervised(
    947         estimator=estimator,
    948         fold=fold,
    949         round=round,
    950         cross_validation=cross_validation,
    951         fit_kwargs=fit_kwargs,
    952         groups=groups,
    953         verbose=verbose,
    954         return_train_score=return_train_score,
    955         **kwargs,
    956     )

File /usr/local/lib/python3.8/site-packages/pycaret/internal/tabular.py:3243, in create_model_supervised(estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, verbose, system, X_train_data, y_train_data, metrics, experiment_custom_tags, add_to_model_list, probability_threshold, display, return_train_score, **kwargs)
   3239 display.move_progress()
   3241 logger.info("Creating metrics dataframe")
-> 3243 fold = cv.n_splits
   3245 if return_train_score:
   3246     model_results = pd.DataFrame(
   3247         {
   3248             "Split": ["CV-Train"] * fold
   (...)
   3255         }
   3256     )

AttributeError: 'LeaveOneOut' object has no attribute 'n_splits'
```

### Installed Versions

<details>
'2.3.10'
</details>

**Comment by kumar21120** [comment]
This might not be an exact solution you need. However the following code works:

from pycaret.regression import *
from pycaret.datasets import get_data
import math

boston_data = get_data('boston')
exp = setup(boston_data, target = 'medv', fold_strategy = 'kfold', fold = math.floor(len(boston_data)*0.7), session_id=123)

The following statement is from scikit-learn documentation:

'Note: LeaveOneOut() is equivalent to KFold(n_splits=n) and LeavePOut(p=1) where n is the number of samples.'

I hope this helps.

**Comment by m-kaka** [comment]
@kumar21120 
Thank you for your good solution. I understand!
I will changed the fold number adjusting by train_data size when use the LeaveOneOut.

By the way, do you know the way to know that to know the each training and validation data per CV?
