### ISSUE TITLE
add metric Specificity doesn't work

### ISSUE THREAD

**Issue by Emhyrr** [pycaret/pycaret#3351]
```
from pycaret.datasets import get_data
data = get_data('juice')

from pycaret.classification import *
s = setup(data, target = 'Purchase', session_id = 123, silent = True)

# create a custom function
def calculate_specificity(y, y_pred):
    
    tp, tn, fn, fp = 0.0,0.0,0.0,0.0
    for l,m in enumerate(y):        
        if m==y_pred[l] and m==1:
            tp+=1
        if m==y_pred[l] and m==0:
            tn+=1
        if m!=y_pred[l] and m==1:
            fn+=1
        if m!=y_pred[l] and m==0:
            fp+=1
            
    return tn/(tn+fp)

# add metric to PyCaret
add_metric('specificity', 'specificity', calculate_specificity)

lr = create_model('lr')
```
_Originally posted by @moezali1 in https://github.com/pycaret/pycaret/issues/1593#issuecomment-922936685_

""""
But this doesn't work. It gives zero value
![image](https://user-images.githubusercontent.com/118763844/222052448-15800349-77ff-4168-a29c-ee76cd08cb33.png)

**Comment by Yard1** [comment]
@Emhyrr the problem here is twofold:
1. the metric gets added correctly and is used by pycaret, but the issue is that `(tn+fp)` equals 0, resulting in a divide by zero error
2. that error is swallowed and not propagated anywhere.

I'll open a PR to redirect metric errors to `logs.log`.
