### ISSUE TITLE
[BUG]: remove_outliers behaving weird

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#3365]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

```
# load dataset
from pycaret.datasets import get_data
insurance = get_data('insurance')

# init setup
from pycaret.regression import *
reg1 = setup(data = insurance, target = 'charges', remove_outliers = True)
```

![image](https://user-images.githubusercontent.com/54699234/223151502-d8ad35aa-b806-4606-855a-6c12b225bde8.png)

Why the sum of transformed train `899` and transformed test `402` doesn't match the transformed data shape `1304`. The outlier threshold % is set to 0.05 then why the difference between number of rows in original data and transformed data is not 5%?

### Reproducible Example

```python
see above
```

### Expected Behavior

see above

### Actual Results

```python-traceback
see above
```

### Installed Versions

rc9

**Comment by tvdboom** [comment]
There is an issue here but it's not related to outliers. The difference of 5% is only on the training set, since outlier removal should only be applied to the training set. before 936 rows, after 889 => 936 * 0.95 = 889, so that's correct.

The problem is that the initial display of the length of the transformed dataset is wrong. The results you get after with `reg1.train_transformed` etc are correct. @Yard1 can you have a look? I think it has something to do with the new caching you added to the internal pipeline.

**Comment by moezali1** [comment]
@tvdboom Why the train set is `899` and not `889`?

**Comment by tvdboom** [comment]
It's not. Check the length of `exp.train`. The initial display is wrong.

**Comment by Yard1** [comment]
I'll take a look, yeah

**Comment by Yard1** [comment]
@tvdboom I am getting the same results both with and without caching (if session_id is the same), and indeed train+test doesn't add up to dataset. Looking deeper

**Comment by Yard1** [comment]
@tvdboom I think what's happening is that the outliers are removed from X, but the preprocessor doesn't remove the rows from y. Then, when X and y are concatted, extra rows are added again.

**Comment by Yard1** [comment]
Also random state was not set on `RemoveOutliers` which was the main reason for weirdness

**Comment by tvdboom** [comment]
> I think what's happening is that the outliers are removed from X, but the preprocessor doesn't remove the rows from y (as it requires X, so it's a noop when just y is passed). Then, when X and y are concatted, extra rows are added again. A quick fix is to ensure we use inner joins instead of outer joins. That being said, the preprocessor itself should be fixed as well (that may be tricky, though).

It's not that. y is changed together with X, see: https://github.com/pycaret/pycaret/blob/ba6a9309bfc3071bc3609ceacfeab37e17baaffc/pycaret/internal/preprocess/transformers.py#L498-L502.

I figured it out. The way the data attributes were called was all wrong. X and y should never be calculated independently, which was happening now. I think Nikhil unintendingly changed this behavior  when refactoring to separate data attributes per module. I'll create a new PR for this and reject yours. Neither inner joins nor unique indices are necessary.

> Also random state was not set on RemoveOutliers which was the main reason for weirdness

This was not set indeed. I added it to the new PR.
