### ISSUE TITLE
[BUG]: default value of index parameter in the setup

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#3373]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

We currently have `index` parameter in the `setup` with default set to `False`. We should NOT reset the index by default. It should be explicit choice of user if anything. Can we set the default to `True` meaning Keep the provided index.

![image](https://user-images.githubusercontent.com/54699234/223572011-16c7bf05-14ea-478e-9c60-8bb2c95a8856.png)

### Reproducible Example

```python
see above
```

### Expected Behavior

see above

### Actual Results

```python-traceback
see above
```

### Installed Versions

rc9

**Comment by tvdboom** [comment]
I don't agree with this. I think the vast majority of users don't use the index of the dataframe for anything. Keeping the index can cause confusion when you drop rows of the dataset, therefore the dataset becomes of length 300 and your indices displayed when printing the dataframe go up to 350 (just as an example)

**Comment by moezali1** [comment]
@tvdboom I have a production use-case and I know many other implementations where index is used to for join after predictions. 

Normally when people drop rows, they usually do reset_index. 

I think it will be very weird for people to see their indexes reset by default without explicitly asking for it. @Yard1 @ngupta23 What are your thoughts on this?

**Comment by ngupta23** [comment]
I can see use cases where the index is the ID and used after the prediction. Better to avoid changing it if we can. Is there any reason to reset it other than drop rows will produce non continuous indices?

**Comment by Yard1** [comment]
SMOTE or anything else that adds extra rows will require an index reset.

**Comment by tvdboom** [comment]
I'll set the default to True

**Comment by moezali1** [comment]
@Yard1 If I remember correctly, the SMOTE dataset is never exposed to user. It happens internally within CV. Is that still correct?

I can't think of any parameter other than `remove_outliers` and `fix_imbalance` to be capable of changing the number of rows. Am I still correct on this?

**Comment by moezali1** [comment]
tested using `master` branch on 3/15/2023. The issue has been fixed.
