### ISSUE TITLE
[BUG]: low_variance_threshold buggy behavior

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#3375]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

`low_variable_threshold` is only suppose to impact categorical features as per documentation. However I noticed it is somehow dropping a large % of numeric features as well. see example below

![image](https://user-images.githubusercontent.com/54699234/223573003-7b8fd58e-774e-4cf8-a411-1431f959b6c5.png)

```
# load dataset
from pycaret.datasets import get_data
mice = get_data('mice')

# filter dataset
mice = mice[mice['Genotype'] == 'Control']

# init setup
from pycaret.classification import *
clf1 = setup(data = mice, target = 'class', low_variance_threshold = 0.1)

```
![image](https://user-images.githubusercontent.com/54699234/223573182-60c33e41-a4c3-457b-bcae-1740164ee186.png)

![image](https://user-images.githubusercontent.com/54699234/223573161-75a00fd9-ac02-41ab-9d1a-e2d2130fb214.png)

### Reproducible Example

```python
see above
```

### Expected Behavior

see above

### Actual Results

```python-traceback
see above
```

### Installed Versions

rc9

**Comment by tvdboom** [comment]
Why should it only impact categorical features? That makes no sense. You want to remove numerical features with all the same value or with minimal variance.

**Comment by moezali1** [comment]
Maybe this is lack of my knowledge. How are you calculating low variance for numeric features? I don't disagree with you but I thought we were using count frequency in past and that is why it was only applicable on categorical feature.

**Comment by tvdboom** [comment]
The new implementation uses sklearn's [VarianceThreshold](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.VarianceThreshold.html). It calculates the variance over the column using numpy

**Comment by moezali1** [comment]
Got it. thanks.
