### ISSUE TITLE
[DOC]: proper way to avoid findfont warning message

### ISSUE THREAD

**Issue by castorfou** [pycaret/pycaret#3376]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://pycaret.gitbook.io/docs/get-started/tutorials

### Documentation problem

I have some warning message (due to matplotlib I guess) when evaluating models

`findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial, Liberation Sans, Bitstream Vera Sans, sans-serif`

And I cannot find in documentation a way to fix it or to silent it.

### Suggested fix for documentation

maybe in tutorials?

**Comment by moezali1** [comment]
@castorfou You can add this code at the beginning of the notebook. Please note that it will suppress all warnings. 

```
import warnings
warnings.filterwarnings("ignore")
```

**Comment by castorfou** [comment]
I tried with filterwarnings but it doesn't help.

What helped for me was to delete matplotlib font cache which was at `~/.cache/matplotlib/fontlist-v330.json`
This has been provided by https://stackoverflow.com/questions/37920935/matplotlib-cant-find-font-installed-in-my-linux-machine.

I don't think it needs an entry in Pycaret doc but someone with the same problem could find a solution in this thread.
