### ISSUE TITLE
[BUG]: Formatting of period index messed up in time series module

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#3387]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Formatting of period index messed up in time series module

### Reproducible Example

```python
see above
```

### Expected Behavior

see above

### Actual Results

```python-traceback
see above
```

### Installed Versions

rc9

**Comment by ngupta23** [comment]
Also reported in https://github.com/pycaret/pycaret/issues/3333. Fixed in https://github.com/pycaret/pycaret/pull/3335. Will go out in the next release

**Comment by moezali1** [comment]
tested using `master` branch on 3/15/2023. The issue has been fixed.
