### ISSUE TITLE
[INSTALL]: `mamba (conda-forge)`: nothing provides gensim <4.0.0 needed by pycaret-2.3.10-pyhd8ed1ab_0

### ISSUE THREAD

**Issue by jeanmonet** [pycaret/pycaret#3394]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Trying to install the latest version of pycaret via conda-forge (with `mamba`), I get the following error:

    nothing provides gensim <4.0.0 needed by pycaret-2.3.10-pyhd8ed1ab_0

Can this be fixed?

### Reproducible Example

```python
mamba install "pycaret==2.3.10" -c conda-forge
```

### Expected Behavior

Should install with gensim > 4.0.0

### Actual Results

```python-traceback
> Could not solve for environment specs
> Encountered problems while solving:
>   - nothing provides gensim <4.0.0 needed by pycaret-2.3.10-pyhd8ed1ab_0
> The environment can't be solved, aborting the operation
```

### Installed Versions

<details>
Latest mamba & conda version.

Python 3.10
</details>

**Comment by ngupta23** [comment]
Pycaret 2.3.x does not support Python 3.10. My recommendation would be to install it as follows

- Use a dedicated environment to install
- Use pip to install the latest pre-release version which supports python 3.10

```
pip install --pre -U pycaret
```

**Comment by jeanmonet** [comment]
Thanks, got it to work by installing the pre-releas (rc9).
