### ISSUE TITLE
[DOC]: Not able to reach PyCaret Tutorials 

### ISSUE THREAD

**Issue by binaryyskull** [pycaret/pycaret#3403]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://nbviewer.org/github/pycaret/pycaret/blob/master/examples/time_series/forecasting/time_series_101.ipynb

### Documentation problem

I can not reach all of the tutorials. Error message is:404 : Not Found
Remote HTTP 404: examples/time_series/forecasting/time_series_101.ipynb not found among 379 files

### Suggested fix for documentation

Before that, I was able to open but I could not now. It is highly important for us. Thanks!

**Comment by moezali1** [comment]
All documentation will be updated tonight.
