### ISSUE TITLE
[INSTALL]: Possible dependency conflicts

### ISSUE THREAD

**Issue by AccuInsight** [pycaret/pycaret#3404]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

ubuntu

### Installation Method

pip install

### pycaret Version

latest

### Python Version

3.8, 3.9

### Description

Running pipdeptree -p pycaret shows the sklearn dependencies as shown below.

$ pipdeptree -p pycaret |grep skl
Warning!!! Possibly conflicting dependencies found:
* tensorflow==2.3.1
 - numpy [required: >=1.16.0,<1.19.0, installed: 1.23.5]
------------------------------------------------------------------------
Warning!! Cyclic dependencies found:
* list-imports => list-imports => list-imports
------------------------------------------------------------------------

Since sklearn is not used when installing scikit-learn, please remove it from dependencies.

### Installation Logs

<details>

Requirement already satisfied: future in /opt/conda/lib/python3.8/site-packages (from pyLDAvis->pycaret) (0.18.3)
Collecting sklearn
  Downloading sklearn-0.0.post1.tar.gz (3.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
[91m  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      
      If the previous advice does not cover your use case, feel free to report it at
      https://github.com/scikit-learn/sklearn-pypi-package/issues/new
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
[0m[91merror: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
</details>

**Comment by ngupta23** [comment]
Can you try this with the pre-release version of `pycaret` - 3.0.0rc9 (soon to be released version 3.0.0)? It has much lighter dependencies and hopefully, this issue will not show up there.

**Comment by ngupta23** [comment]
Update: Please try on 3.0.0 which was released yesterday. This should hopefully not have any issues.

**Comment by AccuInsight** [comment]
we install pycaret==2.3.10. I will check 3.0.0 version. Thanks.
