### ISSUE TITLE
> AttributeError: Coefficients are not defined for Booster type gbtree

### ISSUE THREAD

**Issue by HigorNunesM** [pycaret/pycaret#3406]
> AttributeError: Coefficients are not defined for Booster type gbtree

Would be nice to have a standardized way to get the feature importances. 
This also does not work for random forest or other types of models.

_Originally posted by @sorenwacker in https://github.com/pycaret/pycaret/issues/815#issuecomment-905766620_
            
Was this improvement addressed? I am trying to get the feature importance of multiple trained models. Some I can access with:

pd.DataFrame({'Feature': get_config('X_train').columns, 'Value' : abs(lr.feature_importances_)}).sort_values(by='Value', ascending=False)

but other algorithms like lasso I can't.

**Comment by ngupta23** [comment]
These are not defined by pycaret. It is defined by sklearn and is only available for some models. Please feel free to file an enhancement request with sklearn. If that is implemted by them, it will automatically be made available within pycaret once we upgrade to that version of sklearn.
