### ISSUE TITLE
[DOC]: The links for the tutorial are broken

### ISSUE THREAD

**Issue by garciadias** [pycaret/pycaret#3407]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://pycaret.gitbook.io/docs/get-started/tutorials

### Documentation problem

The list of linked tutorials is broken.
For example: https://nbviewer.org/github/pycaret/pycaret/blob/master/tutorials/Regression%20Tutorial%20Level%20Beginner%20-%20REG101.ipynb

### Suggested fix for documentation

I am not sure how to correct the embedded links at nbviewer, but a quick fix would be to use the github pages, like in https://github.com/pycaret/pycaret/blob/master/tutorials/Tutorial%20-%20Regression.ipynb

**Comment by moezali1** [comment]
The documentation will be completely refreshed tonight with the release of 3.0.

Thanks for reporting.
