### ISSUE TITLE
Skipping Imputation

### ISSUE THREAD

**Issue by sparvaneh** [pycaret/pycaret#342]
Hi,

Is there anyway to disable imputation in setup?

**Comment by pycaret** [comment]
@sparvaneh If there is no missing value in data, there is no impact. 

Why would you want to disable imputation? If it's a general use-case, we can take this as an enhancement for future sprint.

**Comment by sparvaneh** [comment]
As two general use cases:
1- Classifiers like XGboost can handle data with missing value very well and imputation might be unnecessary. 
2- In some cases, it would be interesting to report results with and without imputation and enabling/disabling imputation allows to have this comparison.
3- Assuming that you will make it easier to use Pycaret with external training and test sets in the future, imputation might be done in data preparation before using Pycaret.

**Comment by pycaret** [comment]
Thanks @sparvaneh. Adding **enhancement** tag.

**Comment by pycaret** [comment]
@sparvaneh Would you like to work on this change?

**Comment by sparvaneh** [comment]
@pycaret Depends on your timeline, I would be happy to help.

**Comment by pycaret** [comment]
@sparvaneh 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.

**Comment by miteshyadav** [comment]
Has this feature been added? How do you disable imputation?

**Comment by bimhud** [comment]
It seems that this feature hasn't been added. There are only two choices of imputation, can't disable it from the current version @sparvaneh

**Comment by sparvaneh** [comment]
@miteshyadav and @bimhud  You can skip imputation by setting preprocess: False. However, you can't train many classifiers such as SVM and LDA.
Below is description for preprocess:
When set to False, no transformations are applied except for train_test_split and custom transformations passed in custom_pipeline param. Data must be ready for modeling (no missing values, no dates, categorical data encoding), when preprocess is set to False.
