### ISSUE TITLE
[BUG]: Transformed test set shape (samples) is not the same input test_data shape (samples)

### ISSUE THREAD

**Issue by aymaneco** [pycaret/pycaret#3428]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

My X_train has 2552 samples and my X_HO has 851 samples.

- In the latest version of pycaret, when i'm using just **test_data=X_HO** in the setup() method, my transformed test set shape has 1702 samples (the origin samples are doubled), however as stated before my X_HO has just 851 samples.
![image](https://user-images.githubusercontent.com/59214472/227446672-53171e3f-d2cc-4370-9e9f-6d646d67361d.png)
This issue was not observed in the previous version of pycaret, i tested with the old version ('2.3.10')  '2.3.10'
![image](https://user-images.githubusercontent.com/59214472/227445962-7b3ef660-ff22-4bd1-a382-ce1014935cba.png)

### Reproducible Example

```python
exp_name = setup(
    session_id=1234,
    data=X_train,
    target='target',
    preprocess=False,
    remove_outliers=False,
    test_data=X_HO,
    data_split_shuffle=True,
    ordinal_features={'column': list(X_train.column.unique())})
```

### Expected Behavior

I'm expecting that the results be the same as the previous version of pycaret, as here in the screen.
![image](https://user-images.githubusercontent.com/59214472/227445962-7b3ef660-ff22-4bd1-a382-ce1014935cba.png)

### Actual Results

```python-traceback
The problem is already detailed in the description.
```

### Installed Versions

<details>
Pycaret 3.0.0
</details>

**Comment by tvdboom** [comment]
Could it be that your `X_train` and `X_HO` have the same indices? Pycaret doesn't work well with duplicate indices in the dataset. Try changing the indices in `X_HO` and let me know if that changes the results.

**Comment by aymaneco** [comment]
Yes it works by setting **index=False** in the setup() method, and now the result is as expected, thank you so much :)

**Comment by ngupta23** [comment]
@tvdboom - Not sure of the specifics, but can we somehow check this internally and raise an error in `setup`?

**Comment by aymaneco** [comment]
@ngupta23 it would be really helpful to raise this error :)
