### ISSUE TITLE
[DOC]: Update get_config()  parameters in doc! 

### ISSUE THREAD

**Issue by DiegoCotacio** [pycaret/pycaret#3431]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

I was trying to get the train preprocessed dataframe with the current online documentation of get_config() function but these are not the rigth ones:
https://pycaret.gitbook.io/docs/get-started/functions/others

### Documentation problem

![online-doc](https://user-images.githubusercontent.com/107958204/227755191-f47c1ed8-bccc-4a50-87fe-7f015a79b97a.png)

outdated information!

### Suggested fix for documentation

These are the rigth parameters according to ValueError:
... Possible variables are: ['train_transformed', 'y_train', '_available_plots', 'log_plots_param', 'fix_imbalance', 'X_train_transformed', 'is_multiclass', 'variables', 'memory', 'variable_and_property_keys', 'target_param', 'y_train_transformed', 'test', 'fold_generator', 'seed', 'test_transformed', 'html_param', 'X_train', 'USI', 'exp_id', 'y_test_transformed', '_ml_usecase', 'fold_shuffle_param', 'y_test', 'gpu_param', 'n_jobs_param', 'X_test_transformed', 'X', 'idx', 'data', 'X_test', 'y_transformed', 'y', 'exp_name_log', 'logging_param', 'dataset_transformed', 'gpu_n_jobs_param', 'fold_groups_param', 'X_transformed', 'dataset', 'pipeline', 'train']

**Comment by ngupta23** [comment]
Are you using the latest release (3.0.0) and not an older `rc` release?

**Comment by moezali1** [comment]
@DiegoCotacio Thanks for letting us know. I have updated the documentation now.
