### ISSUE TITLE
[BUG]: Dagshub in setup doesn't work when using Jupyter Notebook or VSC

### ISSUE THREAD

**Issue by DiegoCotacio** [pycaret/pycaret#3435]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [x] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Hello!
I am trying to integrate my project to Dagshub.
I tried the examples of the documentation in a Google Colab and everything works Ok.
However, when running it from a Jupyter Notebook or VSC I have problems when I specify the owner_name/repo_name input of my dagshub repo.

The error generated is an "IndexError: list index out of range".

Verification was done in dagshub but only that.
In the same way, I tried the alternative of launching dagshub integration but it didn't work either:
https://dagshub.com/blog/pycaret-integration/
(**I'm using version 3.0.0 of pycaret**)

### Reproducible Example

```python
s = setup(data, target = 'Exited', session_id = 123, log_experiment = 'dagshub', experiment_name = 'churn_v4', log_data = True)
```

### Expected Behavior

Please insert your repository owner_name/repo_name:diego.cotacio/churn_v4
Repository initialized!
2023/03/27 05:10:53 INFO mlflow.tracking.fluent: Experiment with name 'project_iris' does not exist. Creating a new experiment.
Uploading files (2) to "diego.cotacio/churn_v4"...
Upload finished successfully!

### Actual Results

```python-traceback
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_21112\2050961637.py in <cell line: 7>()
      6 
----> 7 s = setup(data, target = 'Exited', session_id = 123, fix_imbalance=True, log_experiment = 'dagshub', experiment_name = 'churn_v4', log_profile = True, log_data = True, experiment_custom_tags=None)

~\anaconda3\envs\curso\lib\site-packages\pycaret\classification\functional.py in setup(data, data_func, target, index, train_size, test_data, ordinal_features, numeric_features, categorical_features, date_features, text_features, ignore_features, keep_features, preprocess, create_date_columns, imputation_type, numeric_imputation, categorical_imputation, iterative_imputation_iters, numeric_iterative_imputer, categorical_iterative_imputer, text_features_method, max_encoding_ohe, encoding_method, rare_to_value, rare_value, polynomial_features, polynomial_degree, low_variance_threshold, group_features, group_names, drop_groups, remove_multicollinearity, multicollinearity_threshold, bin_numeric_features, remove_outliers, outliers_method, outliers_threshold, fix_imbalance, fix_imbalance_method, transformation, transformation_method, normalize, normalize_method, pca, pca_method, pca_components, feature_selection, feature_selection_method, feature_selection_estimator, n_features_to_select, custom_pipeline, custom_pipeline_position, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, verbose, memory, profile, profile_kwargs)
    601     exp = _EXPERIMENT_CLASS()
    602     set_current_experiment(exp)
--> 603     return exp.setup(
    604         data=data,
    605         data_func=data_func,

~\anaconda3\envs\curso\lib\site-packages\pycaret\classification\oop.py in setup(self, data, data_func, target, index, train_size, test_data, ordinal_features, numeric_features, categorical_features, date_features, text_features, ignore_features, keep_features, preprocess, create_date_columns, imputation_type, numeric_imputation, categorical_imputation, iterative_imputation_iters, numeric_iterative_imputer, categorical_iterative_imputer, text_features_method, max_encoding_ohe, encoding_method, rare_to_value, rare_value, polynomial_features, polynomial_degree, low_variance_threshold, group_features, group_names, drop_groups, remove_multicollinearity, multicollinearity_threshold, bin_numeric_features, remove_outliers, outliers_method, outliers_threshold, fix_imbalance, fix_imbalance_method, transformation, transformation_method, normalize, normalize_method, pca, pca_method, pca_components, feature_selection, feature_selection_method, feature_selection_estimator, n_features_to_select, custom_pipeline, custom_pipeline_position, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, engine, verbose, memory, profile, profile_kwargs)
   1023 
   1024         runtime = np.array(time.time() - runtime_start).round(2)
-> 1025         self._set_up_logging(
   1026             runtime,
   1027             log_data,

~\anaconda3\envs\curso\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py in _set_up_logging(self, runtime, log_data, log_profile, experiment_custom_tags)
    262 
    263         if self.logging_param:
--> 264             self.logging_param.log_experiment(
    265                 self,
    266                 log_profile,

~\anaconda3\envs\curso\lib\site-packages\pycaret\loggers\dashboard_logger.py in log_experiment(self, experiment, log_profile, log_data, experiment_custom_tags, runtime)
    206         params = kdict.get("Value")
    207         for logger in self.loggers:
--> 208             logger.init_experiment(
    209                 experiment.exp_name_log, f"{SETUP_TAG} {experiment.USI}", setup=True
    210             )

~\anaconda3\envs\curso\lib\site-packages\pycaret\loggers\dagshub_logger.py in init_experiment(self, setup, *args, **kwargs)
     63                 self.remote = os.getenv("MLFLOW_TRACKING_URI")
     64 
---> 65             self.repo = Repo(
     66                 owner=self.remote.split(os.sep)[-2],
     67                 name=self.remote.split(os.sep)[-1].replace(".mlflow", ""),

IndexError: list index out of range
```

### Installed Versions

System:
    python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\diego\anaconda3\envs\curso\python.exe
   machine: Windows-10-10.0.22621-SP0

PyCaret required dependencies:
                 pip: 21.2.4
          setuptools: 60.10.0
             pycaret: 3.0.0
             IPython: 7.34.0
          ipywidgets: 7.7.4
                tqdm: 4.65.0
               numpy: 1.23.5
              pandas: 1.5.3
              jinja2: 3.0.3
               scipy: 1.9.1
              joblib: 1.2.0
             sklearn: 1.2.2
                pyod: 1.0.9
            imblearn: 0.10.1
   category_encoders: 2.6.0
            lightgbm: 3.3.5
               numba: 0.56.4
            requests: 2.27.1
          matplotlib: 3.7.1
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.13.1
             kaleido: 0.2.1
         statsmodels: 0.13.5
              sktime: 0.16.1
               tbats: 1.1.2
            pmdarima: 2.0.3
              psutil: 5.9.4

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: 0.3.2
                umap: 0.5.3
    pandas_profiling: 3.6.6
  explainerdashboard: 0.4.2.1
             autoviz: 0.1.58
           fairlearn: 0.7.0
             xgboost: 1.7.4
            catboost: Not installed
              kmodes: Not installed
             mlxtend: Not installed
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: Not installed
              optuna: Not installed
               skopt: Not installed
              mlflow: 1.30.0
              gradio: 3.23.0
             fastapi: 0.95.0
             uvicorn: 0.21.1
              m2cgen: 0.10.0
           evidently: 0.2.7
               fugue: Not installed
           streamlit: Not installed
             prophet: Not installed

**Comment by moezali1** [comment]
@DiegoCotacio Hi, I am unable to reproduce this error.

**Comment by sefirotha** [comment]
I have the same issue. 
If i print os.sep, it will show "\\" but the way pycaret handles the dagshub path is by using the "/" separator.
If I change the separator by doing os.sep = "/", I got an error later when the output csv file should be uploaded on dagshub, as the path containing the temporary file is not recognized anymore.

**Comment by sefirotha** [comment]
> I have the same issue. If i print os.sep, it will show "\" but the way pycaret handles the dagshub path is by using the "/" separator. If I change the separator by doing os.sep = "/", I got an error later when the output csv file should be uploaded on dagshub, as the path containing the temporary file is not recognized anymore.

The issue in the dagshub_logger.py:
line 65: owner=self.remote.split(os.sep)[-2]
line 66:name=self.remote.split(os.sep)[-1].replace(".mlflow", "")
os.sep should be replaced by "/" as it's what it expected when prompting the dagshub directory in the prompt command.

**Comment by timho102003** [comment]
Hi @DiegoCotacio and @sefirotha:
We are working on the fix. Thanks for reporting the bug!
