### ISSUE TITLE
[BUG]: Custom Cross-Validation (CV) not returning results

### ISSUE THREAD

**Issue by ddlatumalea** [pycaret/pycaret#3436]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I'm trying to use a custom cross-validator with Pycaret. However, this does not work as `compare_models` does not return any results. It looks like none of the models are being trained.

A reproducible example for both the functional and OOP API is provided.

This issue is also confirmed with a custom cross-validator that extends `_BaseKFold` from `sklearn.model_selection.split._BaseKFold`.

### Reproducible Example

```python
class UpsampleStratifiedKFold:
   """https://stackoverflow.com/questions/30040597/how-to-generate-a-custom-cross-validation-generator-in-scikit-learn"""
    def __init__(self, n_splits=3):
        self.n_splits = n_splits

    def split(self, X, y, groups=None):
        for rx, tx in StratifiedKFold(n_splits=self.n_splits).split(X,y):
            nix = np.where(y[rx]==0)[0]
            pix = np.where(y[rx]==1)[0]
            pixu = np.random.choice(pix, size=nix.shape[0], replace=True)
            ix = np.append(nix, pixu)
            rxm = rx[ix]
            yield rxm, tx

    def get_n_splits(self, X, y, groups=None):
        return self.n_splits

# functional API
from pycaret.classification import setup, compare_models
from sklearn.datasets import make_classification

X, y = make_classification()
data = pd.DataFrame(X)
data['label'] = y

cv = UpsampleStratifiedKFold()
setup(data=data, target='label', fold_strategy=cv)

compare_models()
# returns []

# OOP API
from pycaret.classification import ClassificationExperiment
from sklearn.datasets import make_classification

X, y = make_classification()
data = pd.DataFrame(X)
data['label'] = y

cv = UpsampleStratifiedKFold()
exp = ClassificationExperiment()
exp.setup(data=data, target='label', fold_strategy=cv)

exp.compare_models()
# returns []
```

### Expected Behavior

Expected behaviour would be an output with several models and their corresponding scores. It does work when **not** providing a custom cv.

### Actual Results

```python-traceback
[]
```

### Installed Versions

<details>
3.0.0
</details>

**Comment by tvdboom** [comment]
Hi. The problem here is in these lines
> nix = np.where(y[rx]==0)[0]
   pix = np.where(y[rx]==1)[0]

pycaret works with pandas objects (dataframe for X and series for y) instead of numpy arrays. Thus, using `y[rx]` will select the row in y with index rx, instead of the rx-th row. Use this instead

```
nix = np.where(y.iloc[rx]==0)[0]
pix = np.where(y.iloc[rx]==1)[0]
```
