### ISSUE TITLE
[INSTALL]: from pycaret.classification import *

### ISSUE THREAD

**Issue by Dpakkk** [pycaret/pycaret#3437]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Output exceeds the size limit. Open the full output data in a text e ... ---> 24 from pandas._typing import (      25     Axis,      26     FilePath,  ImportError: cannot import name 'FilePath' from 'pandas._typing' (/Users/bikashpokharel/opt/anaconda3/lib/python3.9/site-packages/pandas/_typing.pyditor --------------------------------------------------------------------------- ImportError                               Traceback (most recent call last) /var/folders/ck/22v0x0pj3rvchfgdwdpklf5h0000gn/T/ipykernel_15789/2548886149.py in        1 # data preparation ----> 2 from pycaret.classification import *       3 #from pycaret.classification import *       4 #s = setup(df, target = 'Churn', ignore_features = df[customerID])  ~/opt/anaconda3/lib/python3.9/site-packages/pycaret/classification/__init__.py in  ----> 1 from pycaret.classification.functional import (       2     add_metric,       3     automl,       4     blend_models,       5     calibrate_model,  ~/opt/anaconda3/lib/python3.9/site-packages/pycaret/classification/functional.py in        6 from joblib.memory import Memory       7  ----> 8 from pycaret.classification.oop import ClassificationExperiment       9 from pycaret.internal.parallel.parallel_backend import ParallelBackend      10 from pycaret.loggers.base_logger import BaseLogger  ~/opt/anaconda3/lib/python3.9/site-packages/pycaret/classification/oop.py in       14 from scipy.optimize import shgo      15  ...

### Installation Method

pip install

### pycaret Version

3.0.0

### Python Version

3.9.7

### Description

When I am importing classification from pycaret from this: pycaret.classification import *
Got an error
<img width="1123" alt="Screenshot 2023-03-27 at 10 31 25 AM" src="https://user-images.githubusercontent.com/38802452/227971364-190c88c3-a5a8-421e-8747-461e33f247ca.png">

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by ngupta23** [comment]
Please add all the version details here so we can check it out.

```
from pycaret import show_versions;
show_versions()
```

**Comment by Dpakkk** [comment]
Sure. Here are the versions:
<img width="618" alt="image" src="https://user-images.githubusercontent.com/38802452/227981928-66272d62-1a9c-43fc-814d-737e92de858c.png">

**Comment by ngupta23** [comment]
Thanks. Can you also paste the entire "original" error stack in text format here (from the import)? It only shows part of the stack in your original image. Thanks!

**Comment by Dpakkk** [comment]
It is 3.9.7
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/38802452/228581508-5602b3cc-8446-4c6f-848f-0db242e64f90.png">

**Comment by ngupta23** [comment]
My apologies. I meant pandas not python since the downgrade of pandas solved the issue.

**Comment by Dpakkk** [comment]
No worries. It is 1.5.2
