### ISSUE TITLE
[INSTALL]: Is Arules still available?

### ISSUE THREAD

**Issue by ometsci** [pycaret/pycaret#3439]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Linux-5.10.147+-x86_64-with-glibc2.31

### Installation Method

pip install

### pycaret Version

3.0.0

### Python Version

3.9

### Description

Using google colab. Is Arules no longer supported? 

----> 1 from pycaret.arules import*
      2 arules = setup(data = min, 
      3                     transaction_id = 'SampleNumber',
      4                     item_id = 'value') 

ModuleNotFoundError: No module named 'pycaret.arules'

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by ngupta23** [comment]
No, it was removed from 3.0.0. The last available pycaret version that has this is 2.3.10.
