### ISSUE TITLE
Classification - execution taking longer than normal

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#3442]
### Discussed in https://github.com/pycaret/pycaret/discussions/3441

<div type='discussions-op-text'>

<sup>Originally posted by **vahahn** March 28, 2023</sup>
Hello,

I have a fairly small-ish dataset (~6000 rows, 7 cols). I ran a script that I've been running for the past 3 months, but this time it's taking much longer than normal (used to take a couple of minutes). I have approx 1000 more rows of data than I did previously and I've read from a few posts that many are working with much larger datasets, so I'm assuming that I may be doing something wrong. 

If anyone can shed some light then that would be warmly appreciated!

This is what I am currently reading at the bottom
`Executing (1h 1m 36s) Cell navigate_next setup() navigate_next setup() navigate_next _prepare_dataset() navigate_next merge() navigate_next merge() navigate_next get_result() navigate_next _get_join_info() navigate_next join() navigate_next join() navigate_next _join_non_unique()`

**_Here's the script:_**

```
from pycaret.classification import *

clf1 = setup(cta_call, 
             target = 'cta_call', 
             log_experiment=True, 
             experiment_name='compare_models')
             feature_selection = True, 
             remove_multicollinearity = True)

best_model = compare_models()
print(best_model)
evaluate_model(best_model)
```

pycaret version: 3.0.0
google collab: 3.9.16

</div>

**Comment by ngupta23** [comment]
Few questions/suggestions.

1. Do you have DateTimeIndex in the dataframe?
2. Can you try disabling mlflow and checking?
3. Can you try disabling feature selection and checking?

Please report back with the findings so we can debug better. Otherwise, if you can share the data for us to reproduce the problem, it would be best.

**Comment by vahahn** [comment]
Thank you!

1. No DateTimeIndex.
2. Disabled and no success.
3. Disabled and no success.

The script I last ran looked like this: `clf1 = setup(cta_app, target = 'cta_app')`

Here's a portion of my data 
[cta_app.csv](https://github.com/pycaret/pycaret/files/11103250/cta_app.csv)

**Comment by Yard1** [comment]
@vahahn could you paste the output of `pycaret.show_versions`?

**Comment by vahahn** [comment]
Hi @Yard1,

Surprisingly, today I tried the original script without log_experiments and it worked! I don't know why I had the initial issue, but I can't replicate it. 

I don't have the original output for show_versions.

If the long lag time occurs again, then I will report back.

**Comment by Yard1** [comment]
Awesome! I'll close the issue for now, feel free to reopen if needed.
