### ISSUE TITLE
[BUG]: evaluate_model() Ipynb widget in the Decision Tree mode not displaying Tree due to Error.

### ISSUE THREAD

**Issue by Jogsterdgl** [pycaret/pycaret#3444]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

When using a fresh Google colab notebook i have encountered the Problem that i can not display the decision tree for the Decision Tree Classifier model. The problem occurs when using either evaluate_model() or plot_model() in the evaluation step. I have reproduced the bug with the code of the built-in diabetes set.

### Reproducible Example

```python
https://colab.research.google.com/drive/1aYVbveSmxyFt1usVspD0Hv5DYVNtAgS4?usp=sharing
```

### Expected Behavior

The tree is shown.

### Actual Results

```python-traceback
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

/usr/local/lib/python3.9/dist-packages/ipywidgets/widgets/interaction.py in update(self, *args)
    255                     value = widget.get_interact_value()
    256                     self.kwargs[widget._kwarg] = value
--> 257                 self.result = self.f(**self.kwargs)
    258                 show_inline_matplotlib_plots()
    259                 if self.auto_display and self.result is not None:

1 frames

/usr/local/lib/python3.9/dist-packages/pycaret/internal/pycaret_experiment/tabular_experiment.py in tree()
   1509                             i: class_name
   1510                             for i, class_name in enumerate(
-> 1511                                 get_label_encoder(self.pipeline).classes_
   1512                             )
   1513                         }

AttributeError: 'NoneType' object has no attribute 'classes_'
```

### Installed Versions

<details>
System:
    python: 3.9.16 (main, Dec  7 2022, 01:11:51)  [GCC 9.4.0]
executable: /usr/bin/python3
   machine: Linux-5.10.147+-x86_64-with-glibc2.31

PyCaret required dependencies:
                 pip: 22.0.4
          setuptools: 60.10.0
             pycaret: 3.0.0
             IPython: 7.34.0
          ipywidgets: 7.7.1
                tqdm: 4.64.1
               numpy: 1.22.4
              pandas: 1.4.4
              jinja2: 3.1.2
               scipy: 1.9.3
              joblib: 1.2.0
             sklearn: 1.2.2
                pyod: 1.0.9
            imblearn: 0.10.1
   category_encoders: 2.6.0
            lightgbm: 3.3.5
               numba: 0.56.4
            requests: 2.27.1
          matplotlib: 3.6.3
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.13.1
             kaleido: 0.2.1
         statsmodels: 0.13.5
              sktime: 0.16.1
               tbats: 1.1.2
            pmdarima: 2.0.3
              psutil: 5.9.4

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: 0.3.2
                umap: 0.5.3
    pandas_profiling: 3.6.6
  explainerdashboard: 0.4.2.1
             autoviz: 0.1.58
           fairlearn: 0.7.0
             xgboost: 1.7.4
            catboost: 1.1.1
              kmodes: 0.12.2
             mlxtend: 0.21.0
       statsforecast: 1.5.0
        tune_sklearn: 0.4.5
                 ray: 2.3.1
            hyperopt: 0.2.7
              optuna: 3.1.0
               skopt: 0.9.0
              mlflow: 1.30.0
              gradio: 3.23.0
             fastapi: 0.95.0
             uvicorn: 0.21.1
              m2cgen: 0.10.0
           evidently: 0.2.7
               fugue: 0.8.2
           streamlit: Not installed
             prophet: 1.1.2
</details>

**Comment by ngupta23** [comment]
Also see https://github.com/pycaret/pycaret/discussions/3421
