### ISSUE TITLE
[INSTALL]: sdist for v3.0.0

### ISSUE THREAD

**Issue by kaisen** [pycaret/pycaret#3453]
### Describe the feature you want to add to this project

There isn't an sdist on public pypi for v3.0.0 even though the previous versions have a corresponding sdist. Will there be one for v3.0.0?

### Describe your proposed solution

Upload the v3.0.0 sdist to public pypi

**Comment by moezali1** [comment]
@kaisen Thanks for your comment. Can you please share the use-case of sdist file despite that we already have a public github repo?

**Comment by moezali1** [comment]
@kaisen PyCaret is python-only package. There is no difference between wheel and source dist. If you are looking for source distribution you might just clone the repo from github.com/pycaret/pycaret.

**Comment by harper357** [comment]
Sorry for posting in a closed issue, but one use case is conda-forge's automation requires the source on pypi. Without it, the conda version will not get updated to v3.x.
