### ISSUE TITLE
[BUG]: ValueError occurs in tune_model of CatboostRegresser when use_gpu=True is set with optuna.

### ISSUE THREAD

**Issue by kyosuke0924** [pycaret/pycaret#3457]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

ValueError occurs in tune_model of CatboostRegresser when use_gpu=True is set  with optuna.

environment：win11(Home edition ver. 22H2)+WSL2(Ubuntu 22.04)+docker desctop(v4.17.0)
CPU:12th Gen Intel(R) Core(TM) i7-12700K 3.60 GHz
GPU:NVIDIA GeForce RTX 3090(Driver Version: 531.29)
RAM:32GB

### Reproducible Example

```python
#pycaret
from sklearn import datasets
data = datasets.load_diabetes(as_frame=True)

df_train=data.data.copy()
df_train['target'] = data.target

from pycaret.regression import *
conf = setup(data = df_train, target = 'target', preprocess=True,session_id=345,use_gpu=True) 
cbr = create_model('catboost')
tuned_cbr= tune_model(cbr,search_library='optuna')
```

### Expected Behavior

The tune_model should succeed as follows.

| Fold | MAE | MSE | RMSE | R2 | RMSLE | MAPE| 
| -- | -- | -- | -- | -- | -- | --
0|50.8788 | 3877.5936 | 62.2703 | 0.3461 | 0.4281 | 0.3931
1|56.2441 | 4478.5372 | 66.9219 | 0.3897 | 0.4787 | 0.4907
2|38.0593 | 1975.3151 | 44.4445 | 0.5633 | 0.3796 | 0.3732
3|43.7186 | 2990.2972 | 54.6836 | 0.4078 | 0.3997 | 0.3798
4|51.8235 | 4255.7882 | 65.2364 | 0.3629 | 0.4201 | 0.3687
5|47.5727 | 3362.1540 | 57.9841 | 0.3480 | 0.4957 | 0.5440
6|49.7989 | 3120.0468 | 55.8574 | 0.4779 | 0.3978 | 0.4050
7|48.9999 | 3237.1370 | 56.8958 | 0.4936 | 0.3810 | 0.3531
8|41.3521 | 2285.3568 | 47.8054 | 0.4504 | 0.4318 | 0.4504
9|50.4994 | 3301.2026 | 57.4561 | 0.2438 | 0.4592 | 0.4422
mean|47.8947 | 3288.3429 | 56.9556 | 0.4083 | 0.4272 | 0.4200
std|5.1261 | 745.3283 | 6.6639 | 0.0865 | 0.0380 | 0.0580

```
[I 2023-04-04 15:14:26,479] Searching the best hyperparameters using 309 samples...
[I 2023-04-04 15:14:55,645] Finished hyperparemeter search!
```

### Actual Results

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[16], line 11
      9 conf = setup(data = df_train, target = 'target', preprocess=True,session_id=345,use_gpu=True) 
     10 cbr = create_model('catboost')
---> 11 tuned_cbr= tune_model(cbr,search_library='optuna')

File /opt/miniconda3/envs/developer/lib/python3.8/site-packages/pycaret/utils/generic.py:965, in check_if_global_is_not_none.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    963     if globals_d[name] is None:
    964         raise ValueError(message)
--> 965 return func(*args, **kwargs)

File /opt/miniconda3/envs/developer/lib/python3.8/site-packages/pycaret/regression/functional.py:1208, in tune_model(estimator, fold, round, n_iter, custom_grid, optimize, custom_scorer, search_library, search_algorithm, early_stopping, early_stopping_max_iters, choose_better, fit_kwargs, groups, return_tuner, verbose, tuner_verbose, return_train_score, **kwargs)
   1015 @check_if_global_is_not_none(globals(), _CURRENT_EXPERIMENT_DECORATOR_DICT)
   1016 def tune_model(
   1017     estimator,
   (...)
   1035     **kwargs,
   1036 ):
   1038     """
   1039     This function tunes the hyperparameters of a given estimator. The output of
   1040     this function is a score grid with CV scores by fold of the best selected
   (...)
   1205 
   1206     """
-> 1208     return _CURRENT_EXPERIMENT.tune_model(
   1209         estimator=estimator,
   1210         fold=fold,
   1211         round=round,
   1212         n_iter=n_iter,
   1213         custom_grid=custom_grid,
   1214         optimize=optimize,
   1215         custom_scorer=custom_scorer,
   1216         search_library=search_library,
   1217         search_algorithm=search_algorithm,
   1218         early_stopping=early_stopping,
   1219         early_stopping_max_iters=early_stopping_max_iters,
   1220         choose_better=choose_better,
   1221         fit_kwargs=fit_kwargs,
   1222         groups=groups,
   1223         return_tuner=return_tuner,
   1224         verbose=verbose,
   1225         tuner_verbose=tuner_verbose,
   1226         return_train_score=return_train_score,
   1227         **kwargs,
   1228     )

File /opt/miniconda3/envs/developer/lib/python3.8/site-packages/pycaret/regression/oop.py:1511, in RegressionExperiment.tune_model(self, estimator, fold, round, n_iter, custom_grid, optimize, custom_scorer, search_library, search_algorithm, early_stopping, early_stopping_max_iters, choose_better, fit_kwargs, groups, return_tuner, verbose, tuner_verbose, return_train_score, **kwargs)
   1318 def tune_model(
   1319     self,
   1320     estimator,
   (...)
   1338     **kwargs,
   1339 ):
   1341     """
   1342     This function tunes the hyperparameters of a given estimator. The output of
   1343     this function is a score grid with CV scores by fold of the best selected
   (...)
   1508 
   1509     """
-> 1511     return super().tune_model(
   1512         estimator=estimator,
   1513         fold=fold,
   1514         round=round,
   1515         n_iter=n_iter,
   1516         custom_grid=custom_grid,
   1517         optimize=optimize,
   1518         custom_scorer=custom_scorer,
   1519         search_library=search_library,
   1520         search_algorithm=search_algorithm,
   1521         early_stopping=early_stopping,
   1522         early_stopping_max_iters=early_stopping_max_iters,
   1523         choose_better=choose_better,
   1524         fit_kwargs=fit_kwargs,
   1525         groups=groups,
   1526         return_tuner=return_tuner,
   1527         verbose=verbose,
   1528         tuner_verbose=tuner_verbose,
   1529         return_train_score=return_train_score,
   1530         **kwargs,
   1531     )

File /opt/miniconda3/envs/developer/lib/python3.8/site-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py:2663, in _SupervisedExperiment.tune_model(self, estimator, fold, round, n_iter, custom_grid, optimize, custom_scorer, search_library, search_algorithm, early_stopping, early_stopping_max_iters, choose_better, fit_kwargs, groups, return_tuner, verbose, tuner_verbose, return_train_score, **kwargs)
   2661             model_grid.fit(data_X, data_y, groups=groups, **fit_kwargs)
   2662 else:
-> 2663     model_grid.fit(data_X, data_y, groups=groups, **fit_kwargs)
   2664 best_params = model_grid.best_params_
   2665 self.logger.info(f"best_params: {best_params}")

File /opt/miniconda3/envs/developer/lib/python3.8/site-packages/optuna/integration/sklearn.py:831, in OptunaSearchCV.fit(self, X, y, groups, **fit_params)
    804 def fit(
    805     self,
    806     X: TwoDimArrayLikeType,
   (...)
    809     **fit_params: Any,
    810 ) -> "OptunaSearchCV":
    811     """Run fit with all sets of parameters.
    812 
    813     Args:
   (...)
    828         self.
    829     """
--> 831     self._check_params()
    833     random_state = check_random_state(self.random_state)
    834     max_samples = self.subsample

File /opt/miniconda3/envs/developer/lib/python3.8/site-packages/optuna/integration/sklearn.py:761, in OptunaSearchCV._check_params(self)
    759 for name, distribution in self.param_distributions.items():
    760     if not isinstance(distribution, distributions.BaseDistribution):
--> 761         raise ValueError("Value of {} must be a optuna distribution.".format(name))
    763 if self.enable_pruning and not hasattr(self.estimator, "partial_fit"):
    764     raise ValueError("estimator must support partial_fit.")

ValueError: Value of actual_estimator__depth must be a optuna distribution.
```

### Installed Versions
<details>
System:
    python: 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:46:39)  [GCC 10.4.0]
executable: /opt/miniconda3/envs/developer/bin/python
   machine: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.10

PyCaret required dependencies:
                 pip: 23.0.1
          setuptools: 60.10.0
             pycaret: 3.0.0
             IPython: 8.11.0
          ipywidgets: 8.0.5
                tqdm: 4.64.1
               numpy: 1.23.5
              pandas: 1.5.3
              jinja2: 3.1.2
               scipy: 1.9.3
              joblib: 1.2.0
             sklearn: 1.2.2
                pyod: 1.0.9
            imblearn: 0.10.1
   category_encoders: 2.6.0
            lightgbm: 3.3.5
               numba: 0.56.4
            requests: 2.28.2
          matplotlib: 3.6.3
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.13.1
             kaleido: 0.2.1
         statsmodels: 0.13.5
              sktime: 0.16.1
               tbats: 1.1.2
            pmdarima: 2.0.3
              psutil: 5.9.4

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: Not installed
                umap: 0.5.3
    pandas_profiling: 0.0.dev0
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
             xgboost: 1.6.2
            catboost: 1.1.1
              kmodes: 0.12.2
             mlxtend: 0.21.0
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: Not installed
              optuna: 3.1.0
               skopt: Not installed
              mlflow: 2.2.2
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: Not installed
           evidently: Not installed
               fugue: Not installed
           streamlit: Not installed
             prophet: Not installed
</details>

**Comment by kyosuke0924** [comment]
Wouldn't it be appropriate to modify it in this way?

https://github.com/pycaret/pycaret/blob/b4cf58ab8feb982e7b2639beee5ff2b9f686d3f7/pycaret/containers/models/regression.py#L1845-L1847

↓

```python
if use_gpu:
    tune_grid["depth"] = list(range(1, 9))
    tune_distributions["depth"] = IntUniformDistribution(1, 8)
```

**Comment by kyosuke0924** [comment]
Could someone please check my PR?

**Comment by Chanakan55991** [comment]
Can confirm this fixed it, the problem also exists with the classification file with the exact same solution, so maybe update your PR to also make a change to that

https://github.com/pycaret/pycaret/blob/b4cf58ab8feb982e7b2639beee5ff2b9f686d3f7/pycaret/containers/models/classification.py#L1467-L1469

**Comment by kyosuke0924** [comment]
@Chanakan55991 
Thank you for pointing this out. I detected a similar bug in the classifier and I have made the same modified as for the regressor.
