### ISSUE TITLE
[ENH]: Disable One-hot encoding

### ISSUE THREAD

**Issue by loschicosdeldato** [pycaret/pycaret#3460]
### Describe the feature you want to add to this project

Tree-based models dont required one-hot encoding and can affect the [performance and interpretability.](https://towardsdatascience.com/one-hot-encoding-is-making-your-tree-based-ensembles-worse-heres-why-d64b282b5769)

### Describe your proposed solution

Open the possibility to disable One-hot encoding in the preprocessing.

**Comment by ngupta23** [comment]
The problem, I think, is that we only have 1 preprocessing pipeline inside right now. Your recommendation will need the ability to have model-specific preprocessing pipelines. There is also caching of transformations going on inside which complicates things a bit.

@tvdboom and @Yard1 worked on this and will be in a better position to comment on whether this is easy to implement and maintain or not.

**Comment by tvdboom** [comment]
Onehot encoding can be disabled setting `max_encoding_ohe=0`, but this will shut it down for all models.

**Comment by loschicosdeldato** [comment]
Thanks!
