### ISSUE TITLE
using get_data and profile=True on a csv file

### ISSUE THREAD

**Issue by sandeepraizada** [pycaret/pycaret#347]
Hi, I like the get_data feature and using profile = True to review the data. However, this seems to only work on the datasets that are available. How an I get to use this on my own data? I tried relacing e.g. 'kiva' with the path to the file and by downloading the file and providing the local path to it too, but I get an error. I am using Google Colab. Looks lik a feature that is not yet supported?

**Comment by pycaret** [comment]
@sandeepraizada 

**get_data** function is only for internal repository. If you want to check profile on your data. **setup** function in each module as profile parameter. For example:

data = pd.read_csv('your-data-here.csv')
s = setup(data, target = 'name-of-target', profile = True)

If this helps. Please close this issue.
