### ISSUE TITLE
MLflow Projects Run Configuration in def setup?

### ISSUE THREAD

**Issue by eedeleon** [pycaret/pycaret#349]
Are there plans to support MLflow Projects Run and associated configurations for running Model creation in separate processes during compare_models?

This would help me scale up the hyper parameter search.

For my scenario configuring the backend and passing the backend config would work.

https://mlflow.org/docs/latest/projects.html#running-projects

**Comment by pycaret** [comment]
@eedeleon Can you please add some example. It will help me create a user story for next sprint. I haven't worked with MLFlow projects before but it looks interesting to me.

**Comment by pycaret** [comment]
@eedeleon Hi. Are you still interested in proposing this enhancement?
