### ISSUE TITLE
[BUG]: deprecated distribution error using optuna + catboost

### ISSUE THREAD

**Issue by verajosemanuel** [pycaret/pycaret#3490]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

getting regression results from Catboost Using Pycaret gives me an error when using optuna library as hyperparameter tuning.

Reproducible Example below

### Reproducible Example

```python
#pycaret
from sklearn import datasets
data = datasets.load_diabetes(as_frame=True)

df_train=data.data.copy()
df_train['target'] = data.target

from pycaret.regression import *
conf = setup(data = df_train, target = 'target', preprocess=True,session_id=123) 
cbr = create_model('catboost')
tuned_cbr= tune_model(cbr,search_library='optuna')
```
```


### Expected Behavior

model is created with no issue

### Actual Results

```python-traceback
`ValueError: Deprecated distribution is specified in `actual_estimator__eta` of param_distributions. Rejecting this because it may cause unexpected behavior. Please use new distributions such as FloatDistribution etc.`
```

### Installed Versions

<details>
Replace this line with the output of the version code above.
</details>

**Comment by Yard1** [comment]
Hi, this has been fixed in 3.0.0. Please ensure your PyCaret version is up to date.
