### ISSUE TITLE
[BUG]: feature_selection=True & compare_models() return lightgbm with dummy regressor scores

### ISSUE THREAD

**Issue by hakan-77** [pycaret/pycaret#3493]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

setup
feature_selection=True 
compare_models() 

returns a dummy regressor and a lightgbm and their scores are exactly the same.

### Reproducible Example

```python
from pycaret.regression import RegressionExperiment
from pycaret.datasets import get_data

data = get_data('ice_cream')

exp = RegressionExperiment()

exp.setup(data, target="Revenue", feature_selection=True)
model = exp.compare_models()
results = exp.pull()

display(results)
```

### Expected Behavior

Multiple models and their accurate scores

### Actual Results

```python-traceback
compare_models() return lightgbm and dummy regressor and their scores are exactly the same 

Model       MAE         MSE      RMSE  

lightgbm  Light Gradient Boosting Machine  
dummy                     Dummy Regressor  

140.7582  31129.5727  174.4564   
140.7582  31129.5741  174.4564   

              R2   RMSLE    MAPE  TT (Sec)  

lightgbm
dummy
 
-0.0404  0.4448  0.5652     0.025  
-0.0404  0.4448  0.5652     0.026
```

### Installed Versions

<details>
System:
    python: 3.8.16 (default, Mar  1 2023, 21:19:10)  [Clang 14.0.6 ]
executable: /Users/hakan/.conda/envs/myenv/bin/python3
   machine: macOS-10.16-x86_64-i386-64bit

PyCaret required dependencies:
                 pip: 23.0.1
          setuptools: 66.0.0
             pycaret: 3.0.0
             IPython: 8.12.0
          ipywidgets: 8.0.6
                tqdm: 4.65.0
               numpy: 1.23.5
              pandas: 1.5.3
              jinja2: 3.1.2
               scipy: 1.9.1
              joblib: 1.2.0
             sklearn: 1.2.2
                pyod: 1.0.9
            imblearn: 0.10.1
   category_encoders: 2.6.0
            lightgbm: 3.3.5
               numba: 0.56.4
            requests: 2.28.2
          matplotlib: 3.7.1
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.14.1
             kaleido: 0.2.1
         statsmodels: 0.13.5
              sktime: 0.17.0
               tbats: 1.1.3
            pmdarima: 2.0.3
              psutil: 5.9.5

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: 0.3.2
                umap: Not installed
    pandas_profiling: Not installed
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: 0.8.0
             xgboost: 1.7.5
            catboost: 1.1.1
              kmodes: Not installed
             mlxtend: Not installed
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: Not installed
              optuna: Not installed
               skopt: Not installed
              mlflow: 2.3.0
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: Not installed
           evidently: Not installed
               fugue: Not installed
           streamlit: Not installed
             prophet: Not installed
</details>

**Comment by moezali1** [comment]
@hakan-77 Can you please upload the dataset and notebook so that we can reproduce the issue? Thanks for reporting.

**Comment by hakan-77** [comment]
@moezali1 please see attached. Thank you. 

[ice_cream.csv](https://github.com/pycaret/pycaret/files/11413676/ice_cream.csv)

**Comment by moezali1** [comment]
@tvdboom This issue is only happening when `feature_selection=True` in the `setup`. When it is False, it returns all models as expected.

Logs when its failed is attached. See towards the end.

[logs (3).log](https://github.com/pycaret/pycaret/files/11465453/logs.3.log)

**Comment by hakan-77** [comment]
@moezali1 @tvdboom  FYI- Adding the below highly correlated features to the dataset before setup() did not solve the issue. On the other hand, I can confirm that feature_selection=True worked for another dataset just fine, e.g. boston house. 

```python
data["Temp2"] = data["Temperature"] * 2
data["Temp3"] = data["Temperature"] * 4
data["Temp4"] = data["Temperature"] * 8
```

**Comment by tvdboom** [comment]
The issue is because the defaultg value of the parameter `n_features_to_select` is 0.2, Which means: select 20% of the initial features. If you have less than 5 features, it will remove them all because it's rounded to zero. Try using `n_features_to_select=2`, with the dataset with 4 featurs and you'l' see it works. I would argue that using feature selection on a  dataset with less than 5 features makes no sense.

**Comment by ngupta23** [comment]
@tvdboom Can we raise a `ValueError` from pycaret in such cases? It may be easier for users to understand what is going on internally and take corrective action. Will also save developers time to debug :)

**Comment by hakan-77** [comment]
@tvdboom I have to disagree. In the example I give, should the model use temp, temp2, temp3 and temp4 although they are highly correlated? 
@ngupta23 I would rather prefer setup() ignore the request, and optionally print a warning, instead of raising a ValueError.

**Comment by ngupta23** [comment]
The value error should be printed when you are left with 0 features. That is a true error and not a warning.

**Comment by hakan-77** [comment]
@ngupta23 I see what you are saying. What I mean is, in this case setup() should avoid selecting features, print a warning "we do not select features if you have less than 5 features" and continue running.

**Comment by tvdboom** [comment]
@hakan-77 You can set the `n_features_to_select` parameter in setup to determine the number of features you want to keep. Just use that parameter instead of implementing logic depending on the  number of features

**Comment by hakan-77** [comment]
@tvdboom We are using Pycaret to help others, and many of our users will not be able to know the correct number of features to use. 

The below is from Pycaret documentation, and if we take it with its face value, it suggests features be selected by importance score, which is exactly what we need.

feature_selection: When set to True, a subset of features is selected based on a feature importance score determined by feature_selection_estimator.

Maybe the problem here is that we don't use how n_features_to_select correctly. For a dataset with 100 features, if we set n_features_to_select=100, does that mean we eliminate feature selection all together? Or does that mean we wil lget 100 or less selected features?

**Comment by tvdboom** [comment]
> The below is from Pycaret documentation, and if we take it with its face value, it suggests features are selected by importance score, which is exactly what we need.

This is correct. Features are selected by importance, and the number of features selected is given by the `n_features_to_select` parameter. You can either set an integer to select the exact number of features or a float to select a fraction of the initial features. So, if you don't know beforehand how many features to select, use the float

> For a dataset with 100 features, if we set n_features_to_select=100, does that mean we eliminate feature selection all together?

In this case you will perform feature selection and select all 100 features to remain, so that doesn't make sense. If you don;t want to use feature selection, just use `feature_selection=False`. 

> Or does that mean we will get 100 or less selected features?

The number of features you get is determined by `n_features_to_select`, as described before

**Comment by hakan-77** [comment]
@tvdboom in this case current code is working as designed. I'm closing the issue.  I can also confirm that by if n_features_to_select is set, the code will work, scores are correct etc.
