### ISSUE TITLE
Compare Models to return more than 1 model

### ISSUE THREAD

**Issue by Alex-Malainic** [pycaret/pycaret#3499]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I am using Python 3.9.13 and just installed pycaret version 3.0.0. My issue is simple: when using the regression module, compare_models() does not return the list of fitted estimators and their scores like it did previously, instead it returns one estimator (I assume the best one?). 

I've attached below the reproducible example right from the docs, it's the same behaviour. 

### Reproducible Example

```python
from pycaret.datasets import get_data
data = get_data('insurance')

s = setup (data, target = 'charges')

compare_models()
```

### Expected Behavior

The expected behaviour of compare_models should be the previous table with fitted estimators and their scores.

### Actual Results

```python-traceback
![models](https://user-images.githubusercontent.com/50654936/233735960-781f1ac6-f34e-4296-84d0-cd0c7248d277.jpg)
```

### Installed Versions

<details>
Version 3.0.0
</details>

**Comment by ngupta23** [comment]
compare model always returned the best model by default (even in older versions). It also displayed the table of all models and metrics, but returned only the best one by default.

**Comment by Alex-Malainic** [comment]
Ok, but the parameter 'n_select' doesn't solve anything. It returned the table of all models, and now it doesn't anymore. Can you take a look at this?

**Comment by ngupta23** [comment]
If you are using VSCode notebook, there are bugs in their latest implementation. Try in a standalone notebook or google colab. We don't see any issues with the code and everything shows up fine.
