### ISSUE TITLE
[DOC]: Not clear why predict_model is not working.

### ISSUE THREAD

**Issue by jbrepogmailcom** [pycaret/pycaret#3502]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://pycaret.gitbook.io/docs/get-started/functions/deploy#unseen-data-predictions

### Documentation problem

Hello, I am trying to estimate numbers. I trained model with compare_models and I received "NaiveForecaster(strategy='mean')"

I then created new dataset and I am trying to get estimates with predict_model(model, data=new_data). I get error "TypeError: predict_model() got an unexpected keyword argument 'data'"

I cannot find explanation why the example in documentation is working ( https://pycaret.gitbook.io/docs/get-started/functions/deploy#unseen-data-predictions ) and why my case throws error.

Can someone help please? Thanks

### Suggested fix for documentation

describe when data keyword argument is invalid in predict_model and how to fix it.

**Comment by ngupta23** [comment]
What module are you using for your code? Can you paste your complete code?
