### ISSUE TITLE
[INSTALL]: Issue installing pycaret 2.3.10 AttributeError: 'Styler' object has no attribute 'set_precision'

### ISSUE THREAD

**Issue by sorenwacker** [pycaret/pycaret#3503]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Linux-4.18.0-425.10.1.el8_7.x86_64-x86_64-with-glibc2.31

### Installation Method

conda install

### pycaret Version

2.3.10

### Python Version

Python 3.9.16

### Description

I want to create a pycaret 2 environment to run some comparisons with version 3. However, I am running in all sorts of dependencies issues. 

    conda create -n pycaret=2.3.10 

for example installs the wrong numpy, and scikit-learn versions. After trying to fix this manually, I am stuck with something I don't know where it comes from:

```

File /bulk/LSARP/envs/conda/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py:3316, in create_model_supervised(estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, verbose, system, X_train_data, y_train_data, metrics, experiment_custom_tags, add_to_model_list, probability_threshold, display, return_train_score, **kwargs)
   3312     indices = ["Mean"]
   3313 model_results = color_df(
   3314     model_results, "yellow", indices, axis=1
   3315 )
-> 3316 model_results = model_results.set_precision(round)
   3318 # end runtime
   3319 runtime_end = time.time()

AttributeError: 'Styler' object has no attribute 'set_precision'
```

Does anybody have a pip command or conda command with all the necessary dependencies specified?

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by sorenwacker** [comment]
conda install -c conda-forge pycaret pip 'numpy<1.24' 'scipy<1.9'

Then :
```
from pycaret.classification import *

setup(data, 
          target=target, 
          categorical_features=categorical_features, 
          numeric_features=numeric_features,
          log_experiment = True, 
          experiment_name = 'OUTCOME-ThirtyDay_Death',
          silent=True,
         )

model = create_model('et', fold=3)
```

This runs until 'finalizing model' and throws:

```
ile /bulk/LSARP/envs/conda/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py:3316, in create_model_supervised(estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, verbose, system, X_train_data, y_train_data, metrics, experiment_custom_tags, add_to_model_list, probability_threshold, display, return_train_score, **kwargs)
   3312     indices = ["Mean"]
   3313 model_results = color_df(
   3314     model_results, "yellow", indices, axis=1
   3315 )
-> 3316 model_results = model_results.set_precision(round)
   3318 # end runtime
   3319 runtime_end = time.time()

AttributeError: 'Styler' object has no attribute 'set_precision'
```

**Comment by sorenwacker** [comment]
This is an incompatibility with pandas 2. 

    conda create -n pycaret2 -c conda-forge pycaret=2.3.10 pip 'numpy<1.24' 'scipy<1.9' 'pandas<2.0'
    
fixed this.

**Comment by ngupta23** [comment]
@sorenwacker - Can we close this issue?

**Comment by sorenwacker** [comment]
I guess so, it would be good to update e.g. the conda recipe to install the correct versions though.
