### ISSUE TITLE
[BUG]: sktime 0.17.2 has deprecations that cause issues

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#3523]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

https://github.com/pycaret/pycaret/actions/runs/4840258415/jobs/8625788825

![image](https://user-images.githubusercontent.com/33585645/235366366-4b7009ed-c2ac-4561-be2f-f8de519d2114.png)

### Reproducible Example

```python
Unit tests from Github
```

### Expected Behavior

Should work with sktime 0.17.2 and above.

### Actual Results

```python-traceback
See image above
```

### Installed Versions

<details>
3.0.1 (development)
</details>

**Comment by silva-celso** [comment]
@ngupta23 I've been receiving some weird errors in my code for a time series analysis since yesterday, that weren't happening last week. I think this might be it. If I force install a version of sktime before the 0.17.2, should it be enough to prevent the bug you reported?

**Comment by ngupta23** [comment]
> @ngupta23 I've been receiving some weird errors in my code for a time series analysis since yesterday, that weren't happening last week. I think this might be it. If I force install a version of sktime before the 0.17.2, should it be enough to prevent the bug you reported?

Please file a separate issue with the error and reproducible example so we can understand the root cause and potentially suggest a fix.
