### ISSUE TITLE
[DOC] High cardinality features in 3.0.0

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#3528]
### Discussed in https://github.com/pycaret/pycaret/discussions/3527

<div type='discussions-op-text'>

<sup>Originally posted by **TashowarTanzim** May  3, 2023</sup>
In the previous version of pycaret (2.3.10), I was able to specify some of my highly cardinal features (i.e. categorical features with a lot of levels) within the setup() function with the parameter :"high_cardinality_features = [....]". However, I get an argument error with this parameter while I try to use it in an environment with the latest version of pycaret (version 3.0). Any idea what has changed, and how exactly can I prevent one-hot encoding of highly cardinal features. I could not find anything in the documentation of Pycaret 3.0</div>

**Comment by tvdboom** [comment]
You can prevent one-hot encoding of high cardianlity features using the parameter:

```
max_encoding_ohe: int, default = 25
            Categorical columns with `max_encoding_ohe` or less unique values are
            encoded using OneHotEncoding. If more, the `encoding_method` estimator
            is used. Note that columns with exactly two classes are always encoded
            ordinally. Set to below 0 to always use OneHotEncoding.
```

**Comment by TashowarTanzim** [comment]
Hello, thanks for the reply. I also saw that there is the parameter "encoding_method: category-encoders estimator, default = None", which specifies the encoding method I can apply to my high cardinal features. If nothing is specified, documentation says that the LeaveOneOut encoder will be used by default. Can you please tell me what other encoding methods are availabe to be used (like frequency encoding, helmert encoding, etc....) in Pycaret 3.0? And how do I specify the other encoder methods in this parameter within the setup() function? I couldn't find such a list, neither an example of use anywhere. Thanks a lot!!

**Comment by tvdboom** [comment]
You can add an instance of any encoding class from the [`category-encoders`](https://contrib.scikit-learn.org/category_encoders/) library. Not all are tested so there's no guarantee all of them will work though.
