### ISSUE TITLE
Reducing risk for data leakage

### ISSUE THREAD

**Issue by sparvaneh** [pycaret/pycaret#353]
It sees that pre-processing (e.g. imputation) is done before splitting data to train and test. Current workflow increase risk of data leakage as mean/median of the whole dataset will be used for imputation while in real application only mean/median of training set should be used for imputation. 
Easy solution could be doing data split first and then pre-process/prepare data.

As another suggestion, separation of creating train/test data from setup under a separate module in the future versions could make it easier to use externally provided training and test sets.

**Comment by pycaret** [comment]
@sparvaneh Thanks for suggestion. Adding **enhancement** tag for now.

**Comment by Yard1** [comment]
I created a PR for this, https://github.com/pycaret/pycaret/pull/360. In addition, some code has been refactored for easier maintenance (identical code blocks in if elses have been moved outside).

**Comment by pycaret** [comment]
@Yard1 Can you submit a separate PR just for the split change?

**Comment by Yard1** [comment]
I'll redo this PR @pycaret

**Comment by pycaret** [comment]
@Yard1 As discussed, we will hold-on for this one for `2.1` release and give some thought to fix it during refactoring.

**Comment by pycaret** [comment]
## Issue parked for `pycaret==2.2`. Assigned to @Yard1 

### Please do not work on this issue.

**Comment by pycaret** [comment]
@sparvaneh 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
