### ISSUE TITLE
[ENH]: EOL for python 3.7

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#3539]
### Describe the feature you want to add to this project

Should we drop support for python 3.7 since it will be EOL soon.

![image](https://user-images.githubusercontent.com/33585645/236889451-24df9dcb-5516-4710-bda3-942e925aee75.png)

### Describe your proposed solution

Drop support for python 3.7 in pycaret 3.0.1 release?

### Describe alternatives you've considered, if relevant

Wait till 3.7 is officially EOL to stop supporting.

**Comment by ngupta23** [comment]
> Is there a reason to drop it? Like is it preventing us from doing other stuff?

Just that most libraries will stop supporting 3.7 (or have already done) and when we include 3.11 for pycaret, it will need extra compute and run time on the CI GitHub tests.

**Comment by moezali1** [comment]
What are the chances that things will just stop working on Python 3.7?

**Comment by tvdboom** [comment]
let's drop support at v3.0.2. @moezali1 Changes are increasingly higher. the newest versions of sklearn no longer support 3.7 for example, so right now we have to be compatible with the latest version and the latest supporting 3.7 version. this is bound to give issues sooner rather than later

**Comment by ngupta23** [comment]
pycaret 3.1.0 released where python 3.7 was deprecated.
