### ISSUE TITLE
Feature Suggestion: Group k-Fold

### ISSUE THREAD

**Issue by clgarciga** [pycaret/pycaret#354]
Hello, I would like to suggest adding sklearn.model_selection.GroupKFold as a CV option in compare_models and related pycaret functionality and, along the same lines, sklearn.model_selection.GroupShuffleSplit for train/test splitting in pycaret setup.

**Comment by vmasrani** [comment]
+1! I have to write some awkward outer loops to address this - GroupKFold would be very helpful :)

**Comment by pycaret** [comment]
# Open for contribution now

**Comment by pycaret** [comment]
will be handled through custom_splitter param.

**Comment by pycaret** [comment]
@clgarciga 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
