### ISSUE TITLE
[ENH]: Scikit-Learn 1.3 support

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#3540]
### Describe the feature you want to add to this project

Scikit-Learn 1.3 support

### Describe your proposed solution

we should start preparing pycaret for when scikit-learn 1.3 arrives.
So when scikit-learn 1.3 is released, pycaret already has support for scikit-learn 1.3.

### Additional context

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 3
      1 import mariadb
      2 import pandas as pd
----> 3 from pycaret.classification import *

File ~\anaconda3\lib\site-packages\pycaret\classification\__init__.py:1
----> 1 from pycaret.classification.functional import (
      2     add_metric,
      3     automl,
      4     blend_models,
      5     calibrate_model,
      6     check_drift,
      7     check_fairness,
      8     compare_models,
      9     convert_model,
     10     create_api,
     11     create_app,
     12     create_docker,
     13     create_model,
     14     dashboard,
     15     deep_check,
     16     deploy_model,
     17     eda,
     18     ensemble_model,
     19     evaluate_model,
     20     finalize_model,
     21     get_allowed_engines,
     22     get_config,
     23     get_current_experiment,
     24     get_engine,
     25     get_leaderboard,
     26     get_logs,
     27     get_metrics,
     28     interpret_model,
     29     load_experiment,
     30     load_model,
     31     models,
     32     optimize_threshold,
     33     plot_model,
     34     predict_model,
     35     pull,
     36     remove_metric,
     37     save_experiment,
     38     save_model,
     39     set_config,
     40     set_current_experiment,
     41     setup,
     42     stack_models,
     43     tune_model,
     44 )
     45 from pycaret.classification.oop import ClassificationExperiment
     47 __all__ = [
     48     "ClassificationExperiment",
     49     "setup",
   (...)
     90     "check_drift",
     91 ]

File ~\anaconda3\lib\site-packages\pycaret\classification\functional.py:8
      5 import pandas as pd
      6 from joblib.memory import Memory
----> 8 from pycaret.classification.oop import ClassificationExperiment
      9 from pycaret.internal.parallel.parallel_backend import ParallelBackend
     10 from pycaret.loggers.base_logger import BaseLogger

File ~\anaconda3\lib\site-packages\pycaret\classification\oop.py:17
     14 from scipy.optimize import shgo
     16 from pycaret.containers.metrics import get_all_class_metric_containers
---> 17 from pycaret.containers.models import get_all_class_model_containers
     18 from pycaret.containers.models.classification import (
     19     ALL_ALLOWED_ENGINES,
     20     get_container_default_engines,
     21 )
     22 from pycaret.internal.display import CommonDisplay

File ~\anaconda3\lib\site-packages\pycaret\containers\models\__init__.py:1
----> 1 from .anomaly import get_all_model_containers as get_all_anomaly_model_containers
      2 from .base_model import ModelContainer
      3 from .classification import get_all_model_containers as get_all_class_model_containers

File ~\anaconda3\lib\site-packages\pycaret\containers\models\anomaly.py:17
     15 import pycaret.containers.base_container
     16 import pycaret.internal.cuml_wrappers
---> 17 from pycaret.containers.models.base_model import ModelContainer
     18 from pycaret.internal.distributions import Distribution
     19 from pycaret.utils.generic import get_logger, param_grid_to_lists

File ~\anaconda3\lib\site-packages\pycaret\containers\models\base_model.py:9
      7 from pycaret.containers.base_container import BaseContainer
      8 from pycaret.internal.distributions import CategoricalDistribution
----> 9 from pycaret.internal.pycaret_experiment.pycaret_experiment import _PyCaretExperiment
     10 from pycaret.utils.generic import get_allowed_engines, get_logger
     13 class ModelContainer(BaseContainer):

File ~\anaconda3\lib\site-packages\pycaret\internal\pycaret_experiment\pycaret_experiment.py:12
     10 import pycaret.internal.patches.sklearn
     11 import pycaret.internal.patches.yellowbrick
---> 12 import pycaret.internal.persistence
     13 from pycaret import show_versions
     14 from pycaret.internal.logging import get_logger

File ~\anaconda3\lib\site-packages\pycaret\internal\persistence.py:13
     11 from pycaret.utils._dependencies import _check_soft_dependencies
     12 from pycaret.utils.generic import MLUsecase, get_logger
---> 13 from pycaret.utils.time_series.forecasting.pipeline import _add_model_to_pipeline
     16 def deploy_model(
     17     model, model_name: str, authentication: dict, platform: str = "aws", prep_pipe_=None
     18 ):
     19     """
     20     (In Preview)
     21 
   (...)
    101 
    102     """

File ~\anaconda3\lib\site-packages\pycaret\utils\time_series\forecasting\pipeline.py:6
      4 import pandas as pd
      5 from sktime.forecasting.base import BaseForecaster
----> 6 from sktime.forecasting.compose import ForecastingPipeline
      7 from sktime.transformations.compose import TransformerPipeline
      8 from sktime.transformations.series.impute import Imputer

File ~\anaconda3\lib\site-packages\sktime\forecasting\compose\__init__.py:47
     40 from sktime.forecasting.compose._multiplexer import MultiplexForecaster
     41 from sktime.forecasting.compose._pipeline import (
     42     ForecastingPipeline,
     43     ForecastX,
     44     Permute,
     45     TransformedTargetForecaster,
     46 )
---> 47 from sktime.forecasting.compose._reduce import (
     48     DirectTabularRegressionForecaster,
     49     DirectTimeSeriesRegressionForecaster,
     50     DirRecTabularRegressionForecaster,
     51     DirRecTimeSeriesRegressionForecaster,
     52     MultioutputTabularRegressionForecaster,
     53     MultioutputTimeSeriesRegressionForecaster,
     54     RecursiveTabularRegressionForecaster,
     55     RecursiveTimeSeriesRegressionForecaster,
     56     make_reduction,
     57 )
     58 from sktime.forecasting.compose._stack import StackingForecaster

File ~\anaconda3\lib\site-packages\sktime\forecasting\compose\_reduce.py:42
     40 from sktime.forecasting.base._sktime import _BaseWindowForecaster
     41 from sktime.regression.base import BaseRegressor
---> 42 from sktime.transformations.compose import FeatureUnion
     43 from sktime.transformations.series.summarize import WindowSummarizer
     44 from sktime.utils.datetime import _shift

File ~\anaconda3\lib\site-packages\sktime\transformations\compose\__init__.py:5
      2 """Meta-transformers for building composite transformers."""
      3 # copyright: sktime developers, BSD-3-Clause License (see LICENSE file)
----> 5 from sktime.transformations.compose._column import (
      6     ColumnEnsembleTransformer,
      7     ColumnwiseTransformer,
      8 )
      9 from sktime.transformations.compose._featureunion import FeatureUnion
     10 from sktime.transformations.compose._fitintransform import FitInTransform

File ~\anaconda3\lib\site-packages\sktime\transformations\compose\_column.py:9
      6 __all__ = ["ColumnwiseTransformer"]
      8 import pandas as pd
----> 9 from sklearn.utils.metaestimators import if_delegate_has_method
     11 from sktime.base._meta import _ColumnEstimator, _HeterogenousMetaEstimator
     12 from sktime.transformations.base import BaseTransformer

ImportError: cannot import name 'if_delegate_has_method' from 'sklearn.utils.metaestimators' (C:\Users\celes\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py)

**Comment by celestinoxp** [comment]
more information for the context of this issue:

I asked the sktime team to support scikit-learn before the release so that when the release comes, everything works fine, as for the sktime side, it looks like it's taken care of.

Now the problem is another one, I hope someone has the time and patience to try to help, even if it involves third-party packages, we can encourage them to update the code, as I did with the sktime team.

pycaret now returns this error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 9
      6 # Definir a opção para mostrar todas as colunas
      7 pd.set_option('display.max_columns', None)
----> 9 from pycaret.classification import *

File ~\anaconda3\lib\site-packages\pycaret\classification\__init__.py:1
----> 1 from pycaret.classification.functional import (
      2     add_metric,
      3     automl,
      4     blend_models,
      5     calibrate_model,
      6     check_drift,
      7     check_fairness,
      8     compare_models,
      9     convert_model,
     10     create_api,
     11     create_app,
     12     create_docker,
     13     create_model,
     14     dashboard,
     15     deep_check,
     16     deploy_model,
     17     eda,
     18     ensemble_model,
     19     evaluate_model,
     20     finalize_model,
     21     get_allowed_engines,
     22     get_config,
     23     get_current_experiment,
     24     get_engine,
     25     get_leaderboard,
     26     get_logs,
     27     get_metrics,
     28     interpret_model,
     29     load_experiment,
     30     load_model,
     31     models,
     32     optimize_threshold,
     33     plot_model,
     34     predict_model,
     35     pull,
     36     remove_metric,
     37     save_experiment,
     38     save_model,
     39     set_config,
     40     set_current_experiment,
     41     setup,
     42     stack_models,
     43     tune_model,
     44 )
     45 from pycaret.classification.oop import ClassificationExperiment
     47 __all__ = [
     48     "ClassificationExperiment",
     49     "setup",
   (...)
     90     "check_drift",
     91 ]

File ~\anaconda3\lib\site-packages\pycaret\classification\functional.py:8
      5 import pandas as pd
      6 from joblib.memory import Memory
----> 8 from pycaret.classification.oop import ClassificationExperiment
      9 from pycaret.internal.parallel.parallel_backend import ParallelBackend
     10 from pycaret.loggers.base_logger import BaseLogger

File ~\anaconda3\lib\site-packages\pycaret\classification\oop.py:29
     24 from pycaret.internal.meta_estimators import (
     25     CustomProbabilityThresholdClassifier,
     26     get_estimator_from_meta_estimator,
     27 )
     28 from pycaret.internal.parallel.parallel_backend import ParallelBackend
---> 29 from pycaret.internal.pipeline import Pipeline as InternalPipeline
     30 from pycaret.internal.preprocess.preprocessor import Preprocessor
     31 from pycaret.internal.pycaret_experiment.non_ts_supervised_experiment import (
     32     _NonTSSupervisedExperiment,
     33 )

File ~\anaconda3\lib\site-packages\pycaret\internal\pipeline.py:16
     13 from copy import deepcopy
     14 from inspect import signature
---> 16 import imblearn.pipeline
     17 import sklearn.pipeline
     18 from sklearn.base import clone

File ~\anaconda3\lib\site-packages\imblearn\__init__.py:52
     48     sys.stderr.write("Partial import of imblearn during the build process.\n")
     49     # We are not importing the rest of scikit-learn during the build
     50     # process, as it may not be compiled yet
     51 else:
---> 52     from . import (
     53         combine,
     54         ensemble,
     55         exceptions,
     56         metrics,
     57         over_sampling,
     58         pipeline,
     59         tensorflow,
     60         under_sampling,
     61         utils,
     62     )
     63     from ._version import __version__
     64     from .base import FunctionSampler

File ~\anaconda3\lib\site-packages\imblearn\combine\__init__.py:5
      1 """The :mod:`imblearn.combine` provides methods which combine
      2 over-sampling and under-sampling.
      3 """
----> 5 from ._smote_enn import SMOTEENN
      6 from ._smote_tomek import SMOTETomek
      8 __all__ = ["SMOTEENN", "SMOTETomek"]

File ~\anaconda3\lib\site-packages\imblearn\combine\_smote_enn.py:12
      9 from sklearn.base import clone
     10 from sklearn.utils import check_X_y
---> 12 from ..base import BaseSampler
     13 from ..over_sampling import SMOTE
     14 from ..over_sampling.base import BaseOverSampler

File ~\anaconda3\lib\site-packages\imblearn\base.py:21
     18 from sklearn.utils.multiclass import check_classification_targets
     20 from .utils import check_sampling_strategy, check_target_type
---> 21 from .utils._param_validation import validate_parameter_constraints
     22 from .utils._validation import ArraysTransformer
     25 class SamplerMixin(BaseEstimator, metaclass=ABCMeta):

File ~\anaconda3\lib\site-packages\imblearn\utils\_param_validation.py:908
    906 from sklearn.utils._param_validation import generate_valid_param  # noqa
    907 from sklearn.utils._param_validation import validate_parameter_constraints  # noqa
--> 908 from sklearn.utils._param_validation import (
    909     HasMethods,
    910     Hidden,
    911     Interval,
    912     Options,
    913     StrOptions,
    914     _ArrayLikes,
    915     _Booleans,
    916     _Callables,
    917     _CVObjects,
    918     _InstancesOf,
    919     _IterablesNotString,
    920     _MissingValues,
    921     _NoneConstraint,
    922     _PandasNAConstraint,
    923     _RandomStates,
    924     _SparseMatrices,
    925     _VerboseHelper,
    926     make_constraint,
    927     validate_params,
    928 )

ImportError: cannot import name '_MissingValues' from 'sklearn.utils._param_validation' (C:\Users\celes\anaconda3\lib\site-packages\sklearn\utils\_param_validation.py)

**Comment by ngupta23** [comment]
@Yard1 - May need to pin sklearn to < 1.3 until this is taken care of.

**Comment by celestinoxp** [comment]
imbalanced-learn solved the problem
