### ISSUE TITLE
[BUG]: plot_model displays empty plot  

### ISSUE THREAD

**Issue by imadarsh1001** [pycaret/pycaret#3541]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I have encountered an issue with the plot_model function in PyCaret where it displays an empty plot. I have tried running it on both my local system and on Google Colab but the issue persists. I have also tried using the %matplotlib inline magic command as suggested in previous issues but it does not solve the problem. As a temporary workaround, I am using display_format="plotly-dash" to display the plot.

### Reproducible Example

```python
#Tried PyCaret latest and pre versions.
#Load a dataset and train a model using PyCaret.
from pycaret.time_series import *
#Call the plot_model function to display a plot.
plot_model(plot='diagnostics')
```

### Expected Behavior

The plot_model function should display a plot of the requested model.

### Actual Results

```python-traceback
The plot_model function displays an empty plot.
```

### Installed Versions

<details>
3.0.0
</details>

**Comment by ngupta23** [comment]
What are you calling the plot model on? There is no experiment object in your code.

**Comment by imadarsh1001** [comment]
i have tried both API functional and OOP but facing the same issue. above example code is using OOP API.

**Comment by ngupta23** [comment]
Closing this due to missing information. Feel free to reopen with the complete details.
