### ISSUE TITLE
[BUG]: Unable to export transformed train and test data from setup

### ISSUE THREAD

**Issue by SSMK-wq** [pycaret/pycaret#3546]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I am currently trying to build a ML model using pycaret. So, I used the below `setup` function

# initialize setup with custom holdout size and name
```
clf = setup(data = df.loc[:, df.columns != 'ID'], target='final_label',session_id=123, 
            categorical_features=['Gender','Country'], 
            fold_strategy='stratifiedkfold', 
            fold=5, fold_shuffle=True, n_jobs=-1, 
            create_clusters=False,polynomial_features=False, 
            polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, 
            remove_multicollinearity=True, multicollinearity_threshold=0.90)
```

This initializes the process with list of variables from which I wish to extract `transformed_train_set` and `transformed_test_set`

![image](https://github.com/pycaret/pycaret/assets/30723825/62307453-cf9b-4b7f-b753-09e5309cb826)

While the `data` and `data_unseen` can be exported because we do this in the beginning using below code

```
data = dummy_out.sample(frac=0.70).reset_index(drop=True)
data_unseen = dummy_out.drop(data.index).reset_index(drop=True)
```

But how can I export `transformed_train_set` and `transformed_test_set`?

### Reproducible Example

```python
train_data = predict_model(rft,data = X_train,raw_score=True)
train_data['phase'] = 'train'
test_data = predict_model(rft,data = X_test,raw_score=True)
test_data['phase'] = 'test'
```

### Expected Behavior

Pycaret shoud either allow us to export the train and test before transformation and also after transformation

### Actual Results

```python-traceback
NameError: name 'X_train' is not defined

NameError: name 'transformed_train_set' is not defined
```

### Installed Versions

<details>
pycaret version = 2.3.10 and windows 10 and python 3.8
</details>

**Comment by moezali1** [comment]
@SSMK-wq You can access those using the `get_config` method. Run this command:

```
X_train_transformed = get_config('X_train_transformed')
X_test_transformed = get_config('X_test_transformed')
X_train = get_config('X_train')
X_test = get_config('X_test')
```
