### ISSUE TITLE
[BUG]: Precision and Recall scores are all zeros

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#3549]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Under some conditions, precision and recall scores are all zeros (example below from #3507)

![image](https://github.com/pycaret/pycaret/assets/33585645/733800d1-21c7-4292-bba6-2a3ff5006488)

### Reproducible Example

```python
from pycaret.classification import *

# Import libraries
import numpy as np
import pandas as pd

# Set random seed for reproducibility
np.random.seed(42)

# Define number of samples
N = 30000

# Generate features
numeric_feature = np.random.normal(0, 1, N)
cat_feature = np.random.choice(31, N).astype(int)
cat_feature2 = np.random.choice(2, N).astype(str)

# Combine features into a single matrix
X = np.column_stack((cat_feature, cat_feature2))

# Generate target variable
y = np.random.binomial(1, 0.2, N)

# Convert to DataFrame and add target variable
df = pd.DataFrame(X, columns=['categorical-cardinal', 'categorical-binary'])
df['target'] = y

# Print the first five rows of the dataset
print("Synthetic Dataset for Machine Learning:\n")
print(df.head())

setup(df, target='target', numeric_features=[], categorical_features=['categorical-cardinal', 'categorical-binary'])

model = create_model('lightgbm')

plot_model(model, 'auc')

predict_model(model)
```

### Expected Behavior

Precision and Recall should not be zeros

### Actual Results

```python-traceback
See image above
```

### Installed Versions

<details>
pycaret 3.0.1
</details>

**Comment by moezali1** [comment]
I have tested this. This is probably happening because TP on test set is 0 and hence causing zero divisibility error.

![image](https://github.com/pycaret/pycaret/assets/54699234/d8b3315a-8702-4797-8e30-e89fa763e376)

Notebook here: https://colab.research.google.com/drive/1EtoiYS-z9Dq5Olv5-cg3xVZI0fBTGo8C?usp=sharing

So I guess its a non-problem. shall we close this?
