### ISSUE TITLE
[BUG]: Setting X_train using set_config function doesn't work

### ISSUE THREAD

**Issue by Luna0298** [pycaret/pycaret#3555]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Hello, I'm trying to change X_train through the "set_config" function in a classification problem, but I'm getting the following error:
Variable X_train not found or is not writeable. Possible writeable variables are: ['data', 'USI', 'fix_imbalance', 'exp_name_log', 'exp_id', 'html_param', 'n_jobs_param', 'fold_generator', 'memory', 'seed', 'fold_shuffle_param', 'idx', 'log_plots_param', 'fold_groups_param', 'target_param', 'logging_param', 'pipeline', 'gpu_param']
Is this variable really not changeable manually? I saw that it could be changed in newer versions of pycaret (I'm using pycaret 3.0.1)

### Reproducible Example

```python
from pycaret.classification import *
from pycaret.datasets import get_data

data = get_data('diabetes')
s = setup(data = data, target = 'Class variable', session_id = 123)

# Save X_train and X_test with all features
X_train_all = get_config('X_train')
X_test_all = get_config('X_test')

# Try to change X_train
set_config('X_train', X_train_all[[
    'Number of times pregnant',
    'Plasma glucose concentration a 2 hours in an oral glucose tolerance test']])

# Even if i tried get only a sample of X_train it does not work 
Xtrain_sampled = X_train_all.sample(n = 100, random_state = 123)
set_config('X_train', Xtrain_sampled )
```

### Expected Behavior

Expected to be able to swap X_train for another dataframe.

### Actual Results

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-40a6d8fd8c36> in <cell line: 1>()
----> 1 set_config('X_train', X_train_all[[
      2     'Number of times pregnant',
      3     'Plasma glucose concentration a 2 hours in an oral glucose tolerance test']])

2 frames
/usr/local/lib/python3.10/dist-packages/pycaret/internal/pycaret_experiment/pycaret_experiment.py in set_config(self, variable, value, **kwargs)
    372             ]
    373             if k not in writeable_keys:
--> 374                 raise ValueError(
    375                     f"Variable {k} not found or is not writeable. Possible writeable variables are: {writeable_keys}"
    376                 )

ValueError: Variable X_train not found or is not writeable. Possible writeable variables are: ['exp_id', 'pipeline', 'fold_shuffle_param', 'logging_param', 'fold_generator', 'fix_imbalance', 'data', 'exp_name_log', 'n_jobs_param', 'gpu_param', 'fold_groups_param', 'target_param', 'USI', 'html_param', 'seed', 'log_plots_param', 'idx', 'memory']
```

### Installed Versions

<details>
System:
    python: 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]
executable: /usr/bin/python3
   machine: Linux-5.15.107+-x86_64-with-glibc2.31

PyCaret required dependencies:
                 pip: 23.1.2
          setuptools: 67.7.2
             pycaret: 3.0.1
             IPython: 7.34.0
          ipywidgets: 7.7.1
                tqdm: 4.65.0
               numpy: 1.22.4
              pandas: 1.5.3
              jinja2: 3.1.2
               scipy: 1.10.1
              joblib: 1.2.0
             sklearn: 1.2.2
                pyod: 1.0.9
            imblearn: 0.10.1
   category_encoders: 2.6.1
            lightgbm: 3.3.5
               numba: 0.56.4
            requests: 2.27.1
          matplotlib: 3.7.1
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.13.1
             kaleido: 0.2.1
         statsmodels: 0.13.5
              sktime: 0.17.0
               tbats: 1.1.3
            pmdarima: 2.0.3
              psutil: 5.9.5

PyCaret optional dependencies:
                shap: Not installed
           interpret: Not installed
                umap: Not installed
    pandas_profiling: Not installed
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
             xgboost: 1.7.5
            catboost: Not installed
              kmodes: Not installed
             mlxtend: 0.14.0
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: 0.2.7
              optuna: Not installed
               skopt: Not installed
              mlflow: Not installed
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: Not installed
           evidently: Not installed
               fugue: Not installed
           streamlit: Not installed
             prophet: 1.1.2
</details>

**Comment by ngupta23** [comment]
I think the error message is self-explanatory. This variable is controlled internally and not settable after the experiment is created. If you want to sample, you should just sample before creating the experiment and pass it to the experiment setup.

```
ValueError: Variable X_train not found or is not writeable. Possible writeable variables are: ['exp_id', 'pipeline', 'fold_shuffle_param', 'logging_param', 'fold_generator', 'fix_imbalance', 'data', 'exp_name_log', 'n_jobs_param', 'gpu_param', 'fold_groups_param', 'target_param', 'USI', 'html_param', 'seed', 'log_plots_param', 'idx', 'memory']
```

**Comment by Luna0298** [comment]
I thought so but I saw examples that in other versions it was possible to change.
There are even no restrictions on the function documentation, it is not said that there are immutable global variables.
Here is an article with an example of previous versions that I found: https://towardsdatascience.com/5-things-you-are-doing-wrong-in-pycaret-e01981575d2a
The code example I sent is with X_train, but even with X_test it doesn't work.

**Comment by ngupta23** [comment]
@Luna0298 - The tutorial is from a older version of pycaret 2.x.

@Yard1 @tvdboom @moezali1 - Has the behavior of `set_config` changed in pycaret 3.x (see error above which worked in the older version per @moezali1 's article?

**Comment by Luna0298** [comment]
Got it, so there's no way to change it anyway. I believe it would be interesting to have this possibility in future releases. My intention in the code was to be able to compare a model without selection of variables versus one with a selection, and for a fair comparison, the correct thing would be to use the same training and testing base in both. I am currently running the setup again, but as the input dataframe is changed there is no guarantee that training and testing will be the same, or even the cross validation folds.
Thank you for your help!

**Comment by ngupta23** [comment]
I think if you set the `session_id`, it acts as a seed and may help get the same splits internally. Does it not work?

**Comment by Luna0298** [comment]
I'm using the `session id`, but some functions consider different dataframes when we change columns, so I figured there would be a risk that the draw would be different. I will confirm that the training bases are the same even with different setups. Thanks!

**Comment by Yard1** [comment]
Yes, the behavior has changed. We don't allow setting it aside from `setup` because we need to create the entire preprocessing pipeline based on the data we have.
