### ISSUE TITLE
Is that possible to export results from compare_model

### ISSUE THREAD

**Issue by yizhuozhang** [pycaret/pycaret#356]
Now the result table is directly print out. Is that possible to get/export results from compare_model ? 

`
compare_models(fold=5,whitelist = ['lr','knn','nb','dt','svm'])
`
Model | Accuracy | AUC | Recall | Prec. | F1 | Kappa | MCC | TT (Sec)
-- | -- | -- | -- | -- | -- | -- | -- | --
SVM - Linear Kernel | 0.9157 | 0.0000 | 0.6129 | 0.9408 | 0.9390 | 0.8739 | 0.8749 | 0.6500
Logistic Regression | 0.8137 | 0.0000 | 0.2334 | 0.8565 | 0.8674 | 0.7249 | 0.7412 | 0.4090
K Neighbors Classifier | 0.8191 | 0.0000 | 0.4512 | 0.8715 | 0.8712 | 0.7153 | 0.7303 | 1.4219
Naive Bayes | 0.8776 | 0.0000 | 0.5499 | 0.8161 | 0.8729 | 0.7270 | 0.7276 | 0.3024
Decision Tree Classifier | 0.7176 | 0.0000 | 0.3181 | 0.8697 | 0.8174 | 0.5551 | 0.5640 | 13.9305

**Comment by Yard1** [comment]
`get_config('display_container')[-1]` will return the latest printed out dataframe, so if you call it after `compare_models()` you'll get that into a variable.

**Comment by pycaret** [comment]
@yizhuozhang You can also do this:

compare_models()
results = pull()

This will store the score grid as pandas df. Hope this helps.
