### ISSUE TITLE
[BUG]: AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by alihht** [pycaret/pycaret#3569]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Executing the following

from pycaret.classification import *

ends up with the following error:
AttributeError: 'NoneType' object has no attribute 'split'

pycaret==3.0.2
Python==3.10.9

I uninstalled python and anaconda. I removed all the files related to python and anaconda from my PC to start fresh. I reinstalled anaconda again and installed pycaret[full]. However, still facing the same issue!

I searched looking for a solution since for couple of weeks, but still not solution. Any idea? 

Regards, 

### Reproducible Example

```python
from pycaret.classification import *
```

### Expected Behavior

NA

### Actual Results

```python-traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_2072\3664932101.py in <cell line: 1>()
----> 1 from pycaret.classification import *
      2 s = setup(data, target = 'Status', session_id = 123, preprocess=True, transformation=True, normalize=True)

~\AppData\Roaming\Python\Python310\site-packages\pycaret\classification\__init__.py in <module>
----> 1 from pycaret.classification.functional import (
      2     add_metric,
      3     automl,
      4     blend_models,
      5     calibrate_model,

~\AppData\Roaming\Python\Python310\site-packages\pycaret\classification\functional.py in <module>
      6 from joblib.memory import Memory
      7 
----> 8 from pycaret.classification.oop import ClassificationExperiment
      9 from pycaret.internal.parallel.parallel_backend import ParallelBackend
     10 from pycaret.loggers.base_logger import BaseLogger

~\AppData\Roaming\Python\Python310\site-packages\pycaret\classification\oop.py in <module>
     15 
     16 from pycaret.containers.metrics import get_all_class_metric_containers
---> 17 from pycaret.containers.models import get_all_class_model_containers
     18 from pycaret.containers.models.classification import (
     19     ALL_ALLOWED_ENGINES,

~\AppData\Roaming\Python\Python310\site-packages\pycaret\containers\models\__init__.py in <module>
----> 1 from .anomaly import get_all_model_containers as get_all_anomaly_model_containers
      2 from .base_model import ModelContainer
      3 from .classification import get_all_model_containers as get_all_class_model_containers
      4 from .clustering import get_all_model_containers as get_all_clust_model_containers
      5 from .regression import get_all_model_containers as get_all_reg_model_containers

~\AppData\Roaming\Python\Python310\site-packages\pycaret\containers\models\anomaly.py in <module>
     15 import pycaret.containers.base_container
     16 import pycaret.internal.cuml_wrappers
---> 17 from pycaret.containers.models.base_model import ModelContainer
     18 from pycaret.internal.distributions import Distribution
     19 from pycaret.utils.generic import get_logger, param_grid_to_lists

~\AppData\Roaming\Python\Python310\site-packages\pycaret\containers\models\base_model.py in <module>
      7 from pycaret.containers.base_container import BaseContainer
      8 from pycaret.internal.distributions import CategoricalDistribution
----> 9 from pycaret.internal.pycaret_experiment.pycaret_experiment import _PyCaretExperiment
     10 from pycaret.utils.generic import get_allowed_engines, get_logger
     11 

~\AppData\Roaming\Python\Python310\site-packages\pycaret\internal\pycaret_experiment\pycaret_experiment.py in <module>
     10 import pycaret.internal.patches.sklearn
     11 import pycaret.internal.patches.yellowbrick
---> 12 import pycaret.internal.persistence
     13 from pycaret.internal.logging import get_logger
     14 from pycaret.utils.constants import DATAFRAME_LIKE

~\AppData\Roaming\Python\Python310\site-packages\pycaret\internal\persistence.py in <module>
     11 from pycaret.utils._dependencies import _check_soft_dependencies
     12 from pycaret.utils.generic import MLUsecase, get_logger
---> 13 from pycaret.utils.time_series.forecasting.pipeline import _add_model_to_pipeline
     14 
     15 

~\AppData\Roaming\Python\Python310\site-packages\pycaret\utils\time_series\forecasting\pipeline.py in <module>
      4 import pandas as pd
      5 from sktime.forecasting.base import BaseForecaster
----> 6 from sktime.forecasting.compose import ForecastingPipeline
      7 from sktime.transformations.compose import TransformerPipeline
      8 from sktime.transformations.series.impute import Imputer

~\AppData\Roaming\Python\Python310\site-packages\sktime\forecasting\compose\__init__.py in <module>
     30 ]
     31 
---> 32 from sktime.forecasting.compose._bagging import BaggingForecaster
     33 from sktime.forecasting.compose._column_ensemble import ColumnEnsembleForecaster
     34 from sktime.forecasting.compose._ensemble import (

~\AppData\Roaming\Python\Python310\site-packages\sktime\forecasting\compose\_bagging.py in <module>
     12 from sklearn import clone
     13 from sklearn.utils import check_random_state
---> 14 from sklearn.utils._testing import set_random_state
     15 
     16 from sktime.datatypes._utilities import update_data

~\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_testing.py in <module>
    395     fails_if_pypy = pytest.mark.xfail(IS_PYPY, reason="not compatible with PyPy")
    396     fails_if_unstable_openblas = pytest.mark.xfail(
--> 397         _in_unstable_openblas_configuration(),
    398         reason="OpenBLAS is unstable for this configuration",
    399     )

~\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\__init__.py in _in_unstable_openblas_configuration()
     88     import scipy  # noqa
     89 
---> 90     modules_info = threadpool_info()
     91 
     92     open_blas_used = any(info["internal_api"] == "openblas" for info in modules_info)

~\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\fixes.py in threadpool_info()
    148         return controller.info()
    149     else:
--> 150         return threadpoolctl.threadpool_info()
    151 
    152 

~\AppData\Local\anaconda3\lib\site-packages\threadpoolctl.py in threadpool_info()
    122     In addition, each module may contain internal_api specific entries.
    123     """
--> 124     return _ThreadpoolInfo(user_api=_ALL_USER_APIS).todicts()
    125 
    126 

~\AppData\Local\anaconda3\lib\site-packages\threadpoolctl.py in __init__(self, user_api, prefixes, modules)
    338 
    339             self.modules = []
--> 340             self._load_modules()
    341             self._warn_if_incompatible_openmp()
    342         else:

~\AppData\Local\anaconda3\lib\site-packages\threadpoolctl.py in _load_modules(self)
    371             self._find_modules_with_dyld()
    372         elif sys.platform == "win32":
--> 373             self._find_modules_with_enum_process_module_ex()
    374         else:
    375             self._find_modules_with_dl_iterate_phdr()

~\AppData\Local\anaconda3\lib\site-packages\threadpoolctl.py in _find_modules_with_enum_process_module_ex(self)
    483 
    484                 # Store the module if it is supported and selected
--> 485                 self._make_module_from_path(filepath)
    486         finally:
    487             kernel_32.CloseHandle(h_process)

~\AppData\Local\anaconda3\lib\site-packages\threadpoolctl.py in _make_module_from_path(self, filepath)
    513             if prefix in self.prefixes or user_api in self.user_api:
    514                 module_class = globals()[module_class]
--> 515                 module = module_class(filepath, prefix, user_api, internal_api)
    516                 self.modules.append(module)
    517 

~\AppData\Local\anaconda3\lib\site-packages\threadpoolctl.py in __init__(self, filepath, prefix, user_api, internal_api)
    604         self.internal_api = internal_api
    605         self._dynlib = ctypes.CDLL(filepath, mode=_RTLD_NOLOAD)
--> 606         self.version = self.get_version()
    607         self.num_threads = self.get_num_threads()
    608         self._get_extra_info()

~\AppData\Local\anaconda3\lib\site-packages\threadpoolctl.py in get_version(self)
    644                              lambda: None)
    645         get_config.restype = ctypes.c_char_p
--> 646         config = get_config().split()
    647         if config[0] == b"OpenBLAS":
    648             return config[1].decode("utf-8")

AttributeError: 'NoneType' object has no attribute 'split'
```

### Installed Versions

<details>
System:
    python: 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\****\AppData\Local\anaconda3\python.exe
   machine: Windows-10-10.0.19042-SP0

PyCaret required dependencies:
                 pip: 22.3.1
          setuptools: 65.6.3
             pycaret: 3.0.2
             IPython: 8.10.0
          ipywidgets: 7.6.5
                tqdm: 4.64.1
               numpy: 1.23.5
              pandas: 1.5.3
              jinja2: 3.1.2
               scipy: 1.10.0
              joblib: 1.1.1
             sklearn: 1.2.2
                pyod: 1.0.9
            imblearn: 0.10.1
   category_encoders: 2.6.1
            lightgbm: 3.3.5
               numba: 0.56.4
            requests: 2.28.1
          matplotlib: 3.7.0
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.9.0
             kaleido: 0.2.1
         statsmodels: 0.13.5
              sktime: 0.17.0
               tbats: 1.1.3
            pmdarima: 2.0.3
              psutil: 5.9.0

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: 0.4.1
                umap: 0.5.3
    pandas_profiling: 4.1.2
  explainerdashboard: 0.4.2.2
             autoviz: 0.1.604
           fairlearn: 0.7.0
             xgboost: 1.7.5
            catboost: 1.2
              kmodes: 0.12.2
             mlxtend: 0.22.0
       statsforecast: 1.5.0
        tune_sklearn: 0.4.5
                 ray: 2.4.0
            hyperopt: 0.2.7
              optuna: 3.1.1
               skopt: 0.9.0
              mlflow: 1.30.1
              gradio: 3.32.0
             fastapi: 0.95.2
             uvicorn: 0.22.0
              m2cgen: 0.10.0
           evidently: 0.2.8
               fugue: 0.8.3
           streamlit: Not installed
             prophet: Not installed
</details>

**Comment by ngupta23** [comment]
Are you somehow running Anomaly Detection in your flow along with classification?

**Comment by alihht** [comment]
> Are you somehow running Anomaly Detection in your flow along with classification?

It is the first line nothing after it. I'm just executing:
from pycaret.classification import *

That's it. All the lines after it are empty. It is failing in importing from pycaret.

Regards,

**Comment by ngupta23** [comment]
This is not reproducible on Google Colab (see below). Will need to keep digging into this as time permits.

![image](https://github.com/pycaret/pycaret/assets/33585645/cdcb9784-7f77-4b72-8ae6-4967315a442c)

**Comment by ngupta23** [comment]
Opened an issue with sktime. Will see if they can help: https://github.com/sktime/sktime/issues/4669

**Comment by alvarado1984** [comment]
Has anyone solved it? I have the same problem :(

**Comment by ngupta23** [comment]
It should get solved when sktime makes a new release with this fix. 
Also, it is not a completely reproducible error (e.g. it works on my machine).
Can you try on a different machine, or Google Colab, etc. to verify?

**Comment by ngupta23** [comment]
Also, can you verify if installing sktime from git directly (which supposedy has the fix) resolves the issue.
i.e. in your current environment which is giving the failure, try installing

```
git clone https://github.com/sktime/sktime.git
```

**Comment by hashirkhan-786** [comment]
This worked for me as i was encountering the similar error but for regression 

!pip install --upgrade threadpoolctl

i hope this resolves!

**Comment by ngupta23** [comment]
Thanks @hashirkhan-786 Can you also check what version of sktime you have? There was a release of sktime yesteday (version 0.19.2) that could have also fixed it. The prior issue was coming with versions of sktime older than 0.19.2.

**Comment by ngupta23** [comment]
Closing for now. Please feel free to comment and/or reopen this if the issue persists.

Summary of Possible Solutions:

- Upgrade `threadpool`: `pip install --upgrade threadpoolctl`
- Upgrade `sktime`: `pip install sktime >= 0.19.2`
