### ISSUE TITLE
[BUG]: Comet logging broken due to logging update

### ISSUE THREAD

**Issue by sherpan** [pycaret/pycaret#3572]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Unexpected new argument in the` loggers.set_tags(USI)` this new expectation wasn't added into CometLoggers and now logging with comet doesn't work

### Reproducible Example

```python
# load dataset
from pycaret.datasets import get_data
data = get_data('diabetes')

# init setup
from pycaret.classification import *
clf1 = setup(data, target = 'Class variable', log_experiment = 'comet_ml', experiment_name = 'pycaret_example', log_data=True),

# model training
best_model = compare_models()
```

### Expected Behavior

I think two solutions 

1. add the USI argument to the Comet Logger (it's not really relevant) 
2. only pass the USI argument if logger is of the Mlflow type 

### Actual Results

```python-traceback
COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Couldn't find a Git repository in '/content' nor in any parent directory. Set `COMET_GIT_DIRECTORY` if your Git Repository is elsewhere.
COMET INFO: Experiment is live on comet.com https://www.comet.com/sherpan/pycaret-example/a3c49ab8ce8f44eb89cc16cf61df09c2

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-30b6a517087a> in <cell line: 7>()
      5 # init setup
      6 from pycaret.classification import *
----> 7 clf1 = setup(data, target = 'Class variable', log_experiment = 'comet_ml', experiment_name = 'pycaret_example', log_data=True),
      8 
      9 # model training

3 frames
/usr/local/lib/python3.10/dist-packages/pycaret/loggers/dashboard_logger.py in log_experiment(self, experiment, log_profile, log_data, experiment_custom_tags, runtime)
    210             )
    211             logger.log_params(params, "setup")
--> 212             logger.set_tags(
    213                 "setup", experiment_custom_tags, runtime, USI=experiment.USI
    214             )

TypeError: CometLogger.set_tags() got an unexpected keyword argument 'USI'
```

### Installed Versions

<details>
PyCaret required dependencies:
                 pip: 23.1.2
          setuptools: 67.7.2
             pycaret: 3.0.2
             IPython: 7.34.0
          ipywidgets: 7.7.1
                tqdm: 4.65.0
               numpy: 1.22.4
              pandas: 1.5.3
              jinja2: 3.1.2
               scipy: 1.10.1
              joblib: 1.2.0
             sklearn: 1.2.2
                pyod: 1.0.9
            imblearn: 0.10.1
   category_encoders: 2.6.1
            lightgbm: 3.3.5
               numba: 0.56.4
            requests: 2.27.1
          matplotlib: 3.7.1
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.13.1
             kaleido: 0.2.1
         statsmodels: 0.13.5
              sktime: 0.17.0
               tbats: 1.1.3
            pmdarima: 2.0.3
              psutil: 5.9.5

PyCaret optional dependencies:
                shap: Not installed
           interpret: Not installed
                umap: Not installed
    pandas_profiling: Not installed
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
             xgboost: 1.7.5
            catboost: Not installed
              kmodes: Not installed
             mlxtend: 0.14.0
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: 0.2.7
              optuna: Not installed
               skopt: Not installed
              mlflow: Not installed
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: Not installed
           evidently: Not installed
               fugue: Not installed
           streamlit: Not installed
             prophet: 1.1.3
</details>

**Comment by sherpan** [comment]
@Yard1 any guidance here?

**Comment by Yard1** [comment]
Thanks, will take a look
