### ISSUE TITLE
[BUG]: The Evaluations for the clustering Model gets printed Multiple Times

### ISSUE THREAD

**Issue by nnlbu** [pycaret/pycaret#3573]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

- Once you initiate a model it often gets printed two times. 

For example for the density-based clustering algorithm, it returns null as the final evaluation and it also prints it two times: 

![Untitled](https://github.com/pycaret/pycaret/assets/133973106/9cbd6a01-d24e-4fd9-96de-4f3e62fb3c7f) 

I used [this dataset](https://archive.ics.uci.edu/ml/datasets/Mturk+User-Perceived+Clusters+over+Images) and that was the result I received.  

For the **DBCA** the evaluations are not correct. 

### Reproducible Example

# Rows are the features
# Columns are the images 

```
MainFeatureData = pd.read_csv("./data_feature.csv")
MainFeatureData 
dbscan_model = create_model('dbscan') 
``` 
you'd receive the output I mentioned above.

### Expected Behavior

- The evaluation model needs to be printed once and for **DBCA** it should not return null as the final result. 

### Actual Results

```python-traceback
The output is null for the evaluations. 
The dataset is very straightforward and it should not print null for the metrics two times.
```

### Installed Versions

I use the latest version: '3.0.2'
![2](https://github.com/pycaret/pycaret/assets/133973106/59ba4839-1c0f-4c00-a297-7749df03a4cb)

**Comment by moezali1** [comment]
@nnlbu Can you restart your kernel or try in fresh notebook and see if it still cause the issue with double printing?

**Comment by nnlbu** [comment]
yes, I test it and update this issue today.

**Comment by nnlbu** [comment]
I think this issue is resolved. 
Possibly It was because of my notebook logs and history. 
Thanks
