### ISSUE TITLE
Refractor compare_models() to use create_model()? 

### ISSUE THREAD

**Issue by Yard1** [pycaret/pycaret#358]
It seems to me that it would be a good idea to move out all model-generating code out of `compare_models()`, and instead use `create_models()` internally. Right now, the code that essentially does the same thing is duplicated in two places, making maintenance and extensibility harder. If `compare_models()` was to be refactored like that, it would be much easier to add new models, and also, allow for variations of the function that eg. compare tuned or existing models.

I'd be happy to try my hand at this if you feel it is a good idea. It would be a big change, and it may introduce some new issues, but I think it is necessary for the project going forward.

**Comment by pycaret** [comment]
@Yard1 

It all started with this one single PR. :) 

Closing this now...
