### ISSUE TITLE
[BUG]: no interactive dashboard appear after evaluate_model

### ISSUE THREAD

**Issue by tankienleong** [pycaret/pycaret#3580]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

no interactive dashboard appear after execute evaluate_model

### Reproducible Example

```python
from pycaret.datasets import get_data
juice = get_data('juice')
from pycaret.classification import *
exp_name = setup(data = juice,  target = 'Purchase')
lr = create_model('lr')
evaluate_model(lr)
```

### Expected Behavior

I should see interactive dashboard appear

### Actual Results

```python-traceback
This is what I get on terminal after execute python script
interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipeline'), ('Hyperparameters', 'parameter'), ('AUC', 'auc'), ('Confusion Matrix', 'confusion_matrix'), ('Threshold', 'threshold'), ('Precision Recall', 'pr'), ('Prediction Error', 'error'), ('Class Report', 'class_report'), ('Feature Selection', 'rfe'), ('Learning Curve', 'learning'), ('Manifold Learning', 'manifold'), ('Calibration Curve', 'calibration'), ('Validation Curve', 'vc'), ('Dimensions', 'dimension'), ('Feature Importance', 'feature'), ('Feature Importance (All)', 'feature_all'), ('Decision Boundary', 'boundary'), ('Lift Chart', 'lift'), ('Gain Chart', 'gain'), ('Decision Tree', 'tree'), ('KS Statistic Plot', 'ks')), value='pipeline'), Output()), _dom_classes=('widget-interact',))
```

### Installed Versions

<details>
System:
    python: 3.8.10 (default, Apr  4 2023, 16:32:19)  [GCC 7.5.0]
executable: /home/test/.pyenv/versions/pycaret_venv/bin/python3
   machine: Linux-5.4.0-149-generic-x86_64-with-glibc2.2.5

PyCaret required dependencies:
                 pip: 23.1.2
          setuptools: 56.0.0
             pycaret: 3.0.0
             IPython: 7.34.0
          ipywidgets: 7.7.5
                tqdm: 4.64.1
               numpy: 1.23.5
              pandas: 1.5.3
              jinja2: 3.1.2
               scipy: 1.9.1
              joblib: 1.2.0
             sklearn: 1.2.2
                pyod: 1.0.9
            imblearn: 0.10.1
   category_encoders: 2.6.0
            lightgbm: 3.3.5
               numba: 0.56.4
            requests: 2.28.2
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.14.0
             kaleido: 0.2.1
         statsmodels: 0.13.5
              sktime: 0.17.0
               tbats: 1.1.2
            pmdarima: 2.0.3
              psutil: 5.9.4

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: 0.3.2
                umap: 0.5.3
    pandas_profiling: 4.1.2
  explainerdashboard: 0.4.2.1
             autoviz: 0.1.58
           fairlearn: 0.7.0
             xgboost: 1.7.5
            catboost: 1.1.1
              kmodes: 0.12.2
             mlxtend: 0.22.0
       statsforecast: 1.5.0
        tune_sklearn: 0.4.5
                 ray: 2.3.1
            hyperopt: 0.2.7
              optuna: 3.1.0
               skopt: 0.9.0
              mlflow: 1.30.0
              gradio: 3.24.1
             fastapi: 0.95.0
             uvicorn: 0.21.1
              m2cgen: 0.10.0
           evidently: 0.2.8
               fugue: 0.8.3
           streamlit: Not installed
             prophet: Not installed
</details>

**Comment by moezali1** [comment]
`evaluate_model` only works in Notebook environment where `IPython` is available.

The message that you have shown above interactive(...) is usually shown when IPython is not supported in that environment.
