### ISSUE TITLE
[BUG]:  Can not import any pycaret modules 

### ISSUE THREAD

**Issue by HarshkumarDegamadiya** [pycaret/pycaret#3582]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Issue : AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_8216\215956045.py in <module>
----> 1 from pycaret.regression import *

~\AppData\Roaming\Python\Python39\site-packages\pycaret\regression\__init__.py in <module>
----> 1 from pycaret.regression.functional import (
      2     add_metric,
      3     automl,
      4     blend_models,
      5     check_drift,

~\AppData\Roaming\Python\Python39\site-packages\pycaret\regression\functional.py in <module>
      8 from pycaret.internal.parallel.parallel_backend import ParallelBackend
      9 from pycaret.loggers.base_logger import BaseLogger
---> 10 from pycaret.regression.oop import RegressionExperiment
     11 from pycaret.utils.constants import DATAFRAME_LIKE, SEQUENCE_LIKE, TARGET_LIKE
     12 from pycaret.utils.generic import check_if_global_is_not_none

~\AppData\Roaming\Python\Python39\site-packages\pycaret\regression\oop.py in <module>
      9 
     10 from pycaret.containers.metrics import get_all_reg_metric_containers
---> 11 from pycaret.containers.models import get_all_reg_model_containers
     12 from pycaret.containers.models.regression import (
     13     ALL_ALLOWED_ENGINES,

~\AppData\Roaming\Python\Python39\site-packages\pycaret\containers\models\__init__.py in <module>
----> 1 from .anomaly import get_all_model_containers as get_all_anomaly_model_containers
      2 from .base_model import ModelContainer
      3 from .classification import get_all_model_containers as get_all_class_model_containers
      4 from .clustering import get_all_model_containers as get_all_clust_model_containers
      5 from .regression import get_all_model_containers as get_all_reg_model_containers

~\AppData\Roaming\Python\Python39\site-packages\pycaret\containers\models\anomaly.py in <module>
     15 import pycaret.containers.base_container
     16 import pycaret.internal.cuml_wrappers
---> 17 from pycaret.containers.models.base_model import ModelContainer
     18 from pycaret.internal.distributions import Distribution
     19 from pycaret.utils.generic import get_logger, param_grid_to_lists

~\AppData\Roaming\Python\Python39\site-packages\pycaret\containers\models\base_model.py in <module>
      7 from pycaret.containers.base_container import BaseContainer
      8 from pycaret.internal.distributions import CategoricalDistribution
----> 9 from pycaret.internal.pycaret_experiment.pycaret_experiment import _PyCaretExperiment
     10 from pycaret.utils.generic import get_allowed_engines, get_logger
     11 

~\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pycaret_experiment\pycaret_experiment.py in <module>
     10 import pycaret.internal.patches.sklearn
     11 import pycaret.internal.patches.yellowbrick
---> 12 import pycaret.internal.persistence
     13 from pycaret.internal.logging import get_logger
     14 from pycaret.utils.constants import DATAFRAME_LIKE

~\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\persistence.py in <module>
     11 from pycaret.utils._dependencies import _check_soft_dependencies
     12 from pycaret.utils.generic import MLUsecase, get_logger
---> 13 from pycaret.utils.time_series.forecasting.pipeline import _add_model_to_pipeline
     14 
     15 

~\AppData\Roaming\Python\Python39\site-packages\pycaret\utils\time_series\forecasting\pipeline.py in <module>
      4 import pandas as pd
      5 from sktime.forecasting.base import BaseForecaster
----> 6 from sktime.forecasting.compose import ForecastingPipeline
      7 from sktime.transformations.compose import TransformerPipeline
      8 from sktime.transformations.series.impute import Imputer

~\AppData\Roaming\Python\Python39\site-packages\sktime\forecasting\compose\__init__.py in <module>
     30 ]
     31 
---> 32 from sktime.forecasting.compose._bagging import BaggingForecaster
     33 from sktime.forecasting.compose._column_ensemble import ColumnEnsembleForecaster
     34 from sktime.forecasting.compose._ensemble import (

~\AppData\Roaming\Python\Python39\site-packages\sktime\forecasting\compose\_bagging.py in <module>
     12 from sklearn import clone
     13 from sklearn.utils import check_random_state
---> 14 from sklearn.utils._testing import set_random_state
     15 
     16 from sktime.datatypes._utilities import update_data

~\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\_testing.py in <module>
    395     fails_if_pypy = pytest.mark.xfail(IS_PYPY, reason="not compatible with PyPy")
    396     fails_if_unstable_openblas = pytest.mark.xfail(
--> 397         _in_unstable_openblas_configuration(),
    398         reason="OpenBLAS is unstable for this configuration",
    399     )

~\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\__init__.py in _in_unstable_openblas_configuration()
     88     import scipy  # noqa
     89 
---> 90     modules_info = threadpool_info()
     91 
     92     open_blas_used = any(info["internal_api"] == "openblas" for info in modules_info)

~\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\fixes.py in threadpool_info()
    148         return controller.info()
    149     else:
--> 150         return threadpoolctl.threadpool_info()
    151 
    152 

C:\ProgramData\Anaconda3\lib\site-packages\threadpoolctl.py in threadpool_info()
    122     In addition, each module may contain internal_api specific entries.
    123     """
--> 124     return _ThreadpoolInfo(user_api=_ALL_USER_APIS).todicts()
    125 
    126 

C:\ProgramData\Anaconda3\lib\site-packages\threadpoolctl.py in __init__(self, user_api, prefixes, modules)
    338 
    339             self.modules = []
--> 340             self._load_modules()
    341             self._warn_if_incompatible_openmp()
    342         else:

C:\ProgramData\Anaconda3\lib\site-packages\threadpoolctl.py in _load_modules(self)
    371             self._find_modules_with_dyld()
    372         elif sys.platform == "win32":
--> 373             self._find_modules_with_enum_process_module_ex()
    374         else:
    375             self._find_modules_with_dl_iterate_phdr()

C:\ProgramData\Anaconda3\lib\site-packages\threadpoolctl.py in _find_modules_with_enum_process_module_ex(self)
    483 
    484                 # Store the module if it is supported and selected
--> 485                 self._make_module_from_path(filepath)
    486         finally:
    487             kernel_32.CloseHandle(h_process)

C:\ProgramData\Anaconda3\lib\site-packages\threadpoolctl.py in _make_module_from_path(self, filepath)
    513             if prefix in self.prefixes or user_api in self.user_api:
    514                 module_class = globals()[module_class]
--> 515                 module = module_class(filepath, prefix, user_api, internal_api)
    516                 self.modules.append(module)
    517 

C:\ProgramData\Anaconda3\lib\site-packages\threadpoolctl.py in __init__(self, filepath, prefix, user_api, internal_api)
    604         self.internal_api = internal_api
    605         self._dynlib = ctypes.CDLL(filepath, mode=_RTLD_NOLOAD)
--> 606         self.version = self.get_version()
    607         self.num_threads = self.get_num_threads()
    608         self._get_extra_info()

C:\ProgramData\Anaconda3\lib\site-packages\threadpoolctl.py in get_version(self)
    644                              lambda: None)
    645         get_config.restype = ctypes.c_char_p
--> 646         config = get_config().split()
    647         if config[0] == b"OpenBLAS":
    648             return config[1].decode("utf-8")

AttributeError: 'NoneType' object has no attribute 'split'

1
​

### Reproducible Example

```python
from pycaret.regression import *
```

### Expected Behavior

It should import the library b

### Actual Results

```python-traceback
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_8216\215956045.py in <module>
----> 1 from pycaret.regression import *

~\AppData\Roaming\Python\Python39\site-packages\pycaret\regression\__init__.py in <module>
----> 1 from pycaret.regression.functional import (
      2     add_metric,
      3     automl,
      4     blend_models,
      5     check_drift,

~\AppData\Roaming\Python\Python39\site-packages\pycaret\regression\functional.py in <module>
      8 from pycaret.internal.parallel.parallel_backend import ParallelBackend
      9 from pycaret.loggers.base_logger import BaseLogger
---> 10 from pycaret.regression.oop import RegressionExperiment
     11 from pycaret.utils.constants import DATAFRAME_LIKE, SEQUENCE_LIKE, TARGET_LIKE
     12 from pycaret.utils.generic import check_if_global_is_not_none

~\AppData\Roaming\Python\Python39\site-packages\pycaret\regression\oop.py in <module>
      9 
     10 from pycaret.containers.metrics import get_all_reg_metric_containers
---> 11 from pycaret.containers.models import get_all_reg_model_containers
     12 from pycaret.containers.models.regression import (
     13     ALL_ALLOWED_ENGINES,

~\AppData\Roaming\Python\Python39\site-packages\pycaret\containers\models\__init__.py in <module>
----> 1 from .anomaly import get_all_model_containers as get_all_anomaly_model_containers
      2 from .base_model import ModelContainer
      3 from .classification import get_all_model_containers as get_all_class_model_containers
      4 from .clustering import get_all_model_containers as get_all_clust_model_containers
      5 from .regression import get_all_model_containers as get_all_reg_model_containers

~\AppData\Roaming\Python\Python39\site-packages\pycaret\containers\models\anomaly.py in <module>
     15 import pycaret.containers.base_container
     16 import pycaret.internal.cuml_wrappers
---> 17 from pycaret.containers.models.base_model import ModelContainer
     18 from pycaret.internal.distributions import Distribution
     19 from pycaret.utils.generic import get_logger, param_grid_to_lists

~\AppData\Roaming\Python\Python39\site-packages\pycaret\containers\models\base_model.py in <module>
      7 from pycaret.containers.base_container import BaseContainer
      8 from pycaret.internal.distributions import CategoricalDistribution
----> 9 from pycaret.internal.pycaret_experiment.pycaret_experiment import _PyCaretExperiment
     10 from pycaret.utils.generic import get_allowed_engines, get_logger
     11 

~\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\pycaret_experiment\pycaret_experiment.py in <module>
     10 import pycaret.internal.patches.sklearn
     11 import pycaret.internal.patches.yellowbrick
---> 12 import pycaret.internal.persistence
     13 from pycaret.internal.logging import get_logger
     14 from pycaret.utils.constants import DATAFRAME_LIKE

~\AppData\Roaming\Python\Python39\site-packages\pycaret\internal\persistence.py in <module>
     11 from pycaret.utils._dependencies import _check_soft_dependencies
     12 from pycaret.utils.generic import MLUsecase, get_logger
---> 13 from pycaret.utils.time_series.forecasting.pipeline import _add_model_to_pipeline
     14 
     15 

~\AppData\Roaming\Python\Python39\site-packages\pycaret\utils\time_series\forecasting\pipeline.py in <module>
      4 import pandas as pd
      5 from sktime.forecasting.base import BaseForecaster
----> 6 from sktime.forecasting.compose import ForecastingPipeline
      7 from sktime.transformations.compose import TransformerPipeline
      8 from sktime.transformations.series.impute import Imputer

~\AppData\Roaming\Python\Python39\site-packages\sktime\forecasting\compose\__init__.py in <module>
     30 ]
     31 
---> 32 from sktime.forecasting.compose._bagging import BaggingForecaster
     33 from sktime.forecasting.compose._column_ensemble import ColumnEnsembleForecaster
     34 from sktime.forecasting.compose._ensemble import (

~\AppData\Roaming\Python\Python39\site-packages\sktime\forecasting\compose\_bagging.py in <module>
     12 from sklearn import clone
     13 from sklearn.utils import check_random_state
---> 14 from sklearn.utils._testing import set_random_state
     15 
     16 from sktime.datatypes._utilities import update_data

~\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\_testing.py in <module>
    395     fails_if_pypy = pytest.mark.xfail(IS_PYPY, reason="not compatible with PyPy")
    396     fails_if_unstable_openblas = pytest.mark.xfail(
--> 397         _in_unstable_openblas_configuration(),
    398         reason="OpenBLAS is unstable for this configuration",
    399     )

~\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\__init__.py in _in_unstable_openblas_configuration()
     88     import scipy  # noqa
     89 
---> 90     modules_info = threadpool_info()
     91 
     92     open_blas_used = any(info["internal_api"] == "openblas" for info in modules_info)

~\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\fixes.py in threadpool_info()
    148         return controller.info()
    149     else:
--> 150         return threadpoolctl.threadpool_info()
    151 
    152 

C:\ProgramData\Anaconda3\lib\site-packages\threadpoolctl.py in threadpool_info()
    122     In addition, each module may contain internal_api specific entries.
    123     """
--> 124     return _ThreadpoolInfo(user_api=_ALL_USER_APIS).todicts()
    125 
    126 

C:\ProgramData\Anaconda3\lib\site-packages\threadpoolctl.py in __init__(self, user_api, prefixes, modules)
    338 
    339             self.modules = []
--> 340             self._load_modules()
    341             self._warn_if_incompatible_openmp()
    342         else:

C:\ProgramData\Anaconda3\lib\site-packages\threadpoolctl.py in _load_modules(self)
    371             self._find_modules_with_dyld()
    372         elif sys.platform == "win32":
--> 373             self._find_modules_with_enum_process_module_ex()
    374         else:
    375             self._find_modules_with_dl_iterate_phdr()

C:\ProgramData\Anaconda3\lib\site-packages\threadpoolctl.py in _find_modules_with_enum_process_module_ex(self)
    483 
    484                 # Store the module if it is supported and selected
--> 485                 self._make_module_from_path(filepath)
    486         finally:
    487             kernel_32.CloseHandle(h_process)

C:\ProgramData\Anaconda3\lib\site-packages\threadpoolctl.py in _make_module_from_path(self, filepath)
    513             if prefix in self.prefixes or user_api in self.user_api:
    514                 module_class = globals()[module_class]
--> 515                 module = module_class(filepath, prefix, user_api, internal_api)
    516                 self.modules.append(module)
    517 

C:\ProgramData\Anaconda3\lib\site-packages\threadpoolctl.py in __init__(self, filepath, prefix, user_api, internal_api)
    604         self.internal_api = internal_api
    605         self._dynlib = ctypes.CDLL(filepath, mode=_RTLD_NOLOAD)
--> 606         self.version = self.get_version()
    607         self.num_threads = self.get_num_threads()
    608         self._get_extra_info()

C:\ProgramData\Anaconda3\lib\site-packages\threadpoolctl.py in get_version(self)
    644                              lambda: None)
    645         get_config.restype = ctypes.c_char_p
--> 646         config = get_config().split()
    647         if config[0] == b"OpenBLAS":
    648             return config[1].decode("utf-8")

AttributeError: 'NoneType' object has no attribute 'split'

1
​
```

### Installed Versions

<details>
System:
    python: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
executable: C:\ProgramData\Anaconda3\python.exe
   machine: Windows-10-10.0.22000-SP0

PyCaret required dependencies:
                 pip: 22.2.2
          setuptools: 63.4.1
             pycaret: 3.0.2
             IPython: 7.31.1
          ipywidgets: 7.6.5
                tqdm: 4.64.1
               numpy: 1.21.5
              pandas: 1.4.4
              jinja2: 2.11.3
               scipy: 1.9.1
              joblib: 1.1.0
             sklearn: 1.0.2
                pyod: 1.0.9
            imblearn: 0.10.1
   category_encoders: 2.6.1
            lightgbm: 3.3.5
               numba: 0.55.1
            requests: 2.28.1
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.9.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.17.0
               tbats: 1.1.3
            pmdarima: 1.8.5
              psutil: 5.9.0

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: 0.4.1
                umap: 0.5.3
    pandas_profiling: 4.1.2
  explainerdashboard: 0.4.2.2
             autoviz: 0.1.604
           fairlearn: 0.7.0
             xgboost: 1.7.5
            catboost: 1.1.1
              kmodes: 0.12.2
             mlxtend: 0.22.0
       statsforecast: 1.4.0
        tune_sklearn: 0.4.5
                 ray: 2.2.0
            hyperopt: 0.2.7
              optuna: 3.1.1
               skopt: 0.9.0
              mlflow: 1.30.1
              gradio: 3.32.0
             fastapi: 0.95.2
             uvicorn: 0.22.0
              m2cgen: 0.10.0
           evidently: 0.2.8
               fugue: 0.8.4
           streamlit: 1.22.0
             prophet: 1.1.3
</details>

**Comment by ngupta23** [comment]
Same error as in https://github.com/pycaret/pycaret/issues/3569

**Comment by ngupta23** [comment]
Opened an issue with sktime. Will see if they can help: https://github.com/sktime/sktime/issues/4669

**Comment by celestinoxp** [comment]
@ngupta23 I don't know if it's relevant, but pycaret has been updated to 3.0.2 but joblib is at version 1.1.0. I think pycaret hasn't been updated well either, because minimum joblib is 1.2.
In my opinion you should uninstall pycaret and reinstall

**Comment by ngupta23** [comment]
Can you verify if installing sktime from git directly (which supposedly has the fix) resolves the issue?
i.e. in your current environment which is giving the failure, try installing

```
git clone https://github.com/sktime/sktime.git
```

**Comment by ngupta23** [comment]
See https://github.com/pycaret/pycaret/issues/3569#issuecomment-1602729600 and https://github.com/pycaret/pycaret/issues/3569#issuecomment-1603527436 for potential solutions.

**Comment by ngupta23** [comment]
We would appreciate it if you can test with the above upgrade of sktime and let us know if the issue has been resolved. Thanks!

**Comment by ngupta23** [comment]
Closing for now. Please feel free to comment and/or reopen this if the issue persists.

Summary of Possible Solutions:

- Upgrade `threadpool`: `pip install --upgrade threadpoolctl`
- Upgrade `sktime`: `pip install sktime >= 0.19.2`
