### ISSUE TITLE
[BUG]: use_train_data=True/False

### ISSUE THREAD

**Issue by hipotures** [pycaret/pycaret#3583]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Plots for use_train_data=False and use_train_data=True return the same values/graphs/data. Tested on my own data and test code from repo: pycaret/tests/test_classification_plots.py 

### Reproducible Example

```python
for plot in available_plots:
    pycaret.classification.plot_model(model, plot=plot, use_train_data=False)
    pycaret.classification.plot_model(model, plot=plot, use_train_data=True)
```

### Expected Behavior

Values from train/test data should be different

### Actual Results

```python-traceback
use_train_data=False and use_train_data=False create the same results
```

### Installed Versions

<details>
System:
    python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21)  [GCC 9.4.0]
executable: /opt/conda/bin/python
   machine: Linux-4.19.0-23-cloud-amd64-x86_64-with-debian-bullseye-sid

PyCaret required dependencies:
                 pip: 23.0.1
          setuptools: 67.6.0
             pycaret: 3.0.2
             IPython: 7.34.0
          ipywidgets: 8.0.5
                tqdm: 4.64.1
               numpy: 1.21.6
              pandas: 1.3.5
              jinja2: 3.1.2
               scipy: 1.7.3
              joblib: 1.2.0
             sklearn: 1.0.2
                pyod: 1.0.9
            imblearn: 0.10.1
   category_encoders: 2.6.1
            lightgbm: 3.3.5
               numba: 0.56.4
            requests: 2.28.2
          matplotlib: 3.5.3
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.13.1
             kaleido: 0.2.1
         statsmodels: 0.13.5
              sktime: 0.17.0
               tbats: 1.1.3
            pmdarima: 2.0.3
              psutil: 5.9.3

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: 0.4.1
                umap: 0.5.3
    pandas_profiling: 3.6.6
  explainerdashboard: 0.3.8
             autoviz: 0.1.604
           fairlearn: 0.7.0
             xgboost: 1.6.2
            catboost: 1.2
              kmodes: 0.12.2
             mlxtend: 0.22.0
       statsforecast: 1.5.0
        tune_sklearn: 0.4.5
                 ray: 2.3.1
            hyperopt: 0.2.7
              optuna: 3.1.1
               skopt: 0.9.0
              mlflow: 1.30.1
              gradio: 3.32.0
             fastapi: 0.95.0
             uvicorn: 0.21.1
              m2cgen: 0.10.0
           evidently: 0.2.8
               fugue: 0.8.3
           streamlit: Not installed
             prophet: 1.1.3
</details>

**Comment by hipotures** [comment]
Tested on test_classification_plots.py  from repo https://raw.githubusercontent.com/pycaret/pycaret/master/tests/test_classification_plots.py

**Comment by ngupta23** [comment]
Please provide complete code and data to reproduce the issue. Thanks!

**Comment by hipotures** [comment]
```
import pandas as pd

import pycaret.classification
import pycaret.datasets


def test_plot():
    # loading dataset
    data = pycaret.datasets.get_data("juice")
    assert isinstance(data, pd.DataFrame)

    # init setup
    pycaret.classification.setup(
        data,
        target="Purchase",
        log_experiment=True,
        log_plots=True,
        html=False,
        session_id=123,
        fold=2,
        n_jobs=1,
    )

    model = pycaret.classification.create_model("rf", max_depth=2, n_estimators=5)

    exp = pycaret.classification.ClassificationExperiment()
    available_plots = exp._available_plots

    for plot in available_plots:
        pycaret.classification.plot_model(model, plot=plot, use_train_data=False)
        pycaret.classification.plot_model(model, plot=plot, use_train_data=True)

    models = [
        pycaret.classification.create_model("et"),
        pycaret.classification.create_model("xgboost"),
    ]

    # no pfi due to dependency hell
    available_shap = ["summary", "correlation", "reason", "pdp", "msa"]

    for model in models:
        for plot in available_shap:
            pycaret.classification.interpret_model(model, plot=plot)
            pycaret.classification.interpret_model(
                model, plot=plot, X_new_sample=data.drop("Purchase", axis=1).iloc[:10]
            )

    assert 1 == 1


if __name__ == "__main__":
    test_plot()

```

**Comment by Yard1** [comment]
Thanks, this is indeed an issue. This argument was put into `plot_model` by mistake. It is only usable in `interpret_model`.
