### ISSUE TITLE
[BUG]: deepchecks issue

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#3590]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

2023-06-08 08:44:22,754:WARNING:C:\Users\user\anaconda3\lib\site-packages\deepchecks\__init__.py:136: DeprecationWarning:

Ability to import base tabular functionality from the `deepchecks` package directly is deprecated, please import from `deepchecks.tabular` instead

### Reproducible Example

```python
from pycaret.datasets import get_data
juice = get_data('juice')
from pycaret.classification import *
exp_name = setup(data = juice,  target = 'Purchase')
lr = create_model('lr')
deep_check(lr)
```

### Expected Behavior

.

### Actual Results

```python-traceback
Error displaying widget
```

### Installed Versions

<details>
System:
    python: 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\user\anaconda3\python.exe
   machine: Windows-10-10.0.22621-SP0

PyCaret required dependencies:
                 pip: 23.1.2
          setuptools: 67.8.0
             pycaret: 3.0.2
             IPython: 7.34.0
          ipywidgets: 7.7.5
                tqdm: 4.65.0
               numpy: 1.24.3
              pandas: 2.0.2
              jinja2: 3.1.2
               scipy: 1.10.1
              joblib: 1.3.0.dev0
             sklearn: 1.2.2
                pyod: 1.0.9
            imblearn: 0.10.1
   category_encoders: 2.6.1
            lightgbm: 3.3.5
               numba: 0.57.0
            requests: 2.31.0
          matplotlib: 3.7.1
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.14.1
             kaleido: 0.2.1
         statsmodels: 0.14.0
              sktime: 0.19.1
               tbats: 1.1.3
            pmdarima: 2.0.3
              psutil: 5.9.5

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: 0.4.2
                umap: 0.5.3
    pandas_profiling: 4.2.0
  explainerdashboard: 0.4.2.2
             autoviz: 0.1.720
           fairlearn: 0.8.0
             xgboost: 2.0.0-dev
            catboost: 1.2
              kmodes: 0.12.2
             mlxtend: 0.22.0
       statsforecast: 1.5.0
        tune_sklearn: 0.4.5
                 ray: 2.4.0
            hyperopt: 0.2.7
              optuna: 3.2.0
               skopt: 0.9.0
              mlflow: 2.3.2
              gradio: 3.33.1
             fastapi: 0.96.0
             uvicorn: 0.22.0
              m2cgen: 0.10.0
           evidently: 0.3.2.1
               fugue: 0.8.4
           streamlit: Not installed
             prophet: Not installed
</details>

**Comment by huaji1992** [comment]
+1

**Comment by Sunishchal** [comment]
+1

**Comment by moezali1** [comment]
@celestinoxp Unfortunately we are dropping the support for `deepchecks` and `eda` in the next release.
