### ISSUE TITLE
[BUG]: predict model failed with a pipeline from a colleague

### ISSUE THREAD

**Issue by Mcthomas777** [pycaret/pycaret#3594]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Hello team, 

I am working on a project, and someone send me over his model (.pkl). I'm able to load the model, but then when I'm running **predict_model()**. It returns
```
 FileNotFoundError for : 
path\\to\\my\\colleagues\\Temp\\joblib\\pycaret\\internal\\pipeline\\_full_transform\\func_code.py
```
- I tried **overiding .pkl file altering the path** to a correct one, but then I got this error : 
```
    pickle.py", line 317, in load_frame
        self.current_frame = io.BytesIO(self.file_read(frame_size))
    MemoryError
```
Code was working on pycaret <3.0.* with corresponding pipeline

### Reproducible Example

```python
def _load_model_pipeline(self) -> Optional[any]:
        """Load model pipeline.

        :raises FileNotFoundError: if model pipeline file is not found
        :return: pipeline as model object
        """
        if not self.path_model_pipeline.exists():
            self.log.info(f"Pipeline path incorrect: {self.path_model_pipeline}")
            raise FileNotFoundError(f"File {self.path_model_pipeline} does not exist!")

        self.log.info("Loading pipeline ...")
        model_pipeline = load_model(self.path_model_pipeline.with_suffix(".pkl"))

        self.log.info("Pipeline successfully loaded!")
        return model_pipeline

recommendations_df = predict_model(self.model_pipeline, data=df)
```

### Expected Behavior

Predict model return results of the prediction over the dataset

### Actual Results

```python-traceback
**predict_model()**. It returns

 FileNotFoundError for : 
path\\to\\my\\colleagues\\Temp\\joblib\\pycaret\\internal\\pipeline\\_full_transform\\func_code.py
```
- I tried **overiding .pkl file altering the path** to a correct one, but then I got this error : 
```
    pickle.py", line 317, in load_frame
        self.current_frame = io.BytesIO(self.file_read(frame_size))
    MemoryError
```
```


### Installed Versions

<details>
Replace this line with the output of the version code above.
-python 3.9.13
-pycaret 3.0.2 / lastest commit of master 
</details>

**Comment by ngupta23** [comment]
There is a big change in the internal structure between pycaret 2.x and 3.x. The model should be created and loaded using the same python environment (including pycaret version) to avoid any issues and incompatibilities.

**Comment by Mcthomas777** [comment]
we are now both running pipeline on the same python version (3.10.10), and pycaret 3.0.2, but the issue persist, any further idea ? 

In the .pkl file, looks like there is some info related to path where pipeline has been created, see the following pics 
![image](https://github.com/pycaret/pycaret/assets/79689100/88ae69e2-bf46-41bd-91e4-8f42de66cd83)

I alterate these path but then pipeline as a memory issue, I guess it could be something cached, but I don t have this cache on my computer,

Great day :)

**Comment by ngupta23** [comment]
Not sure how to reproduce this problem. We have not encountered this, but if you can somehow share code + data that we can use to reproduce this, we can have a look at it.

**Comment by madinshibo** [comment]
Hi team,

**Comment by madinshibo** [comment]
Hi team,

**Comment by madinshibo** [comment]
Hi team,
I met the same issue when it comes to two PC of mine. First I trained and used **save_model** to get pkl file (model and pipline) on PC **A**.Secondly I moved the pkl file to PC **B**, using **load_model** successfully but got error below when using **predict_model** on **B**, which exactly like the issue above indicating that it can not find **pipline** stored on **A** while  the code is running on **B**. 
` FileNotFoundError for : 
path\\to\\user\\A\\Temp\\joblib\\pycaret\\internal\\pipeline\\_full_transform\\func_code.py`
Both of PC A and B with python==3.8 and pycaret 3.0.0, so maybe it has nothing to do with version conflict. I guess the model and pipline save by **save_model** can be used out of pycaret  but in same environment or computer?  
![image](https://github.com/pycaret/pycaret/assets/49478786/b99d5b38-a5c2-4b05-8a4f-1f898f56d5ee)

**Comment by Yard1** [comment]
Hi, this should be fixed in the next release (targeting next weekend)
