### ISSUE TITLE
`plot_model` in Time Series

### ISSUE THREAD

**Issue by ha-seungwon** [pycaret/pycaret#3597]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

i did plot_model() in my code but image did not save in .png file  
plot_model() save html file in my code plz help me

### Reproducible Example

```python
from pycaret.time_series import *
```

### Expected Behavior

s = setup(data, fh = 3, session_id = 123)
model = s.compare_models()
plot_model(plot = 'ts',save=True)

### Actual Results

```python-traceback
'Time Series Plot.html'
```

### Installed Versions

pycaret=='3.0.2'

**Comment by ngupta23** [comment]
I have verified that both OOP and Functional Interface are working. The file gets save to the path from which you are running.

```python
from pycaret.datasets import get_data
from pycaret.time_series import TSForecastingExperiment, setup, plot_model

data = get_data("airline")

# Functional Interface
setup(data, fh=3, session_id=123)
plot_model(plot="ts", save=True)

# OOP Interface
exp = TSForecastingExperiment()
exp.setup(data, fh=3, session_id=123)
exp.plot_model(plot="ts", save=True)
```

If you are still facing the issue, please provide a completely reproducible example that we can copy-paste and run. Without this, we can not debug the issue.

**Comment by ngupta23** [comment]
Note that the image gets saved as a HTML interactive file not PNG.

**Comment by ha-seungwon** [comment]
but classification, regression plot_model function saved PNG file i think. Is it different with time series plot_model function???

**Comment by ngupta23** [comment]
Yes, we use plotly and save as html by default. If you want to save as png, you can return the figure object instead and save it yourself as PNG (plotly allows you to do that).

**Comment by ha-seungwon** [comment]
Thank :)

can i ask another question??

**Comment by ngupta23** [comment]
Sure if it is related, we can use the same thread. If not, you can close this issue and open a new discussion post or issue depending on the type of question.
