### ISSUE TITLE
[ENH]: How to obtain the number of parameters in a trained model?

### ISSUE THREAD

**Issue by melodyL1** [pycaret/pycaret#3601]
### Describe the feature you want to add to this project

How to obtain the number of parameters in a trained model?

### Describe your proposed solution

How to obtain the number of parameters in a trained model?

### Describe alternatives you've considered, if relevant

How to obtain the number of parameters in a trained model?

### Additional context

How to obtain the number of parameters in a trained model?
![JH Z`G )23W0{ 2DSUKH)7G](https://github.com/pycaret/pycaret/assets/92028510/031fee4b-0fdd-4b32-a5fa-5d8737f5648a)

**Comment by ngupta23** [comment]
These are scikit learn (or compatible) models under the hood. You have access to all the parameters that scikit learn provides. Please refer to the individual libraries to find the parameters.
