### ISSUE TITLE
ValueError: Invalid number of components: 2

### ISSUE THREAD

**Issue by nkalhan** [pycaret/pycaret#361]
Hi any one familiar to this error:

I used the code:
import pycaret.classification import *
exp_reg = setup(data, target = 'Division', high_cardinality_features=['Account Name'], high_cardinality_method='clustering')

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-6ec95d66148c> in <module>
----> 1 exp_reg = setup(data, target = 'Division', high_cardinality_features=['Account Name'], high_cardinality_method='clustering')

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\pycaret\classification.py in setup(data, target, train_size, sampling, sample_estimator, categorical_features, categorical_imputation, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, data_split_shuffle, folds_shuffle, n_jobs, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile)
   1206                                           display_types = display_dtypes_pass, #this is for inferred input box
   1207                                           target_transformation = False, #not needed for classification
-> 1208                                           random_state = seed)
   1209 
   1210     progress.value += 1

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\pycaret\preprocess.py in Preprocess_Path_One(train_data, target_variable, ml_usecase, test_data, categorical_features, numerical_features, time_features, features_todrop, display_types, imputation_type, numeric_imputation_strategy, categorical_imputation_strategy, apply_zero_nearZero_variance, club_rare_levels, rara_level_threshold_percentage, apply_untrained_levels_treatment, untrained_levels_treatment_method, apply_ordinal_encoding, ordinal_columns_and_categories, apply_cardinality_reduction, cardinal_method, cardinal_features, apply_binning, features_to_binn, apply_grouping, group_name, features_to_group_ListofList, apply_polynomial_trigonometry_features, max_polynomial, trigonometry_calculations, top_poly_trig_features_to_select_percentage, scale_data, scaling_method, Power_transform_data, Power_transform_method, target_transformation, target_transformation_method, remove_outliers, outlier_contamination_percentage, outlier_methods, apply_feature_selection, feature_selection_top_features_percentage, remove_multicollinearity, maximum_correlation_between_features, remove_perfect_collinearity, apply_feature_interactions, feature_interactions_to_apply, feature_interactions_top_features_to_select_percentage, cluster_entire_data, range_of_clusters_to_try, apply_pca, pca_method, pca_variance_retained_or_number_of_components, random_state)
   2563     return(pipe.fit_transform(train_data),pipe.transform(test_data))
   2564   else:
-> 2565     return(pipe.fit_transform(train_data))
   2566 
   2567 

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\pipeline.py in fit_transform(self, X, y, **fit_params)
    365         """
    366         fit_params_steps = self._check_fit_params(**fit_params)
--> 367         Xt = self._fit(X, y, **fit_params_steps)
    368 
    369         last_step = self._final_estimator

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\pipeline.py in _fit(self, X, y, **fit_params_steps)
    294                 message_clsname='Pipeline',
    295                 message=self._log_message(step_idx),
--> 296                 **fit_params_steps[name])
    297             # Replace the transformer of the step with the fitted
    298             # transformer. This is necessary when loading the transformer

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\joblib\memory.py in __call__(self, *args, **kwargs)
    350 
    351     def __call__(self, *args, **kwargs):
--> 352         return self.func(*args, **kwargs)
    353 
    354     def call_and_shelve(self, *args, **kwargs):

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    738     with _print_elapsed_time(message_clsname, message):
    739         if hasattr(transformer, 'fit_transform'):
--> 740             res = transformer.fit_transform(X, y, **fit_params)
    741         else:
    742             res = transformer.fit(X, y, **fit_params).transform(X)

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\pycaret\preprocess.py in fit_transform(self, dataset, y)
   1405     # now make PLS
   1406     self.pls = PLSRegression(n_components=2) # since we are only using two componenets to group #PLSRegression(n_components=len(data_t1.columns)-1)
-> 1407     data_pls = self.pls.fit_transform(data_t.drop(self.target,axis=1),data_t[self.target])[0]
   1408 
   1409     # # now we will take one component and then we calculate mean, median, min, max and sd of that one component grouped by the catagorical levels

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\cross_decomposition\_pls.py in fit_transform(self, X, y)
    517         x_scores if Y is not given, (x_scores, y_scores) otherwise.
    518         """
--> 519         return self.fit(X, y).transform(X, y)
    520 
    521     def _more_tags(self):

c:\users\nkalhan\anaconda3\envs\pycaret\lib\site-packages\sklearn\cross_decomposition\_pls.py in fit(self, X, Y)
    292         if self.n_components < 1 or self.n_components > p:
    293             raise ValueError('Invalid number of components: %d' %
--> 294                              self.n_components)
    295         if self.algorithm not in ("svd", "nipals"):
    296             raise ValueError("Got algorithm %s when only 'svd' "

ValueError: Invalid number of components: 2

**Comment by pycaret** [comment]
@nkalhan Can you please upload logs.log file generated in your local directory. Also please provide the details of version you are using, python environment, dataset sample and the environment.

**Comment by nkalhan** [comment]
thank you for reply... please find attached.
      -- my python version is 3.7.7
      -- anaconda environment
      -- i am using my work data. but I can share some details about it. It has ony one feature (text) and one target (text)
      -- Please let me know if there is more information

[logs.log](https://github.com/pycaret/pycaret/files/5029635/logs.log)

**Comment by pycaret** [comment]
@nkalhan Can you please update pycaret to `2.2` and let us know if the issue persists?
