### ISSUE TITLE
Decision tree visualization is not working. in the latest release

### ISSUE THREAD

**Issue by rcshetty3** [pycaret/pycaret#3642]
Hi, I have the same issue in the latest release, please check.

![image](https://user-images.githubusercontent.com/20124925/253925928-6b2b82a4-0dea-4e0d-9713-4ac8ec9262df.png)

           @LerysG @ArtificialZeng @rcshetty3 The issue has been fixed in the latest rc version. Can you try installing pycaret in new env with `pip install --pre pycaret` and try again? It should work.

![image](https://user-images.githubusercontent.com/54699234/203330185-b7889085-3b2a-48ad-90e4-37e67bd3e8e3.png)

_Originally posted by @moezali1 in https://github.com/pycaret/pycaret/issues/2992#issuecomment-1323706381_

**Comment by ngupta23** [comment]
Please provide a complete reproducible example (data + code) so we can debug further.

**Comment by rcshetty3** [comment]
The code is 

# functional API
evaluate_model(tuned_best_model)

# OOP API
#s.evaluate_model(best)

the model is a 'dt'

the experiment is run on the titanic dataset.

I tried with other tree based models as well such as randomforest, it's showing the following error - 
![image](https://github.com/pycaret/pycaret/assets/20124925/ed977e25-2810-4f43-99f2-97f2e6d3cdd1)


Name: pycaret
Version: 3.0.0
Summary: PyCaret - An open source, low-code machine learning library in Python.
Home-page: https://github.com/pycaret/pycaret
Author: Moez Ali
Author-email: moez.ali@queensu.ca
License: MIT
Location: c:\miniconda3\lib\site-packages
Requires: numba, requests, schemdraw, tbats, jinja2, lightgbm, ipywidgets, markupsafe, matplotlib, deprecation, imbalanced-learn, plotly-resampler, statsmodels, sktime, tqdm, psutil, pmdarima, cloudpickle, plotly, category-encoders, xxhash, scikit-plot, pyod, kaleido, pandas, numpy, scipy, nbformat, joblib, ipython, scikit-learn, yellowbrick, importlib-metadata

**Comment by moezali1** [comment]
@rcshetty3 Can you please share the complete reproducible notebook and dataset for us to try and troubleshoot what is causing this?

**Comment by rcshetty3** [comment]
Hi, i've lost access to those files since they were on a machine that died recently. I'll try to reproduce this and share the notebook as soon as i get a minute.
