### ISSUE TITLE
[BUG]: Score based CV-metrics (like AUC) are all zero for custom model

### ISSUE THREAD

**Issue by MarselScheer** [pycaret/pycaret#3656]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

The predict_proba() method of a custom model seems "not to work properly" during evaluation of the model using compare_model(). All AUCs are zero. However, predict_model() shows a non-zero AUC.

### Reproducible Example

```python
from pycaret.datasets import get_data
diabetes = get_data('diabetes')

from pycaret.classification import *
setup(data = diabetes, target = 'Class variable', n_jobs=1, verbose=False)

from sklearn.linear_model import LogisticRegression
from sklearn.base import BaseEstimator, ClassifierMixin
class CustomClassifier(BaseEstimator, ClassifierMixin):

    def __init__(self):
        self.est = LogisticRegression()

    def fit(self, X, y=None):
        self.est.fit(X, y)
        return self
    
    def predict(self, X, y=None):
        return self.est.predict(X)
        
    def predict_proba(self, X, y=None):
        return self.est.predict_proba(X)
    
# AUC is zero for all folds
m = create_model(CustomClassifier())

# AUC is calculated (and class-probs are returned)
predict_model(m, raw_score=True)
```

### Expected Behavior

non-zero AUCs for each of the 10-folds.

### Actual Results

```python-traceback
create_model yields:

 	Accuracy	AUC	Recall	Prec.	F1	Kappa	MCC
Fold	 	 	 	 	 	 	 
0	0.8519	0.0000	0.6316	0.9231	0.7500	0.6499	0.6736
1	0.8519	0.0000	0.7895	0.7895	0.7895	0.6752	0.6752
2	0.7778	0.0000	0.7368	0.6667	0.7000	0.5242	0.5259
3	0.7778	0.0000	0.6842	0.6842	0.6842	0.5128	0.5128
4	0.8148	0.0000	0.6316	0.8000	0.7059	0.5735	0.5820
5	0.7963	0.0000	0.5263	0.8333	0.6452	0.5123	0.5389
6	0.7593	0.0000	0.5263	0.7143	0.6061	0.4384	0.4490
7	0.7170	0.0000	0.5000	0.6000	0.5455	0.3424	0.3454
8	0.7547	0.0000	0.5556	0.6667	0.6061	0.4301	0.4339
9	0.7925	0.0000	0.5556	0.7692	0.6452	0.5038	0.5172
Mean	0.7894	0.0000	0.6137	0.7447	0.6677	0.5163	0.5254
Std	0.0402	0.0000	0.0931	0.0911	0.0692	0.0950	0.0973

predict_model yields:

 	Model	Accuracy	AUC	Recall	Prec.	F1	Kappa	MCC
0	Logistic Regression	0.7316	0.6826	0.5185	0.6462	0.5753	0.3826	0.3875
```

### Installed Versions

<details>
System:
    python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
executable: /opt/conda/bin/python3.10
   machine: Linux-5.15.120+-x86_64-with-glibc2.31

PyCaret required dependencies:
                 pip: 23.1.2
          setuptools: 59.8.0
             pycaret: 3.0.4
             IPython: 8.14.0
          ipywidgets: 7.7.1
                tqdm: 4.65.0
               numpy: 1.23.5
              pandas: 1.5.3
              jinja2: 3.1.2
               scipy: 1.7.3
              joblib: 1.2.0
             sklearn: 1.2.2
                pyod: 1.1.0
            imblearn: 0.10.1
   category_encoders: 2.6.1
            lightgbm: 3.3.2
               numba: 0.57.1
            requests: 2.31.0
          matplotlib: 3.7.1
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.15.0
    plotly-resampler: Not installed
             kaleido: 0.2.1
           schemdraw: 0.15
         statsmodels: 0.14.0
              sktime: 0.21.0
               tbats: 1.1.3
            pmdarima: 2.0.3
              psutil: 5.9.3
          markupsafe: 2.1.3
             pickle5: Not installed
         cloudpickle: 2.2.1
         deprecation: 2.1.0
              xxhash: 3.2.0
           wurlitzer: 3.0.3

PyCaret optional dependencies:
                shap: 0.42.0
           interpret: Not installed
                umap: 0.5.3
    pandas_profiling: 4.3.1
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
          deepchecks: Not installed
             xgboost: 1.7.6
            catboost: 1.2
              kmodes: 0.12.2
             mlxtend: 0.22.0
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: 2.5.1
            hyperopt: 0.2.7
              optuna: 3.2.0
               skopt: 0.9.0
              mlflow: Not installed
              gradio: Not installed
             fastapi: 0.98.0
             uvicorn: 0.22.0
              m2cgen: Not installed
           evidently: Not installed
               fugue: Not installed
           streamlit: Not installed
             prophet: 1.1.1
</details>

**Comment by Yard1** [comment]
@MarselScheer Thanks for the report. Any metric scoring issues will be printed to the log file, created in the directory you run the script from. In this case, the issue is as follows:

```
2023-08-27 22:24:54,480:WARNING:/home/ubuntu/pycaret/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ubuntu/pycaret/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/home/ubuntu/pycaret/clean/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 321, in _score
    y_pred = self._select_proba_binary(y_pred, clf.classes_)
AttributeError: 'CustomClassifier' object has no attribute 'classes_'
```

sklearn expects the `classes_` attribute to be set for such an estimator. Indeed, setting the custom classifier `classes_` to match the internal estimator during fit fixes the issue and AUC is calculated correctly.
