### ISSUE TITLE
[INSTALL]: Pycaret locally

### ISSUE THREAD

**Issue by MrZombie69232** [pycaret/pycaret#3659]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Windows-10-10.0.22621-SP0

### Installation Method

pip install

### pycaret Version

3.0.4

### Python Version

3.9.16

### Description

When I am installing pycaret uisng pip it exits with suprocess error  everytime 

### Installation Logs

<details>

Replace this line with the installation logs.

</details>
  Using cached pandas-1.3.3.tar.gz (4.7 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [247 lines of output]
      Ignoring numpy: markers 'python_version == "3.7" and (platform_machine != "arm64" or platform_system != "Darwin") and platform_machine != "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and (platform_machine != "arm64" or platform_system != "Darwin") and platform_machine != "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_machine == "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "arm64" and platform_system == "Darwin"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.9" and platform_machine == "arm64" and platform_system == "Darwin"' don't match your environment
      Collecting setuptools>=51.0.0
        Using cached setuptools-68.0.0-py3-none-any.whl (804 kB)
      Collecting wheel
        Using cached wheel-0.41.0-py3-none-any.whl (64 kB)
      Collecting Cython<3,>=0.29.21
        Using cached Cython-0.29.36-py2.py3-none-any.whl (988 kB)
      Collecting numpy==1.19.3
        Using cached numpy-1.19.3.zip (7.3 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        Preparing metadata (pyproject.toml) did not run successfully.
        exit code: 1

        [210 lines of output]
        setup.py:67: RuntimeWarning: NumPy 1.19.3 may not yet support Python 3.11.
          warnings.warn(
        Running from numpy source directory.
        setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
          run_build = parse_setuppy_commands()
        Processing numpy/random\_bounded_integers.pxd.in
        Processing numpy/random\bit_generator.pyx
        Processing numpy/random\mtrand.pyx
        Processing numpy/random\_bounded_integers.pyx.in
        Processing numpy/random\_common.pyx
        Processing numpy/random\_generator.pyx
        Processing numpy/random\_mt19937.pyx
        Processing numpy/random\_pcg64.pyx
        Processing numpy/random\_philox.pyx
        Processing numpy/random\_sfc64.pyx
        Cythonizing sources
        blas_opt_info:
        blas_mkl_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries mkl_rt not found in ['C:\\Users\\singh\\anaconda3\\envs\\pyc\\lib', 'C:\\', 'C:\\Users\\singh\\anaconda3\\envs\\pyc\\libs', 'C:\\Users\\singh\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        blis_info:
          libraries blis not found in ['C:\\Users\\singh\\anaconda3\\envs\\pyc\\lib', 'C:\\', 'C:\\Users\\singh\\anaconda3\\envs\\pyc\\libs', 'C:\\Users\\singh\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        openblas_info:
          libraries openblas not found in ['C:\\Users\\singh\\anaconda3\\envs\\pyc\\lib', 'C:\\', 'C:\\Users\\singh\\anaconda3\\envs\\pyc\\libs', 'C:\\Users\\singh\\anaconda3\\Library\\lib']
        get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
        customize GnuFCompiler
        Could not locate executable g77
        Could not locate executable f77
        customize IntelVisualFCompiler
        Could not locate executable ifort
        Could not locate executable ifl
        customize AbsoftFCompiler
        Could not locate executable f90
        customize CompaqVisualFCompiler
        Could not locate executable DF
        customize IntelItaniumVisualFCompiler
        Could not locate executable efl
        customize Gnu95FCompiler
        Could not locate executable gfortran
        Could not locate executable f95
        customize G95FCompiler
        Could not locate executable g95
        customize IntelEM64VisualFCompiler
        customize IntelEM64TFCompiler
        Could not locate executable efort
        Could not locate executable efc
        customize PGroupFlangCompiler
        Could not locate executable flang
        don't know how to compile Fortran code on platform 'nt'
          NOT AVAILABLE

        atlas_3_10_blas_threads_info:
        Setting PTATLAS=ATLAS
          libraries tatlas not found in ['C:\\Users\\singh\\anaconda3\\envs\\pyc\\lib', 'C:\\', 'C:\\Users\\singh\\anaconda3\\envs\\pyc\\libs', 'C:\\Users\\singh\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        atlas_3_10_blas_info:
          libraries satlas not found in ['C:\\Users\\singh\\anaconda3\\envs\\pyc\\lib', 'C:\\', 'C:\\Users\\singh\\anaconda3\\envs\\pyc\\libs', 'C:\\Users\\singh\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        atlas_blas_threads_info:
        Setting PTATLAS=ATLAS
          libraries ptf77blas,ptcblas,atlas not found in ['C:\\Users\\singh\\anaconda3\\envs\\pyc\\lib', 'C:\\', 'C:\\Users\\singh\\anaconda3\\envs\\pyc\\libs', 'C:\\Users\\singh\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        atlas_blas_info:
          libraries f77blas,cblas,atlas not found in ['C:\\Users\\singh\\anaconda3\\envs\\pyc\\lib', 'C:\\', 'C:\\Users\\singh\\anaconda3\\envs\\pyc\\libs', 'C:\\Users\\singh\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        accelerate_info:
          NOT AVAILABLE

        C:\Users\singh\AppData\Local\Temp\pip-install-kx39pu19\numpy_3b45584b81cc40c5be697c6003648c60\numpy\distutils\system_info.py:1914: UserWarning:
            Optimized (vendor) Blas libraries are not found.
            Falls back to netlib Blas library which has worse performance.
            A better performance should be easily gained by switching
            Blas library.
          if self._calc_info(blas):
        blas_info:
          libraries blas not found in ['C:\\Users\\singh\\anaconda3\\envs\\pyc\\lib', 'C:\\', 'C:\\Users\\singh\\anaconda3\\envs\\pyc\\libs', 'C:\\Users\\singh\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        C:\Users\singh\AppData\Local\Temp\pip-install-kx39pu19\numpy_3b45584b81cc40c5be697c6003648c60\numpy\distutils\system_info.py:1914: UserWarning:
            Blas (http://www.netlib.org/blas/) libraries not found.
            Directories to search for the libraries can be specified in the
            numpy/distutils/site.cfg file (section [blas]) or by setting
            the BLAS environment variable.
          if self._calc_info(blas):
        blas_src_info:
          NOT AVAILABLE

        C:\Users\singh\AppData\Local\Temp\pip-install-kx39pu19\numpy_3b45584b81cc40c5be697c6003648c60\numpy\distutils\system_info.py:1914: UserWarning:
            Blas (http://www.netlib.org/blas/) sources not found.
            Directories to search for the sources can be specified in the
            numpy/distutils/site.cfg file (section [blas_src]) or by setting
            the BLAS_SRC environment variable.
          if self._calc_info(blas):
          NOT AVAILABLE

        non-existing path in 'numpy\\distutils': 'site.cfg'
        lapack_opt_info:
        lapack_mkl_info:
          libraries mkl_rt not found in ['C:\\Users\\singh\\anaconda3\\envs\\pyc\\lib', 'C:\\', 'C:\\Users\\singh\\anaconda3\\envs\\pyc\\libs', 'C:\\Users\\singh\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        openblas_lapack_info:
          libraries openblas not found in ['C:\\Users\\singh\\anaconda3\\envs\\pyc\\lib', 'C:\\', 'C:\\Users\\singh\\anaconda3\\envs\\pyc\\libs', 'C:\\Users\\singh\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        openblas_clapack_info:
          libraries openblas,lapack not found in ['C:\\Users\\singh\\anaconda3\\envs\\pyc\\lib', 'C:\\', 'C:\\Users\\singh\\anaconda3\\envs\\pyc\\libs', 'C:\\Users\\singh\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        flame_info:
          libraries flame not found in ['C:\\Users\\singh\\anaconda3\\envs\\pyc\\lib', 'C:\\', 'C:\\Users\\singh\\anaconda3\\envs\\pyc\\libs', 'C:\\Users\\singh\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        atlas_3_10_threads_info:
        Setting PTATLAS=ATLAS
          libraries lapack_atlas not found in C:\Users\singh\anaconda3\envs\pyc\lib
          libraries tatlas,tatlas not found in C:\Users\singh\anaconda3\envs\pyc\lib
          libraries lapack_atlas not found in C:\
          libraries tatlas,tatlas not found in C:\
          libraries lapack_atlas not found in C:\Users\singh\anaconda3\envs\pyc\libs
          libraries tatlas,tatlas not found in C:\Users\singh\anaconda3\envs\pyc\libs
          libraries lapack_atlas not found in C:\Users\singh\anaconda3\Library\lib
          libraries tatlas,tatlas not found in C:\Users\singh\anaconda3\Library\lib
        <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
          NOT AVAILABLE

        atlas_3_10_info:
          libraries lapack_atlas not found in C:\Users\singh\anaconda3\envs\pyc\lib
          libraries satlas,satlas not found in C:\Users\singh\anaconda3\envs\pyc\lib
          libraries lapack_atlas not found in C:\
          libraries satlas,satlas not found in C:\
          libraries lapack_atlas not found in C:\Users\singh\anaconda3\envs\pyc\libs
          libraries satlas,satlas not found in C:\Users\singh\anaconda3\envs\pyc\libs
          libraries lapack_atlas not found in C:\Users\singh\anaconda3\Library\lib
          libraries satlas,satlas not found in C:\Users\singh\anaconda3\Library\lib
        <class 'numpy.distutils.system_info.atlas_3_10_info'>
          NOT AVAILABLE

        atlas_threads_info:
        Setting PTATLAS=ATLAS
          libraries lapack_atlas not found in C:\Users\singh\anaconda3\envs\pyc\lib
          libraries ptf77blas,ptcblas,atlas not found in C:\Users\singh\anaconda3\envs\pyc\lib
          libraries lapack_atlas not found in C:\
          libraries ptf77blas,ptcblas,atlas not found in C:\
          libraries lapack_atlas not found in C:\Users\singh\anaconda3\envs\pyc\libs
          libraries ptf77blas,ptcblas,atlas not found in C:\Users\singh\anaconda3\envs\pyc\libs
          libraries lapack_atlas not found in C:\Users\singh\anaconda3\Library\lib
          libraries ptf77blas,ptcblas,atlas not found in C:\Users\singh\anaconda3\Library\lib
        <class 'numpy.distutils.system_info.atlas_threads_info'>
          NOT AVAILABLE

        atlas_info:
          libraries lapack_atlas not found in C:\Users\singh\anaconda3\envs\pyc\lib
          libraries f77blas,cblas,atlas not found in C:\Users\singh\anaconda3\envs\pyc\lib
          libraries lapack_atlas not found in C:\
          libraries f77blas,cblas,atlas not found in C:\
          libraries lapack_atlas not found in C:\Users\singh\anaconda3\envs\pyc\libs
          libraries f77blas,cblas,atlas not found in C:\Users\singh\anaconda3\envs\pyc\libs
          libraries lapack_atlas not found in C:\Users\singh\anaconda3\Library\lib
          libraries f77blas,cblas,atlas not found in C:\Users\singh\anaconda3\Library\lib
        <class 'numpy.distutils.system_info.atlas_info'>
          NOT AVAILABLE

        lapack_info:
          libraries lapack not found in ['C:\\Users\\singh\\anaconda3\\envs\\pyc\\lib', 'C:\\', 'C:\\Users\\singh\\anaconda3\\envs\\pyc\\libs', 'C:\\Users\\singh\\anaconda3\\Library\\lib']
          NOT AVAILABLE

        C:\Users\singh\AppData\Local\Temp\pip-install-kx39pu19\numpy_3b45584b81cc40c5be697c6003648c60\numpy\distutils\system_info.py:1748: UserWarning:
            Lapack (http://www.netlib.org/lapack/) libraries not found.
            Directories to search for the libraries can be specified in the
            numpy/distutils/site.cfg file (section [lapack]) or by setting
            the LAPACK environment variable.
          return getattr(self, '_calc_info_{}'.format(name))()
        lapack_src_info:
          NOT AVAILABLE

        C:\Users\singh\AppData\Local\Temp\pip-install-kx39pu19\numpy_3b45584b81cc40c5be697c6003648c60\numpy\distutils\system_info.py:1748: UserWarning:
            Lapack (http://www.netlib.org/lapack/) sources not found.
            Directories to search for the sources can be specified in the
            numpy/distutils/site.cfg file (section [lapack_src]) or by setting
            the LAPACK_SRC environment variable.
          return getattr(self, '_calc_info_{}'.format(name))()
          NOT AVAILABLE

        numpy_linalg_lapack_lite:
          FOUND:
            language = c
            define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]

        C:\Users\singh\AppData\Local\Temp\pip-build-env-82m1_2r0\overlay\Lib\site-packages\setuptools\_distutils\dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
          warnings.warn(msg)
        running dist_info
        running build_src
        build_src
        building py_modules sources
        creating build
        creating build\src.win-amd64-3.11
        creating build\src.win-amd64-3.11\numpy
        creating build\src.win-amd64-3.11\numpy\distutils
        building library "npymath" sources
        error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by celestinoxp** [comment]
i think your installation is using cached old files, try it:

use uninstall command 2 times because i found some problems about installations

```
pip uninstall pycaret -y
pip uninstall pycaret -y

pip uninstall pandas -y
pip uninstall pandas -y

pip cache purge

pip install pycaret
```

what is doing?
1 - make sure pycaret is completly removed
2 - make sure pycaret is completly removed
3 - clean cache
4 - install pycaret. if you want all extras install like this `pip install pycaret[full]`

**Comment by luminoso** [comment]
I'm facing same problem. `pycaret` fails to install in a completely new environment.

Steps to reproduce:

1. Create an empty directory: `cd $(mktemp -d)`
2. Create a new venv: `python -m venv .`
3. Activate venv: `source bin/activate`
4. Install pycaret: `pip install pycaret==3.0.4`

There's a problem while installing...

```
  Using cached Werkzeug-2.1.2-py3-none-any.whl (224 kB)
INFO: pip is looking at multiple versions of plotly to determine which version is compatible with other requirements. This could take a while.
Collecting plotly>=5.0.0
  Using cached plotly-5.14.1-py2.py3-none-any.whl (15.3 MB)
INFO: pip is looking at multiple versions of pandas to determine which version is compatible with other requirements. This could take a while.
Collecting pandas<2.0.0,>=1.3.0
  Using cached pandas-1.5.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.0 MB)
  Using cached pandas-1.5.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.0 MB)
  Using cached pandas-1.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.0 MB)
  Using cached pandas-1.4.4.tar.gz (4.9 MB)
```
this keeps looping until the pip solver ends up failing.

in my case it fails building some numpy version.

**Comment by ngupta23** [comment]
Looks like both of you are somehow installing on python 3.11. This is not supported. It is better to try with python 3.10

```
RuntimeError: Cannot install on Python version 3.11.4; only versions >=3.7,<3.11 are supported.
```
