### ISSUE TITLE
Tune model on "mape" for regression is not available ?

### ISSUE THREAD

**Issue by akshaykapila20392** [pycaret/pycaret#366]
My first issue is with mape. Why is it negative ? Isn't mape = mean absolute percentage error which is  
abs(Actual-Predicted)/Actual. Snip below : 

![image](https://user-images.githubusercontent.com/50828423/89441018-2249f980-d76a-11ea-8eb5-8dcd1375e542.png)

Secondly, Why can't I tune my random forest regressor on accuracy metric as "mape".

tuned_rf = tune_model('rf',optimize = 'mape') gives me following error : 

![image](https://user-images.githubusercontent.com/50828423/89441094-4279b880-d76a-11ea-9917-9e4f4e96097d.png)

Documentation says the metrics for regression available are : MAE, MSE, RMSE, R2, RMSLE, MAPE

Any work around ?

**Comment by Yard1** [comment]
You need to pass the model object (created with create_model) as the first argument and then use capital letters.

**Comment by akshaykapila20392** [comment]
Thanks @Yard1 Can you give me an example w.r.t  to my code ?

raf = create_model('rf')
tuned_rf = tune_model(raf) 

OR even if I write what you suggested 

tuned_rf = tune_model(raf, optimize = "MAPE") 

Above code is giving me following error : 

![image](https://user-images.githubusercontent.com/50828423/89444337-2f1d1c00-d76f-11ea-8d6b-59294bdb1679.png)

**Comment by Yard1** [comment]
Are you using PyCaret 2.0?

**Comment by akshaykapila20392** [comment]
> Are you using PyCaret 2.0?

I am using pycaret==1.0.0 . Should I upgrade ?

**Comment by Yard1** [comment]
Yeah, you should. Though in your case, taking that into account, the only thing you need to change in the code in your first post is the capitalization - though IIRC some optimization metrics weren't available in 1.0.0, so it still may not work. Regardless, update to 2.0.0.

**Comment by akshaykapila20392** [comment]
> Yeah, you should. Though in your case, taking that into account, the only thing you need to change in the code in your first post is the capitalization - though IIRC some optimization metrics weren't available in 1.0.0, so it still may not work. Regardless, update to 2.0.0.

Sure , I will update then and yes I used the "mape" in capital words as well and it didn't work as well. Let me try with pycaret ==2. 

I am like 70% completed with my current project and need to tune model w.r.t mape and do not want to switch from caret to manual coding all over again and hence want this to be rectified. 

Will keep you posted on this and once again thankyou

**Comment by pycaret** [comment]
@akshaykapila20392 you should use `MAPE` instead of `mape` when you update it to PyCaret 2.0

**Comment by akshaykapila20392** [comment]
> @akshaykapila20392 you should use `MAPE` instead of `mape` when you update it to PyCaret 2.0

Thank you . It worked but MAPE is still showing as negative , can you tell me how the mape is being calculated ?

**Comment by pycaret** [comment]
```
def calculate_mape(actual, prediction):
        mask = actual != 0
        return (np.fabs(actual - prediction)/actual)[mask].mean()
```

**Comment by pycaret** [comment]
@akshaykapila20392 Do you have negative target values in your dataset?
