### ISSUE TITLE
[BUG]: Lightgbm 4.0 showing debug info

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#3660]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Pycaret allow install latest version of lightgbm, but something has changed, because now is show by dafault all debug info and warnings. can confirm if verbose param values has changed?

![image](https://github.com/pycaret/pycaret/assets/41735311/2e585e6e-dacd-44a2-9d30-cbb46a5d0abf)

### Reproducible Example

```python
setup()...
```

### Expected Behavior

no lightgbm messages after setup

### Actual Results

```python-traceback
.
```

### Installed Versions

<details>
latest-dev
</details>

**Comment by celestinoxp** [comment]
maybe related to https://github.com/microsoft/LightGBM/issues/6014 ?

**Comment by moezali1** [comment]
@celestinoxp Can you try if this command will make it silent?

```
import os
os.environ["PYCARET_CUSTOM_LOGGING_LEVEL"] = "CRITICAL"
```

**Comment by celestinoxp** [comment]
> @celestinoxp Can you try if this command will make it silent?
> 
> ```
> import os
> os.environ["PYCARET_CUSTOM_LOGGING_LEVEL"] = "CRITICAL"
> ```

not working
