### ISSUE TITLE
[BUG]: Custom Metric producing 0 values

### ISSUE THREAD

**Issue by enesbesinci** [pycaret/pycaret#3663]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

im reading moez's pycaret blog "https://towardsdatascience.com/predict-customer-churn-the-right-way-using-pycaret-8ba6541608ac" and when i add this metric to pycaret , when i compare the models, im always facing with 0 values in "profit" column. can someone help me? 
![image](https://github.com/pycaret/pycaret/assets/110482608/297660dd-d23c-48e2-bd56-f8da494e68fb)

### Reproducible Example

```python
# create a custom function
def calculate_profit(y, y_pred):
    tp = np.where((y_pred==1) & (y==1), (5000-1000), 0)
    fp = np.where((y_pred==1) & (y==0), -1000, 0)
    return np.sum([tp,fp])
# add metric to PyCaret
add_metric('profit', 'Profit', calculate_profit)

# compare all models
best_model = compare_models(sort='Profit')
```

### Expected Behavior

![image](https://github.com/pycaret/pycaret/assets/110482608/14745f0e-0836-4654-bf15-38093ee17beb)

### Actual Results

```python-traceback
.
```

### Installed Versions

<details>
Replace this line with the output of the version code above.
</details>

**Comment by enesbesinci** [comment]
@moezali1

**Comment by ngupta23** [comment]
It may have to do with the labels of the target variable being treated differently than 1/0. 

@Yard1 - Did we not see this earlier and/or fix/provide a proposed fix on usewr code?

@enesbesinci - maybe search closed issues related to metrics to see if you can find a solution.

**Comment by ngupta23** [comment]
@Yard1 will add changes to address this shortly per discussion on 2023/07/28.

**Comment by moezali1** [comment]
closing this issue as its duplicate. Track here: #3491
