### ISSUE TITLE
Feature Suggestion: Add CV functionality for Time Series

### ISSUE THREAD

**Issue by clgarciga** [pycaret/pycaret#368]
Hello, I would like to suggest adding [sklearn.model_selection.TimeSeriesSplit](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.TimeSeriesSplit.html#sklearn.model_selection.TimeSeriesSplit) as a CV option in compare_models and related pycaret functionality.

**Comment by pycaret** [comment]
@clgarciga There is a separate `timeseries` module planned for future 2.x release.
