### ISSUE TITLE
[INSTALL]: Fresh install of Pycaret[full] and Jupyterlab raises error

### ISSUE THREAD

**Issue by anogassis** [pycaret/pycaret#3680]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Linux-4.18.0-372.32.1.el8_6.x86_64-x86_64-with-glibc2.28

### Installation Method

pip install

### pycaret Version

3.0.4

### Python Version

3.10

### Goal:
Install `pycaret[full]` and `jupyterlab` in a fresh conda environment to execute the tutorials.

### Steps to reproduce:
`conda create -n pycaret python=3.10`
`conda activate pycaret`
`pip install pycaret[full]`
`pip install jupyterlab`

### Expected behavior:
pycaret and jupyterlab should install without raising any errors.

### Error
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
deepchecks 0.17.4 requires pyzmq<24.0.0, but you have pyzmq 25.1.0 which is incompatible.
notebook 6.5.5 requires pyzmq<25,>=17, but you have pyzmq 25.1.0 which is incompatible.

It is possible to launch Jupyterlab and run the regression tutorial, but Jupyter displays `Error displaying widget` on several of the cell outputs, including `compare_models()`.

I have also tried to install jupyterlab first, then pycaret[full]. The error is different:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyterlab 4.0.3 requires jupyter-server<3,>=2.4.0, but you have jupyter-server 1.24.0 which is incompatible.

### Installation Logs

<details>
[pycaret_install_log.txt](https://github.com/pycaret/pycaret/files/12232672/pycaret_install_log.txt)
</details>

**Comment by moezali1** [comment]
@anogassis Can you try this with Jupyter Notebook instead of jupyter lab and see if the same issue persist? I just tried installing `pycaret[full]` on colab and was able to do so without any issues.

**Comment by anogassis** [comment]
@moezali1 You are correct, no issues detected with the vanilla Jupyter Notebook.
