### ISSUE TITLE
[BUG]: Not working correcly with Target mapping of classification when target values were float values.

### ISSUE THREAD

**Issue by m-kaka** [pycaret/pycaret#3689]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [x] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

When used the classification dataset which target values were folat, it failed to create the models like below.
 
![f1018ecf-7781-4979-8dc3-5559efcb849c](https://github.com/pycaret/pycaret/assets/111260246/a33ad24e-5666-4657-a152-6e07adf7b7c4)

Here is the sample file.
[iris-test.csv](https://github.com/pycaret/pycaret/files/12256172/iris-test.csv)

### Reproducible Example

```python
import pandas as pd
from pycaret.classification import *
data = pd.read_csv("iris-test.csv")
s = setup(data, target = 'species', session_id = 123)
```

### Expected Behavior

Sucess to run the classification even if the target values were float.

### Actual Results

```python-traceback
Any error did not show on console. It only show the below result.
[]
```

### Installed Versions

pycaret                   3.0.4

**Comment by moezali1** [comment]
@m-kaka Target variable cannot be float using `pycaret.classification` module. If you are trying to do classification and your labels truly is in float, you have to figure out a way to encode them before you can use classification model.

However, thanks for bringing this up. We will improve the error message to make it more clear in future.

Thanks
