### ISSUE TITLE
[ENH]: 

### ISSUE THREAD

**Issue by qqfengxueyao** [pycaret/pycaret#3693]
### Describe the feature you want to add to this project

Add custom model to compare_models()

### Describe your proposed solution

I don't have any ideas yet

**Comment by moezali1** [comment]
@qqfengxueyao It is already possible to pass custom models in `compare_models`. You can use the `include` parameter of `compare_models`.

Read more here: https://pycaret.gitbook.io/docs/get-started/functions/train#compare-only-a-few-models
