### ISSUE TITLE
[BUG]:  predict_model() function throwing exception in aws lambda

### ISSUE THREAD

**Issue by arnabksarkar** [pycaret/pycaret#3695]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I have been trying to predict a model using pycaret on aws lambda and its throwing this weird exception. It seems like its trying to write something in the lambda directory which is read only.

### Reproducible Example

```python
import pycaret
from pycaret.classification import *

def lambda_handler(event, context):
  df = df = pd.DataFrame([dict(event)])
  trained_model = load_model('my_model')
  prediction = predict_model(trained_model, raw_score = True, data = df)
```

### Expected Behavior

`prediction = predict_model(trained_model, raw_score = True, data = df)`

this throws an exception while executing lambda. 

I am not sure why it's trying to write a file on the aws lambda.

### Actual Results

```python-traceback
File "/var/lang/lib/python3.10/site-packages/joblib/memory.py", line 763, in _check_previous_func_code
self.store_backend.get_cached_func_code([func_id]))
File "/var/lang/lib/python3.10/site-packages/joblib/_store_backends.py", line 284, in get_cached_func_code
with self._open_item(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/gj/4q4s5q4s64x5jgq07g83rdcc0000gn/T/joblib/pycaret/internal/pipeline/_full_transform/func_code.py'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 39, in lambda_handler
prediction = predict_model(trained_model, raw_score = True, data = df)
File "/var/lang/lib/python3.10/site-packages/pycaret/classification/functional.py", line 2201, in predict_model
return experiment.predict_model(
File "/var/lang/lib/python3.10/site-packages/pycaret/classification/oop.py", line 2843, in predict_model
return super().predict_model(
File "/var/lang/lib/python3.10/site-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py", line 4952, in predict_model
X_test_ = pipeline.transform(
File "/var/lang/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 271, in transform
X, y = self._memory_full_transform(
File "/var/lang/lib/python3.10/site-packages/joblib/memory.py", line 655, in __call__
return self._cached_call(args, kwargs)[0]
File "/var/lang/lib/python3.10/site-packages/pycaret/internal/memory.py", line 350, in _cached_call
self._check_previous_func_code(stacklevel=4)
File "/var/lang/lib/python3.10/site-packages/joblib/memory.py", line 765, in _check_previous_func_code
self._write_func_code(func_code, first_line)
File "/var/lang/lib/python3.10/site-packages/joblib/memory.py", line 717, in _write_func_code
self.store_backend.store_cached_func_code([func_id], func_code)
File "/var/lang/lib/python3.10/site-packages/joblib/_store_backends.py", line 272, in store_cached_func_code
self.create_location(func_path)
File "/var/lang/lib/python3.10/site-packages/joblib/_store_backends.py", line 403, in create_location
mkdirp(location)
File "/var/lang/lib/python3.10/site-packages/joblib/disk.py", line 61, in mkdirp
os.makedirs(d)
File "/var/lang/lib/python3.10/os.py", line 215, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/var/lang/lib/python3.10/os.py", line 215, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/var/lang/lib/python3.10/os.py", line 215, in makedirs
makedirs(head, exist_ok=exist_ok)
[Previous line repeated 5 more times]
File "/var/lang/lib/python3.10/os.py", line 225, in makedirs
mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/var/folders'
```

### Installed Versions

<details>
3.0.0
</details>

**Comment by moezali1** [comment]
The error message you've provided indicates that there's an attempt to write files to a directory on a read-only file system. This typically happens when working with AWS Lambda because the only directory that your Lambda function can write to is /tmp. Other directories are read-only.

To resolve this issue:
- Set `joblib` cache directory: From the traceback, it seems that joblib is trying to cache some results or data. You can set the cache directory of joblib to the writable /tmp directory in AWS Lambda.

```
from joblib import Memory
memory = Memory(location='/tmp/joblib_cache', verbose=0)
```

**Comment by arnabkarsarkar-okta** [comment]
Hi @moezali1 

I appreciate your response. 

I tried setting the memory location but somehow its still trying to write a code or something to the same location and its still giving me the same error. 

I even tried to cache the memory. 

`from joblib import Memory
memory = Memory(location='/tmp/joblib_cache', verbose=0)

s3 = boto3.resource('s3')

@memory.cache 
def lambda_handler(event, context):`

This is my code 

`   df = pd.DataFrame([dict(event)])
    print(df.info())
    try:
        bucketname = os.environ.get('bucket')
        model_name = os.environ.get('model_name')
        trained_model = load_model(model_name=model_name,  platform='aws', authentication={'bucket':bucketname})
        prediction = predict_model(trained_model, raw_score = True, data = df)
        return {
            'statusCode': 200
            'prediction': prediction.iloc[0]["prediction_label"]
        }
    except Exception as exc:
            exc_info = sys.exc_info()
            print(''.join(traceback.format_exception(*exc_info))) 
            return {
                'statusCode': 500,
                'headers': {'Content-Type': 'application/json'},
                'body': ''.join(traceback.format_exception(*exc_info))
            }`

**Comment by PaulinaLP** [comment]
I had a similar error and I checked trained_model._memory_full_transform.store_backend.location (you can run this line in your script) and see that the location in my colleague's computer was saved as location for cached memory. 
So what you can do is to change this location just by putting trained_model._memory_full_transform.store_backend.location="putYourPathHere"
I think that to avoid this in the future when creating a model in setup the argument memory should by put to False. From pycaret website: [memory: str, bool or Memory, default=True
Used to cache the fitted transformers of the pipeline.
If False: No caching is performed. If True: A default temp directory is used. If str: Path to the caching directory.]

**Comment by arnabksarkar** [comment]
> I had a similar error and I checked trained_model._memory_full_transform.store_backend.location (you can run this line in your script) and see that the location in my colleague's computer was saved as location for cached memory. So what you can do is to change this location just by putting trained_model._memory_full_transform.store_backend.location="putYourPathHere" I think that to avoid this in the future when creating a model in setup the argument memory should by put to False. From pycaret website: [memory: str, bool or Memory, default=True Used to cache the fitted transformers of the pipeline. If False: No caching is performed. If True: A default temp directory is used. If str: Path to the caching directory.]

Thank you so much!!!!! OMG.. simply doing this does the trick. 
`trained_model._memory_full_transform.store_backend.location="putYourPathHere"
`
