### ISSUE TITLE
[BUG]: When using Prophet for time series, TypeError: predict_quantiles() got an unexpected keyword argument 'legacy_interface'

### ISSUE THREAD

**Issue by bfdykstra** [pycaret/pycaret#3708]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

As title says, cannot run a prophet model as an estimator for a time series

### Reproducible Example

```python
#### Load data ----
from pycaret.datasets import get_data
y = get_data("airline")

#### Setup experiment ----
from pycaret.time_series import TSForecastingExperiment
exp = TSForecastingExperiment()
exp.setup(data=y, fh=12, session_id=42)

#### Initial Training ----
model = exp.create_model("prophet")
```

### Expected Behavior

I'd expect that the model would be able to finish training properly

### Actual Results

```python-traceback
File ~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/pycaret/time_series/forecasting/oop.py:2464, in TSForecastingExperiment.create_model(self, estimator, fold, round, cross_validation, fit_kwargs, experiment_custom_tags, engine, verbose, **kwargs)
   2461     self._set_engine(estimator=estimator, engine=engine, severity="error")
   2463 try:
-> 2464     return_values = super().create_model(
   2465         estimator=estimator,
   2466         fold=fold,
   2467         round=round,
   2468         cross_validation=cross_validation,
   2469         fit_kwargs=fit_kwargs,
   2470         experiment_custom_tags=experiment_custom_tags,
   2471         verbose=verbose,
   2472         **kwargs,
   2473     )
   2474 finally:
   2475     if engine is not None:
   2476         # Reset the models back to the default engines

File ~/.pyenv/versions/3.9.7/lib/python3.9/site-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py:1753, in _SupervisedExperiment.create_model(self, estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, probability_threshold, experiment_custom_tags, verbose, return_train_score, **kwargs)
...
    391     finally:
    392         # Break a reference cycle with the exception in self._exception
    393         self = None

TypeError: predict_quantiles() got an unexpected keyword argument 'legacy_interface'
```

### Installed Versions

<details>

System:
    python: 3.9.7 (default, Sep 21 2022, 13:01:38)  [Clang 15.0.0 ]
executable: /Users/<my name>/.pyenv/versions/3.9.7/bin/python
   machine: macOS-12.6-arm64-arm-64bit

PyCaret required dependencies:
                 pip: 23.0.1
          setuptools: 57.4.0
             pycaret: 3.0.4
             IPython: 8.5.0
          ipywidgets: 8.0.4
                tqdm: 4.64.1
               numpy: 1.23.3
              pandas: 1.5.0
              jinja2: 3.1.2
               scipy: 1.9.1
              joblib: 1.2.0
             sklearn: 1.1.2
                pyod: 1.1.0
            imblearn: 0.11.0
   category_encoders: 2.6.2
            lightgbm: 4.0.0
               numba: 0.56.2
            requests: 2.28.1
          matplotlib: 3.6.0
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.16.1
    plotly-resampler: Not installed
             kaleido: 0.2.1
           schemdraw: 0.15
         statsmodels: 0.13.2
              sktime: 0.22.0
               tbats: 1.1.3
            pmdarima: 2.0.3
              psutil: 5.9.2
          markupsafe: 2.1.1
             pickle5: Not installed
         cloudpickle: 2.2.0
         deprecation: 2.1.0
              xxhash: 3.3.0
           wurlitzer: 3.0.3

PyCaret optional dependencies:
                shap: Not installed
           interpret: Not installed
                umap: Not installed
    pandas_profiling: Not installed
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
          deepchecks: Not installed
             xgboost: 1.6.2
            catboost: Not installed
              kmodes: Not installed
             mlxtend: Not installed
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: Not installed
              optuna: Not installed
               skopt: Not installed
              mlflow: Not installed
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: Not installed
           evidently: Not installed
               fugue: Not installed
           streamlit: Not installed
             prophet: 1.1.4

</details>

**Comment by ngupta23** [comment]
Somehow your installation has not honored the pycaret requirement that sktime must be < 0.22.0. Can you downgrade sktime to one version below 0.22.0?

https://github.com/pycaret/pycaret/blob/dda93659a78649527d2448646b72cd4ff2b8512a/requirements.txt#L40-L43

**Comment by bfdykstra** [comment]
Thank you that worked!

For posterity, `sktime===0.21.1` did not work and received the same error. However `sktime===0.20.0` did work.

Appreciate your response and the work you do!
