### ISSUE TITLE
suggestion : big data imputation 

### ISSUE THREAD

**Issue by atwahsz** [pycaret/pycaret#372]
if it's possible to add this feature where to predict missing values weather it's a class or a number as preprocessing prior to modeling

train on non naan and predict nan values for every feature missing

**Comment by pycaret** [comment]
@atwahsz Can you please give some example?

**Comment by atwahsz** [comment]
https://github.com/epsilon-machine/missingpy

**Comment by pycaret** [comment]
@atwahsz Thanks. Will have a look soon.
