### ISSUE TITLE
[BUG]: pycaret tests failing (parallel error)

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#3721]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

some tests in pycaret failing with these messages:
FAILED tests/test_time_series_engines.py::test_engines_setup_global_args - TypeError: AutoARIMA.__init__() got an unexpected keyword argument 'parallel'
FAILED tests/test_time_series_engines.py::test_create_model_engines_local_args - TypeError: AutoARIMA.__init__() got an unexpected keyword argument 

i found a pr in sktime package saying the problem maybe related to statsforecast, see: https://github.com/sktime/sktime/commit/748106ae78c3e1c7112d88fb99acdb12c4268381

we can find a different solution or the same

### Reproducible Example

```python
.
```

### Expected Behavior

.

### Actual Results

```python-traceback
FAILED tests/test_time_series_engines.py::test_engines_setup_global_args - TypeError: AutoARIMA.__init__() got an unexpected keyword argument 'parallel'
FAILED tests/test_time_series_engines.py::test_create_model_engines_local_args - TypeError: AutoARIMA.__init__() got an unexpected keyword argument
```

### Installed Versions

<details>
github latest
</details>

**Comment by celestinoxp** [comment]
More context: https://github.com/Nixtla/statsforecast/issues/576

**Comment by ngupta23** [comment]
Thanks for reporting. There PR above should fix this.
