### ISSUE TITLE
[BUG]: Support Pandas v2.1

### ISSUE THREAD

**Issue by celestinoxp** [pycaret/pycaret#3722]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

sktime is working to support new pandas 2.1, we should do the same (https://github.com/sktime/sktime/pull/5185)

more context: since pandas 1.5.3, have various releases we not support, ex: pandas 2, 2,0.1, 2.0,2, 2.0.3 and now 2.1

time to update!

### Reproducible Example

```python
.
```

### Expected Behavior

.

### Actual Results

```python-traceback
.
```

### Installed Versions

<details>
latest
</details>

**Comment by celestinoxp** [comment]
more info: pandas 2.1 only accepts python 3.9 or higher, we should use this in requirements.txt

**Comment by celestinoxp** [comment]
new version of pandas is 2.1.1

**Comment by akaymd** [comment]
I am using sqlalchemy >= 2.0 for my project.
Some features of SQLAlchemy >= 2.0 are only available in pandas >= 2.0.
So I have no choice but to use pandas >= 2.0.

I hope this issue will be resolved.

**Comment by celestinoxp** [comment]
new version of pandas is 2.1.2. pycaret still not supporting pandas 2.x ?!
I have installed manually pandas version 2 and works fine!
