### ISSUE TITLE
[ENH]: Access to Preprocessed Data for Use in Other Frameworks

### ISSUE THREAD

**Issue by hibana2077** [pycaret/pycaret#3781]
### Describe the feature you want to add to this project

I propose adding a feature that allows users to easily extract the preprocessed training and test datasets after running the setup function. This feature would be particularly useful for users who wish to use PyCaret's preprocessing capabilities but want to employ other machine learning frameworks for model training.

### Describe your proposed solution

1. Extend the `get_config()` function or introduce a new function that can also retrieve the preprocessing pipeline.
2. Allow users to apply this pipeline to new data (e.g., a separate test dataset) to obtain a preprocessed DataFrame.

The function could look something like this:

```python
# For training data
preprocessed_train_data = get_preprocessed_data(type='train')

# For test data
preprocessed_test_data = get_preprocessed_data(data=test_data, type='test')
```

### Describe alternatives you've considered, if relevant

An alternative would be to manually replicate the preprocessing steps in another framework, but this could be error-prone and time-consuming. Another alternative could be to use the entire dataset in the `setup` function and then split the preprocessed data into training and test sets, but this approach might not be practical for all use-cases.

### Additional context

Being able to easily extract preprocessed data would make PyCaret more flexible and broaden its applicability. Users could take advantage of PyCaret's powerful preprocessing capabilities while still using their preferred machine learning models and frameworks for training.

**Comment by Rodrigolorcas** [comment]
You already can get the transformed data with get_config() params. Ill attach a picture with the highlighted params:
![image](https://github.com/pycaret/pycaret/assets/54085915/b694fc34-8527-4ed5-93a7-dfb53872de87)


I would love to get the pipeline to another framworks, for example, in some cheap clusters, you cannot install the whole pycaret dependencies, so would be great if you can just use the pipeline to call the transformers and easily transform our datasets.

**Comment by hibana2077** [comment]
Thank you so much for solving my problem and providing me with the guidance on how to use the get_config() function to access the transformed data and pipeline parameters. Your help is greatly appreciated!
