### ISSUE TITLE
[BUG]: Not getting prediction_score

### ISSUE THREAD

**Issue by jhaanuj2108** [pycaret/pycaret#3823]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

After running the compare_models, I am running the predict_model(best_model) on the hold out data, but I am not getting any prediction_score.
My best model is 
```
RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001)
```

I am getting the score for other models like Linear Discriminant Analysis, Logistic Regression, Naive Bayes. Is there a list of models for which I might not get the prediction score?

### Reproducible Example

```python
# load sample dataset
from pycaret.classification import *
from pycaret.datasets import get_data

data = get_data('diabetes')
s = setup(data, target = 'Class variable', session_id = 123)
best = compare_models(include = ['ridge'])
predictions = predict_model(best)
print(predictions)
```

### Expected Behavior

I am expecting a prediction_score column in predictions. 

### Actual Results

```python-traceback
No prediction_Score column present in predictions
```

### Installed Versions

<details>

System:
    python: 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:38:37) [MSC v.1916 64 bit (AMD64)]
executable: c:\Users\jhaan\anaconda3\python.exe
   machine: Windows-10-10.0.22621-SP0

PyCaret required dependencies:
                 pip: 23.3.1
          setuptools: 68.0.0
             pycaret: 3.2.0
             IPython: 8.12.0
          ipywidgets: 8.0.4
                tqdm: 4.65.0
               numpy: 1.24.3
              pandas: 1.5.3
              jinja2: 3.1.2
               scipy: 1.10.1
              joblib: 1.2.0
             sklearn: 1.2.2
                pyod: 1.1.1
            imblearn: 0.10.1
   category_encoders: 2.6.3
            lightgbm: 4.1.0
               numba: 0.57.0
            requests: 2.31.0
          matplotlib: 3.6.0
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.9.0
    plotly-resampler: Not installed
             kaleido: 0.2.1
           schemdraw: 0.15
         statsmodels: 0.14.0
              sktime: 0.21.1
               tbats: 1.1.3
            pmdarima: 2.0.4
              psutil: 5.9.0
          markupsafe: 2.1.1
             pickle5: Not installed
         cloudpickle: 2.2.1
         deprecation: 2.1.0
              xxhash: 3.4.1
           wurlitzer: Not installed

PyCaret optional dependencies:
                shap: Not installed
           interpret: Not installed
                umap: Not installed
     ydata_profiling: Not installed
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
          deepchecks: Not installed
             xgboost: Not installed
            catboost: Not installed
              kmodes: Not installed
             mlxtend: Not installed
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: Not installed
              optuna: Not installed
               skopt: Not installed
              mlflow: Not installed
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: Not installed
           evidently: Not installed
               fugue: Not installed
           streamlit: Not installed
             prophet: Not installed
</details>

**Comment by SarthakNikhal** [comment]
Can I work on this issue?

**Comment by jhaanuj2108** [comment]
> Can I work on this issue?

By all means, if you're asking me. :)

**Comment by tvdboom** [comment]
The column is called `prediction_label` for classification tasks

**Comment by SarthakNikhal** [comment]
@tvdboom is there any fix required? how can i help

**Comment by tvdboom** [comment]
unless I misunderstood the issue, there is no fix required since this is not a bug. I'll close, but feel free to reopen
