### ISSUE TITLE
[INSTALL]:  update in annaconda/snowflake

### ISSUE THREAD

**Issue by shuaiwang88** [pycaret/pycaret#3845]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

snowpark

### Installation Method

pip install

### pycaret Version

3.0.2

### Python Version

3.8

### Description

Not able to find the latest in https://repo.anaconda.com/pkgs/snowflake/

### Installation Logs

just wanted to use the latest version in snowpark.

**Comment by tvdboom** [comment]
The snowpark conda channel is managed by Snowflake and not by pycaret. They are responsible for providing the latest package versions. We can't do anything about that matter.
