### ISSUE TITLE
[BUG]: when I run tune model it it gives me ValueError: _CURRENT_EXPERIMENT global variable is not set. Please run setup() first error

### ISSUE THREAD

**Issue by teto2005** [pycaret/pycaret#3868]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I get this error when I want to tune the model. Although I have used setup()  as present in the code:
`from pycaret.classification import setup
from pycaret.classification import compare_models
from pycaret.clustering import create_model

# setup the dataset
grid = setup(data=data, target='variable')
# train model
rf = create_model('rf)

#tune model
tuned_rf = tune_model(rf)`

### Reproducible Example

```python
from pycaret.classification import setup
from pycaret.classification import compare_models
from pycaret.clustering import create_model

# setup the dataset
grid = setup(data=data, target='variable')
# train model
rf = create_model('rf)

#tune model
tuned_rf = tune_model(rf)`
```

### Expected Behavior

ValueError                                Traceback (most recent call last)
Input In [25], in <cell line: 9>()
      7 grid = setup(data=data_full, target='Class')
      8 # train model
----> 9 rf = create_model('rf')
     11 #tune model
     12 tuned_rf = tune_model(rf)

File ~\AppData\Roaming\Python\Python39\site-packages\pycaret\utils\generic.py:964, in check_if_global_is_not_none.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    962 for name, message in global_names.items():
    963     if globals_d[name] is None:
--> 964         raise ValueError(message)
    965 return func(*args, **kwargs)

ValueError: _CURRENT_EXPERIMENT global variable is not set. Please run setup() first.

### Actual Results

```python-traceback
ValueError                                Traceback (most recent call last)
Input In [25], in <cell line: 9>()
      7 grid = setup(data=data_full, target='Class')
      8 # train model
----> 9 rf= create_model('rf')
     11 #tune model
     12 tuned_rf = tune_model(rf)

File ~\AppData\Roaming\Python\Python39\site-packages\pycaret\utils\generic.py:964, in check_if_global_is_not_none.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    962 for name, message in global_names.items():
    963     if globals_d[name] is None:
--> 964         raise ValueError(message)
    965 return func(*args, **kwargs)

ValueError: _CURRENT_EXPERIMENT global variable is not set. Please run setup() first.
```

### Installed Versions

<details>
from pycaret.classification import setup
from pycaret.classification import compare_models
from pycaret.clustering import create_model

# setup the dataset
grid = setup(data=data, target='variable')
# train model
rf = create_model('rf)

#tune model
tuned_rf = tune_model(rf)
</details>

**Comment by celestinoxp** [comment]
your code has errors! imports make no sense. You are mixing classification with clustering...
If you want to do classification, you can change all imports to `from pycaret.classification import *`

you should read the docs: https://pycaret.readthedocs.io/en/stable/api/classification.html

**Comment by teto2005** [comment]
Thanks
