### ISSUE TITLE
[DOC]: Slack invite link is out of date

### ISSUE THREAD

**Issue by pascal456** [pycaret/pycaret#3880]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

- pycaret.gitbook.io

### Documentation problem

- [pycaret.gitbook.io](pycaret.gitbook.io) shows a join slack link
- link is outdated
- current link is: https://join.slack.com/t/pycaret/shared_invite/zt-row9phbm-BoJdEVPYnGf7_NxNBP307w

### Suggested fix for documentation

- Update the link with a new / refreshed one

**Comment by norbit8** [comment]
The link that you've shared is inactive

**Comment by pascal456** [comment]
link is still out of date

**Comment by soham2710** [comment]
https://join.slack.com/t/pycaret/shared_invite/zt-2honw3rhy-U29vEnfgNjlQ8~T5mu7qOg

This link expires in 30 days.

**Comment by soham2710** [comment]
If someone wants to join the slack channel, they can use this link for the next 30 days, https://join.slack.com/t/pycaret/shared_invite/zt-2lvxjwp9v-8DJc9NKsFLZQJNBvjk83Bg

If not then please drop me a message on Linkedin https://www.linkedin.com/in/soham-sharma/ and I can share with you the link incase this one gets expired.
