### ISSUE TITLE
    y_gotdata=loaded_model.predict(np.array([test_list])) AttributeError: 'numpy.ndarray' object has no attribute 'predict'

### ISSUE THREAD

**Issue by OCTO16042020-Rahul** [pycaret/pycaret#389]
Hi pycaret team!
In flask almost done with upto the generation only in the last step i got the error that is AttributeError: 'numpy.ndarray' object has no attribute 'predict'.plz resolve this error.

**Comment by pycaret** [comment]
@rkharatmol123 Can you please provide more details such as your code, link to repo etc.
