### ISSUE TITLE
[BUG]: The table of best models does not present the AUC - Classification Model And the api presents error with pydantic

### ISSUE THREAD

**Issue by JuanBaldemarG** [pycaret/pycaret#3916]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

The table of best models does not present the AUC

### Reproducible Example

```python
from pycaret.datasets import get_data
df = get_data ("iris")
import pandas as pd
from pycaret.classification import *
df_train =df.sample(frac=.7, random_state=786)
df_train.shape
df_train.head()
df.test = df.drop(df_train.index)
df.test.shape
df.test.head()
df_train.reset_index(drop=True, inplace=True)
df_train.head()
from pycaret.classification import*
clas = setup(data=df_train,
            target = "species",
            session_id=123)
best = compare_models()
tuned_rf = tune_model(rf)
create_api(tuned_rf, 'my_first_api')
!python my_first_api.py
```

### Expected Behavior

Table best models incomplete- AUC
![TABLA AUC PYCARET](https://github.com/pycaret/pycaret/assets/147532295/e14edacb-b8f3-4506-b696-0bab6f349d27)

this is the error of api instruction..

Traceback (most recent call last):
  File "C:\Users\bgarz\pycaret\my_first_api.py", line 16, in <module>
    input_model = create_model("my_first_api_input", **{'sepal_length': 6.400000095367432, 'sepal_width': 3.200000047683716, 'petal_length': 5.300000190734863, 'petal_width': 2.299999952316284})
  File "C:\Users\bgarz\miniconda3b\lib\site-packages\pydantic\main.py", line 1490, in create_model
    return meta(
  File "C:\Users\bgarz\miniconda3b\lib\site-packages\pydantic\_internal\_model_construction.py", line 92, in __new__
    private_attributes = inspect_namespace(
  File "C:\Users\bgarz\miniconda3b\lib\site-packages\pydantic\_internal\_model_construction.py", line 384, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `sepal_length = 6.400000095367432`. All model fields require a type annotation; if `sepal_length` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

For further information visit https://errors.pydantic.dev/2.6/u/model-field-missing-annotation
predict_model(tuned_rf)

### Actual Results

```python-traceback
TABLE AUC PRESENTS ONLY "0" VALUES.

EXAMPLE WITH IRIS DATA SET.

the api doesn`t work ... shows error.
```

### Installed Versions

<details>
Replace this line with the output of the version code above.
</details>
3.3.0

**Comment by celestinoxp** [comment]
the problem with AUC metrics is being investigated, as are the pydantic messages... thank you

**Comment by JuanBaldemarG** [comment]
I've just tried it with pydantic<2..and it worked..  Might be good to upgrade... thanks ..
