### ISSUE TITLE
Is it possible to have user defined loss function?

### ISSUE THREAD

**Issue by zhaoli-IHEP** [pycaret/pycaret#392]
Is it possible to have user defined loss function? We did not find this in the tutorial.

**Comment by pycaret** [comment]
Not yet. @zhaoli-IHEP

**Comment by pycaret** [comment]
I will add this as enhancement for future sprints.

**Comment by pycaret** [comment]
`custom_scorer` param is now added in `tune_model` function in `classification.py` and `regression.py`

**Comment by zhaoli-IHEP** [comment]
> `custom_scorer` param is now added in `tune_model` function in `classification.py` and `regression.py`

Thank you for this improvement. Is it possible to use `custom_scorer` in `compare_models`?

**Comment by Yard1** [comment]
Not yet, but it will be possible in the next version.

**Comment by zhaoli-IHEP** [comment]
In the result of `tune_model` function, how to show the result of `custom_scorer`, and how to use `custom_scroer` for the option `optimize`? Thank you.
