### ISSUE TITLE
[BUG]: Unable to import pycaret nlp

### ISSUE THREAD

**Issue by Akshat111111** [pycaret/pycaret#3933]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-10-3484db4205ec>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from pycaret.nlp import*

ModuleNotFoundError: No module named 'pycaret.nlp'

### Reproducible Example

```python
I am using this version 2.3.10, but cant import the nlp module.
```

### Expected Behavior

The code should run succesfully as I have already  installed pycaret but Its saying module not found

### Actual Results

```python-traceback
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-10-3484db4205ec> in <cell line: 1>()
----> 1 from pycaret.nlp import*

ModuleNotFoundError: No module named 'pycaret.nlp'
```

### Installed Versions

<details>
 2.3.10
</details>

**Comment by celestinoxp** [comment]
can you use latest version?

**Comment by Akshat111111** [comment]
I have upgraded it to latest still, pycaret nlp is not available

**Comment by aniiketbarphe** [comment]
i am also facing same issue

**Comment by celestinoxp** [comment]
I went to investigate, and discovered that the nlp module was intentionally removed, see here:
https://github.com/pycaret/pycaret/pull/3299

**Comment by celestinoxp** [comment]
> But it should be available in version 2.0??

I think the best person to provide you with details is: @Yard1

**Comment by Akshat111111** [comment]
But the maintainers are not responding

**Comment by ngupta23** [comment]
pycaret nlp was deprecated from version 3.0.0. It should be available in pycaret 2.x.
You can check out the release notes here: https://github.com/pycaret/pycaret/releases/tag/3.0.0

**Comment by Akshat111111** [comment]
Thankyou so much for it
