### ISSUE TITLE
Plot Model-how to Set image resolution and output high quality image

### ISSUE THREAD

**Issue by lcg29** [pycaret/pycaret#394]
I want to plot high-quality images, it doesn't seem to be in the current guidance. In addition, plot style also can't find. 
Thanks.

**Comment by pycaret** [comment]
@lcg29 It's not possible at the moment. Please feel free to propose what kind of change would be required inside `plot_model` function to allow high-quality images. We are using `yellowbricks` and `plotly` as backend for visualization. I think `yellowbricks` uses `matplotlib` which allows resolution to be modified.

**Comment by lcg29** [comment]
Yeah，set ` yellowbricks` uses `matplotlib`  is a good idea. Thanks.  

I think `plot_model(modelname, dpi=600)`,  dpi of png maybe an excellent function.

**Comment by pycaret** [comment]
@lcg29 Would you like to work on this?

**Comment by lcg29** [comment]
Thanks for your invitation. I learned Python for less than a month....you know lack of ability. So I can't give you a definite answer. If I have worked out a solution, I will reply to you in time.

**Comment by pycaret** [comment]
@Yard1 Do you want to have a look at this one when you get a chance? 

User story : Can we add `dpi` parameter in `plot_model` to control the high resolution of plots.

**Comment by Yard1** [comment]
I cna take a look

**Comment by ifyoungnet** [comment]
how to set dpi or scale when using interpret_model()?
