### ISSUE TITLE
[DOC]: Installation on Mac M1

### ISSUE THREAD

**Issue by asmaier** [pycaret/pycaret#3949]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://pycaret.gitbook.io/docs/get-started/installation

### Documentation problem

Missing installation guide for Mac computers

### Suggested fix for documentation

To install on Mac (with Apple Silicon) do the following

```
brew install cmake libomp
poetry add kaleido==0.2.1
poetry add pycaret
```

See:
- https://stackoverflow.com/questions/74566704/cannot-install-lightgbm-3-3-3-on-apple-silicon
- https://stackoverflow.com/questions/70993385/how-to-add-kaleido-package-to-poetry-lock-file

**Comment by celestinoxp** [comment]
@moezali1 FYI
