### ISSUE TITLE
Some of the required packages are missing in Conda and Conda-Forge.

### ISSUE THREAD

**Issue by Abhinandan1414** [pycaret/pycaret#40]
>> conda install -f -y -q -c conda-forge --file requirements.txt

PackagesNotFoundError: The following packages are not available from current channels:

  - cufflinks==0.17.0
  - kmodes==0.10.1
  - datefinder==0.7.0
  - yellowbrick==1.0.1
  - datetime==4.3

Alternatives would be appreciated. Thanks in advance

**Comment by pycaret** [comment]
@Abhinandan1414 Anything you can do to help?

**Comment by Abhinandan1414** [comment]
I have created package. Please try pip install --extra-index-url https://pypi.anaconda.org/Abhinandan1414/simple pycaret
I have tested it. But could some one verify it and then please close this

**Comment by pycaret** [comment]
Thanks.
