### ISSUE TITLE
interpret_model shows default 20 features only. How to see full list

### ISSUE THREAD

**Issue by swankyshahir** [pycaret/pycaret#401]
interpret_model documentation of SHAP library shows option for (max_display =  int) . so how to implement it in pycaret.
tried my luck with this
TypeError                                 Traceback (most recent call last)
<ipython-input-42-e54a9d40fbe8> in <module>()
----> 1 interpret_model(tuned_et , max_display = 50)

TypeError: interpret_model() got an unexpected keyword argument 'max_display'

Any help would be greatly appreciated

**Comment by pycaret** [comment]
@swankyshahir Will add this in next release.

**Comment by pycaret** [comment]
@swankyshahir I have now added ****kwargs** support in `interpret_model` for `classification.py` and `regression.py`. You can now pass `max_display` or any other applicable param in `interpret_model`.

```
lightgbm = create_model('lightgbm')
interpret_model(lightgbm, max_display = 50)
```
Please sync the latest `master` branch to test the feature. If you are having issues using it, please open another issue.
