### ISSUE TITLE
[ENH]: Ease index requirement for provided test_data

### ISSUE THREAD

**Issue by Ruibin-Liu** [pycaret/pycaret#4039]
### Describe the feature you want to add to this project

Currently if we provide a Pandas DataFrame to `test_data` in the `setup()` function and its indices have overlap with those in `self.data` of the `Preprocessor` instance (mostly like by setting the `data` keyword), the concatenated dataframe as below can have overlapping indices. 
https://github.com/pycaret/pycaret/blob/1ef3451ec9296e2b770c7c86e97533095bf2602b/pycaret/internal/preprocess/preprocessor.py#L261 
It will trigger the error from https://github.com/pycaret/pycaret/blob/1ef3451ec9296e2b770c7c86e97533095bf2602b/pycaret/internal/preprocess/preprocessor.py#L207 in the `set._set_index` function.

It's quite common that a test dataframe is generated INDEPENDENTLY along with the training data, so it's better to easy the index requirement for `test_data`. 

### Describe your proposed solution

Just change `self.data = self._set_index(pd.concat([self.data, test_data]))` to `self.data = self._set_index(pd.concat([self.data, test_data]).reset_index(drop=True))`

### Describe alternatives you've considered, if relevant

We can apply `self._set_index` to `test_data` first by setting the indices of `test_data` according to `set.data.index`. It requires change in that function. This solution could have better compatibility.

### Additional context

I am not sure why that index duplicate checking line was added but if the purpose was to make sure the `test_data` has no overlap with the train data, we can check the data duplication before concatenation and raise an error/warning if there are any.

**Comment by celestinoxp** [comment]
@Ruibin-Liu can you, please,  create a pull-request fixing this?

**Comment by Ruibin-Liu** [comment]
> @Ruibin-Liu can you, please, create a pull-request fixing this?

Just did one. Don't think I should provide a test case for such a simple and predictable change, unless we want to check whether there are REAL duplicates between train & test data and we want to add more code to for that.
