### ISSUE TITLE
Problems with sparse matrix

### ISSUE THREAD

**Issue by ByrdOfAFeather** [pycaret/pycaret#404]
Hi all,
     I'm currently trying to leverage a sklearn CountVectorizer to extract word counts from a textual dataset. As you might imagine, this produces a sparse matrix. While the documentation on the website says that regression can deal with a sparse matrix, I am unable to get it to work. 

-------
What I've tried:
```
test_features = CountVectorizer(stop_words="english")
test_features.fit(data[0])
features = test_features.transform(data[0])
sparse_matrix = pd.DataFrame.sparse.from_spmatrix(features)
sparse_matrix["target"] = data["target"]
```

This gives me a pandas DataFrame with some sparse columns. I have to convert it to a pandas sparse matrix as the original output of the CountVectorizer is a scipy sparse matrix which does not support labeled columns. Labeled columns are required ruing setup. 

The problem is that when setup is run:
`regression_task = setup(sparse_matrix, target="target", numeric_features=[i for i in sparse_matrix.columns if i != "target"])`
I get the following error:

```
Traceback (most recent call last):
  File "C:/Users/matth/AppData/Roaming/JetBrains/PyCharm2020.1/scratches/pycaret_scratch.py", line 15, in <module>
    regression_task = setup(sparse_matrix, target="target", numeric_features=[i for i in sparse_matrix.columns if i != "target"])
  File "C:\VirtualEnvironments\DQG\lib\site-packages\pycaret\regression.py", line 1180, in setup
    data = preprocess.Preprocess_Path_One(train_data=data,
  File "C:\VirtualEnvironments\DQG\lib\site-packages\pycaret\preprocess.py", line 2565, in Preprocess_Path_One
    return(pipe.fit_transform(train_data))
  File "C:\VirtualEnvironments\DQG\lib\site-packages\sklearn\pipeline.py", line 367, in fit_transform
    Xt = self._fit(X, y, **fit_params_steps)
  File "C:\VirtualEnvironments\DQG\lib\site-packages\sklearn\pipeline.py", line 292, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "C:\VirtualEnvironments\DQG\lib\site-packages\joblib\memory.py", line 352, in __call__
    return self.func(*args, **kwargs)
  File "C:\VirtualEnvironments\DQG\lib\site-packages\sklearn\pipeline.py", line 740, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "C:\VirtualEnvironments\DQG\lib\site-packages\pycaret\preprocess.py", line 340, in fit_transform
    data = self.fit(data)
  File "C:\VirtualEnvironments\DQG\lib\site-packages\pycaret\preprocess.py", line 102, in fit
    data.replace([np.inf,-np.inf],np.NaN,inplace=True)
  File "C:\VirtualEnvironments\DQG\lib\site-packages\pandas\core\frame.py", line 4166, in replace
    return super().replace(
  File "C:\VirtualEnvironments\DQG\lib\site-packages\pandas\core\generic.py", line 6703, in replace
    new_data = self._data.replace(
  File "C:\VirtualEnvironments\DQG\lib\site-packages\pandas\core\internals\managers.py", line 589, in replace
    return self.apply("replace", value=value, **kwargs)
  File "C:\VirtualEnvironments\DQG\lib\site-packages\pandas\core\internals\managers.py", line 442, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\VirtualEnvironments\DQG\lib\site-packages\pandas\core\internals\blocks.py", line 790, in replace
    return block.replace(
  File "C:\VirtualEnvironments\DQG\lib\site-packages\pandas\core\internals\blocks.py", line 769, in replace
    blocks = self.putmask(mask, value, inplace=inplace)
  File "C:\VirtualEnvironments\DQG\lib\site-packages\pandas\core\internals\blocks.py", line 1682, in putmask
    new_values[mask] = new
  File "C:\VirtualEnvironments\DQG\lib\site-packages\pandas\core\arrays\sparse\array.py", line 461, in __setitem__
    raise TypeError(msg)
TypeError: SparseArray does not support item assignment via setitem

Process finished with exit code 1
```
which is preventing me from moving forwards. It seems that perhaps this is not the way to use a sparse matrix in which case, what is the correct way to use a sparse matrix? 

----
steps to reproduce:
```
test_features = CountVectorizer(stop_words="english")
test_features.fit([
	"This is a basic.",
	"Example this is a."
])
features = test_features.transform([
	"This is a basic.",
	"Example this is a."
])
sparse_matrix = pd.DataFrame.sparse.from_spmatrix(features)
print(type(sparse_matrix))
sparse_matrix["target"] = [0, 1]
regression_task = setup(sparse_matrix, target="target", numeric_features=[i for i in sparse_matrix.columns if i != "target"])

```

**Comment by pycaret** [comment]
@ByrdOfAFeather Can you show me head and shape of dataframe you are passing in `setup`.

**Comment by ByrdOfAFeather** [comment]
The shape of the dataframe I want to use is (including target column):
(7405, 16396)
The shape of the dataframe in the case of the steps to reproduce is (including target column):
(2, 2)

**Comment by pycaret** [comment]
@ByrdOfAFeather If you can attach the notebook and dataset incase that's not the problem for you. I will try to have a look at it or even somebody else might be able to help quicker. 

Thanks.

**Comment by ByrdOfAFeather** [comment]
This should do the trick, just put the dataset in the same directory as the notebook.
[DQG.zip](https://github.com/pycaret/pycaret/files/5050768/DQG.zip)

Ensure you have the following packages installed:
- scikit-learn 
- pandas
- pycaret (of course)

**Comment by pycaret** [comment]
@ByrdOfAFeather I have tried this. You are right. It doesn't with sparse matrix. Would you like to work on the fix?

**Comment by ByrdOfAFeather** [comment]
I can certainly try to.

**Comment by pycaret** [comment]
@ByrdOfAFeather For now we have changed all the documentation to specifically mention `pd.Dataframe` and removed `sparse-matrix` as a criterion for input param. Once you will make the change, we will change the documentation.

Have you made any progress on the upgrade?

**Comment by sarang-kharpate** [comment]
Getting same error in case of sparse matrix.  Shape of dataframe is data=(215126, 10001) last columns is of label.

**Comment by pycaret** [comment]
@sarang-kharpate is it pandas.DataFrame or are you passing sparse matrix into the `setup` function?

**Comment by ByrdOfAFeather** [comment]
> @ByrdOfAFeather For now we have changed all the documentation to specifically mention `pd.Dataframe` and removed `sparse-matrix` as a criterion for input param. Once you will make the change, we will change the documentation.
> 
> Have you made any progress on the upgrade?

@pycaret I've made some investigation into the issue and tried some quick fixes. There are a few things to note where this is coming from:
- First and foremost the preprocessing pipeline simply doesn't support sparsity. This is the biggest issue as there are a multitude of functions in pre-processing and it's unclear what does and does not support sparsity. As well, there are global variables modified in the pre-processing code, which prevents the program from running without using pre-processing - even if pre-processing isn't necessary. 
- Secondly, it seems that there are models that are tested that don't support sparsity. 

I've got a working case in make a non-sparse matrix convert to a sparse type matrix, but when I try to use a bag-of-word sparse matrix I'm still seeing an error I don't quite understand yet.

**Comment by sarang-kharpate** [comment]
@pycaret I will not be able share the code as such, but process which I have followed is like below 
1. Created a TfidfVectorizer using sklearn 
2. Fit and transform my corpus of 10k words
3. As it is a sparse matrix of scipy format, and Pycaret needs data frame, so create a pd.DataFrame using 
```python training_data = pd.DataFrame.sparse.from_spmatrix(vectorizer)```
4. added another column 'Label' as a (0, 1) in the end and given this data frame as a input to pycaret.

**Comment by Hveemos** [comment]
I bump into the same problem. I'm working with Swedish text data so I cannot rely on the built-in preprocessing in Pycaret. I tried to turn preprocessing off but I still get an error message from scripts with names such as `preprocess.py`.

So for the example from @ByrdOfAFeather 
```
from sklearn.feature_extraction.text import CountVectorizer
test_features = CountVectorizer(stop_words="english")
test_features.fit([
	"This is a basic.",
	"Example this is a."
])
features = test_features.transform([
	"This is a basic.",
	"Example this is a."
])
sparse_matrix = pd.DataFrame.sparse.from_spmatrix(features)
print(type(sparse_matrix))
sparse_matrix["target"] = [0, 1]
regression_task = setup(sparse_matrix, target="target", numeric_features=[i for i in sparse_matrix.columns if i != "target"])
```
Will give these type or errors:

```

c:\Datalab\train_ml\venv\lib\site-packages\pycaret\internal\preprocess.py in fit_transform(self, dataset, y)
    410 
    411         # since this is for training , we dont nees any transformation since it has already been transformed in fit
--> 412         data = self.fit(data)
    413 
    414         # additionally we just need to treat the target variable

c:\Datalab\train_ml\venv\lib\site-packages\pycaret\internal\preprocess.py in fit(self, dataset, y)
    151 
    152         # if there are inf or -inf then replace them with NaN
--> 153         data.replace([np.inf, -np.inf], np.NaN, inplace=True)
    154 
    155         # also make sure that all the column names are string
```

My expectation was the if there were any errors they would not be attributed to anything with preprocessing.

A work around might of course be to transform my sparse matrix to a regular dense one, i.e.: 
```
data_tfidf = pd.DataFrame(features.toarray(), 
                          columns=test_features.get_feature_names())
data_tfidf["target"] = [0, 1]
```
But since I've got 22220 features I a a bit reluctant to do that.

**Comment by Yard1** [comment]
The first preprocessing step is always executed to infer data types and remove values that will cause errors later. Unfortunately, support for dense matrices is not yet present. They may work, but it is not guaranteed.

**Comment by Hveemos** [comment]
Ok, so I guess I have to wait until this bug is resolved before I use Pycaret with a sparse matrix.

**Comment by moezali1** [comment]
@tvdboom With the new preprocessing module, can we pass sparse matrix in `setup`?

**Comment by tvdboom** [comment]
Yes, the new rc version accepts sparse matrices as input. However, many of the preprocessing steps don't work with sparse data so either use `preprocess=False` or select which steps to use carefully. Also, not all models have native sparse data support. Using `compare_models` will return a limited list.
