### ISSUE TITLE
#AttributeError: module 'matplotlib' has no attribute 'rcParams'

### ISSUE THREAD

**Issue by Jun-hub2020** [pycaret/pycaret#406]
when i want to run the 'setup':

 from pycaret.classification import *
training_set = setup(data = training,target='salClass',session_id=123)

there is an issue as follows:
![f95f26915a93eb2fab4a4a599fa1860](https://user-images.githubusercontent.com/62453598/89764307-b92a0380-db26-11ea-9994-f288268a2ca2.png)

could you tell me how i should do?

**Comment by mahmoudyusof** [comment]
could you specify which version of matplotlib you are using in this notebook?
in the notebook
```python
import matplotlib as mpl
mpl.__version__
```

**Comment by Jun-hub2020** [comment]
thank you for your reply. I have soved it.
I think it was probably due to a problem during my installation. i reinstalled the 'matplotlib' and it works. However, the same problem occurs with other packages. so I reinstalled the faulty package.
