### ISSUE TITLE
[DOC]: How should pycaret v3 be cited? 

### ISSUE THREAD

**Issue by mariamonzon** [pycaret/pycaret#4078]
### pycaret version checks

- [X] I have checked that the issue still exists on the latest versions of the docs [here](https://pycaret.gitbook.io/docs/)

### Location of the documentation

https://pycaret.readthedocs.io/en/latest/

### Documentation problem

I would like to know how Pycaret v3 can be acknowledge, the documentation and old issue (#1548) still refer to v1. 

### Suggested fix for documentation

 get a software doi  by uploading to Zenodo

**Comment by celestinoxp** [comment]
@moezali1
