### ISSUE TITLE
[INSTALL]: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. sktime 0.26.0 requires pandas<2.2.0,>=1.1, but you have pandas 2.2.3 which is incompatible. pycaret 3.3.2 requires pandas<2.2.0, but you have pandas 2.2.3 which is incompatible.

### ISSUE THREAD

**Issue by RicardoDeGouveia** [pycaret/pycaret#4082]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

import pandas as pd

### Installation Method

pip install

### pycaret Version

3.3.2

### Python Version

3.10.7

### Description

Please update pycaret to work with pandas 2.2.2 (last and stable version)

### Installation Logs

pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sktime 0.26.0 requires pandas<2.2.0,>=1.1, but you have pandas 2.2.3 which is incompatible.
pycaret 3.3.2 requires pandas<2.2.0, but you have pandas 2.2.3 which is incompatible.

**Comment by amotl** [comment]
Hi. This is also tripping us. 🙏 

- https://github.com/crate/cratedb-examples/pull/477#issuecomment-2181001780
