### ISSUE TITLE
Error when loading saved models

### ISSUE THREAD

**Issue by ABorakati** [pycaret/pycaret#415]
Hello,

I've made a logistic regression model and data transformation pipeline with Pycaret 2.0 :
save_model('finallr', 'lr')
Transformation Pipeline and Model Succesfully Saved
finallr=load_model('lr')
Transformation Pipeline and Model Sucessfully Loaded

When I then try and use this model to predict (even on the same data set it was trained on) I get this error:
predict_model(estimator=finallr)
Traceback (most recent call last):

  File "<ipython-input-262-e5eae01ac0cb>", line 1, in <module>
    predict_model(estimator=finallr)

  File "C:\Users\~\AppData\Roaming\Python\Python38\site-packages\pycaret\classification.py", line 11149, in predict_model
    pred_ = model.predict(Xtest)

AttributeError: 'str' object has no attribute 'predict'

Can't see any similar errors elsewhere, this happens for any model and any data,

Does anyone have any ideas?

Many thanks

**Comment by mahmoudyusof** [comment]
I think I know the problem, you are passing the first argument to `save_model` as text while you should pass the model itself, for example
```python
finallr = create_model('lr')
save_model(finallr, 'lr')
loaded_model = load_model('lr')
predictions = predict_model(loaded_model, data)
```

**Comment by ABorakati** [comment]
Thanks a lot! That fixed it
