### ISSUE TITLE
get rid of the data types confirmation input text, or add option to disable it in setup

### ISSUE THREAD

**Issue by juancrescente** [pycaret/pycaret#416]
In jupyter lab, the textbox never shows, which makes it impossible for me to run the setup step. 

"Following data types have been inferred automatically, if they are correct press enter to continue or type 'quit' otherwise."

BTW I got label in a regression in my Y values, is that correct?

**Comment by pycaret** [comment]
@juancrescente Thanks. You can avoid the input box by passing `silent` parameter within `setup` as `True`. 

Hope this helps.
