### ISSUE TITLE
Tune Model [WinError 5] Access is denied

### ISSUE THREAD

**Issue by wsn4iv** [pycaret/pycaret#42]
I am using Windows 10 and Python 3.7.1. Whenever I run tune_model() for any model, I receive a [WinError 5] Access is denied error. The full error code is attached.

Please advise.

[Error.txt](https://github.com/pycaret/pycaret/files/4522949/Error.txt)

**Comment by pycaret** [comment]
Hi,

Which environment are you using? Jupyter?

Thanks.

**Comment by wsn4iv** [comment]
Yes. I am using Jupyter Notebook

**Comment by pycaret** [comment]
Can you run Jupyter Notebook as administrator and try again?

Please let me know how it goes.

**Comment by wsn4iv** [comment]
It is a work computer and I do not have admin access. I can create a ticket to see if our IS department can assist with running as an admin.

**Comment by pycaret** [comment]
Sure. Let us know how it goes.

**Comment by wsn4iv** [comment]
I attempted it after running Jupyter notebook as admin and the problem still persists
