### ISSUE TITLE
DNA sequence classification using k-mer and 

### ISSUE THREAD

**Issue by sambhe** [pycaret/pycaret#420]
Hi, 

I would say a good add on would be to have k-mer processing and Countvectorizer (Bag of words) if it's not there.  I am trying to do a classification problem on a genetic sequence (RNA/DNA) data in which I pre-process the alphabetical sequences data forming k-mers  and fit and transform (train data) using countvectoriser (extract frequencies of those words in a seuqnce). 
Using same CV then, I transform the test data. 

For now I am going to use the externally processed data as above and then user PyCaret for modelling. 

Thanks,
Vijay

**Comment by pycaret** [comment]
@sambhe Maybe if you share an example notebook with some clear user story, somebody might be interested in adding this as an enhancement. You are welcome to work on PR.

**Comment by sambhe** [comment]
Sure, I will add a simple notebook in the coming days (3-4) . I might be available next month to work on this if no one is available to take this on.

**Comment by sambhe** [comment]
[Data.zip](https://github.com/pycaret/pycaret/files/5105786/Data.zip)

[DNAClassification_jupyterNotebook.zip](https://github.com/pycaret/pycaret/files/5105796/DNAClassification_jupyterNotebook.zip)

Reference - https://github.com/nageshsinghc4/DNA-Sequence-Machine-learning

I have run the code in a jupyter notebook, showing the all the output.
Data is uploaded too.
