### ISSUE TITLE
Tune Model Never Completes

### ISSUE THREAD

**Issue by brinew27** [pycaret/pycaret#423]
Hi all,

I'm enjoying PyCaret quite a bit so far. However, when I attempt to tune a model of any size (say 5 million rows), the tune model stop simply never progresses, it begins, gives the initial output and then never changes. I let it run for over 8 hours last night with no progress.

The model I'm attempting to tune is a GPU accelerated xgboost ('xgboost', tree_method = 'gpu_hist', gpu_id = 0). Training the model takes under 30 seconds even with 5 million rows. Chaging the model to not use GPU doesn't appear to make a difference.

I have seen it finish once, but it was with many fewer rows, (say around 200K). I'm simply running "tuned_xgb = tune_model(xgb, optimize='Precision')".

Any thoughts?

Thanks!

**Comment by pycaret** [comment]
@brinew27 If you take a sample of dataset, would `tune_model` works. I think I know why this is happening. I think `tune_model` is not affected by `GPU` parameter. This could be a bug.

**Comment by brinew27** [comment]
Yes, when I trained and tuned on 10% of the data, it worked. I thought it might have been related to the n_jobs parameter, but I can confirm 10% data works on both n_jobs=-1 and n_jobs=1. When I set it back to full dataset, even with n_jobs=1 it never reaches the first fold, it stops at "Initializing RandomizedSearchCV" in the INFO logs.

Also, adding GPU support for tuning would be much appreciated as that will always a much longer process than training, where it's supported.

Thanks!

**Comment by pycaret** [comment]
@brinew27 I have now amended `tune_model` function in `classification.py` and `regression.py` to inherit `params` from the estimator passed in `tune_model`.

Can you please sync the `master` branch and test it? I will close the issue upon your confirmation.

**Comment by pycaret** [comment]
@brinew27 If you are still having issues, please open another issue.
