### ISSUE TITLE
Should data be explicitly a pd.DataFrame?

### ISSUE THREAD

**Issue by clgarciga** [pycaret/pycaret#425]
In `setup`, parameter `data` is defined as:

```
    data : {array-like, sparse matrix}
        Shape (n_samples, n_features) where n_samples is the number of samples and n_features is the number of features.
```

But throughout the code it seems to me like `data` is implicitly assumed to be a `pd.DataFrame` . For example, passing a `numpy` array throws an error:

![image](https://user-images.githubusercontent.com/13739205/90076943-ef09ec00-dcce-11ea-928d-6b4a52cac3cb.png)

It isn't explicit in the docs that `data` must be a `pd.DataFrame`, and there is also no check in the code that throws a meaningful error if `data` is not so.

**Comment by pycaret** [comment]
@clgarciga Yes. I remember `preprocess.py` is designed to work with the panda's data frame only. If we have to accept `numpy` we have to handle the conversion first thing in the `setup` function.

**Comment by clgarciga** [comment]
Then should the docs be amended to reflect this, and should `setup` include a check for `data` being a `pd.DataFrame`?

**Comment by pycaret** [comment]
@clgarciga I think so docs should be amended. Would you look to work on this?

**Comment by clgarciga** [comment]
@pycaret Sure!
