### ISSUE TITLE
Unable to enter text for regression setup in databricks

### ISSUE THREAD

**Issue by shamv** [pycaret/pycaret#43]
Using pycaret.regression to build the model. But unable to enter after displaying column datatypes.

![image](https://user-images.githubusercontent.com/9548391/80126808-19fdf200-85b1-11ea-834a-6fdfcfe94fda.png)

**Comment by pycaret** [comment]
Databricks doesn't support input() function. We are investigating alternates. For now, try passing silent = True parameter within setup and it shall work.

**Comment by pycaret** [comment]
I am marking this as en enhancement for DB compatibility in future.

**Comment by shamv** [comment]
Thanks team. I choose that option and worked. But there is one more issue observed.
![image](https://user-images.githubusercontent.com/9548391/80206131-7280ce00-8649-11ea-94fa-b9b4e009eb62.png)

Please add to your list and make it compatible with databricks

**Comment by pycaret** [comment]
@shamv Sorry for late response. Can you please explain what's the issue in the Association Rule Example you have shown above?
