### ISSUE TITLE
Enhancement of test

### ISSUE THREAD

**Issue by daikikatsuragawa** [pycaret/pycaret#431]
For each function, it is necessary to test it in detail.

For example, in test_utils.py:

```py
    accuracy = pycaret.utils.check_metric(actual, prediction, "Accuracy")
    assert accuracy >= 0
    assert accuracy <= 1
```

**Comment by pycaret** [comment]
@daikikatsuragawa Agree. I have merged all the changes you submitted yesterday and today. Let's continue to improve unit tests.

**Comment by Yard1** [comment]
We could consider preparing datasets that are sure to give consistent results with a set session ID, and use them for testing, to make sure the output of the functions is as expected.

**Comment by pycaret** [comment]
@Yard1 This sounds good. I plan to discuss this with you in the meeting but I guess the idea would be to release `2.1` in the next 10 days and then start major refactoring after that for `2.2` release.

Once we close all items added into project `2.1 Authors sprint`, we will be ready for the release.

Would love to wrap up the GitHub actions thing before that.

**Comment by pycaret** [comment]
@daikikatsuragawa Do you consider this complete for this sprint?

**Comment by daikikatsuragawa** [comment]
At the very least, I want to complete all return type checks for the tests.
I think we can do it in the same way as before.

Also, I dare to solve this problem somehow. I can't solve it. #458

**Comment by Yard1** [comment]
@daikikatsuragawa opened a PR fixing it https://github.com/pycaret/pycaret/pull/476

**Comment by daikikatsuragawa** [comment]
@Yard1 Thanks!!

**Comment by daikikatsuragawa** [comment]
> At the very least, I want to complete all return type checks for the tests.
> I think we can do it in the same way as before.

This seems to have been resolved.

**Comment by pycaret** [comment]
@daikikatsuragawa Great. I am planning to drop the `2.1` release next week. Let me know if you need any help to finish this.

**Comment by daikikatsuragawa** [comment]
No type checking is done for the libraries used to create a particular model. This is because we may use another library in the future. For example, I might change A to another library that does the same thing.

Therefore, I don't think it is mandatory for the test to fail in such cases. Because it is not the essence. Therefore, I am doing this. Based on that idea, the general type check is completed.

For the rest, I want to check the evaluation value and finish it for the time being.

However, the test is very profound...

**Comment by pycaret** [comment]
@daikikatsuragawa One thing we should also try to do before `2.1` release is to add tests related to preprocessing which means that we will have to add a couple of `setup` functions above the final `setup` function based on which all other modeling functions are executed. I will try to add an example of what I am saying in `test_classification.py` soon. Then maybe you can replicate that for other modules. Thanks.

**Comment by daikikatsuragawa** [comment]
@pycaret 
Thank you very much.
I will use it as a reference for other tests.

**Comment by pycaret** [comment]
@daikikatsuragawa I have now started adding preprocess related tests. I am calling `preprocess.py` from `pycaret.classification` not sure if we want to replicate the tests using `pycaret.regression` as both the modules use the same file and function from `preprocess.py` but I will leave it up to you. So far I have added:

- test_normalize.py
- test_missing_values.py
- test_categorical_features.py

I am trying to follow the convention you are following to remain consistent. If you want to add more tests, please feel free to do so.

By the time you will look at it, I might have added more files. My plan is to increase the coverage of testing of all preprocessing functionalities that are accessible through the `setup` function in `pycaret.classification` `pycaret.regression` `pycaret.clustering` `pycaret.anomaly`.

**Comment by daikikatsuragawa** [comment]
Thank you! I will check it from now on.

**Comment by pycaret** [comment]
@daikikatsuragawa Great. We will be releasing `2.1` tomorrow. I guess between `2.1` and `2.2` refactoring sprint there would be a lot of work that we can do on improving unit tests.

**Comment by pycaret** [comment]
@Yard1 I suggest we continue to commit the new tests or changes on the `master` branch. Do you agree?

**Comment by Yard1** [comment]
@pycaret Yes, that's fine.

**Comment by pycaret** [comment]
@daikikatsuragawa I will close this issue for now. Once @Yard1 will merge `refactor-2.2` branch into the `master`, I can open another issue for test enhancement, and then we can add more tests for the next release `2.2`.
