### ISSUE TITLE
Lack of info in the create_model function documentation

### ISSUE THREAD

**Issue by joaopcnogueira** [pycaret/pycaret#45]
In the create_model() function, after the model has been evaluated on a kfold cross validation and its ready to be used to make predictions on unseen data, a question remained (I've read the function documnetation and didn't find an answer): Is the model trained in the entire data set?

If yes, would it be great to have this piece of information stated in the function docs?

**Comment by pycaret** [comment]
Hi.

The model is not trained on the entire dataset until you you finalize_model( ) function. For example:

lr = create_model('lr') <-- this model is trained on training dataset only, the results presented in grid is CV results. 

Once you are ready to deploy the model, you can check the score of model on hold-out set by using:

predict_model(lr);

Once you have checked over-fitting / under-fitting after evaluating test scores. You can fit the model on entire dataset by using:

final_lr = finalize_model(lr)

Read more about finalize_model function : https://www.pycaret.org/finalize-model

Hope this was easy. Let me know how it goes.

**Comment by joaopcnogueira** [comment]
Thanks for the quick answer! 

Now it is clear for me. Maybe it should be more cristal clear in the documentation.

**Comment by pycaret** [comment]
Thanks. Will try to improve documentation. 

Closing issue now.
