### ISSUE TITLE
Word2Vec function for NLP.

### ISSUE THREAD

**Issue by yashmehta10** [pycaret/pycaret#451]
if possible we should add word2vec function using gensim. I would be happy to work on this feature. https://radimrehurek.com/gensim/sklearn_api/w2vmodel.html

**Comment by pycaret** [comment]
@yashmehta10 sure. I think the only change required would be in `create_model` in `pycaret.nlp` plus all the documentation that goes with that. It should be a very quick change. I am assigning this to you.

Thanks for working on this.

**Comment by yashmehta10** [comment]
@pycaret, I believe it should be a part of `setup` in `pycaret.nlp`. Another way would be to have a new function to transform text data into vectors.

**Comment by moezali1** [comment]
We are no more supporting the `nlp` and `arules` module in PyCaret due to lack to resources. Closing the issue now.
