### ISSUE TITLE
TypeError: cannot astype a datetimelike from [datetime64[ns]] to [float64] 

### ISSUE THREAD

**Issue by sagarnildass** [pycaret/pycaret#454]
Hi 

I just trained a pycaret regression model with one date column in the training dataset. Pycaret correctly recognized it and from the documentation, I realized that pycaret would ignore that feature.

Now after saving the model, when I ran it on the test dataset (with the date column present), it gave me this error: TypeError: cannot astype a datetimelike from [datetime64[ns]] to [float64] .

Am I not correct in inferring that pycaret should drop this column before making inference?

**Comment by pycaret** [comment]
@sagarnildass PyCaret doesn't ignore DateTime. In fact, its extracts feature out of it. Can you make sure in test data, DateTime is correctly formatted so new features can be parsed?

**Comment by sagarnildass** [comment]
Sure, thanks I will take a look at it.

**Comment by pycaret** [comment]
@Yard1 Can you take a look at this when you get chance?

**Comment by Yard1** [comment]
This should have been fixed in the meantime.
