### ISSUE TITLE
Getting a model name out of `compare_models`

### ISSUE THREAD

**Issue by George3d6** [pycaret/pycaret#460]
In pycaret tutorials such as: https://github.com/pycaret/pycaret/blob/master/tutorials/Regression%20Tutorial%20Level%20Beginner%20-%20REG101.ipynb

It seems that the appropriate workflow to get a top-performing model is to get a list of the top models using `compare_models` and then separately create the best model using `create_model`.

However, `create_model` takes a magic string representing the model's name as the argument. So is there any way to programmatically write something like:

```
top = compare_models(... etc)

create_model(top[0].get_model_name_as_str())
```

In order to create the best model based on `compare_models` ?

**Comment by Yard1** [comment]
@George3d6 you can use the code in my notebook for now - https://www.kaggle.com/yard1pl/predicting-icu-admission-using-with-pycaret-0-2

A built in way to do it should be available in a later release.

**Comment by George3d6** [comment]
Hmh, I can't see anything in there that would achieve this, I see that the model is still create from a manually input string (`create_model('rf')`) rather than via somehow generating that string from the top models list.

**Comment by Yard1** [comment]
If you call get_model_name from that notebook, cell 53 on an estimator it will return its name (like in cell 58).

Eg. `get_model_name(compare_models())` will return the name of the best model.

**Comment by George3d6** [comment]
Ah, alright, that works perfectly for what I need. Thanks :)

Feel free to leave the issue open if it's a feature you want to implement.

**Comment by pycaret** [comment]
@George3d6 Unfortunately Tutorials are not updated. In `pycaret==1.0` , `compare_models` didn't returned any model but it should not be a problem in `pycaret==2.0` as `compare_models` return trained model object. See example below:

```
top5 = compare_models(n_select = 5)
```

If you still want the names of the model you can call the `pull` function to store the score grid as a pandas data frame and then subset the model name column. 

```
top5 = compare_models(n_select=5)
results = pull()
results.Model.tolist()
```

Hope this helps.

**Comment by George3d6** [comment]
Ah, I see, so I should be able to just call `predict_model` on that model directly, that makes sense.

I was doing that before, but getting low accuracies, so I assumed the models may not have been properly trained.

**Comment by pycaret** [comment]
Yes, @George3d6. You can call `predict_model` directly on the output of `compare_models` if n_estimators = 1. By default, its set to 1.

```
best_model = compare_models()
predictions = predict_model(best_model, data=new-dataframe)
```

Hope this helps.

**Comment by Yard1** [comment]
@pycaret It should still be finalized before using it on unseen data, though, yes?

**Comment by pycaret** [comment]
Yes @Yard1 That was just for example. finalize_model must be used to fit on the entire dataset before predicting on the new dataset. 

Even without finalize_model it won't give any error but the estimator will only be trained on X_train.

**Comment by prabhakaran2812** [comment]
best=compare_models() is working in my pc, but in colab it is returning null object. Is there a fix for it?
My pycaret version 2.2
