### ISSUE TITLE
How to only compare models that allow for blending and stacking ?

### ISSUE THREAD

**Issue by George3d6** [pycaret/pycaret#461]
It seems that a good approach to predicting is to use `compare_models` and then select the top `x` on which `blend_models`+`stack_models` can be used in order to get an ensemble model (which can then be optimized with `automl`).

However, some models don't support this and will throw errors if they happen to be in the list of top models.

Is there any way to call `compare_models` and specify that you only want to compare models that can be blended and stacked ?

**Comment by Yard1** [comment]
Isn't it just Catboost? Regardless, this should too be improved in a future release.

**Comment by George3d6** [comment]
I don't know. Is it just catboost that should behave like this ? tbh I think I only got the error for that one, but I might be wrong.

In that case should I be able to just use `blacklist = ['catboost']` and the approach will work fine otherwise ?

Also, quick followup to that question if you know: Does `automl` generate a "trained" model or does it generate "untrained" models similarly to `compare_models` ? My impression seems to be that it's the former, but I'm not 100% sure from the docs (https://pycaret.org/automl/)

**Comment by Yard1** [comment]
It should be just Catboost, so blacklisting it should be enough. `compare_models`, `create_model` and `automl` return the same type of models, which need to be finalized. I am not sure what you mean by trained (do you mean finalized?). All methods call `fit` internally on training data.

**Comment by George3d6** [comment]
By `trained` I mean that they are fit on the data_frame that I give to `setup` and can be used to generate predictions using `predict_model`

As in, can I safely use the return value of `automl` (let's call it `auto_model`) as:

```
auto_model = automl(...

predictions = predict_model(auto_model, data=validation_data_dataframe)
```

**Comment by Yard1** [comment]
Ok, so finalized. I checked the code and yes, it returns a finalized model indeed, so it is how you assumed. My bad.

**Comment by pycaret** [comment]
Only `catboost` will cause a problem as it is not compatible with sklearn `VotingClassifier`. Although, it works fine in regression with `VotingRegressor`.

I agree this needs to be improved in next release with a condition to drop `catboost` in `blend_models`.

For now, your best option is to blacklist `catboost` in `compare_models` using `blacklist` param.

**Comment by George3d6** [comment]
This is the code I ended up with for creating & optimizing a model using those functions:

```
    setup_return = setup(data=df_train, target=target)

    top_models = compare_models(n_select=3, verbose=False, sort=pycaret_acc_func_str, turbo=True, blacklist = ['catboost'])

    # Ensemble the top models and optimize the resulting model
    blender = blend_models(estimator_list=top_models, verbose=False)
    stacker = stack_models(estimator_list=top_models, meta_model=top_models[0], verbose=False)
    best_model = automl(optimize=pycaret_acc_func_str)

    df_test_dropped = df_test.drop(columns=[target])

    predictions = predict_model(best_model, data=df_test_dropped)

    accuracy = acc_func(list(predictions['Label']), list(df_test[target]))
    return accuracy
```

It seems to work fine unlike previous attempts, but some of the accuracies produced are quite low.

At any rate, I'll go ahead and create another issue if I notice a weird pattern with very low accuracies on all datasets I test this one.

Thanks a lot for the help here :)

**Comment by pycaret** [comment]
Thanks
