### ISSUE TITLE
error with plotly.express during setup()

### ISSUE THREAD

**Issue by PabloJMoreno** [pycaret/pycaret#465]
Team,

since yesterday night I am experiencing issues when running PyCaret both in Power BI and Jupyter. 

I have attached the screenshot of the Jupyter error, and bellow the error that I have in Power BI, and just happened yesterday. Previously to that, I worked with PyCaret perfectly, both in Power BI and Jupyter

It seems that I have some conflicts with versions and some packages like plotly.express, and some others (which I think it happened suddenly)

I tried everything, like uninstall / install Python, Anaconda, re-install Python 3.6. My dedicated environment is created where I install PyCaret, etc... everything

My system is Windows 10 (in spanish)

Your help will be very much appreciated, as I'm putting some projects in production
![pycaret error](https://user-images.githubusercontent.com/17184092/90448556-35829080-e0ab-11ea-8832-881a0e8937a0.png)

Error in Power BI:
![pycaret error](https://user-images.githubusercontent.com/17184092/90448441-fbb18a00-e0aa-11ea-8da8-972651aedb5b.png)

DataSource.Error: ADO.NET: Python script error.
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 2, in <module>
    import os, pandas, matplotlib
  File "C:\Users\creyes\AppData\Local\Continuum\anaconda2\envs\myenv\lib\site-packages\matplotlib\__init__.py", line 174, in <module>
    _check_versions()
  File "C:\Users\creyes\AppData\Local\Continuum\anaconda2\envs\myenv\lib\site-packages\matplotlib\__init__.py", line 159, in _check_versions
    from . import ft2font
ImportError: DLL load failed: No se puede encontrar el módulo especificado.
Details:
    DataSourceKind=Python
    DataSourcePath=Python
    Message=Python script error.
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 2, in <module>
    import os, pandas, matplotlib
  File "C:\Users\creyes\AppData\Local\Continuum\anaconda2\envs\myenv\lib\site-packages\matplotlib\__init__.py", line 174, in <module>
    _check_versions()
  File "C:\Users\creyes\AppData\Local\Continuum\anaconda2\envs\myenv\lib\site-packages\matplotlib\__init__.py", line 159, in _check_versions
    from . import ft2font
ImportError: DLL load failed: No se puede encontrar el módulo especificado.
    ErrorCode=-2147467259
    ExceptionType=Microsoft.PowerBI.Scripting.Python.Exceptions.PythonScriptRuntimeException

**Comment by pycaret** [comment]
@PabloJMoreno It seems like a dependency conflict of `plotly` with some other packages you have installed in the environment. I can suggest creating a separate conda environment for `pycaret`. To create a separate conda environment, please see below:

```
#create a conda environment
conda create --name yourenvname python=3.6

#activate environment
conda activate yourenvname

#install pycaret
pip install pycaret==2.0

#create notebook kernel connected with the conda environment
python -m ipykernel install --user --name yourenvname --display-name "display-name"
``` 

Hope this helps.

**Comment by PabloJMoreno** [comment]
Thanks PyCaret team, 

I have the same problem again. I created a brand new environment, run one of your samples on Python 3.6 and here is the result

![pycaret error2](https://user-images.githubusercontent.com/17184092/90458201-59ea6700-e0c3-11ea-8080-9ccd38d59a82.png)

**Comment by pycaret** [comment]
@PabloJMoreno 

Can you try uninstall seaborn with pip and reinstall with conda:

```
pip uninstall seaborn
conda install seaborn
```

**Comment by PabloJMoreno** [comment]
In the same environment where PyCaret is installed, right?

**Comment by pycaret** [comment]
@PabloJMoreno Yes.

**Comment by PabloJMoreno** [comment]
Team, now Jupyter is working fine, but I have the following error in Power BI, which it seems a version conflict with some packages. Can you please advise?

DataSource.Error: ADO.NET: Python script error.
C:\Users\creyes\Anaconda3\envs\myenv\lib\site-packages\numpy\__init__.py:138: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 2, in <module>
    import os, pandas, matplotlib
  File "C:\Users\creyes\Anaconda3\envs\myenv\lib\site-packages\pandas\__init__.py", line 17, in <module>
    "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
ImportError: Unable to import required dependencies:
numpy:
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.
We have compiled some common reasons and troubleshooting tips at:
    https://numpy.org/devdocs/user/troubleshooting-importerror.html
Please note and check the following:
  * The Python version is: Python3.6 from "C:\Users\creyes\Anaconda3\envs\myenv\python.exe"
  * The NumPy version is: "1.19.1"
and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.
Original error was: DLL load failed: No se puede encontrar el módulo especificado.
Details:
    DataSourceKind=Python
    DataSourcePath=Python
    Message=Python script error.
C:\Users\creyes\Anaconda3\envs\myenv\lib\site-packages\numpy\__init__.py:138: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 2, in <module>
    import os, pandas, matplotlib
  File "C:\Users\creyes\Anaconda3\envs\myenv\lib\site-packages\pandas\__init__.py", line 17, in <module>
    "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
ImportError: Unable to import required dependencies:
numpy:
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumP...
    ErrorCode=-2147467259
    ExceptionType=Microsoft.PowerBI.Scripting.Python.Exceptions.PythonScriptRuntimeException
