### ISSUE TITLE
Hyperlink for available models in docs

### ISSUE THREAD

**Issue by clgarciga** [pycaret/pycaret#466]
For example, this table is available under `create_model` in the classification docs:

![image](https://user-images.githubusercontent.com/13739205/90451205-4b974d80-e0b9-11ea-8179-6f5814fe8ebc.png)

But it is displayed nowhere else on the page, even though it would be useful to be able to see/reference easily for other functions, e.g. when specifying `blacklist` or `whitelist` in `compare_models`. 

Could there be a separate section/page with this table, with a hyperlink to it for any parameters where the user would need to know the string names/abbreviations for the available models. Same for regression, just using classification here as an example.

**Comment by pycaret** [comment]
@clgarciga We are trying to get away from the hassle of maintaining the website and hence we are moving everything slowly to `readthedocs` as it's more sustainable in terms of maintenance. The website is an entirely manual effort using `WordPress` and I want to discontinue that asap. 

Thanks for the suggestion anyways.
