### ISSUE TITLE
Support for custom Error & metrics function  on data "SETUP"

### ISSUE THREAD

**Issue by Anbulenin** [pycaret/pycaret#469]
### Example ### :
from pycaret.regression import *
pipeline = setup( 
data=dataframe, 
**error_fuction= custom_error(y_true,y_pred)
metrics =custom_metrics(y_true,y_pred)**
)

**Comment by pycaret** [comment]
@Anbulenin 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
