### ISSUE TITLE
inbalanced data

### ISSUE THREAD

**Issue by chamsdg** [pycaret/pycaret#474]
Hello everyone, when a applied fix_inbalance = True, 
There’s no effect in my dataset

i work in jupyterlab

below my code

```
exp01 = setup(data = data, target = "CHURN", train_size = 0.8, session_id=123,
              fix_imbalance = True, normalize = True) 

```

**Comment by pycaret** [comment]
@chamsdg 

When you set `fix_imbalance` to `True`. `resampler` is applied on the training partition during CV under each function such as `create_model` `tune_model` `blend_models` etc. As such you won't see the impact on your `X_train`, `X_test` from `get_config`. 

Hope this clarifies.
