### ISSUE TITLE
Tune Model causes an error

### ISSUE THREAD

**Issue by brinew27** [pycaret/pycaret#478]
Hi there,

This is in relation to the new version of Tune Model in master. Previously it would simply run my CPU at 100% with no progress. Now, it quickly generates an error. The training takes about 3 seconds for 10 folds. Training data is 246779 rows. When it gets to Tune Model it displays the header for the results, I hear my computer fans speed up, it runs for about 15 seconds (no change in output), then errors out.

The error is: "joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker."

I'm running 16GB RAM and a GTX 1080 GPU if that matters.

Here is the code I'm using:

```python
exp_clf101 = setup(data = data, target = 'IsEntry', session_id=123, silent=True, sampling=False)
    
xgb = create_model('xgboost', eval_metric="map", tree_method = 'gpu_hist', gpu_id = 0, base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.01, max_delta_step=0, max_depth=3,
              min_child1_weight=1, missing=np.nan, monotone_constraints='()',
              n_estimators=100, num_parallel_tree=1,
              objective='binary:logistic', reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=0.8,
              validate_parameters=1)
    
tuned_xgb = tune_model(xgb)
```

I've attached the stack trace if that helps.

[Stack Trace.txt](https://github.com/pycaret/pycaret/files/5091991/Stack.Trace.txt)

**Comment by pycaret** [comment]
@brinew27 It seems like `n_jobs` param causing an issue. Can you please try passing `n_jobs` as `None` in the `setup` function. By default, it is set to `-1`.

**Comment by pycaret** [comment]
@brinew27 Would you also mind trying this with `lightgbm` estimator as well?

**Comment by brinew27** [comment]
@pycaret I changed n-jobs to None. It did move past the first step to "Loading Dependencies" and didn't give an error, but it just sat on that step for 30 minutes with no changes.

I tried lightgbm, just with the default parameters (lightgbm = create_model('lightgbm')), and it did successfully tune the model and return. I am not sure if that was using my GPU or not.

**Comment by pycaret** [comment]
@brinew27 You have to create `lightgbm` like this:

```
create_model('lightgbm', tree_method = 'gpu_hist', gpi_id = 0)
```

Let me know how that goes.

**Comment by brinew27** [comment]
@pycaret I ran both:

```
create_model('lightgbm', tree_method = 'gpu_hist', gpi_id = 0)
```

and

```
create_model('xgboost', tree_method = 'gpu_hist', gpi_id = 0)
```

lightgbm completed fine (after searching for hyperparameters for about 60 seconds, then training). xgboost does now throw an error now, but sits at "Loading dependencies" as mentioned and requires the kernel being reset.
