### ISSUE TITLE
interpret_model() problem with XGBoost regression

### ISSUE THREAD

**Issue by nasospat** [pycaret/pycaret#48]
I was trying interpret_model with XGBoost for a regression model and had this error
 
![shap_xgboost](https://user-images.githubusercontent.com/26347750/80281748-061fd080-8716-11ea-9980-28ee6bb91187.PNG)

I searched for it and seems to be a known issue of shap-0.32.1. 
https://github.com/slundberg/shap/issues/887
I updated to shap-0.35.0 and the problem was fixed. Maybe you should consider not using the shap-0.32.1 version.

**Comment by pycaret** [comment]
Thanks for identifying. Will do it in next release.
