### ISSUE TITLE
PyCaret & SQL Machine Learning Server 

### ISSUE THREAD

**Issue by georgepapaioannou** [pycaret/pycaret#482]
When we 're trying to install pycaret version 2.0 in a Windows 2019 Server with SQL Machine Learning Server we 're taking the following error
![pycaret_error](https://user-images.githubusercontent.com/69902674/90630938-91bfee80-e22a-11ea-97d5-111ae6b4aa96.png)

 Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/1f/cb/a8ec24334c35a7d0c87b4e4e056bd2137573c7c1bd81c760b79a2f370254/lightgbm-2.3.1-py2.py3-none-win_amd64.whl (544kB)
    100% |################################| 552kB 1.6MB/s
Collecting spacy (from pycaret==2.0)
  Using cached https://files.pythonhosted.org/packages/18/db/499f374339b522b6618234b93f25d2990692795ccce3152519ccc508586c/spacy-2.3.2.tar.gz
Collecting scikit-learn>=0.23 (from pycaret==2.0)
  Could not find a version that satisfies the requirement scikit-learn>=0.23 (from pycaret==2.0) (from versions: 0.9, 0.10, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.14, 0.14.1, 0.15.0b1, 0.15.0b2, 0.15.0, 0.15.1, 0.15.2, 0.16b1, 0.16.0, 0.16.1, 0.17b1, 0.17, 0.17.1, 0.18rc2, 0.18, 0.18.1, 0.18.2, 0.19b2, 0.19.0, 0.19.1, 0.19.2, 0.20rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21rc2, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.22rc2.post1, 0.22rc3, 0.22, 0.22.1, 0.22.2.post1)
No matching distribution found for scikit-learn>=0.23 (from pycaret==2.0)
You are using pip version 9.0.1, however version 20.2.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by Yard1** [comment]
Update pip as the yellow text says and try again.

**Comment by georgepapaioannou** [comment]
Than you for your reply
1. I have update pip
2. I have override the TLS/SSL download problem

and now I'm getting the following error

![pycaret_error](https://user-images.githubusercontent.com/69902674/90770569-a8357b00-e2fa-11ea-8314-1e0d270b2a3a.png)

The user in Windows is Administrator

**Comment by Yard1** [comment]
I have only very cursory experience with Microsoft SQL Server, but maybe there are people here who can help. That being said, this isn't a PyCaret issue, so you may have better luck asking for help on Microsoft forums.

**Comment by georgepapaioannou** [comment]
Thank you

**Comment by pycaret** [comment]
@georgepapaioannou I have informed one of the team member who is a subject matter expert on the SQL server. He will respond here shortly.
