### ISSUE TITLE
Sources of Data

### ISSUE THREAD

**Issue by clgarciga** [pycaret/pycaret#494]
I recognize some but not all of the [datasets included in pycaret](https://pycaret.org/get-data/). Were they all obtained from existing datasets online? If so, could we include links to the original source of the data/data documentation if it exists online somewhere?

**Comment by pycaret** [comment]
Yes. Most of them are from UCI. This is a mid to long-term project to get their links and metadata information as well.

Nobody complained so far but we must give a link and credit to original source on website as well as docstrings. 

Thanks for bringing this up. 

I will keep this open and see if any student has interest in working on this?

**Comment by pycaret** [comment]
@fireddd Great I have assigned the issue to you. Please keep us posted on your progress. Let's target this for next release `2.2` (end of Sep)

**Comment by fireddd** [comment]
If you give me an idea of what is expected from me as the final result that would be really good to know.

**Comment by pycaret** [comment]
@fireddd we have a lot of public datasets uploaded here: https://github.com/pycaret/pycaret/tree/master/datasets

They are used in `get_data` function from `pycaret.datasets` module. For example:

```
from pycaret.datasets import get_data
data = get_data('titanic')
```

This function reads the data frame from the GitHub repo and returns it as a pandas data frame. There are two problems:

1. We do not have appropriate credits/citations in place. The first step would be to add new column in `index.csv` to give that citation/credit for each dataset. Most of the datasets are commonly used and 90% of them are from `UCI` so it won't be a problem for you to find.

2. Once step 1 is completed.  We will need to think about the data dictionary or metadata information. The problem with just `get_data` is that sometimes people don't know what the data means, in such cases, we will need to collect the metadata and also give the option to read the metadata from the GitHub.

I suggest let's do it in step. Let's complete step 1 first?

Waiting for your PR.

Thanks

**Comment by fireddd** [comment]
Hi, sure adding column shouldn't be a problem in the index.csv , is there a naming convention that is being followed while giving credit like just the name of the organization or something else?

**Comment by soma2000-lang** [comment]
Is the issue still not solved ??If not then I would like to work on it...
