### ISSUE TITLE
Classification dataset with groups

### ISSUE THREAD

**Issue by clgarciga** [pycaret/pycaret#495]
I've looked through the datasets included in pycaret and maybe I overlooked it but I can't find a classification dataset with non-i.i.d. data. Was wondering if there was one with groups (e.g. dataset of repeated measures on different patients - here the groups would be the patients) already included, or if anyone can think of one off the top of their head that is available online somewhere. If not I have an idea for one I can create and contribute but I figure it's probably better to pull one off the internet somewhere if it exists.

**Comment by pycaret** [comment]
@clgarciga Would be good to include that in `dataset` folder and also `index.csv` must be updated with metadata.
