### ISSUE TITLE
Custom estimators in compare_models

### ISSUE THREAD

**Issue by SuryaThiru** [pycaret/pycaret#497]
Currently `compare_models()` only takes model strings for the `whitelist` parameter. Is it possible to pass a custom sklearn-compatible estimator object like in `create_model()`?

**Comment by Yard1** [comment]
This is planned for a future release.

**Comment by pycaret** [comment]
@Yard1 How are we planning to add custom estimators in `compare_models`. Is it similar to `add_metric` we will have a function of `add_model` ?

**Comment by Yard1** [comment]
@pycaret Users can pass sklearn-compatible model objects to `include` in `compare_models` and they will be handled correctly.

**Comment by pycaret** [comment]
@SuryaThiru 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
