### ISSUE TITLE
getting error in predict_model function

### ISSUE THREAD

**Issue by divyanshu-sam** [pycaret/pycaret#498]
I have used this earlier also but right now I am getting in the predict_model() function. My pkl file is getting successfully loaded but after that in predict_model() showing this error.

![image](https://user-images.githubusercontent.com/61079404/90748969-761f1b80-e2f0-11ea-9153-bd57117723cc.png)

using this code for prediction **prediction_price_Model_1 = predict_model(model_predictor_price_1,data=unseen_predictions_2)**

and unseen_predictions_2 variable contains below image top-line data

![image](https://user-images.githubusercontent.com/61079404/90749314-ed54af80-e2f0-11ea-847e-3f327c2a7ede.png)

Any help on this ASAP.

**Comment by pycaret** [comment]
@divyanshu-sam What's the version of `pycaret` are you using? Have you trained your model using `pycaret` on a different machine or in the same machine? Are you using `conda` environment?

**Comment by divyanshu-sam** [comment]
Hi @pycaret , 

Problem solved there was an issue with the pandas version. I have updated the pandas and problem solved. Thanks for your quick reply.

**Comment by pycaret** [comment]
@divyanshu-sam Thanks. Closing the issue.
