### ISSUE TITLE
Error in Binary Classification Tutorial Level Beginner -  CLF101 tutorial

### ISSUE THREAD

**Issue by papagala** [pycaret/pycaret#516]
I was reproducing locally this tutorial and came across this error:

```python
SystemExit: (Type Error): The behavior of tune_model in version 1.0.1 is changed. Please pass trained model object.
```

The solution was to remove the quotes from 

```python
tuned_dt = tune_model('dt')
``` 

to 

```python
tuned_dt = tune_model(dt)
```

Something similar with 

```
tuned_knn = tune_model(knn)
```
```
tuned_rf = tune_model(rf)
```

**Comment by papagala** [comment]
I’d love to help if you let me. We could divide and conquer. Thanks anyways for looking into this

**Comment by pycaret** [comment]
@papagala Great. I have now updated all the tutorials. Please check `/pycaret/tutorials` for all the tutorials. We don't have an `expert` level tutorial for any of the modules (there is a placeholder though). Let's not worry about expert level tutorials for now.

If you can spend a couple of hours checking all the tutorials it would be great. Look for these things:

- Broken links and fix them
- Cross-referencing among tutorials 
- grammar and semantic improvement (I will be happy if you can reword any part to make it more simple)
- indexing and sequence
- anything else that can improve readability of these tutorials.

**Comment by papagala** [comment]
Happy to help

**Comment by papagala** [comment]
First results, I'll go in more detail next week that I have got more time if you're still interested. 

Successfully ran 

- Anomaly Detection Tutorial Level Beginner - ANO101
- Clustering Tutorial Level Beginner - CLU101
- Regression Tutorial Level Beginner - REG101
- Natural Language Processing Tutorial Level Beginner - NLP101
- Natural Language Processing Tutorial Level Intermediate - NLP102
- Multiclass Classification Tutorial Level Beginner - MCLF101
- Binary Classification Tutorial Level Beginner -  CLF101


Unsuccessfully ran 

- Regression Tutorial Level Intermediate - REG102

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-f7b2fb433c8d> in <module>
----> 1 tuned_bagged_dt = tune_model('dt', ensemble = True, method = 'Bagging', n_iter = 100)

TypeError: tune_model() got an unexpected keyword argument 'ensemble'
```

- Binary Classification Tutorial (CLF101) - Level Beginner (typo)

 As such, the function that actually allows to you create a model is unimaginatively called `create_model()`

- Binary Classification Tutorial Level Intermediate - CLF102

```python
An exception has occurred, use %tb to see the full traceback.

SystemExit: (Type Error): CatBoost Classifier not supported in this function.
```

**Comment by pycaret** [comment]
@papagala Thanks. I have fixed the issue in Regression Intermediate but I can't find the typo error you mentioned in Classification Beginner anymore. Can you please recheck? 

https://github.com/pycaret/pycaret/blob/master/tutorials/Binary%20Classification%20Tutorial%20Level%20Beginner%20-%20%20CLF101.ipynb
