### ISSUE TITLE
2.2 Unused Imports

### ISSUE THREAD

**Issue by clgarciga** [pycaret/pycaret#521]
Seems like there are a number of unused imports in `classification`, could be an opportunity to reduce the code base further:

![image](https://user-images.githubusercontent.com/13739205/90983505-b8d53380-e53c-11ea-8e1c-9b358ac14f48.png)

For example all imports from `metrics` to `px` above are unused. Happy to submit a PR removing these. Let me know @Yard1.

**Comment by Yard1** [comment]
@clgarciga Would be great if you could do that, but after I finish adding the new features to classification. I'll let you know when you can go ahead with it, thanks.

**Comment by Yard1** [comment]
@clgarciga Feel free to start working on it now. Please use the up to date `2.2-refactor` branch and make a PR into it.

**Comment by pycaret** [comment]
@Yard1 Can we close this now?
