### ISSUE TITLE
A typo

### ISSUE THREAD

**Issue by Ijustwantyouhappy** [pycaret/pycaret#526]
I'd like to count how many datasets for each task contained in this git repository, then I use codes:
```python
from pycaret.datasets import get_data

df = get_data('index')
df.groupby('Default Task').Dataset.nunique()
```
and from the results below I feel a little bit strange,  there seems to be an extra space before 'Classification (Multiclass)' and 'Multivariate'.

![image](https://user-images.githubusercontent.com/26211339/91029534-76415300-e631-11ea-8e92-aa253d8b85dd.png)

![image](https://user-images.githubusercontent.com/26211339/91029912-a5f05b00-e631-11ea-9287-d3065ac47020.png)

**Comment by Yard1** [comment]
Thanks, opened a PR fixing it.
