### ISSUE TITLE
Re-using auto-sklearn

### ISSUE THREAD

**Issue by elgalu** [pycaret/pycaret#528]
Would it make sense to transparently re-use https://github.com/automl/auto-sklearn in pycaret ?

**Comment by pycaret** [comment]
@elgalu Already in WIP.

**Comment by pycaret** [comment]
@elgalu 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
