### ISSUE TITLE
Feature request: training and predicting time to the compare_models

### ISSUE THREAD

**Issue by reza1615** [pycaret/pycaret#53]
Please add training and predicting time to the compare_models table.
![image](https://user-images.githubusercontent.com/2202483/80307397-d95fcd80-8796-11ea-99f5-7c2cac7cfe6b.png)

**Comment by pycaret** [comment]
Thank you for your contribution. I will mark this as an enhancement for future release.

**Comment by reza1615** [comment]
@pycaret You removed the history https://github.com/pycaret/pycaret/graphs/contributors
I don't contribute here

**Comment by pycaret** [comment]
@reza1615 Is it only showing contribution on master branch?

**Comment by reza1615** [comment]
I had [this](https://github.com/pycaret/pycaret/pull/74) commit  after you reuploaded the file all history removed [here ](https://github.com/pycaret/pycaret/commits/dev-1.0.1/pycaret/classification.py)
