### ISSUE TITLE
Creating separate Models

### ISSUE THREAD

**Issue by reza1615** [pycaret/pycaret#54]
Please make a alternative model name's dictionary for Creating separate Models.
PyCaret doesn't recognize 'Extra Trees Classifier'
![image](https://user-images.githubusercontent.com/2202483/80307478-47a49000-8797-11ea-9136-7039806c9949.png)

It would be helpful to get the names from this table
![image](https://user-images.githubusercontent.com/2202483/80307496-6e62c680-8797-11ea-9b73-bba1f7158899.png)

**Comment by pycaret** [comment]
Hi. To create Extra Trees please use following:

create_model('et'). 

Read complete list of models at https://www.pycaret.org/create-model

Closing the issue.

**Comment by reza1615** [comment]
I saw https://www.pycaret.org/create-model. I mean also config pycart to accept full name. Now it needs to check  https://www.pycaret.org/create-model for finding the abrivation. you can make it simple to also accept "LogisticRegression" or "lr"
