### ISSUE TITLE
How to use imputer in sklearn?

### ISSUE THREAD

**Issue by zhenlingcn** [pycaret/pycaret#541]
I find that the imputation method in pycaret is rather simple. I hope to use the imputer in sklearn to improve the performance, such as the KNNImputer or even Iterative Imputer. It seems that the API documentation does not provide this choice, so is it possible to use those imputers in the current version?

**Comment by pycaret** [comment]
@zhenlingcn This is WIP. We will be adding this in next release `2.2`

**Comment by pycaret** [comment]
@zhenlingcn 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
