### ISSUE TITLE
compare_models use GPU

### ISSUE THREAD

**Issue by SSITB** [pycaret/pycaret#542]
Can i use compare_models to be trained on GPU ?

below is the Signature for it

compare_models(
    blacklist=None,
    whitelist=None,
    fold=10,
    round=4,
    sort='Accuracy',
    n_select=1,
    turbo=True,
    verbose=True,
)

**Comment by Yard1** [comment]
Support for GPU models will be added in `2.2`.

**Comment by SSITB** [comment]
Thank you

**Comment by pycaret** [comment]
@SSITB 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
