### ISSUE TITLE
Migrate commonly implemented processing to utils.py

### ISSUE THREAD

**Issue by daikikatsuragawa** [pycaret/pycaret#547]
This is one of the refactoring plans. I think it would be nice to find out where it seems to be applicable.

**Comment by pycaret** [comment]
@Yard1 FYI.

**Comment by Yard1** [comment]
@daikikatsuragawa I will need to look, but tbh it's a pretty low priority thing. What I had in mind was eg. copying datasets and so on, but I am not sure if it's worth it moving them to a function.

**Comment by pycaret** [comment]
This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
