### ISSUE TITLE
Showing warning message instead of error

### ISSUE THREAD

**Issue by reza1615** [pycaret/pycaret#56]
It would be perfect to inactive buttons for multi-class classification or showing a warning message instead of error.
![image](https://user-images.githubusercontent.com/2202483/80309149-116c0e00-87a1-11ea-9e51-3a21976682ad.png)

**Comment by pycaret** [comment]
Marking this as an bug / enhancement.

**Comment by reza1615** [comment]
@pycaret You removed the history https://github.com/pycaret/pycaret/graphs/contributors
I don't contribute here
