### ISSUE TITLE
Compare models MLFlowException

### ISSUE THREAD

**Issue by sagarnildass** [pycaret/pycaret#566]
Hi. I just upgraded to pycaret 2.1. When I ran the compare_models function with the Titanic dataset, I got the following error:

MlflowException: Unable to map 'np.object' type to MLflow DataType. np.object canbe mapped iff all values have identical data type which is one of (string, (bytes or byterray),  int, float)

The same code worked fine in pycaret 2.0.

**Comment by pycaret** [comment]
@sagarnildass Hi, Thanks for reporting. This seems like an error from `MLFlow`. I tried to reproduce this out of `pycaret` and I was successful. See below code that throws an error:

```
import pandas as pd
data = pd.read_csv('titanic.csv') #train data from Kaggle
from mlflow.models.signature import infer_signature
infer_signature(data)
```
This gives the following error:
MlflowException: Unable to map 'np.object' type to MLflow DataType. np.object canbe mapped iff all values have identical data type which is one of (string, (bytes or byterray),  int, float).

I will log an issue on MLFlow GitHub.

**Comment by sagarnildass** [comment]
Hey

Thanks for the quick reply. 

I found out that presence of null values are a problem. If the dataset contains null values, this error was raised. When I imputed the null values, this problem was solved. Can you also mention this when you log this issue?

Thanks!

**Comment by pycaret** [comment]
@sagarnildass Thanks. I have added that in my issue but I don't think so it's 100% True. I have worked with few missing datasets and it worked okay. For example, the `hepatitis` dataset on our repo works fine. Example code:

```
from pycaret.datasets import get_data
data = get_data('hepatitis')
from pycaret.classification import *
s = setup(data, target = 'Class', log_experiment=True, experiment_name = 'hepatitis1')
```

This dataset has missing values but it just worked fine. 

![image](https://user-images.githubusercontent.com/58118658/91642055-41991700-e9f6-11ea-9b6f-0f42a86401d9.png)

Can you investigate more and add your comments on the original issue here: https://github.com/mlflow/mlflow/issues/3362

Thanks a lot for helping.

**Comment by pycaret** [comment]
@Yard1 I don't know how soon `MLFLow` will be able to fix this but in `2.2` we will have to create some kind of exceptions under `logging_param` chunks to not fail the process even when `infer_signature` fails, as it's not mandatory and has no impact other than the signature file that gets generated under `model` directory when `log_experiment` is set to `True`.

**Comment by sagarnildass** [comment]
@pycaret : I believe object datatypes are a problem. It clearly states: "np.object canbe mapped iff all values have identical data type which is one of (string, (bytes or byterray), int, float)". So do you think null values in a object datatype column might be the root  problem here? Because in hepatitis data, all the columns are numeric.

**Comment by Yard1** [comment]
@pycaret If we get MLFlow logging into a function then it will be easy to wrap it into a try except block.

**Comment by pycaret** [comment]
@sagarnildass Thanks again for reporting. I am planning to do a bug fix release tomorrow `2.1.1`. For now, I have wrapped this inside `try` and `except` clause to avoid the error. I have tested it on the titanic dataset.

Can you please sync the `master` and try to see if you can reproduce the error now?

Thanks

**Comment by sagarnildass** [comment]
Done...it's working as expected.

**Comment by pycaret** [comment]
@sagarnildass Thanks. I will publish the `2.1.1.` release today. @Yard1 FYI.

Thanks for your help @sagarnildass
