### ISSUE TITLE
Recursive Feature Selection is too slow

### ISSUE THREAD

**Issue by reza1615** [pycaret/pycaret#57]
Please make it verbose to show results in each iterations. may be stopping at the middle is useful.
I test it for [this tutorial](http://www.pycaret.org/tutorials/html/CLF101.html) and after 10min I stopped the process

**Comment by pycaret** [comment]
Marketing for investigation and future enhancement.

**Comment by reza1615** [comment]
@pycaret You removed the history https://github.com/pycaret/pycaret/graphs/contributors
I don't contribute here
