### ISSUE TITLE
Facing issue when load .pkl in new environment , NameError: name 'target_inverse_transformer' is not defined

### ISSUE THREAD

**Issue by saitej123** [pycaret/pycaret#571]
For my streamlit app , used only .pkl output from pycaret. when I loaded and run the app, got error

name 'target_inverse_transformer' is not defined. 2 months back I used same code It was working .

but when I loaded the pkl file in the  same notebook where I created model, it is fine . 

![image](https://user-images.githubusercontent.com/18657211/91666585-984c4100-eb1b-11ea-9a9a-a4cd78f754fd.png)

**Comment by saitej123** [comment]
https://github.com/saitej123/ML-APP-HEROKU

Please use this repo to recreate

**Comment by pycaret** [comment]
@saitej123 Have you trained your model using `2.0` and trying to generate predictions using `2.1`? 

We have recently changed the behavior of `Pipeline`. Can you try re-training the model in `2.1` and see if you still get the error?

**Comment by pycaret** [comment]
@saitej123 This could also be due to one of the bug in `2.0`. Can you please update to `2.1` and see if this is okay now?

**Comment by saitej123** [comment]
@pycaret I am using latest version, 
![image](https://user-images.githubusercontent.com/18657211/91681543-58fa1080-eb6c-11ea-90e6-67fd402507f0.png)

trained model on latest version and tried to deploy.

**Comment by pycaret** [comment]
@saitej123 I can't reproduce the issue. Please provide your notebooks/code so I can have a look.

**Comment by pycaret** [comment]
@saitej123 Thanks. I have now figured out the issue. It's a bug, I have fixed this and will shortly release 2.1.2 on PyPi. I will ask you to please retest after the update. Thanks

**Comment by pycaret** [comment]
@saitej123  After updating my version `pycaret==2.1.2` this works fine now. 

![image](https://user-images.githubusercontent.com/58118658/91745355-d9c70580-eb88-11ea-921a-62b39b82f4b8.png)

Thank you for reporting the bug.

**Comment by saitej123** [comment]
Cheers !
