### ISSUE TITLE
confused about the steps to reach a prediction

### ISSUE THREAD

**Issue by webzest** [pycaret/pycaret#572]
I am excited to work with your pycaret tool for python.  I use caret for R and like it, but I find it unable to help me raise the score on kaggle.  I was so happy to see your python version and hope it can help me deliver a great prediction for my housing competition project.
I am trying to predict housing prices and was trying to follow the tutorials.  I am not able to find a straight-forward tutorial that I can use from start to finish to reach a prediction.  for example, I would like to stack three models together (ensemble) to make a final prediction on some unknown data after training on a labeled dataset.  
The tutorials are all in pieces and only cover one single model at a time.  I was wondering if you have an approach or notebook that takes me step by step to reach a regression prediction with 4 models stacked together.

**Comment by pycaret** [comment]
@webzest Thanks. There are many tutorials around. Tutorials were created to provide building blocks but there are also many examples available that shows end-to-end process plus you can find all my tutorials here: https://medium.com/@moez_62905

For now, let me show an end-to-end flow here:

```
from pycaret.datasets import get_data
data = get_data('boston')

from pycaret.regression import *
reg1 = setup(data, target = 'medv')
top3 = compare_models(n_select = 3)
stacker = stack_models(top3)
stacker = finalize_model(stacker)
predict_model(stacker, data=new_df)
```
Hope this helps. Please close the issue, if this answers your question.

**Comment by webzest** [comment]
Thank you for your response...  I ran your recommended step-by-step.  The predictions were not great, In fact, they were terrible and scored 0.19739.   This score is way to high and needs to be improved...    I am looking for a much better score, such as a 0.0001 or we can start with a 0.10000, if that is even possible.

How would we go about tuning the initial selected top 3 models with a GridSearchCV(), for example, to enhance/lower the score from the default results of 0.19739?

**Comment by pycaret** [comment]
@webzest Not sure I can help you with scores. It really depends on the dataset. 

You can tune your top3 models. Here is what I would do:

```
top3 = compare_models(n_select = 3)
tuned_top3 = [tune_model(i) for i in top3]
```

Hope this helps.

**Comment by webzest** [comment]
when I tuned as indicated, the score is higher, not lower: 0.24312  :(

**Comment by pycaret** [comment]
@webzest Sorry. Can't help you without any more information. Can you share the dataset and your script?

**Comment by webzest** [comment]
Sure...  
You can download the Data from here:  https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data
train and test data are available for you to download.
```

#import regression module 
from pycaret.regression import *
from enum import Enum
import pandas as pd
import numpy as np

### STEP1: settings
class Settings(Enum):
    train_path    = './data/train.csv'
    test_path     = './data/test.csv'

    def __str__(self):
        return self.value

def process_data(train_path, test_path):  
    global train
    global test
    
    # load data
    train = pd.read_csv(str(train_path))
    test = pd.read_csv(str(test_path))

process_data(Settings.train_path, Settings.test_path)

reg1 = setup(train, target = 'SalePrice')
top3 = compare_models(n_select = 3)
tuned_top3 = [tune_model(i) for i in top3]
stacker = stack_models(tuned_top3)
stacker = finalize_model(stacker)
predictions = predict_model(stacker, data=test)
```

**Comment by pycaret** [comment]
@webzest Thanks. Can you share the notebook, please?

**Comment by webzest** [comment]
[pyCaretEnsembleReduced.zip](https://github.com/pycaret/pycaret/files/5156031/pyCaretEnsembleReduced.zip)

**Comment by webzest** [comment]
please let me know if that works...  I can also create a GIT to share it, if that is better for you.
