### ISSUE TITLE
Getting Error when I run Regression problem

### ISSUE THREAD

**Issue by whiran** [pycaret/pycaret#575]
Recently I use pycaret package to solve my regression issue. Unfortunately, following issue came up when I run jupyter notebook.
`blacklist  = ['ransac', 'TheilSen Regressor']`
`top_model = compare_models(
    blacklist = ['TheilSen Regressor']
    ,sort = 'MAE' ## competition metric
    ,turbo = True
    ,verbose=1
)`
**TypeError: compare_models() got an unexpected keyword argument 'blacklist'**

In addition, when we try to run the code  
`top3 = compare_models(n_select = 3)`

I got following error
**ValueError: If using all scalar values, you must pass an index**

The data description  is mention below. 
![2020-08-31 11_52_07-Window](https://user-images.githubusercontent.com/7403939/91688821-805ad880-eb80-11ea-8418-47c1040bac4c.jpg)

Can some one help me to get solve this problem.

**Comment by Yard1** [comment]
`blacklist` has been renamed to `exclude`. Also, you need to use the ID of the TheilSen Regressor, not the full name. You can find the IDs in the documentation.

**Comment by pycaret** [comment]
@whiran As @Yard1 said, In `2.1` we have renamed `blacklist` and `whitelist` to `exclude` and `include`. Please read the release notes for more details. Also as he mentioned, you have to put `ID` of the model in `exclude` or `include`. To get all the model information you can do this:

```
from pycaret.regression import models
models()
```
Hope this helps.
