### ISSUE TITLE
Custom Transformer Integration

### ISSUE THREAD

**Issue by krlng** [pycaret/pycaret#577]
**Is your feature request related to a problem? Please describe.**
I want to create more powerful, hand-crafted features. Therefore I often create custom sklearn Transformers and use those in a Pipeline with my model. How ever, this does not work with pycaret, since it is not possible to apply the Transformers before doing the train_test_split, which is done within the setup step. How ever I am not aware of a configuration, which would apply some custom functionality after the train_test_split but before the model training.

**Describe the solution you'd like**
Include an option to the setup function to pass a custom [sklearn pipeline](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html), which will be run after the train_test_split.

**Describe alternatives you've considered**
I think I could manually set the X_train, y_train... datasets after setup, but this really breaks the beautiful workflow of pycaret

**Comment by pycaret** [comment]
@krlng Great suggestions. Would you have time and skills to work on this change?

**Comment by Yard1** [comment]
The changes I have made on refactor allow for this already, I just need to add it as a parameter to setup

**Comment by Yard1** [comment]
`2.2` will have `custom_pipeline_steps_after_split_before_pycaret` and `custom_pipeline_steps_after_split_after_pycaret` parameters, allowing the user to add their custom transformers after train-test split and before/after PyCaret's transformers (eg. SMOTE).

**Comment by krlng** [comment]
That sounds just perfect - can't wait for 2.2
