### ISSUE TITLE
Set n_jobs

### ISSUE THREAD

**Issue by reza1615** [pycaret/pycaret#58]
How can i set n_jobs=-1

**Comment by pycaret** [comment]
n_jobs are by default set to -1 in all processes.

**Comment by reza1615** [comment]
in the below image shows n_jobs is None
![image](https://user-images.githubusercontent.com/2202483/80313615-f0fc7d80-87b9-11ea-886b-3a62515f080f.png)

**Comment by pycaret** [comment]
Actuall you are right. This is a bug. 

Thanks for pointing out.

**Comment by pycaret** [comment]
Re-opened and marked as bug.
