### ISSUE TITLE
is there any way to set default 'yes' to "setup" Step?

### ISSUE THREAD

**Issue by saitej123** [pycaret/pycaret#583]
At the end of this step we have to give  "yes' or quit 
clf1 = setup(data, target = 'Class variable') 

is there any way to setup that in default step? 

trying to implement pycaret AUTOML using streamlit based on target variable selection 
 unless I select it wont got the next step 

Please suggest any hack to select yes

**Comment by pycaret** [comment]
@saitej123 Yes. please pass `silent = True` within the `setup` function. You can programmatically control the data types, in this case, using `categorical_features` and `numeric_features` param inside the `setup`. Read more: https://www.pycaret.org/setup

**Comment by saitej123** [comment]
thanks, is there any way to deploy in heroku..with less dependencies..size
reached more than 600 mb..app crashed

**Comment by pycaret** [comment]
@saitej123 Unfortunately not.

**Comment by saitej123** [comment]
Ok thanks
