### ISSUE TITLE
Trigonometry Features not working

### ISSUE THREAD

**Issue by gcaminero** [pycaret/pycaret#584]
Hi!!

I got no results when trying to get feature enginnering by trigonometry features setting the boolean: trigonometry_features = True
This is not working as expected. It isn't generating new features like expected in the example: https://i0.wp.com/pycaret.org/wp-content/uploads/2020/03/trig_after.png?resize=1080%2C186&ssl=1

As the example, my output: reg1[0].columns is:

```python
Index(['age', 'bmi', 'sex_female', 'sex_male', 'children_0', 'children_1',
       'children_2', 'children_3', 'children_4', 'children_5', 'smoker_no',
       'smoker_yes', 'region_northeast', 'region_northwest',
       'region_southeast', 'region_southwest'],
      dtype='object')
```

My environment: windows, anaconda python 3.7 and tried with pycaret 2.0 and 2.1

Thanks

**Comment by Yard1** [comment]
Can you run this after setup: `get_config('X').columns` and see if the columns are in the returned dataframem

**Comment by gcaminero** [comment]
Hi

This is the result:

```
get_config('X').columns
---
Index(['age', 'bmi', 'sex_female', 'sex_male', 'children_0', 'children_1',
       'children_2', 'children_3', 'children_4', 'children_5', 'smoker_no',
       'smoker_yes', 'region_northeast', 'region_northwest',
       'region_southeast', 'region_southwest'],
      dtype='object')
```

**Comment by pycaret** [comment]
@gcaminero I have checked. For some reason, you need to have `polynomial_features` enabled as well for `trigonometry_features` to work but on this particular dataset even that is not working.

**Comment by gcaminero** [comment]
This works, but they are discarded because of their low importance.
You can see how it works by setting the threshold_polynomial = 0.99

And the output is next:
```
Index(['age', 'bmi', 'sin(bmi)', 'cos(bmi)', 'cos(age)', 'age_Power2',
       'bmi_Power2', 'sin(age)', 'tan(age)', 'tan(bmi)', 'sex_female',
       'sex_male', 'children_0', 'children_1', 'children_2', 'children_3',
       'children_4', 'children_5', 'smoker_no', 'smoker_yes',
       'region_northeast', 'region_northwest', 'region_southeast',
       'region_southwest'],
      dtype='object')
```

The problem is that polynomials may not be of interest in my case so It would be nice if they could be chosen separately.
Also making posible to set `trigonometry_threshold` as importance threshold.

Thanks

**Comment by pycaret** [comment]
@gcaminero You know actually what. The threshold for `trigonometry_features` is also controlled through `polynomial_threshold`. Will just have to clarify that in the documentation somewhere.

Thanks for bringing this up.
