### ISSUE TITLE
Adding SGD to the model list

### ISSUE THREAD

**Issue by reza1615** [pycaret/pycaret#59]
Based on [here](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html). SGD mostly recommended for data more than 100K. Please add it to the list of models to have better comparsion.

**Comment by pycaret** [comment]
It is already there.  To create a linear SVM model use:

create_model('svm'). 

SVM uses SGDClassifier() from sklearn with linear parameters to create a linear support vector machine. For radial kernel you can use:

create_model('rbfsvm')

Thanks.
