### ISSUE TITLE
[Bug] Tuned model has worse performance than default model

### ISSUE THREAD

**Issue by rohan-gt** [pycaret/pycaret#590]
In this particular Kaggle [example](https://www.kaggle.com/frtgnn/pycaret-introduction-classification-regression), the tuned LghtGBM performance has worse performance compared to the default model. This can be fixed if the default model is compared to the tuned model and the best model chosen from there

**Comment by Yard1** [comment]
You can use the `choose_better=True` parameter to return the untuned model if it's better.

**Comment by pycaret** [comment]
@rohan-gt as @Yard1 mentioned you can use `choose_better` parameter in functions to return the better performing model as a result of your functions like `tune_model` `ensemble_model` etc.

**Comment by gm039** [comment]
Hi
Thanks for the suggestion. The option choose_better=True still gives a worse model than the untuned one. Even I tried increasing n_iter, but no much improvement.
Please suggest.

![image](https://user-images.githubusercontent.com/50217085/92945548-6d1ef700-f423-11ea-8055-29566e790164.png)

**Comment by Yard1** [comment]
The printed out grid is for the tuned model, but the model object is the better one.
