### ISSUE TITLE
Replace Nan values by Zero in pycaret 2.1

### ISSUE THREAD

**Issue by chamsdg** [pycaret/pycaret#591]
Hello, when i want to replace nan values by zero in version 2.1
i have an issue

i get this error:

`SystemExit: (Value Error): numeric_imputation param only accepts 'mean' or 'median' `

someone can help me
thank you

**Comment by pycaret** [comment]
@chamsdg Which module are you using?

**Comment by chamsdg** [comment]
i use classification for predict churn
i work in jupyterLab

**Comment by pycaret** [comment]
@chamsdg What's your version?

**Comment by chamsdg** [comment]
ok i will try it

**Comment by chamsdg** [comment]
hello i try iy

but i have the same error

![pycaret_2](https://user-images.githubusercontent.com/50946856/92240756-6e996e00-eebd-11ea-89de-d02cafad9bc2.PNG)


![pycaret_zero](https://user-images.githubusercontent.com/50946856/92240786-76591280-eebd-11ea-9c29-edfe16280847.PNG)

**Comment by pycaret** [comment]
@chamsdg Are you using any virtual / conda environment?

**Comment by chamsdg** [comment]
Yes, i create a virtual environment

**Comment by pycaret** [comment]
@chamsdg Please uninstall `pycaret` and install again.

```
pip uninstall pycaret
pip uninstall pycaret-nightly
pip install pycaret
```

It seems like there is a conflict in your environment with `pycaret-nightly` or older versions.

Thanks

**Comment by chamsdg** [comment]
I try all
but i have the same error
