### ISSUE TITLE
Bug: compare_models() got an unexpected keyword argument 'blacklist'

### ISSUE THREAD

**Issue by lbaiao** [pycaret/pycaret#592]
The `compare_models` method does not accept the `blacklist` argument.

![image](https://user-images.githubusercontent.com/25750921/92119704-8940e980-edce-11ea-98bc-b84eb9d3b544.png)

version: pycaret==2.1.2

**Comment by jrycw** [comment]
`blacklist` and `whitelist` parameters in `compare_models` function is now renamed to `exclude` and `include` with no change in functionality for [pycaret2.1](https://towardsdatascience.com/pycaret-2-1-is-here-whats-new-4aae6a7f636a).

**Comment by lbaiao** [comment]
@jrycw Thanks for the answer! I think this change in `compare_models` is not documented yet.

**Comment by krlng** [comment]
Would be great, if this could be changed in the docs as well: https://pycaret.org/compare-models/
