### ISSUE TITLE
Error in Pycaret regression/predict_model 

### ISSUE THREAD

**Issue by papagala** [pycaret/pycaret#593]
I used to be able to run [pycaret_deployment_streamlit](https://github.com/pycaret/pycaret-deployment-streamlit) with no problem. All of the sudden I started getting this error 

```python
pycaret/regression.py", line 7955, in predict_model     sys.exit("Pipeline not found")
```
![image](https://user-images.githubusercontent.com/6526276/92144962-1c811b80-eddd-11ea-8ca6-422ca0ed7549.png)

Reproduction steps

```bash
cd pycaret-deployment-streamlit
virtualenv virtual
source virtual/bin/activate
virtual/bin/pip install --upgrade pip
virtual/bin/pip install --force-reinstall streamlit
virtual/bin/pip install --force-reinstall pycaret==2.1.2
virtual/bin/streamlit run app.py --server.address 0.0.0.0 --server.port 8888
```

I'm running Python 3.8 and tried it in multiple OS (Ubuntu anr MacOsX).

**Note: I originally opened this [issue on pycaret-deployment-streamlit](https://github.com/pycaret/pycaret-deployment-streamlit/issues/2), but I feel this problem is more general and worth expanding the scope**

**Comment by papagala** [comment]
I figured this out. It turned out that the model was built with Pycaret 1.0 and I was running the streamlit app with 2.1.2. I think it would be nice to put it on the docs if not already. I can help out with that.

**Comment by pycaret** [comment]
@papagala Yes. Can you please put a warning under the `predict_model` function for all modules. Please submit a PR on `master`. Following the documentation format followed for other functions. See the `warnings` section for the `compare_models` as an example.

**Comment by papagala** [comment]
[PR](https://github.com/pycaret/pycaret/pull/595) is up

**Comment by vireshsaini** [comment]
> I figured this out. It turned out that the model was built with Pycaret 1.0 and I was running the streamlit app with 2.1.2. I think it would be nice to put it on the docs if not already. I can help out with that.

I am also facing same problem in "predict_model
    raise ValueError("Pipeline not found")"  and i trained the model and ran on same version pycaret 2.2.3
I don't know where is the gap.
I just saved the model in .pkl file and using the same model in program for testing data set..
Please help
Thanks
Viresh
