### ISSUE TITLE
Inference of Numerical features in Clustering  not working even when forced ...

### ISSUE THREAD

**Issue by doubianimehdi** [pycaret/pycaret#594]
Hi,

I have the following dataset 
	LIBELLE_ARRET	CATEGORIE_TITRE	NBRE_VALID
997	CHATELET-LES HALLES	NAVIGO	83082
4606	SAINT-LAZARE	NAVIGO	60859
1904	GARE DU NORD	NAVIGO	54785
180	AUBER	NAVIGO	46096
2345	LA DEFENSE-GRANDE ARCHE	NAVIGO	45454
...	...	...	...
3426	NANTEUIL-SAACY	?	5
4422	ROSNY-SUR-SEINE	?	5
4641	SAINT-MARTIN-D'ETAMPES	?	5
5124	US	?	5
5283	VIARMES	?	5

info on the dataset : 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5509 entries, 0 to 5508
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype   
---  ------           --------------  -----   
 0   LIBELLE_ARRET    5509 non-null   category
 1   CATEGORIE_TITRE  5509 non-null   category
 2   NBRE_VALID       5509 non-null   int32   
dtypes: category(2), int32(1)
memory usage: 63.9 KB

When executing this code : 
from pycaret.clustering import *
clu1 = setup(validsemtitre,
             numeric_features=['NBRE_VALID'],
             session_id=123, 
             log_experiment=True,
             log_plots = True, experiment_name='valmoycatarret1')

![image](https://user-images.githubusercontent.com/33954127/92224715-7c8dc580-eea2-11ea-87cf-0d4116dd8e1c.png)

But then : 
Description	Value
0	session_id	123
1	Original Data	(5509, 3)
2	Missing Values	False
**3	Numeric Features	0
4	Categorical Features	3**
5	Ordinal Features	False
6	High Cardinality Features	False
7	Transformed Data	(5509, 742)
8	Numeric Imputer	mean
9	Categorical Imputer	constant
10	Normalize	False
11	Normalize Method	None
12	Transformation	False
13	Transformation Method	None
14	PCA	False
15	PCA Method	None
16	PCA components	None
17	Ignore Low Variance	False
18	Combine Rare Levels	False
19	Rare Level Threshold	None
20	Numeric Binning	False
21	Remove Multicollinearity	False
22	Multicollinearity Threshold	None
23	Group Features	False

Anyone having the same issue ?

Thanks !

**Comment by pycaret** [comment]
@doubianimehdi The grid shows the inferred information on original dataset. I don't think it's looking at overwriting functions.

You can check get_config('X') and if `NBRE_VALID` is not one-hot-encoded then you are good. It will be treated as numeric.

**Comment by doubianimehdi** [comment]
Sorry but I didn't understand what you mean ...

**Comment by doubianimehdi** [comment]
the get_config('X') gives me this : 

NBRE_VALID | CATEGORIE_TITRE_? | CATEGORIE_TITRE_AMETHYSTE | CATEGORIE_TITRE_AUTRE TITRE | CATEGORIE_TITRE_FGT | CATEGORIE_TITRE_IMAGINE R | CATEGORIE_TITRE_NAVIGO | CATEGORIE_TITRE_NAVIGO JOUR | CATEGORIE_TITRE_NON DEFINI | CATEGORIE_TITRE_TST
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
20.0 | 1.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
96.0 | 0.0 | 1.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
37.0 | 0.0 | 0.0 | 1.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
81.0 | 0.0 | 0.0 | 0.0 | 1.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
570.0 | 0.0 | 0.0 | 0.0 | 0.0 | 1.0 | 0.0 | 0.0 | 0.0 | 0.0
... | ... | ... | ... | ... | ... | ... | ... | ... | ...
124.0 | 0.0 | 0.0 | 0.0 | 1.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
652.0 | 0.0 | 0.0 | 0.0 | 0.0 | 1.0 | 0.0 | 0.0 | 0.0 | 0.0
3070.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 1.0 | 0.0 | 0.0 | 0.0
6.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 1.0 | 0.0 | 0.0
164.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 1.0

It seems ok for the execution but NBRE_VALID is numeric in the original dataset , and it does not show here : 
Description Value
0 session_id 123
1 Original Data (5509, 3)
2 Missing Values False
**3 Numeric Features 0 => SHOULD BE Numeric Features 1 !!!
4 Categorical Features 3**
5 Ordinal Features False
6 High Cardinality Features False
7 Transformed Data (5509, 742)
8 Numeric Imputer mean
9 Categorical Imputer constant
10 Normalize False
11 Normalize Method None
12 Transformation False
13 Transformation Method None
14 PCA False
15 PCA Method None
16 PCA components None
17 Ignore Low Variance False
18 Combine Rare Levels False
19 Rare Level Threshold None
20 Numeric Binning False
21 Remove Multicollinearity False
22 Multicollinearity Threshold None
23 Group Features False
