### ISSUE TITLE
Issue with fix_imbalance_method

### ISSUE THREAD

**Issue by danbricedatascience** [pycaret/pycaret#598]
When setting `fix_imbalance=True,fix_imbalance_method=imblearn.over_sampling.RandomOverSampler ` in setup (or any other imblearn method, including SMOTE), I always get this error when calling `create_model('rf')`:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-164-5b7c95f350b2> in <module>
----> 1 rf = create_model('rf')

~/anaconda3/envs/ai/lib/python3.8/site-packages/pycaret/classification.py in create_model(estimator, ensemble, method, fold, round, cross_validation, verbose, system, **kwargs)
   3324                 resampler = fix_imbalance_method_param
   3325 
-> 3326             Xtrain,ytrain = resampler.fit_sample(Xtrain, ytrain)
   3327             logger.info("Resampling completed")
   3328 

TypeError: fit_resample() missing 1 required positional argument: 'y'
```

**Comment by pycaret** [comment]
@danbricedatascience Can you please upload the sample dataset, I will try to reproduce the issue.

**Comment by djokester** [comment]
@pycaret can I take this issue up?

**Comment by danbricedatascience** [comment]
@pycaret  this dataset is confidential but I can check a dummy one that can generate the same issue.

**Comment by pycaret** [comment]
@danbricedatascience Great. Please upload the sample data so I can reproduce the issue.

**Comment by danbricedatascience** [comment]
Please find how to reproduce with synthetic data: 

```python
dummy_df = pd.DataFrame.from_dict({
    'feature1': np.random.randint(0,10,100),
    'feature2': np.random.randint(0,10,100),
    'feature3': np.random.randint(0,10,100),
    'feature4': np.random.randint(0,10,100),
    'feature5': np.random.randint(0,10,100),
    'label': np.random.choice([0,1],100,p=[0.9,0.1])
})

experiment = setup(data=dummy_df,target='label',
    numeric_features=dummy_df.columns[:5],
    folds_shuffle=False,session_id=123,
    fix_imbalance=True,
    fix_imbalance_method=imblearn.over_sampling.RandomOverSampler)

clf = create_model('rf',fold=5)
```

Then we get :

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-385-14cc4cc2416a> in <module>
----> 1 clf = create_model('rf',fold=5)

~/anaconda3/envs/ai/lib/python3.8/site-packages/pycaret/classification.py in create_model(estimator, ensemble, method, fold, round, cross_validation, verbose, system, **kwargs)
   3324                 resampler = fix_imbalance_method_param
   3325 
-> 3326             Xtrain,ytrain = resampler.fit_sample(Xtrain, ytrain)
   3327             logger.info("Resampling completed")
   3328 

TypeError: fit_resample() missing 1 required positional argument: 'y'
```

**Comment by Yard1** [comment]
Are you sure this isn't an issue with imblearn itself?

**Comment by asaglimbeni** [comment]
I resolved instantiating the class RandomOverSampler
`
dummy_df = pd.DataFrame.from_dict({
    'feature1': np.random.randint(0,10,100),
    'feature2': np.random.randint(0,10,100),
    'feature3': np.random.randint(0,10,100),
    'feature4': np.random.randint(0,10,100),
    'feature5': np.random.randint(0,10,100),
    'label': np.random.choice([0,1],100,p=[0.9,0.1])
})

experiment = setup(data=dummy_df,target='label',
    numeric_features=dummy_df.columns[:5],
    folds_shuffle=False,session_id=123,
    fix_imbalance=True,
    fix_imbalance_method=imblearn.over_sampling.RandomOverSampler() ) # <--- instance of RandomOverSampler
clf = create_model('rf',fold=5)
`

**Comment by pycaret** [comment]
@asaglimbeni Thanks for sharing.

I am closing the issue now. @danbricedatascience If this is still a problem, please feel free to open another issue.
