### ISSUE TITLE
plot_model only works when used once in a Jupyter cell

### ISSUE THREAD

**Issue by TKassis** [pycaret/pycaret#599]
The plot_model() function works well when run once in a Jupyter cell, but when I try:

```
available_plots = ['residuals', 'error', 'cooks',  'rfe', 'learning', 'vc', 'manifold', 'feature']

for p in available_plots:
    try:
        plot_model(best_model, plot=p, scale=2, save=True, verbose=False)
    except:
        print('{} plot could not be generated for target {}'.format(p, target))
```

The resulting plots are flawed in a variety of ways. See attached as an example.

Is there a way to save these plots outside of a Jupyter notebook? I'd like to use them in a .py script.

![Validation Curve](https://user-images.githubusercontent.com/9168908/92313123-d28f6580-ef95-11ea-872b-a6c43b2bbbb2.png)

**Comment by pycaret** [comment]
@TKassis you can use the `save` parameter inside the `plot_model` function to save them as `png` file in your working directory. So if you are using `.py` scripts to run your jobs, you can do this:

```
plot_model(model, save=True)
```

This will use the `png` file in your working directory. You cannot choose the names of files as of now, it will use some default names (self-explanatory, though). You can also increase the `scale` of the plot to print high-resolution images. For example:

```
plot_model(model, save=True, scale = 3)
```

Hope this helps.

**Comment by TKassis** [comment]
Thank you for the feedback. Unfortunately, I'm already doing what you suggested, but the plots only behave properly when executed in a Jupyter notebook one cell at a time.

**Comment by Yard1** [comment]
I can take a look. What software are you using to handle notebooks @TKassis.

**Comment by TKassis** [comment]
Jupyter Lab (version 2.2.4)
