### ISSUE TITLE
Top Models from Compare Models

### ISSUE THREAD

**Issue by Riazone** [pycaret/pycaret#6]
Hi,

I was wondering if there is a way to select top 'n' models from compare models. If we can have this feature, the whole training process can be automated. This would also help users to use it in platforms like KNIME/Power BI that do not support HTML output.

Thanks,
Riaz

**Comment by pycaret** [comment]
### Feature now available in pycaret-nightly.

You can install **pycaret-nightly** using "pip install pycaret-nightly". 

You can test this and let us know what you think? Please close the issue if the enhancement addresses the original issue. 

It will be shipped to PyCaret 2.0x in few weeks.
