### ISSUE TITLE
Integrate custom accuracy function for CV in regression/classification?

### ISSUE THREAD

**Issue by shubhsoni** [pycaret/pycaret#60]

**Comment by pycaret** [comment]
Can you elaborate a little bit or share example?

**Comment by shubhsoni** [comment]
Sorry for incomplete info...
Below is an example of custom function used for tuning (could also be used during 'setup' itself)

##custom error function
def error_fun(y_true, y_pred):
    return np.sqrt(mean((np.log(y_true) - np.log(y_pred))**2))

##use user define error function 
hb = tune_model('huber', optimize=error_fun)

**Comment by pycaret** [comment]
@shubhsoni This feature is now added. Please sync `master` repo to test the feature. 

You can now pass `custom_scorer` in `tune_model` function for `classification.py` and `regression.py`.

If you are having issues with using this, please open another issue.

Hope this helps.
