### ISSUE TITLE
Predictions on a separate hold out set

### ISSUE THREAD

**Issue by rushingJustice** [pycaret/pycaret#600]
Hello!

Thank you for creating pycaret. I've learning a lot!

I am trying to make predictions on a personal holdout set (not the holdout set that pycaret auto-generated from `setup`). 

I figured it would be as simple as:

```
pipe = clf_loaded[0] #the loaded model (after save)
df_test_transformed = pipe.transform(df_test)
```

`df_test `appears to transform just fine, but when I go to use `predict_model`:

```
predict_new = predict_model(clf_loaded, data=df_test_transformed )
predict_new.head()
```

I get the following error: `SystemExit: (Type Error): test data does not have column ps_ind_01 which was used for training`

It appears that column `ps_ind_01` is getting dropped during `.transform`? I confirmed that all columns present in `df_test `are also present in `df_train `(the data I used for `setup`).

Thank you in advance!

**Comment by Yard1** [comment]
Don't transform the data yourself, it will be transformed inside the function. Just pass unedited data to it, it should work fine :)

**Comment by pycaret** [comment]
@rushingJustice If this answered your question, please feel free to close the issue.
