### ISSUE TITLE
New feature : add **kwarg to compare_models

### ISSUE THREAD

**Issue by danbricedatascience** [pycaret/pycaret#602]
Add `**kwarg` to `compare_models`. Several models accept the same args like `class_weight` for instance.

For managing the models not accepting a given arg:

- first call to the model with exception catch
- if exception is raised  : remove all the args for this model and call it again
- at the end of `compare_models` add a summary telling which models were not called with optional arg because at least ont the the args was not accepted

This will enable using `class_weight` for instance that could be critical for several models in some situations (rf, xgboost, lightgbm, et)

**Comment by Yard1** [comment]
Already in progress for `2.2`.

**Comment by pycaret** [comment]
@danbricedatascience 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.

**Comment by danbricedatascience** [comment]
I can't use it for `class_weight`. 

I get: 

```
~/anaconda3/envs/ai+/lib/python3.8/site-packages/imblearn/pipeline.py in fit(self, X, y, **fit_params)
    279                                  self._log_message(len(self.steps) - 1)):
    280             if self._final_estimator != "passthrough":
--> 281                 self._final_estimator.fit(Xt, yt, **fit_params)
    282         return self
    283 

TypeError: fit() got an unexpected keyword argument 'class_weight'
```

If it's applied to the model fit function only, it's normal as `class_weight` has to be applied to the model creation.

Anyway, can you confirm the syntax for fit_kwarg dict?

```python
best_model = compare_models(fit_kwargs={'class_weight':{0:1,0:5}})
```

**Comment by Yard1** [comment]
`class_weight` is not a fit param. Pass it as a keyword argument (`compare_models(class_weight=:{0:1,0:5})`).

**Comment by jisho-iemoto** [comment]
Please let me learn about this, for my poor understanding.
I have a dataset containing imbalanced labels: Class 0:10, 1:1, 2:1, 3:1 in ratios, for example.
Then, where and how should I pass the parameters?

1. in setup, compare_models, create_model, tune_model, blend_models, ...?
2. How can I cast the parameter?
    <eg> compare_models(DF, target=TGT, class_weight={0:10,1:1,2:1,3:1})
              compare_models(DF, target=TGT, class_weight=[10,1,1,1])
3. Anything else to be considered?

**Comment by ekamperi** [comment]
Hey folks. Is there any update on this one? Pass `class_weight(s)` on `compare_models()` doesn't work. It yield an error: "TypeError: compare_models() got an unexpected keyword argument 'class_weights(s)'. Is it a valid workaround to change the class_weight attribute, after `compare_models()` returns and before calling `tune_model()`? To at least tune with the desired class weights?
