### ISSUE TITLE
Feature Request: Reduce max_depth to max 10 for rf, lgbm, xgb in tune_model

### ISSUE THREAD

**Issue by clgarciga** [pycaret/pycaret#605]
`tune_model` seems to never finish for me for lgbm and I think it is because `max_depth` can take a value up to 100 currently, which seems like quite a bit? And I would like to avoid passing my own parameter grid...

**Comment by Yard1** [comment]
Already done for `2.2`.

**Comment by pycaret** [comment]
@Yard1 I have done this for `xgboost` only in `2.1` release. Have you taken care of `lightgm` and `rf` as well?

**Comment by Yard1** [comment]
@pycaret I had no issues with those, even with that depth, but if other people experience problems we should reduce it for them as well.

**Comment by pycaret** [comment]
@clgarciga 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
