### ISSUE TITLE
Hi, I'm testing pycaret in Databricks but I can't visualize some plots, especially interactive graphics, for example the tsne plot, would you have any idea how I could visualize them?

### ISSUE THREAD

**Issue by CosmicMiriam** [pycaret/pycaret#607]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pycaret** [comment]
@CosmicMiriam Do you know if `plotly` is compatible with Databricks. I am not sure.

Can you give a try to create plots using plotly on Databricks? Please let us know.
