### ISSUE TITLE
Error loading saved model from different Jupyter notebooks

### ISSUE THREAD

**Issue by David-Luca** [pycaret/pycaret#609]
Hi there,
I have an issue loading a saved model: when I load a saved model from the same Jupyter notebook where I created it there is no problem, but when I load it from a different notebook, I get the following error:
`---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
~/.local/share/virtualenvs/testing_productivizacion-kmC-PmVJ/lib/python3.6/site-packages/pycaret/regression.py in predict_model(estimator, data, round, verbose)
   7900     try:
-> 7901         target_transformer = target_inverse_transformer
   7902     except:

NameError: name 'target_inverse_transformer' is not defined

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-15-2a083b62a9ea> in <module>
----> 1 preds = predict_model(model, analytic_set)
      2 preds

~/.local/share/virtualenvs/testing_productivizacion-kmC-PmVJ/lib/python3.6/site-packages/pycaret/regression.py in predict_model(estimator, data, round, verbose)
   7901         target_transformer = target_inverse_transformer
   7902     except:
-> 7903         target_transformer = estimator.steps[13][1].p_transform_target # make it dynamic instead of hardcoding no 13
   7904 
   7905     # dataset

AttributeError: 'Empty' object has no attribute 'p_transform_target'`

**Comment by pycaret** [comment]
@David-Luca This was the bug we have recently fixed in `2.1.2` release. Can you please update your pycaret to `2.1.2`.

```
pip install --upgrade pycaret
```

Let me know how it goes.

**Comment by Wookloo** [comment]
You might have to re do the model from scratch as the model i created prior to the update i wasn't able to load it despite updating pycaret.

got the folowing error: 
TypeError: object of type 'NoneType' has no len()

**Comment by pycaret** [comment]
@David-Luca Yes. Please retrain the model using the latest upgrade.
