### ISSUE TITLE
MLflow integration for load and save models 

### ISSUE THREAD

**Issue by sulphuricacid** [pycaret/pycaret#612]
**Is your feature request related to a problem? Please describe.**
I have tried to integrate mlflow with pycaret to load and save pycaret model with mlflow. But later realised that mlflow enables to save and load models for few model varieties like sklearn,xgboost,fast.ai etc, but not pycaret models.

**Describe the solution you'd like**
Include MLflow save and load functions for pycaret models.

**Describe alternatives you've considered**

**Additional context**

**Comment by pycaret** [comment]
@sulphuricacid You can use `sklearn` flavor to `load_model` from `MLFlow`. 

https://www.mlflow.org/docs/latest/_modules/mlflow/sklearn.html#load_model
