### ISSUE TITLE
availibale datatype in setup function, like sparse metrics

### ISSUE THREAD

**Issue by twostarxx** [pycaret/pycaret#615]
When the sparse metrics size is too big, `pd.DataFrame` datatype in `regression.setup` function is out of memory. Is there an solution?

**Comment by pycaret** [comment]
@twostarxx How big is your dataset?

**Comment by twostarxx** [comment]
> @twostarxx How big is your dataset?

```python
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129709 entries
Columns: 10846 entries
dtypes: float64(10846)
memory usage: 10.5 GB
