### ISSUE TITLE
Requirement for K- Prototype clustering

### ISSUE THREAD

**Issue by ArjunKadya** [pycaret/pycaret#618]
**Is your feature request related to a problem? Please describe.**

It is becoming difficult to get precise results in existing clustering algorithms of pycaret for data set containing both numerical and categorical features. 

**Describe the solution you'd like**
While K modes will work with categorical and k means with numerical. Require algorithm like K prototypes to handle data-sets having both categorical and numerical in one go.

**Describe alternatives you've considered**
https://github.com/nicodv/kmodes

k-prototypes

[HUANG97] | (1, 2) Huang, Z.: Clustering large data sets with mixed numeric and categorical values, Proceedings of the First Pacific Asia Knowledge Discovery and Data Mining Conference, Singapore, pp. 21-34, 1997.
-- | --

**Comment by pycaret** [comment]
@ArjunKadya 

KPrototypes is not available in the model library of `pycaret.clustering` but you can still use it in PyCaret. For example:

```
from pycaret.datasets import get_data
data = get_data('jewellery')

from pycaret.clustering import *
s = setup(data, sesion_id = 123)

from kmodes.kprototypes import KPrototypes
kprot = KPrototypes(num_clusters = 4) # used 4 as example

kprot_trained = create_model(kprot)
```

Hope this helps.

**Comment by angieariza** [comment]
> ```
> from pycaret.datasets import get_data
> data = get_data('jewellery')
> 
> from pycaret.clustering import *
> s = setup(data, sesion_id = 123)
> 
> from kmodes.kprototypes import KPrototypes
> kprot = KPrototypes(num_clusters = 4) # used 4 as example
> 
> kprot_trained = create_model(kprot)
> ```
> 
> Hope this helps.

Hi I'm trying to implement k-modes as you said, but it happens that setup transforms all my categorical features into numerical by itself and it haven't been possible to use the k-prototype algorithm, it's suggesting me the k-means algorithm . Do you know how can I stop the transformation to happens?

**Comment by moezali1** [comment]
@angieariza You can stop all the transformations by passing `preprocess=False` in the `setup` function.
