### ISSUE TITLE
Clustering create_model not working

### ISSUE THREAD

**Issue by Satinder83** [pycaret/pycaret#62]
The create_model for Kmeans or other clustering seems not to be working.  I get the following error 

SystemExit: (Value Error): Estimator Not Available. Please see docstring for list of available estimators.

even n_clusters is also not available. 

Setup worked fine. 

I am using colab for processing

**Comment by pycaret** [comment]
This is exception. Can you share the code you are writing?

**Comment by Satinder83** [comment]
Hi,
Here is the code - 

`import pandas as pd
from pycaret.classification import *

mf = pd.read_csv(mf_test_complete.csv', thousands= ',')

clf1 = setup(data = mf, 
             numeric_imputation= 'mean', 
             categorical_imputation = 'mode', 
             create_clusters= False, 
             normalize = True,
             target = 'greatstone_rating', 
             ignore_features= ['fund_id','tag' ],
             categorical_features = ['investment_class','fund_size', 'category'],
             #pca = True, pca_components = .9, 
             remove_outliers = True,
             feature_selection = False,
             remove_multicollinearity = True, 
             numeric_features = ['bb_rating','below_b_rating','others_rating','b_rating','a_rating','aaa_rating','aa_rating','bbb_rating',
                                 'maturity_bond','duration_bond','portfolio_communication_allocation','portfolio_financial_services',
                                 'portfolio_industrials_allocation','portfolio_tech_allocation','portfolio_materials_basic_allocation',
                                 'portfolio_energy_allocation','portfolio_consumer_defence_allocation','portfolio_healthcare_allocation',
                                 'portfolio_property_allocation','portfolio_utils_allocation','portfolio_cyclical_consumer_allocation',
                                 'fund_ratio_net_annual_expense','pb_ratio','ps_ratio','pc_ratio','pe_ratio','yield',
                                 'return_ytd','cash_percent_of_portfolio','ytd_return_category','stock_percent_of_portfolio',
                                 'bond_percentage_of_porfolio','fund_return_3years','3yrs_treynor_ratio_fund','3yrs_sharpe_ratio_fund',
                                 '3yrs_treynor_ratio_category','3yrs_sharpe_ratio_category','3_years_return_category','5yrs_sharpe_ratio_fund',
                                 '5yrs_sharpe_ratio_category','5yrs_treynor_ratio_fund','5yrs_treynor_ratio_category','5_years_return_fund',
                                 '5_years_return_category','10yrs_sharpe_ratio_fund','10yrs_treynor_ratio_fund','10yrs_treynor_ratio_category',
                                 '10_years_return_fund','10_years_alpha_category','10_years_return_category']
)







kmeans = create_model('kmeans')`

and the error - 

An exception has occurred, use %tb to see the full traceback.

SystemExit: (Value Error): Estimator Not Available. Please see docstring for list of available estimators.

**Comment by pycaret** [comment]
On top of your code you are importing classification module instead of clustering. You should import clustering module by:

from pycaret.clustering import *

**Comment by Satinder83** [comment]
This worked. Sorry, did not realize this.. I thought setup is same across pycaret modules. 
Great tool you have developed

**Comment by pycaret** [comment]
No problem. Closing this now.
