### ISSUE TITLE
Feature importance plot

### ISSUE THREAD

**Issue by Sebagam** [pycaret/pycaret#622]
Dear all,

How can I get the full feature importance list?
Currently, it shows only the 10 most important features.

Regards,
Sebastian

**Comment by hehuan710** [comment]
Same question

**Comment by pycaret** [comment]
@Sebagam @hehuan710 We will add a new plot `feature-all` in the next release. Keep an eye here.

**Comment by Sebagam** [comment]
Thanks,

While we wait, is there a quick override that we can apply to the code to avoid the feature list shortening? 

Another question, what does exactly the feature rank measure? Does the x-axis correspond to a statistical test score or is it just a weight of the feature assessing the relevance in the model?

**Comment by Yard1** [comment]
@Sebagam If you don't have issues with modifying the module code itself, [remove line 8138 in classification.py](https://github.com/pycaret/pycaret/blob/c65a6f83a893872ca343bc9f8fafbfa6f2c62396/pycaret/classification.py#L8138).

**Comment by krishcode** [comment]
for catboost it is saying plot_model cant be used and we need to use interpret_model , how to get feature importance for a catboost model?

**Comment by Yard1** [comment]
Using `interpret_model`.

**Comment by pycaret** [comment]
@krishcode The compatibility issue of `catboost` with `plot_model` function is fixed. Will be available in the next release `2.2`. Keep an eye on the repo for next release.

**Comment by pycaret** [comment]
@krishcode @Sebagam @hehuan710 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
