### ISSUE TITLE
regression “predict_model”  Error

### ISSUE THREAD

**Issue by hehuan710** [pycaret/pycaret#624]
![QQ截图20200913160659](https://user-images.githubusercontent.com/21091848/93013464-515e5100-f5db-11ea-96c1-0ce7bf71d701.png)
Hello,
Use regression Mode，“predict_model”  Error。

**Comment by AnshuTrivedi** [comment]
@hehuan710 can you share programmig file or lines of code used before error code line.
It seems there is no 'index' in dataframe.Or do what logging says use regression mode.

**Comment by hehuan710** [comment]
> @hehuan710 can you share programmig file or lines of code used before error code line.
> It seems there is no 'index' in dataframe.Or do what logging says use regression mode.

Yes, there is no 'index' column, but why do you need it?
