### ISSUE TITLE
Not able to fill missing values 

### ISSUE THREAD

**Issue by abhishekmamdapure** [pycaret/pycaret#63]
Hello, 

According to [Missing Value Imputation](https://pycaret.org/missing-values/) section, I am trying out to fill the missing values but the syntax is not mentioned. I am in search of the syntax to impute the missing values as mentioned on the page. 

I tried to use the following code but that does not work. 

```python
import pycaret
from pycaret.datasets import get_data
hepatitis = get_data('hepatitis')
```

```python
# Importing module and initializing setup
from pycaret.classification import *
clf1 = setup(data = hepatitis, target = 'Class',numeric_imputation='mean',categorical_imputation = 'mode')
```

The above code did not work and the missing values still exist in the dataset. Kindly, provide the syntax for the same. 

Thanks

**Comment by pycaret** [comment]
Can you please share the dataset and the code you are using?

**Comment by abhishekmamdapure** [comment]
Hello, 

I am using the same dataset mentioned in the pycaret which is 'hepatitis' and the code that I have used is mentioned above. 

I am looking for the syntax to fill the missing values using the pycaret library.

**Comment by abhishekmamdapure** [comment]
Hello, 

Can I kindly get any update on this?

**Comment by pycaret** [comment]
@abhishekmamdapure The missing values are imputed automatically. See an example how you can see imputed values.

from pycaret.datasets import get_data
data = get_data('hepatitis')

from pycaret.classification import *
clf1 = setup(data, target = 'Class')
clf1[0]

See how NaN is imputed on instance 3 in STERIOD column.

**Comment by WebDevelopmentLabs** [comment]
I am also having the same problem and it is not imputing the missing values. I am using a heart disease dataset. Shall I share that here?
