### ISSUE TITLE
Support lightgbm>=3.0.0 in pycaret 2.2

### ISSUE THREAD

**Issue by clgarciga** [pycaret/pycaret#633]
See: https://github.com/microsoft/LightGBM/releases/tag/v3.0.0

**Comment by Yard1** [comment]
If the sklearn wrapper hasn't changed, it should still work fine.

**Comment by clgarciga** [comment]
Okay, then I would suggest adding lightgbm>=3.0.0 to requirements.txt

**Comment by Yard1** [comment]
I can confirm it works with every lightgbm version starting 2.3.1, including 3.0.

**Comment by pycaret** [comment]
@Yard1 Thanks.
