### ISSUE TITLE
tune_model hangs at "loading_dependencies"

### ISSUE THREAD

**Issue by dknoxon** [pycaret/pycaret#634]
Hi,

I've been using pycaret with our dataset and wanted to use the tune_model feature.  However, it would hang on our dataset.  Switched over to the example in your documentation and get the same problem.  It hits the tune_model step and hangs at loading_dependencies / Initializing and never returns or completes and am forced to reset the kernel in Jupyter Lab.

I was running pycaret 2.0, and thought 2.1.2 would fix it, but it didn't.  Noticed another user about a month ago say they were having a similar issue with tune_model hanging at the same point.

Thx

**Comment by pycaret** [comment]
Can you please confirm the size of your dataset and the model you are using?

**Comment by dknoxon** [comment]
Yes ... I'm using the "kiva" dataset from the example code (see below) for LDA.

>>> from pycaret.datasets import get_data
>>> kiva = get_data('kiva')
>>> experiment_name = setup(data = kiva, target = 'en')
>>> tuned_lda = tune_model(model = 'lda', supervised_target = 'status')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6818 entries, 0 to 6817
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   country      6818 non-null   object
 1   en           6818 non-null   object
 2   gender       6818 non-null   object
 3   loan_amount  6818 non-null   int64 
 4   nonpayment   6818 non-null   object
 5   sector       6818 non-null   object
 6   status       6818 non-null   int64 
dtypes: int64(2), object(5)
memory usage: 8.9 MB

**Comment by pycaret** [comment]
@dknoxon Can you try reproducing this behavior on google colab?

**Comment by dknoxon** [comment]
Hi ... I tried on google colab and it doesn't complete.  Hangs at the same spot (initializing/loading dependencies), then I get a javascript error and have to force quit chrome.
