### ISSUE TITLE
Following data types have been inferred automatically, if they are correct press enter to continue or type 'quit' otherwise.

### ISSUE THREAD

**Issue by nithinreddyy** [pycaret/pycaret#635]
The above step is the problem for me. we can press enter when running on colab or jupyter. But how can we press when running code in command prompt or when we deploy code we can't press enter each and every time right? Is there any solution to this?

```
from pycaret.anomaly import *
ano1 = setup(data=dataset, session_id=123, log_experiment=True, experiment_name='anomaly1')
```

**Comment by Yard1** [comment]
Use `silent` param.

```python
from pycaret.anomaly import *
ano1 = setup(data=dataset, session_id=123, log_experiment=True, experiment_name='anomaly1', silent=True)
```

**Comment by nithinreddyy** [comment]
> Use `silent` param.
> 
> ```python
> from pycaret.anomaly import *
> ano1 = setup(data=dataset, session_id=123, log_experiment=True, experiment_name='anomaly1', silent=True)
> ```

Thanks, man.
