### ISSUE TITLE
Inconsistencies in compare_model Documentation replace (whitelist, blacklist) with (include, exclude)

### ISSUE THREAD

**Issue by ayoolafelix** [pycaret/pycaret#638]
compare_models = (whitelist = ['xgboost', 'lightgbm']) raises an error because instead the module had compare_models =(include = ['xgboost', 'lightgbm']) 

compare_models = (blacklist = ['xgboost', 'lightgbm']) raises an error because instead the module had compare_models =(exclude = ['xgboost', 'lightgbm']) 

There is a need to correct this either in the documentation or in the code itself. I'm willing to make the change I just want to the code I do need to know if (whitelist, blacklist) is the better option to (include, exclude)

**Comment by Yard1** [comment]
It will be fixed in the next release :)

**Comment by pycaret** [comment]
@ayoolafelix The documentation on the website is only updated on major releases. For the most-updated documentation please see this link: https://pycaret.readthedocs.io/en/latest/
