### ISSUE TITLE
pycaret  automl for large and medium sized dataset and dask integration

### ISSUE THREAD

**Issue by sanath984** [pycaret/pycaret#639]
Thinking on how to support large datasets above 1gb to 20gb

**context**
the tool is very good in simplify ml modeling with multiple models. the framework could be extended to dask so that it
can support distributed preprocessing, and training 
additionally it will be great if all the algorithms are ported to support incremental fitting for large datasets

**alternatives**
dask-ml but lot of customisation required to train multiple model on large datasets.

**Comment by Yard1** [comment]
We are considering adding support for libraries like Dask and Ray but that's planned for a future release.

**Comment by argenisleon** [comment]
Hi, Any update on this?

**Comment by piEsposito** [comment]
Hi, any updates on this?

**Comment by Yard1** [comment]
No updates, distributed training is something we would like to have but it's not on our schelude atm.

**Comment by moezali1** [comment]
This issue is now being moved to #2015
