### ISSUE TITLE
Tree visulization

### ISSUE THREAD

**Issue by vijay1057** [pycaret/pycaret#64]
Hi,

Thank You for a nice package.

Is there a way to visualize the tree output in Pycaret?
Like plot_tree or export_graphviz?

**Comment by pycaret** [comment]
Not yet available. Can you please provide an example. Will see If we can add it in future.

**Comment by vijay1057** [comment]
I have built a multiclass classification model and want to interpret the results. Currently interpretation is not available for multiclass, please correct me if wrong.

**Comment by pycaret** [comment]
yes. shapley values are not available for multiclass problems.
