### ISSUE TITLE
Bug when loading two modules, the prediction value is different

### ISSUE THREAD

**Issue by SSITB** [pycaret/pycaret#642]
I Have a strange error.
I have two trained modules (regression and classification)
when i load only the regression module and i use the predict_model function i got for example a number 1.6 
but when i have loaded only the classification module before the regression the prediction is now different

Below is an example of what i mean

# Example:

import pandas as pd
from sklearn import datasets
from pycaret.regression import *

#df is a loaded dataframe

mdl1= load_model('mdl1_Reg')
predictions = predict_model(mdl1, data = df)

### The output is for example 1.6

but when i add the below line under the mdl1, the prediction_model return another result
mdl2= load_model('mdl1_Class')

i think its something related to import * ,  
i solved by changing the import as below

## Solution
from pycaret.regression  import predict_model as reg_predict_model
from pycaret.regression  import load_model as reg_load_model

from pycaret.classification  import predict_model as class_predict_model
from pycaret.classification  import load_model as class_load_model

do you suggest another approach ?

**Comment by pycaret** [comment]
@SSITB This is the correct approach. Normally PyCaret works one module at a time but in cases where you want to use both, you can have to import the functions individually with a different alias, just like you have done in your code above.
