### ISSUE TITLE
Question: Is it possible to re train a saved model (.pkl) with a new set of data

### ISSUE THREAD

**Issue by Wookloo** [pycaret/pycaret#646]
Hi,

I have train a regression model with data for 2018 and 2019 to predict Sales for 2020.
I would like to know if it is possible to, once i get the new sales data every month, be able to load it in the saved model and readjust the model based on the latest data i received and then make new adjusted prediction ? 
Is this possible without have to start a model from scratch ?

Thanks

**Comment by pycaret** [comment]
@Wookloo You will have to manually re-train the model.

**Comment by Wookloo** [comment]
Got it thanks
