### ISSUE TITLE
New feature : add custom_scorer to create_model and compare_model

### ISSUE THREAD

**Issue by danbricedatascience** [pycaret/pycaret#647]
* Add the possibility to pass a `custom_scorer` to `create_model`, `compare_model`, `predict_model` and any other future displaying metrics
* Display its output in the returned score grid

**Comment by Yard1** [comment]
Already done for next release.

**Comment by pycaret** [comment]
@danbricedatascience Already done for next release.

**Comment by pycaret** [comment]
@danbricedatascience 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
