### ISSUE TITLE
Default RF n_estimators does not match with scikit-learn default RF

### ISSUE THREAD

**Issue by danbricedatascience** [pycaret/pycaret#649]
scikit-learn version installed: 0.23.1

Default `n_estimators` is 10 with pycaret and 100 with scikit-learn.

This default was changes in scikit-learn in 0.22.

When using many features, let's say 200, having only 10 estimators, each trained on sqrt(200) = 14 features by default makes missing features.  

The default sklearn seems to be a better choice when using `compare_models` even if longer to train. The future feature enabling setting hyper-parameters from `compare_models` will resolve that.

But in general, when people let PyCaret does the job for a first quick and dirty training, if the engine modifies the default hyperparams I think, in a AutoML perspective, it should take into account the number of features for some models to make sur that feature sampling will not miss some of them.

**Comment by pycaret** [comment]
@danbricedatascience Thanks for bringing this up. 

In the next release, we will adapt to the default values of `sklearn` i.e. 100.

@Yard1 FYI. I think you have already fixed this. Somebody opened an issue of not being able to pass `n_estimators` in `RandomForestClassifier`. This issue is linked to that one.

**Comment by Yard1** [comment]
Yep, both things have been fixed.

**Comment by pycaret** [comment]
@danbricedatascience 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
