### ISSUE TITLE
WOE Encoder

### ISSUE THREAD

**Issue by reza1615** [pycaret/pycaret#65]
would you please add WOE as a Encoder alternative? 
[Source](https://medium.com/@sundarstyles89/weight-of-evidence-and-information-value-using-python-6f05072e83eb)
[Library for WOE](http://contrib.scikit-learn.org/category_encoders/)

**Comment by pycaret** [comment]
Future enhancement.

**Comment by reza1615** [comment]
@pycaret You removed the history https://github.com/pycaret/pycaret/graphs/contributors
I don't contribute here
