### ISSUE TITLE
Error from tune_model

### ISSUE THREAD

**Issue by zhaoli-IHEP** [pycaret/pycaret#655]
We are trying to use `tune_model` for `dt` as 
```
tuned_dt = tune_model(dt, verbose=False)
```
However, it produced an error.
```
Traceback (most recent call last):
  File "fit_nn.py", line 122, in <module>
    tuned_dt = tune_model(dt, verbose=False)
  File "/home/zhaoliML/anaconda3/lib/python3.8/site-packages/pycaret/regression.py", line 4309, in tune_model
    param_grid = {"max_depth": np.random.randint(1, (len(X_train.columns)*.85),20),
  File "mtrand.pyx", line 743, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1260, in numpy.random._bounded_integers._rand_int64
ValueError: low >= high
```
What could be the possible root of the error?
Thank you.

**Comment by pycaret** [comment]
@zhaoli-IHEP Can you attach the Notebook with a sample dataset so that we can reproduce the error and investigate further?

**Comment by zhaoli-IHEP** [comment]
> @zhaoli-IHEP Can you attach the Notebook with a sample dataset so that we can reproduce the error and investigate further?

I have upload the sample code and data in the following place.

https://github.com/zhaoli-IHEP/play_pycaret

**Comment by pycaret** [comment]
@zhaoli-IHEP Can you please update the version to `pycaret==2.2` and try again? Please let us know if the issue persists.
