### ISSUE TITLE
Is there a way to improve on pyCaret Predictions?

### ISSUE THREAD

**Issue by webzest** [pycaret/pycaret#656]
Hi,

No matter how I setup and ran pyCaret, the best predicton is always around 0.14... on Kaggle, which is a very poor prediction, but it is a good start on the housing competition.  Nevertheless, I can't seem to find a way to enhance the score.  

I tried tuning, stacking, and blending five top models, etc.  The score remains around 0.14.  As an example, this is my finalyze blender that generated a kaggle prediction of 0.14296 :

```
```
VotingRegressor(estimators=[
                             ('Bayesian Ridge_0',
                             BayesianRidge(alpha_1=0.15, alpha_2=0.3,
                                           alpha_init=None, compute_score=False,
                                           copy_X=True, fit_intercept=True,
                                           lambda_1=0.005, lambda_2=0.001,
                                           lambda_init=None, n_iter=300,
                                           normalize=False, tol=0.001,
                                           verbose=False)),
                            ('Ridge_1',
                             Ridge(alpha=0.997, copy_X=True, fit_intercept=False, max_iter=None,
                                   normalize=True, random_state=786, solver='auto', tol=0.001)),
                             ('LineraRegression_1',
                             LinearRegression(copy_X=True, fit_intercept=True, n_jobs=-1, normalize=True)),
                             ('Lars_1',
                             Lars(copy_X=True, eps=0.0005, fit_intercept=True,
                                  fit_path=True, jitter=None,
                                  n_nonzero_coefs=500, normalize=False,
                                  precompute='auto', random_state=None,
                                  verbose=False)),
                            ('Theil Sen Regressor_4',
                             TheilSenRegressor(copy_X=True, fit_intercept=True,
                                               max_iter=300,
                                               max_subpopulation=20000,
                                               n_jobs=-1, n_subsamples=None,
                                               random_state=786, tol=0.001,
                                               verbose=False))],
                n_jobs=-1, verbose=False, weights=None)
```

```

**Comment by pycaret** [comment]
@webzest This question is outside the scope of this repo. I can suggest feature engineering and anything to do with data processing but you must handle before passing the dataset to PyCaret.

Thanks.
