### ISSUE TITLE
Problems with vscode and azure notebooks

### ISSUE THREAD

**Issue by zepef** [pycaret/pycaret#657]
Hello,

I really enjoy using PyCaret. Binary Classification Tutorial (CLF101) - Level Beginner works fine with collab.
I run into problems with both vscode and Azure Notebooks. I tried to use PyCaret 2.1 and the nightly version.

**With vscode / anaconda / python 3 (6,7,8) I get**:

  File "c:\Users\zepef\source\repos\fnm-pyc-prospect-train\fnm-pyc-prospect-train.py", line 14, in <module>
    compare_models()
  File "D:\Users\zepef\anaconda3\envs\fnm-pyc-prospect-train\lib\site-packages\pycaret\classification.py", line 2062, in compare_models
    display_id = display_.display_id
AttributeError: 'NoneType' object has no attribute 'display_id'

**and with Azure notebooks I get:**

AttributeError                            Traceback (most recent call last)
<ipython-input-4-9f0ce91bf86c> in <module>
     14 
     15 exp_clf101 = setup(data = data, target = 'default', session_id=123)
---> 16 compare_models()
     17 dt = create_model('dt')
     18 print(dt)
/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pycaret/classification.py in compare_models(exclude, include, fold, round, sort, n_select, budget_time, turbo, verbose)
   2455                 time_start=time.time()
   2456                 logger.info("Fitting Model")
-> 2457                 model.fit(Xtrain,ytrain)
   2458                 logger.info("Evaluating Metrics")
   2459                 time_end=time.time()
/anaconda/envs/azureml_py36/lib/python3.6/site-packages/catboost/core.py in fit(self, X, y, cat_features, text_features, embedding_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   4290         self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
   4291                   eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period,
-> 4292                   silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   4293         return self
   4294 
/anaconda/envs/azureml_py36/lib/python3.6/site-packages/catboost/core.py in _fit(self, X, y, cat_features, text_features, embedding_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   1791             use_best_model, eval_set, verbose, logging_level, plot,
   1792             column_description, verbose_eval, metric_period, silent, early_stopping_rounds,
-> 1793             save_snapshot, snapshot_file, snapshot_interval, init_model
   1794         )
   1795         params = train_params["params"]
/anaconda/envs/azureml_py36/lib/python3.6/site-packages/catboost/core.py in _prepare_train_params(self, X, y, cat_features, text_features, embedding_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   1678         train_pool = _build_train_pool(X, y, cat_features, text_features, embedding_features, pairs,
   1679                                        sample_weight, group_id, group_weight, subgroup_id, pairs_weight,
-> 1680                                        baseline, column_description)
   1681         if train_pool.is_empty_:
   1682             raise CatBoostError("X is empty.")
/anaconda/envs/azureml_py36/lib/python3.6/site-packages/catboost/core.py in _build_train_pool(X, y, cat_features, text_features, embedding_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, column_description)
    983             raise CatBoostError("y has not initialized in fit(): X is not catboost.Pool object, y must be not None in fit().")
    984         train_pool = Pool(X, y, cat_features=cat_features, text_features=text_features, embedding_features=embedding_features, pairs=pairs, weight=sample_weight, group_id=group_id,
--> 985                           group_weight=group_weight, subgroup_id=subgroup_id, pairs_weight=pairs_weight, baseline=baseline)
    986     return train_pool
    987 
/anaconda/envs/azureml_py36/lib/python3.6/site-packages/catboost/core.py in __init__(self, data, label, cat_features, text_features, embedding_features, column_description, pairs, delimiter, has_header, ignore_csv_quoting, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    453                     )
    454 
--> 455                 self._init(data, label, cat_features, text_features, embedding_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    456         super(Pool, self).__init__()
    457 
/anaconda/envs/azureml_py36/lib/python3.6/site-packages/catboost/core.py in _init(self, data, label, cat_features, text_features, embedding_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    964             baseline = np.reshape(baseline, (samples_count, -1))
    965             self._check_baseline_shape(baseline, samples_count)
--> 966         self._init_pool(data, label, cat_features, text_features, embedding_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    967 
    968 
_catboost.pyx in _catboost._PoolBase._init_pool()
_catboost.pyx in _catboost._PoolBase._init_pool()
_catboost.pyx in _catboost._PoolBase._init_features_order_layout_pool()
_catboost.pyx in _catboost._set_features_order_data_pd_data_frame()
AttributeError: module 'pandas' has no attribute 'SparseDtype'

I will still try to find a solution and I'll keep You updated.

Thank You,

Pierre-Emmanuel

**Comment by pycaret** [comment]
@zepef When working outside of the Notebook environment you have to pass `silent = True` parameter in the `setup` function.

**Comment by zepef** [comment]
Hello PyCaret,

I passed an html=False in setup.py but it does not work neither in vscode nor from command-line python

Best regards,

Pierre-Emmanuel
