### ISSUE TITLE
Issue with binary inputs

### ISSUE THREAD

**Issue by Rahul9597** [pycaret/pycaret#658]
**Is your feature request related to a problem? Please describe.**
When you have data with both numeric and binary inputs, the library considers binary as categorical and compare models throws this error - 
FloatingPointError                        Traceback (most recent call last)
<ipython-input-31-9ff5ccfe3077> in <module>
----> 1 compare_models()

~\AppData\Roaming\Python\Python37\site-packages\pycaret\classification.py in compare_models(blacklist, fold, round, sort, turbo)
   3435 
   3436                 model.fit(Xtrain,ytrain)
-> 3437                 pred_prob = model.predict_proba(Xtest)
   3438                 pred_prob = pred_prob[:,1]
   3439                 pred_ = model.predict(Xtest)

~\Anaconda3\lib\site-packages\sklearn\naive_bayes.py in predict_proba(self, X)
    113         C : array-like of shape (n_samples, n_classes)
    114             Returns the probability of the samples for each class in
--> 115             the model. The columns correspond to the classes in sorted
    116             order, as they appear in the attribute :term:`classes_`.
    117         """

~\Anaconda3\lib\site-packages\sklearn\naive_bayes.py in predict_log_proba(self, X)
     95         """
     96         check_is_fitted(self)
---> 97         X = self._check_X(X)
     98         jll = self._joint_log_likelihood(X)
     99         # normalize by P(x) = P(f_1, ..., f_n)

~\Anaconda3\lib\site-packages\scipy\special\_logsumexp.py in logsumexp(a, axis, b, keepdims, return_sign)
    110         tmp = b * np.exp(a - a_max)
    111     else:
--> 112         tmp = np.exp(a - a_max)
    113 
    114     # suppress warnings about log of zero

FloatingPointError: underflow encountered in exp

**Describe the solution you'd like**
I wish there was a way we could standardize only selective columns, so that the binary inputs do not get standardized as well

I tried converting binary to numeric and everything works fine but my binary inputs also get standardized in the process.

**Comment by pycaret** [comment]
@Rahul9597 Can you please attach the Notebook and sample dataset that we can use to reproduce this error. Thanks.

**Comment by pycaret** [comment]
@Rahul9597 Were you able to resolve the issue? If yes, can you please share your findings?

**Comment by Rahul9597** [comment]
No I wasn't.

**Comment by pycaret** [comment]
@Rahul9597 You can overwrite the automated datatype inference done by PyCaret by passing the `numeric_features` and `categorical_features` parameters in the `setup` function.

Hope this helps. If this solves your issue, please close this issue.
