### ISSUE TITLE
Confidence interval for performance metrics

### ISSUE THREAD

**Issue by npapan69** [pycaret/pycaret#66]
Is there any way to compute 95%CI for all performance metrics (especially the hold-out test set) since a single value doesn't really help that much to evaluate models robustness. Many thanks for the great work you have done and keep on doing.

**Comment by pycaret** [comment]
Thanks for suggestion.

Marking as future enhancement.

**Comment by pycaret** [comment]
# Open for contribution now

**Comment by pycaret** [comment]
@npapan69 Would you like to work on this issue or at least provide a detailed user story so that its easy to understand the requirement and expected results. Feel free to upload example notebooks and calculations required to calculate CI.

**Comment by kmedved** [comment]
This is an incredibly difficult problem fwiw, and an area of active research. I'll flag two libraries with active development on this issue, which are [ngboost ](https://stanfordmlgroup.github.io/projects/ngboost/)(from Andrew Ng's team), and Catboost's recently released [RMSEWithUncertainty](https://github.com/catboost/catboost/releases) loss function, but analyzing CIs more robustly may require true Bayesian approaches, e.g., Stay, PyMC3, Pyro, etc...

**Comment by pycaret** [comment]
@kmedved I have no experience with this. I will leave it open and see if we can get any contributor to this.
