### ISSUE TITLE
permission error when ran blend_models

### ISSUE THREAD

**Issue by E-B-Manohar** [pycaret/pycaret#662]
blend_hard = blend_models()

[permission error.docx](https://github.com/pycaret/pycaret/files/5261438/permission.error.docx)

issue only with blend models so far

**Comment by pycaret** [comment]
@E-B-Manohar Seems like an issue with parallel processing. Can you try passing `n_jobs` in the `setup` function as `None`. By default, it's set to `-1`. Let me know how it goes.

**Comment by E-B-Manohar** [comment]
Yeah worked.
and this disables te parallel  processing ability right  :(
Please look into on avoiding this ... blender is nice function

**Comment by E-B-Manohar** [comment]
I guess, I want your response to go further and close this issue?
