### ISSUE TITLE
How to silent these input fields?

### ISSUE THREAD

**Issue by E-B-Manohar** [pycaret/pycaret#663]
![Please Enter the sample % of data you would](https://user-images.githubusercontent.com/45871357/93901159-d94b0600-fd13-11ea-915e-8d8a0381b978.PNG)
![data types have been inferred automatically](https://user-images.githubusercontent.com/45871357/93901286-ff70a600-fd13-11ea-9f6e-12b63e3bcc89.PNG)

**Comment by Yard1** [comment]
Don't use sampling.

**Comment by E-B-Manohar** [comment]
> Don't use sampling.

Okay, how to avoid the 2nd field?

**Comment by Yard1** [comment]
`silent=True`

**Comment by E-B-Manohar** [comment]
> silent=True

Dang it... My question has answer in it... Thanks Budd
