### ISSUE TITLE
Feature selection options.

### ISSUE THREAD

**Issue by gm039** [pycaret/pycaret#665]
Hi,

May I know what are the statistical tests available for feature selection?
Can we perform feature selection using 'Wilcoxon','ttest','mrmr'?

Thank you

**Comment by pycaret** [comment]
@gm039 There are currently two methods available for feature selection. `classic` method uses a combination of `lightgbm` and `randomForest` feature importance and the `boruta` method uses the `boruta` algorithm for features selection.

Read more about it: https://pycaret.readthedocs.io/en/latest/
