### ISSUE TITLE
Throwed Key Error when loaded a model ("et") 

### ISSUE THREAD

**Issue by E-B-Manohar** [pycaret/pycaret#666]
plot_model(fd_best_loaded, 'auc')

>> [Key Error.docx](https://github.com/pycaret/pycaret/files/5276474/Key.Error.docx)

Here, "Class" is target variable name.

**Comment by pycaret** [comment]
@E-B-Manohar Can you share the dataset and notebook please?

**Comment by E-B-Manohar** [comment]
The dataset: https://www.kaggle.com/mlg-ulb/creditcardfraud/download

model is "et"
then saved it
---------
performed **plot_model** on the **loaded model**
plot_model(fd_best_loaded, 'auc')
