### ISSUE TITLE
How to use pycaret in terminal without jupyter notebook or Ipython kernel ?

### ISSUE THREAD

**Issue by actcod01** [pycaret/pycaret#667]
1. Looking for a simple way to **train model in command line/terminal** 

2. It should **always consider the best model while model_save.**

**Comment by pycaret** [comment]
@actcod01 You can use pycaret just like any other python script. The only thing you have to take care of is the `silent` parameter in the `setup` that must be set to `True` and `html` should be set to `False`.

**Comment by actcod01** [comment]
**✔️  AIM : To run pycaret this snippet as the py script.**  
___
I didn't found the required solution params so ,

## Can you **Update this Code-Snippet** ? 

**Note :** 
I'm getting issues while importing `from pycaret.classification import * ` and snippet is not running as py script.
.

____


```
from pycaret.datasets import get_data
import json

# from pycaret.classification import *   # 

from pycaret.classification import setup,compare_models

dataset = get_data('credit')
    
data = dataset.sample(frac=0.95, random_state=786)
data_unseen = dataset.drop(data.index)

data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)


exp_clf101 = setup(data = data, target = 'default')

best_model = compare_models()

```

Thanks ,
