### ISSUE TITLE
While interpreting the model, Took almost 5+ min time for "Name Error"

### ISSUE THREAD

**Issue by E-B-Manohar** [pycaret/pycaret#668]
![interpret_model_ delay](https://user-images.githubusercontent.com/45871357/94163344-5a85d280-fea5-11ea-8ce1-f2611c084c6b.PNG)

I'm not sure why?  Can someone explain this delay could have occured?

**Comment by pycaret** [comment]
@E-B-Manohar Just by looking at the error I can tell `best` is not defined.

**Comment by E-B-Manohar** [comment]
> @E-B-Manohar Just by looking at the error I can tell `best` is not defined.

I knew that and I am wondering about the execution **time** it took to identify that "best" is not defined?
