### ISSUE TITLE
how to optimize with custom_scorer?

### ISSUE THREAD

**Issue by zhaoli-IHEP** [pycaret/pycaret#672]
In the result of tune_model function, how to show the result of custom_scorer, and how to use custom_scroer for the option optimize? Thank you.

**Comment by pycaret** [comment]
@zhaoli-IHEP Adding custom metrics will be available in the next release.

**Comment by pycaret** [comment]
@zhaoli-IHEP 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
