### ISSUE TITLE
Databricks setup support

### ISSUE THREAD

**Issue by claywey** [pycaret/pycaret#675]
Databricks does not support ipywidgets when running notebooks from the UI. Cannot finish setup because the widget for data type confirmation will not display as a widget. Example output below:

Text(value="Following data types have been inferred automatically, if they are correct press enter to continue or type 'quit' otherwise.", layout=Layout(width='100%'))

This also happens with HTML=False

**Comment by pycaret** [comment]
@claywey You have to also pass `silent = True` along with `html = False` in the `setup` function. When you pass `silent` as `True`, it will not ask for confirmation of data types and would instead use whatever is inferred by default. To programmatically define the data types you can use `numeric_features` and `categorical_features` parameter in the `setup` function.

Hope this helps.
