### ISSUE TITLE
Out of ram on colab during setup

### ISSUE THREAD

**Issue by Evange95** [pycaret/pycaret#679]
I'm still facing this problem during setup with a dataset of shape (261942, 93). After confirming datatypes the colab session suddenly crashes because OOM

**Comment by Evange95** [comment]
> Similar issue, ran out of RAM in colab.  dataset was ~40k rows, but guessing the 2 columns with nearly 1400 distinct values caused it to crash.

Yeah I can confirm that I solved it dropping the categorical columns with too many categories

**Comment by Yard1** [comment]
Is it possible for you to share the datasets?

**Comment by Lion-Mod** [comment]
Morning, I cannot given the confidentiality of it. But based upon Evange95's point it should work.

I didn't declare the columns as high cardinality features so will try that.

**Comment by pycaret** [comment]
@Lion-Mod Also we are making some major improvements on the memory footprint in the next release. It should definitely solve this problem. Keep an eye on the repo.

@Yard1 - FYI

**Comment by pycaret** [comment]
@Lion-Mod Can you please update pycaret to 2.2 `pip install --upgrade pycaret` and try again?

**Comment by Lion-Mod** [comment]
Tried and seems like it works. Takes a while to run but produces a result! Thank you.
