### ISSUE TITLE
fix_imbalance and SMOTE

### ISSUE THREAD

**Issue by phuggins** [pycaret/pycaret#680]
I'm trying to find the SMOTE training data that is being created when fix_imbalance = True. I've set it to True and then run get_config to pull out the X/Y/train/test data but it does not appear that SMOTE is being used on the training sets that are pulled from get_config. 

Is the balanced training set stored somewhere else?

![image](https://user-images.githubusercontent.com/59326297/94460797-e0906a80-017e-11eb-8aaa-4aa0cb622700.png)

**Comment by claywey** [comment]
No. SMOTE should be added as a step to the pipeline. If you are doing any sort of cross-validation, you will want the sampling to occur WITHIN training folds. If you apply a sampling technique, like SMOTE, as a preprocessing step first, you will leak data into the test folds and overfit.

**Comment by phuggins** [comment]
Awesome, thank you for the information!
________________________________

**Comment by pycaret** [comment]
@phuggins Yes. For SMOTE in order to avoid leakage, we are over-sampling within the folds as oppose to outside of the fold and hence you cannot access the over-sampled dataset.
