### ISSUE TITLE
deep learning

### ISSUE THREAD

**Issue by Aurora11111** [pycaret/pycaret#681]
can this be used in deeplearning?

**Comment by kunalgupta2616** [comment]
No @Aurora11111 .For now, the Pycaret platform only supports Machine Learning, Hopefully, in future, we'll get to see it automate Deep Learning tasks.

> can this be used in deeplearning?

**Comment by pycaret** [comment]
@Aurora11111 At this point its not on the road map. Keep an eye on the repo for more updates in the future.
