### ISSUE TITLE
Is pycaret going to be commercial one?

### ISSUE THREAD

**Issue by sathishkumar369** [pycaret/pycaret#683]
Hi pycaret team and Moez!

we are planning to create machine learning web applications and we wanted to use pycaret for our backend instead of sklearn and some other pacakges. our senior management had asked a question to us, what if pycaret is going to be paid one, then again all your code needs to be restructured with open source packages. 
so I told them it will be open source for data science community. can you guys please confirm me on this (@Moez and team).

**Comment by pycaret** [comment]
@sathishkumar369 PyCaret is an open-source library and will remain so.
