### ISSUE TITLE
Use Hummingbird for sklearn acceleration using GPU

### ISSUE THREAD

**Issue by BraINstinct0** [pycaret/pycaret#694]
**Is your feature request related to a problem? Please describe.**
Though several sklearn models support multicore CPU for speedups, they mostly still don't support the use of GPU.

**Describe the solution you'd like**
By incorporating/using MS's [Hummingbird](https://github.com/microsoft/hummingbird), this can be achieved(though currently not in stable release).

**Comment by pycaret** [comment]
@BraINstinct0 

We have included gpu support using RAPID's AI and it will be generally available in the next release. Keep an eye on the repo.

@Yard1 - FYI.

Thanks,

**Comment by varshithvvs** [comment]
@pycaret, a quick question does pycaret support hummingbird from PyCaret 2.3 ??

Context:
I'm working on creating data pipelines using machine learning. However, I felt it would be helpful if I can leverage the low code functionality along with GPU acceleration.

I have tried installing RAPIDS for GPU support, but RAPIDS doesn't support PIP install. I'm new to conda environment and have faced difficulty setting up the requirements within my jupyter server.

It would be great if I can convert the final models into tensorflow models. I still am exploring about tensorflow support by hummingbird

PS: I'm a newbie here, pls let me know if my question makes sense at the first place or If I'm missing anything.
