### ISSUE TITLE
Error comes when I run the regression model

### ISSUE THREAD

**Issue by whiran** [pycaret/pycaret#696]
Following error is being generated when I run regression model 
`top_model = compare_models(exclude  = ['ransac', 'tr'],sort = 'R2',n_select = 3,turbo = False  )` 

**Latter part of the Error**
`~\anaconda3\envs\py36\lib\site-packages\pandas\core\internals\construction.py in extract_index(data)
    353 
    354         if not indexes and not raw_lengths:
--> 355             raise ValueError("If using all scalar values, you must pass an index")
    356 
    357         if have_series:
`

**`ValueError: If using all scalar values, you must pass an index`**

**Comment by pycaret** [comment]
@whiran Can you please share the notebook and sample dataset here so we can reproduce the error?

**Comment by ngupta23** [comment]
Hi @whiran, Since this issue has been open for a while, could you let us know if the reproducible example can be shared. It will help with debugging. Thanks!
