### ISSUE TITLE
Setup function on Databricks do not give an option to accept the data types

### ISSUE THREAD

**Issue by NitinMahajan1** [pycaret/pycaret#697]
Hello!
I'm having issues when running setup function on data-bricks notebook.
The function rightly gives all dater types but it does not give any option to accept or quit. So, the command gets struck, while waiting for an input which I am unable to provide.

**Comment by NitinMahajan1** [comment]
I did try silent=true and it helps but then I’m not able to modify data types

**Comment by pycaret** [comment]
@NitinMahajan1 You can programmatically define data types by using `numeric_features`, `categorical_features`, and `date_features` parameter in the `setup` function.

Read more: https://pycaret.org/data-types/

Hope this helps.
