### ISSUE TITLE
Custom Tuning Grid

### ISSUE THREAD

**Issue by Riazone** [pycaret/pycaret#7]
Hi,

The current **_tune_model()_** I understand uses randomized grid search for tuning a model. However, how can I provide my own tuning grid for selected hyper-parameters. I don't think PyCaret currently offers this flexibility. If we can have this feature, it will be very instrumental.

Thanks

**Comment by pycaret** [comment]
### Feature now available in pycaret-nightly.

You can install **pycaret-nightly** using "pip install pycaret-nightly". 

It will be shipped to PyCaret 2.0x in few weeks.
