### ISSUE TITLE
DL impeded fucntions

### ISSUE THREAD

**Issue by atwahsz** [pycaret/pycaret#700]
hello , is it possible to wrap around skorch ? they have a framework similar to sklearn but for deep learning

all of the best

saleh ,

**Comment by pycaret** [comment]
@atwahsz As long as it follows sklearn API, you should be able to pass it under `create_model`. It would be a good test to see. Would you like to try?

**Comment by atwahsz** [comment]
yes of course !

**Comment by joaopalotti** [comment]
Hi @atwahsz, jumping into this stuck conversation, could you use skorch with pycaret?

I tried it today and could not make it work.
Made this smaller example below using standard skorch and pycaret:

```python
import numpy as np
from torch import nn
from pycaret.datasets import get_data
from pycaret.classification import *
from skorch import NeuralNetClassifier


class MyNet(nn.Module):
    def __init__(self, num_units=10, nonlin=nn.ReLU()):
        super(MyNet, self).__init__()

        self.dense0 = nn.Linear(24, num_units)
        self.nonlin = nonlin
        self.dropout = nn.Dropout(0.5)
        self.dense1 = nn.Linear(num_units, num_units)
        self.output = nn.Linear(num_units, 2)
        self.softmax = nn.Softmax(dim=-1)

    def forward(self, x, **kwargs):
        X = self.nonlin(self.dense0(x))
        X = self.dropout(X)
        X = self.nonlin(self.dense1(X))
        X = self.softmax(self.output(X))
        return X


net = NeuralNetClassifier(
    MyNet,
    max_epochs=10,
    lr=0.1,
)

data = get_data('diabetes')
clf1 = setup(data, target = 'Class variable')
create_model(net)

```

But got this error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-402abfe81ae2> in <module>
     37 data = get_data('diabetes')
     38 clf1 = setup(data, target = 'Class variable')
---> 39 create_model(net)

~/.conda/envs/cp38/lib/python3.8/site-packages/pycaret/classification.py in create_model(estimator, fold, round, cross_validation, fit_kwargs, groups, verbose, **kwargs)
    887     """
    888 
--> 889     return pycaret.internal.tabular.create_model_supervised(
    890         estimator=estimator,
    891         fold=fold,

~/.conda/envs/cp38/lib/python3.8/site-packages/pycaret/internal/tabular.py in create_model_supervised(estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, verbose, system, X_train_data, y_train_data, metrics, display, **kwargs)
   3128             logger.info("Finalizing model")
   3129             with io.capture_output():
-> 3130                 pipeline_with_model.fit(data_X, data_y, **fit_kwargs)
   3131             model_fit_end = time.time()
   3132 

~/.conda/envs/cp38/lib/python3.8/site-packages/pycaret/internal/pipeline.py in fit(self, X, y, **fit_kwargs)
    116 
    117     def fit(self, X, y=None, **fit_kwargs):
--> 118         result = super().fit(X, y=y, **fit_kwargs)
    119 
    120         self._carry_over_final_estimator_fit_vars()

~/.conda/envs/cp38/lib/python3.8/site-packages/imblearn/pipeline.py in fit(self, X, y, **fit_params)
    279                                  self._log_message(len(self.steps) - 1)):
    280             if self._final_estimator != "passthrough":
--> 281                 self._final_estimator.fit(Xt, yt, **fit_params)
    282         return self
    283 

~/.conda/envs/cp38/lib/python3.8/site-packages/skorch/classifier.py in fit(self, X, y, **fit_params)
    140         # this is actually a pylint bug:
    141         # https://github.com/PyCQA/pylint/issues/1085
--> 142         return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
    143 
    144     def predict_proba(self, X):

~/.conda/envs/cp38/lib/python3.8/site-packages/skorch/net.py in fit(self, X, y, **fit_params)
    901             self.initialize()
    902 
--> 903         self.partial_fit(X, y, **fit_params)
    904         return self
    905 

~/.conda/envs/cp38/lib/python3.8/site-packages/skorch/net.py in partial_fit(self, X, y, classes, **fit_params)
    860         self.notify('on_train_begin', X=X, y=y)
    861         try:
--> 862             self.fit_loop(X, y, **fit_params)
    863         except KeyboardInterrupt:
    864             pass

~/.conda/envs/cp38/lib/python3.8/site-packages/skorch/net.py in fit_loop(self, X, y, epochs, **fit_params)
    773             self.notify('on_epoch_begin', **on_epoch_kwargs)
    774 
--> 775             self.run_single_epoch(dataset_train, training=True, prefix="train",
    776                                   step_fn=self.train_step, **fit_params)
    777 

~/.conda/envs/cp38/lib/python3.8/site-packages/skorch/net.py in run_single_epoch(self, dataset, training, prefix, step_fn, **fit_params)
    810             yi_res = yi if not is_placeholder_y else None
    811             self.notify("on_batch_begin", X=Xi, y=yi_res, training=training)
--> 812             step = step_fn(Xi, yi, **fit_params)
    813             self.history.record_batch(prefix + "_loss", step["loss"].item())
    814             self.history.record_batch(prefix + "_batch_size", get_len(Xi))

~/.conda/envs/cp38/lib/python3.8/site-packages/skorch/net.py in train_step(self, Xi, yi, **fit_params)
    707             return step['loss']
    708 
--> 709         self.optimizer_.step(step_fn)
    710         return step_accumulator.get_step()
    711 

~/.conda/envs/cp38/lib/python3.8/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     24         def decorate_context(*args, **kwargs):
     25             with self.__class__():
---> 26                 return func(*args, **kwargs)
     27         return cast(F, decorate_context)
     28 

~/.conda/envs/cp38/lib/python3.8/site-packages/torch/optim/sgd.py in step(self, closure)
     84         if closure is not None:
     85             with torch.enable_grad():
---> 86                 loss = closure()
     87 
     88         for group in self.param_groups:

~/.conda/envs/cp38/lib/python3.8/site-packages/skorch/net.py in step_fn()
    703         def step_fn():
    704             self.optimizer_.zero_grad()
--> 705             step = self.train_step_single(Xi, yi, **fit_params)
    706             step_accumulator.store_step(step)
    707             return step['loss']

~/.conda/envs/cp38/lib/python3.8/site-packages/skorch/net.py in train_step_single(self, Xi, yi, **fit_params)
    643         """
    644         self.module_.train()
--> 645         y_pred = self.infer(Xi, **fit_params)
    646         loss = self.get_loss(y_pred, yi, X=Xi, training=True)
    647         loss.backward()

~/.conda/envs/cp38/lib/python3.8/site-packages/skorch/net.py in infer(self, x, **fit_params)
   1045         if isinstance(x, dict):
   1046             x_dict = self._merge_x_and_fit_params(x, fit_params)
-> 1047             return self.module_(**x_dict)
   1048         return self.module_(x, **fit_params)
   1049 

~/.conda/envs/cp38/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

TypeError: forward() missing 1 required positional argument: 'x'
```

I used 24d in the input layer as this is what I see for the ``Transformed Train Set | (537, 24)``.
To be able to use this network with skorch only, the input layer has to be changed to 8d, and the following type casts are done:

```python
y = data["Class variable"].values.astype(np.int64)
X = data.drop(columns="Class variable").values.astype(np.float32)

net.fit(X, y)
```

The way I currently see it is that, even if someone finds the reason why forward is complaining, the type cast would still need to be done somewhere.
But, first thing first, any clue what could be wrong with the forward?

**Comment by atwahsz** [comment]
To be honest , it did not work theb I decided for the time being to use
pycaret to setup then extract X and Y and use skorch directly

**Comment by atwahsz** [comment]
gents , can we investigate 

https://github.com/google/model_search

possibly fork it for another set of compare_models()

**Comment by IncubatorShokuhou** [comment]
@joaopalotti Did you successfully use skorch with pycaret now? I am also trying to work on it, but met a same error exactly as yours.

**Comment by IncubatorShokuhou** [comment]
Well, I think I have figure out how to use skorch in PyCaret: all we need is use a pipeline instead of a native model:
Here is an example:
```python
from pycaret.classification import *
from pycaret.datasets import get_data
from sklearn.pipeline import Pipeline
from skorch import NeuralNetClassifier
from skorch.helper import DataFrameTransformer
from torch import nn

juice = get_data("juice")


class MyModule(nn.Module):
    def __init__(self, num_units=10, nonlin=nn.ReLU()):
        super(MyModule, self).__init__()
        self.dense0 = nn.Linear(17, num_units)
        self.nonlin = nonlin
        self.dropout = nn.Dropout(0.5)
        self.dense1 = nn.Linear(num_units, num_units)
        self.output = nn.Linear(num_units, 2)
        self.softmax = nn.Softmax(dim=-1)

    def forward(self, X, **kwargs):
        X = self.nonlin(self.dense0(X))
        X = self.dropout(X)
        X = self.nonlin(self.dense1(X))
        X = self.softmax(self.output(X))
        return X

# create NN classifier
net = NeuralNetClassifier(
    MyModule,
    max_epochs=10,
    lr=0.1,
    iterator_train__shuffle=True,
)

# create a pipeline to handle dataframe for input
# sklearn pipeline also support sklearn api (fit,predict et al)
# so it can work with PyCaret
pipe = Pipeline(
    [
        ("transform", DataFrameTransformer()),
        ("net", net),
    ]
)

exp_name = setup(data=juice, target="Purchase", silent=True)
sknet = create_model(pipe)

```

**Comment by atwahsz** [comment]
@IncubatorShokuhou  nice work , 

now i tried replicating this for another dataset

i get this error
IndexError: Target 5 is out of bounds.

**Comment by IncubatorShokuhou** [comment]
> @IncubatorShokuhou nice work ,
> 
> now i tried replicating this for another dataset
> 
> i get this error
> IndexError: Target 5 is out of bounds.

Maybe you can list your dataset and your script so that I can help reprocuce & solve the error.

**Comment by atwahsz** [comment]
import pandas as pd
import numpy as np
train = pd.read_csv('https://raw.githubusercontent.com/pkhetland/Facies-prediction-TIP160/master/datasets/facies_vectors.csv')
train=train.rename(columns={'Well Name':'WELL','Facies':'FACIES','Formation':'TOP','Depth':'DEPTH'})

from pycaret.classification import *
from sklearn.pipeline import Pipeline
from skorch import NeuralNetClassifier
from skorch.helper import DataFrameTransformer
from torch import nn

# get data


# setup

exp_name = setup (train,target='FACIES',ignore_features=['WELL','DEPTH'],categorical_features=['TOP'],use_gpu=True,silent=True)


# get the input size of the model
X_train = get_config("X_train")
input_size = X_train.shape[-1]

# create NN model
class MyModule(nn.Module):
    def __init__(self, num_units=10, nonlin=nn.ReLU()):
        super(MyModule, self).__init__()
        self.dense0 = nn.Linear(input_size , num_units)  # here determine the input size
        self.nonlin = nonlin
        self.dropout = nn.Dropout(0.5)
        self.dense1 = nn.Linear(num_units, num_units)
        self.output = nn.Linear(num_units, 2)
        self.softmax = nn.Softmax(dim=-1)

    def forward(self, X, **kwargs):
        X = self.nonlin(self.dense0(X))
        X = self.dropout(X)
        X = self.nonlin(self.dense1(X))
        X = self.softmax(self.output(X))
        return X

# create NN classifier
net = NeuralNetClassifier(
    MyModule,
    max_epochs=10,
    lr=0.1,
    iterator_train__shuffle=True,
)

# create a pipeline to handle dataframe for input
# sklearn pipeline also support sklearn api (fit,predict et al)
# so it can work with PyCaret
pipe = Pipeline(
    [
        ("transform", DataFrameTransformer()),
        ("net", net),
    ]
)

# create model
sknet = create_model(pipe)

# the created `sknet` can also be compared
best_model = compare_models(include=[sknet,"lr"])

**Comment by atwahsz** [comment]
`import pandas as pd
import numpy as np
train = pd.read_csv('https://raw.githubusercontent.com/pkhetland/Facies-prediction-TIP160/master/datasets/facies_vectors.csv')
train=train.rename(columns={'Well Name':'WELL','Facies':'FACIES','Formation':'TOP','Depth':'DEPTH'})

from pycaret.classification import *
from sklearn.pipeline import Pipeline
from skorch import NeuralNetClassifier
from skorch.helper import DataFrameTransformer
from torch import nn

# get data


# setup

exp_name = setup (train,target='FACIES',ignore_features=['WELL','DEPTH'],categorical_features=['TOP'],use_gpu=True,silent=True)


# get the input size of the model
X_train = get_config("X_train")
input_size = X_train.shape[-1]

# create NN model
class MyModule(nn.Module):
    def __init__(self, num_units=10, nonlin=nn.ReLU()):
        super(MyModule, self).__init__()
        self.dense0 = nn.Linear(input_size , num_units)  # here determine the input size
        self.nonlin = nonlin
        self.dropout = nn.Dropout(0.5)
        self.dense1 = nn.Linear(num_units, num_units)
        self.output = nn.Linear(num_units, 2)
        self.softmax = nn.Softmax(dim=-1)

    def forward(self, X, **kwargs):
        X = self.nonlin(self.dense0(X))
        X = self.dropout(X)
        X = self.nonlin(self.dense1(X))
        X = self.softmax(self.output(X))
        return X

# create NN classifier
net = NeuralNetClassifier(
    MyModule,
    max_epochs=10,
    lr=0.1,
    iterator_train__shuffle=True,
)

# create a pipeline to handle dataframe for input
# sklearn pipeline also support sklearn api (fit,predict et al)
# so it can work with PyCaret
pipe = Pipeline(
    [
        ("transform", DataFrameTransformer()),
        ("net", net),
    ]
)

# create model
sknet = create_model(pipe)

# the created `sknet` can also be compared
best_model = compare_models(include=[sknet,"lr"])`

**Comment by atwahsz** [comment]
```
import pandas as pd
import numpy as np
train = pd.read_csv('https://raw.githubusercontent.com/pkhetland/Facies-prediction-TIP160/master/datasets/facies_vectors.csv')
train=train.rename(columns={'Well Name':'WELL','Facies':'FACIES','Formation':'TOP','Depth':'DEPTH'})

from pycaret.classification import *
from sklearn.pipeline import Pipeline
from skorch import NeuralNetClassifier
from skorch.helper import DataFrameTransformer
from torch import nn

# get data


# setup

exp_name = setup (train,target='FACIES',ignore_features=['WELL','DEPTH'],categorical_features=['TOP'],use_gpu=True,silent=True)


# get the input size of the model
X_train = get_config("X_train")
input_size = X_train.shape[-1]

# create NN model
class MyModule(nn.Module):
    def __init__(self, num_units=10, nonlin=nn.ReLU()):
        super(MyModule, self).__init__()
        self.dense0 = nn.Linear(input_size , num_units)  # here determine the input size
        self.nonlin = nonlin
        self.dropout = nn.Dropout(0.5)
        self.dense1 = nn.Linear(num_units, num_units)
        self.output = nn.Linear(num_units, 2)
        self.softmax = nn.Softmax(dim=-1)

    def forward(self, X, **kwargs):
        X = self.nonlin(self.dense0(X))
        X = self.dropout(X)
        X = self.nonlin(self.dense1(X))
        X = self.softmax(self.output(X))
        return X

# create NN classifier
net = NeuralNetClassifier(
    MyModule,
    max_epochs=10,
    lr=0.1,
    iterator_train__shuffle=True,
)

# create a pipeline to handle dataframe for input
# sklearn pipeline also support sklearn api (fit,predict et al)
# so it can work with PyCaret
pipe = Pipeline(
    [
        ("transform", DataFrameTransformer()),
        ("net", net),
    ]
)

# create model
sknet = create_model(pipe)

# the created `sknet` can also be compared
best_model = compare_models(include=[sknet,"lr"])
```

**Comment by IncubatorShokuhou** [comment]
@atwahsz I think you are trying to run a regression model, but your NN model has a softmax layer at the end of froward....  Maybe you should customize your own model structure ending with ,for example, a FC layer.

**Comment by IncubatorShokuhou** [comment]
My fault.I misread the code.

**Comment by IncubatorShokuhou** [comment]
@atwahsz You have 9 kinds in your output, but dimenson of last layer in your model is 2. You should try `self.output = nn.Linear(num_units, 9)` .
