### ISSUE TITLE
problem of the example of Regression Tutorial (REG101) 

### ISSUE THREAD

**Issue by BettyWang07** [pycaret/pycaret#702]
data = dataset.sample(frac=0.9, random_state=786).reset_index(drop=True)
data_unseen = dataset.drop(data.index).reset_index(drop=True)

These code may bring data leakage.

**Comment by pycaret** [comment]
This issue was fixed some time ago. Can you confirm if you still see this on master branch?

**Comment by BettyWang07** [comment]
I can still see this on&nbsp;http://www.pycaret.org/tutorials/html/REG101.html.
I do not know the&nbsp;updated document has been changed.
Thanks for your reply.





王雨
华南理工大学 土木与交通学院
Tel:18813296316
Email: 2401344829@qq.com
地址：广州市天河区华南理工大学五山校区 510641




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pycaret/pycaret"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月7日(星期三) 上午9:04
收件人:&nbsp;"pycaret/pycaret"<pycaret@noreply.github.com&gt;;
抄送:&nbsp;"言叶"<2401344829@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pycaret/pycaret] problem of the example of Regression Tutorial (REG101)  (#702)





 
This issue was fixed some time ago. Can you confirm if you still see this on master branch?

**Comment by pycaret** [comment]
@BettyWang07 Sorry. I have now updated the link on the website. Here is the updated tutorial link:

https://github.com/pycaret/pycaret/blob/master/tutorials/Regression%20Tutorial%20Level%20Beginner%20-%20REG101.ipynb
