### ISSUE TITLE
plot_model confusion matrix and other visualisation options for CatBoost

### ISSUE THREAD

**Issue by deesumblip** [pycaret/pycaret#709]
I'm finding that a lot of visualisation options for multiclass classification with CatBoost are not available. I'd like to see classification accuracy broken down by each label within the my multiclass target. Was wondering if this feature will be added soon?

**Comment by Yard1** [comment]
Yes, they will be available in the next version.

**Comment by pycaret** [comment]
@deesumblip 

This issue has been fixed in the `pycaret-nightly` release. Please install pycaret-nightly using `pip install pycaret-nightly`. Feel free to open a new issue, in case the problem persists. This fix will be published to PyPi as `pycaret==2.2.0` on October 28, 2020.
