### ISSUE TITLE
Error message "SystemExit: (Value Error): Target parameter doesnt exist in the data provided."

### ISSUE THREAD

**Issue by roberthoyt** [pycaret/pycaret#710]
Here is the code I ran to do a classification to predict diabetes (yes = 1, no = 0)
data = pd.read_csv('/Users/roberthoyt/Desktop/NHANES 2011-2012/Merged files/Adults/Adults_Diabetes_NHANES_2011_2012.csv')
from pycaret.classification import *
exp_clf = setup(data, target = 'Diabetes')

I ran data.head to confirm that the last column was Diabetes. Why won't it accept the column as target? It is capitalized
I did read it in as a csv and xlsx file and got the same error for both

[Adults_Diabetes_NHANES_2011_2012.xlsx](https://github.com/pycaret/pycaret/files/5350851/Adults_Diabetes_NHANES_2011_2012.xlsx)

**Comment by pycaret** [comment]
@roberthoyt I have checked your file. Apparently there is a space at the end of the target variable name. It is "Diabetes " NOT "Diabetes". As such if you will run this code, it should work:

```
exp_clf = setup(data, target = 'Diabetes ')
```

Please close the issue if this works.
