### ISSUE TITLE
How to get score for all labels in multiclassification problems?

### ISSUE THREAD

**Issue by leocd91** [pycaret/pycaret#714]
Suprised to see this new variable when predict after updating PyCaret.
Can I get the other label score too?
For example : 
- label 0 : 0.7, label 1 : 0.2, label 2 : 0.1

**Comment by pycaret** [comment]
@leocd91 PyCaret's native `predict_model` will only attach the probability of the predicted class. If you want to see the probability value for all classes, I suggest you use `predict_proba` function.
