### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.externals.funcsigs'

### ISSUE THREAD

**Issue by ssfantasy** [pycaret/pycaret#715]
1186     #import library
-> 1187     import pycaret.preprocess as preprocess
   1188 
   1189     logger.info("Creating preprocessing pipeline")

~/venv_total/venv3/lib/python3.6/site-packages/pycaret/preprocess.py in <module>
     26 from sklearn.decomposition import IncrementalPCA
     27 from sklearn.preprocessing import KBinsDiscretizer
---> 28 from pyod.models.knn import KNN
     29 from pyod.models.iforest import IForest
     30 from pyod.models.pca import PCA as PCA_od

~/venv_total/venv3/lib/python3.6/site-packages/pyod/models/knn.py in <module>
     13 from sklearn.utils.validation import check_is_fitted
     14 
---> 15 from .base import BaseDetector
     16 
     17 

~/venv_total/venv3/lib/python3.6/site-packages/pyod/models/base.py in <module>
     12 
     13 import abc
---> 14 from sklearn.externals.funcsigs import signature
     15 from sklearn.externals import six
     16 

ModuleNotFoundError: No module named 'sklearn.externals.funcsigs'

**Comment by pycaret** [comment]
@ssfantasy What is your `sklearn` version?
