### ISSUE TITLE
Get coefficients and intercept for linear regression

### ISSUE THREAD

**Issue by g2giovanni** [pycaret/pycaret#72]
How can I collect coefficients and intercept for a linear regression model I created with PyCaret?

In ScikitLearn I can do:

lm = LinearRegression()
print(lm.intercept_)
print(lm.coef_)

**Comment by pycaret** [comment]
Hi.

Same way.

lr = create_model('lr')
print(lr.coef_)
print(lr.intercept_)

Thanks.
