### ISSUE TITLE
Decrease/Increase # of words being plotted in Pycaret 

### ISSUE THREAD

**Issue by shjb16** [pycaret/pycaret#722]
Is there a way to Decrease/Increase # of words being plotted in Pycaret ? Right now by default is shows Top 100 words after removing stop words, but I need the Top 30 . 

Also is there a way to get the words and their frequencies in a list?

**Comment by pycaret** [comment]
@shjb16 Not yet. We can put it in our backlog for future.

**Comment by moezali1** [comment]
We are no more supporting the `nlp` and `arules` module in PyCaret due to lack to resources. Closing the issue now.
