### ISSUE TITLE
could you please avoid the step that setup is asking for quit or enter option to preprocess

### ISSUE THREAD

**Issue by sathishkumar999** [pycaret/pycaret#728]
Hi pycaret team,

we wanna use pycaret in our production instead of sklearn and some other packages to reduce the code.
but we are facing some problems with pycaret when we run in production. especially when we use setup.
the data is about predicting priority on customer ticket. I could not share the data, because it's confidential.
pls find the attachments.
![Screenshot (408)](https://user-images.githubusercontent.com/40235632/96261025-7892ae80-0fdd-11eb-91a9-c62d3469a602.png)
![Screenshot (410)](https://user-images.githubusercontent.com/40235632/96261499-28681c00-0fde-11eb-86b1-6caaec8b42eb.png)

**Comment by Yard1** [comment]
`silent=True` in `setup()`

**Comment by sathishkumar999** [comment]
Hi @Yard1 
thanks that works, but setup data is not interpreting with the compare models. is there any way to pass 'setup' data into compare models. I know in jupyter notebook it does automatically. but here when we create functions it's not working. if we pass "clf-setup" data into compare models for training it might works.
![Screenshot (411)](https://user-images.githubusercontent.com/40235632/96361931-6af93800-1147-11eb-977b-290fe97f2ff9.png)

**Comment by jonppe** [comment]
Maybe you should specify the column types explicitly using categorical_features=[...], numeric_features=... and so on?

**Comment by Yard1** [comment]
Try importing pycaret inside the function, before calling setup.

**Comment by sathishkumar999** [comment]
we couldn't pass import module inside the function.

![Screenshot (412)](https://user-images.githubusercontent.com/40235632/96399042-fd9ee300-11ea-11eb-8f1d-9d60765ed904.png)

**Comment by Yard1** [comment]
Well, the error message explains it. Remove all pycaret imports outside the function level, and then import just the pycaret functions you use inside each of your functions. Eg. `from pycaret.classification import setup, compare_models`

**Comment by sathishkumar999** [comment]
Hi, I'm really sorry for interrupting @Yard1 
still the same issue. try to see once. if it's not possible. I'm gonna close this ticket. I don't want to disturb.
it's the same when I calling " from pycaret.classification import * " from outside the function and inside the function as you mentioned in the above comment as " from pycaret.classification import setup, compare_models "

![Screenshot (413)](https://user-images.githubusercontent.com/40235632/96399256-9170af00-11eb-11eb-8581-8e06fcf6beb1.png)

![Screenshot (414)](https://user-images.githubusercontent.com/40235632/96476455-d5e36580-1252-11eb-8982-6757222b0e43.png)

**Comment by Yard1** [comment]
Could you try one last thing? Pass `html=False` in `setup()`.

**Comment by sathishkumar999** [comment]
Thanks a lot @Yard1 
that's worked...

**Comment by sptiwari** [comment]
silent=True in setup() worked for me.

**Comment by ArashMehraban** [comment]
So silent=True does not work for me. I pass in a dataframe (df):
`import pycaret.anomaly as anom`

`df_ftrs = anom.setup(df, silent=True)`

The shell **hangs** after the forth:
`Initiated  . . . . . . . . . . . . . . . . . .            14:23:23`
`Status     . . . . . . . . . . . . . . . . . .  Preprocessing Data`

I am using idle python version 3.8.5 on Macbook pro with BigSur.
Any suggestion?

**Comment by Yard1** [comment]
This is for unrelated reasons. I wager your data is really big.

**Comment by ArashMehraban** [comment]
About 100K rows in the dataframe and the (pycaret) code executes fast. If I take the `silent=True` out, I get this:

`Text(value="Following data types have been inferred automatically, if they are correct press enter to continue or type 'quit' otherwise.", layout=Layout(width='100%'))`

and it gives me a list of my Data Types and then it hangs. There are only 5 categories and it guessed them all correctly. 

I am using  a small sample (100K). I will have millions or rows in production. Won't pycaret be able to handle it?

**Comment by ArashMehraban** [comment]
@Yard1 

> 

Correction: the data is pretty large, millions of rows (100M). So should I wait until it releases the terminal?
