### ISSUE TITLE
i got this memory error in text mining dataset

### ISSUE THREAD

**Issue by sai45741** [pycaret/pycaret#743]
[courseera reviews.zip](https://github.com/pycaret/pycaret/files/5410240/courseera.reviews.zip)
This is a dataset

`corpus`

['good interest',
 'one excellent course coursera information technology boss managers',
 'reason apply course bcg content pretty unique include high level analysis wide range knowledge need cover detail aspects best regard oleg serov',
 'course say anything digitization core subject digital wave',
 'videos present french could translate english',
 'course content quite good though could deeper areas peer review system work well regard le',
 'great piece work especially like lifehack cio',
 'excellent course reward term use tool give excellent today put use job thank inculcate knowledge move',
 'excellent representation day day thank share vision experience advices regardsdaniel damas',
 'interest well design mooc',
 'excellent course totally recommend',
 'great course information content interest unfortunately peer grade assignment classmates must grade although two classmates give pass grade one classmate give really justify make submit assignment thankfully amaze classmates saw quality work',
 'interest course learn lot history aboriginal education',
 'great content learn lot',
 'phenomenal course education worldviews first nations people educator first nation community ontario north knowledge lecture phenomenal',
 'find course interest great learn tool glad would recommend course people ni awen',
 'well present content comprehensive illustrations easy follow cover proper order every aspect draw autocad would appreciate english subtitle available whole course students could access handy lecture exercise',
 'basic course learners without autocad experience',
 'good quality',
 'thank',
 'course comprehensive detail bite fast pace people new finance',
 'great course person',
 'think engage course practical examples',
 'excellent overview ways print use may use future',
 'well document course assignments design way stimulate think box',
 'good informative course',
 'excellent course completely enjoy thank vishal team',
 'open understand could accomplish print',
 'important information copy right patent etc',
 'progress state flux one must reach best academia particular subject get realistic update technology course help catch design think get',
 'really challenge enrich course amaze world print course discover unimaginable amount applications print offer open mind ways think possible',
 'really good survey class potential print examples individuals empower others without obstacles traditional tool relatively short learn curve low investment also demonstrate ways increasingly future capable design solutions problems increase agility thing could make better would design challenge thank',
 'excellent course enjoy learn',
 'great course informative',
 'start say course give good insight wide variety applications print lot interview people leverage additive manufacture original effective ways last week course also introduce interest seemingly effective framework design think reason rat star however useful thing learn course design think framework think would better videos scatter throughout rest specialisation see value include material specialisation outright course',
 'course contain new information teach excitedly show commonly know facts better ways invest time',
 'great course enjoy learn material',
 'excellent course good class easy follow update content high quality videos',
 'merge course',
 'nutritional course real world examples let understand potential print emerge technology',
 'interest',
 'topics relate economy business something good enjoy read course help learn bunch useful things would otherwise put effort study',
 'able understand materials devices use print software aspects printers get introductory view cut edge applications print biomedical applications',
 'course interest enlighten wonderful introduction especially learners prior experience print',
 'great information videos ready next step gus',
 'excellently frame course',
 'like fact many leaders print come diverse background share infectious spirit learn push boundaries software hardware materials science',
 'great overview introduction print',
 'great want overview current situation print technology develop business print watch',
 'think great high level intro world print',
 'get new prospect vision print tech',
 'great course great implementation motivation provide definitely increase enthusiasm really look forward course increase skills',
 'excellent course well present enjoy instruction sessions also interview specialists fascinate field great course inspire one continue pursue career',
 'informative approachable course really like way aric present information excite complete rest specialization',
 'good introduction',
 'best course beginners',
 'thank course open world print start',
 'great course aric rindfleisch encourage enthusiasm new techology revolution give fundamental basics matter furthermore interest print start course surely follow follow illinois university course print',
 'great intro print many many ways use',
 'good experience start',
 'give nice view print',
 'course change view print revolution',
 'get great insight towards print',
 'excelent lot information really interest interview plus aric rindfleisch extremely clear lecture congratulations',
 'wow learn easy bring innovation reality please join course highly recommend',
 'great introduction print cover basics different print technologies desktop industrial hardware show resources service available utilise print effectively provide interview entrepreneurs others industry use technology',
 'course contain new information teach excitedly show commonly know facts better ways invest time',
 'fred j feilernov pstchat start pm utc pm fred j feiler need start date print software course learners concern course never happen even enrol since june pm coursera support thank reach us someone right pm jessy join chat pm jessy thank reach us happy help today pm jessy sorry inconvenience pm jessy please allow moment take look fred pm fred j feiler thank pm fred j feiler enrol five course specialization momentum standstill course delay look something better pm jessy sorry inconvenience fred check course sessions available yet pm jessy look like need time look issue go escalate support specialists investigate mean end chat become support ticket email receive email transcript chat record someone support team review chat email update soon possible pm fred j feiler ok thank',
 'excellent introduction print course well design engage look forward course series',
 'course fantastic learn much excite continue track',
 'great course wait next one start',
 'accord expect',
 'thumb learn something never learn',
 'great course start print technology',
 'great introduction print world',
 'good introductory course novice print help lot understand basics print',
 'good place start know anything print',
 'complete extensive weeks actually take weeks complete',
 'thank much',
 'excellent information cover understandable practical examples great professors',
 'interest course',
 'comprehensive total introduction basic concepts print',
 'excellent course really lloking forward rest specialization',
 'suberb introducition print idea usage',
 'really like print revolution course easy understand need background knowledge find much topic include materials use technologies print company also materials cover history future print great introductory course instructor guests amaze recommend',
 'nice introduction absolute beginners interest interview entrepreneurs',
 'great course fundamentals cover excite take next course',
 'mostly basic stuff even introduce concepts aware',
 'great thank dr aric smiley face one enrol course would get great knowledge usefull information print addtive manufacture throw simple excite videos would get another benefit information priting like get knowledge many company inside see stories successfull people achieve keep work meet colleagues make new friends finally grow english skills like listen grow vocabulary great thaks coursera team pleasure learn',
 'nice introduction print love',
 'good introductory course little bite short like gus',
 'rate really enjoy max',
 'great course must every individual idea even aric team guide throughout wonderful technique',
 'great course learn print see technology gottten pursue rest capstone',
 'hesitate enroll brain storm course like way teach',
 'great course delivery instructor great opportunity meet great people like real journey course give clear understand print high level look forward get depth knowledge course would highly recommend course wish know print',
 'provide good overview print stimulate people attend look great course start journe',
 'geeat give confidence unleash creativity see world different eye great opportunities create customize object',
 'good introductory course print everybody every level',
 'mind blow course',
 'great introduction',
 'like course pretty concise straight forward highly recommend',
 'eye mind open course',
 'good introduction print',
 'good introduction subject instructor never loose attention new topics examples',
 'great introduction even people pursue completion full specialisation',
 'perfect introduction print world',
 'amaze interactive engage comprehensive',
 'excellent introduction print',
 'great content videos talk motivate give excite overview subject thank great work',
 'great class',
 'interactive reflective course highly recommend',
 'good overview make long',
 'know little nothing additive sound interest good place start',
 'excellent course start completely new print easy understand language little special tech talk course suitable virtually anybody true need tech genius get acquanted world print',
 'good course please provide practice quiz depth',
 'simply interest',
 'nice brief introduction print technology',
 'good helpful introduction print',
 'great class',
 'good easy understand first inmersion world print',
 'exactly like lecturer say would like hard part last part actually remix exist model think part lecturer video depth look use app nevertheless course good learn lot new stuff give spoilers worth',
 'good introduction print',
 'great information print help understand current scope technology start',
 'really care stories students see space one whole lecture video clear ultimaker sponsor felt like commercial want learn',
 'fantastic',
 'great class']

```
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

x=cv.fit_transform(corpus).toarray()
x

```

MemoryError                               Traceback (most recent call last)
<ipython-input-23-eabbfea76370> in <module>
----> 1 x=cv.fit_transform(corpus).toarray()
      2 x

~\anaconda3\lib\site-packages\scipy\sparse\compressed.py in toarray(self, order, out)
   1023         if out is None and order is None:
   1024             order = self._swap('cf')[0]
-> 1025         out = self._process_toarray_args(order, out)
   1026         if not (out.flags.c_contiguous or out.flags.f_contiguous):
   1027             raise ValueError('Output array must be C or F contiguous')

~\anaconda3\lib\site-packages\scipy\sparse\base.py in _process_toarray_args(self, order, out)
   1187             return out
   1188         else:
-> 1189             return np.zeros(self.shape, dtype=self.dtype, order=order)
   1190 
   1191 

MemoryError: Unable to allocate 21.6 GiB for an array with shape (107018, 27113) and data type int64

**Comment by Yard1** [comment]
Try converting the corups to `int32`.

**Comment by sai45741** [comment]
@Yard1  corpus is in str format, its not work

**Comment by Yard1** [comment]
Try
```python
import numpy as np
CountVectorizer(dtype=np.int32)
```

**Comment by sai45741** [comment]
@Yard1 Thank you for giving the suggestion its working

**Comment by sai45741** [comment]
`from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)`

MemoryError                               Traceback (most recent call last)
<ipython-input-36-4cc4229aa9df> in <module>
      1 from sklearn.model_selection import train_test_split
      2 
----> 3 x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

~\anaconda3\lib\site-packages\sklearn\model_selection\_split.py in train_test_split(*arrays, **options)
   2152         train, test = next(cv.split(X=arrays[0], y=stratify))
   2153 
-> 2154     return list(chain.from_iterable((_safe_indexing(a, train),
   2155                                      _safe_indexing(a, test)) for a in arrays))
   2156 

~\anaconda3\lib\site-packages\sklearn\model_selection\_split.py in <genexpr>(.0)
   2152         train, test = next(cv.split(X=arrays[0], y=stratify))
   2153 
-> 2154     return list(chain.from_iterable((_safe_indexing(a, train),
   2155                                      _safe_indexing(a, test)) for a in arrays))
   2156 

~\anaconda3\lib\site-packages\sklearn\utils\__init__.py in _safe_indexing(X, indices, axis)
    393         return _pandas_indexing(X, indices, indices_dtype, axis=axis)
    394     elif hasattr(X, "shape"):
--> 395         return _array_indexing(X, indices, indices_dtype, axis=axis)
    396     else:
    397         return _list_indexing(X, indices, indices_dtype)

~\anaconda3\lib\site-packages\sklearn\utils\__init__.py in _array_indexing(array, key, key_dtype, axis)
    179     if isinstance(key, tuple):
    180         key = list(key)
--> 181     return array[key] if axis == 0 else array[:, key]
    182 
    183 

MemoryError: Unable to allocate 8.65 GiB for an array with shape (85614, 27113) and data type int32

**Comment by Yard1** [comment]
You need to buy more RAM, or increase the size of you swap memory.
