### ISSUE TITLE
Not working on module level :from pycaret.classification import *

### ISSUE THREAD

**Issue by VinayChaudhari1996** [pycaret/pycaret#744]
### Problem :-
___
1) Import * is not working on some platforms.

Example: 
`from pycaret.classification import *`

2) How can I use individual import rather than *

Thanks

**Comment by Yard1** [comment]
You can import individual functions. For example, `from pycaret.classification import setup, create_model`.

**Comment by VinayChaudhari1996** [comment]
👍 thanks
