### ISSUE TITLE
I could not understand what is that error.

### ISSUE THREAD

**Issue by sai45741** [pycaret/pycaret#747]
![Demand forecasting](https://user-images.githubusercontent.com/73189049/96753998-4b376d80-13ee-11eb-94ee-46f303908bde.jpg)
This is a dataset

```
from sklearn.neighbors import KNeighborsClassifier
classifier_knn=KNeighborsClassifier(n_neighbors=5)
classifier_knn.fit(x_train,y_train)
y_pred_knn=classifier_knn.predict(x_test)
fpr,tpr,thresold=roc_curve(y_test,y_pred_knn)
x=dataset.drop("units_sold",axis=1)
y=dataset["units_sold"]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
np.set_printoptions(precision=2,suppress=True)
x_train
array([[-0.87, -0.45, -1.16, ...,  0.07, -0.4 , -1.36],
       [-1.1 , -0.45, -1.19, ..., -0.33, -0.4 , -0.77],
       [ 2.05, -0.42,  0.17, ...,  1.35, -0.4 ,  0.71],
       ...,
       [-1.23, -0.45, -1.32, ..., -0.8 ,  0.18, -0.81],
       [-1.16, -0.37, -0.28, ...,  0.07,  1.55,  0.81],
       [-0.54, -0.42, -0.14, ..., -1.41, -0.4 ,  0.31]])
```

I tried remaining classifiers and regressors also but i get same error

ValueError                                Traceback (most recent call last)
<ipython-input-44-e2fa6b830ebd> in <module>
----> 1 fpr,tpr,thresold=roc_curve(y_test,y_pred_knn)

~\anaconda3\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     71                           FutureWarning)
     72         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 73         return f(**kwargs)
     74     return inner_f
     75 

~\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py in roc_curve(y_true, y_score, pos_label, sample_weight, drop_intermediate)
    773 
    774     """
--> 775     fps, tps, thresholds = _binary_clf_curve(
    776         y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
    777 

~\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py in _binary_clf_curve(y_true, y_score, pos_label, sample_weight)
    537     if not (y_type == "binary" or
    538             (y_type == "multiclass" and pos_label is not None)):
--> 539         raise ValueError("{0} format is not supported".format(y_type))
    540 
    541     check_consistent_length(y_true, y_score, sample_weight)

ValueError: multiclass format is not supported

**Comment by Yard1** [comment]
This isn't a PyCaret issue (same as your last issue). Please open an issue in the scikit-learn repository.
