### ISSUE TITLE
Add Python Version Badge to README

### ISSUE THREAD

**Issue by clgarciga** [pycaret/pycaret#748]
For example:

![image](https://user-images.githubusercontent.com/13739205/96800721-00a8f780-13d4-11eb-87d1-cd95947fd083.png)

**Comment by pycaret** [comment]
@clgarciga Would you like to work on this? Can you please submit a PR on master?

**Comment by clgarciga** [comment]
Yup

**Comment by pycaret** [comment]
@clgarciga Are you planning to push PR soon?

**Comment by clgarciga** [comment]
@pycaret Was going to get to it on Saturday.

**Comment by pycaret** [comment]
@clgarciga Thanks. Waiting for PR.

**Comment by pycaret** [comment]
@clgarciga Do you think you can still do this?

**Comment by clgarciga** [comment]
No, I've unassigned myself.

**Comment by pycaret** [comment]
@rajpratyush Thanks. I have assigned it to you now.

**Comment by rajpratyush** [comment]
Thank you! @pycaret

**Comment by rajpratyush** [comment]
@pycaret Check the PR #1019

**Comment by pycaret** [comment]
@rajpratyush Thanks. Will merge soon. Appreciate your help.

**Comment by rajpratyush** [comment]
@pycaret thanks for the opportunity
