### ISSUE TITLE
How to configure parameters of algorithm ?

### ISSUE THREAD

**Issue by actcod01** [pycaret/pycaret#749]
**Problem: Regression**
Pycaret version: 2.0.0

❌ The example mentioned in docs is not working 
https://pycaret.org/tune-model/

____

Ex: I have used the decision tree

### 1) How to configure the parameters of the selected algorithm?
![image](https://user-images.githubusercontent.com/67143298/96855841-e8d87e80-147a-11eb-8a0f-99091c1ebf30.png)

___
Error :

![image](https://user-images.githubusercontent.com/67143298/96856250-52f12380-147b-11eb-9df9-dcc4231b2583.png)

Thanks

**Comment by Yard1** [comment]
The example is for classification, but your issue states that you have a problem with regression. `DecisionTreeRegressor` and `DecisionTreeClassifiers` have different possible values for some parameters. Refer to scikit-learn documentation.
