### ISSUE TITLE
Catboost : Did not show parameters of model

### ISSUE THREAD

**Issue by Practcdi** [pycaret/pycaret#754]
**Pycaret version : 2.0.0**
___
**Issue: I m trying to get parameters like [  **ada**  ] but it does not work for [  catboost  ]**
___

### In Ada
![image](https://user-images.githubusercontent.com/58843833/96959589-0874b300-151e-11eb-976b-bb7e765f6be3.png)

____

### In Catboost
![image](https://user-images.githubusercontent.com/58843833/96959376-85535d00-151d-11eb-9196-0e7ca862ad18.png)

Thanks,

**Comment by pycaret** [comment]
@Practcdi You can use this to get catboost params:

```
catboost = create_model('catboost')
catboost.get_all_params()
```
