### ISSUE TITLE
Stack_models method error 

### ISSUE THREAD

**Issue by Jheel-patel** [pycaret/pycaret#757]
Obtained this error on running  `stack_hard = stack_models(top3, method='hard')`

An exception has occurred, use %tb to see the full traceback.

SystemExit: (Value Error): Method parameter not acceptable. It only accepts 'auto', 'predict_proba', 'decision_function', 'predict'.

On running %tb

---------------------------------------------------------------------------
SystemExit                                Traceback (most recent call last)
<ipython-input-34-e95db3cc70da> in <module>
----> 1 stack_hard = stack_models(top3, method='hard')

~\AppData\Roaming\Python\Python38\site-packages\pycaret\classification.py in stack_models(estimator_list, meta_model, fold, round, method, restack, choose_better, optimize, verbose)
   6851     available_method = ['auto', 'predict_proba', 'decision_function', 'predict']
   6852     if method not in available_method:
-> 6853         sys.exit("(Value Error): Method parameter not acceptable. It only accepts 'auto', 'predict_proba', 'decision_function', 'predict'.")
   6854 
   6855     #checking restack parameter

SystemExit: (Value Error): Method parameter not acceptable. It only accepts 'auto', 'predict_proba', 'decision_function', 'predict'.

**Comment by pycaret** [comment]
@Jheel-patel As the message says, please pass one of these values:  'auto', 'predict_proba', 'decision_function', 'predict'.

Old methods have been deprecated. 'hard' equivalent would be 'predict'. For example:

```
stack_hard = stack_models(top3, method='predict')
```
