### ISSUE TITLE
use multiple process to do predict in parallel 

### ISSUE THREAD

**Issue by wentworth001** [pycaret/pycaret#758]
Hi,

Currently I want to use regression.predict_model in multiple processes, but seems it quit each process, could you give a hand? Thanks.

Meanwhile, my model is already trained, so I want to transfer it to sub-process by ProcessPoolExecutor's executor.submit, seems I cannot send it to sub-process. Then I have to load model in each sub process directly, but still fail as I mentioned at the beginning.

**Comment by wentworth001** [comment]
sometimes it hung, maybe deadlock?

**Comment by Yard1** [comment]
PyCaret is not designed to be ran in parallel. You should save and load the model pipeline with `save_model` and `load_model` and predict using sklearn API in that case.

**Comment by wentworth001** [comment]
got it, thanks, let me close this question.
