### ISSUE TITLE
PyCaret in Azure Databricks issue 

### ISSUE THREAD

**Issue by hakobjan** [pycaret/pycaret#781]
when running the setup command in Azure data bricks 

`exp_ano101 = setup(data, normalize = True,
                   session_id = 123)` 

It takes a very long time to run the cell and does not converge. 
any idea why is it happening or is there a fix? 
Thanks in advance

**Comment by pycaret** [comment]
@hakobjan Azure Databricks doesn't support html. Please pass silent = True and html = False in the setup function. Your code should look like this:

```
exp_ano101 = setup(data, normalize = True, session_id = 123, silent = True, html = False)
```

Hope this will help. Please close the issue if it works for you.

**Comment by hakobjan** [comment]
I see, thanks for the tip
