### ISSUE TITLE
QuadraticDiscriminantAnalysis instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

### ISSUE THREAD

**Issue by gm039** [pycaret/pycaret#782]
from pycaret.classification import *
exp_name = setup(data,  target = 'TARGET')
Model_qda = create_model('qda', fold = 5)
tuned_model_qda_best = tune_model(Model_qda, fold = 5,choose_better=True,n_iter = 100) #Return best model
pred_holdouts_qda = predict_model(tuned_model_qda_best)

I get the following error in PyCaret 2.2.0. It used to work well on PyCaret 2.1.0. Can you please help?

########################################################################################
NotFittedError                            Traceback (most recent call last)
<ipython-input-220-4b906e995d95> in <module>()
    179   # Res_pred_holdouts_lda=pull()
    180 
--> 181   pred_holdouts_qda = predict_model(tuned_model_qda_best)
    182   #pred_holdouts_qda.to_csv('pred_holdouts_qda.csv')
    183   Res_pred_holdouts_qda=pull()

5 frames
/usr/local/lib/python3.6/dist-packages/pycaret/classification.py in predict_model(estimator, data, probability_threshold, encoded_labels, round, verbose)
   1869         round=round,
   1870         verbose=verbose,
-> 1871         ml_usecase=MLUsecase.CLASSIFICATION,
   1872     )
   1873 

/usr/local/lib/python3.6/dist-packages/pycaret/internal/tabular.py in predict_model(estimator, data, probability_threshold, encoded_labels, round, verbose, ml_usecase, display)
   8270     # prediction starts here
   8271 
-> 8272     pred = np.nan_to_num(estimator.predict(X_test_))
   8273 
   8274     try:

/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py in predict(self, X)
    783         C : ndarray of shape (n_samples,)
    784         """
--> 785         d = self._decision_function(X)
    786         y_pred = self.classes_.take(d.argmax(1))
    787         return y_pred

/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py in _decision_function(self, X)
    730     def _decision_function(self, X):
    731         # return log posterior, see eq (4.12) p. 110 of the ESL.
--> 732         check_is_fitted(self)
    733 
    734         X = check_array(X)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py in check_is_fitted(estimator, attributes, msg, all_or_any)
   1017 
   1018     if not attrs:
-> 1019         raise NotFittedError(msg % {'name': type(estimator).__name__})
   1020 
   1021 

NotFittedError: This QuadraticDiscriminantAnalysis instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

**Comment by Yard1** [comment]
@gm039 Thanks for your report. I just pushed commit 3ff4b89cda0879ba4a11fa14371cec2505b0862a that should fix this issue. Could you run
`pip install --upgrade --user git+git://github.com/pycaret/pycaret.git` to install PyCaret's development version and try again?

**Comment by gm039** [comment]
> @gm039 Thanks for your report. I just pushed commit [3ff4b89](https://github.com/pycaret/pycaret/commit/3ff4b89cda0879ba4a11fa14371cec2505b0862a) that should fix this issue. Could you run
> `pip install --upgrade --user git+git://github.com/pycaret/pycaret.git` to install PyCaret's development version and try again?

Thanks! It worked. 
I found another issue with catboost model. it throws the below error when I run the following lines.

Model = create_model('catboost', fold = 5)
tuned_model_best = tune_model(Model, fold = 5,choose_better=True,n_iter = 100) #Return best model
pred_holdouts_qda = predict_model(tuned_model_best)

############################################################################
       44 Model = create_model('catboost', fold = 5)
---> 45 tuned_model_best = tune_model(Model, fold = 5,choose_better=True,n_iter = 100)
     46 
     47 pred_holdouts_qda = predict_model(tuned_model_best)

2 frames
/root/.local/lib/python3.6/site-packages/pycaret/classification.py in tune_model(estimator, fold, round, n_iter, custom_grid, optimize, custom_scorer, search_library, search_algorithm, early_stopping, early_stopping_max_iters, choose_better, fit_kwargs, groups, return_tuner, verbose, tuner_verbose, **kwargs)
   1092         verbose=verbose,
   1093         tuner_verbose=tuner_verbose,
-> 1094         **kwargs,
   1095     )
   1096 

/root/.local/lib/python3.6/site-packages/pycaret/internal/tabular.py in tune_model_supervised(estimator, fold, round, n_iter, custom_grid, optimize, custom_scorer, search_library, search_algorithm, early_stopping, early_stopping_max_iters, choose_better, fit_kwargs, groups, return_tuner, verbose, tuner_verbose, display, **kwargs)
   4466             groups=groups,
   4467             fit_kwargs=fit_kwargs,
-> 4468             display=display,
   4469         )
   4470 

/root/.local/lib/python3.6/site-packages/pycaret/internal/tabular.py in _choose_better(models_and_results, compare_dimension, fold, fit_kwargs, groups, display)
   9592     for model, result in models_and_results:
   9593         if result is not None or not is_fitted(model):
-> 9594             result = result.loc["Mean"][compare_dimension]
   9595         else:
   9596             logger.info(

AttributeError: 'NoneType' object has no attribute 'loc'

**Comment by Yard1** [comment]
@gm039 Thanks. I pushed another fix.

**Comment by pycaret** [comment]
@gm039 Can you re-test again and let us know if the problem is resolved after installing the latest master branch? We are planning to push out a patch release over weekend.

**Comment by gm039** [comment]
Thanks!
The problem is solved.
