### ISSUE TITLE
TypeError: tune_model() got an unexpected keyword argument 'search_library'

### ISSUE THREAD

**Issue by nau7ic** [pycaret/pycaret#783]
Python Version 3.8.5
Pycaret 2.2

when i try to run

tuned_top5 = [tune_model(i,choose_better=True, search_library='scikit-optimize') for i in top5]

i get

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-4a1ae687039d> in <module>
----> 1 tuned_top5 = [tune_model(i,choose_better=True, search_library='scikit-optimize') for i in top5]

<ipython-input-12-4a1ae687039d> in <listcomp>(.0)
----> 1 tuned_top5 = [tune_model(i,choose_better=True, search_library='scikit-optimize') for i in top5]

TypeError: tune_model() got an unexpected keyword argument 'search_library'

**Comment by pycaret** [comment]
@nau7ic Seems like some kind of conflict with the previous version. Can you please upload the` logs.log` here? You can find it the directory where your Notebook or Python script is.

**Comment by pycaret** [comment]
@nau7ic Your logs shows you are using the old version. Can you uninstall and re-install pycaret from scratch or install in a new environment?

```
pip uninstall pycaret -y
pip install pycaret[full]
```

![image](https://user-images.githubusercontent.com/58118658/97620348-d8368400-19f7-11eb-97bb-718595b81f89.png)

**Comment by nau7ic** [comment]
Thank you! The reinstall helped
