### ISSUE TITLE
plot_model prediction error plot - X and Y scale not adapted to data

### ISSUE THREAD

**Issue by anne-leroy-T** [pycaret/pycaret#784]
Hello,

For plot_model prediction error plot, the X and Y scale is not adapted to data.

scale parameter only changes the size of the plot, not the scaling; so it's useless.

Is there another parameter that could help ?

Please check attached picture
<img width="268" alt="plot" src="https://user-images.githubusercontent.com/25195665/97576189-2050a900-19ee-11eb-8a56-b0bdd8b9131b.png">

Thanks.

**Comment by anneleroytotal** [comment]
If this cannot be solved at the present time, is there a way to get the yhat for the train, so I can plot it myself ?

**Comment by anne-leroy-T** [comment]
This is due to the fact i think that my target is a very small number between 0.001 and 0.10

Is this a bug ?

**Comment by pycaret** [comment]
@anne-leroy-T Nope. This is due to the target variable being too small. We are using `yellowbricks` at the back end which seems like not scaling the graph appropriately.

**Comment by anne-leroy-T** [comment]
OK; I found an easy solution by multiplying my target by 1000; but well it's anyway an issue ....   with yellowbricks then ;-)

I close the subject. Thanks for your answer. Have a nice day.

Anne
