### ISSUE TITLE
Output multiple create model in a single jupyter notebook cell

### ISSUE THREAD

**Issue by anneleroytotal** [pycaret/pycaret#785]
Hello,

I try to iterate on some models (without using compare) with create_model and tune_model.  I would like to receive in the output jupyter cell iteratively all the results of each model.
But it only gives me the last. 

I changed the interactive shell property, but it does not help :
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

If not possible and possibily better as I could save that in a dataframe if possible,, is there a way afterwards to extract this information from the model that is built. Printing the model, only gives me the parameters, i would like to have the full output of create_model that is each value of each cross validation step.

Thanks.

**Comment by Yard1** [comment]
You can get the last displayed dataframe with `pull()`, so for example:
```python
results = [] #will be a list of dataframes
for model in models:
	create_model(model)
	results.append(pull())
```

**Comment by anneleroytotal** [comment]
Thank you for your precious help. It's working !
