### ISSUE TITLE
How to get final metrics value after model training like , R2 or Accuracy ?

### ISSUE THREAD

**Issue by Practcdi** [pycaret/pycaret#789]
## Pycaret Version: 2.2

_____

**Task Regression:**

Problem: I'm trying to find the final Score of my model, without creating an unseen dataset 

`Mean   905.49  3792223.23  1888.88  0.96   0.10  0.07
`

_____
![image](https://user-images.githubusercontent.com/58843833/97709441-58381900-1ae0-11eb-8b6e-ad897ef6e507.png)

☑️  In code I have used 70% Data for training, I want to **find the final Model score on the remaining 30% data:** 

____

`exp_reg101 = setup(data = data, target = 'Price',train_size=0.7)
`

____

**Looking for expected output like:**

### Final Model Score by R2 : _96%_

Thanks,

**Comment by pa-blan** [comment]
Try the finalize_model function:

pycaret.classification.finalize_model(estimator, fit_kwargs: Optional[dict] = None, groups: Optional[Union[str, Any]] = None, 
model_only: bool = True) 

This function trains a given estimator on the entire dataset including the holdout set.

**Comment by Yard1** [comment]
`predict_model(model)` will do that.

**Comment by Practcdi** [comment]
Hey,

**Problem : ```predict_model(model)``` returns type data frame and I think model evaluation comes from print()
statement**
____

![image](https://user-images.githubusercontent.com/58843833/97838028-5dc27880-1d05-11eb-95fa-3c96dc3e843a.png)


**So how can I access the R2 value in it?  I want to store model performance data in list or dict !** 
____
![image](https://user-images.githubusercontent.com/58843833/97838282-dc1f1a80-1d05-11eb-8c58-ee6ab94e0e68.png)


Thanks ,

**Comment by Yard1** [comment]
`pull()` will return the latest printed dataframe, so just call it after `predict_model()`.

**Comment by VinayChaudhari1996** [comment]
`pull()` is worked for me ,
Thanks

**Comment by Practcdi** [comment]
`Pull ()` worked for me!
Thanks ,
