### ISSUE TITLE
feature Proposal : Enable profile tuning in setup

### ISSUE THREAD

**Issue by danbricedatascience** [pycaret/pycaret#792]
The `profile` parameter in setup enable getting pandas profiling reports. This can be quite long for big datasets. 

So in addition to `True` or `False`, enable passing the mode including minimal mode for large dataset.

**Comment by pycaret** [comment]
@danbricedatascience What is the minimal mode, do you have any example?

**Comment by danbricedatascience** [comment]
When using directly pandas-profile.

https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/big_data.html

```python
profile = ProfileReport(large_dataset, minimal=True)
```

So in PyCaret setup this could becomes:

```python
clf1 = setup(data, target = 'Purchase', session_id=1, log_experiment=True,experiment_name='juice1',
profile=True, profile_minimal=True)
```
Or also enable customizing the report:

https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/advanced_usage.html#general-settings

When using directly pandas-profile:

```python
profile = df.profile_report(
     title="Report without correlations",
     correlations={
         "pearson": {"calculate": False},
         "spearman": {"calculate": False},
         "kendall": {"calculate": False},
         "phi_k": {"calculate": False},
         "cramers": {"calculate": False},
     },
 )

 # or using a shorthand that is available for correlations
    profile = df.profile_report(
     title="Report without correlations",
     correlations=None,
 )
```

So in PyCaret setup this could becomes:

```python
clf1 = setup(data, target = 'Purchase', session_id=1, log_experiment=True,experiment_name='juice1',
profile=True, profile_correlations=None)
```
