### ISSUE TITLE
How to use different encoding techniques in setup()

### ISSUE THREAD

**Issue by VinayChaudhari1996** [pycaret/pycaret#794]
Pycaret - 2.2
_____
I want to use following encoding techniques for specific columns in pycaret. How can I use that in ```setup()``` ?

______

**One hot Encoding
Dummy Encoding
Effect Encoding
Binary Encoding
BaseN Encoding
Hash Encoding
Target Encoding**

For now , I think very few techniques are supported in pycaret 2.2.0

So is there any way to integrate custom techniques in setup ? 
 
Ref blog :- 
https://www.analyticsvidhya.com/blog/2020/08/types-of-categorical-data-encoding/

Thanks ,

**Comment by Yard1** [comment]
Only OHE is supported in the current release.

**Comment by VinayChaudhari1996** [comment]
So, how can I **integrate any custom encoding technique in existing pycaret pipeline ?** 
Is it possible ?

Final Aim is to **use original features for inference** (not encoded one? 

Beacuse in traditional ways, we loose all mapping information after any encoding techniques and it becomes very tricky for inference.

Thanks ,

**Comment by Yard1** [comment]
At this moment, the only way to do that is to preprocess the data yourself and pass it to `setup()` with `preprocess=False` argument.

**Comment by VinayChaudhari1996** [comment]
**There is one method in pycaret 2.2 called :-** 
_____

`custom_pipeline: (str, transformer) or list of (str, transformer), default = None`


1) How to use it , there is no valid resources about it. 

2) Does it update existing pipeline ? 

Thanks,

**Comment by Yard1** [comment]
Custom pipeline is applied after the default PyCaret pipeline steps (one of which is one hot encoding). You could set `preprocess=False` in `setup` and then use this parameter. You should just pass a list of sklearn transformers as a value for `custom_pipeline` argument.

**Comment by ngupta23** [comment]
Lets leave this open since it is marked as an enhancement.
