### ISSUE TITLE
question about iterative imputation:

### ISSUE THREAD

**Issue by atwahsz** [pycaret/pycaret#795]
does the iterative imputation (lightgbm,knn,etc) use the setup prepossessing prior to training  a model to fill the missing data ?

all of the best

Saleh ,

**Comment by Yard1** [comment]
Iterative imputation uses simple imputation as the first step.

**Comment by atwahsz** [comment]
In pycaret 2.2 it says that it uses lightgbm to train on data and fill the missing

**Comment by pycaret** [comment]
@atwahsz Yes, `lightgbm` is used by default but you can change it to any estimator available in the library using `categorical_iterative_imputer` and `numeric_iterative_imputer` parameters in the setup. 

In case you meant to ask for a sequence of steps, missing value imputation is applied right after data type identification that means before all other preprocessing in the setup. 

If this answers your question, please feel free to close the issue.

**Comment by pycaret** [comment]
@atwahsz I am closing the issue for now as there are no details on which we can act. Please feel free to open another issue when you are ready and if required.
