### ISSUE TITLE
Issue with tree plot from Jupyterlab 2

### ISSUE THREAD

**Issue by danbricedatascience** [pycaret/pycaret#798]
Jupyterlab 2.2.6

When displaying a tree plot with:

```python
plot_model(dt2,plot='tree');
```
The resulting plot is badly displayed, see screenshot.
<img width="1120" alt="tree" src="https://user-images.githubusercontent.com/10685563/97909550-b2d3ae00-1d48-11eb-86f3-a87e6bafa33f.png">

**Comment by Yard1** [comment]
I'll have to fiddle with it some more, looks like. It is very tricky to balance it between being readable and taking as little space as possible.

**Comment by danbricedatascience** [comment]
Using graphviz instead of plot_tree enable getting a better rendering, but it can be quite big.

Maybe a solution can be to export a temporary .png through graphviz then display it according to a scale factor that can be tuned in `plot_model`, so only the .png size will change, but the leafs will never hide each other.

<img width="1711" alt="Capture d'écran-1" src="https://user-images.githubusercontent.com/10685563/97960853-789ef680-1db2-11eb-91c6-b00a6082cc84.png">
