### ISSUE TITLE
Dataframe with custom index breaks prediction

### ISSUE THREAD

**Issue by leonsolon** [pycaret/pycaret#799]
Test dataframes with custom index (unseen data) breaks at prediction. It seems the Score column is set with positional index and the rest of the values of the rows with no matching indexes are all set to NaN. 

To avoid, this one has to reset index to positional and then recover the custom original index, which is not the way it should work.

That being said: pycaret is the bomb, you guys created an amazing tool, congrats.

Here's a screenshot of the issue;

![pycaret_error](https://user-images.githubusercontent.com/17159048/97950002-35259780-1d74-11eb-9daf-2009fa4e5028.png)

**Comment by pycaret** [comment]
@leonsolon Thank you for reporting.

Is it possible for you to upload Notebook and sample data here so we can reproduce the issue?

**Comment by Yard1** [comment]
@leonsolon  I just pushed commit 9c5d00077bb12749bdd25965d5501e27eb645c71 that should fix this issue. Could you run
`pip install --upgrade --user git+git://github.com/pycaret/pycaret.git` to install PyCaret's development version and try again?

**Comment by leonsolon** [comment]
Great, it worked! Thanks a lot.
