### ISSUE TITLE
Merging Stack_Model and Stacknet

### ISSUE THREAD

**Issue by Riazone** [pycaret/pycaret#8]
Hi,

**_stack_model()_** and **_create_stacknet()_** are both wonderful features, something I havent seen being provided by any other package. However, intrinsically I feel the only difference in them is of layers. If we can have just one function with options of choosing number and estimators at each layer, we would not need two functions here.

Thanks.

**Comment by pycaret** [comment]
@Riazone **create_stacknet** is deprecated and will be removed from PyCaret 3.0x. 

Closing this issue.
