### ISSUE TITLE
error when predict_model()

### ISSUE THREAD

**Issue by atwahsz** [pycaret/pycaret#801]
good morning

i get an error when it try to predict_model()

ValueError: Pipeline not found 

it happens when i use iterative imputation

**Comment by pycaret** [comment]
@atwahsz What's your version of PyCaret? Can you please update `logs.log` file here?

**Comment by pycaret** [comment]
@atwahsz Please update your version to `2.2`. I am closing this issue for now as there are no details we can work on. Please feel free to open another issue, if it persists and when you are ready.
