### ISSUE TITLE
How to get train_yhat for create_model and tune_model      - and test_yhat for predict_model

### ISSUE THREAD

**Issue by anne-leroy-T** [pycaret/pycaret#802]
As I have an issue with the plot error (#784), I would like to get the yhat resulting from the create_model and tune_model; as well as the yhat from test, in order to plot it by myself.

How can I achieve this ?

Thanks

**Comment by Yard1** [comment]
`create_model()` and `tune_model()` return a trained model object. You can get the train and test data frames with `get_config('X_train')`, `get_config('X_test')`, `get_config('y_train')` and `get_config('y_test')`.

**Comment by anneleroytotal** [comment]
Great, it's working fine.  In the meantime, I found : predict_model(my_model_tuned, data=train) where I can get results as well. I will check if it gives me the same results before closing the subject

**Comment by anne-leroy-T** [comment]
I do not want the real y_train and y_test from my dataset, I would like to get the y that are predicted by the create_model and tune_model.
This is because the plot "error" has obviously an issue (see my (#784) and I want to plot it by myself instead to check prediction versus real.

Thanks

**Comment by Yard1** [comment]
`predict_model()` will return a dataframe with the `Label` column being the predicted values.

**Comment by anne-leroy-T** [comment]
This looks not so easy as I want the prediction on the train.

The solution I can find to get the predict on train is : 
- get_config('X_train') in order to know the records that were selected by the create_model for the train/test split. Because this is already the transformed dataset, I cannot use it directly for the predict however.
- extract from my full input dataset, the records that are specified in the get_config(X_train)
- predict on this subset

is there an easier way ?

**Comment by anne-leroy-T** [comment]
ok ... it seems that get_config('y_train')   does not give the label from the train set ... but the predicted label ... am I right ...if I'm right, this is exactly what I need.  could you confirm ?  Sorry, I did not find this info in the doc ... (or at least understood it ;-) )

**Comment by anne-leroy-T** [comment]
It seems I don't understand, the predict as described by : 
The solution I can find to get the predict on train is :

get_config('X_train') in order to know the records that were selected by the create_model for the train/test split. Because this is already the transformed dataset, I cannot use it directly for the predict however.
extract from my full input dataset, the records that are specified in the get_config(X_train)
predict on this subset


gives me R2 of 1 ... I may be wrong but it seems the predict on train dataset is not working

**Comment by anne-leroy-T** [comment]
I do want to mention I do all this in order to plot by myself the plot-error diagram, that is not working when having targets low below zero :  issue with the plot error (#784), Anyway I think it would be interesting for everyone to easily retrieve the calculated values from create_model and tune_model

**Comment by pycaret** [comment]
@anne-leroy-T See the below example on how to do what you are trying to achieve:

```
from pycaret.datasets import get_data
data = get_data('boston')

from pycaret.regression import *
s = setup(data, target = 'medv')

dt = create_model('dt')

train_data = data.iloc[get_config('X_train').index.to_list()]
predict_model(dt, data=train_data)
``` 

![image](https://user-images.githubusercontent.com/58118658/98123839-668b8980-1e80-11eb-8960-887f0c8fbc06.png)

Hope this helps.

**Comment by anne-leroy-T** [comment]
I submitted the example you gave me and it explains my problem.

If you look at the R2 of the create_model(dt), it gives you 0.7154.
If you calculate the R2 from the label predicted, it gives you 0.9999

You can see by looking at your output that the prediction on the X_train is almost perfect and you get the y_predicted equal the real y-value. So this is definitely not the values that were calculated by the create_model.

I also tried not to use the get_config(X_train) directly because it is already transformed by the pipeline and removing the target column.
pytrain = get_config('X_train')
X_train = full_pycaret.loc[pytrain.index]
y_train = X_train['target']
X_train = X_train.drop(labels='target', axis=1)

on my own data. I had the tune_model that gave me a **0.20** of R2 which we agree is very bad ...
and the predict on this data gives me a R2 of **1**.


It seems like as the create_model has already seen the train data and the real value, it keeps this info and give it back in the predict.
i know this sounds strange but if you look at the example you sent me and the Label predicted versus the real value, you'll see there's something wrong.

**Comment by anne-leroy-T** [comment]
In fact, you don't even have to execute the previous code to see that something is wrong with the predict on train set : 
![image](https://user-images.githubusercontent.com/25195665/98225915-9ce70880-1f55-11eb-8826-ec655f3a30ff.png)

**Comment by joschkazj** [comment]
Hi,
I came here looking for an explanation on the mismatch between the results from tuning/cross-validation and the model plots.
Would you care to elaborate how the scores are computed, i.e. on which data (sub)sets?

In my case the R² **training** score in the residual plot does not resemble anything displayed during model comparison, or tuning. The R² **test** score, however, is at least consistent between residual and prediction error plot.
1. Am I correct in assuming the **test** score is computed on the hold-out set?
2. What is used to compute the **training** score?
![image](https://user-images.githubusercontent.com/1842005/98379489-a51f7080-2047-11eb-94d2-c4ee6284ac5e.png)
![image](https://user-images.githubusercontent.com/1842005/98379620-cf712e00-2047-11eb-9f5b-89c913b284b5.png)

**Comment by anne-leroy-T** [comment]
Hi "pycaret", As "joschkazj" confirms above there's a mismatch between the CV scores and the predict on train score.

Could you check this please ?

This issue can be checked with the boston script dataset you sent me either using the predict on get_config(X_train) or simply after creating the model, plotting the residuals where you can see that the R2 on train is not correct.
Please note the R2 on test is correct

![image](https://user-images.githubusercontent.com/25195665/98520191-00cd4200-2272-11eb-93d6-281a872b7807.png)

**Comment by joschkazj** [comment]
My colleague figured out what the two R² scores refer to: they are computed on the **entire train/test set**, respectively.
Note below how the two values of R² = 0.558 and 0.724 are reproduced:

![image](https://user-images.githubusercontent.com/1842005/98553436-e6aa5880-229f-11eb-8f85-1b35943aaa3d.png)
![image](https://user-images.githubusercontent.com/1842005/98553482-f32eb100-229f-11eb-8891-1d8c3fe65e11.png)

```
X_train, X_test = r.get_config("X_train"), r.get_config("X_test")
r.predict_model(model[0])
```

Model | MAE | MSE | RMSE | R2 | RMSLE | MAPE
| -- | -- | -- | -- | -- | -- | --
Huber Regressor | 2.3253 | 18.7118 | 4.3257 | **0.7238** | 0.1913 | 0.1542

```
trainset_results = r.predict_model(model[0], df_combined.loc[X_train.index, :])
metrics.r2_score(trainset_results["log_total_time"], trainset_results["Label"])
# result: 0.5584831668724606
```

**Comment by anne-leroy-T** [comment]
i'm not sure about that. Anyway if it was the case, the label : train R2 is misleading and my question is still valid : how do I get the predictions on the train.

Why am I not sure ?

Because when i get_config(X_train), which we agree is only the train set and not the test set, and then predict, I get the same result mentioned on your residual plot.

on the boston dataset, for a TREE algorithm, do the create_model('dt') for instance, predict on get_config(X_train) which we agree (I checked) only gives back the train dataset, as you advised me to do and then compute the R2, you will see it is incorrect compared to CV but the same as the residual plot. 
I do not have those issues with create_model('lr') I think

**Comment by anne-leroy-T** [comment]
Hello,

Do you allow me to close this issue and to open a new one with a more clear title and explanation please ; as my first question was answered but in fact generated a new issue and the title and flow of the comments could be misleading ?

**Comment by pycaret** [comment]
Thats a good idea. Please close this thread and open a new issue.
