### ISSUE TITLE
Documentation for automatic tuning

### ISSUE THREAD

**Issue by anneleroytotal** [pycaret/pycaret#803]
Is there a place where I can check for each algorithm which parameters and values are specified in the automatic tuning function ?
So I can check if I need to be more specific about some of these and make my own specified grid search.

Thanks a lot.

**Comment by Yard1** [comment]
`models(internal=True) ["Tune Grid"]` should give you what you need.

**Comment by anneleroytotal** [comment]
This is exactly what I need. Thanks a lot. I close the subject.
