### ISSUE TITLE
Unable to access Optimize_threshold results

### ISSUE THREAD

**Issue by ParthaKarthikeyan** [pycaret/pycaret#804]
Hi, 

I am using pycaret for a classification project. I am trying to optimize the model for my use case, but I am not able to return the optimize_results dataframe which consists of the Optimal Probability Threshold and the Optimized Cost Function. 

I tried using get_config() but that doesnt seem to work either. 

![image](https://user-images.githubusercontent.com/45417280/98011904-1946e380-1dbe-11eb-88e2-d535baff8b99.png)

**Comment by pycaret** [comment]
@ParthaKarthikeyan It's unclear why you are trying to access optimize_threshold using `get_config`. 

The output of `optimize_threshold` is a visual:

![image](https://user-images.githubusercontent.com/58118658/98127346-98065400-1e84-11eb-93ae-6b6954b2bf58.png)

Read the documentation here: http://pycaret.org/optimize-threshold/

**Comment by ParthaKarthikeyan** [comment]
I understand that it is a visual. 

I just want to extract the optimized probability threshold value. Is there any way to do that?

**Comment by pycaret** [comment]
@ParthaKarthikeyan Got it. I have just pushed a commit that will return the threshold value as numpy float. Can you please install the latest from the master and try? 

`pip install git+https://www.github.com/pycaret/pycaret@master`

Once you update it, `optimize_threshold` will return the numpy float containing the optimized threshold value.

Please let me know if this solves your problem.

Thanks.

**Comment by ParthaKarthikeyan** [comment]
@pycaret Thank you for the prompt reply and update. I have installed and tried to get the output. But the return still seems to be a part of the image. 

The output of the optimize_threshold still says NoneType. 

I want to be able to store that value such that I can dynamically call it in the Predict_model function, without having to go back and manually check the optimize threshold and input it in the predict function.

**Comment by Yard1** [comment]
@ParthaKarthikeyan @pycaret I think it should be `pip install --upgrade git+https://www.github.com/pycaret/pycaret@master` - without `--upgrade`, it won't overwrite the release PyCaret version.

**Comment by pycaret** [comment]
@Yard1 Thanks. 

@ParthaKarthikeyan I am closing this issue as we have tested and `optimize_threshold` returns an optimized value as a numpy array. In case you are still having a problem after upgrading pycaret to `2.2.1`, please feel free to open another issue.

Thanks
