### ISSUE TITLE
Iterative imputer with error

### ISSUE THREAD

**Issue by leonsolon** [pycaret/pycaret#807]
When I set the imputation_type to "iterative" I get an error:

TypeError: can't pickle dict_keys objects

Here's the notebook and data. Thanks!

[iterative_imputer.zip](https://github.com/pycaret/pycaret/files/5483747/iterative_imputer.zip)

**Comment by Yard1** [comment]
@leonsolon Thanks for reporting this issue. I just pushed commit f03581a4bbea9c70650f6ea5291c7b8ea25658b0 that should fix this issue. Could you run
`pip install --upgrade --user git+git://github.com/pycaret/pycaret.git` to install PyCaret's development version and try again?

**Comment by leonsolon** [comment]
Already? Working! Tested with default iterative imputer, knn and catboost: all good. 

You guys are fast, thanks a lot!
