### ISSUE TITLE
plot_model(kmeans) not working

### ISSUE THREAD

**Issue by DesiKeki** [pycaret/pycaret#808]
Pycaret version 2.2.0
Data:
40 clusters
300 features type: float

Hi Team,

The vanilla usage of plot_model(kmeans) is erroring out. 
I am getting following error:

```
/usr/local/lib/python3.6/dist-packages/pycaret/internal/tabular.py in cluster()
    5883 
    5884                     for i in pca_.Cluster:
->5885                         a = int(i.split()[1])
    5886                         clus_num.append(a)
    5887 

**AttributeError: 'float' object has no attribute 'split'**
```

The code I used is:

```
df_train = pd.concat([df_X, df_y], axis=1)
df_train.fillna(1, inplace=True)

clu1 = setup(data=df_train, ignore_features = ['intent'], session_id=123, log_experiment=True, log_plots = True, 
             experiment_name='test1')

kmeans = create_model('kmeans', num_clusters = 40)
plot_model(kmeans)
```

Am I missing something here?

**Comment by Yard1** [comment]
Thanks for the report, will look into it.

**Comment by shapatel13** [comment]
Hello I am having the same issue.

**Comment by DesiKeki** [comment]
Sure @Yard1 
Please find the dataset attached.
[data_pycaret_plot_issue.zip](https://github.com/pycaret/pycaret/files/5491634/data_pycaret_plot_issue.zip)


> Thanks for the report, will look into it. Is it possible for you to share the dataset?

**Comment by Yard1** [comment]
@DesiKeki Hey, I can't replicate this. Is it possible for you to share an entire, reproducible notebook?

**Comment by shapatel13** [comment]
https://colab.research.google.com/drive/1tNzRAPhUZaJQV1qBL-BRK8If_E8zNsPq?usp=sharing

**Comment by shapatel13** [comment]
![image](https://user-images.githubusercontent.com/50153301/98409672-46ef8f00-2041-11eb-8596-80fa2aa5ed81.png)

**Comment by shapatel13** [comment]
I am still having the same issue, I am using the new version

pip install --upgrade --user git+git://github.com/pycaret/pycaret.git

**Comment by Yard1** [comment]
Thank you, I will look into it.

**Comment by Yard1** [comment]
@shapatel13 Hey, I can't access the colab notebook. Could you make sure everyone can view the link? Thanks.

**Comment by shapatel13** [comment]
hello, here is a link where you can edit/acces

https://colab.research.google.com/drive/1tNzRAPhUZaJQV1qBL-BRK8If_E8zNsPq?usp=sharing

**Comment by Yard1** [comment]
@shapatel13 Would it be possible to also share the dataset? Thanks.

**Comment by shapatel13** [comment]
https://drive.google.com/file/d/1VwlYP2xZGc4zmbE4mGBXMfekAxGCXk69/view?usp=sharing

**Comment by Yard1** [comment]
@shapatel13 @DesiKeki I have pushed commit 40ed93e836451ffcfbfd60ae8e1498875dc85da3 which should fix this issue. Can you install PyCaret through `pip install --upgrade --user git+git://github.com/pycaret/pycaret.git` again and see if it solves the problem for you?

**Comment by shapatel13** [comment]
Thank you its working now.

**Comment by DesiKeki** [comment]
Thanks @Yard1 
Working now!

**Comment by parthskansara** [comment]
Similar issue, Google Colab cell gets stuck for `plot_model(iforest)`.  

Already tried reinstalling using `pip install --upgrade --user git+git://github.com/pycaret/pycaret.git` but still stuck.

**Comment by dvl00** [comment]
same plot_model does not seem to work on colab
