### ISSUE TITLE
tune_model function of clustering not accepting estimator argument

### ISSUE THREAD

**Issue by DesiKeki** [pycaret/pycaret#809]
Pycaret Version: 2.2.0

Hi Team,

The tune_model function of clustering is erroring out at passing estimator argument:

```
----> 1 tuned_kmeans = tune_model(model = 'kmeans', supervised_target = 'intent', estimator = 'ridge')

TypeError: tune_model() got an unexpected keyword argument 'estimator'
```

Is the name of the argument changed?

**Comment by Yard1** [comment]
It's `supervised_estimator` since 2.2.

**Comment by pycaret** [comment]
@DesiKeki The parameter `estimator` has been renamed to `supervised_estimator`. 

![image](https://user-images.githubusercontent.com/58118658/98127503-c7b55c00-1e84-11eb-89e4-6bc797b91e1c.png)

Please see documentation here:  https://pycaret.readthedocs.io/en/latest/api/clustering.html
