### ISSUE TITLE
Pycaret clustering, how does it identify the target, so it knows to ignore?  The previous version had a supervised target option.  

### ISSUE THREAD

**Issue by shapatel13** [pycaret/pycaret#811]
Hello, I noted in the new version of pycaret, there is no supervised target option in the clustering.  How will it recognize the target, so it can ignore it?  I am trying to cluster with k means first and then do classification after.  Thank you

**Comment by Yard1** [comment]
You should pass the name of the target column to `ignore_features` argument in Clustering's `setup()`.

**Comment by shapatel13** [comment]
Ok, thank you.  I am also having issues performing clustering when I choose
iterative as my imputing strategy.  Any thoughts?

**Comment by shapatel13** [comment]
I am having issues using iterative imputer for clustering.  The error I get below.  

UnboundLocalError                         Traceback (most recent call last)
<ipython-input-18-b471737b2079> in <module>()
----> 1 exp_clu = setup(df,normalize=True, normalize_method='minmax',imputation_type='iterative',ignore_features=['target'])

1 frames
/usr/local/lib/python3.6/dist-packages/pycaret/internal/tabular.py in setup(data, target, ml_usecase, available_plots, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, transform_target, transform_target_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile, display)
   1031 
   1032         iterative_imputer_models_globals = globals().copy()
-> 1033         iterative_imputer_models_globals["y_train"] = y_before_preprocess
   1034         iterative_imputer_models_globals["X_train"] = X_before_preprocess
   1035         iterative_imputer_classification_models = {

UnboundLocalError: local variable 'y_before_preprocess' referenced before assignment

**Comment by Yard1** [comment]
Thanks for the report, will look into it.

**Comment by Yard1** [comment]
@shapatel13 I just pushed commit 6e9f758531f4505a135360cd53983a2b98130e1c that should fix this issue. Could you run
`pip install --upgrade --user git+git://github.com/pycaret/pycaret.git` to install PyCaret's development version, restart your notebook and try again?

**Comment by pycaret** [comment]
@shapatel13 You can still use `supervised_target` parameter available in the `tune_model` for `pycaret.clustering`. 

![image](https://user-images.githubusercontent.com/58118658/98394617-0ab03480-2029-11eb-9937-d8aa5de27a52.png)

See this link for more info: https://pycaret.readthedocs.io/en/latest/api/clustering.html#pycaret.clustering.tune_model

`ignore_features` will ignore the particular column throughout including from the `create_model` function that is used to train cluster models.

**Comment by pycaret** [comment]
@shapatel13 Is the problem resolved?

**Comment by shapatel13** [comment]
Hi I apologize, yes it is resolved .  Thank you again
