### ISSUE TITLE
Unable to load_config

### ISSUE THREAD

**Issue by linhy1993** [pycaret/pycaret#812]
Hello guys,

I am able to save config as pkl file use save_config, however, when I want to load the config by using load_config, it return empty.
I check `/pycaret/internal/tabular.py`, in line 9492 `r = pycaret.internal.utils.load_config(file_name, globals())` but it doesn't return anything to r in function `pycaret.internal.utils.load_config()`

Could you check that? Thanks in advance.

**Comment by Yard1** [comment]
`load_config()` is not supposed to return anything. It sets global variables that `setup()` would set up normally, allowing you to use PyCaret without calling `setup()` again.

**Comment by linhy1993** [comment]
OK, so I can create the model directly? 
I will close the issue. Thanks

**Comment by Yard1** [comment]
Yeah you can just carry on as you would after calling `setup()`.
