### ISSUE TITLE
Logging, Pickling, and Graphing Errors

### ISSUE THREAD

**Issue by shambhavithakur** [pycaret/pycaret#814]
Hi,

Thanks for conceptualizing and building the PyCaret library. PyCaret can help us quickly identify relevant models and parameters at the beginning of a project. It is also good for implementing ML workflows end to end. What adds to its appeal is that its documentation is concise and coherent. 

I discovered PyCaret recently, and I am delighted that PyCaret 2.2  includes many of the features that I require. However, it also produced a few errors when I ran it in Google Colab.

I installed PyCaret in Colab using the following command: `pip install pycaret[full]`, and the errors that I came across were related to logging, pickling, and graphing.

 Here are descriptions of some of those errors:

- The `setup()` function runs all right when the `log_experiment` parameter is set to `False`. But when the parameter is enabled, an error occurs.: `TypeError: can't pickle dict_keys objects`.
 
> Note that I had reset the index of the dataframe that I assigned to `setup()`.

- When I tried to obtain predictions on unseen data, there were a couple of errors. 

    - Command used: `pred_unseen = predict_model(final_model, data=data_test)`
    - Errors returned:
        - `TypeError: can't pickle dict_keys objects`
        - `ValueError: Pipeline not found`
  
>  **Note**: I had used `finalize_model` to train the model on the training+validation data. Is there an additional function that can add imputers and other pipeline elements to a finalized model? I discovered a function named [`save_experiment`](https://pycaret.org/save-experiment/) a few moments ago. This function apparently bundles multiple models and transformers, so it might not serve the purpose.

- Some of the graphing functions, such as `evaluate_model`, caused Colab notebooks to stop responding.

**Comment by Yard1** [comment]
Pickling issues should be fixed on master. Could you run
`pip install --upgrade --user git+git://github.com/pycaret/pycaret.git` to install PyCaret's development version and try again?

**Comment by shambhavithakur** [comment]
Thanks, Antoni. The errors have been resolved in the development version of PyCaret.

**Comment by Yard1** [comment]
I'll take a look at the other things too. Not sure if anything can be done about `evaluate_model`, it is a very intensive function, but we can probably tweak how `profile` works.

**Comment by Yard1** [comment]
@shambhavithakur You should be able to pass arguments to the `ProfileReport` using `profile_kwargs` argument in `setup()` which I have just added in commit 74ad34d26d734ea8ca4bd0806b4aa410cf60be40.
