### ISSUE TITLE
Feature importance list/plotting feature importance

### ISSUE THREAD

**Issue by fjehlik** [pycaret/pycaret#815]
Is there a way that one can adjust the length of the plot_model(model, plot='feature') figure output? In other words, select the number of  features one would like on the plot (increase or decrease)? Additionally, is there a way to access the entire feature importance list results once it has been calculated? Apologies if I have missed it, I just haven't found a way to do either of these.

**Comment by Yard1** [comment]
You can do `plot='feature_all'` to get a plot with all features. Sadly, in the current version, it's either top 10 or all. You can get the feature importances from the models themselves - usually it's either `coef_` or `feature_importances_` attributes. Refer to sklearn/other model library documentation.

**Comment by pycaret** [comment]
@fjehlik If you are using a model that provides coefficient value or built-in feature importance like Random Forest, you can simply call off the attribute from the trained model. For example:

```
from pycaret.datasets import get_data
data = get_data('juice')

from pycaret.classification import *
s = setup(data, target = 'Purchase')

lr = create_model('lr')
plot_model(lr, plot = 'feature')

# this is how you can recreate the table
import pandas as pd
pd.DataFrame({'Feature': get_config('X_train').columns, 'Value' : abs(lr.coef_[0])}).sort_values(by='Value', ascending=False)
```
![image](https://user-images.githubusercontent.com/58118658/98395398-308a0900-202a-11eb-98f0-5b7a6dadc0d6.png)
 
![image](https://user-images.githubusercontent.com/58118658/98395387-2b2cbe80-202a-11eb-9827-cc12154cd76e.png)

Hope this helps.

**Comment by fjehlik** [comment]
Excellent and thank you both. This addresses what I was looking for and appreciate your time~

**Comment by pycaret** [comment]
Thanks @fjehlik

**Comment by stulrajtermatej** [comment]
Hi, any example of regression?

**Comment by ifyoungnet** [comment]
@stulrajtermatej 
hi, 
For regression, just change the 
pd.DataFrame({'Feature': get_config('X_train').columns, 'Value' : abs(lr.coef_[0])}).sort_values(by='Value', ascending=False)
to
pd.DataFrame({'Feature': get_config('X_train').columns, 'Value' : abs(lr.feature_importances_)}).sort_values(by='Value', ascending=False)
