### ISSUE TITLE
Evaluate model performance and obtain all the metrics and plots on unseen data?

### ISSUE THREAD

**Issue by gm039** [pycaret/pycaret#818]
Hi,

 I would also like to ask what is the recommended way out for saving and reloading the model and testing later on unseen data.
I want to obtain all the metrics and plots on unseen data.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#Save the model
save_model(tuned_model_best,'tuned_model_best')
save_config('tuned_model_best_config.pkl')
import pycaret.classification import *

#Load the saved model later  for prediction on unseen data
load_config('tuned_model_best_config.pkl')
Loaded_model=load_model('tuned_model_best')

#Predict on unseen data
pred_unseen = predict_model(Loaded_model,data_unseen)

#Evaluate performance
evaluate_model(Loaded_model)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Using the above lines, I can successfully load the model and predict it as well. I want to know how to obtain all the metrics and plots on unseen data?

**Comment by Yard1** [comment]
You can get the last displayed dataframe using `pull()`:
```python
pred_unseen = predict_model(Loaded_model,data_unseen)
results = pull()
```

You can create and save individual plots with `plot_model(model, save=True, plot="PLOTNAME")`.

**Comment by pycaret** [comment]
@gm039 Is this issue resolved? If yes, can you please close the issue.

**Comment by gm039** [comment]
Thanks for the suggestion.

plot_model(model, save=True, plot="PLOTNAME")

The above command will give the plot for the holdout data. How to obtain them for the data_unseen?

**Comment by Yard1** [comment]
That's not possible if the unseen data is missing the true target values. However, if it is not missing those, you can use it as the holdout set by specyfing `test_data=data_unseen` in `setup()` and then plot.

**Comment by pranaymodukuru** [comment]
> You can get the last displayed dataframe using `pull()`:
> 
> ```python
> pred_unseen = predict_model(Loaded_model,data_unseen)
> results = pull()
> ```
> 
> You can create and save individual plots with `plot_model(model, save=True, plot="PLOTNAME")`.

Gives me "NameError: name 'display_container' is not defined" when calling "results = pull()"

**Comment by Yard1** [comment]
You need to run `setup()` first in order for `pull()` to work.

**Comment by garyee** [comment]
@pranaymodukuru the error could also be related to #1100

**Comment by gm039** [comment]
> That's not possible if the unseen data is missing the true target values. However, if it is not missing those, you can use it as the holdout set by specyfing `test_data=data_unseen` in `setup()` and then plot.

Thanks @Yard1 . I am worried that my data might get
