### ISSUE TITLE
AttributeError: probability estimates are not available for loss='hinge'

### ISSUE THREAD

**Issue by gm039** [pycaret/pycaret#819]
Hi,
I encountered a new error in PyCaret 2.2. Reporting it FYI. 

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_scorer.py in _cached_call(cache, estimator, method, *args, **kwargs)
     55     try:
---> 56         return cache[method]
     57     except KeyError:

KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
19 frames
<ipython-input-46-6a561903b62e> in <module>()
     71   print('QDA: Iteration Running', Rep)
     72 
---> 73   Model_svm = create_model('svm', fold = 5)
     74   tuned_model_svm_best = tune_model(Model_svm, fold = 5,choose_better=True,n_iter = 100, optimize = Optimizer_nm) #Return best model
     75   KFold=pull()

/usr/local/lib/python3.6/dist-packages/pycaret/classification.py in create_model(estimator, fold, round, cross_validation, fit_kwargs, groups, verbose, **kwargs)
    895         groups=groups,
    896         verbose=verbose,
--> 897         **kwargs,
    898     )
    899 

/usr/local/lib/python3.6/dist-packages/pycaret/internal/tabular.py in create_model_supervised(estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, verbose, system, X_train_data, y_train_data, metrics, display, **kwargs)
   3087             n_jobs=n_jobs,
   3088             return_train_score=False,
-> 3089             error_score=0,
   3090         )
   3091         model_fit_end = time.time()

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py in cross_validate(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, return_train_score, return_estimator, error_score)
    246             return_times=True, return_estimator=return_estimator,
    247             error_score=error_score)
--> 248         for train, test in cv.split(X, y, groups))
    249 
    250     zipped_scores = list(zip(*scores))

/usr/local/lib/python3.6/dist-packages/joblib/parallel.py in __call__(self, iterable)
   1046             # remaining jobs.
   1047             self._iterating = False
-> 1048             if self.dispatch_one_batch(iterator):
   1049                 self._iterating = self._original_iterator is not None
   1050 

/usr/local/lib/python3.6/dist-packages/joblib/parallel.py in dispatch_one_batch(self, iterator)
    864                 return False
    865             else:
--> 866                 self._dispatch(tasks)
    867                 return True
    868 

/usr/local/lib/python3.6/dist-packages/joblib/parallel.py in _dispatch(self, batch)
    782         with self._lock:
    783             job_idx = len(self._jobs)
--> 784             job = self._backend.apply_async(batch, callback=cb)
    785             # A job can complete so quickly than its callback is
    786             # called before we get here, causing self._jobs to

/usr/local/lib/python3.6/dist-packages/joblib/_parallel_backends.py in apply_async(self, func, callback)
    206     def apply_async(self, func, callback=None):
    207         """Schedule a func to be run"""
--> 208         result = ImmediateResult(func)
    209         if callback:
    210             callback(result)

/usr/local/lib/python3.6/dist-packages/joblib/_parallel_backends.py in __init__(self, batch)
    570         # Don't delay the application, to avoid keeping the input
    571         # arguments in memory
--> 572         self.results = batch()
    573 
    574     def get(self):

/usr/local/lib/python3.6/dist-packages/joblib/parallel.py in __call__(self)
    261         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    262             return [func(*args, **kwargs)
--> 263                     for func, args, kwargs in self.items]
    264 
    265     def __reduce__(self):

/usr/local/lib/python3.6/dist-packages/joblib/parallel.py in <listcomp>(.0)
    261         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    262             return [func(*args, **kwargs)
--> 263                     for func, args, kwargs in self.items]
    264 
    265     def __reduce__(self):

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py in _fit_and_score(estimator, X, y, scorer, train, test, verbose, parameters, fit_params, return_train_score, return_parameters, return_n_test_samples, return_times, return_estimator, error_score)
    558     else:
    559         fit_time = time.time() - start_time
--> 560         test_scores = _score(estimator, X_test, y_test, scorer)
    561         score_time = time.time() - start_time - fit_time
    562         if return_train_score:

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py in _score(estimator, X_test, y_test, scorer)
    605         scores = scorer(estimator, X_test)
    606     else:
--> 607         scores = scorer(estimator, X_test, y_test)
    608 
    609     error_msg = ("scoring must return a number, got %s (%s) "

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_scorer.py in __call__(self, estimator, *args, **kwargs)
     86             if isinstance(scorer, _BaseScorer):
     87                 score = scorer._score(cached_call, estimator,
---> 88                                       *args, **kwargs)
     89             else:
     90                 score = scorer(estimator, *args, **kwargs)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_scorer.py in _score(self, method_caller, clf, X, y, sample_weight)
    245 
    246         y_type = type_of_target(y)
--> 247         y_pred = method_caller(clf, "predict_proba", X)
    248         if y_type == "binary":
    249             if y_pred.shape[1] == 2:

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_scorer.py in _cached_call(cache, estimator, method, *args, **kwargs)
     56         return cache[method]
     57     except KeyError:
---> 58         result = getattr(estimator, method)(*args, **kwargs)
     59         cache[method] = result
     60         return result

/usr/local/lib/python3.6/dist-packages/sklearn/utils/metaestimators.py in __get__(self, obj, type)
    111                     continue
    112                 else:
--> 113                     getattr(delegate, self.attribute_name)
    114                     break
    115             else:

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py in predict_proba(self)
   1021         http://jmlr.csail.mit.edu/papers/volume2/zhang02c/zhang02c.pdf
   1022         """
-> 1023         self._check_proba()
   1024         return self._predict_proba
   1025 

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_stochastic_gradient.py in _check_proba(self)
    982         if self.loss not in ("log", "modified_huber"):
    983             raise AttributeError("probability estimates are not available for"
--> 984                                  " loss=%r" % self.loss)
    985 
    986     @property

AttributeError: probability estimates are not available for loss='hinge'

**Comment by Yard1** [comment]
Is it possible for you to share the notebook or code that causes this error?
