### ISSUE TITLE
Please help resolve

### ISSUE THREAD

**Issue by osabobo** [pycaret/pycaret#820]
from pycaret.utils import check_metric
check_metric(unseen_predictions.price.ast, unseen_predictions['Label'], 'MSE')
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-33-5d499e1b50e9> in <module>
      1 from pycaret.utils import check_metric
----> 2 check_metric(unseen_predictions.price, unseen_predictions['Label'], 'MSE')

~\anaconda3\envs\pycaret\lib\site-packages\pycaret\utils.py in check_metric(actual, prediction, metric, round)
     92 
     93 
---> 94     return result
     95 
     96 

UnboundLocalError: local variable 'result' referenced before assignment

**Comment by Yard1** [comment]
It appears that your version of PyCaret is outdated. Please run:
```
pip uninstall pycaret
pip uninstall pycaret-nightly
pip install --upgrade pycaret
```

to install the latest version.
