### ISSUE TITLE
Error running examples

### ISSUE THREAD

**Issue by kusumy** [pycaret/pycaret#821]
trying to run an example located at (using pycaret v2.2):

1. https://github.com/pycaret/pycaret/blob/master/examples/Pycaret_2.1_Regression_EmployeePerformance.ipynb

    There is an error message after compare_models:

    _LinAlgError: SVD did not converge_

2.  https://github.com/pycaret/pycaret/blob/master/examples/TimeSeries_Forecasting.ipynb

    There is an error message after compare_models:

    _ValueError: The Box-Cox transformation can only be applied to strictly positive data_

3.  Calling predict_models() before finalize_model() shows error message:

     NotFittedError: This RandomForestRegressor instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
   
     Same error shows if i use other models.

The errors did not happen on pycaret v2.1.2

I am studying pyCaret to use if as a tool for  timeseries forecasting.

Please advise.

**Comment by kusumy** [comment]
Error number 3 was solved by using latest development version.

**Comment by pycaret** [comment]
@kusumy Error no 1 should also be gone away. Can you check?

**Comment by kusumy** [comment]
> @kusumy Error no 1 should also be gone away. Can you check?

I have to run cell containing compare_models() twice to eliminate the error no. 2.

**Comment by pycaret** [comment]
@kusumy All official tutorials are now updated and they will work with the `pycaret>2.0` version.

**Comment by kusumy** [comment]
Great news, thank you
