### ISSUE TITLE
tune model causing error

### ISSUE THREAD

**Issue by hayilmaz** [pycaret/pycaret#822]
tuned_kmeans = tune_model(model = 'kmeans', supervised_target = 'result')

 IndexError: list index out of range 
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-25-71f34533b05f> in <module>
----> 1 tuned_kmeans = tune_model(model = 'kmeans', supervised_target = 'result')

/opt/anaconda3/envs/pycaret/lib/python3.7/site-packages/pycaret/clustering.py in tune_model(model, supervised_target, estimator, optimize, custom_grid, fold, verbose)
   3517         best_model = master[ival]
   3518         best_model_df = master_df[ival]
-> 3519         best_model_tt = model_fit_time_list[ival]
   3520 
   3521         logger.info("Rendering Visual")

IndexError: list index out of range

**Comment by Yard1** [comment]
Can you share the code/notebook that caused this?

**Comment by Yard1** [comment]
@hayilmaz It appears that your version of PyCaret is outdated. Please run:
```
pip uninstall pycaret
pip uninstall pycaret-nightly
pip install --upgrade pycaret
```

to install the latest version.
