### ISSUE TITLE
Tune Function degrades model accuracy

### ISSUE THREAD

**Issue by aniketkumar88** [pycaret/pycaret#824]
Hi Team,

Tune_model function degrades model accuracy even though after trying multiple iterations. Its not happening with 1 datset, but happens with most of them. Is there any work around or I am missing something ?

Thanks

**Comment by Yard1** [comment]
Tuning is not guaranteed to always choose better hyperparameters. You can add `choose_better=True` to the arguments to make sure that the original model will be returned if it's better.

**Comment by pycaret** [comment]
@aniketkumar88 As @Yard1 mentioned tuning does not guarantee improved performance. If you want, you can use the `choose_better` parameter inside the `tune_model` function to get the original model back. 

There is nothing that can be done here. I am closing this issue.
