### ISSUE TITLE
Ignore Feature removing the column from data

### ISSUE THREAD

**Issue by aniketkumar88** [pycaret/pycaret#827]
Hi Team,

I see the that ignore_features function is removing the column from the data. I believe this function ignores the column while training or prediction rather than removing the column . 

Is this a bug ? Or if there is any other way to keep the column as it but do not consider as a feature for training ?

Currently ignore function removes the column from test data / predicted data set as well.

**Comment by Yard1** [comment]
Yes, it indeed removes the column. It's not possible to implement this feature otherwise.

**Comment by aniketkumar88** [comment]
But in previous version it di not use to remove the columns .

**Comment by Yard1** [comment]
Are you sure about that? The implementation of that feature has not changed much.

**Comment by aniketkumar88** [comment]
I am sure about that. As I have been using this feature to ignore few of my variables in prediction datset. But that did not remove my variable.

**Comment by Yard1** [comment]
Can you show me the code you used? You are talking about `predict_model`, yes?

**Comment by aniketkumar88** [comment]
Yes predict_model removes the ignored variables from new data set.

**Comment by pycaret** [comment]
@Yard1 That's true indeed. I am sharing the Notebook with you by email. Let's fix this in the next sprint.

**Comment by Yard1** [comment]
I have pushed commit 707d3418481365a8411cdec6a56e354ce091336e which should fix this issue.

**Comment by aniketkumar430** [comment]
Thanks alot for considering this issue. This will help Pycaret and end users like us to scale and rely upon Pycaret capabilities and features.

**Comment by pycaret** [comment]
@aniketkumar430 Can you test this?

**Comment by aniketkumar430** [comment]
Thanks for fixing this ! It works fine in  pycaret-nightly-2.2.1.dev1605659215 version.
