### ISSUE TITLE
BrokenProcessPool

### ISSUE THREAD

**Issue by graillou** [pycaret/pycaret#828]
Hello,
I've tried pyCaret with a DataFrame having the following features :
puissance_moyenne     float32
nb_ampli                int32
nb_sect                 int32
Zone5                category
Trafic3GVoix          float32
Trafic2GData          float32
Trafic2GVoix          float32
nb_bande_freq           int32
Trafic4GData          float32
nb_bande_4G             int32
Trafic3GData          float32
Trafic4GVoix          float32
nb_du                   int32
nb_baie                 int32
z_arcep              category
nb_bande_3G             int32
nb_trx                  int32

I'va also tried without the category features, but I've got the same following issues.
When I do a compare_models, with best = compare_models(include = ['knn','rf','et'],sort = 'MAE'), nothing is displayed.
So I've tried a create_model with et = create_model('et') (or with rf, and I've got the same answer), I've got an issue, with the following last message:
"BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable."

I haven't found any issue like that, so I hope not to bother you.
Thanks for this great lib

**Comment by pycaret** [comment]
@graillou Can you please upload the logs file here?

`logs.log` is generated automatically in the folder your Notebook is.

**Comment by graillou** [comment]
Hello @pycaret 

please find the logs, thanks in advance

Processing:
		
		
Initiated 	. . . . . . . . . . . . . . . . . . 	16:00:31
Status 	. . . . . . . . . . . . . . . . . . 	Fitting 10 Folds
Estimator 	. . . . . . . . . . . . . . . . . . 	Random Forest Regressor
	MAE 	MSE 	RMSE 	R2 	RMSLE 	MAPE

---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
'''
Traceback (most recent call last):
  File "C:\Base\WinPy\WPy64-3810\python-3.8.1.amd64\lib\site-packages\joblib\externals\loky\process_executor.py", line 391, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\Base\WinPy\WPy64-3810\python-3.8.1.amd64\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "C:\Base\WinPy\WPy64-3810\python-3.8.1.amd64\lib\site-packages\ipyparallel\serialize\codeutil.py", line 24, in code_ctor
    return types.CodeType(*args)
TypeError: an integer is required (got type bytes)
'''

The above exception was the direct cause of the following exception:

BrokenProcessPool                         Traceback (most recent call last)
<ipython-input-344-5b7c95f350b2> in <module>
----> 1 rf = create_model('rf')

~\AppData\Roaming\Python\Python38\site-packages\pycaret\regression.py in create_model(estimator, fold, round, cross_validation, fit_kwargs, groups, verbose, **kwargs)
    885     """
    886 
--> 887     return pycaret.internal.tabular.create_model_supervised(
    888         estimator=estimator,
    889         fold=fold,

~\AppData\Roaming\Python\Python38\site-packages\pycaret\internal\tabular.py in create_model_supervised(estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, verbose, system, X_train_data, y_train_data, metrics, display, **kwargs)
   3077 
   3078         model_fit_start = time.time()
-> 3079         scores = cross_validate(
   3080             pipeline_with_model,
   3081             data_X,

C:\Base\WinPy\WPy64-3810\python-3.8.1.amd64\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

C:\Base\WinPy\WPy64-3810\python-3.8.1.amd64\lib\site-packages\sklearn\model_selection\_validation.py in cross_validate(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, return_train_score, return_estimator, error_score)
    240     parallel = Parallel(n_jobs=n_jobs, verbose=verbose,
    241                         pre_dispatch=pre_dispatch)
--> 242     scores = parallel(
    243         delayed(_fit_and_score)(
    244             clone(estimator), X, y, scorers, train, test, verbose, None,

C:\Base\WinPy\WPy64-3810\python-3.8.1.amd64\lib\site-packages\joblib\parallel.py in __call__(self, iterable)
   1015 
   1016             with self._backend.retrieval_context():
-> 1017                 self.retrieve()
   1018             # Make sure that we get a last message telling us we are done
   1019             elapsed_time = time.time() - self._start_time

C:\Base\WinPy\WPy64-3810\python-3.8.1.amd64\lib\site-packages\joblib\parallel.py in retrieve(self)
    907             try:
    908                 if getattr(self._backend, 'supports_timeout', False):
--> 909                     self._output.extend(job.get(timeout=self.timeout))
    910                 else:
    911                     self._output.extend(job.get())

C:\Base\WinPy\WPy64-3810\python-3.8.1.amd64\lib\site-packages\joblib\_parallel_backends.py in wrap_future_result(future, timeout)
    560         AsyncResults.get from multiprocessing."""
    561         try:
--> 562             return future.result(timeout=timeout)
    563         except LokyTimeoutError:
    564             raise TimeoutError()

C:\Base\WinPy\WPy64-3810\python-3.8.1.amd64\lib\concurrent\futures\_base.py in result(self, timeout)
    437                 raise CancelledError()
    438             elif self._state == FINISHED:
--> 439                 return self.__get_result()
    440             else:
    441                 raise TimeoutError()

C:\Base\WinPy\WPy64-3810\python-3.8.1.amd64\lib\concurrent\futures\_base.py in __get_result(self)
    386     def __get_result(self):
    387         if self._exception:
--> 388             raise self._exception
    389         else:
    390             return self._result

BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

​

**Comment by pycaret** [comment]
@graillou Thanks for sharing. This is the traceback message. What we need is a file called `logs.log` that is automatically generated in the folder your Notebook or py file is. Can you upload the `logs.log` here?

@Yard1 FYI.

**Comment by graillou** [comment]
@pycaret sorry, didn't get. Please find the log fil
[logs.log](https://github.com/pycaret/pycaret/files/5547325/logs.log)

**Comment by Yard1** [comment]
@graillou @pycaret This doesn't seem to be an issue with PyCaret itself.

@graillou Could you try passing `n_jobs=1` in `setup()`?

**Comment by graillou** [comment]
Thanks, it works well now, for the different function I've tried (compare_models, create_models, tune_models). I'll check the others.
I don't know if you need it, but in case, the logs file.
[logs.log](https://github.com/pycaret/pycaret/files/5554189/logs.log)
If you have the time, can you explain me, or redirect me to a link, to understand what n_jobs=1 has changed?

Thanks again

**Comment by Yard1** [comment]
Nothing has changed with PyCaret in this regard. You seem to have some sort of an issue when processes are ran in parallel, unrelated to PyCaret.

**Comment by pycaret** [comment]
@graillou @Yard1 

If I am not wrong this is a very old issue with loky library (you will find it if you google it). This issue is mostly seen in scenarios with >30 cores in a machine.

**Comment by graillou** [comment]
@pycaret thanks for the explanation.
Every function I've tested works well now. Thanks a lot for your help
