### ISSUE TITLE
ValueError: DataFrame constructor not properly called!

### ISSUE THREAD

**Issue by gm039** [pycaret/pycaret#831]
Hi,

I am getting an error "ValueError: DataFrame constructor not properly called!". 
The same error goes away when I use classical feature selection instead of boruta.

Any suggestions?

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-85c65aed1211> in <module>()
     11                   use_gpu =True,
     12                   fix_imbalance =True,
---> 13                   fix_imbalance_method= SMOTE(),
     14                   #verbose=False
     15                   )

8 frames
/usr/local/lib/python3.6/dist-packages/pycaret/classification.py in setup(data, target, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs)
    652         verbose=verbose,
    653         profile=profile,
--> 654         profile_kwargs=profile_kwargs,
    655     )
    656 

/usr/local/lib/python3.6/dist-packages/pycaret/internal/tabular.py in setup(data, target, ml_usecase, available_plots, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, transform_target, transform_target_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs, display)
   1303             test_data = pd.concat([X_test, y_test], axis=1)
   1304 
-> 1305         train_data = prep_pipe.fit_transform(train_data)
   1306         # workaround to also transform target
   1307         dtypes.final_training_columns.append(target)

/usr/local/lib/python3.6/dist-packages/sklearn/pipeline.py in fit_transform(self, X, y, **fit_params)
    365         """
    366         fit_params_steps = self._check_fit_params(**fit_params)
--> 367         Xt = self._fit(X, y, **fit_params_steps)
    368 
    369         last_step = self._final_estimator

/usr/local/lib/python3.6/dist-packages/sklearn/pipeline.py in _fit(self, X, y, **fit_params_steps)
    294                 message_clsname='Pipeline',
    295                 message=self._log_message(step_idx),
--> 296                 **fit_params_steps[name])
    297             # Replace the transformer of the step with the fitted
    298             # transformer. This is necessary when loading the transformer

/usr/local/lib/python3.6/dist-packages/joblib/memory.py in __call__(self, *args, **kwargs)
    350 
    351     def __call__(self, *args, **kwargs):
--> 352         return self.func(*args, **kwargs)
    353 
    354     def call_and_shelve(self, *args, **kwargs):

/usr/local/lib/python3.6/dist-packages/sklearn/pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    738     with _print_elapsed_time(message_clsname, message):
    739         if hasattr(transformer, 'fit_transform'):
--> 740             res = transformer.fit_transform(X, y, **fit_params)
    741         else:
    742             res = transformer.fit(X, y, **fit_params).transform(X)

/usr/local/lib/python3.6/dist-packages/pycaret/internal/preprocess.py in fit_transform(self, data, y)
   2760             data frame
   2761     """
-> 2762         self.fit(data)
   2763         return self.transform(data)
   2764 

/usr/local/lib/python3.6/dist-packages/pycaret/internal/preprocess.py in fit(self, data, y)
   2572         # self.data_c = self.data1.T.drop_duplicates()
   2573         # self.data1 = self.data_c.T
-> 2574         corr = pd.DataFrame(np.corrcoef(self.data1.T))
   2575         corr.columns = self.data1.columns
   2576         corr.index = self.data1.columns

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    527         else:
    528             if index is None or columns is None:
--> 529                 raise ValueError("DataFrame constructor not properly called!")
    530 
    531             if not dtype:

ValueError: DataFrame constructor not properly called!

![image](https://user-images.githubusercontent.com/50217085/98908741-e0c69a00-248e-11eb-83c4-4100ee76e8fb.png)

![image](https://user-images.githubusercontent.com/50217085/98908795-f4720080-248e-11eb-94dc-36d6bf3bcf6e.png)

**Comment by Yard1** [comment]
@g0lemXIV FYI. Can you look into this? You know Boruta best.

**Comment by pycaret** [comment]
@gm039 Can you share the dataset and Notebook for troubleshooting?

**Comment by gm039** [comment]
Sure,

Please find the attached.


Thanks & Regards
Gourav Modanwal

**Comment by gm039** [comment]
Hi @pycaret @g0lemXIV 

Any updates?

**Comment by pycaret** [comment]
@g0lemXIV Hi. Did you get a chance to look into this?

**Comment by ngupta23** [comment]
Let's leave this open since it is marked as bug.
