### ISSUE TITLE
Showing original target name rather than encoded target in plot_model for classification

### ISSUE THREAD

**Issue by sparvaneh** [pycaret/pycaret#840]
**Is your feature request related to a problem? Please describe.**
This is a feature request. plot_model for confusion_matrix and error in classification will use integer target labels rather than original labels.

**Describe the solution you'd like**
Rather than showing 0 and 1 for binary classification, it shows original target labels (sepsis/nonsepsis). 

**Describe alternatives you've considered**
For having the original target labels, I am plotting the confusion matrix and error plot separate from Pycaret library.
Since **encoded_labels** parameter is implemented in predict_model, it would be nice to include this parameter for related plots in plot_model

**Additional context**

**Comment by ngupta23** [comment]
Lets leave it open since it is marked as an enhancement.

**Comment by soerendip** [comment]
This would be great. The encoded labels are not very helpful for interpreting which classes are mixed up.

**Comment by yeli7068** [comment]
Thanks any efforts to solve this issue in advance.

It has been a year passed since this issue has been opened up. This would be very helpful for communicating with others. 

Plz !!

**Comment by moezali1** [comment]
This will be addressed through enhancement in #1939. Hence closing this issue.
