### ISSUE TITLE
Failed to handle ordinal features 

### ISSUE THREAD

**Issue by weishunc5** [pycaret/pycaret#842]
Hi,

I am practicing using PyCaret to build a regression model for the famous house price data on Kaggle. The dataset has a lot of ordinal features. I try to write a dictionary for all the ordinal features based on data description. But only some of the degree shows in train data hence in the setup step, error exists.

For example, there are 'Po', 'Fa', 'TA', 'Gd', 'Ex' 5 degrees for a quality feature, but only 'Fa', 'TA', 'Gd' exist in training data. Hence if I set up the dictionary like 'Qual': ['Po', 'Fa', 'TA', 'Gd', 'Ex'], error will exist. What will PyCaret do if 'Po' and 'Ex' exist in test data? 

With known data dictionary, I think it will be more convenient to cancel this exception error when we try to set up ordinal features.

Thanks for making such great tool and feel free to share your idea with me.

**Comment by weishunc5** [comment]
After I read over your documentation, if you treat it like a categorical feature and handle unseen categories as the least frequent one. Here is an example. If the unseen category is 'excellent' but the least frequent category is 'poor' hence it messes things up...What do you think?

**Comment by Yard1** [comment]
Thanks for the suggestion, will look into this.

**Comment by Yard1** [comment]
Would it be possible for you to share the notebook and the dataset? I believe I made a similar request in another issue, so feel free to just do it in one.

**Comment by pycaret** [comment]
@weishunc5 This is really difficult to determine whether you would want to merge the unknown with most frequent or least request, hence there is a parameter in the `setup` to set that. It is called `unknown_categorical_method` which is by default set to `least_frequent` but you can set it to `most_frequent`. 

For ordinal feature mapping, I think the factor levels should be present in train and test data to work. We will look into this to see if anything can be done about that. Open to your suggestions as well.

![image](https://user-images.githubusercontent.com/58118658/99804405-f2e8ae00-2b08-11eb-890b-a9a23ca94ef4.png)
