### ISSUE TITLE
Fail on blacklist, whitelist and catboost modelling while compare_models() On Kaggle Notebook

### ISSUE THREAD

**Issue by weishunc5** [pycaret/pycaret#843]
Hi,

I am running codes on Kaggle notebook. I want to go through compare_models() step with blacklist or whitelist options. It says:
TypeError: compare_models() got an unexpected keyword argument 'blacklist'.

When I compare all models, it says 
CatBoostError: catboost/libs/metrics/metric.cpp:5119: All train targets are equal

FYI, I install pycaret inside Kaggle notebook via !pip install pycaret.

**Comment by pa-blan** [comment]
blacklist -> exclude
whitelist -> include

https://pycaret.readthedocs.io/en/latest/api/classification.html#pycaret.classification.compare_models

**Comment by Yard1** [comment]
What @pa-blan said. If this doesn't solve your issue, feel free to make a new one.
