### ISSUE TITLE
COF Broken

### ISSUE THREAD

**Issue by cdurakci** [pycaret/pycaret#845]
today I upgraded to v2.2.1 and my simple code has broken both on my local machine and colab throwing the same error.
It has been working since inception unchanged

```
from pycaret.anomaly import *

exp_ano = setup(anomaly, silent = True, normalize = False, transformation = False, pca = False)

cof = create_model('cof') 
```

```
/usr/local/lib/python3.6/dist-packages/pyod/models/cof.py in __init__(self, contamination, n_neighbors)
     69         else:
     70             raise TypeError(
---> 71                 "n_neighbors should be int. Got %s" % type(n_neighbors))
     72         self.n_neighbors_ = n_neighbors
     73         self.decision_scores_ = None

TypeError: n_neighbors should be int. Got <class 'NoneType'>
```

**Comment by Yard1** [comment]
This is actually an issue with the `pyod` library we use for models. We haven't caught it before. I have pushed commit 4cb383d9c39e42429f84174000d552e605d9d204 which should fix this issue. Could you run
`pip install --upgrade --user git+git://github.com/pycaret/pycaret.git` to install PyCaret's development version and try again?

**Comment by cdurakci** [comment]
It seems working in the development version now.
assign_model generated anomaly binary label column name changed from 'Label' to 'Anomaly' but it is not a big issue maybe it is related with one of the new features of this release.
Thank you very much.
