### ISSUE TITLE
Anomaly detection fails when  imputation_type = 'iterative'

### ISSUE THREAD

**Issue by bigjoedata** [pycaret/pycaret#848]
Hello, I discovered another issue, I'm using the latest build. This works fine when imputation not included
```
ano1 = setup(df_clean, session_id=246, log_experiment=True, experiment_name='anomaly1', profile=True,
             transformation=True, 
             imputation_type = 'iterative',
             numeric_features=['num1'],
             date_features=['timestamp'],
             high_cardinality_features = ['feata', 'featb']) 
```

Sample output:

`---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
~\AppData\Roaming\Python\Python37\site-packages\pycaret\internal\preprocess.py in _impute_one_feature(self, X, column, X_na_mask, fit)
    824             try:
--> 825                 assert self.warm_start
    826                 estimator.partial_fit(X_train, y_train)

AssertionError: 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-143-10a921504816> in <module>
      5              high_cardinality_features = ['feata', 'featb']) 

~\AppData\Roaming\Python\Python37\site-packages\pycaret\anomaly.py in setup(data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, group_features, group_names, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs)
    436         verbose=verbose,
    437         profile=profile,
--> 438         profile_kwargs=profile_kwargs,
    439     )
    440 

~\AppData\Roaming\Python\Python37\site-packages\pycaret\internal\tabular.py in setup(data, target, ml_usecase, available_plots, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, transform_target, transform_target_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs, display)
   1326         y = data[target]
   1327     else:
-> 1328         X = prep_pipe.fit_transform(train_data).drop(target, axis=1)
   1329         X_train = X
   1330 

~\miniconda3\envs\ds\lib\site-packages\sklearn\pipeline.py in fit_transform(self, X, y, **fit_params)
    365         """
    366         fit_params_steps = self._check_fit_params(**fit_params)
--> 367         Xt = self._fit(X, y, **fit_params_steps)
    368 
    369         last_step = self._final_estimator

~\miniconda3\envs\ds\lib\site-packages\sklearn\pipeline.py in _fit(self, X, y, **fit_params_steps)
    294                 message_clsname='Pipeline',
    295                 message=self._log_message(step_idx),
--> 296                 **fit_params_steps[name])
    297             # Replace the transformer of the step with the fitted
    298             # transformer. This is necessary when loading the transformer

~\miniconda3\envs\ds\lib\site-packages\joblib\memory.py in __call__(self, *args, **kwargs)
    350 
    351     def __call__(self, *args, **kwargs):
--> 352         return self.func(*args, **kwargs)
    353 
    354     def call_and_shelve(self, *args, **kwargs):

~\miniconda3\envs\ds\lib\site-packages\sklearn\pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    738     with _print_elapsed_time(message_clsname, message):
    739         if hasattr(transformer, 'fit_transform'):
--> 740             res = transformer.fit_transform(X, y, **fit_params)
    741         else:
    742             res = transformer.fit(X, y, **fit_params).transform(X)

~\AppData\Roaming\Python\Python37\site-packages\pycaret\internal\preprocess.py in fit_transform(self, X, y, **fit_params)
    911         self.initial_imputer_ = None
    912 
--> 913         return self._impute(X, fit=True)
    914 
    915     def fit(self, X, y=None, **fit_params):

~\AppData\Roaming\Python\Python37\site-packages\pycaret\internal\preprocess.py in _impute(self, X, fit)
    876             for feature in self.imputation_sequence_:
    877                 get_logger().info(f"Iterative Imputation: {i+1} cycle | {feature}")
--> 878                 X_imputed = self._impute_one_feature(X_imputed, feature, X_na_mask, fit)
    879 
    880         if target_column is not None:

~\AppData\Roaming\Python\Python37\site-packages\pycaret\internal\preprocess.py in _impute_one_feature(self, X, column, X_na_mask, fit)
    826                 estimator.partial_fit(X_train, y_train)
    827             except:
--> 828                 estimator.fit(X_train, y_train, **fit_kwargs)
    829 
    830         X_test = X.drop(column, axis=1)[X_na_mask[column]]

~\miniconda3\envs\ds\lib\site-packages\lightgbm\sklearn.py in fit(self, X, y, sample_weight, init_score, eval_set, eval_names, eval_sample_weight, eval_class_weight, eval_init_score, eval_metric, early_stopping_rounds, verbose, feature_name, categorical_feature, callbacks, init_model)
    836                                         verbose=verbose, feature_name=feature_name,
    837                                         categorical_feature=categorical_feature,
--> 838                                         callbacks=callbacks, init_model=init_model)
    839         return self
    840 

~\miniconda3\envs\ds\lib\site-packages\lightgbm\sklearn.py in fit(self, X, y, sample_weight, init_score, group, eval_set, eval_names, eval_sample_weight, eval_class_weight, eval_init_score, eval_group, eval_metric, early_stopping_rounds, verbose, feature_name, categorical_feature, callbacks, init_model)
    598                               evals_result=evals_result, fobj=self._fobj, feval=feval,
    599                               verbose_eval=verbose, feature_name=feature_name,
--> 600                               callbacks=callbacks, init_model=init_model)
    601 
    602         if evals_result:

~\miniconda3\envs\ds\lib\site-packages\lightgbm\engine.py in train(params, train_set, num_boost_round, valid_sets, valid_names, fobj, feval, init_model, feature_name, categorical_feature, early_stopping_rounds, evals_result, verbose_eval, learning_rates, keep_training_booster, callbacks)
    229     # construct booster
    230     try:
--> 231         booster = Booster(params=params, train_set=train_set)
    232         if is_valid_contain_train:
    233             booster.set_train_data_name(train_data_name)

~\miniconda3\envs\ds\lib\site-packages\lightgbm\basic.py in __init__(self, params, train_set, model_file, model_str, silent)
   1981                     break
   1982             # construct booster object
-> 1983             train_set.construct()
   1984             # copy the parameters from train_set
   1985             params.update(train_set.get_params())

~\miniconda3\envs\ds\lib\site-packages\lightgbm\basic.py in construct(self)
   1323                                 init_score=self.init_score, predictor=self._predictor,
   1324                                 silent=self.silent, feature_name=self.feature_name,
-> 1325                                 categorical_feature=self.categorical_feature, params=self.params)
   1326             if self.free_raw_data:
   1327                 self.data = None

~\miniconda3\envs\ds\lib\site-packages\lightgbm\basic.py in _lazy_init(self, data, label, reference, weight, group, init_score, predictor, silent, feature_name, categorical_feature, params)
   1063                                                                                              feature_name,
   1064                                                                                              categorical_feature,
-> 1065                                                                                              self.pandas_categorical)
   1066         label = _label_from_pandas(label)
   1067 

~\miniconda3\envs\ds\lib\site-packages\lightgbm\basic.py in _data_from_pandas(data, feature_name, categorical_feature, pandas_categorical)
    395             raise ValueError("DataFrame.dtypes for data must be int, float or bool.\n"
    396                              "Did not expect the data types in the following fields: "
--> 397                              + ', '.join(data.columns[bad_indices]))
    398         data = data.values
    399         if data.dtype != np.float32 and data.dtype != np.float64:

ValueError: DataFrame.dtypes for data must be int, float or bool.
Did not expect the data types in the following fields: timestamp`

**Comment by Yard1** [comment]
Thanks for the report. Can you share the notebook and dataset with us?

**Comment by bigjoedata** [comment]
Unfortunately, I can't share much, it's not a public dataset and I don't own so I can't really share. But the pandas dtypes are:
20 categorical
1 datetime64[ns] - no missing values
1 int32 - no missing values
2 string objects

I'm realizing upon rereading the documentation that I don't need this function because it is separate from categorical imputation so that might be the root cause. I don't have any missing values in datetime or int32

Thanks!

**Comment by Yard1** [comment]
Yeah I believe the issue is with the datetime column. I'll be able to look into it regardless. Thanks.

**Comment by Yard1** [comment]
I just pushed commit e0018bc458f290bea8e9e54c1b8ef60c49792a80 that should fix this issue. Could you run
`pip install --upgrade --user git+git://github.com/pycaret/pycaret.git` to install PyCaret's development version and try again?

**Comment by bigjoedata** [comment]
Confirmed working. Great job on a great product!
