### ISSUE TITLE
blend_models() missing 1 required positional argument: 'estimator_list' 

### ISSUE THREAD

**Issue by dgg32** [pycaret/pycaret#849]
Hi. while following the tutorial in Google Colab: [Binary Classification Tutorial Level Intermediate](https://github.com/pycaret/pycaret/blob/master/tutorials/Binary%20Classification%20Tutorial%20Level%20Intermediate%20-%20CLF102.ipynb) at In[25], I have encountered the following error:

TypeError: blend_models() missing 1 required positional argument: 'estimator_list'

**Comment by Yard1** [comment]
The tutorial is sadly outdated. You must now specify a list of model objects (created with `create_model`) and pass it as that parameter.

**Comment by pycaret** [comment]
@dgg32 The tutorials are now updated.

Thanks for reporting.
