### ISSUE TITLE
ValueError: Method parameter not acceptable. It only accepts 'auto', 'predict_proba', 'decision_function', 'predict'.

### ISSUE THREAD

**Issue by dgg32** [pycaret/pycaret#850]
Hi in Google Colab, in the tutorial [Binary Classification Tutorial Level Intermediate](https://github.com/pycaret/pycaret/blob/master/tutorials/Binary%20Classification%20Tutorial%20Level%20Intermediate%20-%20CLF102.ipynb), at cell In [31]: stack_hard = stack_models(top3, method='hard'), I encountered the following error:

ValueError                                Traceback (most recent call last)

<ipython-input-36-e95db3cc70da> in <module>()
----> 1 stack_hard = stack_models(top3, method='hard')

1 frames

/usr/local/lib/python3.6/dist-packages/pycaret/internal/tabular.py in stack_models(estimator_list, meta_model, fold, round, method, restack, choose_better, optimize, fit_kwargs, groups, verbose, display)
   5381     if method not in available_method:
   5382         raise ValueError(
-> 5383             "Method parameter not acceptable. It only accepts 'auto', 'predict_proba', 'decision_function', 'predict'."
   5384         )
   5385 

ValueError: Method parameter not acceptable. It only accepts 'auto', 'predict_proba', 'decision_function', 'predict'.

**Comment by Yard1** [comment]
The tutorials are sadly outdated. `stack_models` doesn't accept `method` parameter anymore.

**Comment by pycaret** [comment]
@dgg32 The tutorials are now updated. 

Thanks for reporting.
