### ISSUE TITLE
Documentation - Replace "whitelist" and "blacklist" for "include" and "exclude" on Compare Models page examples. 

### ISSUE THREAD

**Issue by vbrenck** [pycaret/pycaret#851]
When comparing models (compare_models()), if you want to "blacklist" or "whitelist" a model, you should use include= or exclude= in the latest versions, since the expressions "blacklist" and "whitelist" were deprecated. However, the examples shown in page [Compare Models - PyCaret](https://pycaret.org/compare-models/) still use the old parameter names. I only found out that they have been replaced by include and exclude reading a forum post. Thanks for the great tool and I hope PyCaret keeps improving!

**Comment by pycaret** [comment]
@vbrenck Thanks for notifying us. Our documentation on the website only gets updated for major versions. 

The most up-to-date documentation is here: https://pycaret.readthedocs.io/en/latest/

Anyways, I will put a Note on the website to make sure people are re-directed to the updated documentation to avoid confusion.

Thanks.
