### ISSUE TITLE
TypeError when using pycaret rule mining in streamlit

### ISSUE THREAD

**Issue by batmanscode** [pycaret/pycaret#854]
I get:

`TypeError: expected string or bytes-like object`

When running:

```
from pycaret.datasets import get_data

data = get_data('france')

from pycaret.arules import *

exp_name = setup(data = data, transaction_id = 'InvoiceNo', item_id = 'Description')
model1 = create_model(metric = 'confidence')
model1
```

Env:
- streamlit 0.71.0
- pycaret 2.2.0
- python 3.8.5 (miniconda)

I'm not sure what's going wrong here. Any help is much appreciated!

**Comment by Yard1** [comment]
Could you send us the `logs.log` file in the directory form where you run PyCaret?

**Comment by batmanscode** [comment]
I ran it again to try and get logs but this time it worked! This might be a bigger problem since I don't know what the problem actually was lol

And how can I find `logs.log`? I tried `get_system_logs()` but got `NameError: name 'get_system_logs' is not defined`

Also, I tried the `get_rules()` instead of `setup()` and `create_model()` and got `TypeError: 'bool' object is not callable`

**Comment by Yard1** [comment]
`logs.log` is just a file that will be created in the directory from which you run the notebook/script.

**Comment by batmanscode** [comment]
I can't seem to find a `logs.log` file unfortunately.

Sure. I made a new script with some cleaned up code since the main one is super messy and incomplete.

It's fairly short so I will paste the code below. It's requirements are pandas, streamlit and of course pycaret.

To run, save this and use `streamlit run <filename.py>` in the terminal to launch the app and once in, press the **"Get rules"** button.

### Code:

```
import pandas as pd
import streamlit as st
from pycaret.arules import *

st.set_page_config(page_title="issue #854")

st.title("code for #854")
st.write("###### https://github.com/pycaret/pycaret/issues/854")

# load data

# from pycaret.datasets import get_data
# data = get_data('france')
# worked earlier but this gives a "AttributeError: module 'http' has no attribute 'client'"

data = pd.read_csv("data.csv")  # I had the france dataset saved locally
st.write(data)

st.header("Params")

col1, col2, col3 = st.beta_columns(3)

with col1:
    item = st.selectbox("Item description column", options=(data.columns), index=2)

with col2:
    tx = st.selectbox("Transaction column", options=(data.columns))

with col3:
    confidence = st.number_input(
        "confidence greater/equal to", value=0.95, min_value=0.5, max_value=1.0
    )


if st.button("Get rules"):
    st.header("Results")
    st.markdown("---")

    # rules = get_rules(data=data, transaction_id=tx, item_id=item)
    # doesn't work, returns -> "TypeError: expected string or bytes-like object"

    rule_setup = setup(data=data, transaction_id=tx, item_id=item)

    rules = create_model(threshold=confidence)

    rules = rules.filter(items=["antecedents", "consequents", "confidence"])
    rules.sort_values(by=["confidence"], ascending=False)

    # get_system_logs() -> #NameError: name 'get_system_logs' is not defined

    st.table(rules)
    # doesn't get displayed properly :( but maybe a problem with streamlit


```

**Comment by pycaret** [comment]
@batmanscode Thanks for sharing this. I have not tried the streamlit but I ran the code you gave in your first post and It ran okay for me.

It may be some dependency issue. Can you try creating a new conda environment and install pycaret using `pip install pycaret[full]`.

Let me know how that goes.

![image](https://user-images.githubusercontent.com/58118658/99593833-4d2a2780-29c0-11eb-9a57-26eba45fb27b.png)

**Comment by batmanscode** [comment]
@pycaret Thank you for trying it out. The code in my first post worked after I restarted my env (I am not sure why though).

`get_rules()` still gives me an error [only] in streamlit and the resulting table [doesn't get printed properly](https://discuss.streamlit.io/t/problem-with-how-a-df-is-being-displayed/7218) but this is probably a problem with streamlit.

I will try creating a new environment and get back.

**Comment by pycaret** [comment]
@batmanscode Unfortunately I can't help you with this. I tried to troubleshoot to see if `get_rules` is returning frozenset instead of pandas.DataFrame but indeed it returns pandas.DataFrame so I am not sure why `streamlit` is not formatting it correctly.

![image](https://user-images.githubusercontent.com/58118658/99805546-bb7b0100-2b0a-11eb-80ac-f18cbd177d99.png)

I hope you will be able to resolve this with streamlit. 

Thanks for reporting. We will be open to making any changes to our code-base to support correct formatting with streamlit. If you figure out anything to be fixed here, please open another issue describing the change and would be happy if you would like to work on the change yourself. 

Thanks

**Comment by batmanscode** [comment]
@pycaret Thank you for trying. I get frozenset printed when I try `create_model` and `get_rules` just returns: `TypeError: expected string or bytes-like object`.

So right now `create_model` is the only one that works and when using streamlit it returns a df with frozenset.

Thankfully, I got a [workaround ](https://discuss.streamlit.io/t/problem-with-how-a-df-is-being-displayed/7218/4) on the streamlit forum:
`st.table(df.applymap(lambda x: tuple(x) if isinstance(x, frozenset) else x ))`

Great, I will definitely submit a PR if I am able to 😃

**Comment by actcod01** [comment]
Hello Guys, @Yard1 @pycaret 

**pycaret version : 2.2.3**
___

I'm getting issue while accessing the `get_system_logs` function


`NameError: name 'get_system_logs' is not defined
`

How can I get logs in cmd?
