### ISSUE TITLE
Columns suppressed by setup

### ISSUE THREAD

**Issue by anne-leroy-T** [pycaret/pycaret#855]
HI,

Do you have an idea why the setup function has removed several columns from my input dataset. These are regular numerical columns with values and I have not changed the remove multicollenearity which is to false.

Thanks

**Comment by Yard1** [comment]
Could you send us the `logs.log` file in the directory form where you run PyCaret?

**Comment by anne-leroy-T** [comment]
Hello,   I found the issue.  I had variables that were at the start polynomial of others and it seems the option : 
remove_perfect_collinearity is True by default.
I changed to False and my issue is now solved.
