### ISSUE TITLE
Pycaret Power Bi  Issue 

### ISSUE THREAD

**Issue by hakobjan** [pycaret/pycaret#856]
Hello, when trying to run a python script in Power Query Editor to train machine learning models in a Power BI environment: 

`from pycaret.anomaly import *
saved_iforest = load_model('‪C:/Users/Gtech/Final IForest Model powerbi')
dataset = predict_model(iforest, data = dataset)`

Getting the following error message 

DataSource.Error: ADO.NET: Python script error:
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Gtech\.conda\envs\myenv\lib\logging\__init__.py", line 996, in emit
    stream.write(msg)
  File "C:\Users\Gtech\.conda\envs\myenv\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u202a' in position 101: character maps to <undefined>
Call stack:
  File "PythonScriptWrapper.PY", line 15, in <module>

**Comment by pycaret** [comment]
@hakobjan Can you share the dataset so we can try to reproduce the issue in Power BI?
