### ISSUE TITLE
About pycaret.classification.blend_models 

### ISSUE THREAD

**Issue by joey1616** [pycaret/pycaret#857]
When I use pycaret.classification.blend_models in Colab, It reported a mistake with
'TypeError: __init__() got an unexpected keyword argument 'verbose''.
How should I blend models?
Thanks

**Comment by Yard1** [comment]
Can you show us the exact code?

**Comment by joey1616** [comment]
Hello.The code is 
blender = cls.blend_models(estimator_list = [xgboost_classifier, lightgbm_classifier, catboost_classifier], method = 'hard')
And the error is 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-31-64e2121f26bb> in <module>()
----> 1 blender = cls.blend_models(estimator_list = [xgboost_classifier, lightgbm_classifier, catboost_classifier], method = 'hard')

2 frames
/usr/local/lib/python3.6/dist-packages/pycaret/internal/tunable.py in __init__(self, estimators, voting, weights, n_jobs, flatten_transform, verbose, **kwargs)
   1000             n_jobs=n_jobs,
   1001             flatten_transform=flatten_transform,
-> 1002             verbose=verbose,
   1003         )
   1004 

TypeError: __init__() got an unexpected keyword argument 'verbose'

**Comment by joey1616** [comment]
> Can you show us the exact code?

Hello.The code is
blender = cls.blend_models(estimator_list = [xgboost_classifier, lightgbm_classifier, catboost_classifier], method = 'hard')
And the error is
TypeError Traceback (most recent call last)
in ()
----> 1 blender = cls.blend_models(estimator_list = [xgboost_classifier, lightgbm_classifier, catboost_classifier], method = 'hard')

2 frames
/usr/local/lib/python3.6/dist-packages/pycaret/internal/tunable.py in init(self, estimators, voting, weights, n_jobs, flatten_transform, verbose, **kwargs)
1000 n_jobs=n_jobs,
1001 flatten_transform=flatten_transform,
-> 1002 verbose=verbose,
1003 )
1004

TypeError: init() got an unexpected keyword argument 'verbose'

**Comment by Yard1** [comment]
Thank you, I'll look into it.

**Comment by Yard1** [comment]
Could you send us the `logs.log` file which is automatically generated in the folder from which you run a notebook/script?

**Comment by joey1616** [comment]
> Could you send us the `logs.log` file which is automatically generated in the folder from which you run a notebook/script?
Hello, this is my logs.log in colab.
https://drive.google.com/file/d/1-0ZnjqPGnJ--ckIxoWCg-fNkIYY1OvxJ/view?usp=sharing

**Comment by Yard1** [comment]
Sorry, I don't have access. Please make sure you have chosen that everyone with this link can view it.

**Comment by joey1616** [comment]
> Sorry, I don't have access. Please make sure you have chosen that everyone with this link can view it.

Sorry, I updated the link again. Please use the new link to view.
https://drive.google.com/file/d/1-0ZnjqPGnJ--ckIxoWCg-fNkIYY1OvxJ/view?usp=sharing

**Comment by Yard1** [comment]
Could you update `scikit-learn` and try again? You can do it with `pip install -U scikit-learn`.

**Comment by joey1616** [comment]
> Could you update `scikit-learn` and try again? You can do it with `pip install -U scikit-learn`.

The problem has been solved by update 'scikit-learn'. Thank you.
