### ISSUE TITLE
catboost/libs/metrics/metric.cpp:5119: All train targets are equal

### ISSUE THREAD

**Issue by dgg32** [pycaret/pycaret#858]
Hi I am following the [regression intermedia](https://github.com/pycaret/pycaret/blob/master/tutorials/Regression%20Tutorial%20Level%20Intermediate%20-%20REG102.ipynb). At cell In [7], I have encounter the following error:

_catboost.pyx in _catboost._CatBoost._train()

_catboost.pyx in _catboost._CatBoost._train()

CatBoostError: catboost/libs/metrics/metric.cpp:5119: All train targets are equal

![Screenshot from 2020-11-18 11-24-40](https://user-images.githubusercontent.com/1873196/99518324-b3975180-2990-11eb-92f0-b3380650bf71.png)

In fact, the tutorial from there on encounters errors in the next cells too. It needs a correction urgently for new users.

**Comment by Yard1** [comment]
Yes, the tutorials are in the process of being updated. Apologies for any inconvenience.

**Comment by pycaret** [comment]
@dgg32 Can you update the Catboost version by `pip install --upgrade catboost`.

I believe the error should go away with the new version of Catboost.

**Comment by dgg32** [comment]
@pycaret Unfortunately no. I have pip upgraded it to catboost-0.24.3. Still the same error.

**Comment by pycaret** [comment]
@dgg32 Can you share the reproducible Notebook with the sample dataset for us to troubleshoot?

**Comment by dgg32** [comment]
@pycaret It is just the [tutorial notebook](https://github.com/pycaret/pycaret/blob/master/tutorials/Regression%20Tutorial%20Level%20Intermediate%20-%20REG102.ipynb). Not my code.

**Comment by pycaret** [comment]
@dgg32 Thanks, I will try to look at this today. Will let you know if I have any updates.

**Comment by pycaret** [comment]
@dgg32 This issue has been fixed in `pycaret=2.2.2`. Please update your version and try again.

Feel free to open another ticket, if the issue persists.

**Comment by sriprad** [comment]
Hi ,
I have the same error version is 2.2.3. Can you please help?
Thanks
