### ISSUE TITLE
Difference performance metrics in every run with same session_id 

### ISSUE THREAD

**Issue by noorikhalifa** [pycaret/pycaret#859]
Similar to issue #417 I am getting different performance metrics with catboost classifier after I restart the kernel and run the cells again. I am using pycaret version 2.2.0 and I am not changing any variable selection methods either (as it was mentioned in the previous issue).
![image](https://user-images.githubusercontent.com/63507090/99493460-40dca500-2995-11eb-937f-f25e0b9ed31c.png)
![image](https://user-images.githubusercontent.com/63507090/99520574-43e98c80-29b9-11eb-8d91-b0af58de91bf.png)

Also, 
plot_model(best_none, plot = 'confusion_matrix', use_train_data = True) 
![image](https://user-images.githubusercontent.com/63507090/99520704-71363a80-29b9-11eb-8565-d83a57be3e86.png)  

evaluate_model(best_none) 
gives this confusion matrix for the test set if I'm not wrong. 
![image](https://user-images.githubusercontent.com/63507090/99520948-c96d3c80-29b9-11eb-8aa6-8114c44ee529.png)
The regular formulas for the obtained values in the confusion matrix give different values from what is given in the compare_model metrics. 
Could you please clarify how the metrics are actually calculated and a better way for reproducibility.
Thanks!

**Comment by Yard1** [comment]
It seems to be due to how CatBoost works. This is not something we, as PyCaret, can account for, as we are already doing everything we can do (that is, passing the same seed to the CatBoost estimator). I'd imagine that you could improve your reproductibility if you set `n_jobs=1, use_gpu=False` in `setup()`, at a cost of performance.

**Comment by davins90** [comment]
is it not possible to add the "session_id / random_state" also as a parameter of each model?

**Comment by Yard1** [comment]
That's already being done.

**Comment by pycaret** [comment]
@davins90 @noorikhalifa 

The `random_state` is propagated to all the models including CatBoost using the `session_id` defined in the `setup` function. But this seems like an issue with CatBoost. I will be willing to take this up with their team one of you can share the reproducible Notebook with a sample dataset here? 

Thanks

**Comment by davins90** [comment]
thanks for the answer! tomorrow i'll try to provide you a reproducible notebook! thanks

**Comment by JosAndr** [comment]
I'm having a similar problem without using CatBoost,  i'm getting a different merics in each try, sometimes i'm getting a differetn clasifier as the best one,   i'm using the same dataset and the  same initial setup configuration.

![image](https://user-images.githubusercontent.com/54367290/100371393-b0761400-2fd5-11eb-9d95-c7e7a8ba3668.png)

![image](https://user-images.githubusercontent.com/54367290/100371857-6b061680-2fd6-11eb-836d-b8d0c7e1f20d.png)

**Comment by vinay9986** [comment]
This is what I have observed. Training CatBoost using the `compare_models` method creates a directory `catboost_info`. The reported metrics do not change when the `cat boost_info` directory is not altered from the initial run. If you delete the `catboost_info` the reported metrics changes. 

P.S.
This is my observation. I will try and put together a notebook that can verify this behavior.
