### ISSUE TITLE
# memory error #PyCaret 2.2.1

### ISSUE THREAD

**Issue by onkarS23** [pycaret/pycaret#860]
**MemoryError: Unable to allocate 231. GiB for an array with shape (176066, 176066) and data type float64**
Hi I am using, the latest PyCaret (2.2.1), I have a Train, test and validation dataset with (total number is 70K rows  9k columns). 
However, I used small dataset with 8K rows and 9K columns but  I am getting a memory error, so is there any possibility to fix it. I am running the code on server which has 128 Gb ram, and I think memory should be enough to execute the program. Any help will be appreciated.
![memory error](https://user-images.githubusercontent.com/73878916/99652855-4e785480-2a93-11eb-87a7-6026349ae669.png)

Thank you in advance

**Comment by pycaret** [comment]
@onkarS23 Can you convert float64 to lower float32, that might help?

**Comment by pycaret** [comment]
@onkarS23 Do you still need help?

**Comment by onkarS23** [comment]
> 
> 
> @onkarS23 Do you still need help?

Sorry for my late reply, I am beginner and was trying to find the way to convert float64 to lower float32 by looking online or is there anyway to convert in pycaret itself? Thank you for your reply and help.
after that I can tell it is working or not. but thank you so much your reply

**Comment by pycaret** [comment]
@onkarS23 You can read about it here: https://stackoverflow.com/questions/45955186/convert-numpy-array-type-and-values-from-float64-to-float32
