### ISSUE TITLE
Where is the plot?

### ISSUE THREAD

**Issue by roberthoyt** [pycaret/pycaret#863]
I just finished the beginner module on clustering and noticed that several plots are missing, in particular, plot_model(kmeans) . It is missing in the tutorial and when I uploaded my own data, I did not see plotted clusters. I also tried this command which did not generate a plot - plot_model(kmeans, plot = 'cluster')
See PDF below

[Untitled11.pdf](https://github.com/pycaret/pycaret/files/5568281/Untitled11.pdf)

**Comment by pycaret** [comment]
@roberthoyt Can you update your pycaret version to `2.2.0` by using `pip install --upgrade pycaret`. 

Let me know if that solves the problem.

**Comment by roberthoyt** [comment]
After upgrading I now have a setup error when I press Enter I did not have before

I can't export the Jupyter Lab as a PDF or any other format accepted on this forum from what I can tell

**Comment by roberthoyt** [comment]
I was able to upload and analyze with unsupervised learning problem in CoLab so case closed
