### ISSUE TITLE
Change cross validation method [Leave One Group Out cross-validator]

### ISSUE THREAD

**Issue by jpcaico** [pycaret/pycaret#866]
Is it possible to change cross validation method while compare_models or create_model?
There are case where is needed to apply Leave One Group Out cross-validator and compare performances, regular k-fold cross validation does not goes well in this cases since it mixes same group data in training/test folds

**Comment by pycaret** [comment]
@jpcaico It is possible to change the fold strategy by defining the `fold_strategy` parameter when calling the `setup` function.

![image](https://user-images.githubusercontent.com/58118658/99802818-5cb38880-2b06-11eb-9190-25e60ebaea34.png)

Please read more about it in the documentation here: https://pycaret.readthedocs.io/en/latest/api/classification.html

Hope this helps. Thanks
