### ISSUE TITLE
Score seems incoherent with class prediction

### ISSUE THREAD

**Issue by danielmarostica** [pycaret/pycaret#868]
This doesn't make sense to me. How can higher scores (which is supposed to be probability, right?) return 0 instead of 1?

![image](https://user-images.githubusercontent.com/3595998/99833556-f0a24600-2b40-11eb-8c11-e231076b3097.png)

**Comment by pycaret** [comment]
@danielmarostica Can you please upload the Notebook with a sample dataset?

**Comment by pycaret** [comment]
@danielmarostica The probability value is the value of the predicted class. So in your example Label 0 with a score of 0.9542 means 95.42% probability of class 0 and (1 - 0.9542) would be the probability of Class 1 (incase you want to calculate).

![image](https://user-images.githubusercontent.com/58118658/99837425-8e901380-2b35-11eb-882f-9fcc21969217.png)
