### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float64')

### ISSUE THREAD

**Issue by Arun-Chhikara** [pycaret/pycaret#870]
Hello, I am getting this ValueError when i try to use create_model() from below provided setup() configuration:-

from pycaret.datasets import get_data
dataset = get_data('diamond')
exp_reg102 = setup(data = data, target = 'Price', session_id=133, numeric_imputation = 'mean', categorical_imputation = 'mode', normalize = True, transformation = True, transform_target = True,  combine_rare_levels = True, rare_level_threshold = 0.05, remove_multicollinearity = True, multicollinearity_threshold = 0.95,  bin_numeric_features = ['Carat Weight'], log_experiment = False, experiment_name = 'diamond1')

The error will disappear with transform_target = False in setup() configuration

How can I get/access the dataset transformed by the pipeline defined in setup(); just like displayed illustrations 'Before' and 'After' in [Transformation](https://pycaret.org/transformation/) ?

**Comment by pycaret** [comment]
@Arun-Chhikara This issue has been fixed. Please update the version to `pycaret==2.2.2`.

To get access to the transformed dataset, please use the `get_config` function. Check the docstring of the function for more information.
