### ISSUE TITLE
compare_model() giving ZERO R2 (and all other regression metrics as well) when fold = 1 in compare_model()

### ISSUE THREAD

**Issue by Arun-Chhikara** [pycaret/pycaret#871]
Hello, This is what i get with following setup() configuration:-

from pycaret.datasets import get_data
dataset = get_data('diamond')

from pycaret.regression import *
exp_reg102 = setup(data = data, target = 'Price', session_id=133, numeric_imputation = 'mean', categorical_imputation = 'mode', normalize = True, transformation = True, transform_target = True,  combine_rare_levels = True, rare_level_threshold = 0.05, remove_multicollinearity = True, multicollinearity_threshold = 0.95,  bin_numeric_features = ['Carat Weight'], log_experiment = False, experiment_name = 'diamond1')

model = compare_models(include = ['rf','br'],fold = 1)

![image](https://user-images.githubusercontent.com/64885325/99880960-c46bef80-2c3c-11eb-872a-afc38e7ccae8.png)

But when fold = 2, I can see meaningful results:-

best = compare_models(include = ['rf','br'],fold = 2)
![image](https://user-images.githubusercontent.com/64885325/99892746-2c9eed80-2c9e-11eb-91c7-df2c2a6fcae8.png)

**Comment by Arun-Chhikara** [comment]
Apologies. I just found in the documentation that 'fold' must be at least 2.

**Comment by Yard1** [comment]
We should probably raise an exception in this case. Thanks.
