### ISSUE TITLE
When plotting silhouette for k-means, I get an n_clusters error.

### ISSUE THREAD

**Issue by charljduplessis** [pycaret/pycaret#873]
### Issue:
I was working through tutorial CLU101. When I created and assigned the kmeans model I tried to do the silhouette plot but got this error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
...\lib\site-packages\pycaret\internal\tabular.py in silhouette()
   6314                             groups=groups,
-> 6315                             display=display,
   6316                         )

...\lib\site-packages\pycaret\internal\plotting.py in show_yellowbrick_plot(visualizer, X_train, y_train, X_test, y_test, name, handle_train, handle_test, scale, save, fit_kwargs, groups, display, **kwargs)
     41         logger.info("Fitting Model")
---> 42         visualizer.fit(X_train, y_train, **fit_kwargs_and_kwargs)
     43     elif handle_train == "fit_transform":

...\lib\site-packages\yellowbrick\cluster\silhouette.py in fit(self, X, y, **kwargs)
    141         self.n_samples_ = X.shape[0]
--> 142         self.n_clusters_ = self.estimator.n_clusters
    143 

**AttributeError: 'Pipeline' object has no attribute 'n_clusters'**

### Using:
pycaret 2.2.1
python 3.7.0
ipython 7.19.0
jupyter-client 6.1.7
jupyter-core 4.7.0
jupyterlab-pygments 0.1.2
Visual Studio Code 1.51.1

**Comment by Yard1** [comment]
The tutorials are sadly not yet up to date.

**Comment by charljduplessis** [comment]
No problem, is there a workaround for this?

**Comment by pycaret** [comment]
@Yard1 This could be a bug as well. I will try to run CLU101 tutorial tomorrow and see If get the same error.

**Comment by pycaret** [comment]
@charljduplessis This issue has been fixed. Please update your version to `pycaret==2.2.2`.

If the issue persists, please feel free to open another issue.

Thanks for reporting.
