### ISSUE TITLE
classification.models() not working anymore

### ISSUE THREAD

**Issue by HighPerformance01** [pycaret/pycaret#874]
Hello

df = classification.models() 

is not working anymore

**Comment by pycaret** [comment]
@HighPerformance01 Can you please elaborate more? Which version you are using and what is the complete error?

**Comment by HighPerformance01** [comment]
Sorry, I just thought it can be noticed directly as I have tried this on two computers 

Both of them are upgraded from the earlier version to the recent version that is pycaret 2.2.1

The error says:

logger.info(f"gpu_param set to {gpu_param}")
NameError: name 'logger' is not defined

Thank you

**Comment by pycaret** [comment]
@HighPerformance01 This issue has been fixed. Please update your version to `pycaret==2.2.2`.

If the issue persists, please feel free to open another ticket.

**Comment by HighPerformance01** [comment]
Thank you very much

**Comment by HighPerformance01** [comment]
The issue still there even though it has been tested in 3 computers so far (2 windows and 1 Linux)

Code:
from pycaret import classification
df = classification.models() 

Error Message:
Traceback (most recent call last):

  File "C:\Users\MSG-PC\Google Drive\py\dash01\test03.py", line 3, in <module>
    df = classification.models()

  File "C:\Users\MSG-PC\Anaconda3\lib\site-packages\pycaret\classification.py", line 2239, in models
    type=type, internal=internal, raise_errors=raise_errors

  File "C:\Users\MSG-PC\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 9136, in models
    logger.info(f"gpu_param set to {gpu_param}")

NameError: name 'logger' is not defined
