### ISSUE TITLE
The inconsistent results between computing AUC by two ways

### ISSUE THREAD

**Issue by super233** [pycaret/pycaret#877]
The AUC computed by `predict_model()` and `get_metrics().loc['auc', 'Score Function']` are not the same.
Is this a bug? Or pycaret has hidden some details of computing? 
My pycaret version is 2.2.1

![image](https://user-images.githubusercontent.com/35358984/100064084-067b7800-2e6d-11eb-9bfb-053c5cc2ffe9.png)

**Comment by Yard1** [comment]
For Binary classification problems, the score returned by PyCaret is the probability of the selected class, while scikit-learn expects the probability of the positive class. You can use the following code to obtain the latter from the former.

```
r_score = np.where(result['Label']==0, 1-result["Score"], result["Score"])
score_function(result["Label"], r_score)
```

Where `score_function` is the AUC score function.

This will give the same metric value as from `predict_model`.

**Comment by super233** [comment]
Thanks, I got it.
