### ISSUE TITLE
Compare models with different features

### ISSUE THREAD

**Issue by Cokral** [pycaret/pycaret#879]
Hello,

I've been using pycaret recently in order to build a regression model to predict some retail daily quantities.
In order to figure out the best variables to use, especially the lag features, I'd like to be able to specicify a list of variables to try with / without in a grid search fashion.

I believe this is not currently possible as you setup your dataset once and then run the comparison module.
Is it something that could be interesting to others and implemented ? 

In my mind it could be another parameter in the `setup()`, such as `optional_columns=List[str]`.
Given this parameter, the `compare_model` function would not only compare models, but also `compare_models` with different sets of features.

What do you think ?

Thank you

**Comment by pycaret** [comment]
@Cokral Thanks for sharing. I have tagged this as an enhancement. Can you please write a more detailed user story with examples and expected outcomes so that they help our developers when implementing the functionality.

**Comment by ngupta23** [comment]
@Yard1 I think this would be possible by having separate objects in the new (unreleased) OOP flow by having different objects hold different sets of features. Then the `compare_model` results could be pulled from different objects, concatenated and used as needed. Is this correct?

**Comment by Yard1** [comment]
@ngupta23 It's already possible in the current release by doing, for example:
```python
model1 = create_model("lr", alpha=10.0)
model2 = create_model("lr", alpha=100.0)
compare_models(include=[model1, model2, "lr"])
```
