### ISSUE TITLE
Correlation Feature Selection

### ISSUE THREAD

**Issue by wsn4iv** [pycaret/pycaret#88]
When using the interpret_model correlation plot, can you select the two specific features for the correlation?

**Comment by pycaret** [comment]
@wsn4iv 

Unfortunately not at the moment. It should be an easy change. I will tag this as an enhancement.

Thanks.

**Comment by pycaret** [comment]
@wsn4iv **kwargs support now added in `interpret_model` in `classification.py` and `regression.py`. Now you can pass the feature inside `interpret_model` using the parameters of `shap`
