### ISSUE TITLE
About setup

### ISSUE THREAD

**Issue by joey1616** [pycaret/pycaret#882]
Hi,my target have 123 classes,when i use regression.setup and classification.setup, program error with 
```
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py in _encode_python(values, uniques, encode)
     67         except KeyError as e:
     68             raise ValueError("y contains previously unseen labels: %s"
---> 69                              % str(e))
     70         return uniques, encoded
     71     else:

ValueError: y contains previously unseen labels: 'Eating Disorder'
```
How can i solve it. Thanks

**Comment by pycaret** [comment]
@joey1616 Please upload the reproducible Notebook and sample data to help us troubleshoot the error.

**Comment by pycaret** [comment]
@joey1616 Are you still facing the problem. If not, please close the issue.

**Comment by igorkf** [comment]
I had the same issue.      
It went away when I changed `data_split_shuffle=False` to `data_split_shuffle=True`.
