### ISSUE TITLE
"TypeError: expected string or bytes-like object" but only sometimes

### ISSUE THREAD

**Issue by batmanscode** [pycaret/pycaret#883]
**Is your feature request related to a problem? Please describe.**
This works most of the time but when running `setup `and `create_model` in `arules`, every now and then I get this error.

**How/when it happens:**
I am currently working on a little streamlit project which has a button that runs `setup` and `create_model` when pressed.

This usually works and I get the get the results as expected.

Many button presses later, after working on this for a while, I'll press the button only to get `TypeError: expected string or bytes-like object` with the traceback pointing to where `setup `starts.

**The fix I use:**
Oddly, when I deactivate and then reactivate the environment (without making any changes), it works just fine and returns the results as expected.

**Describe the solution you'd like**
Why does this happen and how might I permanently prevent it?

**Describe alternatives you've considered**
I've created new environments with both `pip install pycaret` and `pip install pycaret[full]`. I also tried with `--upgrade`.

**Additional context**
Button code:

```
get_rules = st.button("Get rules")

if get_rules:
    rule_setup = setup(data=data, transaction_id=tx, item_id=item, ignore_items=ignore)

    rules = create_model(threshold=confidence)
```

Env:

- streamlit 0.71.0
- pycaret 2.2.0
- python 3.8.5 (miniconda)

**Comment by pycaret** [comment]
@batmanscode Sorry for the late response. Were you able to resolve this issue? Can you share your findings?
