### ISSUE TITLE
Unsupervised learning

### ISSUE THREAD

**Issue by roberthoyt** [pycaret/pycaret#885]
1. I was able to visualize a few plots using Google CoLab but using Jupyter Lab I could only plot an elbow plot. I can't import the ipynb file here
2. I thought the clusters created in GoLab looked good with good separation. I now need to profile clusters. Each row was assigned a cluster when I assigned the model. What is the next logical step to profile the clusters?

**Comment by pycaret** [comment]
@roberthoyt You can use the `assign_model` function to assign the cluster labels or use the `predict_model` function on unseen/new data to profile them into clusters using the trained model. You can save the model using the `save_model` function and load it back using the `load_model` function.

Hope this helps.
