### ISSUE TITLE
Getting prediction probability for each class in predict_model

### ISSUE THREAD

**Issue by sparvaneh** [pycaret/pycaret#886]
Hi,

predict_model returns the probability of predicted class. Is there any way to get the probability for each class?

Thanks,
Saman

**Comment by pycaret** [comment]
@sparvaneh In the case of binary classification you can simply use 1 - score to get the probability of other class. For multiclass, unfortunately at the moment, you cannot get the probability of all classes using the native `predict_model`  functionality. However, if you want you could use the model object and call of `.predict_proba` method to get an array of the probability of all classes. 

However, I am tagging this as an enhancement and something to think about in future releases.

**Comment by pycaret** [comment]
@Yard1 For multiclass problems, we can append the N number of columns in the `predict_model` return in `pycaret.classification` where N = number of classes.

**Comment by Yard1** [comment]
We can have this behavior toggled with a parameter, will be easy to add.

**Comment by sparvaneh** [comment]
How do you find and assign a Score in binary classification using predict_model? Why changing a threshold is changing score?

**Comment by Yard1** [comment]
Functionality added in commit e729cf7d6716bb582233aa4bcf2689e72968b293 - do `predict_model(model, raw_score=True)` to obtain scores for all labels in separate columns.
