### ISSUE TITLE
predict_model error on cross_validation=False

### ISSUE THREAD

**Issue by happytk** [pycaret/pycaret#887]
In my cases, following error always occurs when I call `predict_model(..cross_validation=False)`

```
  File "/usr/local/lib/python3.8/site-packages/pycaret/classification.py", line 889, in create_model
    return pycaret.internal.tabular.create_model_supervised(
  File "/usr/local/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 3029, in create_model_supervised
    predict_model(pipeline_with_model, verbose=False)
  File "/usr/local/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 8374, in predict_model
    d = []
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

I inspected pycaret-code, and below explanation is what I found.

1. below function return values are float32, not int
```
# tabular.py:8320
pred = np.nan_to_num(estimator.predict(X_test_))
```

2. so next logic could be error. python index must be int not float.
```
# tabular.py:8373
    if score is not None:
        d = []
        for i in range(0, len(score)):
            d.append(score[i][pred[i]])
```

using:
- pycaret==2.2.1

**Comment by pycaret** [comment]
@happytk Can you please share the exact code that is generating the error? 

`predict_model` function does not accept the `cross_validation` parameter.

**Comment by pycaret** [comment]
@Yard1 FYI

**Comment by pycaret** [comment]
@happytk Is this still a problem and you need help? 

If not, please close this thread.

**Comment by happytk** [comment]
I couldn't reproduce this problem again. I'll write down if something is found.
