### ISSUE TITLE
compare_models RMSLE error metric with setup(use_gpu = False)

### ISSUE THREAD

**Issue by raultomasmora** [pycaret/pycaret#889]
Regarding "compare_models", when you run it with "use_gpu = False"  in setup(), the RMSLE error metric comes out zero in all ML algorithms.
When "use_gpu = True", the RMSLE metric is calculated.

pycaret v. 2.2.2

**Comment by pycaret** [comment]
@raultomasmora Can you please upload a reproducible Notebook and sample data, that will help us troubleshoot the error?

**Comment by raultomasmora** [comment]
It seems to be a problem with the configuration of my system, sorry for the inconvenience.
