### ISSUE TITLE
Passing custom grid to the tune_model function

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#89]
Can we pass a custom grid to the `tune_model` function? I looked at the code on github and it seems that this can be added fairly easily through an argument and passed to the model object. 

Reference: [Discussion on LinkedIn](https://www.linkedin.com/feed/update/urn:li:ugcPost:6661097050945519616?commentUrn=urn%3Ali%3Acomment%3A%28ugcPost%3A6661097050945519616%2C6661456303426191360%29)

**Comment by pycaret** [comment]
Thanks. Will be added in next release. 

Tagging this as enhancement.

**Comment by ngupta23** [comment]
I can submit a pull request if you like...

**Comment by pycaret** [comment]
I have worked on this already. If you can, can you please see if you can permutation plot and partial dependence in plot_model function. They are released in >0.21

**Comment by pycaret** [comment]
Released in sklearn.

**Comment by ngupta23** [comment]
Sure, I will have a look at it and see if I can add it.

**Comment by pycaret** [comment]
### Feature now available in pycaret-nightly.

You can install **pycaret-nightly** using "pip install pycaret-nightly".

New parameter **custom_grid** is now added in **tune_model()**. 

Can you please test this and close the issue if the enhancement addresses the original issue.

It will be shipped to PyCaret 2.0x in few weeks.

**Comment by ngupta23** [comment]
Thank you. It works great!
