### ISSUE TITLE
Pycaret pipeline for other ml-frameworks 

### ISSUE THREAD

**Issue by pa-blan** [pycaret/pycaret#890]
**Is your feature request related to a problem? Please describe.**

Hi, first of all, I would like to say that pycaret is really good. I want to use the pipeline, that is created in the setup for a Keras model. How do I get new data in the same format via the created pipeline so that it has the same format as via get_config("X_train")? I tried to use the transform function, but I just get the One-Hot encoded features. How do I solve my problem?

prep_pipe = pycc.get_config("prep_pipe")
after_prep_pipe = prep_pipe.transform(df_test)
after_prep_pipe

(df_test is just a row from the dataset)

**Describe the solution you'd like**

pycaret.classification.get_config(prep_pipe)

**Describe alternatives you've considered**

**Additional context**

**Comment by pycaret** [comment]
@Yard1

**Comment by Yard1** [comment]
Compatibility with other frameworks is something we will be working on for the next major release.

**Comment by pa-blan** [comment]
I think i solved my problem with:
#%%
prep_pipe = pycc.get_config("prep_pipe")
prep_pipe
#%%
prep_pipe.steps.append(['trained_model', model])
#%%
prep_pipe.predict(df_test)
