### ISSUE TITLE
Returning untransformed feature values from get_config()

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#892]
**Is your feature request related to a problem? Please describe.**

Currently, I can only get the transformed values of the features from get_config(). Is it possible to get the original values as well (without any transformation

```python
help(get_config)
```
```
- X_train: Transformed train dataset (X)
- X_test: Transformed test/holdout dataset (X)
```

**Describe the solution you'd like**
Get the original values using something like 

```python
get_config("X_train_org")
```

**Comment by Yard1** [comment]
`get_config('X_before_preprocess')` should work.

**Comment by ngupta23** [comment]
Thanks. Does it tell you which ones are used for training and which ones are used for testing (before finalizing the model)?

**Comment by Yard1** [comment]
No, but you can get the indices from `get_config('X_train')` and `get_config('X_test')` and just select the matching rows.

**Comment by ngupta23** [comment]
Thanks. That will work. I hope this shortcut can be added to get_config as well!

**Comment by pycaret** [comment]
@ngupta23 Good idea. We can create new global variables in `2.3`. @Yard1 FYI. 

X_train_org
X_test_org
y_train_org
y_test_org
