### ISSUE TITLE
Date time feature did not fit

### ISSUE THREAD

**Issue by JproChen** [pycaret/pycaret#897]
I was using the same dataset for training and testing
and when using the predict_model for testing
some of the data success, but some of them failed
this input "Timestamp":"2020-09-01-10:00:00 " is fine
this input "Timestamp":"2020-09-01-00:00:00 " fails
and give me the error says the feature did not fit
the Timestamp displays as  Date data type in the setup
So, do I have to manually change the Timestamp to  one-hot code or something?
or there is some setup I have missing
thanks

**Comment by Yard1** [comment]
Would it be possible for you to share the dataset and the code?

**Comment by JproChen** [comment]
https://drive.google.com/file/d/1Dm20j0Iw83BYEHNqDoUKXqNFpcT0RM_0/view?usp=sharing

The link provided my minimum reproducible example, and dataset
Thanks!

**Comment by Yard1** [comment]
I just pushed commit 311ab2aff8599563baa4e66f3e677542f5f8b669 that should fix this issue. Could you run
`pip install --upgrade --user git+git://github.com/pycaret/pycaret.git` to install PyCaret's development version and try again?

**Comment by pycaret** [comment]
@JproChen Can you please test and confirm?

**Comment by JproChen** [comment]
Thanks, it worked
but the prediction is very slow comparing to the old version
