### ISSUE TITLE
df = classification.models() not working

### ISSUE THREAD

**Issue by HighPerformance01** [pycaret/pycaret#899]
Hi,

classification.models() is not working

The issue still there even though it has been tested in 3 computers so far (2 windows and 1 Linux)

Code:
from pycaret import classification
df = classification.models()

Error Message:
Traceback (most recent call last):

File "....\test03.py", line 3, in
df = classification.models()

File "...\classification.py", line 2239, in models
type=type, internal=internal, raise_errors=raise_errors

File "...\tabular.py", line 9136, in models
logger.info(f"gpu_param set to {gpu_param}")

NameError: name 'logger' is not defined

**Comment by pa-blan** [comment]
@HighPerformance01 Try first the classification.setup() with all needed parameters and then  the classification.models() function.

**Comment by HighPerformance01** [comment]
But at that point, still, I do not have all information to setup the model.

The idea is first to show the user the available algorithms.

**Comment by HighPerformance01** [comment]
But at that point, still, I do not have all information to setup the model.

The idea is first to show the user the available algorithms.

Also, this was working perfectly in the old version which causes the issue when trying to move to the new version.

**Comment by Yard1** [comment]
Since 2.2 release, it is necessary to run `setup()` first in order for this function to work. This behavior may change in the future.

**Comment by pycaret** [comment]
@Yard1 In the next release we can remove the dependency of the `models` function on the `setup`. We may have to think about what to show in metrics and models when `internal=True`.
