### ISSUE TITLE
Meta model default in stacking

### ISSUE THREAD

**Issue by Riazone** [pycaret/pycaret#9]
The default for _meta-model_ is linear/logistic for classification/regression. Though it might work in certain cases, places where I have used, especially with re-stack = True, the model performance only improves when I have chosen one of the better performing models as meta model. Since most of the users would begin with Compared_models(), if there was a way to have the stacking default to best model from compare_model, it would be more convenient.

**Comment by pycaret** [comment]
@Riazone 

Its not possible to default _meta_model_ to best model as a user may or may not run **compare_models** before stacking. However, what you can do to achieve this in PyCaret 2.0x is as follows:

> top5 = compare_models(n_select=5)
> stack_models(estimator_list = top5, meta_model = top5[0])

If this answers your question, can you please close the issue?
