### ISSUE TITLE
Question: Setup, get_config

### ISSUE THREAD

**Issue by pa-blan** [pycaret/pycaret#902]
Which settings in the setup affect the get_config("X_train") function? (X_train, X_test, y_train, y_test, X, y)

**Comment by Yard1** [comment]
I am not sure what you mean by "what settings affect". All the preprocessing settings affect the final forms of data.

**Comment by pa-blan** [comment]
For example, when I apply smote (fix_imbalance) in the Setup, does this change something in the transformed train_test_split which I can get from get_config? 

import pycaret.classification as pycc

clf1 = pycc.setup(df, target = 'Survived', session_id=123, verbose= False, silent = True, use_gpu=False, fix_imbalance=True)

X = pycc.get_config('X').reset_index(drop=True)
y = pycc.get_config('y').reset_index(drop=True)
X_train = pycc.get_config('X_train').reset_index(drop=True)
X_test = pycc.get_config('X_test').reset_index(drop=True)
y_train = pycc.get_config('y_train').reset_index(drop=True)
y_test = pycc.get_config('y_test').reset_index(drop=True) 

#%%

clf1 = pycc.setup(df, target = 'Survived', session_id=123, verbose= False, silent = True, use_gpu=False, fix_imbalance=False)


X = pycc.get_config('X').reset_index(drop=True)
y = pycc.get_config('y').reset_index(drop=True)
X_train = pycc.get_config('X_train').reset_index(drop=True)
X_test = pycc.get_config('X_test').reset_index(drop=True)
y_train = pycc.get_config('y_train').reset_index(drop=True)
y_test = pycc.get_config('y_test').reset_index(drop=True)

**Comment by Yard1** [comment]
SMOTE is applied for each CV fold and not during setup, therefore it will not be visible in preprocessed data you can get with `get_config`. However, as of now, SMOTE is the only data preprocessing step with this behavior.

**Comment by pycaret** [comment]
@pa-blan As @Yard1 mentioned, SMOTE is applied during CV hence there is no single `X_train`. The number of over-sampled datasets in case of over-sampling = number of folds and it is strictly applied during CV to avoid leakage.
