### ISSUE TITLE
Custom Pipeline Clarification

### ISSUE THREAD

**Issue by JaneCuiQin** [pycaret/pycaret#903]
Hi,
I defined a custom_pipline as below for pycaret.
class CreateNewFeature(BaseEstimator, TransformerMixin):
    def __init__(self):
        print('CreateNewFeaturer Init method: ')
        
    def fit(self, X, y=None):
        return self

    def transform(self, X_):
        X = X_.copy()
        X['age_class'] = X['Age']*X['Pclass']

        return X
    def fit_transform(self, X, y=None):
        return self.transform(X)

but i can't see it from get_config('X_train'), is it possible to add newly created feature by custom_pipeline into X_train?

thanks 

Jane

**Comment by Yard1** [comment]
The custom pipeline is applied at each CV step, and therefore is not visible in `X_train`.

**Comment by pycaret** [comment]
@Yard1 We will have to think about this for `2.3`. Since we are planning to apply all the transformations within CV, we will have to see how we can make everything available in `X_train`, `X_test` ... etc. etc.

**Comment by Yard1** [comment]
I do have an idea for it - we can just dynamically apply the transformations on the dataset whenever the user asks for X_train.
