### ISSUE TITLE
Lightgbm fails in PyCaret regression

### ISSUE THREAD

**Issue by OleksiyAnokhin** [pycaret/pycaret#904]
Hi team, have some issues with `lightgbm` in regression. 

`import pycaret`
`from pycaret.regression import *`
`mlb_pycaret = setup(data = pycaret_df, target = 'pts', train_size = 0.8, session_id = 123)`

`lightgbm_model = create_model('lightgbm', fold = 10)` gives me all zeros. Other models work fine. 

![image](https://user-images.githubusercontent.com/24446791/100847770-d708d480-3445-11eb-97a0-a7ff57141487.png)

**Comment by OleksiyAnokhin** [comment]
Other models works just fine. 
![image](https://user-images.githubusercontent.com/24446791/100847865-f7389380-3445-11eb-9e2e-80a7a0acf150.png)

Also tried this and failed too
![image](https://user-images.githubusercontent.com/24446791/100847899-04ee1900-3446-11eb-8549-ced1be8de807.png)

**Comment by Yard1** [comment]
Would it be possible for you to share the dataset?

**Comment by pycaret** [comment]
@OleksiyAnokhin Whats the version of your lightgbm?

**Comment by OleksiyAnokhin** [comment]
> Would it be possible for you to share the dataset?

@Yard1, this is a simple baseball dataset. Pretty big, so not sure if it is worth of it. 

Interestingly enough, initially the model worked on my colab, but when I tried to use it for other subsetted datasets, it failed
![image](https://user-images.githubusercontent.com/24446791/100911567-0561d080-3495-11eb-8437-8db53c36f82f.png)

The model also works as a part of a broad comparison, but not individually
![image](https://user-images.githubusercontent.com/24446791/100911734-38a45f80-3495-11eb-971e-29f957045846.png)

I am a big fan of PyCaret and use it often, but never had this problem. Plus several other models work fine with `create_model`.

**Comment by OleksiyAnokhin** [comment]
> @OleksiyAnokhin Whats the version of your lightgbm?

Found existing installation: lightgbm 2.2.3
    **Uninstalling lightgbm-2.2.3:
      Successfully uninstalled lightgbm-2.2.3**
Successfully installed feature-selector-1.0.0 **lightgbm-2.1.1** matplotlib-2.1.2 numpy-1.14.5 pandas-0.23.1 scikit-learn-0.19.1 seaborn-0.8.1

**Comment by Yard1** [comment]
I'd like to ask for the dataset again, if it's not confidential. It's quite hard to debug otherwise. Can you also post the `logs.log` file created in the directory from which the notebook/script is ran?

**Comment by actcod01** [comment]
#### pycaret - 2.2.2
##### dataset used : Diamond
____
I have checked, `lightgbm` has some issues with regression task

![image](https://user-images.githubusercontent.com/67143298/100994633-cb6bf980-357c-11eb-9afd-0421ba08a107.png)

**Comment by pycaret** [comment]
@actcod01 I cannot reproduce this issue. I just did a fresh installation on colab and it just works fine. Here is the code you can use to reproduce this:

```
# pip install pycaret

from pycaret.datasets import get_data
data = get_data('diamond')

from pycaret.regression import *
s = setup(data, target = 'Price', session_id = 213)

lightgbm = create_model('lightgbm')

plot_model(lightgbm)

```

![image](https://user-images.githubusercontent.com/58118658/101017186-bfaa1400-3537-11eb-998a-58f007f43f90.png)

![image](https://user-images.githubusercontent.com/58118658/101017203-c5075e80-3537-11eb-9552-f8338b6b48f8.png)

Let me know your thoughts.

**Comment by OleksiyAnokhin** [comment]
@Yard1, thanks, I will ask my project team and might share the dataset. Nothing confidential there, just it is a team project. 
@pycaret, @actcod01, thanks for looking into this!

**Comment by OleksiyAnokhin** [comment]
Team, I ran my code from scratch and LGBM regression worked this time. So it is definitely not my dataset.
![image](https://user-images.githubusercontent.com/24446791/101127452-36402380-35c3-11eb-9468-b66eac51037e.png)
I think it is the issue with `!pip install` on Colab ( I do it everytime). But still good fot you to know and be aware.

**Comment by Yard1** [comment]
We cannot really change how Colab works, I'm afraid. Thank you for taking the time to figure this out.

**Comment by pycaret** [comment]
Thanks, @OleksiyAnokhin for confirming.

Thanks, @Yard1 for your help.
