### ISSUE TITLE
Issue in Xgboost in pycaret 2.2

### ISSUE THREAD

**Issue by atwahsz** [pycaret/pycaret#905]
When trying to do regression 
On Xgboost I get this error in both GPU and non GPU
XGBoostError: need to call fit or load_model beforehand

**Comment by Yard1** [comment]
Would it be possible for you to share the notebook and the dataset?

**Comment by atwahsz** [comment]
Im using sklearn breast cancer dataset

**Comment by atwahsz** [comment]
In pycaret 2.1 the regression runs smoothly for the same dataset

**Comment by Yard1** [comment]
Can you share the code?

**Comment by atwahsz** [comment]
I tried to recreate the problem in Google colab but everything ran smoothly ! .

The system in which I have the problem runs on python 3.6.x

**Comment by pycaret** [comment]
@atwahsz This seems like an issue with your local installation. We suggest create a separate conda environment and install pycaret==2.2.2 from scratch. You can follow the instructions here: https://pycaret.readthedocs.io/en/latest/installation.html
