### ISSUE TITLE
Feature request get_config("setup_config")

### ISSUE THREAD

**Issue by blanpa** [pycaret/pycaret#906]
**Is your feature request related to a problem? Please describe.**
I think it would be useful for non-notebook environments like streamlit to get the Setup Config as a panda dataframe.

**Describe the solution you'd like**
`get_config("setup_config")`

return pd.dataframe

**Describe alternatives you've considered**
via `get_config("experiment__")[0]`

```
import pandas as pd
import io
data = io.StringIO(str(.get_config("experiment__")[0]))
df = pd.read_csv(data, sep=",")
df
```

**Comment by pycaret** [comment]
@pa-blan Thanks. Will tag this as an enhancement for future release.

**Comment by pycaret** [comment]
@Yard1 FYI

**Comment by Yard1** [comment]
We can just hook it up to the display container tbh, if it's not already

**Comment by Yard1** [comment]
With commit 314848a4b15221e6ac7d9c95b6ad88929df8e094, the `setup` dataframe can now be obtained with `pull()`, like the dataframes displayed by other functions.

**Comment by pycaret** [comment]
@pa-blan Can you please test this?

**Comment by ngupta23** [comment]
@blanpa , we will close out this issue for now. Please feel free to reopen if the issue persists.
