### ISSUE TITLE
Too many mandatory dependencies

### ISSUE THREAD

**Issue by jamesmyatt** [pycaret/pycaret#908]
**Is your feature request related to a problem? Please describe.**

There are too many heavyweight mandatory dependencies. For example, is it mandatory to have lightgbm, catboost and xgboost when you have an image classification problem? Do you really need spacy and nltk even when you're doing anything involving natural language? Do you really need ipython and other notebook-oriented dependencies when running something in batch mode?

https://github.com/pycaret/pycaret/blob/master/requirements.txt

**Describe the solution you'd like**

Most libraries should be optional dependencies, following an approach like pandas, i.e. ImportError raised only at the time that the dependency is used, along with clear documentation: https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html?highlight=install#dependencies

R caret also has a minimal list of mandatory dependencies, but a long list of suggestions: https://cran.r-project.org/web/packages/caret/index.html

**Describe alternatives you've considered**

N/A

**Additional context**

This is a very interesting project and I'd like to try it out, but the list of mandatory dependencies is off-putting.

**Comment by Yard1** [comment]
Improving modularity and decreasing the amount of mandatory dependencies is something we are planning to do in the future.
