### ISSUE TITLE
"ValueError: feature_names mismatch" while use predict_model()

### ISSUE THREAD

**Issue by traveler000** [pycaret/pycaret#909]
unlike the formal issue https://github.com/pycaret/pycaret/issues/387 ,I can use compare_models(), but cannot use predict_model
![image](https://user-images.githubusercontent.com/66821033/101107415-3c5af200-360d-11eb-8029-208239416a43.png)
![image](https://user-images.githubusercontent.com/66821033/101107460-5268b280-360d-11eb-9321-2271522df9e2.png)
![image](https://user-images.githubusercontent.com/66821033/101107754-ecc8f600-360d-11eb-957a-dbb9d19573dc.png)
pycaret version 2.2.2
And the old version did not have this problem( I have used same code in version2.1 )

**Comment by Yard1** [comment]
It would be very helpful if you could provide the full exception traceback, with the line number and such.

**Comment by traveler000** [comment]
> It would be very helpful if you could provide the full exception traceback, with the line number and such.

![image](https://user-images.githubusercontent.com/66821033/101165964-7b6f5e80-3672-11eb-8eea-f9d44ce0a715.png)

**Comment by Yard1** [comment]
Is it possible to show the entire code?

**Comment by traveler000** [comment]
> Is it possible to show the entire code?
![image](https://user-images.githubusercontent.com/66821033/101166841-e79e9200-3673-11eb-9590-51b616c46af8.png)
i'm sorry , i'm greenhand in github 
it seems that the feature order was not well organized cause the feature_name is the same, and i used the same dataset

**Comment by Yard1** [comment]
What about the code used to create the model? Including `setup()`.

**Comment by traveler000** [comment]
> What about the code used to create the model? Including `setup()`.
![image](https://user-images.githubusercontent.com/66821033/101171807-43b8e480-367b-11eb-927c-e622f26fcb76.png)
![image](https://user-images.githubusercontent.com/66821033/101171886-5e8b5900-367b-11eb-9106-413f5eb2b38a.png)
And I used save_model(final_xg,'./final') 
The "final" mentioned before is from load_model('./final')
These codes have run well in pycaret2.1

**Comment by Yard1** [comment]
Are you loading and using a model created on an older version of PyCaret?

**Comment by traveler000** [comment]
> Are you loading and using a model created on an older version of PyCaret?

No, this model was created on pycaret2.2.2 , but the same code used well in 2.1

**Comment by Yard1** [comment]
I imagine it is not possible for you to share the dataset, correct?

**Comment by traveler000** [comment]
I just update the pycaret and run the same code again ,in another folder...

**Comment by traveler000** [comment]
> I imagine it is not possible for you to share the dataset, correct?

I'm sorry , I cannot share the dataset .
Maybe I can try to  reproduce the error in other dataset?

**Comment by Yard1** [comment]
Would it be possible to at least share the dataset with just the column names and one row with random values that match the data types? The column names are what's the most important here.

**Comment by traveler000** [comment]
I found my mistake ,before I saved the model I have run this script to draw a 10-fold ROC curve
![image](https://user-images.githubusercontent.com/66821033/101231350-916a3700-36e5-11eb-9131-93671b8a8456.png)
![image](https://user-images.githubusercontent.com/66821033/101231212-aabeb380-36e4-11eb-8aa2-2a4b1c734922.png)
It would be fine to save the model earlier, but I cannot explain why this did not happen in the previous version
