### ISSUE TITLE
Adding a custom wrapped Scikit learner to the PyCaret framework

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#91]
Can I add a custom (proprietary) model that has already been wrapped into Scikit-learn into the PyCaret framework (for regression and classification)? 

Reference: [Discussion on LinkedIn](https://www.linkedin.com/feed/update/urn:li:ugcPost:6661097050945519616?commentUrn=urn%3Ali%3Acomment%3A%28ugcPost%3A6661097050945519616%2C6661456303426191360%29)

**Comment by pycaret** [comment]
@ngupta23 There is no functionality for custom object but it should not be a problem if its already wrapped around sklearn API but I think other dependencies will not work with that for example yellowbricks in plot_model won't work and shap in interpret_model will not work etc. We have to think a little bit about broader implications.

Maybe 3 - 4 releases down the road we can pick this up.

**Comment by ngupta23** [comment]
Yes, that makes sense. I think it might still work with yellowbrick, but not sure about the SHAP functionality yet. I am also fairly new to wrapping custom models in scikit so will probably know better in a few weeks, once I have played more with it.

**Comment by pycaret** [comment]
Tagging this as enhancement.

**Comment by pycaret** [comment]
### Feature now available in pycaret-nightly.

You can install pycaret-nightly using "pip install pycaret-nightly".

You can now use custom model objects in **create_model** function. The custom model must be compatible with fit_predict API used by sklearn.

Can you please test this and close the issue if the enhancement addresses the original issue.

It will be shipped to PyCaret 2.0x in few weeks.
