### ISSUE TITLE
PicklingError: Can't pickle <function Styler.apply.<locals>.<lambda> at 0x7f2666835e18>: it's not found as pandas.io.formats.style.Styler.apply.<locals>.<lambda>

### ISSUE THREAD

**Issue by gm039** [pycaret/pycaret#913]
Hi,

I am getting an error in saving the configuration file using save_config('Setup_config'). Although it saves the Setup_config file but also throws the below error.

Not sure if it because of Pycaret?

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
AttributeError                            Traceback (most recent call last)
/usr/lib/python3.6/pickle.py in save_global(self, obj, name)
    917             module = sys.modules[module_name]
--> 918             obj2, parent = _getattribute(module, name)
    919         except (ImportError, KeyError, AttributeError):

31 frames
/usr/lib/python3.6/pickle.py in _getattribute(obj, name)
    265             raise AttributeError("Can't get local attribute {!r} on {!r}"
--> 266                                  .format(name, obj))
    267         try:

AttributeError: Can't get local attribute 'Styler.apply.<locals>.<lambda>' on <function Styler.apply at 0x7f269df7a048>

During handling of the above exception, another exception occurred:

PicklingError                             Traceback (most recent call last)
<ipython-input-24-7d43677c5f20> in <module>()
      1 
      2 
----> 3 save_config('Setup_config')
      4 

/usr/local/lib/python3.6/dist-packages/pycaret/classification.py in save_config(file_name)
   2537     """
   2538 
-> 2539     return pycaret.internal.tabular.save_config(file_name=file_name)
   2540 
   2541 

/usr/local/lib/python3.6/dist-packages/pycaret/internal/tabular.py in save_config(file_name)
   9521     import pycaret.internal.utils
   9522 
-> 9523     return pycaret.internal.utils.save_config(file_name, globals())
   9524 
   9525 

/usr/local/lib/python3.6/dist-packages/pycaret/internal/utils.py in save_config(file_name, globals_d)
    134     import joblib
    135 
--> 136     joblib.dump(globals_to_dump, file_name)
    137 
    138     logger.info(f"Global variables dumped to {file_name}")

/usr/local/lib/python3.6/dist-packages/joblib/numpy_pickle.py in dump(value, filename, compress, protocol, cache_size)
    478     elif is_filename:
    479         with open(filename, 'wb') as f:
--> 480             NumpyPickler(f, protocol=protocol).dump(value)
    481     else:
    482         NumpyPickler(filename, protocol=protocol).dump(value)

/usr/lib/python3.6/pickle.py in dump(self, obj)
    407         if self.proto >= 4:
    408             self.framer.start_framing()
--> 409         self.save(obj)
    410         self.write(STOP)
    411         self.framer.end_framing()

/usr/local/lib/python3.6/dist-packages/joblib/numpy_pickle.py in save(self, obj)
    280             return
    281 
--> 282         return Pickler.save(self, obj)
    283 
    284 

/usr/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    474         f = self.dispatch.get(t)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return
    478 

/usr/lib/python3.6/pickle.py in save_dict(self, obj)
    819 
    820         self.memoize(obj)
--> 821         self._batch_setitems(obj.items())
    822 
    823     dispatch[dict] = save_dict

/usr/lib/python3.6/pickle.py in _batch_setitems(self, items)
    845                 for k, v in tmp:
    846                     save(k)
--> 847                     save(v)
    848                 write(SETITEMS)
    849             elif n:

/usr/local/lib/python3.6/dist-packages/joblib/numpy_pickle.py in save(self, obj)
    280             return
    281 
--> 282         return Pickler.save(self, obj)
    283 
    284 

/usr/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    474         f = self.dispatch.get(t)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return
    478 

/usr/lib/python3.6/pickle.py in save_list(self, obj)
    779 
    780         self.memoize(obj)
--> 781         self._batch_appends(obj)
    782 
    783     dispatch[list] = save_list

/usr/lib/python3.6/pickle.py in _batch_appends(self, items)
    803                 write(MARK)
    804                 for x in tmp:
--> 805                     save(x)
    806                 write(APPENDS)
    807             elif n:

/usr/local/lib/python3.6/dist-packages/joblib/numpy_pickle.py in save(self, obj)
    280             return
    281 
--> 282         return Pickler.save(self, obj)
    283 
    284 

/usr/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    519 
    520         # Save the reduce() output and finally memoize the object
--> 521         self.save_reduce(obj=obj, *rv)
    522 
    523     def persistent_id(self, obj):

/usr/lib/python3.6/pickle.py in save_reduce(self, func, args, state, listitems, dictitems, obj)
    632 
    633         if state is not None:
--> 634             save(state)
    635             write(BUILD)
    636 

/usr/local/lib/python3.6/dist-packages/joblib/numpy_pickle.py in save(self, obj)
    280             return
    281 
--> 282         return Pickler.save(self, obj)
    283 
    284 

/usr/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    474         f = self.dispatch.get(t)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return
    478 

/usr/lib/python3.6/pickle.py in save_dict(self, obj)
    819 
    820         self.memoize(obj)
--> 821         self._batch_setitems(obj.items())
    822 
    823     dispatch[dict] = save_dict

/usr/lib/python3.6/pickle.py in _batch_setitems(self, items)
    845                 for k, v in tmp:
    846                     save(k)
--> 847                     save(v)
    848                 write(SETITEMS)
    849             elif n:

/usr/local/lib/python3.6/dist-packages/joblib/numpy_pickle.py in save(self, obj)
    280             return
    281 
--> 282         return Pickler.save(self, obj)
    283 
    284 

/usr/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    474         f = self.dispatch.get(t)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return
    478 

/usr/lib/python3.6/pickle.py in save_list(self, obj)
    779 
    780         self.memoize(obj)
--> 781         self._batch_appends(obj)
    782 
    783     dispatch[list] = save_list

/usr/lib/python3.6/pickle.py in _batch_appends(self, items)
    806                 write(APPENDS)
    807             elif n:
--> 808                 save(tmp[0])
    809                 write(APPEND)
    810             # else tmp is empty, and we're done

/usr/local/lib/python3.6/dist-packages/joblib/numpy_pickle.py in save(self, obj)
    280             return
    281 
--> 282         return Pickler.save(self, obj)
    283 
    284 

/usr/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    474         f = self.dispatch.get(t)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return
    478 

/usr/lib/python3.6/pickle.py in save_tuple(self, obj)
    734         if n <= 3 and self.proto >= 2:
    735             for element in obj:
--> 736                 save(element)
    737             # Subtle.  Same as in the big comment below.
    738             if id(obj) in memo:

/usr/local/lib/python3.6/dist-packages/joblib/numpy_pickle.py in save(self, obj)
    280             return
    281 
--> 282         return Pickler.save(self, obj)
    283 
    284 

/usr/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    474         f = self.dispatch.get(t)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return
    478 

/usr/lib/python3.6/pickle.py in save_global(self, obj, name)
    920             raise PicklingError(
    921                 "Can't pickle %r: it's not found as %s.%s" %
--> 922                 (obj, module_name, name))
    923         else:
    924             if obj2 is not obj:

PicklingError: Can't pickle <function Styler.apply.<locals>.<lambda> at 0x7f2666835e18>: it's not found as pandas.io.formats.style.Styler.apply.<locals>.<lambda>

**Comment by Yard1** [comment]
Thanks, will look into it. Is it possible for you to share the entire notebook/script?

**Comment by Yard1** [comment]
I just pushed commit c192ed7144658cc2f17e17363aa256a4fa36fc4b that should fix this issue. Could you run
`pip install --upgrade --user git+git://github.com/pycaret/pycaret.git` to install PyCaret's development version and try again?

**Comment by pycaret** [comment]
@gm039 Can you please test if the issue is resolved?

**Comment by gm039** [comment]
Thanks! The issue is resolved now.
