### ISSUE TITLE
Add a custom metrics to compare_models(), and other functions such as create_model, tune_models etc

### ISSUE THREAD

**Issue by JianWang2016** [pycaret/pycaret#914]
Hi, Any advice on the following questions is greatly appreciated.

Unbalanced data for binary classification.
1) add specificity as a custom metric to compare_models()'s output.

2) Any support from pycaret to use a different threshold than probability = 0.5 to get the crisp label

3) If I want to control specificity as 0.9, for example, is there a way to set it so the other metrics would be adjusted based on the specificity

Thanks much.

**Comment by Yard1** [comment]
You can add sklearn-compatible metrics using the `add_metric()` function. Metrics added that way will be calculated and visible in every function.

Unfortunately, in order to have metrics depend on another metric, you would need to create your own versions of the metrics and add them with `add_metric()`.

You can change the threshold when using `predict_model()` with the `probability_threshold` argument.

**Comment by pycaret** [comment]
@JianWang2016 You can read more about `add_metric`, `remove_metric` in the documentation here

You can pass the `probability_threshold` in the `predict_model` function as @Yard1 mentioned.

add_metric documentation: https://pycaret.readthedocs.io/en/latest/api/classification.html#pycaret.classification.add_metric

predict_model documentation: https://pycaret.readthedocs.io/en/latest/api/classification.html#pycaret.classification.predict_model

**Comment by Luoyunsong** [comment]
Hello, I want to know why I added precision and recall of sklearn, but the result is different from that of pycaret, while ACC, MCC and kappa are the same.
![1](https://user-images.githubusercontent.com/33373798/102014709-54abd900-3d92-11eb-998f-a6ef163cc9b5.png)
![2](https://user-images.githubusercontent.com/33373798/102014710-56759c80-3d92-11eb-9c1e-918f94a26950.png)

**Comment by Luoyunsong** [comment]
@Yard1 @pycaret

**Comment by Yard1** [comment]
Is this for multilabel classification?

**Comment by Luoyunsong** [comment]
No， it is a binary classification

**Comment by Yard1** [comment]
Please make sure PyCaret is up to date with `pip install -U pycaret`.
