### ISSUE TITLE
Mrs

### ISSUE THREAD

**Issue by JaneCuiQin** [pycaret/pycaret#915]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JaneCuiQin** [comment]
Hi Team,
I am using the following data to do a simple prediction and then noticed that the Label and Scores has no relationships by even by using default cutoff =0.5 ( e.g scores with 0.9 , some of the label is 1 and some are 0 which are contradicted)

Please check and clarify


data = pd.read_csv('../data/titanic_raw.csv')
clf1 = setup(data = data, 
             target = 'Survived',
#              train_size = 0.99,
             numeric_features=['Pclass','Age', 'Fare','SibSp','Parch'],
             categorical_features = ['Sex'], 
             ignore_features = ['Name','Ticket','Cabin','PassengerId','Embarked','PassengerId'],
             custom_pipeline = transformer
            )
best = compare_models(sort='Recall', turbo=True)
pred = predict_model(best)


Jane

**Comment by Yard1** [comment]
The scores for binary classification are the probability of the chosen class, and not the probability of the positive class (what sklearn uses). For example, if the label is 0 and score is 0.9, then the probability of positive class (1) is 0.1.

**Comment by pycaret** [comment]
@JaneCuiQin Please read the documentation. As @Yard1 mentioned the score is the probability of the predicted class, not the positive class. 

![image](https://user-images.githubusercontent.com/58118658/101246514-dc824b00-36e1-11eb-8dfb-482bfe8474b2.png)

**Comment by JaneCuiQin** [comment]
Thanks Antoni!

Don’t understand why we not using Sklearn’s logic which is already known to lots of the users. The documentation it’s not very clear to explain the logic saying probability is only about predicted . as data scientist tend to treat their interested target as positive.

Jane
________________________________
发件人: Antoni Baum <notifications@github.com>
发送时间: 2020年12月5日 19:40
收件人: pycaret/pycaret <pycaret@noreply.github.com>
抄送: JaneCuiQin <cuiqin1234@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [pycaret/pycaret] Mrs (#915)


The scores for binary classification are the probability of the chosen class, and not the probability of the positive class (what sklearn uses). For example, if the label is 0 and score is 0.9, then the probability of positive class (1) is 0.1.

―
