### ISSUE TITLE
error while predicting on new data

### ISSUE THREAD

**Issue by sathishkumar999** [pycaret/pycaret#916]
Hi pycaret team!

we are trying to create an auto_ml by using pycaret as a wrapper.
it worked well to train the model and saving it on the server. but it's creating an issue while predicting on new data.
the new data is a single input value but not on batch data.

pls find the attachment
![Screenshot (584)](https://user-images.githubusercontent.com/40235632/101241380-79150f00-371b-11eb-8dd8-29bbb0227597.png)

**Comment by Yard1** [comment]
Are you sure that the data you are passing is indeed a pandas dataframe?

**Comment by sathishkumar999** [comment]
@Yard1 
thanks for immediate replay,
got the results buddy.

![Screenshot (585)](https://user-images.githubusercontent.com/40235632/101245646-3e6ba080-3734-11eb-877c-5f935c631fcf.png)

![Screenshot (583)](https://user-images.githubusercontent.com/40235632/101245773-395b2100-3735-11eb-8336-44b874811d56.png)

I have a small question, Instead of making a data frame for along with column name for testing. is it possible to predict the output.

Ex1 :  summary = "On Compass_M5_WebServers, Major: M5CAN_adcm5026 3 out of 3 transactions failed"
       new_doc = [summary]
       predict_new = predict_model(loaded_model, data = new_doc, encoded_labels = False)
       print(predict_new)

the reason I'm mentioning this, every time we have to mention testing column exactly which is trained in the model and have to make a data frame as it's for testing.
        
EX: loaded_model = load_model('one vs rest classifier')
    new_doc = pd.DataFrame({"summary":[summary]})
    predict_priority = predict_model(loaded_model, data = new_doc, encoded_labels = False)
 
if you see in the second line, I must have to mention summary column name in data frame which is trained. it should not be the case for single input. if you pass multilpe records then I can agree we need to mention testing column name as it is.

pls check my example one scenario.
hope you are getting me

**Comment by sathishkumar999** [comment]
Hi pycaret team,

Do you mean to say, It won't work. without data frame as input. sorry, it's just my concern. if there is a way, then it will be great.

thanks for helping me out, @Yard1 and to the pycaret team.
