### ISSUE TITLE
Q: optimize threshold understanding

### ISSUE THREAD

**Issue by Lion-Mod** [pycaret/pycaret#920]
Quick question regarding optimize threshold.

I'm working on a classification problem where like most, false negatives are a big no no.

I understand that I want to weight these as being "worse" if predicted incorrectly and ultimately minimise the loss function.

Using optimize threshold could someone explain how I would do this? (let's say tp, fp and tn are weighted equally).

Also looking at the example https://pycaret.org/optimize-threshold/ . Why would you give tn a positive number? This isn't trivial to me.

**Comment by pycaret** [comment]
@Lion-Mod Hi. You are right. Mostly the cost is associated with FP and FN however for the purpose of completeness the parameters for TP and TN are also available. If you want you can leave them blank.
