### ISSUE TITLE
Pull from s3 and specify folder

### ISSUE THREAD

**Issue by ericbugin** [pycaret/pycaret#922]
Hello, 

Can't find documentation on how to use the 'load_model' function to pull from s3 and specify the folder that the model is in.

**Comment by dmangonakis** [comment]
Hi @ericbugin,

[pycaret.regression.load_model](https://pycaret.readthedocs.io/en/latest/api/regression.html?highlight=load_model#pycaret.regression.load_model)

BR

**Comment by ericbugin** [comment]
Yeah I saw that documentation, and thanks for your reply. I get now that the model_name variable should include the entire path and file name.

Another issue I am running into: When I put the path into load_model it keeps generating random characters and adding them to the end of the path. 

For example:

model_location = "models/learning/pycaret_model/pycaret_model.pkl"
model = load_model(model_name=model_location,` platform='aws', authentication={'bucket':'syntasa-gov-01'})

FileNotFoundError: [Errno 2] No such file or directory: 'models/learning/pycaret_model/pycaret_model.pkl.5EeEfb3A'

FileNotFoundError: [Errno 2] No such file or directory: 'models/learning/pycaret_model/pycaret_model.pkl.7afaa6FB'

**Comment by pycaret** [comment]
@amjadraza Can you help on this one?

**Comment by dmangonakis** [comment]
@ericbugin: Make sure that the path `models/learning/pycaret_model` exists ... 

@pycaret: Yes, it correctly returns `models/lr-aws-sunday.pkl.514251d3` but it cannot be saved on the local file system.

I'm fixing it.

**Comment by pycaret** [comment]
@dmangonakis Would you like to make this change and submit a PR, please? Is this a problem for `aws` or other platforms `gcp`, `azure` as well?

@Yard1 Which branch @dmangonakis should submit PR to?

**Comment by Yard1** [comment]
@pycaret @dmangonakis Please submit PRs to `master`

**Comment by Yard1** [comment]
PR merged
