### ISSUE TITLE
CatBoost on GPU

### ISSUE THREAD

**Issue by TKassis** [pycaret/pycaret#925]
I have a large dataset and a powerful GPU, I've noticed that while using CatBoost enabling the GPU gives strange behavior after the 50,000 sample size mark (which is when the GPU kicks in according to PyCaret). The top plot is with GPU enabled, the bottom plot is with GPU disabled. 'Number of Scans' here refers to the number of training samples which are sampled randomly from a 350k dataset. Is this expected when enabling GPU training? If so, why?

![Layout 2](https://user-images.githubusercontent.com/9168908/101680926-63f7f300-3a2f-11eb-92fe-de8657e092e1.png)

**Comment by Yard1** [comment]
This would be a question to ask the Catboost authors, I am afraid. We do not change the behavior aside from making it switch to GPU mode above 50k samples (if `use_gpu=True`).

**Comment by pycaret** [comment]
@TKassis Thanks for reporting. As @Yard1 mentioned, would you like to open this issue with the Catboost repo? We can link up that issue here for other people having similar issues.

Thanks for your help!

**Comment by pycaret** [comment]
@TKassis Hi, Happy New Year! Were you able to log an issue with the `catboost` repo? Do you mind linking it here for future reference?

**Comment by TKassis** [comment]
Not yet

**Comment by ngupta23** [comment]
@TKassis, we will close out this issue for now. Please feel free to reopen if needed.

**Comment by XiangBu** [comment]
I set up use_gpu=True and it's weird when training lightgbm, it works while catboost doesn't.
