### ISSUE TITLE
How to save interpret_model() plots ?

### ISSUE THREAD

**Issue by Practcdi** [pycaret/pycaret#927]
### Pycaret - v2.2.0
_________________________

1) How to save **interpret_model() plots** like normal `save = True` ?
There is no method available for saving the SHAP plots on disk.

#### Required :+1: 

1) Save `interpret_model()`  plots on disk 
2) Need extra arguments like , `save=True & set PATH for dumping the plots at any location `

Thanks,

**Comment by pycaret** [comment]
@Practcdi Currently not possible. Would you like to work on this and include the functionality to save plots in the `interpret_model`. Please have a look at the codebase.

**Comment by Yard1** [comment]
Should be possible starting with commit 7e98fc54ce8e0936d030a3096d2f59f33f363c1f

**Comment by Practcdi** [comment]
> Should be possible starting with commit [7e98fc5](https://github.com/pycaret/pycaret/commit/7e98fc54ce8e0936d030a3096d2f59f33f363c1f)

So, Now is possible to save SHAP plots?

**Comment by Yard1** [comment]
No, not yet. But you can install the development version that allows it with `pip install -U git+https://github.com/pycaret/pycaret.git`.
