### ISSUE TITLE
"feature_selection_threshold / top_pick_features" is not working when feature_selection_method='boruta'

### ISSUE THREAD

**Issue by JosAndr** [pycaret/pycaret#929]
I'm testing this feature selection method,but when i change the value of feature_selection_threshold the selected features ans the models performance are the same for each threshold:
0.9
![image](https://user-images.githubusercontent.com/54367290/101933699-8f531d00-3baa-11eb-8d1a-ab36a1f40ef5.png)
![image](https://user-images.githubusercontent.com/54367290/101933734-9c700c00-3baa-11eb-9809-b3e286fef989.png)
![image](https://user-images.githubusercontent.com/54367290/101933870-c75a6000-3baa-11eb-8594-907dce8ec88b.png)

0.1
![image](https://user-images.githubusercontent.com/54367290/101934019-025c9380-3bab-11eb-91a8-2fbe46cbce9e.png)
![image](https://user-images.githubusercontent.com/54367290/101934050-0b4d6500-3bab-11eb-8de5-ed1f4f68817f.png)
![image](https://user-images.githubusercontent.com/54367290/101934099-1a341780-3bab-11eb-9a49-e05204c72e03.png)

0.03
![image](https://user-images.githubusercontent.com/54367290/101934264-57000e80-3bab-11eb-819a-a351d3d35730.png)
![image](https://user-images.githubusercontent.com/54367290/101934288-5ff0e000-3bab-11eb-9d97-182b131d7a3f.png)
![image](https://user-images.githubusercontent.com/54367290/101934351-772fcd80-3bab-11eb-845a-562afa0a636d.png)

I reviewed the code and the parameter is not passing in any place to the function

**Comment by pycaret** [comment]
@JosAndr I am guessing `feature_selection_threshold` will not work when `feature_selection_method` is not `classic`. However, I am not 100% sure if this was intentional.

**Comment by gm039** [comment]
Hi,

I am curious to know if this issue has been resolved? Does the feature_selection_threshold works with Boruta, now?
