### ISSUE TITLE
Anomaly Detection Parameters

### ISSUE THREAD

**Issue by brunobarella** [pycaret/pycaret#932]
Through the method of creating models in the anomaly detection package, it is not possible to change the value of the "contamination" parameter.
For the Local Outlier Factor method, it is not possible to access the "Novelty" parameter to work as a novelty detection.

**Comment by Yard1** [comment]
Thanks for the suggestion. Will add kwarg support to it, similar to other modules.

**Comment by Yard1** [comment]
It is possible to pass additional arguments to the model using keyword arguments, for example
```python
create_model(model="lof", contamination=0.05)
```

**Comment by brunobarella** [comment]
Correct however it is not working.

**Comment by brunobarella** [comment]
When the model parameters are printed, it remains with the default value of 0.05.

**Comment by Yard1** [comment]
I believe that could be an issue with the pyod library, but I will investigate. Do you have a sample code to reproduce?

**Comment by brunobarella** [comment]
When I use the create_model method with the contamination parameter it does not make the configuration.
![image](https://user-images.githubusercontent.com/28939189/102026535-2cfe4600-3d7d-11eb-9c9c-23b1309cc159.png)

The alternative I found to parameterize was to use the tune_model function:
![image](https://user-images.githubusercontent.com/28939189/102026717-31772e80-3d7e-11eb-8a83-aba5c812243b.png)


The other problem is for the novelty parameter that exists in the Sklearn library:
https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.LocalOutlierFactor.html
![image](https://user-images.githubusercontent.com/28939189/102026642-caf21080-3d7d-11eb-9f6c-5fbfa3647eab.png)

**Comment by Yard1** [comment]
Our LOF model is from the pyod library and not sklearn, so that is to be expected.

**Comment by Yard1** [comment]
@brunobarella the `contamination` parameter is set by `fraction` parameter of `create_model()`.

**Comment by pycaret** [comment]
@brunobarella If the issue is resolved, can yu please close it?

**Comment by brunobarella** [comment]
The problem with `contamination`parameter still exists.

**Comment by Yard1** [comment]
Even if you do `fraction`?

**Comment by brunobarella** [comment]
It worked with the faction parameter!

`create_model(model="lof", fraction=0.2)`
