### ISSUE TITLE
Pycaret: Anomaly Detection

### ISSUE THREAD

**Issue by sanjalchetu8055** [pycaret/pycaret#934]
Hi, I am working on anomaly detection using pycaret. I have got the visualization of the 3D graph but when I hover around the anomaly its shows 0,1, feature, and anomaly. Could anyone explain to me what is that?
![doubt](https://user-images.githubusercontent.com/63895873/102020169-4fa05700-3d9d-11eb-9e7b-50904c0bd975.png)

**Comment by pycaret** [comment]
@sanjalchetu8055 1 and 2 is the PCA value and Anomaly 1 or 0 represents the anomaly flag. 1 being outlier and 0 being inlier.

**Comment by sanjalchetu8055** [comment]
Thank you for the information. But what does 0 & feature represent?
