### ISSUE TITLE
Access to model expected input

### ISSUE THREAD

**Issue by thibaultdaoulas** [pycaret/pycaret#937]
Hi,

After loading a model, it would be very helpful to know what the expected input columns for the processing pipeline are. I was not able to find documentation about and could not access relevant members of the model while debugging.

I have new data coming in regularly that needs a forecast to be run on, and it occurs often that a few new variables appear, or features from the trained model no longer exist in the new dataset, and I would like to make that new data have the same format as the training data.

**Comment by thibaultdaoulas** [comment]
I have just found how to retrieve the columns needed : 
Given the loaded model m, these are the columns needed : m.named_sted['dtypes'].final_training_columns

Is this the right way to do so, or is there a less verbose method?

**Comment by Yard1** [comment]
In general, PyCaret excepts all columns that were present in the data that was passed in `setup()`. Lacking any of those columns n data to be predicted may (though it's not a hard rule) raise an exception. Any columns that were not present in `setup()` data are simply ignored.

**Comment by thibaultdaoulas** [comment]
Thank you for the info! Right, in my case it did raise an exception that the column was missing. I created an additional column filled with 0.
