### ISSUE TITLE
Different size of Features after Regression Setup 

### ISSUE THREAD

**Issue by brunobarella** [pycaret/pycaret#938]
Why the setup get 375 features but in dataset have 400?
![image](https://user-images.githubusercontent.com/28939189/102374732-7084ca00-3fa0-11eb-850b-2f1005bb2733.png)

**Comment by Yard1** [comment]
By default, features with perfect correlation are removed. You can change that behavior by passing `remove_perfect_collinearity=False` to `setup()`.

**Comment by brunobarella** [comment]
Worked perfectly.
