### ISSUE TITLE
Is it possible to use pycaret on multi nodes?

### ISSUE THREAD

**Issue by IncubatorShokuhou** [pycaret/pycaret#939]
I have several  Intel(R) Xeon(R) Silver 4210 CPU managed by a slurm system. Each of the CPU node is rather small and it is very slow to train a model on a single node using pycaret.
So,I am wonderinf if it is possible to use pycaret on multi nodes,instead of on a single node. For example, is it possible to use dask or mpi4py when training multi jobs?

**Comment by Yard1** [comment]
This is something we are planning to add support for in the future.
