### ISSUE TITLE
setup() inferring wrong data types

### ISSUE THREAD

**Issue by ericbrownaustin** [pycaret/pycaret#940]
I have tried to use setup() to split a data set that is all either int64 or float64 (per pandas.dataFrame.dtypes).  Data set has 44 columns.  Setup() infers only 6 of the columns as numeric with the rest as categorical or label.

`clf = setup(data = dat2, target = 'transactionSessions', train_size = 0.7)`
![py1](https://user-images.githubusercontent.com/11723172/102579186-98b81a00-40c1-11eb-8782-c17ac24c04f4.jpg)
![py2](https://user-images.githubusercontent.com/11723172/102579192-9ce43780-40c1-11eb-9b52-017376a905dc.jpg)

**Comment by Yard1** [comment]
In case pycaret fails to determine the column type properly, please pass `categorical_feautres = []` and `numerical_features=[]` to `setup()` with the lists containing the names of the columns of a given type.

**Comment by pycaret** [comment]
@ericbrownaustin Please close this issue if your problem is resolved 👍
