### ISSUE TITLE
custom_pipeline not apply transformations 

### ISSUE THREAD

**Issue by JosAndr** [pycaret/pycaret#941]
I would like to use a custom pipeline, i first test it with a couple of common transformations but they are not getting applied to 
the features

![image](https://user-images.githubusercontent.com/54367290/102632108-97680b00-411c-11eb-9e39-3c2bb46576ef.png)

![image](https://user-images.githubusercontent.com/54367290/102631940-5bcd4100-411c-11eb-86d2-63d24eabfd9c.png)

![image](https://user-images.githubusercontent.com/54367290/102631984-6556a900-411c-11eb-99d0-156b935dabe1.png)

![image](https://user-images.githubusercontent.com/54367290/102632012-70a9d480-411c-11eb-9df3-548021c42135.png)
If i leave preprocess=True they aren't neither getting applied

Peprocess= True, not custom pipeline
![image](https://user-images.githubusercontent.com/54367290/102632445-1cebbb00-411d-11eb-8fbd-444c1deb36cb.png)
![image](https://user-images.githubusercontent.com/54367290/102632505-34c33f00-411d-11eb-93e3-93f3e525dc54.png)

Peprocess= True, custom pipeline

![image](https://user-images.githubusercontent.com/54367290/102632639-5a504880-411d-11eb-8269-efb440c5c3e6.png)
![image](https://user-images.githubusercontent.com/54367290/102632592-4d335980-411d-11eb-9afa-9c56362d7f32.png)

**Comment by JosAndr** [comment]
I also would like to knwo if its possible to change the  steps Pycaret internal pipeline

**Comment by Yard1** [comment]
Custom pipeline steps are applied during cross validation for every fold and thus will not be visible in data obtained with `get_config`.

**Comment by JosAndr** [comment]
> Custom pipeline steps are applied during cross validation for every fold and thus will not be visible in data obtained with `get_config`.

Alrigth,
Another question out of nowhere in this topic: can you use Pycaret to do nested cross-validation?

**Comment by Yard1** [comment]
You can use any sklearn-API cross validation generator.

**Comment by JosAndr** [comment]
Ok, i'm going to close this

**Comment by AlvaroMatsuda** [comment]
Hi, I would like to know if it's possible to access the transformed dataframe when we use custom_pipeline?
