### ISSUE TITLE
How to differentiate between sklearn model and pycaret model?

### ISSUE THREAD

**Issue by hbaniecki** [pycaret/pycaret#942]
Hi, I would like to differentiate a typical model made with the `sklearn` module, from the `pycaret` model. This is to know for sure that `predict_model` needs to be used. Is there any hidden attribute in the model instance that could be used for finding the origin?

![image](https://user-images.githubusercontent.com/32574004/102691428-c9f13100-420c-11eb-982e-b382433a8642.png)

**Comment by Yard1** [comment]
There is no difference. Pycaret uses sklearn underneath. If you want to use the model outside PyCaret, run `finalize_model()` to retrain it on all data and then you will be left with a normal sklearn object.

**Comment by hbaniecki** [comment]
I am aware that `pycaret` uses `sklearn` underneath. 

It would be useful to have any hidden property so that the user can check the origin of the model (e.g. `model._pycaret is not None`). `finalize_model()` doesn't help, since afaik it forgets the pipeline.

![image](https://user-images.githubusercontent.com/32574004/102691932-623ce500-4210-11eb-9425-a2f16af20d4f.png)

**Comment by Yard1** [comment]
You can get the pipeline with `finalize_model(model, model_only=False)`.

I'm not sure what the use case would be for this. Could you explain how this functionality would help you?

**Comment by hbaniecki** [comment]
Ofc: I was trying to add native support for `pycaret` models to [`dalex`](https://github.com/ModelOriented/DALEX/tree/master/python/dalex). The package would automatically detect when to use a custom predict, which would return only `numpy` array (something around `predict_model(m, d, verbose=False)['Score'].values`). 

Anyway, Thanks! `model_only=False` works for me, since the `sklearn` API is convenient.
