### ISSUE TITLE
sklearn's logloss with in multiclass problem

### ISSUE THREAD

**Issue by minkim88** [pycaret/pycaret#943]
Hi, I greatly appreciate your hard work for this amazing library.

I saw the example of using sklearn's log_loss metric in pycaret and tried with a multiclass classification dataset and it doesn't seem to work. 

1. When I run the compare_model() function it works fine at first.
1. When I run the compare_model() function, after running the "add_metric('logloss', 'LogLoss', log_loss, greater_is_better=False)" function, it returns an empty set.
2.Then, when I run the tune_model() function, it gives an error "y_true and y_pred contain different number of classes 6, 2"

My dataset is a 6 class classification problem. As far as I know, log_loss function works well with multiclass problems.
The setup function returns "Target Type | Multiclass" , so it does know that I'm on a multiclass problem, but it doesn't seem to work with the sklearn.metrics.log_loss function.

Am I doing something wrong? Is there a way around this problem?

**Comment by Yard1** [comment]
Can you send us the logs.log file generated in the folder form where you ran the script/notebook?

**Comment by minkim88** [comment]
[logs.log](https://github.com/pycaret/pycaret/files/5720549/logs.log)

**Comment by minkim88** [comment]
I just tried using 

**add_metric('logloss', 'LogLoss', log_loss, greater_is_better=False)**

with the **< Multiclass Classification Tutorial (MCLF101) - Level Beginner >**  example on your github and it doesn't work.

Is there another parameter that I should set to use  sklearn.metrics.log_loss function in multiclass problems?

Thanks.

**Comment by Yard1** [comment]
`ValueError: y_true and y_pred contain different number of classes 6, 2. Please provide the true labels explicitly through the labels argument. Classes found in y_true: [0 1 2 3 4 5]`

This is the exception. It would appear had you tried using logloss without PyCaret, as all we are doing is passing it to sklearn objects and methods. The fix would be to modify `add_metric` like so:

```python

**Comment by minkim88** [comment]
Sorry but it doesn't work.
It raises an error
**ValueError: The number of classes in labels is different from that in y_pred. Classes found in labels: [0 1 2 3 4 5]**

I just found what works. It works when I set **labels = [0,1]**
My guess is that it's because pycaret internally uses one vs rest method.

The problem now is that the logloss value is way higher than what I've been seeing before using sklearn cross_val_score function.
Way higher meaning more that x2. (Using same fold number, same feature, same(at least very similar) hyperparameters)

Please tell me if you know a solution or at least why this is happening

**Comment by Yard1** [comment]
I am not sure why it would be different, as we use sklearn's `cross_validate` function underneath the hood. Could you maybe share the full code you are using to compare the two scores?

**Comment by minkim88** [comment]
Sorry for the late response.

Here's the full code.

from sklearn import datasets
from sklearn.metrics import log_loss
from sklearn.model_selection import cross_val_score
import catboost
import xgboost
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold

wine = datasets.load_wine()
winedata = pd.DataFrame(wine.data)
winedata['target'] = wine.target

exp = setup(data = winedata, target = 'target', session_id=123) 

add_metric('logloss', 'LogLoss', log_loss, greater_is_better=False, labels = [0,1])

compare_models(include = ['rf','xgboost','catboost'])

rf_acc=cross_val_score(estimator=RandomForestClassifier(),
                           X = winedata.drop(columns='target'),
                           y = winedata.target,
                           cv = StratifiedKFold(n_splits = 10),
                           scoring='accuracy')

xgb_acc=cross_val_score(estimator=(xgboost.XGBClassifier(verbosity = 0)),
                            X = winedata.drop(columns='target'),
                            y = winedata.target,
                            cv = StratifiedKFold(n_splits = 10),
                            scoring='accuracy')

cat_acc=cross_val_score(estimator=catboost.CatBoostClassifier(verbose=False),
                            X = winedata.drop(columns='target'),
                            y = winedata.target,
                            cv = StratifiedKFold(n_splits = 10),
                            scoring='accuracy')

rf_logloss=cross_val_score(estimator=RandomForestClassifier(),
                           X = winedata.drop(columns='target'),
                           y = winedata.target,
                           cv = StratifiedKFold(n_splits = 10),
                           scoring='neg_log_loss')

xgb_logloss=cross_val_score(estimator=(xgboost.XGBClassifier(verbosity = 0)),
                            X = winedata.drop(columns='target'),
                            y = winedata.target,
                            cv = StratifiedKFold(n_splits = 10),
                            scoring='neg_log_loss')

cat_logloss=cross_val_score(estimator=catboost.CatBoostClassifier(verbose=False),
                            X = winedata.drop(columns='target'),
                            y = winedata.target,
                            cv = StratifiedKFold(n_splits = 10),
                            scoring='neg_log_loss')



![image](https://user-images.githubusercontent.com/39758422/103187580-33a5c500-4908-11eb-8591-8884b4baae86.png)

![image](https://user-images.githubusercontent.com/39758422/103187585-3d2f2d00-4908-11eb-8092-fd79d47446b5.png)


You see that accuracy differs a little, and logloss differs a lot.

Moreover, it's not very intuitive that you have to set 
**labels = [0,1]** in 
**add_metric('logloss', 'LogLoss', log_loss, greater_is_better=False, labels = [0,1])**
in a multiclass classification problem.

**Comment by Yard1** [comment]
Ok, the issue is that `neg_log_loss` targets prediction probability and not predictions. We cannot automatically determine that when creating the metric, so the user needs to explicitly pass the `target` parameter in `add_metric`.

```python
add_metric('logloss', 'LogLoss', log_loss, greater_is_better=False, target="pred_proba")
```

This will work and give the same results as pure sklearn.

**Comment by minkim88** [comment]
Very nice! It works!

I should have read the document more thoroughly.

Thanks again for the help!
