### ISSUE TITLE
Proper way to use the newly-added fit_kwargs for the classification compare_models routine

### ISSUE THREAD

**Issue by jtrenkle** [pycaret/pycaret#944]
I have been using `pycaret` for the last several months with great outcomes, so thanks for that.  

The current issue is as follows:  I am using compare_models to determine the Top 5 algos for my task, but I have noticed that
`XGBoost` is taking more time to run than all of the other techniques combined.  In digging, I found a recommendation to set it to _hist_ mode for a dramatic speed-up; however, changing this parameter in the context of _compare_models_ seems like it can only be achieved using the very recently added *fit_kwargs* field. I see that it's a dict, but my question is, what does that map look for setting a particular parameter for a specific algo? 

My current call looks like this: 

```
top5Models = compare_models(exclude=excludeAlgs,   # May be empty
                                sort='MCC',        # 'Precision',
                                fold=kFolds,
                                turbo=True,
                                verbose=True,
                                n_select=topN
                                fit_kwargs={
                                   'xgboost':{"tree_method":"hist"}
                                 }
                               )

```

I have been unable to find any explicit examples, what I have here does _not_ work, so how should that look? 

Thanks for any help in advance.

**Comment by Yard1** [comment]
`fit_kwargs` will be applied to every model, so this will most likely cause an exception. Furthermore, `tree_method` is not a `fit` argument but rather a model parameter. What you could do, however, is to use the `include` parameter of `compare_models` in conjunction with `models(internal=True)` to create a modified version of xgboost while keeping everything else the same.

```python
models_list = models(internal=True)
xgboost_model = models_list.loc["xgboost"] # get the xgboost entry
# we can pass both string ids and model objects to compare_models(include=
models_list = [x for x in models_list[models_list["Special"] == False].index if x not in excludeAlgs + ["xgboost"]] # exclude cannot be used together with include

xgboost_args = xgboost_model["Args"] # grab PyCaret arguments for xgboost to ensure everything is the same
xgboost_args["tree_method"] = "hist" # replace tree method param
xgboost_model = xgboost_model["Class"](**xgboost_model["Args"]) # instantiate the object with the args
models_list.append(xgboost_model) # append the new xgboost object to the string ids list

top5Models = compare_models(include=models_list,   # May be empty
                                sort='MCC',        # 'Precision',
                                fold=kFolds,
                                turbo=True,
                                verbose=True,
                                n_select=topN
                               )
```

Let me know if that helps.

**Comment by jtrenkle** [comment]
Aha, I misconstrued how _fit_kwargs_ was meant to be used.  I definitely like your solution because it is so much clearer how each model is modified.  I had similar tweaks I wanted to do for `CatBoost` and now it's crystal clear.  Thanks!

Just plugged that in and it seems to be working like a charm.  Thanks, I appreciate you quick and useful response!
