### ISSUE TITLE
add_metric has problems while executing code the second time throws error "ValueError: id already present in metrics dataframe"

### ISSUE THREAD

**Issue by SAnand47** [pycaret/pycaret#947]
Added "macro-f1" using add_metric function as below
```
add_metric('f1avg', 'macrof1', score_func=get_myscore, greater_is_better = True)
```
The first time the above code was executed, it added the macrof1 and could be checked with get_metrics() function. The output of get_metrics() is shown below

![get_metrics](https://user-images.githubusercontent.com/56620094/102747650-d9ac6a80-431d-11eb-8b0e-364dbe6292d1.JPG)

As seen in last line microf1 is added.

The problem is when add_metric gets executed again as in you run the code again. It throws up an error as below

![add_metrics_Error](https://user-images.githubusercontent.com/56620094/102747370-673b8a80-431d-11eb-8587-59dd1e5d7e5e.PNG)

Was able to get around using try and except but was wondering if any fix available.

**Comment by Yard1** [comment]
`add_metric` should be only ran once per metric. If you cannot change your code so that it's only ran once, put it in a `try...except` block.
