### ISSUE TITLE
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).

### ISSUE THREAD

**Issue by bhaskoro-muthohar** [pycaret/pycaret#948]
When I tried to initialize setup training environment
```py
clf = setup(
    df_pogchampmain,
    train_size=0.85,
    date_features=['age', 'year_graduated'], 
    target='Best Performance', 
    fix_imbalance=True,
    fold_shuffle=True, 
    remove_multicollinearity=True,
    feature_selection=True,
    #feature_selection_method = 'boruta',
    verbose = False
    )
```

It raised 
```py
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
```

![image](https://user-images.githubusercontent.com/35159954/102793383-687fbc80-43dc-11eb-9ffd-9a677322a8bb.png)

No problem about the predictors, LightGBM is running and give nice results. I just want to report this warning message that maybe someone able to give workaround.

**Comment by sahil0094** [comment]
Pls update

**Comment by Yard1** [comment]
It's just a warning that can be ignored. Alternatively you can set those parameters yourself using keyword arguments in `create_model()`.
