### ISSUE TITLE
Question : Why some algorithms doesn't support feature importance plot ?

### ISSUE THREAD

**Issue by Practcdi** [pycaret/pycaret#950]
#### Pycaret 2.2.2
____

Hello Guys ,

1) Why some algorithm like knn,svm etc doesn't support `feature importance` plot?

2) Can you provide the list of all algorithm in Pycaret which doesn't have support for `feature importance` plot?

Thanks,

**Comment by pycaret** [comment]
@Practcdi PyCaret uses `scikit-learn` algorithm attributes to generate feature importance plots. Hence the algorithms that do not support the `feature_importances_` attribute or `coef_` are not supported for feature importance plots. I don't have a complete list of such algorithms but any algorithm that returns weights, in general, will be supported for feature importance.

Hope this helps.
