### ISSUE TITLE
ValueError: Sklearn version error

### ISSUE THREAD

**Issue by HSubbu** [pycaret/pycaret#951]
I am getting following error while using pycaret. I am using pycaret as a beginner. 

ValueError: Sklearn version error

I am using  0.24.0  sklearn and pycaret 2.2.2 .

Please advise

**Comment by minhaajre** [comment]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-94b688d97f7b> in <module>()
----> 1 from pycaret.classification import *
      2 clf1 = setup(df, target = 'TargetValue', session_id=123, log_experiment=True, experiment_name='test')

5 frames
/usr/local/lib/python3.6/dist-packages/pyod/utils/utility.py in _get_sklearn_version()
    444     if int(sklearn_version.split(".")[1]) < 19 or int(
    445             sklearn_version.split(".")[1]) > 23:
--> 446         raise ValueError("Sklearn version error")
    447 
    448     return int(sklearn_version.split(".")[1])

**Comment by bhaskoro-muthohar** [comment]
Same experuence. When trying to import pycaret
```py
from pycaret.classification import *
```

**Comment by Yard1** [comment]
We are aware and will release a fix very soon.

**Comment by bhaskoro-muthohar** [comment]
For meanwhile the workaround is using sklearn version 0.23.2
```py
pip install -U scikit-learn==0.23.2
```

**Comment by dmangonakis** [comment]
pycaret 2.2.1 doesn't work either ...

**Comment by pycaret** [comment]
# The fix has been released for this. pycaret==2.2.3

**Comment by raultomasmora** [comment]
I was getting this error using pycaret==2.2.1 and streamlit==0.71.0 versions.
AttributeError: 'Simple_Imputer' object has no attribute 'fill_value_categorical'.

I fixed the problem by forcing scikit-learn version==0.23.2
