### ISSUE TITLE
PyCaret in Azure Databricks issue

### ISSUE THREAD

**Issue by augustomolke** [pycaret/pycaret#952]
when running the create_model command in Azure data bricks:

setup1 = setup(data, normalize = True, session_id = 123, silent=True, html=False)
rf= create_model(estimator = 'rf', verbose=False)

It takes a very long time to run the cell and does not converge.
any idea why is it happening or is there a fix?
Thanks in advance

**Comment by pycaret** [comment]
@augustomolke How big is the dataset?
