### ISSUE TITLE
check_metric reports same value for MSE and RMSE for a regression use case

### ISSUE THREAD

**Issue by pahire** [pycaret/pycaret#953]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pahire** [comment]
Sample code and results.
unseen_data_mse = check_metric(unseen_predictions['fieldA'], unseen_predictions.Label, 'MSE')
print(unseen_data_mse)
-------------
79959.3149
-------------

unseen_data_rmse = check_metric(unseen_predictions['fieldA'], unseen_predictions.Label, 'RMSE')
print(unseen_data_rmse)
--------------
79959.3149
-------------

MSE values seems correct, while the RMSe value is not performing the square root.

**Comment by Yard1** [comment]
Is it possible to share the dataset with us?

**Comment by pahire** [comment]
No, the dataset is confidential.

**Comment by pahire** [comment]
I see proper values for RMSE and MSE in compare_models, tune_model and ensemble_model calls. RMSE is the square root of MSE. The value of MSE is of a similar order of magnitude as seen above.

**Comment by Yard1** [comment]
Would it be possible for you to check if this issue can be reproduced on a public dataset (like the ones provided by `pycaret.datasets`)? Thanks.

**Comment by pahire** [comment]
I have seen it before. Would this link help ? In cells 52, 53 I encountered the same problem. The dataset and code is available there.

https://www.kaggle.com/paviah/credit-score-prediction-light-gbm-pycaret

**Comment by pahire** [comment]
class RMSEMetricContainer(RegressionMetricContainer):
    def __init__(self, globals_dict: dict) -> None:

        super().__init__(
            id="rmse",
            name="RMSE",
            score_func=metrics.mean_squared_error,
            greater_is_better=False,
            args={"squared": False},
            scorer="neg_root_mean_squared_error",
        )
Isn't the score_func wrong ?

**Comment by tezansahu** [comment]
Yeah, I think it should be modified to `score_func=np.sqrt(metrics.mean_squared_error)`

**Comment by tezansahu** [comment]
I'll try to submit a PR with the correction.
