### ISSUE TITLE
compare_models() returns empty list in Rstudio

### ISSUE THREAD

**Issue by Cytotoxicity** [pycaret/pycaret#954]
Hello, I'm using pycaret with reticulate package in Rstudio 1.3 version.
To try pycaret in this, I used the sample code.

```
from pycaret.classification import * 
from pycaret.datasets import get_data

diabetes = get_data('diabetes')
clf1 = setup(data = diabetes, target = 'Class variable')

best=compare_models()
type(best)
len(best)
```

But it returned
```
>>> type(best)
<class 'list'>

>>> len(best)
0
```

In IDLE, pycaret returned 
`>>> type(best)
<class 'catboost.core.CatBoostClassifier'>`

Why compare_models() returns empty list in only Rstudio? Is it the problem with Rstudio? If so, will this be solved in Rstudio 1.4 Release which supports python much more than now? Or is it the problem with reticulate and pycaret?

**Comment by ngupta23** [comment]
Since it is working standalone in Python in various IDEs, I think this is likely an issue with reticulate. Can you file a Issue in the [right repo](https://github.com/rstudio/reticulate/issues) and link this issue to that one?

**Comment by Cytotoxicity** [comment]
Thanks for reply, I will do that soon.

**Comment by ngupta23** [comment]
@Cytotoxicity we will close this. Feel free to reopen or submit another issue if there are other issues with `pycaret`.
