### ISSUE TITLE
How to apply custom cv ?

### ISSUE THREAD

**Issue by atwahsz** [pycaret/pycaret#957]
Spouse I want to apply GeneticSelectionCV

How do I pass it as it requires an estimator

**Comment by Yard1** [comment]
Through the `fold` argument of most functions.

**Comment by atwahsz** [comment]
Ok what about group k fold . While groups are available in the dataset as a column

**Comment by pycaret** [comment]
@atwahsz You can pass the column name containing groups in the `fold_groups` parameter when initializing the `setup` function. See below:

![image](https://user-images.githubusercontent.com/58118658/103179680-6d20f680-485c-11eb-9cce-2f183eee7dbe.png)
