### ISSUE TITLE
PyCaret is unable to scale for large datasets

### ISSUE THREAD

**Issue by sid-the-coder** [pycaret/pycaret#96]
I'm facing some issue with the setup() while using this dataset which contains 4357336 rows and 26 columns. 

Here's the Kaggle link:
https://www.kaggle.com/c/pubg-finish-placement-prediction/data

I tried to run my scripts on Google Colab using GPU/TPU but I am facing similar issues. It crashes after confirming the feature types. 

Is this supposed to happen for large datasets. If yes, how do I rectify it?

P.S. Thank you for this awesome library! I love using it!

**Comment by pycaret** [comment]
@sid-the-coder 

Hi Sid. This is due to a reported bug. Will be fixed in next version.

Thanks for reporting.

**Comment by DaGuT** [comment]
after https://github.com/pycaret/pycaret/pull/103 this pull request is merged you will be able to install fixed version of pycaret via `pip install https://github.com/pycaret/pycaret/archive/dev-1.0.1.zip`

That way you will not have to wait for stable release or do changes manually

**Comment by xhlubuntu** [comment]
i'm really appreicate it if this package supprot spark or dask distribution.

**Comment by dani-lbnl** [comment]
we were able to use pycaret with dask - needed to hack cufflinks/auth.py and pycaret/classification.py
