### ISSUE TITLE
CountVectorizer / TfidfVectorizer with pycart

### ISSUE THREAD

**Issue by PiotrAntoniak** [pycaret/pycaret#960]
Hi, Great tool! Still can't wrap my head around how good it is.

However, I have run into a slight problem. I have dataset with loads of urls and want to use them in the classification problem. The CountVectorizer /TfidfVectorizer seems to be the way to go. However, I couldn't figure out how to make them work in the setup - so I tried to just feed the transformed data into the pycart. HOWEVER, this gives me:
AttributeError: columns not found.

Any workarounds/tips?

Thanks in the advance.

Also, sorry if I'm breaking some unwritten  laws, this is the first time I use "issues".

**Comment by Yard1** [comment]
Can you post the code you are using? With both the data transformation and how you call `setup()`.

**Comment by PiotrAntoniak** [comment]
![image](https://user-images.githubusercontent.com/67911055/103095946-3fd50e00-45fa-11eb-8072-843c9c5465b8.png)
and the error:
![image](https://user-images.githubusercontent.com/67911055/103095806-d228e200-45f9-11eb-85ed-81cbe5ca0dd8.png)
I got exactly the same using TfidfVectorizer.

**Comment by Yard1** [comment]
I am afraid that PyCaret doesn't support sparse matrices just yet. Only Pandas dataframes are supported, which may not quite work with how much data you have. Sorry.

**Comment by PiotrAntoniak** [comment]
;/
Tried to use pandas and scale down the number of the features but the setup would still take ages.
However, by doing this:
fake = pd.DataFrame(data = {"col1":[1,2,3,4,5,6,7], "col2":[2,2,3,4,5,6,7], "target":[1,0,1,0,1,0,0]})
exp1 = setup(fake,target = "target", 
             fold = 5, train_size = 0.7, session_id = 2137, fix_imbalance = True, use_gpu = True)
and then supplying the actual data:
set_config('X_train', X_train)
set_config('y_train', y_train)
set_config('X_test', X_test)
set_config('y_test', y_test)

It worked a lot faster.

**Comment by pycaret** [comment]
@PiotrAntoniak This is a good trick.

**Comment by norbert-liki** [comment]
With Pycaret 2.3 you can add a custom pipeline to preprocess your input data.
I got it working by doing this:

![image](https://user-images.githubusercontent.com/47354641/111062174-a5bd8d00-84a7-11eb-80f0-f121697dfc9f.png)

What I have noted is that Pycaret does not report the dataset shapes correctly upon returning the setup() step, however the final trained pipeline involves the custom pipeline.

**Comment by Yard1** [comment]
Yes, unfortunately we cannot predict how the custom transformed data will look like, but this is indeed the correct usage for the `custom_pipeline` argument.
