### ISSUE TITLE
Dynamic Classifier Selection Ensembles

### ISSUE THREAD

**Issue by developpeur-windev-php-python** [pycaret/pycaret#961]
Is it possible to use or to implemnt DESlib with pycaret ?

https://github.com/scikit-learn-contrib/DESlib

**Comment by Yard1** [comment]
It is one of the things we would like to implement eventually, but it is not coming soon. In the meantime, you can use PyCaret to create models and preprocess data and pass it to other sklearn API objects with `get_config() `.
