### ISSUE TITLE
ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by satyam2829** [pycaret/pycaret#964]
I am getting this error while installing pycaret. Not sure how to resolve it.

Collecting pycaret
  Using cached pycaret-2.2.3-py3-none-any.whl (249 kB)
  Using cached pycaret-2.2.2-py3-none-any.whl (249 kB)
  Using cached pycaret-2.2.1-py3-none-any.whl (248 kB)
  Using cached pycaret-2.2-py3-none-any.whl (248 kB)
  Using cached pycaret-2.1.2-py3-none-any.whl (252 kB)
  Using cached pycaret-2.1.1-py3-none-any.whl (251 kB)
  Using cached pycaret-2.1-py3-none-any.whl (251 kB)
  Using cached pycaret-2.0-py3-none-any.whl (255 kB)
Collecting cufflinks>=0.17.0
  Using cached cufflinks-0.17.3.tar.gz (81 kB)
Requirement already satisfied: setuptools>=34.4.1 in c:\users\satya\anaconda3\envs\pycaret\lib\site-packages (from cufflinks>=0.17.0->pycaret) (51.0.0.post20201207)
Collecting colorlover>=0.2.1
  Using cached colorlover-0.3.0-py3-none-any.whl (8.9 kB)
Collecting datefinder>=0.7.0
  Using cached datefinder-0.7.1-py2.py3-none-any.whl (10 kB)
Collecting DateTime>=4.3
  Using cached DateTime-4.3-py2.py3-none-any.whl (60 kB)
Collecting IPython
  Using cached ipython-7.19.0-py3-none-any.whl (784 kB)
Collecting ipywidgets
  Downloading ipywidgets-7.6.2-py2.py3-none-any.whl (121 kB)
     |████████████████████████████████| 121 kB 2.2 MB/s
Collecting ipykernel>=4.5.1
  Using cached ipykernel-5.4.2-py3-none-any.whl (119 kB)
Collecting jedi>=0.10
  Using cached jedi-0.18.0-py2.py3-none-any.whl (1.4 MB)
Collecting jupyterlab-widgets>=1.0.0
  Using cached jupyterlab_widgets-1.0.0-py3-none-any.whl (243 kB)
Collecting kmodes>=0.10.1
  Using cached kmodes-0.10.2-py2.py3-none-any.whl (18 kB)
Collecting joblib
  Using cached joblib-1.0.0-py3-none-any.whl (302 kB)
Collecting lightgbm>=2.3.1
  Using cached lightgbm-3.1.1-py2.py3-none-win_amd64.whl (754 kB)
Requirement already satisfied: wheel in c:\users\satya\anaconda3\envs\pycaret\lib\site-packages (from lightgbm>=2.3.1->pycaret) (0.36.2)
Collecting nbformat>=4.2.0
  Using cached nbformat-5.0.8-py3-none-any.whl (172 kB)
Collecting jsonschema!=2.5.0,>=2.4
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting attrs>=17.4.0
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting numpy>=1.17
  Using cached numpy-1.19.4-cp39-cp39-win_amd64.whl (13.0 MB)
Collecting pandas
  Downloading pandas-1.2.0-cp39-cp39-win_amd64.whl (9.3 MB)
     |████████████████████████████████| 9.3 MB 3.2 MB/s
Collecting pandas-profiling>=2.3.0
  Using cached pandas_profiling-2.9.0-py2.py3-none-any.whl (258 kB)
Collecting visions[type_image_path]==0.5.0
  Using cached visions-0.5.0-py3-none-any.whl (64 kB)
Collecting confuse>=1.0.0
  Using cached confuse-1.4.0-py2.py3-none-any.whl (21 kB)
Collecting htmlmin>=0.1.12
  Using cached htmlmin-0.1.12.tar.gz (19 kB)
Collecting jinja2>=2.11.1
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1.tar.gz (19 kB)
Collecting matplotlib
  Using cached matplotlib-3.3.3-cp39-cp39-win_amd64.whl (8.5 MB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.1-cp39-cp39-win_amd64.whl (51 kB)
Collecting missingno>=0.4.2
  Using cached missingno-0.4.2-py3-none-any.whl (9.7 kB)
Collecting networkx>=2.4
  Using cached networkx-2.5-py3-none-any.whl (1.6 MB)
Collecting decorator
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting parso<0.9.0,>=0.8.0
  Using cached parso-0.8.1-py2.py3-none-any.whl (93 kB)
Collecting phik>=0.9.10
  Using cached phik-0.10.0-py3-none-any.whl (599 kB)
Collecting numba>=0.38.1
  Using cached numba-0.51.2.tar.gz (2.1 MB)
Collecting llvmlite<0.35,>=0.34.0.dev0
  Using cached llvmlite-0.34.0.tar.gz (107 kB)
Collecting Pillow
  Using cached Pillow-8.0.1-cp39-cp39-win_amd64.whl (2.1 MB)
Collecting plotly>=4.4.1
  Using cached plotly-4.14.1-py2.py3-none-any.whl (13.2 MB)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Using cached prompt_toolkit-3.0.8-py3-none-any.whl (355 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting pyrsistent>=0.14.0
  Using cached pyrsistent-0.17.3.tar.gz (106 kB)
Collecting python-dateutil>=2.4.2
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz
  Using cached pytz-2020.5-py2.py3-none-any.whl (510 kB)
Collecting regex>=2017.02.08
  Using cached regex-2020.11.13-cp39-cp39-win_amd64.whl (270 kB)
Collecting requests>=2.23.0
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\satya\anaconda3\envs\pycaret\lib\site-packages (from requests>=2.23.0->pandas-profiling>=2.3.0->pycaret) (2020.12.5)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting retrying>=1.3.3
  Using cached retrying-1.3.3.tar.gz (10 kB)
Collecting scikit-learn>=0.23.2
  Using cached scikit_learn-0.24.0-cp39-cp39-win_amd64.whl (6.9 MB)
Collecting scipy>=0.13.3
  Using cached scipy-1.5.4-cp39-cp39-win_amd64.whl (31.4 MB)
Collecting seaborn
  Using cached seaborn-0.11.1-py3-none-any.whl (285 kB)
Collecting six>=1.9.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting tangled-up-in-unicode>=0.0.6
  Using cached tangled_up_in_unicode-0.0.6-py3-none-any.whl (3.1 MB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Collecting tornado>=4.2
  Using cached tornado-6.1-cp39-cp39-win_amd64.whl (422 kB)
Collecting tqdm>=4.43.0
  Using cached tqdm-4.55.0-py2.py3-none-any.whl (68 kB)
Collecting traitlets>=4.2
  Using cached traitlets-5.0.5-py3-none-any.whl (100 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
Collecting widgetsnbextension~=3.5.0
  Using cached widgetsnbextension-3.5.1-py2.py3-none-any.whl (2.2 MB)
Collecting notebook>=4.4.1
  Using cached notebook-6.1.6-py3-none-any.whl (9.5 MB)
Collecting jupyter-client
  Using cached jupyter_client-6.1.7-py3-none-any.whl (108 kB)
Collecting jupyter-core
  Using cached jupyter_core-4.7.0-py3-none-any.whl (82 kB)
Collecting pywin32>=1.0
  Using cached pywin32-300-cp39-cp39-win_amd64.whl (9.2 MB)
Collecting pyzmq>=17
  Using cached pyzmq-20.0.0-cp39-cp39-win_amd64.whl (699 kB)
Collecting terminado>=0.8.3
  Using cached terminado-0.9.1-py3-none-any.whl (13 kB)
Collecting pywinpty>=0.5
  Using cached pywinpty-0.5.7.tar.gz (49 kB)
Collecting xgboost>=1.1.0
  Using cached xgboost-1.3.1-py3-none-win_amd64.whl (95.2 MB)
Collecting yellowbrick>=1.0.1
  Using cached yellowbrick-1.2-py3-none-any.whl (269 kB)
Collecting argon2-cffi
  Using cached argon2_cffi-20.1.0-cp39-cp39-win_amd64.whl (42 kB)
Collecting cffi>=1.0.0
  Using cached cffi-1.14.4-cp39-cp39-win_amd64.whl (179 kB)
Collecting backcall
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting catboost
  Using cached catboost-0.1.1.2-py3-none-win_amd64.whl (2.3 MB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting gensim
  Using cached gensim-3.8.3.tar.gz (23.4 MB)
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\satya\anaconda3\envs\pycaret\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\satya\\AppData\\Local\\Temp\\pip-install-fl9lenun\\gensim_de88da29d8294cb8827f88bb459bc020\\setup.py'"'"'; __file__='"'"'C:\\Users\\satya\\AppData\\Local\\Temp\\pip-install-fl9lenun\\gensim_de88da29d8294cb8827f88bb459bc020\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\satya\AppData\Local\Temp\pip-pip-egg-info-as_1e1kx'
         cwd: C:\Users\satya\AppData\Local\Temp\pip-install-fl9lenun\gensim_de88da29d8294cb8827f88bb459bc020\
    Complete output (42 lines):
    running egg_info
    creating C:\Users\satya\AppData\Local\Temp\pip-pip-egg-info-as_1e1kx\gensim.egg-info
    writing C:\Users\satya\AppData\Local\Temp\pip-pip-egg-info-as_1e1kx\gensim.egg-info\PKG-INFO
    writing dependency_links to C:\Users\satya\AppData\Local\Temp\pip-pip-egg-info-as_1e1kx\gensim.egg-info\dependency_links.txt
    writing requirements to C:\Users\satya\AppData\Local\Temp\pip-pip-egg-info-as_1e1kx\gensim.egg-info\requires.txt
    writing top-level names to C:\Users\satya\AppData\Local\Temp\pip-pip-egg-info-as_1e1kx\gensim.egg-info\top_level.txt
    writing manifest file 'C:\Users\satya\AppData\Local\Temp\pip-pip-egg-info-as_1e1kx\gensim.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\satya\AppData\Local\Temp\pip-install-fl9lenun\gensim_de88da29d8294cb8827f88bb459bc020\setup.py", line 367, in <module>
        setup(
      File "C:\Users\satya\anaconda3\envs\pycaret\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\satya\anaconda3\envs\pycaret\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\satya\anaconda3\envs\pycaret\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\satya\anaconda3\envs\pycaret\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\satya\anaconda3\envs\pycaret\lib\site-packages\setuptools\command\egg_info.py", line 298, in run
        self.find_sources()
      File "C:\Users\satya\anaconda3\envs\pycaret\lib\site-packages\setuptools\command\egg_info.py", line 305, in find_sources
        mm.run()
      File "C:\Users\satya\anaconda3\envs\pycaret\lib\site-packages\setuptools\command\egg_info.py", line 536, in run
        self.add_defaults()
      File "C:\Users\satya\anaconda3\envs\pycaret\lib\site-packages\setuptools\command\egg_info.py", line 572, in add_defaults
        sdist.add_defaults(self)
      File "C:\Users\satya\anaconda3\envs\pycaret\lib\distutils\command\sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "C:\Users\satya\anaconda3\envs\pycaret\lib\distutils\command\sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "C:\Users\satya\anaconda3\envs\pycaret\lib\distutils\cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "C:\Users\satya\anaconda3\envs\pycaret\lib\distutils\cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "C:\Users\satya\AppData\Local\Temp\pip-install-fl9lenun\gensim_de88da29d8294cb8827f88bb459bc020\setup.py", line 113, in finalize_options
        import numpy
      File "c:\users\satya\appdata\local\temp\pip-install-fl9lenun\gensim_de88da29d8294cb8827f88bb459bc020\.eggs\numpy-1.19.4-py3.9-win-amd64.egg\numpy\__init__.py", line 305, in <module>
        _win_os_check()
      File "c:\users\satya\appdata\local\temp\pip-install-fl9lenun\gensim_de88da29d8294cb8827f88bb459bc020\.eggs\numpy-1.19.4-py3.9-win-amd64.egg\numpy\__init__.py", line 302, in _win_os_check
        raise RuntimeError(msg.format(__file__)) from None
    RuntimeError: The current Numpy installation ('c:\\users\\satya\\appdata\\local\\temp\\pip-install-fl9lenun\\gensim_de88da29d8294cb8827f88bb459bc020\\.eggs\\numpy-1.19.4-py3.9-win-amd64.egg\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information:
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by pycaret** [comment]
@satyam2829 Can you please give more details about what environment you are using and are you using any virtual environment like conda or virtualenv?

**Comment by satyam2829** [comment]
Am following the same steps as specified in pycaret website like creating the environment, activating the environment and then installing pycaret.

Am using conda environment.

**Comment by rajpratyush** [comment]
@pycaret I am trying if the same error gets reproduced in my system(windows). @satyam2829 can y6ou tell me the version of anaconda you are using? and are you trying it on Linux, mac or windows

**Comment by rajpratyush** [comment]
Hi @pycaret I tried to install the same way as mentioned in the website I didn't got any error as mentioned by @satyam2829. I used the same process in the conda environment in windows 10. My Anaconda navigator version is 1.9.7 and i am also having Nvididia GeForce GTX 1050
![Screenshot (650)](https://user-images.githubusercontent.com/53184883/105570143-568f9180-5d6d-11eb-841b-8849959f3376.png)
 I am attaching the screenshots as well for your reference. 
![Screenshot (642)](https://user-images.githubusercontent.com/53184883/105570115-36f86900-5d6d-11eb-834a-3f8f75880d06.png)
![Screenshot (643)](https://user-images.githubusercontent.com/53184883/105570118-3c55b380-5d6d-11eb-9604-f9992bc990ed.png)
![Screenshot (644)](https://user-images.githubusercontent.com/53184883/105570123-411a6780-5d6d-11eb-9abc-d869aa87bc4b.png)
![Screenshot (645)](https://user-images.githubusercontent.com/53184883/105570128-45468500-5d6d-11eb-9160-156ae79b8ea8.png)
![Screenshot (646)](https://user-images.githubusercontent.com/53184883/105570133-4aa3cf80-5d6d-11eb-9488-faaa76572306.png)
![Screenshot (647)](https://user-images.githubusercontent.com/53184883/105570139-4ecfed00-5d6d-11eb-92ea-f507350de072.png)
![Screenshot (648)](https://user-images.githubusercontent.com/53184883/105570142-52637400-5d6d-11eb-9663-85d42e104429.png)
