### ISSUE TITLE
Range of the Score Column in the predict_model output 

### ISSUE THREAD

**Issue by muriloafonso** [pycaret/pycaret#968]
The Score column (for Catboost Classifier) in the predict_model output is returning a value between 0.5 and 1 for both classes, instead of 0 to 1. How can I fix this?

**Comment by Yard1** [comment]
The probability in the score column is for the predicted class, and not for the positive class (like in sklearn). An option to get the sklearn-like scores will be added in a future update.

**Comment by muriloafonso** [comment]
Thanks for the answer
