### ISSUE TITLE
Undersampling majority class

### ISSUE THREAD

**Issue by sahil0094** [pycaret/pycaret#969]
Is there a way to undersample majority class while cross validation in pycaret?

**Comment by bhaskoro-muthohar** [comment]
Maybe you can try to pass `fix_imbalance = True, fix_imbalance_method = TomekLinks ` on your setup parameter in order to use undersample with TomekLinks method

**Comment by vtoliveira** [comment]
To be more specific, you can do:

```python

from imblearn.under_sampling import RandomUnderSampler

ru = RandomUnderSampler(random_state=default_setup['session_id'])
clf = setup(
        **default_setup,
        fix_imbalance=True,
        fix_imbalance_method=ru
     )

```

Where `default_setup` is a dictionary containing the remaining of setup parameters.
Don't forget to install imblearn:

```pip install imbalanced-learn```

**Comment by bhaskoro-muthohar** [comment]
When you installed `pip install pycaret[full]` you won't need to install `imbalanced-learn` manually, because the full version takes care of it already

**Comment by pycaret** [comment]
That's correct. With `pycaret[full]` you do not need to install `imbalanced-learn` separately. :)
