### ISSUE TITLE
[ 📊 Enhancement ] : How to choose plotly or dash backend for model evaluation plots ?

### ISSUE THREAD

**Issue by VinayChaudhari1996** [pycaret/pycaret#970]
Hello Guys , 

I'm thinking about how we can choose model evaluation plots backend like **plotly/dash** for more interactive charts than traditional plots. 

Is is possible to add this feature like to choose **plots backend** in next version ? 

Thanks ,

**Comment by batmanscode** [comment]
I think most of the plots are already done with plotly 🤔

**Comment by VinayChaudhari1996** [comment]
> I think most of the plots are already done with plotly 🤔

But they all are static (not very interactive)

**Comment by pycaret** [comment]
@VinayChaudhari1996 Would you like to work on this functionality?

**Comment by VinayChaudhari1996** [comment]
Yes for sure, I need steps and some guidance to start with.

**Comment by Yard1** [comment]
@VinayChaudhari1996 @batmanscode has added streamlit as a backend recently, perhaps he could help? If not I can do it, though I am occupied at this moment.

**Comment by batmanscode** [comment]
> @VinayChaudhari1996 @batmanscode has added streamlit as a backend recently, perhaps they could help? If not I can do it, though I am occupied at this moment.

Yes I can. My plotting skills are basic but what better way to learn!

**Comment by VinayChaudhari1996** [comment]
Hello Guys ,

Here is something interesting.
PACKAGE : https://github.com/oegedijk/explainerdashboard

DEMO : http://titanicexplainer.herokuapp.com/
Can we integrate it in pycaret ?

Thanks,
