### ISSUE TITLE
finalize_model with unseen_data too?

### ISSUE THREAD

**Issue by dgg32** [pycaret/pycaret#975]
**Is your feature request related to a problem? Please describe.**

According to the [tutorial ](https://github.com/pycaret/pycaret/blob/master/tutorials/Binary%20Classification%20Tutorial%20Level%20Beginner%20-%20%20CLF101.ipynb), the finalize_model method trains on the 95% fraction of my training data. And then we predict_model(final_lightgbm, data=data_unseen) on the last 5% to get the final metrics of the model. Question: is it possible to give finalize_model an option to include this 5% unseen_data too to make a 100% training model? This will make sense for Kaggle, where users will like to train the model with all the seen and unseen data before they deploy it to the test data.

**Describe the solution you'd like**

Add an option in finalize_model to include the unseen_data for one final fit.

**Describe alternatives you've considered**

Alternative, the user can get to make two sessions, one with 5% data_unseen and one without. Find the best tuned model with the first, and finalize the best tuned model with the second. But this workflow is complicated and confusing.

**Additional context**

It is possible to go ahead with the model without the 5% unseen data. But for time series Kaggle competition, one final fit of the model on the latest data points is imperative. I think this feature is highly desired.

**Comment by Yard1** [comment]
`finalize_model` trains on all data. This must be a mistake in the tutorial.

**Comment by pycaret** [comment]
@dgg32 Thanks for reporting. I have read the tutorial and I can't figure out what made you think that the `finalize_model` only trains on the training set. In fact, the purpose of the `finalize_model` function is to fit the model on the entire data.

![image](https://user-images.githubusercontent.com/58118658/104073588-17ddd100-51dc-11eb-9a1c-e9cfc7a1abd5.png)

**Comment by dgg32** [comment]
@pycaret Hi thank you for replying. 

Perhaps I misunderstood the setting in the tutorial. I can think of two ways of understanding the tutorial. But regardless which, it is clear to me that the "12.0 Finalize Model for Deployment" happens before the "13.0 Predict on unseen data" (the 5% data). This implies that the final model should have not included the 5% data because otherwise it is cheating. 

My understanding:

All 100% of the data is visible to the user. And the user split the data in 1. Training set for K-fold and 2. Unseen

This understanding makes sense because the unseen data prediction gives us a good final test of the model. But I want to fit my model on those 5% data after 13. too before I deploy it to the wild, i.e. to the real unseen data that are not even included in our tutorial data. 


Alternative understanding, the kaggle-competition way:

95% is for the user to see and 5% is only visible to the organizer. 

The finalize_model uses all the 95% of the data in 12.0. And in 13.0, the user predicts the outcome for the 5% and then the tutorial plays the role of the organizer to score the 5% prediction. If this were the setting, then I think it misses the final testing step like the one I mentioned above.
 
So, could you please help me to understand, which design does the tutorial have in mind please? And in step 7.0 "Comparing All Models", in the function "compare_models", there is no mention of the variable "exp_clf101" setup in 6.0. Does the name "exp_clf101" matter? Thank you!

**Comment by Yard1** [comment]
The 5% has been held back specifically in the tutorial to act as unseen data for purposes of demonstration. The dataset has been divided into 95% to act as "known" data and 5% to act as "unknown" data before it was passed onto PyCaret. PyCaret does not do any data splitting aside from separating the data it receives into train and test sets. `finalize_model()` fits the model on all data passed to PyCaret. Hope that clears it up.

**Comment by dgg32** [comment]
> The 5% has been held back specifically in the tutorial to act as unseen data for purposes of demonstration. The dataset has been divided into 95% to act as "known" data and 5% to act as "unknown" data before it was passed onto PyCaret only for purposes of tutorial demonstration. PyCaret does not do any data splitting aside from separating the data it receives into train and test sets. `finalize_model()` fits the model on all data passed to PyCaret. Hope that clears it up.

@Yard1  So you mean in an everyday scenario, there is no need for me to create that 5% data? Thank you!

**Comment by Yard1** [comment]
That's correct. It was just for the purposes of the tutorial.
