### ISSUE TITLE
Q: Reason plot for unseen data in streamlit apps

### ISSUE THREAD

**Issue by Lion-Mod** [pycaret/pycaret#979]
I'm looking to build a streamlit app that once build you can predict a value which will be displayed along with the shap/reason plot.

I've been trying with `interpret_plot`. I'm thinking if I can't get this working to go after the shap values way using `get_config("X")` to get the data for the `explainer.shap_values`.

Is there a known way of handling this?

**Comment by pycaret** [comment]
This is not yet implemented @Lion-Mod.

**Comment by Lion-Mod** [comment]
Ok. I've had some progress since. Ideally I have the unseen data but need to acquire it preprocessed using the same steps from the pycaret setup.

I understand their is a pipeline used but I'm struggling to understand the underlying code to apply this to my unseen data (untransformed and no target column).

Is there a way I can apply the pipeline preprocessing as described?

**Comment by Lion-Mod** [comment]
Got it!

I've exported (using `joblib.dump`) the `prep_pipe`. Obtained via get_config(`prep_pipe`)

Loading this in I've used prep.transform(prediction_df)

Where prep is the `prep_pipe`

Only problem was any columns that were ignored I had to add back in prior to the transform step.
