### ISSUE TITLE
Loading model w/o PyCaret?

### ISSUE THREAD

**Issue by dmangonakis** [pycaret/pycaret#985]
Hi,

I've built a model with PyCaret and saved it into s3.
Now, I want to create an application w/o importing pycaret.

Downloading the model is easy with `boto3` but loading it with `joblib.load(...)` leads back to:

`ModuleNotFoundError: No module named 'pycaret.internal'`

It seems like joblib.load calls numpy_pickle, then runpy and finally pickle where find_class does `__import__(module, level=0)`

Any ideas for a workaround?

Thanks!

**Comment by Yard1** [comment]
By default, the entire pipeline is saved, which requires PyCaret. You can use the `model_only=True` argument in `save_model()` to save just the model.

**Comment by pycaret** [comment]
@dmangonakis You can also directly use `joblib` after the model is returned from the `create_model`, if you just need to access sklearn estimator. Hope this helps!
