### ISSUE TITLE
conda install -c conda-forge pycaret - fails

### ISSUE THREAD

**Issue by subrockmann** [pycaret/pycaret#991]
Problem:
I am trying to install pycaret through Anaconda on Python 3.7.9 and all my tried installs failed due to unsolvable dependencies.

`(tensorflow) C:\Users\Susanne>conda install -c conda-forge pycaret
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

`
I have taken a look into the hard dependencies for pycaret and to me it looks like the hard dependency scipy==1.5.4 is the limiting factor. The latest available version for scipy on Anaconda is 1.5.2. Therefore it is impossible to run this in Anaconda without using pip. I really try to avoid mixing pip and Anaconda in my environments.

**Comment by Yard1** [comment]
I believe it could be changed to `scipy<=1.5.4` without issues. I have just done so in commit `ad629e7a8ea3fb36023e04529fc6ac15798ab25c`.

**Comment by subrockmann** [comment]
@Yard1: Unfortunately the version on Anaconda has not been updated yet. Therefore I am unable to check the results.

**Comment by Yard1** [comment]
Yes, you will need to wait, I am afraid. Shouldn't take long though

**Comment by rajpratyush** [comment]
The error is still there 
This is the error message I got:

 C:\Users\rajpr>conda install -c conda-forge pycaret
Collecting package metadata (repodata.json): done
Solving environment: /
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/win-64::anaconda-client==1.7.2=py37_0
  - defaults/win-64::anaconda==custom=py37_1
  - defaults/win-64::anaconda-navigator==1.9.7=py37_0
  - defaults/noarch::anaconda-project==0.8.4=py_0
  - conda-forge/noarch::arviz==0.8.3=py_0
  - defaults/win-64::bokeh==2.0.2=py37_0
  - conda-forge/win-64::conda==4.9.2=py37h03978a9_0
  - defaults/win-64::conda-build==3.17.8=py37_0
  - defaults/noarch::dask==2.17.2=py_0
  - defaults/win-64::distributed==2.17.0=py37_0
  - conda-forge/win-64::fbprophet==0.6=py37h6538335_0
  - conda-forge/noarch::gitdb==4.0.5=py_0
  - conda-forge/noarch::gitpython==3.1.12=pyhd8ed1ab_0
  - defaults/win-64::ipykernel==5.1.4=py37h39e3cac_0
  - defaults/noarch::ipywidgets==7.5.1=py_0
  - defaults/win-64::jupyter==1.0.0=py37_7
  - defaults/noarch::jupyterlab==1.2.6=pyhf63ae98_0
  - defaults/noarch::jupyterlab_server==1.1.4=py_0
  - defaults/noarch::jupyter_client==6.1.3=py_0
  - defaults/noarch::jupyter_console==6.1.0=py_0
  - defaults/win-64::matplotlib==3.1.3=py37_0
  - defaults/win-64::matplotlib-base==3.1.3=py37h64f37c6_0
  - defaults/win-64::notebook==6.0.3=py37_0
  - defaults/noarch::numpydoc==0.9.2=py_0
  - conda-forge/noarch::pydeck==0.3.1=pyh9f0ad1d_0
  - conda-forge/win-64::pystan==2.19.1.1=py37h12199cf_1
  - defaults/noarch::qtconsole==4.7.4=py_0
  - defaults/win-64::scikit-image==0.16.2=py37h47e9c7a_0
  - defaults/noarch::seaborn==0.10.1=py_0
  - defaults/noarch::sphinx==3.0.4=py_0
  - defaults/win-64::spyder==4.1.3=py37_0
  - defaults/win-64::spyder-kernels==1.9.1=py37_0
  - conda-forge/noarch::streamlit==0.75.0=pyhd8ed1ab_0
  - defaults/win-64::terminado==0.8.3=py37_0
  - defaults/win-64::widgetsnbextension==3.5.1=py37_0
  - defaults/win-64::_anaconda_depends==2020.02=py37_0
  - defaults/win-64::_ipyw_jlab_nb_ext_conf==0.1.0=py37_0
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining @/win-64::__win==0=0:  20%|██████████▍                                         | 1/5 [00:01<00:04,  1.22s/it]/Determining conflicts:   0%|                                                                     | 0/5 [00:00<?, ?it/s]/failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
