### ISSUE TITLE
Can't get the hyperparameter of CatBoost Regressor

### ISSUE THREAD

**Issue by linchen111** [pycaret/pycaret#993]
When I tuned the CatBoost Regressor model, I want to check the hyperparameter,
but when I use 'print(model)'
all I can get is this :<catboost.core.CatBoostRegressor object at 0x1a2ea2f6d0>

**Comment by Yard1** [comment]
That is a CatBoost issue. Please try `print(model.get_params())`.

**Comment by linchen111** [comment]
Thanks! It worked!

> That is a CatBoost issue. Please try `print(model.get_params())`.
