### ISSUE TITLE
Program fails with msg y contains previously unseen labels: '3'

### ISSUE THREAD

**Issue by muraris** [pycaret/pycaret#994]
While attempting to learn and use pycaret on a dataset for regression, observed that for it errors with error..
"item_name1 with msg y contains previously unseen labels: '32'"
Appreciate any help to fix this.

[pycaret_issue_testing.zip](https://github.com/pycaret/pycaret/files/5799904/pycaret_issue_testing.zip)

**Comment by Yard1** [comment]
I have ran the code you've posted without any issues. Please try reinstalling PyCaret in a new virtual environment.

**Comment by muraris** [comment]
Thanks for the sharing your observation.
I was testing it just using Python 3.x and Jupyter.

**Comment by pycaret** [comment]
@muraris I can also run the code without any issue. As @Yard1 recommended, please try installing pycaret in new virtual environment. You can follow the instructions here:

https://pycaret.readthedocs.io/en/latest/installation.html

Feel free to open another issue if it still doesn't work.
