### ISSUE TITLE
Handling SHAP values and one hot encodings

### ISSUE THREAD

**Issue by Lion-Mod** [pycaret/pycaret#995]
I've been using interpret plot and exploring the use of SHAP values. I've been looking at the SHAP library and looks like whenever OHE is used it could affect the shap plots given the column(s) splitting into multiple and being filled with 0s.

[Understanding1](https://github.com/slundberg/shap/issues/1342)
[Understanding2](https://github.com/slundberg/shap/issues/397)

I can't see a way that pycaret handles this?

**Comment by pycaret** [comment]
@Lion-Mod PyCaret currently just treats all one-hod-enoded columns separately.
