### ISSUE TITLE
PyCaret and Google Cloud Functions

### ISSUE THREAD

**Issue by vmady** [pycaret/pycaret#998]
I try to use PyCaret in a Google Cloud Functions but I cannot import the classification modules (from pycaret.classification import *) because there is a reference to a non writable directory (OSError: [Errno 30] Read-only file system: '/workspace/logs.log') 

Does anybody know a workaround or does that mean that PyCaret is not compliant with Cloud Function yet ?

**Comment by pycaret** [comment]
@vmady This means that your account in GCP does not have access to the workspace directory where logs are written.

@Yard1 This problem also exists in other cloud environments where the user is not an admin and does not have access to files written in cluster workspace. Are you planning to disable system logs by providing a `setup` parameter? What are your thoughts?

**Comment by Yard1** [comment]
@pycaret I am not yet sure on the specific way to do it but I'll figure something out.

**Comment by Yard1** [comment]
Fixed in commit 6db437f27ad5c8ec98a99fe9c78260e8300b486d - if the logger cannot save a file, then it will just carry on with logging disabled
